### ISSUE TITLE
Creating Python Extension Packages

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/PTVS#100]
This issue was started here... https://pytools.codeplex.com/discussions/637161

Couple of questions for PTVS and Visual Studio extensions. 

 Are there any plug-ins to create VSIX projects for Python similar to C#/VB? Example of clicking New Project > Python > Extensibility > VISX Project. If so, how do you get the extension? 

 (Not completely related to PTVS) How do you add new file types and categories to the New File Window. Example clicking File > New > File... I would like to create a new category/file type to create/edit/save on demand instead of creating a solution/project. 

 Any examples will be appreciated. Thx.

**Comment by shaggygi** [comment]
@pminaev Thanks for the response.

 I am able to create an extension with C# pretty easily. File > New > Project > C# Extensibility > VSIX Project > and add the project/item templates. So let's say I added the basic C# project template that included one class file. If you notice, the project has the C# icon (and other language related stuff) and when I right-click > Add New Item > there is only C# related items to add.

 I would like my extension to be able to show the Python icon and only be able to select Python items (similar to the PTVS type projects). Would this type of extension need to be created still using a C# VSIX? Any examples/docs would be helpful.

 In addition, I will review the link for creating the templates to see about adding the New File extension.

 Thanks again.

**Comment by int19h** [comment]
VSIX by itself is language agnostic. If you only have file and/or project templates in it, then you can use any template to get started, it won't really matter.

I would recommend that you take a look at the [PTVS project samples](https://github.com/Microsoft/PTVS-Samples). This sounds exactly like what you're trying to do, so you can just take that solution and replace the project templates there with your own.

**Comment by shaggygi** [comment]
Thanks @int19h the samples got me started on the project question.  Now if I could figure out how to do the 2nd issue by adding new file types to the New Window.

**Comment by int19h** [comment]
Look at the source for file templates that ship with the product itself: https://github.com/Microsoft/PTVS/tree/master/Python/Product/PythonTools/Templates/Files
