### ISSUE TITLE
call stack switching to different frames

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#1001]
I right click on the call stack window and choose switch to frame to move up the stack.  However the "python debug interactive" window debugger attached to the current session, doesn't change accordingly to the same frame, it remains in the current one, so there is no way to run commands in the switched frame even though you can hover your mouse over the variables in a previous frame and look at the contents.

**Comment by zooba** [comment]
#986 is the same issue. Thanks for the report
