### ISSUE TITLE
IntelliSense with system-site-packages enabled in virtualenv

### ISSUE THREAD

**Issue by bruce55** [Microsoft/PTVS#1004]
I'm using PTVS 2.2 on VS 2015 Community 2015.
For a project I want to import a package that cannot be installed using pip to my virtualenv. I enabled system site packages and all my system packages appeared under the virtual environment. However, when I'm trying to refresh IntelliSense's database, it's only displaying packages in the virtualenv.

**Comment by zooba** [comment]
We should provide IntelliSense for all packages if you've enabled it, but it doesn't show up in the user interface. (What we actually do is combine the entire database from the base environment, so you can look at that one in the UI. When the option is not enabled we only merge the standard library.)

**Comment by bruce55** [comment]
Umm... I open the project again today and IntelliSense is functioning normally. It was telling me to refresh the database. I'll open up a new solution and try reproducing the issue.

**Comment by zooba** [comment]
It's entirely possible that something is not very robust here. We don't encourage or regularly test this scenario.

Why can't you install the package into the virtualenv? I may know a trick to do it.

**Comment by bruce55** [comment]
I was enabling system site packages in a command prompt. That might be the issue. PTVS is smart enough to show updated packages under the environment, but unable to combine IntelliSense db on the fly. All I need to do is to close the solution and open it up again.

Yep, it is a pretty dirty way. The package is pygame. I think I tried installing and compiling all the stuff using pip a long time ago and was having issues related to library dependencies.

**Comment by zooba** [comment]
Ah yes, we don't automatically pick up the change, but we will if you close/reopen. It simplified things considerably (so much so that we wouldn't have added support at all if we "needed" to pick it up on the fly), and we expect most people to set the flag at creation time and never notice.

Yeah, pygame is one of the tricky ones. No good solution, but if you wanted to suggest that they release wheels for Windows then that may help things along.

**Comment by bruce55** [comment]
Actually they are providing a link on their download section to UCI's unofficial builds. That used to be msi packages a year ago. They are wheels now.

Thank you so much for your help.
