### ISSUE TITLE
Invalid warning with PTVS 2.1 (also on 2.1.1) and visual studio 2010

### ISSUE THREAD

**Issue by assafmendelson** [Microsoft/PTVS#1009]
I created a solution with a single python project. 
I get the following error:
Warning 1   The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.  C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets  983

**Comment by assafmendelson** [comment]
anyone knows how to solve this?

**Comment by zooba** [comment]
Should be fixed in newer versions.
