### ISSUE TITLE
PTVS install fails with 2015 update 1

### ISSUE THREAD

**Issue by scottz1** [Microsoft/PTVS#1010]
In case PTVS team hasn't seen this thread, a couple of us are stuck: https://social.msdn.microsoft.com/Forums/vstudio/en-US/7613397d-595e-4db1-9bdc-ddf7deb5c7f9/update-1-setup-blocked?forum=vssetup

**Comment by zooba** [comment]
It's an error in the online feed. I fixed it a couple of weeks back, but it was determined to be non-critical and was deferred until January.

Downloading the latest release from here is the best option, as it also has a few more fixes that aren't available via the version in VS setup right now (also deferred until January).
