### ISSUE TITLE
IronPython Console has stopped working; Crash when closing VS2015

### ISSUE THREAD

**Issue by lcorrigan** [Microsoft/PTVS#1011]
We have a number of Win 7 x64 PC's running VS2015 Pro w/ PTVS 2.1 and 2.2.  Of my two, one of them has an issue where IronPython crashes every time you close VS2015.  I've narrowed it down to one simple action: Just 'import clr' in the IronPython 2.7 console windows within the IDE. Don't need to load any projects.  When you close the IDE, You get: IronPython Console has stopped working. with the following details:
Problem signature:
 Problem Event Name:    CLR20r3
 Problem Signature 01:  ipy.exe
 Problem Signature 02:  2.7.5.1000
 Problem Signature 03:  548329c1
 Problem Signature 04:  IronPython.Modules
 Problem Signature 05:  2.7.5.1000
 Problem Signature 06:  548329bf
 Problem Signature 07:  a80
 Problem Signature 08:  23
 Problem Signature 09:  System.Exception
 OS Version:    6.1.7601.2.1.0.256.48
 Locale ID: 1033
 Additional Information 1:  0a9e
 Additional Information 2:  0a9e372d3b4ad19135b953a78882e789
 Additional Information 3:  0a9e
 Additional Information 4:  0a9e372d3b4ad19135b953a78882e789

This is the only PC that does it.  I have fully re-installed VS2015, PTVS (and upgraded to 2.2.2) and IronPython 2.7.5 but have had no luck (2 x for PTVS and IPY).  Did registry / file cleaning in between + reboots for both.  Not sure what the recipe for disaster is on this machine. Doesn't appear to have any missing .NET compared to my own other working machine. Not sure why the CLR20r3 and not a CLR4.x......
Closest ticket I could find for this was: https://github.com/Microsoft/PTVS/pull/970.  I've attached my event viewer applicable entries and the PTVS config data.  Would love some help on this mystery - thanks.

[EventViewer and Config.txt](https://github.com/Microsoft/PTVS/files/50960/EventViewer.and.Config.txt)

**Comment by ipyguy** [comment]
I should probably add that this does not happen when using an iropython console outside of VS2015.  It also does not happen in Eclipse with PyDev.

**Comment by zooba** [comment]
Extracted from the linked file:
```
Application: ipy.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
Stack:
   at Microsoft.Scripting.Interpreter.Interpreter.Run(Microsoft.Scripting.Interpreter.InterpretedFrame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run5[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.__Canon, System.__Canon, System.__Canon, System.__Canon)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon, System.__Canon, System.__Canon)
   at IronPython.Runtime.FunctionCaller`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Call2(System.Runtime.CompilerServices.CallSite, IronPython.Runtime.CodeContext, System.Object, System.__Canon, System.__Canon)
   at IronPython.Runtime.Method+MethodBinding`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SelfTarget(System.Runtime.CompilerServices.CallSite, IronPython.Runtime.CodeContext, System.Object, System.__Canon)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon, System.__Canon)
   at IronPython.NewTypes.System.IO.TextWriter_8$8.Write(System.String)
   at System.IO.TextWriter+SyncTextWriter.Write(System.String)
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.UnhandledException(Microsoft.Scripting.Hosting.ScriptEngine, System.Exception)
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.RunCommandLine()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.ExecuteInternal()
   at PythonConsoleHost.ExecuteInternal()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Execute()
   at Microsoft.Scripting.Hosting.Shell.ConsoleHost.Run(System.String[])
   at PythonConsoleHost.Main(System.String[])
```

The stack trace shows the exception is entirely within IronPython itself. I suspect this means that our interactive code (in `visualstudio_py_repl.py`) is somehow triggering an exception in IronPython that is not being caught.

I can't repro the issue on my own machine, but I'm setting up a Win7 box to try it out. There is a Win7+CLR+NGen issue that occasionally causes IronPython to crash, which has been fixed in Win8 and later. That may be involved here, but since we're running IronPython in its own process it seems unlikely.

**Comment by zooba** [comment]
And it repros easily on Win 7. Will let you know what I find

**Comment by ipyguy** [comment]
Thanks.  I'll butt-out after this, but wanted to let you know that calling quit() in the console before closing the IDE makes the crash go away, but the error is there when you click the console reset button.  I use the reset button a lot and at least on this machine, I've been seeing massive memory increase as I reset the console and create new instances of our .NET class's.  I thought it was our libs but now I wonder if the reset is not cleaning things up as well as it should.

**Comment by zooba** [comment]
So it looks like we're trying to write output back to VS, which is raising exceptions after VS is closed. I have no idea why this doesn't crash on all OSs, but perhaps .NET does caching of writers differently?

In any case, the fix can be applied by hand to `visualstudio_py_repl.py`. The offending code starts around line 1265 and with the fix (the `try/except Exception` lines added) looks like this:

```python
if sys.platform == 'cli':
    import System
    class DotNetOutput(System.IO.TextWriter):        
        def __new__(cls, backend, is_stdout, old_out=None):
            return System.IO.TextWriter.__new__(cls)
        
        def __init__(self, backend, is_stdout, old_out=None):
            self.backend = backend
            self.is_stdout = is_stdout
            self.old_out = old_out

        def Write(self, value, *args):
            if self.old_out:
                self.old_out.Write(value, *args)

            if not args:
                if type(value) is str or type(value) is System.Char:
                    try:
                        if self.is_stdout:
                            self.backend.write_stdout(str(value).replace('\r\n', '\n'))
                        else:
                            self.backend.write_stderr(str(value).replace('\r\n', '\n'))
                    except Exception:
                        pass
                else:
                    super(DotNetOutput, self).Write.Overloads[object](value)
            else:
                self.Write(System.String.Format(value, *args))

        def WriteLine(self, value, *args):
            if self.old_out:
                self.old_out.WriteLine(value, *args)

            if not args:
                if type(value) is str or type(value) is System.Char:
                    try:
                        if self.is_stdout:
                            self.backend.write_stdout(str(value).replace('\r\n', '\n') + '\n')
                        else:
                            self.backend.write_stderr(str(value).replace('\r\n', '\n') + '\n')
                    except Exception:
                        pass
                else:
                    super(DotNetOutput, self).WriteLine.Overloads[object](value)
            else:
                self.WriteLine(System.String.Format(value, *args))

        @property
        def Encoding(self):
            return System.Text.Encoding.UTF8
```

I'm currently rewriting the REPL backend entirely for our next version of PTVS, so I'll make this change locally in case I end up retaining this class (which seems likely). But there probably won't be a PTVS release with this fix any time soon as we're now focused on our next big release.

**Comment by ipyguy** [comment]
That's working nicely. Thanks a bunch.

**Comment by lcorrigan** [comment]
Quickly reminded of this one after doing a fresh install today with PTVS 2.2.5 and IronPython 2.7.6.3 on VS2015 Pro. I don't recall this 'visualstudio_py_repl.py' being in two places last time but with the above combination of versions, I see two files. One at 
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2
and one at
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\ptvsd
I changed both files and now I get lockups just typing import clr (Enter) and then the exception thrown before.  Not sure if I should have changed only one, or if there's a new issue.

**Comment by zooba** [comment]
There might be a new issue - we haven't done thorough testing with IronPython 2.7.6 yet (simply due to lack of time - we did 2.7.5 pretty well). Are you still on Windows 7?

Also, changing both files is fine, though the one in `ptvsd` shouldn't matter here. Because of the way we grafted remote debugging into our existing debugger, it was easiest to install two copies of the same file.

**Comment by lcorrigan** [comment]
Yep, still on Windows 7 (x64 pro) - just on a PC I configured a few weeks ago.  
After the above, I went back to 2.2.4 - Got an error on startup stating the PTVS couldn't load.
Since then, I've tried the following (some more often than others) in different combinations.  I either get the failed to load the extension at startup, get lockup when typing 'import clr' or get to the level of error I had earlier in this ticket (exception on closing).  Typically if I uninstall, I run CC cleaner on files and registry after:
* Uninstalled Anaconda3 
* re-installed IronPython 2.7.6 / tried 2.7.4 again 
* Did a repair on VS2015
* Did numerous repair trials on PTVS when not uninstalling them altogether.
* Tried PTVS 2.2.3 and up. etc. 
* Deleted my VS2015 Component cache a few times here and there, always built the IronPython Autocompletion for the console before using etc.

My current state is PTVS 2.2.4 (installed through VS2015 setup) and IronPython 2.7.5.  Even though I changed both files, I can't get better than my original issue.  I.e.: import clr and then exit the IDE == crash.  Tried using the x64 and x86 versions of the interpreter in PTVS == same.  I have a colleage who has been running IronPython 2.7.5 with 2.2.3 PTVS for some time now.  I might try that combo now.  He has never had to do the file hack above and he's on windows 7 too.  Totally lost.

**Comment by lcorrigan** [comment]
PTVS 2.2.3 and IronPython 2.7.5 on this machine in it current state, will crash after closing the IDE (after import clr) as well.  Since my colleage has this combo without issues, I wonder what else it could be.

**Comment by zooba** [comment]
Could you open Tools, Python Tools, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com? It should include info about the crashes you're seeing.

**Comment by lcorrigan** [comment]
Sorry Steve, Before I saw your post, I removed and re-installed VS2015.  VS must have left so much crap behind from previous removals that it wouldn't even start without freezing (complaining about Azure and others) even in SafeMode.  I snapped - uninstalled it again and have been deleting un-removed VS2015 folders and registry entries ever since.  Were SO many installer entries.....  Currently installing VS2015 from another location, with default install.  Will put IronPython 2.7.5 on if I can start VS, and will put PTVS 2.4.5 on separately after all that and let you know how it goes (tomorrow).  Thanks for being more responsive than I am observant.

**Comment by lcorrigan** [comment]
Well....I managed to get VS2015 up and running by itself again - slight complaint about having a later version of VC++ at the end of the install.  Installed IronPython 2.7.5.  Then installed PTVS 2.2.5 manually (not through extensions).  I get a message when starting VS now that "The 'Python Tools Package' package did not load correctly.  I had this earlier today with some combo I was using. Not sure if this is related to the C++ runtimes but I can't click the diagnostics or I just get that same message box.

**Comment by zooba** [comment]
One problem that can cause that is lingering files in your `%LocalAppData%\Microsoft\VisualStudio\14.0` and `%AppData%\Microsoft\VisualStudio\14.0` directories. Those are safe to delete entirely if you've just reinstalled VS (you may lose some of your configuration, but everything else in there will be regenerated automatically).

**Comment by lcorrigan** [comment]
Yeah, I had deleted both of those a few times yesterday.  At my last post, I had though i cleaned things up totally (registry too) but no version of PTVS that was remotely working in the past will run on my machine now (2.2.3, 4 & 5). IronPython 2.7.5.  Will tinker with it at a later time.

**Comment by zooba** [comment]
The only remaining piece here seems to be testing with new IronPython versions, which we are getting to (slowly, but it mostly seems to be okay so far).
