### ISSUE TITLE
Django DB not syncing/migrating and not modifying database table

### ISSUE THREAD

**Issue by aewhatley** [Microsoft/PTVS#1015]
I've run into a strange issue - whenever I change the parameters of a Model, and then sync the DB or migrate, I either get a message along the lines of "column name not found for app_name" if I added in a new parameter, or "column name cannot be blank" if I deleted an old parameter. The only solution I have found to this is to open command prompt, close Visual Studio, and type in "python migrate.py dbshell" and then "DROP TABLE name;" and then migrate/sync everything again, which is very unwieldy. I posted about this on Django Googlegroups, and was told that Django should have no problem modifying the database table if the model is changed.

I am running  VS 2015 Update 1 with Django 1.8.6.

**Comment by jchildren** [comment]
I had the same issue, the only way I found I could fix it was deleting the .sql3 file entirely, after which the issue disappeared. It was likely caused when I updated from 1.7 to 1.9.

However, you can also obtain it from not running 'makemigrations' before 'migrate', as the former is required for model changes to be reflected in the database. However you can only do this manually currently, it would be nice if a button were added for the command.

**Comment by zooba** [comment]
So it sounds like this is related to the changed Django commands? We've added new context menu items for them and they will be in our next update, already available as a [dev build](https://github.com/Microsoft/PTVS/releases/tag/dev-2016-02-01)

We'll always require users to have enough Django knowledge to make this stuff work - we can't possibly maintain deep integration that is also up to date (e.g. when they release Django 1.10 and break whatever we've done again).

**Comment by jchildren** [comment]
Yes sorry, I should have mentioned that I was using the latest devbuild which has a context menu item for `migrate`, but not `makemigrations`. 

`migrate` does at least tell you there is an error in the console which most people should be able to figure out.

**Comment by zooba** [comment]
`makemigrations` has been added.
