### ISSUE TITLE
Python Tools Background Analyzer Automatically Starts Up

### ISSUE THREAD

**Issue by MarkIvanDev** [Microsoft/PTVS#1016]
Whenever I start Visual Studio 2015 Community Edition, Python Tools Background Analyzer automatically starts up. Even when I am not working on a python project or the interactive window is not open. Is this a behavior I can change? Because it is a memory hog.

**Comment by zooba** [comment]
Sure, you'll find that option under Tools, Options, Python Tools, "Automatically generate completion DB on first use".

FWIW, it's only a temporary memory hog. Once it finishes running it saves the results and doesn't run again (unless you install new packages).

**Comment by allanelder** [comment]
Actually, this is still an issue if you uncheck that option based on what I just saw. If you start an instance of VS2015, the CPU doesn't spike. If you start a 2nd instance, somehow it kicks off the completion DB population even if I'm not using python. This was with PTVS 2.2.5 and confirmed using the performance analyzer in VS.

**Comment by zooba** [comment]
Depending on the specific steps you followed, the option may not be turned off in all instances of Visual Studio. I'll see if I can reproduce it, but there's unlikely to be a fix for it in VS 2015.
