### ISSUE TITLE
basic issue with interactive window

### ISSUE THREAD

**Issue by durbinjw** [Microsoft/PTVS#1018]
I am brand new to PTVS. I brought up the interactive window and typed in 2 + 2 and hit the return key. I am expecting it to show

4

instead it shows

2 + 2
...
what am it doing wrong? I can't get to 1st base.

Jim

**Comment by zooba** [comment]
Which versions of Visual Studio and PTVS do you have? I believe this could potentially happen with VS 2015 Update 1 and PTVS 2.2 or earlier.

The most up to date versions are VS 2015 Update 1 and [PTVS 2.2.2](https://github.com/Microsoft/PTVS/releases/tag/v2.2.2).

**Comment by durbinjw** [comment]
Microsoft Visual Studio Professional 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Visual Basic 2015   00322-50050-99457-AA890
Microsoft Visual Basic 2015

Visual C# 2015   00322-50050-99457-AA890
Microsoft Visual C# 2015

Visual C++ 2015   00322-50050-99457-AA890
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.30718.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.30718.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.30718.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

**Comment by aewhatley** [comment]
Weird. I just typed in 2+2 on the interactive window for Python 2.7 and 3.5, in VS 2015 Update 1 and PTVS 2.2.2, and got 4.....

**Comment by durbinjw** [comment]
maybe it is broken in PTVS 2.2.30178.0?  How do I get support for this?  I
can't begin to use it as is.

**Comment by zooba** [comment]
Yep, you have installed VS 2015 Update 1 without the PTVS update (somehow... this isn't supposed to be possible).

Install PTVS 2.2.2 from https://github.com/Microsoft/PTVS/releases/tag/v2.2.2

**Comment by durbinjw** [comment]
That fixed it.  Help now shows Python tools 2.2.31124.00 - looks like there was a recent fix.

Thanks.- now I can proceed to become REALLY confused.
