### ISSUE TITLE
Connection refused when trying to add session variabel to cache in Django

### ISSUE THREAD

**Issue by aewhatley** [Microsoft/PTVS#1019]
I am trying to add a session variable to the cache in Django using django-redis using the exact same code on this documentation page (https://niwinz.github.io/django-redis/latest/). However, when I add the cache settings to settings.py, and run:

from django.core.cache import cache
cache.set("foo", "value", timeout=25)

I get the following error message: redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

I do not have any firewalls set up or anything that I can think of blocking the connection, so perhaps the problem lies with something in VS 2015.....

**Comment by zooba** [comment]
It seems like the cache is not running on that port. Does the code work if you run the Django site from the command line?

**Comment by aewhatley** [comment]
I tried that as well. I got the same error when running from port 8000, and when I tried running from port 6379 (the same port that the documentation uses) I got a different error message: 

"Error while reading from socket: ('Connection closed by server.',)"

**Comment by zooba** [comment]
Is that last error the one you get when running outside of VS?

**Comment by aewhatley** [comment]
Yes; my comment was referring to what happened when I ran it from command line.

**Comment by zooba** [comment]
Guessing it's the same error, but you're seeing it earlier in VS.

Unfortunately, I'm not much help if it isn't working from the command line either. I'm not familiar enough with how to configure Redis to advise. If you can get it working from there but it still won't run within VS, I (or someone else here) may be able to help figure out what's different.

**Comment by aewhatley** [comment]
Ok hmm, it looks like the redis server does not work on Windows, which is probably what is causing the  issue. Looks like I''ll have to look in to how to store complex session variables in another way.
