### ISSUE TITLE
Profiling but not coverage? Are you mad?

### ISSUE THREAD

**Issue by jameshnsears** [Microsoft/PTVS#1020]
RE: http://blogs.technet.com/b/machinelearning/archive/2015/08/25/help-design-the-next-version-of-python-tools-for-visual-studio.aspx / "Make Your Voice Count"

It's great that VS 2015 supports Python. Coming back to VS after so many years away is nostalgic.

But I just don’t get it. Why do you have profiling but not coverage? If you want to make me use this tool over pycharm or pydev then incorporate coverage. Sure I can run a script from the command line – but why should I? It’s not as if I don’t have enough to do as it is.

Please make it easy for me – and I am sure others as well - to come back to VS rather than for me consider it a joke and have to go back to half of this and half of that. Surely your better than that Microsoft?

**Comment by zooba** [comment]
Good suggestion. We'll take a look at integrating that for the next release.

Are you mainly interested in coverage as part of profiling or part of testing? (Obviously "yes" is an appropriate answer, but we always need to look at what to prioritise if we can't get everything done.)

**Comment by jameshnsears** [comment]
Hi Steve – thank you for the follow up and for consideration.

Coverage, for me, is all about the unit tests. Apologies for being ambigious.

I rarely – maybe a handful of times each year, if that - use profiling. Whereas I regularly - say a few times each day, on average mind you - incorporate feedback from coverage when writing code.

Put another way, omission slows me down, it puts a downer on me wanting to use the tool. Inclusion says, “yay – we’ve got a great tool and we’re doing all we can to enable you to write great, professional quality, software”.

Hope that helps.

PS – don’t get me started on missing flake8 functionality ;-)

**Comment by zooba** [comment]
It does, thank you. Our unit testing support is pretty threadbare right now, in part because it's really hard to extend the Visual Studio UI in this area (it was basically designed solely with C# in mind, unfortunately). Analyzing test coverage is also unavailable in the lower-spec versions of VS, which is where most of our users are (Express and Community), and to make it available to them as well is a lot more work. But it is certainly something we'd love to support.

(You can see how we added PyLint support [here](https://github.com/Microsoft/PTVS/blob/master/Python/Product/BuildTasks/Microsoft.PythonTools.targets#L144) - feel free to clone and modify within your own projects to run flake8. It doesn't require changing or rebuilding PTVS.)

**Comment by hawkerm** [comment]
Is there a way to modify the command line that gets executed by the plugin when it discovers/runs tests?  It's be great to just inject the call to the coverage library: http://coverage.readthedocs.org/en/coverage-4.0a5/

**Comment by hawkerm** [comment]
Just posting to anyone looking for a solution:

I luckily have all my test cases inherit from a base test case which extends unittest.TestCase.  In the setUp method I add the coverage lines:
    import coverage
    coverage.process_startup()

(you can wrap them in a try/except ImportError if you don't want to cause things to fail if [coverage ](https://pypi.python.org/pypi/coverage/4.0a5) isn't installed).

I created a '.coveragerc' [config file](http://coverage.readthedocs.org/en/coverage-4.0a5/config.html#config) as the docs suggest in the root of my solution.  I made sure to enable the 'parallel=True' option in the [run] section.  Then I set a system environment variable for [COVERAGE_PROCESS_START](http://coverage.readthedocs.org/en/coverage-4.0a5/subprocess.html) equal to '.coveragerc' (without single quotes) and restarted VS.

Now, when I run my tests I get the corresponding .coverage.XXXXXX.####.#### files from each test run and can use '[coverage combine](http://coverage.readthedocs.org/en/coverage-4.0a5/cmd.html#cmd-combining)' to generate a consolidated file to run 'coverage report' or 'coverage html' on.
