### ISSUE TITLE
Intellisense not showing certain modules

### ISSUE THREAD

**Issue by jkm137** [Microsoft/PTVS#1022]
I installed protobuf 2.6.1 via pip in PTVS, and it installed correctly. Intellisense does not know about the module though (even after multiple "Refresh DB" clicks under the Intellisense tab). It always shows the standard error: 

Unable to resolve "google.protobuf". Intellisense may be missing for this module 

I am able to import and use the module if I run python from the command line. Under Diagnostic Info in PTVS, I also see the package installed: 

Installed Packages: 
Name,Version,InterpreterName,InterpreterVersion,InterpreterArchitecture,Installer,Elevated,InstallResult 
Successful Installations
astroid,1.4.1,CPythonInterpreterFactory,2.7,X86,Existing,False,0
colorama,0.3.3,CPythonInterpreterFactory,2.7,X86,Existing,False,0
cycler,0.9.0,CPythonInterpreterFactory,2.7,X86,Existing,False,0
jinja2,2.7.3,CPythonInterpreterFactory,2.7,X86,Existing,False,0
lazy-object-proxy,1.2.1,CPythonInterpreterFactory,2.7,X86,Existing,False,0
markupsafe,0.23,CPythonInterpreterFactory,2.7,X86,Existing,False,0
matplotlib,1.5.0,CPythonInterpreterFactory,2.7,X86,Existing,False,0
numpy,1.10.1,CPythonInterpreterFactory,2.7,X86,Existing,False,0
p4python,2014.2.962887,CPythonInterpreterFactory,2.7,X86,Existing,False,0
pip,7.1.2,CPythonInterpreterFactory,2.7,X86,Existing,False,0
protobuf,2.6.1,CPythonInterpreterFactory,2.7,X86,Existing,False,0
pylint,1.5.1,CPythonInterpreterFactory,2.7,X86,Existing,False,0
pyparsing,2.0.6,CPythonInterpreterFactory,2.7,X86,Existing,False,0
python-dateutil,2.4.2,CPythonInterpreterFactory,2.7,X86,Existing,False,0
pytz,2015.7,CPythonInterpreterFactory,2.7,X86,Existing,False,0
scikit-learn,0.17,CPythonInterpreterFactory,2.7,X86,Existing,False,0
setuptools,18.7.1,CPythonInterpreterFactory,2.7,X86,Existing,False,0
six,1.10.0,CPythonInterpreterFactory,2.7,X86,Existing,False,0
wheel,0.26.0,CPythonInterpreterFactory,2.7,X86,Existing,False,0
wrapt,1.10.5,CPythonInterpreterFactory,2.7,X86,Existing,False,0
Failed Installations 

I'm running PTVS 2.2. Any idea what the issue is?

Thanks for your help!

**Comment by zooba** [comment]
Guessing it's a namespace package, since you're importing a different name from the package. (This is where a fake package is created at runtime and there's no `__init__.py` file in the `google` folder where there normally would be - currently we don't detect these properly unless you add the `__init__.py`.)

This is already tracked by #572
