### ISSUE TITLE
Error While Opening Django Shell - Python Interactive Window

### ISSUE THREAD

**Issue by nerdy21** [Microsoft/PTVS#1023]
I wanna mention that i'm just learning python so i'm a newbie and i need some help.
Here is my problem -
I was following the lesson https://mva.microsoft.com/en-US/training-courses/developing-websites-using-python-and-django-11415?l=uw7LHeEJB_5304300477

And i tried opening the python interactive window Right Click On " DatabaseFun " > Python > Open Django Shell 

And the interactive windows opens with error : 

Python interactive window. Type $help for a list of commands.
An internal error has occurred in the Interactive window.  Please restart Visual Studio.

And the interactive window seems to be disconnected 

Additional Details - 
I've installed Python 3.5 - 32bit
Visual Studio 2015
Screenshots -

<blockquote class="imgur-embed-pub" lang="en" data-id="qun6E"><a href="//imgur.com/a/qun6E">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by huguesv** [comment]
Which version of VS 2015 and PTVS do you have? (check VS about box)

I tried with VS 2015 Update 1 (build 24720) and PTVS 2.2 (build 31124) and the Django Shell worked for me (on an unmodified new project).

**Comment by nerdy21** [comment]
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA482
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA482
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA482
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Console Launcher   1.4.1.0
A command to launch Console in the currently selected Solution Explorer item context. Added to the Tools and Solution Explorer menu when a solution or project is open.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.30718.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.30718.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.30718.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

These are all the details i found on VS.

**Comment by huguesv** [comment]
I would recommend that you upgrade to the newer build of PTVS available here (build 31124):
https://github.com/Microsoft/PTVS/releases/tag/v2.2.2

There were definitely REPL bugs with VS 2015 Update 1 and the earlier builds of PTVS 2.2, but I'm not sure if they were fixed in the version you are currently using or not.

**Comment by nerdy21** [comment]
@huguesv , Thanks that saved my day :D

**Comment by crwilcox** [comment]
Closing as it is resolved with a newer build.

**Comment by mohamadalkhuzeem** [comment]
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA572
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA572
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA572
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.30718.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.30718.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.30718.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio


Same error for me. Using all the latest versions of the needed software (i.e. Visual Studio, PTVS and Python).

Here's the error message I'm getting:
Python interactive window. Type $help for a list of commands.
An internal error has occurred in the Interactive window.  Please restart Visual Studio.
