### ISSUE TITLE
tkinter form

### ISSUE THREAD

**Issue by nlukiv** [Microsoft/PTVS#1025]
Hey guys
I'm trying to run simple gui program via PTVS with 2015 VS

from tkinter import *
gui = Tk()
gui.geometry('450x450')
gui.title("GUI")
gui.mainloop()

The problem is that no form appears, just the console window with "Press any key to continue". If i'm doing this via cmd, the form appears correctly

Please help me on this matter
I am sorry if such isuue already resolved, couldn't find it.

**Comment by int19h** [comment]
Check your taskbar - perhaps the window did appear, but was hidden by the VS window?

**Comment by nlukiv** [comment]
nope, just console window there

**Comment by int19h** [comment]
Hm. It really shouldn't matter, but just in case, try going to project properties and checking the checkbox on the General tab that says "Windows application".

**Comment by nlukiv** [comment]
done. now even the console window ceased to appear

**Comment by nlukiv** [comment]
(okay, I just pressed the wrong comment submission button here. whoops)

tried the checkbox you said, it made the console window do not appear anymore. no positive result

**Comment by int19h** [comment]
Can you provide the version numbers for all components (VS - including any updates, PTVS, and Python) so that I can try to repro?

**Comment by nlukiv** [comment]
VS Pro 14.0.24720.00, no updates
PTVS - 2.2, Python Tools for VS 2015
Python 3.5

**Comment by nlukiv** [comment]
I found the reason. It was executing the main file of the python project, which was empty. The gui.py file was omitted

Thank you for your involvement, much appreciated!

**Comment by int19h** [comment]
Great! I would still strongly recommend updating to VS 2015 Update 1 and PTVS 2.2.2 (you should get the latter automatically if you do the former). There are other bugs that have been fixed there that you might run into otherwise.
