### ISSUE TITLE
QGIS Lyon 2.12.1 Environment fails

### ISSUE THREAD

**Issue by subsci** [Microsoft/PTVS#1030]
**It should not be this difficult to set up.  PTVS as configured here freezes, does not scan libs, and otherwise frustrates.**

Traceback (most recent call last):
  File "F:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_launcher.py", line 25, in <module>
    import visualstudio_py_debugger as vspd
  File "F:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_debugger.py", line 24, in <module>
    import ctypes
  File "F:\QGIS_Lyon\apps\Python27\Lib\ctypes__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes

**_Internal error detected. Please copy the above traceback and report at
http://go.microsoft.com/fwlink/?LinkId=293415**_

Press Enter to close. . .

**Environments:**
    Microsoft.PythonTools.Project.LoadedProjectInterpreterFactoryProvider
    Microsoft.PythonTools.Interpreter.ConfigurablePythonInterpreterFactoryProvider
        Id: 08a18329-cec0-4f35-9c50-8d1402f77714
        Factory: qgis py
        Version: 2.7
        Arch: X86
        Prefix Path: F:\QGIS_Lyon\bin\
        Path: F:\QGIS_Lyon\bin\python.exe
        Windows Path: F:\QGIS_Lyon\bin\pythonw.exe
        Lib Path: F:\QGIS_Lyon\apps\Python27\Lib
        Path Env: PYTHONPATH

**_Microsoft Visual Studio Enterprise 2015**_
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA104
Microsoft Architecture and Modeling Tools

UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA104
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA104
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA104
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JustDecompile Tools   1.0
Makes JustDecompile functionality available in VIsual Studio. Requires JustDecompile installation.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

**Python Tools for Visual Studio   2.2.31105.00**
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.31105.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.31105.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by crwilcox** [comment]
Am I understanding correctly that you were trying to attach the PTVS debugger to a running python process created by [QGIS](http://qgis.org/en/site/about/index.html)? Or are you trying to use the python.exe that is shipped with QGIS to do other development? 

Further information about what you are doing and how you were doing it (reproduction steps) would help us to provide you better assistance.

Thanks!

**Comment by subsci** [comment]
I am simply trying to use the python.exe that is shipped with QGIS to do development.  

This python.exe shipped with QGIS requires a complex environment to develop standalone apps that use its rich geoprocessing.  QGIS docs demonstrate setting up the environment on windows in eclipse with pydev (and no remote debugging).  I start Visual Studio in this environment

PYTHONPATH=F:\QGIS_Lyon\apps\qgis\bin
set PATH = F:\QGIS_Lyon;F:\QGIS_Lyon\bin;F:\QGIS_Lyon\bin\apps\qgis\bin;F:\QGIS_Lyon\apps\qgis\python\qgis;F:\QGIS_Lyon\apps\Python27\libs;F:\QGIS_Lyon\apps\Python27\DLLs;%PATH%

**Comment by subsci** [comment]
I simply execute this program below and the shell window that pops up shows the error at the top of this thread.  I am doing the simplest of hello world stuff that fails.  Even if I do not alter the  environment that VS runs in, the same failure happens.  The Python environment is filled in using autocomplete with the PTVS dialog.  The only manual thing I do is set the Lib directory, and this seems ok, because intellisense finds the third party stuff.  I also use PYTHONPATH.  Iron Python works fine.  I have not installed CPython

import os
print 42
print os.getcwd()

**Comment by subsci** [comment]
The use case I want to do is this.  
This has not been possible for me to configure, but evidence suggests it can be done.

Install QGIS Lyon 1.12 to my Windows 10 machine where I have VS2015 with PTVS.
Then using the Python27 shipped with QGIS in VS IDE develop simple standalone programs like the following that use the python geo-processing of QGIS.  For example this simple working program works fine when run from QGIS Python Console, but there is no QGIS IDE.  I have read reports VS IDE instead of eclipse IDE can be used, both for standalone app and plugin development.  I have not been able to do so.  I am not developing a QGIS plugin. I do not want to attach to the QGIS process running the plugin.  I think this is a use case that will benefit a large number of GIS app developers

import qgis.core
import qgis.analysis
import processing
    
layer = QgsVectorLayer("f.shp", "f", "ogr")
if layer.isValid():
    print "Layer %s loaded" % layer.name()
elif  not layer.isValid(): 
    print "Layer %s did not load" % layer.name()

processing.runalg("qgis:intersection", a.shp, b.shp, axb.shp )

**Comment by crwilcox** [comment]
Thanks for providing more information. I haven't used QGIS so getting this information from you saves a good amount of time. I am going to look into this and see if we can't chase down what isn't working here.

**Comment by crwilcox** [comment]
It seems QGIS Provides a script to run python.exe as they setup up a few different paths. There may be a cleaner way to do this but since QGIS seems to use a script like this I figured it was reasonable to start with that.

I took this script and just changed it to launch VS instead of python.exe at the end. This launched VS in the correct context. 

SCRIPT (named python-qgis-vs.bat and put in qgis bin directory):
```bat
@echo off
call "%~dp0\o4w_env.bat"
@echo off
path %OSGEO4W_ROOT%\apps\qgis\bin;%PATH%
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis\qtplugins;%OSGEO4W_ROOT%\apps\qt4\plugins
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis\python;%PYTHONPATH%

SET VISSTUDIO="C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe"
start "Visual Studio 14 with QGIS" /B %VISSTUDIO%
```

Then, as for setting up your vs environment, go to Tools > Python Tools > Python Environments and then click +Custom.  The settings are pretty easy to fill in.  You can use the auto detect to find the python.exe and wpython.exe.  You will need to manually enter the lib location. At the end hit apply.  

![untitled](https://cloud.githubusercontent.com/assets/638797/11859033/3814ecc4-a41c-11e5-9fd8-0be083be5e00.png)

And that should leave you with an environment that works.

**Comment by subsci** [comment]
This is great thanks.  

Now I can use the standard library from QGIS python in PTVS.  E.g. **import os** works!

However The debugger tells me the QGIS modules (see below) cannot be found.
**ImportError was unhandled by user code.** 
**Message: No module named qgis.core**
Please let me know if you have tested importing the QGIS modules.

Unless something is broken, the only difference in my environment is that  I installed QGIS in a custom location that lacks spaces in pathnames.  (This is required to use embedded GRASS without any issue, as GRASS sometimes cannot handle spaces in pathnames).  Note too that PTVS intellisense in my config never finishes.  The button to update the DB never goes away.  Intellisense finds the stuff in LIB, but nothing else. 

**PTVS reports these modules cannot be found:**

from qgis.core import *
from qgis.gui import *
from qgis.utils import *
from PyQt4.QtCore import *
from PyQt4.QtGui import *
app = QgsApplication([], True)
app.setPrefixPath("f:/QGIS_Lyon/apps/qgis", True)
app.initQgis()

**Comment by crwilcox** [comment]
I just tried this again and it is working fine for me so there is something slightly different between your setup and mine. I don't think it is the non-default path.

One thing that might be wrong is the env script that is called by the bat file I provided. The script for VS needs to be in the bin directory of QGIS for it to find it properly (this line `call "%~dp0\o4w_env.bat"`). I have mine at `C:\Program Files (x86)\QGIS Lyon\bin\python-qgis-vs.bat` which is where the other python-qgis.bat script lives.

It definitely doesn't mind spaces but I wonder if you placed it elsewhere.

![untitled](https://cloud.githubusercontent.com/assets/638797/11876552/30f02c5a-a49f-11e5-93ff-6aa9f7556d93.png)

**Comment by subsci** [comment]
Thank you so very much for following up on this--so helpful for a large number of us to see **your proof that PTVS and the rich VS IDE can host QGIS library based applications!!!**.

I have installed QGIS to *F:\QGIS_Lyon* and the script for VS lives in *F:\QGIS_Lyon\bin*.  

The `call "%~dp0\o4w_env.bat` does work.

QGIS does not mind the spaces in the path, but to use the GRASS toolset within the QGIS Desktop, the spaces are problems.  

I will dig into this, and seeing the proof gives me incentive. 

Perhaps I need to install QGIS to the default location `C:\Program Files (x86)\QGIS Lyon\`.  I notice that some instructions for setting up python IDE add the directories of QGIS binaries to the System PATH in addition or rather than using the `o4w_env.bat` but that does not seem to help much with my installation on *F:\QGIS_Lyon*

**Comment by crwilcox** [comment]
I am happy I could help you so far.  

You should be able to add all of the items to your PATH and PYTHONPATH manually but I, not being very familiar with QGIS, just relied on the script they sent along. If you were to set the settings to the correct place though you don't need that. Just for reference, this is what PATH and PYTHONPATH get set to.

```
C:\Users\crwilcox>echo %PATH%
C:\PROGRA~2\QGISLY~1\apps\qgis\bin;C:\PROGRA~2\QGISLY~1\bin;C:\Windows\system32;C:\Windows;C:\Windows\WBem;C:\PROGRA~2\QGISLY~1\apps\msys\bin;C:\PROGRA~2\QGISLY~1\apps\Python27\Scripts

C:\Users\crwilcox>echo %PYTHONPATH%
C:\PROGRA~2\QGISLY~1\apps\qgis\python;
```

**Comment by subsci** [comment]
thank you.  I prefer not to add paths manually.  If I invoke `set` then pause in the VS-python bat, I see the *environment* (as below filtered for just the QGIS stuff). do you think it's worth a try to reinstall QGIS in the default directory

GDAL_DATA=F:\QGIS_Lyon\share\gdal
GDAL_DRIVER_PATH=F:\QGIS_Lyon\bin\gdalplugins
GDAL_FILENAME_IS_UTF8=YES
GEOTIFF_CSV=F:\QGIS_Lyon\share\epsg_csv
HOME=C:\Users\Michael
HOMEDRIVE=C:
HOMEPATH=\Users\Michael
ITK_AUTOLOAD_PATH=F:\QGIS_Lyon\apps\orfeotoolbox\applications;
OSGEO4W_ROOT=F:\QGIS_Lyon
Path=F:\QGIS_Lyon\apps\qgis\bin;F:\QGIS_Lyon\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\WBem;F:\QGIS_Lyon\apps\msys\bin;F:\QGIS_L
yon\apps\Python27\Scripts
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROJ_LIB=F:\QGIS_Lyon\share\proj
PYTHONHOME=F:\QGIS_Lyon\apps\Python27
PYTHONPATH=F:\QGIS_Lyon\apps\qgis\python;
QGIS_PREFIX_PATH=F:/QGIS_Lyon/apps/qgis
QT_PLUGIN_PATH=F:\QGIS_Lyon\apps\qgis\qtplugins;F:\QGIS_Lyon\apps\qt4\plugins
QT_RASTER_CLIP_LIMIT=4096
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\Michael\AppData\Local\Temp
TMP=C:\Users\Michael\AppData\Local\Temp
VISSTUDIO="f:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe"
VS140COMNTOOLS=F:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSI_CACHE=TRUE
VSI_CACHE_SIZE=1000000

Press any key to continue . . .

**Comment by crwilcox** [comment]
Honestly, I don't know enough about QGIS to give you a decent answer. I know I would try since it isn't super hard to install but I am not sure it will have any effect.
