### ISSUE TITLE
Problems with PVTS recognizing classes in sub directories in projects in Python 3.4+ without __init__.py

### ISSUE THREAD

**Issue by lightmanca** [Microsoft/PTVS#1031]
Hi. I'm not sure where the forum is.  This may be best answered in a forum, and not as a bug.  If you redirect me, I'll put it there.

I just have a bunch of python scripts that work just fine in my Pycharm project, and when run in python. I'd like to use Visual Studio python tools, as it looks to have better intellisense.   It appears that PVTS is not finding my classes located in sub directories.  

I added the directories to the search path, but it did not help.  What did seem to help was mangling the import command to just note the class name, but then I figured python probably wouldn't run my project, so I'd like to see what I need to do for PVTS to work correctly.

I have the following structure. It's actually a collection py.test tests, with start script that initializes py.test: 

project-dir 
apitestrunner.py (test setup script) 
| 
|---ApiTestSuites 
| | 
| --test_api_app.py (Pytest module) 
| 
|---helpers
       |
       |
       ---Config.py   (def class Config)
       ---ServicesClass.py  (def class ServicesClass)
apitestrunner.py is the "startup script". It gets some config settings, and fires up pytest to run tests 

Because I have problems in both apitestrunner, and my test class, I do not think this has anything to do with pytest. 

pytools is telling me that it cannot resolve references to class Config.py, or ServicesClass.py from apitestrunner.py and test_api_app.py. Normally main-script does not import the test scripts (test_api_app.py), but I just tried it, and importing that seemed to work just fine. 

Is there some reason why the ide would have trouble recognizing the helper classes? The classes have the same name as the file names, and as I said this all works fine in other IDEs. 

Here are my import statements: 
apitestrunner.py:
 from helpers.Config import Config
 from helpers.ServicesClass import ServicesClass
test_api_app.py:
 from helpers.Config import Config
 from helpers.ServicesClass import ServicesClass
Thanks! 

Sam

**Comment by brettcannon** [comment]
Did you purposefully leave out your __init__.py files in your example or do you not have them? Does that make a difference?

And here is an attempt to rebuild the diagram of files and folders so it's readable.
```
project-dir 
apitestrunner.py (test setup script) 
| 
|---ApiTestSuites 
| | 
| --test_api_app.py (Pytest module) 
| 
|---helpers
       |
       |
       ---Config.py   (def class Config)
       ---ServicesClass.py  (def class ServicesClass)
```

**Comment by lightmanca** [comment]
Hi.  I don't have an init.py script. I don't deploy this anywhere.

Would PTVS look at init.py

**Comment by crwilcox** [comment]
To Add to what Brett said, if you don't have __init__.py files it will not run in Python 2.7. It would work in Python 3.5 so I am assuming that is what you are using?

**Comment by lightmanca** [comment]
Hi.  Sorry I guess that would be important to know.  I'm running Python
3.4.3

Thanks!

Sam

**Comment by crwilcox** [comment]
Perfect. I am going to update the title to specify 3.4+ Python since it is sort of relevant.  I can add some screen caps from my side. There is an actual issue here and we will have to make improvements to analysis.

Thanks for your feedback!
Chris

**Comment by crwilcox** [comment]
From @zooba, who is currently in a place nicer than Seattle on holiday:

We currently infer full package names backwards from the directory structure (rather than forwards from a search path), so namespace packages don't get their full name and we can't resolve them.

I'm fixing this in analyzer 2.0. For now, you can add __init__.py files and make your interpreter happy.

**Comment by crwilcox** [comment]
https://github.com/Microsoft/PTVS/issues/572 is tracking the fix for namespace packages.

**Comment by lightmanca** [comment]
Hi.  Thank you.

are you actually talking about __init__.py files?  That's all I found when
I googled the subject.  (I haven't had a need to create a module before)

Thanks!

Sam

**Comment by brettcannon** [comment]
Yep, Chris is talking about `__init__.py` files. Unfortunately they come out as "__init__.py" when you use Markdown.

**Comment by zooba** [comment]
Dup of #572
