### ISSUE TITLE
WinError bug

### ISSUE THREAD

**Issue by zwing99** [Microsoft/PTVS#1032]
I am pretty sure that visualstudio_py_testlauncher.py has a bug.  It references WinError when it should reference WindowsError. https://docs.python.org/2/library/exceptions.html.

This page: https://docs.python.org/2/library/ctypes.html states that WinError is simply a wrapper to raise a WindowsError.

I use 64bit python and i had to change this in order to make PTVS run my unittests.

**Comment by crwilcox** [comment]
Thanks @zwing99. That seems to make sense. If you want to you can submit a PR for that and we should be able to integrate the change. If you are not interested though, let us know and one of the core team can look into it.

Thanks!

**Comment by zwing99** [comment]
Pull request created #1033

**Comment by crwilcox** [comment]
Merged and closing.
