### ISSUE TITLE
Internal error python interactive window

### ISSUE THREAD

**Issue by ixje** [Microsoft/PTVS#1034]
Steps to reproduce:
- Create a Django Web Project
- Right click project -> Python -> Choose either "open django shell" or "django sync db"

the django management console at the bottom reports the following:
Python interactive window. Type $help for a list of commands.
An internal error has occurred in the Interactive window.  Please restart Visual Studio.

The output tab shows: 
An error occurred while running resource:Microsoft.PythonTools.Django;Microsoft.PythonTools.Django.Resources;OpenDjangoShellLabel.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Repl.BasePythonReplEvaluator.ExecuteTextWorker(String text)
   at Microsoft.PythonTools.Repl.BasePythonReplEvaluator.ExecuteText(String text)
   at Microsoft.PythonTools.Project.CustomCommand.<RunInRepl>d__41.MoveNext()

Using: 
* VS2015 Express web (v14.0.24720.00 Update 1)
* Python Tools for Visual studio 2.2.30718.00 (latest installer on website)
* Python environment set to "Python 2.7"

Note: interactive window also doesn't work when creating a "python application project" from a fresh start. In that case however it doesn't print any stack trace or additional messages in the "Output" tab.

**Comment by crwilcox** [comment]
Hi @ixje,

We have newer versions where this has been addressed. You can get them over on the [releases page](https://github.com/Microsoft/PTVS/releases).

Also, I am sorry we haven't kept the GitHub.IO page up to date, which is where you (pretty sure anyway) grabbed that older version from. I have made an issue for us to go fix that. https://github.com/Microsoft/PTVS/issues/1035
