### ISSUE TITLE
completion error

### ISSUE THREAD

**Issue by kidfruit** [Microsoft/PTVS#1038]
When I use flask-sqlalchemy, the completion can't work to analysis the class field like SQLAlchemy 's Model or session and so on.

Code like this:

```
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from sqlalchemy import *

app = Flask(__name__)
db = SQLAlchemy(app)

class User(db.Model):
            username = db.Column(db.String(80), unique=True)
            pw_hash = db.Column(db.String(80))

user1 = User.query.filter_by(username='peter').first()
```

This code can compile and run **without error**.
**BUT** ptvs can't analysis the type and give completion suggestion when coding. When I point the mouse to 'db', it will show me that db is a SQLAlchemy type, when point to 'Model', it will show **'unknown type'** and all code depend 'db.Model' can't have type analysis and completion suggestion. I open the source file of flask-sqlalchemy and find that the problem may be Model is a field of class SQLAlchemy. It's a normal problem not only in flask-sqlalchemy, but also in many other libs.

**Comment by zooba** [comment]
Dup of #3046
