### ISSUE TITLE
starting new django web project -> syntax error in apps.py & models.py

### ISSUE THREAD

**Issue by ixje** [Microsoft/PTVS#1040]
In following the Django 1.9 intro tutorial (off the official Django website) I create a new Django web project, selecting "install into virtual environment", and selecting python 3.5 as interpreter. 

The output tab (bottom) shows 2 syntax errors:

> Virtual environment is being created at 'c:\users\erik\documents\visual studio 2015\Projects\polls\polls\env'
> Virtual environment was successfully created at 'c:\users\erik\documents\visual studio 2015\Projects\polls\polls\env'
> Installing packages from 'c:\users\erik\documents\visual studio 2015\Projects\polls\polls\requirements.txt'
> Downloading/unpacking django<2 (from -r c:\users\erik\documents\visual studio 2015\Projects\polls\polls\requirements.txt (line 1))
> Installing collected packages: django
```python
> *** Error compiling 'c:\\users\\erik\\documents\\visual studio 2015\\Projects\\polls\\polls\\env\\build\\django\\django\\conf\\app_template\\apps.py'...
  File "c:\users\erik\documents\visual studio 2015\Projects\polls\polls\env\build\django\django\conf\app_template\apps.py", line 4
    class {{ camel_case_app_name }}Config(AppConfig):
          ^
SyntaxError: invalid syntax
*** Error compiling 'c:\\users\\erik\\documents\\visual studio 2015\\Projects\\polls\\polls\\env\\build\\django\\django\\conf\\app_template\\models.py'...
  File "c:\users\erik\documents\visual studio 2015\Projects\polls\polls\env\build\django\django\conf\app_template\models.py", line 1
    {{ unicode_literals }}from django.db import models
                             ^
SyntaxError: invalid syntax
```
Successfully installed django
Cleaning up...
'requirements.txt' was installed successfully.

It's unclear for me how to differentiate if I should report this at the Django project or here. Let me know if this is the wrong location.

**Comment by ixje** [comment]
A bit more information

Microsoft Visual Studio Express 2015 for Web
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Python Tools for Visual Studio   2.2.31124.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.31124.00
Provides templates and integration for the Django web framework.

For what it's worth: md5 of PTVS 2.2.2 VS 2015 installer ec1fdda0e83f4a3d4010ad22a48fe783

**Comment by zooba** [comment]
This would seem to be a Django issue (or perhaps setuptools). Those are template files that are not supposed to be precompiled on install.

**Comment by ixje** [comment]
@zooba , you're right it was a setuptools issue. Upgrading setuptools as suggested in the link below resolved the issue.

https://docs.djangoproject.com/en/1.9/releases/1.9/#syntaxerror-when-installing-django-setuptools-5-5-x
