### ISSUE TITLE
has_key method needed for debugger to recognise an object as dict-like

### ISSUE THREAD

**Issue by slishak** [Microsoft/PTVS#1044]
I've implemented a class that inherits from `collections.MutableMapping`, and it acts like a dictionary. I was hoping that the debugger would show the keys and values in a DataTip, but it only shows the keys.  After some digging through visualstudio_py_debugger.py, it turns out I have to implement a `has_key` method too otherwise it's not recognised (line 1338). The `has_key` method isn't called, so I guess it's just used to prevent some false positives where it would mistakenly recognise anything that has an attribute `items` as a dict. However, wouldn't it be nicer for it to recognise methods like `__getitem__` instead? Surely the bare minimum is for an object to implement a method to iterate over/list the keys (`keys`/`iterkeys`/`__iter__`), and a method to get the associated value (`__getitem__`)?

Obviously one could argue that `collections.MutableMapping` should implement `has_key` already...

``` python
import collections

class Test(collections.MutableMapping):
    def __init__(self):
        self.__internal_dict = {}

    def __getitem__(self, key):
        return self.__internal_dict[key]

    def __setitem__(self, key, val):
        self.__internal_dict[key] = val

    def __delitem__(self, key):
        del self.__internal_dict[key]

    def __iter__(self):
        return iter(self.__internal_dict)

    def __len__(self):
        return len(self.__internal_dict)

class Test2(Test):
    def has_key(self):
        raise Exception('Not needed?')

# Looks like an enumerable object
t = Test()
t['a'] = 1
t['b'] = 2

# Looks like a dict
t2 = Test2()
t2['a'] = 1
t2['b'] = 2
```

**Comment by zooba** [comment]
Agreed. We should use the same test as the mapping ABC.
