### ISSUE TITLE
Go to Definition fails on super method calls.

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/PTVS#105]
If I have a method call in my class:

```
super(KingOfTheBubbleGame, self).GUICFG()
```

And select GUICFG and try to Go To Definition, I get a message box which says "Cannot go definition "super(KingOfTheBubbleGame, self).GUICFG"

I would expect it to take me to the parent class or pop-up the find symbols window.

**Comment by zooba** [comment]
Migrated from https://pytools.codeplex.com/workitem/1750

Thanks!

**Comment by huguesv** [comment]
We have a new language service starting in the 15.6 release. If you still see this problem, please open a new issue.
