### ISSUE TITLE
Python 3 assumes source code is encoded with UTF-8

### ISSUE THREAD

**Issue by hajimen** [Microsoft/PTVS#1050]
But PTVS saves with OS's codepage encoding by default. Furthermore, I cannot find any resort to change the default behavior in VS. I don't want to change OS's codepage.
I think the default behavior should save with UTF-8 when the environment is Python 3.

**Comment by zooba** [comment]
Are you using [PTVS 2.2.2](https://github.com/Microsoft/PTVS/releases/tag/v2.2.2) (from about a month ago)? We had a bug around this in an earlier version that was causing issues here.

Also note that Visual Studio will always save a file with the same encoding as it was loaded with, so if there's something in the file indicating the encoding to use, it may be the issue. You can change the encoding through File, Advanced Save Options.
