### ISSUE TITLE
Auto-indent doesn't work in VS 2015 anymore

### ISSUE THREAD

**Issue by jkassies** [Microsoft/PTVS#1051]
I'm experiencing this with VS 2015 Professional - when hitting enter for a new line, the text editor no longer auto-indents.   I just installed VS 2015 and noticed this, having been using VS 2013 successfully.

To try to correct the issue, I installed PTVS 2.2.2 for 2015 from https://github.com/Microsoft/PTVS/releases, but it didnt help.

I am having this issue on 2 different PCs: Windows 10 and Windows 7

To further check if something unique to my PCs is causing this, I installed VS 2015 Update 1 from scratch on a Win 7 VM, but it also has the issue

![image](https://cloud.githubusercontent.com/assets/3199964/12257785/35886fc2-b901-11e5-8322-03957c5ee70b.png)

**Comment by jkassies** [comment]
under 2013

![image](https://cloud.githubusercontent.com/assets/3199964/12257801/67e69124-b901-11e5-8f72-f7c617118371.png)

**Comment by LRPalacios** [comment]
I think the default option for the change editor changed, 

Go to tools -> options -> text editor -> python -> tabs: and set it to smart

![screenshot_34](https://cloud.githubusercontent.com/assets/4844997/12268414/55500f8e-b912-11e5-9aec-740c6993b45a.png)

**Comment by jkassies** [comment]
yep, that's it, thanks

**Comment by zooba** [comment]
And since you were (I assume) signing in to all your VS instances, the setting was being synchronised automatically, which is why it showed up in the new installs. But that does mean you should only need to fix it once and it will be changed everywhere else too.

**Comment by nicodeslandes** [comment]
I had the same issue. Shouldn't the default indenting mode be switched to "Smart", rather than forcing users to go in and manually change this setting themselves?

**Comment by zooba** [comment]
The default indenting mode is Smart, however there is a bug in VS that causes a race-condition that causes the default to be set incorrectly. While annoying, it's not a big enough issue on its own for us to release an update (fixing the setting is just as effective, and easier than downloading an update would be), but it has been fixed for future releases.

**Comment by nicodeslandes** [comment]
Thanks for the update. I was afraid the default mode had been changed somehow.
Glad to hear it's fixed in the future releases!
