### ISSUE TITLE
How can i excute 'manage.py inspectdb' in PTVS?

### ISSUE THREAD

**Issue by BenyT** [Microsoft/PTVS#1055]
How can i excute 'manage.py inspectdb' in PTVS?
Thanks.

**Comment by crwilcox** [comment]
@BenyT 

There is no extra functionality in PTVS for running the manage.py script in django.  We do have a few special commands and they can be found here. 
![image](https://cloud.githubusercontent.com/assets/638797/12331219/79e42998-ba9d-11e5-9745-d6f03eadcc0d.png)

To do what you want though, I would just open a command prompt using the `Open a Command Prompt Here` under the right click menu and execute `python manage.py inspectdb`

![image](https://cloud.githubusercontent.com/assets/638797/12331261/ae115b32-ba9d-11e5-958c-4f4de0a4ef4c.png)

**Comment by BenyT** [comment]
thanks a lot :100: )
