### ISSUE TITLE
Error when Opening Django Shell

### ISSUE THREAD

**Issue by mohamadalkhuzeem** [Microsoft/PTVS#1059]
Python interactive window. Type $help for a list of commands.
An internal error has occurred in the Interactive window.  Please restart Visual Studio.

Here's my System Info:
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA572
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA572
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA572
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.30718.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.30718.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.30718.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

I submitted a comment on another post that was marked as closed. Just opening this issue again in case my comment there would be ignored.

**Comment by huguesv** [comment]
Please try upgrading to this build:
https://github.com/Microsoft/PTVS/releases/tag/v2.2.2

**Comment by zooba** [comment]
Yes, it looks like you've managed to get PTVS 2.2 installed on VS 2015 Update 1, which is not supported. You'll need to update to PTVS 2.2.2.

**Comment by mohamadalkhuzeem** [comment]
Thanks huguesv. That solved it. Thanks also zooba. :)
