### ISSUE TITLE
Unable to Sync db Django

### ISSUE THREAD

**Issue by vladbelo** [Microsoft/PTVS#1063]
I.Right-click the project node and select Python->Django Sync DB. I receive an error:
 Executing manage.py syncdb
Unknown command: 'syncdb'
Type 'manage.py help' for usage.
The Python REPL process has exited

**Comment by zooba** [comment]
Are you using Django 1.9? The command has been removed from that version, and we haven't released an update yet that switches to the new command.

**Comment by vladbelo** [comment]
Correct 1.9.1

**Comment by aarsan** [comment]
any update on this? i was hoping to switch to visual studio for django development but ...

**Comment by zooba** [comment]
Sorry, no updates yet, but we are considering this (and a range of other Django 1.8-1.9 fixes) for a minor update in several weeks. It'll probably only be for VS 2015 users though.

**Comment by zooba** [comment]
Dup of #175

**Comment by carnag3kid7** [comment]
So is the only recourse here reverting to an older version of django?

**Comment by zooba** [comment]
Or you can update to our latest release - [releases](https://github.com/Microsoft/PTVS/releases)

If you are stuck on VS 2013 and can't get 2015 then I'd suggest opening a command prompt and calling the commands directly (`python manage.py migrate` etc.). Alternatively, you could use Django 1.6 or earlier, but I think you're best to be on the latest version.
