### ISSUE TITLE
Autocomplete is not showing aliases to functions

### ISSUE THREAD

**Issue by warpuv** [Microsoft/PTVS#1065]
In this sample zeros() function is not shown as suggestion.
It is an alias defined as `zeros = multiarray.zeros`

```
import numpy as np
image = np.zeros((10, 10))
```

PTVS version 2.2.31124.00
Visual Studio 2015 Update 1

**Comment by zooba** [comment]
This is a known issue - we do not produce great intellisense for native functions, unless they have very precise documentation. We're working on good ways to fix this, which will probably rely on type hint files, though it won't be available for a while.
