### ISSUE TITLE
Editing value of variable of collection type such that it changes number of items crashes VS

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#1069]
```python
xs = [1, 2, 3]
print(xs)
```
Set breakpoint on `print` and run. When it's hit, expand `xs` in Locals, then double-click on its value to edit, and change it to `[1,2,3,4,5]`.

After the edit, children are suddenly collapsed. Attempting to re-expand `xs` will cause VS to crash.

**Comment by int19h** [comment]
This is actually a VS bug, and also happens in RTVS in the same scenario. Added for completeness, and so that other people hitting it can find it in the repo.

**Comment by int19h** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/2288512

**Comment by zooba** [comment]
Marked as fixed on the linked Connect issue.
