### ISSUE TITLE
Can't inspect private variables in debugger

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/PTVS#107]
When the debugger is running I can't inspect, edit, or access private variables.  

I imagine this is because the debugger isn't doing the transform to add '_ClassName' to the variable?  E.g.

```Python
class MyClass:
    def __init__(self):
         self.__private_var = 5
    def public_method(self):
        print 'public method', self.__private_var

obj = MyClass()
# But if you inspect the object, it's not hard to get to
dir(obj)
['_MyClass__private_var', '__doc__', '__init__', '__module__', 'public_method']
```

**Comment by int19h** [comment]
The debugger does, in fact, get the list of member attributes via `dir()`, so we should be definitely picking it up. In fact, I can't seem to be able to repro this with 2.2:

![image](https://cloud.githubusercontent.com/assets/1175142/7548941/0e2e3946-f5d6-11e4-998f-3807be4145f3.png)

![image](https://cloud.githubusercontent.com/assets/1175142/7548939/00cc4dc4-f5d6-11e4-8a24-c80417270d9b.png)

**Comment by hawkerm** [comment]
I guess I'm expecting to use them still like I would in C# and have access to them in the watch and immediate windows without having to mangle the name...

But what probably confused me more was the fact that the variable preview in context doesn't pop-up for them.  For instance in the image, if I hover over the line above the breakpoint.  I can get the tip that public_var is now 5 (had to pin it to get screenshot):

![pythonpublicvar](https://cloud.githubusercontent.com/assets/8959496/7549412/e752b4de-f5e7-11e4-928f-8affdae4cc15.png)

But I can't get that for the __private_var.  I can't drill into it if it represents an object in context with the code:

![pythonintellisense](https://cloud.githubusercontent.com/assets/8959496/7549391/68d2c3a6-f5e7-11e4-9ffe-57267464f747.png)

**Comment by zooba** [comment]
Name mangling is done purely based on the AST and cannot change at runtime, so this should be possible. We probably want to try and detect it on the Python side and alias the name there.
