### ISSUE TITLE
В чом ошыбка???

### ISSUE THREAD

**Issue by loreps** [Microsoft/PTVS#1075]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Your packages may not have been installed.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Закрыть]

[Expanded Information]
System.ArgumentException: Параметр задан неверно. (Исключение из HRESULT: 0x80070057 (E_INVALIDARG))
   в EnvDTE.Commands.Raise(String Guid, Int32 ID, Object& CustomIn, Object& CustomOut)
   в Microsoft.PythonTools.ProjectWizards.InstallRequirementsWizard.ProjectFinishedGenerating(Project project)

**Comment by zooba** [comment]
I assume you are not using English versions of Visual Studio or Windows? We probably need to localize (or avoid) a string somewhere in our templates.

Thanks for the report!

**Comment by zooba** [comment]
Same error as #1986, we'll track on that one.
