### ISSUE TITLE
Package not loading, SetSite Failed

### ISSUE THREAD

**Issue by luigir86** [Microsoft/PTVS#1076]
Hello, 

I have installed Visual Studio Community 2015 on Windows 7 64bit, from the iso file. 

I have installed PTVS too, but at start I receive the error message "The "Python Tools" package didn't load correctly check the log file for more information."

I've checked the log file ( C:\Users\UserName\AppData\ActivityLog.xml ) and I've seen the following lines:

`SetSite failed for package [Python Tools Package][Could not load file or assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.]:{ at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg) at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent) at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit) at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit) at Microsoft.VisualStudio.Shell.Package.RegisterToolboxItemDiscoveryFactories() at Microsoft.VisualStudio.Shell.Package.Initialize() at Microsoft.VisualStudioTools.CommonPackage.Initialize() at Microsoft.PythonTools.PythonToolsPackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)}
`

**Comment by zooba** [comment]
This is likely due to a corrupted VS install. We rely on C# being installed correctly to provide the `Microsoft.VisualStudio.VsInteractiveWindow.dll` file that is being complained about here.

I'd suggest running a Repair install from Programs and Features, first on VS and then on PTVS.
