### ISSUE TITLE
Class View navigation to method leaves method at bottom of editor window

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/PTVS#108]
If I use the Class View window (VS 2013) to navigate to the method, PTVS jumps it so the first line of the method (the declaration) is the last line of the editor window:

![pythonclassviewjump](https://cloud.githubusercontent.com/assets/8959496/7553022/5487dcb8-f68e-11e4-8229-9722c034131e.png)

It seems to always happen if my source file is detached from the main window, but otherwise still occurs quite often.

**Comment by zooba** [comment]
Appears to no longer occur.
