### ISSUE TITLE
Your github release page has a link to download the msi but it has not been uploaded to the storage container

### ISSUE THREAD

**Issue by amarzavery** [Microsoft/PTVS#1082]
https://ptvs.blob.core.windows.net/download/PTVS%20Dev%202016-02-01%20VS%202015.msi
```
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:a479fe9c-0001-0027-6ccf-5e862d000000 Time:2016-02-03T22:10:00.2693765Z
</Message>
</Error>
```

**Comment by amarzavery** [comment]
The latest release: https://github.com/Microsoft/PTVS/releases/tag/dev-2016-02-01

**Comment by zooba** [comment]
Thanks. Fixed now - the upload app I used (not written in Python :( ) swallowed an error and didn't report it.

**Comment by amarzavery** [comment]
You can use the [Azure Storage Explorer](http://storageexplorer.com/) for uploading the MSI. We use the same for azure-xplat-cli :)

**Comment by zooba** [comment]
That's the one that swallowed the error...

**Comment by amarzavery** [comment]
Arghh... This was good to know. I think we should actually click on the test link in the App to make sure the download works.
