### ISSUE TITLE
Completion DB is not up to date

### ISSUE THREAD

**Issue by kr4uzi** [Microsoft/PTVS#1085]
Im using Visual Studio 2015 with python 2.7 64 bit and it always states that "Completion DB is not up to date". But nothing changes when i click the refresh button. Reinstalled python and python tools already but this issue still remains.
i just cannot get the intellisense working with any non-built-in modules.

**Comment by smortaz** [comment]
It can take about an hour for a distro like Anaconda to be analyzed and for IntelliSense to be ready.   If you open an environment you can see the progress bar.   If you work in the repl  IntelliSense should be always available.

**Comment by kr4uzi** [comment]
im using the the official installer from python.org

**Comment by kr4uzi** [comment]
ok i fixed it by adding a custom new environment with the *exact* same settings as the default env already had (which i cannot delete now but thats a different issue)

**Comment by zooba** [comment]
Are you able to share the contents of Tools, Python Tools, Diagnostic Info? You'll need to post in into a [gist](https://gist.github.com) or email to ptvshelp@microsoft.com, but it should include the errors that were blocking you earlier.

**Comment by jwise** [comment]
I've run into this too.  @zooba, would you like me to post here, or send by mail?

**Comment by zooba** [comment]
@jwise Up to you. Making it public may help others in the future, and it keeps the context together better than a separate email, but there may be private info in the file. (If you do email, please please please make it an attachment :) )
