### ISSUE TITLE
Getting unhandled exception details

### ISSUE THREAD

**Issue by joflashstudios** [Microsoft/PTVS#1086]
Hey, I'm using PTVS with Flask, and I'm running into an issue:

When an unhandled exception occurs, Flask spits out a generic 500 error page. The Visual Studio debugger does not break or give any information about the error.

I can set `app.debug = True` - this causes Flask to spit out a detailed error page on unhandled exceptions, but seems to disable Visual Studio debugging entirely - breakpoints are not hit while `app.debug = True`.

Is there a way to get the details of unhandled exceptions and still be able to step through code in Visual Studio?

**Comment by zooba** [comment]
If you open the Exceptions window (under Debug, Windows, Exceptions) you can force breaking on Python exceptions. Then the debugger will break when it occurs.

Alternatively, Flask likely has a setting to enable detailed messages without adding whatever auto-reload or tracing functionality they use with `app.debug`. The [Working with debuggers](http://flask.pocoo.org/docs/0.10/errorhandling/#working-with-debuggers) section of their docs also apply to PTVS, so you'll want to follow that.
