### ISSUE TITLE
Installing and Using PTVS ML 2.2.2

### ISSUE THREAD

**Issue by marabout2015** [Microsoft/PTVS#1089]
I have VS 2015 Enterprise. I downloaded and installed PTVS 2.2.2. I also downloaded PTVS ML 2.2.2, and now want to install and use it. How do I do that?

**Comment by zooba** [comment]
You should be able to double click it and the installer will appear.

If it was renamed to `.zip` then you will need to change it back to `.vsix`. Some browsers will detect the contents and change the name.

**Comment by marabout2015** [comment]
Changing the extension was exactly the solution. Thank you!

Mario

**Comment by zooba** [comment]
Turns out this was probably our fault - the upload had the wrong content type associated with it. It's fixed now, and we'll take care to double check next time.

**Comment by marabout2015** [comment]
Thank you!

Mario
