### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] when creating new virtualenv 

### ISSUE THREAD

**Issue by markrowsoft** [Microsoft/PTVS#1090]
I work in an environment behind an SSL proxy and typically have to run pip with the --trusted-host option in order to install python packages from a particular repository.

I am unsure how to add this option using the 'add virtual environment' feature of PTVS.
For now I will just do it manually.  Is there a work around in settings and therefore this isn't a real issue?

Installs work fine when using the PyPi repository.  I am using  https://api.anaconda.org however.
snippet of error: 

```
  File "C:\Anaconda2\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\Anaconda2\lib\site-packages\pip\_vendor\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed `(_ssl.c:590)```
```

**Comment by zooba** [comment]
No, we don't have any workaround for this (at one point I was experimenting with pulling the command lines from an editable location, but it never landed).

Using "Open Command Prompt" on the project and using pip/virtualenv manually should be fine.

I'll consider this a request to be able to customize those commands.

**Comment by markrowsoft** [comment]
I was able to fix after updating the virtualenv module to 13.0.1-py27_0 using the conda utility instead of pip.  Adding new virtual env's worked afterwards.
