### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.VsInteractiveWindow

### ISSUE THREAD

**Issue by sanyorkeatmstar** [Microsoft/PTVS#1096]
Hi,
      after I install VS professional 2015 update 1 on windows 10, i encountered this problem. I uninstall and re-install several times for PTVS 2.2.2, and that can't solve this problem,
     here i paste the VS log:
  <entry>
    <record>51</record>
    <time>2016/02/11 07:04:49.078</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [Python Tools Package][Could not load file or assembly &apos;Microsoft.VisualStudio.VsInteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.]:{   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)&#x000D;&#x000A;   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)&#x000D;&#x000A;   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly&amp; lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType&amp; attributeType, IRuntimeMethodInfo&amp; ctor, Boolean&amp; ctorHasParameters, Boolean&amp; isVarArg)&#x000D;&#x000A;   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)&#x000D;&#x000A;   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)&#x000D;&#x000A;   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.RegisterToolboxItemDiscoveryFactories()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudioTools.CommonPackage.Initialize()&#x000D;&#x000A;   at Microsoft.PythonTools.PythonToolsPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)}</description>
    <guid>{6DBD7C1E-1F1B-496D-AC7C-C55DAE66C783}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>52</record>
    <time>2016/02/11 07:04:49.078</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [Python Tools Package]</description>
    <guid>{6DBD7C1E-1F1B-496D-AC7C-C55DAE66C783}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by zooba** [comment]
Can you try repairing Visual Studio? The missing assembly is part of C# support, so it should be there, but it may have gone missing in an update.

**Comment by sanyorkeatmstar** [comment]
after I uninstall and clean the VS 2015, then re-install VS 2015, now it works for me.
thanks for you reply.
