### ISSUE TITLE
Cannot install packages with Python UWP 3.5

### ISSUE THREAD

**Issue by FrancoisSavard** [Microsoft/PTVS#1099]
I am trying to import Python library numpy in a Background Application (IOT). Using the Python Environment Window, choosing Python UWP 3.5 and trying to install the python library numpy with pip, I get the following error:

----- Installing 'numpy' -----
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudioTools.Project.ProcessOutput..ctor(Process process, Redirector redirector)
----- Failed to install 'numpy' -----

It works fine for normal Python Application project and I can add libraries to the environment Python 3.5 environment, but not with IOT.

How am I supposed to add libraries in a Python IOT project?

**Comment by zooba** [comment]
So Python UWP is a different platform from Win32, which means most compiled packages need to be rebuilt.

As far as I know, nobody has made a build of `numpy` that will work with UWP yet (and `numpy` is very difficult to build on Windows already), so you may be out of luck.

But the actual issue you're facing here is that we're trying to run UWP Python on regular Windows, which also does not work. I'll rename this issue, as we should add way to work around that so packages can be installed.

**Comment by FrancoisSavard** [comment]
Thank you very much for your fast answer. 

I would very appreciate the workaround to rebuild the packages/libraries so that they can be installed in UWP.

**Comment by zooba** [comment]
Unfortunately, it's less of a workaround and more of a task for someone who knows the project well. There are likely to be a number of changes required to `numpy` to make it build, and it may not even be possible because of their reliance on Fortran code.

But we'll certainly take your request as a vote in favour and suggest the idea next time we meet with the people who are directly involved.

**Comment by zooba** [comment]
@alanch-ms Is this considered fixed now? (Not installing numpy, but installing packages in general)?

I have just made some significant changes that should get into our internal builds this week, but they shouldn't change whether this works or not.

**Comment by alanch-ms** [comment]
I haven't tried numpy, but installing packages should work in general as long as the packages are python-only packages (ie. no .pyd's).  I know VS15 preview 4 came out yesterday.  I plan on installing it today and try installing pip packages for UWP today.
