### ISSUE TITLE
Intellisense extremely slow in mixed mode debugging.

### ISSUE THREAD

**Issue by burhop** [Microsoft/PTVS#11]
When placing the mouse cursor over a variable in a python code window, Visual studio will "lock up" for 10 seconds to couple minutes.  

This is only occurring in mixed mode debugging where I have an application that has loaded python33.dll.  It works fine when not debugging.  It also works fine for pure python coding using the .python exe.  

I originally saw this problem with VS2012 where it would appear to hang (is it related to this ?  https://pytools.codeplex.com/workitem/3015)  Eventually, I figured out it was when I moved the cursor over text so suspected Intellisense.

I installed VS2013 and tired again.  This time, the intellisense window would pop up but only after a very long delay.  All other functions work fine.  I can step though code, see variables in the watch windows, etc.

I don't have access to the core application importing python33.dll but can say it is python 3.3.2 64 bit.  If there is another application out there that uses python33.dll, I could try that to determine if it is my setup our somehow related to my application (suggestions?)

I'm guessing this must have been tested so that there is some configuration out there that can make this work.

**Comment by burhop** [comment]
I installed the BETA of PTVS hoping the problem would have been fixed.  In fact, it got worse.  Now, each time I step to a new line in the debugger, VS locks up for about 30 seconds to a minute.  Before, it was only when I put the cursor over a code.

**Comment by burhop** [comment]
Here is a video that might help:  https://youtu.be/P-vUo0F1jo8

**Comment by int19h** [comment]
Very interesting. Are you seeing this on this particular codebase only, or does it also happen if you e.g. try to mixed-mode debug a simple "Hello world" type console application?

**Comment by burhop** [comment]
Good question... 

I created a simple python script that I ran separately.  I then Attached the VS debugger to python.exe using both "native" and "Python"  This worked fine with tooltips.  I was using python 3.4.0 64bit and had to download the python pdbs to get it to work.

**Comment by burhop** [comment]
I uninstalled 2.2(Beta) and reinstalled 2.1 for VS13.  This at least lets me step through the code without locking up. However, the lag in displaying the tool tip is still there :-(

**Comment by burhop** [comment]
One of our interns took a look at this problem and has a workaround.  However, there is probably a better fix that someone dedicated to the PTVS project can implement.

The problem occurs when obj.GetDebugChildren() returns more than 1000 children. Testing for that and returning avoids the freeze.  Here are his notes:

>Further investigation of the code yielded that PTVS uses two different debugging engines, namely AD7 and DKM (Concord). The Concord engine is used for mixed-mode debugging. 
>Visual studio will freeze during the execution of the following method in >Microsoft.PythonTools.DkmDebugger.ExpressionEvaluator. 
>public List<DkmEvaluationResult> GetChildren(ExpressionEvaluator exprEval, DkmEvaluationResult result, DkmInspectionContext inspectionContext);
>In particular, during the execution of the following loop:
>foreach (var child in obj.GetDebugChildren(reprOptions).Take(MaxDebugChildren)) { … }
>I found out that the problem arises when the obj.GetDebugChildren contains more than 1000 elements. Having a simple test like:
>int childCount = obj.GetDebugChildren(reprOptions).Count();
>if (childCount > 1000) return evalResults;
>prevents VS from freezing. 
>However, the foreach loop will always take a maximum of 1000 elements due to the MaxDebugChildren variable. 
>Maybe there is a way of running the loop in parallel/async (e.g. Parallel.ForEach) to speed things up a little bit? 
>However, further testing showed that setting MaxDebugChildren to e.g. 20 has the same result. I saw that the python function __dict__ will be called on the python object. The python object used to achieve this strange behavior is in an external .pyd file defined. Maybe this is the reason of the problem.

**Comment by int19h** [comment]
This is actually rather surprising, because `GetDebugChildren` is generally implemented as a lazy iterator (i.e. it will produce only as many children as the loop asks for), while on the other hand using `Count()` will force it to be enumerated entirely. Can you give more details about the object/class on which this is happening?
