### ISSUE TITLE
Bugs in  PTVS in visual studio 2015 (for django development)

### ISSUE THREAD

**Issue by yusufmh** [Microsoft/PTVS#1101]
Hello, I'm a loving-VS user and I was really happy when I heard that VS supports python and django but unfortunately I tried to use the simplest things in django development such as ( adding new django app, manage.py tasks and other tasks)--> it prompts me with lots of errors that I couldn't find a solution for.
I hope to debug the app for the newest django version 1.9.2. I'm a newbie to django but I tried a lot and my wanted-commands works on CMD but not on VS2015. 
sorry for my English :) 
thanks in advance

**Comment by zooba** [comment]
I'd suggest trying our [latest dev build](https://github.com/Microsoft/PTVS/releases/tag/dev-2016-02-01), where we've added support for Django 1.9.

Previously we only had support up to Django 1.6, and they made some changes to Django that broke us.

**Comment by yusufmh** [comment]
@zooba Ok, I will try it now. Thanks a lot for doing this software.

**Comment by yusufmh** [comment]
@zooba after downloading the last release, the same problem occurs when adding new django app:
https://www.dropbox.com/s/xkgcwxuteyu93ad/ptvs.png
also, when I run the migrate command, i can't see the createsuperuser task after the migration being done, this output come in the end:
`      The Python REPL process has exited`
I'm trying also to use some manage.py tasks and I couldn't, is there any guide to use it in VS? I don't know why I couldn't do it.
thanks in advance..

**Comment by zooba** [comment]
There may be some other issue popping up here, we'll take a look.

I don't think we added a menu item for `createsuperuser`, but we will. Which other tasks did you need to use?

**Comment by yusufmh** [comment]
@zooba Can't you just make a prompt for taking any command? If you can take a look at pycharm
in `Tools`> `run manage.py task`
it will open a `python manage.py `:
see link for a screenshot
https://www.dropbox.com/s/reoth0v5rkf8o2r/mangpy.png
thanks again

**Comment by zooba** [comment]
Yeah, that's a separate request that we haven't gotten to yet.

It's very easy to add specific commands for Django projects, compared to creating a nice experience for entering arbitrary commands quickly.

**Comment by yusufmh** [comment]
I see, `createsuperuser` is important becuase I can't see after migration in VS.
Thanks a lot.
