### ISSUE TITLE
Can't refresh Completion DB

### ISSUE THREAD

**Issue by odbaev** [Microsoft/PTVS#1102]
The refreshing starts and stops immediatly. The notification always says "Completion DB is not up to date. Click to start refreshing" and InrelliSense tab says "(Standart Library)  (0 modules)".

The autocomplete list always shows "The completion DB needs to be refreshed".

I'm using VS2015 with Update 1, PTVS 2.2.3 and Anaconda 2.5.0 (64-bit) Python 3.5.

**Comment by zooba** [comment]
Can you copy the information from Tools, Python Tools, Diagnostic Info into a [gist](https://gist.github.com) or email to ptvshelp@microsoft.com please? That should include some logs that well help us diagnose what is going wrong.

**Comment by odbaev** [comment]
Here it is [https://gist.github.com/odbaev/de24a1a76e5a22cc659a](url)

**Comment by odbaev** [comment]
The problem was solved by reinstalling Anaconda to C:\Anaconda3.

**Comment by zooba** [comment]
Very strange.

It's possibly related to the non-English character in the previous directory name, but we have tested that before without issue. For some reason the log is empty, which doesn't make any sense either. Maybe it is related to Anaconda.

We will retest this scenario. Thanks for the report, and glad you found a solution.

**Comment by MuhammedAlavi** [comment]
I had the same problem. I tried many solutions but I found one of them effective, that is you must delete your environment and reinstall it.
