### ISSUE TITLE
Add django app failure on dev build 2016-02-01

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1104]
Create new project
Web/Blank Django Web Project
Right-click on project in solution explorer, Add, Django App...
Enter a name
```
---------------------------
Microsoft Visual Studio
---------------------------
The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
---------------------------
OK   
---------------------------
```
Note: if you use Add New Item, Django 1.4 app, then it works

**Comment by zooba** [comment]
Fairly sure I just forgot to add the template into the installer.
