### ISSUE TITLE
any plans to support solutions with C# and Python projects?

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#1106]
This is for IronPython and pythonnet projects. Right now I have to open multiple instances of Visual Studio or python files without project setup. Maybe this even applies to PTVS code base.

Especially since mixed-mode debugging works with C# and Python, when native is enabled.

**Comment by zooba** [comment]
"Support" as in actively test and promote? We have some basic automated tests for IronPython and C# projects in the same solution, but it isn't hugely popular so we don't talk about it much. It should work though.

Or perhaps you mean something different by support? Could you clarify what you would like to be able to do?

**Comment by denfromufa** [comment]
@zooba I think before I had issues, now I see that both python, c++ and ironpython projects can be added to c# project!
