### ISSUE TITLE
[Feature Request] Support Python 3.5 for IIS

### ISSUE THREAD

**Issue by Korijn** [Microsoft/PTVS#1107]
The steps on [this page](https://azure.microsoft.com/en-us/documentation/articles/web-sites-python-configure/) don't apply to Python 3.5, apparently, because the subpackage [wfastcgi](https://pypi.python.org/pypi/wfastcgi) is incompatible.

Can this be fixed, or can you explain what the problem is so that someone else might contribute a fix?

**Comment by zooba** [comment]
`wfastcgi` should work fine with Python 3.5 - we just haven't posted an update to it since Python 3.5 released and so the classifiers haven't been updated.

Are you encountering actual problems trying to use it?

**Comment by gschizas** [comment]
The problem is that the default installation folder for Python 3.5 is in `Program Files`. wfastcgi.enable() doesn't properly quote the arguments (which have spaces)

I've fixed it on my PC, I'll be doing a pull request soon.

**Comment by Korijn** [comment]
Is this a priority yet?

**Comment by gschizas** [comment]
It has been live, on production, for some time now.

**Comment by Korijn** [comment]
Awesome. Where do you blog about these things?

**Comment by gschizas** [comment]
I rarely blog :)

**Comment by zooba** [comment]
Yeah, sorry, it was fixed but we didn't make any major announcement. At the very least I should have posted a comment here and closed the issue - I'll try to be better at that next time.

**Comment by Korijn** [comment]
No worries. Thanks!
