### ISSUE TITLE
Not possible to collapse single line functions in the editor

### ISSUE THREAD

**Issue by matt77hias** [Microsoft/PTVS#1108]
It is not possible to collapse single line functions in the editor.

Example:

**Could not be collapsed** (no _minus _marker appears)
```
def f(*args, **kwargs):
    pass
```

**Could be collapsed** (_minus _marker appears)
```
def f(*args, **kwargs):
    # deliberate empty line
    pass
```

Is this a design decision or a bug?

System: Visual Studio 2015 Community Edition and corresponding PTVS

**Comment by zooba** [comment]
It's a design decision. The amount of space saved is minimal, and we are aware that having too many markers on the left-hand side can be confusing. (Bear in mind that we use the same rule for all compound statements, so once you factor in all the single-line `if`, `elif`, `else`, `for`, `while`, `with`, `try`, `except`, `finally` blocks too you can easily get a marker on every second line.)

That said, if you have a reason to change that we're certainly open to reconsidering the design. But if you're just checking whether it's a bug, then thanks, but it's deliberate.

**Comment by matt77hias** [comment]
Ok thanks, it was just for checking. (Since I migrated from Canopy IDE, I would already be happy with very minimal collapsing support.)
