### ISSUE TITLE
Unit test not discovered when inheriting unittest.TestCase based class from outside of current directory

### ISSUE THREAD

**Issue by graemecoates** [Microsoft/PTVS#1113]
I've got a series of tests written within PTVS that have a structure like this from the python project root :

    PythonProject
              |-lib ----------
              |              |-__init__.py
              |              |-Base_Test_Case.py
              |-test_cases_1 ---
              |              |-testcase.py
              |-test_cases_2 ---
    etc...    |

within Base_Test_Case.py, I define a base test class as follows to allow the same setUp / tearDown to be inherited by all test cases:

    class BaseTestCase(unittest.TestCase):
    
        def setUp(self):
            #dosomething
        
        def tearDown(self):
            #dosomethingelse

and then in the test itself, testcase.py, I setup the test class as follows:

    from lib.Base_Test_Case import BaseTestCase
    class testClass(BaseTestCase):
        def test_A(self):
            #dothetest

(I have a search path "." setup to allow lib to be found by the test module (or I can add "lib" into the serach path and reference BaseTestCase directly)). As it is, the tests don't get picked up by the Test Explorer in VS (though they will run successfully). If I copy BaseTestCase.py into the same folder as the test case and reference that module, the tests are picked up straight away in the Test Explorer. 

This seems wrong - I'd like to inherit one version of the BaseTestCase file, rather than having one copy in each of the test sub-modules. What's the expected behaviour here - should the tests be discovered in this way?

**Comment by zooba** [comment]
We may not be flowing through the search path correctly when discovering tests.
