### ISSUE TITLE
Auto indent default is block

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1117]
PTVS 3.0
CPython 3.4

I am using a pre-installed image with PTVS 3.0, and the default indentation was set to Block rather than Smart.  I am 99% sure I didn't change it myself.  I checked that C# default was set to Smart.

Block indenting gives you this:

```
def hello():
print('hello')
```

**Comment by zooba** [comment]
Not sure that this is our fault, but it is certainly the case.

**Comment by zooba** [comment]
Same issue can also exist on Update 1. There seems to be some sort of race condition on initial install - we're investigating with a few of the VS devs.

**Comment by zooba** [comment]
Currently exists in both branches, but will go away from 3.x with #732 (which will remove the autoload completely).

I'll add a fix into the 2.x branch in case we do another release out of there.

**Comment by huguesv** [comment]
I installed Dev 15 Preview 5 and default was still block indent.

**Comment by huguesv** [comment]
It's smart indent on the latest VS 2017 build!

**Comment by int19h** [comment]
It was set to "Block" for me for a new clean install:
![image](https://cloud.githubusercontent.com/assets/1175142/20849953/db8762de-b88d-11e6-8a10-fb2b75b55118.png)

**Comment by int19h** [comment]
This is with DS profile. RTVS smart indent is also inappropriately set to "Block".

**Comment by zooba** [comment]
Given this does not repro with Python on its own, I'm inclined to suggest that RTVS is loading the text manager during initialization, which is what we've already fixed.
