### ISSUE TITLE
Using "Start" from contextual menu in "Web Launcher" mode gives weird message

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1120]
Hi,

I have Web project and I tried to launch a file using "Start without Debugging" (same with "Start with Debugging")

I got this cryptic message:
![2016-02-25](https://cloud.githubusercontent.com/assets/1050156/13338599/6649f0ce-dbd7-11e5-90df-3e2874e206e7.png)

If these options are not available in "Web Launcher" mode, they should be disabled. Otherwise, maybe just do "python {file}"?

VS 2015 PTVS 2.2.31124.0

**Comment by zooba** [comment]
Was this a generic web project with no framework configured?

**Comment by lmazuel** [comment]
Yes, the AzureResourceViewer project here:
https://github.com/Azure/azure-sdk-for-python/tree/master/examples/AzureResourceViewer

**Comment by zooba** [comment]
Did you recreate the virtual environment it expects?

**Comment by lmazuel** [comment]
Yes, actually If I "Open Command Prompt here" from the virtual env and type

> python myfile.py

It works

**Comment by zooba** [comment]
This now works - I suspect it was fixed when I rewrote these commands.
