### ISSUE TITLE
ptvsd auto reconnect

### ISSUE THREAD

**Issue by brizjin** [Microsoft/PTVS#1124]
Hello!
I try to debbug my python app in docker contener. I connect to it by using ptvsd at VS. But after each restart or modification i need to restart docker app, then open Attach to proccess dialog, then each time write ptvsd connection string (some why it doesn't save at connections list), then find the process, then connect, and after all become debuggin. From this I have a question: Is this possible to make VS auto-wait my docker app to become started and after app "wait attach" it automaticaly connect to debug? Because it annoying after each restart app make this list of actions to make debuggin work. It have to be work as easy as regular debuggin work: we are just clicking Debug run button and debuggin is start. Is that possible to make Remote ptvsd debugging, may be after same configuration, to work by one button click? Thank you!

**Comment by zooba** [comment]
It's not currently possible, and we don't have any control over the existing Attach dialog (otherwise we would have made it save already :) ), but we could certainly add our own way of doing this.

We should probably make this a debug launcher so that it ties into F5 (i.e. press F5 and it waits to attach to a certain endpoint).

**Comment by M0sc** [comment]
Possible solution to automate attach to process repetitive action by using macro:
```
Imports System
Imports EnvDTE
Imports EnvDTE80

Public Module PythonTools
    Sub AttachToProcess(Optional ByVal strArguments As String = "")
        Dim strarrArguments As String()
        Dim strTransportQualifier As String, strProcessName As String
        Dim dbg As EnvDTE80.Debugger2

        strarrArguments = strArguments.Split(Nothing, 2)

        If strarrArguments.Length > 0 Then
            strTransportQualifier = strarrArguments(0)

            If strarrArguments.Length = 2 Then
                strProcessName = strarrArguments(1)
            End If
        End If

        If strTransportQualifier = "" Then
            strTransportQualifier = "tcp://localhost"
        End If

        If strProcessName Is Nothing Then
            strProcessName = ""
        End If

        dbg = DTE.Debugger

        Try
            dbg.GetProcesses(dbg.Transports.Item("Python remote debugging"), strTransportQualifier).Item(strProcessName).Attach()
        Catch
        End Try
    End Sub
End Module
```
One can run this macro from the Command window of IDE:

`>Macros.MyMacros.PythonTools.AttachToProcess tcp://secret@192.168.0.1:1234 PythonApp`

or just

`>Macros.MyMacros.PythonTools.AttachToProcess`

to attach to the first process with default transport qualifier (tcp://localhost:5678).

Surely one can extend PythonTools Module with additional macro code to start local or remote process.
:wink:

**Comment by huguesv** [comment]
There should now be a reattach command that appears in the debug menu after you've attached once.
