### ISSUE TITLE
holographic apps in python?

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#1125]
https://dev.windows.com/en-us/holographic/using_visual_studio

**Comment by zooba** [comment]
Would be awesome! Personally, I think the best way is going to be via Unity - maybe that's already possible?

**Comment by denfromufa** [comment]
If hololens is using Windows IoT, then porting micropython also seems
viable approach. uPy runs on very diverse set of IoT already but did not run
successfully on uPy last time uPy team tried it.

However this is completely unknown territory for me, so I may be discussing
very unrealistic things.
