### ISSUE TITLE
'We didn't find any interpreters' page downloads 3.4.3 Python

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/PTVS#1137]
VS 2015 - link http://go.microsoft.com/fwlink/?LinkId=299430
![image](https://cloud.githubusercontent.com/assets/638797/13680440/6847e8c8-e6ad-11e5-8e50-dd27247bd4f5.png)

**Comment by zooba** [comment]
Updated to point at 3.4.4, which is compatible with what runs on Azure Web Apps. Encouraging 3.5 through here is currently problematic because it will lead people down a path where they can't deploy and it won't be obvious why.

**Comment by zooba** [comment]
Pulling the trigger and making this 3.6. People deploying to Azure through VS 2015 are not going to have a fun time right now anyway...

**Comment by zooba** [comment]
Fixed. Now points to 3.6.0 x86 web installer
