### ISSUE TITLE
Editable variables in Django stack frames

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#1143]
When on a breakpoint in a Django template, variables that are displayed in Locals can be edited, but committing the changes doesn't work - the variable just reverts to its original values.

Ideally, this should just work. Alternatively, if all these variables cannot be edited, then Locals shouldn't allow to edit them (i.e. set the read-only flag on `IDebugProperty2`).

**Comment by huguesv** [comment]
should be retested, unsure if this is any better in ptvsd 4.x

**Comment by huguesv** [comment]
@karthiknadig tested it, definitely not fixed
