### ISSUE TITLE
Django Web Project template 'app' is missing migrations package

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1146]
When you add a new Django app, it includes a `migrations/__init__.py` with it, but the 'app' that is present with the new project template doesn't have it.

**Comment by chrisgd56** [comment]
All corrected:  Ref: Django Web Project template 'app' is missing migrations package #1146 < regarding this issue.  My MVA Django does not work, either.  I see the great guidance for adding in that reference, but where are those files to be edited.  This for VS 2015 and Python Tools for VS.   Thx!
