### ISSUE TITLE
Publish django project to azure web app makes VS unresponsive

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1148]
VS 2015 Update 2

Create new Django Web Project
Set STATIC_ROOT as needed
Fix db.sqlite3 as needed (migrate)
Publish to Azure Web App

Status bar says Publish started...
Progress bar on the status bar appears to be at 100%
VS not responding for several minutes
I have changed by msbuild output mode to diagnostics - that may be making it worse?

**Comment by zooba** [comment]
> I have changed by msbuild output mode to diagnostics - that may be making it worse?

Almost certainly. What does your CPU usage look like? Which processes are working hard?

**Comment by huguesv** [comment]
It may be an isolated case of Azure misbehaving.  It eventually came back to life and I got this.  I would feel better if someone reported that this actually works for them.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Web deployment task failed. (Could not complete the request to remote agent URL 'https://huguesdjango3.scm.azurewebsites.net/msdeploy.axd?site=huguesdjango3'.)

Could not complete the request to remote agent URL 'https://huguesdjango3.scm.azurewebsites.net/msdeploy.axd?site=huguesdjango3'.
The operation has timed out	DjangoWebProject3	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.Publishing.targets	4276	

```

**Comment by huguesv** [comment]
I just tried again and it worked!  Closing.
