### ISSUE TITLE
Instructions for Using Python tools Intellisense with a Custom DLL

### ISSUE THREAD

**Issue by WXNeil** [Microsoft/PTVS#1149]
Does anyone have tested instructions for how to Using Python tools Intellisense with a Custom written DLL.

It seems to be unclear and any help would be appreciated.

I am using VS 2013 and VS2015

**Comment by zooba** [comment]
Are you using IronPython and a .NET DLL? Or CPython and a native DLL/pyd?

**Comment by WXNeil** [comment]
IronPython and a .Net DLL

**Comment by zooba** [comment]
Have you seen [this page](https://github.com/Microsoft/PTVS/wiki/Projects#net-projects) on our wiki? There's a section for .NET Projects that also applies to DLLs.

**Comment by WXNeil** [comment]
Yes I have looked at it. Interesting I cannot get intellisense working with my dll in the VSE but I do get it working in the IronPython 2.7 interactive window.  Would you have any clues why this would be?

**Comment by zooba** [comment]
Because we actually execute code in the interactive window, while in the editor we try and avoid running arbitrary code.

For the editor you need both the `clr.AddReference` call (or equivalent) _and_ to add the DLL as a Reference. In the interactive window, you need `clr.AddReference` and search paths to be correct. It's a slightly annoying difference, but we haven't had a chance to straighten it out yet.

**Comment by WXNeil** [comment]
in the editor I tried  clr.AddReference  and clr.AddReferenceToFile.  Still won't work in the editor.  Can you give me some dll that you have (non MS) that works and you can try it there and I can try it here. It would be great to get the intellisense working in the editor:)

I saw people write about adding it to the GAC but I would rather make it simple.  Appreciate anything you can do.

**Comment by zooba** [comment]
Did you right-click References in Solution Explorer and add the DLL there?

**Comment by WXNeil** [comment]
Yes I did right-click References in Solution Explorer and add the DLL there

**Comment by andygraham** [comment]
I can see my custom dlls in Intellisense with IronPython. I added the dll as a reference and also seemed to need to add the path to it under search paths. In my case a relative path of "." sufficed as the dll is in the project folder with the IronPython source.

**Comment by zooba** [comment]
I just checked and the search path is not necessary for getting IntelliSense, so possibly your DLL is failing to load.

Does it have any dependencies? Are they either in the GAC or in the same directory as the DLL?

**Comment by WXNeil** [comment]
The only dependencies would be .Microsoft.Net dlls which I would expect to be in the GAC already.

**Comment by zooba** [comment]
Okay, maybe we need to step back a bit.

What does it look like when you don't have Intellisense? Are your namespaces available after you type `import`? Do you see namespaces but no classes in `from <my namespace> import ...`? What are you expecting to see that you aren't seeing?

**Comment by WXNeil** [comment]
Namespaces are not available after typing import

After I addreferencetofile and import myclassname

And Afteni type m = myclassname

I should be able to type m.  And get a list of functions showing

It works this way when I am in the interactive window




Sent from my iPhone

On Mar 11, 2016, at 3:55 PM, Steve Dower <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, maybe we need to step back a bit.

What does it look like when you don't have Intellisense? Are your namespaces available after you type import? Do you see namespaces but no classes in from <my namespace> import ...? What are you expecting to see that you aren't seeing?

-
Reply to this email directly or view it on GitHub<https://github.com/Microsoft/PTVS/issues/1149#issuecomment-195547257>.

________________________________
This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.

**Comment by zooba** [comment]
It's starting to seem like there's something about your DLL that we aren't handling well, or it may be a change in IronPython 2.7.5 that we haven't adapted for.

Are you able to share the outline of your code? Like, strip out all the contents of the functions but show what the namespaces and classes and function definitions look like? You can email privately to ptvshelp@microsoft.com if you don't want to put anything up publicly.

**Comment by WXNeil** [comment]
Thanks for your response.  It appears that any of the custom DLL's will not show up in Intellisense but as I said before they show up in both the interactive mode and in the object browser. Is it possible that you can send me a project that you know works with a custom DLL included (even "hello world").  I have tried several custom dlls and after doing a 

clr.AddReferenceToFile("My.dll')
import myclass

After hovering over myclass it will say
myclass : <unknown type>
unable to resolve "myclass". Intellisense may be unavailable for this module.

I have the dll added to references and a search path added to it

Again if you can send me some dll that you know works and it does not work here that would seem to suggest that it has to do with my dlls

Thanks

**Comment by andygraham** [comment]
[IronPy.zip](https://github.com/Microsoft/PTVS/files/172033/IronPy.zip)
Attached is a subset of my larger project. Note that ironpydebug.py is edited in the VS IDE but run by invoking IronPy.exe in the ironpydebug folder. there is just enough of the standard library in the Lib folder to let it start. Intellisense works fine for the IronPy.exe assembly which holds custom Windows Forms Forms. zoobaboce was correct, I only needed to a reference to the assembly, the search path was not needed (though there was a comment in my source that I had found it was needed at some time in past).

**Comment by zooba** [comment]
@WXNeil You keep using `import myclass` in your examples, but you probably need to import your _namespace_ and then dot through to access the class.

Unless you have `namespace myclass` at the top of your file, but even then you won't see functions after typing `myclass.` - you can only write classes within a namespace in .NET.

**Comment by WXNeil** [comment]
oops, I wrote that incorrectly
what I meant to write was

clr.AddReferenceToFile("Mydll.dll')
 import mydll

After hovering over myDll it will say
 myDll : 
 unable to resolve "myDll". Intellisense may be unavailable for this module.

I have the dll added to references and a search path added to it

Again if you can send me some dll that you know works and it does not work here that would seem to suggest that it has to do with my dlls

Thanks

**Comment by zooba** [comment]
Try using `Microsoft.PythonTools.ProjectWizards.dll` from your [install directory](https://github.com/Microsoft/PTVS/wiki/Where-is-PTVS-installed):

```python
import clr
clr.AddReference("Microsoft.PythonTools.ProjectWizards")
from Microsoft.PythonTools.ProjectWizards import InstallRequirementsWizard
```

**Comment by andygraham** [comment]
Don't put the extension on the Assembly name. When I do it breaks Intellisense. Also as Zooba says it's a top namespace you import. If you look in my sample project I posted above you will see

clr.AddReference('IronPy')  # Assembly IronPy.exe named without the extension
 ...
from IronDebug import *  # Required name space within the Assembly

I have several namespaces in the assembly and you have to import each one you want individually. When imported a .NET namespace becomes an IronPython module.

**Comment by WXNeil** [comment]
I believe I am on to something. I have several dlls that I tried. Some have namespaces and intellisense works great!  Some were built **without** namespaces and intellisense will not work.  Is it possible to get them to work if they were created without namespaces?

Thanks

**Comment by zooba** [comment]
That's probably the issue. IronPython may support DLLs without namespaces, but I don't think we do anything for that as it's a very unusual situation to end up in.

When I get a chance to check it out I'll do so, but any fixes here won't be available until our next major release. I'd strongly recommend using a namespace in your DLL - even if it's the same as the assembly name.

**Comment by WXNeil** [comment]
Thanks so much for your help!  Some of the assemblies were old and did not have the namespace. That was definitely the problem.  It is soooooooooooo much easier using PyTools when writing iron python scripts.
