### ISSUE TITLE
IntelliSense for Django models is not aware of all expected attributes.

### ISSUE THREAD

**Issue by RussBaz** [Microsoft/PTVS#1153]
It seems like IntelliSense does not know about a default model manager - 'objects', and it is not aware of model exceptions such as 'DoesNotExist'.

**Comment by caligula1989** [comment]
It's not even aware of things like the model attributes, or anything to do with django models, really.

**Comment by volkit** [comment]
I've got the same problem, see screenshots. In runtime, the methods work like they should, no problems.

Diagnostic info: https://gist.github.com/volkit/a9db61f7f506c480026f89b734f8e68f


![1](https://cloud.githubusercontent.com/assets/22052934/22423143/688fc834-e6f0-11e6-87da-0799abc84246.PNG)
![2](https://cloud.githubusercontent.com/assets/22052934/22423142/688bbc94-e6f0-11e6-8053-ac47fffbcc20.PNG)






Any ideas?

**Comment by zooba** [comment]
Belongs to #3046
