### ISSUE TITLE
Start debugging django project without launching browser?

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/PTVS#116]
Migrated: https://pytools.codeplex.com/workitem/2627

I've setup a django project. After clicking Start Debugging it launches a new tab in my browser. This is really annoying, most of the time I already have a browser tab open to the page I'm debugging. Is there a way to start debugging without launching the browser? 

I'm using Pytools 2.1 RC, Python 2.7, Django 1.6, Windows 7 Pro 64 bit. 

Thanks. 

https://pytools.codeplex.com/discussions/561900 

 We should copy the "Start web browser on launch" checkbox that we have in NTVS.

**Comment by crwilcox** [comment]
We have a similar option in Node.js Tools for Visual Studio that we can use for reference.

**Comment by zooba** [comment]
This can be done by clearing the launch URL in project properties.
