### ISSUE TITLE
Remote interpreter on CE ?

### ISSUE THREAD

**Issue by jvidin** [Microsoft/PTVS#1165]
Is it possible to run/debug code on a remote interpreter using Comunity Edition ? If so any documentation available.

**Comment by DinoV** [comment]
Fir just debugging instructions are here: https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging

They say they're cross platform but they should work with Windows as well.  There's no built in way to start remotely when you press F5 though.
________________________________

**Comment by jvidin** [comment]
Thanks @DinoV , im really looking for the feature of running code on a remote interpreter similar to Pycharm Professional edition - https://www.jetbrains.com/help/pycharm/5.0/configuring-remote-python-interpreters.html?origin=old_help#d26878e117
