### ISSUE TITLE
pip always make vs2015 unresponsive

### ISSUE THREAD

**Issue by reaCodes** [Microsoft/PTVS#1172]
When I use pip to install modules ,vs2015 will be always unresponsive.

Thers is another problem. Using pip I can't install some modules.

For example, 

----- Installing 'Scrapy' -----
Collecting Scrapy
  Could not fetch URL https://pypi.python.org/simple/scrapy/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement Scrapy (from versions: )
No matching distribution found for Scrapy
----- Failed to install 'Scrapy' -----

**Comment by zooba** [comment]
Thanks for the example.

Firstly, are you using pip from the Python Environments window? Or are you right-clicking the environment in your project and choosing "Install Python package"? They should do the same thing, but as it is affecting the UI, it will matter to us which way you are doing it.

For the SSL issue, this probably means that you need to upgrade Python - which version are you currently using? Alternatively, you may have a special "openssl" or "cryptography" package installed that is out of date. Can you try opening a command prompt for your environment and running `pip install scrapy` directly to see if the error is the same?

**Comment by reaCodes** [comment]
Yes, when install VS2015, I check install PTVS .

I run `pip install scrapy` in command, the Error is same.

**Comment by zooba** [comment]
What do you see if you run `python -V`?
