### ISSUE TITLE
Strengthen interpreter checks for Azure Publishing to Web App

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/PTVS#118]
If you try to use PyPy, which is version 2.7, publish won't throw an error currently but this is not a supported interpreter on Azure Web Apps. 

 CPython 2.7 and 3.4 are supported. 

 We should strengthen this error check so we get the following: 
 env (PyPy) is not supported on Web Sites. Please select Python 2.7 or 3.4.

**Comment by zooba** [comment]
This functionality is completely gone, so the bug doesn't matter anymore.
