### ISSUE TITLE
Intellisense not working well on pyd module references

### ISSUE THREAD

**Issue by emonette123** [Microsoft/PTVS#1181]
I do have a directory structure using .pyd modules as suggested on http://www.boost.org/doc/libs/master/libs/python/doc/html/tutorial/tutorial/techniques.html.  Mainly, each module subdirectory is using the `__init__.py` file to inject the content of the pyd module in the current namespace.

Directory structure looks like that:

```
root
|
|___ a
|       __init__.py
|      _a.pyd
|
|___b
|      __init__.py
|     _b.pyd
__init__.py
_root.pyd
```

and so on.  Each `__init__.py` does this:  `from root._a import *`

Adding a reference to the pyd files, I am sometimes able to get intellisense to work correctly on the root module and the a, b, ... module (there are many more).  But sometimes, I will loose the Intellisense on the root module after adding references to _b.pyd.  In all cases, if I save my solution with intellisense kinda working, close the solution and open it anew, intellisense is no longer working at all.  Trying to add references to the pyd modules will usually crash Visual Studio.

I am using VS 2013 with PTVS 2.2.2.

**Comment by zooba** [comment]
(I added some `backticks` to your issue to make it easier to read.)

I have a feeling we don't actually handle this case very well, where `.pyd` files are inside another package. We just assume that `.pyd` files are top-level modules. This is obviously incorrect, but it's how the support was originally implemented and we haven't fixed it yet. Moving your `.pyd` files to the top of the project will help, but I wouldn't want to mess up your project just to work around our issue. 

Adding `.py` files with the interface should work though (e.g. you have `_a.py` alongside `_a.pyd`). We will use the `.py` file, but Python will use the `.pyd` file. This is obviously a lot of extra work, but it's possible you have an easy way to produce the `.py` files, so I wanted to suggest it anyway.

The crash is concerning - could you post the contents of Tools, Diagnostic Info into a [gist](https://gist.github.com) or email it to ptvshelp@microsoft.com? It should include details about the crash that will help us figure out what's broken.

**Comment by emonette123** [comment]
I just dig into this a bit deeper.  It doesn't work even if I have top level pyd.  I moved all of the pyd in the same directory and kept the original directory structure as is.  Both directories are in the Search Paths.  If I add a reference to _root.pyd, the word completion for root.something will work, starting from a blank python project.  If I add a reference to _a.pyd, Word completion for root.a.something might or might not work.  Sometimes it does, sometimes no.  

No matter what, if I close the solution and reopen it, the word completion for root.something no longer works.  The only way to make it work again is to somehow trigger the Add References code.  If the window when adding references pops up, word completion comes back.

I just figured out why the root.a.something completion will not work.  I simplified my problem, but in reality, there is a custom site loader for the .pyd files (I did not write that library, I have to somehow manage to use it in PTVS).  So, I do not think the scraper finds the module in the __init__.py of the a directory.  The library builder packaged it that way:  libroot has a libroot.pyd file.  libroot.moduleA has a libroot_moduleA.pyd file.  libroot.moduleB is in libroot_moduleB.pyd, and so on.  And all the .pyd files are in the same directory, containing a custom loader to be able to convert the libroot.moduleA module to its libroot_moduleA.pyd file.  Everything works fine in the interpreter, but since intellisense is using a scraper, I doubt it is smart enough to figure out the __init__.py file in the a subdirectory:  from libroot.moduleA import *.

Writing this, I found a promising solution to deal with that definitively weirdly packaged library:  use from libroot_moduleA import * to inject the A module in the correctly packaged directory structure.  It looks like it could work.

I would not worry too much about the crash, I had some very non kosher dependencies when I was testing.

I do still have the problem of intellisense not working when loading an existing solution with pyd references in it.  I have to trigger the Add Reference code to wake up intellisense.  I will dig in the python code to see what line wakes up the intellisense.

**Comment by emonette123** [comment]
Ok, I am a bit further.  I am able to add the references to my pyd module if and only if I add them 2 by 2.  The first one gets added, the second one gets removed!  So if I select `libroot_moduleA.pyd` along with `libroot_moduleB.pyd` when adding a reference, I get intellisense for module A.  If I add `libroot_moduleB.pyd` and `libroot_moduleC.pyd` I get intellisense for both modules A and B.  If I select anew `libroot_moduleA.pyd` along with `libroot_moduleB.pyd`, I loose intellisense on module B.

And if I close the solution and load it back, I loose all intellisense on these modules.  I have to add reference by pairs all again.

**Comment by emonette123** [comment]
There is nothing in the ExtensionScraper.py module which could explain waking up intellisense.  The problem must be on the C# code of PTVS itself.

By the way, when adding references to pyd modules, they no longer appear in the Solution navigator under References.  I remember seeing them using Visual Studio 2012 and PTVS 2.1...  Is this a normal behavior for PTVS 2.2 and VS 2013?

**Comment by zooba** [comment]
It sounds like #810 again, but that was fixed in PTVS 2.2.2, so you should be fine if you're on our latest version.

Not appearing in Solution Explorer is a problem... do they appear anywhere when you add them? Or are they just disappearing? Can you send a screenshot after you've added some items?

**Comment by emonette123** [comment]
I am using the latest version of PTVS which I downloaded last week...

**Comment by emonette123** [comment]
Well, I am clueless:  adding references to the project now works fine and the references are also persisted when closing and reloading the solution...  I am still using the same version of VS 2013.  Probably some reboot helped; go figure!

**Comment by zooba** [comment]
That bothers me - I don't like it when bugs magically disappear :)

Did anything change at all? Same project? Same filenames?
