### ISSUE TITLE
configuration switch

### ISSUE THREAD

**Issue by wpalfi** [Microsoft/PTVS#1188]
I know python projects are platform and configuration independent.

But I have a python project with a reference to a c++ (pyd) project. For the import statement it would be convenient to know the current solution configuration:

```
if [configuration]=="Debug":
    import mypyd_d as mypyd
else:
    import mypyd as mypyd
```

**Comment by wpalfi** [comment]
by the way: I noticed that in the pyproj file there is a section

```
<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
    <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
</PropertyGroup>
```
but in VS there is no way to create or edit platforms/configurations for python projects, there are only some grayed-out boxes on top of the properties window.

**Comment by zooba** [comment]
We still have #86 open for supporting project configurations properly, but I don't think you actually need or want that here.

The `_d` suffix on a module name means it has been built against a debug build of Python. If you do this, it will only work against the debug build of Python, and the `_d` suffix is added automatically. If you've installed the debug binaries for Python 3.5 (the only version that lets you do this) or have built them yourself, you don't need the switch on import.

If you _do_ need the switch, it means you've got incompatible settings between your interpreter and your module. There's a video in the playlist at http://aka.ms/PTVSTutorial where I create a native module and configure the properties to get a Debug extension module against a Release interpreter. I'd suggest copying those settings (I used 3.4 in the video, but the same applies for all versions, along with the caveat that unless you're also setting the platform toolset to build using the right compiler, you'll risk other compatibility issues.)

**Comment by wpalfi** [comment]
No, I don't build against a debug build of Python. I'm using boost.python which by default uses the release build of python even for debug builds. Maybe I should not use _d if that is reserved for debug python builds.

Let me tell you why I added the _d suffix to my C++ project:
In my python project I added a reference to the C++ project. But there is an exclamation mark icon on the reference and I am not able to import the module in my python project, I don't know why. So I added file references to the debug and release versions of the pyd. But that only works if I have different names for debug and release build.

**Comment by zooba** [comment]
Hard to say why the reference was showing up as missing - I'm assuming that building the solution didn't fix it? Normally that's all it takes.

Even with the release builds of Python (possibly _only_ with the release builds), and without any proper configuration support in Python projects, switching the configuration between Debug and Release will affect the C++ project and the reference, so there shouldn't be any need for different import code.

Are you able to share your project (by emailing a link to ptvshelp@microsoft.com) or a stripped down version that has just enough code to show the issue?

**Comment by weltkante** [comment]
> Even with the release builds of Python (possibly only with the release builds), and without any proper configuration support in Python projects, switching the configuration between Debug and Release will affect the C++ project and the reference

It doesn't do that for me, VS (2015) puts both Debug and Release folders of the win32 dll project into the `sys.path`:
> ['C:\\projects\\PythonApplication1\\PythonApplication1', 'C:\\projects\\PythonApplication1\\Debug', 'C:\\projects\\PythonApplication1\\Release', 'C:\\Program Files (x86)\\Python35\\python35.zip', 'C:\\Program Files (x86)\\Python35\\DLLs', 'C:\\Program Files (x86)\\Python35\\lib', 'C:\\Program Files (x86)\\Python35', 'C:\\Program Files (x86)\\Python35\\lib\\site-packages']

This way, regardless of what I chose in the VS configuration dropdown, it always loads the debug build of my extension.

Am I missing something?

**Comment by zooba** [comment]
@weltkante Yeah, that's probably a bug. For VS 2017 we've completely revamped how project references and search paths interact, so it should be much better here (e.g. changing the solution configuration updates the search path immediately, which starts updating Intellisense immediately, etc.).

I'm actually quite proud of how much nicer it is :) Now I just need to fix the new compiler issues VS 2017 is introducing... *grumble grumble*

**Comment by zooba** [comment]
Closing because the fix is in VS 2017.
