### ISSUE TITLE
Test Explorer fails to run tests from linked files

### ISSUE THREAD

**Issue by wpalfi** [Microsoft/PTVS#1189]
The Test Explorer shows tests of all modules in the project, even if the module is a linked file or a file in a subfolder. But it fails to run the tests when the file is not in the project root dir:

```
Test Name:	test_B
Test Outcome:	Failed
Result StandardError:	
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 70, in <module>
    main()
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 61, in main
    __import__(opts.module)
ImportError: No module named 'test1'
```

We are using CMake-generated projects, so the source files are always "linked".

(VS2015/Update 1, PTVS 2.2.31124.00)

**Comment by wpalfi** [comment]
found similar issue #840 Running tests from UI does not support module structure without package

**Comment by wpalfi** [comment]
As a workaround I set <ProjectHome> to the folder with the py-files. Of course that does not work if you have multiple source folders. 

I also had to modify visualstudio_py_testlauncher.py (see #1197).

**Comment by zooba** [comment]
Setting the working directory (through Project Properties, Debug) is probably easier and should have the same effect for tests.

Issue #840 is the same issue as this, so we'll track it there.
