### ISSUE TITLE
Changes to values in Debug Interactive not reflected on Autos or Locals window

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/PTVS#119]
I have a value 'guess' that I alter in the Debug Interactive Window. It is changed, but this change is not reflected in the locals, autos, or watch window. 

 It seems Immediate window changes aren't perfect either. The Autos and Watch windows are updated but locals is not. 
 Immediate Window Changes

**Comment by zooba** [comment]
IIRC, this is a limitation of Visual Studio's debugger UI.

**Comment by int19h** [comment]
There's no non-hacky way to do this, but a hacky one that works is this:

https://github.com/Microsoft/RTVS/blob/db6353d5ebdd12bcfa44b11b4a86bc8175d20777/src/Debugger/Impl/DTEDebuggerExtensions.cs#L16

We just need to do this after every expression eval in the REPL.

**Comment by zooba** [comment]
Reopening due to #1935

**Comment by zooba** [comment]
I can't repro this any more.
