### ISSUE TITLE
Intellisense error with class method

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1195]
When using a class method, the tooltip highlight does not follow the good parameter:
![image](https://cloud.githubusercontent.com/assets/1050156/14089737/4c4dfb84-f4eb-11e5-9580-c036d2b92264.png)
and then:
![image](https://cloud.githubusercontent.com/assets/1050156/14089752/628eb532-f4eb-11e5-8f25-d1b2b1944bb5.png)

Tested with [GitPython](http://gitpython.readthedocs.org/en/stable/index.html), class method `Repo.clone_from` and PTVS 2.2.31124.00 on VS 14.0.24720.00 Update 1

**Comment by zooba** [comment]
We shouldn't be displaying the `cls` parameter here when you're accessing the method on a class.
