### ISSUE TITLE
"Debug Selected Test" fails when <ProjectHome> is not default

### ISSUE THREAD

**Issue by wpalfi** [Microsoft/PTVS#1197]
I modified `<ProjectHome>` in the pyproj file (as a workaround for #1189), but then "Debug Selected Test" started to fail:

```
Test Outcome:   Failed
Result StandardError:   
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 69, in <module>
    main()
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 33, in main
    from ptvsd.visualstudio_py_debugger import DONT_DEBUG, DEBUG_ENTRYPOINTS, get_code
ImportError: No module named 'ptvsd'

```

As a workaround/bugfix(?) I modified visualstudio_py_testlauncher.py:

`line 30: sys.path[0] = os.getcwd()`
replaced with
`line 30: sys.path.append(os.getcwd())`

(VS2015/Update 1, PTVS 2.2.31124.00)

**Comment by zooba** [comment]
Have you tried modifying the current working directory for the project, rather than `ProjectHome`? That should have less impact on your project.

#840 is the main bug we're tracking this issue with.

**Comment by Artfunkel** [comment]
I hit a very similar problem when modifying the PYTHONPATH env var. Adding the location of that module (`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2`) to the path list fixed the issue.

**Comment by zooba** [comment]
Closing. We'll track this on #840
