### ISSUE TITLE
 A abend of microsoft.pythontools.parsing.badsouurceexception 

### ISSUE THREAD

**Issue by pengshp** [Microsoft/PTVS#1198]
when I open a python projcet,it show;
![](http://imgsrc.baidu.com/forum/w%3D580%3Bcp%3Dtieba%2C10%2C149%3Bap%3Dvs2013%B0%C9%2C90%2C157/sign=6c2a3fd993eef01f4d1418cdd0c5fa55/906676adcbef760993931f2229dda3cc7dd99e02.jpg)
what should I do??who can help me

**Comment by zooba** [comment]
Can you check the `.py` files in your project to see whether you have specified coding comments at the start? If these are incorrect then we may observe this exception (though we're supposed to handle them all).

**Comment by zooba** [comment]
Didn't hear any response, so closing this. Feel free to reopen if you have new information.
