### ISSUE TITLE
Unable to find vcvarsall.bat when using python3.5 with vs 2013

### ISSUE THREAD

**Issue by unhealthy** [Microsoft/PTVS#1199]
My python version is 3.5 and I use vs2013.
I want to install `lxml` package use pip in a virtualenv, but it always show that `Unable to find vcvarsall.bat`
I have already add a system environment variable `VS140COMNTOOLS` and set its value to '%VS120COMNTOOLS%', but nothing works.
What can I do?
I cannot use vs2015 now because I need CUDA sdk, which does not support vs2015 now.

**Comment by zooba** [comment]
For Python 3.5 you will need VS 2015, or at least the [C++ build tools](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/).

Simply having VS 2015 installed is enough - you do not need to be using it.

**Comment by unhealthy** [comment]
It works. I install both vs2015 and vs2013 in my computer.
I use vs2015 to finish python project and vs2013 to CUDA project.
Thanks very much
