### ISSUE TITLE
Azure Websockets 

### ISSUE THREAD

**Issue by thcrnk** [Microsoft/PTVS#1201]
I am hosting my web app using azure web app. Do You consider to support websockets in azure? Right now I can't configure it with the FastCgi in IIS.

**Comment by zooba** [comment]
I haven't looked into how to configure this, but [this page](https://azure.microsoft.com/en-us/blog/introduction-to-websockets-on-windows-azure-web-sites/) suggests that it is possible.

At a guess, I'd expect the instructions for Python would be similar to Node.js, so you'll need a separate websocket library.
