### ISSUE TITLE
StopIteration was unhandled by user code

### ISSUE THREAD

**Issue by rfalcades** [Microsoft/PTVS#1202]
After update 2 of visual studio 2015, my application starts to show this message when interact over a enum.

**StopIteration was unhandled by user code**

If I run same line direct on python prompt, it works normally.

Here is enum definition:

```
from enum import Enum

class Environments(Enum):
    DEV = 0
    UAT = 1
    STG = 2 
    PRD = 3
```

and line with exception:

`environmentsAvailable = [e.name for e in Environments]`

Before update 2 it was ok.

**Comment by zooba** [comment]
I don't believe we may any changes in Update 2 that would affect this, but possibly some Exception settings have changed?

Open Debug, Windows, Exceptions and find `StopIteration`, and see whether it is selected to break. By default, it should be deselected.

**Comment by rfalcades** [comment]
I removed "Python Environments" configurations and setup it again and everything is working again.

Thanks

**Comment by zooba** [comment]
Interesting. I guess you had something not configured correctly? Do you know what that was?

**Comment by rfalcades** [comment]
Maybe it could be something wrong in python environments inside visual studio

**Comment by zooba** [comment]
If that's the case, recreating the environment identically would not fix the problem. Maybe you changed the Library path? IIRC, we use that to decide whether code files are user code or non-user code.

**Comment by rfalcades** [comment]
What I've done was, under "Python Environments", I had a virtual environment using Python 3.5:

- So I removed virtual environment under python environment
- I closed Visual Studio
- In windows explorer, in solution path, I removed "env" folder 
- I opened visual studio and solution again 
- I did a new virtual environment using Pyton 3.5 (right click, "Add Virtual Environment ....")

And it worked as before update apply.

**Comment by zooba** [comment]
Ah okay. Not sure how that worked, but glad you got it sorted out.
