### ISSUE TITLE
Can not remove python environment uninstalled

### ISSUE THREAD

**Issue by zh19970205** [Microsoft/PTVS#1211]
First, I install Ironpython and Anaconda
Then, I install PTVS from VS
Then, I uninstall Anaconda
But Now Anaconda python still exists in my environments
And I can not remove it
How to solve it?
![image](https://cloud.githubusercontent.com/assets/11623447/14375561/c506f060-fd94-11e5-9838-3a2c09505050.png)
Thank you

**Comment by zooba** [comment]
It looks like Anaconda did not uninstall its registry keys correctly when you removed it.

Have a look under `HKEY_CURRENT_USER\Software\Python\PythonCore\2.7` or `HKEY_LOCAL_MACHINE\Software\Python\PythonCore\2.7` to see if they are still there. You can remove the key if you have already uninstalled Anaconda.
