### ISSUE TITLE
Intellisense cannot refresh

### ISSUE THREAD

**Issue by clu8** [Microsoft/PTVS#1215]
I'm trying to refresh the completion DB for my installation of Python 64-bit 3.5 on Windows 10 running Visual Studio 2015 with PTVS 2.2.3. However, every time I click the "Refresh DB" button, the progress bar spins for a couple seconds and reverts to its earlier state (nothing happens, and the refresh DB button shows up again). 

I believe this issue may have begun when I installed numpy and matplotlib (precompiled versions). I have tried reinstalling VS, PTVS, and removing numpy and matplotlib, but the problem continues. I've attached my diagnostic info. Thanks!
[Diagnostic Info 2016-04-10T154551.txt](https://github.com/Microsoft/PTVS/files/212052/Diagnostic.Info.2016-04-10T154551.txt)

**Comment by zooba** [comment]
Thanks!

It's a little hard to tell from the logs, but it looks like you've got an analyzer process stuck open? Rebooting your machine is the easiest way to make sure it's cleaned up, but if you can still see any `Microsoft.PythonTools.Analyzer.exe` processes running, kill them and then restart VS.

**Comment by clu8** [comment]
Unfortunately I doubt this is the issue. I have rebooted my machine countless times since this issue started occurring, and just rebooted again to double check. I also see no `Microsoft.PythonTools.Analyzer.exe` processes. Also, I forgot to mention that this was happening with PTVS 2.2.2 before I upgraded as well.

**Comment by zooba** [comment]
It's possible that you have a `C:\Users\charl\AppData\Local\Python Tools\CompletionDB\14.0\9a7a9026-48c1-4688-9d5d-e5699d47d074\3.5\database.pid` file that was not deleted.

It is supposed to be removed by the operating system even if we crash, but if it exists you can just delete it.

**Comment by clu8** [comment]
That fixed it. Thanks!
