### ISSUE TITLE
cElementTree.py import issue

### ISSUE THREAD

**Issue by sjjpo2002** [Microsoft/PTVS#1218]
Hi,

Every time I run the code it stops at cElementTree.py which is just a empty file with one line:

    # Wrapper module for _elementtree

    from _elementtree import *

and it says:
un(shallow)copyable object of type <type 'Element'>

Error was not handled by user code.

But the code runs after I press continue. What is the reason for this? and how to fix it?

**Comment by zooba** [comment]
The exception is handled further up the stack, but we aren't able to detect it.

The `_elementtree` module is written in C, so we can't show the source code, but it's possible that we can see exceptions being set - that's what is happening here.

You can deselect the checkbox in the popup to avoid breaking on this type of exception, which is likely to be fine for most of your code. Just remember that you've done it in case you do cause the exception in your own code and wonder why the debugger doesn't break.

**Comment by sjjpo2002** [comment]
Thanks for your reply. I'll just deselect the box.

**Comment by illera88** [comment]
@zooba I don't get any pop up when stopping at it. Where can I find the checkbox in the options configuration?

Thannks

**Comment by zooba** [comment]
@illera88 Look under Debug, Windows, Exception Settings and find (or add) the exception to the Python section.
