### ISSUE TITLE
Intellisense update for virtual environments

### ISSUE THREAD

**Issue by traits** [Microsoft/PTVS#1229]
Recently, I created a new virtual environment on top of Python 3.4.4 (WinPython) from command line, giving also access to the parents site-packages (--system-site-packages switch). Intellisense seems to parse all these packages again, after pointing PTVS to the new environment. Would it be possible to inherit this information from the original python environment without the necessity of parsing it again?

**Comment by zooba** [comment]
Did you add the virtual environment as a Custom Environment or a Virtual Environment (see [this wiki page](https://github.com/Microsoft/PTVS/wiki/Python-Environments) for the difference).

If the latter, then we should pick up the underlying environment's DB automatically (though we are looking to change that in the next version, as it adds a huge amount of complexity that isn't really necessary - manually creating the environment with `--system-site-packages` is required to get that option as we don't expose it through the UI, but we do recognize it when it is set).

If the former, we treat the environment as completely independent, as we don't have enough information to know how dependencies change. We know about the source directories by inspecting `sys.path`, but that doesn't reliably let us reuse completion DBs, which may have been affected by the Python version or various builtins or extension modules. So in this case, no, we can't necessarily inherit the information.

**Comment by traits** [comment]
I created the virtual environment by pure Python 3.4 means, in calling `python -m venv --system-site-packages myenv`. After that, I picked it up from inside VS, utilizing 'Add Existing Virtual Environment...' - so this should be the mentioned 'latter' case.

**Comment by zooba** [comment]
Yes, you're right. We should handle that case fine. I can't look into this right away, but I'll mark it as a regression bug so we get back to it soon.

**Comment by zooba** [comment]
As far as I can tell, we're still handling this correctly. It will look like the virtual environment is being parsed while the base environment is (the progress bars are the same, but if you look at the IntelliSense pane it will say "Waiting for another refresh"), but we aren't redoing everything.

There _is_ a bug where we are expecting some modules in the DB but aren't generating them, which results in the "refresh" button always showing up. Is that what you're seeing? Or it is actually spending the full time regenerating all the same modules as are in the base environment?

**Comment by zooba** [comment]
This no longer applies, as we don't treat virtual environments any differently from regular ones. The `sys.path` value will be used.
