### ISSUE TITLE
Missing intellisense for .NET Assemblies  

### ISSUE THREAD

**Issue by bmenne-dspace** [Microsoft/PTVS#1230]
The PTVS intellisense for .NET classes, interfaces and methods within VS does not work if a type implements an interface from another assembly. 

Formally: If a _class C_ in _Assembly A_ implements an _Interface X_, which is placed in _Assembly B_ the intellisense does not work for_ class C_. 

Workaround: If I added the assembly which includes the interfaces to the GAC it works fine.

In my point of view the PTVS cannot find the assembly which provides the base interfaces. I also try to reference the assembly which includes the base interfaces but this neither works. Is there any opportunity to get intellisense in the described scenario without using the GAC? 

Thank you very much!

**Comment by zooba** [comment]
> PTVS cannot find the assembly which provides the base interfaces

That seems most likely. Is there a copy of assembly A alongside the assembly B that you are referencing? I'm fairly sure we should pick it up automatically then, but if they are not in the same directory then we may not.

**Comment by bmenne-dspace** [comment]
In my situation the assemblies are not alongside. I try to place them alongside but that does not work.

I set up a testproject you can see here:
[IronPythonApplication1.zip](https://github.com/Microsoft/PTVS/files/229791/IronPythonApplication1.zip)

I added two classes "ClassThatWorks" and "ClassThatDoesNotWorks". "ClassThatDoesNotWorks" implements BaseInterface from another assembly (ClassLibrary1). 

Within the IronPythonApplication1 project you can reproduce the problem. For "x" there is intellisense fro "y" there is no intellisense.

import clr

clr.AddReference("ClassLibrary1")
clr.AddReference("ClassLibrary2") 

from ClassLibrary2 import ClassThatWorks
from ClassLibrary2 import ClassThatDoesNotWork

def test():
    x = ClassThatWorks()
    y = ClassThatDoesNotWork()

It also does not work if I reference the assemblies ClassLibrary1.dll and ClassLibrary2.dll which are placed alongside.

May I change something at the import statments "clr.AddReference("ClassLibrary1")" or somethong else? 

Thank you very much!
