### ISSUE TITLE
Error when trying to install Django in PTVS on Win 10

### ISSUE THREAD

**Issue by rvaughn70** [Microsoft/PTVS#1239]
I receive the following error message when attempting to install Django in Visual Studio.  Any help would be greatly appreciated!

**Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35-32\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-iatnivnq-unpack\\Django-1.9.5-py2.py3-none-any.whl'**

**Comment by zooba** [comment]
That seems like a strange error (nothing to do with Visual Studio, by the way - we just start running `pip` for you - but I'll see how I can help).

You've censored your username - can you confirm that it's only made up of Latin alphabet characters (a-z) and numbers? Python can occasionally have issues with accented characters or those from non-English alphabets.

Is this your own machine, or is someone else responsible for managing it? It is unusual, but possible to not have full access to your own temp directory.

If you retry the installation, is the result any different?

**Comment by rvaughn70** [comment]
Actually, my name is Robert.  No big mystery.  :)  It is my laptop and I am a local admin.  I have played around with permissions on that Temp folder to include giving "Everyone" Full permissions, but the install continues to fail.  One interesting thing to note is I have Django installed at the Global level.  It is just failing with the above error when trying to install it in the virtual environment.  I know it may be crazy to worry about, but I would just like to be able to use it in the virtual environments.

**Comment by rvaughn70** [comment]
Ok.  I just retried installing after giving "Everyone" Full permissions on my Temp folder again AS WELL AS Checking the "Run as Administrator" checkbox on pip within Visual Studio and I received the following NEW message...

**Installing 'django'
Collecting django
  Using cached Django-1.9.5-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python35-32\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Robert\\AppData\\Local\\Temp\\pip-kf3zq69q-unpack\\Django-1.9.5-py2.py3-none-any.whl'

During handling of the above exception, another exception occurred:**

It then goes on to list other errors that I believe to just be related to the original failure.

Thanks again for all/any help!!

**Comment by zooba** [comment]
Sorry for the delay... notifications got lost in piles of email :(

What virus scanner are you running? I wonder whether it's blocking some writes into the Temp directory?

**Comment by rvaughn70** [comment]
Hmmm.  That is very possible.  I am running Cylance, but have access to disable it.  I think I may have tried that already, but will try it again and let you guys know.  Thank you for keeping up with this!  Have a GREAT Memorial Day weekend!!

 

Robert
