### ISSUE TITLE
wfastcgi 2.2 + IIS 8 + Flask 0.10.1 + Python 3.5.1 = error

### ISSUE THREAD

**Issue by chuckmo8** [Microsoft/PTVS#1240]
I am running a flask webapp of which standalone script runs fine. When it is integrated into IIS 8 with wfastcgi we get this error:
```
Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\python\python34\lib\site-packages\wfastcgi.py", line 779, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\python\python34\lib\site-packages\wfastcgi.py", line 621, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv('WSGI_HANDLER'))
  File "c:\python\python34\lib\site-packages\wfastcgi.py", line 594, in get_wsgi_handler
    handler = handler()
TypeError: __call__() missing 2 required positional arguments: 'environ' and 'start_response'


StdOut: 

StdErr: 
```
web.config file:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appSettings>
    <add key="WSGI_HANDLER" value="app.app()" />
    <add key="PYTHONPATH" value="C:\Flaskapp" />
  </appSettings>
  <system.webServer>
    <!--<handlers accessPolicy="Read, Execute, Script" />-->
    <modules runAllManagedModulesForAllRequests="true" />
    <handlers>
      	    <add name="Python FastCGI" 
			path="*" verb="*" 
			modules="FastCgiModule" 
			scriptProcessor="C:\python\python34\python.exe|c:\python\python34\lib\site-packages\wfastcgi.py" 
			resourceType="Unspecified" requireAccess="Script" />
    </handlers>
  </system.webServer>
</configuration>
```
How can this be fixed? Thanks.

**Comment by zooba** [comment]
At a guess, your `WSGI_HANDLER` app setting should be `app.app` (without the trailing `()`). That way, `wfastcgi` will do:

```python
handler = __import__("app")
handler = getattr(handler, "app")
handler(environ, start_response)
```

Currently, it's doing this:
```python
handler = __import__("app")
handler = getattr(handler, "app")
handler = handler()  # Call here is missing arguments
#handler(environ, start_response)  never reached
```

**Comment by chuckmo8** [comment]
Great! It works.

We could not distinguish the different between app and app().

Thanks a lot Steve.

**Comment by zooba** [comment]
Just out of interest, can you tell me where you looked to try and figure this out? I want to go through the places that people are actually looking at and make these answers more obvious.

**Comment by chuckmo8** [comment]
The major document I read was wfastcgi on pypi: https://pypi.python.org/pypi/wfastcgi

I also googled with these key words "python flask iis"

https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-classic-python-django-web-app/

http://netdot.co/2015/03/09/flask-on-iis/

https://heejune.me/2015/04/22/running-python-flask-on-a-local-iis-not-azure-with-wfastcgi-py/

Most of the examples I have gone through were with blankets in WSGI_HANDLER value. We followed that and failed.

**Comment by zooba** [comment]
Awesome, thanks! That's valuable info. 👍
