### ISSUE TITLE
Renaming decorators does not always work

### ISSUE THREAD

**Issue by RussBaz** [Microsoft/PTVS#1245]
When an applied generator is renamed, then PTVS renames both an applied decorator and its definition. However, if only its definition is renamed, then an applied decorator is not renamed.

**Comment by zooba** [comment]
Nice catch, thanks! We'll take a look.

**Comment by DinoV** [comment]
I'm not able to repro this on current builds...  If I do:

```
def f():
    pass

def g():
    pass

@f(42)
@g
def decorated(self):
    pass
```

I can rename either f or g at their definition site or where they're applied to the decorator.  In both cases we rename both the definition and the place where the decorator is used.

It may be that we've fixed it in some recent changes, or it could be that I don't understand the repro.  Is this what isn't working for you?

**Comment by RussBaz** [comment]
You are right! I can no longer reproduce it either. Unfortunately, I can't remember what has changed. I think I have updated Visual Studio to the 'Update 2' since then. I am sorry but I didn't keep the full record this time.

**Comment by zooba** [comment]
Reported again at https://developercommunity.visualstudio.com/content/problem/75362/refactor-rename-doesnt-update-decorators-in-python.html

**Comment by huguesv** [comment]
Here are the Python 3 code examples from the community link, properly formatted.

This one is reported as problematic, but I'm not seeing any issues renaming `decorate` from either location.
```
def decorate(func):
    def wrap(*args, **kwargs):
        print(args)
        print(kwargs)
        return func(*args, **kwargs)
    return wrap

@decorate
def test(alpha, omega):
    print(alpha)
    print(omega)

test(1, 2)
```

For this one rename of `DecoratorTest` only applies to where the rename occurs, the other location is unchanged.
```
class DecoratorTest:
    def __init__(self, *args, **kwargs):
        self.args = args
        self.kwargs = kwargs

    def __call__(self, klass):
        class kustom(klass):
            def __init__(me, *args, **kwargs):
                print('Inside Kustom')
                print('======__init__ args, kwargs===========')
                print(args)
                print(kwargs)
                print('======Decorator args, kwargs==========')
                print(self.args)
                print(self.kwargs)
                super().__init__(args, kwargs)
        return kustom

@DecoratorTest({'alpha':'A'}, parameter = False)
class Klown: 
    def __init__(self, args, *kwargs): 
        print('Inside class Klown')

k = Klown({'omega': 'Z'}, simulation = True)

```

**Comment by MikhailArkhipov** [comment]
I can have a look

**Comment by zooba** [comment]
@MikhailArkhipov It may not repro now - I just closed 2-3 similar to this last week. PR #3166 should have fixed many of these issues.

**Comment by zooba** [comment]
This still reproduces. It looks like using a class as a decorator adds a definition to the decorator, but does not add a reference to the class.

**Comment by zooba** [comment]
Nope, I was wrong. We don't process decorators on classes - only functions.
