### ISSUE TITLE
unable to load solution using vs2015

### ISSUE THREAD

**Issue by agiknight** [Microsoft/PTVS#1247]
all projects load fail with this message "H:\PTVS\Python\Product\PythonTools\PythonTools.csproj : error  : ....“H:\PTVS\BuildOutput\MicroBuild.Core\build\MicroBuild.Core.props”。......  H:\PTVS\Build\MicroBuild.props

**Comment by zooba** [comment]
Yeah, that's a known issue with both our projects and also our build instructions.

You need to run `Build\PreBuild.ps1` first to install some extra packages. Once I fix the project loading issue, you'll be able to load them and then it will run this when you first try to build, at which point you'll probably need to restart VS to load everything again.

However, note that the `v2.x` branch _does not_ require this, and so the current instructions apply correctly for that.
