### ISSUE TITLE
PTVS to do suggest imports in the way C# suggests usings

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/PTVS#1248]
In Visual Studio in a C# file, if I begin to type a statement like:

`var scn = new SqlConnection(); `

the reference to SqlConnection will be underlined in a red squiggly. If I right-click on it, the context menu contains a Resolve item, that suggests that I need a using statement. If I accept the suggestion, the using statement is added to my program.

If I do the same thing in ptvs, no error (squiggly) is generated and there is no suggestion to import the missing module.

Can this be added?

Similarly, if I have another Python file called Foo containing a class called Foo that I want to use that is part of the same project, and I begin to type:

`f = Foo()`

I'd like ptvs to first note that there is an error (missing ref) and second offer to add 

`from Foo import Foo `

to my import statements.

Can this be done?

**Comment by zooba** [comment]
It's possible. We already have a lightbulb appear at the left of the editor in this case, so also showing a squiggly would be possible (but likely to be a bit noisy, as they'd appear _everywhere_), and also having an extra menu item.

Guessing the light bulb isn't god enough because you can only see it once you've selected the word, right?

**Comment by gbritton1** [comment]
Well, not sure it works properly.  I have a project with two files: Foo.py and App.py.  Foo.py has the class Foo in it.  While editing App.py I type:

f = Foo()

no lightbulb appears at the left. No suggestion to import.  (I need a "from Foo import Foo" statement )

Also tried it with a .Net object (using IronPython)

sql = SqlConnection()

selecting the object just gives "Unknown type".  This kind of thing works in C#/VB and knows what to suggest.

**Comment by gbritton1** [comment]
More on Foo().  It's a little more complicated.  In App.py, I type f = Foo().  The first time I do that, If I hover over Foo(), a drop-down appears offering to add "from Foo import Foo" -- just what I need.  If I subsequently delete the import statement, Foo() still appears in blue with a description, even though the import is gone.  I guess PTVS is not aware of the change or what removing the import  statement implies.

This kind of thing is pretty seamless in C#
