### ISSUE TITLE
No completions in virtual env REPL

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1251]
Dev15 Preview 2, Python 2.7, in a virtual env REPL:
```
text = "hello"
tex <ctrl-space>
```
Nothing comes up. I haven't changed the default options.

Edit: While it originally seemed to on global and virtual env, now it only reproduce for virtual env.

**Comment by zooba** [comment]
Seems like we aren't creating the temporary file (`evaluator.AnalysisFilename`) in the analyzer, and so `TryGetAnalysisEntry` is failing.

**Comment by zooba** [comment]
It's probably because we aren't passing the project file info to the analyzer when creating it in PythonInteractiveEvaluator.
