### ISSUE TITLE
IntelliSense does not recognise pathlib objects constructed by '/'

### ISSUE THREAD

**Issue by RussBaz** [Microsoft/PTVS#1255]
Example:
```python
from pathlib import Path

a = Path('.').absolute()
b = a / 'src'
```
When I do as shown in the snippet above, IntelliSense would not recognise object 'b' as a 'Path' object.

**Comment by frozax** [comment]
I'd love to get this feature, too

**Comment by DinoV** [comment]
We're not getting the true division flag correctly set.  One work around is to add a from __future__ import division to the top of your file and then we'll get the right intellisense.
