### ISSUE TITLE
Error messages lost when running in debug

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/PTVS#1256]
I have a simple program that has one line:

`f = Foo()`

Note that Foo is not defined anywhere.  If I run this from the command line, I get an error message:

> C:\Program Files (x86)\IronPython 2.7>ipy C:\Users\brittg2\Projects\Python\TestP
> y\IronPythonApplication1\App.py
> Traceback (most recent call last):
>   File "C:\Users\brittg2\Projects\Python\TestPy\IronPythonApplication1\App.py",
> line 1, in <module>
> NameError: global name 'Foo' is not defined

As expected.  If I run this in Visual Studio under debug, however, I do not see the error message.  In the output window I get lots of stuff (most of which look like errors, but not mine!) but not the message I get when running from the command line.  Where does that go? (note that the Error tab is empty)

Output window after running the one-liner:

> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Program Files (x86)\IronPython 2.7\ipy.exe'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Dynamic\v4.0_1.1.0.20__7f709c5b713576e1\Microsoft.Dynamic.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Scripting\v4.0_1.1.0.20__7f709c5b713576e1\Microsoft.Scripting.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\IronPython\v4.0_2.7.5.0__7f709c5b713576e1\IronPython.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\IronPython.Modules\v4.0_2.7.5.0__7f709c5b713576e1\IronPython.Modules.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Program Files (x86)\IronPython 2.7\DLLs\IronPython.SQLite.dll'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Program Files (x86)\IronPython 2.7\DLLs\IronPython.Wpf.dll'
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in IronPython.Modules.dll
> A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'Snippets.scripting'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'Anonymously Hosted DynamicMethods Assembly'
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in IronPython.Modules.dll
> A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in IronPython.Modules.dll
> A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in IronPython.Modules.dll
> A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in IronPython.Modules.dll
> A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> A first chance exception of type 'IronPython.Runtime.Exceptions.ImportException' occurred in Microsoft.Dynamic.dll
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'Snippets.debug.scripting'
> 'ipy.exe' (Managed (v4.0.30319)): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\ISymWrapper\v4.0_4.0.0.0__b03f5f7f11d50a3a\ISymWrapper.dll'
> The thread '<No Name>' (0x249c) has exited with code 0 (0x0).
> The thread '<No Name>' (0x16cc) has exited with code 0 (0x0).
> The thread '<No Name>' (0x2050) has exited with code 0 (0x0).
> The thread '<No Name>' (0x15e0) has exited with code 0 (0x0).
> A first chance exception of type 'IronPython.Runtime.UnboundNameException' occurred in IronPython.dll
> A first chance exception of type 'IronPython.Runtime.UnboundNameException' occurred in Snippets.debug.scripting
> A first chance exception of type 'IronPython.Runtime.UnboundNameException' occurred in Snippets.debug.scripting
> The program '[5468] ipy.exe: Program Trace' has exited with code 0 (0x0).
> The program '[5468] ipy.exe: Managed (v4.0.30319)' has exited with code 1 (0x1).

**Comment by gbritton1** [comment]
Any feedback on this issue?

**Comment by DinoV** [comment]
You're currently configured to be using .NET debugging - the first chance UnboundNameException error is actually your unbound "Foo".  You can either disable .NET debugging (and use Python debugging which gives you a much better experience with Python code) or you can reconfigure your exception settings.

To disable .NET debugging right click on your project, choose Properties, and then select the Debug tab in the project properties pane.  From there change "Launch Mode" to Standard Python Launcher.

To enable breaking on other exceptions bring up the exceptions tool window (Debug->Windows->Exception Settings) and check "Common Language Runtime Exceptions".  That should enable breaking on all exceptions.  You could also just add "IronPython.Runtime.UnboundNameException" in this case and make sure it's checked.  Checking them all might result in more exceptions then you want to see, but you can uncheck them in the Exception Assistant window whenever an exception is raised.

If that doesn't help let us know!

**Comment by gbritton1** [comment]
that did it...thanks!
