### ISSUE TITLE
Intellisence not working in PTVS

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/PTVS#1259]
If I import a module into a new python file like **import pydocumentdb.base as base**
I don't get correct tooltip when I type base. and hover over "base". It shows as <unknown type>. Also when I press '.' after base, I get <No completions> but if I close my solution and reopen it again, everything works fine.

So looks like adding an import statement to a file doesn't imports any module until I close and reopen the solution.

pydocumentdb/base.py is already in my project.

Microsoft Visual Studio Enterprise 2015: Version 14.0.25123.00 Update 2
Python Tools for Visual Studio   2.2.40315.00

**Comment by gbritton1** [comment]
Same here, different version:

Microsoft Visual Studio Ultimate 2012
Version 11.0.61219.00 Update 5
Microsoft .NET Framework
Version 4.5.51209

Python Tools for Visual Studio   2.1.30810.00

**Comment by gbritton1** [comment]
Here's an interesting variation:

1. Create a module with a bare-bones class in it and save it
2. Create a second module that imports the first one and instantiates it
3. Run the second module
4. Now, remove the import statement.
--> IntelliSense still shows the class constructor signature, even though the import is gone.
--> no offer to add an import statement.
5. save and close module 2 then reopen it
-- IntelliSense still shows the signature!
