### ISSUE TITLE
VS 2015 crashes when opening an existing python file or when entering code in the editor.

### ISSUE THREAD

**Issue by modulexcite** [Microsoft/PTVS#1267]
Hi,

As soon as I start entering code in the Visual Studio editor it's crashing it; entering comments is fine which makes me think the interpreter or PTVS intellisense is causing the issue. I'm able to create new projects but can't enter any code. I can't open any existing python files with code as Visual Studio crashes the minute it finishes loading the environment. 
Please review the attached diagnostic info from PTVS Tools; it seems like its encountering a few errors while parsing the python files. Any help is much appreciated and thank you for the tools.

The following is my environment:
- Windows 7 64-bit
- PTVS 2.3.3
- Visual Studio 2015 Update 
- Python 3.5 32-bit
- IronPython 2.7

[PTVS-Error.txt](https://github.com/Microsoft/PTVS/files/252369/PTVS-Error.txt)

**Comment by zooba** [comment]
That error is coming from "Devart":
```
Time: 2016-05-06T09:51:26
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Devart.Shell.ErrorReport.UnexpectedError..ctor(System.Exception, System.Object, Boolean, Boolean)
   at Devart.Shell.ErrorReport.UnhandledExceptionHelper.ShowErrorReport(System.Object, System.Exception, Boolean, Boolean, Boolean)
   at Devart.Shell.ErrorReport.UnhandledExceptionHelper.SyncUnhandledException(System.Object, System.UnhandledExceptionEventArgs)
   at Devart.Shell.ErrorReport.UnhandledExceptionHelper.UnhandledException(System.Object, System.UnhandledExceptionEventArgs)
```

I don't know exactly what this is, but I'd guess it's one of your other extensions? We probably need to get in touch with the developers of that extension and let them know that they are crashing on Python files.

Would you know what extension it is and where their website is?

**Comment by modulexcite** [comment]
That was my initial reaction as well, it was an extension from Devart but after removing it I get a similar error with a different extension called "ErrorHighlighter" so I assumed it will keep throwing errors with a different extension until I remove all of them.

___________________________
Thanks.

    _____________________________

**Comment by modulexcite** [comment]
So every time it's a different extension as soon as I remove the one it's complaining about in the error logs. I tried Visual Studio SafeMode but that unfortunately disables PTVS as well.

**Comment by zooba** [comment]
It seems to be dealing with an otherwise unhandled exception, so once you've disabled all the extensions that are doing that (probably all the ones from Devart, at a guess), it should just crash VS. Then you'll get the actual error entry appear in the log, instead of the error in another extension trying to handle the error.

**Comment by modulexcite** [comment]
After disabling a couple of extensions, i"m now able to work with python files. I'll contact the developer of those extensions, sorry for the trouble.
