### ISSUE TITLE
Incorrectly highlighted syntax error when using lambda and tuple unpacking to generate function arguments on Python 3

### ISSUE THREAD

**Issue by Asday** [Microsoft/PTVS#1270]
In the simplest form:

```
args = {
    "a": lambda: (1, 2, 3),
    }

def f(a, b, c, d):
    print(a, b, c, d)

f(*args["a"](), 4)
```

PTVS highlights the `4` on line 8 as a syntax error, noting "non-keyword arg after keyword arg", but this is valid Python for Python 3.  Doesn't happen for 

```
args = {
    "a": lambda: 1,
    }

def f(a, b):
    print(a, b)

f(args["a"](), 4)
```

**Comment by DinoV** [comment]
Thanks for the report!  We've already fixed this in our latest 3.0 builds so you shouldn't see it anymore when we release the next alpha or beta.
