### ISSUE TITLE
Add Existing Item creates a copy

### ISSUE THREAD

**Issue by mlamarre** [Microsoft/PTVS#1284]
PTVS 2.2.3 on VS 2015. On a new "From existing Python code" project, when using SHIFT-ALT-A (or project menu, or right click on solution explorer) to "Add Existing Item..." a new copy of the selected file is created and put in the project file folder (pyproj). 

That's not the expected behavior, at least not for someone coming from using VS for C++. 

In my case, the pyproj file is not in the source code tree.

My workaround is to manually edit the pyproj file.

**Comment by mlamarre** [comment]
Found "Add as a Link" drop down on the Add button.

**Comment by zooba** [comment]
You may also want to look at the `ProjectHome` property - this is a relative path from the .pyproj file to the root of your source tree, and it is intended to let you keep the project file somewhere else.

It's supposed to be set automatically when you use "From existing Python Code" or when you use Save As on the project file, but if you moved the file manually it may not have been updated. You need to edit the file manually to change it, and will probably have to modify all your file references as well.
