### ISSUE TITLE
BreaksExistingExtensionException when attempting to install new Roslyn vsix on Dev 15 Preview

### ISSUE THREAD

**Issue by KevinH-MS** [Microsoft/PTVS#1285]
I believe the dependency on "VisualStudio Interactive Copmonents" needs to be bumped to ```[1.0.0.50618,3.0)``` (or at least ```...,2.1)``` :

https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/source.extension.vsixmanifest

The plan is for the Roslyn version in Dev15 to be 2.0.0.0.

**Comment by KevinH-MS** [comment]
FYI @kuhlenh @tannergooding

**Comment by zooba** [comment]
The actual plan is for the interactive components to be separate from Roslyn completely, but I expect they'll be version 2.0.0.0 too, so I'll make the change. (If you're not aware of this plan, please ping me internally so we can chat about it - there are some _serious_ issues that require the change.)
