### ISSUE TITLE
Variable highlighting

### ISSUE THREAD

**Issue by AldoMaine** [Microsoft/PTVS#1286]
Not sure of this is a feature request or I don't know how to use the editor correctly.  When I edit a C# file in VS2015, if I click on a variable name, all other instances of that variable in my code are highlighted.  I don't see this behavior when editing a Python file.  Is there a way to enable this?  Or a better practice to find all the other places I've used a variable?   I'm aware of "Find all references" but this isn't as convenient as the automatic highlighting behavior I'm looking for.

**Comment by zooba** [comment]
It's a feature request, but it's the same as #76, so I'll close this as a duplicate.
