### ISSUE TITLE
PTVS Concord components should avoid using NoFilter in their .vsdconfigxml

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/PTVS#1289]
PTVS uses NoFilter for three of its the interfaces -- [IDkmExceptionManager](https://github.com/Microsoft/PTVS/blob/819bd32ea0f4a812300bf9ff9392d4dd79ca4264/Python/Product/Debugger/DkmDebugger/RemoteComponent.vsdconfigxml#L78), [IDkmAsyncBreakCompleteReceived](https://github.com/Microsoft/PTVS/blob/819bd32ea0f4a812300bf9ff9392d4dd79ca4264/Python/Product/Debugger/DkmDebugger/RemoteComponent.vsdconfigxml#L78) and [IDkmCallStackFilter](https://github.com/Microsoft/PTVS/blob/819bd32ea0f4a812300bf9ff9392d4dd79ca4264/Python/Product/Debugger/DkmDebugger/LocalComponent.vsdconfigxml#L57).

For IDkmExceptionManager, I think you could use an EngineId filter. For the others you may be able to use either a CallOnlyWhenLoaded constraint.

Having the exception manager loaded causes an issue with XBox game development. This is somewhat a bug in the core debugger. But it seems like a good fix here anyway.

Using CallOnlyWhenLoaded, I believe you can cut down on the number of scenarios that the code loads in, which is good for perf for scenarios where the user isn't using Python. You could use your custom message listener, or an IDkmRuntimeLoadNotification to get your code to load when Python does load in the target process.

**Comment by int19h** [comment]
Since we have a single DLL for all our components (in fact all component interfaces are implemented by the same class), and that class already gets loaded when Python is in play, will that satisfy `CallOnlyWhenLoaded`?

**Comment by gregg-miskelly** [comment]
CallOnlyWhenLoaded is true anytime the dispatcher loads an instance of the class. So you will want at least one interface per class which isn't call-only-when-loaded or else the class will never get loaded.

**Comment by int19h** [comment]
Right, and the same class that does `IDkmCallStackFilter` also does `IDkmRuntimeInstanceLoadNotification`, which is configured to load for the Python runtime. And we really only need the filter to apply when our runtime is loaded. So it sounds like it should just work with `CallOnlyWhenLoaded` - I'll give it a try.

**Comment by zooba** [comment]
@int19h Did you ever try this? What does the change look like?

**Comment by int19h** [comment]
As I recall, it wasn't as simple as changing .vsdxml - some things didn't get loaded when they should, and it required debugging to figure out what's going on. Since the bug in the context of which this was originally filed was resolved without the need for a workaround on our side, I didn't investigate further.
