### ISSUE TITLE
Problem opening Interactive window

### ISSUE THREAD

**Issue by clutchclayton806** [Microsoft/PTVS#1302]
Hi,

This is my first serious encounter with Python or Visual Studio, I am having issues trying to open the interactive window on Python 2.7 and Python 3.5. From what I can tell, would I need to set up an environment first. Here is a screenshot for reference.

![image](https://cloud.githubusercontent.com/assets/19419126/15343698/bcd46992-1c64-11e6-8a6a-72183bfd1f94.png)

Thanks for any help,

Clayton

**Comment by zooba** [comment]
Did you fix this? It looks like you have a pending VS update to install, which is likely to resolve this sort of issue.

**Comment by clutchclayton806** [comment]
Thanks for the help. Currently updating right now. I closed the issue because I felt like it was not appropriate to post for help without checking to see if its up to date first or providing more context.
