### ISSUE TITLE
Cannot publish a Webapp using Py3.5 even with Py3.5 WebApp extension installed

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1315]
If a create a Webapp and add the Python 3.5 official extension:
https://www.siteextensions.net/packages/python/

I expect to be able to create a venv using Py3.5 in PTVS and publish it. But PTVS does not allow me to do this:
![image](https://cloud.githubusercontent.com/assets/1050156/15481209/53283d9c-20de-11e6-9a69-d74724fa7c16.png)

Maybe a warning box or some parameters to override "at your own risk" this behavior could be nice.

**Comment by zooba** [comment]
Firstly, that extension is not official. Second, it's not going to work well with a virtualenv deployed using web deploy anyway.

I'm working on alternative ways to deploy using Python 3.5. Until then, only Python 3.4 is supported (and using git deployment is strongly recommended).

**Comment by lmazuel** [comment]
I guess we don't have the same definition of "official" :)
I mean, "you can activate this in a few click right on the Azure portal"
![image](https://cloud.githubusercontent.com/assets/1050156/15483304/dcfec194-20e8-11e6-9193-61b5d62977a5.png)

When you say "git deployment is strongly recommended", are you saying that we should not use PTVS to deploy right now?

**Comment by zooba** [comment]
It says "David Ebbo" and not "Python Software Foundation" or "Microsoft" - hence, unofficial :) Anyone can upload an extension to that view.

Right now, you should only use PTVS to deploy virtualenvs for Python 2.7 or Python 3.4 32-bit when you have very few dependencies and can safely retry deployments multiple times. Configuring git deployment saves you from directly uploading dependencies, and is less likely to fail randomly.
