### ISSUE TITLE
no such table: app_poll

### ISSUE THREAD

**Issue by bwang2453** [Microsoft/PTVS#1318]
tried to build the poll app from PTVS Samples 2.2.3 and got the error: no such table: app_poll.

I am using VS2015 community (with update 2) and django 1.9.6.

I have run the makemigrations and migrate commands

**Comment by zooba** [comment]
We still need to upgrade that template to work with later Django versions. Hopefully the 2.2.4 sample pack will get the update.

**Comment by rsafarnejad** [comment]
We have run into the same issue with Visual Studio 2015 and Django 1.9.7. We look forward to seeing a fix. Also the tutorials are out of date. Can we (users) upload our own? We are really big fans of Visual Studio with Python and Django as 2nd Logic.

**Comment by huguesv** [comment]
Hi Reza.  Thanks for the feedback.  This is in progress (https://github.com/Microsoft/PTVS-Samples/pull/5), the tutorial will be updated as well.

**Comment by zooba** [comment]
Has been fixed
