### ISSUE TITLE
 VS output window is blank / WPF / IronPython

### ISSUE THREAD

**Issue by nedcrest** [Microsoft/PTVS#1324]
I have a problem while running my WPF Python simple application in Visual Studio. The "output" window is completely blank and it shows no elements that I used in VS xaml designer:

**My xaml code:**
`<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window1" Height="324.913" Width="469.204">
    <Grid>
        <Label x:Name="Label" Content="blablablablabla" HorizontalAlignment="Left" Height="59" Margin="29,10,0,0" VerticalAlignment="Top" Width="223"/>
        <Canvas HorizontalAlignment="Left" Height="190" Margin="10,69,0,0" VerticalAlignment="Top" Width="242" Background="#FFD4D4D4"/>
        <Menu x:Name="menu" HorizontalAlignment="Left" Height="26" Margin="10,69,0,0" VerticalAlignment="Top" Width="90">
            <MenuItem Header="MenuItem" RenderTransformOrigin="0.5,0.5">
                <MenuItem.RenderTransform>
                    <TransformGroup>
                        <ScaleTransform/>
                        <SkewTransform/>
                        <RotateTransform Angle="366.586"/>
                        <TranslateTransform/>
                    </TransformGroup>
                </MenuItem.RenderTransform>
                <MenuItem Header="MenuItem" Height="100" Width="100"/>
            </MenuItem>
        </Menu>
        <DataGrid x:Name="dataGrid" HorizontalAlignment="Left" Height="190" Margin="257,69,0,0" VerticalAlignment="Top" Width="204"/>
    </Grid>
</Window>`

**Window1.py (wasn't changed):**
`import wpf

from System.Windows import Window

class Window1(Window):
    def __init__(self):
        wpf.LoadComponent(self, 'Window1.xaml')`
   
**WindowApplication2.py (wasn't changed):**
`import clr
clr.AddReference('System.Drawing')
clr.AddReference('System.Windows.Forms')

from System.Drawing import *
from System.Windows.Forms import *

class MyForm(Form):
    def __init__(self):
        # Create child controls and initialize form
        pass

Application.EnableVisualStyles()
Application.SetCompatibleTextRenderingDefault(False)

form = MyForm()
Application.Run(form)`

**Here are screenshots of settings for the interpreter:**
![wpf1](https://cloud.githubusercontent.com/assets/17677787/15572274/d53bdab0-233f-11e6-83af-bd4ef2169585.JPG)

![wpf2](https://cloud.githubusercontent.com/assets/17677787/15572278/dcbc6fde-233f-11e6-8033-2d464d866b93.JPG)

**My project panel:**
_as you see I have active ironpython environment (i tried both x64 and x32)_
![wpf-proj](https://cloud.githubusercontent.com/assets/17677787/15572316/27396e68-2340-11e6-835e-be26a313af68.JPG)

**And finally my "output window":**
![wpf3](https://cloud.githubusercontent.com/assets/17677787/15572360/69458c24-2340-11e6-989d-fb5bd42cb480.JPG)

Any ideas?

**Comment by zooba** [comment]
It looks like you're starting the WinForms window (`WindowsApplication2.py`) and need to set `Window1.py` as your startup file (it's in the right-click menu in Solution Explorer).

Thanks for all the screenshots! Makes it easy to see what's going on :)

**Comment by nedcrest** [comment]
Thank you for the suggestion, however it did not help. The output window did not appear at all.
Maybe I need to add some code/initializing in this place?:
![code_marked](https://cloud.githubusercontent.com/assets/17677787/15582897/933cd40a-2373-11e6-9537-fd5f3f0a6a43.JPG)

If yes, can you suggest me what should I add?

**Comment by nedcrest** [comment]
Oh, I guess I found the mistake: I was trying to tart Window instead of WPF form.
I did start a new pythonWPFproject and it works!))
![woooorks](https://cloud.githubusercontent.com/assets/17677787/15584311/5cca2038-237a-11e6-9c84-611c67e24c71.JPG)

**Comment by zooba** [comment]
Glad to hear it!
