### ISSUE TITLE
syncdb no longer works for Django 1.9+ 

### ISSUE THREAD

**Issue by vanflymen** [Microsoft/PTVS#1336]
Please use `migrate` instead.

**Comment by huguesv** [comment]
Have you tried the latest PTVS that is included with VS 2015 Update 2?  That should have the new Django commands.

![image](https://cloud.githubusercontent.com/assets/1696845/15902761/7a1d89b6-2d5e-11e6-852b-60b9ca9de4cf.png)

**Comment by vanflymen** [comment]
Ah, I looked for an updated PTVS instead of the VS Update. I've installed it and it works fine now. :)
