### ISSUE TITLE
Copying an external file into .pyproj dir while running tests

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/PTVS#1338]
I have a .pyproj which has a test sub folder. There is a common .json file that resides into another directory(in .net test folder outside of this python dir). I want to reuse the same .json in my python test but want to avoid keeping a duplicate copy of that into the python test dir. I've added it as a "Link"(Add->Existing Item->Add as a Link). That shows it in the python project(with the FullPath set to the location of that file in .net folder).

I also want it to get copied locally before my test is run. Is there a way for me to enforce that? 
There is a reason why I cannot have it referenced as a relative path to the actual location of the file in the test code itself. So I'm looking for a way to overcome this limitation.

**Comment by zooba** [comment]
You may be able to enable builds for your project (add `<Target Name="CoreCompile" />` to your `.pyproj` file somewhere) and then [override MSBuild targets](https://msdn.microsoft.com/en-us/library/ms366724.aspx) (probably `AfterBuild` - or you can just do it in `CoreCompile`) to do the copy (plenty of info at that link).

I _believe_ builds will be run before tests, though they may be optimized away sometimes. Currently we don't have an equivalent for C#'s "copy on build" action.

**Comment by zooba** [comment]
That said, you probably _really_ want to do the copy in Python code, as that will also work for anyone who runs tests outside of VS. Though it may be a little more complicated to track down the file in that case.
