### ISSUE TITLE
Default Flask Web Role template does not work in Azure

### ISSUE THREAD

**Issue by lhoang29** [Microsoft/PTVS#1339]
Visual Studio 2015 Update 2
Python Tools 2.2.3 for VS 2015

To repro, in Visual Studio 2015:
1. New Project -> Python -> Azure Cloud Service -> Flask Web Role
2. Install into Virtual Environment, Python 2.7 64-bit
3. Publish to Azure

Web page returns with **500 Internal Server Error**, diagnostics logs shows: **Failed to load role assembly: Microsoft.PythonTools.WebRole, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a**

The entire project including the virtual environment is attached, but this should be easily reproducible from scratch.

[AzureCloudService1.zip](https://github.com/Microsoft/PTVS/files/311029/AzureCloudService1.zip)

**Comment by lhoang29** [comment]
This seems to be true for Visual Studio 2013 with Python Tools 2.2 as well.

**Comment by huguesv** [comment]
Hi!  Please try with Python 2.7 32-bit:
https://github.com/Microsoft/PTVS/wiki/Cloud-Project#webpi-references

**Comment by YoungjaeKim** [comment]
Is this problem solved? I still got this error even though I installed 32bit.

**Comment by zooba** [comment]
Have a look at https://azure.microsoft.com/en-us/documentation/articles/cloud-services-python-ptvs/ especially the updated instructions on how to install Python on a cloud service.

Basically, WebPI turned out to not be as useful as we thought, so we're revising our instructions. It means more work for you, but you'll also get much more control and insight into what's going on.

**Comment by YoungjaeKim** [comment]
Got it. it's working fine but this error message is still recorded in WebRole log. Maybe internal Startup process invokes this module.
 
> Failed to load role assembly: Microsoft.PythonTools.WebRole, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by zooba** [comment]
So we used to be forced to deploy that because everything had to be .NET. Are you able to look on the web role and see if it's there (or in the `.cspack` file - it's just a ZIP)? Maybe we aren't deploying it for some reason...
