### ISSUE TITLE
Default Django Web Role template missing views.py

### ISSUE THREAD

**Issue by lhoang29** [Microsoft/PTVS#1340]
Visual Studio 2015 Update 2
Python Tools 2.2.3 for VS 2015

To repro, in Visual Studio 2015: New Project -> Python -> Azure Cloud Service -> Django Web Role. No views.py is created after this, even though urls.py is importing it. Running locally gives an ImportError.

**Comment by zooba** [comment]
Thanks! Probably our template shouldn't be importing it, since we don't include any actual views. We're about to start a major review of all of our templates for our next release, so it should get fixed as part of that.
