### ISSUE TITLE
is it possible to check whether PTVS Python debugger is attached to process?

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#1347]
The equivalent in C# is like this:

``` csharp
            while (!Debugger.IsAttached)
            {
                Thread.Sleep(100);
            }
```

**Comment by denfromufa** [comment]
and I do not mean ptvsd remote Python debugger, but the regular CPython debugger selected from debugging engines.

**Comment by denfromufa** [comment]
here is related issue:

http://stackoverflow.com/questions/9663040/how-to-check-whether-debugger-of-python-tools-for-visual-studio-is-attached-to-c

**Comment by denfromufa** [comment]
maybe check sys.gettrace()?

**Comment by zooba** [comment]
This isn't guaranteed to keep working, but for currently released versions:

```
import sys
IS_DEBUGGING = '$visualstudio_py_debugger' in sys.modules
```

**Comment by denfromufa** [comment]
@zooba is it possible to scan for this `sys.modules` change in a for loop?

**Comment by zooba** [comment]
There's no need if you want to check whether it was started with the debugger. I'm looking at the native attach code and it seems like this won't work as we never actually add the module to `sys.modules`. Checking whether `sys.gettrace() is not None` is probably the best option here, as I think that's the only visible change we make.

**Comment by denfromufa** [comment]
@zooba no, I want to `sleep()` while debugger is not attached, like in c# code above.

**Comment by zooba** [comment]
Then you'll need to look at `sys.gettrace()`, as you won't see the module appear in an injected debug-attach.

**Comment by denfromufa** [comment]
@zooba I just tested and sys.gettrace() is working! This is very handy:

https://github.com/pythonnet/pythonnet/issues/332#issuecomment-282608123
