### ISSUE TITLE
Use SIO_LOOPBACK_FAST_PATH in debugger

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1350]
Python 3.6 [adds the SIO_LOOPBACK_FAST_PATH flag](http://bugs.python.org/issue26536) for sockets, which dramatically increases the bandwidth for loopback connections (I got >4x on my machine with the test code on the linked issue).

We should enable this flag where possible in our debugger. The functionality has existed since Windows 8, but using it on earlier OSs may cause an exception. It is safe to use if the socket eventually gets a connection from another IP.

**Comment by huguesv** [comment]
Moved to https://github.com/Microsoft/ptvsd/issues/912
