### ISSUE TITLE
Is it possible to run Picamera library on UWP ?

### ISSUE THREAD

**Issue by SergioMasson** [Microsoft/PTVS#1354]
I'm trying to build an application to run the raspberry Pi camera module using the Windows IoT platform, but since the only support I found for the camera was written in Python I've decided to try to make a mixed application using C# for the UI and Python for dealing with the camera. Is it possible? 

Thank you very much.

**Comment by zooba** [comment]
@alanch-ms will know better how this will work. I suspect you'll need to use the IoT Python build and PInvoke into `python35.dll`, which is going to be fairly painful. Using C++ would be easier, but maybe there's another way to make it work (two apps, perhaps?).

**Comment by alanch-ms** [comment]
@SergioMasson , unfortunately, the raspberry Pi camera isn't support on Windows IoT core.  However, USB webcams are supported.  See our sample page on how to access the USB webcam: https://developer.microsoft.com/en-us/windows/iot/win10/samples/webcamsample
