### ISSUE TITLE
Error loading web project

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1360]
Dev15 Preview 3 (using xlab image with it preinstalled, not the low impact)

I'm able to load an empty ASP.NET web project, but Python web projects don't load.
```
---------------------------
Microsoft Visual Studio
---------------------------
The project file 'C:\Users\huvalo\AppData\Local\Temp\g1kivfqy.5rj\Temp\BottleWebProject2.pyproj' cannot be opened.

There is a missing project subtype.
Subtype: '{1b580a1a-fdb3-4b32-83e1-6407eb2722e6}' is unsupported by this installation.
---------------------------
OK   Help   
---------------------------
```

**Comment by zooba** [comment]
This appears to be devenv /setup issue. I reproduced it with the latest build, but a proper install fixed it.

**Comment by huguesv** [comment]
On latest from master, when I run in Exp, and the first thing I do starting VS is load a bottle project, I get the error.  I tried making sure my MEF cache gets rebuilt by deleting the folder here:
