### ISSUE TITLE
File has invalid module name

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1376]
I see this after opening a django project, in the Output window Tests pane.
```
------ Load Playlist started ------
========== Load Playlist finished (0:00:00.0020016) ==========
------ Discover test started ------
File has an invalid module name: C:\Users\huvalo\Documents\Visual Studio 2015\Projects\DjangoWebProject2\DjangoWebProject2\app\migrations\0001_initial.py
========== Discover test finished: 3 found (0:00:03.3397661) ==========
```

**Comment by zooba** [comment]
No way around this, unfortunately. Either we make people start opting individual files into have tests detected, or stop warning people when they've made a file that can't have tests in it.

If there's a third option I've missed, please reopen and suggest it.
