### ISSUE TITLE
Unable to update from 2.2.3 to 2.2.4 from VS

### ISSUE THREAD

**Issue by AndriySvyryd** [Microsoft/PTVS#1377]
Using VS 2015 U3 25420 
Click "Update" in the "Extensions and Updates" dialog.

The UPDATE button is disabled, see screenshot.
![updateissue](https://cloud.githubusercontent.com/assets/6539701/16318086/50640362-3942-11e6-8b74-5d6a578d7249.jpg)

**Comment by zooba** [comment]
I guess you're already up to date, and this will just let you remove it?

What version do you see for Python Tools in Programs & Features?

**Comment by AndriySvyryd** [comment]
It says 2.2.4, but I don't think VS picked it up, because I still experience https://github.com/Microsoft/PTVS/issues/1355

**Comment by zooba** [comment]
Certainly looks like an install issue. Can you remove and then reinstall via Modify on VS 2015?

**Comment by zooba** [comment]
Actually, depending on when you installed, you might have old bits. After uninstalling, go to `C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller\14.0\installers` and delete all the folders starting with `PythonTools`

**Comment by zooba** [comment]
No, it's my fault, I didn't update the version listed in the vsixmanifest file before putting out the 2.2.4 build. I'll make another one with the fix

**Comment by zooba** [comment]
@AndriySvyryd I've updated the published file, so if you delete the cached one and reinstall you should be fine.
