### ISSUE TITLE
Ability to have Tab Depth Indicators

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/PTVS#1381]
Feature request.  Take a look at the F# Power Tools.  Python is a tab oriented language syntactically and this would make a world of difference for readability.

**Comment by zooba** [comment]
Do you mean like [Indent Guides](https://visualstudiogallery.msdn.microsoft.com/e792686d-542b-474a-8c55-630980e72c30)? I don't see anything on the F# Power Tools that looks like "Tab Depth Indicators" - perhaps you could post a screenshot?
