### ISSUE TITLE
Feature: Interactive Coding while in Debug

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/PTVS#1382]
Would be really nice to have this option.  I'm working on a multi-nested loop, hit a break point, be great to try out a few options right there, get it fixed, and keep moving.

**Comment by smortaz** [comment]
have your checked out the "Debug Interactive" feature?

https://github.com/Microsoft/PTVS/wiki/Debugging

**Comment by denfromufa** [comment]
I think this refers to "Edit and Continue" available for C#, VB.NET, and C++:

https://github.com/Microsoft/PTVS/issues/77

**Comment by Leeyaa** [comment]
this question was raised about 3 years ago ,i wonder if the ENC available now?
