### ISSUE TITLE
Load wpf libraries outise visual studio

### ISSUE THREAD

**Issue by IlanHindy** [Microsoft/PTVS#1383]
Hi,
I use PTVS. and I want to document the code with sphinx.
The problem is that sphinx try's to load the modules I wrote but it fails
to load the modules in which there is an import for the .net libraries (probably because
there is no appropriate path or something like that)
The problem also occurs when I try to load such a module in Visual Studio IronPython Interactive window
Is there a solution to this problem?
Thanks,
Ilan Hindy

**Comment by IlanHindy** [comment]
I found the way to activate the python outside the visual studio (using add reference etc..)
but in order to activate sphinx I need 2 things:
1. set the default directory to Iron python directory and I did that
2. set IronPython the default python program that meens that when I print python the iron python 
will be activated . The problem is that the name of the iron python program is ipy and not python
I tried to use windows set command but it didn't work

**Comment by zooba** [comment]
Glad you figured out the references.

I'm afraid I can't help with the Sphinx problem, but I see you've already posted on the sphinx-users mailing list, so I'm sure somebody will be able to help you there.

(Feel free to reopen if you think you need more help from our side.)
