### ISSUE TITLE
MSVS 2015 Update 3 does not work with PTVS

### ISSUE THREAD

**Issue by ehoeks** [Microsoft/PTVS#1388]
Python tools seems to be broken. It’s still showing 2.2.3 is currently installed and update 2.2.4 is availiable. But during installation “Update” button is gray that makes update not possible

**Comment by zooba** [comment]
We accidentally published a release with the wrong version number in Extensions and Updates. This triggers the notification, even though you've got 2.2.4 installed (see Help/About).

A fix was published last week - before it was released - but it seems people are still getting the earlier version somehow (probably a CDN issue). If you install the 2.2.4 release from [the releases page](https://github.com/Microsoft/PTVS/releases) you'll get the version number fix and won't see the notification any more.

(Uninstalling and reinstalling through the VS installer does not work because of the caching done by the installer.)

**Comment by ehoeks** [comment]
Thank you for the very fast reaction. This kind of slip-ups can happen to anybody.

But, after the install of 2.2.4 from the release page I still have an error loading the plugin.


![error](https://cloud.githubusercontent.com/assets/10461844/16481164/0502c620-3eaa-11e6-8ae7-189955279b24.png)


  <entry>
    <record>398</record>
    <time>2016/06/30 06:13:29.265</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [Python Tools Package]Source: &apos;Microsoft.VisualStudio.Composition&apos; Description: Expected 1 export(s) with contract name &quot;Microsoft.PythonTools.Interpreter.IInterpreterOptionsService&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name &quot;Microsoft.PythonTools.Interpreter.IInterpreterOptionsService&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()&#x000D;&#x000A;   at Microsoft.PythonTools.PythonToolsService..ctor(IServiceContainer container)&#x000D;&#x000A;   at Microsoft.PythonTools.PythonToolsPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{6DBD7C1E-1F1B-496D-AC7C-C55DAE66C783}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>399</record>
    <time>2016/06/30 06:13:29.280</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [Python Tools Package](null)</description>
    <guid>{6DBD7C1E-1F1B-496D-AC7C-C55DAE66C783}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>400</record>
    <time>2016/06/30 06:13:29.282</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [Python Tools Package]</description>
    <guid>{6DBD7C1E-1F1B-496D-AC7C-C55DAE66C783}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by zooba** [comment]
This is an occasional upgrade issue that we haven't been able to track down. VS keeps a cache of loaded assemblies that doesn't always get invalidated when it should.

If you delete `C:\Users\You\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache` and restart you should be fine.

**Comment by huguesv** [comment]
@zooba FYI RTVS added setup custom action to wipe that folder, as a workaround to that occasional bug.
https://github.com/Microsoft/RTVS/blob/master/src/SetupCustomActions/CustomAction.cs#L66

**Comment by Kitemaker** [comment]
@zooba 
I had same issue. I removed "ComponentModelCache " and it works now. Thanks!!   !:)
