### ISSUE TITLE
IPython interactive PTVS 2.0

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#139]
Hi

I have Anaconda (x86) with PTVS 2.0 (due to a intellisense crash in 2.1 - see http://pytools.codeplex.com/workitem/3021, and I found 2.2 beta had some issues).

When I try to use the IPython interactive environment, I get the following error:

The Python REPL process has exited
Error using selected REPL back-end:
cannot import name ShellChannel
Using standard backend instead

Is this issue known/fixed in later versions? Please let me know if you would like more information.

Thank you.

**Comment by zooba** [comment]
Yes, this is because IPython 3.0 changed their public API and we need to update to fix it.

We don't have any current releases with the fix, but there will be a dev build coming soon. The fix is already checked in.
