### ISSUE TITLE
Port selector dialog for this transport. Not implemented

### ISSUE THREAD

**Issue by rajivharris** [Microsoft/PTVS#1390]
I have deployed a django application in IIS (dev server not azure), using PTVS tools published in debug mode. I am able to connect to the ptvsd endpoint using the url http://server/application/ptvsd. 
When I try to remote debug the application from VS 2015 - update 3 with PTVS tools 2.4.4.

I am getting the following error

**"Error displaying the Port Selector dialog for this transport. Not implemented"**

Server : Windows Server 2012 R2 Standard
Web Sockets : Enabled
pip installed ptvsd
Client : Windows 7
VS version : VS 2015 update 3
PTVS version : 2.2.4

**Comment by int19h** [comment]
You're probably trying to click on the "Find" button after putting the URL into the Qualifier textbox. That button is, indeed, not implemented for PTVS remote debugging (it's meant to provide a UI to locate and select known servers). In order to get the dialog to refresh using the URL that you've typed, just press Enter in the textbox instead.

**Comment by rajivharris** [comment]
Thanks for the reply.

Now i get a different error

"Unable to connect to 'wss://<my debug secret>@<server/application/ptvsd>'. Operation is not supported on this platform."

**Comment by int19h** [comment]
Websockets (ws:// and wss:// schemas) are only supported on Win8 and above, unfortunately.

But if you're trying to debug on the same machine where server is running on, or even a different machine which is on the same network, you should be able to avoid websockets entirely, and use the standard ptvsd protocol (i.e. just call ptvsd.enable_attach explicitly from your Python code, and use tcp:// URI when attaching - no need for anything in web.config etc). Websockets are only really needed when the server is behind a firewall and/or proxy, and the only way to connect to it at all is via HTTP.

**Comment by rajivharris** [comment]
Thanks @int19h . I will close the issue.

**Comment by sartys** [comment]
So, what is _working_ version of ptvsd for VS2015? I have 3.2.1 and it doesn't work.
