### ISSUE TITLE
Loadfailed after Update 3 installed. Expected 1 export(s) with contract name but found 0

### ISSUE THREAD

**Issue by spSerg** [Microsoft/PTVS#1391]
LegacySitePackage failed for package [Python Tools Package]Source: 'Microsoft.VisualStudio.Composition' Description: Expected 1 export(s) with contract name "Microsoft.PythonTools.Interpreter.IInterpreterOptionsService" but found 0 after applying applicable constraints. Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.PythonTools.Interpreter.IInterpreterOptionsService" but found 0 after applying applicable constraints. at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition) at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality) at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName) at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName) at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]() at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]() at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]() at Microsoft.PythonTools.PythonToolsService..ctor(IServiceContainer container) at Microsoft.PythonTools.PythonToolsPackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)

**Comment by spSerg** [comment]
Just deleted folder of VS appdata (c:\Users\root\AppData\Local\Microsoft\VisualStudio\14.0), and started VS again. Also was required  to restore all else extensions.

**Comment by zooba** [comment]
For future reference, you only need to delete the `AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache` folder to resolve this error.

**Comment by assetozen** [comment]
@zooba 
you saved my life too 

tnx man

**Comment by RhealShailendra** [comment]
When we are trig to open project in VS 2015 we are getting message as "Expected 1 export(s) with contract name Microsoft.Internal.VisualStudio.PlatformUI.ISolution Attached Collection Service but found 0 after applying applicable constraints".
However we are facing this issue. This issue reflecting after windows update.

**Comment by RMMamun** [comment]
Thanks zooba, I just faced the problem with VS 2017 and sold by your help. I just deleted the folder - AppData\Local\Microsoft\VisualStudio\15.0\ComponentModelCache


Thanks again.

Rashed from Bangladesh

**Comment by oguzhankircali** [comment]
@zooba You saved my time by coming from 2016.
Thank you very much.

**Comment by charulathakrishnamoorthy** [comment]
Yes, its working fine now after deleted the ComponentModelCache folder, thank you so much!
