### ISSUE TITLE
pip IronPython and PTVS on VS 2015 doesn't seem to work well

### ISSUE THREAD

**Issue by HarelM** [Microsoft/PTVS#1397]
I tired to look for an issue because I don't think I'm the first one to encounter it but I couldn't find one.
Here are the step I did:
1. Install latest visual studio 2015 community Version 14.0.25421.03 Update 3 with PTVS (To be honest it was already installed) 
2. Install latest IronPython - 2.7.5 (to program files - I know this creates an issue with admin rights).
3. Try and install html5lib from VS environment (right click the "python environment" on an IronPython vs project).
![image](https://cloud.githubusercontent.com/assets/3269297/16540368/50d20ce2-406b-11e6-991e-def5ee2746bf.png)
I get this output:

```
Restarting IronPython with -X:Frames
Installing with ensurepip
Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking setuptools
Downloading/unpacking pip
Installing collected packages: setuptools, pip
Successfully installed setuptools pip
Cleaning up...
Downloading/unpacking pip from https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
Downloading/unpacking setuptools from https://pypi.python.org/packages/d7/3d/577bafbfc9fcd78ed7b45de24a6bc30a94cc75cbde786389f1014d433614/setuptools-23.1.0-py2.py3-none-any.whl#md5=bdffb519c49d6bf3aae47f8f1a6ea3b5
Downloading/unpacking wheel
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
  Found existing installation: setuptools 3.6
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed pip setuptools wheel
Cleaning up...

Installation Complete
C:\Program Files (x86)\IronPython 2.7\Lib\weakref.py:1: DeprecationWarning: object.__init__() takes no parameters for type KeyedRef
  """Weak reference support for Python.
C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py:1: DeprecationWarning: object.__new__() takes no parameters
  # urllib3/connectionpool.py
C:\Program Files (x86)\IronPython 2.7\Lib\weakref.py:1: DeprecationWarning: object.__init__() takes no parameters for type KeyedRef
  """Weak reference support for Python.
'pip' was installed successfully.
Installing 'html5lib'
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 170, in run_module
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 101, in _get_module_details
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 456, in get_loader
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 466, in find_loader
  File "C:\Program Files (x86)\IronPython 2.7\Lib\pkgutil.py", line 422, in iter_importers
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\__init__.py", line 13, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\exceptions.py", line 6, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\six.py", line 701, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pip\_vendor\six.py", line 692, in exec_
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 109, in _get_module_details
AttributeError: 'module' object has no attribute '_getframe'
```

I know this is related to the -X:Frames flag which I found in various places but I have configured it in the interactive window settings but I'm not sure it applies to pip.

I have managed to do it from outside visual studio using regular command line so I don't think this is an IronPython issue as far as I can understand.
I'm very new to python but extremely familiar with Visual Studio (C#, C++, TypeScript, etc...)

**Comment by HarelM** [comment]
More investigation:
When letting visual studio install pip and trying to using it afterwards from command line outside visual studio I get this error:
```
c:\Program Files (x86)\IronPython 2.7>ipy -X:Frames -m pip install html5lib
Unhandled exception:
Traceback (most recent call last):
  File "c:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 170, in run_module
  File "c:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_module_details
ImportError: No module named urllib; 'pip' is a package and cannot be directly executed
```

This does not happen if I install pip from command line which makes me think that there might be a problem with the pip VS is installing...?

Please let me know if I'm doing something incorrect...

**Comment by zooba** [comment]
It's possible that when we update pip we get a version that isn't compatible with IronPython. The first log shows that we're jumping ahead a lot of versions. Unfortunately, I don't think the old version of pip will actually work anymore, as PyPI has had some changes.

I don't think you're doing anything incorrect, you're just doing something that's fairly uncommon. There is a *very* small community trying to use pip with IronPython and an even smaller one trying to keep them compatible. Probably it's going to require someone to dig through and diagnose all the issues, then submit a PR to pip to get support again.

The `-m pip` error might be an IronPython bug or a pip bug. Generally `-c "import pip; pip.main()"` is a direct replacement for `-m pip` here.

**Comment by HarelM** [comment]
So why not just disable pip when using IronPython?

**Comment by zooba** [comment]
@HarelM Mostly out of hope that one day they get it to work (it really just needs `six` to fix their bug and `pip` to start including that version), and then we won't have to do anything else to enable it. If we disabled it completely, it could be fixed tomorrow and if we don't do any more updates then nobody can use it.

**Comment by igitur** [comment]
If `pip` or `six` is so buggy, what is the recommended way to install packages in `IronPython`?

**Comment by HarelM** [comment]
Our company had an extensive research on that matter and the bottom line is: don't use IronPython...

**Comment by zooba** [comment]
Right now there's a lot of the PyPI ecosystem that won't work in IronPython anyway, so most people tend to end up managing their own .NET dependencies manually. We'd love to see this improved, but there are a lot of pieces involved and it's really up to the IronPython community to find the model they'd like to work with (it's likely that conda would actually work well).

**Comment by wwaller** [comment]
I'm confused here. Python Tools was advertised on the first page of "relevant/reccommended" extensions for VS2015 when you go to the extensions page. I'm trying to use pyhue to communicate with the Hue API and I thought writing a WPF application in Python would be neat, and it was obviously on the front page of the extensions store so it must be a glowing experience. But if I can't even use pip from the environments page, what *can* you do?

**Comment by zvacha** [comment]
HarelM, were you able to find a solution to 
"AttributeError: 'module' object has no attribute '_getframe'" 
I tried installing without using pip  (using setup.py) but no success

**Comment by HarelM** [comment]
Actually, I don't remember, but we couldn't use other libraries we needed so we stopped trying making it work.
