### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by IlanHindy** [Microsoft/PTVS#1401]
What is the common way to document project written in IronPython in visual studio

**Comment by zooba** [comment]
The "in Visual Studio" part has no impact here - all Python code is documented with docstrings. I'd suggest looking into the style guides (e.g. numpy-style and Google-style are popular) and tools (e.g. sphinx, epydoc) for those.

Bear in mind that the tool creators have probably not tested them against IronPython, so if they don't work well you'll need to file bugs (or submit fixes) to those projects.

**Comment by IlanHindy** [comment]
sphinx has to be operated using IronPython because it imports the modules in order to get the doc strings and IronPython uses libraries(clr) that are not found in any other pythom implementation
my solution was to activate the sphinx as a project in visual studion
Thanks,
Ilan
