### ISSUE TITLE
improving new environment creation process

### ISSUE THREAD

**Issue by ryansmccoy** [Microsoft/PTVS#1402]
i have same env folder:

%anaconda%\env\py27
%anaconda%\env\py35

but when i add new one it always starts in "This PC" ... and i open dialog, navigate to my new env folder, then have to auto detect and go through all menus and select new environment folder... so much work! why not set default folder for new environments to last folder used, or even better auto-detect a new environment by searching the %anaconda%\env ...

**Comment by zooba** [comment]
We'd love to have special support for Anaconda here, but haven't had the time to make it happen.

Remembering the previous folder when browsing should be fairly straightforward here, though we do share a decent chunk of this code throughout the product, so there'll be more flow-on effects that may be expected.

**Comment by huguesv** [comment]
We auto detect conda environments now :)
