### ISSUE TITLE
Install pip with IronPython

### ISSUE THREAD

**Issue by IlanHindy** [Microsoft/PTVS#1410]
Hi,
I want to install projects using pip. I did the following:
1. opened python environment
2. installed pip from there
    I got the following message
Failed to upgrade pip, which is probably because of IronPython. Leaving the earlier version.
----- Successfully installed pip -----
(I am using IronPython 2.7.5)
3. searched a module six
4. pressed install of the module from the list
  I got the following
ImportError: No module named pip
----- Failed to install 'six' -----
What went wrong ? 
Thanks,
Ilan

**Comment by IlanHindy** [comment]
I found the problem It was because the directory was write protected
I released it and successfully installed pip (It had no errors and I saw it in the site-packeges directory)
I tried to install a module but It wrote the following error:
`AttributeError: 'module' object has no attribute '_getframe'
I know that this is because I have to operate iron python with the -X:FullFrames flag
My question is where I have to put it I tried to put it in the following locations:
In the project configuration > debug
In tools > options > Python Tools > interactive windows > interpreter options
but it did not work
Can you help?
Thanks
Ilan

**Comment by zooba** [comment]
As much as I'd like six to just remove the dependency on `_getframe`, it seems we'll have to add some magic for running pip with `-X:Frames` in IronPython.

Luckily, we can do that fairly easily now that package management is per-environment.
