### ISSUE TITLE
VS2015 initially fails to load project created using PTVS2.2.4. Okay for inbuilt projects.

### ISSUE THREAD

**Issue by tsweeney2016** [Microsoft/PTVS#1411]
Launching  a VS2015 Solution by clicking on the solution file in Windows Explorer results in the Project within failing to load. Right clicking the project in Solution Explorer and select Reload Project loads it correctly. But is you save all and try to launch again the same way it occurs again.
Only occurs with projects created using PTVS2.2.4 and not other inbuilt types such as Visual C#.

Issue does not occur is you open up VS2015 and then load solution from File menu.
Issues even occurs with unmodified New Projects.

**Comment by melak47** [comment]
I get this as well, with the following error in the output log:

    D:\python\App\App\App.pyproj : error  : Object reference not set to an instance of an object.

**Comment by traits** [comment]
Same here (VS2015 Update 3): 
For a specific solution, either all the projects fail, occasionally only the last one in the list does, or all projects are loaded successfully.

**Comment by zooba** [comment]
Thanks. I think I know why this is occurring (VS team asked us to make a change to when we load our extension at startup, and when you double-click the project is now loaded too early), but not sure how to resolve it right now without simply undoing that change (which was also the fix to #1117).

If/when we are able to resolve this, there'll be a update notification shown in VS, so just keep an eye out for that.

**Comment by hungclues** [comment]
Whether fully resolved not know, leave a message on a shared dimension.

When I opened *.pyproj by 'Notepad++', is to 'UTF-8-BOM'.
I saved changes to it as 'UTF-8 without BOM' project opens normally.

I hope these comments are helpful.

**Comment by tsweeney2016** [comment]
Hi hungclues.
 Unfortunately, changing the encoding of he project file does not resolve
my issue.
Hopefully it is resolved with an update.

**Comment by zooba** [comment]
Fix has been merged and will be available when we release our next update.

**Comment by tsweeney2016** [comment]
Thanks Steve.
