### ISSUE TITLE
Upon remote debugging PTVSD does not break into the debugger

### ISSUE THREAD

**Issue by FeydCron** [Microsoft/PTVS#1412]
### Problem

After I successully attached the Debugger via Transport "Python remote (ptvsd)" to a quite simple python script that is running on a remote machine (raspberry pi, Python 3.2.3) the PTVSD does not break into the Debugger even though a breakpoint has been set.

Everything else seems to be ok: I can set breakpoints and they seem to be active (red filled circle) and I can see that the console output of my script which appears in the debugger output window.
Actually, only hardcoded breakpoints in the shape of "ptvsd.break_into_debugger()" seem to work. Also waiting for the Debugger until being attached using "ptvsd.wait_for_attach()" is working well.

I took a closer look at the tcp Connection using wireshark even though I am not familiar with the protocol. Anyway, I discovered the following sequences on the wire:
- "brkr" probably upon removing a breakpoint from the python script
- "brkp" probably upon setting a breakpoint in the python script

and
- "BRKF" following a 64-bit value of 2

Is this an error indication? There is no feedback in Visual Studio indicating that something might went wrong with setting the breakpoint.
### Debugger Machine

A upgraded Windows 10 (from Windows 8.1), German)

VS 2015 Microsoft Visual Studio Community 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installierte Version: Community
...
Python Tools for Visual Studio   2.2.40623.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40623.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40623.00
Profiling support for Python projects.
...
### Debuggee Machine

Raspberry Pi, Debian wheezy, created from a NOOBS Image

Python 3.2.2

PTVSD 2.2.0 installed via PIP

**Comment by zooba** [comment]
Yeah, `BRKF` means the breakpoint failed to bind. I'm not sure why we aren't reporting that on the VS side (I haven't worked on this part of the project for a while).

Looking at `visualstudio_py_debugger.py` at the `try_bind_break_point` function, it seems we're comparing two paths as strings without normalizing between OSs - though this has definitely worked in the past so presumably I'm missing something here.

One of the larger tasks I've wanted to do is to refactor the debugger completely to (among other things) better handle filename comparisons. I suspect that may be the problem here.

@int19h - any other insight?

**Comment by int19h** [comment]
`AD7Engine.OnBreakpointBindFailed` is a no-op, and seems to have been the way since forever. It appears that the message name is really a misnomer, because the comment at the point where it's sent indicates that we actually treat it as "breakpoint is pending" - i.e. it couldn't be set because the corresponding module wasn't found, so we assume that the module simply hasn't been loaded yet. On VS side, the breakpoint will be seen as unbound, which is observable if you expand it in the Breakpoints window (bound breakpoints will have one child, unbound ones will have none).

**Comment by int19h** [comment]
And yes, it does seem that we basically never treat breakpoints as bound when paths don't match exactly (e.g. for remoting). This doesn't preclude us from reporting them as hit, though.

So the real question here is why we never call `report_breakpoint_hit` from `handle_line`.

@FeydCron, can you provide some more details about your code and the environment? Ideally, some sample lines of code where you're setting breakpoints, and what the full pathnames of source files look like on your local machine and on the remote one.

**Comment by FeydCron** [comment]
Hi Pavel,

sorry for the late answer. Here are the additional information you
requested. Attached please find the python script, I used for testing
debugging as well as a wireshark capture of a debug session.
I think I tried to put the breakpoint at line 22 or 23 of the debugtest.py
script. Anyway, the correct line numbers should appear anywhere in the
capture file.

As I already mentioned, in VS the breakpoint appeared as a filled red
circle - there was no hint that the breakpoint was not active.
The "ptvsd.wait_for_attach()" and "ptvsd.break_into_debugger()"
instructions worked well.

Path information of the python script:
Local path: D:\GitHub\RasPyWeb\berry\debugtest.py
Remote path: /home/pi/berry

Best regards,
FeydCron



2016-07-14 23:00 GMT+02:00 Pavel Minaev <notifications@github.com>:

> And yes, it does seem that we basically never treat breakpoints as bound
> when paths don't match exactly (e.g. for remoting). This doesn't preclude
> us from reporting them as hit, though.
>
> So the real question here is why we never call report_breakpoint_hit from
> handle_line.
>
> @FeydCron <https://github.com/FeydCron>, can you provide some more
> details about your code and the environment? Ideally, some sample lines of
> code where you're setting breakpoints, and what the full pathnames of
> source files look like on your local machine and on the remote one.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/PTVS/issues/1412#issuecomment-232791012>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANdFTHURoEIfZFFIqGNn9Nh57xtoZ4qTks5qVqOAgaJpZM4JITsk>
> .
>

﻿import ptvsd
ptvsd.enable_attach("debug")

import threading

def main():
	global nCount

#	ptvsd.wait_for_attach()
#	ptvsd.break_into_debugger()
	
	nCount = 0
	threading.Timer(2.0, onTimer).start()   

	return

def onTimer():
	global nCount

#	ptvsd.break_into_debugger()

	nCount += 1
	print("onTimer is running for " + str(nCount) + " times - waiting 2 seconds ...")
	threading.Timer(2.0, onTimer).start()
	return

if __name__ == '__main__':
	main()

**Comment by KronosKoderS** [comment]
I'm having a similar issue.  Unfortunately, I can't share the code being used, but I'm trying to remotely debug python scripts running on a Red Hat Server and Python 2.6.  Break points are working correctly, and so is attaching to the target.  However, when trying to run the debugger interactive, the connection doesn't appear to be working.

**Comment by zooba** [comment]
@KronosKoderS If breakpoints are working then your issue is probably different from this one. Please file a new issue with as many steps for us to follow as you can provide.

**Comment by zooba** [comment]
@FeydCron I don't have line numbers on your code file - are you setting the breakpoint inside the `onTimer` function? That seems to be a much more specific issue than if you are also having trouble in `main()`.

We have to do some monkeypatching to be able to debug new threads, which it's possible that the `Timer` class bypasses. In that case, I'd expect to not be able to debug the code.

**Comment by zooba** [comment]
Looks like we should use `threading.settrace()` to set the trace function for all threads, rather than monkeypatching. (I'm not entirely sure why we didn't start with that function... maybe it's new in Python 3?)

**Comment by ZSkowronS** [comment]
The tag on this issue is "enchancement", but it should be "bug".
It makes remote debugging practically useless.

**Comment by zooba** [comment]
It's an enhancement because the task we need to do is add new support for debugging `threading.Timer`.

If you are having trouble, please file a new bug with the details.

**Comment by huguesv** [comment]
We have a new debug engine in the 15.8 release, if you still see this problem, please open an issue at https://github.com/Microsoft/ptvsd
