### ISSUE TITLE
Editor or Editor Extension

### ISSUE THREAD

**Issue by xiongshi08** [Microsoft/PTVS#1415]
<time>2016/07/09 05:35:03.254</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: &#x672A;&#x5C06;&#x5BF9;&#x8C61;&#x5F15;&#x7528;&#x8BBE;&#x7F6E;&#x5230;&#x5BF9;&#x8C61;&#x7684;&#x5B9E;&#x4F8B;&#x3002;&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.Extensions.GetAnalyzer(ITextBuffer buffer, IServiceProvider serviceProvider)&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.PythonClassifier..ctor(PythonClassifierProvider provider, ITextBuffer buffer)&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.PythonClassifierProvider.GetClassifier(ITextBuffer buffer)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)</description>
  </entry>
  <entry>
    <record>470</record>
    <time>2016/07/09 05:35:03.285</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: &#x672A;&#x5C06;&#x5BF9;&#x8C61;&#x5F15;&#x7528;&#x8BBE;&#x7F6E;&#x5230;&#x5BF9;&#x8C61;&#x7684;&#x5B9E;&#x4F8B;&#x3002;&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger..ctor(PythonToolsService pyService, ITextBuffer buffer)&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.OutliningTaggerProvider.CreateTagger[T](ITextBuffer buffer)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>471</record>
    <time>2016/07/09 05:35:03.332</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: &#x672A;&#x5C06;&#x5BF9;&#x8C61;&#x5F15;&#x7528;&#x8BBE;&#x7F6E;&#x5230;&#x5BF9;&#x8C61;&#x7684;&#x5B9E;&#x4F8B;&#x3002;&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.Extensions.GetAnalyzer(ITextBuffer buffer, IServiceProvider serviceProvider)&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.Extensions.GetAnalyzer(ITextView textView, IServiceProvider serviceProvider)&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.Intellisense.IntellisenseControllerProvider.TryCreateIntellisenseController(ITextView textView, IList`1 subjectBuffers)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseManagerConnectionListener.&lt;&gt;c__DisplayClass8_1.&lt;SubjectBuffersConnected&gt;b__1(IIntellisenseControllerProvider provider)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)</description>
  </entry>
  <entry>
    <record>472</record>
    <time>2016/07/09 05:35:04.676</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>PERF: Shell start. 10240 ms</description>
  </entry>
  <entry>
    <record>473</record>
    <time>2016/07/09 05:35:04.973</time>
    <type>Information</type>
    <source>VSPackage</source>
    <description>Should automatically check for an update</description>
  </entry>
  <entry>
    <record>474</record>
    <time>2016/07/09 05:35:04.973</time>
    <type>Information</type>
    <source>VSPackage</source>
    <description>Next update check in &apos;83796382&apos; ms </description>
  </entry>
  <entry>
    <record>475</record>
    <time>2016/07/09 05:35:04.989</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: &#x672A;&#x5C06;&#x5BF9;&#x8C61;&#x5F15;&#x7528;&#x8BBE;&#x7F6E;&#x5230;&#x5BF9;&#x8C61;&#x7684;&#x5B9E;&#x4F8B;&#x3002;&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.Extensions.GetAnalyzer(ITextBuffer buffer, IServiceProvider serviceProvider)&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.PythonClassifier..ctor(PythonClassifierProvider provider, ITextBuffer buffer)&#x000D;&#x000A;   &#x5728; Microsoft.PythonTools.PythonClassifierProvider.GetClassifier(ITextBuffer buffer)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)</description>
  </entry>

**Comment by xiongshi08** [comment]
This error will occur as long as you open the project that did not close the PYTHON file.

**Comment by zooba** [comment]
Like #1411, this is also because we're now loading our package later and so our service is not available this early.

**Comment by xiongshi08** [comment]
Trouble to release the new version, I do not compile the environment, thank you!

**Comment by zooba** [comment]
The fix has been merged and will be released as part of our next update.
