### ISSUE TITLE
Corrupted environment after saving a Flask project

### ISSUE THREAD

**Issue by stenci** [Microsoft/PTVS#1429]
### Problem
1. Start Visual Studio
2. Create a new Flask web project
3. Click on "install into a virtual environment" and then click on Create. At this point Visual Studio downloads and installs all the required dependencies and creates a virual environment
4. Press F5 and the server starts and the browser can navigate through the 3 default pages. Great!
5. Press Ctrl+Shift+S to save the project and click on Save to save to the default folder
6. Press F5 and the server does not start. An error message about the environment being incorrectly configured or missing appears. I tried the same steps a few times, and sometimes at this point instead of the error message I get a Python crash.

If I close and restart VS and reopen the project just saved, the solution explorer shows the environment env previously created, but there are no modules in it.
### Workaround

Create a new environment:
1. Close and reopen Visual Studio and reload the project
2. Right click on the corrupted env environment and delete it
3. Right click on the Python Environment tree element and add an environment

**Comment by zooba** [comment]
What version of Python are you using? Have you installed `virtualenv` - if so, which version?

**Comment by stenci** [comment]
I have Anaconda 2.5.0 32 bit with Python 3.5.1.

I installed it a few months ago and I don't remember installing `virtualenv`. I don't use it because I work with a few apps, all with the same configuration.

**Comment by huguesv** [comment]
This is due to creating the project in temp directory.

**Comment by zooba** [comment]
Specifically, it's because the project is default created in Temp and has not been saved yet. When you save the project, it gets copied into the actual project directory, but it won't copy a virtual environment at that point.

It's probably easiest to force people to save their project before creating a virtual environment.
