### ISSUE TITLE
Try to launch PyLint crashes my PTVS

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1434]
It was the first time I try to launch PyLint, so PTVS proposes me to install it. It installed PyLint 1.6.2.

Just after that (3 seconds), PTVS crashed:
![image](https://cloud.githubusercontent.com/assets/1050156/16885157/1584767c-4a82-11e6-848f-76251cc54324.png)

After restarting, I tried again but crashes each time.

Using a Venv Python 3.5 on PTVS 2.2.40315.00 and VS 14.0.25123.00 Update 2

**Comment by lmazuel** [comment]
I'm currently updating to test on newer version

**Comment by zooba** [comment]
You should have error messages in Event Viewer under the Application log. If you could copy those into the issue it'll probably be really easy to fix this.

**Comment by lmazuel** [comment]
Still broken with PTVS 2.2.40623.00 and VS 14.0.25422.01 Update 3

You mean this:
![image](https://cloud.githubusercontent.com/assets/1050156/16887003/60385b20-4a8c-11e6-95c3-6d288a954c6f.png)

You need details view of the three?

**Comment by zooba** [comment]
Just the one with the call stack in it - there's probably a ".NET Runtime" event nearby with it.

**Comment by lmazuel** [comment]
Error Handler Exception: System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.PipeException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes) --- End of inner exception stack trace --- at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) at System.ServiceModel.Channels.ConnectionStream.EndRead(IAsyncResult asyncResult) at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult) --- End of inner exception stack trace --- at System.Net.Security.NegotiateStream.EndRead(IAsyncResult asyncResult) at System.ServiceModel.Channels.StreamConnection.EndRead() --- End of inner exception stack trace --- at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message) at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext) at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext) \r\n at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message) at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext) at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext)

**Comment by lmazuel** [comment]
Don't know how to present this better :(

**Comment by lmazuel** [comment]
There is a .NET Runtime 3 minutes before:

Error Handler Exception: System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.PipeException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes) --- End of inner exception stack trace --- at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) at System.ServiceModel.Channels.ConnectionStream.EndRead(IAsyncResult asyncResult) at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult) --- End of inner exception stack trace --- at System.Net.Security.NegotiateStream.EndRead(IAsyncResult asyncResult) at System.ServiceModel.Channels.StreamConnection.EndRead() --- End of inner exception stack trace --- at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message) at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext) at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext) \r\n at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result) at System.ServiceModel.Channels.TransportDuplexSessionChannel.EndTryReceive(IAsyncResult result, Message& message) at System.ServiceModel.Dispatcher.DuplexChannelBinder.EndTryReceive(IAsyncResult result, RequestContext& requestContext) at System.ServiceModel.Dispatcher.ErrorHandlingReceiver.EndTryReceive(IAsyncResult result, RequestContext& requestContext)

**Comment by zooba** [comment]
I normally find-replace `" at "` with `"\r\n at "` and then embed the whole thing in triple backquotes.

The latter looks like ours, but unfortunately it's not at all obvious what the cause is. Still, I can try and repro it (or if you want to dig deeper and figure it out, I can help point you in the right direction?)

**Comment by lmazuel** [comment]
I'm always glad to help, but here I don't code C#, I'm not sure I have the necessary skill right now to dig deeper... :(

**Comment by int19h** [comment]
I tried to repro this with either or both windows not open at VS startup, but no lock so far.

The code that deals with the Error List ultimately just uses `ErrorListProvider`. It's not documented to throw, but perhaps it could. We could do defensive try/catch around the invocation of its constructor - but it's not clear what to catch.

For the output window, we do throw `InvalidOperationException` if we couldn't obtain `SVsOutputWindow`, or if we couldn't create the desired output window pane. We could handle this as well.

Although in both cases, it's not clear why any of these would fail in the first place; and if they do, the real root cause would be the reason for that failure. We should be able to show error list & output if they aren't there yet.

**Comment by zooba** [comment]
@int19h I agree, but I want the errors to go away :)

I'll add some general error handling. We can't do anything useful if this fails, and the E_FAIL error code isn't helpful for anyone, so may as well just suppress it.

**Comment by zooba** [comment]
Actually, the original issue has no relation to the one I linked, so really we should have a new issue for it. Then again, with no +1s on the other old issue, it was probably due for closure anyway, so I'll just hijack it and fix it :)
