### ISSUE TITLE
Django commands not working on PTVS 3.0

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1443]
PTVS 3.0, VS 2015 Update 3, latest from master branch running in Exp

If you try to run a custom command more than once (such as Django check), it only works the first time.  If you're not lucky, it won't work first time either.

If you try to run a command that needs input (such as Django createsuperuser), it never works, not even first time.

When I say 'doesn't work', I mean it prints the command but then nothing else happens:
```
Python 32-bit 3.5 interactive window [PTVS 3.0.1000.00-14.0]
Type $help for a list of commands.
Executing manage.py check
>>> 
```

It never comes back from the call to
```
await pyEvaluator.ExecuteFileAsync(filename, arguments);
```

**Comment by zooba** [comment]
This is a race between a lock when starting the interactive window. Easy enough to un-race
