### ISSUE TITLE
Python not installed on VM after deploying Service

### ISSUE THREAD

**Issue by andrewkittredge** [Microsoft/PTVS#1447]
Generally following the instructions @ https://github.com/Microsoft/PTVS/wiki/Cloud-Project and https://azure.microsoft.com/en-us/documentation/articles/cloud-services-python-ptvs/ (which are apparently outdated) I deploy a service with a WebJob in it to Azure.

Nothing happened.  When I opened the log files on the VM I get the following message repeatedly, it seems like Python is not installed on the VM.  Is that possible?  Do I have to do something with the deploy scripts to make sure Python is deployed?

gi : Cannot find path 'E:\approot\%INTERPRETERPATH%' because it does not exist.
At E:\approot\bin\LaunchWorker.ps1:93 char:15
- Set-Alias py (gi $interpreter_path -EA Stop)
-               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (E:\approot\%INTERPRETERPATH%:St 
    ring) [Get-Item], ItemNotFoundException
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetIt 
    emCommand

**Comment by zooba** [comment]
Yeah, those pages have fallen behind a bit :(

Our current recommendation is to deploy a copy of Python yourself by adding the installer to the cloud project and running it either in the .csdef file or the CreateCloudService.ps1 file (both of which you can freely edit). Then you'll be in control of where it is installed and you can hardcode the path in LaunchWorker.ps1. You'll also be able to use any version of Python you like, rather than just the (old) ones we provided through the Web Platform Installer.

We have someone working on new tutorials for this, and might get to do new templates for the next release, depending on how other work goes.

**Comment by andrewkittredge** [comment]
Thank you.  Is there an example of how to do that somewhere?  I'm trying to keep my PowerShell skills to a minimum.

**Comment by zooba** [comment]
https://samrueby.com/2014/08/23/how-to-run-a-program-during-azure-deployment/ looks like it has the basics.

You can use a batch file instead - there's no need to use the powershell scripts we give you at all.

**Comment by andrewkittredge** [comment]
Do I need to get the binary installer from python.org and then run it with PowerShell or a batch file?

Sorry, I have no idea how to do this stuff on Windows, I am much more familiar with the Linux package managers.

**Comment by andrewkittredge** [comment]
@zooba http://stevedower.id.au/blog/building-for-python-3-5-part-two/ is huge by the way.  Made life much easier.  Now we just need a Fortran compiler for Windows, :-).

**Comment by zooba** [comment]
> Do I need to get the binary installer from python.org and then run it with PowerShell or a batch file?

Yep. Depending on how reliable you need it to be you can either get the web installer (smallest upload for you - most network usage when installing) or the full installer, then reference https://docs.python.org/3/using/windows.html for the command line options.

If you're on Python 2.7, you don't get as many choices - use `msiexec /q /i python...whatever.msi` as the command to install it. (You may have to put it in a batch file... not 100% sure. The 3.5 installer you can reference directly from the csdef file.)

**Comment by andrewkittredge** [comment]
I am using Python 3.5.  I think what is needed to here is a working example somewhere.  I don't know powershell, csdef, or Windows batch file syntax.

This is very frustrating.

**Comment by huguesv** [comment]
@lhoang29, would you be able to share your working custom deployment script with Andrew here?

**Comment by Thraka** [comment]
I've updated the Azure Documentation which provides some PowerShell scripts and guidance about getting it all working again. It is available [here](https://azure.microsoft.com/documentation/articles/cloud-services-python-ptvs/#install-python-on-the-cloud-service)

**Comment by lhoang29** [comment]
Sure. What I needed was a custom 64-bit distribution of python which was difficult to set up to be deployed automatically via either the virtual environment or the included .ps script. Below steps are what I ended up doing:   

1. Build the Python distribution on my local box, zip and upload it to a publicly available location. If you're on Windows, miniconda should be useful to install the right packages without much efforts.  
2. Write an executable that would run as part of the cloud start up task to download and unzip this package to the local storage of the cloud instance.  

        <Startup>
          <Task executionContext="elevated" taskType="simple" commandLine="elcloud-setup.exe" />
          <Task executionContext="elevated" taskType="simple" commandLine="ps.cmd ConfigureCloudService.ps1">
            <Environment>
              <Variable name="EMULATED">
                <RoleInstanceValue xpath="/RoleEnvironment/Deployment/@emulated" />
              </Variable>
            </Environment>
          </Task>
        </Startup>  

3. The last step is to modify the ConfigureCloudService.ps1 to set the Python interpreter path to point to my own distribution. See [ConfigureCloudService.txt](https://github.com/Microsoft/PTVS/files/388609/ConfigureCloudService.txt) (rename to .ps1).  

I'm happy to provide more details and could create a sample github project if needed.

**Comment by zooba** [comment]
The docs from @Thraka are more general and are currently best-practice for getting Python onto a cloud service instance. (They're also very transparent, so if you need to customize anything you can see basically all the pieces that are involved.)

**Comment by lhoang29** [comment]
@zooba definitely, my case was rather special because I needed to install other Python packages that are not easily streamlined via things like pip or the built-in requirements.txt (for example, if you need to build from code, etc...). Shipping the local setup to the cloud instances as mentioned above was the easiest way I found to get it working.

**Comment by Thraka** [comment]
@lhoang29 It's a great idea. Totally create a GitHub project that can build out the executable. I'm sure it will help someone.

**Comment by lhoang29** [comment]
@Thraka I just created the sample project with some instructions here: https://github.com/lhoang29/azure-python-flask.
