### ISSUE TITLE
Unable to upgrade to June 2016 version - Update button disabled

### ISSUE THREAD

**Issue by tillig** [Microsoft/PTVS#1453]
In trying to update VS for the June 2016 version of the Python tools, the "Update" button is disabled and there's no way to enable it. I already have VS 2015 Update 3 installed and can't uncheck it; unchecking the Python Tools option just provides a "Next" button that yields no actual installation. I've seen this on three different Server 2012 R2 machines.

![Installation Screen](https://cloud.githubusercontent.com/assets/1156571/17028825/a77f3b08-4f1d-11e6-848f-025de6b319a6.PNG)

**Comment by zooba** [comment]
This means you've already got the right version installed, but you're hitting a version number bug (as well as a CDN caching issue, apparently).

You can either dismiss and ignore the notification, or you can install the MSI from [here](https://github.com/Microsoft/PTVS/releases/tag/v2.2.4) which will update the version number and prevent the notification from showing (there are no other changes besides preventing the notification).

**Comment by tillig** [comment]
Installing via the MSI you linked to fixed it. Thanks!
