### ISSUE TITLE
Question: Is it possible to align my imports according to PEP8?

### ISSUE THREAD

**Issue by InvisibleDev** [Microsoft/PTVS#1465]
Currently I run PyLint on the project and then fix the module warnings separately. Is there a config or plugin that aligns import according to PEP8? e.g. native modules are first and by alphabet, then donwloaded ones and local ones in the end?

Thanks,
--rustam

**Comment by zooba** [comment]
Nothing that I'm currently aware of, sorry. Changing the order of imports can change the behavior of Python code, so we don't want to encourage people to do it automatically and potentially break their code.

**Comment by InvisibleDev** [comment]
Hi Steve,
Isn't it always the case that python standard modules should be imported
first, then downloaded community libraries like numpy, pandas etc and then
modules from your current project?

Thanks,
Rustam

**Comment by InvisibleDev** [comment]
I mean if that changes the behaviour of someone's code, the developer should refactor it so that the code is import order agnostic. Users of such code might struggle using the module as they might see varied behavior depending on imports on top of that module if the code is import order dependant.

**Comment by zooba** [comment]
Python doesn't have any "always the case" situations - there are always exceptions to every rule, and Python embraces and allows that.

It's not always possible to change the code that is causing issues, and while I would totally agree that it's bad when import order affects behavior, the fact is that it happens and many people make good use of it.

Ordering imports in any way is purely a question of style that is going to vary from user to user (PEP 8 is only relevant if you choose to follow it), and right now we don't prefer any particular style within VS.

**Comment by InvisibleDev** [comment]
Ok thanks.
