### ISSUE TITLE
Question: F12 doesn't take me to definition of function but rather proposes a choice

### ISSUE THREAD

**Issue by InvisibleDev** [Microsoft/PTVS#1466]
The choice is not on different implementations but usage of the module and definition of function. Would be nice if it simply could jump to definition straight away.

Thanks,
--rustam

**Comment by zooba** [comment]
I assume by "usage of the module" you mean a "from ... import" statement, and I agree. It would be nice to skip that choice.

**Comment by big-kahuna-burger** [comment]
Yes please, coming from C# myself (used VS before I learned any python), I'm used to jump straight to class definition, when instead in a large project I get presented with a list of imports in format ```from ... import SomeClass``` plus an entry ```class SomeClass(object)``` where actually I would like to jump straight onto the last entry.
