### ISSUE TITLE
Question: is it possible to debug the script from running in python interactive shell?

### ISSUE THREAD

**Issue by InvisibleDev** [Microsoft/PTVS#1467]
It would be extremely convenient to be able to debug by running module functions from console and stepping through rather than creating "main" function and running script based on that.

Can I set this up somehow? Apologize if I missed any information from wiki but I couldn't find on how to attach debugger to python console.

Thanks,
Rustam

**Comment by zooba** [comment]
It looks like our info on attaching the debugger to an interactive window disappeared from the wiki...

To do this, open Tools, Options, Python Tools, Interactive Options, select the one you want, and the enable attaching to interactive window. Then in the window, type `$attach` and hit enter. VS will switch into debugging mode, and if you import and call functions from files in the interactive window you can debug them.

Unfortunately, you can't currently set breakpoints in the interactive window itself. This is a very old feature that doesn't get used a lot, and while it's perfect for some circumstances, it leaves a lot to be desired for many people. Issue #751 is where we're tracking the work to improve this.
