### ISSUE TITLE
Problem in interactive window and step into

### ISSUE THREAD

**Issue by IlanHindy** [Microsoft/PTVS#1468]
Hi,
I want to activate the interactive window (IronPython Interactive)
When I type $attach it says that the enable interactive window in PythonTools options should be set
It is set and the interactive window does not attach 
I reacently installed the June 2016 version
Another problem is that I cannot activate the step into while debugging 
when I press the step into it works like step over
Can you tell me what to do?
Thanks,
Ilan

**Comment by zooba** [comment]
I don't think debugging an IronPython interactive window is well supported at all - I'm not surprised it has issues. We're mostly focused on working well with CPython and haven't invested a lot in making sure that IronPython/Jython/PyPy/etc. also work in all circumstances.

As for normal debugging, by default IronPython projects are configured to use the .NET debugger, which can sometimes behave strangely. See Project Properties/Debug and switch to the Standard launcher to use our Python debugger. If it keeps behaving strangely, perhaps you could post some of the code that isn't working right and describe what you expect to happen?

**Comment by IlanHindy** [comment]
Thanks for your answer.
I changed the debug launcher and the step into problem disappeared.
I still have a problem with the interactive window (refuse to attach)
Here is what I did:
I installed the latest version of CPython from python.org (64-bit)
I selected in tools>Python Tool  The Python 64-bit 3.5 interactive
I seted in the Debug>Options>Python Tools>Interactive Windows the Enable attaching to interactive
(only for this window)
(The project > properties > General > interpreter is still IronPython)
And I still got the message in the interactive window to set the Enable attaching to interactive
Can combination like this work? (When the interpreter is different from the interactive window interpreter?)
If so can you tell me what to check\change ?
Thanks,
Ilan

**Comment by zooba** [comment]
There's a screenshot [here](https://github.com/Microsoft/PTVS/wiki/Interactive-REPL#code-completions) that shows the options dialog - you need to make sure that where it says "Python 3.4" in that screenshot you have the name of the interactive window you are trying to use. The one selected in your project is currently unrelated to what you use in the interactive window.
