### ISSUE TITLE
Python not visible in Blend for Visual Studio Community 2015

### ISSUE THREAD

**Issue by jradcli924** [Microsoft/PTVS#1486]
I have installed Blend for Visual Studio Community 2015 with a custon inclusion of Python. I have also installed Anaconda. I do not see Python template available when attempting to start a new project. Looking at View\Other Windows does not show Python windows.

Going to Programs and Features and attempting to change the installation indicates that Python is already installed. Directly running PTVS responds that the feature is already installed. 

It appears that PTVS thinks that it is installed and Visual Studio is not aware of the installation. 

Does anyone know a solution to this?

**Comment by zooba** [comment]
You won't see Python in Blend, you should open "Visual Studio 2015" instead.

**Comment by jradcli924** [comment]
Thanks, this solved the problem. I was not aware of this restriction in Blend. Perhaps a warning should be included somewhere on the PTVS pages.
