### ISSUE TITLE
cannot get jython to work in visual studio

### ISSUE THREAD

**Issue by hbozic** [Microsoft/PTVS#1488]
the sample code works fine if the interpreter is python, However If i switch the  interpreter to jython , then this is the error  

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_launcher.py", line 25, in <module>
    import visualstudio_py_debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_debugger.py", line 562, in <module>
    attach_lock = thread.allocate()
AttributeError: type object 'org.python.modules.thread.thread' has no attribute 'allocate'

Internal error detected. Please copy the above traceback and report at
http://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .
```
This is similar to issue #1271

Also, using jython in the interactive window seems to work ok ( this was a simple brie test I did in the interactive window)

import sys
sys.version
'2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) \n[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]'
print "hello"
hello

**Comment by zooba** [comment]
I'd say this is exactly the same as #1271.

The file with the error in it is just Python code, so if you wanted to fix it yourself and submit a patch that would be very helpful. The problematic code is over five years old, so clearly Jython has made a breaking change that is affecting us - it may also be helpful to report it to them too.
