### ISSUE TITLE
Add/remove environment dialog checks all envs when none are referenced

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1504]
Create New Project
Add/Remove python environments

Instead of checking only the environments that are currently referenced, it is checking all of them?  This only happens when none are referenced by the project.  I don't recall it behaving that way in the past.  Is this correct?
![image](https://cloud.githubusercontent.com/assets/1696845/17309096/fb0eb55a-57f1-11e6-8335-e07dba8bfbf2.png)

**Comment by zooba** [comment]
Same as #1496 but is likely going to be fixed with #1469 and not before.
