### ISSUE TITLE
Can't install packages using conda, even when run elevated

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1505]
Dev 15.

I'm trying to install into the Anaconda that was installed by the VS installer.
I checked the "Run elevated" in the "Install package" dialog, but that doesn't help.

I know changes were made recently to "Run elevated", so I'm wondering if I'm hitting a bug or if it's by design and I have to follow the "clone this environment" instructions.

```
Installing 'boto3'
Fetching package metadata .......
Solving package specifications: ..........
Package plan for installation in environment C:\Program Files\Anaconda3:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.2            |           py35_0          67 KB
    jmespath-0.9.0             |           py35_0          28 KB
    conda-4.1.11               |           py35_0         247 KB
    botocore-1.4.37            |           py35_0         1.9 MB
    boto3-1.3.1                |           py35_0          97 KB
    ------------------------------------------------------------
                                           Total:         2.3 MB
The following NEW packages will be INSTALLED:
    boto3:     1.3.1-py35_0  (copy)
    botocore:  1.4.37-py35_0 (copy)
    jmespath:  0.9.0-py35_0  (copy)
The following packages will be UPDATED:
    conda:     4.1.6-py35_0  --> 4.1.11-py35_0 (copy)
    conda-env: 2.5.1-py35_0  --> 2.5.2-py35_0  (copy)
Error: Missing write permissions in: C:\Program Files\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\Program Files\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone=C:\Program Files\Anaconda3
'boto3' failed to install. Exit code: 1
```

**Comment by venkatesh-1** [comment]
I'm having the same issue. Any Suggestions?

**Comment by zooba** [comment]
@venkatesh-1 You're probably best to open an elevated command prompt and run the command manually.

Our integrated support for conda is _very_ basic, and has actually been removed (temporarily) in our next release until we can invest the time in making it work nicely (which we hope to include in a minor update to VS 2017).

**Comment by castitatislilium** [comment]
I tried this solution and it worked. I hope it helps:

Go to C:\Program Files. Right click on Anaconda. Properties --> Security. Then change permissions for all users.

**Comment by zooba** [comment]
This code path has been removed. When we add it back, we'll make sure it works better than it did before.
