### ISSUE TITLE
Python Environment info for virtual environment

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1508]
Looks a little weird.  Should that info 'panel' be collapsed in this case.  I'm talking about that 'By'.

![image](https://cloud.githubusercontent.com/assets/1696845/17310486/9f01c18c-57f9-11e6-8271-8ad38cbeac88.png)

**Comment by zooba** [comment]
Whole section is getting a facelift with #1469, but this will serve as a reminder.
