### ISSUE TITLE
Clicking on the python.exe in env window gives error

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1509]
I would expect it to start the exe in a console in interactive mode, not give this error:
```
C:\Python27amd64\python.exe: can't find '__main__' module in ''
Press any key to continue . . .
```

Is it picking up context from the project or files I have open?

Anyway, here's where I clicked:

![image](https://cloud.githubusercontent.com/assets/1696845/17310627/85da709a-57fa-11e6-99a9-78a7b845260e.png)

**Comment by zooba** [comment]
Already fixed in #1495 - you probably don't have our latest build (my feed update only just got merged today).
