### ISSUE TITLE
pip_downloader.py uses an out-dated link.  

### ISSUE THREAD

**Issue by alanch-ms** [Microsoft/PTVS#1516]
pip_downloader.py uses the link "https://go.microsoft.com/fwlink/?LinkId=616663" install pip.  However, that link, which redirects to "https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py", no longer works.  Please update the MS fwlink to redirect to "https://bootstrap.pypa.io/get-pip.py"

Here's the content of https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py:

#!/usr/bin/env python
import sys

def main():
    sys.exit(
        "You're using an outdated location for the get-pip.py script, please "
        "use the one available from https://bootstrap.pypa.io/get-pip.py"
    )

if __name__ == "__main__":
    main()

**Comment by zooba** [comment]
Fixed
