### ISSUE TITLE
Project creation fails - why ?

### ISSUE THREAD

**Issue by srfpala** [Microsoft/PTVS#1520]
Running VS Community Updt 3   Python Tools for VS on Win 10
Issue Cannot create new Python Project :

Error System cannot find the file specified HRESULT 0x80070002

﻿Creating Project PythonApplication1     Project Creation Failed
Unclear as to where to post this to get help on PTVS 

Please advise  Bob

Bob

**Comment by zooba** [comment]
This is the right place, but unfortunately I can only guess at what the problem may be.

Have you tried running a Repair install of Visual Studio? That would be the first place I'd suggest starting. There may be some corrupt or missing files that could cause this error.

**Comment by srfpala** [comment]
Attempted a Repair  and Repair ran fine.

But PTVS 2016-07-08 V3.0.1690.1 still failed as before.
 I uninstalled PTVS 2016-07-08 V3.0.1690.1  and then

installed PTVS VS2015  (2.2.30718.00)
This older version  works  fine  !
BR

  Bob  [😊]

________________________________

**Comment by zooba** [comment]
Ah, you didn't mention you were trying a Dev build. Those are often going to fail for no apparent reason, so you should be prepared to uninstall it and use a stable version when you hit problems.
