### ISSUE TITLE
Can't update PTVS through Visual Studio

### ISSUE THREAD

**Issue by Crazometer** [Microsoft/PTVS#1521]
When I try to update PTVS through visual studio I am unable to click on the install button. I am running VS Update 3 and am attempting the PTVS 2.2.3 > PTVS 2.2.4 update. It looks like the following...

![Screenshot](https://i.snag.gy/LQKq8z.jpg)

I've tried restarting my computer, running VS as administator and updating VS.

In the end I downloaded directly from the releases page on github which solved the issue.

**Comment by zooba** [comment]
Glad you got it resolved. We've already fixed the download that should be coming through the installer, but it seems some people are still getting the one with this issue (it's just the version number - everything else was up to date). There doesn't seem to be anything we can do about it, I think it's a CDN issue.
