### ISSUE TITLE
PTVS with bash on Windows

### ISSUE THREAD

**Issue by icoxfog417** [microsoft/PTVS#1522]
I want to import Python project that runs on [bash on Windows(=Ubuntu)](https://msdn.microsoft.com/ja-jp/commandline/wsl/about).  Are there any plan to enable this?

**Comment by zooba** [comment]
Yes, there are plans, but we're waiting on better integration between Windows and Bash before we can move forward. Until then, [remote debugging](https://github.com/Microsoft/PTVS/wiki/Cross-Platform-Remote-Debugging) should already work.

**Comment by robertcrowe** [comment]
I have a similar need.  I'd like to use a virtualenv hosted on Bash on Windows, so that I can develop with PTVS using Tensorflow, which doesn't install natively on Windows due to the dependency on Bazel.  I don't want to change Tensorflow itself, I just want intellisense and all the goodness that PTVS brings.  Is there a way to make this work?

**Comment by zooba** [comment]
@robertcrowe Not yet I'm afraid. We currently rely on being able to directly run the version of Python and we can't do that yet with Python inside Bash on Windows. But it'll come eventually.

**Comment by robertcrowe** [comment]
@zooba Thanks for the info, so I don't beat my head against that particular wall anymore.  Can you think of any other way to accomplish this?  I can load Tensorflow on a separate Linux system or a VM and build it, so I just need PTVS to see it enough to at least do Intellisense, although I'd love to be able to debug also.  I can build on Linux if necessary, and it seems like it probably will be necessary.

**Comment by zooba** [comment]
You can copy the code from a Linux machine to a Windows machine (find the folder inside your `site-packages` and put it into the Python install on Windows). You won't be able to run any code against it, obviously, but we should be able to parse enough to give you IntelliSense.

If you want to go further, you could look at mocking out the pieces that won't work on Windows, which would also let you debug it. I don't know exactly how the dependency looks, so I don't know how possible that is.

**Comment by robertcrowe** [comment]
It turned out to be easier to just build a Linux VM and use Visual Studio Code.  But I'm looking forward to the day when I can use bash on Windows and the full Visual Studio experience!

**Comment by Xazax-hun** [comment]
This would be a great feature, huge +1 :)

**Comment by Xazax-hun** [comment]
> @robertcrowe Not yet I'm afraid. We currently rely on being able to directly run the version of Python and we can't do that yet with Python inside Bash on Windows. But it'll come eventually.

Did that change with the Creators Update?

**Comment by zooba** [comment]
@Xazax-hun Maybe... :)

If you're not already, keep an eye on [our blog](https://aka.ms/pythonblog). I'm hoping to put up a very early preview soon.
