### ISSUE TITLE
Move InterpreterReference and InterpreterId from pyproj to user file

### ISSUE THREAD

**Issue by holyoaks** [microsoft/PTVS#1523]
When my team is committing changes to our repository, one of the challenges we face is that each one of us changes the pyproj file's "InterpreterReference" and "InterpreterId" sections. If we commit and push that change, everyone else has to remember to update their Python interpreter or they can't get Intellisense or debug the application. If we don't commit and push that change, the next time we pull the pyproj file from the repository (to get updated file includes, etc.) we have to throw away our Python interpreter reference and remember to update our Python interpreter or we can't get Intellisense or debug the application. Someone is always having to update their python interpreter.

If the Python Interpreter could be removed from the pyproj file and included either in pyproj.user or another user level file, it would eliminate this headache and make working with PTVS more pleasurable than it already is.

**Comment by zooba** [comment]
Out of interest, why do you need to keep changing?

We have some significant changes coming in our next version that will likely fix this anyway - interpreter IDs are going to be stable and customisable, so if you are creating custom environments simply giving them the same name will ensure that you don't have to keep switching.

**Comment by zooba** [comment]
That said, I am sympathetic to wanting settings to be truly per-user. But there are also good reasons for them to be saved in the project file, and we don't really have a good UI model to support choosing (though we can do some things to make it work if you're prepared to directly edit project files).

**Comment by holyoaks** [comment]
We don't keep changing. PTVS doesn't recognize my interpreter as the same as my colleagues, so PTVS forces us to "change". If we commit the "change", it blows up everyone else's environment. If we don't commit, we blow up our own environment when we pull the pyproj file after an update is made to it.

Glad to hear you're adding the enhancement; that should resolve our issue. Thanks for the response

**Comment by zooba** [comment]
Is this a custom environment that you've added yourself?

**Comment by holyoaks** [comment]
Yes. We're using virtual environments.

**Comment by zooba** [comment]
Okay, you should be fine with the next release (coming with the next version of VS, so a bit of a wait I'm afraid, but we aren't planning to update the VS 2015 release again for anything except regressions).

I'll keep this open as a reminder to look at enabling some way to make this a per-user setting rather than per-project.

**Comment by holyoaks** [comment]
OK. Thanks!
