### ISSUE TITLE
Interactive environment problems

### ISSUE THREAD

**Issue by arpruss** [Microsoft/PTVS#1525]
I'm using Visual Studio 2015 Express for Desktop. I have PyPy 2.7 installed in c:\pypy, and configured as a PTVS custom environment. It all worked with an earlier PTVS version, but now with 2.2.5RC1 when I try to open an interactive session, I get "Value does not fall within the expected range".

I then made a custom environment for my c-python 3.5 32-bit install in c:\python35. Opening an interactive window failed with "The DocumentSite on a WindowFrame may only be set once".

I then deleted all my environments, and made a new custom c-python 2.7 32-bit environment pointed to c:\python27 . Opening an interactive session gave me "Value does not fall within the expected range".

**Comment by zooba** [comment]
Can you show me all the values you've configured for these environments? There are a lot of places that error could be coming from, but if I can see the actual values it will probably be easy to figure out.

**Comment by MatzeTechInfo** [comment]
I got the same error when I try to open the "Python 3.4 Interactive". When I try to open the "interactive window" in Python environments VS Express 2015 crashed.
Is there any workaround/fix for this problem?

**Comment by zooba** [comment]
@MatzeTechInfo Can you try with [PTVS 2.2.6](https://github.com/Microsoft/PTVS/releases/tag/v2.2.6) and see if it still fails?

If so, please attach the output from Tools, Python Tools, Diagnostic Info here, as a [gist](https://gist.github.com/) or email to ptvshelp@microsoft.com.
