### ISSUE TITLE
Mixed-mode debugging silently fails when Native Compatibility Mode is enabled

### ISSUE THREAD

**Issue by Artfunkel** [Microsoft/PTVS#1526]
When Options > Debugging > General > Use Native Compatibility Mode is enabled, mixed-mode Python debugging does not result in any Python stack frames appearing. Instead the raw C calls are displayed.

This is an understandable limitation, but not an obvious one. The user should be informed of the problem with their configuration by an error message on mixed-mode attach.

**Comment by zooba** [comment]
Thanks. We probably ought to look further into what "Native Compatibility Mode" means, since I've actually never heard of it before. I'm guessing it just uses the old native debug engine, which is why we can't integrate, but we may not be able to detect that.

**Comment by Artfunkel** [comment]
Yes, it uses the VC10 debug engine.

**Comment by int19h** [comment]
Yes, this is the pre-Concord stuff.

We should be able to detect it. Our AD7 engine gets loaded anyway (we just bail out early everywhere to let Concord take over), so there is some running code where the checks can be placed.

And we should be able to tell the difference by looking at other engines in the process (which we already do to detect mixed / non-mixed), and paying attention to their GUIDs. As I recall, compat engines have different GUIDs.

**Comment by int19h** [comment]
In VS 2017, Native Compatibility Mode is gone (I assume because the new engine can now do everything the old one did). Managed Compatibility Mode is still present, but VS itself will detect and prevent mixing languages when it's enabled:

![image](https://cloud.githubusercontent.com/assets/1175142/23385920/1979adc2-fd08-11e6-9c28-1510fda49e53.png)
