### ISSUE TITLE
Default flask template does not include __init__.py and views.py

### ISSUE THREAD

**Issue by roozbehid-ic** [Microsoft/PTVS#1527]
As in subject.
File -> New -> Project -> Flask Web Project.
It does not have those files which seems to be required.

Visual STudio Enterprise 2015
V 14.0.25425.01 Update 3
Python Tools for VS 2.2.40623.00

**Comment by zooba** [comment]
I think this may already be fixed for our next update, and we're unlikely to release another update for VS 2015 to fix this.

**Comment by huguesv** [comment]
I verified that the templates for VS 2017 are ok.
