### ISSUE TITLE
Auto merge causes indentation problems

### ISSUE THREAD

**Issue by HHest** [Microsoft/PTVS#1528]
Hello, 

I've noticed that the merge tool does not handle indentation merging very well, particularly if one refactors code and changes the indentation levels. I saw this issue in our live code, while using Visual Studio with PTVS. Investigating the cause, I've narrowed it down to the behavior of VSDiffMerge, which PTVS uses. 

My sample files are attached. The "source" file makes a small change to a function name, as compared to the "common" file. The "target" file performs two modifications: 1) an if check is added, and the indentation level increased in g1, and 2) the if check is eliminated and indentation decreased in g2. 

Rather than keeping the indentation of the target, or at least marking the differences as a conflict, VSDiffMerge auto merges with the incorrect indentations taken from the source/common file. Problem with the first set of indentation is particularly dangerous.

Here's the command you can use to reproduced the behavior:

`vsdiffmerge.exe source.py target.py common.py result.py /t /m`

Perhaps this is an issue with vsdiffmerge, but since indentation is particularly important in python, I am raising it to your attention here. Hope you can do something about it. Thank you.

p.s. Had to add .txt to .py files, in order to attach them.
[Updated 12Sep16 to include explanations of changes and expected results]

[target.py.txt](https://github.com/Microsoft/PTVS/files/467076/target.py.txt)
[common.py.txt](https://github.com/Microsoft/PTVS/files/467077/common.py.txt)
[result.py.txt](https://github.com/Microsoft/PTVS/files/467079/result.py.txt)
[source.py.txt](https://github.com/Microsoft/PTVS/files/467078/source.py.txt)

MSVS Pro 2013 v. 12.0.30723.00 update 3
PTVS v. 2.2.31124.00

**Comment by HHest** [comment]
Here's another demonstration that auto-merging can be dangerous. First, a picture of a correctly done merge, using the tool "Beyond Compare":

![beyondcompare](https://cloud.githubusercontent.com/assets/3169669/18787078/837c6c56-81a1-11e6-88d3-9dc557f9c23a.PNG)

The "Source" version has done all the modifications, and it should take precedence. The resulting merge agrees with this. 

Now a picture of the incorrectly done merge, using PTVS. **The resulting merge indents incorrectly the lines 504--507.** This was done without any warning, and required careful reading to discover.

![vsmergediff](https://cloud.githubusercontent.com/assets/3169669/18787198/1264bb1c-81a2-11e6-9a87-43c96db02c2d.PNG)

**Comment by zooba** [comment]
Are you still using VS 2013? With VS 2015 Update 3 I see this merge for your example files, and it looks fine:

**Comment by zooba** [comment]
Wait, not quite fine. The second change is right, but the added indentation is not accounted for until you choose either side of the conflict, at which point it changes to the one selected.

I think this summarizes down to "the VS merge tool does not treat whitespace-only changes as conflicts". Does that sound accurate? (I'll have to pass this on to another team, so the easier I make it to understand the issue, the more likely it'll get fixed.)

**Comment by HHest** [comment]
Thanks for taking a look at this issue. Yes, I am still using VS 2013. It sounds like VS 2015 has improved the situation a little then. At least 2015 marks the changes as having conflicts. In 2013, the merge tool does not even warn about possible conflict.

I would not want to insist that VS merge tool has to treat all whitespace-only changes as conflicts. It's more like the tool isn't considering whitespace-only changes as important, and it always chooses the indentation of the common file (which isn't always correct).
