### ISSUE TITLE
No completions on namedtuple

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#153]
In the following code, p is of unknown type, which means no completions at all.  It would be great to have 'x' and 'y' as suggestions.

```
from collections import namedtuple

Point = namedtuple('Point', ['x', 'y'])

p = Point(10, 20)
print(p.x)
```

https://pytools.codeplex.com/workitem/695

**Comment by zooba** [comment]
This one already exists on CodePlex, so if someone wants to track it down and close it or post a link, that'd be appreciated.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/PTVS/issues/731
https://github.com/Microsoft/vscode-python/issues/2377
