### ISSUE TITLE
Remote debug between Linux and windows, Visual Studio Code used.

### ISSUE THREAD

**Issue by weiayong** [Microsoft/PTVS#1537]
Hi, I am using Visual Studio Code for coding Python, and trying remote debugging with ptvsd.
Now I can achieve remote debugging between two PCs both installed Windows OS. But I can’t achieve this remote debugging between Linux and Windows. Are there anyone who ever tried this can share some experience. Thank you very much!

**Comment by zooba** [comment]
You may need to ask this on the Visual Studio Code site if you hope to find some community answers. Alternatively, the site for the Python extension for VS Code may have some helpful documentation.

It's very likely that you'll need a different version of ptvsd for Visual Studio Code. The one we maintain here and on PyPI is for Visual Studio, and the VS Code one is different. I am not sure where it is best to obtain a copy of it from.
