### ISSUE TITLE
How can I fix this issue? Im a rookie 

### ISSUE THREAD

**Issue by santiagodl** [Microsoft/PTVS#1539]
ImportError:  DLL load failed: %1 is not a valid win32 application.

**Comment by huguesv** [comment]
Hi! We'll need a bit more details in order to help. 
- What distro+version of python are you using?
- Which library are your trying to use?  How did you install it? (assuming it didn't come with your distro)
- Seeing the section of your code that triggers the error would also help.

**Comment by qwergram** [comment]
Are you using 32 bit python or 64 bit python? Switch versions to see if it makes a difference.
