### ISSUE TITLE
Create virtual env dialog doesn't always come up via new project

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1542]
VS 15 Preview 4 (daily)

Start VS
New Project->Bottle Web Project
Install into a virtual environment

Result: Virtual env dialog doesn't come up, virtual env not created

If you repeat this in the same instance of VS, it will work the second time.

You'll need to restart VS to repro again.

**Comment by zooba** [comment]
At a guess, we aren't getting `project.Properties.Item("InterpreterDescription")` or `project.Properties.Item("InterpreterId")` back from the project after it's created.

**Comment by zooba** [comment]
Still seeing this occasionally on VS 2017

**Comment by zooba** [comment]
The earlier idea is clearly wrong because we're now sending a command to the project. I'm trying adding more debug messages to identify the reason for failing.

**Comment by zooba** [comment]
This looks like DTE being unreliable. I'm trying some solutions to bypass DTE completely here.
