### ISSUE TITLE
can't debug remote python code running on linux via tcps

### ISSUE THREAD

**Issue by witheri** [Microsoft/PTVS#1550]
I'm trying to debug some code on a remote linux machine and VS fails to connect. The message under the "additional information" of the error dialog is "Authentication failed because the remote party has closed the transport stream". Has anybody else seen this before or knows how to get some more trace/debug messages out of ptvsd?
I was able to debug a session running on localhost (a win7 box), without using secure transport.
I'm using VS2013, Python 3.5.1 and ptvsd-2.2.0.

**Comment by zooba** [comment]
That sounds to me like there's a firewall interfering, but maybe @int19h has more details?

Are you able to try with an insecure transport to the Linux machine?

**Comment by witheri** [comment]
@zooba Can't try an insecure connection to that particular linux box - that is blocked (corp intranet).  But I have an extra VM, that I can mess with and if I can debug using that target, then I'd agree to blame some network config/firewall.

**Comment by witheri** [comment]
Update 2: When I try a secure connection to localhost I'm getting a different error message: 

> The handshake failed due to an unexpected packet format

I'm guessing that I'm doing something wrong when I generate the certificate, but I don't know what that could be. Certificate installed fine. Certificates were generated with openssl 1.0.1e

**Comment by int19h** [comment]
Both of these error messages look like they're coming from the SSL layer. 

The first one, I haven't seen before, but it would seem to indicate some sort of underlying transport failure. Does ptvsd process exit when you do that, and/or print any error messages?

The second message usually appears when one side tries to connect using SSL, but the other side does not have SSL enabled (and responds to the SSL handshake with an error packet). Can you show your code (or command line, if you're using that) for ptvsd initialization?

**Comment by witheri** [comment]
@int19h : There is no visible output on the target side by ptvsd and the wait_for_attach() function does not return, either. Even with python -v there is nothing. 

The class that I'm using to interface with ptvsd and as debug target is this one:
[DebugTest.zip](https://github.com/Microsoft/PTVS/files/431149/DebugTest.zip)
**Note:** I just added the paths to the certificate & keyfiles to see if that makes any difference (it doesn't)
The script that I'm executing in python is this one:

`from DebugTest.DebugTestClass import DebugTestClass`
`_t= DebugTestClass()`
`_t.waitForDebugger()`
At this point I'm trying to attach the debugger and do stuff.
