### ISSUE TITLE
Support Open Folder

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#1556]
Currently in Visual Studio 2017, when you open a folder we don't have a great Python experience. We should raise this to as-good-as the current project-based experience.

This task will be considered complete when projects are _only_ required for tasks that are inherently MSBuild related, and the experience is equivalent to having a .pyproj containing all the project-related files visible in the workspace.

Tasks remaining:
- [ ] #1780 manage environments without a project
- [ ] read/write IntelliSense configuration to JSON file
- [ ] complete debugging configuration in JSON file
- [ ] launch browser when debugging from JSON file
- [ ] launch standalone scripts with correct configuration
- [ ] launch tools (linters, mypy, etc.) in directory
- [ ] detect and launch unit tests without a project
- [ ] build via `setup.py` when available

**Comment by zooba** [comment]
PR #1605 implemented debugging and launching scripts (which are actually the same).

**Comment by zooba** [comment]
Removing release-blocking label, but we still have work to do here. It's just not so bad right now that we need to hold up RC because of it (and we can create new release-blocking issues if necessary).

**Comment by tuespetre** [comment]
In reference to #2653: the .NET Core SDKs have allowed wildcards for a while. And I **love** that. Would I be welcome to poke around at getting something like that to work with PTVS?

**Comment by zooba** [comment]
@tuespetre Sorry to miss your comment.

Ultimately, wildcards will not work well with Python projects because we use a totally different project system implementation. The .NET Core project system was rewritten specifically to support that, but we have far too many assumptions throughout for it to work well (specifically, there are a number of places where the wildcard gets converted into the actual files and you lose the automatic updating ability).

Having proper support for Open Folder is our best way forward right now. Unfortunately, it's a lower priority than many of the existing bugs we have in other areas of the product.

**Comment by Annihilator708** [comment]
Please add this to VSC too, thanks!

**Comment by huguesv** [comment]
Most of these have been implemented, except for launching tools and building setup.py. I'll close this and we can implement the others if there is demand.
