### ISSUE TITLE
VS 2015 PVTS Output Error?

### ISSUE THREAD

**Issue by rgasper** [Microsoft/PTVS#1558]
I'm having what seems to me to be an error but I am not very familiar with Visual Studio.

When running a python script, Visual studio seems to be incapable of actually opening and writing files to the disk- so, take for example the following simple test.py script:

output = open('testfile.txt','w') #open my file
output.write("Hello world, this is a test string!") #print a silly string
output.close() #close my file

Executing this inside of VS 2015 does nothing- testfile.txt never appears. As well, if I manually write testfile.txt in the directory to something, executing this script inside of VS 2015 will not overwrite it. No error messages are produced, and the thread/python exit successfully. Running VS 2015 as administrator does not solve the issue.

If I take the same script and run it from cmd, it works as one would expect- the file is either written (if it doesn't exist initially) or is overwritten if it already exists.

Thanks

**Comment by zooba** [comment]
I'd suggest you try running `import os; os.getcwd()` to see where the interactive window is running. It's very likely that it is in a different directory than where you may expect.

We've already made changes for our next release to improve this. For the current release, your best option is to use `os.chdir(r"C:\Path\Goes\Here")` to change the working directory (or alternatively, to specify a full path name when opening files).

**Comment by rgasper** [comment]
That solved the issue, thanks.
