### ISSUE TITLE
Error when using urllib2.urlopen while debugging

### ISSUE THREAD

**Issue by fhussains** [Microsoft/PTVS#1559]
I have a python file that I am trying to debug.  When I call urllib2.urlopen(instance), no data is returned and the next step in the code fails.  If I put a breakpoint at me urllib2.urlopen, and run the same command in immediate window, it returns data from the website.  

Here is my code snippet... 

```
    handle1 = urllib2.urlopen(instanceRequest)
    jsonData1  = json.loads(handle1.read())
```

handle1 always comes up empty when I step through the code, but when I do the same in immediate window, I get the data.

**Comment by zooba** [comment]
How did you create `instanceRequest`?

It's possible that our debugger is reading a value and using it up, but I'm not sure what that would be.
