### ISSUE TITLE
Test adapter not using specified VirtualEnv?

### ISSUE THREAD

**Issue by KerstinKeller** [Microsoft/PTVS#1568]
I've setup my project to use a virtual python environment and that works using the Projects "Python Environments". However when I run my tests in the test explorer, I get import errors for those packages that are contained only in the virtualenv.
When I try to set the Visual Studios default Python environment to my virtual environment (via Tools -> Options -> Python Tools -> Environment Options), it does not work either. The option always switches back to "Python2.7" when I reopen the Options window.
When I start the module normally with the debugger, the import works fine.

I am using PTVS 2.2.40315.00 for VS2015 Professional.

**Comment by zooba** [comment]
Are you able to get the output from Tools, Python Tools, Diagnostic Info while you have your project open and either post it to a [gist](https://gist.github.com) or email to ptvshelp@microsoft.com? That should give us enough information about how you've set things up to help you.
