### ISSUE TITLE
Allow IPython 5.x syntax highlighting to control colors in interactive shell.

### ISSUE THREAD

**Issue by haz-q** [Microsoft/PTVS#1570]
When using Anaconda / IPython interactive shell, the syntax highlighting matches that of the code editor. I'd like it to instead utilize IPython's color scheme as though it were run in the command line.

**Comment by zooba** [comment]
I'm not sure that we're able to flow the colours through to our interactive window, but if you have specific suggestions about the differences you'd like to see then we may be able to do some of those.
