### ISSUE TITLE
Unable to load PTVS 2.2.5 on Visual Studio 2015

### ISSUE THREAD

**Issue by akssnsk** [Microsoft/PTVS#1578]
After I installed PTVS2.2.5 on VS2015, python projects stop loading and/or VS shows a error prompt on start. It doesn't matter if I open Visual Studio with or without any solution.
"""
The 'Python Tools Package' package did not load correctly
The problem may have been caused .....
Restarting Visual Studio could help reslove this issue.
....
Continue to show this error message? 
YES NO
"""

I attached a part of ActivityLog with the error
[PTVS225.txt](https://github.com/Microsoft/PTVS/files/448551/PTVS225.txt)

Visual Studio Professional 2015 14.0.25425.01 Update 3

Afterwards all PTVS 2.2.2, 2.2.4 stop loading too.

**Comment by zooba** [comment]
This may be easily resolved by deleting the files in `%LocalAppData%\Microsoft\VisualStudio\14.0\ComponentModelCache` and restarting VS.

If that doesn't fix it, we need to look into a corrupt installation, but since you tried other versions I don't think that's going to be the problem.

**Comment by akssnsk** [comment]
I had to solve it quick, so I deleted all %LocalAppData%\Microsoft\VisualStudio\14.0 and HKCU registry for 14.0 and all settings for python as stated in [this description](https://github.com/Microsoft/PTVS/wiki/Where-is-PTVS-installed). 
It works now, but your solution is obviously nicer. Thanks.

**Comment by gmonkman** [comment]
Had failed PTVS update on vs 2015 community. Had to reinstall PTVS manually. Was having this problem on loading VS after PTVS install.

zooba's advice resolved the issue: 

> This may be easily resolved by deleting the files in %LocalAppData%\Microsoft\VisualStudio\14.0\ComponentModelCache and restarting VS.
