### ISSUE TITLE
Problem in inserting new environment

### ISSUE THREAD

**Issue by IlanHindy** [Microsoft/PTVS#1579]
Hi,
I recently installed the new version of IronPython.
I inserted new python environment through Python Environments > custom
I setted the new environment to be the default environment
I saw in Debug > options > Python Tools > Environment Options that the default environment
was setted to the parameters I inserted
I activated the debug of my program and looked in Debug > Windows > modules and saw that the path of the IronPython executable (ipyw.exe) was of the old environment
can you tell me what's wrong?
Thanjks,
Ilan

**Comment by zooba** [comment]
Can you post the output from Tools, Python Tools, Diagnostic Info into a [gist](https://gist.github.com) or email to ptvshelp@microsoft.com? Make sure the project is loaded when you get the info. That'll help us see where various configuration options are pointed.

**Comment by IlanHindy** [comment]
Hi,
I closed the VS and reopen it and the problem gone.
Thamks
Ilan
