### ISSUE TITLE
Controls arrangement in interactive window options is unexpected on VS 2015

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#158]
The "Use inline prompts" checkbox is not a valid option on VS 2015, so it's hidden.  So the page looks like this:

![reploptions](https://cloud.githubusercontent.com/assets/1696845/7657326/f0de11f8-fae5-11e4-8e73-8eb5cbb760c5.png)

**Comment by zooba** [comment]
This page has been redesigned since this issue.
