### ISSUE TITLE
Problem loading symbol file

### ISSUE THREAD

**Issue by IlanHindy** [Microsoft/PTVS#1580]
Hi,
For some unknown reason When I set a breakpoint and start the debugger it says that no symbols are loaded  for the module.
I looked in the debug > windows > modules and in the ipyw.exe module there was a comment that the symbol loading was skipped
The only difference between the time It was working and now is that I installed visual studio update 3 (including the new vertion of PTVS)
Thanks,
Ilan

**Comment by zooba** [comment]
What version of IronPython are you using? I know they just came out with a new version, but we haven't tested with it yet.

Alternatively, in your project properties you can change the debug launcher to "Standard Python launcher" if you only need Python debugging. By default it will use the .NET debugger, which only correctly debugs Python code if IronPython correctly encodes the debugging information.

**Comment by IlanHindy** [comment]
Hi,
Thank you for your answer.
I could not overcome the problem so I started a new project and it works fine.
(there still remains the question if there is a way to force creating symbols on the project's files
if from one reason they where corrupted)
Thanks,
Ilan

**Comment by IlanHindy** [comment]
Hi,
I found the problem and I think you should pay attention to it.
I had a solution with 2 projects
When I inserted the first project and inserted breakpoints to it, it hit the breakpoints
When I inserted the second project and inserted breakpoints to it it hit the breakpoints
But after inserting the second project the breakpoints of the first project did not hit and I got
the message that the breakpoints will not hit because the symbols where not loaded
I backed up my first solution (with the 2 projects) so if you need data from it I can send you
Thanks,
Ilan

**Comment by zooba** [comment]
I think we'll need the two projects to be able to investigate this. You can email them as an attachment (with source code - not binaries) to ptvshelp@microsoft.com, or put them online somewhere and email us a link.

It sounds somewhat like #1292, but if you're using the CLR debugger on IronPython then it's actually unrelated.

**Comment by IlanHindy** [comment]
I put the solution in my google drive and sent an invitation to the e-mail address
I sent an explanation in the e-mail of the problem
