### ISSUE TITLE
Python interpreter - Docker

### ISSUE THREAD

**Issue by HaruzeM** [Microsoft/PTVS#1582]
I installed the Anaconda3 in a Docker container. Is it possible to setup the interpreter in the Visual Studio Community 2015?

**Comment by zooba** [comment]
Not today, unfortunately. We rely on being able to run `python.exe` directly, pass in arbitrary command lines, and establish network connections. I don't believe we can do that transparently into a docker container, and we don't have any specific support for it yet.

**Comment by zooba** [comment]
This is something that would probably be enabled by #185
