### ISSUE TITLE
The Source code of 2.2.5 tags for downloads is wrong

### ISSUE THREAD

**Issue by amos402** [Microsoft/PTVS#1583]
The version of codes in two archive files is 3.0, not 2.2.5.
And I found this version did not find right path of targets files such like `Microsoft.PythonTools.targets`  when I using Experimental Instance of Visual Studio 2015 to create a new Python project or open a project.

**Comment by zooba** [comment]
You're right! Thanks for the notice - I've updated the tag to 2.2.5post1 and put it against the right branch.
