### ISSUE TITLE
unable to resolve build-in module and no completion

### ISSUE THREAD

**Issue by denallo** [Microsoft/PTVS#1595]
recently I found that my vs2015 cannot autocomplete many of build-in module, such as os,trackback,threading (but time,datime,sys...etc is work well).
 when i type a module name, it just show me "no completions", and if I write a import line, ide will hint "unable to resolve "XXX", IntelliSense maybe missing for this module"
I'm confused because everything was work well prior to this week, all of this errors are seems suddenly occur.
I tried reset the ide, repaire/reinstall ptvs but help nothing.

**Comment by denallo** [comment]
I have copied Diagnostic Info and sent it to ptvshelp@microsoft.com

**Comment by zooba** [comment]
I'll admit, this is strange.

Can you try deleting the `C:\Users\<username>\AppData\Local\Python Tools` directory and regenerating the DB? Possibly something has become corrupted but we aren't detecting it properly.

**Comment by ykresnin** [comment]
Worked for me, thanks Zooba
