### ISSUE TITLE
[VS2012][PTVS 2.1][W8] Neither signature help nor completion / IntelliSense

### ISSUE THREAD

**Issue by msprj2010** [Microsoft/PTVS#1596]
I have just installed PTVS 2.1-VS2012-Windows8. There is neither signature help nor completion. I have replayed the sequence of task described on the video "PTVS 2.0: A quick overview (2-4 mins per feature)", url : www.youtube.com/watch?v=JNNAOypc6Ek.

![_160909-2334_signature help_no completions](https://cloud.githubusercontent.com/assets/22107474/18404036/77da40f8-76e8-11e6-953a-04371292247c.PNG)
 
![_160909-2332_signature help](https://cloud.githubusercontent.com/assets/22107474/18404131/f82b0620-76e8-11e6-879c-f6ea2ab92610.PNG)

![_160909-2333_signature help](https://cloud.githubusercontent.com/assets/22107474/18404136/0001d4a0-76e9-11e6-9182-e5a682baa5ba.PNG)

**Comment by zooba** [comment]
If you change `_init_` to `__init__`, do you get the suggestions you expect? (You need two underscore characters at either end of the name.)

**Comment by msprj2010** [comment]
:) Thx you Zooba for your help.
Sorry for my dummy question.
I am learning python.

I will make more research before posting another question next time.
