### ISSUE TITLE
Formatting document (ctrl-k,d) removes async keyword in front of "async for"

### ISSUE THREAD

**Issue by meastream** [Microsoft/PTVS#1601]
Hi,

we are observing some very peculiar behavior while using the 'Format Document' function of Visual Studio in a Python project. The function removes the `async` keyword and any single line comment before it from in front of a `async for` statement, even though it recogizes async as a keyword. This can be summarized by the code snippets below:

Before CTRL-K,D
```python
logger.debug('some code here')
#Some comment
async for event in device.async_read_loop():
    logger.debug('dispatch event')
```

After CTRL-K,D
```python
logger.debug('some code here') for event in device.async_read_loop():
    logger.debug('dispatch event')
```

using :
```
Visual Studio 2015 Update 3 (v14.0.25425.01)
Python Tools 2.2.4
```

Best regards,

**Comment by zooba** [comment]
Well that's embarrassing. Thanks for the info :)
