### ISSUE TITLE
rename throws error

### ISSUE THREAD

**Issue by big-kahuna-burger** [Microsoft/PTVS#1602]
Putting cursor to .__instaces and hitting Ctrl+R, R (with intent to fix typo) I get an 
error. They say images speak more than words, so here they are: 

![first](https://cloud.githubusercontent.com/assets/11753867/18478764/c0620864-79d2-11e6-807d-590c117b5b05.png)

![second](https://cloud.githubusercontent.com/assets/11753867/18478796/d4011a4a-79d2-11e6-8dbd-624097bed210.png)

![third](https://cloud.githubusercontent.com/assets/11753867/18478815/dd8f6116-79d2-11e6-9b27-4dc81fc4ef71.png)

**Comment by big-kahuna-burger** [comment]
Python Tools dll 2.0.2.2015,
Python interperter 2.7

**Comment by big-kahuna-burger** [comment]
additional note: when I tried without Preview Reference Changes being checked it succeeds. Also, after that it succeeds regardless of the checkbox status.
After VS restart I'm unable to reproduce it anymore :dancer:

**Comment by zooba** [comment]
I can't reproduce this now, so I'm going to assume we fixed it.

Let me know if you can still reproduce it in VS 2017 (when that releases)
