### ISSUE TITLE
cookiecutter should make it more obvious when it doesn't create a subdirectory

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1612]
I clicked through creating a project from the web app template and put it in a top-level directory rather than creating a subdirectory.

We really shouldn't let this happen. Either we need to provide a subdirectory by default when not explicitly adding to an existing project, or make it much clearer where the files are going to go.

**Comment by zooba** [comment]
@huguesv Let's get this one sorted asap. Pick something that will make people succeed by default and we can argue the details after the upcoming release.

**Comment by huguesv** [comment]
The files always go in the folder you've specified in "Create To".  I'm not sure what the problem is?

**Comment by zooba** [comment]
That folder is my Documents by default, and should be "Documents\Visual Studio x\Projects" with #1611, but neither of these is a good root for the project. The problem is it's too easy to miss the fact that I need to change the field.

One other option would be to make it empty by default and force the user to fill it in.

**Comment by huguesv** [comment]
I think leaving it empty may be good option for now. The watermark will help make it more obvious, and the fact it's not pre-filled will avoid misleading them.
![image](https://cloud.githubusercontent.com/assets/1696845/18527795/1f58e6d2-7a7b-11e6-8a1e-b4852eadb2f0.png)

**Comment by zooba** [comment]
Either that or adding the name of the template at the end, followed by a "-1", "-2", etc. if it already exists.

**Comment by zooba** [comment]
Let's go blank for now. We discussed the idea of tagging some properties as "likely project names", so we should use that.

**Comment by huguesv** [comment]
It's blank now, so I've removed the release-blocking label, but keeping this open so we can improve for next release.

**Comment by huguesv** [comment]
I think we can close this now?

**Comment by zooba** [comment]
Yep
