### ISSUE TITLE
cookiecutter ui does not update after installing package

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1618]
I had the prompt to install the package, so I did, but the UI did not update. I can't find any way to get rid of the "This feature requires..." message.

**Comment by huguesv** [comment]
Yeah it requires a VS restart. We should definitely mention that in the doc page.  My hope is that we'll be able to reduce/eliminate/automate those requirements post preview 5 (depending on what legal tells us we can do).

**Comment by 11bblandin** [comment]
Please unsubscribe me from this thread. I have tried to do this multiple times using the link at the end of emails unsuccessfully.

**Comment by zooba** [comment]
@11bblandin You probably need to visit https://github.com/Microsoft/PTVS and click on "Unwatch" near the top of the page. We don't have any control over your subscriptions.

**Comment by huguesv** [comment]
If you are getting the message saying you need Python, install Python and then click Home, it will now look for it.  As for the package, that is no longer something the user needs to worry about, as we manage a private virtual environment for that.
