### ISSUE TITLE
cookiecutter templates failing to clone

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1620]
All templates are failing to clone with similar messages:

```
----- Cloning template 'pydanny/cookiecutter-djangopackage' -----

Cloning into 'cookiecutter-djangopackage'...

----- Failed to clone template 'pydanny/cookiecutter-djangopackage' -----
```

I have no idea what's going wrong - some more detail would be very valuable here.

AFAICT I have `git.exe` in the right place, though it's not on my PATH.

**Comment by zooba** [comment]
Adding git.exe to my path doesn't help.

**Comment by huguesv** [comment]
Dev14 or Dev15?

**Comment by huguesv** [comment]
If Dev14, you'll need it in your PATH.

**Comment by zooba** [comment]
Today's build of VS with the latest PTVS side-loaded in (just like we do for tests).

**Comment by zooba** [comment]
It could be the sideloading, but that shouldn't cause any problems. Certainly shouldn't cause problems that don't have an error message.

**Comment by huguesv** [comment]
This is what I get this if I turn on airplane mode before cloning:
```
----- Cloning template 'pytest-dev/cookiecutter-pytest-plugin' -----

Cloning into 'cookiecutter-pytest-plugin'...
fatal: unable to access 'https://github.com/pytest-dev/cookiecutter-pytest-plugin/': Couldn't resolve host 'github.com'

----- Failed to clone template 'pytest-dev/cookiecutter-pytest-plugin' -----
```

So it is able to print out errors. And if it wasn't able to find git.exe, you'd see the missing requirements info bar.

**Comment by zooba** [comment]
So apparently we have a case that fails without errors... let me attach a debugger and use procmon to see what's going on.

**Comment by zooba** [comment]
Looks like the problem is that the path to git.exe (`"C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd\git.exe"`) is going via a symlink that somehow causes some dependent DLLs to not be found. If we resolve to the actual directory then it works fine. The `GetFinalPathName` helper in `CommonProjectNode` should work for this.

Also, the exit code returned from here is non-zero but not displayed anywhere. Perhaps we should include a message "git.exe returned an exit code of 128".

**Comment by huguesv** [comment]
Thanks, I'll look at making those 2 changes.
