### ISSUE TITLE
Fix mixed-mode debugging for 3.6

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1634]
Python 3.6 almost certainly doesn't work for MMD anymore because the internals have changed so much.

**Comment by int19h** [comment]
Isn't PGO now on by default, too? If so, that will probably be the biggest hurdle.

**Comment by denfromufa** [comment]
+1 I need mixed-mode debugger once python 3.6 is not beta.

**Comment by zooba** [comment]
True, PGO is on for the 64-bit release (until we find a compelling reason to drop it again). But maybe VS 2015 produces better debug information? We should ping someone from the VC team about it and see what options exist.

Alternatively, we may be able to enable ETW tracing for Python 3.6 (via the dtrace support that was just added), so maybe there's an alternative way to get the same info?

**Comment by int19h** [comment]
As I recall, the info that we needed that was broken by PGO was the function body spans, specifically DebugStart and DebugEnd DIA symbols. I'm not sure this is something that can be addressed by ETW, unless there are specific events corresponding to that exactly.

**Comment by zooba** [comment]
DebugEnd was broken anyway I think as there is no guarantee of having only one return instruction in a function - we had to move some breakpoints to after the return because of this.

ETW may let us rebuild enough callstack information that we don't have to trace as many points. Or maybe we can keep a parallel list of frame objects by injecting a trace function?

**Comment by zooba** [comment]
We should definitely get this fixed before release - it's probably our most compelling feature, and we certainly do not want to block 3.6 adoption because we are missing it.
