### ISSUE TITLE
Installing Python Tools for VS2015 Sep 2016 Breaks C++ installation

### ISSUE THREAD

**Issue by prjahelka** [Microsoft/PTVS#1636]
After installing this update, my C++ projects won't load.

**Comment by zooba** [comment]
Are you able to provide any logs or further information? There were potentially other updates installed at the same time (assuming you used the Visual Studio installer), so we'll need more information to figure out the cause.

**Comment by pgerell** [comment]
I had the same problem. When opening my solution all projects failed to load and I was prompted with "install visual c++ 2015 tools for windows desktop"

**Comment by zooba** [comment]
@pgerell Does it work after you install the tools?

**Comment by pgerell** [comment]
Yes. It works again.

**Comment by zooba** [comment]
Did you install with the MSI from GitHub? Or through the Visual Studio installer?

**Comment by pgerell** [comment]
Through the Visual Studio installer.

**Comment by zooba** [comment]
Okay, you will have received some other updates too. I'll pass the feedback onto the team, as I suspect it's not directly our fault.

**Comment by SmithCpp** [comment]
We are unable to repo your issue with the available information. Could you collect the logs of your install with http://bit.ly/vscollect and post to a place we can access?
