### ISSUE TITLE
Debug and Launch Settings deletes previous customization

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1641]
In Solution Explorer - Folder View, right-click on a .py file and choose Debug and Launch Settings
Add an entry for "WebBrowserUrl":"5555", save and close the file (launch.json)
If you check on disk in .vs folder, you'll see the file has your changes
In Solution Explorer, right-click again on the file and choose Debug and Launch Settings

Result: Your changes were overwritten with the default.  The opened document doesn't have your changes, and the file on disk (open with notepad) also doesn't have them.

**Comment by zooba** [comment]
I don't see it overwriting any settings, but it certainly provides defaults for the wrong schema.

**Comment by zooba** [comment]
This seems to be okay now (apart from our known limitations)
