### ISSUE TITLE
IOT project template priority

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#165]
I understand we probably want to make people aware of it, but putting it above Python Application is kind of a bold move :)

![iot](https://cloud.githubusercontent.com/assets/1696845/7661725/26976082-fb0a-11e4-8d52-88b0d5533cba.png)

**Comment by zooba** [comment]
(cc @juanyaw)

I think you're right. We probably want to suppress the rollup - the extra category in the treeview will be more obvious once we move it down. (Also, until we handle the lack of dependencies better, we don't want it too prominent.)

**Comment by juanyaw** [comment]
Yes, that is definitely an oversite by me.  I'll look into fixing this

**Comment by juanyaw** [comment]
This should be fixed by merge #174
