### ISSUE TITLE
How to cross debug python and C++ in VS2013?

### ISSUE THREAD

**Issue by choushin** [Microsoft/PTVS#1651]
Hi Sir:

I have a project that contains C++ DLL project and python project. Because I'm coding some algorithm, it's important that the breakpoint can be located anywhere.

When I try to call C++ function from python using CType, it's worked fine and the breakpoint in C++ can be reached while I'm in python code. But when I try to call python function from C++, it can run successfully, but the breakpoint I set in python  project just won't get.

I　use the normal way to call python from C++:

Py_Initialize()

PyAPI....

Py_Finalize()

So what I'm asking is: If I start the project in C++ project, how can I call python function and make the breakpoing set in python be reached in VS2013?? TKS！~

**Comment by zooba** [comment]
@int19h may know... currently we don't have any easy way of doing this, but I believe there was a way to enable specific debug engines in a C++ project.

Actually, the easiest way is probably to have a Python project but set the Interpreter Path in Project Properties to be your executable. We shouldn't pass any special arguments to it, just the name of the selected `.py` file.

(I thought we had an issue somewhere to add support to C++ to allow selecting our debug engine, but I can't seem to find it now.)

**Comment by int19h** [comment]
They have a hardcoded list, which includes JS and managed, but not Python. You can see it in C++ project properties, "Debugger Type" under "Debugging" page. 

I also thought we have an issue for this, but I can't find it either. So I guess this one is it.

**Comment by choushin** [comment]
@zooba @int19h So it can't be done currently, right? Thanks for your time!

**Comment by zooba** [comment]
Not directly from the C++ project, but if you make a Python project that depends on the C++ one and set the Interpreter Path property to the executable then you should be able to start in Python/C debugging mode.

**Comment by zooba** [comment]
Reactivating this since I've been working on it.

The extension mentioned in our [blog post](https://blogs.msdn.microsoft.com/pythonengineering/2017/08/25/python-updates-in-visual-studio-15-4-preview-1/) adds this support, but I'm going to merge it in properly for the next preview. Once that's done, this issue will be resolved.
