### ISSUE TITLE
Class not registered error in project properties

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#166]
PTVS 2.2 30515.00
VS 2015 RC

Create IronPython Application (console, wpf, doesn't matter)
Right click project node

![classnotregistered](https://cloud.githubusercontent.com/assets/1696845/7661936/ddb78804-fb0b-11e4-9e1f-0cb4943f9c0f.png)

I installed IronPython after installing PTVS.  Also I've restarted VS several times.

Edit: This also happens with Python Console app, it's not restricted to IronPython.
Edit 2: Also repros in VS 2013.

**Comment by zooba** [comment]
I can't reproduce this any more. Can you try with a newer PTVS build?

**Comment by huguesv** [comment]
Me neither, on debug rolling build.  Maybe the common project changes that went in yesterday fixed this.
