### ISSUE TITLE
Support rich cookiecutter fields

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1662]
See https://github.com/audreyr/cookiecutter/pull/360 for the support that exists in cookiecutter to support rich fields.

We should use the prompt and default fields from dict objects when they exist. We should also support a richer set of types than cookiecutter so that we can offer UI in VS for selecting values. For example:
- file/directory selector
- DB connection string
- Azure subscription/resource group
- (more ideas?...)

**Comment by huguesv** [comment]
There's a few open pull requests (including the one linked above) to improve prompts and/or user input validation, but none have been accepted so far.

**Comment by zooba** [comment]
You're right, I misread the green label and thought it was finished.

Let's see if the discussion at https://github.com/audreyr/cookiecutter/issues/794 goes anywhere, and if not we should look for a `_vs_parameters` key with `label`, `help` (tooltip), `watermark` (replace visible default value), and `selector` fields (all optional, defaulting to current behaviour), similar to the proposal at that issue.

**Comment by huguesv** [comment]
We've implemented this using our own extension to the template format.
