### ISSUE TITLE
Python environment description hard to read on blue and dark themes

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1668]
![image](https://cloud.githubusercontent.com/assets/1696845/18895138/186d1df6-84cc-11e6-8829-25648427c277.png)

![image](https://cloud.githubusercontent.com/assets/1696845/18895163/4c5a116e-84cc-11e6-91a6-47c187a6db6b.png)

**Comment by zooba** [comment]
Also the dropdown on the dark theme:

![image](https://cloud.githubusercontent.com/assets/1693688/20847083/5d66372e-b881-11e6-924c-06c19982a116.png)
