### ISSUE TITLE
IronPython no IntelliSense on user built .NET dll

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#167]
I get a squiggly which doesn't go away. The code runs fine. Also I don't get any IntelliSense on ClassLibrary1 or MyCalculator. 

![ironpython-squiggly](https://cloud.githubusercontent.com/assets/1696845/7661980/3ce271f4-fb0c-11e4-9cfe-98a8f639ab34.png)

Ported from: https://pytools.codeplex.com/workitem/2721

Verified that it still occurs on VS 2015 RC with PTVS 2.2 30515

**Comment by gnychis** [comment]
Can you verify that you are building ClassLibrary1 with "AnyCPU" architecture?  I had this issue when I had it fixed to x64.

**Comment by zooba** [comment]
Also check that it works when you run it. We "handle" most calls through `clr` by forwarding them to IronPython and letting it do the load, and `AddReferenceToFile` may not be working with a partial assembly name - try `AddReference`.
