### ISSUE TITLE
Python Tools for Visual Studio (September 2016) failed to install

### ISSUE THREAD

**Issue by bgoldstein14** [Microsoft/PTVS#1671]
I've tried on a couple of different computers to execute the suggested update for the Python Tools within Visual Studio 2015 (with most recent VS updates on Windows 7 - 64-bit) without luck. I get a message stating: "The selected Visual Studio item 'Python Tools for Visual Studio (September 2016)' failed to install. Check the %Temp% directory for VS install logs."

When reviewing the Windows\Temp directory there are no logs indicating any recent install failure.

What might I try to get the installation to work?

**Comment by huguesv** [comment]
I'm not really sure, but our resident expert @zooba is out at a conference, so I'll see what I can do.

Can you try installing and running this?
https://www.microsoft.com/en-us/download/details.aspx?id=12493

"The log collection tool creates a compressed cabinet of all the Visual Studio, .NET Framework, and SQL Server setup logs and other supporting logs at %TEMP%\vslogs.cab"

If it creates a .cab file, please send it over to us at ptvshelp at microsoft.com

I suppose you could try to install directly from the msi at https://github.com/Microsoft/PTVS/releases/tag/v2.2.5post1

You could uninstall the old version first, that might help.

You can have it log by running from a command prompt with `msiexec "PTVS 2.2.5 VS 2015.msi" /l*v ptvs.log`

**Comment by zooba** [comment]
The logs are going to be in `C:\Users\You\AppData\Local\Temp`, since that is where `%TEMP%` generally refers (rather than `C:\Windows\Temp`, which is only used for a few admin-only service accounts and not for real users anymore).

The collection tool is a good way to make sure you get all the right information though.

**Comment by bgoldstein14** [comment]
Thank you for your replies! As you know, work can push you down many paths and I will need to come back to this in short order and let you know what happens. I'm thinking that my best course of action will likely be to uninstall and attempt to reinstall the components within Visual Studio.
