### ISSUE TITLE
Can't create virtual environment on Data Science workload Anaconda

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1678]
Dev15 Preview 5 with Data Science only

```
>>> import sys
>>> sys.version
'3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]'
>>> 
```

Right click on Python Environments, Add Virtual Environment

Not sure why it's trying to use virtualenv instead of venv?  It can't install it because it's not elevating.

```
----- Installing 'https://go.microsoft.com/fwlink/?LinkID=317969' -----
Collecting https://go.microsoft.com/fwlink/?LinkID=317969
  Downloading https://go.microsoft.com/fwlink/?LinkID=317969 (1.7MB)
  Cannot determine compression type for file C:\Users\huvalo\AppData\Local\Temp\pip-hw_v7fi3-unpack\fwlink.obj
Installing collected packages: virtualenv
  Running setup.py install for virtualenv: started
    Running setup.py install for virtualenv: finished with status 'error'
    Complete output from command "C:\Program Files\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\huvalo\\AppData\\Local\\Temp\\pip-7nqkz_01-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\huvalo\AppData\Local\Temp\pip-mk11c1p7-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    copying virtualenv.py -> build\lib
    creating build\lib\virtualenv_support
    copying virtualenv_support\__init__.py -> build\lib\virtualenv_support
    copying virtualenv_support\pip-6.1.1-py2.py3-none-any.whl -> build\lib\virtualenv_support
    copying virtualenv_support\setuptools-15.0-py2.py3-none-any.whl -> build\lib\virtualenv_support
    running install_lib
    copying build\lib\virtualenv.py -> C:\Program Files\Anaconda3\Lib\site-packages
    error: could not create 'C:\Program Files\Anaconda3\Lib\site-packages\virtualenv.py': Permission denied
    
    ----------------------------------------
Command ""C:\Program Files\Anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\huvalo\\AppData\\Local\\Temp\\pip-7nqkz_01-build\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\huvalo\AppData\Local\Temp\pip-mk11c1p7-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\huvalo\AppData\Local\Temp\pip-7nqkz_01-build\
----- Failed to install 'https://go.microsoft.com/fwlink/?LinkID=317969' -----

Virtual environment was not created at 'c:\projects\temp\PythonApplication1\PythonApplication1\env\'
```

**Comment by zooba** [comment]
I think this is because of how we were handing the search for `virtualenv` and/or `venv` - typically the FindModulesAsync function is used to find _exactly_ the modules provided, but for this case we don't expect it to find all of them.

That said, I haven't tested my fix against an actual Anaconda install yet, so there could be some weirdness.

**Comment by tjprescott** [comment]
I get this error when I try and create a Python2 virtual environment in VS2017.  

----- Installing pip -----
Did not find C:\Program Files (x86)\Python27\setuptools.tar.gz
Installing with ensurepip
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.3 setuptools-39.0.1
Collecting pip
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
Successfully installed pip-10.0.1 setuptools-39.2.0 wheel-0.31.1
Installation Complete
----- Successfully installed pip -----

----- Installing 'https://go.microsoft.com/fwlink/?LinkID=317969' -----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'main'
----- Failed to install 'https://go.microsoft.com/fwlink/?LinkID=317969' -----

**Comment by huguesv** [comment]
@tjprescott it's because the way we invoke pip on python 2.7 isn't compatible with pip 10. See https://github.com/Microsoft/PTVS/issues/4194
