### ISSUE TITLE
Cookiecutter should do template update notifications

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1679]
Give a visual cue that an update to an installed template is available.
Have a command to do an update.

GitHub gives you a few timestamps:
https://developer.github.com/v3/repos/#list-your-repositories

```
    "pushed_at": "2011-01-26T19:06:43Z",
    "created_at": "2011-01-26T19:01:12Z",
    "updated_at": "2011-01-26T19:14:43Z",
```

Need to verify that `updated_at` is the value we need.

**Comment by huguesv** [comment]
We have a couple of options:

1. Compare GitHub's `pushed_at` with the local disk `DirectoryInfo().CreationDateUtc`.

This would work since cookiecutter and (us) always delete the folder if it exists before cloning.

Pro: Lightweight check
Con: Calling GitHub too often leads to 403 errors


2. Compare last commit on `origin/master` with `master`. This requires doing a `git fetch` to have access to the remote commits.  We can do a `git merge` to perform the update instead of deleting/cloning again.

Pro: Not calling the GitHub api
Con: Doing a git fetch is more heavyweight. More potential for failure.

**Comment by huguesv** [comment]
FYI GitHub's `updated_at` appears to account for non code changes (issues modified, etc).

**Comment by zooba** [comment]
Is a `git fetch` really more error prone than `git clone`?

**Comment by huguesv** [comment]
I was worried that some cookiecutter template developers may make "improper" use of the folder under `~./cookiecutters`.

For example:
- They install a template for which they are the owner.
- They realize they want to make a change to the template.
- It's tempting to make the change in `~./cookiecutters/mytemplate` repo directly
- They test it by re-running it from Installed section.
- When it works, commit the change and push.

The proper workflow is to not modify the cookiecutter working folder:
- They install a template for which they are the owner.
- They realize they want to make a change to it.
- They clone it to a proper location on disk.
- They make a change
- They test by pasting the folder path in the search box.
- When it works, commit the change and push.

I don't think `git fetch` would fail if they made local changes (`git merge` could though).  It could be unexpected if it's not user initiated and they're using the folder as their development clone.

If that's not worth worrying about, then I can do the `git fetch` for checking update, and do the delete/re-clone for update to ensure no failure due to local changes (we'll be wiping them out).

**Comment by zooba** [comment]
I doubt anyone would use it as the development clone (seems more convenient to point cookiecutter at a local repo), but arguably we should fail if git fetch/merge fails and recommend deleting the repo? It seems a rare enough scenario that a message in the output window should suffice - we can adapt based on feedback.

**Comment by eclectir** [comment]
A global "check for updates" solves the scenario, but I wonder if we can be more proactive by doing running the check in the background when the explorer is loaded at the start of a new Visual Studio session. Similar to what happens when you boot Windows. 

The compare GitHub's  pushed_at  with the local disk  DirectoryInfo().CreationDateUtc should work since we are doing the check only once per session (instead of polling and risking 403 errors) and it is lighter weight than doing a git fetch.

**Comment by huguesv** [comment]
You have to call github once PER template, which means for > 1 templates installed, you are at risk of a 403.  To reduce the risk, you can sleep for a certain period between each call (at least 1 sec), which means we wouldn't be able to have a command the user can click on to "recheck for updates", because that would be expected to finish in a reasonable time.

**Comment by eclectir** [comment]
It is a risk, but how fragile is it? Maybe the risk is less when you are calling GitHub once for each template vs. multiple times. If it is not too much work, can we prototype this and try it out to get some hard data on it before ruling proactive update cues? If you feel that would not help, let's just go with the global, user initiated check.

I feel the 1s delay is a no-op for the reason you mentioned. Also, if we block the full loading of the tool on this to get around, it will degrade the start-up experience of the tool. I think we should avoid any design that leads the behavior of the tool to change (worsen) with how frequently it is used (as # of templates go up).

**Comment by huguesv** [comment]
Search API: 10 requests per minute
https://developer.github.com/v3/search/#rate-limit

All other API: 60 requests per hour
https://developer.github.com/v3/#rate-limiting

Getting a specific repo details is this API, and it falls under "All other API":
https://developer.github.com/v3/repos/#get

We already use it to fetch the template description, for templates from the "Installed" and "Recommended" sections (only when the user selects a template, so we can show it in the info panel at the bottom, and it's cached for the session).

Depending on that API for getting the last pushed date as well can easily push us past that 60 per hour limit.

**Comment by huguesv** [comment]
Automatic + manual check for update has been implemented.
