### ISSUE TITLE
CPU high occupancy

### ISSUE THREAD

**Issue by reaCodes** [Microsoft/PTVS#1680]
When I updated IntelliSense.
CPU: i5-5300U
Hard Disk: Samsung SSD

![qq 20160930105815](https://cloud.githubusercontent.com/assets/13817254/18979448/8aa0b85a-86fd-11e6-9a58-826ed09ff609.png)

**Comment by zooba** [comment]
This is by design - analysing Python code is a difficult task that runs for a while but saves the result. Once it has completed CPU will return to normal.

You also appear to have a system scan running, which is the first two items. They are unrelated to Visual Studio.
