### ISSUE TITLE
Fix text on profiler error messages

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1681]
Sometimes clicking on a profiler report pops the message "File not found" although you can see the reports listed in the Treeview. This can happen if the program is not doing enough computation. We should say that “Your program may not be doing enough computation” or some version of it.

**Comment by zooba** [comment]
I can't reproduce this even with an empty file. Perhaps @huguesv has more info about the sort of scripts this occurs for?

**Comment by huguesv** [comment]
No repro for me right now (on VS 2015).  Empty file still produces report.

**Comment by zooba** [comment]
Okay, this seems to be a problem where the file is never created but we still create the hierarchy node. We should validate that profiling actually succeeded before creating the UI for the node.
