### ISSUE TITLE
Dialog popup related to external packages on new project doesn't handle elevation

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1682]
Since Dev 15 installs CPython/Anaconda into Program Files, and requires elevation to do any type of package install, it is likely that the first steps a user takes after installing VS will fail:
- New Project, Bottle Web Project
- Dialog pops up asking to install packages
- Choosing to create a virtual environment will fail if using Anaconda. See https://github.com/Microsoft/PTVS/issues/1678
- Choosing to install packages into global Anaconda will also fail

**Comment by zooba** [comment]
AFAICT, the correct UI handlers are already being used, so this should be fine. But something could be going wrong, so will test.

**Comment by zooba** [comment]
Cannot reproduce this.
