### ISSUE TITLE
Intellisense packages are not sorted

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1694]
In addition to #1585, we don't sort the packages in this list. They should be sorted alphabetically.

**Comment by huguesv** [comment]
Was this closed accidentally?  They are still not sorted.
![image](https://cloud.githubusercontent.com/assets/1696845/25458151/b17e848c-2a8d-11e7-8486-abbe6617b70c.png)

**Comment by zooba** [comment]
They are sorted by full name, but we only display the last segment. I don't remember why that is exactly.
