### ISSUE TITLE
Modules in search paths show as unresolved

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1698]
From [Developer Community](https://developercommunity.visualstudio.com/content/problem/275/python-import-statements-have-unable-to-resolve-mo.html)

Add a search path to a directory containing python modules. Import one of those modules to another python file. The import statements will have green squiggily lines under them with the error "Unable to resolve "[module name]". Intellisense may be missing for this module". However, the intellisense for the module does in fact work.

**Comment by zooba** [comment]
This will be fixed with #1729

**Comment by michaeldaw** [comment]
I don't have anything quantitative to substantiate this, but intellisense does seem to be working a lot better in the new release. Thanks for looking into it!
