### ISSUE TITLE
Python program not showing result or output in Windows console

### ISSUE THREAD

**Issue by shatir** [Microsoft/PTVS#1704]
I am new to python tools for visual studio and need help.

I tried to run a simple "Hello World" code but cannot see its output. To give the details regarding the problem I have created a short video showing the issue while executing the code and python environment settings selected in my visual studio. Please check this link http://www.screencast.com/t/kFU7HsOtiGIk.

**Comment by zooba** [comment]
Firstly, thank you for the excellent screen capture!

The first thing I'd ask you to try is to disable the "Wait after [ab]normal exit" options and add `input()` at the end of your program. When either of these options are set, we run via `cmd.exe`, and it's possible that there is added processing or policies in effect that could cause trouble. Without those options, we run `python.exe` directly, but then you have to add the pause yourself.

If this is a common problem, we could look at implementing our own launcher to handle the pause at the end. But we haven't seen this issue in the past, so I'm interested to figure out what's different in this case.

**Comment by shatir** [comment]
As suggested by you I added input() to the code and ran the code
1) Without changing any settings
2) With only "Wait after abnormal exit" disabled
3) With only "Wait after normal exit" disabled
4) With both the settings "Wait after [ab]normal exit" disabled

But still I faced the same issue. Please have a look at this link http://www.screencast.com/t/TfuOQVo7rtV

**Comment by zooba** [comment]
What happens when you right-click in the file and select "Start with debugging" or "Start without debugging"?

**Comment by shatir** [comment]
Nothing happens when I select "Start with debugging" or "Start without debugging"

**Comment by zooba** [comment]
In the Python Environments window, when you select your installed environment, there is a link to the .exe file (see it [here](https://github.com/Microsoft/PTVS/wiki/Python-Environments#global-environments)). What happens when you click on that? You _should_ get a Python console window.

**Comment by shatir** [comment]
Yes it opens the Python console window. I believe its not the problem with python installation or python environment setting because if you see my first video I sent you could notice that I was successfully able to run the code in interactive window by right-clicking it.

**Comment by zooba** [comment]
I agree, but it's always worth checking the easy stuff first.

Next thing: can you find a file names `C:\Users\<you>\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache\Microsoft.VisualStudio.Default.err` and - if it exists - post it as a [gist](https://gist.github.com) or email it to ptvshelp@microsoft.com?

**Comment by shatir** [comment]
Your requested file is empty.

**Comment by zooba** [comment]
@shatir Apologies for forgetting about this issue and not replying to you. Do you still want to try to figure this out? Or have you moved on?

**Comment by shatir** [comment]
Thanks man ... I have already figured out and fixed the issue.

**Comment by shatir** [comment]
For all those who are facing same problem they should check for any broken extensions installed. In my case it was Xamarin.

To fix my issue I had to uninstall the Visual Studio completely not simply from control panel but by using VisualStudioUninstaller command line tool. This tool will help uninstall all extensions linked with visual studio but still it will not remove some hidden folders and entries from registry so I manually removed registries and hidden folders for Visual Studio. You also need to remove a local folder in which all the setup files for xamarin are downloaded.

**Comment by doctor-mosbat** [comment]
Install Python and the Python extension For a quick install, use Python 3.8 from python.org and install the extension from the VS Code marketplace. Now, create a Python file and then:
![Untitled](https://user-images.githubusercontent.com/40474178/80857768-b2f3d380-8c69-11ea-84ae-d95784a42015.jpg)

**Comment by JRitmeester** [comment]
@doctor-mosbat You do realise you're just necroposting on an issue that is more than 3 years old, right?

**Comment by huguesv** [comment]
@doctor-mosbat for VS Code, please file an issue at https://github.com/microsoft/vscode-python/

**Comment by Tabrez007-Ahmad** [comment]
#my code is also not running what is the error can someone tell me                                                                                                                                                                                                   
  class Test:
    def __init__(self,str1):
        self.str1=str1
    def check(self):
        str2=self.str1.lower()
        splitstr=str2.split(" ")
        if ("light" in splitstr):
            for i in range(len(splitstr)):
                if (splitstr[i]=="percent"):
                    if(int(splitstr[i-1])>=100):
                        retstr="light-->100"
                    elif (int(splitstr[i-1])==0):
                        retstr="light-->off"
                    else:
                        retstr="light"+splitstr[i-1]
                        print(retstr)
        elif ("fan" in splitstr):
            for i in range(len(splitstr)):
                if (splitstr[i]=="percent"):
                    if(int(splitstr[i-1])>=100):
                        retstr="fan-->100"
                    elif (int(splitstr[i-1])==0):
                        retstr="fan-->off"
                    else:
                        retstr="fan"+splitstr[i-1]
                        print(retstr)   
        else:
            print("no occurence")
t1=Test("light is on 100 percent")       
t1.check()

**Comment by gresm** [comment]
@Tabrez007-Ahmad 
Maybe incorrect code indent?
I see one more problem...
> elif ("fan" in splitstr):

there is no need of these ()
correct shoud be:

elif "fan" in splitstr:

Maybe repost cleaner code?

**Comment by kat0016-k** [comment]
i have the same problem with my code please help python isn't working.





mylists = [1,2,3,4,5,6,7,8]

def even_bool(num):
     return num%2 == 0

evens = filter(even_bool, mylists)
print(list(evens))
![image](https://user-images.githubusercontent.com/66197595/186070335-eef4a600-b1c8-4c33-a618-11c0680cdf59.png)
