### ISSUE TITLE
Python solutions not loading

### ISSUE THREAD

**Issue by pyuser00** [Microsoft/PTVS#1706]
Every time I open a *.sln, the solution fails to load with the 

error:'Microsoft.VisualStudio.Editor.Implementation.EditorPackage' did not load correctly. 

And each time I open a solution I need to 'install missing features' through Solution Explorer and then re-open each *.py file for intelli-sense to kick in, at which point all code folding/outlining is lost.

This is likely a continuation of issue #1573

**Comment by zooba** [comment]
This sounds like a corrupt installation - there's generally no reason for that package to fail to load.

Can you see whether you have a `C:\Users\<you>\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml` file? If so, that would be very helpful. It likely has the specific error message in it showing what is wrong.

**Comment by pyuser00** [comment]
ActivityLog.xml; all type=error:

 <entry>
    <record>378</record>
    <time>2016/10/10 16:44:36.011</time>
    <type>Error</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.VisualStudio.TeamFoundation.TeamExplorer.Extensions&apos; is already loaded at C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\4NDYSCFD.VN2\...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TEAMFOUNDATION\TEAM EXPLORER\</path>
  </entry>
  <entry>
    <record>379</record>
    <time>2016/10/10 16:44:37.918</time>
    <type>Error</type>
    <source>Color Theme Service</source>
    <description>The color &apos;Popup&apos; in category &apos;de7b1121-99a4-4708-aedf-15f40c9b332f&apos; does not exist.</description>
  </entry>

**Comment by pyuser00** [comment]
missed one:
<entry>
    <record>387</record>
    <time>2016/10/10 16:44:44.218</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.PythonTools.Extensions.GetAnalyzer(ITextBuffer buffer, IServiceProvider serviceProvider)&#x000D;&#x000A;   at Microsoft.PythonTools.PythonClassifier..ctor(PythonClassifierProvider provider, ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.PythonTools.PythonClassifierProvider.GetClassifier(ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)</description>
  </entry>

**Comment by zooba** [comment]
Are you on the latest release? This was supposed to be fixed in our last update ([2.2.5](https://github.com/Microsoft/PTVS/releases/tag/v2.2.5post1))

**Comment by pyuser00** [comment]
Confirmed issue resolved with upgrade to v2.2.5.

Note VS --> Help --> About lists PTVS version as 2.2.40825.00, which is a source of confusion.
