### ISSUE TITLE
Python profiling tool disables regular profiler for c#

### ISSUE THREAD

**Issue by hecsalazar** [Microsoft/PTVS#1714]
I noticed that the original profiler is not available anymore, in the "Analyze" menu, so i've been unable to debug c# code

**Comment by zooba** [comment]
Which version of Visual Studio? I see "Performance Profiler" in both VS 2015 and VS 15 (with just Python installed).

**Comment by hecsalazar** [comment]
VS 2015 pro update 2

**Comment by huguesv** [comment]
For VS 2015 pro update 2, it's Debug / Start Diagnostic Tools Without Debugging.  I don't see an entry under Analyze menu.

For VS 2015 pro update 3 (I was forced to update when trying to install Python Tools via VS installer), it's Debug / Performance Profiler AND Analyze / Performance Profiler.
