### ISSUE TITLE
PTVS search path not working

### ISSUE THREAD

**Issue by slegall56** [Microsoft/PTVS#1716]
Hi, 
I created two simple projects, project1 and project2 which contain respectively one file, file1.py and file2.py

Content of file1.py : 
```
def test():
    return 0
```

Content of file2.py
```
import file1 as f
a = f.test()
```

But when launching project 2 I got "No module name file1" even if intellisense manage to find it

I'm working on vs 2015 community and PTVS 2.2.3

**Comment by huguesv** [comment]
Hi! In Solution Explorer, you'll need to right-click on project2's Search Paths node and select the project1 folder.

**Comment by slegall56** [comment]
Hi, 

That is what I did but it did not worked

**Comment by zooba** [comment]
Can you share the folder/file structure of your projects and the search path you added?

**Comment by slegall56** [comment]
Well strange it works this morning, just have to reboot my computer. Soory for that
