### ISSUE TITLE
[Cookiecutter Explorer] Refresh template list while typing after small delay

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1722]
After conducting an initial search, I need to clear the text in the box and hit search again to restore the default view (which shows installed templates, recommended templates, etc). Could we program this so when the search string hits length == 0, we restore the default view?

**Comment by huguesv** [comment]
You can press ESC in the text box, it will clear and refresh the view.

Automatic delayed refresh while typing is something I wanted to do eventually, and since there's no issue filed on it, we'll make it this one.
