### ISSUE TITLE
[Cookiecutter Explorer] Surface variable input requirements or errors in the tool UI instead of the output Window

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1723]
There is no way to know what the input restrictions of the cookicutter variables are. Consider the case below involving the Azure Web App cookiecutter. The project failed to create because there was an invalid character in the site name “Usman_Site”. I had also tried “Usman’s Site” and “Usman Site” before. So it took me three tries to realize that no special characters or spaces are allowed. It would be nice to surface the variable input related errors under the variable entry in the explorer instead of in the output window.  Maybe we can work with cookiecutter to come up with a standard way of surfacing these errors outputs so we can easily catch them for display?

![cookiecutter-input](https://cloud.githubusercontent.com/assets/5177491/19377973/e610a46a-919e-11e6-9d23-b06bfca1818c.jpg)

**Comment by huguesv** [comment]
A few relevant issues:
https://github.com/audreyr/cookiecutter/issues/381
https://github.com/audreyr/cookiecutter/issues/175
