### ISSUE TITLE
[Cookiecutter Explorer] Rename "Recommended" Section

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1724]
“Recommended” Section – I think we should just call this section “Azure Templates”. It feels a bit off to have a recommended section that does not explain how templates get recommended, who recommends them, or if they are based on some user preferences (using a recommendation engines etc). In absence of any recommendation framework, we should just call the section what we intend it to be for now – a section of Azure templates. We can revisit this when (and if) we have recommendation smarts.

**Comment by huguesv** [comment]
We designed it so they can customize the feed location in tools/options.  It won't make much sense for them to customize the azure feed.  Do we get rid of the customization as well?

**Comment by huguesv** [comment]
Thinking more about this, our original idea was to do like NuGet and have a list of customizable feed with Name/Uri pairs.  We would have used the 'Name' part in the tree view.

We ended up simplifying to a single feed instead, to save time doing all that UI work in the options page, and the updates to the registry saving/loading wrappers.

We could solve this for now by having an additional text box in tools/options to specify the name for the single customizable feed.

**Comment by zooba** [comment]
I think we're likely to have to go scenario and/or language focused in the future. But it's not blocking.
