### ISSUE TITLE
Tests are not launched in VS15 preview 5

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1727]
Using VS15 preview 5, I can see my tests in the test explorer:
![image](https://cloud.githubusercontent.com/assets/1050156/19405208/f748be76-9229-11e6-8945-fac6c6231e18.png)

But if try to launch them, it does nothing. "Run selected tests" does nothing. "Run all" seems to think (button switch to Cancel), but nothing happens.

Got a message on TEst output

```
Cannot discover test extensions installed by NuGet. The NuGet service is not available. Tests may not be found due to missing test adapter extensions.
```

Microsoft Visual Studio Enterprise 15 Preview 5
Version 15.0.25802.0 PREVIEW
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual Basic 15 Preview 5   00369-50000-00000-AA578
Microsoft Visual Basic 15 Preview 5

Visual C# 15 Preview 5   00369-50000-00000-AA578
Microsoft Visual C# 15 Preview 5

ASP.NET and Web Tools 2016   15.0.20908.0
ASP.NET and Web Tools 2016

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft .NET Core Tools   15.0.20908.0
Microsoft .NET Core Tools

Python Tools for Visual Studio   3.0.16266.1
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Cookiecutter Integration   3.0.16266.1
Provides cookiecutter integration.

Python Tools for Visual Studio - Django Integration   3.0.16266.1
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   3.0.16266.1
Profiling support for Python projects.

TypeScript   2.0.5.0
TypeScript tools for Visual Studio

**Comment by lmazuel** [comment]
In "Run all" mode, when I click "Cancel" I got:
```
========== Run test finished: 0 run (0:02:38.880) ==========
```

**Comment by lmazuel** [comment]
Launching my test directly using "Start without debugging" is ok:
![image](https://cloud.githubusercontent.com/assets/1050156/19405569/bdd391e4-922d-11e6-98e9-ea31112b7854.png)

**Comment by huguesv** [comment]
Can you try with a new project?  New Python Application, Add New Item->Python Unit Test.

That's working for me with Dev 15 Preview 5.

**Comment by lmazuel** [comment]
@huguesv That's working with your scenario

**Comment by zooba** [comment]
There seems to be an issue with extra text being sent when an error or possibly a warning is raised.

@lmazuel Can you try fixing that deprecation warning and trying again?

**Comment by zooba** [comment]
There seems to be an issue with extra text being sent when an error or possibly a warning is raised.

@lmazuel Can you try fixing that deprecation warning and trying again?

**Comment by lmazuel** [comment]
@zooba That's better, but now I have this output:
```
------ Run test started ------
Cannot discover test extensions installed by NuGet. The NuGet service is not available. Tests may not be found due to missing test adapter extensions.
Unexpected test result: .
Unexpected test result: .
========== Run test finished: 0 run (0:00:00.924) ==========
```

**Comment by huguesv** [comment]
For me, discovery is unreliable (sometimes I get them all discovered, sometimes partial, sometimes none).

But when I do get the tests discovered, I get the above error `Unexpected test result: .` for tests that have an import that fails. For example, the test for commerce mgmt fails because the search path doesn't include the commerce mgmt folder.  But the test for cdn mgmt succeeds, and that one is in the search path.

**Comment by zooba** [comment]
@huguesv We collect test info from the analyzer now, so when it fails there may be relevant messages in the Diagnostic Info window.

**Comment by huguesv** [comment]
Simple repro:
Create new python application
Add new item, python unit test
Add `import foooo` at the top of the file
Open explorer and run the test

Result:
The test doesn't 'fail' and the output window shows:
```
------ Run test started ------
cd c:\users\huvalo\documents\visual studio 2015\Projects\PythonApplication4\PythonApplication4\
set PYTHONPATH=c:\users\huvalo\documents\visual studio 2015\Projects\PythonApplication4\PythonApplication4\
C:\Users\huvalo\AppData\Local\Programs\Python\Python35-32\python.exe "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0EXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON TOOLS FOR VISUAL STUDIO\3.0\visualstudio_py_testlauncher.py" -t test1.Test_test1.test_A -r 12512
Unexpected test result: .
========== Run test finished: 0 run (0:00:00.7704042) ==========
```

**Comment by huguesv** [comment]
Running the launcher script directly with the cmd line that was printed above (minus the -r):
```

C:\Users\huvalo\Documents\Visual Studio 2015\Projects\PythonApplication4\PythonApplication4>C:\Users\huvalo\AppData\Local\Programs\Python\Python35-32\python.exe "C:\USERS\HUVALO\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0EXP\EXTENSIONS\MICROSOFT CORPORATION\PYTHON TOOLS FOR VISUAL STUDIO\3.0\visualstudio_py_testlauncher.py" -t test1.Test_test1.test_A
======================================================================
ERROR: test1 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test1
Traceback (most recent call last):
  File "C:\Users\huvalo\AppData\Local\Programs\Python\Python35-32\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\huvalo\Documents\Visual Studio 2015\Projects\PythonApplication4\PythonApplication4\test1.py", line 2, in <module>
    import foooo
ImportError: No module named 'foooo'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

C:\Users\huvalo\Documents\Visual Studio 2015\Projects\PythonApplication4\PythonApplication4>
```

**Comment by huguesv** [comment]
While this now works with Python 2.7, it still doesn't work with 3.5.
