### ISSUE TITLE
Python library not scraped when using Maya 2016

### ISSUE THREAD

**Issue by Artfunkel** [Microsoft/PTVS#1734]
I'm using Maya 2016's Python interpreter with these settings:

![maya_interp](https://cloud.githubusercontent.com/assets/3618066/19515408/319d64aa-95ef-11e6-9f34-2be6f1707c8a.png)

The lib folder is strange because I can't get any of the libraries to load, no matter what. If I head to the Intellisense tab of the Python Environments window and hit Refresh DB it says "Collecting files" for a moment and that's it. No files are found even when `H:\mayapy\Lib` contains only one module containig one variable.

Modules embedded in the Python binary (e.g. `array`, `datetime`) work fine and have full intellisense. Nothing else is recognised.

I've discovered an oddity that may be the cause: Maya will force `sys.path` to a certain directory to the exclusion of any custom search paths the user may have set up. This is the list of paths which it enforces:

C:\Program Files\Autodesk\Maya2016\bin\python27.zip
C:\Program Files\Autodesk\Maya2016\Python\DLLs
C:\Program Files\Autodesk\Maya2016\Python\lib
C:\Program Files\Autodesk\Maya2016\Python\lib\plat-win
C:\Program Files\Autodesk\Maya2016\Python\lib\lib-tk
C:\Program Files\Autodesk\Maya2016\bin
C:\Program Files\Autodesk\Maya2016\Python
C:\Program Files\Autodesk\Maya2016\Python\lib\site-packages

If I add `C:\Program Files\Autodesk\Maya2016\bin\python27.zip` as a search path for my project Visual Studio immediately crashes.

**Comment by zooba** [comment]
I really need to get a copy of Maya so I can work on our integration... maybe I should reach out and see if they'll give me one :)

If VS crashed as a result of adding the ZIP file, you should have a stack trace in the Event Log or in the Diagnostic Info log. However, I'm right now in the process of removing all that code from our next release (Visual Studio "15"), so the only fix for VS 2015 is likely to be to prevent the crash and not to make it fully functional. (Though one quick question is: does that file even exist? Python adds it to sys.path automatically but ignores it if it isn't real.)

I would be interested to see the analysis log. Probably sending through your entire Diagnostic Info is easiest - either a [gist](https://gist.github.com) or ptvshelp@microsoft.com.

**Comment by zooba** [comment]
Oh, I should also mention that we changed the normal behavior of the analyzer to ignore the Library path a while back. It now runs the Python interpreter and inspects sys.path to get the directories to look at.

Right now we assume CPython-equivalent support (see [get_search_paths.py](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Analysis/get_search_paths.py) for an updated and more robust version of what we do in 2.2), so if this is failing it may well cause the rest of the process to fail. But there should be sufficient info in the logs to figure out what's going on here.

**Comment by Artfunkel** [comment]
[Diagnostic Info is here.](https://gist.github.com/Artfunkel/fc27415fbc0b339d4b69289378eced1d)

All paths exist apart from these two:

C:\Program Files\Autodesk\Maya2016\Python\lib\plat-win
C:\Program Files\Autodesk\Maya2016\Python\lib\lib-tk

**Comment by zooba** [comment]
Hmm... looks like we're completely failing to scrape any of Maya's Python.

If you want to try and get something useful, you could try running this command (copied from your log file, with an extra `/lib:` argument to avoid our automatic detection):

```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\Microsoft.PythonTools.Analyzer.exe" /id {a9b04c63-6bc3-40c4-8a47-2f5375410f1f} /version 2.7 /python "C:\Program Files\Autodesk\Maya2016\bin\mayapy.exe" /outdir "C:\Users\tedwards\AppData\Local\Python Tools\CompletionDB\14.0\a9b04c63-6bc3-40c4-8a47-2f5375410f1f\2.7" /basedb "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\CompletionDB" /log "C:\Users\tedwards\AppData\Local\Python Tools\CompletionDB\14.0\a9b04c63-6bc3-40c4-8a47-2f5375410f1f\2.7\AnalysisLog.txt" /glog "C:\Users\tedwards\AppData\Local\Python Tools\CompletionDB\14.0\AnalysisLog.txt" /wait "" /lib "C:\Program Files\Autodesk\Maya2016\Python\lib"
```

It may not get everything, but it shouldn't be any worse than before we changed the handling of the library path. Hopefully it doesn't detect as being out of date and deleting everything repeatedly - there's an option under Tools, Options, Python Tools, General to disable automatic refresh if necessary.

**Comment by Artfunkel** [comment]
That did the trick! I had to use the lib directory I created in order to get everything in one place, but it now works just fine. :)

**Comment by zooba** [comment]
Good to hear!

It might help us ensure that Maya works better in our next version if you could try running [this script](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Analysis/get_search_paths.py) with it and let us know what the output is. You'll need to pass `-S` before the script name, but hopefully it'll print a list of directories rather than an error. In our next update, those will be the directories we search for library modules.

**Comment by Artfunkel** [comment]
> c:\program files\autodesk\maya2016\bin|stdlib|
> c:\program files\autodesk\maya2016\python|stdlib|
> c:\program files\autodesk\maya2016\python\dlls|stdlib|
> c:\program files\autodesk\maya2016\python\lib|stdlib|
> c:\users\tedwards\downloads|stdlib|
> c:\program files\autodesk\maya2016\python\lib\site-packages||

Just beware that the first path is actually pointing to a file called python27.zip, not a directory! That's where Maya's standard library lives so you won't get far without it.

**Comment by zooba** [comment]
Thanks. Adding support for zip files at this point is on our list, but it looks like it won't make it.

One trick you could try is to extract the ZIP file into a directory named exactly the same as the ZIP file. Both Python and VS shouldn't have any trouble with that.

For now I don't think there's a bug here so I'll close the issue. Feel free to reopen it if you think there's anything else that needs to be addressed.
