### ISSUE TITLE
Cookiecutter template label unreadable on dark theme when not focused

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1745]
On dark theme, select a template from the tree view, and give focus to solution explorer or any other tool window / doc window.

![image](https://cloud.githubusercontent.com/assets/1696845/19575561/05e841a6-96c4-11e6-87cb-da8e85b47d4a.png)

**Comment by zooba** [comment]
Guessing we need to bind the non-focused-selected colour to the right one (possibly all the selection colours are incorrect...)
