### ISSUE TITLE
Debug unit test confused about which debugger to use

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1748]
VS 2015 Update 3 + PTVS 3.0

This happens with the azure-sdk-for-python solution. I will try to repro on another project.

It's trying to use the mixed-mode debugger, but that's turned off in my project settings.

![image](https://cloud.githubusercontent.com/assets/1696845/19579447/99204c1e-96d5-11e6-89bc-e66fd36a446d.png)

![image](https://cloud.githubusercontent.com/assets/1696845/19579461/afed8fe2-96d5-11e6-81ff-e97fca47343f.png)

**Comment by zooba** [comment]
Our bool parsing code is broken.
