### ISSUE TITLE
Django syncdb removal, and migrations support

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#175]
If you try running our django syncdb command on django 1.8, you'll see:
```
The syncdb command will be removed in Django 1.9
```

It appears that we should include commands, and refer to migrations (in docs, readme, etc) instead.
https://docs.djangoproject.com/en/1.8/topics/migrations/

**Comment by kevin-brown** [comment]
:+1: 

The starting place would be to [replace the existing `syncdb` target](https://github.com/Microsoft/PTVS/blob/298bf4057811026227ae4d0e28b5e8d33c7aad46/Python/Product/Django/Microsoft.PythonTools.Django.targets#L207-L219) with a `migrate` one.

Side note: https://github.com/Microsoft/PTVS/issues/334 is also related, but for the missing `makemigrations` target.
