### ISSUE TITLE
can`t press +custom in python environments

### ISSUE THREAD

**Issue by rufengsuixing001** [Microsoft/PTVS#1760]
![image](https://cloud.githubusercontent.com/assets/22387141/19625452/6e2b634a-994b-11e6-8dc6-31dc4f2d2603.png)

i have python 3.5 32 and python 3.6 64
it occur after i write 3.6 in it，and it occurs an error，i wait for a short time and use Taskmgr to kill it。
and it can`t be config again,just like the picture shows.

**Comment by rufengsuixing001** [comment]
i choose repair ,but  can`t fix it.
i uninstall python tools and reinstall it , can`t fix it too.
what should i do.

**Comment by zooba** [comment]
Does restarting VS let you click it again? If so, can you get us a copy of the error it displays? (It is normal behavior for the button to become disabled after an error occurs, but it should come back after restarting.)

**Comment by rufengsuixing001** [comment]
restart is useless ，i have tried for many times。
i try to reinstall vs（not repair） ，try to reinstall  Python interpreter ，but useless。
finally i format c: and reinstall the windows10 operating system and vs，it was helpful。
i am sorry i didn't have the copy of display。
i just remember after i choose the 3.6 piefix path，press auto detect,press apply ,it get a error。
