### ISSUE TITLE
Intellisense gives strange data types for unittest.TestCase.assertEqual

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#178]
This may turn out to be technically correct, but it is unexpected. This is a case where seeing the data types in the intellisense will confuse you more than if they weren't there. 

![assertequal](https://cloud.githubusercontent.com/assets/1696845/7663191/2e6eac82-fb1b-11e4-973c-74e358558ef9.png)

For the other asserts, it's actually pretty good.  It's assertEqual that's the worse.  Note that it's slightly different between Python 2.7 and 3.4.

Steve's comment:
We should special-case the analysis of unittest to assume object. This will also improve DB refresh times, since we spend quite a bit of time analyzing the test suite because of this.

From: https://pytools.codeplex.com/workitem/1582
Verified on VS 2015 RC with PTVS 2.2 30515

**Comment by zooba** [comment]
No longer applies, as we're not using this sort of code analysis on unittest any more.
