### ISSUE TITLE
Error profiling Dev15 RC

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1785]
This is a day or two old build of Dev15 RC with updated PTVS build (today's) using our install script.

I created a bottle app
I selected virtual env option (based on 3.5)
App works when I launch with F5
Launch Python profiling
Result in command prompt:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Profiling\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Profiling\vspyprof.py", line 65, in profile
    pyprofdll = ctypes.PyDLL(profdll)
  File "C:\Program Files\Python35\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Press any key to continue . . .
```

If this is because I'm missing some VS component (when I installed VS i only picked Python workload), then we need to check for it early in the command handler, tell the user if it's missing, and I assume use IVsProjectAcquisitionSetupDriver  like done in https://github.com/Microsoft/PTVS/pull/1769.

**Comment by zooba** [comment]
No, that error means that our DLL is not there. Can you post a file listing of the `Extensions\Microsoft\Python\Profiling` directory?

**Comment by huguesv** [comment]
```
extension.vsixmanifest
Microsoft.PythonTools.Profiling.dll
Microsoft.PythonTools.Profiling.pdb
Microsoft.PythonTools.Profiling.pkgdef
proflaun.py
Python Tools for VS License.rtf
PythonProject.ico
PythonProjectBig.ico
VsPyProf.dll
VsPyProf.pdb
vspyprof.py
VsPyProfX86.dll
VsPyProfX86.pdb
```

**Comment by huguesv** [comment]
Profiling works fine on d15prerel build 25828.02 with data science workload on anaconda.
