### ISSUE TITLE
Autocomplete for fuzzy match should bring up completions even when there's just one item

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1789]
Add this code to empty file:
```
int get_current_language_bidi() {
    return 0;
}
```

Type this:
```
curdi
```

If completions appear, dismiss them.

Now go at the end of `curdi` and hit ctrl-space.

Result:

It changes the code to `get_current_language_bidi`.

Expected:

Bring up completions with a single entry `get_current_language_bidi` in it.  This is what happens for the equivalent scenario in C++.

Note that if you type `get_current_` and repeat the same steps, it changes the code to `get_current_language_bidi` in both Python and C++, which is correct.

**Comment by zooba** [comment]
Ctrl+Space is Complete Word, which only brings up the list if there is ambiguity. Use Ctrl+J to List Members and see the list regardless of how many matches there are.

**Comment by huguesv** [comment]
So it's C++ that's wrong?

**Comment by huguesv** [comment]
I would say that there is ambiguity if what you typed does not resemble at all what it's going to auto complete with.

**Comment by zooba** [comment]
It'd be worse to break Ctrl+Space for all the cases where the selected word is the correct one. Improving the fuzzy match algorithm has some open enhancement items already.
