### ISSUE TITLE
Support PEP 448 syntax

### ISSUE THREAD

**Issue by lordcrc** [Microsoft/PTVS#1798]
[PEP 448](https://www.python.org/dev/peps/pep-0448/) generalizes unpacking, for example allowing for code such as `z = {**x, **y}` to merge dictionaries.

Currently the parser gets all confused by this syntax.

**Comment by zooba** [comment]
We already have #337 tracking this, but thanks for the reminder. It wouldn't surprise me if `{**x, **y}` is a case we've missed since it looks like a set.

**Comment by lordcrc** [comment]
Ah, sorry for the noise, I messed up the search it seems.
