### ISSUE TITLE
NuGet package install support

### ISSUE THREAD

**Issue by JaggerJo** [microsoft/PTVS#1801]
C# like installing of nuget packages

**Comment by zooba** [comment]
We tried to get this once before and nuget rejected our pull request. It may be time to try again.

**Comment by huguesv** [comment]
@JaggerJo can you tell us more about your scenario? What Python environment are you using (CPython, IronPython) and what type of packages would you like to install from NuGet?

While we have our own ideas on why NuGet would be useful, having real customer scenarios that we can point to is valuable when discussing with NuGet team.

**Comment by JaggerJo** [comment]
@huguesv 

**IronPython**
I am using IronPython [v2.7.5.0] with the current Python Tools for VS

**Usecase**
I want to install NuGet packages => download the dlls and reference them in IronPython (For Example Nancy (HTTP Webserver))

**Comment by JaggerJo** [comment]
@zooba 
Yes, PIP support for normal Python is great, but for IronPython the equivalent in NuGet..

**Comment by denfromufa** [comment]
Pythonnet will also benefit from nuget packages:

https://github.com/pythonnet/pythonnet/issues/165

**Comment by denfromufa** [comment]
pythonnet now supports nuget:

https://www.nuget.org/packages/pythonnet/2.3.0-py27-dotnet
https://www.nuget.org/packages/pythonnet/2.3.0-py35-dotnet

https://www.nuget.org/packages/pythonnet_py27_dotnet/
https://www.nuget.org/packages/pythonnet_py35_dotnet/

**Comment by VinayGupta23** [comment]
Is there any plans to develop this?

As a concrete example of my usage, I want to download a plotting library (in particular, https://lvcharts.net/) from NuGet for use in my IronPython + WPF application.
