### ISSUE TITLE
Offer to install missing packages

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1809]
**Scenario:** I created a regression project using the ML pack. It had dependencies on sci-kitlearn and pandas. The project can run without any customizations, but I need to pip install the dependencies first.
 
**Feature:** It will be awesome if PTVS detects these on project load and give an option to install them if they are not already installed in the selected Python environment. 

**Potential Implementation:** The pieces we need to do this seem to be in place already. One implementation I could think of:
a.	On project load, run the analyzer in the background to detect the first missing import.
b.	Show some UI that asks to install the missing package and detect the next one. 
c.	If user chooses yes, call the Pip install on it for the default environment. 
d.	Run the analyzer to detect next missing import. 
e.	It looks like the analyzer can only catch the first missing import is detects, so the above experience  is a piece-wise install of packages. If it could detect all imports, we could show the user option to install packages en masse. Not sure what’s possible here given Python is an interpreted language.

**Comment by zooba** [comment]
This is probably best done as a lightbulb on unresolved imports. Analysis is asynchronous, which means we can't do blocking UI, and project load is a critical performance path so we shouldn't be adding more processing here.

But if we have some mapping from well-known module names to the packages that provide them, we can recommend installing certain packages when the imports are missing. (We could probably also recommend installing Anaconda if they are known-problematic packages like sklearn/pandas.)

**Comment by huguesv** [comment]
We now check for missing packages listed in requirements.txt, and we also propose to create a conda env when none exist. The ML packs now include a environment.yml, which triggers the conda env prompt.
