### ISSUE TITLE
Formatting option for spaces after if and print

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#181]
The following code doesn't get reformatted:

```
        b = 7
        if  true:
            pass
        if    b is None:
            pass

        print(b)
        print (b)
        print  (b)
```

We should have additional option(s) for spaces after 'if' and 'print'.  This is on Python 2.7.  On Python 3.4, the spaces after print are removed.

From: https://pytools.codeplex.com/workitem/1648

**Comment by MikhailArkhipov** [comment]
In favor of https://github.com/Microsoft/PTVS/issues/4698
