### ISSUE TITLE
IronPython Exceptions not thrown visually

### ISSUE THREAD

**Issue by JaggerJo** [Microsoft/PTVS#1811]
IronPython Exceptions does'nt show in VisualStudio. (they only show in the CommandPrompt that opens and dissapear after they are thrown)

(Unreadable Exception)
![image](https://cloud.githubusercontent.com/assets/13090415/19968900/c6828fc6-a1d6-11e6-92e5-ed91d201085e.png)

(Readable Exception (visible in seperate console window, but dissapears immediatally))
![image](https://cloud.githubusercontent.com/assets/13090415/19968963/05033232-a1d7-11e6-92e0-5c122fd0fc6f.png)

(Exception Settings)
![image](https://cloud.githubusercontent.com/assets/13090415/19969074/779db38a-a1d7-11e6-967b-321833ccb2ea.png)

PTVS Version: 2.2.5
IronPython: 2.7 (64 Bit)

**Comment by zooba** [comment]
It looks like you're running under the .NET debugger (which is the default) rather than the Python debugger. See [our docs](https://github.com/Microsoft/PTVS/wiki/Debugging#launch-modes) for more info on what that means and how to change it.

**Comment by JaggerJo** [comment]
@zooba Thank you. works as expected now
