### ISSUE TITLE
Intellisense only works for Python 2.7

### ISSUE THREAD

**Issue by atsats** [Microsoft/PTVS#1812]
I'm using VS2015 Update 3 with Python Tools 2.2.40825 

For a very simple 1-file project, Intellisense doesn't work unless I activate the 2.7 environment. I have 3.5 (32-bit and 64-bit) environments installed by the Anaconda distribution. I rebuilt the Intellisense DBs multiple times and exited and restarted VS, but the problem is always there in the 3.5 environments.

**Comment by zooba** [comment]
Could you open Tools, Python Tools, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?
