### ISSUE TITLE
[Cookiecutter Explorer] Clicking "Home" button should load default view 

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1817]
If I search something, and then want to go to that default you, I have no way to do that other than hitting search on a blank search box or "esc". Clicking the home button is my foremost intuition, but it does not take me to the default view – I recommend that it does. Hitting “Esc” does feel very obvious.

**Comment by huguesv** [comment]
I had been waiting for this feedback :)  I agree.
