### ISSUE TITLE
[Cookiecutter Explorer] Banner's shade of yellow, "x", and feel does not match with other tools

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1818]
Should we match the yellow color of the cookiecutter banner with the yellow color of the team explorer banner? Same for the feel: Our banner is embossed, Team Explorer’s is flat. Also the “x” are different. Not major, but looks a bit out of place now when you can have both tools open SxS. 

![banner color](https://cloud.githubusercontent.com/assets/5177491/19991309/86a7c158-a1f1-11e6-8a7e-64789391da52.PNG)

**Comment by huguesv** [comment]
We're using the built-in info bar functionality.  We provide text and links, and VS takes care of presentation.  Team Explorer doesn't use it.  They probably should match their color with the VS built-in info bar.
