### ISSUE TITLE
cookiecutter list should display user icon

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1825]
We should display the icon of the user who created the template. This will help make it easier for users to find templates from trusted creators.

**Comment by huguesv** [comment]
This looks like a trusted creator :)
![image](https://cloud.githubusercontent.com/assets/1696845/20078564/e39bbc3c-a4f5-11e6-98dc-aa49d9df9515.png)
I made the image clickable, so it goes to the owner's GitHub url.
