### ISSUE TITLE
Environment package window oddity

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1834]
Search results all show up as `/simple/<name>/`, I don't remember seeing that before.

![image](https://cloud.githubusercontent.com/assets/1696845/20123643/6d442656-a5d5-11e6-8344-d3be575d50c7.png)

Clicking the link fails with error about not finding simple distribution.

Tested on a second machine, seeing it there too.

**Comment by zooba** [comment]
Uh, no. That must be a regression in a recent change I made to not hardcode the index URL. I'll fix it tomorrow.
