### ISSUE TITLE
Clone fails due to Unicode character?

### ISSUE THREAD

**Issue by japj** [Microsoft/PTVS#184]
I am trying to clone PTVS with the VS2015RC Github integration ("Open in Visual Studio").

However I get a failure to clone:
Error encountered while cloning the remote repository: Failed to stat file 'C:/Github/PTVS/Python/Tests/TestData/UnicodePath�.sln': No mapping for the Unicode character exists in the target multi-byte code page.

**Comment by zooba** [comment]
We may have to change our tests to generate this file while running if git doesn't know how to handle Unicode properly.

**Comment by int19h** [comment]
`git clone` in command line works fine, but the files will then show up as if they were renamed.

**Comment by ethomson** [comment]
That's not a unicode character, that's a Latin-1 character:

    git ls-files --stage | grep -i UnicodePath.*.sln
    100644 7411333d2102a578025ea00306ab543f7992eee8 0     "Python/Tests/TestData/UnicodePath\344.sln"

Octal 344 is hex `0xe4`, which is Latin-1 for `ä`.

Git repositories store filenames as UTF-8 internally.  If you want this to be `ä` (U+00e4), then this should be `0xc3 0xa4` in UTF-8.

If you know how this got into your repository, then I would recommend filing a bug against that tool vendor.  In the meantime, please rename this and commit the new name.  While you're doing that, the folder `Unicode\344` is incorrect as well.
