### ISSUE TITLE
Run as admin for venv?

### ISSUE THREAD

**Issue by LeeRuns** [Microsoft/PTVS#1842]
What does run as admin do?
![image](https://cloud.githubusercontent.com/assets/15914558/20266632/480879e2-aa34-11e6-9a5b-28f673ced2f0.png)

**Comment by zooba** [comment]
It will run pip as administrator, which may be necessary if you're installing packages somewhere that needs administrative privileges (e.g. Program Files).

This dialog has been removed from our next release and we'll automatically detect whether you need privileges and prompt.
