### ISSUE TITLE
using PTVS to organize all python environments

### ISSUE THREAD

**Issue by LeeRuns** [Microsoft/PTVS#1843]
Since PTVS has the ability to scan through my computer and find all of my python environments.  Would it be possible to make it generate an output that shows all of my environments, where they are stored.  What packages are installed and generate a report of this?  Even if it was a powershell script that would be great.  Especially, if I could specify multiple network drives to read through, the packages, and the windows environment that the python environment is identified as.

The reality is that for those of us doing python development in PTVS, we are also doing python development for windows deployment.  Being able to administrate, different programs, and evaluate the existing python libraries+Packages on a multiple computers is really valuable.

**Comment by zooba** [comment]
I would suggest looking at [PEP 514](https://www.python.org/dev/peps/pep-0514/), which defines the registration for Python interpreters. Currently the only ones we detect that are not registered like this are Canopy and IronPython - I believe Canopy has its own management tools, and IronPython is simply a different registry key right now. We don't do any disk searching or other analysis beyond looking in the registry ("In the face of ambiguity, resist the temptation to guess").

Once you've got the executable paths, the packages can be obtained using pip. All we do in Visual Studio is run `pip list` and parse the output.

I agree that it's valuable, but we haven't really looked at addressing the needs of system administrators on this level. Right now it's unlikely that we'll get to it any time soon, so if you'd benefit from it, I'd say dive in and don't wait for us :)

**Comment by zooba** [comment]
FWIW, I started work on a Python package [pep514tools](https://github.com/zooba/pep514tools) that can do this. It doesn't have all the functionality yet, but I'd much rather provide the tools as a Python library first.

**Comment by zooba** [comment]
Marking this wontfix - hopefully the external tools are sufficient (the `py.exe` launcher is also gaining a `-0` option that will do this, so there's very little motivation to add it to VS).
