### ISSUE TITLE
cookiecutter should default to current project path when entering from Add New Item

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1870]
We have multiple entry points into the cookiecutter Explorer window. If you come in from the Add New Item entry point (rather than New Project), we should default to installing the template into the current project directory. We can keep installing into that directory until another entry point is used.

We probably also need to display a little note underneath the path ("We chose your current project to add new items" or something), otherwise it may not be immediately obvious where we're going to put the files.

**Comment by huguesv** [comment]
Also, the generated files should be added to the project. I guess do it automatically when Create succeeds. Don't know how that affects Open in Solution Explorer link when we return to the home page. Doesn't make a lot of sense to have it in that scenario.

**Comment by huguesv** [comment]
Since this isn't a modal dialog, the user can leave the tool open for a long period and forget that it was opened with a "Add From".  They may have deleted the parent folder that was there when invoked, and the project may have been closed.

**Comment by zooba** [comment]
We can detect that the directory is gone and reset. We can probably also handle the case where the project is closed or the workspace is changed too. But I think having an info notice next to the path is the best way to deal with this.
