### ISSUE TITLE
Diff does not detect indentation change

### ISSUE THREAD

**Issue by HHest** [Microsoft/PTVS#1875]
Hi again,

Today I noticed that PTVS/VS diff is not sensitive to a change in indentation. I made a modification such that some lines were moved under the if statement above it. For example:

```
[old.py]
if isNeeded:
    print 'I am needed.'
print 'I should also be needed.'
print 'I am not needed.'
```

```
[new.py]
if isNeeded:
    print 'I am needed.'
    print 'I should also be needed.'
print 'I am not needed.'
```

These two files will show "no difference". The problem is most likely related to [the merge problem](https://github.com/Microsoft/PTVS/issues/1528) I reported earlier. Thanks for keeping an eye on this issue.

Regards,

Thao

p.s. I have updated my setup to
**Visual Studio pro 2015, v 14.0.25420.01 Update 3
PTVS 2.2.40825.00**

**Comment by zooba** [comment]
There's definitely a toolbar button to toggle whitespace:
![image](https://cloud.githubusercontent.com/assets/1693688/20397712/9ac3c46c-ac9f-11e6-9635-8c0c9aca33d9.png)

(Obviously this doesn't help with #1528, unless the change to make it a conflict is sufficient, but given the majority of languages used in VS are not whitespace sensitive I think it's reasonable that the default diff view does not show whitespace-only changes.)

**Comment by HHest** [comment]
Ah! Thank you for that, zooba. I assume it is not possible for PTVS to change this default for .py files?

I guess the real issue still is for VS to recognize that the beginning whitespaces are relevant for python files. It would be great if vsdiffmerge has a flag for this. VS itself already provides a way to set this proposed flag when merging/diff'ing .py files (cf. Options, Source Control, VS TFS, Config User Tools...)
