### ISSUE TITLE
Python Environments window does show full functionality when DS settings selected

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1882]
When I start VS and choose the Data Science Settings (R) in the customization dialog, the IDE presents with the variable explorer and solution explorer stacked on top of each other. However, if I open the Python Environments window (from Python Tools window), I get . Clicking on Overview, Packages, Intellisense does not do anything.

![dssettings_pythonenv](https://cloud.githubusercontent.com/assets/5177491/20575574/b81ded0c-b16e-11e6-935e-736cf4218a72.png)

For reference, here's what the window looks like when I restore general profile settings

![general_pythonenv_packages](https://cloud.githubusercontent.com/assets/5177491/20575588/cceb24f2-b16e-11e6-8f56-643f59fdb44c.png)

**Comment by zooba** [comment]
Looks like when the window opens to the horizontal layout the content control is not shown. Once you resize the window then it appears.

**Comment by zooba** [comment]
This should have been fixed at the same time as #1906, but I forgot to tag the issue in the commit.
