### ISSUE TITLE
ptvs windows not responding in vs2015 when click "pip" item 

### ISSUE THREAD

**Issue by ppLorins** [Microsoft/PTVS#1893]
os: win7 sp1
vs: Microsoft Visual Studio Community 2015 Version 14.0.25425.01 Update 3
Microsoft .NET Framework Version 4.6.01055

the windows  is stuck every time I click "pip" item , every time , I don't know how to upload a picture,
but you may know what I mean 'stuck',  it is no responding , and windows turn gray.
I'm going to be crazy since I can't install any packages now !

**Comment by zooba** [comment]
I haven't ever seen this occur, and most of the code in question has been dramatically changed for VS 2017, so there's a good chance it's been inadvertently fixed.

Leaving this open for now, but unless we see it happening with the latest release, it's hard to do anything about it.
