### ISSUE TITLE
Completion DB stuck at about 25%, never updates

### ISSUE THREAD

**Issue by Jesuszilla** [Microsoft/PTVS#1896]
Whenever I click to refresh the Completion DB, it gets stuck at 25% and just gives up.

Happens no matter what my environment is for my requirements.txt, though I use Python 2.7 32-bit as the base.

[requirements.txt](https://github.com/Microsoft/PTVS/files/623700/requirements.txt)

**Comment by zooba** [comment]
Have a look at #1883 and see if that's the same problem. If so, we're aware of it and there's a fix in our next update.

**Comment by Jesuszilla** [comment]
Yep, appears to be the same issue! Thanks, looking forward to the next update!
