### ISSUE TITLE
Deadlock(?)  loading IronPython project in VS DesktopExpress 2013

### ISSUE THREAD

**Issue by andygraham** [Microsoft/PTVS#19]
I have a mixed VS solution with three C# projects and one IronPython project in it. When I try to open this solution with the 13th April build of PTVS installed VS 2013 Desktop Express freezes with the notification "VS Express 2013 Desktop Express is busy ... waiting for an internal operation to complete ...". Solution Explorer shows that the Solution is "(loading...)" but there is little to no CPU activity. It looks like something is deadlocked. 

I originally thought that this was due to some combination of editor windows being open but this seems to be not so. If I rename the solution folder then the project opens fine. Doing nothing further if I then immediately close it and reopen it then the hang occurs. Renaming the solution folder again repeats this behaviour, it opens once the first time and not thereafter.

The behaviour first occurred in the 6th April Dev Build, before then Dev Build 2015-03-26 seemed to work fine except for the occasional freeze that required a restart which all previous builds of PTVS seem to have suffered from when an IronPython project is loaded in VS but with the IronPython source not necessarily being loaded in the editor.

**Comment by int19h** [comment]
I believe this is the same problem that I've seen with freezes on project open due to deadlocks in async analysis code - it's not  specific to IronPython.

**Comment by int19h** [comment]
Fixed in RC.
