### ISSUE TITLE
Install from/Generate Requirements.txt commands should be disabled on no interpreters

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#190]
On a machine with no Python interpreters installed:

Create new console app 
In solution explorer, you'll have "No Interpreters (global default)", select it 
Right-click, Generate Requirements.txt 
You'll get an error

Both Generate and Install commands should be disabled in this case.

From: https://pytools.codeplex.com/workitem/2971
Verified on PTVS 2.2 30515

**Comment by zooba** [comment]
Real bug is that we shouldn't show "No Interpreters" here.

**Comment by huguesv** [comment]
Sorry, I'll add that to the original post.  The machine doesn't have any interpreters installed.
