### ISSUE TITLE
code snippet 'main' not working via shortcut

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1903]
I used to be able to type `main` and hit TAB, and it would trigger the code snippet.

That still works for some other snippets, such as `while`, `except`, but for some reason it no longer works for `main`.  It doesn't show up in the completion list either like the other snippets.

Note that I can still add it via the Insert Snippet command.

**Comment by zooba** [comment]
It's because "main" doesn't appeal in the completion list. We should include code snippet shortcuts in normal completions.
