### ISSUE TITLE
Two versions of Anaconda installed, but only one is visible

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#1907]
During VS installation, I checked two boxes - one for Anaconda 2.7 64-bit, and one for Anaconda 3.5 32-bit.

For one thing, I've got Anaconda 3.5 *64-bit* instead, so it looks like the label in the installer is incorrect. I also got 2.7 64-bit installed as expected.

However, after launching VS, in the Python Environments window, only Anaconda 3.5 is present.

**Comment by int19h** [comment]
Screenshot of installer checkbox that says "Anaconda3 32-bit":

![image](https://cloud.githubusercontent.com/assets/1175142/20849419/72756fc2-b88b-11e6-9ed0-2b6afe656d43.png)

What actually got installed:

![image](https://cloud.githubusercontent.com/assets/1175142/20849453/a073407a-b88b-11e6-8c7c-405ee8c88afd.png)

**Comment by int19h** [comment]
Never mind that part - Anaconda3 64-bit was also checked (by default), and so both 32-bit and 64-bit Anaconda3 got installed. The bug is still the same - only one Anaconda (out of three installed) is in the Environments window.

**Comment by zooba** [comment]
And that's a dup of #1897 which was fixed in #1902
