### ISSUE TITLE
Anaconda 32-bit not checked by default when installing on 32-bit machine

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1908]
Empty python environments windows shows up, with no clear instruction what's missing. The UI appears broken. Maybe we can make the UI more graceful.

**Comment by zooba** [comment]
Open to suggestions that improve upon the UI only displaying a "help me install an environment" link.

**Comment by huguesv** [comment]
Since VS installer has CPython and Anaconda, should we add links to open the VS installer?  Maybe since the feed can change more often than the tool window itself, that may be a reason not to?

**Comment by huguesv** [comment]
We've added links to open the VS installer from within VS. We've also removed Anaconda from the VS installer.
