### ISSUE TITLE
Instructions to get interpreters are out of date

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1910]
Click "Click here to learn how to get my environments" link in the empty environments window. This should show instructions to modify the installation via willow.

**Comment by zooba** [comment]
At that point I'd rather make that not the default option, since you're almost certainly going to have a better experience in the long run by installing it just for the current user. But the page probably needs updating (it's just on the wiki, so feel free to jump in and fix it)

**Comment by huguesv** [comment]
The page at the new location briefly mentions that VS 2017 comes with a Python interpreter.
https://docs.microsoft.com/en-us/visualstudio/python/python-environments#selecting-and-installing-python-interpreters

I don't know that it's worth keeping this bug around.

**Comment by zooba** [comment]
I consider this has been fixed.
