### ISSUE TITLE
Default environment does not stick. 

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#1911]
![image](https://cloud.githubusercontent.com/assets/3840081/20849405/629082ea-b88b-11e6-837b-285d22330bdc.png)

**Comment by zooba** [comment]
Seems to be 32-bit only, so it may be related to the registry detouring.

**Comment by zooba** [comment]
Doesn't trivially reproduce, at least on Win7 32-bit, though we do seem to lose it when new environments are being installed. Possibly we're failing an object identity test somewhere.

**Comment by zooba** [comment]
I think that PR will fix the issue, but it's difficult to validate on 32-bit OS without a proper build.
