### ISSUE TITLE
No sig help for "requests.ConnectionError()" but "requests.RequestException()" does get them

### ISSUE THREAD

**Issue by DinoV** [Microsoft/PTVS#1912]
VS 2017, create virtual env, install requests
import requests
requests.ConnectionError()

No signature help.  requests.RequestException() does get it though

**Comment by zooba** [comment]
I can't see any immediate reason for this, except that `ConnectionError` is a subclass of `RequestException` with no body (other than a docstring), so perhaps we aren't correctly inheriting initializers for signature help?

**Comment by huguesv** [comment]
See #3046
