### ISSUE TITLE
Can't debug anything when mixed mode is enabled

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#192]
I built my own custom python 2.7 interpreter using MSVC 2013 using the sln that ships with the python source distribution.  When I make a Python Environment which points to python_d.exe, pythonw_d.exe, etc from this distribution, and enable mixed mode debugging and press F5, nothing happens.  It does not even launch the interpreter.  This used to work prior to 2.2, and in fact I think I believe it even used to work in earlier versions of the 2.2 RC / beta.  So this appears to be a fairly serious regression.

**Comment by zjturner** [comment]
I can confirm that this has regressed sometime between [2.2 beta (good)](https://pytools.codeplex.com/releases/view/612409) and [2.2 RC (bad)](https://pytools.codeplex.com/releases/view/614624)

**Comment by int19h** [comment]
Does this only happen when you enable mixed mode, or it refuses to launch without it, as well?

**Comment by zjturner** [comment]
Only with mixed mode.  I just cloned the repo, was going to try to bisect.

**Comment by zjturner** [comment]
Made some progress.  It was introduced by a combination of edf03f8a114fddfd693122c5a9a79d580311eb48 and dfbe5e55559a4e1c620946eccaef0f33938e91a1  (the latter adds some missing files, so it won't compile at edf03f8a114fddfd693122c5a9a79d580311eb48.  Specifically, it seems to be related to the creation of the bstrEnv parameter that you're passing to VsDebugTargetDebugInfo.  In the code that works, bstrEnv is set to null.  In the code that doesn't work, it's set to an actual value.  I confirmed by modifying the value of the field under the debugger and setting it to null, that it fixes the broken code.

**Comment by zjturner** [comment]
Actually I think I just fixed it.  Shall I make a pull request?

**Comment by int19h** [comment]
We do want to set `bstrEnv` to correspond to the environment variables, if any are set. If the launch fails when it happens, I expect this has more to do with the proper format of the string?

But yes, you're welcome to make the pull request, and we can talk it over there (if the diff in the PR doesn't answer my question right away, that is :) ).

**Comment by zjturner** [comment]
Yea, I think my patch respects the environment and still fixes the issue, so it shouldn't be a problem.  Let me try to figure out this pull request thingy. :)

**Comment by int19h** [comment]
Was this fixed by https://github.com/Microsoft/PTVS/pull/197/ ?

**Comment by zooba** [comment]
We believe this is fixed, since we have rewritten the code around this area completely since this bug. If it still occurs on the latest releases, feel free to let us know and we'll reopen it.
