### ISSUE TITLE
IoT project requires additional installation

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#1922]
![image](https://cloud.githubusercontent.com/assets/3840081/20850648/1477b302-b891-11e6-8b1d-b119d2911571.png)

IoT project requires http://go.microsoft.com/fwlink/?LinkID=613495&amp;clcid=0x409 but the link is not clickable.

**Comment by zooba** [comment]
@alanch-ms This came up in our bug bash today, FYI.
