### ISSUE TITLE
IoT CPython UWP link points to PTVS 2.2.3

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#1923]
Also the IoT python VSIX in the link has to be updated to support VS2017
https://github.com/ms-iot/python/releases?amp;clcid=0x409

**Comment by zooba** [comment]
@alanch-ms This came up in our bug bash today, FYI.

**Comment by alanch-ms** [comment]
@zooba Yes, I just send out a PR which updates PythonIoT to VS2017RC. 
https://github.com/ms-iot/python/pull/29
