### ISSUE TITLE
installing pkgs should direct attention to Output Window

### ISSUE THREAD

**Issue by smortaz** [Microsoft/PTVS#1928]
clicking on a pkg to be installed, just gives a green progress bar.

that implies things went well, while in reality, there could be an error.

at least the install dialog should say "See REPL for installation status".

**Comment by zooba** [comment]
We already direct attention via the status bar, which is the correct place to do this. I'm hesitant to add more noise to the UI, but having better feedback when the install fails wouldn't be a bad thing (other than the package simply not appearing in the list of installed packages, which is probably already filtered to the package that was just installed).

**Comment by zooba** [comment]
Accessibility reviewers have okayed the current design.
