### ISSUE TITLE
Flask web role 500 error

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1930]
New Azure Cloud Service, include Flask Web Role
Publish
Error when trying to open web site

I think it's because the web.config that's included refers to `app.wsgi_app()` and it should be `app.wsgi_app` instead.

**Comment by huguesv** [comment]
I made that change and it didn't help.

**Comment by huguesv** [comment]
Bottle Web Role worked.  Will have to try Flask Web Role again.

**Comment by zooba** [comment]
You also need to enable the site extension - https://aka.ms/PythonOnAppService

**Comment by huguesv** [comment]
But I'm using web role (cloud service).

**Comment by zooba** [comment]
Ah, you're right. You should be able to get detailed logs then - https://github.com/Microsoft/PTVS/wiki/Cloud-Project#troubleshooting

**Comment by huguesv** [comment]
[ConfigureCloudService.txt](https://github.com/Microsoft/PTVS/files/632037/ConfigureCloudService.txt)

Python install is there, but flask wasn't installed.

**Comment by zooba** [comment]
Ah, setuptools issue with the nuget packages - https://github.com/pypa/setuptools/issues/857

**Comment by zooba** [comment]
This has been fixed in the CPython nuget packages.
