### ISSUE TITLE
Packages list not synced after prompt pip install

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1931]
I installed my packages from a prompt cmd hsell, because I have to write "-r dev_requirements.txt" and I don't think we can do it from PTVS.

After that, my venv got updated:
![image](https://cloud.githubusercontent.com/assets/1050156/20851877/cab56c58-b897-11e6-9eab-5bc259f027ed.png)

But not the Python Environment view:
![image](https://cloud.githubusercontent.com/assets/1050156/20851900/e197eedc-b897-11e6-9895-5393b7013773.png)

Even after end of analysis:
![image](https://cloud.githubusercontent.com/assets/1050156/20851941/1283db8c-b898-11e6-81ad-e4c55b282e15.png)

I tried to click to every menus, combobox, to try to trigger a refresh, but was not able to find something to make it work

Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26001.1 D15REL
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

Visual Basic 2017 RC   00369-50000-00000-AA049
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA049
Microsoft Visual C# 2017 RC

Visual F# 4.1   00369-50000-00000-AA049
Microsoft Visual F# 4.1

ASP.NET and Web Tools 2016   15.0.21128.0
ASP.NET and Web Tools 2016

Azure App Service Tools v2.9.6   15.0.21130.0
Azure App Service Tools v2.9.6

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python Tools for Visual Studio   3.0.16334.1
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Cookiecutter Integration   3.0.16334.1
Provides cookiecutter integration.

Python Tools for Visual Studio - Django Integration   3.0.16334.1
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   3.0.16334.1
Profiling support for Python projects.

R Tools for Visual Studio   0.5.21104.1600
Provides project system, R Interactive window, plotting, and more for the R programming language.

TypeScript   2.1.3.0
TypeScript tools for Visual Studio

**Comment by lmazuel** [comment]
Restart PTVS solves the issue

**Comment by zooba** [comment]
Guessing we didn't set up the file watcher properly, so we weren't getting any notifications that packages had changed.
