### ISSUE TITLE
Install packages into venv: current dir should be project dir

### ISSUE THREAD

**Issue by lmazuel** [microsoft/PTVS#1933]
In case my requirements.txt is named like "dev_requirements.txt", I should be able to click on "Install packages" and write "-r dev_requirements.txt" to install my requirements.txt. Currently, file is not found, whatever I try.

Currently, the only way I found to install this file is to open a Command Prompt and type it myself.

**Comment by zooba** [comment]
There are arguments for and against this - currently the working directory is the Python directory - but maybe it's worth switching over for this case.
