### ISSUE TITLE
No completions for Django variables

### ISSUE THREAD

**Issue by DinoV** [Microsoft/PTVS#1938]
File->New project for Django project

Template for about.html includes:
<h2>{{ title }}.</h2>

Typing "{{ " gives no completions

**Comment by zooba** [comment]
Did you have any completions for Django at all? Because of the other analysis bugs?

I can't repro this when Django completions are working, but if we can't resolve anything (specifically, `render`) then this doesn't work.

**Comment by David-Wobrock** [comment]
Hi @DinoV 

After coming back to PTVS after a long time, all Django completions also broke for me.
I thought something very bad happened, until I realised I forgot to let PTVS analyse the selected python interpreter.
It is required that the python environment is analysed to be able to analyse and have IntelliSense on the django project.
Once it finished, completion worked fine again.

I hope it's just this and it will help.

**Comment by zooba** [comment]
I think we broke virtual environments at some point and they stopped creating a file-system watcher. As a result, they did not notice when the DB had been refreshed, which would then lead to this. Reopening the solution is a workaround, but we really want to detect the actual update so we don't look so broken.
