### ISSUE TITLE
MMD: breakpoint in Python file gives weird call stack

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#1939]
Python 3.5.2 32-bit.
```py
import sys
import module1

print('before')
module1.example(module1, 123)
print('after')
```
Tried this with breakpoint on either the first print, or on the function call after. Either way, when the breakpoint is hit, the stack looks like this:
![image](https://cloud.githubusercontent.com/assets/1175142/20852549/319dc872-b89b-11e6-8f8d-95baa19caf57.png)
and in the editor, you get:
![image](https://cloud.githubusercontent.com/assets/1175142/20852602/68ce3214-b89b-11e6-905b-cdfcbdd67dd4.png)

However, Python debugger is actually active, and in particular, you may Step In (F11). If you do, everything is suddenly back to normal - the stack now looks like this:
![image](https://cloud.githubusercontent.com/assets/1175142/20852613/842e2172-b89b-11e6-80da-a6eae694aca5.png)

and the editor shows the correct line:
![image](https://cloud.githubusercontent.com/assets/1175142/20852626/9c9b8f9c-b89b-11e6-8a08-a789c333b644.png)

The Python frame on the stack is also correct, and double-clicking it shows the appropriate line in .py file.

Furthermore, if you now Step Out of native code, you get the expected behavior also:
![image](https://cloud.githubusercontent.com/assets/1175142/20852651/c20b952e-b89b-11e6-8e34-c4e7df778fd4.png)

![image](https://cloud.githubusercontent.com/assets/1175142/20852666/d273673e-b89b-11e6-81d6-bfbc379e2f3c.png)

**Comment by zooba** [comment]
Good news! This is just because we aren't including the PDB files for the DebuggerHelper DLLs.
