### ISSUE TITLE
Potentially confusing cloning status message: "installing cookiecutter..."

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1941]
When the cookiecutter template is installing, the message under the green progress bar is: "installing cookiecutter..." at default window size. This is a bit confusing since all templates have "cookiecutter-.." in them. It would be better to show the latter part of the string e.g. "installing cutter-djano template"

So the message is: Installing < name after "cookiecuter-"> template"

**Comment by huguesv** [comment]
That's not what it's doing.  The "Installing cookiecutter" message is the ONE TIME SETUP that creates a private virtual environment, pip install cookiecutter package into that environment.  It's triggered the first time that you try to load or clone a template.

That takes a bit of time, maybe up to 1 min.  Then you'll see the Cloning message for whatever template you've selected (this is relatively fast).

**Comment by huguesv** [comment]
We could change it to something like "Preparing cookiecutter for the first time" or something similar (ideally not that long)

**Comment by zooba** [comment]
I like that, and I don't actually mind if it's that long (and wrapped around).
