### ISSUE TITLE
Creating Python environment forcibly prepends it with "VisualStudio".  Editing re-prepends.

### ISSUE THREAD

**Issue by ChronosWS** [Microsoft/PTVS#1943]
Repro steps:
1. Create a new Python environment
2. Rename it to something "Foo"
3. Configure it properly, click 'Apply'

Note the environment is called 'VisualStudio Foo'
4. Edit the environment, Click Apply
5. Note a new environment called 'VisualStudio VisualStudio Foo', along with the old one.

Expected:
Environment should be called 'Foo'.  Editing it should not create a new one with a new name.

**Comment by zooba** [comment]
We're writing out the wrong registry value and so the display name does not get overridden.
