### ISSUE TITLE
Changing environment library path does not toggle Apply button/link state

### ISSUE THREAD

**Issue by ChronosWS** [Microsoft/PTVS#1944]
Repro steps:
1. Create a new environment
2. Configure it, including with a library path.
3. Click 'Apply'
4. Re-configure the environment editing the library path to a different directory.
5. Note 'Apply' is disabled.
6. Change the Python version
7. Note 'Apply' is now enabled.

Expected:
Changing the library path should allow the configuration change to be saved.

**Comment by zooba** [comment]
The actual bug here is that we still have the textbox for Library Path, but it is totally ignored :)
