### ISSUE TITLE
C/C++ extension module for Python

### ISSUE THREAD

**Issue by gravivector** [Microsoft/PTVS#1945]
Any working project for download ? Getting tired with LINK : fatal error LNK1104: cannot open file 'python27_d.lib'

**Comment by zooba** [comment]
The easy fix for that is to change your solution configuration from "Debug" to "Release".

Currently we only have a project for Python 3.5 and later, which is included in VS 2017 when you select the native development option in the Python workload (it's in the C++ templates section).
