### ISSUE TITLE
Crash on Go To Definition (F12)

### ISSUE THREAD

**Issue by caligula1989** [Microsoft/PTVS#1948]
Using PTVS 3 preview, on VS2017 RC, clicking F12 or Right-click + Go To Definition, results in a crash of visual studio whenever the definition is not in the same file.

**Comment by zooba** [comment]
Could you open Tools, Python Tools, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

**Comment by caligula1989** [comment]
Sure: https://gist.github.com/caligula1989/a286f27d07ad9aa2d59d417ca5828be1

**Comment by zooba** [comment]
Thanks. Looks like `Microsoft.PythonTools.Language.EditFilter.GetDefsRefsAndValues` needs better protection against incoming null values (and we need to figure out why we're passing in null values).
