### ISSUE TITLE
Tests are not shown on VS 2017

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#1953]
Opening the Azure SDK for Python project, after migration, analysis, several open/close of VS, still does not see my tests.

Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26006.2 D15REL
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual Basic 2017 RC   00369-50000-00000-AA399
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA399
Microsoft Visual C# 2017 RC

Application Insights Tools for Visual Studio Package   8.4.01118.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2016   15.0.21206.0
ASP.NET and Web Tools 2016

ASP.NET Web Frameworks and Tools 2013   5.2.41123.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v2.9.6   15.0.21130.0
Azure App Service Tools v2.9.6

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio vNext - v2.9.41121.2

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python Tools for Visual Studio   3.0.16334.1
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Cookiecutter Integration   3.0.16334.1
Provides cookiecutter integration.

Python Tools for Visual Studio - Django Integration   3.0.16334.1
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   3.0.16334.1
Profiling support for Python projects.

SQL Server Data Tools   15.1.61124.0
Microsoft SQL Server Data Tools

TypeScript   2.1.3.0
TypeScript tools for Visual Studio

**Comment by huguesv** [comment]
I'm on the same build.  I had the project opened with the tests not discovered, I left it for about 5 mins and when I came back they were there and I was able to run one.  That was with a Python 3.5 64-bit venv, with requirements.txt installed into it.

![image](https://cloud.githubusercontent.com/assets/1696845/21058748/4ace2568-bdf4-11e6-82b7-04ddf15792a4.png)

I need to try again some more.

**Comment by zooba** [comment]
Test discovery is tied to code analysis now, so while analysis is still running for the project you won't see any tests.

Perhaps we should look at an AST-based discovery mechanism that can return faster than overall analysis.

**Comment by zooba** [comment]
Fixed in #1981

**Comment by zooba** [comment]
Reopening this - there appears to be some sort of race condition when opening a project where the test analysis extension does not get correctly hooked up. As a result, you can easily get into a state where you will never see tests.

I believe that closing/opening the project may eventually hit a point where you see tests again, but I've only been able to "fix" it by attaching a debugger and letting it slow everything down.
