### ISSUE TITLE
IntelliSense Existing problems

### ISSUE THREAD

**Issue by xiongshi08** [Microsoft/PTVS#1957]
![1](https://cloud.githubusercontent.com/assets/3833674/21003716/ddc35916-bd67-11e6-977f-058ee15f0de8.png)
![2](https://cloud.githubusercontent.com/assets/3833674/21003738/f4172be8-bd67-11e6-94d2-7b721d13c51b.png)
![4](https://cloud.githubusercontent.com/assets/3833674/21003741/f8b4b59e-bd67-11e6-8d7e-141504616b9c.png)
![3](https://cloud.githubusercontent.com/assets/3833674/21003798/31b900ac-bd68-11e6-9c97-aba07ffde8aa.png)

**Comment by xiongshi08** [comment]
IntelliSense has a problem with reference to the.Net object support.

**Comment by zooba** [comment]
The last image is what is expected though, correct? I don't consider it a bug that we do not scrape .NET assemblies while the completion DB is invalid, as that's going to create conflicting state when the DB refresh completes.
