### ISSUE TITLE
Tools/options for limit on the number of modules for cross-module analysis

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#196]
We have a limit on the number of modules we’ll allow before we stop doing cross-module analysis. By default, that limit is 1300. Django has >1800 modules, and so cross-module analysis is severely limited as a result. 

 Setting HKCU\Software\Microsoft\VisualStudio\1x.0[Exp]\PythonTools\Options\Advanced:CrossModuleAnalysisLimit=”2000” (REG_SZ) makes it so that you get full and correct completions for Django. However, it now takes noticeably longer to analyze. 

 That registry key is undocumented. We should have a way for users of large projects to increase the limit. This could be a tools/options. They would have to know that they are hitting the limit so they go increase it. So it would be good if we could detect that we have hit the limit and tell them, in the status bar, interpreters window, or in the intellisense dropdown.

From: https://pytools.codeplex.com/workitem/1777

**Comment by sonictk** [comment]
It would be great if this was exposed as a global UI option at the very least instead of hiding it in the registry. It makes working with Maya unusable without setting this value a lot higher than the default (Mine is set to 3000)

**Comment by zooba** [comment]
Not enough demand.
