### ISSUE TITLE
"Microsoft.PythonTools.Uwp.targets" not found when creating IoT project due to custom VS install location

### ISSUE THREAD

**Issue by WasabiFan** [Microsoft/PTVS#1970]
I am currently trying to follow the guide [here](https://developer.microsoft.com/en-us/windows/iot/samples/helloworldpython) to create a new Windows IoT Core / UWP project for Python. After installing PTVS and the IoT-specific components, I am unable to create the project due to the following error (displayed in a message box):

> The imported project "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio - UWP\2.2\Microsoft.PythonTools.Uwp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> 
> `C:\Users\<username>\AppData\Local\Temp\<string of letters>\Temp\TestBackgroundIoTApp.pyproj`

After a bit of investigation, it seems that this is caused by the fact that Visual Studio is installed on my secondary drive (`D:`) instead of `C:`. The directory mentioned in the error message does not exist, however the equivalent path _does_ exist on my `D:` drive. What do I need to change in my set-up to make this work as a temporary measure, and what must be changed to get a permanent fix?

_I am not completely sure that this is an error produced by PTVS; it may actually be the IoT extension that is to blame. However, from reading through the related bits in this repo it seems like this is more likely to be the cause (or at least in a position to fix it)._

**Comment by huguesv** [comment]
@alanch-ms can you look at this IoT issue?

**Comment by alanch-ms** [comment]
@WasabiFan 

Yes, there's a bug in Python IoT project templates.  It's not looking at the correct place.  This bug was fixed in 3.0 but not in 2.2.X.  

As a workaround, you can modify the project template with the following diffs.


\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplatesCache\Python\Windows IoT Core\BackgroundService.zip\PythonBackgroundService.pyproj:

```
   <PropertyGroup>
     <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
     <PtvsVersion Condition="'$(PtvsVersion)' == ''">2.2</PtvsVersion>
-    <PtvsTargetsFile>$(LocalAppData)\Microsoft\VisualStudio\$(VisualStudioVersion)Exp\Extensions\Microsoft Corporation\Python Tools for Visual Studio - UWP\$(PtvsVersion)\Microsoft.PythonTools.Uwp.targets</PtvsTargetsFile>
-    <PtvsTargetsFile Condition="'$(PtvsTargetsFile)' == '' or !Exists('$(PtvsTargetsFile)')">$(MSBuildProgramFiles32)\Microsoft Visual Studio $(VisualStudioVersion)\Common7\IDE\Extensions\Microsoft Corporation\Python Tools for Visual Studio - UWP\$(PtvsVersion)\Microsoft.PythonTools.Uwp.targets</PtvsTargetsFile>
+    <_PythonToolsPath Condition="!Exists($(_PythonToolsPath))">$([MSBuild]::GetRegistryValueFromView('HKEY_LOCAL_MACHINE\Software\Microsoft\PythonTools\$(VisualStudioVersion)', 'InstallDir', null, RegistryView.Registry32))</_PythonToolsPath>
+    <_PythonToolsPath Condition="!Exists($(_PythonToolsPath))">$(LocalAppData)\Microsoft\VisualStudio\$(VisualStudioVersion)\Extensions\Microsoft\Python Tools for Visual Studio\$(PtvsVersion)</_PythonToolsPath>
+    <PtvsTargetsFile>$(_PythonToolsPath)\..\..\Python Tools for Visual Studio - UWP\$(PtvsVersion)\Microsoft.PythonTools.Uwp.targets</PtvsTargetsFile>
   </PropertyGroup>
```

**Comment by WasabiFan** [comment]
🎉 It works! Given that the last release of the IoT Python tools was over six months ago, it would be great if you got it ready for a release so that people can actually use these fixes -- them just sitting in the git history without being released doesn't help users. and you'll probably just keep getting bug reports like this.

**Comment by cirokenzie1** [comment]
If this helps anyone.

I had the same problem even tho my VS was installed in the proper directory, VS was not able to load the solution. It kept on saying Microsoft.PythonTools.Uwp.targets". After lot of headbanging I noticed that while installation of PTVS for visual studio 2017, checkbox for python IoT support was unchecked. Checking that solved my problem of loading it onto VS.

**Comment by Saibamen** [comment]
`MSBuildExtensionsPath32` system variable need to be set to `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild`.
Bug: https://developercommunity.visualstudio.com/content/problem/465815/msbuildextensionspath32-is-not-added-to-system-var.html
