### ISSUE TITLE
Find All References Not Working After VS Update 3

### ISSUE THREAD

**Issue by claytoncarney** [Microsoft/PTVS#1971]
In VS Community 2015, the 'Find All References' function always returns 'Search found no results' after installing VS Update 3 (KB3022398). Prior to that, it had been working properly. Seems to be a PTVS issue, since it still works properly in a C# project.

**Comment by claytoncarney** [comment]
UPDATE:
I uninstalled Update 3. HUGE MISTAKE! VS was left completely FUBAR; would not even start. Ran Repair three times: no change. So I manually uninstalled VS and its associated components. After reinstalling VS, Find All References appears to be working properly again.

Simply amazing how often IME VS updates break the app...

**Comment by claytoncarney** [comment]
This is still happening, albeit intermittently. I will try to find a repeatable pattern of occurence.

**Comment by claytoncarney** [comment]
OK, here's one repeatable occurrence: dynamic classes.

    test1 = type('test1', (), {})()
    test1.ref = []
    test1.ref.append([])

    test2 = type('test2', (), {ref: []})
    test2.ref.append[1]

    test3 = type('test3', (object,), {ref: []})
    test3.ref.append[1]

Any attempt to Find All References for the ref property (test1.ref, test2.ref, test3.ref) yields 'Search found no results'. When I hover over a ref property, VS does recognize it (e.g. `test2.ref: <unknown type>`). It just doesn't find the references.

**Comment by zooba** [comment]
Are you specifying `{ref: []}` or `{'ref': []}`? The former is only valid if you've defined `ref = 'ref'` somewhere else in your code.

And it wouldn't surprise me if we simply don't handle this case well on its own. Static analysis of Python code is incredibly difficult, and it's simply infeasible to be able to handle both the cases where the key _values_ matter rather than the key types or the fact that it's a dictionary.

If Find All References is working on a regular class definition, then I'm not sure there's a problem here anymore. And I'm sorry you had to go through the messy reinstall process - VS 2017 has significantly cleaned this up, so it should be (a) less likely to be needed in the future, and (b) easier and faster to do if it is necessary.

**Comment by claytoncarney** [comment]
Don't really understand your question. I'm working with dynamically created objects, not dictionaries. The snippet provided is a simplified, but representative, example of the code I'm using. AFAIK, basic dynamic classes and properties in Python.

I may be mistaken, but I thought this was working before Update 3. That's why I raised it as a potential issue. If this is beyond the scope of reasonable static analysis, so be it.

**Comment by claytoncarney** [comment]
Appears the static analysis is simply not addressing the type() statement. The following works fine:

    class Test(object):
        pass

    test = Test()
    test.ref = []
    test.ref.append(1)

AFAIK, these two methods produce equivalent objects.

**Comment by zooba** [comment]
> Appears the static analysis is simply not addressing the type() statement

That sounds very likely. I don't recall exactly how deep we go there, but we generally discard the actual values in dictionaries and only retain the types, which means passed in members are not going to flow through, and it's entirely possible that we don't specialize the type() function at all, which would basically just result in poor results.

There's probably a few improvements we can make here, but ultimately highly dynamic code is never going to play well with any form of static analysis, so there are very diminishing returns and we realistically have to prioritise other work above trying to cover every little edge case.

**Comment by claytoncarney** [comment]
No complaints. PTVS is an excellent tool. My recollection must have been faulty. Probably just the complete breakdown after Update 3 made me think it had previously covered all bases.
