### ISSUE TITLE
Uses much memory when large .py file is in project folder

### ISSUE THREAD

**Issue by mrolle45** [Microsoft/PTVS#1972]
I have a project which dynamically imports another module by name (using importlib.import_module).  There are three such .py files totaling a few hundred thousand lines.  These files are not included in the project.
When I open the project in VS, the VS process starts consuming memory and when it reaches about 3 GB, it runs out of memory and VS crashes.
I am guessing that PTVS is performing code analysis on these modules, even though they aren't part of the project, nor are they imported in the project (other than import_module () calls).  So PTVS seems to be looking for all .py files in the project folder and analyzing them.
If I delete these three files, VS memory tops out at 375 MB, so I know for sure that these files are to blame.

**My questions:**
1. Is there possibly a memory leak in the code analysis, and is 3 GB of memory reasonable to accumulate to analyze 300,000 lines of Python code?
2. How can I tell PTVS not to analyze these extra files in the background, and only analyze them if they are opened in a window, or perhaps when debugging if one of the files shows up on the stack?
3. What if I only keep the compiled .pyc files around?  Is it possible to import them, or run their code in some other way?

By the way, what I am trying to do is recreate a data structure with something like 100,000 objects without using pickle.  It takes pickle.load several seconds to load this structure.  The equivalent Python code actually creates elements of this data structure only on demand, and so each has a corresponding lambda expression, which is called the first time the element is referenced.  This way, a typical use of this data structure will create only a much smaller subset of the elements and take much less time and memory than would pickle.load.

However, if PTVS croaks on a large Python file, then this approach is impractical.

Any advice will be much appreciated.  Thank you.
Michael Rolle

**Comment by mrolle45** [comment]
Forgot to mention, using VS 2013 and PTVS 2.2.2.

**Comment by mrolle45** [comment]
I only use one of these three Python files in current practice, so I deleted the other two.  Now VS runs up to about 1.3 GB.  Still a lot, but not enough to crash.
I also deleted the remaining Python file and left the .pyc file.  I see that import works fine, and VS doesn't consume the extra memory.  I guess I can't debug any of that code, and if I want to debug it, I'll just have to regenerate the .py file.

**Comment by zooba** [comment]
Ooh, yeah, that's basically our worst case :) Functions (including lambdas) are our unit of analysis, so each one takes up a decent chunk of memory (mock stack frames, and multiplied by potential call sites).

You _should_ be able to add the file and change it's type from Compile to Content (in the Properties window when you've selected it in Solution Explorer). I don't think we'll try and analyse it then, but there is still the implicit analysis that may pull it in (depending on PTVS version - it's changed quite a bit).

Given you have a lot of lambda functions, there isn't really any workaround. We shouldn't have a problem with large files or data structures, unless they contain a lot of functions. Maybe you can convert it to generate calls into a builder?

```python
def make_lazy(fn, *args):
    def maker():
        return fn(*args)
    return maker

DATA = {
 'a': make_lazy(generate, 'a'),
 'b': make_lazy(generate, 'b'),
}
```

We still may see this as a lot of function definitions, depending on the parameter types, and we may lose information about the values in `DATA`, but it shouldn't have the same memory issues.

**Comment by mrolle45** [comment]
Thanks for such a thorough reply.  I'll try the Compile to Content thing.

However, I couldn't do this if my application is also generating these files dynamically, so that I would not know ahead of time what their names are.  In this case, I suppose the best thing is to put the generated Python files in some other folder (not a package) and use the imp package to load them.

Remaining points .. Does the analysis really need to pull in Python code just because it is lying in the package folder, and is not explicitly imported?  Can I set some option or property somewhere so that Python code is treated as Content by default rather than Compile?

If the file is located in a subpackage but the subpackage is not mentioned in the Project, would code analysis pull in the entire package anyway?

If I dynamically import a module, and this module gets added to sys.modules, then will the code analysis see this and analyze the code?

**Comment by zooba** [comment]
We do basically everything statically, so all potential imports will be found and analyzed regardless of whether they are ever imported. If we don't do this, then we end up losing useful information.

One change coming in VS 2017 is that files only available from a search path will not be analyzed - instead, they'll have much simpler parsing performed and only on-demand. So if these files are not included in your project file (which *should* exclude them from analysis) but you add a search path to their directory, you'll still get some completions when you import them but they won't use lots of memory.

The ideal case would be for us to detect when a module is taking too much memory and switch over to this approach automatically. We haven't implemented that yet, and it wouldn't have been possible in the past anyway because we didn't have the support handy.

**Comment by mrolle45** [comment]
**Build Type = Content does not help.**
I added my file to the Project, set the Build Type property to Content, and VS still croaked.

**Comment by mrolle45** [comment]
Here's what works for me as a workaround.
1. Generate file `foo.py`.
2. Use `py_compile.compile` to generate `foo.pyc`.
3. Rename `foo.py` to `foo.py_`.  This enables me to look at the file in VS as a plain text file.
4. To dynamically load the module I use
`try: f, n, p = imp.find_module ('foo'); module = imp.load_module ('package.foo', f, n, p)
finally: f.close ()`
The package name is needed if `foo` contains relative import statements.
