### ISSUE TITLE
'A build is already in progress' error during solution opening

### ISSUE THREAD

**Issue by 0xDAD** [Microsoft/PTVS#1982]
The following error appears sometimes on VS 2015 solution opening:
**<project path/name>.pyproj : error  : A build is already in progress.** 

![ptvs1](https://cloud.githubusercontent.com/assets/958565/21255555/b053fa5a-c37d-11e6-9b7d-21bb16faa1c1.PNG)

Used VS Info:
> Microsoft Visual Studio Community 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01055
> 
> Installed Version: Community
> 
> Visual Basic 2015   00322-20000-00000-AA019
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-20000-00000-AA019
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-20000-00000-AA019
> Microsoft Visual C++ 2015
> 
> AnkhSVN - Subversion Support for Visual Studio   2.6.12735.14
> AnkhSVN - Subversion Support for Visual Studio 2.6.12735.14 
>  * Ankh.Package 2.6.12735.14
>  * Subversion 1.9.2 via SharpSvn 1.9002.3777.76
> 
> SharpSvn is linked to: Apr 1.5.1, Apr-util 1.5.4, Cyrus Sasl 2.1.26, eXpat 2.1.0, LibSSH2 1.6.0, OpenSSL 1.0.2d 9 Jul 2015, Serf 1.3.8, SQLite 3.8.11.1, Subversion 1.9.2-SharpSvn, Utf8proc 1.1.5, ZLib 1.2.8
> SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 0.65.0(SharpSvn)
> 
> Application Insights Tools for Visual Studio Package   1.0
> Application Insights Tools for Visual Studio
> 
> Clang with Microsoft CodeGen   14.0.25516
> Clang with Microsoft CodeGen
> 
> ClangFormat   1.0
> Formats code by calling the clang-format executable.
> 
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> GitHub.VisualStudio   2.1.1.5
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> KofePackagePackage Extension   1.0
> KofePackagePackage Visual Studio Extension Detailed Info
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> NuGet Package Manager   3.4.4
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> Python Tools for Visual Studio   2.2.40825.00
> Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.
> 
> Python Tools for Visual Studio - Django Integration   2.2.40825.00
> Provides templates and integration for the Django web framework.
> 
> Python Tools for Visual Studio - Profiling Support   2.2.40825.00
> Profiling support for Python projects.
> 
> Qt Visual Studio Tools   2.0.0
> The Qt Visual Studio Tools allow developers to use the standard development environment without having to worry about any Qt-related build steps or tools.
> 
> TypeScript   1.8.36.0
> TypeScript tools for Visual Studio
> 
> Visual Assist   
> For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c) 1997-2016 Whole Tomato Software, Inc.
> 
> Visual C++ for Cross Platform Mobile Development (Android)   14.0.25401.00
> Visual C++ for Cross Platform Mobile Development (Android)
> 
> Visual C++ for Cross Platform Mobile Development (iOS)   14.0.25401.00
> Visual C++ for Cross Platform Mobile Development (iOS)
> 
> Windows Installer XML Toolset   3.10.3.3007
> Windows Installer XML Toolset version 3.10.3.3007
> Copyright (c) .NET Foundation and contributors. All rights reserved.

**Comment by zooba** [comment]
Thanks.

Just out of interest, do you _only_ see this when you have C++ projects in the solution? I'm fairly sure I know why it's occurring (there are occasionally deadlocks on project open because of the same issue :( ), but I haven't actually seen this particular error message appear.

**Comment by zooba** [comment]
#1266 is the other issue. Ideally, we wouldn't trigger builds at all on open, but it's the only way to get reliably information from MSBuild (technically we're not building anything, but we need to execute some tasks).

**Comment by 0xDAD** [comment]
Hi,
I couldn't reproduce it on solution having only .pyproj or 2 or 3 c++ projects. This usually happens on my working solution having ~300 C++ projects, ~10 WiX projects, 2-3 c# projects.

**Comment by zooba** [comment]
Do the Python projects have references to any C++ projects?
