### ISSUE TITLE
Navigation Bar does not navigate to classes

### ISSUE THREAD

**Issue by supakorn-ras** [Microsoft/PTVS#1988]
PTVS 3.0.16334.1, VS2017 RC 15.0.26014.0

Create a new python project, copy python code, navigation bar does not properly navigate to classes/functions. Within classes, the methods navbar also doesn't properly navigate to selected methods.

**Comment by zooba** [comment]
Thanks! When you say "does not properly navigate", do you mean it doesn't go anywhere? Or it goes to the wrong place? If the latter, is it consistently wrong (for example, always X lines above/below the definition)?

**Comment by supakorn-ras** [comment]
If at the top of the code, the navigation bar doesn't navigate at all. If anywhere else, the navigation bar always comes back to the first function regardless of what was selected, along with the bar itself. (For example, if the first function is main() and I navigated to another class within the file, the navbar comes back to main no matter what I do.)
