### ISSUE TITLE
.vsp files generated by profiler give "VSP1237: sharing violation" error when Anaconda env selected

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1991]
I was trying to profile some code with Anaconda, but got the following error. It worked when I switched to a Python 3.5 environment. What profiler are we using? What work would we need to do to enable profiling in the Anaconda environment?
 
Given Anaconda is an important part of the VS data science workload, we should resolve this for VS2017 if possible. 

![image](https://cloud.githubusercontent.com/assets/5177491/21463149/220fa5f8-c91a-11e6-95cc-a2ef997d6d08.png)

**Comment by zooba** [comment]
Assigning people doesn't get bugs fixed quicker (we all use the assignment field to mean "actively working on right now", and when it's set, nobody else will take the issue even if they can get it done sooner).

If it needs to be fixed, the `release-blocking` tag is the way to mark it.

**Comment by eclectir** [comment]
The intention wasn't to get it done sooner as assumed. Hugues was investigating the prolfiler bugs before so seemed like the natural fit for this since he might have had some context. He can assign it back. Thanks for clarifying your convention.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Dec 27, 2016 at 9:18 AM -0800, "Steve Dower" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigning people doesn't get bugs fixed quicker (we all use the assignment field to mean "actively working on right now", and when it's set, nobody else will take the issue even if they can get it done sooner).

If it needs to be fixed, the release-blocking tag is the way to mark it.
