### ISSUE TITLE
Error thrown when opening project

### ISSUE THREAD

**Issue by jh502** [Microsoft/PTVS#1992]
Error occurred when opening a solution created in VS2015 into VS2017 RC (Build 15.0.26014.0), upon loading the first python project in the solution.

Python tools version in use: 3.016334.1

```
System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudioTools.Project.ProjectReferenceNode.get_ReferencedProjectBuildOutputs()
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode.get_ReferencedProjectOutputPath()
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode.Initialize()
```
After the error occurred, and was dismissed, both of the python projects in the solution were imported, seemingly successfully, but both appear as checked out, with changes to .pyproj, as you may expect.

The lines changed in each .pyproj file were identical, and are listed below:-
Removed:
`    <PtvsTargetsFile>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Python Tools\Microsoft.PythonTools.targets</PtvsTargetsFile>`

  `<Import Condition="Exists($(PtvsTargetsFile))" Project="$(PtvsTargetsFile)" />`

  `<Import Condition="!Exists($(PtvsTargetsFile))" Project="$(MSBuildToolsPath)\Microsoft.Common.targets" />
`

Added:
`  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Python Tools\Microsoft.PythonTools.targets" />
`

**Comment by zooba** [comment]
Thanks! The changes to your project are expected, but that exception is not. (I _think_ I may have fixed it already, but need to check before closing this issue.)
