### ISSUE TITLE
Auto-detect crashes with Python 3.6 64-bit

### ISSUE THREAD

**Issue by r0f1** [Microsoft/PTVS#1994]
Hi,
I downloaded and installed 'Python 3.6.0 - 2016-12-23', 64-bit version from the [python website](https://www.python.org/downloads/windows/). After opening VS, I saw, that the new environment was not recognized, in the Python Environment tab, so I started to add it manually. However, when I wanted to select the version, there was no option for 3.6 (only 3.5), so I clicked on "Auto-detect". Then VS crashed. 
After a restart, **all** of my exsisting Python Environments were gone and the "+ Custom" button was greyed out. Also, navigating to the "Python Tools" section of the "Options", I saw that I have "no environments installed" and everything was greyed out over there as well.

I am now uninstalling Python 3.6 and reinstalling VS+PTVS. Just thought you should know.
Best, r0f1

UPDATE: The new installation did not help. But I got my python environments back by editing the registry: I navigated to

    HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0\PythonTools\Interpreters

There was one folder in this directory (and some of the keys told me that the version was indeed the one that I added with version 3.6). After deleting the folder, everything was back to normal.

**Comment by zooba** [comment]
I believe this is just the auto-detection crashing. You should be able to select "3.5" from the drop-down and fill in the other information by hand (nothing apart from the directory has changed from 3.5).

You won't get any support for the new syntax in 3.6, but that's the nature of software updates. We don't have any updates planned for VS 2015 any more, but [VS 2017](https://www.visualstudio.com/downloads/#visual-studio-community-2017-rc) has proper support for 3.6, as well as a fix for this particular crash.

**Comment by r0f1** [comment]
Thanks!

**Comment by tobigithub** [comment]
Not sure how this is closed its still open somewhere else:
https://github.com/Microsoft/PTVS/issues/1565

**Comment by zooba** [comment]
There is a 2.2.6 RC release at https://github.com/Microsoft/PTVS/releases/tag/v2.2.6-rc with the fix for this issue. Please try it out and let us know if anything goes horribly wrong - we want to push the fix to all users within the next month.

**Comment by hickford** [comment]
Hi @zooba. I installed that RC but PVTS still doesn't autodetect Python 3.6 on my computer

    Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by zooba** [comment]
@hickford The auto-detect we are referring to is when you are adding it as a custom Python environment. PTVS in VS 2015 does not support Python 3.6, and so it will never automatically detect it completely, but you can pretend that it is Python 3.5 and it will work well enough.

VS 2017 properly supports Python 3.6, and automatically detects it as soon as you install it.

**Comment by hickford** [comment]
Thanks @zooba . Installed Visual Studio 2017 RC and now using it with Python 3.6. Really impressed by PTVS, I love the profiler and the debugger.

**Comment by csiege** [comment]
@zooba, hit this problem on VS2015. Thanks for your post, installing latest PVTS and was able to get custom option working.
