### ISSUE TITLE
Beta 2.2 slows down Text editor

### ISSUE THREAD

**Issue by pinguin999** [Microsoft/PTVS#20]
Hi

I tryed the 2.2 Beta and it slows the IDE sown so every key stroke needs 1-2sec to display on the screen...

Changed back to 2.1 for now.

**Comment by zooba** [comment]
Are you able to give us any idea of what CPU usage looked like while it was running slow? Was it always using a single (or multiple) cores, or just when you pressed a key? Did you have a large project open? Was it just in Python code or in every file?

**Comment by pinguin999** [comment]
The CPU usage was high until the key showed up. I don't know if it was single or multi core load. 

I have a "bigger" Django project and it was in the python and the html files.

**Comment by zooba** [comment]
Okay, thanks.

@crwilcox - have you noticed anything like this recently? Not entirely sure if your project qualifies as big though, so it may not have been as dramatic...
