### ISSUE TITLE
PTVS does not compile at ToT with VS 2013

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#200]
18>D:\src\PTVS\Python\Product\EnvironmentsList\PipExtensionProvider.cs(352,25,352,55): error CS1984: **Cannot await in the body of a finally clause**
18>D:\src\PTVS\Python\Product\EnvironmentsList\PipExtensionProvider.cs(405,25,405,55): error CS1984: **Cannot await in the body of a finally clause**
19>------ Build started: Project: PythonTools, Configuration: Debug Any CPU ------
19>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. **Could not locate the assembly "Microsoft.VisualStudio.InteractiveWindow"**. Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
19>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. **Could not locate the assembly "Microsoft.VisualStudio.VsInteractiveWindow"**. Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

"Cannot await in the body of a finally clause appears to be a C# 6.0 language feature.  The [installation instructions](https://github.com/Microsoft/PTVS/wiki/Build-Instructions-for-PTVS) do not mention a requirement of C# 6.0, and actually given the list of supported build environments (i.e. going back to VS 2010) it seems like this was probably just an oversight.  I guess that these lines of code somehow need to be removed.

For the second issue, I have installed the Visual Studio 2013 SDK but these assemblies are still nowhere to be found.  Are these Microsoft internal?  Or only with the VS 2015 SDK?  Or am I just overlooking something in the instructions that explains how to get them?

I also encountered two additional build errors.  The Azure SDK is listed as optional, but it appears to be required.  `PythonCore\PythonTools` has a reference to `Microsoft.VisualStudio.WindowsAzure` and will not successfully compile without it.  

Second, when installing the Azure SDK, it's not enough to just install the Azure SDK for Python.  After it is complete, you explicitly have to go and add Azure SDK for .NET Framework as a separate step, otherwise you won't get the assemblies.

The missing references and C# 6.0 language features appear to have been introduced in the past month, because if I sync back to April or so I don't get these errors.

**Comment by int19h** [comment]
If you have just fetched the fresh source, try reloading the solution in VS - this should take care of the missing VSInteractiveWindow assembly issue (it is VS 2015 only, but when building with VS 2013 there should be a bunch of conditionals in the .csproj file that exclude that code). 

await inside finally is a genuine issue that simply went unnoticed. Note though that for 2.2, we only support VS 2013 and higher (the build instructions page needs to be updated).

You're also right about Azure SDK.

**Comment by zjturner** [comment]
Closing and reloading the solution doesn't seem to fix the VsInteractiveWindow problem for me.  I opened up the .csproj in an editor and I see this:

    <Reference Include="Microsoft.VisualStudio.VsInteractiveWindow">
        <HintPath>$(DevEnvDir)PrivateAssemblies\Microsoft.VisualStudio.VsInteractiveWindow.dll</HintPath>
    </Reference>

Is it possible the conditionals were just accidentally left out of this one?

**Comment by zooba** [comment]
Actually, there don't seem to be any conditions on those references - I've got a fix coming

**Comment by zooba** [comment]
Leaving this issue open so we remember to fix the build instructions, and tagging appropriately.
