### ISSUE TITLE
Feature request: Django: Format HTML

### ISSUE THREAD

**Issue by pvkc** [microsoft/PTVS#2016]
There is no option to format the clumsy html. The` ctrl+k,f `doesn't work.
Much appreciated if this would be working
![image](https://cloud.githubusercontent.com/assets/11032841/21667468/ed6a9d0e-d2be-11e6-94c5-336629baec97.png)

**Comment by huguesv** [comment]
Yeah, we had to disable it because it was causing loss of data. There are some details on our old tracker: http://pytools.codeplex.com/workitem/2301

Hopefully we can make this work and re-enable the commands.
