### ISSUE TITLE
Immediate Window says "global name is not defined" for local variable.

### ISSUE THREAD

**Issue by HHest** [microsoft/PTVS#2023]
Hi, the code below runs fine, 

```
import pandas as pd

def f(x, y):
    return x + y

def a():
    n = 100
    df = pd.DataFrame({'a': [1, 2, 3], 'b': [10, 11, 12]})

    df['c'] = df.apply(lambda row: f(row['a'], n), axis=1)
    return df

if __name__ == '__main__':
    print a()
```

Output:

```
   a   b    c
0  1  10  101
1  2  11  102
2  3  12  103
Press any key to continue . . .
```

but behaves strangely in the debugger. First, set a break point on the `df['c'] =` line, then when the breakpoint is hit, type `df.apply(lambda row: f(row['a'], n), axis=1)` in the Immediate Window. 

```
df.apply(lambda row: f(row['a'], n), axis=1)
error: ("global name 'n' is not defined", u'occurred at index 0')
```

Thanks and regards!

**Comment by zooba** [comment]
Perhaps the Immediate window is not running in the current scope? It's entirely possible.

Instead of using the Immediate window, can you try the Python Debug Interactive window? (It should be under the Debug-Windows menu). This will give you a much better experience for Python, but it basically behaves the same way as the immediate window.

**Comment by HHest** [comment]
Thanks for the Debug Interactive window tip! I've never used it before. Unfortunately it did not help, although it gave a traceback:

```
>>> 
df.apply(lambda row: f(row['a'], n), axis=1)
Traceback (most recent call last):
  File "<debug input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 4061, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 4157, in _apply_standard
    results[i] = func(v)
  File "<debug input>", line 1, in <lambda>
NameError: ("global name 'n' is not defined", u'occurred at index 0')
>>> n
100
```

I added a few prints to frame.py, and I noticed that the func.func_closure is different if I just let the code run while debugging, versus when I execute the command manually in DIW.

[run while debugging]
```
in _apply_standard True False
func_closure: (<cell at 0x0238FE30: int object at 0x0081B77C>,) 100
in reduce block
returned
   a   b    c
0  1  10  101
1  2  11  102
2  3  12  103
Press any key to continue . . .
```

[execute command in DIW. Note func_closure is empty]
```
>>> df.apply(lambda row: f(row['a'], n), axis=1)
in _apply_standard True False
func_closure: NoneTraceback (most recent call last):
  File "<debug input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 4061, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 4093, in _apply_standard
    print 'func closure', func.func_closure, func.func_closure[0].cell_contents
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by HHest** [comment]
p.s. I have pandas 0.18.1. Attached frame.py

[frame.py.txt](https://github.com/Microsoft/PTVS/files/693316/frame.py.txt)

**Comment by zooba** [comment]
Interesting. Perhaps it is because we call `compile(text ... 'eval')` rather than `compile(text ... 'exec')`? Or perhaps the call with `eval` fails and we end up calling with `exec`? I don't know all the subtleties of these without looking at the sources, but it's almost certainly going to affect evaluation of the outermost frame, which could lead to `func_closure` being unset.

Perhaps reassigning `n` (literally, `n = n`) in DIW will help? That ought to bring it into the current evaluation frame.

**Comment by HHest** [comment]
Nope. Same issue:

```
Python debug interactive window.  Type $help for a list of commands.
Python 2.7 interactive window [PTVS 2.2.40825.00-14.0]
Type $help for a list of commands.
>>> n = n
>>> df.apply(lambda row: f(row['a'], n), axis=1)
Traceback (most recent call last):
  File "<debug input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 4061, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 4157, in _apply_standard
    results[i] = func(v)
  File "<debug input>", line 1, in <lambda>
NameError: ("global name 'n' is not defined", u'occurred at index 0')
```
