### ISSUE TITLE
Keyboard scrolling in completions list broken

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2033]
Using this week's build of VS 2017, when you hit arrow down on the completion list in Python, for example in the list that appears when you type `import <space>`, you see the selection change until you go below the last visible item, where it looks like selection keeps moving down, but you don't see it because the list isn't scrolling.

I checked C# and F#, and they don't have the issue.

**Comment by zooba** [comment]
Okay, that's really weird. I'd want to try it with a proper build (we weren't using a proper installation of PTVS today), but it basically has to be related to the underlying completion control. I'm not sure who owns that, but F# certainly made a lot of changes recently, and it may have affected it.

**Comment by huguesv** [comment]
Still repros on a proper install, on build 26109.02 from d15rel.

**Comment by zooba** [comment]
This also happens in the diagnostic info window. I'm at a total loss...

**Comment by zooba** [comment]
Figured it out.
