### ISSUE TITLE
No longer able to set a startup item in folder view

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2035]
In previous releases of VS 2017, I was able to use F5/CTRL-F5 when opening python folder in solution explorer folder view (I was using Brett's web app cookiecutter template).

But with the latest builds, it's not letting me set a startup item, so my only option is to right-click in the editor on the .py file I want to run and select start with/without debugging from context menu.

Not sure if it's VS bug or us. Again, I'm pretty sure this worked at some point and is a regression.

**Comment by zooba** [comment]
I think this was a build related regression that should be fixed now. I'll try and repro.

**Comment by zooba** [comment]
Works fine in latest builds.
