### ISSUE TITLE
Profiling django project doesn't run the server

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#2036]
It doesn't use the info from the django launcher, so what you're profiling is django printing out the various command line arguments you can pass to it, instead of actually launching the server.

So instead of selecting to profile "Open Project", you have to pick "Standalone script", and fill in all those parameters.

It would be convenient if it worked with "Open Project".

**Comment by zooba** [comment]
Did this ever work in the past? I suspect it did not...

**Comment by huguesv** [comment]
I was asking myself the same question!
