### ISSUE TITLE
Unable to set up python environment.

### ISSUE THREAD

**Issue by Ni9elC** [Microsoft/PTVS#2039]
when I select an interpreter through the python environment window, there is a crash on my laptop. I mean I was forced to reboot my machine. after restart my laptop, the "+custom" button in the python environment window cannot be clicked. I have uploaded a pic of my issue.
![issue](https://cloud.githubusercontent.com/assets/19585104/21762840/d1642c62-d695-11e6-98e9-a1bd66f86ca5.PNG)

**Comment by zooba** [comment]
We have an update in testing to fix this - you can try the RC release by installing the MSI from [our 2.2.6 RC release page](https://github.com/Microsoft/PTVS/releases/tag/v2.2.6-rc). You'll get a notification in VS when we release the final fix.

Please let us know if you still see issues after installing this update.

**Comment by Ni9elC** [comment]
@zooba thanks! it works!
