### ISSUE TITLE
Code snippets don't expand in REPL

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2045]
They show up in completion list, but pressing TAB doesn't expand them.

FYI we've had several issues in RTVS regarding snippets in REPL (they now work).

If it's expensive to fix, I'm tempted to say remove them from REPL completions.  Simply to avoid this frustrating scenario:
![image](https://cloud.githubusercontent.com/assets/1696845/21821023/cf5d1c44-d726-11e6-8b53-a8b7a859b54a.png)

**Comment by zooba** [comment]
They're not supported in the REPL right now, so we should remove them from the list.

**Comment by zooba** [comment]
(Though note that most of our snippets are also keywords, which do appear in the repl. testc/main will go await though.)
