### ISSUE TITLE
Add UI to configure interactive window for Environment: <project name>

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2048]
I was trying to set my project's interactive window to use IPython interactive mode, and eventually found out that it was possible if I create a folder under `Documents/Visual Studio 15/Python Scripts/<projectName>`.  (I first configured my global Anaconda via the UI, then copy-pasted its folder)

While that works fine, it would be nice if that was exposed via the UI.

**Comment by zooba** [comment]
There's an item for this in the Python Environments window.
