### ISSUE TITLE
idna package very slow to analyze

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2051]
Create new python application
Create a requirements.txt with:
```
futures
python-dateutil
requests
vcrpy
coverage
pyopenssl
msrest>=0.4.0,<0.5.0
msrestazure>=0.4.0,<0.5.0
```
Create a virtual environment, installing packages into it (I've tried based on Python 3.5 and 3.6).
Check Python Environments, you'll see env IntelliSense analysis progress gets stuck at about 75%, at `idna` for maybe 5-10 minutes.  Eventually it will complete.

`idna` is so small that it feels like it shouldn't take that long to analyze.  It's just 7 modules, but maybe it's due to the large arrays and dicts returned by functions.

**Comment by zooba** [comment]
Great catch! We spend a lot of time concatenating the lists returned from the functions in `idna.uts46data`. My guess is that because they are list literals, we are trying to keep every value around in case it gets splatted, and because of how they've split up the lists we're probably _just_ missing a trigger point to collapse it to a single type.

**Comment by zooba** [comment]
Waiting for this is holding up my recording session by over 15 minutes... let's fix this :)

**Comment by zooba** [comment]
According to https://developercommunity.visualstudio.com/content/problem/72710/appjar-on-anaconda-440.html the same thing happens with [appJar](https://pypi.org/project/appJar/). Might be the same reason, but we should look into both.

**Comment by zooba** [comment]
Reducing to P2 - the work on replacing the background analysis completely will cover this.

**Comment by zooba** [comment]
According to #3378, also occurs with `vpython`.

**Comment by zooba** [comment]
Out of date now that we don't use this analysis approach anymore.
