### ISSUE TITLE
ESC doesn't clear the cookiecutter search filter when there's an active doc

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2058]
If you have a document window open, then hitting ESC in the cookiecutter search box will put focus on the active document.

Without any document, ESC clears the filter and applies it.

It should clear search in both cases.

**Comment by zooba** [comment]
Probably just need to add `e.Handled = true` to the event handler, or possible switch to a PreviewKeyDown event instead.

**Comment by huguesv** [comment]
Our event handler isn't called, even with PreviewKeyDown.  We do get called for ENTER, but not ESC.

**Comment by zooba** [comment]
Ah of course, because VS handles that keypress to switch window. Might have to file this one with the IDE team

**Comment by huguesv** [comment]
Yes, and the environment packages search box has the same issue.

For reference, RTVS hosts the VS standard search control, in the history window (in toolbar) and in the package manager (as part of the control), and it doesn't have the issue.

![image](https://cloud.githubusercontent.com/assets/1696845/25629412/4172b8da-2f1e-11e7-8a2c-ae6bae188f13.png)
