### ISSUE TITLE
Add existing py file from subdirectory "fails"

### ISSUE THREAD

**Issue by bicolorado** [Microsoft/PTVS#2072]
When adding a new py file to project from existing py file in a subdirectory under the main app solution directory, the file adds correctly to the solution but copies the original into the main directory... I expect it to keep the item in the original source directory.
Before add:
   \PythonApp.pyproj
   \PythonApp.sln
   \file.py
   \test\file2.py

After add of file2.py using "Add -> Existing Item.." popup :
   \PythonApp.pyproj
   \PythonApp.sln
   \file.py
   \file2.py
   \test\file2.py

Changes to the file2.py file in the solution explorer only modify the one in the \ path.

Guessing the expected use model is to create new folders in the solution, but that's not how other languages work.

**Comment by zooba** [comment]
Another way to do this is to enable [Show all files](https://github.com/Microsoft/PTVS/wiki/Browsing-Code-Using-PTVS#show-all-files) button and then right-click the file you want and select "Include in Project". You can do the same for entire directories and it will include all the files contained as well. Or yes, create the folder and then right-click _that_ and choose to add the new item there (though this may not work if the folder is already on disk).

As far as I'm aware, all other languages besides C++ (which has a _very_ different model) will copy an existing file through that approach. If they don't, they are newer than our support, and so it's a little unfair to say we should have copied them before they existed :)

One of the main reasons we chose to do it this way is that we really want the Solution Explorer view to match what Python will see when you start running, which is based on the file system. So while we do allow [linked files](https://github.com/Microsoft/PTVS/wiki/Projects#linked-files), everything else should be in the same place on disk as it appears in Solution Explorer.

**Comment by bicolorado** [comment]
Fair cop.. really appreciate your response and thank you for the info.
