### ISSUE TITLE
Q: How to tell VS/Test Explorer about deleted tests?

### ISSUE THREAD

**Issue by HHest** [Microsoft/PTVS#2081]
I was playing around with Test Explorer, and having assessed it, I tried to turn it off by closing the window. Afterwards I deleted a test file from my project.  Now, whenever I debug something, VS would complain "The item "TestXYZ.py" does not exist in the project directory. It may have been moved, renamed, or deleted."

That message is correct: yes, I did delete the test. How do I stop it from appearing again please?

Thanks for your help.

**Comment by zooba** [comment]
Once you save the project file it should go away.

In VS 2015 and earlier, we check every file listed in the project for tests, and warn if anything doesn't look right.

**Comment by HHest** [comment]
Thanks for that. Do you mean this should work in VS2017, but not in VS2015, then? Unfortunately we are still using VS2015. My project is saved---it does not have a "*", and in any case, I have closed and restarted VS---but the warning is still there. 

Here's my work-around: first, I edited my .playlist file to remove the deleted test, but that did not fix the problem. Then when I edited the .pyproj file as well, the warning went away.

Will mark this as closed. Thank you.

**Comment by zooba** [comment]
Hmm... perhaps something got cached.

In VS 2017 we detect tests in code files as we're doing our analysis, so we never directly refer to the project file and will know straight away when you remove a file.
