### ISSUE TITLE
Set Search Path for entire solution

### ISSUE THREAD

**Issue by Nummer35** [Microsoft/PTVS#2084]
Hello,

i develop with a custom sdk in visual studio 15 and want to have intellisense against my own product API (.Net) with my ironpython scripts. These python scripts are in different projects inside of the solution. Is there a way to set the search path for an entire solution or force visual studio to use the IRONPYTHONPATH variable without generating a specific pythonproject?

Greetings,
Alex

**Comment by zooba** [comment]
The `Ignore system-wide PYTHONPATH variables` option under Tools, Options, Python Tools will let you set `IRONPYTHONPATH` globally (we specified `PYTHONPATH` in the description just for recognition, but it actually disables masking of whatever environment variable name is specified for the Python environment).

**Comment by Nummer35** [comment]
Is there a way to get intellisense against my .dll files without setting the search/reference path?

**Comment by zooba** [comment]
No. We try to be consistent with how it will work at runtime, and if you don't have a search path for your DLL when running then IronPython won't be able to find it.
