### ISSUE TITLE
Links broken at releases/v2.2

### ISSUE THREAD

**Issue by HatsuMora** [Microsoft/PTVS#2089]
The links are broken on the https://github.com/Microsoft/PTVS/releases/v2.2 page,

For example the first one is and should be: 
"https://ptvs.blob.core.windows.net/download/PTVS" 
"https://ptvs.blob.core.windows.net/download/PTVS 2.2 VS 2015.msi"

The link has spaces, for this reason is broken.

**Comment by zooba** [comment]
Thanks for the heads-up. Looks like GitHub changed how they handle URLs, since these definitely used to be right.

**Comment by zooba** [comment]
I think I've fixed them all now.
