### ISSUE TITLE
No intellisense/completion db for extension module that contains submodules

### ISSUE THREAD

**Issue by vdolbakyan** [Microsoft/PTVS#2093]
Hi,

I created python extension module that has 2 sub modules

In analyzer i see it launches ExtensionScraper.py  script. But i dont see how it really dumps the completion db for the submodules

After this call 
**module_table['members'] = generate_member_table(module, extra_types = extra_types).** 

I see my 2 submodues as 
_modulename1 = type(builtins, module)
modulename2 = type(builtins, module)_

But looks like its missing the step when it has to go and scrape each submodule and dump the data to completion db

As a result my modules reported as "unknown type) when i import them in my script

Thanks

**Comment by huguesv** [comment]
Not a critical scenario for us.
