### ISSUE TITLE
Qt and PTVS

### ISSUE THREAD

**Issue by heedaf** [Microsoft/PTVS#210]
Is it possible to use Qt Designer with PTVS.  If so how do I get the ui file?

**Comment by int19h** [comment]
There's no integration with Qt design tools in PTVS. You'll have to use the Designer as a standalone app. It probably has the ability to create a new .ui file; if not, you'll have to look for a sample and copy it.

**Comment by heedaf** [comment]
Thanks for the reply.  How do I get the ui file into the project?  Would I just copy the file into the folder or is there something special I would need to do?

**Comment by zooba** [comment]
You can use the Add Existing Item command (right-click the folder you want to add it to and then browse to the file) to add it. This will make sure that if you use PTVS to deploy your code elsewhere it will be included, but we don't do anything special for .ui files - we'll just treat it like plain text.

**Comment by heedaf** [comment]
Thanks!  Once the ui file is loaded how do I refer/access the widgets in the ui file?

**Comment by zooba** [comment]
You'd be best to refer to the PyQt documentation at this point. You'll probably need to write some Python code to load it when you run, or you can use VS's plain text editor to look at the file. We don't have any support for visually designing these.
