### ISSUE TITLE
PTVS no longer discovers my Unit Tests

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/PTVS#2101]
Up until recently, I was able to see my unit tests in the VS Test Explorer. Now no tests appear in the Test Explorer window. When I change my project, the output window shows:

```
------ Discover test started ------
========== Discover test finished: 0 found (0:00:06.2472349) ==========
```

However there are dozens and dozens of tests that as recently as last week appeared. I tried updating to the latest PTVS but that didn't fix anything. The wiki notes a "beta caveats" for known issues and workarounds but I don't know where those are.

**Comment by zooba** [comment]
Could you open Tools, Python Tools, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

**Comment by tjprescott** [comment]
I sent the requested info to the alias.

**Comment by tjprescott** [comment]
Thanks @zooba!  Deleting my PythonTools\CompletionDB folder and rebuilding worked for me!
