### ISSUE TITLE
[Feature] Multi-group on test explorer

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#2103]
I can change the "group by" in Test Explorer:
![image](https://cloud.githubusercontent.com/assets/1050156/22521079/a1905190-e86b-11e6-9347-dc9e907bd3bb.png)

However, in multi-project solutions, when I want to launch *some* tests of *one* project, it becomes complicated:
- If I use project grouping, I see all my test *methods*, whatever the class, together. Ordered by name (so mixed up between classes).
- If I use class grouping, I see all the classes of all the projects. Ordered by name (so mixed up between projects)

I currently rename my classes to be able to "group by project" them under the "class" PTVS group. I should not feel required to name the classes to improve my usage.

Something like (random ideas):
- Prefixing method name by class name in "project" grouping (MyClass.myTest)
- Multi-hierarchy support (first level project, second level class)

Not critical, but not handy.

**Comment by huguesv** [comment]
I agree, I was just thinking about possibly renaming some tests yesterday for exactly this reason.

We need to convince the Test Explorer team to improve this.

I found these entries on user voice:
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/9803082-allow-multiple-filter-clauses-in-test-explorer
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/14762844-unittest-2-levels-of-grouping
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/18170995-enhance-test-explorer-window-with-sub-groupings

**Comment by huguesv** [comment]
Show Test Hierarchy button, which was added later in 15.x releases, makes the lack of multi-group functionality more tolerable.
