### ISSUE TITLE
Sometimes have empty path environment variable name

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#211]
See #197 for initial discussion

We should handle the cases where we currently set the variable name to an empty string and ensure it is being set to `PYTHONPATH` instead.

**Comment by huguesv** [comment]
In dialog, we'll validate when they click OK and prevent them from setting it to empty (like we do for other fields).
Edit via env window will still be able to set it to empty, we can deal with that when that part is redesigned.

**Comment by judej** [comment]
The environments Window redesign will take care of this scenario
