### ISSUE TITLE
PTVS 2.2.6 VS 2015 is broke on my machine 

### ISSUE THREAD

**Issue by matthewsheeran** [Microsoft/PTVS#2124]
Package errors on Visual Studio start-up.
Reinstalled PTVS 2.2.5 VS 2015 which works just fine.
* Let me know what logs, where, and how to turn them on, so I can then attach them here so whatever the bug is and introduced into 2.2.6 that can then be fixed for 2.2.7. :-)
Regards,
Matthew
Just let me know * and email me offline..

**Comment by huguesv** [comment]
These types of errors usually have details in the activity log, which is located at %APPDATA%\Microsoft\VisualStudio\14.0\ActivityLog.xml

If you open it in IE, it will show the errors in red, look near the bottom of the file.

**Comment by zooba** [comment]
There's also a good chance this is the component model cache issue, which is known but not fixed in VS 2015.

You can try deleting the contents of your `%LocalAppData%\Microsoft\VisualStudio\14.0\ComponentModelCache` after upgrading and then restart VS.

**Comment by zwn** [comment]
Mine is not working as well. Deleting the cache did not help. The ActivityLog.xml contains no recent data - everything is from 2017/02/08. I have also tried to uninstall and reinstall python tools. Still broken. Property pages in Options related to Python Tools say "An error occurred loading this property page".

**Comment by zwn** [comment]
Installing 2.2.5 did not help either. When opening python project I get

> The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

For reference, this is my setup: 
* win7
* vs2015 community
* vs2008 express
* python (none in path, only the py launcher)
  - 2.7
  - 3.5
  - 3.6

**Comment by matthewsheeran** [comment]
I haven't gotten around to trying the cache clear etc. suggestion above but you definitely have a different and sound like more serious problem than mine as a reinstall of 2.2.5 worked just fine for me.
I have all of VS 2010-2012-2013-2015 on my machine so you could try 2013 as an interim solution and see if that gets you by or reveals a more serious issue..
BTW PTVS is my preferred Python Dev environment but just don't try mixing .py's into .cs Projects I have found that the VS engine starts syntax checking and complaining about the Python files last time I tried this.

**Comment by zwn** [comment]
Just a status update: I uninstalled all python versions and also VS2015. Just removed everything. Installed back VS2015 and miniconda3 and everything seems to be working now.

**Comment by matthewsheeran** [comment]
Well I ain't doing that: that can wait until the next time I have to
refresh or reinstall Windows or more likely when I install on a new
machine! ;-)

**Comment by zooba** [comment]
@matthewsheeran I'm fairly sure clearing that cache will work for you. Please try that before reformatting your entire machine.

**Comment by matthewsheeran** [comment]
Yeah I cleared that cache today but just haven't gotten around to trying
the reinstall and maybe I'll uninstall clear it again then reinstall :-)
over the next week or so and I'll let you know how it goes..

**Comment by matthewsheeran** [comment]
Yes another attempt at installing 2.2.6 worked after having cleared that component cache last week!
Thanks and Regards,
Matthew
