### ISSUE TITLE
Skipped tests should be reported as skipped by test explorer instead of passed

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#213]
Now that we have the ability to run tests that are marked as unittest.skip or unittest.skipIf, we could look in StandardError to determine if we should report it as `TestOutcome.Passed` or `TestOutcome.Skipped`.

Right now we report them as passed, which can be quite misleading.

Example test output for a skipped test:
```
Test Name:	test_deployments
Test Outcome:	Passed
Result StandardError:	
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK (skipped=1)

```

By comparison, C# reports tests marked with Ignore() as skipped.

**Comment by zooba** [comment]
This ties into the need for a custom test result formatter that can either use a parseable output format (preferably one that we can parse incrementally).

As long as the exit code is the only information we have about test runs, we need to stick with one test per launch and the same limited output we currently have.
