### ISSUE TITLE
Character doubling in Interactive Window

### ISSUE THREAD

**Issue by craig-powell-NT** [Microsoft/PTVS#2133]
I have a new install of PTVS, and have added a pre-existing Anaconda installation of python as its environment.  When I open an interactive session, it doubles each letter after '=', '(', '[', and '{' (at least).  For example, typing
y=x
in a new session results in
y=xx
and it's necessary to use the backspace key to correct such a statement.

The initial automatic installed version was 2.2.6, but have switched to [PTVS 2.2.31124.00-14.0] without any change.

Thanks,

**Comment by huguesv** [comment]
Do you have other VS extensions that you could try disabling to see if it helps? That was the conclusion for https://github.com/Microsoft/PTVS/issues/1713

**Comment by craig-powell-NT** [comment]
Aha, removing the SCE GnD Editor Extension did the job.  I'm surprised I didn't find that earlier issue when I first searched.

**Comment by zooba** [comment]
Hmm... the GnD editor extension again? I'd guess they're just not expecting to be called on Python code, but I can't track down any way to report the issue.

Do you know where you got the extension from?

**Comment by craig-powell-NT** [comment]
I think that the GnD editor extension is the Visual Studio 2015 Integration component of the Sony PS4 SDK 4.0, and probably previous versions.  I don't see a support ticket on DevNet on the issue; it might be possible to post one if you can't contact the developers directly.

**Comment by zooba** [comment]
@craig-powell-NT I can't get into that site, but if you'd like to post something and let them know either to come to this issue or email ptvshelp@microsoft.com it'd be nice to figure this out. (If they're going to charge you for filing a ticket then you don't have to, but if you can get someone's attention that'd be great.)
