### ISSUE TITLE
Completion DB is Not Up to Date, It Doesn't Allow Me to Update

### ISSUE THREAD

**Issue by spaskiba** [Microsoft/PTVS#2135]
I use Visual studio 2015 with python.
when I try
import argparse or import os
it shows me a warning saying "unkown type", the files do exist in lib folder so it's there, I upgraded to pip 9 as well.

I guess it's because completion DB is not up to date, but whenever I click the "start refreshing" button, it starts and half a second later it stops, with no message, and still says completion DB is not up to date, what should I do?

I read somewhere a similar problem somewhere but I didn't find a fix, someone asked for a diagnostic python file..? I don't know where it is, so please tell me the paths for the files if you need any.

I might as well add that I have never seen a python code until today, usually I'm programming in C++, so I don't know anything about python. Help! Thanks.

**Comment by zooba** [comment]
Yes, the diagnostic information we'll need is under Tools, Python Tools, Diagnostic Info. You can save it to a file and attach it here, or send it to ptvshelp@microsoft.com and we'll take a look.
