### ISSUE TITLE
IntelliSense on 3rd party module only includes some items

### ISSUE THREAD

**Issue by csharpen** [Microsoft/PTVS#2139]
Hi,
I'm running VS 2015u3, with Python Tools 2.2.6. I've installed the F5 SDK (pip install f5-sdk or https://github.com/F5Networks/f5-common-python ), and it's functioning properly. It's also showing up under the IntelliSense listing with a checkmark as expected, and I've repeatedly rebuilt the Intellisense DB without issue. (I've also rebuilt my VS profiles/etc).

The problem I'm running into, is that while it lists *many* IntelliSense items, it's by no means complete.

For example:
`from f5.bigip import ManagementRoot`
`mgmt = ManagementRoot("10.0.0.1", "admin", "admin")`
`pools = mgmt.tm.ltm.pools.get_collection()`

... is a fairly simple usage of the SDK. However, In that example, mgmt.tm or mgmt.tm.(anything) won't show up, but a list of several other items does. Some other items show no completion at all.

Is the lack of IntelliSense items due to the way the module was written, or something the reflection routines are missing?

Thanks in advance for any assistance!

**Comment by zooba** [comment]
It'll be a bit of both. We use static analysis to determine IntelliSense results, so when it's not easy to determine a return type or attribute type we likely end up missing it completely.

We'd have to look into the F5 SDK to see whether this is likely. I'll leave this open as a reminder to investigate in case there is something that can easily be changed (either on our side or in the SDK itself) to make this analysis better.

**Comment by zooba** [comment]
See #3046
