### ISSUE TITLE
Intellisense problem when trying to access objects member of a model in django

### ISSUE THREAD

**Issue by amirzadajmal** [Microsoft/PTVS#2144]
Hi,

I am developing a Django project with PTVS 2.2.6 and whenever I want to filter a query, the objects member of model doesn't appear in the intellisense.

I have attached a picture of the problem. I would really appreciate being helped on this.

![error](https://cloud.githubusercontent.com/assets/22231935/22849971/796329ce-f020-11e6-8416-894d21cd4cd2.png)

**Comment by crwilcox** [comment]
Hi Amir.
Can I ask for some details on the directorates object that you expect to see a completion for? Is this a class implementing django.db.models.Model and you expect it to have object? (https://docs.djangoproject.com/en/1.10/ref/models/instances/#django.db.models.Model)

**Comment by amirzadajmal** [comment]
Hello Christopher,

Yeah, It is a class implementation of the django.db.models.Model. As you know that this class implementation by default has a Manager named object which appears in the completion list while working with Pycharm, however in the case of VS 2015, it doesn't appear and the pylint also gives an error about it.

Below is the code of the directorates model which will help you evaluate the problem

    class Departments(models.Model):
        entrydate = models.DateTimeField(auto_now=True)
        departmentname = models.CharField("Department", max_length=1000)
        note = models.CharField("Note", max_length=2000, null=True)
        directorate = models.ForeignKey(Directorates, on_delete=models.CASCADE)
        insertedby = models.IntegerField(null=False)
        updatedby = models.IntegerField(null=False, default='0')
        deletedby = models.IntegerField(null=False, default='0')

        def __str__(self):
            return self.departmentname

Please note that I also defined a class attribute of the type models.Manager but it didn't help me.

The main problem is that I was previously developing with pycharm and its itellisense would help me query a model using its objects.filter method, since it is a pain working with two different IDEs, I installed the PTVS 2.2.6 and VS is not giving me the departments.objects.filter so i can query the table.

**Comment by zooba** [comment]
Yeah, we don't do a great job on Django models (because we haven't added special support for them - it's just using our normal code analysis - and they're very dynamic Python code).

We have issue #1153 tracking this already, and our next release has better extensibility for code analysis that should make it easy for us (or someone else) to add special support for this.
