### ISSUE TITLE
Can I debug pypy RPython code in PTVS?

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#2145]
PyPy interpreter is written in RPython, which is translated to C for normal use cases. Is it possible to debug this interpeter code in PTVS?

**Comment by zooba** [comment]
If the transformation to C includes `#line` directives, then you should be able to debug using the regular native debugger in VS and it will automatically show you the lines from the original source file.

Our mixed-mode debugging relies on intimate knowledge of memory layouts and source code, so it's incredibly unlikely to work for anything we haven't deliberately added support for.

**Comment by denfromufa** [comment]
Can you point to any docs or examples how #line directives work? I'm not
sure how the native debugger is able to do this source mapping?

**Comment by zooba** [comment]
https://msdn.microsoft.com/en-us/library/b5w2czay.aspx

Essentially, it changes the information emitted to the PDB file, so you'll also need to make sure you have a PDB file generated from the build. Then the mapping works just like for C/C++ files, except it will go to another file.

**Comment by denfromufa** [comment]
@zooba that article does not mention anything about "automatically show you the lines from the original source file". it only mentions that these line directives are used by compiler when reporting errors.

**Comment by zooba** [comment]
Maybe not, but that's certainly how it works. Very few people need the functionality, so it's not surprising that it isn't prominently documented, but it is used everywhere (e.g. by the C/C++ preprocessor so that when you debug C/C++ code you see your original file and not the preprocessed version).
