### ISSUE TITLE
PythonTools .vsct localization

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2148]
It's working for cookiecutter, django and profiling, but not for python tools.

![image](https://cloud.githubusercontent.com/assets/1696845/22906467/6af93a88-f1f9-11e6-85a9-e7b6b82d1391.png)

Edit: Confirmed django vsct working.

**Comment by zooba** [comment]
Seems like our tooling requires the resource name to be `Menus.ctmenu` (or maybe just the `.ctmenu` suffix - didn't check).
