### ISSUE TITLE
"Django template tag" and "Python Interactive Window Error Output" not localized in options/fonts

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2149]
Our main Python entries are localized:
![image](https://cloud.githubusercontent.com/assets/1696845/22907169/b5ba91d6-f1fc-11e6-83e3-f58897ecbbcb.png)

But if you scroll down, you'll see these 2 entries are not:
`Django template tag`
`Python Interactive Window Error Output`

**Comment by zooba** [comment]
The latter is gone with #2168, so now it's just `Django template tag` remaining.
