### ISSUE TITLE
Incompatible with frida package

### ISSUE THREAD

**Issue by shuffle2** [Microsoft/PTVS#215]
I've installed [frida](http://frida.re) manually via easy_install, and PTVS does not detect the module at all for intellisense purposes.
You also cannot install frida via PTVS:

```
----- Installing 'frida' -----
Collecting frida
  Could not find a version that satisfies the requirement frida (from versions: )
  No matching distribution found for frida
----- Failed to install 'frida' -----
```

I guess this is because PTVS is only trying pip(?).

PTVS does detect frida is installed, it's just that the intellisense component does not detect it.

I'm using PTVS 2.2 RC, VS2013 update 4, and python 3.4.2 amd64. All standard packages (pip, setuptools, etc) are up to date.

**Comment by shuffle2** [comment]
Note: I realize the full sources are not shipped with the easy_install-able version, but if you can do:
```python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> dir(frida)
['AddressInUseError', 'ExecutableNotFoundError', 'ExecutableNotSupportedError', 'InvalidArgumentError', 'InvalidOperationError', 'NotSupportedError', 'PermissionDeniedError', 'ProcessNotFoundError', 'ProcessNotRespondingError', 'ProtocolError', 'ServerNotRunningError', 'TimedOutError', 'TransportError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_device_manager', '_frida', '_get_device', 'attach', 'get_device_manager', 'get_remote_device', 'get_usb_device', 'kill', 'resume', 'shutdown', 'spawn', 'threading']
>>> help(frida.spawn)
Help on function spawn in module frida:

spawn(argv, device_id=None)
```
...then I would expect a similar level of information available from intellisense.

**Comment by zooba** [comment]
This is probably because it is installed using an egg, and we currently require access to the source code to perform our analysis on it (we avoid executing arbitrary code without an explicit user action, like typing `dir()` in the interactive window).

We used to have an issue to extract source files from eggs so we can analyze them, and to add an option to analyze .pyc files by executing them, but they don't seem to be on github now so I'll recreate them.

**Comment by zooba** [comment]
This is completely covered by #217 and #219.
