### ISSUE TITLE
Switch to text-based protocol for debugger

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2154]
We need to switch to a fuzz-proof protocol for debugging so that random bit flips will not cause us to crash.

Since everyone is doing JSON these days, let's make it JSON.

**Comment by crwilcox** [comment]
Is the issue the format or fault tolerance of the design? It seems debugging protocols could be tolerant of bad data to APIs without changing a protocol?

**Comment by zooba** [comment]
It's the format. When we send strings as byte count followed by bytes, we have no way to know whether the string is really 1073741827 bytes long or if a random bit got flipped (and if you think that one's obvious, keep moving the flipped bit to the right until it becomes "reasonable", and then realize that we still need to work in unreasonable cases).

Going to JSON won't magically make us robust, but it adds a lot more constraints on the contents of each message, so detecting corruption becomes much easier to the point where we can reasonably protect against fuzzing. Right now, we have no ability to do that.

**Comment by huguesv** [comment]
Implemented in https://github.com/Microsoft/PTVS/pull/2323
