### ISSUE TITLE
Debug a python file in bash on windows

### ISSUE THREAD

**Issue by aviklai** [Microsoft/PTVS#2165]
I have a python file in my Bash on Windows environment. Is it possible to debug it with PTVS?
Can a debugger be attached to the Linux python version that exists in the Bash on Windows environment?

**Comment by huguesv** [comment]
Using remote debugging (ptvsd), it should be possible.
https://github.com/microsoft/ptvs/wiki/Cross-Platform-Remote-Debugging

Some more info on bash support here: https://github.com/Microsoft/PTVS/issues/1522

**Comment by aviklai** [comment]
@huguesv Thanks - I will try to do it through remote debugging.
