### ISSUE TITLE
Interrupt code running in interactive window (repl)

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#2169]
Looks like we don't have a button to interrupt running code.  I checked against PTVS 2.2 on VS 2015 Update 3, and it's not there either.  Unsure if versions prior to that had the feature or not.

**Comment by mmusket** [comment]
I am using PTVS to run keras and I really miss an interrupt button. Training a model can take a while and while its doing that my only two options are either waiting or starting from scratch. Sometimes I want to tweak something without loosing all the training up to the point.

**Comment by huguesv** [comment]
Also reported on uservoice: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33992545-keyboard-interupt-for-python-interactive-environme

**Comment by joseortiz3** [comment]
This would be really useful in interactive mode when a user executes (by accident) code that runs too long or forever and doesn't want to throw away what is in their interactive session.

**Comment by novog** [comment]
The lack of a keyboard interrupt is far and away the biggest thing keeping me from recommending PTVS for python development. In every other python environment that I have used, it is possible to interrupt a long-running statement without losing existing state that may have taken a significant amount of time to build up.

**Comment by joseortiz3** [comment]
Considering how much python is used for data science, lack of keyboard interrupt in a python development environment is _really_ bad. As @novog stated, sometimes the state I'm working in takes ten or twenty minutes to build, sometimes hours. Then I'll accidentally execute something I know might take hours or days to finish, so I need to stop it, and currently the only way is to kill the python process, resulting in an enormous waste of time.
