### ISSUE TITLE
Project template localization

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2173]
Names and descriptions in .vstemplate files

May not need to localize the generated code. I'll check ASP.NET to see if they do.

**Comment by huguesv** [comment]
I was thinking that since are web templates are based on the ASP.NET templates, we might want to follow their example.  But translating the master page (top and bottom header) and not translating the other pages makes no sense.
![image](https://cloud.githubusercontent.com/assets/1696845/23036577/322a118c-f438-11e6-92e8-e0ac64c07f3b.png)

**Comment by zooba** [comment]
For now, we'll get the title and description. We need to invest a decent amount more time to go through and get the template contents to be localized safely. I'll open another issue for that
