### ISSUE TITLE
Change tracking appears in REPL window

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2175]
![image](https://cloud.githubusercontent.com/assets/1693688/23037035/c971a5fe-f439-11e6-979e-ed20c7babd2f.png)

This is new with the change to use the built-in REPL.

**Comment by huguesv** [comment]
I'm not seeing it.
![image](https://cloud.githubusercontent.com/assets/1696845/23037693/383d1b2e-f43c-11e6-8970-0ed53777dd22.png)

**Comment by zooba** [comment]
I'm not seeing it now either - maybe it was just a bad build.
