### ISSUE TITLE
"The parameter is incorrect" error when clicking "Start without debugging"

### ISSUE THREAD

**Issue by nidleo** [Microsoft/PTVS#218]
Error appears after choosing "Start without debugging" from right-click menu on the editor

**Comment by zooba** [comment]
What version of PTVS are you using? Do you have a project open or just a single file (or is it part of another type of project, like a C++ project)? What version of Python do you have?

**Comment by nidleo** [comment]
PTVS 2.2 on visual studio 2013. It's a python project with a single file open in editor.
Python version: WinPython 2.7.9.5 64 bit

**Comment by int19h** [comment]
Pretty sure that's yet another `PYTHONPATH` related bug with custom interpreters.

@nidleo, can you go into environment configuration for WinPython, and put `PYTHONPATH` as the name of the path environment variable there, and see if that fixes the problem?

**Comment by nidleo** [comment]
Not sure I know how to do that. As far as I know the only env var related configuration is through winpython.ini file which looks like this:

[debug]
state = disabled

[environment]
## <?> Uncomment lines to override environment variables
#PATH = 
#PYTHONPATH = 
#PYTHONSTARTUP = 


Could you provide further instructions?

**Comment by int19h** [comment]
It should be in the same place where you've originally added it (Tools -> Options -> Python Tools -> Environment Options). Select WinPython in the "Show settings for" combo box, and then edit the Path Environment Variable textbox to "PYTHONPATH".

![image](https://cloud.githubusercontent.com/assets/1175142/7716706/b25d688a-fe4a-11e4-9bb7-de53c18b5764.png)

**Comment by nidleo** [comment]
Thanks! It worked.
I see that "without debugging" things run faster.

I wonder what the speed up could be. Is there a per-line overhead in debug mode?

**Comment by zooba** [comment]
Yep. When debugging is enabled, Python calls a separate function for each line. We try to keep the overhead as small as possible, but we do still need to check for exceptions and breakpoints, and the call itself is pretty significant.

There are some longer term plans to do things to reduce this overhead, at least for some users, but we've been prioritizing other issues for this release.
