### ISSUE TITLE
Analyze .pyc files

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#219]
Rather than ignoring .pyc files, we could analyze them by loading them into Python and using the built-in introspection tools.

As this will result in code execution where it is not common to avoid it (compare to .pyd, where simply importing the module rarely does anything other than setting up definitions and almost never have other dependencies), we probably need to make this an opt-in setting.

**Comment by zooba** [comment]
(See #215 for an example)

**Comment by huguesv** [comment]
We have a new language service starting in the 15.6 release. If you still see this problem, please open a new issue.
