### ISSUE TITLE
Beta VS for Mac

### ISSUE THREAD

**Issue by FuzzyCCIE** [Microsoft/PTVS#2192]
Guys,

I know its Beta and I know its a new productbut is there a way to install PTVS into the Mac Version of Visual Studio

Cheers

Andy

**Comment by zooba** [comment]
Unfortunately not.

Despite the naming, Visual Studio and Visual Studio for Mac are essentially different products, so we would have to reimplement most of PTVS. But we know the team behind the Mac version is keen to have Python support, so if you want to send some encouragement their way (through their [UserVoice site](https://visualstudio.uservoice.com/forums/563332-visual-studio-for-mac)) it will help make it happen.
