### ISSUE TITLE
error installing python tool in vs version 2.2.6

### ISSUE THREAD

**Issue by epiqueadmin** [Microsoft/PTVS#2195]
That a look at that screenshot plz.

![vspython](https://cloud.githubusercontent.com/assets/11728993/23285819/710cb458-fa01-11e6-9bf8-c8445b80b952.jpg)

**Comment by huguesv** [comment]
It's probably the same as https://github.com/Microsoft/PTVS/issues/2124

Try closing VS, deleting the contents of your %LocalAppData%\Microsoft\VisualStudio\14.0\ComponentModelCache and then restart VS.
