### ISSUE TITLE
sklearn deprecation triggered by ML samples

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2197]
Our ML samples trigger the following warning from scikit-learn (as of Anaconda 4.3.0):

> C:\Program Files\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
>   "This module will be removed in 0.20.", DeprecationWarning)

**Comment by huguesv** [comment]
Changing
```
from sklearn.cross_validation import train_test_split
```
to
```
from sklearn.model_selection import train_test_split
```
appears to work fine, without warnings.

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/49290/module-deprecation-warning-in-python-regression-ml.html

**Comment by rebeen** [comment]
I have the same problem , please could you tell me how to solve it I tried many ways

**Comment by huguesv** [comment]
Try changing the import as mentioned above.

**Comment by rebeen** [comment]
Thank you that works for me

**Comment by rebeen** [comment]
@huguesv please can I talk to you in private (email...) I have a problem in my code
