### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by clairegeek05** [Microsoft/PTVS#2213]
I'm trying to bring in a new module/library that is located in another folder on my computer. I cannot copy the files to the working project directory. 

This new folder contains a few .pyc files, of which I need to import one of the .pyc files in my code, and then be able to use functions within this file.

Can PTVS add this new module/library? 

Currently I'm getting a 'Import Error' and 'No Source Available'. When I try to add this to the projects 'Search Path' the program crashes.

**Comment by zooba** [comment]
Could you open Tools, Python Tools, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

Adding the directory to Search Paths is likely the correct solution here, but we should not be crashing. Are there other files besides the .pyc files in that directory?

**Comment by clairegeek05** [comment]
I noticed that when I run my code without debugging, the library is pulled and accessed as expected.
However, when I'm debugging my code is when I get the Import Errors. First, there is a pop-up window to search for the file name, but it's looking for a .py file, and the files I'm trying to access are .pyc.

Yes, there are other files in the folder, various types too.

**Comment by zooba** [comment]
That sounds right. The dialog is trying to show you the source code for the file you are debugging, so if you don't have the source code, just hit Cancel and you should be able to step through or out of the function (or just hit F5 to keep running).

**Comment by clairegeek05** [comment]
When I'm in debug mode and hit cancel, it brings up the screen for 'No Source Available'. I can't continue on debugging either.

**Comment by huguesv** [comment]
We have a new debug engine in the 15.8 release, if you still see this problem, please open an issue at https://github.com/Microsoft/ptvsd
