### ISSUE TITLE
Detect non-virtual environments from Add virtual env dialog

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2216]
If you go through the Add virtual env dialog and select a non-virtual environment, we will refuse to add it - the correct path is to add a custom global environment through the Python Environments window. However, we don't make this at all obvious.

Similarly, if you go to Add/Remove Environments then we don't help you add a custom one (there's a link to go online and install one, but that's it).

In both of these dialogs, we should have a way to redirect users to the Python Environments window and get them into the Add Custom Environment view.

**Comment by huguesv** [comment]
Add existing virtual env and add existing custom env are now both done in the same UI.
