### ISSUE TITLE
SyntaxError: multiple statements found while compiling a single statement

### ISSUE THREAD

**Issue by chanansh** [Microsoft/PTVS#222]
I get this error when I try to send or copy-paste lines of code to the interactive window after changing it to be iPython.

**Comment by zooba** [comment]
Do you have IPython installed? What version? And which version of PTVS are you using? (We made some recent fixes to this behaviour)

I think this could probably happen if you have changed the mode to IPython but then it falls back on the regular mode.

**Comment by chanansh** [comment]
I am using latest Anaconda (3.4)

**Comment by zooba** [comment]
Do we display any warning when you start like `Using standard backend instead`?
