### ISSUE TITLE
Always notices "completion db is not up to date"

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/PTVS#223]
I'm using VS2013 community and latest Anaconda python 2.7 64-bit. The autocomplete list shows that *The completion DB needs to be refreshed*, and I open Python Environment pane and click Refresh DB to do it. The refreshing runs for a while and seems to end in the middle of the whole progress. But the notification does not go away: the notify button always shows that *Completion DB is not up to date. Click to start refreshing.* I tried several times but each time it is the same.

**Comment by zooba** [comment]
Can you try with the latest version of PTVS (from the Releases tab on our front page)? We fixed a bug in our code analyzer recently that was being triggered by a package in the latest Anaconda.

**Comment by renkun-ken** [comment]
The latest version works! Thanks!

**Comment by Gonzalo2683** [comment]
Hello, i have the same problem, but with visual studio community 2017RC, i have a virtual env, and when i click in refresh DB, is the same of renkun-ken say. You know some solution for this? thanks.

**Comment by aljohn0422** [comment]
I have the same problem with VS 2017RC!

**Comment by zooba** [comment]
See #1883 to see if it's the same problem. If so, we have a fix coming soon, otherwise, please open a new issue and attach the output of Tools, Python Tools, Diagnostic Info.
