### ISSUE TITLE
PTVS is gone in VS 2017 Enterprise

### ISSUE THREAD

**Issue by donamk** [Microsoft/PTVS#2244]
Hello,

I was using PTVS in VS 2017 RC Enterprise( sorry, I don't know which RC version)

After I have updated from VS 2017 RC to VS 2017 RTM (Version 15.0.26228.4 D15RTWSVC), I could not find PTVS at all (there is not python project)

In the installer, I could not find PTVS.

How can I get PTVS back?

**Comment by zooba** [comment]
Right now, the Python development workload (our fancy new name for PTVS) is only available in the preview of VS 2017. See [our blog post](http://blogs.msdn.microsoft.com/pythonengineering/2017/03/07/python-support-in-vs2017/) for more information.

**Comment by donamk** [comment]
@zooba Thank  you so much for a quick reply. I can wait a few months
