### ISSUE TITLE
Why the vs2017 community edition publiced in 7 Mar,2017 have no python?

### ISSUE THREAD

**Issue by muguangyuze** [Microsoft/PTVS#2248]

**Comment by holmboe** [comment]
The blog post at https://blogs.msdn.microsoft.com/pythonengineering/2017/02/22/python-in-vs2017/ explains it.

**Comment by rosch100** [comment]
There is a VS2017 Python preview available at:
[https://www.visualstudio.com/de/vs/preview/](url)

**Comment by kdriedger-simutech** [comment]
My project starts to load and crashes Visual Studio 2017 Preview.  How do I get started debugging this problem?  Putting a /log on the devenv.exe produces an ActivityLog.xml.  This log does not seem to give me a hint on why VS is crashing.   In the wiki, I see instructions on building but I don't see how I attach a debugger to the devenv.exe instance and start stepping through the code.

**Comment by zooba** [comment]
@kdriedger-simutech Please open a new issue for this, and include the text from Tools, Python, Diagnostic Info as an attachment.

**Comment by zooba** [comment]
I'm leaving this issue open (so people find it more easily) but locked for the time being. The links above are the answer to the question.
