### ISSUE TITLE
When trying to install pip package from VS 2017, Python Tools for VS runs into expected error

### ISSUE THREAD

**Issue by mrlarson2007** [Microsoft/PTVS#2251]
Python Tools for Visual Studio 2017 crashes when I try to install pytest into the active python environment my python project is using. Here is the detailed information from the error dialog I got when trying to do it:

[Window Title]
Visual Studio - Python support

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
System.InvalidOperationException: Operation cannot be started because the environment is not configured.
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<AbortIfNotReady>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.<InstallPackage>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipExtension.<InstallPackage_Executed>d__14.MoveNext()
```

**Comment by zooba** [comment]
Thanks for the info!

This looks like there's something not configured properly about your environment - could you collect the output from Tools, Python, Diagnostic Info _while your project is loaded_ and either attach it here or email to ptvshelp@microsoft.com? That will help us see what setting we are failing on.

**Comment by suoranta** [comment]
I also came across this issue a week ago and e-mailed the diagnostic info. Is there anything new to this?

**Comment by zooba** [comment]
@suoranta I found your email (we were mostly out of the office last week at PyCon). It looks like you're using IronPython, which has a range of problems with pip, but it's likely you're hitting the one that we have recently fixed where pip is not installed but we do not show the button to install it.

I'd strongly recommend switching to CPython or Anaconda if you want to use the Python ecosystem - IronPython is great for .NET integration but very limited outside of that. If you choose to continue with IronPython, you'll have to install pip manually (e.g. `ipy.exe -m ensurepip` run with admin privileges should do it).

**Comment by suoranta** [comment]
My primary aim is to have interactive environment for utilizing developed with static/compiled .NET languages, so I would switch to F# Interactive rather than CPython.

`Ipy.exe -X:Frames -m ensurepip` confirms that pip is already installed and `pip show pip` indicates version 9.0.1 and location c:\program files\anaconda3\lib\site-packages (I installed Anaconda with VS 2017). I'm not very familiar with pip, but it appears I am unable to control which Python environment pip should modify. If I run `ipy -X:Frames -m pip install [package]` with IronPython interpreter, pip either tells that package is already installed (if Anaconda has it) or fails with unhandled exception 

> File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 4715, in <module>
> IndexError: index out of range: -1

So this goes really beyond PTVS.

**Comment by zooba** [comment]
> So this goes really beyond PTVS.

Yes, I'm afraid it does. Both the IronPython project and the pip project are keen for contributions, and I think both need work to fix this situation.

However, if F# is a suitable alternative then why do you need pip? You can use nuget.exe from the command line (they haven't enabled support for Python projects in VS) to get .NET packages and reference them from IronPython relatively easily via `sys.path` (or search paths in VS projects).

**Comment by suoranta** [comment]
Need to reference .NET libraries is a hard constraint, but there are secondary objectives that made me consider IronPython. IronPython combined with popular Python packages would have offered advantage over F# in, e.g., interactive plotting functionality. Python is more popular and perhaps easier to adopt than F# for the other users. So I will use F# interactive for now but see continued case for adopting IronPython if it gains ground and support in VS is improved.

**Comment by zooba** [comment]
Closing this as an IronPython limitation, and not something we can reasonably fix ourselves.
