### ISSUE TITLE
Define multiple run configurations

### ISSUE THREAD

**Issue by avik-taranis** [Microsoft/PTVS#2252]
Is it possible to define multiple debug configurations in PTVS? I know that one configuration can be defined here:
![image](https://cloud.githubusercontent.com/assets/18595338/23757495/ae94cf92-04ef-11e7-8e0c-995d2616fccc.png)

But is it possible to define more than one configuration? for example, pycharm allows to define multiple configurations.

**Comment by zooba** [comment]
Right now we don't support that. Issue #86 is where we are tracking the work, but it hasn't risen high enough on our priority list compared to other items to be completed yet. (And in a slightly perverse twist, the longer we wait for this the easier it is going to be - the underlying platform support keeps changing, so if we'd done this 5 years ago we'd be using very old complicated APIs, but it's nearly at a point where this is going to be trivial to do.)
