### ISSUE TITLE
Opening a python Solution in VS 2017 Preview crashes VS

### ISSUE THREAD

**Issue by kdriedger-simutech** [Microsoft/PTVS#2256]
When loading my solution, VS 2017 preview crashes. 

Perhaps something to do with ReferencedProjectBuildOutputs:
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32, IntPtr)
   at Microsoft.VisualStudioTools.Project.ProjectReferenceNode.get_ReferencedProjectBuildOutputs()
...

In this context does a reference project refer to one .pyproj referring to another .pyproj or could it be a reference to an imported python library?

[PTVS - Diagnostic Info 2017-03-09T130600.txt](https://github.com/Microsoft/PTVS/files/831916/PTVS.-.Diagnostic.Info.2017-03-09T130600.txt)

**Comment by zooba** [comment]
This is the same as issue #2200, which I thought I fixed before release, but now see that we didn't quite make it. There should be an update sometime next week with a fix for this - you'll get a notification when it becomes available.

Thanks!
