### ISSUE TITLE
IPython REPL Pandas issues

### ISSUE THREAD

**Issue by smortaz** [Microsoft/PTVS#226]
whenever you get an error in the REPL / IPython when using pandas, there is a long pause, line numbers spin, then finally you get some error spewed.  the pause and the weird error display makes the experience extremely unpleasant.  

VS 2013, Pandas, IPython 2.x (probably on 3.0 as well).

also, see this bug from a regular user:

http://pytools.codeplex.com/workitem/2797

**Comment by zooba** [comment]
Fixed in VS 2013.

For VS 2015 we need to do the span calculations ourselves when writing text with coloured escapes to the REPL.

**Comment by zooba** [comment]
Moved to interactive-window repo.
