### ISSUE TITLE
Error: Object reference not set to an instence of object

### ISSUE THREAD

**Issue by user-na** [Microsoft/PTVS#2263]
My configuration:
VS 2013 Version 12.0.30501.0 - installed via a company installer
Anaconda 4.2.0 Python 2.7 64bit
PTVS 2.2.2 VS 2013

VS2013 and Python were already installed and are working fine. I just installed PTVS and created a new Python Application.
When I now press start, I get an error Box from VS showing the error "Object reference not set to an instence of object".
From the A quick overview I would have expected that I get a dialog to select the interpreter.
Any help would be very appeciated.

**Comment by user-na** [comment]
Here is a screenshot of the Options Dialog on VS.
![options](https://cloud.githubusercontent.com/assets/19994053/23789551/a00774b6-057b-11e7-91b7-1cd5e08b7657.png)

**Comment by zooba** [comment]
It looks like your install may have been corrupted. Can you try deleting the contents of `C:\Users\you\AppData\Local\Microsoft\VisualStudio\12.0\ComponentModelCache` and restarting VS? Hopefully that will fix it.
