### ISSUE TITLE
How can I install packages?

### ISSUE THREAD

**Issue by jenokizm** [Microsoft/PTVS#2272]
I need to set it permissible pystun. (https://pypi.python.org/pypi/pystun) But there is an error. How to fix it?
output (install type = pip):

> Installing 'pystun'
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_module_details
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\__init__.py", line 13, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\exceptions.py", line 6, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\six.py", line 701, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\six.py", line 692, in exec_
AttributeError: 'module' object has no attribute '_getframe'
'pystun' failed to install. Exit code: 1

or output (install type = easy_install):

> Installing 'pystun'
Searching for pystun
Reading https://pypi.python.org/simple/pystun/
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/pystun/: too many values to unpack -- Some packages may not be found!
Couldn't find index page for 'pystun' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: too many values to unpack -- Some packages may not be found!
No local packages or download links found for pystun
error: Could not find suitable distribution for Requirement.parse('pystun') (--always-copy skips system and development eggs)
'pystun' failed to install. Exit code: 1

**Comment by huguesv** [comment]
Please have a look at https://github.com/Microsoft/PTVS/issues/1720

**Comment by jenokizm** [comment]
ok thanks. i now run cmd command:
`ipy -X:Frames -m pip install pystun`
but i have error output:

> Collecting pystun
C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\pac
kages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made,
 but the SNI (Subject Name Indication) extension to TLS is not available on this
 platform. This may cause the server to present an incorrect TLS certificate, wh
ich can cause validation failures. For more information, see https://urllib3.rea
dthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\pac
kages\urllib3\connection.py:1: SubjectAltNameWarning: Certificate for pypi.pytho
n.org has no `subjectAltName`, falling back to check for a `commonName` for now.
 This feature is being removed by major browsers and deprecated by RFC 2818. (Se
e https://github.com/shazow/urllib3/issues/497 for details.)
  from __future__ import absolute_import
Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\basecommand.
py", line 209, in main
    status = self.run(options, args)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\commands\ins
tall.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\req\req_set.
py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files (x86)\IronPython 2.7\Lib\contextlib.py", line 35, in __
exit__
    self.gen.throw(type, value, traceback)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\utils\loggin
g.py", line 36, in indent_log
    yield
ValueError: too many values to unpack

**Comment by zooba** [comment]
At this stage, you really ought to report this to the `pip` or IronPython teams, as it is outside of our ability to fix.

If you simply want to use `pystun`, then you could consider installing Python 2.7 from [python.org](https://python.org) instead of using IronPython. Unless you are integrating it with a larger application that must use IronPython, you will generally find libraries work better with CPython.

**Comment by jenokizm** [comment]
I use IronPython only because it can make the interface of the window on WPF or WF. ok well then I'll write to other repositories.

**Comment by int19h** [comment]
[pythonnet](http://pythonnet.github.io/) is another option if you specifically need Windows Forms. Unlike IronPython, it's a Python/.NET interop bridge that runs on top of stock Python interpreter.

If you just need good-looking UI, consider [PySide](https://wiki.qt.io/PySide).
