### ISSUE TITLE
ImportError: No module named mpl_toolkits.mplot3d

### ISSUE THREAD

**Issue by atursunov** [Microsoft/PTVS#2273]
Hi there,

When I try to load mpl_toolkits.mplot3d it gives following error:

from mpl_toolkits.mplot3d import Axes3D
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mpl_toolkits.mplot3d

I have VS 2010, PTVS 2.1, Python 2.7 and Anaconda2 4.0.0. In IPython and Spyder code is working. How can I import this library into VS environment.

Thanks,
Aziz.

**Comment by huguesv** [comment]
It's likely that you are running using the wrong python environment.

I don't recall if PTVS 2.1 was able to auto-detect Anaconda or not.  Under Tools/Options/Python Tools there should be a page that lists all configured environments.  If Anaconda isn't detected, you'll need to configure it manually.  You can also select which one is the global default environment.

A project can use any of the globally configured environments, if none are selected then the global default is used.  That selection is done in solution explorer, under Python environments node, or via the project settings, general page.
