### ISSUE TITLE
No PTVS in VS 2017 anymore?

### ISSUE THREAD

**Issue by adabo** [Microsoft/PTVS#2275]
I just installed Visual Studio 2017 and can't find anything related to this project. I searched the online extensions. Searched the VS Community installer. Nothing about Python development.

I'm not sure, but I think VS 2017 is no longer "Preview". Is that the problem?

**Comment by huguesv** [comment]
Hi abado.  Please have a look at the links at the top of our readme:
https://github.com/Microsoft/PTVS/blob/master/README.md

You can still get Python support in VS 2017, but it's only in the early adopter preview builds right now.

**Comment by adabo** [comment]
Ok. I understand now. I think I downloaded the wrong version of 2017. Maybe the final build or something. I uninstalled it and found a preview build and it has the PTVS in it. Thank you very much.

**Comment by zooba** [comment]
Just to be clear, the VS 2017 Preview is exactly what's in the final build, _plus_ some newer stuff. It isn't an older preview - it's a preview of the _next_ update to VS.

**Comment by yefengzkk** [comment]
can i use ptvs in vs2017 community by extensions?

**Comment by tr00st** [comment]
@yefengzkk VS 2017 preview is available from here: https://www.visualstudio.com/vs/preview/

**Comment by costa974** [comment]
what a mess

**Comment by dave750** [comment]
Is there a why to this?  I'm not mad, it just has always worked so well for me in the past that I am a little perplexed.

**Comment by zooba** [comment]
@dave750 See the blog post we linked from the front page - http://blogs.msdn.microsoft.com/pythonengineering/2017/03/07/python-support-in-vs2017/
