### ISSUE TITLE
Ghost files in "Solution Explorer" 

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#2276]
I don't know exactly how I get that, removing files and moving them from a File Explorer and going back to ptvs created at some point a "ghost" empty line:
![image](https://cloud.githubusercontent.com/assets/1050156/23870897/5ce415f6-07e5-11e7-89be-dca089b67807.png)

The file list is accurate, with what I have on disk, but it looks like old files were removed, but keep use space in Solution Explorer.
Nothing crashes, double-click or right click does nothing, but it's unexpected.  Restart of VS solves this, so it's a minor issue but I thought it was worth mentioning it anyway.

PTVS 2.2.50113.00

**Comment by zooba** [comment]
Wow, interesting.

But since it doesn't break anything, unless we can also see it in VS 2017 it won't ever get fixed at this stage.
