### ISSUE TITLE
Tkinter problems

### ISSUE THREAD

**Issue by alekcanddrr** [Microsoft/PTVS#2283]
Hello, updated Python Tools. 
While debugging, Tkinter does not show its windows now.
How can i fix it?
Re-installing previous versions of Pyhton Tools does not help too

**Comment by zooba** [comment]
Honestly, it's very unlikely that anything on our side is affecting Tkinter.

Have you updated Python itself recently? What version are you using?

**Comment by alekcanddrr** [comment]
No, i havn't updated Python recently
Using 2.7.13 Python and VS 2015

**Comment by alekcanddrr** [comment]
Problem solved by re-installing Python
Sorry for disturbness
