### ISSUE TITLE
Pandas library is not recognized when imported

### ISSUE THREAD

**Issue by omarkahwaji** [Microsoft/PTVS#2284]
I am trying to use Python for machine learning on visual studio 2017 preview. when i import pandas library, compiler complains that pandas is not installed, i double checked and found out Pandas is installed. 
Has anybody run into this issue? 

Thanks, 
Omar

**Comment by zooba** [comment]
This is expected while your completion DB is regenerating, which may take a while. Once that's complete, the warning should go away.
