### ISSUE TITLE
Refactor Rename doesn't work in all cases

### ISSUE THREAD

**Issue by jenstMS** [Microsoft/PTVS#2287]
I was trying to refactor my code to comply with Python style guide, an refactor-rename (F2) works only partially

e.g. in the line below, I cannot F2 "stateMachineStatsFile". Snapshot with error below (sorry if TMI)
`with open(state_machine_stats_file_name, 'w+') as stateMachineStatsFile:`

![image](https://cloud.githubusercontent.com/assets/26393182/23964176/d8368a40-0970-11e7-9c73-ce520dacc0da.png)

Doesn't work on method definitions either:
`def GetSessionData(inputFileName):`

![image](https://cloud.githubusercontent.com/assets/26393182/23964460/d7956678-0971-11e7-9175-e81668be261c.png)

**Comment by zooba** [comment]
Thanks. I've been working on some changes here already that may fix this, but I'll double check.

**Comment by Sleeptime17** [comment]
So did the changes fix it?

**Comment by zooba** [comment]
Yes, at least for the two examples here. If you know of other problems in this area, let me know and I'll check with the latest sources.
