### ISSUE TITLE
Django Management Console error

### ISSUE THREAD

**Issue by LovingJava** [Microsoft/PTVS#2305]
I am new to Django and also new to PTVS.
I am having a lot of difficulty using Django Magement Console.
It appears that it takes a while to get refreshed (to database) and I am not getting the objects appear automatically as I expected using Intellisense.
I typed in following:

Starting Django 1.10.6 shell
>>> from app.models import Artist

and getting this error:
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

I am not sure what I should do to get it working.

Thanks in advance.

**Comment by huguesv** [comment]
Thanks for letting us know. I'm able to repro on latest PTVS build.  Works fine in an external command prompt `python manage.py shell` but not in PTVS.

We'll let you know if there's a workaround.

**Comment by zooba** [comment]
Maybe we aren't setting the environment variables correctly? I just ran a Django shell and don't see the `DJANGO_SETTINGS_MODULE` variable.

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/27272/django-shell-1106-fail-to-import-model-in-visualst.html

**Comment by huguesv** [comment]
I had noticed that when I tried to repro and I tried to set the environment variable before importing models module, but that just led to a different error (which I can't find, I probably forgot to save it).

**Comment by zooba** [comment]
Here is the easiest workaround I could find:

Add this code to your settings.py:
```python
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "<settings.py module name goes here>")
```

Then make the first thing you run in the management console `django.setup()`. This will ensure your settings have taken effect, since we missed the first opportunity.

As for the underlying bug, the environment should be set correctly, but we appear to not be flowing it through from custom commands any more.
