### ISSUE TITLE
Import coverage file... menu item under Tools/Python

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2314]
I found the French translation to be ambiguous, and it turns out it's because our original English version is also a bit ambiguous.

To be consistent with other parts of VS (see Test main menu), we should refer to it as "code coverage" instead of just "coverage".  

The file filter in that command's open file dialog should also be updated from `Coverage XML (*.xml)` to `Code Coverage XML (*.xml)`.

FYI the current French translation for the menu item is "Importer le fichier de couverture..." and it should be changed to "Importer le fichier de couverture du code..."

**Comment by zooba** [comment]
I think it's specifically a coverage.py XML file, so perhaps we should call it that and not localize the name?

**Comment by huguesv** [comment]
Yeah that could work.
