### ISSUE TITLE
Looking forward to python tools for VS 2017 RTM

### ISSUE THREAD

**Issue by cpoyraz** [Microsoft/PTVS#2331]
Hello,
No need to say a word. I think a lot of people is waiting for its new version. Please hurry :)

**Comment by zooba** [comment]
Glad to hear it!

If you don't want to wait any longer, you can grab [VS 2017 Preview](https://visualstudio.com/vs/preview) and start using it now (this is all of VS 2017 RTM plus some previews of upcoming updates).

**Comment by seanmcne** [comment]
@zooba - what @cpoyraz probably meant was he can't wait until this codebase produces an installer that works for VS 2017.  How can we install the python tools for VS 2017?

**Comment by seanmcne** [comment]
Arrg, ok so after some searching now I get it.  The python tools and others weren't ready for prime time quite yet (or some dependency) so the only way to get the python tools in VS2017 is by using this newer "Preview" version of VS2017: https://blogs.msdn.microsoft.com/pythonengineering/2017/03/07/python-support-in-vs2017/
