### ISSUE TITLE
Feature request: Pylint usability improvements

### ISSUE THREAD

**Issue by vyktor90** [microsoft/PTVS#2332]
It would be useful to be execute pylint only for one (current) file (and bind a keyboard shortcut to it).

Also it would be nice to have error messages in error window (messages in messages) and not everything crammed into warnings.

**Comment by huguesv** [comment]
Thanks for the suggestions!

**Comment by HHest** [comment]
Would love this feature also! 

In the meanwhile, you could add a new "External Tools" in the Tools menu:

Title: PyLint
Command: C:\Python27\Scripts\pylint.exe (or whatever you use)
Arguments: --output-format=msvs $(ItemDir)$(ItemFileName)$(ItemExt)
Initial directory: $(ProjectDir)
Use Output windows: checked

Regards

**Comment by michaelosthege** [comment]
Maybe it is possible to integrate with the existing Visual Studio features for code styles?
