### ISSUE TITLE
Can the debugger halt for unhandled exceptions

### ISSUE THREAD

**Issue by mkimberling** [Microsoft/PTVS#2333]
When a bug in my Python program results in an unhandled exception, I want Visual Studio to do the same thing it does when I'm debugging a C++ program: stop at the location of the problem.  It seems like this behavior/feature is not present in PTVS.  Is that right or did I miss something?  

I realize there is Exception Settings in Debug=>Windows but that doesn't distinguish between handled and unhandled exceptions.  Handled exceptions represents the parts of my program that function correctly and I have no interest in the debugger stopping each time one happens.

I'm running PTVS 2.2.50113.00

Thanks!

**Comment by zooba** [comment]
The debugger should be breaking automatically for most exceptions if you don't have a handler (this was actually the first feature I wrote as an intern :) ).

If you don't see any distinction between exception handling types, you may have disabled Just My Code (through Debug, Options). This disables the feature entirely.

Also, there are some common exceptions where we don't detect that they are handled well, such as AttributeError. To break on these, you'll need to enable them.

Does that help at all?

**Comment by mkimberling** [comment]
Hi Zooba,

Thank you! That was indeed the problem.  I had no idea that this checkbox existed or that it would have any affect on Python.  Visual Studio now halts as expected at the location of an unhandled exception.  This checkbox was not checked for me or any of my coworkers desks.

I would add as a suggestion that this extremely important checkbox could be advertised better.  I never would have guessed that it had anything to do with Python.

Thanks!
