### ISSUE TITLE
Django Template Language Breaks Highlighting/Intellisense for Javascript Blocks

### ISSUE THREAD

**Issue by delizin** [Microsoft/PTVS#2340]
If` you insert any Django Template Language tags such as {{csrf_token}} or {% comment %} within a script block inside an html page, all of the javascript highlighting and intellisense will be removed from everything within that block and it will only highlight and provide intellisense for the DTL tag. Other javascript blocks will be unaffected.

Example:
```
<script type="text/javascript">
    var a = "foo";
</script>
```

vs 

```
<script type="text/javascript">
    var a = "{{ bar }}";
</script>
```

If this is in fact a bug, it was also present in VS2013 with Pytools installed.

**Comment by huguesv** [comment]
Thanks! We already have a bug for this, so I'll close this as a duplicate.
https://github.com/Microsoft/PTVS/issues/1098
