### ISSUE TITLE
venv can not work on another PC after git version control

### ISSUE THREAD

**Issue by Huqin-China** [Microsoft/PTVS#2343]
i start a new project use ptvs,and use venv  as env.
i upload it to some git website,and then download it on another PC,
although this project can work and build success,but vs can't activate the env-xmate as defualt env,and also can't manage package through env-xmate.
i tried to keep two machine's python install on the same path,didn't solve this.
Here is my code
[https://git.oschina.net/HuQin/XMate.git](url)

**Comment by zooba** [comment]
Interesting, that all looks like it should be okay.

Can you post some screenshots of the second PC showing how it looks? Specifically in Solution Explorer (with the Python Environments item expanded) and in the Python Environments window.

**Comment by Huqin-China** [comment]
![Uploading image.png…]()

Can't list and manage packages through env on the new PC

**Comment by huguesv** [comment]
Does the virtual environment work when used from command line on the new PC?
`python -m pip list --format=json` is what we use internally, we fall back to `python -m pip list` if that fails.
