### ISSUE TITLE
Python Tools for VS 2015 - Goodbye to Windows Phone App Development

### ISSUE THREAD

**Issue by TheRealFeleo** [Microsoft/PTVS#2345]
Installed Pythontools in VS 2015 prof from the template menu. Everything worked really fine, it even finds different installed python versions and connects them with the ide. Some hours later I tried to continue developing my Windows Phone Application - s h o c k   it doesn't open anymore! With the hint "User input required - install an update by clicking right on project" the whole thing remains closed.

I urgently need to finalize this app, so: has anyone already had this problem? Right clicking on project has no result, there is no possibility to update something.

Thank you.

Kind regards

**Comment by zooba** [comment]
We have occasionally seen issues in the installer that when you go through it (for any reason, but in this case probably to update Python Tools) it sometimes uninstalls things.

I suggest going back to the VS installer through Programs and Features, Microsoft Visual Studio 2015, Modify, and make sure that the options you expect are selected. If they are, go back and choose Repair, which should restore any files that are missing.

**Comment by TheRealFeleo** [comment]
Thank you very much, Mr. Dower, everything works fine again. And I even can use the pythontools, which are very comfortable! Now my Phone-Project will in time get ready!

 

Kind regards

 

Von: Steve Dower [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. März 2017 21:11
An: Microsoft/PTVS
Cc: TheRealFeleo; Author
Betreff: Re: [Microsoft/PTVS] Python Tools for VS 2015 - Goodbye to Windows Phone App Development (#2345)

 

We have occasionally seen issues in the installer that when you go through it (for any reason, but in this case probably to update Python Tools) it sometimes uninstalls things.

I suggest going back to the VS installer through Programs and Features, Microsoft Visual Studio 2015, Modify, and make sure that the options you expect are selected. If they are, go back and choose Repair, which should restore any files that are missing.

**Comment by huguesv** [comment]
Glad to hear it's working.
