### ISSUE TITLE
Parse docstrings for class attributes

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#235]
PTVS gives documentation in the tooltip for class properties, but not for class attributes (aka fields aka members).

According to Sphynx docs, it can parse the documentation in the following format, and PTVS should do the same.
http://sphinx-doc.org/ext/autodoc.html

Quoted from the above link:

This means that in the following class definition, all attributes can be autodocumented:

```
class Foo:
    """Docstring for class Foo."""

    #: Doc comment for class attribute Foo.bar.
    #: It can have multiple lines.
    bar = 1

    flox = 1.5   #: Doc comment for Foo.flox. One line only.

    baz = 2
    """Docstring for class attribute Foo.baz."""

    def __init__(self):
        #: Doc comment for instance attribute qux.
        self.qux = 3

        self.spam = 4
        """Docstring for instance attribute spam."""
```

**Comment by zooba** [comment]
Only tricky part here is that we don't currently have anywhere in our code model to put the docstrings. The ones for classes/functions have a value to be attached to, but these need to be attached to a name in a scope (and probably shared across multiple scopes, though it may just be the one), which will make retrieving them difficult.

**Comment by huguesv** [comment]
We have a new language service starting in the 15.6 release. If you still see this problem, please open a new issue.
