### ISSUE TITLE
[3dsmax][Maya] Intellisense works for a moment, then all modules become <unknown type>

### ISSUE THREAD

**Issue by sonictk** [Microsoft/PTVS#236]
Hi all:

I'm trying to get 3ds max 2015 working with Intellisense in PTVS. I have VS 2013 installed.

I configured the python interpreter to use the same paths that I do in PyCharm, and set the project search paths the same way, along with also setting the project references to a _MaxPlus.pyd file as well. When I first open my python project using the default Python interpreter and then open my 3ds max project, initially I am able to actually get intellisense working for the MaxPlus module and other built-in modules such as sys, os etc, and able to even get auto-completions working. **However, after a few seconds, suddenly all auto-completions will stop, and I will get the _No completions_ dialog, along with everything, even builtins such as sys and os showing _unknown type_.**

Clearly, things are working before something happens in the background that breaks everything related to Intellisense, so could anyone point me as to how I might resolve/narrow down what's causing this issue? I have tried refreshing the db as well, but that has not helped.

How I have my Python Project set up:
http://i.imgur.com/hokUFi2.png

How I have the 3ds max python interpreter configured:
http://i.imgur.com/HySEXjs.png

I should point out here that I have used the same paths and .pyd file to get 3ds max auto-completion working in both PyCharm and Wing IDE flawlessly; this is my first time trying to use PTVS with 3ds max however, so if anyone spots me doing something incorrect in the setup here, I'd appreciate some pointers.

UPDATE: I attempted the workaround as detailed here: https://pytools.codeplex.com/workitem/3005 by setting `HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\12.0\PythonTools\Options\Advanced@CrossModuleAnalysisLimit` to 10000. I also tried installing the latest development release of PTVS. The odd thing is that sometimes I do get intellisense working on certain modules such as MaxPlus, sometimes not. Additionally, I have issues with modules that say they have been indexed in the database such as PySide, but when I do an import statement such as `import PySide`, they show themselves as _unknown type_ again as well. Builtins such as sys, os, ctypes etc. seem to work now though.

The last thing is that I tried adding one of my current production 3ds max projects to PTVS, but for some reason, even though the PYTHONPATH and search paths are set up exactly the same way as I have them in PyCharm, my modules seem to be incorrectly trying to reference a folder level that they shouldn't be when determining the module root folder, and this is using a virtualenv as well.

A screenshot of that project and its search paths is as shown here:
http://i.imgur.com/9QReX5i.png

I'm expecting to be able to do a `import stkToolkit_3dsmax` and have the module have Intellisense on it, but somehow it seems to be taking `scripts` (the solution's parent folder) as the top-level module for some reason. 

Anyone got any idea on what might be causing this issue, I'd love to have your input (on top of the general slowdown in PTVS, such as almost-hanging when right clicking on items in my solution explorer as well)

Thanks!

**Comment by zooba** [comment]
Adding lots of items to Search Paths like that can certainly cause problems. Right now we have some tricks to keep memory use manageable for full Python installations, but search paths will bypass that.

I'd suggest creating a custom environment. See [this page](https://github.com/Microsoft/PTVS/wiki/Python-Environments#global-environments) on our wiki, and note that the UI has changed for 2.2 so it may look different (if you see `+ Custom...` in your Python Environments window, click that). For this, you'll want to use Autodesk's Python folder for the interpreter and library, and then you can remove those from your search path.

Once you have that set up, if you've created a virtualenv from Autodesk's Python (that is, its orig-prefix.txt or pyvenv.cfg points to Autodesk's Python), then you should be able to right-click Python Environments in Solution Explorer and add an existing virtual environment. This (probably) won't work until you've added the custom environment above.

(We really do need to write up some walkthrough pages on setting up PTVS with various applications... no writers on our team right now, unfortunately.)

**Comment by int19h** [comment]
Judging by the second link in the issue, this is already a custom environment (but this then invites the question as to why the search paths are even necessary).

**Comment by sonictk** [comment]
Ah, ok. Removing the search paths and relying on just adding one top-level path '.' to the search paths (in order to solve the top-level module issue) solved it, and PTVS is responding a lot more snappily now.

One last question: if I am doing a statement like ``from ctypes import windll``, I cannot do a goto definition for the ``ctypes`` symbol, it just says it is of *unknown type*. However, if I actually just type ``import ctypes``, I am able to goto the definition for that statement's symbol. Is there any way I can also have this behavior for relative import statements as well?

**Comment by int19h** [comment]
If you do `from ctypes import windll`, there really isn't a `ctypes` symbol in that file, it's just a module name that does not become a variable.

**Comment by sonictk** [comment]
Hmm, but it happens for things like PySide, among other builtins.

I guess I'm more used to the behaviour of PyCharm and Wing where if I go to a definition of that symbol, it will open the __init__.py of the module if there is no defined symbol that actually exists.

Thanks for clarifying!

**Comment by sonictk** [comment]
Hmm, I just tried doing this for Maya, and I have the same problem occurring again: intellisense works sporadically, but when I create a new file (or even a new statement), suddenly everything breaks. 

I was following instructions as detailed here:
http://josbalcaen.com/maya-python-visual-studio-2013/

This time I logged visual studio to a file though:
http://pastebin.com/wGNvsK4s

Apparently many people have gotten this working just by doing this with full Intellisense and everything, so I'm wondering why it is only me that seems to be having issues...I don't see anything that jumps out at me in the log file. Does PTVS have its own log that I can look at to see what might be happening?

**Comment by zooba** [comment]
Sounds like the same issue you referred to at the start, and increasing the cross-module analysis limit is still the best available workaround (you may have to go even higher if you're still hitting the limit). Anything better requires a significant amount of work on our code analyser, which we simply don't have the resources to do right now.

There is nothing useful in the VS log for us, unfortunately, but we do have a menu item under Tools, Python Tools, Diagnostic Info that may have something relevant. However, in this case, I don't expect to see anything of value there as it sounds like everything is working "correctly" (for a not very good definition of correct :( )

**Comment by sonictk** [comment]
Hi @zooba :

Is there any way to tell if I'm actually hitting the limit? I looked at the Refresh Modules page, but adding up all the modules doesn't even bring the total count anywhere near 3000...and my limit is currently set to 10000. (Increasing it to 20k didn't seem to solve the issue, either.)

**Comment by zooba** [comment]
Unfortunately there's no way to tell.

However, looking at the log you posted, you may be able to resolve all the issues by clearing your search paths. Once you have a configured environment, there's no need to include Lib or site-packages folders in your search path, and this is basically guaranteed to be the cause of the problem.

With the latest builds of PTVS, we actually detect all of the paths to pre-analyze by looking at `sys.path`, so anything that's already there should not be specified in your project. (Previously we would just look in `Lib` and `Lib\site-packages`.)

I'll make an issue to notify people when adding search paths that aren't helpful. I'm sure we used to have one, but it may not have made it across from CodePlex.

**Comment by sonictk** [comment]
@zooba:
This is actually *not* related to the 3ds max virtualenv issue anymore though; it's Maya, where I am using a custom environment instead. The reason is that I have different versions of Maya at home/work, and I'm not using virtualenvs for either of the 2 projects.

One thing I do suspect might be the issue is that I actually *don't* want PTVS to automatically add anything from my ``PATH`` or ``PYTHONPATH``; they are filled with tons of paths and might be causing a ton of modules to be unnecessarily searched. I left that part empty when configuring my custom environment for Maya, but from what you're saying, does PTVS still search those environment variables by default? If so, is there any way I can disable this behaviour? 

I think I realize what's going on though. For Maya, adding the following paths seems to work:
C:\Program Files\Autodesk\Maya2013\devkit\other\pymel\extras\completion\py
C:\Program Files\Autodesk\Maya2013\devkit\other\pymel\extras\completion\py\maya
C:\Program Files\Autodesk\Maya2013\lib

However adding any of the other two:
C:\Program Files\Autodesk\Maya2013\Python\Lib\site-packages
C:\Program Files\Autodesk\Maya2015\Python\Lib\site-packages\pymel\core

Starts to cause issues, completions go missing, etc. (I had to keep closing/re-opening/refreshing the DB vs after adding each path one-by-one, since it seems that once a path is added, there's some cached auto-completion going on that makes my testing really tough to do)

Maybe there might be duplicate entries in those two folders that are confusing the Intellisense DB? How is the DB propogated at the moment? Would you guys be interested in investigating this further? I can host these folders somewhere for your team to pick through.

**Comment by zooba** [comment]
PTVS deliberately doesn't search `PATH` or `PYTHONPATH` at all and will actively clear the latter to avoid any conflicts with global settings (there's an option to disable this if you need it). The field when configuring the environment is so we know what the name of the variable is so we can clear or set it - we don't ever use the global value.

You're spot on about those paths. Basically anything under `Python\Lib` shoeld already be covered by the Intellisense DB because we detected it when you set the path for the custom environment. Adding it again is asking for trouble, especially since we legitimately can't keep an entire standard library in memory all at once because there are so many files (we use some simplifications and tricks for the DB).

The duplication is only really an issue because everything should work fine without the duplicates (there'll be a little bit of confusion in the analyzer, but nothing significant).

**Comment by sonictk** [comment]
Hmm, the problem is that the way Autodesk has set it up, both the extra 2 directories at:

``C:\Program Files\Autodesk\Maya2013\Python\Lib\site-packages``
``C:\Program Files\Autodesk\Maya2015\Python\Lib\site-packages\pymel\core``

contain additional libraries and procs that are not included in the auto-completion directories (the earlier 3 ones). Thus, while the majority of auto-completions now work, some procedures are still missing. 

I can't say for sure, but I assume PyCharm and Wing just scrape everything and merge all duplicates if they do exist in the auto-completion; I know that if I type ``mc.connectAttr()`` for example, I get hints from the auto-completion folder, but if I do ``import pymel.core`` and try to inspect that module, I am able to go to the actual library itself in the ``C:\Program Files\Autodesk\Maya2015\Python\Lib\site-packages\pymel\core`` directory, instead of the auto-completion directories.

Do you guys foresee PTVS ever being able to accommodate this sort of scenario? Alternatively, is there any workaround I could use for this? (I assume making a virtualenv for multiple Maya versions and switching between them should circumvent this issue?)

**Comment by zooba** [comment]
We handle duplicates fine for suggestions, but it sounds like we may have a bug if you shadow a standard library module with a user-defined module (in this case, we treat modules in Search Paths as user-defined) when you try to go to the definition of it. I'll check it out and file a new issue if I can reproduce it.

I'm confused as to why those folders are not being included automatically. If you run `print(sys.path)` in Maya's `python.exe`, what do you see?

You should definitely be using separate environments for each Maya version (in general, different path to `python.exe` means you should have a separate environment).

**Comment by sonictk** [comment]
The default ``lib\site-packages`` path is included, but not ``Lib\site-packages\pymel\core``.

Here is the output from printing the ``PATH`` from the maya Python interpreter:
```python
C:\Program Files\Autodesk\Maya2017\Python\lib\site-packages\setuptools-5.7-py2.7.egg
C:\Program Files\Autodesk\Maya2017\Python\lib\site-packages\pip-1.5.6-py2.7.egg
C:\Program Files\Autodesk\Maya2017\bin\python27.zip
C:\Program Files\Autodesk\Maya2017\Python\DLLs
C:\Program Files\Autodesk\Maya2017\Python\lib
C:\Program Files\Autodesk\Maya2017\Python\lib\plat-win
C:\Program Files\Autodesk\Maya2017\Python\lib\lib-tk
C:\Program Files\Autodesk\Maya2017\bin
C:\Program Files\Autodesk\Maya2017\Python
C:\Program Files\Autodesk\Maya2017\Python\lib\site-packages
```

**Comment by zooba** [comment]
I'm not familiar with pymel: is there a reason you need to import modules from `pymel\core` directly and can't write `from pymel.core import ...`? That's the usual way to import modules that are laid out like this.

**Comment by sonictk** [comment]
I mean, what is usually the procedure is ``import pymel.core as pm`` since usually you end up using a ton of modules within it and only importing the necessary ones you use is a PITA when writing production code. Same goes for modules such as ``maya.cmds``, or in other DCC applications.

**Comment by zooba** [comment]
That makes sense, and it also means that you don't need to add the `pymel\core` directory as a search path. When you `import pymel` it will look through each path to find the folder/file, and it'll be found in `lib\site-packages\pymel` and not `lib\site-packages\pymel\core\pymel`. (With the extra search path, you could write `from pymel.code import eggs` as `import eggs`, but other imports will probably break, so it's not really a good idea...)

We mimic Python here and do the same lookup (with some minor differences since we can't run all of the arbitrary user-defined code that Python does on startup, but it's good enough for this), so we will also find `pymel` through the `site-packages` folder and we don't need the extra search path. What this means is that if we *do* need the extra search path, we have a bug, and I'd like to figure out what it is - we've talked about so many different things now I'm a bit lost as to what the problem looks like to you.

I can virtually guarantee that adding search paths here is causing more problems that it's solving, so if you can walk me through exactly what doesn't work when you don't set the search paths, I'll try and get it fixed for our next release. (If it turns out that you do need the search paths, then we can look at the new issues that introduces and try and fix those, but I already know that many are unfixable at this stage.)

**Comment by sonictk** [comment]
Hi @zooba:

Sorry, I got caught up with other stuff at work over the past day or two. I think for now, adding the 3 specific paths for visual studio specifically should work. I'm surprised more TDs haven't run into this issue, considering how many people out there are using PTVS for Maya stuff and are apparently using the same setup that was illustrated (having those 5 specific search paths instead of the 3 listed

Something is definitely odd in the way that the intellisense db is searching for modules though. If I refresh the db, I can see Cython and other libraries that are definitely **not** part of the maya interpreter, and that are only accessible via my ``PATH``. 

For example, this is the list of packages I have installed at my maya interpreter site-packages, which looks correct to me:

![Image](http://i.imgur.com/SkAfMkc.png)

But in the IntelliSense options when configuring the interpreter, it shows a ton more packages, all definitely added from my ``PATH`` and ``PYTHONPATH``:

![Image](http://i.imgur.com/RNYijmx.png)

I believe this is what was requiring me to change the cross module analysis limit in the first place; I have a gazillion packages on my path. However, you're saying that this shouldn't be the case, right? I'm wondering if there's some other configuration setting I'm missing.

This is a screenshot of how I have the mayapy.exe interpreter set up in PTVS:

![Image](http://i.imgur.com/YRhJeyo.png)

(Sorry about the whiteouts. The file paths are definitely correct though :) )

**Comment by zooba** [comment]
So there is a difference between the two lists, which is the first (under Solution Explorer or the pip tab) only shows what pip recognizes as being installed (we just display the output from `pip list` here), while the IntelliSense list shows everything we think you can import.

It's entirely possible that Maya has included Cython by default without the metadata needed for pip to recognize it, which would explain it appearing in the latter list.

The empty "Path environment variable" field may be the issue. We don't ignore "PYTHONPATH" - we ignore whatever you've put in this field because that's telling us which variable your environment is going to look at. So it's entirely likely that your global PYTHONPATH value is interfering here because we aren't actually clearing it like I said we were.

**Comment by sonictk** [comment]
Hi @zooba :

> It's entirely possible that Maya has included Cython by default without the metadata needed for pip to > recognize it, which would explain it appearing in the latter list.

This is definitely not the case. I can't import Cython in maya for one, but more tellingly, a lot of my custom libraries (such as ``blur``) show up, which are most definitely not available to mayapy. Those are on my path for various reasons (in this case, ``blur`` is the 3ds max 2014 libraries for Python) Same goes for ``lowdown``, among others.

> The empty "Path environment variable" field may be the issue. We don't ignore "PYTHONPATH" - we ignore whatever you've put in this field because that's telling us which variable your environment is going to look at. So it's entirely likely that your global PYTHONPATH value is interfering here because we aren't actually clearing it like I said we were.

Sorry, I'm confused. I thought based on your earlier explanation this was just something I could arbitrarily set so that PTVS would clear it instead of using a global fixed value like ``PATH`` or ``PYTHONPATH``. What should I do then in this case, since setting it to either doesn't seem to work (Or is it supposed to?) It was mentioned that there was a setting where I could override this behaviour if needed?

Thanks!

**Comment by eksod** [comment]
Just for the record, I got Intellisense working again by cleaning up non-essential modules/folders from a very large solution (as commented here: https://github.com/Microsoft/PTVS/issues/276 ).

Also, with Motionbuilder Autodesk doesn't provide a python.exe, but a python.zip instead without a .exe inside. Using a normal Python environment works. For Intellisense to work with Motionbuilder python modules you just need this file in a search path somewhere:

C:\Program Files\Autodesk\MotionBuilder 2013\bin\config\Python\pyfbsdk_gen_doc.py

Renamed to pyfbsdk.py.

**Comment by sonictk** [comment]
Hi @eksod :D I didn't realize this was you since your Twitter handle is different haha

Thanks for the heads-up, for MoBu I use PyCharm for debugging so it's not as big of a deal, 3ds max is only where everything fails except the PTVS debugger haha. Also these days I end up using virtualenvs with site config files (.pth) which seems to work a lot better at stopping global site-packages from being included, though I still have to add the paths I do want manually to PTVS ( #863 )

**Comment by eksod** [comment]
Hey @sonictk ! :D

I've been using PTVS with Mobu for a few years (the remote debugging is easy to setup and quite useful in times of panic), but Intellisense has been broken for a while and I never had time to investigate why. I had the same symptoms as you mentioned in the first post, it works for a few seconds but then it stops working, or at least that's the case in VS 2012 and PTVS 2, and in VS 2015 I just got the No completion symptom, until I tried starting a new solution from scratch.

It's a shame python deployment from Autodesk is so confusing, with each package (Mobu, Maya, Max) deploying it in a different way.

Hopefully @zooba and the PTVS team can look into this too many search paths/references/modules bug soon. ;)

**Comment by zooba** [comment]
The too many search paths issue is resolved for VS 2017, and being able to provide useful Intellisense even after hitting the module limit is on the list and doesn't require this bug to remain open.

**Comment by atridave** [comment]
@zooba  
You might need to open it again as it is causing problem with VS2017  & maya, for me that was working fine with VS 2015 . not sure what is causing it this time

**Comment by zooba** [comment]
Can you describe the problems?
