### ISSUE TITLE
Django Build Stopped by Errors in Javascript Libraries

### ISSUE THREAD

**Issue by delizin** [Microsoft/PTVS#2360]
I am working on a django project that uses a large number of external javascript libraries. After including the JS files in my project so I could keep them with my source control, I could no longer run my django project from VS 2017. 

The build is stopped by the multitude of warnings and minor errors in the JS files and there is no readily apparent way that I've found to suppress errors on these specific files yet still keep them included in my project.

After searching for a solution, this seems to be an issue for other users working with common JS libraries.

**Comment by huguesv** [comment]
I'm not able to reproduce this in a Django project on VS2017 by inserting warnings in bootstrap.js, for example. I was thinking that the Build Action may affect this behavior, but changing it from Content to Compile or None made no difference.

I also tried having the Error List open, but it still didn't trigger this.

Could you share some step by step instructions on how to get it to repro?

**Comment by delizin** [comment]
Strange. I am also unable to reproduce this error any more. This error previously occurred for me using a fresh install of the previous Preview version. Since it happened, I had been keeping my JS libraries excluded from my project to allow it to run the development server. 

It does not appear to be occurring any more with the latest Preview update so another change could have fixed it or that it was a one off sort of bug. I'll close this issue for now and keep an eye out to see if it happens again.

Thanks for looking into it.
