### ISSUE TITLE
Azure msdeploy Python App Service Issue

### ISSUE THREAD

**Issue by jt-mott** [Microsoft/PTVS#2364]
I'm trying to deploy an Azure App Service running Flask on Python 3.4.  When I deploy from within Visual Studio (2015) via Web Deploy, everything works nicely.  But, when I attempt to deploy from my CI/CD server (TeamCity 10.0.3 on Windows Server 2012 R2) using an MSBuild step, the deployment succeeds without errors, but my app is apparently missing some crucial components and just throws HTTP errors on every request (my logging isn't able to capture the actual errors because the app is apparently totally hosed at this point).  My build has the following steps and executes against the .pyproj file.  I'm deploying numerous C# applications from this TeamCity instance using Web Deploy without fail:

1. Command Line Runner - Copy publish profile (because msdeploy looks for it at ~/__profiles for some unknown reason and I can't find a flag or configuration setting to change): 

    `mkdir __profiles 
    copy *.pubxml __profiles`

2. Command Line Runner - Create venv at top level folder: 

    `c:\python34\python.exe -m venv env`

3. Command Line Runner - Install from requirements.txt: 

    `env\scripts\pip install -r requirements.txt`
    

4. Powershell Runner - Stop Azure App Service

5. MSBuild Runner - Deploy (Build file path points to the .pyproj file): 

    `/p:DeployOnBuild=true 
    /p:PublishProfile="My Publish Profile"
    /p:Configuration=Release
    /p:AllowUntrustedCertificate=True 
    /p:UserName=%WebDeployUserName%
    /p:Password=%WebDeployPassword%`

6. Powershell Runner - Start Azure App Service

[Related question on SO](http://stackoverflow.com/questions/43192274/azure-msdeploy-python-app-service)

**Comment by huguesv** [comment]
You could use the Console in the Azure portal to check for differences in the file system on working vs non-working and also run some Python code to check that your virtual environment and packages are working fine.  Interactivity in the console is limited, but it's can still be useful.
![image](https://cloud.githubusercontent.com/assets/1696845/24672276/0bf7d9f2-1929-11e7-9f1b-c3419b525216.png)

One thing to note is that PTVS on VS 2015 will deploy the virtual environment as part of your application code.  Your custom script is creating a virtual env, and the msbuild deploy probably also copies the virtual env.  I don't know what kind of mixed-up deployment that might create.

The basic logging done by Azure can be useful. It's enabled via the portal:
![image](https://cloud.githubusercontent.com/assets/1696845/24672560/0c764444-192a-11e7-90f3-b0ac106f0672.png)

**Comment by justin-wolgamott** [comment]
Thanks for the pointers huguesv, I disabled the venv related build steps and enabled diagnostic logs, after which I re-ran the msdeploy step.  When viewing the dir contents in the shell, everything looks as expected, but my requests still error out and I see the following in the diagnostic log for every request:

```
<h3>HTTP Error 500.0 - Internal Server Error</h3> 
<h4>&lt;handler&gt; scriptProcessor could not be found in &lt;fastCGI&gt; application configuration</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
```

**Comment by huguesv** [comment]
You should look at the contents of web.config on the live site with Web Deploy and MSBuild.  If I recall correctly, some % variables are getting replaced somewhere in the pipeline when using Web Deploy.  If that's not happening, that could be the problem. Ex: %INTERPRETERPATH%

**Comment by huguesv** [comment]
By the way, just so you're aware, things are changing significantly with VS 2017.

The current situation (on VS 2017 Preview) is that we no longer publish a virtual environment.  We also no longer auto-generate web.config files.  The Python interpreter is selected by installing a site extension.  There's no automatic installation of Python packages, you have to log in to the console and issue `pip install -r requirements.txt`.

Read more at: https://blogs.msdn.microsoft.com/pythonengineering/2016/08/04/upgrading-python-on-azure-app-service/

Other team members are currently working on a CLI that will simplify all these steps, but that's not in yet.

**Comment by justin-wolgamott** [comment]
Thanks @huguesv, the web.config variables were in fact the issue.  The following % variables are replaced dynamically by the publish process in VS 2015 (even if I hard code the actual values, they are replaced with these placeholders when running msdeploy from TeamCity);

```
<appSettings>
    <add key="WSGI_ALT_VIRTUALENV_HANDLER" value="app.wsgi_app" />
    <add key="WSGI_ALT_VIRTUALENV_ACTIVATE_THIS" value="%ROOTDIR%\env\Scripts\python.exe" />
    <add key="WSGI_HANDLER" value="ptvs_virtualenv_proxy.get_venv_handler()" />
    <add key="PYTHONPATH" value="%ROOTDIR%" />
  </appSettings>
```
```
<handlers>
      <add name="Python FastCGI" path="handler.fcgi" verb="*" modules="FastCgiModule" scriptProcessor="%INTERPRETERPATH%|%WFASTCGIPATH%" resourceType="Unspecified" requireAccess="Script" />
    </handlers>
```
I hope PTVS for 2017 allows us to support a CD workflow without having to manually run a publish from VS.  For now, I'm looking at options for automating CD of this app using Docker.

**Comment by zooba** [comment]
Since all we do in publish now is copy files, you can use any approach to publishing that you like (FTP, DropBox, etc.) after the initial site configuration. The trick is in creating a static `web.config` that is correct so that you don't rely on the transform step.

For VS 2017 we've added new templates to help create a static one, but the link above (also https://aka.ms/PythonOnAppService) shows what the entries should look like.
