### ISSUE TITLE
Mixed mode debugging on 3.6 gives exe_common.inl not found

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2365]
Tried with both CPython 3.6 and Anaconda 3.6, which both have pdb files, and my script is this with a breakpoint on the print line:
```
import sys
print(sys.version)
```

It happens once per breakpoint.  F5 continue execution.  At no point did it show me my Python code where my breakpoint(s) are located.

![image](https://cloud.githubusercontent.com/assets/1696845/24684869/3c5dc75c-195e-11e7-9ae4-f1f2ecf14534.png)

**Comment by int19h** [comment]
What does the stack look like if you disable "Just My Code"?

**Comment by huguesv** [comment]
With "Just My Code" disabled
![image](https://cloud.githubusercontent.com/assets/1696845/24716459/faa8086e-19e3-11e7-926d-3a89d08896b1.png)

**Comment by huguesv** [comment]
Line numbers are slightly different because I changed the code a little bit since then.  It's effectively the same with it on/off, but when it's off the 2 C++ frames are black instead of gray.

**Comment by huguesv** [comment]
CPython 3.5 64-bit works fine, so this bug may be 3.6 only.

**Comment by zooba** [comment]
I can't repro this with CPython 3.6 32-bit or 64-bit. Any more ideas?

**Comment by zooba** [comment]
I've reproduced this on another machine, and it's also been reported [on developer community](https://developercommunity.visualstudio.com/content/problem/49193/breakpoints-not-hit-in-python-code-after-enabling.html). I'm guessing there's some difference in the environment, but I'm not yet sure what it would be (cached symbols is my guess).

**Comment by zooba** [comment]
I think this is due to a new optimization in the VC toolset we are building with - works with debug build of DebuggerHelper but not release. I'm going through adjusting build options until it works.
