### ISSUE TITLE
add new empty python file makes a ANSI encoding py file

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/PTVS#2368]
which should better be utf-8

**Comment by zooba** [comment]
I thought we'd fixed this - what version of VS are you using? Can you paste the contents of Help/About here please?

**Comment by alanpurple** [comment]
@zooba 
Microsoft Visual Studio Community 2017 Preview (2)
Version 15.1 (26401.1-Preview) Preview
VisualStudio.15.Preview/15.1.0-Preview+26401.1
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA231
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA231
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA231
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.6.00209.10
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30320.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17081.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

MenuCommands Extension   1.0
MenuCommands Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.3.50316.00
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17081.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17081.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17081.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17081.1
Profiling support for Python projects.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

**Comment by zooba** [comment]
Ah okay, looks like our default encoding is not being used when the file is empty. The easiest fix might be to add a newline to the "empty" files.

**Comment by huguesv** [comment]
It's an issue for the empty files in the project templates too, like PythonApplication1.py

**Comment by zooba** [comment]
Updated the PR with newlines in all of those files too.
