### ISSUE TITLE
VS2017 Ipython does not work in specific project

### ISSUE THREAD

**Issue by spruzzer** [Microsoft/PTVS#2374]
Dear all, 

I am running VS2017 preview and using Anaconda to build my virtual environments. I am able to add my custom virtual environments to "Python Environments" and use Ipython by calling the REPL from the option "Open Interactive Window". Unfortunately, I cannot use Ipython  when I execute the REPL from my python projects. In this case I have access only to the standard repl with no Ipython.

**Comment by huguesv** [comment]
You're right. While you can set IPython mode on global environment and virtual environment REPL, you can't do it for project environment.

**Comment by spruzzer** [comment]
I would like to ask you whether, in the future, there will be a way to access Ipython from projects or not. I see it as an appreciable feature and if I am not wrong in VS2015 it was possible.

**Comment by huguesv** [comment]
The problem right now is that there's no UI to change this option per-project.

This comment in the code indicates that a change is planned around this option.
https://github.com/Microsoft/PTVS/blob/master/Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml#L140

**Comment by zooba** [comment]
This is a bug. When you open a project's interactive window we should use the same startup mode and scripts as for the matching environment - the only differences should be search paths, working directory, and that the Python environment changes when you change the active environment in your project.

It seems we are not correctly picking up the mode file, which likely implies we aren't running startup scripts correctly either.

**Comment by spruzzer** [comment]
Thank you all for the information. Hope it can be fixed soon :). If it could be helpful I tried to use Ipython from project with a standard python environment (python2.7) and with anaconda 4.2 (python 2 and 3).
