### ISSUE TITLE
The completion DB does not have analysis results for all modules in this package

### ISSUE THREAD

**Issue by Pavel6625** [Microsoft/PTVS#2377]
I fail in trying to refresh the completion DB. The problem is similar to #1102. I am using PTVS 2.2.6, Visual Studio 2015 and CPython 64-bit 3.5. If I go to IntelliSense tab, there is a red exclamation mark before each entry and a message on mouse hover: "_The completion DB does not have analysis results for all modules in this package._" Could it be related to using non-latin symbols in path names?
The diagnostic info is attached.
[Diagnostic Info 2017-04-10T170039.txt](https://github.com/Microsoft/PTVS/files/910287/Diagnostic.Info.2017-04-10T170039.txt)

**Comment by zooba** [comment]
For Python 3.5 it shouldn't - from the attached logs it looks like the DB is already up to date, or there'd be more log messages. Can you try deleting the `C:\Users\Павел\AppData\Local\Python Tools\CompletionDB` folder and refreshing the DB again?
