### ISSUE TITLE
Cannot go to definition of variables

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2389]
If you define a top-level variable, you should be able to use `Ctrl+,` to find and navigate to it.

Currently, only lists/dicts/etc. appear in the list, and selecting them does not navigate to the definition.

**Comment by MightyWing** [comment]
how can i fix that?temporary solution？

**Comment by zooba** [comment]
There's no temporary solution, I'm afraid. It's down to how we represent variables in our code model, which currently just doesn't include the concept of a "definition".
