### ISSUE TITLE
Error when importing code coverage file on VS Community

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2392]
```
---------------------------
Microsoft Visual Studio
---------------------------
Exception was thrown: Could not load file or assembly 'Microsoft.VisualStudio.Coverage.Analysis, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
---------------------------
OK   
---------------------------
```

**Comment by huguesv** [comment]
Not sure why this command is implemented in PythonTools instead of Profiling package, but moving it there should take care of this.

**Comment by zooba** [comment]
Coverage is not available on Community and Pro, so we should handle this exception and display a more useful message. (Maybe there's an upsell page we can link people to on visualstudio.com? I'm not sure.)

**Comment by braindamaged1** [comment]
VS2013 and VS2015 Pro WILL open coverage files (not sure about community).

VS2017 SHOULD be able to open and read files from a build server, just as VS2013 and VS2015 did... the error message thrown looks more like a bug than the removal of this feature.

I keep a copy of VS2015 installed just so I can open these files.

**Comment by huguesv** [comment]
The error message box is shown from low level code in the editor factory, making it pretty difficult to avoid. It is then rethrown and displayed a second time.

If you try to open a .coveragexml file with VS File->Open, you will get the same 2 message boxes.

I reported a problem so that the code coverage folks can fix it on their end, since this doesn't just affect Python users.
https://developercommunity.visualstudio.com/content/problem/135339/failed-to-load-microsoftvisualstudiocoverageanalys.html

**Comment by huguesv** [comment]
Nothing for us to fix, it's up to the code coverage team now.

**Comment by reyou** [comment]
@huguesv  can you please link to issue forwarded to Code Coverage team, if there is one?
