### ISSUE TITLE
Connection class not handling unicode properly

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2402]
I'm currently writing low level message reading/parsing tests, and I'm finding out we have an issue with unicode text when encodedBytes.Length > text.Length, meaning there are multi-byte characters.

The message format is like this:
```
Content-Length: <content byte length>

<content>
```

When writing a message, we use the byte length for Content-Header value:
```
var str = JsonConvert.SerializeObject(packet);
var bytes = Encoding.UTF8.GetBytes(str);
var contentLengthStr = "Content-Length: " + bytes.Length + "\n\n";
var contentLength = Encoding.UTF8.GetBytes(contentLengthStr);

await _writer.WriteAsync(contentLength, 0, contentLength.Length).ConfigureAwait(false);
await _writer.WriteAsync(bytes, 0, bytes.Length).ConfigureAwait(false);
await _writer.FlushAsync(cancel).ConfigureAwait(false);
```

When reading, StreamReader.ReadAsync takes the number of chars to read, and but we give it a number bytes instead.  There are no methods on StreamReader that lets you do binary reads.

So in cases of multi-bytes characters, we read too much. Result will vary depending on whether there are messages queued up in the stream, as we will read into the next message.

As I'm writing tests I've been making the reading code more strict, and now it's obvious when there's a mismatch like this.

StreamReader is buffered, so it's not like we could temporarily read the bytes directly from the Stream, as the Stream position will likely be further ahead than we expect from the prior ReadLineAsync calls.

One solution is to stop using StreamReader altogether, just write our own reader class that has the ability to read both text and binary.  That's pretty much what I did on the Python side.

I'd like to confirm whether VSCode debugger protocol, which is similar that what we are using, considers Content-Length to be character or byte count.  If it's character count, then the solution is to make that change.

**Comment by huguesv** [comment]
I've replaced StreamReader with my own class that can read a specific number of bytes, and can also do ReadLine, so far all my low level tests are passing but the debugger tests are all failing.

**Comment by zooba** [comment]
@huguesv This is a fairly critical bug that we need to fix asap.

I'd suggest we use a binary reader - the separators are always `b"\r\n"`, so we can do a basic readline (perhaps emulated with a small buffer, if we need to) to get the headers.

**Comment by zooba** [comment]
Also, it's byte count, not character count: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

**Comment by huguesv** [comment]
Thanks for the link.  I have something working now.  We've been using `\n`, not `\r\n`, so I'll change that for consistency with that protocol.
