### ISSUE TITLE
Visual studio 2017 / Python 3.6 support

### ISSUE THREAD

**Issue by CaptainSpalding** [Microsoft/PTVS#2404]
This is not so much an issue, I was just wondering if VS2017 and python 3.6 support were coming, and if so when. and also I am going to take a peek at the source and if there is any help needed in the project I am willing to lend.

**Comment by Huqin-China** [comment]
U need to wait the next vs upgrade.
Now ptvs support vs2017 preview and python3.6
[](https://www.visualstudio.com/vs/preview)

**Comment by zooba** [comment]
Also see https://blogs.msdn.microsoft.com/pythonengineering/2017/03/07/python-support-in-vs2017/ for more information about our plans.

**Comment by BMarinov** [comment]
@zooba I still cant find any mention of python 3.6 though, is there a roadmap and how are things looking like? I have a couple of small 3.6 projects with weird issues related to the venv's and the django runserver, not sure if I broke something or its just the missing 3.6 support throwing a tantrum :)
Regards!

**Comment by zooba** [comment]
Python 3.6 is fully supported in VS 2017 (except we're still catching up on some of the new syntax), but there were not many changes required for that. I'm not aware of anything that would break/fix venv or Django - feel free to file new issues with details and we'll try and help you out.

**Comment by mrakitin** [comment]
`pip install mpi4py` fails to compile the library with VS 2017 & Python 3.6 x64. With VS 2015 everything goes smoothly.
