### ISSUE TITLE
Automatically add a # when you hit enter in the *middle* of a comment

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#241]
Example:
```
# this is a really really long line hello world
```
Place the cursor before hello world and hit enter.  I would like to get:
```
# this is a really really long line
# hello world
```
But instead I get:
```
# this is a really really long line
hello world
```

**Comment by zooba** [comment]
+1 I like this

**Comment by zooba** [comment]
It should copy `re.match("[#\s]+")` from the start of the current line onto the start of the next.
