### ISSUE TITLE
No module named 'visualstudio_py_debugger'

### ISSUE THREAD

**Issue by jigneshdpatel** [Microsoft/PTVS#2416]
Got this error which asked to report it here:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\visualstudio_py_launcher.py", line 25, in <module>
    import visualstudio_py_debugger as vspd
ModuleNotFoundError: No module named 'visualstudio_py_debugger'

Internal error detected. Please copy the above traceback and report at
http://go.microsoft.com/fwlink/?LinkId=293415

**Comment by huguesv** [comment]
Can you check that `visualstudio_py_debugger.py` exists in the same folder as `visualstudio_py_launcher.py`?  If it doesn't, you may need to repair your PTVS installation.

**Comment by zooba** [comment]
Also check that you do not have a global `PYTHONPATH` set or any global code that might be modifying `sys.path`. Having a broken search path is the most likely reason for this error to occur.
