### ISSUE TITLE
[3ds max] Debugging with 3ds max?

### ISSUE THREAD

**Issue by sonictk** [Microsoft/PTVS#242]
Hi all:

I'm wondering if it's possible for PTVS to debug python projects with 3ds max. I've successfully done so with Maya before, but I can't seem to get it working with the MaxPlus API in 3ds max 2015 onwards. 

When I try to attach the debugger to the 3dsmax.exe process, I get the following error message:

 ![Image](http://i.imgur.com/4Bfb36v.png)

In the Output window, the following is shown:

`'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\3dsmax.exe'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\AssemblyLoader.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\CSharpUtilities.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\ManagedServices.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\UiViewModels.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\Autodesk.Max.Wrappers.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\Autodesk.Max.StateSets.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\CreaseExplorerView.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\DaylightSimulation.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\FPMaxWpfContent.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\ManagedBootstrap.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\ManagedNetworkUtilities.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\MaterialExplorerView.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\MaxWpfContent.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\mixamo_assembly.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\SceneExplorerView.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\Sunlight.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Autodesk.Max.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'Microsoft.GeneratedCode'. 
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Design\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Design.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'Microsoft.GeneratedCode'. 
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.JScript\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.JScript.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'vdyahyis'. Module was built without symbols.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\SceneExplorer.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\ExplorerFramework.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\WPFCustomControls.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\DevExpress.XtraTreeList.v10.1.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\AdWindows.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\ExplorerManagement.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\MaxCustomControls.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\DevExpress.XtraEditors.v10.1.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\DevExpress.Utils.v10.1.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\MaxMaterialBindings.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\MaxCreaseBindings.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\DevExpress.Data.v10.1.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\MaxExplorerBindings.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\CoreManagedUiControls.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\MaxSerialization.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\bin\assemblies\mxsdotNet.dlx'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\AdApplicationFrame.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\stdplugs\AssetTracking\ATSVault10.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Autodesk.DataManagement.Client.Framework.Vault.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Autodesk.Connectivity.WebServices.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Microsoft.Web.Services3.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Autodesk.DataManagement.Client.Framework.Vault.Forms.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Autodesk.DataManagement.Client.Framework.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Autodesk.Connectivity.Extensibility.Framework.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\Autodesk.DataManagement.Client.Framework.Forms.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'C:\Program Files\Autodesk\3ds Max 2015\DevExpress.Utils.v13.1.dll'. Cannot find or open the PDB file.
'3dsmax.exe' (CLR v4.0.30319: 3dsmax.exe): Loaded 'Microsoft.GeneratedCode'.`

If I try to attach to just the Python code types, it either gives me a timeout error, or successfully attaches, but doesn't seem to hit my breakpoints in the code. 

Is there any way I can get PTVS debugging to work with 3ds max? I understand this is probably not a request made by many users of PTVS, but it would be very beneficial for my workflow as I'm starting to write cross C++/Python plugins for 3ds max and I'm starting to experiment with working in PTVS instead of PyCharm for my day-to-day work as well.

Thanks!

**Comment by int19h** [comment]
Try selecting Native code type in addition to Managed and Python when attaching. I think this might get you past the "invalid state" error.

The real problem, though, is that mixed-mode debugging needs symbols for the Python DLL that the hosting app uses. If they're using stock Python, you should be able to get the matching symbols from python.org; but I suspect that they build their own, and likely don't publish the symbols for that.

**Comment by sonictk** [comment]
@int19h 

I managed to resolve the symbol errors by adding the Autodesk symbol server to my _NT_SYMBOL_PATH: http://symbols.autodesk.com/symbols/

The odd thing is that now I can debug on my home machine, but only if I attach to 3ds max (Only Python, selecting Native still gives me an invalid state error), pause it, and then continue. At my work machine, the first time I launch 3ds max, I am able to attach to Python, but it never hits breakpoints, and the Pause button is grayed out. After I stop debugging and try to re-attach again, I cannot, and keep getting timeout errors.

Python in 3ds max uses a standard build of 2.7.3 afaik.

If you have any ideas as to why my work machine environment is failing, I'd really appreciate it! Both my home and work machines VS' are the same version and set up exactly the same way, settings, plugins etc.

**Comment by int19h** [comment]
If you're attaching with Python only, it uses the regular debug engine that doesn't need symbols, so I'm not sure whether the symbol path is actually helping you any.

If 3DS does indeed use a regular 2.7.3 (or below) build, then we won't support it, because those builds are compiled with PGO, which is something that the debugger cannot handle currently for various reasons. Can you check by looking at the product version of python27.dll in Explorer (if you go into file properties, it should be displayed on the Details tab):

![image](https://cloud.githubusercontent.com/assets/1175142/7817846/abfd0d78-038c-11e5-897e-df288fa3c107.png)

That said, if it is indeed the case, you should have got an error message about PGO. If it's not appearing, then that's a bug in and of itself.

**Comment by sonictk** [comment]
@int19h Hi, this is what I see:

 ![Image](http://i.imgur.com/EeeHCTC.png)

I don't get any error message about PGO, however, and it doesn't make sense: how come I can get it to work on one workstation, but not on another?

**Comment by int19h** [comment]
The one machine that you have it working on, you're using pure Python debugger rather than the mixed-mode one. All the discussion about symbols, PGO etc doesn't apply in that case - pure Python debugger can work with any Python version 2.5+, including custom builds without symbols etc.

But yes, that would be expected to work the same on either machine, if you use the same attach procedure (including the Code Type selection) for both...

Which version of PTVS are you using? If it's 2.1, consider trying 2.2 RC instead.

**Comment by sonictk** [comment]
@int19h Hi Pavel:

Both machines are using PTVS 2.2 RC.Both machines use the same builds of Python and packages (I have an install script to setup my development environment specifically whenever I work with a brand new OSRI)  I tried upgrading to the latest dev build of PTVS on this machine, but it didn't solve the issue either. 

I'm at a loss to explain why the behaviour is different for both...

**Comment by int19h** [comment]
Can you clarify what you mean by "listed as '2'"? (a screenshot would probably be best)

**Comment by sonictk** [comment]
@int19h Hi Pavel:

This was the dialog I was referring to, however, it's irrelevant now; after I restarted the machine that was working (for something unrelated) opening VS and trying to attach to process now shows all of the processes as Sessions type 1.

![Image](http://i.imgur.com/8Tl2wo4.png)

I can still debug 3ds max fine though on my home machine, but not on my work machine. Now I literally have no idea what the difference in environment could be >.<

**Comment by int19h** [comment]
Are you attaching using the settings as displayed on the screenshot? Because that shows both Managed and Python code types selected again (due to auto detection), which means that attach will be using mixed-mode debugger rather than pure Python. You need to explicitly select code types, and either drop Managed or add Native (I don't think we properly support the case of mixed mode where Native is not in the mix - this should probably have better error reporting).

The Session column refers to Windows user session - it's usually 1 unless you have several people logged in to the same machine at once. It's not really important.

**Comment by sonictk** [comment]
@int19h : Hi Pavel; no, I am attaching using just Python. (If I use Managed+Native it will work for debugging the .NET stuff I do in 3ds max, but there is already a built-in debugger in 3ds max for that sort of thing) That screenshot was just to illustrate the session column in the UI which I had no idea what it meant.
