### ISSUE TITLE
Save encoding warning does not appear for project files

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2421]
Start VS, do not open a project.
Open a python file, paste this at the top:
```
#!/usr/bin/env python
# -*- coding: cp866 -*-
print('Бóльшая')
```
Save As, Save With Encoding, Cyrillic (DOS) - Codepage 866

Result: Correct behavior, you get a warning message that says you will lose data and you should change encoding (that 2nd char cannot be encoded).

Now repeat the same operation, but this time, with a file inside of a Python project.

Result: NO warning message. When you close and reload the file, you'll see the 2nd char passed to print is replaced with ?.

FYI RTVS had a similar issue, and it was discovered that the bug was in CPS.
https://github.com/Microsoft/RTVS/issues/2471 (scroll down to the bottom)

Also we discussed the lack of warning in https://github.com/Microsoft/PTVS/issues/74 but the no warning issue was not fixed.

**Comment by zooba** [comment]
Should be covered by #1952
