### ISSUE TITLE
F5 toolbar button caption is Attach instead of Start

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#2423]
When you click on it, it starts debugging (F5), and it briefly changes to say Start right before it changes to Continue.

So it behaves correctly, not sure why caption is wrong.  It still says Start for C# projects.

![image](https://cloud.githubusercontent.com/assets/1696845/25212927/373fb1be-2542-11e7-9525-b8f652b60307.png)

**Comment by huguesv** [comment]
Hmm, it also says Attach when you have no solution loaded. Clicking on it brings up the Attach dialog. That part is correct.

Could this be a regression from https://github.com/Microsoft/PTVS/pull/2393 ?

**Comment by huguesv** [comment]
Ah, when you have Python project open, but you close all editor windows, then it becomes Start.

**Comment by zooba** [comment]
This sounds more like a Lightweight Solution Load issue, but presumably there is some setting we have to provide to VS to keep the button working (possible a UIContext?).

**Comment by zooba** [comment]
Not a duplicate, but also reported at https://developercommunity.visualstudio.com/content/problem/62717/vs-2017-152-python-workload-knopf-anfugen-in-der-t.html

There is a definite code path in core IDE that is responsible for this - we do not set the text ourselves - but in some circumstances it gets it wrong for us. We need to dig into exactly what logic the IDE is using and figure out how to satisfy it.

**Comment by shravan2x** [comment]
Has there been any progress on this?

**Comment by w-sa** [comment]
Any update on this? I'm also facing exact same issue...
