### ISSUE TITLE
File not included in project is getting bolded in addition to startup file

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#2430]
Filing this in case we ever run out of bugs to fix ;)

![image](https://cloud.githubusercontent.com/assets/1696845/25242083/42587b92-25ad-11e7-8618-d9f5626dfb4a.png)

Open a project that has a startup file set.
Enable Show All Files.
Close project.
Copy some extra files or folders to the project folder.
Open project.

Startup file is bolded, and an additional file or folder that's not included in the project is also bolded.

I'm able to repro by opening the project at `\bugs\2422`, enabling show all files, closing project (and save), reopen the project again.

**Comment by zooba** [comment]
I think it's actually to do with how the hierarchy ID gets mapped, since that is the piece we pass to VS to do the bolding. It's probably racing between the Show All Files support.

In any case, this area of code is incredibly messy and hard to debug :(

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/140223/python-set-as-startup-file.html
