### ISSUE TITLE
Django Management Console - Not importing modules with spaces in the title of the project name

### ISSUE THREAD

**Issue by skilfulcoding** [Microsoft/PTVS#2431]
I have a project called 'Database Fun' I opened the DMC and the following error was automatically generated: 

```
v (Python 3.6 (32-bit)) interactive window [PTVS 3.0.17109.1-15.0]
Type $help for a list of commands.
  File "<stdin>", line 1
    import django, Database Fun.settings; print('Starting Django %s shell' % django.get_version())
                              ^
SyntaxError: invalid syntax
```
if I manually type

import django
import Database_Fun.settings
print('Starting Django %s shell' % django.get_version())

all work ok, so appears to be a bug to do with handling of projects with spaces in the name

**Comment by zooba** [comment]
Good catch, thank you!

**Comment by zooba** [comment]
Looking at the code responsible for this, I think an easy workaround is to open Project Properties and select the Django tab. There you'll see that the value for "Settings Module" is probably `$(MSBuildProjectName).settings` - if you change this to the importable name of your project, then it should be okay.

As far as I can tell, this affects imported projects, `StarterDjangoProject` and `PollsDjango`. Our other new project templates correctly use the "safe" name of the project in this field by default.

**Comment by skilfulcoding** [comment]
That work-around worked great, thanks @zooba

**Comment by huguesv** [comment]
The 3 templates (starter, blank and polls) are okay now.

From existing code wizard needs to be updated. It can't rely on the name of the .pyproj either, that may not match the name of the subfolder where settings.py is, so it needs to find that file.
