### ISSUE TITLE
Unable to run python tests from Visual Studio

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/PTVS#2434]
I've started getting the following error while trying to run my Python tests in Visual Studio. I tried looking for this error but couldn't find any reference.

How can I get the following file: Microsoft.VisualStudio.Settings.14.0

------ Run test started ------
An exception occurred while invoking executor 'executor://pythontestexecutor/v1': Exception has been thrown by the target of an invocation.
The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Could not load file or assembly 'Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Resulting in: An exception occurred while trying to create an instance of type 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService'.

Resulting in: Cannot activate part 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService'.
Element: Microsoft.PythonTools.Interpreter.InterpreterOptionsService -->  Microsoft.PythonTools.Interpreter.InterpreterOptionsService -->  AssemblyCatalog (Assembly="Microsoft.PythonTools.VSInterpreters, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

Resulting in: Cannot get export 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService (ContractName="Microsoft.PythonTools.Interpreter.IInterpreterOptionsService")' from part 'Microsoft.PythonTools.Interpreter.InterpreterOptionsService'.
Element: Microsoft.PythonTools.Interpreter.InterpreterOptionsService (ContractName="Microsoft.PythonTools.Interpreter.IInterpreterOptionsService") -->  Microsoft.PythonTools.Interpreter.InterpreterOptionsService -->  AssemblyCatalog (Assembly="Microsoft.PythonTools.VSInterpreters, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")

========== Run test finished: 0 run (0:00:00.0752758) ==========

Here is my environment info:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Python Tools for Visual Studio   2.2.40825.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40825.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40825.00
Profiling support for Python projects.

**Comment by rnagpal** [comment]
Tried updating to latest PVTS update and latest Visual Studio update but same issue.

**Comment by zooba** [comment]
I suspect you've changed your tests to run in 64-bit mode. In VS 2015, we don't support this (it's resolved in VS 2017), so you'll need to run tests in 32-bit mode.

**Comment by ashwini-ms** [comment]
I am facing the same issue with vstest command line even with x86:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "<path_to_projects>\TestApplicationPython\TestApplicationPython\test1.py"  /TestAdapterPath:.  /UseVsixExtensions:true  /platform:x86

**Comment by ashwini-ms** [comment]
@huguesv / @zooba  , Any thoughts ?

**Comment by zooba** [comment]
VSTest is not supported for this. You should run tests using the PyTest or unittest packages when you are outside the IDE.

**Comment by ashwini-ms** [comment]
@zooba , Any thoughts ?
