### ISSUE TITLE
Deployment of Django page via VS 2017 Preview is not working

### ISSUE THREAD

**Issue by OnkelOnk** [Microsoft/PTVS#2435]
If I deploy a Django page via VS to azure it is only working when I created a Django web app via the azure portal and select it for deployment in VS. If I create it via VS the page is not displayed. But more importantly: When I try to deploy an update of the page via VS it doesn’t have any effect. Se more detailed description here:

https://stackoverflow.com/questions/43506691/deploy-a-simple-vs2017-django-app-to-azure-server-error/43562133#43562133

**Comment by zooba** [comment]
I've posted a more detailed answer there, but the canonical answer is available at https://aka.ms/PythonOnAppService and also at https://blogs.msdn.microsoft.com/pythonengineering/2016/12/12/publish-to-azure-in-vs-2017/
