### ISSUE TITLE
IntelliSense STILL not working for Autodesk Maya Python - will this ever be as good as Wing IDE?

### ISSUE THREAD

**Issue by studiowildcard** [Microsoft/PTVS#2437]
Hey guys,

I hate to be harsh but I first started using PTVS when I worked on HoloLens at Microsoft back in 2013. It is now 2017 and I **still** can't get proper / reliable code completion and documentation working in Visual Studio for Maya/PyMel/OpenMaya/etc. I literally tried for 4 hours last night, searching the web, doing a bunch of stuff that didn't work. 

I gave up and installed Wing IDE and everything was working in 10 minutes (see attached image). 

Contact me if you'd like more information, but you guys need to fix this!

![windide-maya](https://cloud.githubusercontent.com/assets/10143893/25357087/69f36eea-28f1-11e7-8bc4-e0132b069208.png)

Jesse

**Comment by huguesv** [comment]
https://github.com/Microsoft/PTVS/issues/3046
