### ISSUE TITLE
Execute in Interactive does not use debug settings

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2449]
If you set the working directory in your project and then execute the project in interactive, it does not use the correct working directory.

(Reported at https://developercommunity.visualstudio.com/content/problem/39038/execute-project-in-python-interactive-import-in-vs.html)

> When I try to debug an individual file on the fly in VS2017, I use "Execute Project in Python Interactive" (SHIFT-ALT-F5), but when I try to import a module that I made (which is in the same folder as the file that I am trying to debug) , it cannot find the module. If I make a Python project and use "Start Debugging" (F5), it works, but it seems that to use "Execute Project in Python Interactive", I still need to import os module, and then do os.chrdir to specify the directory where the files are.

**Comment by huguesv** [comment]
Given this project where `newfolder1/module1.py` is startup item:
```
newfolder1/module1.py
newfolder1/module2.py
```

where module1.py does `import module2`

If I set the working dir to `newfolder1`, it works in both F5 and SHIFT-ALT-F5.
If I leave the working dir to the default `.`, then it only works with F5.

**Comment by huguesv** [comment]
Working directory was fine and matched between debug and run in repl.
It's `sys.path` that was different, the debugger launcher python code was making sure that the startup script's folder was in `sys.path`, but that wasn't the case in the REPL.
