### ISSUE TITLE
remote debuging - need to reenter address all the time

### ISSUE THREAD

**Issue by BartekSzpak** [Microsoft/PTVS#245]
Hi!

Is it always necessary to reenter the address of a remote computer when doing a remote debuging via attach to process ... ?

The address I am entering does not later appear on a selection list and it has to be reentered each time remote debuging is used, even if VS is not closed etc. If this is not my fault it would be very useful to have the address available at least on a selection list or e.g saved it somewhere in a profile.

This would certainly speed-up the debuging in remote mode.

Keep doing a great job!
Bartek

**Comment by int19h** [comment]
Unfortunately, this is the default behavior of VS. We have #239 that would fix it just for PTVS. Alternatively, there's https://github.com/erlandranvinge/ReAttach, which tries to tackle this problem universally, but it doesn't support custom transports yet (but I'm sure a pull request would be welcome ;) )
