### ISSUE TITLE
Pasting into the REPL triggers immediate execution

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2488]
Reported at https://developercommunity.visualstudio.com/content/problem/48964/pasting-into-python-interactive-window-immediately.html

We should detect pastes that are not intended to be executed immediately (because there was existing text? not sure what the best heuristic here is) and allow the insertion without triggering execution.

**Comment by steel3d** [comment]
What is the rationale for Paste executing immediately?

If it is to save a key stroke, then it's probably a bad rationale, given that it precludes a very important workflow (paste, then edit, then execute).

If it is to immediately execute commands sent to the repl window from the editor via Ctrl-Enter, then there should probably be an additional character/command sent in that case to tell the window to execute immediately. 

Not sure that any heuristic will really work. Other than allowing for a painful workaround - type a junk character, paste, delete the junk character, etc.

**Comment by zooba** [comment]
The rationale is that many interactive environments (including the default one) do not support executing multiple statements. So if you paste 4 lines of code it will result in an error - so when you do that, we need to split them up and execute each of them, and presently we do that on paste rather than on execution (and while I'm not opposed to changing this to emulate support for multiple statements, that's work that we haven't allocated time for right now).

When you send code from an editor, we do this splitting preemptively (if necessary) and send each line on its own and execute it. Paste should only do this when we need to split (because the REPL backend requires it) and the pasted code has multiple statements, and even in this case we should not execute the last one.

The bug here likely has a single cause, which will be our code to detect whether to submit or not is checking for a complete statement without being fully aware of how the statement became a complete statement, or whether it was previously complete or empty. Our hope is to fix it for the next release, though we have other more pressing issues to work on as well, as well as deadlines and other requirements. Contributions welcome :)

(Hope that isn't too scatterbrained and makes some sense... we _want_ to fix far more things than we're physically capable of, and have a relatively old codebase, so you'll occasionally apparently odd behaviours that have been around forever that sound easy to fix but we simply haven't gotten to yet.)

**Comment by sn2234** [comment]
Is there an ETA for this one?
It actually prevents me from using VS2017 for python projects

**Comment by zooba** [comment]
@sn2234 Now it's fixed, it'll be in our next release. A few months until then though - we're taking some time off frequent Python-related updates to make a whole range of improvements.
