### ISSUE TITLE
Execute File in Interactive executes wrong file

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2493]
Load a Python project.
Close all document windows.
Check under Tools->Python Tools that the command caption is "Execute Project in Interactive".
Open one of the project Python files, any will do as long as it's not the startup file.
Check under Tools->Python Tools that the command caption is "Execute File in Interactive".
If you execute the command, it will execute the project startup file, not the one you opened. That's unexpected / misleading.

It will execute the opened file only if you don't have a project loaded.

**Comment by somelinguist** [comment]
This fix definitely makes sense, but now there's no quick way to execute the project in Interactive.

I had gotten used to the convenience of having a shortcut that would execute the project no matter what file I was in. I just updated and am missing the unwanted behavior. Is there any other way to have a shortcut for executing the project from any file without having to choose the project?
