### ISSUE TITLE
completions: hitting enter when fully typed in interpreter.

### ISSUE THREAD

**Issue by bagratte** [Microsoft/PTVS#25]
there is an option under tools, options, text editor, python, advanced called "add new line on enter at end of fully typed word". can we have this apply to interpreters too?

**Comment by zooba** [comment]
Are you referring to the interactive windows? The one option should control both. (Or maybe you're asking for two separate options? I'm not sure we can support that easily due to how the VS editor handles Python sections.)

**Comment by bagratte** [comment]
everything is fine. sorry.
