### ISSUE TITLE
HELP - Where to find interpreter for PTVS 3.6

### ISSUE THREAD

**Issue by tedhuskey** [Microsoft/PTVS#2501]
I can't even run HeloWorld.  I keep gettting error stating need Interpreter. I'm running Python 3.6 64 bit and have not be able to find an interpreter to download

**Comment by zooba** [comment]
What version of Visual Studio are you using?

If you're on Visual Studio 2017, please open Tools, Python, Diagnostic Info, save it, and attach it to a comment here.

If you're still using Visual Studio 2015, you'll want to follow the instructions [here](https://docs.microsoft.com/en-us/visualstudio/python/python-environments#creating-an-environment-for-an-existing-interpreter) to add it manually. You'll have to select "3.5" as the version, but apart from some of the new syntax not being supported in the editor, basically everything else should work fine.

**Comment by timeregained** [comment]
I met the same issue when I install the latest 2017 15.2.

An existing anaconda 64 bit installation cannot be found automatically, and this performs differently when I used previous PTVS in VS 2015.

The Diagnostic Info could be found as 
[Diagnostic Info 2017-05-11T194241.txt](https://github.com/Microsoft/PTVS/files/992857/Diagnostic.Info.2017-05-11T194241.txt)
