### ISSUE TITLE
REPL SyntaxError when sending/typing only comments

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2510]
Comments followed by empty line cause a syntax error.
We have a failing test for it: ReplWindowUITests.ReplWindowPythonTests.Comments

```
>>> # hello
... # world
... 
  File "<stdin>", line 3
    
    ^
SyntaxError: invalid syntax
>>> 
```

**Comment by huguesv** [comment]
Similar to https://github.com/Microsoft/PTVS/issues/1840, but that one works fine now.

**Comment by zooba** [comment]
This is weird - it should be returning that it parsed as empty and we shouldn't be trying to execute it...

**Comment by zooba** [comment]
Ah, it's because of the trailing newline.
