### ISSUE TITLE
What's the proper way to select the Python Environment.

### ISSUE THREAD

**Issue by DaveSprague** [Microsoft/PTVS#2518]
I'm using Preview of Visual Studio 2017 Community and trying out the Sample Machine Learning projects.
 
I would think that you set the Python Environment by clicking on it so it's selected in the Python Environments window but that doesn't appear to actually set the active environment.

What is the correct way to set the Python Environment?

I found I need to go into the Projects Setting and I have to select Anaconda 4.3.0 as the Interpreter in place of the <global default>.

Shouldn't selecting the Python Environment in the Python Env. window select the corresponding interpreter for the project and set that Environment for the Solution?

Here's the Python diagnostic info (in this case, it's prior to setting Anaconda as the interpreter under Project Settings)
https://gist.github.com/DaveSprague/e50f82d70af1c145b67ba2efe73b02f9

**Comment by huguesv** [comment]
A project can have references to multiple environments. They will appear in Solution Explorer under Python Environments.  Right-click on it and choose Add/Remove Python Environments.  Then you can right-click on one and Activate Environment.  This is handy if you want to quickly switch back and forth.  As you've noticed, the active environment can also be changed in project settings page.

If a project doesn't have any active environment, it will use the global default.  To change that default, you select it from the Python Environments window, and click on Make this the default environment...

**Comment by huguesv** [comment]
The documentation at https://docs.microsoft.com/en-us/visualstudio/python/python-environments#project-specific-environments has more information and screenshots.

**Comment by zooba** [comment]
Yeah, I think the missing piece here is that the list in the environments window is just that - a list. To activate an environment, you need to take an extra step (this is pretty standard for lists in Windows - selection and activation are rarely the same gesture).

**Comment by DaveSprague** [comment]
Got it. Thanks to all for help with this
