### ISSUE TITLE
help() output is not displayed in interactive window

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2531]
If I type `help(print)` in a Python 3 interactive window, the help text is not displayed.

However, if I then immediately reset the window, the text is displayed as an error message.

Testing with `py -3.6 -c "help(print)" >nul`, it's clearly sending the text to stdout and not stderr, so we are probably misdirecting it.

**Comment by huguesv** [comment]
On Python 2.7, it works fine (with a valid help parameter, not print). The stdout is redirected in the repl backend, and we read if from our socket in `PythonInteractiveEvaluator.CommandProcessorThread.HandleOutput`.

On Python 3.6, it doesn't work. The stdout is not redirected in the repl backend, instead we get it via the Process.OutputDataReceived, our event handler is `PythonInteractiveEvaluator.CommandProcessorThread.StdOutReceived`.
There, we stash the output in a "pre-connection output" string builder, and when the process exits, we print the content of the string builder with `WriteError`.

```
            private StringBuilder _preConnectionOutput;

            private void StdOutReceived(object sender, DataReceivedEventArgs e) {
                if (e.Data != null) {
                    if (!AppendPreConnectionOutput(e)) {
                        _eval.WriteOutput(FixNewLines(e.Data));
                    }
                }
            }

            private bool AppendPreConnectionOutput(DataReceivedEventArgs e) {
                var pco = Volatile.Read(ref _preConnectionOutput);
                if (pco != null) {
                    lock (pco) {
                        pco.Append(FixNewLines(e.Data) + Environment.NewLine);
                        return true;
                    }
                }
                return false;
            }

```

`AppendPreConnectionOutput`  returns true, `_preConnectionOutput` is initialized in ctor.

**Comment by zooba** [comment]
Looks like the easiest fix is to set `os.environ["TERM"] = "dumb"` so that `pydoc` doesn't use redirection through an external process to display help.
