### ISSUE TITLE
open interactive window error

### ISSUE THREAD

**Issue by Arhzi** [Microsoft/PTVS#2534]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Закрыть]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2' from assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

**Comment by Henrycobaltech** [comment]
I have the same error after updated to VS2017.2

**Comment by huguesv** [comment]
Could any of you confirm the version of the Microsoft.VisualStudio.VsInteractiveWindow.dll that you have installed?  It's in `Common7\IDE\CommonExtensions\Microsoft\InteractiveWindow`, under your VS install dir.

![image](https://cloud.githubusercontent.com/assets/1696845/26008938/9fdc76ce-36fb-11e7-80c5-feb65bbe2d86.png)

Additionally, what is your language setting in Tools/Options/Environment/International Settings?  And what's your Windows language setting?

We're having trouble reproducing this :(

**Comment by fklier** [comment]
Same error here.

VS language setting is "English"
Windows display language setting is English (United States). Japanese and French input are also installed.
Microsoft.VisualStudio.VsInteractiveWindow.dll Product version is 2.0.0.61319 (Date Modified 2/23/2017 12:54 AM)

**Comment by Henrycobaltech** [comment]
I have the same dll as @huguesv do but Date Modified is May 11, Language setting is en_US, I also have Chinese IME installed.

**Comment by mwindowshz** [comment]
Save error
![image](https://cloud.githubusercontent.com/assets/17617515/26076504/9cad7f7a-39c1-11e7-898a-0681e0eec4a4.png)

using version 
![image](https://cloud.githubusercontent.com/assets/17617515/26076517/adf8a7c8-39c1-11e7-9f84-db4e692bbff4.png)

Is there a workaround?

**Comment by huguesv** [comment]
No workaround yet, but I would hope that uninstall then reinstall would make it work again.

**Comment by mwindowshz** [comment]
Hi 
Tied removing python from Visual studio , then addining it back.
did not work
Do you think uninstalling Visual Studio completely could help?

**Comment by huguesv** [comment]
That's what I would try, and I would delete the following directories before reinstalling (beware that this will wipe out your settings)
`%localappdata%\Microsoft\VisualStudio\15.0*`
`%appdata%\Microsoft\VisualStudio\15.0*`

And probably remove the `C:\Program Files (x86)\Microsoft Visual Studio\2017` folder too, the installer will tell you if it's already in use when you go to reinstall.

**Comment by huguesv** [comment]
Can anyone check Event Viewer / Windows Logs / Application and see if this logs an error there that has more information than the original stack trace?

Same thing for the activity log? `%AppData%\Microsoft\VisualStudio\15.0<your_id>\ActivityLog.XML`

Does anyone see this error after a clean install of VS 2017? Meaning you didn't have any VS 2017 installed prior to this?

If you've updated from a previous release of VS 2017, which one was it?  15.1, 15.0 or RC from January/February?  The latest RC with Python workload was 15.0.0-RC.3+26109.1 AFAIK.

I'm unable to upgrade from RC.3 to 15.2, the latest it will upgrade me to is 15.0, which doesn't have Python workload.

**Comment by huguesv** [comment]
Another thing to try is to delete the MEF cache folder.

Make sure VS is closed.
Delete `%localappdata%\Microsoft\VisualStudio\15.0_<your_id>\ComponentModelCache`.
Start VS.  It will take longer than usual as it rebuilds the cache.

When the cache is the issue, there's usually an indication that it's the case in the error message, and there isn't any in this bug. I don't have high hopes that this will do anything, but it's easy/quick enough that it's worth trying.

**Comment by mwindowshz** [comment]
Hi Deleting MEF folder did not do anything

Inn windows log,, I am not sure this is relevant but here are some errors:

Activation context generation failed for "C:\Program Files (x86)\Windows Kits\10\bin\arm\signtool.exe.Manifest". Dependent Assembly Microsoft.Windows.Build.Appx.AppxSip.dll,version="0.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.

Activation context generation failed for "C:\Program Files (x86)\Windows Kits\10\bin\arm64\oleview.exe". Dependent Assembly Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="arm64",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.

I still did not try reinstalling visual studio.

**Comment by mwindowshz** [comment]
Full uninstall and reinstall of visual studio worked
Installed 2017 professional.

**Comment by huguesv** [comment]
Thanks for reporting back @mwindowshz and sorry for the trouble.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/issues/3571 - customer has reliable repro

**Comment by zooba** [comment]
Has anyone had VS 2017 Preview installed at all? There may be a potential versioning issue between VS and the preview of the updates that might be at fault.

**Comment by aoime** [comment]
Yes, all machines I have that exhibit this bug had VS 2017 Preview installed when VS 2017 was upgraded to/installed.

**Comment by Funkrusha** [comment]
i had the same problem too, in my case the component was cached in 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions`

the solution was to remove the cached folder, restart visual studio and then vs rebuild the component cache.

hope it will help someone

maybe clean the MEF cache in `%localappdata%\Microsoft\VisualStudio\15.0_<your_id>\ComponentModelCache` before

**Comment by fklier** [comment]
Funkrusha's steps worked for me without needing to uninstall/reinstall anything (thanks!)

After removing the folder containing Microsoft.VisualStudio.VsInteractiveWindow.dll from the IDE\Extensions folder Visual Studio crashed on the next start.  The following start rebuilt the cache and the interactive windows were opening and working normally.

**Comment by pedoc** [comment]
i had the same problem too， the following ways can solve my problem.
In particular, if you are the same as this situation:
vs version:2017 15.2 release

1.check install dirctory,if exists  "`Microsoft.VisualStudio.VsInteractiveWindow.dll`" in "`Extensions`" directory(my case path:`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\lzr5hngx.jje`")
2. clean the MEF cache in `%localappdata%\Microsoft\VisualStudio\15.0_<your_id>\ComponentModelCache`
3.goto `Common7\IDE\CommonExtensions\Microsoft\InteractiveWindow` Directory copy "`Microsoft.VisualStudio.InteractiveWindow.dll`" and "`Microsoft.VisualStudio.VsInteractiveWindow.dll`" replace `step 1` directory same name files.
4.restart vs

postscript：
I noticed that,in "`Extensions`" directory and "`CommonExtensions`",dll version are different,may be vs load first error dll.

hope to help

**Comment by pjwhams** [comment]
I had the same experience of fklier - I followed Funkrusha's steps and I too got the crash on the next run, but it was fine on the one after that.

**Comment by huguesv** [comment]
Looks like these upgrade issues are over now.
