### ISSUE TITLE
Best way to use C# library in IronPython VS shell

### ISSUE THREAD

**Issue by suoranta** [Microsoft/PTVS#2542]
I have a solution with an IronPython project and a C# library project. Working with the IronPython project, I make heavy use of IronPython Interactive shell inside Visual Studio. Referecing C# lib in the IronPython project won't make it load automatically into the Interactive shell. Instead, I have to use clr.AddReferenceToFileAndPath and supply machine-specific full path to the DLL that I actively develop. I am aware that can be done automatically by adding a startup script to the interpreter, but that is somewhat unsatisfying and will affect any solution using the Python environment. Is there a best practice to this?

**Comment by zooba** [comment]
This might be a better question to ask on the [IronPython mailing list](http://ironpython.net/support/), but generally what you would do is specify a search path (via `IRONPYTHONPATH` environment variable - but ask on the list as they probably have better ways to do it when you are hosting) and then you should not have to use the full path to import the DLL.
