### ISSUE TITLE
Can not goto definition

### ISSUE THREAD

**Issue by amos402** [Microsoft/PTVS#2548]
After select a class name by double click, press f12 have no respones.
Version: 3.0.17114.1
Like this:
![default](https://cloud.githubusercontent.com/assets/3406561/26024256/9a9e8228-3800-11e7-99a1-9a09e2c9bd9c.png)

**Comment by huguesv** [comment]
Interesting. If you put the cursor anywhere on the caller, it works fine.  If you partially select the caller, ex. `ASDASDAS` or `SDASDASD`, it works.  But if you select the whole thing `ASDASDASD`, then it doesn't work.

**Comment by huguesv** [comment]
Also reported here: https://developercommunity.visualstudio.com/comments/64750/view.html

Double-click puts the cursor after the last character, and go to definition doesn't work in that case.

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/71319/vs2017-python-go-to-definition-is-not-working.html
