### ISSUE TITLE
Error when running Remove Imports, Current Scope

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#255]
PTVS 2.2 Dev 2015-05-19
VS 2015 RC

Create new python console application
Right Click in editor, Remove Imports, Current Scope

Error message:
```
---------------------------
Microsoft Visual Studio
---------------------------
Specified argument was out of the range of valid values.

Parameter name: position
---------------------------
OK   
---------------------------
```

**Comment by zooba** [comment]
Only occurs when the caret is at the end of the file (and we try to +1 it...)
