### ISSUE TITLE
Can not find Python workload on VS for Mac

### ISSUE THREAD

**Issue by acutexyz** [Microsoft/PTVS#2553]
> To install, run the normal VS installer and select either the Python development workload or the Data science and analytical applications workload.

When installing I have this screen and no mentioning of Python:

![screen shot 2017-05-15 at 1 40 53 pm](https://cloud.githubusercontent.com/assets/536944/26054188/5c565a8e-3974-11e7-959f-0c874a07eff8.png)

**Comment by zooba** [comment]
Yeah, apologies for the confusion. Visual Studio 2017 has Python support in the installer, and Visual Studio Code has an extension available, but there is no Python support for Visual Studio for Mac.

**Comment by acutexyz** [comment]
Alright, thanks!
