### ISSUE TITLE
Can't define TextIOWrapper type

### ISSUE THREAD

**Issue by PacmanLazy** [Microsoft/PTVS#2565]
![default](https://cloud.githubusercontent.com/assets/11561042/26161070/8a589d12-3b2b-11e7-8095-c7d544fad87d.png)
Intellisense doesn't work with code below cause of undefined type. #

**Comment by huguesv** [comment]
I don't think that has ever worked, unfortunately. I've been explained why in the past, but it's been so long I can't remember :(

**Comment by zooba** [comment]
It's because we don't have support for changing the return type based on the arguments.

For example, `open(f, 'r')` and `open(f, 'rb')` have different return types. We can fix this for `open()` by adding a custom specialization (see #731), but there's no general mechanism for this.

**Comment by zooba** [comment]
Actually, since this one is explicitly called out in #731, I'll close this as a duplicate. Thanks for the reminder!
