### ISSUE TITLE
CoreCompile does not exists in the project

### ISSUE THREAD

**Issue by cpoyraz** [Microsoft/PTVS#2570]
When I try to build the python project containing only one file "test.py" with single line code(I know the error is not about that), I get this error "CoreCompile does not exists in the project". What may cause of that?

**Comment by cpoyraz** [comment]
it is fixed after uncommenting CoreCompile tag in project file.

**Comment by it21208** [comment]
Hello cpoyraz, I am facing the same problem I have developed a Python project/solution is VS 2017. Where exactly did you find the CoreCompile tag and in which project file? Thanks (:

**Comment by zooba** [comment]
@it21208 You will have created a file with the extension `.pyproj` at some point - open that in a plain text (or XML) editor and you'll find it near the end of the file.
