### ISSUE TITLE
No error highlighting for clear "NameError"s?

### ISSUE THREAD

**Issue by mdc713** [Microsoft/PTVS#2575]
Suppose I have a script like this:

'''
#!/usr/bin/env python

a = some_variable
'''
That will raise a NameError without fail, yet this kind of very simple error isn't highlighted, and (bafflingly) doesn't even show up when running pylint in VS2017 Preview (or VS2015 for that matter.) Is there something I'm missing, or is this kind of error highlighting just not here? If not, consider this a feature request--I know not everyone likes to use this sort of thing all the time, but for many of us, it helps our productivity immensely.

**Comment by huguesv** [comment]
This kind of highlighting is not there.

You'll get squiggles if the parser finds errors, but we don't attempt to highlight other types of errors, as it is difficult to get it right all the time with a dynamic language like Python.

**Comment by zooba** [comment]
This has been a long-standing feature for us to look at, but ultimately it is incredibly difficult to do well as we rarely know the full context of code.

For example, `exec(your_example_from_above, {"some_variable": 123})` means that there is no longer a `NameError`. It's also likely to be more confusing when we don't highlight less obvious errors but do get some of them - our experience with features like this is that if we can't get 100% or very clearly explain why we got certain answers then we will just be inundated with very specific questions about it. In some cases this is okay, but here we're making a statement about whether someone's code will work or not. Getting it wrong is far more harmful, and if we are only 50% accurate (even without false negatives) we will still convince people to rely on the functionality.

Pylint is transparent and configurable enough to be a good stopgap (as are the other similar tools), and we hope to eventually have a similar tool based on our code analysis. But we don't want to rush out something that is obviously half-done.
