### ISSUE TITLE
Auto detect conda environments

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2581]
Right now I have to add a custom environment for every conda environment that I create.

They appear to be created in a fixed location, we may be able find them automatically, maybe use whatever Anaconda Navigator is using to list them.
C:\Users\huvalo\AppData\Local\Continuum\Anaconda3\envs

![image](https://cloud.githubusercontent.com/assets/1696845/26368968/24e0deaa-3fa8-11e7-899b-0a61e9a10b29.png)

I'm filing this separately from https://github.com/Microsoft/PTVS/issues/358 because I think there is value in detecting the conda environments, even if we don't support conda package management.

**Comment by zooba** [comment]
This part shouldn't be too hard to write, and is going to be necessary to do #358 anyway.

Needs an `IPythonInterpreterFactoryProvider` and that's basically it - the rest is largely going to just work with our default factory implementation. It's even relatively straightforward to inject a new package manager from this point as well (deliberately).

Can be written as a separate extension easily enough. The MEF export of the factory provider is the only important part.

**Comment by huguesv** [comment]
The bulk of this is done. I'll file separate issues for the remaining stuff.
