### ISSUE TITLE
Allow stopping of database refresh

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2582]
I have several database refresh going in parallel that are taking a long time because they have a large number of packages. Some are for conda environments added as custom environments.

Even when I remove the environment in Python Environments window, the database refresh for it doesn't stop. The only way I've found to stop db refresh is to kill the Microsoft.PythonTools.Analyzer.exe process in task manager.

We should have a way of stopping a refresh in the UI, and when an environment is removed from the global list Python Environments window, it probably should stop it as well.

When creating several environments for testing, it's easy to get in a situation where your CPU is fully used by the analyzer processes. Most of the time I don't even care about getting IntelliSense in them.

**Comment by zooba** [comment]
We are not going to fix this - the DB refresh has been removed.
