### ISSUE TITLE
"New Folder" option in context menu

### ISSUE THREAD

**Issue by cigano** [Microsoft/PTVS#2588]
Practicing in a Django Tutorial, I tried to add a new folder using the context menu, but the option doesn't appear.

![pt](https://cloud.githubusercontent.com/assets/1513436/26497350/d28aea24-41f0-11e7-86ad-fb5d67f83010.png)

**Comment by huguesv** [comment]
I was only able to verify VS 2017, where it appeared fine.  I wonder if there's a conflict with DevExpress?  Can you try disabling that extension?

**Comment by cigano** [comment]
In fact there's no way to disable the extension, so I uninstalled the product, and the option reappeared. 

![image](https://cloud.githubusercontent.com/assets/1513436/26538129/ed0599f6-4409-11e7-835c-81f57f8c49c6.png)

So, I can't have DevExpress to have the New Folder option?

**Comment by huguesv** [comment]
I've installed DevExpress on VS 2017 and I can confirm it is working there.
![image](https://cloud.githubusercontent.com/assets/1696845/26595773/6686b4be-4521-11e7-83dc-39c5ee575eda.png)
