### ISSUE TITLE
Use interactive mode checkbox is invisible on high contrast

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2595]
Using the very latest from master.

Regular VS themes are ok.
OS Light and Dark High contrast are not.
When you move the mouse over the checkbox, it becomes invisible.

![image](https://cloud.githubusercontent.com/assets/1696845/26515840/a295ec18-4233-11e7-847c-af0b2643dc28.png)

**Comment by zooba** [comment]
Looks like I assigned checkboxes a hover colour when they really shouldn't have one.
