### ISSUE TITLE
Intellisense: from flask import request | request: <unknown type>

### ISSUE THREAD

**Issue by DubbleClick** [Microsoft/PTVS#2598]
I am importing a bunch of things from Flask (latest version) and Intellisense is working for all of them but the standard Request object "request", which Intellisense does not recognise. Intellisense recognises all other imports and works correctly there.

The code is running, it is however annoying to have most of intellisense break down completely just because it's not able to resolve a single import.

**Comment by zooba** [comment]
When you say "does not recognize", do you mean that it shows up as an unknown type? This is somewhat expected, as Flask uses a wrapper class around a thread-local variable for `request` (and some other globals), which makes it such that it is impossible to determine its true type without an actual request existing.

Our aim is to solve these issues by eventually supporting type hints (#82) and hoping that Flask will also add support for them. There's really nothing else we can reliably do about it with a type this complex right now.
