### ISSUE TITLE
having troubles to start working: IDE freezes completely when I right click and select send to interactive

### ISSUE THREAD

**Issue by chanansh** [Microsoft/PTVS#262]
Hi,
I am new to PTVS (moving from pyCharm). Visual Studio 2013.
I am trying to use Ipython interactive window so to help embedded plots.
Once I run in Python 3.4 I get error Ipython 3.0 not supported.
When I try to used Python 2.7 and right click "send to interactive window" the entire IDE freezes completely.
Frustrating...

**Comment by huguesv** [comment]
Ipython 3.0 support was added after PTVS 2.2 RC was released.  You'll need to install the latest dev build, such as PTVS 2.2 Dev 2015-05-19, available from the github releases page.
