### ISSUE TITLE
Too many requests to pypi.org

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2639]
Apparently we are spamming pypi.org with requests for package data. We should reduce/throttle/whatever we need to do to reduce these.

In theory, we should only be requesting data for visible packages. Perhaps that has broken with the accessibility work?

**Comment by dstufft** [comment]
👍

**Comment by dstufft** [comment]
Just as an FYI, we do have ``Cache-Control``, ``ETag``, and ``Last-Modified`` headers on these URLs and so you should be able to both cache and do conditional GETs against them to reduce the load as well. (I'm assuming that's not the issue here, but just as an additional FYI).

**Comment by dstufft** [comment]
Something interesting I just noticed that might help you debug this: I just turned off pypi.org for a couple of minutes (it was returning a 503 error). It's back on, but that seems to have completely stopped the deluge of requests. In the graph below, pypi.org was serving a 503 from approximately where you see the # of requests take a nose dive until approximately where the line is. After that point is was serving responses again correctly.

<img width="1083" alt="screen-shot-2017-06-03-12-39-10" src="https://cloud.githubusercontent.com/assets/145979/26755369/c705918a-4859-11e7-9cab-490595ca15da.png">

I could be completely off base, but this seems like possibly some sort of loop or something that is checking for a successful return but the conditional is inverted or something. I don't know your code at all but I thought this might be useful information to figuring it out.

**Comment by zooba** [comment]
Once again, I suspect @crwilcox and his bot (or possibly someone else's bot) is spamming and apparently not handling 503 correctly :) IIRC, @takluyver was also running a script to gather metadata, so maybe his broke?

The code we have in VS is running on client machines, so if they're all spamming pypi it's going to look like an attempted DDoS and should have restarted after that line. Having the UA string will help be certain, but in any case I do intend to look into why we're making as many requests as we are (once I finish dealing with the fallout of an office relocation...)

**Comment by dstufft** [comment]
FWIW it has ramped back up again since then (now up to 1500 req/s, not near the 7000 req/s we were getting before, but almost as much as real PyPI's 2000 req/s). It was uh, like 10 different IP addresses, with a plurality belonging to Microsoft but some random home ISPs too and some finacial services company. So not exactly a highly distributed DDoS, but not a single machine either.

Let me know I can expect the UA to start showing up and I can track the requests at that point to see if they stay UA-less or if they start shifting over to the UA you add.

**Comment by dstufft** [comment]
Also no rush! The requests are highly cacheable so it's not really affecting Warehouse itself, it's just adding more load to our donation from Fastly (though since they are cacheable, I suspect less load then if they were not).

**Comment by zooba** [comment]
The UA won't show up for weeks to months, unfortunately. We're basically boxed software, so it's a slow release cycle (or users get too many "you need to restart VS now" prompts and start ignoring them). Which also means the problem will slow down just as slowly.

Can you email me the Microsoft IP addresses? I might be able to track down the specific machines that way and see what they are (e.g. CI machines vs. desktops vs. etc.)

**Comment by dstufft** [comment]
@zooba Yea I figured, but I also assumed that some folks are going to running ``master`` or something (though I could be wrong!) and we'd see some requests start to come in following a similar pattern (or a different pattern to rule out).

**Comment by takluyver** [comment]
> IIRC, @takluyver was also running a script to gather metadata, 

I was thinking about this, but not running it at any scale. @LuisAlejandro's [PyPIContents](https://github.com/LuisAlejandro/pypicontents) project is something similar to what I was thinking - that uses Travis CI to collect the data.
