### ISSUE TITLE
Open interactive python window error

### ISSUE THREAD

**Issue by roberthannah89** [Microsoft/PTVS#2641]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2' from assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

**Comment by turogg** [comment]
I have the same issue on my home PC with only VS2017 installed. This is with Python 3.6 (64 bit) environment. Also, pip installation (e.g. bitarray) fails with a complaint about requiring VC++ 14.0 in case that's related/relevant. At work things work just fine (there I have VS2013, VS2015 and VS2017 installed). Both running the latest Win10 (not the preview stuff).

**Comment by zooba** [comment]
We've been seeing this a few times, and right now we suspect (but have not yet confirmed) that it's an upgrade issue from a previous version.

Can you try uninstalling and reinstalling VS? If you've only installed the Python workload, you should only need to remove/replace that workload, which may save you some time (and shouldn't lose your settings). 

If that works, could you then use the tool at https://aka.ms/vscollect to collect your setup logs into `%TEMP%\vslogs.zip` and email them to ptvshelp@microsoft.com? Those should provide enough information to help us track down exactly why this is happening.

**Comment by zooba** [comment]
Have either of you had VS 2017 Preview installed at all? There may be a potential versioning issue between VS and the preview of the updates that might be at fault.

**Comment by turogg** [comment]
I did have the preview installed.

**Comment by Blealtan** [comment]
@zooba I'm sorry but it seems that reinstalling will not work for me. In fact I've installed python workload when using preview, but later on removed it when 2017 came to public officially. Recently I add it in again, and this error occurs; I mean, it should be a 'fresh' install now on my PC. Could you please help?

**Comment by huguesv** [comment]
We'll just keep one of these open: https://github.com/Microsoft/PTVS/issues/2534
