### ISSUE TITLE
Random endless tests scan

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#2645]
Sometimes it ends in 2 minutes, sometimes it never ends (currently it's 3 hours). Meaning I can't start tests. Restart sometimes helps.

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.3.0 Preview 2.0 [26602.0.d15rel]
VisualStudio.15.IntPreview/15.3.0-pre.2.0+26602.0.d15rel
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Python   3.0.17132.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

**Comment by zooba** [comment]
Since you know where my office is, can you grab me next time it happens? :)

**Comment by lmazuel** [comment]
Sure :)

**Comment by zooba** [comment]
I keep seeing this for C#, and haven't been able to repro for Python. Going to assume it belongs to the test window team and close this.
