### ISSUE TITLE
Importing my own *.py files: Intellisense and Interactive Window don't see my file

### ISSUE THREAD

**Issue by piotrek-k** [Microsoft/PTVS#2647]
I'm having some problems with loading my `*.py` files located in another directory.
Although it works fine when I'm pressing F5 to debug, IntelliSense doesn't seem to see `email_preprocess` function. Also, I would like to run my entire `nb_author_id.py` file in Python Interactive Window. I can't, becuase as you will see on screenshot, it throws `No module named email_preprocess`.
![email_preprocess](https://cloud.githubusercontent.com/assets/5506878/26831227/e262f6ce-4acb-11e7-95a4-49a4dbb5970b.png)
What is the reason of that behavior?

**Comment by zooba** [comment]
This likely means that `email_preprocess` is not a real packages. If you have an empty `__init__.py` file in the directory, then it should work fine.

If it's still not working, can you show me the layout of all your files? Just filenames will be sufficient.

**Comment by piotrek-k** [comment]
@zooba Thanks, Intellisense started to recognize `email_preprocess` when I created `__init__.py` file in directory where `nb_author_id.py` is.

Unfortunately, Interactive Window still doesn't recognize it. It may be that it works on different starting path and it looks for `../tools/` in different place than it should. Can I somehow check and modify where in folder tree does Interactive Window work?

> can you show me the layout of all your files? 

It's actually [this github repository](https://github.com/udacity/ud120-projects). I'm working on ` 	./naive_bayes/nb_author_id.py` file.

**Comment by zooba** [comment]
Yeah, so while it's great to have scripts arranged in folders, once you want to use `import` between them you really need to change them into actual packages by adding that file.
