### ISSUE TITLE
Test explorer highlight error

### ISSUE THREAD

**Issue by lmazuel** [microsoft/PTVS#2651]
Let's assume I launched one test only:
![image](https://user-images.githubusercontent.com/1050156/26844560-abe5aad8-4aa8-11e7-9d78-13dd9c714b5a.png)

I continue to work using PTVS, I see regular scan of tests. And eventually this I see highlighted stuffs I didn't touch:
![image](https://user-images.githubusercontent.com/1050156/26844843-982ccb9c-4aa9-11e7-8594-3f3d3149b5a5.png)

![image](https://user-images.githubusercontent.com/1050156/26844860-a9d2137a-4aa9-11e7-898f-c4b2774bad9f.png)

I see no reason for this highlight.

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.3.0 Preview 2.0 [26602.0.d15rel]
VisualStudio.15.IntPreview/15.3.0-pre.2.0+26602.0.d15rel
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Python   3.0.17132.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

**Comment by lmazuel** [comment]
As I said, eventually highlight more and more for no reason (I'm not even testing anything):
![image](https://user-images.githubusercontent.com/1050156/26846674-572fb324-4aaf-11e7-8f3d-5028f74c51f9.png)

**Comment by zooba** [comment]
I think this is by design for whenever VS detects new tests are available. This could be happening if the line number changes (since it should then get a different ID), or it could be a number of other reasons.

Would be nice if we figure out how to ensure test identity in a way that prevents existing tests being "recognized" as new ones.

**Comment by lmazuel** [comment]
I understand. But usually nothing change, not even the line number. For instance, when `LegacyMgmtWebsiteTest` is highlighted, there is no way I even opened the file where the test is, or even open any file related to this test (just talking about opening, not even editing).

**Comment by huguesv** [comment]
A lot has changed in both VS test explorer since then and our test adapter (in 16.3). Discovery is now more under the user's control as we only trigger it when you save a file.
