### ISSUE TITLE
"Add new project" in a solution and chose "From Existing Python code" creates a new solution

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#2652]
I have an existing project and I want to add new project inside:
![image](https://user-images.githubusercontent.com/1050156/26846932-20d5812c-4ab0-11e7-9762-4f72199e9b9b.png)

I pick "From existing Python code" and fill the correct location and name:
![image](https://user-images.githubusercontent.com/1050156/26847091-a260208a-4ab0-11e7-9070-88ece2a2d903.png)

I hit OK and got a wizard. This is strange, since I already filled the folder, but let's continue:
![image](https://user-images.githubusercontent.com/1050156/26847131-cbedf3fa-4ab0-11e7-9ef3-1561110003cd.png)

I click on "finish" (I tried "next" too but does not change anything).

This closes my current solution and open a new one, this is not what I wanted:
![image](https://user-images.githubusercontent.com/1050156/26847203-07047e14-4ab1-11e7-9d82-331e58fc8029.png)

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.3.0 Preview 2.0 [26602.0.d15rel]
VisualStudio.15.IntPreview/15.3.0-pre.2.0+26602.0.d15rel
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Python 3.0.17132.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

**Comment by zooba** [comment]
#13 is the same bug.
