### ISSUE TITLE
Q: Wildcards in pyproj file to avoid manually adding files to solution?

### ISSUE THREAD

**Issue by Preston-Landers** [Microsoft/PTVS#2653]
Hello. I have a large Python project that is developed by a team that mostly uses PyCharm and vim.  I would like to support Visual Studio as a viable option. I'm testing this with VS 2017 Community.

My problem is that it wants to list each Python source file in the `.pyproj` file. As files are added or deleted by developers who aren't using VS (most of them) they aren't going to be maintaining the VS project. So it looks like new files won't show up there automatically, and `.pyproj` is also littered with deleted files.

Is there a way to configure the `.pyproj` file to see all Python files automatically in certain designated directories? I've tried something like the example below and it doesn't work. VS Solution Explorer shows the named folders but none of the Python files inside. 

The problem is most acute for my Python files but a similar problem applies to my static web resources folder where I don't want to have to list out the files there either.

In this example, `wtlib` is a folder in my PYTHONPATH that contains .py files plus package folders. In PyCharm I can just designate that folder as a "source folder" in the settings and all is well.

```
  <ItemGroup>
    <Content Include="wtp\htdocs\**" />
  </ItemGroup>
  <ItemGroup>
     <Compile Include="wtp\wtlib\*.py" />
     <Compile Include="wtp\wtlib\**\*.py" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wtp\wtlib\" />
    <Folder Include="wtp\wtlib\**" />
  </ItemGroup>
```

Any thoughts would be greatly appreciated.

**Comment by zooba** [comment]
Right now, there is no great way to do this :( The wildcards should work, but will quickly break down if you modify any files in the project (we'll convert them to full lists of files). Manually keeping the project up to date ("Show all files" and the `Include in Project`/`Exclude from project` commands are very useful for this).

What we're working on longer-term is full support for "Open Folder". This will let you use all the functionality of VS without having to create a project file. Right now, there is some basic debugging and Intellisense support when you use Open Folder, which may be sufficient for you (it's roughly at parity with the Python support in VS Code), but as more updates are released you should see it start to improve.

See #1556 for the main issue where we are tracking work on Open Folder.
