### ISSUE TITLE
Does Visual Studio have a compile command for Python?

### ISSUE THREAD

**Issue by gidmeister2** [Microsoft/PTVS#2656]
Python is an interpreted language (line by line).  Does Visual Studio offer a "build" or "compile" option for it?

**Comment by huguesv** [comment]
Not by default (except for web projects).

You can enable build by uncommenting the CoreCompile definition in the .pyproj file. Then you'll be able to customize the build to do whatever you want, and if all you need is pre or post-build custom steps, then those are already declared for you.

For example I've changed mine to print a message in post-build:
```
  <!-- Uncomment the CoreCompile target to enable the Build command in
       Visual Studio and specify your pre- and post-build commands in
       the BeforeBuild and AfterBuild targets below. -->
  <Target Name="CoreCompile" />
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
    <Message Text="Hello world" Importance="high"/>
  </Target>
```

**Comment by gidmeister2** [comment]
Thanks for the answer.

**Comment by Saibamen** [comment]
`dotnet build` but need to set `MSBuildExtensionsPath32` system variable.
Bug: https://developercommunity.visualstudio.com/content/problem/465815/msbuildextensionspath32-is-not-added-to-system-var.html
