### ISSUE TITLE
running 2 scripts (gui.py and pykinect.py) simultaneously

### ISSUE THREAD

**Issue by IsidorosK** [Microsoft/PTVS#2662]
Hello . 
I am using the pyKinect script for a project and I am facing an issue and I need some help. 
I wrote a script for a gui (with PyQt4) and what I want is when I click a button ( Sit) to open the Python Kinect Demo and the gui continue to run (and not showing me Not Responding) . 
Can someone help me ? 

[gui.zip](https://github.com/Microsoft/PTVS/files/1066398/gui.zip)

**Comment by zooba** [comment]
From a quick look at your script, you probably want to investigate the [subprocess](https://docs.python.org/3.6/library/subprocess.html) module, which is meant as a replacement for `os.system`. If you use `sys.executable` as the first argument, it will run with the same copy of Python as was used to start the initial script.
