### ISSUE TITLE
No Cookiecutter Template in VS2013

### ISSUE THREAD

**Issue by Iceman121** [Microsoft/PTVS#2663]
Hi,
I'm running VS2013 Community on Windows 8.1, with PTVS 2.2, Python 3.5.

I have cookiecutter installed on my system, which I can access through command line. However, cookiecutter templates don't show up in my project templates window. 

From documentation [here](https://docs.microsoft.com/en-us/visualstudio/python/cookiecutter), I got the following instruction:
**It's included with Visual Studio 2017 and can be installed separately in earlier versions of Visual Studio.**

But even though I did install PTVS separately, cookiecutter doesn't show up as a project template.

Any thoughts on this?

**Comment by zooba** [comment]
The newest features are only being added to Visual Studio 2017. When you install PTVS separately, you are installing our older versions that are not actively maintained anymore.

Integration for cookiecutter templates is only available in VS 2017.
