### ISSUE TITLE
VS fails to identify anaconda x64 as python

### ISSUE THREAD

**Issue by gilbertw** [Microsoft/PTVS#267]
We should be auto-detecting the python process as python.

Start Anaconda x64
Debug attach
python.exe shows up as x64 and not Python, x64

**Comment by int19h** [comment]
It should actually be just "Python", we don't want mixed-mode by default.

**Comment by zooba** [comment]
What version of Anaconda? 2.7 or 3.4? Can you check whether they're using the original Python binaries or if they've rebuilt them (should be able to tell from `sys.version`).

**Comment by int19h** [comment]
So I cannot repro this with the most recent sources on either my work or my home machine with 64-bit Anaconda 2.7.

**Comment by gilbertw** [comment]
I was using an older anaconda, 2.1.  (python 2.7.8 64-bit)

**Comment by zooba** [comment]
Do we have a recent repro of this? Or can we close

**Comment by gilbertw** [comment]
This was due to the NTVS PTVS guid collisions.  This is now fixed.
