### ISSUE TITLE
REPL comments handling different from command line python

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2682]
In VS Python interactive window, you can't just type a comment, it will keep prompting for input until you also type code. That's not the case when you run python.exe from a command prompt.

Affected tests:
ReplWindowUITests.ReplWindowPythonTests.Comments
ReplWindowUITests.ReplWindowTestsDefaultPrompt.CommentPaste

![image](https://user-images.githubusercontent.com/1696845/27239637-9c8aaf08-5286-11e7-9b44-74c6a85898a8.png)

![image](https://user-images.githubusercontent.com/1696845/27239650-ac451d66-5286-11e7-868c-3172b51b108d.png)

**Comment by zooba** [comment]
We should probably fix this by making the empty line check override our "is it a real statement" check.
