### ISSUE TITLE
Images in REPL no longer auto minimize

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2683]
It used to be that submitting some input to the REPL after an image was received would automatically make the previous image(s) smaller.

This doesn't seem to work anymore, and I'm not sure if that's intentional or not (did we lose this with the Roslyn REPL?)

I personally don't really care for it, but the `ReplWindowUITests.ReplWindowPythonTests.InlineImage` test is expecting the minimizing behavior.

**Comment by zooba** [comment]
Fix the test - I think the current functionality is fine, and nobody has commented on it.
