### ISSUE TITLE
Unsupported Python Version: 3.6

### ISSUE THREAD

**Issue by avinavsinha** [Microsoft/PTVS#2684]
While trying to create a new "Python Application" project on Visual Studio I get an error stating "Unsupported Python Version: 3.6". Any idea how I can fix this? Thanks in advance.

I have Microsoft Visual Studio Professional 2013 Version 12.0.21005.1 REL. 
For Python, I use version 3.6.0. 
For PTVS, I have version 2.2.2 VS 2013.

**Comment by avinavsinha** [comment]
Figured it out.

**Comment by nash-dev** [comment]
What did you do?
