### ISSUE TITLE
Python not showing exception hit

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2707]
I turned on Python exceptions, but it just breaks in the debugger and doesn't pop-up the exception window like I'd see in C#. There's no indication that I hit an uncaught exception here except if I look at my Locals window. I would expect the standard VS Exception window to pop-up to give me options to look up help on the exception or copy it to my clipboard or to ignore this type of exception in the future. 

Reported at https://developercommunity.visualstudio.com/content/problem/55532/python-not-showing-exception-hit.html

**Comment by zooba** [comment]
Okay, I'm having trouble getting a repro going too.

@crwilcox - can you email (internally) the code you were hitting this on and enough info to make it repro? A live machine I can remote to would be perfect

**Comment by sergey-vdovin** [comment]
having the same issue - only first exception window is shown.
the current "workaround" is to relaunch visual studio

**Comment by sergey-vdovin** [comment]
closing the solution and opening it again also works as workaround

**Comment by huguesv** [comment]
@sergey-vdovin we haven't been able to get a consistent repro (I've seen it once during remote debugging then never again). Any additional information you can provide would be greatly appreciated. We still don't know what triggers this, and if it's a timing issue that makes it hard to repro.

Do you have some minimal Python code that you can share that triggers this issue?
Are you using local F5 debugging or did you do a regular attach or ptvsd attach?
Does the rest of the debugger functionality continue to work once the exception popup stops appearing?

**Comment by sergey-vdovin** [comment]
@huguesv  please check the attached zipped flv recording:

[2017-07-01 04-59-01.zip](https://github.com/Microsoft/PTVS/files/1116726/2017-07-01.04-59-01.zip)

**Comment by huguesv** [comment]
Thanks @sergey-vdovin !

I tried your example code with PTVS build 17160 (15.3.0 Preview 3.0) and I could not reproduce it.

On the same machine I also installed PTVS build 17114 (15.2, same build as you) and I am able to consistently repro the issue with it.

Given how much trouble I've had trying to repro on 15.3, and how easy it was on 15.2, I'm hopeful that general debugger fixes that went in since then have fixed this, or improved it greatly.

If you'd like to try out the preview of 15.3, you can click on the "early preview access" links at https://www.visualstudio.com/downloads/

**Comment by sergey-vdovin** [comment]
Thank you @huguesv 
will think about the preview
it is just a bit strange that not so many people are reporting the problem: PTVS build 17114 (15.2) seems to be the latest release version. perhaps downgrade is another variant to resolve (release variant).

**Comment by syagev** [comment]
For me it's also consistent on PTVS build 17114 (15.2)
Running a preview parallel installation isn't easy... Any expectation on when this will make release?

**Comment by sergey-vdovin** [comment]
+1:
questions to those who knows ):
1. when this 15.3.0 with "general debugger fixes that went in since then have fixed this" is going to come?
2. if it is possible to help it to come faster (before 15.3) - like voting somewhere?

**Comment by zooba** [comment]
@syagev Have you had trouble running a parallel Preview install with VS 2017? A huge amount of work went into making this possible, and I do it all the time without issue.

@sergey-vdovin Can't tell you (not up to me when dates are announced), and no, it's not possible.

**Comment by syagev** [comment]
Wouldn't call it trouble, but I'm running a heavy VS Enterprise install with a lot of customization and personalization... managing two of these is not easy (and also may take up quite some disk space..)

But I'll consider doing so nonetheless!

**Comment by sytelus** [comment]
I also just hit this issue with Python on VS 2017.
