### ISSUE TITLE
TextChanged detection not working for some django editing tests

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2719]
Affected tests:
DjangoUITests.DjangoEditingTests.IntellisenseCompletions2
DjangoUITests.DjangoEditingTests.IntellisenseCompletions5
DjangoUITests.DjangoEditingTests.IntellisenseCompletionsJS

They all fail with "Failed to see text change"

We have what appears to be inaccurate logic that counts the delta in buffer size by looking at `TextContentChangedEventArgs.Changes`, so see if typing of the insertion text has completed.

It doesn't seem to consider special characters that we put in insertion text for CTRL+SPACE and 1 sec delay, which won't be added to the text buffer. But even with that taken into account, for those failing tests, we still see a smaller delta than we expect.

In other tests, the delta reported by the Changes collection is actually larger than what we inserted, which makes me think this isn't what we should be looking at.

**Comment by zooba** [comment]
Good analysis. I agree, let's see if we can find a better way - perhaps we need to get the `ITextSnapshot` before and after?
