### ISSUE TITLE
REPL UI tests need to set "interactive mode" option

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2725]
Right now the tests initialize the REPL by passing an `useIPython` bool which turns into a `executionMode` string parameter at some point, which is passed all the way down to `ActivateInteractiveWindow(VisualStudioApp app, string executionMode)` which ignores it.

That means they end up using whatever mode happens to be set as default for the interpreter.

Output text comparison is also not working right when in 'interactive mode'. I think it may have worked in the past thanks to the ability to customize prompts, but that is no longer an option with the Roslyn interactive window (the test settings class has properties for them, but they are not used). It tries to compare the IPython prompts assuming that they are constant, which they aren't (index is incremented for each prompt).

We should also allow the use of Anaconda for running REPL UI tests.

**Comment by huguesv** [comment]
I have work in progress for all of these.

**Comment by zooba** [comment]
Is your work to add better hooks for tests? If so, go ahead. They can and should override whatever environmental settings exist.

I don't want to programmatically expose the default mode for environments, as that's really just a user text file referencing a Python class (which has been handy for testing my work on #2722 :) ).
