### ISSUE TITLE
opened files don't completely refresh when switching between python 2 and 3

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#273]
PTVS.Dev.2015-05-28.VS.2015
Add 2 interpreters to your project (2.7 + 3.5)
Make 2.7 active

Type:
```
print('hello')
```

Notice print is blue.
Switch to 3.5.
Notice print is still blue.
Close & reopen the file, it's no longer blue.

**Comment by zooba** [comment]
Workaround is to close and reopen the file.
