### ISSUE TITLE
Incorrect status when editing tests

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#2734]
Not sure this is a terrific issue, but I guess worth mention.

I have three tests:
![image](https://user-images.githubusercontent.com/1050156/27566507-a3d2e3a4-5a9a-11e7-9c6f-0eb0fc95d6f8.png)

I make something in the file in the second test (features, in term of order in the file, not UI order). Quickly when the python file becomes invalid, the test three disappear (but not test two, for some reason):
![image](https://user-images.githubusercontent.com/1050156/27566659-83c290d6-5a9b-11e7-874f-a3d2ca9c7e39.png)

Once I fix the test. The code of method two (features) is not the same and method three (delete) didn't change, otherwise status of test two is still ok (even with changed code), and I lost test three status (even with unchanged code):
![image](https://user-images.githubusercontent.com/1050156/27566700-bd30f948-5a9b-11e7-991c-b516537e18e9.png)

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.3.0 Preview 2.0 [26602.0.d15rel]
VisualStudio.15.IntPreview/15.3.0-pre.2.0+26602.0.d15rel
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Python   3.0.17132.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

**Comment by zooba** [comment]
I suspect this is exactly the same issue as the one you filed about tests appearing and disappearing - VS maintains the pass/run/not run/failed state of each test, and our responsibility is to provide a stable identifier. If we do that properly, then all of these issues should be resolved.

**Comment by lmazuel** [comment]
I think you're right, but I thought that an interesting testcase for the future (then the issue)

**Comment by zooba** [comment]
The related issue is #2651, so I'll close this (but the reference will stay so we can try to test for this case).
