### ISSUE TITLE
Publish python scripts using SSH

### ISSUE THREAD

**Issue by stamerlan** [microsoft/PTVS#2738]
Hello,

It would be great if python scripts could be copied to remote machine using SSH.
It could be used to develop various python daemons on Linux or python applications running on Linux.

**Comment by zooba** [comment]
I agree, this would be great.

Previously we've been blocked by not having a convenient SSH library we could include with Visual Studio (without getting into complicated licensing issues), but I believe the C++ team has gone through the trouble so this should be much easier for us to do now.

Issues #763 and #1237 are related, but this issue represents a prerequisite for those and should be easier to implement on its own.
