### ISSUE TITLE
unable to debug remotly using ptvsd on VS17

### ISSUE THREAD

**Issue by ag3ntsim0** [Microsoft/PTVS#2739]
hi,
i used ptvsd for awhile using VS15 to debug bunch of python scripts , and right now i have installed VS17 and i have tryied to debug on it , unfortunately it doesn't work ,
it says that it cannot find the running script : "could not connect to remote  python process at ..., plz make sure the process has called ptvsd.enable_attach() and is still running"
"unable to connect to .... operation not supported .unknown error: 0x801004005"
of course my script has ptvsd.enable_attach() and it is running...
i just want to confirm i do the same process on VS15 and it works great !

**Comment by denfromufa** [comment]
You need to update ptvsd to latest from PYPI.

**Comment by ag3ntsim0** [comment]
i guess i have the latest version ptvsd==3.0.0

**Comment by huguesv** [comment]
Latest version is 3.1.0
https://pypi.python.org/pypi/ptvsd/3.1.0

3.0.0 won't work with VS 2017 (Version 15.2)

**Comment by ag3ntsim0** [comment]
i did upgraded into 3.1.0 , but i'm still facing the same error !

**Comment by huguesv** [comment]
I would advise that you print the version from your remote script, just to be sure:
```
print(ptvsd.__version__)
```

Remote debugger should work the same as in VS 2015. There was a large rewrite of the protocol, so there's a possibility that bugs were introduced.

If you can show us your `enable_attach` call, as well as what you paste in the attach dialog, that could be useful.

**Comment by ag3ntsim0** [comment]
@huguesv  thank you a lot , i forgot to upgrade the package on my server (i upgraded just in my local machine on VS python env) ! it was on 3.0.0
after upgrading it it worked successfully , thank you

**Comment by davidalbertonogueira** [comment]
I have ptvsd==4.2.3 in the remote server.
I'm using Visual Studio Enterprise 2017 version 15.9.1 on my local machine, and I also have this error message:
"could not connect to remote python process at ..., please make sure the process has called ptvsd.enable_attach() and is still running"

**Comment by huguesv** [comment]
@davidalbertonogueira does it work with a slightly older release of ptvsd, such as 4.2.0? Make sure you have "Use legacy debugger" option **disabled** in tools/options/python/debugging. For further help, please provide the command line you used to launch the script, and any ptvsd calls you have in your script.
