### ISSUE TITLE
CLR breaks mixed debugging

### ISSUE THREAD

**Issue by VenturaFranklin** [microsoft/PTVS#2741]
Following the example here: https://docs.microsoft.com/en-us/visualstudio/python/cpp-and-python
When I set the option for /clr under: Configuration Properties --> General --> Common Language Runtime Support see image:
![image](https://user-images.githubusercontent.com/2513831/27663966-e11aec4a-5c19-11e7-937c-da7f2c5b09b1.png)
 You then have to disable /Gm, /EHs, and /RTC1.
This will build successfully in debug and release.
However, breakpoints in the c++ code do not trigger, breakpoints in the python code trigger fine.
I believe this is because the symbols are being unloaded when starting the debugger, see image:
![image](https://user-images.githubusercontent.com/2513831/27664130-9a2d82ec-5c1a-11e7-8b13-74fb09a3e100.png)

I can attach to a process running the imported library and then the debugger triggers for the c++ code fine.
When you set "No Common Language Runtime Support", the debugger triggers in both the c++ and python code correctly. The issue is, I would like the clr support.

I am using: Visual Studio Pro 2015 Update 3, PTVS 2.2.50113.00, Python x64 3.5 

I have tried:
- Setting Configuration Properties --> Linker --> Debugging --> Generate Debug Info to "Optimize for debugging", that did not work
- Setting Tools --> Options --> Debugging --> General --> "Use Managed Compatibility Mode" related to this issue: https://stackoverflow.com/questions/33308480/visual-studio-debugger-stops-hitting-breakpoints-in-mixed-debugging-mode , that did not work
- Setting Configuration Properties --> Debugging --> Debugger Type to "Mixed", that did not work
- Excluding the three dll that follow the unloading of the superfastcode.pyd in the picture above, the modules were still loaded anyways.

Short of taking out the clr code, what else can I try?
Thank you for your help,
Frank V.

**Comment by denfromufa** [comment]
Have you tried pythonnet? Here is wiki for debugging with pythonnet:

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython

Once upon a time I did use C++/CLI to embed CPython and mixed-mode debugging worked great (search PTVS codeplex discussions), but many things changed since then and I abandoned C++/CLI due to unresolved memory leaks.

**Comment by zooba** [comment]
I believe the /clr option creates .NET assembly implemented with native code rather than a native DLL that hosts the .NET Runtime. You'll either need to use pythonnet, which _does_ host a .NET runtime, host it yourself in a truly native DLL (not recommended - this is really hard), or create a separate executable that can communicate over stdin/out or a socket with the Python process.

**Comment by VenturaFranklin** [comment]
I did not think that I needed a different python distribution as the dll compiles and loads and functions correctly into regular python without issue. This is primarily to debug the c++ side of things during development.

**Comment by zooba** [comment]
In that case, perhaps you need to Debug/Attach with Managed, Native and Python debugging selected? That "works", but we don't claim to support it.

**Comment by VenturaFranklin** [comment]
I was able to start python in a command prompt, import my pyd file into that command prompt, and then attach a debugger to that. When set to automatic it works fine. If I specify Managed, Native, and Python it works as well. I do get a failed message, but the breakpoints in the c++ trigger correctly.
![image](https://user-images.githubusercontent.com/2513831/27702134-f79b0fd8-5cb7-11e7-8c5d-577cbd317587.png)

It also works when I change the Startup Project from the Python project to the c++ project and start "Local Windows Debugger" and then import the breakpoints then trigger correctly.

Looking at the output of the debugger from these different scenarios I think this is actually because of the skipping of loading and the NOT unloading of the symbols for the pyd file because of the option "Just My Code".
> 'python.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
> 'python.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'E:\workspace\TestPythonVS\x64\Debug\superfastcode.pyd'. Symbols loaded.
> 'python.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

The main difference is that after Unloading the Symbols for the pyd are loaded again but in a different way:
> 'python.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'E:\workspace\TestPythonVS\x64\Debug\superfastcode.pyd'. Symbols loaded.

Whereas previously it was loaded:
> 'python.exe' (Win32): Loaded 'E:\workspace\TestPythonVS\x64\Debug\superfastcode.pyd'. Symbols loaded.

Is there a way to force this "Default Domain" loading for the pyd file? I have tried adding all of the symbols that are skipped loading (according to the output) to the "Specify excluded modules" Symbols options, but this does not help.

In the end, I can debug the c++ side of things fine. I can separately debug the python code, but this is preventing the "mixed" debugging.

**Comment by int19h** [comment]
For Python debugging, the only thing that it should care about is whether symbols are loaded for python*.dll - can you check the messages for those in the log? python.exe doesn't actually matter.

**Comment by VenturaFranklin** [comment]
Yes the python35.dll is loaded fine.
