### ISSUE TITLE
Mixed mode debugger does not show Python stack

### ISSUE THREAD

**Issue by VojtechFried** [Microsoft/PTVS#2743]
I use VS2017 v15.2. I have installed Python 3.6.0-64bit with debug symbols (using Python installer, not VS installer). I attach (from a C++ project/solution) to a running python process with both Native code and Python code. Instead of python stack, I can only see Native to Python Transition and Python to Native Transition. When I set a breakpoint to a python file, it sort of works - the debugger stops and shows me the last native function that called the python code, but still no python stack, only Native to Python Transition.

When I try just Python code (no Native code) when attaching, it sometimes works, sometimes crashes VS when attaching.

**Comment by zooba** [comment]
This is the caused by #2365, which we have already fixed. If you install VS 2017 Preview, then you can have the fix now, or it will be available when the next update is released.
