### ISSUE TITLE
exceptions on python 3.5 when debugging

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#275]
PTVS.Dev.2015-05-28.VS.2015
Python 3.5.0b1 64-bit (installed per-machine, see the path in the messages below)
Enable Just My Code in debugging options

My code:
```
from json import dumps

print('hello')
```

Press F5 and you'll get a series of exceptions that break in the debugger:

```
FileNotFoundError was unhandled by user code
Message: [WinError 2] The system cannot find the file specified
```

```
FileNotFoundError was unhandled by user code
Message: [WinError 2] The system cannot find the file specified
```

```
zipimport.ZipImportError was unhandled by user code
Message: not a Zip file
```

```
FileNotFoundError was unhandled by user code
Message: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\Python 3.5\\lib\\json\\__init__.cp35-win_amd64.pyd'
```

```
FileNotFoundError was unhandled by user code
Message: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\Python 3.5\\lib\\json\\__init__.pyd'
```

etc.

**Comment by huguesv** [comment]
Same thing happens with my Python 3.5.0b1 32-bit, which is installed per-user.

**Comment by zooba** [comment]
Guessing importlib has changed its name somehow and we need to update the list of things not to debug.

**Comment by int19h** [comment]
Doesn't repro on 3.5b2 anymore - I guess it had to do with that importlib issue that b1 had.

**Comment by huguesv** [comment]
I still can.  I compared with another VS and realized that this only repros if you have "Just My Code" enabled.  Only affects Python 3.5.
