### ISSUE TITLE
Tests discovered but not visible in Test Explorer

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2758]
We have seen some cases where tests are discovered and send back as part of the extension request, but never show up in Test Explorer.

I've got logs from a user showing that they are found properly. Nothing jumps out as being invalid, but we do need to investigate this to see what may be failing along that path.

**Comment by jenstMS** [comment]
Repros both on my desktop and on my laptop

**Comment by jenstMS** [comment]
Looks like once the python env is configured correctly, they become discoverable. Should test discovery depend on env. configs?

**Comment by zooba** [comment]
So we extract tests from our code analysis (so that we do a better job handling subclasses of `TestCase`), and code analysis depends on a few more things than we technically need.

When you say "configured correctly," do you mean the completion DB is up to date? Or was there some other setting you discovered was incorrect?

**Comment by jen4ikSt** [comment]
My virtual environments were misconfigured. I loaded code that was initially committed on laptop, which has a different version of anaconda than the desktop. So the virtual env manager freaked out

**Comment by jenstMS** [comment]
My virtual environments were misconfigured. I loaded code that was initially committed on my laptop, which has a different version of anaconda than the desktop. So the virtual env manager freaked out

**Comment by zooba** [comment]
Freaked out how? (Obviously we don't want it to freak out :) )

**Comment by jenstMS** [comment]
Was helpless. Didn't event default to the basic python install that comes with VS. Didn't even search PATH (we know that would've worked because cmd python -m unittest worked)

**Comment by jenstMS** [comment]
But you don't need to modify PATH, you just need to grab info from it. If people want Python to work from CMD, they'll have to add to path either during install or manually (up to them). You can just piggy-back on PATH for some default version that the user would have.

The virtual env manager did have the default Python version on my machine listed properly, as well as 2 Anaconda versions - the one that was on the desktop, and the one it inherited from the laptop code pull. I'd assume that if PTVS are there, then at least default PTVS python exists. Should be enough to default to that when dealing with unittests.

I'd expect unittests to be discovered, but fail on missing pandas etc since it's not part of the minimal python install.

**Comment by zooba** [comment]
The problem is, "dealing with unittests"=="normal code analysis", which means if we pick a random Python version then we'll display errors and warnings all over the place that may be incorrect.

A better result would be to display a specific message saying that "we can't discover tests right now because of a configuration issue - ensure you have selected a Python environment for this project and its completion DB is up to date". That way we're providing correct and actionable feedback, rather than encouraging users to do something that is likely incorrect.

**Comment by jenstMS** [comment]
That's even better of course ^_^

**Comment by jenstMS** [comment]
I'm confused though.. The tests WERE discovered (saw them in log trace). They just were NOT displayed in the Test Explorer in VS. So unittest actually worked properly, but VS (PTVS?) didn't.

**Comment by zooba** [comment]
Yeah, I can't figure that bit out either (though I haven't had a chance to experiment yet - busy with other stuff these next few weeks). It may be that we _were_ running analysis with default settings, but it wasn't communicating properly with the test window, in which case it's easier to get the list of tests to show up even though running them won't work. This is why I haven't closed the issue yet

**Comment by zooba** [comment]
I've made some significant changes to how we manage test list messages, so I suspect this won't be an issue anymore. I'll close this, but please reopen if it occurs again (in 15.6 - will be a little while before you get to see the fix)
