### ISSUE TITLE
Is it possible to add Python to an existing instance of VS2017?

### ISSUE THREAD

**Issue by MDKimzey** [Microsoft/PTVS#2765]
I am somewhat new to GitHub.  I need to add Python from [(https://github.com/Microsoft/PTVS/)] to my existing VS2017.  

- It looks like the only way to do this is to completely uninstall VS 2017 and re-install.  
- I tried using the VS2017 installer, but this puts me in an endless "Please update Visual Studio Installer" loop.

**Comment by zooba** [comment]
Did you get past this? I see you reported #2766 later and it sounds like you got further.

If not, I'd support using the Report a Problem tool from in the installer (if possible) or your existing Visual Studio installation to let the team know. This is an installer issue, and while I can forward your report to them, if you do it using the tool it will automatically include the logs they need to resolve the problem. 

Lack of disk space on your C drive is potentially the problem. The installer does not allow you to customize its location.
