### ISSUE TITLE
debugger attach to python process launched from cmd

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#2767]
if python script is launched from cmd and then debugger attached to it, then it causes the process to crash.

I was debugging one issue with nbopen extension for jupyter and noticed when invoked like this it causes both remote (ptvsd) and attach modes of PTVS to crash the process:

`nbopen.bat`
`python nbopen.py %1`

from command-line:
`nbopen.bat "nbfile.ipynb"`

the code for attach and remote modes injected to nbopen.py:

```
#import ptvsd
#ptvsd.enable_attach("nbopen")
#ptvsd.wait_for_attach()

import sys
import time
print("wait for tracing")
while not sys.gettrace():
    time.sleep(0.1)
print("tracing found")
```

view from process explorer:

![image](https://user-images.githubusercontent.com/7870949/27779207-0ffa94c8-5f87-11e7-8aed-e7ca2eb20ee3.png)

error from VS debugger:

![image](https://user-images.githubusercontent.com/7870949/27779259-5801ede8-5f87-11e7-86e3-3d7f9d80c665.png)

internal error from ntdll.dll:

![image](https://user-images.githubusercontent.com/7870949/27779338-da09a3a8-5f87-11e7-8e99-7daa84ca31d6.png)

**Comment by zooba** [comment]
Can you provide exact version information for the Python that you're using? Copying from the Modules window in the debugger would be ideal.

Debug/Attach uses some nasty tricks to inject itself into the running process, and the smallest difference in the Python build can totally cause this kind of problem.

**Comment by denfromufa** [comment]
Python 3.5, 64-bit stock from python.org, VS 2017. Let me grab more info later.

**Comment by zooba** [comment]
Thanks. As I say, the `x` in the `3.5.x` version is actually critical here (and the fourth version field from the binaries is helpful validation too).

**Comment by denfromufa** [comment]
@zooba I'm not sure if this issue is with specific CPython version, but debugger works with PTVS 2015 on python 2.7 32-bit and python 3.5 64-bit. 

Here is the Python version I'm using with VS 2017 that caused the crash from above:
```
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
```

**Comment by huguesv** [comment]
I believe I've replicated your configuration (3.5.3:1880... 64-bit), and I'm not seeing the crash with either ptvsd or regular process attach. I changed nbopen.py like you did and use nbopen.bat to start. I've tried using both VS 2017 15.2 and 15.3 Preview. I was using a venv.  I also tried with Anaconda 4.3.1 64-bit.

Are you seeing this crash consistently?

**Comment by denfromufa** [comment]
Let's meet tomorrow at 11am at Pavel's location on PyData.

**Comment by denfromufa** [comment]
https://www.dropbox.com/s/f8zrgi7x2uj8y88/python_ptvs_debug.dmp?dl=0

![image](https://user-images.githubusercontent.com/7870949/27937450-bed362b6-627c-11e7-93d7-a9f15ea8d7bb.png)

**Comment by denfromufa** [comment]
https://www.dropbox.com/s/706qb46tvilvtl3/python_ptvs_crash.dmp?dl=0

![image](https://user-images.githubusercontent.com/7870949/27937565-a58ca1d6-627d-11e7-884b-f710bb9f4b54.png)

**Comment by denfromufa** [comment]
now without breakpoint attaching to Python code, crash again:

https://www.dropbox.com/s/ae4ze7on360jsv7/python_ptvs_crash_again.dmp?dl=0

**Comment by denfromufa** [comment]
![image](https://user-images.githubusercontent.com/7870949/27937856-cf89b094-627f-11e7-82ac-b5d96d42128c.png)

**Comment by huguesv** [comment]
We have a new debug engine in the 15.8 release, if you still see this problem, please open an issue at https://github.com/Microsoft/ptvsd
