### ISSUE TITLE
Interactive window suppressing pyspark output?

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#2771]
Hi

I've observed a new behavior in the REPL while running pyspark in PTVS with VS-2017 (VS-2015 did not exhibit this behavior). All log messages (such as progress, Spark warnings, etc.) from pyspark are being suppressed. Any code errors (that cause a spark crash) are coming through, however. 

I'm using Python 2.7.11, Anaconda 2.2.0 (32-bit), and I'm using ipython interactive mode (though the same issue persists even without ipython)  in my interactive window. If I run ipython directly at the command prompt (or powershell), I do see the usual pyspark output. 

Is there a way to prevent the output being suppressed?

Thank you

**Comment by huguesv** [comment]
Out of curiosity, does the output appear after your click Reset on the REPL toolbar?

If so, it's probably the same underlying issue as https://github.com/Microsoft/PTVS/issues/2531. Though for that particular bug, we opted with a simple workaround.

**Comment by sriksrid** [comment]
Hi

You are right - the output does appear after I reset (FYI, I tried the workaround mentioned in #2531, but that didn't work for this particular issue).

Thanks

**Comment by huguesv** [comment]
Thanks for additional info!

**Comment by WladIMirG** [comment]
Hola,
Desde hace rato vengo trabajando con la libreria Pykinect desde el mismo
python, me ha ido muy bien con el trabajo que he realizado ya que capturo
movimiento y lo reproduzco en blender a un avatar virtual que yo mismo cree
asi como el programa que recepciona los datos en el mismo.
Quiero hacer unas modificaciones a la libreria Pykinect, ya que necesito
los datos del acelerometro del kinect y en verdad no tengo idea de como
hacerlo. mi pregunta es:¿Hay alguien que quiera colaborarme para abordar el
trabajo y saber como empezar o por donde meterme para tal caso?
Muchas gracias.

2017-07-05 15:38 GMT-05:00 Srikanth Sridharan <notifications@github.com>:

**Comment by zooba** [comment]
No duplicate bug exists - the referenced one was resolved specifically for that case.

We have a general issue to somehow capture and display output from the standard stream, rather than solely what we capture within Python.

**Comment by zooba** [comment]
There is a duplicate - it's #1080
