### ISSUE TITLE
Python 3.6: using type hints to describe a variable in the function argument list and the Quick Info of this variable display ‘unknown type’

### ISSUE THREAD

**Issue by sarah17wu** [Microsoft/PTVS#2773]
please check this link: https://stackoverflow.com/questions/44901572/intellisense-not-recognising-type-hinting-for-python-3?noredirect=1#comment76835268_44901572 for the detail information and screenshot, it is more intuitive, thanks in advance.
The question: the result in the firstly screenshot is correct and as expected?

**Comment by int19h** [comment]
The result is as expected currently, because PTVS does not yet support type hints to drive code completion. The following issue is tracking that feature: https://github.com/Microsoft/PTVS/issues/82.
