### ISSUE TITLE
Overriden method parameter types not correctly detected...

### ISSUE THREAD

**Issue by CaseyChester** [microsoft/PTVS#2785]
I have a C# library project named PythonPlugin that contains the following class:

```csharp
namespace PythonPlugins
{
    public abstract class PythonPluginBase
    {
        public string Name { get; set; }
        public abstract void Process(string s);
    }
}
```
I then have a Python based project named PluginEditor which was created with the 'IronPython Application' template. The single CustomPlugin.py file with contains the following code:
```python
import clr
clr.AddReference('PythonPlugins')
import PythonPlugins

class CustomPlugin(PythonPlugins.PythonPluginBase):
    def Process(self, s):
        pass

plugin = CustomPlugin()
```
Now when I hoover the cursor over the parameters to the Process method, Visual Studio reports as follows:

- for self: CustomPlugin instance, type str
- for s: \<unknown type\>

![image](https://user-images.githubusercontent.com/10063403/28093144-aa7dfd2a-665b-11e7-826d-dc9286beceac.png)
![image](https://user-images.githubusercontent.com/10063403/28093295-474f0da6-665c-11e7-93bc-320a318e491c.png)

From that point forward, members listed for either parameter do not reflect members from the correct type.

For self I get:
![image](https://user-images.githubusercontent.com/10063403/28093524-43aa0dbc-665d-11e7-939e-74a1a084fe2e.png)

For s I get:
![image](https://user-images.githubusercontent.com/10063403/28093560-6c4943dc-665d-11e7-97b6-8f3dd3056f2e.png)

Is this a bug or am I just missing something?

Thanks

**Comment by zooba** [comment]
Looks like a bug in how we handle subclass analysis for IronPython code (I believe this isn't an issue for Python classes). Thanks!

**Comment by CaseyChester** [comment]
Very well. I am trying to decide how best to proceed with including python plugin capabilities into a larger solution. Can you provide any ETA when this might be corrected? -Thanks

**Comment by zooba** [comment]
Can't provide an ETA, unfortunately. If you've got a high priority need for this fix, please email ptvshelp@microsoft.com with details and we'll see what we can work out.

**Comment by gramster** [comment]
Closing this issue; we are not investing any more in IronPython support due to low usage and high cost.
