### ISSUE TITLE
ImportError with cntk in virtual env

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2806]
The CNTK dependent DLLs that are installed directly in the root env folder (not under scripts or site-packages) are not found when launched from VS.

Create new python application
```
import cntk
print(cntk.__version__)
```
Create new virtual environment based on 3.5 64-bit
Install numpy (with mkl) and scipy from http://www.lfd.uci.edu/~gohlke/pythonlibs
Install cntk from `https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl` as linked from https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python#quick-installation-test

Result: F5 or CTRL-F5 will give you an import error

Are they wrong to be installing their dependent DLLs in the virtual env root folder?
Are we wrong to not be including the env root folder in the PATH automatically?

Workaround 1:
- Set Environment Variables in project settings/debug page: `PATH=C:\pythonapplication1\env`

Workaround 2:
- Open command prompt
- Launch env\scripts\activate.bat
- Launch VS by typing path to devenv.exe

Interesting (works fine):
- Right click project node, open command prompt here
- python.exe pythonapplication1.py

**Comment by huguesv** [comment]
Contents of virtual env folders
[files.txt](https://github.com/Microsoft/PTVS/files/1149654/files.txt)

**Comment by zooba** [comment]
The DLLs should be alongside the module (DLL) that loads them, not the executable. Presumably they chose that path to work with a regular install of Python or an Anaconda env and did not test it with a virtualenv, which has a different layout.

We should not modify PATH. They should fix their wheel (and we've already told them this, so a newer version might be fixed already?). Users can work around it by calling `AddDllDirectory(sys.prefix)` via ctypes before importing cntk.

**Comment by huguesv** [comment]
The wheels that their docs point to were built on May 31st, so it's possible that they've implemented a fix but not released it yet. Or maybe they have, but haven't updated the installation page (linked above).

**Comment by huguesv** [comment]
I found another bug on this:
https://github.com/Microsoft/PTVS/issues/2528

So it looks like they've known about it since May or even earlier. I'll try to find out who it is we need to send a reminder to.

**Comment by zooba** [comment]
Thanks, Hugues.
