### ISSUE TITLE
Debugger pauses at random locations and then hangs on various actions

### ISSUE THREAD

**Issue by syagev** [Microsoft/PTVS#2808]
Remotely debugging a python module cross-platform results in the debugger pausing at random locations within 3rd party code for no apparent reason. Every time the debugger pauses it can be "Continue.."ed with no special side-effects but this happens so often and on multiple worker threads making the debug experience impossible.

I'm experiencing this with `pymongo` and `keras`, but am not sure the issue is limited to these modules.

Minimal example (need a running mongo server and an .h5 file with a keras model):
```python
from pymongo import MongoClient
from keras.models import load_model

mongo_client = MongoClient('mongodb://localhost:27017/')
model = load_model('keras_model.h5')
```
Code running on an Ubuntu 16.04 machine, Python 3.5.2, ptvsd 3.1.0
Debugger running Win10, VS 2017 (15.2), PTVS 3.0 (build 17114)

Debugging this code locally works perfectly well.
Also, no exception are thrown.

**Comment by huguesv** [comment]
You've unchecked all Python exceptions from the Exception Settings window to ensure it's not breaking because of one (bug https://github.com/Microsoft/PTVS/issues/2707)?

Do you have the Options/Tools/Python Tools/Debugging/Enable debugging of the Python standard library option disabled?

**Comment by syagev** [comment]
Yes, all Python exceptions disabled (although bug #2707 is very annoying!)
Debugging of the standard library - disabled.

**Comment by huguesv** [comment]
I tested a bit with 15.2 and the mongodb part didn't cause any issue.

I had trouble finding a h5 model file, the one I found was giving me a config file related error when loading, which appeared to be because of breaking changes that prevent from loading files saved with earlier versions. If you happen to know of a .h5 file that I can use, that would be helpful.

**Comment by huguesv** [comment]
I was able to make my own h5 model file, so never mind that part.

**Comment by syagev** [comment]
Thanks @hugesv, we're you able to reproduce?

**Comment by huguesv** [comment]
I tried it 4 times with your example above, and it didn't break randomly.
I've disabled break on all Python exceptions and have standard library debugging disabled as well.
My virtual env on my local and remote machine is below the project folder, named 'env' in both cases, and it has the same set of packages installed.

If you can show us some screenshots of it when it's in that random break state, that might help.

**Comment by syagev** [comment]
I'll share the screenshots and perhaps even give you temporary access to the linux box.
Will ping back next week with more info.

**Comment by zooba** [comment]
@syagev One useful piece of information would be the contents of your Breakpoints window.

Unlike other VS languages, Python cannot resolve breakpoints ahead of time, especially when doing remote debugging. If you have other breakpoints there, then we may be finding a way to resolve them while debugging, but can't show them in the editor. Since Hugues does not have the same ones set, he won't be able to reproduce it.

**Comment by syagev** [comment]
Hi, attached a screen-recording of the debug session, I have the breakpoints window in view as well.
https://www.dropbox.com/s/0cwilehi7ar6bcj/pypexeso%20%28Debugging%29%20-%20Microsoft%20Visual%20Studio%20%2025_07_17%2013_10_04.mp4?dl=0

The recorder didn't catch the popups that asked me to point at various files in the source code of the pymongo module. I hit "Cancel" each time and so got the "Frame not loaded" message..

**Comment by huguesv** [comment]
I had access to an internal user's remote debugging project, and tried to repro this issue with it.

On 15.2 I experienced an unexpected break even though I had disabled breaking for all Python exceptions.

Using the latest PTVS + ptvsd from master, I never saw it happen.

Based on your screen capture, it seems like it's breaking on an exception (bug #2707).
![image](https://user-images.githubusercontent.com/1696845/28592730-cf775bba-713e-11e7-9b1f-f0b5e8d9b012.png)

**Comment by syagev** [comment]
Understood, so the suggested fix is to wait till next version? Any clue as to when it'll make the stable channel?

**Comment by zooba** [comment]
It'll be in the next update. We only have an internal target date for it and nothing we can share, but we're counting in weeks rather than months.

**Comment by syagev** [comment]
I think we may have been too early classifying this as bug #2707 .

See following capture (which I am now able to consistently reproduce) with debugger breaking in what seems like a random location (in my code this time).

There is another, more serious, symptom here, that once I reach an actual breakpoint and do some stuff (like step into, step over, type a command in the Immediate Window, expand a variable in the Locals Window) - the debugger hangs with the message "Debugger operation in progress". The only way to get back on track is to close the program being debugged.

https://www.dropbox.com/s/ayj16ldzu9pi8iu/pypexeso%20-%20Microsoft%20Visual%20Studio%20%2027_07_17%2000_44_12.mp4?dl=0

**Comment by zooba** [comment]
We haven't been able to reliably reproduce this problem, so there's not much point keeping the issue open. If you have a reliable repro that we would be able to run on our own machines (on the latest version of VS Preview), feel free to comment here and we can look at reopening it.
