### ISSUE TITLE
One click test run feature

### ISSUE THREAD

**Issue by lmazuel** [Microsoft/PTVS#2815]
Would be nice to have the "one click" run/debug test button, like in VSCode for Python:
![image](https://user-images.githubusercontent.com/1050156/28428267-b8bf91fe-6d2d-11e7-9843-2186ce976156.png)

**Comment by huguesv** [comment]
For reference, here's how it looks for C#:
![image](https://user-images.githubusercontent.com/1696845/28430043-d61d18c4-6d33-11e7-9539-2a26f70defd0.png)

**Comment by zooba** [comment]
We need to enable code lens support for this, which is part of #2519 (and last I heard was not a public API, but maybe that's going to change with 15.3)...

**Comment by zooba** [comment]
To be clear, it's a duplicate because we should get this for free when we enable code lens support.
