### ISSUE TITLE
[Window Title] devenv.exe  [Main Instruction] An unexpected error occurred  [Content] 

### ISSUE THREAD

**Issue by atmoskr** [Microsoft/PTVS#2820]
Unexpected error reported while Just creating new IronPython project and switching interactive window to this project.

this is the error logs,
[Window Title] devenv.exe  [Main Instruction] An unexpected error occurred  [Content] Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.  [V] Show details  [닫기(C)]  [Expanded Information] ``` Build: 3.0.17114.1  Microsoft.PythonTools.MissingInterpreterException: The environment "IronPython|2.7-32" appears to be incorrectly configured or missing. You may need to install it or re-create a virtual environment.    at Microsoft.PythonTools.Project.PythonProjectNode.GetInterpreterFactoryOrThrow()    at Microsoft.PythonTools.Project.PythonProjectNode.GetLaunchConfigurationOrThrow()    at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.UpdatePropertiesFromProjectMoniker()    at Microsoft.PythonTools.Repl.PythonReplEvaluatorProvider.GetProjectEvaluator(IReadOnlyList`1 args)    at Microsoft.PythonTools.Repl.PythonReplEvaluatorProvider.GetEvaluator(String evaluatorId)    at Microsoft.PythonTools.Repl.SelectableReplEvaluator.<>c__DisplayClass43_0.<SetEvaluator>b__0(IInteractiveEvaluatorProvider p)    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)    at Microsoft.PythonTools.Repl.SelectableReplEvaluator.SetEvaluator(String id)    at Microsoft.PythonTools.Repl.ReplEditFilter.EvaluatorComboBoxHandler(IntPtr newValue, IntPtr outCurrentValue)    at Microsoft.PythonTools.Repl.ReplEditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)    at Microsoft.PythonTools.Repl.ReplEditFilter.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) ```

**Comment by huguesv** [comment]
Confirmed. Thanks for reporting.
