### ISSUE TITLE
WinForms Support for IronPython

### ISSUE THREAD

**Issue by mancoast** [Microsoft/PTVS#2821]
Greetings Developers,

Please consider support for visual design of WinForms for IronPython projects using Visual Studio 2017.
Does there exist any plans for future support of simplified/minimal code for GUI in IronPython.

Thanks,
coast

**Comment by zooba** [comment]
Thanks for the request. Unfortunately, integrating the WinForms designer with IronPython is a very significant project that we are not currently able to commit to. And while it would be valuable for some users, we are focused on other features that will have broader impact.

As there is nothing actionable here, I'm closing the issue to keep our tracker clean.

**Comment by mancoast** [comment]
Thanks for quick response, maybe in future we can see visual Python GUI design  operations
