### ISSUE TITLE
Update github.io page

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2829]
https://microsoft.github.io/PTVS/

We redirect to it in some places with this link:
https://go.microsoft.com/fwlink/?LinkId=293415

We may want to revise the downloads section at the top right.
We also want to fix the link to documentation.

**Comment by zooba** [comment]
Where does that link get used? Maybe we can just point it at the docs page?

**Comment by huguesv** [comment]
It's used as the link for our 'discussion forum'.
In no interpreters page, ptvsd fatal errors, web role readme files (17 hits total).

**Comment by zooba** [comment]
Let's point it at GitHub then. We should probably also make the GitHub.io page a plain redirect or link to here too.

**Comment by huguesv** [comment]
Updated the fwlink and made minimal changes to the github.io page.
