### ISSUE TITLE
Debugger breaks inside ptvsd

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#2837]
Test code:
```py
import ptvsd
ptvsd.enable_attach(None)

x = 1
while True:
    x += 1
    print(x)
```
Breakpoint set on `print`. After attaching, the stack is:
```
>	enable_attach in __init__ line 87	Python	Symbols loaded.
 	PythonApplication1 module line 7	Python	Symbols loaded.
```
where `__init__` is `ptvsd\__init__.py`. The line in question is inside `enable_attach`. However, the line on which it's actually broken is the one with `print`. So the breakpoint is hit, which is correct, but the stack is weird.

The real problem here is that `__init__.py` is not in `DONT_DEBUG`.

**Comment by zooba** [comment]
This is a new regression, right?

**Comment by int19h** [comment]
Yeah. It's because those functions were previously invoked directly in debugger, but now there are one-line wrappers in `__init__.py` that invoke them (this is so that all the docstrings are in one places). It's those one-liners that show up on the stack now and aren't on the list.

**Comment by int19h** [comment]
Also, for repro & validation purposes, this only happens if the breakpoint is preset before attaching, and only the first time that breakpoint is hit.
