### ISSUE TITLE
Refactor analyzer for .NET Standard

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2846]
We want to be able to build and run the out-of-proc analyzer on .NET Core as well as .NET Standard.

This will likely require separating out interfaces such as the Python registry service and much of the default interpreter implementation.

We could either end up with two assemblies (like `Common`/`VSCommon`), or move types into `VSInterpreters` (though the backwards compatibility implications of this may be more complicated). Alternatively, the builds could produce fundamentally different assemblies between .NET Standard and Core, provided the stdin/out interface is identical (extensions that directly depend on the assembly need to be rebuilt for Core anyway).

**Comment by zooba** [comment]
Ping @brettcannon

**Comment by brettcannon** [comment]
Is the worry .NET Standard versus .NET Core, or more .NET Standard/Core versus .NET Framework? (Still learning my way around the .NET universe so this might be a silly question 😄, but I know Framework is very much Windows-centric while Standard is portable on top of Core, but I also know Standard is new so maybe the worry is it's too new?)

**Comment by zooba** [comment]
@brettcannon You could be right... I lost track of all the renames they did there. Probably .NET Standard vs .NET Framework

**Comment by denfromufa** [comment]
.NET Standard is a way to run C# code as-is on supported CLR runtimes. It addresses issues with previous portable assemblies attempt which were very limiting.

.NET Standard 2.0 should be the way to go, but what is the benefit in PTVS to run on .NET Core, if VS itself is not ported?

**Comment by brettcannon** [comment]
[The announcement of .NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) helps clarify things; basically it's an API spec that all .NET platforms are expected to implement (.NET Framework and Core included). So basically you code for .NET Standard APIs and you know that it will work whether you're executing on top of .NET Framework, .NET Core, or Xamarin (as long as those platforms support that version of .NET Standard you're using).

**Comment by zooba** [comment]
> what is the benefit in PTVS to run on .NET Core, if VS itself is not ported?

Many possibilities, but primarily for cross-platform code analysis. For example, we would need this for true remote environment support (i.e. Intellisense for a Linux or macOS system while using VS), and we'd need this to make a portable [language server](https://github.com/Microsoft/language-server-protocol) that could then be integrated with any editor that supports the protocol.

**Comment by zooba** [comment]
Okay, then in that case we should aim to refactor the assembly to match the standard.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/vscode-python/blob/master/CONTRIBUTING%20-%20PYTHON_ANALYSIS.md
