### ISSUE TITLE
Solution building failed

### ISSUE THREAD

**Issue by amos402** [Microsoft/PTVS#2856]
HEAD: 55a72c4a284100fcbef68076003d723700a3de29
VS: 15.2(26430.16)

> 1>------ Build started: Project: ProjectWizards, Configuration: Debug Any CPU ------
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.Shell.Interop.15.0.DesignTime, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
> 1>I:\Projects\PTVS\Python\Product\ProjectWizards\CloudServiceWizard.cs(70,59,70,85): error CS0246: The type or namespace name 'SVsSetupCompositionService' could not be found (are you missing a using directive or an assembly reference?)
> 1>I:\Projects\PTVS\Python\Product\ProjectWizards\CloudServiceWizard.cs(70,91,70,117): error CS0246: The type or namespace name 'IVsSetupCompositionService' could not be found (are you missing a using directive or an assembly reference?)
> ========== Build: 0 succeeded, 1 failed, 22 up-to-date, 0 skipped ==========
> 

I changed the refrence from `Microsoft.VisualStudio.Shell.Interop.15.0.DesignTime`  to `Microsoft.VisualStudio.Shell.Interop.15.0.DesignTime`, it would pass.
But about `SVsSetupCompositionService` and `IVsSetupCompositionService`, I still don't know whrere I can find it.

* Other errors:

> 1>------ Build started: Project: TestUtilities.UI, Configuration: Debug x86 ------
> 2>------ Build started: Project: Workspace, Configuration: Debug Any CPU ------
> 3>------ Build started: Project: Profiling, Configuration: Debug x86 ------
> 4>------ Build started: Project: Uwp, Configuration: Debug Any CPU ------
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 1>CSC : error CS1705: Assembly 'Microsoft.VisualStudio.Shell.15.0' with identity 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.VisualStudio.Threading, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.Threading' with identity 'Microsoft.VisualStudio.Threading, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> 5>------ Build started: Project: TestUtilities.Python, Configuration: Debug Any CPU ------
> 4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 4>  VsdConfigOutput: I:\Projects\PTVS\\BuildOutput\Debug15.0\raw\obj\Uwp\\RemoteDebugger.vsdconfig
> 4>CSC : error CS1705: Assembly 'Microsoft.VisualStudio.Shell.15.0' with identity 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.VisualStudio.Threading, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.Threading' with identity 'Microsoft.VisualStudio.Threading, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> 6>------ Build started: Project: SharedProjectUITests, Configuration: Debug Any CPU ------
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 2>CSC : error CS1705: Assembly 'Microsoft.VisualStudio.Workspace' with identity 'Microsoft.VisualStudio.Workspace, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.VisualStudio.Threading, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.Threading' with identity 'Microsoft.VisualStudio.Threading, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> 7>------ Build started: Project: Core, Configuration: Debug Any CPU ------
> 5>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 8>------ Build started: Project: DebuggerTests, Configuration: Debug Any CPU ------
> 6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 6>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 9>------ Build started: Project: PythonToolsTests, Configuration: Debug Any CPU ------
> 3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 3>CSC : error CS1705: Assembly 'Microsoft.VisualStudio.Shell.15.0' with identity 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.VisualStudio.Threading, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.Threading' with identity 'Microsoft.VisualStudio.Threading, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> 10>------ Build started: Project: DebuggerUITests, Configuration: Debug Any CPU ------
> 8>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 11>------ Build started: Project: FastCgiTest, Configuration: Debug Any CPU ------
> 9>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 9>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 12>------ Build started: Project: TestAdapterTests, Configuration: Debug Any CPU ------
> 10>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 10>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 13>------ Build started: Project: IronPythonTests, Configuration: Debug Any CPU ------
> 11>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 14>------ Build started: Project: PythonToolsMockTests, Configuration: Debug Any CPU ------
> 12>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 15>------ Build started: Project: ReplWindowUITests, Configuration: Debug Any CPU ------
> 14>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 14>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 16>------ Build started: Project: DjangoUITests, Configuration: Debug Any CPU ------
> 13>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 13>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 17>------ Build started: Project: DjangoTests, Configuration: Debug Any CPU ------
> 15>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\PythonToolsTests.dll' could not be found
> 15>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 15>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 18>------ Build started: Project: ProfilingUITests, Configuration: Debug Any CPU ------
> 16>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 16>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\DebuggerUITests.dll' could not be found
> 16>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 16>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 7>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\Microsoft.PythonTools.Workspace.dll' could not be found
> 19>------ Build started: Project: PythonToolsUITests, Configuration: Debug Any CPU ------
> 20>------ Build started: Project: IpcJsonTests, Configuration: Debug Any CPU ------
> 17>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\DebuggerTests.dll' could not be found
> 17>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 21>------ Build started: Project: VCDebugLauncher, Configuration: Debug Any CPU ------
> 20>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 21>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.ProjectSystem". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
> 21>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.ProjectSystem.VS". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
> 21>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(25,30,25,43): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(26,30,26,43): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(27,30,27,43): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(18,30,18,43): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(19,30,19,43): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(32,56,32,79): error CS0246: The type or namespace name 'DebugLaunchProviderBase' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(25,45,25,72): error CS0246: The type or namespace name 'StronglyTypedPropertyAccess' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(24,6,24,15): error CS0246: The type or namespace name 'AppliesToAttribute' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(24,6,24,15): error CS0246: The type or namespace name 'AppliesTo' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(24,16,24,35): error CS0103: The name 'ProjectCapabilities' does not exist in the current context
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(293,195,293,208): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(35,31,35,48): error CS0246: The type or namespace name 'ConfiguredProject' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(35,68,35,93): error CS0246: The type or namespace name 'IProjectPropertiesContext' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(39,31,39,48): error CS0246: The type or namespace name 'ConfiguredProject' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(39,68,39,87): error CS0246: The type or namespace name 'UnconfiguredProject' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(27,88,27,105): error CS0246: The type or namespace name 'ConfiguredProject' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\RuleProperties.cs(31,31,31,48): error CS0246: The type or namespace name 'ConfiguredProject' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(291,139,291,152): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(112,33,112,46): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(30,6,30,20): error CS0246: The type or namespace name 'ExportDebuggerAttribute' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(30,6,30,20): error CS0246: The type or namespace name 'ExportDebugger' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(31,6,31,15): error CS0246: The type or namespace name 'AppliesToAttribute' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(31,6,31,15): error CS0246: The type or namespace name 'AppliesTo' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(31,16,31,35): error CS0103: The name 'ProjectCapabilities' does not exist in the current context
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(119,35,119,48): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(139,35,139,48): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(159,35,159,48): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(179,35,179,48): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(199,35,199,48): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(219,34,219,47): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(237,103,237,116): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(237,41,237,54): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(244,63,244,76): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(86,61,86,74): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(86,121,86,134): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(107,61,107,74): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(107,193,107,206): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(44,34,44,47): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(56,34,56,47): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(59,92,59,105): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(62,34,62,47): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(68,61,68,74): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(73,61,73,74): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(73,193,73,206): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(102,61,102,74): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(102,193,102,206): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\BuildOutput\Debug15.0\raw\obj\VCDebugLauncher\Microsoft.PythonTools.Debugger.VCDebugLauncher.cs(102,290,102,303): error CS0234: The type or namespace name 'ProjectSystem' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(42,75,42,93): error CS0246: The type or namespace name 'DebugLaunchOptions' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(42,28,42,47): error CS0246: The type or namespace name 'DebugLaunchSettings' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(107,57,107,75): error CS0246: The type or namespace name 'DebugLaunchOptions' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(111,96,111,114): error CS0246: The type or namespace name 'DebugLaunchOptions' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(111,50,111,70): error CS0246: The type or namespace name 'IDebugLaunchSettings' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(107,42,107,56): error CS0115: 'PythonDebugLaunchProvider.CanLaunchAsync(DebugLaunchOptions)': no suitable method found to override
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(111,73,111,95): error CS0115: 'PythonDebugLaunchProvider.QueryDebugTargetsAsync(DebugLaunchOptions)': no suitable method found to override
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(33,37,33,55): error CS0246: The type or namespace name 'DebugLaunchOptions' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(33,57,33,76): error CS0246: The type or namespace name 'DebugLaunchSettings' could not be found (are you missing a using directive or an assembly reference?)
> 21>I:\Projects\PTVS\Python\Product\VCDebugLauncher\PythonDebugLaunchProvider.cs(36,42,36,59): error CS0246: The type or namespace name 'ConfiguredProject' could not be found (are you missing a using directive or an assembly reference?)
> 18>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\Microsoft.PythonTools.Profiling.dll' could not be found
> 18>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 18>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 19>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\Microsoft.PythonTools.Core.dll' could not be found
> 19>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 19>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> 22>------ Build started: Project: AzurePublishingUITests, Configuration: Debug Any CPU ------
> 22>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\PythonToolsUITests.dll' could not be found
> 22>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.Python.dll' could not be found
> 22>CSC : error CS0006: Metadata file 'I:\Projects\PTVS\BuildOutput\Debug15.0\raw\binaries\TestUtilities.UI.dll' could not be found
> ========== Build: 0 succeeded, 22 failed, 46 up-to-date, 0 skipped ==========
>

**Comment by zooba** [comment]
Can you try building with VS 15.3 Preview? We are getting very close to releasing that update, and so we now require it to build the latest version.

(And apologies for our build instructions being so out of date... I really do intend to get to fixing those soon, but there's so much other stuff to do :) )

**Comment by amos402** [comment]
All projects build sucess with use 15.3 preview 6.0
