### ISSUE TITLE
'Django Make Migrations' becomes disabled

### ISSUE THREAD

**Issue by mifozski** [Microsoft/PTVS#2863]
After making migrations fails and exiting the interactive prompt with typing '2', the option 'Django Make Migrations (Django >= 1.7) in the project context menu becomes disabled.

The only solution I've found is to restart Visual Studio.

**Comment by zooba** [comment]
Disabling the menu item is normal behaviour when the command fails to run - closing and reopening the project should be enough to enable it again.

Can you show us the output in the window? There's clearly something going on that is causing the command to fail, but without that information we can't do anything to help.

**Comment by mifozski** [comment]
For some reason I can't repeat this problem. It was present after making migrations was interrupted by some error and the console log outputs 'The interactive Python process has exited.'. The python code itself was valid.

**Comment by zooba** [comment]
Okay, thanks for getting back to us. There's nothing we can fix here as far as I can tell, so I'll close the issue.
