### ISSUE TITLE
"debugging is not supported for python 2.5 and earlier" error on 3.5 Anaconda

### ISSUE THREAD

**Issue by CharcoalStyles** [Microsoft/PTVS#2864]
I'm trying to get VS2017 to hook into the Anaconda environment installed with ArcGIS Pro.
I think I've done what I need (New environment, setup paths, set language version), but when I try to debug some code, it throws the error.

**Comment by huguesv** [comment]
Sorry, but we intentionally removed support when we started relying on json for the debugger protocol.

We considered relying on an external json library (simplejson) but ended up just disabling it instead.

**Comment by int19h** [comment]
From the bug title, it sounds like the Python version in question is not actually 2.5, but rather 3.5 - is that right?

**Comment by huguesv** [comment]
Good point, I missed that.

It could be that the manually configured environment doesn't have the right Python language version.

![image](https://user-images.githubusercontent.com/1696845/28794776-55d8b7c4-75ec-11e7-9e78-11fb54b1e2c3.png)

**Comment by zooba** [comment]
Could you open Tools, Python Tools, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

**Comment by CharcoalStyles** [comment]
@huguesv When I first got the error, I checked the Configure settings and changed that; it's set correctly.

@zooba It seems that a little sleep over night and restarting VS has fixed the problem. But, [here's the gist](https://gist.github.com/CharcoalStyles/b2a5f26ad0960bc123785eacc3953a4a), in case it helps.

**Comment by zooba** [comment]
I can see some entries that show we forgot the version number for a while there (some `/version 0.0` options in the log). Odd that it came good though... perhaps we triggered a settings load while we were still writing them out and that confused things?

We should check for potential race conditions between saving a configured environment and reloading environment settings. We are _supposed_ to suppress reloads while saving, but maybe we missed one.

**Comment by huguesv** [comment]
No repro.
