### ISSUE TITLE
Sort locals window

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#2865]
![image](https://user-images.githubusercontent.com/1693688/28786600-82eec64a-75ce-11e7-8522-d3398e5a4ea8.png)

Would be nice to have the items in alphabetical order (case-insensitive) with underscore items at the end (or perhaps single underscore in order and double underscore at the end?).

**Comment by Ashukm** [comment]
Hi @zooba  I would like to contribute to the project. This will be my first contribution. Let me know if I can chip in!
Thanks

**Comment by zooba** [comment]
Great! Thanks, @Ashukm 

First you'll need to be able to build - I just updated our [development docs](https://github.com/Microsoft/PTVS/wiki/Build-Instructions-for-PTVS) so they should be accurate, but just call out if you get stuck somewhere.

The file needing updates (I believe) is [AD7StackFrame.cs](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Debugger/Debugger/DebugEngine/AD7StackFrame.cs#L165) - there are three functions that create arrays containing the variables for this view, and they do not sort anything.

Feel free to completely replace this code with more modern code (e.g. using Linq). There is no real need for the kind of array manipulation that is being done here. Just avoid changing the API of the functions - they should keep the current `uint, out uint, out IEnumDebugPropertyInfo2` formats. 

There's also a test called `ExpressionEvaluation` in DebuggerUITests.csproj. That looks like a good one to check whether locals are being returned in order (or make a copy of it and simplify it down to only check ordering). However, it is a UI test, which will be harder to get running. If you can't get it going, we'll have someone add the test for you.

**Comment by Ashukm** [comment]
Thanks a lot @zooba I will compile the code and will drop a note if any issues!
