### ISSUE TITLE
Go to definition fails for named argument for instance method call

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2869]
Affected test: NavigableTests.NamedArgumentDefinition

```
class MyClass(object):
    def my_class_func1(self, param2 = True):
        pass

    def my_class_func2(self, param3 = True):
        pass

def my_func(param3 = True):
    pass

my_func(param3=False)

obj = MyClass()
obj.my_class_func1(param2=False)
obj.my_class_func2(param3=False)
```

If you press F12 on `param2` in `obj.my_class_func1(param2=False)`, you'll get Cannot go to definition.

If you press F12 on `param3` in `obj.my_class_func2(param3=False)`, it will go to `my_func` instead of `my_class_func2`.

**Comment by zooba** [comment]
The fact that the first `param3` worked is also a bug - if you insert another function or class before the call then it breaks.

Currently we don't do anything special to resolve argument names. I don't actually recall when we ever did, but I guess we should add it in since the test is there.
