### ISSUE TITLE
autocomplete command from commands history in Python Interactive

### ISSUE THREAD

**Issue by Evfro** [Microsoft/PTVS#287]
For example, in Spyder IDE I can do:
**In[1]:** a = 5
**In[2]:** b = 10

Then, if I type 
**In[3]:** a =
and hit **Arrow Up** key I get the previous matching command from history:
**In[3]:** a = 5

When doing the same in PTVS Interactive I simply get the previous command instead:
**In[3]:** b = 10

Is there a way to make it match current command string and not just return the previous line?

**Comment by Evfro** [comment]
I've investigated a bit and it turned out to be a problem of VS2015RC + PTVS2.2RC bundle.
When using VS2013 + PTVS2.2RC the shortcut **Alt + Arrow Up** does the thing.

But in VS2015 I get "The operation could not be completed" with this shortcut.

Not sure if this is a problem of Visual Studio or PTVS.

**Comment by zooba** [comment]
Probably a bit of both - the Interactive Window is now split between VS and PTVS, and there are a number of new bugs as a result of this work. We're trying to get to them all before our next release, but it may not be possible :(
