### ISSUE TITLE
Unable to resolve "requests". IntelliSense may be missing for this module.

### ISSUE THREAD

**Issue by Crucial1** [Microsoft/PTVS#2870]
Unable to resolve "requests". IntelliSense may be missing for this module.

How to Fix this issue Visual studio 2015
Cant find anywhere to post question

**Comment by zooba** [comment]
This is a good place to post it. Here are some things to check:
* have you installed it?
* is it installed in the project's [active environment](https://docs.microsoft.com/en-us/visualstudio/python/python-environments#project-specific-environments)
* if you don't have a project, is it in the default environment?
* when you look at IntelliSense, does it have a warning note that the completion DB needs to be refreshed?
* do you have IntelliSense for other modules?

If none of these help, and neither does our [documentation page](https://docs.microsoft.com/en-us/visualstudio/python/python-environments), let us know and we'll go deeper.

**Comment by Crucial1** [comment]
99% sure its installed, but just to be sure, how to check?.

![7826b7d7ecd34afd58a022b0d8ec30bb](https://user-images.githubusercontent.com/9994597/28805829-9459fac6-7664-11e7-86b4-ce8266587650.png)

IntelliSense working for other modules.

No visible warning for IntelliSense.

**Comment by Crucial1** [comment]
Fixed while removing and re-installing while visual studio was opened

**Comment by sujeet-banerjee** [comment]
I was facing the issue for my Visual Studio Code on OSX (MacBook). I solved it by adding folder (where the packages were downloaded) to Workspace.  See Attached screenshot...
<img width="794" alt="python_addtows" src="https://user-images.githubusercontent.com/1738131/43886209-abc91b52-9bd8-11e8-9926-74d479cd44b9.png">
