### ISSUE TITLE
Unit test stack trace is not very good

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2871]
The stack trace for failed unit tests appears to be upside down (earliest call first), has no module or class information, and includes standard library modules:
![image](https://user-images.githubusercontent.com/1693688/28805448-dc83f6da-761e-11e7-9ced-f1ebec5794a3.png)

This trace should have one entry that reads `test_util.Test_util.test_daterange_year` or at worst, `Test_util.test_daterange_year`.

**Comment by huguesv** [comment]
I have the ordering and the filtering of the frames done.

I also have the fully qualified name done, sharing the debugger C# code that parses the user's code to determine the context (`QualifiedFunctionNameWalker`).

I tried to determine the qualified name from Python but I couldn't do it in all cases:

I was able to get parent class from an instance method by looking at the 'self' object, relying on naming convention. Once I had that I could also get the module name.

For class static methods or regular global functions, I couldn't see how to get the parent class and/or module name.  I didn't try for local functions.

As you can see from screenshot, the C# solution gets the fully qualified names for class instance methods, static methods, regular functions and local functions. No module names.

![image](https://user-images.githubusercontent.com/1696845/28948036-04a12674-7868-11e7-850e-99945988fbb3.png)
