### ISSUE TITLE
Python Environment missing: {86767848-40B4-4007-8BCC-A3835EDF0E69}\3.5

### ISSUE THREAD

**Issue by andijakl** [Microsoft/PTVS#2872]
I've set up my Visual Studio 2017 with the Python tools to develop for Windows 10 IoT Core.
Creating a project works, but in the Solution Explorer under Python environments, a reference is missing:
UnknownInterpreter\{86767848-40B4-4007-8BCC-A3835EDF0E69}\3.5

This ID isn't referenced by any file in my Hello World app. Seems like it is included by: https://github.com/Microsoft/PTVS/blob/master/Python/Product/Uwp/Microsoft.PythonTools.Uwp.targets
The ID appears to be related to PythonUwpIoT according to: https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/Project/PythonProjectFactory.cs

The project can still compile, but it's strange to have an error in a Hello World app built using the Visual Studio Python template. (based on: https://developer.microsoft.com/en-us/windows/iot/samples/helloworldpython )

My environment:
- Visual Studio 2017 15.2 (26430.16)
- Installed through VS Installer: Python + UWP workloads + manually selected: Python IoT support.
- Also installed: https://github.com/ms-iot/python/releases (latest version 1.4)

So theoretically, that should be it. The Visual Studio about dialog also lists Python as installed (including UWP support) - everything with version 3.0.17114.1

So I'm wondering what is my environment missing that causes this missing reference, and why is this missing component not part of the complete installation that I did?

**Comment by zooba** [comment]
It's actually a lingering reference from our previous version. You're right that it is an error and we should clean it up, but you are not actually missing anything.

If you remove the `InterpreterReference` line from that targets file then it will go away and you shouldn't have any other problems. The reference in PythonProjectFactory is an upgrade step for converting the value into the new style one, and if you start from an up-to-date template (which you have) then it isn't ever used.

(cc @alanch-ms)

**Comment by huguesv** [comment]
Closing as won't fix, since Pyton IoT support in VS has been removed in dev16.
