### ISSUE TITLE
UWP Targets need updating for new ptvsd

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2873]
The [Microsoft.PythonTools.Uwp.targets](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Uwp/Microsoft.PythonTools.Uwp.targets#L38) file contains assumptions about `ptvsd` being located in certain places.

I _think_ the way we refactored it will still work here, but I'm not 100% sure.

@alanch-ms, @int19h - can you take a look?

**Comment by int19h** [comment]
It looks like it just grabs the entirety of `ptvsd` folder, so changes in its internal structure shouldn't matter. The launcher code (`visualstudio_py_remote_launcher.py`) also looks fine. But this definitely needs testing.
