### ISSUE TITLE
Debugger doesn't stop for Step Into or Step Over

### ISSUE THREAD

**Issue by mkimberling** [Microsoft/PTVS#2886]
In VS2015 with 2.7.10, the Python debugger is working nicely in all but one regard: Using "step over" or "step into" is equivalent to pressing F5:  the program doesn't stop on the next line.  The only way to halt it at the next line is to set a break point.

**Comment by zooba** [comment]
Are you stepping through your own code? Or the standard library?

This is a known issue - specifically, we are not meant to be hitting breakpoints there unless you've set the [Enable debugging of the standard library](https://docs.microsoft.com/en-us/visualstudio/python/options#debugging-options) option - generally enabling this option makes it all work as expected (if you expect to be able to step through the standard library).

If this is occurring in your own code, we'd need to take a look at the actual code you're seeing it on and the callstack at the point where it is occurring.

**Comment by mkimberling** [comment]
It is my own code but the files live in the python folder.  Checking that checkbox addressed the issue.  Thank you Zooba!
