### ISSUE TITLE
Adding dirs with *.py files to the index of the IntelliSence

### ISSUE THREAD

**Issue by KhArtNJava** [Microsoft/PTVS#2887]
Hello,

I am using PyCharm now and that IDE allows to add dirs with *.py files and use it in the auto-completion /auto-import/import-suggestion functional.

Now PTVS allows to index folders in Python33\Lib\site-packages\ - after placing my dir, named 'simulation', in that folder, all modules and packages of my dir is available in MS VS now. But! They are available in imports like 
`import simulation.NEEDED_MODULE`
ie, for example
`import simulation.sim`
But I need to import all folder content of the simulation dir as from root directory, ie, I need it like 
`import sim`
![default](https://user-images.githubusercontent.com/757085/29004622-2b77cd26-7ad3-11e7-8ef1-5d6e0ac92784.png)
After simulation dir was added to that config, all *.py files and packages of simulation dir are available like 
`import sim` (not like `import simulation.sim`, as in PTVS).

Is it possible to make PTVS option to add custom dirs via config, not only by placing them into the Python33\Lib\site-packages\ ?

Thank you!

**Comment by zooba** [comment]
If you have a project, you can add them as a [search path](https://docs.microsoft.com/en-us/visualstudio/python/python-environments#search-paths).

We don't currently let you configure additional search paths for the environment itself - only for projects - but if you do an [editable install](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) then we should also pick up the files correctly.
