### ISSUE TITLE
When PEP 484 will be implemented in PTVS?

### ISSUE THREAD

**Issue by KhArtNJava** [Microsoft/PTVS#2888]
Hello.
I found, that PTVS is not support PEP 484, especially #type: TypeName .
There are a lot of questions could be found in Internet about PTVS and PEP 484, they are dated from 2015 year and still not resolved. For example, this - https://github.com/Microsoft/PTVS/issues/82 .
Microsoft, why you don't want to solve that issue? )))

**Comment by zooba** [comment]
We do want to implement that feature, it's just not a high enough priority to overtake the other work that we are doing right now.

Follow issue #82 for updates.
