### ISSUE TITLE
Scipy Package is not installed in VS2017

### ISSUE THREAD

**Issue by Vijaykumarj** [Microsoft/PTVS#2907]
I have VS2017 community Edition for developing Python based projects.
   When i installed "SciPy" package in VS2017, the following error has occurred.

 I have posted StackTrace when installing package.
  \
Command "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\NAGADU~1\\AppData\\Local\\Temp\\pip-build-kyxkhm6t\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\NAGADU~1\AppData\Local\Temp\pip-rnx9ocy7-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\NAGADU~1\AppData\Local\Temp\pip-build-kyxkhm6t\scipy\
----- Failed to install 'scipy==0.19.1' -----

----- Installing 'scipy' -----
Collecting scipy
  Using cached scipy-0.19.1.tar.gz
Installing collected packages: scipy
  Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status 'error'
    Complete output from command C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\NAGADU~1\\AppData\\Local\\Temp\\pip-build-7ienrtx1\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\NAGADU~1\AppData\Local\Temp\pip-gc2cbshp-record\install-record.txt --single-version-externally-managed --compile:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['C:\\Users\\Nagadurga\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\', 'C:\\Users\\Nagadurga\\AppData\\Local\\Programs\\Python\\Python36\\libs']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\Nagadurga\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\', 'C:\\Users\\Nagadurga\\AppData\\Local\\Programs\\Python\\Python36\\libs']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['C:\\Users\\Nagadurga\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\', 'C:\\Users\\Nagadurga\\AppData\\Local\\Programs\\Python\\Python36\\libs']
      NOT AVAILABLE
    
    C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\NAGADU~1\AppData\Local\Temp\pip-build-7ienrtx1\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\NAGADU~1\AppData\Local\Temp\pip-build-7ienrtx1\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\NAGADU~1\AppData\Local\Temp\pip-build-7ienrtx1\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------
Command "C:\Users\Nagadurga\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\NAGADU~1\\AppData\\Local\\Temp\\pip-build-7ienrtx1\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\NAGADU~1\AppData\Local\Temp\pip-gc2cbshp-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\NAGADU~1\AppData\Local\Temp\pip-build-7ienrtx1\scipy\
----- Failed to install 'scipy' -----

Please suggest to me any one. Thanks in advance.

**Comment by zooba** [comment]
I'd suggest installing and using Anaconda rather than CPython for this. Anaconda includes these packages already built and installed, which is the hardest part of using them.

You can add Anaconda by opening Visual Studio Installer from your start menu, selecting "Modify", and you'll find "Anaconda3 (64-bit)" in the list on the right hand side.

**Comment by Vijaykumarj** [comment]
Hi zooba,
   First of all thank you for given reply of above post.

As per ur guidelines, i was installed Anaconda3 in my system & also added this one into VS2017 python Environment.
  Scipy package is installed & pls refer below image.
   
![pyhton - 1](https://user-images.githubusercontent.com/26544969/29406496-e15ef72a-835e-11e7-8b7f-3c6b8b341bb6.PNG)

when i run my project gives error & pls reefer below image.

![pyhton-2](https://user-images.githubusercontent.com/26544969/29406836-f00c5dac-835f-11e7-8e73-420f228fcc96.png)


I need to use sklearn packages in my project. 

 my system environment is :- 
    1. Anaconda3 (Installed)
    2. VS2017 Community (Installed)
    3. Windows 10 , 64-bit (Installed)
    4. Python3 is  not installed.

Please guide to me & thanks in advance.

**Comment by zooba** [comment]
Your error there is from using Canopy. See our docs on [setting up your project](https://docs.microsoft.com/en-us/visualstudio/python/python-projects) to see how to make your project use Anaconda.

**Comment by Vijaykumarj** [comment]
Finally our project was run after activating Anaconda in my project. Thanks to zooba.
