### ISSUE TITLE
Ctrl+Click Peek at definition does not work

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2916]
Apparently when the "Peek" option is enabled, we do not open the correct window.

Needs more investigation - I'm not sure this is our fault. Haven't testing on C# on my current machine.

**Comment by huguesv** [comment]
When the option is enabled, C# does a Peek Definition (Alt+F12) instead of Go To Definition (F12). It looks like this:
![image](https://user-images.githubusercontent.com/1696845/29387292-38e03746-8294-11e7-9d29-daa522fc35b7.png)

We currently don't have the support for the Peek Definition command.

**Comment by zooba** [comment]
I thought I tried it on a debug build and it worked...
