### ISSUE TITLE
python virtual env errors after latest VS upgrade

### ISSUE THREAD

**Issue by tpaz** [Microsoft/PTVS#2923]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17208.1

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Operation cannot be started because the environment is not configured.
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<AbortIfNotReady>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<>c__6`1.<SilenceException>b__6_0(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Operation cannot be started because the environment is not configured.
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<AbortIfNotReady>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__35.MoveNext()<---

```

**Comment by grbd** [comment]
I'm currently using 15.3.1
I think moving from 15.2 to 15.3.1 (With the new logo) has recently caused this.

When expanding the "Python Environments" entry within the project and nodes underneath it sometimes triggers a lock up of VS. It seems to be a bit random but having multiple python projects in a solution under subfolders I think makes it more likley

**Comment by tpaz** [comment]
@grbd for me it seems the pip packages were simply removed for no good reason.

**Comment by grbd** [comment]
It seems to have stopped doing it now which is strange, when it did lock up the memory usage of VS skyrocketed and I ended up having to end task it

**Comment by zooba** [comment]
@grbd That sounds likely. We've seen trouble with Resharper in the past not liking how many items we put in Solution Explorer (though many are hidden), and I don't think there's anything we do there that would cause VS to fill up its memory.

**Comment by zooba** [comment]
@tpaz What were you doing when that error appeared? It looks like you were installing a package, but we trigger that when installing virtualenv if you don't already have it, so it could have been that.

Also, could you open Tools, Python, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

**Comment by tpaz** [comment]
I already re-installed the virtual-env and packages in the requirements file, so not sure if it is relevant now to print the diagnostics. the problem is that the environment && packages were simply gone after the upgrade, that what puzzled me. Took me few minutes to figure that out (just had build errors running my Django app - "could not find django library" and such errors... make sense if all the environment is gone). anyway here is the gist. I kept it "secret" so not sure if you will be able to access it. if not, let me know and I'll send it in attachment.
https://gist.github.com/tpaz/8a62a0c723ebfb23657994ca5198c212

**Comment by zooba** [comment]
Thanks, I can access the log file (I think "secret" just means "you need to be given the direct link"). But you're right, there's nothing to see there.

I suspect we have a race condition between our completion DB analysis and virtual environment creation (see #2926), and that may be bleeding into package detection and virtual environment creation. Seems there are probably some error conditions that don't log themselves properly (e.g. failed to get environment details which leads to "skip this environment" and forgets the "tell someone we skipped it" part, see #2927).

Since you're back in business and I've spun off two specific bugs from this, any problem if I just close this issue? Helps to keep the "me too" comments down.

**Comment by tpaz** [comment]
fine with me.
Thanks for the quick revert.
