### ISSUE TITLE
Tests do not setUp/tearDown correctly

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2929]
(Reported at https://developercommunity.visualstudio.com/content/problem/43362/test-explorer-again.html)

Apparently our test runner does not correctly set up and tear down test classes properly. Need to investigate further.

**Comment by huguesv** [comment]
Bug confirmed for Python 2.7.
Works fine on Python 3.x.

Running the following with F5 shows it runs tear down when there's a test failure, but running it in test explorer, it is missing the tear down output.

```
import unittest

class Test_test1(unittest.TestCase):

    def setUp(self):
        print('doing setUp')

    def tearDown(self):
        print('doing tearDown')

    def test_failure(self):
        self.fail("test not ready")

    def test_success(self):
        pass

if __name__ == '__main__':
    unittest.main()
```

**Comment by huguesv** [comment]
I started by writing the test for it, and it fails on Python 2.6, 2.7, 3.0 and 3.1.

**Comment by huguesv** [comment]
It turns out that `tearDown` was being called, just in a different order that prevented us from capturing its stdout (we were giving the results to VS too early and the tearDown stdout appeared in the following test).

I'm validating a fix right now, will have a PR shortly.
