### ISSUE TITLE
ptvsd no longer working in VisualStudio 2017 after 15.3 Preview 3

### ISSUE THREAD

**Issue by kdriedger** [Microsoft/PTVS#2933]
Not sure, if I need to report the bug here as well but I'm having trouble with python on Visual Studio 2017 after release 15.3 Preview 3 (including the RTM 2017 15.3 release):

https://developercommunity.visualstudio.com/content/problem/99209/python-remote-debugging-ptvsd-cannot-establish-con.html

How do I debug problems related to ptvsd?  println debugging here we come!

**Comment by int19h** [comment]
Yes, print-debugging is pretty much the only way to debug the debugger, unfortunately. There's a twist there, as well - since it redirects output, if you just use `print` normally from inside debugger, it's possible to get weird deadlocks and hangs due to re-entrancy. The thing that always works is printing to `sys.__stdout__` or `sys.__stderr__` - this circumvents redirection.

**Comment by int19h** [comment]
To clarify, is this a problem with GAE specifically? i.e. does a simple ptvsd attach scenario work for you?

**Comment by zooba** [comment]
Also, you don't _need_ to report the bug on both Developer Community and here, but we do triage new DC issues and copy them here when there is something for us to look into.

**Comment by kdriedger-simutech** [comment]
My computer that I had 15.3 RTM installed on has gone to the Computer Hospital (i.e. hardware failure).  When I get it back Monday or Tuesday next week, I'll see if a ptvsd attach on a python 'hello world' works for me.  I'm assuming it will as I had 15.3 Preview 3 working and it stopped after upgrading....  but it should be tested.   I did test on my other machine that has 15.3 Preview 3 on it and the python, hello ptvsd works.  Currently working on a deadline for work and not excited to have my main machine not working with debugging python.

Thanks for investigating!

**Comment by kdriedger** [comment]
Got my computer back.  @int19h Tested attaching to a ptvsd with a console app ('Hello, world') and it works with Visual Studio 2017 Preview - Version 15.3 Preview 7.1 and with the RTM Visual Studio 2017 - Version 15.3

**Comment by kdriedger** [comment]
Here's my hello world:
`print("starting... ")
 
import ptvsd  #ptvsd.settrace() equivalent  
ptvsd.enable_attach(secret = 'sim')
print( "Hey World,eh. Attach to:")
print( "tcp://sim@localhost:5678")
ptvsd.wait_for_attach()

if ptvsd.is_attached:
    print ("Attached debugger, eh")
    #ptvsd.break_into_debugger()

print('hello, eh')
`

**Comment by kdriedger** [comment]
Figured it out myself.  The steps to attach have changed: On the earlier versions (F5 Start Debugging) was acceptable but on the newer versions, you must (Ctrl-F5 Start without Debugging) in order to attach.  Sorry for the diversion.  Looks like it's working for me.  Please close this request.
