### ISSUE TITLE
Anaconda4.4.0访问被拒绝。

### ISSUE THREAD

**Issue by LGL1992** [Microsoft/PTVS#2937]
[Window Title]
devenv.exe

[Main Instruction]
发生意外错误

[Content]
请按 Ctrl+C 复制此对话框的内容并向我们的问题跟踪程序报告此错误。

[^] 隐藏详细信息(D)  [关闭(C)]

[Expanded Information]
```
Build: 3.0.17208.1

System.UnauthorizedAccessException: 对路径“C:\Program Files\Anaconda3\Anaconda 4.4.0\”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   在 System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   在 System.IO.Directory.CreateDirectory(String path)
   在 Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.EnsureScriptDirectory(String path)
```

**Comment by zooba** [comment]
So this is partly a problem where we are assuming we can create the scripts path, and partly a problem in that the scripts path is not supposed to be the interpreter path - by default it should be in your Documents folder. Did you change the default location? Or did this happen by itself?

**Comment by zooba** [comment]
We've decided that this issue is not important enough to continue to pursue. The workaround is to use a user-writable directory for this setting, such as the default value.
