### ISSUE TITLE
Missing package causes Test Explorer to incorrectly report missing test class in module

### ISSUE THREAD

**Issue by mattbenic** [Microsoft/PTVS#2938]
When a unittest.TestCase subclass in a module has a test method that tests functionality depending on a missing package, instead of reporting the missing package when the test is run, it reports the test class as missing:

> Message: 'module' object has no attribute 'Test_Foo'

This is misleading, and does not help diagnose the actual problem.

To recreate:
1. Create a new python project (File->New Project->Python Application)
2. Add a virtual environment for the project (Solution Exporer->Right Click on Python Environments->Add Virtual Environment
3. Add a module, and to that add a function that is dependent on an additional package (do NOT add that package to the environment:
![Foo.py](http://i.imgur.com/fEJI5Dd.png)
4. Add a test class within that module, and add a method that calls the function dependent on the missing package
![Test_Foo.py](http://i.imgur.com/eGSWHOt.png)
5. The function appears in the Test Explorer. Run it.
6. Note that rather than reporting the missing package, the Test Explorer reports the test class as missing:

`Test Name:	test_do_ping
Test FullName:	Foo\Test_Foo.py::Test_Foo::test_do_ping
Test Source:	F:\Win7\Users\Matt\Desktop\PythonApplication1\PythonApplication1\Foo\Test_Foo.py : line 6
Test Outcome:	Failed
Test Duration:	0:00:00

Result StackTrace:	File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\visualstudio_py_testlauncher.py", line 269, in main
    for loaded_test in unittest.defaultTestLoader.loadTestsFromName(test):
  File "C:\Python27amd64\Lib\unittest\loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'Test_Foo'
Result Message:	'module' object has no attribute 'Test_Foo'
Result StandardError:	
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\visualstudio_py_testlauncher.py", line 269, in main
    for loaded_test in unittest.defaultTestLoader.loadTestsFromName(test):
  File "C:\Python27amd64\Lib\unittest\loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'Test_Foo'

`

**Comment by zooba** [comment]
You're right, though I'm not sure whether this is our fault or a Python bug.

Our static code analysis ignores (most) imports when determining which tests exist, and it seems that the Python 2.7 `unittest` module doesn't properly expose runtime errors.

But we may be able to catch the `AttributeError` and do some extra runtime analysis to see whether the module failed to be imported. However, at this stage it's likely that the error is already lost, so the best we can likely do is report that it failed to import for some unknown reason. (Attempting to import the module ourselves before `unittest` does could cause all sorts of other breakage, so I don't want to do that.)

Running the file directly using "Start with/without debugging" should show the error, so perhaps we could recommend that as the next step in our error message?

**Comment by zooba** [comment]
@huguesv Have you checked this case against your current PR? I suspect you'll filter out the entire stack trace when this happens, which means we do need to report an error some other way.

**Comment by mattbenic** [comment]
Ah yes, the start with/without debugging does report a useful error. You're right, as a next/intermediate step simply informing the user to do something along the lines of "Run <filename" with right click->Start without debugging" would definitely be more helpful.

**Comment by huguesv** [comment]
I've tested with and without my changes, and in both cases I see the import error message in test explorer, not the attribute error.
I'm adding a test to validate the error message in this scenario, but I'm not sure why we are seeing different behavior.
Are you on the latest version of VS (15.3)?

**Comment by mattbenic** [comment]
About reports 15.2 (26430.13). Also this is with a Python 2.7 virtual environment and _only_ happens when the class being tested is in a module.

**Comment by mattbenic** [comment]
I can do an update to 15.3.2 when I'm at my office again and have a decent internet connection, I'll retest then.

**Comment by huguesv** [comment]
I was able to repro now. Thanks for your patience.

**Comment by zooba** [comment]
We've decided that this issue is not a high enough priority for now, and so we are closing it to keep our tracker clean. Please reopen with new examples if it continues to be a problem in the latest update.
