### ISSUE TITLE
Interface stuck when use ptvs in vs2015

### ISSUE THREAD

**Issue by danperor** [Microsoft/PTVS#2940]
在VS2015上用PTVS时，打开python enviroments 再点击pip，准备导入pip包的时候，VS2015就无响应了，卡死了。每次必现啊

**Comment by danperor** [comment]
![qq 20170825152749](https://user-images.githubusercontent.com/18207964/29703858-fb989226-89a9-11e7-9a6a-709060f38c39.jpg)

**Comment by zooba** [comment]
Could you open Tools, Python Tools, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

**Comment by huguesv** [comment]
@danperor did you email us diagnostic info regarding this?
