### ISSUE TITLE
Drag/drop tests do not handle dialog

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#2941]
When you drag drop files in Solution Explorer, we pop up a dialog warning you that it may take some time (for some reason - @DinoV, do you remember why?).

The tests don't detect or close this window, so it gets stuck and breaks the rest of the run.

**Comment by huguesv** [comment]
I'm trying to figure out which drag & drop tests you are referring to.
It's not a problem for:
- DragDropCopyCutPaste
- NewDragDropCopyCutPaste

There are some more drag & drop tests in PythonToolsUITests.UITests, those haven't been ported to the new runner.

**Comment by zooba** [comment]
I think I may have got all of these as part of porting the tests to the new runner. Let's close and reopen if we start seeing these tests time out in the runs.
