### ISSUE TITLE
python interactive window crashed after updated with VS 2017 community

### ISSUE THREAD

**Issue by giantchen2012** [Microsoft/PTVS#2950]
Traceback (most recent call last): File "***\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_repl_launcher.py", line 114, in if repl.DEBUG: AttributeError: 'NoneType' object has no attribute 'DEBUG'

VS 2017 with PTVS 3.0.17208.1-15.0

how can i fix this?

**Comment by zooba** [comment]
What would be helpful is if you edited that Python file and added `raise` at the start of the `except` block near the end (in effect, removing the whole `try`/`except` block).

You should get a different error message, and I'm interested as to what that is. `repl` can only be None here if Python is partway through shutting down, and there are *very* few exceptions that we can handle after that has started.

We'll probably have to fix it long term by using `getattr` here and assume that we can't do anything at all.

**Comment by zooba** [comment]
Okay, don't worry about it. I managed to hit the issue with Python 3.1, so I'll add the protections we need to guard against it.

**Comment by giantchen2012** [comment]
OK，It's good to hear that you solved this, I finally rollback to previous edition.
