### ISSUE TITLE
Triple quotes freezing Visual Studio

### ISSUE THREAD

**Issue by j-hudecek** [Microsoft/PTVS#2951]
Hi, 
I've the following code:

    query = "select distinct col from [dbo].table"

    conn.execute_query(query)
    ...  (20 lines of code)
    def otherfunction():
    query = """select ....

When I insert this statement 
    in (""" + ','.join([r["col"] for r in data]) + ")" 
on the empty row the whole Visual Studio 2017 Community freezes with (Not Responding) in window title for about 30s. 

Versions:

Microsoft Visual Studio Community 2017 
Version 15.3.0
VisualStudio.15.Release/15.3.0+26730.3
Microsoft .NET Framework
Version 4.7.02053
Installed Version: Community
Python   3.0.17208.1

**Comment by huguesv** [comment]
I'm afraid we'll need more detailed instructions that allow us to repro the issue. Editor issues often need the exact code to reproduce.

Other options:

- Start a second instance of VS, attach debugger to the frozen devenv.exe, and Debug->Break All (make sure first to uncheck "Enable Just my Code" from Debug/Options. Then CTRL+A and CTRL-C from the call stack window and paste it here.

- Use the VS feedback tool (Help->Send Feedback->Report a Problem), record your steps, cause it to freeze and submit (it can upload a dump).

**Comment by zooba** [comment]
Using the VS feedback tool is the best option - that will automatically include all the information we need.
