### ISSUE TITLE
Msbuild Python project build failure for azure web role

### ISSUE THREAD

**Issue by vvkrishna9** [Microsoft/PTVS#2956]
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(4709,5): error MSB3094: "DestinationFiles" refers to 2 item(s), and "SourceFiles" refers to 1 item(s). They must have the same number of items. [C:\....test.pyproj]

**Comment by zooba** [comment]
What version of Visual Studio are you using? It shouldn't be trying to run with MSBuild 12.0 - that's quite an old version these days.

**Comment by vvkrishna9** [comment]
facing same issue with MsBuild 14.0

**Comment by vvkrishna9** [comment]
"C:\......\LexBadgrCS.sln" (publish ta
rget) (1) ->
"C:\.....\lexbadgr.pyproj" (
Publish target) (3:8) ->
(_CopyFilesToPublishFolder target) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targe
ts(4875,5): error MSB3094: "DestinationFiles" refers to 2 item(s), and "SourceF
iles" refers to 1 item(s). They must have the same number of items. .....\lexbadgr.pyproj]

**Comment by zooba** [comment]
So you are using Visual Studio 2015 then?

Have you tried with Visual Studio 2017? That is the version we are maintaining right now - we've had to shift our focus to the newer one, and so while it's been very significantly improved we haven't been able to fix or update the older version in a while. And ultimately, we aren't going to be able to release any updates for VS 2015 at this stage.

However, it's very likely that this is a simple enough fix in your .pyproj file. Can you share it with us? Either attaching it here (we don't need any code files), or email to ptvshelp@microsoft.com

**Comment by vvkrishna9** [comment]
Hi I have  shared details with my Microsoft account.

**Comment by vvkrishna9** [comment]
[LexBadgr.zip](https://github.com/Microsoft/PTVS/files/1264621/LexBadgr.zip)

**Comment by vvkrishna9** [comment]
I have attached the project file

**Comment by zooba** [comment]
We received it. We're not actually a support team, so occasionally it takes a little longer to respond to these requests than people who don't have other work to do, but I'm taking a look right now.

**Comment by zooba** [comment]
I don't see anything in the project file likely to be causing the issue, so it must be in our old targets files.

If you are building this from the command line, please be aware that is not a supported action for VS 2015. We want it to work, but did not have the resources to ensure it did back then.

If it fails with VS 2017, when run from the command line or in the IDE, we will triage the problem against others that are being considered for our upcoming releases. We don't have time right now to investigate issues that have already been fixed, unfortunately, so if trying with a newer VS is not an option you'll either need to dig into the .targets file on your own or wait for us to get through our current backlog.

**Comment by vvkrishna9** [comment]
[Build.txt](https://github.com/Microsoft/PTVS/files/1275314/Build.txt)
adding build log

**Comment by vvkrishna9** [comment]
build is trying publish  dependent projects which is causing issue, how to stop solution to build and publish  dependencies

**Comment by huguesv** [comment]
Discussing separately and we'll open a new issue if we find something to fix.
