### ISSUE TITLE
Variable highlighting and indent guides

### ISSUE THREAD

**Issue by torquemadaaa** [Microsoft/PTVS#2962]
Hi.
I started using PTVS recently, and have two minor concerns:
1. In promo-videos on PTVS (like v.2.x.x) I noticed that there were definitely indentation guidelines (i.e. for conditional expressions) - but I don't see them in Editor.
2. Variable highlighting for the same occurrence (like in C#/C++) - I believe it was already implemented some time ago (if I read previous issues here correctly), but again - don't have this feature either.
**Environment:**
Extension settings - unmodified.
Latest Visual Studio 2017 15.3.3 with "Python development"
Python Interpreter - 3.6.2 x64
IPython 6.1.0
Everything else works without issues.

**Comment by zooba** [comment]
For 1, you're probably seeing the [Indent Guides](https://marketplace.visualstudio.com/items?itemName=SteveDowerMSFT.IndentGuides) extension. I use it all the time (I also wrote it), and don't always remember to disable it when making videos.

For 2, I don't think we ever did enable that for Python. (Something for @huguesv to consider...)

Glad to hear everything else is working well!

**Comment by huguesv** [comment]
That would be nice indeed. We have an item tracking this: https://github.com/Microsoft/PTVS/issues/76

**Comment by torquemadaaa** [comment]
@zooba Thanks, that extension is exactly what I was referring to! I just was unable to turn on the guideline for non-tabbed expressions - I mean those which zero spaces from the beginning of the line. I assume this was made intentionally to prevent possible overlapping with 'def' [-] rail?
Regarding variable highlighting - I just wish I could contribute to this and other features, but I'm just starting to learn C# and don't even know which .cs file should I dig into.
Again, many thanks for your efforts and kind response!

**Comment by zooba** [comment]
@torquemadaaa If you open Tools, Options, Indent Guides, Appearance then there is an option to modify the style for indent 0 (zero), which is hidden by default. If you make it visible, then it will be there. (It's intentional because I personally don't like it :) But the option is there because people asked for it)

Since we have an existing issue for the other request, I'll close this as a duplicate. But it's on our radar again, so thanks for the poke.
