### ISSUE TITLE
Unable to import pygame

### ISSUE THREAD

**Issue by NowPower** [Microsoft/PTVS#2966]
When I run a game in pygame the __init__.py file is created(the pygame module) and I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Γιάννης\python\race\A bit racey.py", line 1, in <module>
    import pygame
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\pygame\__init__.py", line 133, in <module>
    from pygame.base import *
ModuleNotFoundError: No module named 'pygame.base'
```

The pygame is installed, so the 'pygame.base' should exist.

**Comment by huguesv** [comment]
You should try to start it from the command line, outside of Visual Studio to see if that works any better.

I just installed pygame (using pip) into a 32-bit and also 64-bit Python 3.6 virtual environment, and ran `import pygame` successfully on both using F5 to start debugging from Visual Studio 2017.

**Comment by NowPower** [comment]
I did it by uninstalling and reinstalling pygame using pip. Thanks

**Comment by rrraj** [comment]
I also encountered similar error, though I have uninstalled and reinstalled pygame multiple time (in the correct path and correct version), can anyone help?

**Comment by Jeeroxz** [comment]
@rrraj I had the same issue as you and couldn't find anything to help me anywhere. I tried out many things and for me the issue was that my python was 32 bit and it couldn't work with pygame. I uninstalled python and installed a 64 bit version and now everything works well.

Hope this helps.
