### ISSUE TITLE
Cookiecutter clone repository never terminates on missing repository

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2984]
In the Cookiecutter search bar, enter the URL to a private GitHub repository, or just make up a URL to a repository that doesn't exist.

Click Next, the progress bar turns into "Cloning repository..." which never ends and cannot be canceled.

**Comment by huguesv** [comment]
It's not finding the repository, so it's asking for username/password:
```
C:\Projects\temp>"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin\git.exe" clone https://github.com/Microsoft/PTVS122
Cloning into 'PTVS122'...
Username for 'https://github.com':
```

**Comment by huguesv** [comment]
This code from `ProcessOutput` may not be working as intended?
```
                if (_process.StartInfo.RedirectStandardInput) {
                    // Close standard input so that we don't get stuck trying to read input from the user.
                    try {
                        _process.StandardInput.Close();
                    } catch (InvalidOperationException) {
                        // StandardInput not available
                        Trace.WriteLine(_process.HasExited);
                    }
                }
```

**Comment by huguesv** [comment]
I wasn't able to find any command line arguments that work to prevent username/password input.

**Comment by zooba** [comment]
The prompt is probably coming from a subprocess, which is why closing stdin for the original process doesn't help. I'm not sure of the best way to suppress this - perhaps we just need a timeout? Say 15 seconds without any new output being shown?

Perhaps we could pop up a dialog at that point saying that it may be an unreachable git repository and offer to run an interactive clone operation that may prompt for login credentials?

**Comment by huguesv** [comment]
This kind of works. There is a problem, we don't get any output during the download phase. During the checkout phase, we get output. So we could be timing out if download is too slow. We could make the pop up dialog a 3 choice selection (continue waiting, stop, try again with console) and that might be good enough. Realistically, those cookiecutter repos shouldn't be that large, but slow internet can be slow sometimes...

Here's what I mean by not getting all output:
![image](https://user-images.githubusercontent.com/1696845/30493204-1cc2c94a-99f8-11e7-9d9c-d059768d00e9.png)
We get this:
```
Cloning into 'PTVS'...
Checking out files:   3% (164/5268)   
Checking out files:   4% (211/5268)   
Checking out files:   5% (264/5268)   
Checking out files:   5% (277/5268)   
Checking out files:   6% (317/5268)  
```

**Comment by zooba** [comment]
We could pop up the "working on it" dialog with a cancel button? Blocking the entire UI is not very nice, but neither is implementing all of that UI manually. Then if the user cancels, we can ask if they want to retry with an open console window.

**Comment by huguesv** [comment]
If the user clones a template from a private repository (either via command line tool, from our UI if we show them the console, etc.) then when we get to the "check for updates" phase, we'll also get stuck because that hidden console will ask for login.

I feel like the right solution is to use the git dll directly, not go through git.exe. We didn't do that because it was easier from a legal point of view to use the existing install, but maybe we need to revisit that decision and see if there's a way to make it work legally.
