### ISSUE TITLE
Blank tab and error page in project properties with build PTVS.Dev.2015-05-28.VS.2013

### ISSUE THREAD

**Issue by andygraham** [Microsoft/PTVS#299]
I've just loaded PTVS.Dev.2015-05-28.VS.2013.msi on a 64bit Windows 7 Home Premium system and VS Express 2013 Desktop.

When I open the properties of an IronPython project by any means I get a blank tab above the usual General, Debug and Publish tabs. Selecting this blank tab shows an error page.

An error occurred trying to load the page.
Class not registered. Looking for object with CLSID: {00000000-0000-0000-0000-000000000000}.

I've also seen, on the same projects, this different error associated with the blank tab.

An error occurred trying to load the page.
Unable to create the designer.  File is already opened in an incompatible editor.

This does not occur with PTVS 2.2 RC VS 2013 which shows only the usual General, Debug and Publish tabs.

**Comment by andygraham** [comment]
I've' just seen #166. This looks to be the same problem.

**Comment by crwilcox** [comment]
Will close this issue as the other one you note is tracking this.

Thanks for letting us know you are still seeing this.
