### ISSUE TITLE
Can't load a picture in pygame

### ISSUE THREAD

**Issue by NowPower** [Microsoft/PTVS#2997]
I try to load an image with pygame.image.load() in pygame which is in the same directory as the code file but vs respondes that the image couldn't be load.
Thanks for the help.

**Comment by int19h** [comment]
Is the code file in question at the root folder of your project?

**Comment by NowPower** [comment]
The image wasn't in the root folder. After I moved it there the problem was fixed.
Thank you a lot, I couldn't figure it out.
