### ISSUE TITLE
Debugger helper DLL appearing in stack traces

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#2998]
Occurs in mixed-mode debugging with Python Developer mode enabled.

![image](https://user-images.githubusercontent.com/1693688/30037577-120ca91a-9171-11e7-85e3-12914735448c.png)

**Comment by int19h** [comment]
I think this is actually by design - the "Show Native Python Frames" option is really more of a "don't hide anything" option. I'd like to keep this in some shape or form, since it allows debugging stepping and breakpoints in the helper. I suppose we could have a separate option for the helper?

**Comment by zooba** [comment]
The biggest problem is that you can't see anything when you double click on it. Maybe if we had a registry key to really show everything, and otherwise synthesize a `<Native to Python transition>` frame?
