### ISSUE TITLE
Allow MSBuild property to enable Python Developer mode for MMD

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#2999]
I'd like to be able to automatically enable Python Developer mode in the CPython sources, since that is the most likely case.

We should add an MSBuild property for C++ projects that can start debugging in this mode without needing the registry key. It would also be nice to be able to enable the extra options (or maybe have them enabled by default when in developer mode?)

**Comment by int19h** [comment]
I don't know if all of them make sense enabled by default. E.g. do you really usually want stepping to work on C level? Displaying python.dll frames certainly makes sense, yes.

**Comment by zooba** [comment]
We'd probably have to test the stepping option to see what makes sense as a default, but you're probably right.
