### ISSUE TITLE
Code coverage with PTVS

### ISSUE THREAD

**Issue by mayito** [Microsoft/PTVS#3008]
Hi,

I've installed Visual Studio 2017 Community Edition and PTVS from the Data Science workload.

I've launch some unit tests from the test explorer but nothing appears in the code coverage window.

Can you tell me how to enable this feature ?

Regards,

Thierry.

**Comment by huguesv** [comment]
Sorry, but the feature is not available on Community Edition.

Here's how it's used, taken from the Enterprise Edition (not sure about support in Pro Edition):
![image](https://user-images.githubusercontent.com/1696845/30284020-a171c84e-96ce-11e7-83d2-be74bc56c492.png)

**Comment by huguesv** [comment]
Here's a Visual Studio User Voice item I found regarding this.
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/7839528-include-code-coverage-analysis-in-professional-edi

**Comment by zooba** [comment]
There's nothing we can do to enable this from Python support - voting on the linked User Voice item is the best way to convince the code analysis team to make it available on downlevel versions.

You may also want to look into using the [coverage](https://pypi.org/project/coverage/) package directly. This won't give you the nice overlays we can display in Visual Studio 2017 Enterprise, but it will still make the information available to you (this is the same tool that we use to collect the code coverage data, so you won't miss anything except the visualization).
