### ISSUE TITLE
Python Tooltip when hovering long string overlap mouse

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3011]
(Reported at https://developercommunity.visualstudio.com/content/problem/109893/python-tooltip-when-hovering-long-string-overlap-m.html)

When editing a Python script, if we put the mouse over a string value waiting  for a second, a tooltip appears near the mouse displaying the string.
Generally the tooltip is display on bottom right of the mouse, which is OK.

However, if we have a long multiline string, let's say taking most of the screen height, then the tooltip appears behind the mouse (see attached screen) making almost impossible to select the text itself. We have to continuously fighting against this damned tooltip to select the text.

I didn't found any option to turn off this tooltip.
I don't know if it's related to python only or if it's the case for other languages too.

**Comment by zooba** [comment]
We should really just trim the string contents in tooltips. It's easy enough to F12 or Ctrl+Click to see the full string, and the most valuable uses of this are when the string length is short anyway.

**Comment by huguesv** [comment]
It's also pretty annoying when you are trying to CTRL click. You have to race against the tooltip.

**Comment by zooba** [comment]
Actually, we only show them on the literal itself... let's just stop doing that.

**Comment by huguesv** [comment]
For me it was a problem hovering on `json.dumps` (which I was trying to CTRL click on).

**Comment by zooba** [comment]
That's probably too much docstring in the tooltip, I'm guessing? That's different from a string literal, which is what this specific complaint is about (pretty sure we have another one for docstrings)

**Comment by huguesv** [comment]
You're right, it's docstring in my case.

FYI https://github.com/Microsoft/PTVS/issues/2474 proposed removing string literal tooltips as well.

**Comment by huguesv** [comment]
And https://github.com/Microsoft/PTVS/issues/622 too :)

**Comment by zooba** [comment]
Let's deal with it in #622
