### ISSUE TITLE
Certain python errors cause the code to just freeze

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3012]
(Reported at https://developercommunity.visualstudio.com/content/problem/109407/certain-python-errors-cause-the-code-to-just-freez.html)

When debugging python code, some errors (most recently an undefined variable) result in python just freezing. The debugger shows it as still running, but nothing is happening. If I run the code by choosing "Starty without debugging" I'll see the exception message.

**Comment by huguesv** [comment]
I'm trying to repro by working on bugs that require writing Python instead of C#, but I don't like my odds already.

**Comment by zooba** [comment]
I wonder if this is the same as #2707 (reported by the same user). Might just have to close it as not-enough-info (again).

**Comment by zooba** [comment]
There is not enough information for us to work on this issue. Please let us know if you have a piece of code that reproduces reliably on more than one machine so we can try and track it down from that.
