### ISSUE TITLE
Test executor failures on Python 3.0 only

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3034]
These tests fail, not sure if product is affected but it probably is. I went back to Sept 4 commits and they still fail. I thought they all passed when I introduced multi-Python tests some weeks ago.

- TestExecutorTests30.TestRun
- TestExecutorTests30.TestRunAll

Output has a bunch of ImportErrors that don't appear on other Python versions, like these:
```
ImportError: No module named TestAdapterTestB

ImportError: No module named TestAdapterLibraryOar
```

**Comment by huguesv** [comment]
I just checked and they didn't pass when the multi-Python tests were introduced. Not sure how I missed that.

**Comment by zooba** [comment]
We should probably drop Python 3.0 support completely. I consider this very low priority until we hear some serious complaining about it not working (assuming later versions do work).

**Comment by zooba** [comment]
We are going to stop supporting Python 3.0. The UI visible options can remain, so we don't instantly break anyone who happens to be using it, but as time allows we should remove them to avoid people suffering unexpectedly due to bit-rot.
