### ISSUE TITLE
Activate python environment blocks UI for a few seconds

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#304]
Activating a python env will sometimes cause a delay of a few seconds that freezes VS.  Worse when it's an env that hasn't been activated in that VS session.

This isn't new, it's been bugging me ever since the feature was introduced.

**Comment by zooba** [comment]
Can you add a bit more detail about the context here? We load the DB on a background thread, so there shouldn't be any cases that freeze the UI anymore.

**Comment by zooba** [comment]
This should be fixed by now - the delay is as short as we can reasonably get it without rewriting the DB.
