### ISSUE TITLE
Better handling of broken Python environments

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3057]
Some users have complained that we auto-detect environments that they've uninstalled.

From https://github.com/Microsoft/PTVS/issues/18

Quote: "Maybe we should check whether the path exists when we detect from the registry and just ignore invalid paths? I think that may hide more problems than it helps though..."

Chatted with @DonJayamanne, we agreed to both do the folder check and python.exe check, and not 'auto-detect' if they are missing.

**Comment by huguesv** [comment]
We'll keep showing them and put a link to the doc page.

**Comment by zooba** [comment]
https://docs.microsoft.com/en-us/visualstudio/python/python-environments#moving-an-existing-interpreter is the documentation I was thinking of, but it is less strongly worded that I remember. We may need to generate specific help for this situation.

**Comment by karthiknadig** [comment]
We need to make sure all the commands are disabled, (e.g, set as default environment is enabled for my old Anaconda 4.0.0 which i uninstalled).

In the UI view for the environment, there text could be **strike through**. that would indicate people cannot use it even if it is there.

**Comment by karthiknadig** [comment]
It should also be taken out of this list:
![image](https://user-images.githubusercontent.com/3840081/32863191-828a33a2-ca0f-11e7-9086-754032750eb7.png)
