### ISSUE TITLE
While debugging "import gensim" takes more than 5 mins to load

### ISSUE THREAD

**Issue by Venu-prahalad** [Microsoft/PTVS#3062]
Hi,
I have setup a python project. I am using gensim library. When I debug(using F5) PTVS is pretty responsive until it hits the line "import gensim" or "from gensim import utils". Once the said lines are executed, debugger takes more than 5 mins to load gensim. This is observed in VS 2017 also along with VS 2015 versions.
If I try debugging the same code using spyder, debugger comes loads it pretty quick. This makes me think something wrong with PTVS.
Is this an issue or am I doing something wrong? 

Thank you.

**Comment by huguesv** [comment]
There were some performance improvements that went in for VS 2017 15.4, which will be available soon (you can also get it now using the preview channel).
See https://github.com/Microsoft/PTVS/issues/2797
