### ISSUE TITLE
Customer issue: IntelliSense giving wrong completions

### ISSUE THREAD

**Issue by kraigb** [Microsoft/PTVS#3075]
Verbatim left in the docs 9/13/2017. Unfortunately this is all the information given, and there's no contact information. 

"I did refresh DB for my python 3.5 in VS2015 and VS2017, but they both show wrong IntelliSense, it is showing the functions doesn't beonlg to current class."

If this is unactionable without additional repro cases, feel free to close.

**Comment by zooba** [comment]
Yeah, afraid it is not directly actionable, but we do have longer-term work (that will appear in the next couple of updates) that may help.
