### ISSUE TITLE
Rename function identifier in editor gives "Unable to get analysis for current text view"

### ISSUE THREAD

**Issue by kraigb** [Microsoft/PTVS#3085]
Visual Studio 15.3.5, Python 3.0.17240.1

Repro steps:

1. File > New File, select Python module.
2. Add code:
        def test(x):
            return x
3. Right-click "test" and select Rename. This works.
4. Double-click "test" to select it, then right click and select Rename. This produces the error message.
5. Put a space after "test" before the (, then double-click to select, right-click, Rename. This again works.

So something in the analyzer is getting confused with the identifier running into a (.

**Comment by zooba** [comment]
Hmm... this sounds awfully like the Go To Definition issue #2548. I wonder if they have the same underlying cause

**Comment by huguesv** [comment]
Probably duplicate of https://github.com/Microsoft/PTVS/issues/2287
