### ISSUE TITLE
Cannot attach to running module. +question about embedding

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/PTVS#3094]
_From @qpIlIpp on September 29, 2017 7:54_

## Environment data
VS version:   vs prof 2015, 14.0.25431.01 up3.
Python tools for visual  studio: 2.2.50113.00
Python Version:   python-3.5.2. Win32 on both machines
OS and version:   winserver2012.r2 + win10 enterprise

## Actual behavior
cannot attach to remote python

## Expected  behavior
attach is successful 

## Steps to reproduce:  
I have 2 windows machines. Visual studio 2015 + pyt tools is installed on winserv machine. Python 3.5.2 is installed on both machines.
first of all, python asks me to upgrade pip (python -m pip install --upgrade pip) (see log) on both machines, after that ptvsd version is "ptvsd-3.2.1.dist-info"
I created pytyhon project, which contains code from https://docs.microsoft.com/en-us/visualstudio/python/debugging-cross-platform-remote , copy script on the second machine and started from "python.exe" console (just "import my" command), so it has started and I tried to attach from the first machine.
Firewalls are turned off on both machines. All info about the environment is in the header.
I got exception "remote server at tcp://aaaaaaaa@ip:5678/ is not a Python Tools for Visual Studio remote debugging server, or its version is not supported". After I clicked cancel I got "unable to connect to '..'. Operation not supported, Unknown error: 0x80004005."
So I have the same python on both machines, the same modules, the same ptvsd versions on both win machines, have turned off firewalls, but still cannot connect. What am I doing wrong?

In addition, I want to know: I have written my own c++ app, which is using python C API (py_init, py_invoke etc), am I able to debug with ptvsd my custom C++ application, which is using CPython C API?

## Logs
cmd installation:
c:\Python>python -m pip install --upgrade pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 706kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-9.0.1

c:\Python>pip3 install ptvsd
Requirement already satisfied: ptvsd in c:\python\python35-32\lib\site-packages

_Copied from original issue: DonJayamanne/pythonVSCode#1256_

**Comment by DonJayamanne** [comment]
The latest version of PTVSD is not supported by this extension. Please revert to the older version 3.0.0.

**Comment by DonJayamanne** [comment]
_From @qpIlIpp on September 29, 2017 16:10_

Ok, thnx. But what's about second part of question about embedding?

**Comment by DonJayamanne** [comment]
@qpIlIpp 
My sincerest apologies, this is NOT an issue related to Visual Studio **Code** (cross platform editor), you are using the big brother Visual Studio 2015 Pro for Windows.

I'll move this issue soon, please disregard my previous comments.

**Comment by huguesv** [comment]
Hi, please check the connection troubleshooting section of https://docs.microsoft.com/en-us/visualstudio/python/debugging-cross-platform-remote which lists the version of ptvsd that you must install for your version of Visual Studio.

For the latest builds of VS 2015, it should be ptvsd==2.2.6

**Comment by qpIlIpp** [comment]
Thanks, I'll try. (How can I get exact version?) What's about embedding (the second part of question)?

**Comment by zooba** [comment]
Use `pip install ptvsd==2.2.6` to get the exact version.

You can use mixed-mode debugging from Visual Studio (see https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode), but not from Visual Studio Code. You cannot use ptvsd for this right now - you'll either need to be on the same machine and use Debug/Attach, or follow the [instructions for C++ remote debugging](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-cpp) to set up msvsmon on the remote (Windows) machine and then use Debug/Attach.

**Comment by qpIlIpp** [comment]
Ghm, I was able to debug python.exe, but version 2.2.6 doesn't exist on the server, so I've installed 2.2.0. Thnx.
About second part:
Anyway, I cannot debug my C++ app, it had thrown an exception: "No module named '_socket'".
Steps to reproduce: create console app, set up link and incl addition folders to python, try to load py_import file with "import ptvsd". got error.
I attached zip with solution, it contains code for reproducing. Just download it, correct to your own paths to python, build and start. Although attached screenshot wit error.
Files:
[PytImportPtvsdError.zip](https://github.com/Microsoft/PTVS/files/1348750/PytImportPtvsdError.zip)
![importerror](https://user-images.githubusercontent.com/32383682/31075702-4c70aa72-a790-11e7-9c08-0e3c678a4a63.png)

w8ing for your answer, thank you =)

**Comment by zooba** [comment]
This error is more likely due to a problem in your Python install. There should be a `_socket.pyd` file either next to your `python.exe` or in the `DLLs` directory, and this seems to be missing.

**Comment by qpIlIpp** [comment]
Hmm, I'll see tomorrow, thanks. But that script works correct from Python.exe console, so it automatically finds that file...

**Comment by qpIlIpp** [comment]
Looks like its the python bug, it repeats with c/c++ only with script with "import socket" :
https://mail.python.org/pipermail/python-dev/2012-April/119050.html
https://bugs.python.org/issue4566
I will search the solution. Will write with some results.

**Comment by zooba** [comment]
If you're on Python 3.5.2 then that issue is very out of date and likely doesn't apply.

If you run `<path to your custom python.exe> -c "import _socket"` under the native debugger you should get more information about what DLL cannot be resolved.

**Comment by qpIlIpp** [comment]
The problem was easier :)  https://bugs.python.org/issue30446
I've built debug, but there is not '_socket_d.pyd' file in distributives. It's ok for debugging (release config), but only once.

Let's go further. 
1. Am I able to get ptvsd 2.2.6? There's not that version on servers.
2. When I start python script, twice (py_init py_finalize) I'm getting AV in second Py_initialize. Whose problem is it, ptvsd or python? See attach.
thank you! =)
![importerror2](https://user-images.githubusercontent.com/32383682/31109900-6b482542-a81c-11e7-93be-74143667bd3e.png)
![importerror3](https://user-images.githubusercontent.com/32383682/31109901-6da90f5e-a81c-11e7-8fc0-33663aa4ccb6.png)

[Source.cpp.txt](https://github.com/Microsoft/PTVS/files/1351139/Source.cpp.txt)
[my.py.txt](https://github.com/Microsoft/PTVS/files/1351140/my.py.txt)

**Comment by zooba** [comment]
Apparently ptvsd 2.2.6 isn't a real version - not sure where that came from. Use 2.2.0 if that works.

ptvsd is pure Python code, so the problem is definitely in Python. It is not very well designed for multiple initializations in a single process - there is work going on for Python 3.7 to improve that.

**Comment by qpIlIpp** [comment]
ok, thank you! I think we've done here. 
I appreciate your help! :)

**Comment by zooba** [comment]
No worries, happy to help
