### ISSUE TITLE
Microsoft Visual Studio 2017 crashed out of nowhere

### ISSUE THREAD

**Issue by julmarqu** [Microsoft/PTVS#3098]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 3.0.17208.1

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
   at Microsoft.PythonTools.Intellisense.TaskProvider.Refresh()
```

**Comment by zooba** [comment]
Hi @julmarqu. I think we have already made changes to fix this bug, or at least improve the error message so that we can diagnose what the underlying cause is. Can you try updating your install to the latest version?

**Comment by julmarqu** [comment]
Updated shortly after the crash to 15.3.5. I will let you know if it happens again. thanks

.:|:.:|:.   Julio Marquez
Consulting Engineer
Cisco Services
julmarqu@cisco.com<mailto:julmarqu@cisco.com>
Phone: +1 615 507 2524
Mobile: +1 615 585 6540
CCIE - 38209
