### ISSUE TITLE
Examples for PyKinect

### ISSUE THREAD

**Issue by TjWhale** [Microsoft/PTVS#3103]
I've been trying to hack something together using PyKinect. I'd really benefit from some simple examples of  how to use the audio functionality. I can't seem to find any online.

How do you access the microphone array and then how to do you interpret the data which is read from it?

**Comment by zooba** [comment]
I think @DinoV or @crwilcox are most likely to be able to help out here.

**Comment by crwilcox** [comment]
@TjWhale, I don't think I have ever used the microphone bits :(. Also, are you trying to use PyKinect or PyKinectV2? Most of my experience is with v2 (https://github.com/Kinect/PyKinect2)

**Comment by TjWhale** [comment]
@crwilcox Thanks for the response. At the moment I've just been trying to use PyKinect. 

Do you know what functionality the audio system has? I'm under the impression that it can locate sounds in the space in front of it which is cool so I'd be interested in trying it out. I also saw a couple of pages saying the SDK has some speech recognition capability.

I'm interested in using the kinect to make a simple robot so that would be really cool.

**Comment by huguesv** [comment]
Not investing in the PyKinect libraries anymore.
