### ISSUE TITLE
Command "Python.SendSelectionToInteractive" is not valid.

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3114]
`ReplWindowSendUITests` all fail due to this.

Tried to type it in the command window, get the same error and it doesn't appear in IntelliSense.

`Python.ExecuteInInteractive` which is defined right above in .vsct works fine.
`Python.FillCommentParagraph` which is defined right below in .vsct does not work either.

**Comment by zooba** [comment]
It's probably under `Edit.SendSelectionToInteractive` because of the way VS determines which parent is the most important.

Historically, I guess it has been under `Python` or we wouldn't have written the test that way. Probably worth using the `.Python.` hack in the vsct file to force the name.

**Comment by huguesv** [comment]
Ah yes, they are both under Edit.
