### ISSUE TITLE
Bug in Pykinect function NuiImageGetColorPixelCoordinatesFromDepthPixel

### ISSUE THREAD

**Issue by TjWhale** [Microsoft/PTVS#3118]
I was trying to get the function

NuiImageGetColorPixelCoordinatesFromDepthPixel

which is here, 

https://github.com/Microsoft/PTVS/blob/master/Python/Product/PyKinect/PyKinect/pykinect/nui/_interop.py

line 192 to work in PyKinect and it kept throwing the error "byref(x)" is not defined. I found this page about the issue

http://pytools.codeplex.com/workitem/1078

and it said to change byref(x) and byref(y) to ctypes.byref(x) and ctypes.byref(y) in _interop.py and when I did this the function worked fine so I think it might be a bug. 

If you look at line 186 in _interop.py you can see ctypes.byref(res) being used there.

Hope this is helpful :)

**Comment by zooba** [comment]
That certainly looks like a bug.

We don't get to bugs in our sample libraries very often, but if someone brings a pull request then we'll happily merge it.

**Comment by rv404674** [comment]
Hi @tjwhale, is this bug still open. I am a newcomer and would like to contribute.

**Comment by TjWhale** [comment]
@rv404674 it looks like it is. I got it to work locally by making the change I suggested so I think if you make a pull request it should get accepted. Worth testing first of course. Good luck.

**Comment by rv404674** [comment]
hey @TjWhale , i have opened a PR for the same. Can you please take a look when you get some time. Thanks. :)

**Comment by huguesv** [comment]
Thanks everyone. I merged https://github.com/Microsoft/PTVS/pull/4747.
