### ISSUE TITLE
Intellisense with WSL extension?

### ISSUE THREAD

**Issue by ccarlsonpb** [Microsoft/PTVS#3128]
Hi, I'm currently using the WSL extension mentioned [here](https://blogs.msdn.microsoft.com/pythonengineering/2017/08/25/python-updates-in-visual-studio-15-4-preview-1/) and I was only able to get intellisense working if I manually added the following paths to the project's search paths: 

```
%LOCALAPPDATA%\lxss\rootfs\usr\local\lib\python3.5\dist-packages
%LOCALAPPDATA%\lxss\rootfs\usr\lib\python3\dist-packages
```

I was wondering if there was a better way to go about doing this.

**Comment by zooba** [comment]
Currently there is not, but a big part of the reason we aren't going to include that extension as-is is because it doesn't do IntelliSense. When we integrate WSL properly, it will be able to do it. (It falls under #185, so I'll close this issue.)
