### ISSUE TITLE
Optional pep8 formatting

### ISSUE THREAD

**Issue by BenjaVR** [microsoft/PTVS#3130]
I checked issue #1465, where @zooba said they do not prefer any particular style in VS.

Yet I was wondering why there is not an option to enable complete pep8 formatting. It's easier to work together with people using PyCharm that way, and even VSCode has the python plugins to format like this.
In fact on of the plugins is using [autopep8](https://github.com/hhatto/autopep8). Could this be considered for PTVS?

**Comment by zooba** [comment]
I've added it as a feature to consider. Currently we only support one variety of formatting, which is our own (and honestly it isn't very good - there are a lot of things that are not formatted properly).

Since we don't have a plugin architecture, it isn't trivial to add support for an external library like this. It'll take a bit of work.

**Comment by BenjaVR** [comment]
Would you accept contributions for this? And if so, could you also provide some general thoughts about how you could eventually implement this? Maybe I can try to help where I can.

**Comment by zooba** [comment]
If you want to look in `Microsoft.PythonTools.targets` at how we did very basic pylint support, you could probably clone that to work for a linter. You can add the definition into your own .pyproj file for testing, and submit a PR against the targets file to enable it for everyone's projects.

Ideally we'd be looking at an editor extension that can continuously run the plugin in the background and generate errors and squiggles live. That's a fairly significant task, but if you've got good C# skills and have created other VS extensions in the past, we can probably help you do it.

**Comment by BenjaVR** [comment]
I honestly have no experience with extensions. I will look into it anyway, but probably won't be of any help though.
