### ISSUE TITLE
Have better theme support for VSDarkTheme,  content hidden in black

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/PTVS#314]
![problematic theme](https://cloud.githubusercontent.com/assets/4545925/7981445/89ee2428-0acc-11e5-96ff-986e9565b82f.PNG)
![after highlight](https://cloud.githubusercontent.com/assets/4545925/7981447/8b15a768-0acc-11e5-8b5a-49b3cc40db11.PNG)

It's a little tough to see the function brackets or the assignment operators etc.., It'd be great if these were of a different color so that it blends in with the dark theme without these posing a problem to see them on the editor.

**Comment by zooba** [comment]
What versions of PTVS and VS are you using? We had this issue at one point, but it should be resolved in the latest versions (and should have been resolved in 2.1 too).

**Comment by sudheesh001** [comment]
PTVS 2.1 and VS2015

**Comment by zooba** [comment]
Are you sure? We never released PTVS 2.1 for VS 2015. Maybe you got one of the 2.2 pre-release versions?

**Comment by zooba** [comment]
In fact, you definitely have one of the later versions because I can see outlining on return statements.

When you go to Tools, Options, Fonts and Colors and scroll down to the Python items, are they all set to Default?
