### ISSUE TITLE
Send to Interactive: multiple projects

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#3165]
Hi

Is there a way to target a particular environment for send to interactive? When I have a solution with multiple projects, running "send to interactive" in different project sends the code to different environments. Is there a way to force them to go to the same environment?

Thanks

**Comment by zooba** [comment]
Not currently, but we have an open item to add a "target" button - see #2006 and let us know whether that would work better for you.

**Comment by sriksrid** [comment]
Hi

A target button should work great. In my use case, it would be nice if the default send to interactive would be to send code the last used environment (unless i explicitly set the file target to be a particular environment). 

Thank you

**Comment by zooba** [comment]
Great! I'll add your comment to the other issue and close this one.
