### ISSUE TITLE
Generate SignatureAnalysis without using GetExpressionRange

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#3171]
As part of #3166 we are removing uses of `GetExpressionRange`. The only remaining uses are analyzing signatures to find the current parameter, which does not have an equivalent yet.

We should update signature analysis to not need this function.

**Comment by zooba** [comment]
This also selects the wrong parameter index in code like this:

**Comment by huguesv** [comment]
Improvement no longer relevant.
