### ISSUE TITLE
Cross-project IntelliSense doesn't work properly

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#3197]
This repro involves two projects, named `foo` and `baz`.  

Here is the directory tree layout:
```
ptvs_bug/
├── foo/
│  ├── __init__.py
│  └── bar/
│      ├── __init__.py
│      └── MyClass.py
└──baz/
   └── baz.py
```

I have created one project for `foo` using `File -> New -> Projects -> From Existing Python Code`
I have then created another project for `baz` using the same workflow.  

I right clicked on the Search Paths for `baz` and manually pointed to `ptvs_bug`, which ultimately gets resolved to the relative path `..`.

Here is the code for each of these files.
```python
# ptvs_bug/foo/__init__.py
# This file is empty.
```

```python
# ptvs_bug/foo/bar/__init__.py

import MyClass

my_class = MyClass.TheClass()
my_integer = 7
```

```python
# ptvs_bug/foo/bar/MyClass.py
class TheClass(object):
    pass
```

```python
# ptvs_bug/baz/baz.py
import sys
print(sys.path)

from foo.bar import my_integer
from foo.bar import my_class

x = my_integer
x = my_class
pass
```

In a Python 2.7 environment, the two imports in `baz.py` get squigglies.  I can get rid of them by adding `from __future__ import absolute_import`, but I still get `<unknown type>` when hovering on `my_integer` and `my_class`.

In Python 3.6, the behavior is the same as using a 2.7 environment and using absolute_import.  

All of the search paths are correct, because the program runs just fine, and the `print(sys.path)` line confirms that the correct paths are indeed present.

This may be related to Issue #3159, but it's not entirely clear, and the poster there did not provide a reproducer, which I have here.

I ran Diagnostics which you can see [here](https://gist.github.com/zjturner/c6c2de46cbdc7d07051879eb8d298de5), and I notice some exceptions that look might suspicious.  For example:

```
[10/20/2017 16:34:34] AnalysisOperationFailed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Analysis.LocationInfo.GetHashCode()
   at Microsoft.PythonTools.Analysis.AnalysisVariable.GetHashCode()
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.IsMissingImport(IsMissingImportRequest request)
   at Microsoft.PythonTools.Intellisense.OutOfProcProjectAnalyzer.<RequestHandler>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Ipc.Json.Connection.<ProcessRequest>d__29.MoveNext()
```

Hopefully this is enough information to help track it down.

**Comment by zjturner** [comment]
This is using 15.4, by the way.

**Comment by zooba** [comment]
I suspect the issue may be the same as #3159 (which I'm about to test specifically for this - waiting for machines to wake up after the weekend right now :) ).

That error is also helpful, but very unlikely to be the cause. But I'll fix it too!

**Comment by zooba** [comment]
I've confirmed that this issue is fixed, so our next update to 15.4 should include it. Thanks!

**Comment by zjturner** [comment]
Is there any way to get a preview build?  I trust that you did indeed fix it, but my real project is much larger and more complicated than the minimal repro I came up with for this bug report.  Happy to test on a larger codebase for additional confirmation if there's an easy way to do it.  Otherwise I'll cross my fingers and wait :)

**Comment by zooba** [comment]
Afraid not. We decided to "skip" the current preview release and focus our efforts on the next one, which allows us to do bigger pieces of work. We also plan to update the current Preview release with this bugfix (or else the 15.5 release would also have the same bug...), but it's not clear whether that will be released before the next update to the main release.

Alternatively, if you can build PTVS yourself, you should be able to drop in the DLLs to their install directories and test them that way. You'll need to run our registry script to disable strong name verification (part of the build instructions on our wiki), and it's a very manual (and unsupported) install step. But it works. Our `v3.2` branch has the fix - master is significantly less stable right now.
