### ISSUE TITLE
VS2015 No response

### ISSUE THREAD

**Issue by xiaomaxiao** [Microsoft/PTVS#3198]
when i open ptvs ， VS2015  No response .

**Comment by zooba** [comment]
Can you provide some more information?

**Comment by xiaomaxiao** [comment]
@zooba 


1.
python environments ->pip 

For example, I would like to install opencv. so i input opencv , VS2015 no response.

i think PTVS is being traversal package?

2.

if i add too many picture files  in one folder. when i open ptvs , VS2015 no response.

i think ptvs is being Traversed the folder?

Can you improve these problems?

**Comment by zooba** [comment]
If we can improve them, they would only be improved in Visual Studio 2017. We are no longer updating VS 2015.

Can you try your scenarios with Visual Studio 2017 and if you still have issues, can you provide screenshots indicating what you are doing and where it is failing?
