### ISSUE TITLE
__init__() error and NoneType error when attach the ptvsd

### ISSUE THREAD

**Issue by naeco2005** [Microsoft/PTVS#3201]
Hi, 

My program is a C++ software which UI is developed with QT. We embed a Python process inside. When Python process is initialized, we redirect stdout and stderr with following codes:

```python
import sys
class CatchOutput:
	def __init__(self):
		self.value = ''
	def write(self, txt):
		self.value += txt
	def flush(self):
		pass
catchOutput = CatchOutput()
sys.stdout = catchOutput

import sys
class CatchOutErr:
	def __init__(self):
		self.value = ''
	def write(self, txt):
		self.value += txt
catchOutErr = CatchOutErr()
sys.stderr = catchOutErr
```

Once my program starts, i will call ptvsd::enable_attach and then call ptvsd.wait_for_attach() waiting for attachment. 

when i begin to attach my program with VS2015, i always see the following issues:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__() missing 2 required positional arguments: 'old_out' and 'is_stdout'
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2288, in _excepthook
    do_wait()
  File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2413, in do_wait
    sys.__stdout__.write('Press any key to continue . . . ')
AttributeError: 'NoneType' object has no attribute 'write'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__() missing 2 required positional arguments: 'old_out' and 'is_stdout'
KeyError: '__main__D%3A%2FNeutron%2Fmain%2Fsrc%2FLib64%2FDebug_Build%2FDebug%2FPython%2FSamples%2FSpurGear%2FSpurGear_py'
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2288, in _excepthook
    do_wait()
  File "D:\Neutron\main\src\Lib64\Debug_Build\Debug\Python\lib\site-packages\ptvsd\visualstudio_py_debugger.py", line 2413, in do_wait
    sys.__stdout__.write('Press any key to continue . . . ')
AttributeError: 'NoneType' object has no attribute 'write'
```

i don't know what the root cause is? How to resolve this issue? The PTVSD version i am using is 3.0.0.

Thanks for the help,
-Neil

**Comment by int19h** [comment]
ptvsd itself also redirects stdout and stderr, so that it can tee the output into VS. That said, I can't quite make sense of that exception around missing arguments for `__init__`.

Can you show how your code looks with `ptvsd.enable_attach` in it?

**Comment by zooba** [comment]
This is likely a version mismatch. For VS 2015 you should use `ptvsd==2.2.0`.

That said, the older version is known to not work well with other overrides. You may want to have a flag to skip your `CatchOutput` code when debugging, or make sure it occurs before `enable_attach` and use a `StringIO` object instead. We should be able to wrap that up properly and forward data to it, but what you showed above won't work properly with other overrides.

**Comment by naeco2005** [comment]
@int19h, the code would look like below:

bool debug(strScript)
{
             redirectStdErr();
             redirectStdout();

             preScript = _DNGI("import ptvsd \nptvsd.enable_attach(\'MySecret\', (\'0.0.0.0\', 8000)) \n");
             response = PythonManager::get()->runScript(preScript, status, false, false);

             preScript = _DNGI("ptvsd.wait_for_attach()\n");
             response = PythonManager::get()->runScript(preScript, moduleName, status, false, false);

             ......
             response = PythonManager::get()->runScript(strScript, moduleName, status, false, false);
}

bool 
PythonManager::runScript(const Ns::IString& strScript, const Ns::HString& moduleName, Ns::Status& status, bool bExecSingleLine)
{
	Acquire_Python_GLI_Wrapper lock;
	PyObject *py_module = PyImport_AddModule(moduleName.c_str());
	if(!py_module)	return false;

	PyObject *py_dict = PyModule_GetDict(py_module);
	
	PyObject* res = nullptr;
	auto arena = PyArena_New();
	if (arena)
	{
		auto mod = PyParser_ASTFromString(Ns::ToHString(strScript).c_str(), Ns::ToHString(scriptFileName).c_str(), bExeSingleLine ? Py_single_input : Py_file_input, nullptr, arena);
		if (mod)
		{
			auto co = PyAST_Compile(mod, Ns::ToHString(scriptFileName).c_str(), nullptr, arena);
			if (co)
			{
				res = PyEval_EvalCode((PyObject*)(co), py_dict, py_dict);
				Py_DECREF(co);
			}
		}
		PyArena_Free(arena);
	}
	if(res)
	{
		Py_DECREF(res);
		return true;
	}
	else
	{
		return false;
	}
	
	return true;
}

**Comment by naeco2005** [comment]
@zooba, I guess it is not due to version mismatch. I also tried to use PythonVSCode which also use PTVSD3.0.0, i still encounter this same exception.   

i redirected stderr and stdout before the debug, can you explain a little bit about 'StringIO' you mentioned above? Is there some documentation or help i can refer?

Thanks for the help,
-Neil

**Comment by zooba** [comment]
Ah, it looks like the problem is that we are accessing `sys.__stdout__` which is not set to anything, as your code has set `sys.stdout` only (I added the ``` quotes to your original post, which makes it far more obvious that there are underscores in the code).

The docs for `StringIO` are at https://docs.python.org/3/library/io.html#io.StringIO They are very brief, as there isn't much to the class. Basically you can just do `sys.stdout = StringIO()` and later `sys.stdout.getvalue()` (for better compatibility, `TextIOWrapper(BytesIO())` will support tools that write directly to the underlying stream, as well as letting you specify encoding/errors parameters).

**Comment by naeco2005** [comment]
Thanks @zooba. I changed the code and fixed some other issues, now it works fine. Thanks for the help. 

-Neil
