### ISSUE TITLE
Inconsistent behavior of IntelliSense class/method dropdown boxes

### ISSUE THREAD

**Issue by HHest** [Microsoft/PTVS#3202]
Normally at the top of a .py file, there would be two drop-down boxes, which show the classes and methods in the file. In VS 2017, these boxes sometimes do not show up. One would have to close the tab and reopen the file to recover the boxes.

It seems like the 1st two tabs would have this problem, but not the subsequent ones.

Example:

1) this .py tab was opened automatically when I opened the solution, because I had left it open when I closed VS 2017 the previous time. Note the drop-down boxes do not appear now.

![capture](https://user-images.githubusercontent.com/3169669/31879362-80ec3e1c-b7dd-11e7-9ad1-204d91d8f5ce.PNG)

2) The boxes reappear after I closed and reopen the file. 

![image](https://user-images.githubusercontent.com/3169669/31879449-bd10ae96-b7dd-11e7-8032-97bb2bbdc015.png)

**Comment by HHest** [comment]
See #3046

**Comment by huguesv** [comment]
Thanks. It's been fixed in https://github.com/Microsoft/PTVS/pull/3132 and should be available soon in 15.5 Preview (if not already).
