### ISSUE TITLE
Feature Request - Multi-Threaded Intellisense DB Refresh

### ISSUE THREAD

**Issue by chaseaucoin** [Microsoft/PTVS#3213]
During DB refresh it appears to be using a single thread to do the parsing. This would be a prime candidate for parallelization. I work with anaconda and create new envs for a variety of tasks. Refreshing the intellisense DB is the longest part of the process. I have 32 threads available, and it seems like a shame not to make use of them.

**Comment by chaseaucoin** [comment]
I'd be happy to do the work if someone could point me in the right direction as to where in the codebase the parsing is done.

**Comment by zooba** [comment]
It's actually considerably more complicated than you may think, as the code is very not thread safe.

However, we have been working on removing the completion DB entirely. You can enable an early preview in Visual Studio 2017 15.4 or 15.5 Preview with the registry key mentioned in [our blog](https://blogs.msdn.microsoft.com/pythonengineering/2017/08/25/python-updates-in-visual-studio-15-4-preview-1/), and the version that will be coming in the first 15.6 Preview is already significantly better.

I think you'll be happy with the new approach. It turns the big DB scan into a lazy operation, and is much faster at getting classes and members (though currently does not get return types at all).

**Comment by chaseaucoin** [comment]
"It's actually considerably more complicated than you may think, as the code is very not thread safe."

Can't threaten me with a good time ;)

As for the rest, that sounds awesome, I'll check that out. Thank you! I'll close this ticket.
