### ISSUE TITLE
IPython does not work properly in VS 2017

### ISSUE THREAD

**Issue by NashKol** [Microsoft/PTVS#3220]
Hi !
I am new to PTVS + IPython and i have tried a few lines of code but it does not seem to work ...
this single code line don't work 
`user_name = input("Name :")`
and instead it generate error below : 
C:\Users\da\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\repl\ipython.py:71: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  from IPython.utils.traitlets import Type
Unhandled exception in thread started by <function VsStdInChannel.handle_input_request.<locals>.read_and_respond at 0x000002B1C800A2F0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\repl\ipython.py", line 249, in read_and_respond
    self.input(value)
AttributeError: 'VsStdInChannel' object has no attribute 'input'
I'm a teacher and I already told my students that I found the best python IDE and now it sucks ...
How can i fix this please ... ?

**Comment by zooba** [comment]
This is the same issue as #2722, but you've escalated it from a nice-to-have to an essential. Thanks for the report!
