### ISSUE TITLE
Need to close/reopen editor window to get IntelliSense on newly installed package

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3222]
This doesn't happen 100% of the time, but I'm seeing it frequently following these exact steps:
1. New project, python application
2. Add virtual environment, base python 2.7
3. Right click env, install package `bottle`
4. In the already opened editor, type:
```
import bottle
bottle.
```

Result: `bottle` doesn't appear in the list of modules, doesn't get colorized as a module, and you don't get completions on it. You can wait as long as you want, but that won't help. Close and reopen the editor window and it will then work as expected.

**Comment by zooba** [comment]
This is because we currently suppress a whole range of unnecessary file watchers in the analyzer process. It's an important step towards being platform independent, but that's not our goal right now, so I'll just reenable it.
