### ISSUE TITLE
Unable to setup a working environment using embeddable CPython

### ISSUE THREAD

**Issue by ahnada** [Microsoft/PTVS#3229]
I'm getting this error in the interactive window using a custom environment with the embeddable zip distribution of CPython 3.6.3:

```
Failed to start interactive process:
System.ComponentModel.Win32Exception (0x80004005): Incorrect function
   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.<ConnectAsync>d__43.MoveNext()

Current interactive window is disconnected.
```

This happens for both x86 and x64 embeddable zips.
I do not have any version of Python installed on my machine and PYTHONPATH is not defined.
Using Visual Studio Community 2017 (v15.4.1) and the latest PTVS (v3.0.17262.1).

Any assistance would be appreciated. Thanks!

**Comment by zooba** [comment]
The embeddable zip is not supported for use from Visual Studio. You should use the full installer for CPython (the "[Python developer kit](http://stevedower.id.au/blog/why-so-many-python-installers/)" as I like to think of it). You do not need administrative privileges to install Python 3.6, though the default settings will try to install the launcher for all users, so you'll have to uncheck that box.

You could also use the [nuget](https://www.nuget.org/packages?q=python) packages if you have a need for zero-impact install.
