### ISSUE TITLE
How can I run python script in the path of the .py file

### ISSUE THREAD

**Issue by ShiShuyang** [Microsoft/PTVS#3236]
If there are two files in a floder: 1.py and 1.txt. In python Idle, I can use:
`f = open('1.txt')`
to direct open file. But in VS2017, it tells me that 1.txt can't be found. Using `os.getcwd()`, VS tells me the path is C:\\Program Files\\Python36. So what can I do if I want to open the file just Idle does?
(I didn't build a project and just used Alt+Shift+F5 to run the 1.py)

**Comment by zooba** [comment]
As a workaround, adding the following code snippet at the top of your file should help:

```python
import os, os.path
os.chdir(os.path.dirname(__file__))
```

Otherwise, this is the same issue as #2451, so I'll close this as a duplicate and we'll continue tracking it there.
