### ISSUE TITLE
Use project.json instead of the xml .pyproj format

### ISSUE THREAD

**Issue by philipmat** [Microsoft/PTVS#326]
The XML format of pyproj is a pain in the butt when it comes to handling merging and conflicts, particularly since Visual Studio seems to move the `Include` nodes randomly around the file.
The new [project.json format](https://github.com/aspnet/Home/wiki/Project.json-file) that ASP vNext uses is considerably more flexible because of its pattern-based include/exclude syntax.

Please consider supporting that format for PTVS projects.

**Comment by zooba** [comment]
We are regularly considering how to make our project system more flexible, though it is a huge undertaking and we won't be doing it for our upcoming release. (Closing this issue as we won't be tracking the planning/work with it.)
