### ISSUE TITLE
Having a script name random.py that imports numpy crashes the debugger

### ISSUE THREAD

**Issue by CorentinJ** [Microsoft/PTVS#3278]
Title says it all, [this](https://i.imgur.com/OmSvO8V.png) is the window that I get (I cannot copy its content)

**Comment by zooba** [comment]
Having a script named anything that exists in the standard library is a great way to break Python. This is not unique to the debugger, and ultimately we can't reliably do anything better than fail.

You'll need to rename your script to something that is not an existing Python module, or anything that tries to use the random module will fail.
