### ISSUE TITLE
Fatal error in launcher: Unable to create process (or Virtualenv and Paths with Spaces)

### ISSUE THREAD

**Issue by arqeco** [Microsoft/PTVS#328]
Hello,

My goal is to use Visual Studio as a tool to blog editing using Pelican, a static site generator written in Python

After installing pelican package inside a virtualenv in Visual Studio 2013 Community, I opened a command line prompt and tried to activate the virtualenv and run a script (pelican-quickstart) that comes with pelican and creates basic configuration files and folders needed by pelican, but got an error:

    > env\Scripts\activate
    > pelican-quickstart
    Fatal error in launcher: Unable to create process using '""c:\users\username\documents\visual studio 2013\Projects\PythonApplication6\PythonApplication6\env\Scripts\python.exe"" "c:\users\username\documents\visual studio 2013\Projects\PythonApplication6\PythonApplication6\env\Scripts\pelican-quickstart.exe" '

After some research I've found that the cause of this is the presence of whitespaces in the path. In this case the problem is the VS default folder name: "visual studio 2013". Creating the project in another folder without spaces in its name worked, but it is a problem I believe it should be looked by PTVS developers.

**Comment by zooba** [comment]
It's actually a problem that needs to be looked at by the pip developers, and they've been notified (see https://github.com/pypa/pip/issues/2783, https://github.com/pypa/pip/issues/1997), and apparently it's already been fixed in distlib.

What this probably means is that you'll need to upgrade pip (`python -m pip install -U pip` is the safest way to do this) and reinstall Pelican to get the fix.

**Comment by arqeco** [comment]
Thank you Zooba

**Comment by newlinuxhelper** [comment]
> It's actually a problem that needs to be looked at by the pip developers, and they've been notified (see [pypa/pip#2783](https://github.com/pypa/pip/issues/2783), [pypa/pip#1997](https://github.com/pypa/pip/issues/1997)), and apparently it's already been fixed in distlib.
> 
> What this probably means is that you'll need to upgrade pip (`python -m pip install -U pip` is the safest way to do this) and reinstall Pelican to get the fix.

Well, I solved this issue of [Unable to create process using in virtualenv](https://webmatrices.com/d/503-unable-to-create-process-using-virtualenv) with this forum answer. You guys can simply check it out.
