### ISSUE TITLE
Generating task list

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#329]
Hi

It would be nice if I could automatically add to Visual Studio's task list from specific comments, like #ToDO Task text || status (default: incomplete) || Priority (default normal).

Thank you

**Comment by int19h** [comment]
This was actually implemented in PTVS 2.2 beta. Note that you may need to switch the Task List source to comments to see them, as described here:

http://blogs.msdn.com/b/zainnab/archive/2013/08/15/visual-studio-2013-todo-comments-and-custom-tokens-in-the-task-list.aspx
