### ISSUE TITLE
Conditional breakpoints break on first hit

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3292]
I am following the tutorial here: https://docs.microsoft.com/en-us/visualstudio/python/vs-tutorial-01-04. At step 14, I set the same conditional breakpoint with "i > 1600", and then I "F5" to start the program. I was expecting the breakpoint to hit "only" when i > 1600, but it got hit when i = 0, then the next time it got hit after i increments to be bigger than 1600. 

(Originally reported internally.)

**Comment by huguesv** [comment]
I'm not seeing this. I'll test some more later.
