### ISSUE TITLE
New Project does not follow Create Directory For Solution option

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3295]
1. New project
2. Select Other Languages > Python > Python Application
3. Make sure that 'Create directory for solution' is checked
4. Click ok

Expected:
A new directory is created and the solution is under the new directory.  This is how most other project templates (C#/VB/etc.) work

Actual:
No new directory is created for the solution 

(Originally reported internally)

**Comment by huguesv** [comment]
This is working fine in EXP. I'll test an installed build when I get back access to my test VMs.

**Comment by huguesv** [comment]
Tested on a regular install and it works fine there too.
