### ISSUE TITLE
Memory leak in the background analyzer

### ISSUE THREAD

**Issue by mrolle45** [Microsoft/PTVS#3298]
As I am editing a rather complex Py module, I am finding that my memory usage keeps increasing.

If I do so much as insert a blank line into the module, one of the "background analyzer" processes adds about 45 MB to its total memory usage, and this happens each time.

I have VS 17 now.

When I had VS 13, the main VS IDE process took the memory hits, and then it was around 300 MB each time, and after making several edits to this module, I'd be up to over 2400 MB and then if I didn't exit from VS, it would eventually stop responding long enough to crash.  So your latest Python Tools is considerably better.  Kudos for that.

But I do want to let you know that something is not getting released from one pass of the analyzer to the next, and I think you'll want to fix that.

Here's the module in question.  It's about 1300 lines and imports two other modules totaling about 2000 lines.  All three modules are attached.  codeview.py is the one that imports the other two.  Only editing condeview.py has the leak.  Editing cvtypes.py or cvsyms.py doesn't add to memory usage.

A possible clue here is that codeview imports the other two, each of which imports classes from codeview, which are base classes for some of their own classes, which are later referenced at the module level by codeview.  See the codeview.Parsers dict which has cvsyms.Parser and cvtypes.Parser among its values.

[binFile.zip](https://github.com/Microsoft/PTVS/files/1448621/binFile.zip)

When editing other modules, in a different project, I lose maybe 3 MB.

**Comment by mrolle45** [comment]
After some changes to the modules in question, the problem has become more severe.  Now what happens is that I load my solution, change a few lines to codeview.py, and wait a few _minutes__ while the background analyzer runs, eating up about 450 MB.  It eventually stops running.
Meanwhile in the IDE, the '...' appears in the left of the status bar and doesn't go away even after the analyzer is done.  Furthermore, the drop-down boxes at the top of the source file window don't appear, and Outlining/Hide All isn't enabled (in _any_ of my source windows).  And sometimes the text color updating doesn't work right.
In this case, it looks like the source analyzer process has perhaps given up, but not reported completion status to something in the IDE that uses the results in order to get the aforementioned UI features to work right.
The analyzer runs far longer and uses up far more memory if I change something, wait a moment until the analyzer starts running, and then change something else while the analyzer is still running.  If I just change something and then wait, the analyzer is better behaved.
Here are new versions of the three files involved.
[binFile.zip](https://github.com/Microsoft/PTVS/files/1455981/binFile.zip)

**Comment by huguesv** [comment]
Thanks for the report. Most of the editor functionality relies on the background analyzer, so it is not surprising that it's misbehaving when the analyzer runs into trouble.

We've had a (difficult to fix) memory leak for some time: https://github.com/Microsoft/PTVS/issues/499

This may or may not be the same issue. We'll take a look. Thanks!

**Comment by zooba** [comment]
Bumping this and #499 to P0. I do think they are the same, and the explanation on #499 should be sufficient (I'm really glad I wrote that - would've hated to figure it all out again).

At worst, we should add a "throw it all out and start again" handler when we detect memory spiking.

**Comment by zooba** [comment]
Based on heap analysis with the attached code, this is definitely the same issue as #499. I'll continue tracking over on that bug.

**Comment by zooba** [comment]
Reopening this because there are multiple leaks with this code. I'll analyse the new ones I'm seeing (appears to be due to nested functions being assigned to dynamically generated classes) and follow it up here.
