### ISSUE TITLE
Source analyzer doesn't restart if it gets killed.

### ISSUE THREAD

**Issue by mrolle45** [Microsoft/PTVS#3299]
It looks like a source analyzer process is spawned for each project in the current solution.  I used the Task Manager to kill one of these analyzers, and as a result, the python editor stopped doing some things it usually does, and I didn't see another source analyzer appearing to replace it.
What the editor doesn't do, that I noticed, was (1) update color codings for class names (it's fine for Python keywords), (2) find syntax errors (in my case, I removed the trailing quote from a string, and no squigglies appeared nor anything in the Error List window.
So I think what you would want to do is monitor those spawned processes for any notification that they died and restore them if so.

The reason I did this experiment was on account of my previous issue post (#3298) regarding the source analyzer process growing in memory usage.  I wanted to see what would happen if it grew to the point of running out of memory, so I just manually killed the process instead.

**Comment by huguesv** [comment]
Analyzer restart done in https://github.com/Microsoft/PTVS/pull/5045
