### ISSUE TITLE
"$visualstudio_py_debugger" no longer seems to be present in sys.modules

### ISSUE THREAD

**Issue by MichaelGoulding** [Microsoft/PTVS#3303]
This code worked previously:

def IsPyDebuggerPresent():
    return ("$visualstudio_py_debugger" in sys.modules)

Some version info:

Microsoft Visual Studio Enterprise 2017 Preview
Version 15.5.0 Preview 2.0
VisualStudio.15.Preview/15.5.0-pre.2.0+27019.1
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Python   3.0.17262.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

**Comment by huguesv** [comment]
The `ptvsd` package has been refactored quite a bit. This is probably the best module to check for in the latest version:
```
"ptvsd.debugger" in sys.modules
```

**Comment by MichaelGoulding** [comment]
Or should we just look at sys.gettrace()?

def IsPyDebuggerPresent():
    return (sys.gettrace() != None)

**Comment by huguesv** [comment]
Yes, that will be more accurate. For example, if your code imports ptvsd to attach to it remotely, the debugger module would be loaded but the code wouldn't be necessarily debugged/attached yet.
