### ISSUE TITLE
Cannot edit python environment.

### ISSUE THREAD

**Issue by KawaiYuji** [Microsoft/PTVS#3304]
I recently updated Visual Studio 2017 from ver 15.4.0 to 15.4.2.
Since the update the python environment setting does not appear anywhere.
Right clicking on Python Environment in the solution explorer shows nothing.
Also when I right click on any python file in the solution explorer, "Set as Startup File" does not appear.
[PackageVersions.txt](https://github.com/Microsoft/PTVS/files/1452799/PackageVersions.txt)
Any help will be appreciated.

**Comment by huguesv** [comment]
@zooba this is a Japanese build of 15.4.2. Do we know already if this has the localization issue with commands?

**Comment by zooba** [comment]
Yes, it does. There is an update released today that will resolve it.

**Comment by KawaiYuji** [comment]
Thank you for the information, huguesv and zooba.
I will wait for the update.

**Comment by KawaiYuji** [comment]
My issue was fixed in the latest update.
Thank you!
