### ISSUE TITLE
No inline graph with jupyter client

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3310]
![image](https://user-images.githubusercontent.com/1696845/32582424-9bd2447e-c4a3-11e7-8f4e-1177ab1c890b.png)

**Comment by zooba** [comment]
@huguesv Feel free to dig into this one if you like. Use the `$debugrepl` command to enable the visible command window so you can `print` stuff, and edit the `jupyter_client.py` file directly in the Exp deployment.

**Comment by huguesv** [comment]
We're not getting the `display_data` message, it comes in via `execution_result` and it's plaintext.
```
content.data: {'text/plain': '[<matplotlib.lines.Line2D at 0x24a4fd58128>]'}
``
