### ISSUE TITLE
How to I search for an existing issue (in just this repository) like the one I have?

### ISSUE THREAD

**Issue by mrolle45** [Microsoft/PTVS#3312]
Maybe this is a stupid question, but I haven't been able to find any way to do a textual search of issues within just this forum.  The search bar at the top of this (Microsoft/PTVS) page lets me search the entire repository, or if I click on Issues, it searches *all* of GitHub for issues.  What I want is to search only this repository and only for Issues.

Can you answer this question, or if there's no answer, could you pass this comment onto the GitHub wizards and request this as an enhancement.

I think you would want to make it possible, and easy, for a contributor to check for past similar issues, in order to avoid responding to redundant issue posts.

Thanks.

**Comment by int19h** [comment]
The textbox at the top is the right way to do it, but the UI there is somewhat confusing: *after* you enter your search terms, and get the results page, there are links below the textbox that let you switch between code / issues / PRs.
