### ISSUE TITLE
Using the VS Project System Extensibility

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/PTVS#333]
I understand there has already been lots of work to produce the PTVS installation, but I was wondering if there are thoughts on moving to the new VS Project System Extensibility?  Any thoughts on pros/cons and how it could improve a project like PTVS?  TIA for any feedback.

http://blogs.msdn.com/b/visualstudio/archive/2015/06/02/introducing-the-project-system-extensibility-sdk-preview.aspx?CommentPosted=true#commentmessage

**Comment by zooba** [comment]
We'll certainly be looking into it into the future, but right now it's not part of our immediate plans. I expect the transition to introduce a lot of new and subtle bugs, so we will want to do it very early in a release to ensure plenty of time using it before calling it stable. Our current project system is serving us pretty well, though there are some architectural factors that may be resolved with CPS, such as very large projects being slow and file-system based projects not being easy to manage. We won't know for sure what benefits are there until we change though, which is still fairly speculative at this stage.

**Comment by zooba** [comment]
(Closing this as we won't use this issue to track the idea or the work.)
