### ISSUE TITLE
Creating a new Python ML project is confusing.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3336]
Currently there is no "sign" that says that a cookiecutter feature will start instead of creating a the project/solution. 
Recommendation 1: Update the text here to say that the cookiecutter feature will start and help guide through the project. 
![image](https://user-images.githubusercontent.com/3840081/32798996-3171519c-c92b-11e7-8abc-fdb4533d166a.png)

Recommendation 2: The cookiecutter start button should say "create" or "create with wizard", something along those lines. Currently it is confusing that my attempt to create a project is now forcing me to run some random template.
![image](https://user-images.githubusercontent.com/3840081/32799111-92d698fc-c92b-11e7-9db3-65f7b11abd11.png)

**Comment by huguesv** [comment]
Yeah, we planned for it but I ended up postponing.
https://github.com/Microsoft/PTVS/issues/2989

We should definitely do 1) at a minimum

**Comment by karthiknadig** [comment]
These names should have Cookiecutter in there somewhere:
![image](https://user-images.githubusercontent.com/3840081/32863672-2172587c-ca11-11e7-88d5-a14f61a000a6.png)

**Comment by zooba** [comment]
`Classifier Project (cookiecutter)`, perhaps?
