### ISSUE TITLE
How do I run Makemigrations on model changes?

### ISSUE THREAD

**Issue by mercycoach** [Microsoft/PTVS#334]
I'm trying to make changes in my model ( and therefore db ) without losing any existing data.  Is there any way to do that in the PTVS interface?

**Comment by zooba** [comment]
Do you mean in Django? (We aren't a purely Django-focused IDE, so it helps to clarify which library/framework you're talking about.)

We don't have anything specific for Django to migrate to a new schema, though there is plenty out there to help. If you can run commands from a Django management shell then there is a command to bring that up if you right-click your project and select Python, and if you look in `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\12.0\Python Tools\Microsoft.PythonTools.Django.targets` you'll see how we implemented those commands so you can add your own (either to that file, to your own `.targets` file that you then `<Import>` in your project, or directly to your `.pyproj` file).

**Comment by krisavi** [comment]
Hello,

I tried to edit that file, I have it included in the .pyproj but it doesn't seem to make those lines to appear for me. For some reason it is not like updating the commands there, I tries to change even syncDB, but when I run it, then it still runs the old syncDB command.

**Comment by zooba** [comment]
Make sure you change the target name, probably the label (you can just specify plain text there if you like) and add the target name to `PythonCommands`. (Sorry, my first answer was a little rushed and I forgot about some of the details...)
