### ISSUE TITLE
Ctrl+Shift+Space does not bring up signature help

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#3343]
Stock 15.5 P4

`Ctrl+J` works, `Ctrl+K, Ctrl+I` works too. `Ctrl+Shift+Space` is listed in the `Edit | Intellisense` menu and command _does_ work when selected from the menu. But actually pressing `Ctrl+Shift+Space` seems to have no effect.

**Comment by zooba** [comment]
I don't want to hold up the 15.5 release to fix this. We should check whether it occurs in master.

**Comment by huguesv** [comment]
It also does not work in master.

**Comment by zooba** [comment]
Actually, this isn't working properly in C# for me... do we know if it's 100% consistent? Perhaps the editor team has broken something?

**Comment by huguesv** [comment]
Same here for C#, 15.5.0 Preview 4.0

**Comment by MikhailArkhipov** [comment]
Yeah, C# broken too, so not our issue.
