### ISSUE TITLE
Allow multiple package managers per environment

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3350]
UI work for environments window to display more than one package manager should be pretty minimal, we can just instantiate multiple copies of the same UI and pass it a different package manager.

IPythonInterpreterFactory needs to have an array of IPackageManager instead of a single one (or in addition to the existing property).

Install Package command in solution explorer can bring up the UI for the first package manager.

**Comment by zooba** [comment]
When I was designing the package manager API, I thought the best design would be for IPythonInterpreterFactory to have one _default_ package manager, but allow the UI to use an alternative one.

That should still be possible. Package managers are given the factory instance, and then shouldn't care about what the factory thinks its package manager is.

The `InterpreterListToolWindow.List_ViewCreated` method can add as many extension providers as it likes.

**Comment by huguesv** [comment]
Environment window will have additional package manager in the drop down so the user can pick which one to use there.

Here are features/commands that target the default package manager:
a. Install from Requirements command
b. New project task dialog that appears when requirements.txt is detected (when you pick install into my global env)
c. Generate Requirements command
d. Solution explorer package list
e. Remove package command from solution explorer
f. Install package command from solution explorer just brings up the default package mgr in environment window, user can easily switch to another one

Some of these work more or less with conda as the default package manager:

There's no `bottle` conda package, and you can easily run into that error with b).

When generating requirements for conda env, you'll end up with the conda package list, which will likely fail if someone tries to install that using pip (and vice-versa).

**Comment by huguesv** [comment]
All operations dealing with requirements.txt have been changed to always use pip, so I feel this is all done.
