### ISSUE TITLE
Allow creating new conda environments

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3352]
Need to think about where to put this in order to **not** make it project centric like our virtual environment creation UI.

My initial idea was to add a special item to the environments window (below the detected environments, before or after the item to add custom environment). The bottom part of environment window would have the input parameters and a create button.

![image](https://user-images.githubusercontent.com/1696845/32868402-f4c9bd18-ca26-11e7-9c9a-7dc699de9bed.png)

(parameter list in the above mock is not meant to be exhaustive -- for example, we probably want to let them specify the path if they want to).

We could change the existing Add virtual env dialog into something similar.

# Entry points

Here are various places / reasons where conda environment operations are desirable.

- Create new project from new project template which includes a conda environment file or conda explicit specification file (probably rare for a template since that one is not cross platform).
- Create new project or folder from cookiecutter template where the cookiecutter template has a post-creation step that invokes conda creation. Similar to how a cookiecutter template can invoke the install from requirements.txt command right now. Command handler will need to behave in the case where there is no conda available on the machine.
- User has an existing project open that has a conda environment file / conda explicit specification file. User decides to create an environment from either of them. We probably don't want to rely on naming convention but allow this on any .yaml, .yml or .txt file.
- User has no project open, but they decide to create a conda environment to be used by future project(s).
- User no longer works on some projects, and wants to delete an unused conda environment.
- User wants to investigate upgrading to a newer version of django/flask/etc. User clones their existing environment and then upgrades some packages in the new environment.
- more...

# User interface notes

Right now it's possible that the user has no conda installed, making it impossible to create new environments. Leave the entry points there but let the user know they need conda to proceed (hide the form fields and put the message instead).

# Environment low level operations

Environment management operations that we can consider supporting are documented at https://conda.io/docs/user-guide/tasks/manage-environments.html

## Create a new environment

Specify a name/location
Specify a Python version

`conda create -n <name> python=3.6`
`conda create -p <location> python=3.6`

## Import an environment

Specify an environment definition file, from any of the following types.

### Import from a Conda environment file (*.yml, *.yaml)

Conda environment file lists package names and versions, for both pip and conda packages, and is platform independent.

`conda env create -f environment.yml`
`conda env create -f environment.yml -n <name>`

- name is specified in yaml, so it would be optional user input
- default location (created in %localappdata%\conda\conda\envs\<name>)

`conda env create -f environment.yaml -p <location>`

- name specified in yaml is ignored
- location specified by user

### Import from a Conda explicit specification file (*.txt) - TO VERIFY

Conda explicit specification file is used to build identical conda environment on the same operating system platform, contains platform specific urls to packages.

`conda create -f spec-file.txt -n <name>`
`conda create -f spec-file.txt -p <location>`

### Import from a Pip requirement file (*.txt)

If there is no Python version specified in the file (python==3.5), which there typically isn't, then it will pick one for you.
This operation will fail if the packages listed don't exist in conda repo (it doesn't fall back to pypi)

`conda env create -f requirements.txt -n <name>`
`conda env create -f requirements.txt -p <location>`

### Export to a Conda environment file (*.yml, *.yaml)

`conda env export -p <location> > environment.yml`

### Export to a Conda explicit specification file (*.txt)

`conda env list --explicit -p <location> > spec-file.txt`

## Clone an environment

Specify an existing environment to create a clone on the same machine.
This can be achieved via export/import, so lower priority if we implement export/import.

`conda create -p <location> --clone <source_env_location>`

## Delete an environment

`conda remove -n <name> --all`
`conda remove -p <location> --all`

# To be resolved:

## Architecture

Architecture cannot be specified*, it is based on the architecture of the running conda.
If user has more than one conda installed, we currently pick the first one we find.
We could probably let the user pick the architecture from a combo box where we put in the ones available, and use a conda of the selected architecture to create the environment.

* Conda explicit specification file have a platform field in them, so running conda platform should be ignored when importing from such specification file.

**Comment by zooba** [comment]
I like this mockup, though I think we'll want to make this explicitly a "Shared" conda environment and also have a per-project model.

(We might want to talk to the PM team about branding as well - it might make more sense to call it an "Anaconda environment"...)

**Comment by huguesv** [comment]
Should also have an input field to create from an environment.yml
https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by zooba** [comment]
We might be more interested in exposing that on the file itself... really ought to spend some time working through some ideas here with actual users.

**Comment by huguesv** [comment]
Some of it is available in 15.6, to be continued in future release

**Comment by huguesv** [comment]
Now tracking this in https://github.com/Microsoft/PTVS/issues/4730 as part of a larger UI update for adding environments.
