### ISSUE TITLE
Question on API: is it possible to obtain return type of a function overload?

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/PTVS#3358]
I obtain an instance of OverloadResult from analysis. However, it does not appear to have any references to the analyzed return type. Is there any other place I could get it from?

**Comment by zooba** [comment]
The best way to get return types is to call `GetValues(function + '()', location_of_call)`.

If you know the argument types, you can also specify those (they just have to resolve statically, so `func(int(), str())` is totally fine). Right now, it won't matter and you'll get the union of all possible return types (like we show in tooltips), but in future versions we'll likely get more precise here.

**Comment by lostmsu** [comment]
@zooba , thanks, that worked well
