### ISSUE TITLE
I  have some serious problems , when creating django super user.

### ISSUE THREAD

**Issue by izoohwizard** [Microsoft/PTVS#3367]
The follow  message pops out when i try to create a Django super user;
Executing manage.py createsuperuser
Traceback (most recent call last):
  File "C:\Users\IZOOHWIZARD\source\repos\DjangoWebProject1\DjangoWebProject1\manage.py", line 15, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
The interactive Python process has exited.
The interactive Python process has exited.
>>>

**Comment by zooba** [comment]
This may seem obvious, but have you installed Django? You should have seen a pop-up when creating the project that offered to install it for you.

If you have, please open your project and then save the information from Tools, Python, Diagnostic Info and post it here or email it to ptvshelp@microsoft.com. We might be able to see from that what has happened.
