### ISSUE TITLE
Pipenv support

### ISSUE THREAD

**Issue by BenjaVR** [microsoft/PTVS#3388]
[Pipenv](https://docs.pipenv.org/) is much more convenient when managing dependencies . Would it be possible to detect `Pipfile` in the project, and use/initialize a virtual env based on that? As well as installing (and saving) packages using that `Pipfile`)?

EDIT: Here is a reference to the official repo/docs: https://github.com/pypa/pipfile

**Comment by huguesv** [comment]
Thanks for the suggestion!

**Comment by zooba** [comment]
+1 from me

**Comment by BenjaVR** [comment]
As a follow up, I found a (work in progress) library from the maker of pipenv which could possibly help: https://github.com/kennethreitz/pipenvlib

**Comment by BMBurstein** [comment]
pipenv is now the officially recommended tool to use

**Comment by ewilazarus** [comment]
I'd love to see it too.
