### ISSUE TITLE
my tutorial is broken now

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#3390]
I just tried running PTVS with pythonnet 3.5, Python 2.7 in Azure DSVM Windows Server 2016 and the remote debugging (ptvsd) is not working. I upgraded both VS 2017 and ptvsd to latest.

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython

![image](https://user-images.githubusercontent.com/7870949/33251829-64d3b506-d2ff-11e7-8a0c-fecd19238a61.png)

I will see if this reproduces on my local machine.

**Comment by denfromufa** [comment]
The PTVS guide does not mention which ptvsd to use with VS 2017 15.4

**Comment by denfromufa** [comment]
https://docs.microsoft.com/en-us/visualstudio/python/debugging-cross-platform-remote

**Comment by int19h** [comment]
Can you check whether the endpoint (port) is open on the VM?

**Comment by denfromufa** [comment]
@int19h how do I check this? and if not, how do i find/enable open ports?

**Comment by int19h** [comment]
It's been a while since I last had to do this, and it keeps moving around. @karthiknadig, do you remember where this setting is in Azure Portal these days?

**Comment by denfromufa** [comment]
@int19h i just confirmed that all 3 debugging scenarios are working on local installation so must be ports. Also in the DSVM the second scenario with `sys.gettrace()` is not working.

**Comment by huguesv** [comment]
Regarding opening endpoints, it depends on the type of vm. Here's both docs.
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nsg-quickstart-portal
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/classic/setup-endpoints

**Comment by denfromufa** [comment]
@huguesv I'm using Data Science VM Windows Server 2016

**Comment by denfromufa** [comment]
this time the error is different, i enabled the firewall exception for python.exe like discussed today with @zooba :

![image](https://user-images.githubusercontent.com/7870949/33397518-70a7b760-d511-11e7-9779-d53182e5754c.png)

**Comment by huguesv** [comment]
I got it to work. It required 2 changes after creating the DS VM.

In the portal, I added a new incoming rule to the network security group (which gets automatically created at the same time as DS VM):
![image](https://user-images.githubusercontent.com/1696845/33744172-e60f05b8-db64-11e7-9dd7-f9e509a20bb1.png)

Then in the VM, I added a new incoming rule to windows firewall (port, tcp, 5678, allow connection, domain+private+public):
![image](https://user-images.githubusercontent.com/1696845/33744217-15f5a232-db65-11e7-9196-6a134249331a.png)
