### ISSUE TITLE
XAML designer doesn't work in VS 2015 RC

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#34]
VS 2015 22823.1 D14REL Enterprise (xlab image)
PTVS 30423.00

Create IronPython WPF app
Double click on .xaml file to open in editor

I get the split view of designer/xaml code but the designer part at the top has a progress bar that never ends.

I don't know if it's that same design host dll issue we've had in the past.

**Comment by zooba** [comment]
I don't see any debug messages or exceptions, and the design host DLL is loaded. This will probably take a bit more investigation, but it's a serious enough regression that we ought to look into it.

**Comment by zooba** [comment]
That commit has fixed us, and there seems to be a module load race condition that will be fixed on the VS side.
