### ISSUE TITLE
Refactor Python debug options parsing

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/PTVS#3401]
See ParseOptions in [AD7Engine.cs](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Debugger/Debugger/DebugEngine/AD7Engine.cs) for more info.

**Comment by zooba** [comment]
Worth going one step further and just switching all the options to JSON. We're going to have to have the functionality around anyway, so let's just use it and get out of the manual parsing business.

**Comment by karthiknadig** [comment]
Unassigned, after investigating. I won't be able to finish this before heading off to vacation. This is open for anyone else to pickup meanwhile.
