### ISSUE TITLE
Django 2.0 template issues

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3418]
WIP list of the things that don't work when using Django 2.0 rc1

Starter sample:

error when logging in: 'WSGIRequest' object has no attribute 'session'

Polls sample:

`on_delete` parameter is now required for ForeignKey (param was present but optional since 1.9)
ModuleNotFound for: `from django.core.urlresolvers import reverse`

**Comment by huguesv** [comment]
Just to clarify, our templates have requirements.txt that specify django<2 where these are not an issue. This is about what needs to be done to upgrade our templates to django 2.

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/233822/creating-a-django-project-in-vs-uses-old-django-ve.html

**Comment by huguesv** [comment]
Now that we install Python 3.7 with dev16, we need to update the template to use django>2 ie a version of django that is supported on 3.7.

**Comment by meatballcoder** [comment]
How do we install this into the latest Visual Studio (2017, 15.8.5)?  I did the normal VS installer method and picked the Python tools, workload, etc.  I have 3.7 64Bit installed.  It always installs 1.11 Django, however.

**Comment by huguesv** [comment]
@meatballcoder it's still an open issue, we haven't fixed the template yet.

**Comment by meatballcoder** [comment]
For what it is worth, I was able to get it working by changing requirements.txt to,

`django >=2`

settings.py to, 

```
INSTALLED_APPS = [
    'app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

views.py to,

```

def login(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/login.html',
        {
            'title':'Login',
        }
    )
```
urls.py to,

```
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

url(r'^login$',  
        LoginView.as_view(
            template_name='app/Login.html',
            extra_context={         
              'title': 'Login',
			  'year': datetime.now().year,
              'site_title': 'My Site',
              'site_header': 'My Site Login'
              }), name='login'),
    url(r'^logout$',  
        LogoutView.as_view(
            template_name='app/logout.html',
            extra_context={         
              'next_page': '/',
              }), name='logout'),
```
I was able to use migrations, create a super user, load the webpage and login.

logout.html is not present, so I added that to app/ and created a logout def in views.py

```
from django.contrib.auth.views import LogoutView

def logout(request):
    """Renders the logout page."""
    assert isinstance(request, HttpRequest)
    logout(request)
    return render(
        request,
        'app/logout.html',
        {
            'title':'Logout',
        }
    )
```

From various posting I found online Django documentation, StackOverflow, etc.  I also created a separate 2.x outside of VS and copied and pasted where appropriate, namely the settings.py part above.

**Comment by huguesv** [comment]
@meatballcoder thanks for all the details!

I would probably want to keep passing in `authentication_form` for LoginView. According to  https://docs.djangoproject.com/en/2.1/topics/auth/default/#django.contrib.auth.views.LoginView it looks like that is still supported. Without it, I think the text boxes didn't have proper styling.

For LogoutView, is it not possible to pass `template_name=None` if you just want to go the next page on logout (where the next page is `'/'`).

I'm not sure what the logout function in view.py is for, it doesn't look like that is used? It also looks like it is calling itself infinitely.

GitHub is now reporting security vulnerabilities so I'm now getting a big warning about django<2 dependencies when I go to the main repo page. I think it's just displayed for the owners. So I'm more motivated to get this fixed ASAP.

I'm sorry I just noticed your question regarding a PR.

There are 4 django project templates that need to be updated. They're in the `Python\Templates\Django\ProjectTemplates\Python\Web` folder.

If you're still interested, let me know before you start doing the work. I was thinking of starting on this in the next day or two, but if I can get help, I'll take it.

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/365295/loading-django-pyodbc-azure-breaks-authentication.html
