### ISSUE TITLE
Analysis can't keep up, doesn't see new variables

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3421]
I was typing the code found at https://www.w3resource.com/python-exercises/math/python-math-exercise-14.php

On 3 separate occasions, I was referencing a variable defined on a previous line and it was missing from completions. ESC + CTRL+SPACE to bring up completions again, and then it's there. I'm typing rather slowly too.

In this screenshot, I was expecting `amicables` in the completion list.
![image](https://user-images.githubusercontent.com/1696845/33454733-98889f84-d5ce-11e7-9e71-b627a759d899.png)

**Comment by huguesv** [comment]
Another example where I expected to see `prev_list` in the completions
![image](https://user-images.githubusercontent.com/1696845/33455689-ab334410-d5d1-11e7-978f-8dcba63ccd05.png)

**Comment by zooba** [comment]
Yeah, I've been hitting this today as well. I'll take a look.
