### ISSUE TITLE
Virtual environment still refreshes DB

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3426]
Even with the experimental option enabled, the DB is still being refreshed. (This was in a Django project, but that shouldn't make any difference.)

**Comment by huguesv** [comment]
I'm not sure what to look for. The DB directory under the virtual env? An extra analyzer process? DB UI in environment window?

(I'm not seeing any of those for a virtual env in django project)

**Comment by zooba** [comment]
I was seeing an analyzer process and the UI in the environment window. Perhaps we've already fixed it and I was testing against the slightly older release we shipped today? I thought I fixed it much earlier than that...

**Comment by zooba** [comment]
I can't see any way this could have happened with the current code, so I'll close it and we can reopen if anyone spots it again.
