### ISSUE TITLE
using the python of anaconda ,the breakpoints are not working with VS2017

### ISSUE THREAD

**Issue by wzy306313994** [Microsoft/PTVS#3428]
when i use vs2017 to develop python ,after i add breakpoints on my code ,F5 start debug,all the code  excute to the end of code not triggering any breakpoint,but when i use the same code to debug with the python which the vs2017 Comes with,breakpoints are hitted normally,how can i fix the problem?

**Comment by wzy306313994** [comment]
after i tested,VS2017 cannot debug with python version of 2.7,but can normally debug with python 3.5 or upper.VS2017 donot support the python of version 2.7?

**Comment by huguesv** [comment]
We support debugging of Python 2.6 and later.
Can you provide details on the build of Python that isn't debugging properly?
