### ISSUE TITLE
Update to 15.5 killed PTVS

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#3439]
I was using PTVS in my 15.4 installation yesterday.  After updating to 15.5, Python is not a recognized project type anymore.  I tried opening an existing solution, and I get this:

![image](https://user-images.githubusercontent.com/11823433/33642840-aae31008-d9f0-11e7-8be6-8148612143b5.png)

If I try to create a new project, I get this:

![image](https://user-images.githubusercontent.com/11823433/33642852-bbb5b12e-d9f0-11e7-832f-794252c03b5f.png)

If I run the installer and click Modify to re-install the Python workload, it says it's already installed.

![image](https://user-images.githubusercontent.com/11823433/33642878-d9a74f76-d9f0-11e7-9093-270d4088f5c2.png)

In the first screenshot, I tried right clicking the Project Node and hitting Reload, which prompted me to install the Python workload.  I went through those steps, and it did not report any errors, but at the end, nothing has changed and I still cannot use PTVS.

**Comment by zjturner** [comment]
In case you're remembering our previous discussions on other issues, I want to say pre-emptively that I did *not* muck with the installed files of my real Visual Studio installation.  I did try to build PTVS from source one time, but as there is no installer, and I couldn't figure out what files to copy, I didn't do anything (and even if I had done something, it would have been against my preview install).  So, AFAICT, this is a clean installation.

Hopefully I'm telling the truth here and not mis-remembering something.  I have this error in my Visual Studio Upgrade Log:

```
Package 'Microsoft.DiagnosticsHub.Collection.Service,version=15.0.27128.1,chip=x64' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.DiagnosticsHub.Collection.Service;PackageAction=Install;ReturnCode=1939
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.DiagnosticsHub.Collection.Service,version=15.0.27128.1,chip=x64\Microsoft.DiagnosticsHub.Collection.Service.Msi.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  VSEXTUI="1"  VSFOLDER="C:\Program Files (x86)\Microsoft Visual Studio\Shared" 
        Return code: 1603
        Return code details: Fatal error during installation.
        Message Id: 1939
        Message Details: Service 'Visual Studio Standard Collector Service 150' (VSStandardCollectorService150) could not be configured.  This could be a problem with the package or your permissions. Verify that you have sufficient privileges to configure system services.
    Log
        C:\Users\zturn\AppData\Local\Temp\dd_setup_20171205191139_001_Microsoft.DiagnosticsHub.Collection.Service.log
    Impacted workloads
        Desktop development with C++ (Microsoft.VisualStudio.Workload.NativeDesktop,version=15.0.27102.0)
        Python development (Microsoft.VisualStudio.Workload.Python,version=15.0.27019.1)
    Impacted components
        .NET profiling tools (Microsoft.VisualStudio.Component.DiagnosticTools,version=15.0.27005.2)
        C++ profiling tools (Microsoft.VisualStudio.Component.VC.DiagnosticTools,version=15.0.26823.1)
        Graphics debugger and GPU profiler for DirectX (Microsoft.VisualStudio.Component.Graphics.Tools,version=15.0.26823.1)
        Python language support (Microsoft.Component.PythonTools,version=15.0.26823.1)
        Python web support (Microsoft.Component.PythonTools.Web,version=15.0.27005.2)
```

so this could be a larger problem.

**Comment by zjturner** [comment]
I have the file referenced `dd_setup_20171205191139_001_Microsoft.DiagnosticsHub.Collection.Service.log` but given that it might contain PII, I'd rather email it privately if possible.  LMK if that would be helpful.

**Comment by zooba** [comment]
Given the install failure, you’re going to be best to report this via the Report A Problem tool in the installer. I *think* that will include all the logs automatically, but if you want to be sure you can run https://aka.ms/vscollect and attach %temp%/vslogs.zip to the report. These attachments are tightly controlled, but the description you add will be public.

As for the Python project, this error is normally the magic handling for when a .targets file is missing. There may be more info written to the Output window on the second or third attempt to load it. The easiest way to check whether the rest of our Python support was installed is to check in Tools/Options for our category and whether it loads.

The failed package should only impact profiling, but it may abort the entire branch of dependant packages and so you could be missing a lot of pieces right now.

Thanks for helping out! We appreciate it
