### ISSUE TITLE
Flask: Process dies while debugging after 1.5 minutes.

### ISSUE THREAD

**Issue by jbhalodia** [Microsoft/PTVS#3446]
I am trying to debug the flask app that's being run in IIS. When debugging a response being sent from the server, IIS kills the process after 1.5 minutes. I have changed Application Pool and site settings in IIS like Time-out and Ping settings. These settings increase the timeout and time it takes for the process to die when not debugging. However, while debugging, it kills the process within 1.5 minutes and returns 500 error to the client. Are there any settings any where in flask or wfastcgi.py that will allow us to increase the timeout while debugging?

**Comment by huguesv** [comment]
This may be worth trying: https://social.msdn.microsoft.com/Forums/en-US/ef324552-8dbc-4188-a476-52b9332fb5f4/pythonweb-apps-python-fastcgi-activity-timeout?forum=opensourcedevwithazure
