### ISSUE TITLE
Duplication in help strings when documentation string is present

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3453]
See 2nd and 3rd tooltips
![image](https://user-images.githubusercontent.com/1696845/33788513-9ca5e360-dc27-11e7-81a1-01ac824f2abd.png)

**Comment by huguesv** [comment]
I tried this again with the exact same code, still getting duplicates.

**Comment by MikhailArkhipov** [comment]
Yes, I fixed it
