### ISSUE TITLE
Parameter info doesn't include types

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3456]
When calling a method and typing in the values for parameters, IntelliSense shows you a tooltip with the current parameter name in bold, but the type doesn't appear anywhere.

I would expect to see the type for 'a':
![image](https://user-images.githubusercontent.com/1696845/33790693-38de7f62-dc37-11e7-8360-632a9ec37c6c.png)

The only place that seem to be showing the type is in the method completion list. You end up having to memorize the types when you select the method, or you put the cursor back on the method name and hit CTRL+J.

![image](https://user-images.githubusercontent.com/1696845/33790705-520b6bda-dc37-11e7-882e-309f2daafd14.png)

**Comment by zooba** [comment]
FWIW, this is only on bound methods. Unbound functions work fine.
