### ISSUE TITLE
Connection DB won't refresh

### ISSUE THREAD

**Issue by DanielJSlick** [Microsoft/PTVS#346]
I've installed Anaconda 3.4 and, when I launch VS, I see a message in the "Python Environments" window that indicates that "Connection DB needs refresh". Clicking the "Refresh DB" button causes the DB to refresh but the message appears again after the refresh is complete.

I hope this makes sense and I appreciate any and all assistance to correct this issue.

**Comment by zooba** [comment]
Depending on which version of PTVS you're using, you may be hitting a bug. I'd suggest trying with either 2.2 RC (or the latest release on github, if you're brave).

If that doesn't help (or if you can't upgrade), can you paste the output from Tools, Python Tools, Diagnostic Info into a gist and link it from here?

**Comment by akry1** [comment]
I have the same issue after installing 2.2 RC. I have copied the last section of diagnostic info in the below gist:

https://gist.github.com/akry1/9e5b55929ad6450f9536

**Comment by zooba** [comment]
Ah, looks like I didn't actually fix that until after RC :( Sorry

The good news is that we'll have another update out *very* soon, so hang on for just a bit and we'll get you a fixed one :)
