### ISSUE TITLE
Python Debug Error after latest Visual Studio update

### ISSUE THREAD

**Issue by goo3r** [Microsoft/PTVS#3494]
After updating Visual Studio to 15.5.2 I'm getting this error every time I try to start debugging a Python Project. I've tried uninstalling and reinstalling the Python tools and it still happens. Any help here would be appreciated. 

> Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 29, in <module>
    import ctypes
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by goo3r** [comment]
I think I got this. My virtual environment got corrupted in the upgrade, which is a bummer, but deleting the one I had and making a new one fixed it.

**Comment by kuangzhang** [comment]
hi goo3r..  could you share the step to do this.  I try to uninstall and vs2017 python and reinstalled and still the same result.

**Comment by goo3r** [comment]
Sure!
 In solution explorer, expand Python Environments in your solution. Right click on your environment (mine was called env1) then remove it. Right click on Python Environments again and add virtual environment. Then reinstall any packages you might be using. That fixed it for me.

**Comment by zooba** [comment]
We really should consider attempting #3284, since a few people have been surprised by this (FWIW, you need to recreate virtual environments every time you upgrade Python anyway, but it's more obvious when it gets installed to a different location).

**Comment by kuangzhang** [comment]
I did not create an virtual environment, so it everything went south.  My
fix:
1) remove python from VS2017
2) remove everything that VS did not remove
3) reinstall VS 2017 Python

*Kuang Zhang*
*KuangZhang@gmail.com <KuangZhang@gmail.com>*
*412.600.3663*
