### ISSUE TITLE
Custom Python Environment (WinPython) works in Interactive window but not on the main code editor

### ISSUE THREAD

**Issue by precogtyrant** [Microsoft/PTVS#3506]
Hello,
I am trying to use visual studio for python development. I have added a custom environment (WinPython) and it works fine in the interactive, but on the main code editor, intellisense is not working. It just says `<No Completions> Open Python Environments for more details`

When I run the code, it works but the intellisense isn't working. 

How can I fix this issue? I am running Visual Studio 2017, (WinPython - Python version 3.6, 64bit)

Also the intellisense works on visual studio code with winpython but its really slow. The intellisense in the interactive on visual studio seems pretty fast and it would be great to have it working on the main code editor as well.
![a](https://user-images.githubusercontent.com/2197960/34198123-543538e2-e591-11e7-9511-322c080d34ae.jpg)

**Comment by precogtyrant** [comment]
Here's the diagnostics log: https://pastebin.com/REn81JSg

**Comment by zooba** [comment]
It appears you have something configured in your environment (or in WinPython itself) that is breaking the "-S" parameter. We use that to collect the standard library paths, and our script for doing that fails if the option does not work.

We'll need to look into the specific version of WinPython you've installed to figure out what they've done, or which package is causing this, and then get it fixed there. We can probably also remove the need for this parameter in our next release as the new Intellisense engine doesn't need to know the difference between standard library and installed packages.

If you want to work around this immediately, find `get_search_paths.py` in the Visual Studio install directory and remove the two lines near the start that raise `RuntimeError`. Some completions may be a little wonky, and it will likely take a long time to generate the completion DB, but you should get past the error.

**Comment by precogtyrant** [comment]
Hello,
Thanks for your message. 
This is the version I have https://sourceforge.net/projects/winpython/files/WinPython_3.6/3.6.3.0/ (WinPython-64bit-3.6.3.0Qt5.exe)

I was not able to locate the file named get_search_paths.py in the installation directory(not from the windows search box), do you know the location of that file?

BTW, the intellisense works in the interactive just fine, it just doesn't work on the editor though. 

Also, intellisense works for the built in methods even inside the editor(eg, when I do string. (string dot) , it shows all the available methods) but it doesn't work for numpy or other packages.

**Comment by zooba** [comment]
That file should be under `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core`, though you'll need to change the `2017` and/or `Community` parts if those are not the one you have installed.

**Comment by precogtyrant** [comment]
I removed the following lines but its still the same :(
`if 'site' in sys.modules:
    raise RuntimeError('script must be run with -S')`

**Comment by zooba** [comment]
You'll need to refresh the completion DB, probably manually. Check the Python Environments window and hit Refresh.

**Comment by precogtyrant** [comment]
Yes did that as well but the progress bar goes from left to right only once and the message "Completion DB is not upto date. Click to start refreshing" still shows upon hovering the refresh icon there.

**Comment by zooba** [comment]
It looks like you have WinPython 3.6.0, rather than 3.6.3. I had some contact with one of the contributors about the `python._pth` file, which was included in some releases and has since been removed.

Can you look in your WinPython install directory and see if there's a `python._pth` file? If so, try renaming it. That should enable us to find the modules we need.

**Comment by precogtyrant** [comment]
You da man! Thanks a ton!
Its working now but I think the intellisense is a bit broken at some places, for eg, for numpy, the method arange doesn't show up in the intellisense but the others show up. Not sure why that is happening though, but its not a deal breaker.

Thanks again!!

**Comment by zooba** [comment]
Closing this as resolved.

We've made significant changes here for the next version (which you can check out in [15.6 Preview](https://visualstudio.com/vs/preview)) that should improve results.
