### ISSUE TITLE
My Python files got corrupted after 15.5 upgrade

### ISSUE THREAD

**Issue by kuangzhang** [Microsoft/PTVS#3529]
Just updated VS2017 ... Open my project and this error occurs.

Also tried to create Flask project and have same message in Virtualenv

Please advice what is the fix

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 29, in <module>
    import ctypes
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\ctypes\__init__.py", line 14, in <module>
    from struct import calcsize as _calcsize
ImportError: cannot import name 'calcsize'

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .

**Comment by kuangzhang** [comment]
Any Info on how to fix?

**Comment by zooba** [comment]
If you open "Apps and Features" (or perhaps "Programs and Features" depending on your Windows version) you'll find an entry for Python 3.6 (64-bit). From there, you can select Modify (or if your only option is "Uninstall", select that and you'll get to the same place) and then Repair.

**Comment by kuangzhang** [comment]
Hi,

the Python on my computer was installed with visual studio 2017 so there
are no uninstall via program features.  I have tried to uninstall and
reinstall python via visual studio 2017 which did not work.

Now I will try to remove all python folders on my computer and reinstall.
Will keep you posted.


*Kuang Zhang*
*KuangZhang@gmail.com <KuangZhang@gmail.com>*
*412.600.3663*

**Comment by zooba** [comment]
Python will show up independently of VS in the list of programs, and can be managed on its own. If it doesn't show up, we have a new bug, since it is supposed to.
