### ISSUE TITLE
Mixed mode debugging wierdness.

### ISSUE THREAD

**Issue by WildCard65** [Microsoft/PTVS#3531]
When attaching a debugger to a python_d.exe (see #3517 for build and execution command line), set to mixed mode debugging (Native and Python), the debugger refuses to step into the C code (even though symbols are available AND loaded according to the output window), using information from #2657 and xoring between 2 right click options allows me to step into the C code, but only allows me to step through the currently executing function at the moment a break point was triggered, otherwise I step through the code to processing a frame, keeping the 2 options active together forces me to only be able to debug the DLL injected by the debugger (A PTVS DLL).

The options are: Show Native Frames (Allows me to step into C code) and I believe the other is called Show Python Frames.

**Comment by int19h** [comment]
Are you trying to debug Python itself? i.e. is the native code in question inside python*.dll?

If so, then you will need "Show Native Python Frames" to be able to step into them at all. And then you'll also need to uncheck "Use Python Stepping" whenever you want to step through CPython code. The problem, basically, is that whenever the current instruction pointer is in python.dll, the stepper assumes that when you step in/out/over, you want Python stepping semantics (i.e. continue execution until the next line of Python code is executed). Unchecking that option disables the Python stepper, and then step in/out/over is delegated to the Native debugger, which will treat CPython code same as any other C program.

**Comment by WildCard65** [comment]
Ah, it's not the "Show Native Python Frames", but the one you said, I
forgot what it was and guessed the name, either way, the wierdness existed,
and yes I was trying to step through CPython itself, but the debugger was
having an existential crisis (either it will only do what I already
mentioned or "Step Into" behaves like "Continue"
