### ISSUE TITLE
VS code debugger installation

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3536]
To be determined - amounts to F5 should 'just work'.

**Comment by karthiknadig** [comment]
We could add a command to this menu, to install the experimental debugger:
![image](https://user-images.githubusercontent.com/3840081/34743771-d4bf9e36-f53f-11e7-8b6f-8cdf55b46bd7.png)

**Comment by int19h** [comment]
We don't need to install it as a package - we can just ship it with VS, and add it to the search path, same as we do with `ptvsd` today (but reorder the search path so that it preferentially loads the system-wide package if one is there).

**Comment by huguesv** [comment]
Can we do that even though we now rely on native modules for certain Python versions?

**Comment by zooba** [comment]
We can prebuild and ship the native modules. For 3.5 and upwards they are named differently from each other, so we can just drop them all in a single copy of the library. For 2.7 we probably need to add a version-specific search path for it, or we just default to the slower debugger unless you install our wheels (which we could also include easily enough).
