### ISSUE TITLE
VS Code debugger error message when closing the console

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3537]
Start debugging a small script that prints to the console, no need for breakpoints
Console stays up at the end leaving only option to close the window
When you do that you get:
```
---------------------------
Microsoft Visual Studio
---------------------------
The debug adapter exited unexpectedly.
---------------------------
OK   
---------------------------
```

or sometimes:
```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.



An existing connection was forcibly closed by the remote host
---------------------------
OK   
---------------------------


```

**Comment by int19h** [comment]
I believe this is because we forcibly close the socket as soon as process exits, even if it still had some unread data on the wire. There should probably be a timeout there to allow the process to close the socket from its end in normal scenarios.

**Comment by karthiknadig** [comment]
This is not fixed until VSC Debugger takes the "exitedEvent" change.
https://github.com/Microsoft/ptvsd/pull/25
