### ISSUE TITLE
Experimental option text for VSC debugger does not reflect the intent accurately

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3539]
The text here is insufficient. 
![image](https://user-images.githubusercontent.com/3840081/34743471-b6789b4a-f53e-11e7-9c25-184312b38436.png)

1. This should not imply that VS Code is needed in any way
2. There should be some text about the installation 
3. [may be] Some more text about reverting or tell the user they don't need to worry about reverting.

**Comment by zooba** [comment]
Though we probably want to hide this for 15.6 and bring it back for the 15.7 Preview...

**Comment by huguesv** [comment]
It's hidden now.
