### ISSUE TITLE
Optimize code that determines which conda.exe to use

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3540]
When more than one global conda.exe is found, we look at the version information `conda.exe -V`, and the latest version wins.

The problem is that it's slow to run `conda.exe -V`. And we do it in a few places. And when the global list of environments is rescanned, it has to be recomputed because a new conda.exe might show up (or an existing one deleted).

We need to minimize the number of times we do this. We should be able to cache the version per file path (maybe along with file time stamp in case it's upgraded).

Users of `CondaEnvironmentManager` are the ones that are computing this every time and need to be updated.

**Comment by zooba** [comment]
Looks like there's a `.version` file in the `Lib/site-packages/conda` directory that would suffice, assuming we can find it.
