### ISSUE TITLE
Test support to switch between current debugger and VSC debugger

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3546]

**Comment by zooba** [comment]
Does this involve writing a test? Or is it just a time-consuming task?

If it isn't going to be closed by a PR, GitHub probably isn't the place to track it.

**Comment by karthiknadig** [comment]
Yes this involves writing tests. here is the PR for it https://github.com/Microsoft/PTVS/pull/3557

**Comment by karthiknadig** [comment]
Removing https://github.com/microsoft/ptvs/issues/3547 as the blocker. We use a force-kill the python process after the test has run.

**Comment by karthiknadig** [comment]
8ae9f28
