### ISSUE TITLE
Syntax highlighting not updating on newline

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#3549]
The repro steps are as follows:

1. Create a new empty .py file.
2. Type `import sys` (with no newline); at this point, `import` is highlighted as keyword.
![image](https://user-images.githubusercontent.com/1175142/34843800-66c1f330-f6c4-11e7-9662-b990c7722baa.png)
3. Save the file.
4. Move cursor to beginning of line and press Enter.
5. `import` (which is now on the second line) is no longer highlighted.
![image](https://user-images.githubusercontent.com/1175142/34843790-5b9be86c-f6c4-11e7-8653-7cd96c3bf3d9.png)

**Comment by zooba** [comment]
We'll need to retest this after #3530 gets merged, as this code has been changed quite a bit.

(Also... fixedsys? Really? :o) )

**Comment by huguesv** [comment]
Several bugs related to syntax highlighting getting out of sync have been fixed. This should be okay now.
