### ISSUE TITLE
Possible defects in the source code

### ISSUE THREAD

**Issue by AppChecker** [Microsoft/PTVS#3551]
Hi.
We've checked your project with [AppChecker static analyzer](https://npo-echelon.ru/en/solutions/appchecker.php) and found a several  possible defects:

1) [ModuleId.cs](https://github.com/Microsoft/PTVS/blob/ebfc4ca8bab234d453f15ee426af3b208f3c143c/Common/Product/SharedProject/Navigation/ModuleId.cs#L51-L52)
```
ModuleId other = obj as ModuleId;
if (null == obj) {
```
Most likely it's necessary to check 'other' variable to null:
```
ModuleId other = obj as ModuleId;
if (other == obj) {
```

2) [ExtractLambdasFromXaml.cs](https://github.com/Microsoft/PTVS/blob/ebfc4ca8bab234d453f15ee426af3b208f3c143c/Common/Tools/BuildTasks/ExtractLambdasFromXaml.cs#L257)

`if (typeAttributesConverter != null || typeAttributesConverter.CanConvertTo(typeof(string))) {`
if 'typeAttributesConverter' will be null, then method CanConvertTo will be invocated.
Probably, it should be:

`if (typeAttributesConverter != null && typeAttributesConverter.CanConvertTo(typeof(string))) {`

3) [IterableInfo.cs](https://github.com/Microsoft/PTVS/blob/6d10f259bcb3a3282cabfa8f616986aba13f27fd/Python/Product/Analysis/Values/IterableInfo.cs#L197)

`                if (si != null && !_node.Equals(_node)) {
`
_node is comared with itself.

Hope it was useful.

**Comment by zooba** [comment]
Clever advertising (and I approve), and thanks for the tips.
