### ISSUE TITLE
Re-disable django html extensions for next preview build

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3552]
in product.settings:
```
    <!-- UNDONE: Exclude HTML editor extensions until we get an API stability guarantee from that team -->
    <IncludeDjangoHtmlExtensions Condition="'$(IncludeDjangoHtmlExtensions)' == ''">false</IncludeDjangoHtmlExtensions>
```    

Reapply this change, in whatever branch we build next preview from.

**Comment by zooba** [comment]
Probably better to just disable it in the build - add a variable `IncludeDjangoHtmlExtensions` with value `false` and it will override the option.

**Comment by zooba** [comment]
In fact, I just made the change and kicked off a test build. So assuming it gets excluded correctly, this is done.

**Comment by zooba** [comment]
Confirmed that the latest build doesn't have any references to the HTML editor.
