### ISSUE TITLE
serial library in python 3.6.3 is deeply changed after update from VS on 10 Jan 2018

### ISSUE THREAD

**Issue by famisano67** [Microsoft/PTVS#3553]
Gentlemen,
I have a problem with Python .6.3 after recent update from Visual Studio.

The new "serial" library seems deeply changed. The Serial class to communicate with serial ports is not apparently anymore provided. It worked well until 10 January, when I updated the packages. The "help" function indeed shows that "serial" is something quite different from the previous one.

Please, could you provide me some suggestions about how this function is now provided? 

Thanks in advance

Franco

**Comment by huguesv** [comment]
The Python install directory changed in the latest Visual Studio update. Both Anaconda and CPython are now installed under `C:\Program Files (x86)\Microsoft Visual Studio\Shared`.

This means you will need to reinstall any external libraries that you previously had installed in the old location. If you had created virtual environments (based on that Python install), you will need to recreate them as well.

Hope this helps. Sorry for the trouble!

**Comment by famisano67** [comment]
No problem Hugues, thanks for your feedback.
 Indeed I have solved the problem more drastically that is uninstalling Python and reinstalling it out of Visual Studio environment. Anyway I will apply your suggestion on another PC to check it.
Kind regards
