### ISSUE TITLE
Closing a Python debugging window causes another Python debug project to close under the same solution

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#3568]
(from https://developercommunity.visualstudio.com/content/problem/179608/关闭一个python调试窗口会导致相同解决方案下另一个python调试项目关闭.html)

Steps: 1, two or more solutions within the Python Project 2, running project 1 debugging 3, running project 2 debugging 4, closing Project 1 debugging phenomenon: All projects Stop debugging

**Comment by huguesv** [comment]
I confirmed that is the case. I tried with 2 console apps, and if I closed one of the consoles, all debugging stopped.
