### ISSUE TITLE
Add 'conda' extension to environments window

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#358]
Currently we only support pip for managing packages through the environments window.

We could add conda support for listing, installing, updating and removing packages through its own tab.

**Comment by denfromufa** [comment]
+1, also virtual environments from conda:

http://conda.pydata.org/docs/_downloads/conda-pip-virtualenv-translator.html

**Comment by thomco** [comment]
+1

**Comment by huguesv** [comment]
The bulk of this is done. I'll file separate issues for the remaining stuff.
