### ISSUE TITLE
Getting compilation error while trying to compile PTVS-master

### ISSUE THREAD

**Issue by SimplifyOrg** [Microsoft/PTVS#3581]
Following is the error that I could collect. I have also attached the detailed build log. Any help will be appreciated. Thanks!

25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbol.cs(26,29,26,45): error CS0246: The type or namespace name 'INavigableSymbol' could not be found (are you missing a using directive or an assembly reference?)
25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbolSourceProvider.cs(31,43,31,73): error CS0246: The type or namespace name 'INavigableSymbolSourceProvider' could not be found (are you missing a using directive or an assembly reference?)
25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbolSource.cs(34,35,34,57): error CS0246: The type or namespace name 'INavigableSymbolSource' could not be found (are you missing a using directive or an assembly reference?)
25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbol.cs(40,28,40,50): error CS0246: The type or namespace name 'INavigableRelationship' could not be found (are you missing a using directive or an assembly reference?)
25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbolSource.cs(60,27,60,43): error CS0246: The type or namespace name 'INavigableSymbol' could not be found (are you missing a using directive or an assembly reference?)
25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbolSourceProvider.cs(28,20,28,50): error CS0246: The type or namespace name 'INavigableSymbolSourceProvider' could not be found (are you missing a using directive or an assembly reference?)
25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbolSourceProvider.cs(47,16,47,38): error CS0246: The type or namespace name 'INavigableSymbolSource' could not be found (are you missing a using directive or an assembly reference?)
25>E:\Projects\Python\PTVSforVS2017\PTVS-master\Python\Product\PythonTools\PythonTools\Navigation\Navigable\NavigableSymbol.cs(43,30,43,52): error CS0246: The type or namespace name 'INavigableRelationship' could not be found (are you missing a using directive or an assembly reference?)
[Buildlog.txt](https://github.com/Microsoft/PTVS/files/1647168/Buildlog.txt)

**Comment by huguesv** [comment]
If you want to build/use the latest from master, you'll need to use 15.6 Preview 2. Previews are available here https://www.visualstudio.com/vs/preview/ and can be installed side-by-side with your regular VS.

**Comment by SimplifyOrg** [comment]
Thanks Hugues!

I will try that on Monday, as I do not have windows at home.

**Comment by SimplifyOrg** [comment]
So I was able to compile PTVS fine using VS 15.6 Preview 2, but I have one more question.
Will the .vsix generated out of it be enough to enable python debugging in VS 15.0. I know I can upgrade my VS 2017 professional to 15.4 and install "python development workload" but in some project I have to use the specific compiler version in VS15.0 and upgrading changes my compiler version so I guess upgrading is not an option for me.

On similar lines will it be possible to update VS without updating compiler?

**Comment by zooba** [comment]
It's very unlikely that you'll be able to get this to install on 15.0. Your best bet will be to install 15.0 to build with, go through `Build\15.0\packages.config` and find the equivalent version for each `VisualStudio` package that matches the 15.0 release, then go through and remove any functionality that doesn't work.

We haven't had to worry about targeting 15.0 ever, and recently we've only been concerned about 15.6, so there are changes in there that simply won't work on the earlier versions.

**Comment by SimplifyOrg** [comment]
Thanks for the information Steve! I will try to see if we can upgrade to 15.5. This it will become a lot easier for us.

**Comment by zooba** [comment]
Also, if you're able to, we'd love it if you could drop us an email at ptvshelp@microsoft.com and give us an idea of why you're having to build PTVS yourself. If there's something we can do in the official release to help out, we're definitely open to it, but mostly we're interested :)

**Comment by SimplifyOrg** [comment]
The reason for us to compile PTVS on our own is, VS15.0 does not have any support for python at all. For some C++ compiler version restrictions we were not able to migrate to VS15.2. Now it seems that there is no way we can work on both python and C++ without upgrading. We are internally exploring if that encompass any compatibility issues or not. As some of our projects are tested on VS15.0 compiler so we are being over cautious about upgrading our c++ compiler version.

**Comment by AndrewPardoe** [comment]
@SimplifyOrg, feel free to reach out to me if you find issue that prevent you from upgrading. The C++ team [carefully tracks changes due to conformance work](https://docs.microsoft.com/en-us/cpp/cpp-conformance-improvements-2017) with fixes when you need to change your code. The VS2017 toolsets area all [binary compatible](https://blogs.msdn.microsoft.com/vcblog/2017/03/07/binary-compatibility-and-pain-free-upgrade-why-moving-to-visual-studio-2017-is-almost-too-easy/) with VS2015: the C++ compiler version in VS2015 is 14.00, in VS2017 it's 14.1x.

**Comment by SimplifyOrg** [comment]
Sure Andrew!
We are going to have a meeting with Microsoft guys sometime later this month to discuss this issue. I will update you the outcome.
