### ISSUE TITLE
[Feature]: Add Jade syntax coloring

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#359]
Create new Flask/Jade project. Open Jade file. Observed: no syntax coloring. 

It would be nice to add basic colors to Jade. WebMatrix can do it.

**Comment by huguesv** [comment]
If you install NTVS, you'll have Jade syntax coloring.

**Comment by zooba** [comment]
This is out of scope for PTVS. Other extensions can provide it.
