### ISSUE TITLE
Interactive scripts work in normal Interactive Window, but not in Debug Interactive.

### ISSUE THREAD

**Issue by EdwardJB** [microsoft/PTVS#3593]
I've added some scripts containing functions to the `...\Visual Studio 2017\Python Scripts\Python 3.6 (64-bit)` folder. These functions import OK and are available under the `Python 3.6 (64-bit) Interactive` Window, but when I try to use them in `Debug Interactive`, they aren't loaded - and I cannot see any way of doing so. I tried creating a folder called `...\Visual Studio 2017\Python Scripts\Debug` and putting the scripts there but that didn't work.

The whole reason I need these functions are to ease debugging.

**Comment by huguesv** [comment]
Support for startup scripts is not implemented in the debug interactive. Thanks for the suggestion.
