### ISSUE TITLE
Analyzer stops responding

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3604]
Latest build from 15.6rel

No completions, tooltips, etc. I had to reload the project to get IntelliSense again.

It happened right after I created a new python file `typing_26_1_1.py` and moved code from `TypeHintsTesting.py` to the new file.

I saw this before while testing the PR, and couldn't find a consistent minimum repro. I'll add more info as I find out more. I'll send the logs too.

![image](https://user-images.githubusercontent.com/1696845/35301596-c8e027fa-0040-11e8-8ea0-0094e652f978.png)

**Comment by zooba** [comment]
From the logs, it looks like the test analysis extension broke it.

**Comment by huguesv** [comment]
Okay, I'll run without test explorer loaded for a while and see what happens.

**Comment by zooba** [comment]
Make sure you restart after closing the window - it never unloads anything.

**Comment by huguesv** [comment]
Yep, I'm used to the restart.

Took less than 2 mins to break again. Sending more logs.

**Comment by huguesv** [comment]
Hmm, I might have a consistent repro. I typed the exact same thing again, and IntelliSense stopped working at the exact same time as my previous test.

I noticed it because `str` didn't appear in completions when I was adding those last 3 lines. After that, `import ` gives no completions, etc.

![image](https://user-images.githubusercontent.com/1696845/35304124-4361f546-0049-11e8-8c73-28fd283f5234.png)

**Comment by huguesv** [comment]
New python application
Paste this code:
```
from typing import List
Vector = List[float]

def scale(scalar: float, vector: Vector) -> Vector:
    return [scalar * num for num in vector]

new_vector = scale(2.0, [1.0, -4.2, 5.4])

from typing import Dict, Tuple, List

ConnectionOptions = Dict[str, str]
Address = Tuple[str, int]
Server = Tuple[Address, ConnectionOptions]

def broadcast_message(message: str, servers: List[Server]) -> None:
    pass
```

Then type this by hand:
```
def broadcast_message(
    message: str,
    servers: List[Tuple[Tuple[str, int], Dict[arg_str, str]]]) -> None:
    pass
```
