### ISSUE TITLE
Inconsistent types reported by IntelliSense

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3607]
Using type hints:

1. The mouse hover tooltip reports a different type for the `vector` parameter `Vector` vs. the method return type `list`.
2. The signature info in the second tooltip has `vector` parameter type `list`.

![image](https://user-images.githubusercontent.com/1696845/35302254-b0654cc6-0042-11e8-8b7e-a0990a6e53a7.png)

If I eliminate all calls to `scale`, reload project then this is the signature I get, with no type for `vector` parameter, as if it ignored the type hint and only went by usage:
![image](https://user-images.githubusercontent.com/1696845/35302367-123e9560-0043-11e8-9d44-0d57240f71ba.png)

**Comment by zooba** [comment]
I think this is partially addressed in my signature help PR. The description of parameters and the signature help is now coming from the same place, and when there is no information in the variable, the annotation is displayed as-is. There is probably no information in `vector` because we weren't able to translate the generic into a real type.

You also have to take into account that type hints are supplementary information - we still prefer actual types over type hints. It works by injecting the actual types inferred from the type hints where we can do it.

**Comment by zooba** [comment]
This is also dramatically helped by #3646, which generates proper descriptions for type annotations.

**Comment by huguesv** [comment]
It looks good now
![image](https://user-images.githubusercontent.com/1696845/41127328-5999b6c0-6a5f-11e8-8a30-9aa9bc018891.png)

For reference, the code:
```
from typing import List

Vector = List[float]

def scale(scalar: float, vector: Vector) -> Vector:
    return [scalar * num for num in vector]

new_vector = scale(2.0, [1.0, -4.2, 5.4])
```

**Comment by michaelosthege** [comment]
Hello,
I am having some trouble with a similar situation. I am interested in type-hinting a property of a [`Generic[T]` container](https://docs.python.org/3/library/typing.html#user-defined-generic-types), but it looks like `Generic[T]` does not work properly (or its my fault).

Based on the example in the comment above:

```python
from typing import TypeVar, Generic, Iterable, List

T = TypeVar('T')

class MyCollection(Generic[T]):
    def __init__(self, col:Iterable[T]):
        self.col = col

    @property
    def first(self) -> T:
        return self.col[0]

    def get_last(self) -> T:
        return self.col[-1]

def to_list(iter: Iterable[float]) -> List[float]:
    #return list(iter)
    pass

def to_collection(iter: Iterable[float]) -> MyCollection[float]:
    #return MyCollection(iter)
    pass

original = [1.0, -4.2, 5.4]

new_list = to_list(original)             # hints as: list[float]
list_last = new_list[-1]                 # hints as: float

new_collection = to_collection(original) # hints as: MyCollection
                                         # expected: MyCollection[float]

first = new_collection.first             # hints as: T
                                         # expected: float

last = new_collection.get_last()         # hints as: T
                                         # expected: float
```

Note that the `return ...` lines are __disabled on purpose__. This is to prevent the type hints from originating from the original iterable.

In the case of `-> List[float]`, the `new_list` and `list_last` type hints are inferred from the hint as expected.

In the case of `-> MyContainer[float]`, the type is not hinted as expected.


So I'd say this is either a bug (missing support for `Generic[T]`?), or I am doing something wrong.
Your thoughts?

cheers & thank you!
Michael
