### ISSUE TITLE
NamedTuple completions only show fields with default values

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3608]
From https://docs.python.org/3/library/typing.html#classes-functions-and-decorators

```
from typing import NamedTuple

class Employee(NamedTuple):
    name: str
    id: int = 3

employee = Employee('Guido')
print(employee.name)
print(employee.id)
employee.
```

Mouse hover tooltip on `employee` correctly shows that the type is `Employee`.

Completions on `employee.` only include `id`, missing `name`.

**Comment by zooba** [comment]
Further info, the "obvious" fix for this (treat undefined variables as defined if there is a type annotation) is not correct, unless we also add support for clearly marking that the variable does not exist.

Automatic definition of annotations should only occur when the metaclass does it (probably hardcoded to those that we know, though it would be ideal to be able to infer it from the implementation).

**Comment by MikhailArkhipov** [comment]
PyCharm does not complain that it is undefined and neither does Pylint
