### ISSUE TITLE
Product/file version doesn't have a build number

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3609]
I tested build 18023.2 and I think maybe our build number injection code is no longer working now that we've gone from version 3 to 15:

![image](https://user-images.githubusercontent.com/1696845/35307701-dde244d6-0058-11e8-91a4-d5460880d0fd.png)

![image](https://user-images.githubusercontent.com/1696845/35307713-f21ad1ca-0058-11e8-8fb5-7aa991bf7ca1.png)

**Comment by zooba** [comment]
Yep, shouldn't have updated `AssemblyVersion.cs` at all.
