### ISSUE TITLE
Mixed-mode debugging doesn't work with 64-bit Python

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3611]
I tried with 15.6 preview 2, and the latest 15.6 build, and I'm getting the same results.

Create new python application
Project settings/debug/enable native code debugging
Set interpreter to Python 3.6
Write some code and put breakpoints
Start debugging

Result: VS goes to debugging mode and app runs, but doesn't stop at breakpoints. Breakpoint icon says it won't be hit because symbols haven't been loaded.

I also tried with Python 2.7.13 64-bit, where I downloaded the pdbs and added the folder to debugger symbols settings (before doing this I got the task dialog telling me to download them).

Am I missing a step?

**Comment by zooba** [comment]
See if the debugger helper DLLs are loaded and have symbols, and if so, try to set a breakpoint in one of them (grab the source code from a build).

Maybe someone has changed the default build settings again and we're getting non-debuggable DLLs.

**Comment by huguesv** [comment]
Symbols for debugger.helper loaded, same for python.exe. I've set breakpoints in every function in trace.cpp, they appear red with no warning, but don't get hit.

**Comment by huguesv** [comment]
I checked that on master branch, debug build of PTVS.

**Comment by int19h** [comment]
What happens if you just do Break All? In particular, what does it show in the call stack and in the modules list?

**Comment by huguesv** [comment]
![image](https://user-images.githubusercontent.com/1696845/35357628-f98ded1a-0108-11e8-9b62-db9190319275.png)

**Comment by int19h** [comment]
So the Python debugger isn't running at all (no .py files in Modules, and python27.dll frames in stack trace). 

Hard to say what's going wrong exactly, but the breakage is certainly much broader than just breakpoints. I'll take a look.

**Comment by int19h** [comment]
Seems to be specific to 64-bit Python - 32-bit works fine.

**Comment by int19h** [comment]
The root cause is that the breakpoint that the debugger sets inside `OnInitialized` (to detect when helper DLL is ready to go) is not hit in 64-bit builds.

The breakpoint is set and enabled properly in this code in `LocalComponent`:
```cs
                    bool isInitialized = moduleInstance.GetExportedStaticVariable<ByteProxy>("isInitialized").Read() != 0;
                    if (isInitialized) {
                        OnHelperDllInitialized(moduleInstance);
                    } else {
                        DkmRuntimeBreakpoint initBP = null;
                        initBP = CreateRuntimeDllExportedFunctionBreakpoint(moduleInstance, "OnInitialized", (thread, frameBase, vFrame, retAddr) => {
                            initBP.Close();
                            OnHelperDllInitialized(moduleInstance);
                        });
                        initBP.Enable();
                    }
```

And `OnInitialized` is executed as expected - but the corresponding breakpoint isn't triggered, and we never get the `OnRuntimeBreakpointReceived` callback.

I suspect this is a VS regression, since we haven't change anything on this code path in a long time.

**Comment by int19h** [comment]
The real reason is that our Concord `RemoteComponent` doesn't get loaded at all in 64-bit, because in that scenario it has to be loaded in a separate process (msvsmon.exe). This is the exception with which it fails:

> {"Could not load file or assembly 'Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

And here's the Fusion log:
```
=== Pre-bind state information ===
LOG: DisplayName = Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/Remote Debugger/x64/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.PythonTools.Debugger, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Remote Debugger\x64\msvsmon.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/Remote Debugger/x64/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/Remote Debugger/x64/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/Remote Debugger/x64/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/Remote Debugger/x64/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.EXE.
LOG: Attempting download of new URL file:///C:/USERS/INT19/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B6255AABEXP/EXTENSIONS/MICROSOFT CORPORATION/PYTHON/3.0/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.DLL.
LOG: Attempting download of new URL file:///C:/USERS/INT19/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B6255AABEXP/EXTENSIONS/MICROSOFT CORPORATION/PYTHON/3.0/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.DLL.
LOG: Attempting download of new URL file:///C:/USERS/INT19/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B6255AABEXP/EXTENSIONS/MICROSOFT CORPORATION/PYTHON/3.0/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.EXE.
LOG: Attempting download of new URL file:///C:/USERS/INT19/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_B6255AABEXP/EXTENSIONS/MICROSOFT CORPORATION/PYTHON/3.0/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces/Microsoft.VisualStudio.Debugger.DebugAdapterHost.Interfaces.EXE.
```
This is the assembly that we're referencing to enable the new ptvsd functionality on VS side of things (the code for which happens to live in the same DLL as the Concord debugger).

**Comment by int19h** [comment]
This is the bit that causes Reflection to try to load all types from the assembly - it in `ComponentBase`:
```cs
        static ComponentBase() {
            // Register all known message types. 
            foreach (var type in typeof(ComponentBase).Assembly.GetTypes()) {
                var baseType = type.BaseType;
                if (baseType != null && baseType.IsGenericType) {
                    var genTypeDef = baseType.GetGenericTypeDefinition();
                    if (genTypeDef == typeof(MessageBase<>) || genTypeDef == typeof(MessageBase<,>)) {
                        RuntimeHelpers.RunClassConstructor(baseType.TypeHandle);
                    }
                }
            }
        }
```

**Comment by int19h** [comment]
The proper fix is to split the assembly, so that Concord debugger doesn't have any unnecessary references.
