### ISSUE TITLE
Publish / debug Python scripts that are deployed as part of a desktop application.

### ISSUE THREAD

**Issue by DrMaxP** [Microsoft/PTVS#3617]
I have a Python project that is part of a larger solution that builds a WPF application. I use this project to debug/test the python code. This same code is called from the WPF application and I deploy the scripts as part of the application.

My problem is that I feel I'm missing a trick on how to deploy these scripts - e.g. when debugging my application. There is a Publish option supported by the Python project. However, this only appears to publishes to one location, it doesn't appear to support relative paths or (MSBuild] parameters. What I'd like to do is to republish the script files to a debug or release folder, based on the build target.

I thought about doing an xcopy or similar. However, because it's a Python project, there is no build option - although it seems there may be a work around for this. How are post and pre build targets triggered. You cannot build the project directly, but if I add a dependency, will it effectively build / publish?

**Comment by int19h** [comment]
"Publish" is mostly for web publishing.

It sounds like the easiest way to do what you want in a multi-project solution would be to manually muck around with MSBuild tasks. To get your project to build, just make sure it has a target for that - you can create a simple Bottle web project, and look at the .pyproj file to see how that works. There are no default build steps, so you'll be fully in control of what happens when.

**Comment by DrMaxP** [comment]
Thanks. What invokes the build tasks. There is no build option for a python project.

**Comment by int19h** [comment]
There is - VS just doesn't enable it unless you have a target named `CoreCompile` in the project (it can be, and usually is, empty for Python projects - it just has to be there).

**Comment by zooba** [comment]
Side note: the `CoreCompile` requirement is specifically for Python projects. We have code running in VS that detects this target and enables the Build command when it is there.

Web projects import a different `.targets` file that defines `CoreCompile`, which is why they can be built.
