### ISSUE TITLE
Code analysis features not updated after package is installed or removed

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#3636]
New Bottle Web Project
Accept Virtual Env + Install requirements option
app.py automatically opens

Notice the squiggles on `import bottle`
Wait for virtual env + package install to finish

Result: Squiggles don't go away. No completions on `bottle.`.

Close/reopen file doesn't help. You have to close/reopen solution.

The reverse problem also exists. Now that you've reloaded the solution and get completions on `bottle`, uninstall the package.

Result: Squiggles don't appear. Close/reopen file doesn't help. You have to close/reopen solution.

**Comment by zooba** [comment]
This repros in master and probably 15.9.

**Comment by zooba** [comment]
It still works sometimes (often?), so there is clearly some non-obvious condition here.
