### ISSUE TITLE
When defining a method in interactive, its parameters don't appear in completions

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#3638]
Open Python interactive
Type anything just to start the process
```
def hello(one, two):
    print(on<ctrl-space>
```

`one` doesn't appear in completions

![image](https://user-images.githubusercontent.com/1696845/35405388-d73dd33a-01ba-11e8-98d7-57e13b5bc5ca.png)

**Comment by MikhailArkhipov** [comment]
Works in VS and VSC

![image](https://user-images.githubusercontent.com/12820357/39319548-42e73758-4936-11e8-9924-189ce60a3efe.png)

**Comment by syeerzy** [comment]
![1](https://user-images.githubusercontent.com/1835017/62770833-70cca580-bace-11e9-9415-2990f169bf1a.png)

It's fixed now.
