### ISSUE TITLE
python library in c# form 

### ISSUE THREAD

**Issue by Onursevig** [Microsoft/PTVS#3648]
hello, I searched internet but can not found a way so I wonder is it possible or not. I want to use some python flies in c# form application ,is that possible ?

**Comment by zooba** [comment]
The easiest way to do this is to use [IronPython](http://ironpython.net/), which is a .NET library you can include that can load and run many Python files.

It can't use all the libraries that regular Python can though (in particular, most of the data science libraries do not work), but if you want to manipulate .NET objects in Python (for example, adding scripting capability to your app) then IronPython is the best option.
