### ISSUE TITLE
Super simple code fails

### ISSUE THREAD

**Issue by Nasalberry** [Microsoft/PTVS#3649]
This simple bit of code fails and I cant tell why:

    def why():
        a = raw_input("type HELLO: ")
        if a == "HELLO":
            print True
        else:
            print False
    why()

whatever I type it always prints False, in python 2.7,  using Visual Studio

**Comment by huguesv** [comment]
It's working as expected for me if I type `HELLO`.

**Comment by zooba** [comment]
Does it work if you run it from a normal Python prompt (i.e. run Python from the start menu and type the same code)?

What language is you computer running in? I can imagine this might be an encoding problem, but that's unlikely unless you're on one of the less common encodings. Testing with Python 3 might give you a better error message (or may just work) if this is the case.
