### ISSUE TITLE
Unicodeescape Codec in Comments

### ISSUE THREAD

**Issue by MarkMoretto** [Microsoft/PTVS#3651]
Hi,

I'm using VS17 with Python 3.5 (64-bit).  When I make initial commentary using triple-bracket enclosures, my comments appear to be checked over and I get a bunch of red squiggles in using directory paths that contain "C:\Users\..."

This is a unicode escape error, which I know can be resolved a few ways in Python.  But, why is VS17 checking this in comments?  Comments aren't active script and should be able to be written in any manner deemed fit for the program.

I haven't had this issue with VS13 at work, which also utilizes IPython.  Should I install that for VS17?

If there's a way I can adjust this that I haven't come across, please let me know!

**Comment by int19h** [comment]
If you mean triple-quoted strings, and the use of the same for docstrings, then they aren't comments in the usual sense - they're still a Python string literal, and must syntactically conform to the rules for the same as far as Python is concerned. This is not a PTVS thing - you'll see the error from Python itself if you try to run your program.
```
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> '''C:\Users'''
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

**Comment by MarkMoretto** [comment]
Huh, really?  Can I enable a feature for those to turn into links in VS17 if not in quotes or raw form?

Also, I want to upgrade Django 1.8.18 to 2.0 in Python 3.5 (64-bit) and think I've selected the environment n the Interactive Window, but am not really sure how to do that.  Django 2.0 is installed in my C:\Anaconda3 folder, but I was hoping to use the Python 3.5 environment.  Any suggestions on adjusting my setup or do you know of any resources I could view to fix this?  (I'm, admittedly, still a computer programming novice.)

**Comment by zooba** [comment]
If you have a path in a string by itself you can press `Ctrl+Space` within it to activate completions. This will pop up files on your computer and help you complete them, and when you commit a change it will automatically turn single backslashes into double ones (unless it's a raw string).

As for managing packages, have a look at [this part of our tutorial](https://docs.microsoft.com/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages). Or if you'd rather watch a short video, there's a 2 minute one [here](https://mva.microsoft.com/en-US/training-courses/python-tools-for-visual-studio-2017-18121?l=qrDmN4LWE_8305918567).
