### ISSUE TITLE
All Python Modules missing after update

### ISSUE THREAD

**Issue by G-Beni** [Microsoft/PTVS#3654]
Im using The Python 3.6 x64-bit Python Environment,  windows 10.0 ,visual studio 2017 version 15.5.
After an Update (either to newest version or to Include Data Science tools) all of my Modules are suddenly missing. 
The Modules are still in my Python folder and they have the init.py files in them but Intellisense doesnt find any of them. I also tried restarting my Pc multiple times. 

Manually installing them works(as far as i can see) but manually installing over 100 modules is realy frustrating.
Also i wont Update this Programm anymore if this is intended, nobody has the time/nerves to do this every time. 
Any help is appreciated.

**Comment by zooba** [comment]
I suspect you've hit the one-off update we did that moves the Python install to a Visual Studio-specific directory. (This is to enable people to install everything onto a different drive, which we didn't allow before by forcing it to go to the default.)

You should find the new Python install directory under `Microsoft Visual Studio\Shared`, and if you move the `site-packages` directory from its old location to the new one then it should be okay (though chances are anything in the `Scripts` directory will still point to the old location).

Alternatively, you can uninstall the copy of Python that Visual Studio installed and reinstall it yourself (from [python.org](https://python.org)), selecting the normal All Users installation location. We offer Python as an install option just for convenience, but if you're comfortable managing it yourself then feel free to deselect it from Visual Studio.

**Comment by G-Beni** [comment]
@zooba Ok i added the Python modules to Microsoft Visual Studio\Shared\Python36_64\Lib\site-packages(they got recognized in MCVS).
And copied the old contents of the Scripts folder into the new Microsoft Visual Studio\Shared\Python36_64\Scripts folder 
when Trying to run any Python Programm i get the Error: The object reference was not set to an object instance.
There is no further indication where this Error could be located. As far as i understand some Module/Extension/etc isn't defined or something like that.
I now have my Modules but no way of using them...

**Comment by zooba** [comment]
It's likely that the contents of your `Scripts` directory is corrupt at this point. When Python installs packages, it embeds the full install path into those scripts, which means you can't just move them around - you really do need to install them again (FWIW, I filed a bug a few years ago for them to fix that, but they haven't yet).

If you can go to Tools, Python, Diagnostic Info, save the file and either post it here or to ptvshelp@microsoft.com, we may be able to see more information about that error. Generally that would indicate registry corruption or an error in a custom environment's configuration.

**Comment by G-Beni** [comment]
@zooba Ok here is the diagnostics File: 
[Diagnoseinformationen 2018-01-30T173352.txt](https://github.com/Microsoft/PTVS/files/1678503/Diagnoseinformationen.2018-01-30T173352.txt)
If i were to install all of my plugins again, how likely would it be to break again with another update ?

**Comment by G-Beni** [comment]
(Update): I just deleted all python modules and scripts and then ran the repair tool in the Visual Studio Installer. The Error is gone but now i have to install all modules again. To anyone that comes accross this Issue, good luck!

**Comment by zooba** [comment]
We're not planning on changing the install location again, but we will provide newer versions of Python as they become available and we don’t guarantee that third-party libraries are going to be compatible with eg. Python 3.6.5 vs. 3.6.4. They should be binary compatible, but may not be. (Python 3.7 will install into a different directory, so won’t be a problem here.)

**Comment by G-Beni** [comment]
That`s good to hear. Thank you for the help. 
Issue "closed" i guess.

**Comment by cyclicredundancy** [comment]
Same thing just happened to me! 
[vent]Terrible decision to move the python install directory[/vent]

**Comment by rootVIII** [comment]
What business does anyone have ruining my dev environment?
