### ISSUE TITLE
Cookiecutter progress bar should not move the button when it shows up

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3661]

**Comment by zooba** [comment]
(A screenshot wouldn't hurt though)

**Comment by karthiknadig** [comment]
Before:
![image](https://user-images.githubusercontent.com/3840081/35749606-f57d1b38-0806-11e8-99c1-7b2337f59d63.png)

After (Next button moves up after clicking on it):
![image](https://user-images.githubusercontent.com/3840081/35749634-10940c74-0807-11e8-938c-38406c889e11.png)
