### ISSUE TITLE
Install packages should be a option in the quick fix UI

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/PTVS#3664]
Currently it only has `Extract Method`. This could also have install package.

![image](https://user-images.githubusercontent.com/3840081/35535681-3765463a-04f9-11e8-930a-1c41d6ede010.png)

**Comment by zooba** [comment]
Should be easy enough to do this as well - the code can be taken from the project command. (Just don't fall into the trap of assuming that the package is installable by the module name - they often aren't, and it'd be an encouragement for more name-squatting malicious packages...)
