### ISSUE TITLE
Auto Completion 'pip' in the Undo Stack

### ISSUE THREAD

**Issue by AlexanderSher** [microsoft/PTVS#3665]
1. Create new file
1. Type `import pip`
1. Type `.`
1. Wait for intellisense to appear
1. Ctrl+z
1. Open `Undo` list:

![image](https://user-images.githubusercontent.com/8933858/35535595-e34ae870-04f8-11e8-978c-d9b27ced0677.png)

Clicking on "Auto Completion 'pip'" doesn't do anything.

**Comment by zooba** [comment]
What if you type `import pi` and then `.`?

I'm not sure how easily we can suppress the undo entry when VS decides to overwrite a word with the exact same word.

**Comment by AlexanderSher** [comment]
`pi` is also a package. If I type `import sy` it completes `import symbol`.

**Comment by huguesv** [comment]
This seems uncommon enough of a scenario to not be worth fixing, but I've marked it P2 for now in case we have more common cases where this comes up.
