### ISSUE TITLE
Internal error detected when executing in debug mode

### ISSUE THREAD

**Issue by KellyDeveloped** [Microsoft/PTVS#3668]
As the title suggests, my Python3 is breaking when I try to run in debug mode.

My python version is Python 3.6.3, running Visual Studio 2017 15.5.5

I've tried installing Python for windows directly from their website, as well as with the VS installer. Neither work.

This problem only appeared tonight after I upgraded from 15.0 to 15.5.5 (not sure why I was so out of date but now I sorta wish I stayed that way haha)

On top of this issue, intellisense isn't working. I assume due to the error that they're connected.

The traceback is as below - it referred me to here for help.

Any idea what's went wrong and how I can fix it?

```
Traceback (most recent call last):
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 34, in <module>
    import ptvsd.debugger as vspd
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd\debugger.py", line 29, in <module>
    import ctypes
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: The specified procedure could not be found.

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415
```

**Comment by huguesv** [comment]
I've replicated this exact scenario.

This happens when you are using a virtual environment that is broken. The upgrade to 15.5 moved the location of CPython 3.6 on disk, so the virtual environment that relies on it no longer works. You'll need to recreate a new virtual environment, and that should work.

Hope this helps!

**Comment by KellyDeveloped** [comment]
Hi, this helped! Sorry for not updating with a comment.

Replacing the virtual environment worked, up until last night where I shutdown my PC without closing a running Flask server and now debug won't launch for any of my virtualenvs on any project. I'm blessed with bad luck with technology haha
