### ISSUE TITLE
Multiple Anaconda installations after updating Visual Studio

### ISSUE THREAD

**Issue by deepyaman** [Microsoft/PTVS#3669]
## Environments

I have both Visual Studio Enterprise 2017 Preview and Visual Studio Enterprise 2017 (2) installed on my machine running Windows 10. I don't actually believe I've used Preview on Windows 10 (I've opened it up, but haven't worked in it), but I used to use it on Windows 7 before the Data Science workload was available in non-Preview, so I went ahead and installed it. On January 23, I updated my Visual Studios and their Data Science workloads. Today, I was creating a new Python project when I got confused and frustrated about not finding packages that I was installing on my OS.

Turns out I was looking in `C:\Program Files\Anaconda2\`, when I was supposed to be looking in `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda2_64`. I only installed Python 2 (and Anaconda2) while updating Visual Studio, because I'm just now starting work on a project that uses Python 2-only packages. However, now I've got:

```powershell
PS C:\Program Files> ls .\Anaconda[23]\


    Directory: C:\Program Files


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/23/2018   7:52 PM                Anaconda2
d-----        9/26/2017   4:52 PM                Anaconda3

PS C:\Program Files> ls C:\Python*\


    Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
da----        1/23/2018   8:12 PM                Python27amd64

PS C:\Program Files> ls '..\Program Files (x86)\Microsoft Visual Studio\Shared\*\'


    Directory: C:\Program Files (x86)\Microsoft Visual Studio\Shared


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/23/2018   8:48 PM                Anaconda2_64
d-----        1/23/2018   8:40 PM                Anaconda3_64
d-----        1/23/2018   8:09 PM                Common
da----        1/24/2018  12:15 PM                Python36_64
```

Moreover, the Python versions are (almost) all different:

```powershell
PS C:\Program Files> .\Anaconda2\python.exe --version
Python 2.7.13 :: Anaconda 4.4.0 (64-bit)
PS C:\Program Files> .\Anaconda3\python.exe --version
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
PS C:\Program Files> & '..\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda2_64\python.exe' --version
Python 2.7.13 :: Anaconda, Inc.
PS C:\Program Files> & '..\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe' --version
Python 3.6.2 :: Anaconda, Inc.
PS C:\Program Files> & 'C:\Python27amd64\python.exe' --version
Python 2.7.14
PS C:\Program Files> & '..\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe' --version
Python 3.6.3
```

Finally, I could have sworn my previous Python 3 installation was at `C:\Program Files\Python3`, but that seems to have disappeared entirely.

## Questions

1. What are the Visual Studio-expected locations for each of these environments? I understand that I can add environments in Visual Studio, but, say, what's the default on clean install? `C:\Anaconda2\`, `C:\Anaconda3\`, `C:\Python3`, etc. made sense to me, but I can understand them all being in the same `Shared` folder now. It's just the `C:\Python27amd64` that's throwing me off.

2. Can I reconcile my new `Anaconda3_64` environment with the old `C:\Anaconda3\` one? I would have expected Anaconda to update, not to get a whole new installation, but maybe it couldn't find it a la #2530? That being said, I have code that I'm still working on that uses extra libraries installed in the `C:\Anaconda3\` environment and a virtual environment created from there, so I'd rather the two Anaconda 3s get rolled into one.

Thank you in advance!

**Comment by huguesv** [comment]
I can't explain the upgrade behavior but here's the expected install folders on a clean install of 15.5 or 15.6.

```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda2_64
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_86
C:\Python27
C:\Python27amd64
```

**Comment by huguesv** [comment]
I believe 2.7 remains at the root and wasn't moved to program files because 2.7 users have been able to pip install without running as admin for years and moving it to program files would have prevented that from working.

**Comment by deepyaman** [comment]
Thanks for the list of expected install folders! At least it makes me feel better about where my environments are now (and that Visual Studio didn't choose other locations because previous installations already existed).

I'm OK with this getting closed (I can manually reconcile my Anaconda 3 environments), but I'll not close it myself now in case somebody has a solution for Question 2.

**Comment by zooba** [comment]
I'd suggest deselecting Anaconda from the Visual Studio installer and then reinstalling (or upgrading) it manually in the location where you'd like it. Anaconda's installer doesn't keep track of existing installs, so that's why it didn't remove the old one (CPython does keep track, and so we won't try and install it unless we have a newer version, and it will clean up the old one as much as it can).

The installers in VS are largely a convenience for users who don't really care where they end up, as long as they are available. So if you'd rather have them somewhere convenient for you, go ahead and deselect them from VS and install it manually.

**Comment by joseortiz3** [comment]
On the recent VS2017 update, I experienced on _multiple_ machines Anaconda 2 and 3 installing via the updater, when previously the installation had been selected _not_ to install Anaconda 2 or 3. So the update settings, whatever they are, are unintentionally installing Anaconda 2 and 3 into everyone's machines, at least from my experience with three Windows 10 machines.

**Comment by huguesv** [comment]
@zooba this sounds like the bug you've mentioned recently, is it fixed now?

**Comment by zooba** [comment]
At this point, we can't fix anything related to this any more. The next version of VS won't include Anaconda in the installer as full installs, and the problem described here is not popping up frequently enough to push out a fix in the upcoming updates. So I'm closing this.
