### ISSUE TITLE
IntelliSense gives unknown type for field with type hint

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3674]
Here's one from Dan's email listing several issues with type hints.

```
class Employee:
    name: str
    id: int

def isValidEmployee(employee: Employee):
    s = employee.name
```

It doesn't know the type of `name` is `str`. It doesn't know about `name` or `id` at all, they don't appear in completions.

![image](https://user-images.githubusercontent.com/1696845/35599563-1f5beb26-05de-11e8-8c3a-a82b352a3389.png)

FYI I checked both 15.6rel and master, no difference between the two.

**Comment by zooba** [comment]
We generally don't display undefined variables as if they are defined, so if we're going to start doing that, we'll have to come up with a way to make clear that they aren't really there.

**Comment by huguesv** [comment]
Tooltip is now okay. Not sure where the sample code originated from, but I'll close as by design.
