### ISSUE TITLE
Can't import openssl in VS2017 debug environments

### ISSUE THREAD

**Issue by kingstarcraft** [Microsoft/PTVS#3684]
There  only one line "Import OpenSSL" in test.py., and I can't start test.py with debug environments.but  I can import OpenSSL in CMD and Interactive window.
The Error at  _big_num_ctypes.py, line 37:
if not libcrypto_path:
    raise LibraryNotFoundError('The library libcrypto could not be found')

**Comment by kingstarcraft** [comment]
I have solved the problem with uninstall pycharm and reinstall  python.

**Comment by zooba** [comment]
Glad to hear you got this resolved!
