### ISSUE TITLE
Type hint isn't properly recognized for complex types

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#3706]
1. Paste the following code:
```python
from typing import Tuple, Dict

def f(x: Tuple[Tuple[str, int], Dict[str, str]]):
    pass
```
2. Type `x[0].` on the line before `pass`

**Actual**
Intellisense for `Dict`
![image](https://user-images.githubusercontent.com/8933858/35835558-32dfab04-0a90-11e8-8f84-b76d29334e42.png)

**Expected**
Intellisense for `Tuple`

**Comment by zooba** [comment]
Yeah, the rules for tuple aren't obviously properly implemented. However, what you're seeing is the union of tuple and dict elements, but tuple doesn't have any public (not `__dunder__`) names.

**Comment by zooba** [comment]
Also, we should definitely fix the display of the type - `dict(dict[str, str]))` is not the right way to show it.

**Comment by zooba** [comment]
Best available info seems to be at https://www.python.org/dev/peps/pep-0484/#the-typing-module
