### ISSUE TITLE
Flask debugging doesn't work with FLASK_DEBUG

### ISSUE THREAD

**Issue by KellyDeveloped** [microsoft/PTVS#3712]
Hi,

I've noticed that if you set the environment variable FLASK_DEBUG=1 (like in the screenshot below), the debugger no longer attaches to flask.

I imagine this is because Flask has some sort of debugger attached its self. Is there any way to attach the visual studio debugger alongside it? It'd be ideal to have debugging inside VS alongside the live reloading that the environment variable gives. 

![image](https://user-images.githubusercontent.com/11000575/35907734-b4eeef36-0be6-11e8-9802-537aac3dd86d.png)

**Comment by huguesv** [comment]
`FLASK_DEBUG` enables the reloader which spawns a subprocess and our debugger doesn't automatically attach to those. You probably could do debug/attach but you'll have to do it every time it reloads.

We have https://github.com/Microsoft/PTVS/issues/125 for this, we just need to ensure that it works well with werkzeug.
