### ISSUE TITLE
 Intellisense squiggles are some times off 

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3733]
In this code there should not be any squiggles but they appear any way. They also appear in wrong position:
![image](https://user-images.githubusercontent.com/3840081/36122581-c0188112-0ffe-11e8-97c5-542354bae6cc.png)

```python
def F(n):
  a = {0:1, 1:1}
  if n < 0:
    raise ValueError('Value is invalid: ' + str(n))
  if n in a:
    return a[n]
  x = F(n - 1) + F(n - 2)
  a[n] = x
  return x

for x in range(1, 300):
  print(F(x))

print('done')
```

**Comment by karthiknadig** [comment]
This seems to occur if you move this line `a = {0:1, 1:1}` from global scope to local.

**Comment by zooba** [comment]
I don't suppose you noticed what the locations listed in the Error List showed? So we can tell whether the analyzer is sending the wrong locations back or if the squiggles are in the wrong places?
