### ISSUE TITLE
Call stack in experimental debugger doesn't show module/line info

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3735]
Experimental debugger:
```
>	calculate_mode	Python
 	main	Python
 	<module>	Python
 	execfile	Python
 	run	Python
 	main	Python
 	debug	Python
 	<module>	Python
```

Good old debugger:
```
>	calculate_median in mymath line 8	Python
 	main in PythonApplication51 line 6	Python
 	PythonApplication51 module line 29	Python
```

**Comment by int19h** [comment]
But it still has the info, right? As in, when you click on the frames, it opens the corresponding file/line, and it's the correct one?

**Comment by huguesv** [comment]
Yes it has the info, but it's not displayed in the window. I've corrected title to reflect hat.

**Comment by huguesv** [comment]
See https://github.com/Microsoft/ptvsd/issues/64
It sounds like we may need to enable the option from VS so I'll keep this open for now.
