### ISSUE TITLE
Unittest exceptions break even when handled by assertRaises 

### ISSUE THREAD

**Issue by teeks99** [Microsoft/PTVS#3744]
When writing python unittest code, it is common to use the pattern

    with self.assertRaises(ExpectedException):
        code_that_causes_exception()

To verify that the appropriate exception is being raised. When using the debugger in PTVS to debug a unittest suite, the debugger will stop at all the points where these exceptions are being raised, and indicate that it isn't being handled. 

![exceptionunhandled](https://user-images.githubusercontent.com/33045/36227466-c7e658da-1196-11e8-92cf-69de4007cd70.png)

I think there is a defiencency in the debugger that prevents it from detecting that these exceptions are being handled by the unittest module.

I have attached a very simple example of this. Simply open the solution, put a break in the last test case (test.py:23), then start the debugger. You will see it break in the call made during the test_2_fail test case.

[PyTestException.zip](https://github.com/Microsoft/PTVS/files/1725618/PyTestException.zip)

**Comment by zooba** [comment]
Thanks for the report. We're working on significant changes to our debugger right now, so we'll recheck whether this exists in the newer one, but I suspect it does and it's hard to plan specific fixes right now (because, well, everything else is a bit broken too :) ). So we're not ignoring this, but it may be a little while before we can commit to a fix.

**Comment by huguesv** [comment]
I checked with the new debugger and it's not an issue there.

It's able to detect that test runner handles all exceptions so it never breaks on unhandled exceptions, no matter if you have an `assertRaises` or not.

I'll close since we won't be fixing this in the current/old debugger at this point.
