### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by q1o1p** [Microsoft/PTVS#3747]
Problem Event Name:	CLR20r3
Problem Signature 01:	Microsoft.PythonTools.Analyzer
Problem Signature 02:	3.0.17320.1
Problem Signature 03:	5a0dfc7f
Problem Signature 04:	mscorlib
Problem Signature 05:	4.7.2563.0
Problem Signature 06:	5a334d03
Problem Signature 07:	3993
Problem Signature 08:	21
Problem Signature 09:	System.OutOfMemoryException
OS Version:	6.1.7601.2.1.0.256.1
Locale ID:	1049
Additional Information 1:	0a9e
Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
Additional Information 3:	0a9e
Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by zooba** [comment]
Thanks. Are you able to share the code that caused it? Either here or email to ptvshelp@microsoft.com. If this happens repeatedly on the same code, we can figure out the cause and fix it, but if it just happened once then it's very hard to track down the underlying problem.

**Comment by huguesv** [comment]
I haven't seen an email come in related to this. Without more information, there isn't much we can do. If you can provide more details that help us reproduce the issue, please post it here or open a new issue.
