### ISSUE TITLE
Native threads calling back into Python

### ISSUE THREAD

**Issue by ultimateDRT** [Microsoft/PTVS#3751]
I have a C++ project wrapped in boost python and I'm using the resultant module created from this to build a Python Application. It works really well however I have noticed that threads that initiate from C++ are not tracked by the debugger and therefor python break points do not get hit on callbacks from C++-> Python. Essentially what is descrived here: https://github.com/Microsoft/PTVS/issues/3003

Can someone tell me what is the most non intrusive fix for this? Has the advice moved on a bit from what was described in the link above? It seems to recommend using ptvsd.debugger.new_external_thread() but I can't seem to import ptvsd as VS doesn't seem to know where the module exists.

Any help would be greatly appreciated. I am using VS2013 not exactly sure how to tell which version of PTVS I am using but it is fairly recent.

**Comment by int19h** [comment]
I don't think we're removing ptvsd from `sys.modules` in the most recent version, so it should be there once debugging begins; i.e. if you can't import it, that would imply that debugger is not attached yet when the thread is started - is that right?

**Comment by ultimateDRT** [comment]
No - The debugger is attached. The program fails to start because it can't import ptvsd. How do I find out where it is? Where should I find ptvsd module normally? Just so I can check my install is correct.

**Comment by int19h** [comment]
It lives in the PTVS extension folder under `...:\Program Files (x86)\Microsoft Visual Studio\...\Enterprise\Common7\IDE\Extensions` (the folder names below that will differ, but you can just search for .py files).

A simpler way for you to be able to import it at any time is to `pip install ptvsd` it into your Python environment. But it's still strange that it won't let you just import it. Can you check what's in `sys.modules`?

**Comment by ultimateDRT** [comment]
It's here but I can't seem to import it.
![image](https://user-images.githubusercontent.com/19968395/36302922-28a47398-1302-11e8-8d11-f1bcb0694826.png)

**Comment by int19h** [comment]
Ah, your version of PTVS is much older than what that workaround was written for.  

In your case, instead of an import, try this:
```py
ptvsd = sys.modules['$visualstudio_py_debugger']
```

**Comment by ultimateDRT** [comment]
Ok, if I download 2.2.2 that should support it?

**Comment by ultimateDRT** [comment]
Ok, I've upgraded to 2.2.2 and created a class like this:

class NativeCallback():
    # ptvsd
    #import ptvsd.debugger
    #ptvsd.enable_attach(secret = 'mysecret', address = ('127.0.0.1', 8080))
    #ptvsd.wait_for_attach()

    @staticmethod
    def register():
        import ptvsd
        import ptvsd.debugger
        ptvsd.debugger.new_external_thread()

Used like this:

    def onHeartbeatResponse(self, context, envelope):
        NativeCallback.register() 

and the breakpoints are still not hit.

**Comment by ultimateDRT** [comment]
Its working now! Upgraded to VS2015 using 2.2.2. Thanks.

**Comment by int19h** [comment]
:+1:
