### ISSUE TITLE
Renaming outside of method, but after method, renames method parameter.

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/PTVS#378]
## PythonToolsMockTests.RefactorRenameTests.DelNonLocal (under 3.4)
- This is failing, not repeatedly.  Ctrl-r-r on the last 'abc = 100'.  Sometimes it renames that abc, other times, that one doesn't change at all

``` python
def g():
    fob = 100
    def f():
        nonlocal fob
        del fob

abc = 100
```

**Comment by crwilcox** [comment]
Adding to this

```
def method(abc):
    abc = 2
abc = 3
```

Renaming the last line's abc changes the others.  We aren't properly detecting the end of the method.

**Comment by zooba** [comment]
Cannot repro this, probably since #3166, but `nonlocal fob` doesn't count as a reference to `fob` for the purposes of F12 or rename on it. We should fix that.
