### ISSUE TITLE
Python/Tensorflow not working with Visual Studio 2017 15.5.x

### ISSUE THREAD

**Issue by getudom** [Microsoft/PTVS#3781]
I installed Visual Studio 2017 on windows 7 64 bit.

To install Tesnsorflow, I followed the instructions here:
https://www.tensorflow.org/install/install_windows

I tried installing
Installing with native pip
Installing with Anaconda
Installing with Anaconda bundled with VS 2017

Python seems to work. This is the test:
![image](https://user-images.githubusercontent.com/36782652/36636434-20c97ede-19a6-11e8-996d-7d0c6cc0352a.png)

This is the test on anaconda bundled:
![image](https://user-images.githubusercontent.com/36782652/36636528-02e342b4-19a7-11e8-962d-e3a5b7c4ca6d.png)

But Is still doesn't works on Visual Studio
![image](https://user-images.githubusercontent.com/36782652/36636544-878606e6-19a7-11e8-9477-5eaad4e88d44.png)

**Comment by zooba** [comment]
Have you made sure that the environment you installed it into is either the default or active environment? See our docs for more info: https://docs.microsoft.com/visualstudio/python/python-environments
