### ISSUE TITLE
Cannot change architecture of a custom environment

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#379]
I have WinPython 3.4 64-bit mistakenly added as a custom 32-bit environment. When trying to change this in the Environments window, on the "Configure" tab, I flip Architecture to 64-bit and click "Apply". The tab changes to "Overview", and if I switch back to "Configure" I can see that it shows up as 32-bit again.

**Comment by int19h** [comment]
Worse yet, this also happens when _adding_ a new environment - it is auto-detected as 64-bit, but after clicking "Apply" this is reset to 32-bit and saved like that. Effectively, this means that there's no way to add a 64-bit custom environment through the UI.

**Comment by huguesv** [comment]
+1 I'm seeing this too.
