### ISSUE TITLE
Migrate special completions to server

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#3798]
As part of #3484 we need to handle the various special completions in the language server rather than the IDE.

**Comment by zooba** [comment]
Related to https://developercommunity.visualstudio.com/content/problem/198212/python-typing.html

**Comment by huguesv** [comment]
It's causing this issue:
![image](https://user-images.githubusercontent.com/1696845/37932150-9e9e2cc0-30fc-11e8-8e1c-40d2655369a9.png)
