### ISSUE TITLE
VSC debugger info bar notification

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3808]
Display an info bar letting the user know about the experimental debugger.

While I have it in front of me, here's the code snippet to get the info bar host for the main window.
```
object obj;
var shell = (IVsShell)GetService(typeof(SVSShell);
shell.GetProperty((int)__VSSPROPID7.VSSPROPID_MainWindowInfoBarHost, out obj);
```

**Comment by zooba** [comment]
When would we pop this? And what would it say?

Also bear in mind that we'd only have this for 1-2 previews before it turns on by default (at which point we may want to pop a slightly different message saying that we've done that...)

**Comment by huguesv** [comment]
One idea could be:
- When user launches debugging with old debugger, we set a registry flag (so we remember they care about debugging)
- When a Python project is opened, registry flag is set and experimental debugger is not set, we show the info bar (problem with this is we miss the open folder users, unless there's a separate hook we can use for them)

We could pop it when they start debugging but that wouldn't affect the debugging session that is starting (because the info bar isn't blocking/modal). That might make it confusing?

Or could we pop it after a debugging session has ended? "Did you find debugging was too slow? Try our new experimental debugger!"

Info bar needs to have a "don't show this again", and it needs a hyperlink that enables experimental debugger without requiring a restart VS. By that point we shouldn't require installing a package to use it, so there's no need for further instructions.

Any opinion on this @qubitron ?

**Comment by huguesv** [comment]
Also, one point that @karthiknadig has made in the past is that ideally we don't push this on users that are too novice to know what to do if this doesn't work out for them.
Users that open their first project and have never debugged before probably shouldn't enable the experimental debugger.

**Comment by qubitron** [comment]
@huguesv the banner should wait until we are at public preview and we believe that most users will benefit from the new debugger. The banner should say "Try out the preview of our new debugger before it becomes the default!" [Enable] [Close] [Don't Show This Again]. 

At the end of the debug session works because then you're less likely to get into a weird state where the user thinks they've turned on the new debugger but are using the old one.

**Comment by zooba** [comment]
Right, except "public preview" is just "on by default in preview", which means no prompts are required.

The prompt we should do then is to say "hey, you just used our new debugger, would you recommend it to your friends?" etc.
