### ISSUE TITLE
Debugger doesn't handle python interpreter arguments correctly

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3813]
If you set Interpreter Arguments to `-v` you will get:
```
FileNotFoundError: [Errno 2] No such file or directory: '-v'
```

**Comment by ttricker** [comment]
hm I saw this after I already submitted a different defect. #3934 I've included more information to what's happening.

**Comment by huguesv** [comment]
No worries. I'll close this one and keep yours.
