### ISSUE TITLE
can not rename a field variable in a python class

### ISSUE THREAD

**Issue by dbsxdbsx** [Microsoft/PTVS#3823]
I take VS 2017 15.6 community preview, with Anaconda 2.7x64 and win10.  And I find vs can not rename field variable in a class, like this:
```
class MyMouse:
    
    def __init__(self):
        self.my_mouse = PyMouse()

    def move_to(self, x, y):
        self.my_mouse.move(x, y)
```

Here, I can not rename `self.my_mouse`.

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/243826/cannot-rename-variable.html

**Comment by zooba** [comment]
This works in master:
![image](https://user-images.githubusercontent.com/1693688/41671806-101536ce-746d-11e8-81be-1590c50c26c6.png)
