### ISSUE TITLE
Squiggles disappear when file is reopened

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3829]
Create new python application
Paste the following in the opened editor:
```
class MyClass:
    pass

m = MyClasse()
```
Wait for colorization/squiggles to appear under `MyClasse`
Save and close
Reopen file from solution explorer
Result: colorization but no squiggles

You might also run into a buffer content mismatch assert, but I don't have reproduceable steps for that.

**Comment by zooba** [comment]
I suspect this may not repro now that we close documents properly. Reopening should trigger a new analysis, which will refresh the squiggles.
