### ISSUE TITLE
Request to coordinate releases of CPython pdbs with Windows binary releases.

### ISSUE THREAD

**Issue by kraigb** [Microsoft/PTVS#3831]
Customer request moved from https://github.com/MicrosoftDocs/visualstudio-docs/issues/612

> Could microsoft work with CPython people to ensure that the pdb's are published on their ftp site at the time of the windows binary releases.

**Comment by zooba** [comment]
(@gmonkman posted the original comment, and probably wants to see the reply)

CPython pdbs are now included with the CPython installer. If you install via Visual Studio then we include them by default, but to add them manually select "Custom install" and then the "Download debug symbols" on the second page.
