### ISSUE TITLE
Colorization mixup after pasting XML into python file

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3832]
This occurred after open a XML file in the editor. Copied the contents, pasted into the .py file (anywhere at). Then hit undo. Then selected an bunch of lines and hit comment out.
![image](https://user-images.githubusercontent.com/3840081/37112098-6993a628-21f6-11e8-923a-3067f2dc2a48.png)

**Comment by karthiknadig** [comment]
This is the XML I used: https://msdn.microsoft.com/en-us/library/ms762271(v=vs.85).aspx

**Comment by zooba** [comment]
This is broken analysis - it always takes a few seconds to catch up with the colors anyway (you'll notice that the colors that remain are classes/methods/modules, which are done in the second pass).

We should probably make comment colours override all other ones as a quick fix, but we also need to investigate why analysis broke.

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/211632/%E5%A4%A7%E9%87%8F%E5%88%A0%E9%99%A4%E6%88%96%E6%B7%BB%E5%8A%A0%E4%BB%A3%E7%A0%81%E4%BD%BF%E5%BE%97%E9%83%A8%E5%88%86%E4%BB%A3%E7%A0%81%E7%9A%84%E5%85%B3%E9%94%AE%E5%AD%97%E5%8F%98%E7%99%BD.html

**Comment by zooba** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/214946/python-syntax-highlighting-randomly-breaks.html

**Comment by karthiknadig** [comment]
The colorization mix-up is fixed but the colorization stops at the line where XML was pasted. See issue #3959
