### ISSUE TITLE
15.6 broke mixed mode debugging. 

### ISSUE THREAD

**Issue by LazyDodo** [Microsoft/PTVS#3841]
I'm using hosted mixed mode environment (ie my hosting executable is not python.exe) when starting the process with F5 i now get a popup saying. 

```
Unable to start debugging. Check your debugger settings by opening 
project properties and navigating to 
'Configuration Properties-->Debugging'
```

the issue is, there's not a whole lot of settings there, i tried changing the target path from $(TargetPath) to the full path to my binary, but that didn't change anything.

![proppages](https://user-images.githubusercontent.com/1330470/37167039-faa08cc2-22bd-11e8-81d9-b87955fed7d2.png)

Repro case: (this is going to be a 'tiny' bit painful, we tried making building as easy as possible, but blender is a big project)
1) Build blender from source with vs2017.6, there's a guide available [here ](https://wiki.blender.org/index.php/Dev:Doc/Building_Blender/Windows) to cut down on the build time, you could generate project files using `make.bat lite 2017 x64 nobuild` which cuts most of the optional components out of blender. 
2) Apply [D3039](https://developer.blender.org/D3039)
3) Change the debugger to 'Python/Native Debugging'
4) hit f5.

edit: Just to clarify, this scenario used to work on 15.5 , attaching to a running instance still works in 15.6, but it be real convenient if launching with f5 worked again.

**Comment by zooba** [comment]
The "good" news is that this repros even with a regular console application, so it's nothing to do with Blender itself.

@huguesv Candidate for 15.6 servicing?

**Comment by huguesv** [comment]
I'd say yes.

**Comment by zooba** [comment]
This is caused by #3790. Because there has been no change in the VSIX version, the old package is still being installed even though the contents have been updated. We should be able to rev just that number and get it into the next build easily enough.
