### ISSUE TITLE
WSL extension not working with Visual Studio 15.6.1

### ISSUE THREAD

**Issue by ccarlsonpb** [Microsoft/PTVS#3848]
Just updated Visual Studio, WSL Launcher is no longer an option under "launch mode" in the project configuration. Tried reinstalling the extension and it says "This extension is already installed to all applicable products." Explicitly removed and reinstalled it, still nothing. I understand it's an experimental extension but I see no mention of this in the release notes so I assume it's a bug and not dropped support.

**Comment by zooba** [comment]
It was actually never supported, so technically we didn't drop anything :)

Are you still installing the VSIX from the blog post? It's likely that some dependencies changed and that particular build (which was for 15.4 Preview, IIRC) can't load any more. I've attached a more recent build below that might work better for you (you'll need to remove the `.zip` extension, don't extract it - GitHub won't upload `vsix` files).

[Microsoft.PythonTools.Wsl.VS2017.vsix.zip](https://github.com/Microsoft/PTVS/files/1797799/Microsoft.PythonTools.Wsl.VS2017.vsix.zip) (for Visual Studio 15.6)

**Comment by ccarlsonpb** [comment]
Yes I still had that file. Thank you for the updated one. Is there documentation for how I could build PTVS myself? I looked into it before but couldn't figure out the process.

**Comment by zooba** [comment]
There are a few pages on our [wiki](https://github.com/Microsoft/PTVS/wiki), but that's about it (then again, we've used it to onboard new internal developers, so I guess it's sufficient?)

If you're most interested in the WSL component, that should build and install on its own without needing to build everything else.
