### ISSUE TITLE
No completion for abc in editor (works in REPL)

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#3857]
```
import abc
abc.
```

![image](https://user-images.githubusercontent.com/12820357/37235354-d05c284a-23b2-11e8-8ce3-998d303fca6c.png)

![image](https://user-images.githubusercontent.com/12820357/37235360-dd4b7dee-23b2-11e8-9e63-794423572348.png)

**Comment by zooba** [comment]
We have one issue for all these sorts of problems, as they tend to have a common cause. Search for “library x” and you should find it.

**Comment by zooba** [comment]
Then again, looking at that first screenshot, you didn't get the module colors either. So perhaps something else failed rather than the import analysis?

**Comment by huguesv** [comment]
@MikhailArkhipov  do you still see this issue? Was it just timing out? If so, pressing ctrl+space should eventually get you completions.

**Comment by MikhailArkhipov** [comment]
OK. Works now in VSC so closing.
