### ISSUE TITLE
Signature display inconsistent with `range`

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#3869]
Type `range(c, 1, `

Hover over `range`
![image](https://user-images.githubusercontent.com/12820357/37359352-97643186-26aa-11e8-9d6e-2581a69b6780.png)

Place cursor after `c` and hit Ctrl+Shift_Space
![image](https://user-images.githubusercontent.com/12820357/37359428-cc3a198e-26aa-11e8-9a18-360841d5e284.png)

Expected signature `range(start, stop, ...)`. Almost works in VSC language server, just picks short signature.

![image](https://user-images.githubusercontent.com/12820357/37359507-04eadf5c-26ab-11e8-92dd-8dad070449a1.png)

May relate to https://github.com/Microsoft/PTVS/issues/3868

**Comment by zooba** [comment]
I think for this one we need a heuristic for when to prefer the class docstring vs. the `__init__` docstring.

**Comment by MikhailArkhipov** [comment]
Yes. In completion and hover I now have

![image](https://user-images.githubusercontent.com/12820357/38433082-73acfd9a-397e-11e8-8e23-691ab628379f.png)

but in signature help

![image](https://user-images.githubusercontent.com/12820357/38433110-861317e4-397e-11e8-82fc-95339369492a.png)

I can look into this.

**Comment by MikhailArkhipov** [comment]
I have solution, but need to discuss it more

![image](https://user-images.githubusercontent.com/12820357/38448307-41d20f88-39b8-11e8-9f38-7aa442e96c00.png)
