### ISSUE TITLE
Visual Studio Bug Reporting

### ISSUE THREAD

**Issue by GrantNieddu** [Microsoft/PTVS#3877]
I was working in VS and received this error.
The error told me to share to this link.

`
  File "C:\Users\SparkedOne\.vscode\extensions\ms-python.python-2018.2.1\pythonFiles\experimental\ptvsd_launcher.py", line 76, in <module>
    import ptvsd
ModuleNotFoundError: No module named 'ptvsd'`

**Comment by huguesv** [comment]
Based on that path it looks like you are using Visual Studio Code?

You've probably selected one of the Python Experimental configurations, which currently require manual install of ptvsd alpha release `pip install ptvsd --pre` into your environment.

See https://blogs.msdn.microsoft.com/pythonengineering/2018/03/08/python-in-visual-studio-code-feb-2018-release/ for details on the experimental debugger.

If you need more help, I would recommend asking at https://github.com/Microsoft/vscode-python/issues

If I misread this and you are really using Visual Studio (not Visual Studio Code), then it may be that your virtual environment is invalid and needs to be recreated. Or perhaps you're on Visual Studio Preview, have enabled experimental debugger and need to install ptvsd alpha using the same command mentioned above.

Hope this helps!
