### ISSUE TITLE
python installation is failing using webpicmd.exe in azure webrole

### ISSUE THREAD

**Issue by vvkrishna9** [Microsoft/PTVS#3888]
WebPiCmd Verbose: 0 : Executing command: "C:\Program Files\Microsoft\Web Platform Installer\WebpiCmd-x64.exe" /Install /Log:F:\sitesroot\0\webpi.log /AcceptEula /Feeds:https://www.microsoft.com/web/webpi/5.0/webproductlist.xml /Products:Python276 
    DateTime=2018-03-14T19:12:38.6523337Z
WebPiCmd Information: 0 : Successfully loaded primary feed: https://go.microsoft.com/?linkid=9842185
    DateTime=2018-03-14T19:12:44.5621078Z
WebPiCmd Error: 0 : Failed to Load feed: https://www.microsoft.com/web/webpi/5.0/webproductlist.xml
    DateTime=2018-03-14T19:12:50.8207436Z
WebPiCmd Error: 0 : An item with the same key has already been added.
    DateTime=2018-03-14T19:12:50.8207436Z
WebPiCmd Start: 0 : The following software is going to be installed:
    DateTime=2018-03-14T19:12:51.3043913Z
WebPiCmd Information: 0 : EULA: 'Python Installer', which is owned by 'Microsoft's Python Tools Team', will be downloaded from 'http://go.microsoft.com/fwlink/?LinkID=397537'.
    DateTime=2018-03-14T19:12:51.3043913Z
WebPiCmd Information: 0 : The license agreement to 'Python Installer' may be included with the software. 
You are responsible for and must separately locate, read and accept these license terms.
    DateTime=2018-03-14T19:12:51.3043913Z
WebPiCmd Information: 0 : EULA: 'Python 2.7.6 (32-bit)', which is owned by 'Python Software Foundation', will be downloaded from 'https://www.python.org/ftp/python/2.7.6/python-2.7.6.msi'.
    DateTime=2018-03-14T19:12:51.3043913Z
WebPiCmd Information: 0 : The license agreement to 'Python 2.7.6 (32-bit)' is available at 'http://docs.python.org/license.html'.
    DateTime=2018-03-14T19:12:51.3043913Z
WebPiCmd Stop: 0 : Accepted EULA.
    DateTime=2018-03-14T19:12:51.3043913Z
WebPiCmd Start: 0 : Starting Installation
    DateTime=2018-03-14T19:12:51.3341562Z
WebPiCmd Information: 0 : Started downloading products...
    DateTime=2018-03-14T19:12:51.4122768Z
WebPiCmd Information: 0 : Started downloading: 'Python Installer'
    DateTime=2018-03-14T19:12:51.5714019Z
WebPiCmd Information: 0 : Downloaded: 'Python Installer'
    DateTime=2018-03-14T19:12:52.7044874Z
WebPiCmd Information: 0 : Install completed (Failure): 'Python Installer'
    DateTime=2018-03-14T19:12:52.7239435Z
WebPiCmd Verbose: 0 : Install completed (Failure): 'PythonInstaller'
    DateTime=2018-03-14T19:12:52.7239435Z
WebPiCmd Error: 0 : PythonInstaller : Failed.
Downloaded file failed signature verification and may have been tampered with
    DateTime=2018-03-14T19:12:52.7358386Z
WebPiCmd Error: 0 : DependencyFailed : Python 2.7.6 (32-bit)
    DateTime=2018-03-14T19:12:52.7530933Z
WebPiCmd Information: 0 : 
    DateTime=2018-03-14T19:12:53.3906790Z
WebPiCmd Start: 0 : Verifying successful installation...
    DateTime=2018-03-14T19:12:53.3906790Z
WebPiCmd Information: 0 : Python Installer                                   False
    DateTime=2018-03-14T19:12:53.3906790Z
WebPiCmd Information: 0 : Python 2.7.6 (32-bit)                              False
    DateTime=2018-03-14T19:12:53.3906790Z
WebPiCmd Verbose: 0 : Download count: 0 Mb, 1 sec
    DateTime=2018-03-14T19:12:53.4070189Z
WebPiCmd Verbose: 0 : Installation count: 0 Mb, 0 sec
    DateTime=2018-03-14T19:12:53.4070189Z
WebPiCmd Verbose: 0 : Products            , Down. Size, Install Time, Down. Time, Install Size, Log Size  
    DateTime=2018-03-14T19:12:53.4070189Z
WebPiCmd Verbose: 0 : PythonInstaller     , 0         , 0         , 1         , 0         , 0         
    DateTime=2018-03-14T19:12:53.4070189Z
WebPiCmd Verbose: 0 : Total (download size/install time): 0 Mb, 0 sec
    DateTime=2018-03-14T19:12:53.4070189Z
WebPiCmd Error: 0 : Install of Products: FAILURE
    DateTime=2018-03-14T19:12:53.4070189Z
WebPiCmd Information: 0 : 
    DateTime=2018-03-14T19:13:38.3529557Z

**Comment by vvkrishna9** [comment]
Failed to Load feed: https://www.microsoft.com/web/webpi/5.0/webproductlist.xml why feed is failing to load

**Comment by huguesv** [comment]
Looks like it's because the link to `installer.ps1` (http://go.microsoft.com/fwlink/?LinkID=397537) points to codeplex, which has been archived, so the install script can't be downloaded.

From the feed at https://www.microsoft.com/web/webpi/5.0/webproductlist.xml
```
<installers>
<installer>
<id>1</id>
<languageId>en</languageId>
<installerFile>
<fileSize>4</fileSize>
<installerURL>http://go.microsoft.com/fwlink/?LinkID=397537</installerURL>
<sha1>e94e20e32f9e3caac4d5257a55d93567b531e8c8</sha1>
</installerFile>
<installCommands>
<cmdLine>
<exe>%comspec%</exe>
<commandLineArguments>
/C "mkdir "%CommonProgramFiles%\microsoft shared\Python Tools for Azure""
</commandLineArguments>
<ignoreExitCode>true</ignoreExitCode>
</cmdLine>
<cmdLine>
<exe>%comspec%</exe>
<commandLineArguments>
/C "copy /y "%InstallerFile%" "%CommonProgramFiles%\microsoft shared\Python Tools for Azure\installer.ps1""
</commandLineArguments>
<ignoreExitCode>false</ignoreExitCode>
</cmdLine>
<cmdLine>
<exe>
%systemroot%\System32\WindowsPowerShell\v1.0\powershell.exe
</exe>
<commandLineArguments>
-ExecutionPolicy RemoteSigned -NoProfile -File "%CommonProgramFiles%\microsoft shared\Python Tools for Azure\installer.ps1" Installer=1.0.0
</commandLineArguments>
<ignoreExitCode>false</ignoreExitCode>
</cmdLine>
</installCommands>
</installer>
</installers>
```

Recommendation: Remove the WebPI reference and write your own install scripts.

We've already moved away from WebPI in VS 2017. We now use NuGet to install Python and put the install script in your project so you can customize it.

The NuGet feed has the latest available Python releases, unlike WebPI which hasn't been updated in over 3 years.

There's documentation here that guides through customizing Python cloud services. That should you get started if you're still on Visual Studio 2015:
https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-python-ptvs
