### ISSUE TITLE
Completion DB refreshing stopped at 'Analzing standard library'

### ISSUE THREAD

**Issue by PterosDiacos** [Microsoft/PTVS#3890]
I have VS Community 15.6.2 and Anaconda 5.1.0 installed on win-10-64bit.
Right after I installed VS auto-completion was working, but at the same time I noticed the Python Environments Panel>IntelliSense prompted that something was disabled (I forgot what)
and to make full use of IntelliSense it needed to be activated. So I did and it showed that the DB needed to be refreshed.
The trouble came ever after. Every time I refreshed the DB, it stopped as 'Analyzing standard library'.
Solutions I've tried include
  i) reinstall the python environment
 ii) delete ."..\AppData\python tools" folder
iii) reinstall python tools for VS
But none of them worked.
Could anyone help me on this?

**Comment by Yezoxant** [comment]
I experienced the same issue, maybe look at my thread #3884. short version i enabled the new intellisense under: Tools > python > experimental.

**Comment by PterosDiacos** [comment]
@Yezoxant  Yes, after enabling 'New intelliSense' in 'tools>opiton>python>experimental' page, I got the auto-completion back.

**Comment by zooba** [comment]
This should be resolved with 15.6.3, which was released today.
