### ISSUE TITLE
Error use ipython in ptvs: cannot import name 'ShellChannel' 

### ISSUE THREAD

**Issue by mbfeng88515** [Microsoft/PTVS#391]
I tried to use ipython in ptvs according to the instructions https://pytools.codeplex.com/wikipage?title=Using%20IPython%20with%20PTVS 

Errors: 
The Python REPL process has exited 
Error using selected REPL back-end: 
cannot import name 'ShellChannel' 
Using standard backend instead 

Is that I should install some packages? (I tried both python 2.7 and 3.4, both VS2010 and 2013, all combinations give the same message)

**Comment by zooba** [comment]
You'll need to upgrade to the latest PTVS build, or downgrade IPython to 2.4 (you can do this by installing `ipython<3`). When they increased to v3 they made some changes that broke our support, and it took until PTVS 2.2 RC for us to catch up.
