### ISSUE TITLE
[loc][Query][VS_PythonTools] Localizability of "0; "CondaExtensionCondaInstallFrom"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/PTVS#3912]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Run command: conda install {0}

File Name:
localize\ENU\Microsoft.PythonTools.Common.dll

Resource ID:
0; "CondaExtensionCondaInstallFrom"

Query:
Is it a description or a command?

**Comment by huguesv** [comment]
"Run command:" is a description and should be translated.
"conda install {0}" is a command and should NOT be translated.

**Comment by huguesv** [comment]
Same for PipExtensionPipInstallFrom, only "Run command:" part should be translated.

They're both incorrectly translated in PR https://github.com/Microsoft/PTVS/pull/3913 and https://github.com/Microsoft/PTVS/pull/3911

**Comment by zooba** [comment]
@huguesv We should probably add comments to the resource files for these, so that we don't lose the clarification in the future.
