### ISSUE TITLE
Support comment type hints

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#3917]
https://www.python.org/dev/peps/pep-0484/
https://www.python.org/dev/peps/pep-0526/

```
PEP_526_style: str = "hello world"
captain: str  # Note: no initial value!
PEP_484_style = SOMETHING # type: str

 
PEP_484_style.
PEP_526_style.upper()
captain.upper()
```

Type declaration is not recognized as string.

![image](https://user-images.githubusercontent.com/12820357/37684756-45ab901a-2c4e-11e8-851a-c36796548b77.png)

Jedi

![image](https://user-images.githubusercontent.com/12820357/37684806-6cf9af4e-2c4e-11e8-927a-99879058cd2f.png)

Related: https://github.com/Microsoft/PTVS/issues/3674

**Comment by zooba** [comment]
I renamed the issue. We currently only support real annotations, not comments, and we don't show anything for undefined variables such as `captain`.

**Comment by MikhailArkhipov** [comment]
Related: https://github.com/Microsoft/PTVS/issues/3608

**Comment by huguesv** [comment]
They're used by typeshed. Example from threading.pyi:
```
class Thread:
    name = ...  # type: str
    ident = ...  # type: Optional[int]
    daemon = ...  # type: bool
```

**Comment by MikhailArkhipov** [comment]
Some, but not all. It is interesting question if typeshed repo owners will accept contrib changing

    encoding = ...  # type: str
    errors = ...  # type: Optional[str]
    newlines = ...  # type: Union[str, Tuple[str, ...], None]

to what we can handle. Or the reply is going to be 'well, handle PEP' ;-)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/7
