### ISSUE TITLE
Colorization bug after pasting XML

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#3959]
Colorization bug after pasting XML into py file and undoing it:
![image](https://user-images.githubusercontent.com/3840081/37931759-89a1caee-30fb-11e8-9052-fbd2d70c1757.png)

Any modification only seems to fix the line immediately after:
![image](https://user-images.githubusercontent.com/3840081/37931869-ceac1482-30fb-11e8-812a-c1eda21727d8.png)

Closing the file an reopening it fixes the colorization.

**Comment by huguesv** [comment]
This looks difficult to repro (haven't seen it in several attempts).

**Comment by AmosHason** [comment]
Is this under investigation? It occurs to me way too much. It's not just about pasting an XML, but pasting in general. Also occurs while in debug.
