### ISSUE TITLE
Django debug throws error

### ISSUE THREAD

**Issue by lzantal** [Microsoft/PTVS#3965]
Hi there,

After updating VSCode to the latest version I can not debug my django projects anymore.
I get the following error:
Traceback (most recent call last):
  File "/Users/laszlo/.vscode/extensions/ms-python.python-2018.2.1/pythonFiles/experimental/ptvsd_launcher.py", line 76, in <module>
    import ptvsd
ModuleNotFoundError: No module named 'ptvsd'

If I install the ptvsd package it doesn't run at all. It starts but then stops without any error message.

Tried using the none Experimental launch file and then I get an Exception in sre_parse.py module
```
def __getitem__(self, index):
        if isinstance(index, slice):
            return SubPattern(self.pattern, self.data[index])
        return self.data[index]
```
```
IndexError, list index out of range
```

Laszlo

**Comment by huguesv** [comment]
If you're installing ptvsd for use with experimental configuration, you'll need to `pip install ptvsd --pre` to get the correct version.

I'm not sure why it doesn't work for the non-experimental configuration though.

Our teammates at https://github.com/Microsoft/vscode-python should be able to help you out.

**Comment by danielisrunning** [comment]
I have the same issue, when I run debug without experimental, on a python 3.6 project, I get the exact same error of
`IndexError, list index out of range`
in the same module. Debug stops and no way to run it further while "uncaught exceptions" is activated.
