### ISSUE TITLE
can't PTVS complete function names imported by from import *?

### ISSUE THREAD

**Issue by NewUserHa** [Microsoft/PTVS#3967]
Microsoft Visual Studio Community 2017 
Version 15.6.1
VisualStudio.15.Release/15.6.1+27428.2002
Python   15.6.18045.1

it's a nice feature I think.

**Comment by MikhailArkhipov** [comment]
Jedi can do that. We need this to PVSC as well.

**Comment by huguesv** [comment]
It's working fine for me, in both 15.6 and latest.

![image](https://user-images.githubusercontent.com/1696845/38046931-bd4d4b5e-3275-11e8-8c33-df68cd5736b3.png)

**Comment by huguesv** [comment]
@NewUserHa @MikhailArkhipov does it eventually work if you give it some time? It may not have completed analysis and is timing out.

**Comment by NewUserHa** [comment]
no, I waited 60 seconds, no difference

**Comment by zooba** [comment]
@NewUserHa What package are you importing from?

**Comment by NewUserHa** [comment]
@zooba 
![12345678](https://user-images.githubusercontent.com/32261870/38204455-9b937f38-36d5-11e8-8f38-3fd5c4f39ec4.gif)

**Comment by huguesv** [comment]
Thanks for the details @NewUserHa. It appears that this only works within a project right now.

**Comment by huguesv** [comment]
Similar to https://github.com/Microsoft/PTVS/issues/3891

**Comment by NewUserHa** [comment]
similar? but in the gif above, the a is not underlined like in #3891

**Comment by MikhailArkhipov** [comment]
It works for me now in VSC, we have test for that.

**Comment by MikhailArkhipov** [comment]
@NewUserHa - when VS update ships. Latest is in the preview channel https://www.visualstudio.com/vs/preview/

**Comment by zooba** [comment]
I had to fix an issue with empty completion items in `random` (see #4172), but otherwise can confirm that this works.
