### ISSUE TITLE
Is is possible to integrate PowerBI with Python, if yes then how?

### ISSUE THREAD

**Issue by ankit1393** [Microsoft/PTVS#3968]

**Comment by huguesv** [comment]
Please have a look at https://powerbi.microsoft.com/en-us/support/ and https://community.powerbi.com/

From the community forum, I found https://community.powerbi.com/t5/Developer/Access-Power-BI-API-with-Python/m-p/189165/highlight/true#M6015 which might help you?

**Comment by tusharvaja** [comment]
@ankit1393  - this is supported in preview now. chekout  https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2018-feature-summary/#python
