### ISSUE TITLE
conda update failed

### ISSUE THREAD

**Issue by davidshen84** [Microsoft/PTVS#3971]
conda --version

    conda 4.3.27

    python --version

    Python 3.6.2 :: Anaconda, Inc.

I installed Anaconda package when I install the `VS 2017` package. As VS updates only address updates to VS itself only, so I think I should manually update my conda environment.

I tried to execute this command un privileged environment.

    conda update --prefix "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64" anaconda -v

Here's the response

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64  (writable)
    default environment : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64
       envs directories : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs
                          C:\Users\DSHEN7\AppData\Local\conda\conda\envs
                          C:\Users\DSHEN7\.conda\envs
          package cache : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\pkgs
                          C:\Users\DSHEN7\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\User1\.condarc
             netrc file : C:\Users\User1/.netrc
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : True
```

I want to know:

1. Is the above sympton an error?
2. What is the recommended way to update the conda environment which is installed by VS installer.

**Comment by huguesv** [comment]
I've been updating conda successfully using our package manager UI. That way I don't have to remember the commands and paths to use. Also I'm biased since I worked on that support ;)

First enable conda support in tools/options/python/experimental, since it's off by default in 15.6.

![image](https://user-images.githubusercontent.com/1696845/38102542-6ec43434-3338-11e8-87e7-2efb20728fa4.png)

Restart VS after changing the settings.

View->Other Windows->Python Environments

Select Anaconda, then Packages (Conda) from combo box, then conda from package list. Wait for it to fetch the latest version of packages and you'll see an UP arrow appear next to conda.

Click the UP arrow and you'll be prompted to elevate.

![image](https://user-images.githubusercontent.com/1696845/38102663-c0a9412c-3338-11e8-83d6-7b7bf4f4234d.png)

**Comment by davidshen84** [comment]
So there's a Python environment management UI inside VS...not very intuitive, but good to know :)

I think this resolved my issue. Thanks! 👍 

BTW, it looks like this package management UI does not have an `update all` button. It would be really nice to have one.

**Comment by davidshen84** [comment]
- There're too many *windows* in the `Other Windows` section.

I think the `Other Windows` section needs a total rework.

- Given that VS is not a fully functional Python development environment, who would think there's a Python package management system inside VS?

I mean, if you ask me to find that menu item in VS, I would certainly find it. But how users would come up with that idea to look for a Python environment inside VS at the first place?
