### ISSUE TITLE
Errors in file when opened out of project, but no errors when in project

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#3973]
Set Python 3.6 as your global default
Create new project
Copy Python 3.6's typing.py and add it to the project
Open the copy from your project
Open the original at Python36/lib/typing.py

Result: No errors for the copy in your project, but several errors for the original.

For screenshot, I renamed the one in the project to typingcopy.py.

![image](https://user-images.githubusercontent.com/1696845/38111555-17be7c6e-3354-11e8-89c6-57cd7e68c95a.png)

I don't know if it would make a difference, but I have PR https://github.com/Microsoft/PTVS/pull/3764 applied to latest master branch.

**Comment by zooba** [comment]
@huguesv Are you saying thot Python 2.7 is your global default and your project was set to (say) 3.6? This is the expected behaviour right now (we have #1042 to improve it)

**Comment by huguesv** [comment]
Global default was 3.6.

**Comment by huguesv** [comment]
Fixed by https://github.com/Microsoft/PTVS/pull/4091
