### ISSUE TITLE
Clarification around threads

### ISSUE THREAD

**Issue by pauldotknopf** [Microsoft/PTVS#3975]
I am using [PyOtherSide](https://github.com/thp/pyotherside/) as an embedded interpretor in a Qt app.

There are two ways to call python.

**call_sync**

https://github.com/thp/pyotherside/blob/cf8a0f8d269ed0cc10f736e60f67c0b43808da17/src/qpython.cpp#L331

This calls Python code directly on the UI thread of Qt.

**call**

https://github.com/thp/pyotherside/blob/cf8a0f8d269ed0cc10f736e60f67c0b43808da17/src/qpython.cpp#L317

This passes values to a single thread in the background to run python code. The thread is re-used.

**What I'm seeing**

I can run this fine, attach a debugger, and step through the code.

```python
ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))
ptvsd.wait_for_attach()
```

If I do this from the ```call_sync``` method, all my break points will get called for any method that is *also* using ```call_sync```. Any breakpoints that are expected to be triggered within a ```call``` (async) command are not hit.

If I do this from a ```call``` method, all my break points will get called for that run only. Any future calls with ```call``` will not trigger a breakpoint.

So, my options are:

* Only use ```call_sync``` and set debugger one at beginning of application.
* Only use ```call``` once during a running application. I will need to move around my ```enable_attach``` call near the code I want to debug, and I can only debug it once.

Am I missing something? Is this expected? Is there a way to get breakpoints on all threads to *just work*?

**Comment by huguesv** [comment]
Please have a look at https://github.com/Microsoft/PTVS/issues/3003. It has some details on how to register threads created outside of Python.

**Comment by huguesv** [comment]
We have a new debug engine in the 15.8 release, if you still see this problem, please open an issue at https://github.com/Microsoft/ptvsd
