### ISSUE TITLE
Mixed mode debugger and launch.vs.json.

### ISSUE THREAD

**Issue by LazyDodo** [microsoft/PTVS#3981]
Previously i have used the mixed mode debugger to debug blenders python scripts, this works great (broke in 15.6 but works again in the 15.7 previews), but it requires you to build blender from source (not an easy thing to do for many python devs)

reasons I like the mixed mode debugger.

1) I don't have to install the ptvsd module.
2) I can put a breakpoint on the very first line of python that gets executed without having to worry about ptvsd initalization and ports and connections.
3) it's really easy, switch debugger, hit f5. *works* , no settings to mess with, best thing ever!

however I like to support the following workflow for end users in visual studio:

1) File->Open->Folder
2) Select the folder the user installed blender in, get a work space.
3) Right click blender.exe in the solution explorer, debug and launch settings, 
4) Select mixed mode native/python debugger.
5) hit f5 to run.

1-3 work, in 4 sadly the mixed mode debugger is not listed.

I tried playing around with the launch.vs.json file to see if there's a way to select it but have been unsuccessful sofar.

Any hints and tips and insights on this would be appreciated.

**Comment by int19h** [comment]
Something that I think should work today, is having a dummy C++ project that is set to launch Blender executable when debugging (there is a setting in project properties there regarding which binary to run), and adding Python in the list of engines. Not as good as Open Folder, of course, but it would give you F5 at least.

**Comment by zooba** [comment]
If you select the “Python native development” option when installing, as well as full C++ support you get some extras. One of these is the Python/native debugging mode for C++ projects.

However, you should also be able to specify a Python configuration in launch.vs.json, with “interpreterPath” set to Blender and one other property that I don’t remember right now (“useNativeDebugging” maybe?) to true. I’ll look up the actual property name once I’m in the office on Monday, but that may be enough of a hint to get you started before then.

**Comment by int19h** [comment]
Wouldn't this require the binary to accept the same arguments that we normally pass to python.exe, though? I thought that the way we allow to specify additional interpreter arguments, it's additive (so you cannot remove the .py filename, for example).

**Comment by zooba** [comment]
Yes, you're right. We still need some way to suppress the script file from the launch arguments. It's going to be easiest to do that using some other configuration besides the current Python ones.
