### ISSUE TITLE
Problem debugging C++ extensions for Python x64

### ISSUE THREAD

**Issue by bitsrules** [Microsoft/PTVS#3989]
I have a problem when I try to debug my C++ extension for Python x64.

I can break in the debugger but when i step over the code it throws an exception.

![debugbreakhit](https://user-images.githubusercontent.com/33675621/38225129-5cc69c32-372e-11e8-9217-9c4ebbb1f441.PNG)

![exceptionthrow](https://user-images.githubusercontent.com/33675621/38225134-60d46b88-372e-11e8-84f7-8fafd850894e.PNG)

I followed this [guide][1] and it works when I run in the release version.
I also works in x64.

Python code:

    from itertools import islice
    from random import random
    from time import perf_counter
    
    COUNT = 500000  # Change this value depending on the speed of your computer
    DATA = list(islice(iter(lambda: (random() - 0.5) * 3.0, None), COUNT))
    
    e = 2.7182818284590452353602874713527
    
    def sinh(x):
        return (1 - (e ** (-2 * x))) / (2 * (e ** -x))
    
    def cosh(x):
        return (1 + (e ** (-2 * x))) / (2 * (e ** -x))
    
    def tanh(x):
        tanh_x = sinh(x) / cosh(x)
        return tanh_x
    
    def sequence_tanh(data):
        '''Applies the hyperbolic tangent function to map all values in
        the sequence to a value between -1.0 and 1.0.
        '''
        result = []
        for x in data:
            result.append(tanh(x))
        return result
    
    def test(fn, name):
        start = perf_counter()
        result = fn(DATA)
        duration = perf_counter() - start
        print('{} took {:.3f} seconds\n\n'.format(name, duration))
    
        for d in result:
            assert -1 <= d <=1, " incorrect values"
    
    from superfastcode import fast_tanh
    if __name__ == "__main__":
	   test(lambda d: [fast_tanh(x) for x in d], '[fast_tanh(x) for x in d]')

C++ code:

    #include <Python.h>
    #include <cmath>
    
    const double e = 2.7182818284590452353602874713527;
    
    double sinh_impl(double x) {
    	return (1 - pow(e, (-2 * x))) / (2 * pow(e, -x));
    }
    
    double cosh_impl(double x) {
    	return (1 + pow(e, (-2 * x))) / (2 * pow(e, -x));
    }
    
    PyObject* tanh_impl(PyObject *, PyObject* o) {
    	double x = PyFloat_AsDouble(o);
    	double tanh_x = sinh_impl(x) / cosh_impl(x);
    	return PyFloat_FromDouble(tanh_x);
    }
    
    static PyMethodDef superfastcode_methods[] = {
    	// The first property is the name exposed to Python, fast_tanh, the second is the C++
    	// function name that contains the implementation.
    	{ "fast_tanh", (PyCFunction)tanh_impl, METH_O, nullptr },
    
    	// Terminate the array with an object containing nulls.
    { nullptr, nullptr, 0, nullptr }
    };
    
    static PyModuleDef superfastcode_module = {
    	PyModuleDef_HEAD_INIT,
    	"superfastcode",                        // Module name to use with Python import statements
    	"Provides some functions, but faster",  // Module description
    	0,
    	superfastcode_methods                   // Structure that defines the methods of the module
    };
    
    PyMODINIT_FUNC PyInit_superfastcode() {
    	return PyModule_Create(&superfastcode_module);
    }

I am using the 64 bit version of Python 3.6, and are building the C++ code in x64 mode. Visual Studio 2017 15.6.4

I am linking with C:\Python\Python36.x64\libs\python36_d.lib and including header files from C:\Python\Python36.x64\include   
My Python interpreter is in C:\Python\Python36.x64\

I get this result when I run the release build

    [fast_tanh(x) for x in d] took 0.067 seconds

  [1]: https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio

Please also see [https://github.com/MicrosoftDocs/visualstudio-docs/issues/769](https://github.com/MicrosoftDocs/visualstudio-docs/issues/769) where I started reporting this issue and was refereed here by @kraigb

**Comment by int19h** [comment]
If your source file is .cpp rather than .c, you might need to add `extern "C"` to the definition of `tanh_impl`, to ensure that calling conventions are compatible. Can you try that and see if it helps?

**Comment by zooba** [comment]
This looks more like a mismatch between debug binaries and release headers.

The guide you've referenced is designed to always use the release binaries of Python, even if you are building a debug extension. So either you should be linking against python36.lib/python36.dll, or ignoring most of the setting changes listed in the guide and linking against python36_d.lib/python36_d.dll (the linking should be automatic once you set the paths - the choice of C runtime library will determine whether debug/release Python is used).

**Comment by huguesv** [comment]
We'll assume you figured it out.
