### ISSUE TITLE
broken environment visual studio

### ISSUE THREAD

**Issue by milo204** [Microsoft/PTVS#3990]
im trying to download numpy and tensorflow into microsoft visual studio.
Ive downloaded visual studio 2017 community, and selected the python package. Ive then gone into python environments in the hope to find pip install and then install numpy and tensorflow. However ive found an error of a 'broken environment' for python 3.6. Ive downloaded python package with visual studio so im not sure why im receiving this error. Many thanks to anyone who can help!

![capture1](https://user-images.githubusercontent.com/38040218/38250152-ff180b76-3745-11e8-956b-b7fae839ab11.JPG)

**Comment by huguesv** [comment]
We mark it as broken if we found an interpreter in the registry that doesn't exist on disk.

I assume your registry must have these, which matches the paths in your screenshot:
![image](https://user-images.githubusercontent.com/1696845/38263417-e84ea48e-3724-11e8-8f4e-3e69197a6484.png)

Can you check that python.exe exists at that location? If not, are there leftover folders / files there?

The solution might be to uninstall the Python 3.6 component using VS installer and then reinstall it.

**Comment by milo204** [comment]
Hi, thanks for you help. Uninstalling the python package and visual studio and reinstalling seemed to do the trick!
