### ISSUE TITLE
Cannot run debugger for Python 2.5. Computer has Python 2.5 and 3.6 installed.

### ISSUE THREAD

**Issue by Geoff-W** [Microsoft/PTVS#3991]
I have a server with both Python 3.6 and Python 2.5 (the AMD64 version). Python 2.5 is the scripting language for a tool I work with and so I must use that version. Python 2.5 was installed after 3.6. When only 3.6 was installed, debugging the same script worked fine.

I select Python 2.5 in VS Code, open my Python script, click the **_Debug menu > Start Debugging_** and I then get this:

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\iNTERFACEWARE\Chameleon\lib>cd "c:\Program Files (x86)\iNTERFACEWARE\Chameleon\lib" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Python25\python.exe C:\Users\Administrator\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher.py "c:\Program Files (x86)\iNTERFACEWARE\Chameleon\lib" 51242 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput "c:\Program Files (x86)\iNTERFACEWARE\Chameleon\lib\Test_SectraPACSUtilities.py" "
Traceback (most recent call last):
  File "C:\Users\Administrator\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 31, in <module>
    import visualstudio_py_debugger as vspd
  File "C:\Users\Administrator\.vscode\extensions\ms-python.python-2018.3.1\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 30, in <module>
    import ctypes
ImportError: No module named ctypes

Internal error detected. Please copy the above traceback and report at
http://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .
```

**Comment by zooba** [comment]
@int19h @DonJayamanne One of you will probably want to move this bug to the correct tracker.

However, as we no longer officially support Python 2.5, we will not be able to prioritise this very high. If you're able to figure out workarounds within the sources (e.g. conditional imports, use of `simplejson`, etc.) then we will consider pull requests.

**Comment by huguesv** [comment]
I installed Python 2.5.4 (first 32-bit, then 64-bit) from python.org. It appears only the 32-bit version has ctypes. If you can, try debugging against that one.

If you need further help with Python in Visual Studio Code, please check their support at https://github.com/Microsoft/vscode-python/issues

**Comment by int19h** [comment]
We'll track it here, but there's probably a lot more than `simplejson` in the code by now - things like set literals etc. 

https://github.com/Microsoft/ptvsd/issues/304

**Comment by huguesv** [comment]
We won't be supporting Python 2.5.
