### ISSUE TITLE
Stepping sometimes requires you to step twice, or ends up in Python's native implementation

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#4]
**Pre-requisites:**
- Mixed Mode Debugging enabled
- Debug Python 2.7 environment

**Repro script:**

``` python
import sys

sys.path.insert("d:\\src")   # Step over this line
sys.path.insert("d:\\python_src")
```

When you step over this line, the first time nothing happens.  The second time, I end up in the C implementation of PyMain -- in native code.  I've seen double stepping in other instances as well where the second step actually succeeds and ends up on the next line of python code, but I can't find a reliable repro for that, so I'm not sure what triggers it to succeed on the second step sometimes vs. ending up in the implementation of Python on the second step other times.

**Comment by zjturner** [comment]
Any particular reason this is a wontfix?

**Comment by zooba** [comment]
Same reasoning as #3
