### ISSUE TITLE
Breakpoint circle disappears

### ISSUE THREAD

**Issue by gilbertw** [Microsoft/PTVS#400]
In attach scenario with no project loaded.
Attach to a python project
Drag your file into the editor
Set a breakpoint
F5 and let the breakpoint be hit
The red circle marking the breakpoint disappears even though the breakpoint remains and will continue to be hit.

Expected
The breakpoint marker should remain in the gutter as long as the breakpoint exists

**Comment by zooba** [comment]
@int19h Is this known/fixed? We got something like this, right?

**Comment by int19h** [comment]
I've seen this before in Azure remote debugging, but very rarely, and never with a consistent repro. I haven't tried reproing with Rick's steps yet.
