### ISSUE TITLE
IntelliSense returning None types for pandas/requests library

### ISSUE THREAD

**Issue by qubitron** [Microsoft/PTVS#4001]
In the following source file of this project:
https://github.com/qubitron/stackoverflow-django/blob/master/stackoverflow.py

VS Code (using the Jedi library) is able to give return types for pandas.read_csv and requests library:
![image](https://user-images.githubusercontent.com/17804393/38380337-3f8176fc-38b8-11e8-8fad-f5fd9469415e.png)
![image](https://user-images.githubusercontent.com/17804393/38380352-4dcc119a-38b8-11e8-825f-030652de366a.png)

In Visual Studio it says "None" for these types:
![image](https://user-images.githubusercontent.com/17804393/38380430-88eb1096-38b8-11e8-9723-b446fa28b7a5.png)
![image](https://user-images.githubusercontent.com/17804393/38380445-9b3a888a-38b8-11e8-9894-9a6b8aa1caf4.png)

Using Python extension version 15.7.18083.1

**Comment by zooba** [comment]
Dup of #3046
