### ISSUE TITLE
AF opening certain file

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#4023]
Add to Python solution and open the attached file

![image](https://user-images.githubusercontent.com/12820357/38527135-0f6a5886-3c0e-11e8-8435-8f5c4e11cbd3.png)
[suppress.py.txt](https://github.com/Microsoft/PTVS/files/1892218/suppress.py.txt)

**Comment by MikhailArkhipov** [comment]
What happens here is there are TWO files that have `class type`. 

![image](https://user-images.githubusercontent.com/12820357/38572623-6f56827a-3ca8-11e8-9b9e-94929e975060.png)

**Comment by zooba** [comment]
This no longer repros.
