### ISSUE TITLE
Editing django run/debug server arguments breaks launch

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4025]
Create django project.
In project settings, debug, edit the debug server command arguments by adding a space before `--settings`.
Save project.
Note: Now the .pyproj file contains `PythonDebugWebServerCommandArguments`  property definition (it doesn't until you edit the project settings).
F5 to debug

Result: `ModuleNotFoundError`

Workaround: Edit the .pyproj and replace `$(DjangoSettingsModule)` in `<PythonDebugWebServerCommandArguments>` with its actual value.

Also reported at https://developercommunity.visualstudio.com/content/problem/224142/djangowebproject-runserver-command-fails.html

**Comment by zooba** [comment]
That property should be in the template by default (and `$(MSBuildProjectName)` isn't necessarily safe - it needs to be importable)

**Comment by karthiknadig** [comment]
I had missed this bit of info. The project XML seems to have `DjangoSettingsModule` defined but in a different property group below the one where `PythonDebugWebServerCommandArguments` gets defined.  May be we should change the set property to add it to the end of the property group that contains `DjangoSettingsModule`.
