### ISSUE TITLE
Inconsistencies in Django project template urlpattern regex

### ISSUE THREAD

**Issue by kraigb** [Microsoft/PTVS#4035]
Perhaps this is intentional, but the Django App Project template's urls.py (for the Django project) has the following: 

```
url(r'^contact$', app.views.contact, name='contact'),
url(r'^about', app.views.about, name='about'),  
# ...
url(r'^logout$', ...)
```

Is there a reason any r'^about' isn't r'^about$'?

Similarly, in the Polls Django Web Project template, there's an added r'^seed':

```
url(r'^about', app.views.about, name='about'),
url(r'^seed', app.views.seed, name='seed'),
```

Should that be r'^seed$'? As it stands, requests to /abouttime and /seedsareinterestingthings are picked up by these patterns.

I'm happy to make a PR if they should be changed for consistency.

**Comment by huguesv** [comment]
Looks like oversight. We'll take your PR if you have time to fix it. Thanks!

**Comment by kraigb** [comment]
Done, #4038
