### ISSUE TITLE
Start debugging times out on Anaconda

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4052]

**Comment by karthiknadig** [comment]
It looks like the 5 second time out for connection we have is too short especially so on slower machines.

**Comment by zooba** [comment]
@karthiknadig I wonder if there are any other signals we could use to keep waiting? Can the OS tell us if the process is running even if Python isn't fully initialized yet? Can we read process times and see if CPU time is changing?

Probably most important is to collect signal on how long this step is taking for people. I already mentioned that on your PRs. But if we can detect a hung or silently-dead process distinct from a slow-but-working process, that might help tidy this up.
