### ISSUE TITLE
Interactive window images do not zoom

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#406]
Start an IPython interactive window and plot something. Then zoom in and out in the editor - the image stays the same size.

**Comment by int19h** [comment]
Worse yet, there's no resize handle, so there isn't even a workaround.

**Comment by zooba** [comment]
All the required pieces are there, but the events are not bubbling into the interactive window properly.

Looking at ZoomableInlineAdornment:
* MouseRightButtonDown makes it but two context menus open and you can't see the adornment one
* PreviewMouseLeftButtonDown arrives but MyContent is never focused
* GotFocus and LostFocus never arrive
* Other events require GotFocus to arrive, so not sure whether they make it

I'd guess the problem is just that the adornment is not allowed to get focus. Hard to tell why that's the case and I can't tweak enough properties in the debugger to make it work, but the rest of the functionality seems to be there.
