### ISSUE TITLE
Bracket highlighting incorrect

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4072]
When you have more than one level, it matches the close bracket with the incorrect open bracket.

Applies to parentheses, curly braces, square brackets.

![image](https://user-images.githubusercontent.com/1696845/38899355-6e3e211e-424c-11e8-8ec3-0c61c52a4b4e.png)

Also reported on developer community at https://developercommunity.visualstudio.com/content/problem/235221/python括号匹对不正确.html

**Comment by zooba** [comment]
Guessing this is an off-by-one error with how we use `GetTokensForwardsFromPoint` vs. `GetTokensInReverseFromPosition` (probably one includes the start point and the other doesn't)

**Comment by seva0stapenko** [comment]
Any chance to get it fixed? 15.9 is out, but no fix for this one.

**Comment by RaymonGulati1** [comment]
@seva0stapenko, this has been fixed and should be updated in 16.2
