### ISSUE TITLE
Django app template should put index.html in a subfolder of templates

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4079]
Instead of this structure:
![image](https://user-images.githubusercontent.com/1696845/38963719-2d9538be-4328-11e8-812d-62bc1e8475dc.png)

We should do this:
![image](https://user-images.githubusercontent.com/1696845/38963738-4453fcde-4328-11e8-9178-50b15d77c535.png)

Note that `django startapp myapp` doesn't create a templates folder, so we are free to change it, as we are already different from command line tool here.

To understand why, see _Template namespacing_ note in https://docs.djangoproject.com/en/2.0/intro/tutorial03/#write-views-that-actually-do-something

Summary is that on multi apps, you need to namespace in order to guarantee loading the correct template.

**Comment by kraigb** [comment]
Check the Django Web Project and Polls Django Web Project templates as well, because they each just create a "templates/app" folder, rather than "templates/{project_name}".

**Comment by huguesv** [comment]
The project templates are correct. Under templates folder you want the app name, not the project name (and the app name is 'app' for the project templates).
