### ISSUE TITLE
detect active Python environment in own VSIX extension

### ISSUE THREAD

**Issue by mseise123** [Microsoft/PTVS#4081]
I want to programmatically (own VSIX extension) detect the current Python interpreter (Path & Exe, typically conda environments). So far I use the "InterpreterID" property from the project and find it in the registry 
Registry.CurrentUser.OpenSubKey("software\\Python\\VisualStudio\\"+InterpreterID+"\\InstallPath"))
That does not work for projects with the default interpreter. Is there a simpler way?

As a second step I want to copy the active python environment to an (automatically) created solution & project. Which properties need to be copied from the original project file?

**Comment by huguesv** [comment]
The short answer is our public API doesn't have a simple way to do what you are after. As you found out, you can get the interpreter id, but that requires some reverse engineering to do anything with it. Looking at the code, there are TODOs (in InterpretersNodeProperties.cs) to provide more interpreter information via automation API.

If you want to see details on how the environments are discovered and ids are generated, see the VSInterpreters project. It's not necessarily a good idea to depend on these details (we may break you later). The provider classes do the discovery and create the ids. There are providers for "Global" (registry search), "IronPython", "CondaEnv" (conda list command), MSBuild (virtual env defined in .pyproj).

For the second step, I don't think we have any API, not even a private one, to do this from the outside. Maybe if you text edit the .pyproj after it's generated... In that case, create a project with a reference to one from each type of providers, save and look at the .pyproj and you'll know what you need to generate.

**Comment by mseise123** [comment]
Thank you for the information.

**Comment by int19h** [comment]
Didn't we have some way of getting this information via MSBuild tasks? For stuff like running custom commands using the current active environment... but it can also be invoked programmatically just to get the requisite output group.

**Comment by zooba** [comment]
ACtually
