### ISSUE TITLE
visual studio 2017 (15.6.6) python intellisense

### ISSUE THREAD

**Issue by PterosDiacos** [Microsoft/PTVS#4099]
System: windows 10 64-bit, visual studio 2017 15.6.6.
I'm using the New Style Intellisense for auto-completion, which doesn't work for contexts like these:

> with open(...) as file:
>     ... 

In the above context, the intellisense is unable to recognize the type of "file".

**Comment by huguesv** [comment]
Thanks, I've added it to https://github.com/Microsoft/PTVS/issues/3046 and will close this one as duplicate.
