### ISSUE TITLE
flask launcher script

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/PTVS#4102]
Starting with flask 0.11, the recommended way to launch flask is by using the flask module (see http://flask.pocoo.org/docs/0.12/server/ ), but I can't figure out how to set this up. Perhaps this should be an option under "launch mode", similar to "Django Web launcher"

**Comment by huguesv** [comment]
The reason they say it's recommended is for improved auto-reloading.

Our debugger currently doesn't support automatically attaching to a child process, so you won't be able to debug unless you disable auto-reloading. It's near the top the list of features we want to do once the new experimental debugger is at parity with the current debugger.

Also, beware of this bug, which probably affects Flask too:
https://github.com/Microsoft/PTVS/issues/4025
