### ISSUE TITLE
Error list not updated when file is reopened

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4112]
Create new Python application
Type something with a syntax error:
```
print("
```
See errors appear in error list
Close file, wait for error list to clear
Open file again (from solution explorer)

Result: no errors appear in error list

If you close and reopen solution, then open the file, you'll see errors appear. Close the file and reopen it, no errors!

**Comment by zooba** [comment]
Hmm... guess we explicitly clear when you close the file, probably to deal with loose files. This likely needs to check whether the file is in the current project and not clear errors.

(When we get to Open Folder, I believe we should only show errors for open files to be consistent with VS Code)
