### ISSUE TITLE
Completions dropdown shouldn't appear after def and class

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4115]
Regression in 15.8 branch

New Python application
Type: `def ` or `class `
Result: after typing the space, completions drop down appears.

Example: type `def he(` and you'll get `def help()` instead of `def he()`, so you're forced to dismiss with ESC to get what you want.

**Comment by huguesv** [comment]
Well, one way to avoid it is to turn this Auto List Members off:
![image](https://user-images.githubusercontent.com/1696845/39221272-d5fa8ed4-47ea-11e8-9aec-8c291726b9e6.png)

**Comment by zooba** [comment]
@huguesv Should we consider for servicing?

**Comment by huguesv** [comment]
No need, it's a problem only for 15.8.
