### ISSUE TITLE
Task List always empty in PTVS

### ISSUE THREAD

**Issue by gigamegawatts** [Microsoft/PTVS#4119]
I recently restart using PTVS for the first time in a couple of years, and I've noticed that none of the comments which used to show up in the Task List are appearing.  

e.g.
```
# TODO: an item to be done
# HACK: a hack to be rewritten
```

The Task List window is always empty. 

I'm running Visual Studio 2017, build 15.6.6 and Python 15.6.18072.2.

The Task List feature is working normally in my C++ projects, so I don't think it's a problem with my Visual Studio configuration.  I haven't made any changes to the defaults in Tools->Environment->Task List.

Is this a known problem?  If not, any suggestions on how to debug it or workaround it?

**Comment by huguesv** [comment]
It's a bug, thank you for reporting it!
