### ISSUE TITLE
Editing in comments should not bring up completions

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4120]
This behavior is new in master branch.
If that was added for VSCode, then we should have it optional so that VS can opt out of it.
![image](https://user-images.githubusercontent.com/1696845/39263334-abfa3b2a-4876-11e8-8efb-ab9f70adf85a.png)

**Comment by zooba** [comment]
Haha, whoops. This is just a bug

**Comment by MikhailArkhipov** [comment]
Seems to still repro in VSC, see https://github.com/Microsoft/vscode-python/issues/1775.
