### ISSUE TITLE
Wrong error count in Error List window when imported module is missing

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4125]
- Launch VS and make sure Error List window is closed, close VS 
- Launch VS and create project 
- Type import xxxx and wait the green wave under-line displayed 
- View > Error List to open Error List window 
- There are 1 line error in grid, but it shows 0 Errors: 
![image](https://user-images.githubusercontent.com/1696845/39268577-192549ca-4885-11e8-9b8f-649dd6cb67c4.png)

Note: if you close the file and reopen it, then the error count will be correct.

Also, should it count as an error or a warning? The icon says it's an error, but the text in tools/options says:
**Warn** when imported module cannot be found

And when you start debugging, these don't trigger the "you have errors, do you really wish to start" message, so we must be treating it in a way that is neither warning or error.

**Comment by huguesv** [comment]
We might just want to do https://github.com/Microsoft/PTVS/issues/3759 which might fix the problem with the error count.

I still think it should be a warning, not an error, given that it's a green squiggle and the "warn" option.

**Comment by shimingsg** [comment]
verified on build 27708.3001 that fixed
