### ISSUE TITLE
No completion for list function argument

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#4130]
```
def foo(a: List[str]):
  a[0].
```
expected: `str` members. PyCharm

![image](https://user-images.githubusercontent.com/12820357/39448499-f057022e-4c79-11e8-9aab-1534e6fc2591.png)

**Comment by huguesv** [comment]
I think you're supposed to use `typing.List`, not `list`.
![image](https://user-images.githubusercontent.com/1696845/39278513-68411462-48a8-11e8-804b-04195f4c9375.png)

![image](https://user-images.githubusercontent.com/1696845/39278516-6ba1c854-48a8-11e8-9ed6-0b2811ed270e.png)

If I run mypy on the code above, I get this:
PythonApplication82.py:7: error: "list" is not subscriptable, use "typing.List" instead

**Comment by balta2ar** [comment]
What if you omit `list`?
```
def foo(a: [str]):
  a[0].
```

**Comment by huguesv** [comment]
If you do that, we show completions for `str`. However, MyPy doesn't like it.
```
PythonApplication84.py:2: error: Invalid type
```

**Comment by MikhailArkhipov** [comment]
PyCharm (and also Jedi)
![image](https://user-images.githubusercontent.com/12820357/39448477-de2698bc-4c79-11e8-8f8f-4e2d8a717461.png)
