### ISSUE TITLE
No completion in namespace packages

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#4138]
```
.
├── projecta
│   └── foo
│       ├── bar
│       │   └── __init__.py
│       └── __init__.py
└── projectb
    └── foo
        ├── baz
        │   └── __init__.py
        └── __init__.py
```

test.py:
```
import projectA.foo
import projectA.foo.bar
import projectB.foo
import projectB.foo.baz

projectA.
```
![image](https://user-images.githubusercontent.com/12820357/39330695-3cf1d9fe-4957-11e8-99d9-7c36ebc77d95.png)

Jedi:
![image](https://user-images.githubusercontent.com/12820357/39330648-1fb33f36-4957-11e8-8d5f-bac8a9d707ea.png)

PyCharm:
![image](https://user-images.githubusercontent.com/12820357/39330711-510b0ece-4957-11e8-921c-4b9c7fc814e9.png)

**Comment by MikhailArkhipov** [comment]
Essentially https://github.com/Microsoft/PTVS/issues/949 . Current code does not consider possibility of the `ProjectA` to be a folder name. It basically assumes that `ProjectA` is a module and `foo` is being imported from that module.

**Comment by MikhailArkhipov** [comment]
Works in 3.6 but not in 2.7. 2.7 works if `__init__.py` is added to `ProjectA` and `ProjectB`. See also https://stackoverflow.com/questions/32152373/python-why-can-i-import-modules-without-init-py-at-all

**Comment by MikhailArkhipov** [comment]
Apparently is is pretty common case. See https://github.com/Microsoft/vscode-python/issues/2213 and https://github.com/Microsoft/vscode-python/issues/2319

**Comment by zooba** [comment]
2.7 doesn't support namespace packages - they were added in 3.3.

`mpl_toolkits` should be coming through `AstPythonInterpreter.ImportModule`, so it should be easy enough to look through all search paths and return a set of multiple modules.

The original issue in this thread is about namespace packages in the user's own project, which is going to be a different fix. You'll probably want to split the "in stdlib" vs "in project" cases into separate bugs.

**Comment by MikhailArkhipov** [comment]
Yes, I know. Matplotlib issue is somewhat simpler.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/12
