### ISSUE TITLE
No completion for custom tags and filters in Django projects

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#4144]
1. Create new Django Web Project
1. In the `app` folder, create new `templatetags` folder
1. Create new module `custom.py` with the following code:
```python
from django import template

register = template.Library()

@register.simple_tag
def get_title():
    return 'Getting started title'

@register.filter(name='get_num_color')
def get_num_color(value):
    if value < 1:
        return "#FF0000"
    elif value <= 3 :
        return "#FF7400"
    else:
        return "#00CC00"
```
4. Add `{% load custom %}` to the beginning of `app\templates\app\index.html`
5. Try get custom tag or filter in html:
![image](https://user-images.githubusercontent.com/8933858/39437387-4e19ea3e-4c66-11e8-8471-21d4ec36572a.png)

**Comment by huguesv** [comment]
Affected tests:
Django.DjangoAnalyzerTests.TestCustomFilter
Django.DjangoAnalyzerTests.TestCustomTag
