### ISSUE TITLE
AD7 debugger can't attach to python 3.7

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#4145]
1. Start `python.exe` from python 3.7
1. Open "Attach to Process" window, select `python.exe`
![image](https://user-images.githubusercontent.com/8933858/39451828-afd05c66-4c95-11e8-8031-2b3e1ccfd875.png)

Bug is reproduced by `AttachTests37_x64.AttachWithOutputRedirection` test.

**Comment by huguesv** [comment]
Mixed-mode debugger is affected too: https://github.com/Microsoft/PTVS/issues/4146

**Comment by huguesv** [comment]
We'll need to support it in 15.8. Whether it's only in the new debugger or also legacy AD7 debugger is TBD.
