### ISSUE TITLE
InvalidOperationException in Microsoft.PythonTools.Ipc.Json.Connection.WriteError

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4148]
Watson crash report. Internal bug 608427. Hit count is pretty high.

**Comment by AlexanderSher** [comment]
Crashes are reported only for PTVS version 15.6.18072.2. All of them are related to the issues with message parsing, but we don't have detailed information about them. We have added telemetry logging in #4272, but that's pretty much everything we can do about this issue right now.
