### ISSUE TITLE
Format document of comma separated import breaks code

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4156]
```
import os,sys
```

Edit->Advanced->Format Document

Result is invalid code:
```
import os

importsys
```

Note: if you have a space after the comma, ie `import os, sys` then it's fine.

**Comment by MikhailArkhipov** [comment]
IMO it should respect user formatting and keep comma separated format if user decided to do so.

**Comment by MikhailArkhipov** [comment]
Microsoft/python-language-server#10
https://github.com/Microsoft/PTVS/issues/4698
