### ISSUE TITLE
PyQt5, with vs2017 15.6.7 intelisense doesn't work very well.

### ISSUE THREAD

**Issue by jmh-aira** [microsoft/PTVS#4165]
Hi,

I just started working with PyQt5.  I started creating a window with it, and I noticed that the intelisense wasn't working really at all.

when I typed:

from PyQt5. ; here it showed me what modules were associated with PyQt5.  but after I selected QtWidgets, and then typed import : after hitting the space bar, it only gave me '*' as an option.

So I typed in the classes I needed, QApplication, and QWidget.

I then typed

app = QApplication()

and then tried:

window = QWidget()

I wanted to set the title, so I tried

window. : and when I did the . it said"No Completions"

Also, as I was typing this message, I shutdown VS, and brought it ack up, now when I do

from PyQt5. : instead of showing me the sub modules, it just brings up a list of all modules in my python install.  so It would autocomplete like PyQt5, or my project's module name.

Please let me know if there is anything I can provide.  Or do.

Thank you.

**Comment by jmh-aira** [comment]
I tried the PyQt5 intelisense in vs code, and it works just fine.  When I go back to the old completion dbs intelisence system, then I get all the PyQt5 information I need.  Also, I tried the vs 2017 preview 15.7 prev iew 6, and the intelisense didn't work there as well.

**Comment by huguesv** [comment]
Thanks. I can confirm I am seeing the same behavior (results only if using completion db).

**Comment by GJpy** [comment]
Just for additionnal informations, I do have the same behavior: no completion with PySide2 and VS 2017 preview 15.7 ( but works fine without the completion DB too ).
