### ISSUE TITLE
build failed with no errors

### ISSUE THREAD

**Issue by mmccoy173** [Microsoft/PTVS#4184]
I created a new python project **From Existing Python Code** and build fails with no errors.

I'm not sure why it's failing because the app runs and works without issue.

I reproduced with a blank Django app created via `django-admin startproject`. I did it this way so I can use Django 2 as the VS Django Web Project template uses Django 1.

**Comment by huguesv** [comment]
It might be a false positive, but it almost looks like adding this property prevents the build error (on build and also rebuild). 

Please let us know if it works for you.

.pyproj:
```
    <SuppressCollectPythonCloudServiceFiles>true</SuppressCollectPythonCloudServiceFiles>
```

settings.py:
```
import posixpath
STATIC_ROOT = posixpath.join(*(BASE_DIR.split(os.path.sep) + ['static']))
```

**Comment by mmccoy173** [comment]
Simply setting `STATIC_ROOT` property in `settings.py` seems to have fixed it. Thanks!

**Comment by huguesv** [comment]
We can fix this by skipping collection of static files on build when STATIC_ROOT is undefined.
