### ISSUE TITLE
File and folder path completions no longer work

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4188]
15.8 or master branch

`open('.\')` press CTRL+SPACE inside the string, you should get a list of files, but instead you get regular completions.

![image](https://user-images.githubusercontent.com/1696845/39843596-a4cdc1a2-53a0-11e8-85f4-2c4c80cf6be7.png)

**Comment by AlexanderSher** [comment]
Regressed by https://github.com/Microsoft/PTVS/pull/4073
