### ISSUE TITLE
Quick Info via keyboard CTRL+K, CTRL+I is incorrect

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4191]
Open an existing file
DO NOT use the mouse
With the keyboard, move the cursor on an identifier
CTRL+K, CTRL+I
Result: nothing happens

Put the mouse on an identifier and wait for quick info to appear
Using the keyboard, move to a different identifier
CTRL+K, CTRL+I
Result: quick info for the *previous* identifier appears

**Comment by MikhailArkhipov** [comment]
Probably same as #4245 - incorrect location passed

**Comment by huguesv** [comment]
It's nowhere near the same statement, so it sounds different than this other bug.
![image](https://user-images.githubusercontent.com/1696845/40453450-141b9e2c-5e9a-11e8-9c8c-9ffc93239303.png)
