### ISSUE TITLE
Can not install wfastcgi 2.1 gateway for iis and python 2.7.9 in IIS

### ISSUE THREAD

**Issue by maxi1693** [Microsoft/PTVS#4202]
Hi, I can not install the "wfastcgi 2.1 gateway for iis and python 2.7.9" in IIS. I see that you change the repository. you can check it? what is the link to download the installer.

Thanks in advance!
![image](https://user-images.githubusercontent.com/39176177/39901350-3f9bcef6-549e-11e8-92b0-95b152d42207.png)

**Comment by huguesv** [comment]
That looks like Web Platform Installer. That feed is not maintained anymore, and it points to files on CodePlex which are no longer now that CodePlex is closed/archived.

We recommend you install from https://pypi.org/project/wfastcgi/ instead, using pip.

**Comment by maxi1693** [comment]
Thanks you very much!
