### ISSUE TITLE
No completions on modules in zip file

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4226]
Create a zip file:
```
module2.zip
    - module2
        - __init__.py <- declare some variables here like MSG = 'hello'
```
Create new python application
Right click search paths and add zip archive to search path, module2.zip
Enter this code, notice you do not get any completions on module2 (even if you wait).
```
import module2
print(module2.MSG)
```
To make sure you've set things up properly, launch the app to see 'hello' printed.

**Comment by MikhailArkhipov** [comment]
Is this common?

**Comment by huguesv** [comment]
Failing test is `PythonToolsTests.CPythonInterpreterTests.ImportFromZipFile`
