### ISSUE TITLE
QuickInfo hover tip annoying grey boxes poping up unexpectedly everywhere in VS Python editor

### ISSUE THREAD

**Issue by abdlg** [Microsoft/PTVS#4231]
Is it possible to add the same functionality in the VS Python editor to disable the hover tip 
as it is offered for the C/C++ editor with the advanced parameters option for C/C++.  

thank  you in advance.

**Comment by huguesv** [comment]
Thanks for the feedback. We have an issue on this already at https://github.com/Microsoft/PTVS/issues/3716 so I'll close this one as duplicate.
