### ISSUE TITLE
Rename broken

### ISSUE THREAD

**Issue by borisneal** [Microsoft/PTVS#4235]
Selected a variable, F2 to rename:

![image](https://user-images.githubusercontent.com/39171152/40207104-9c978c1e-59e7-11e8-84e6-8f487bad6e2a.png)

And nothing gets renamed

**Comment by borisneal** [comment]
This is Windows 10 Pro, VS Professional 15.7.1

**Comment by huguesv** [comment]
We've fixed refactor rename for 15.7.2, which will be out very soon.
https://github.com/Microsoft/PTVS/issues/4169

It's likely to fix your scenario, but I can't say for sure without seeing your code. Let us know if the issue persists once you've updated.
