### ISSUE TITLE
PTVS discovers fewer tests in VS2017 compared to VS2015

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/PTVS#4237]
https://github.com/Microsoft/knack

When I create a VS2015 solution for this repo, it discovers 165 tests, the same as when I discover tests from the command line.  However, when I create a VS2017 solution file, it only discovers 119 tests. As a result, I find myself constantly having to switch back to VS2015 just to debug tests. This has been a problem in the CLI repo since the release of VS2017.

**Comment by huguesv** [comment]
I'm getting 164 tests discovered. I'm on the latest PTVS from master, which is slightly ahead of dogfood build 15.8 Preview 2.

Here's how I've setup the project, with a Python 3.6 venv:

![image](https://user-images.githubusercontent.com/1696845/40327778-fba6380e-5cf8-11e8-96af-7184d6ca5850.png)

Did you setup your project similar to mine?

**Comment by tjprescott** [comment]
Pretty much exactly like yours 

![ss](https://user-images.githubusercontent.com/5723682/40370885-21889be6-5d96-11e8-9dde-6796a75b414c.png)

**Comment by tjprescott** [comment]
I updated to the latest version of VS and PTVS and it looks like all is well. Love the new changes!
