### ISSUE TITLE
Build azure cloud service fails, reports missing .NET Framework 4 targeting pack

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4242]
Install VS with Python development Workload
Create Cloud Service, you get prompted to install Azure Tools for Visual Studio, accept it
Create Cloud Service, add a role
Build service project
Result:
```
------ Rebuild All started: Project: BottleWebProject1, Configuration: Debug Any CPU ------
------ Rebuild All started: Project: BottleWebProject1.Azure, Configuration: Debug Any CPU ------
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
Done building project "BottleWebProject1.Azure.ccproj" -- FAILED.

Build FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```

Workaround is to manually select ".NET Framework 4 targeting pack" individual component in VS installer.

Note that the Azure development workload includes that component by default.

I'm not sure why the "Azure Tools for Visual Studio" component doesn't depend on it, since it requires it to build cloud services projects?

**Comment by zooba** [comment]
If you can repro this with the .NET web workload and the Azure Tools component, I'd send it through Report a Problem.

**Comment by huguesv** [comment]
We've removed support for these.
