### ISSUE TITLE
Hover over expression shows return type rather than call signature

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#4245]
Hover over `now` in `datetime.datetime.now()` - tooltip shows `datetime`.  Hovering over first `datetime` should show module info, over second `datetime` it should show `class datetime` and over `now` it should display the function documentation.

**Comment by zooba** [comment]
Ah, it’s at the start but we are passing the exact string to evaluate. I guess we stopped using the expr member at some point?

Fixing the location and not passing the string should be fine.
