### ISSUE TITLE
Changing search path from project properties doesn't update solution explorer

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4251]
Right click project, properties
In debug tab, set a valid search path
Save
In solution explorer, the Search Paths node isn't updated

Note: The reverse works fine, if you add a search path through solution explorer it immediately updates in the debug tab.

**Comment by zhouwangyang** [comment]
if I clear the "Search Paths" in debug tab, and save,In solution explorer, the Search Paths node isn't updated too, the cleared path is still in SE.
