### ISSUE TITLE
IronPython always picks up legacy debugger

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#4253]
Since we ship both old and new debugger. IronPython seems to import `ptvsd` available in the same location as `ptvsd_launcher.py`. Deleting legacy `ptvsd` makes it pick up the experimental debugger which is in `Packages\ptvsd`

**Comment by huguesv** [comment]
I have details on why this happens here: https://github.com/Microsoft/PTVS/issues/3899

**Comment by karthiknadig** [comment]
Closing this.
