### ISSUE TITLE
Format document doesn't remove last semicolon

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4254]
Input:
```
value = 1;
value = 2;
value = 3;
```
Format document. Result is:
```
value = 1
value = 2
value = 3;
```
Would have expected the last semicolon to be removed as well.

**Comment by AlexanderSher** [comment]
We need to add test for this

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/10
