### ISSUE TITLE
failed to launch debug adapter.

### ISSUE THREAD

**Issue by weihangChen** [Microsoft/PTVS#4270]
I am following this [tutorial ](https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines)trying out the remote debug, but when debugger is attached, nothing happens

### Remote server is set up using docker

`workdir/docker-compose.yml`
```
version: '3'
services:    
  test:
    build: test
    container_name: test
    ports:
      - "5678:5678"
```

`workdir/test/Dockerfile`
```
FROM python
RUN pip install  "ptvsd==3.0.0"
ADD test.py test.py
CMD ["python", "test.py"]
```
`workdir/test/test.py`
```
import random
import ptvsd

ptvsd.enable_attach('my_secret')
print("test!!!!!!!!!!!!!!!!!!!! wait for attach")
ptvsd.wait_for_attach()
guesses_made = 0
name = input('Hello! What is your name?\n')
number = random.randint(1, 20)
print('Well, {0}, I am thinking of a number between 1 and 20.'.format(name))

while guesses_made < 6:
    guess = int(input('Take a guess: '))
    guesses_made += 1
    if guess < number:
        print('Your guess is too low.')
    if guess > number:
        print('Your guess is too high.')
    if guess == number:
        break
if guess == number:
    print('Good job, {0}! You guessed my number in {1} guesses!'.format(name, guesses_made))
else:
    print('Nope. The number I was thinking of was {0}'.format(number))
```
when container is run, the `test.py` is waiting for attach, which is the desired behavior.

### Local visual studio remote debug setup
Visual studio 2017 is used, as I put `tcps://my_secret@127.0.0.1:5678/ `as the remote debug target, just hat the debugger does not attach at all.

Any help?
Regards
Marc

**Comment by polakovicp** [comment]
1) Check if port 5678 is enabled
2) I had similar issue using fabric.api.run(cmd), when I executed command manually using shell, everything worked fine. Maybe it's a problem with piped standard input and outputs.

**Comment by karthiknadig** [comment]
@weihangChen Looks like you are trying to connect to `ptvsd==3.0.0` using the experimental debugger, which requires `ptvsd==4.1.1a1`. 

There are two options:
**[Options 1] Using experimental debugger**
If you want to try with the experimental version, note that does not support 'secret' yet. just change the following things:
In docker file change line 2:
```
RUN pip install  "ptvsd==4.1.1a1"
```
In test.py change line 4:
```
ptvsd.enable_attach()
```
That should do it.

**[Option 2] Using the debugger compatible with ptvsd 3.0.0.**
If you want to try with the debugger compatible with `ptvsd 3.0.0`, go to Tools > Options > Python > Experimental. Un-check the 'Use experimental debugger' and try this again.

**Comment by karthiknadig** [comment]
For **[Option 2]** Can you try restarting VS after disabling the experimental debugger? Another thing, the ptvsd version that is compatible with 15.7.2 is ptvsd 3.2.1. If you update the docker file line 2 to:
```
RUN pip install  "ptvsd==3.2.1"
```
![image](https://user-images.githubusercontent.com/3840081/40688484-1f45dbc4-6353-11e8-8c64-69aa45ff184a.png)

**Comment by weihangChen** [comment]
thank you so much Kanadig !!! ptvsd 3.2.1 works

![capture](https://user-images.githubusercontent.com/2369864/40689446-70503722-63a2-11e8-977b-dd17d90366bf.PNG)
