### ISSUE TITLE
Unknown appears in method signature for dict.get

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4279]
`Unknown()` looks suspicious in this method signature. That's not a real Python thing, is it?

```
d = {'a': 1 }
d.get(
```
![image](https://user-images.githubusercontent.com/1696845/40690106-2d95a2b6-635a-11e8-84e5-715175b28b77.png)

**Comment by zooba** [comment]
Not in this case. We normally filter them out before they ever reach the user, but there have been recent changes here that may have caused it to leak through our module scraper as a different type.
