### ISSUE TITLE
Incorrect inferred type for s in s = sum(i for i in [0,1])

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/PTVS#4286]
Steps:

1. try this code:
```python
s = sum(i for i in [0,1])
```
2. hover over `s`

Expected: `s: int`
Actual: `s: generator[int]`

Curious thing is that the type of `sum(i for i in [0,1])` does not seem to be inferred at all on its own.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/8

**Comment by lostmsu** [comment]
@MikhailArkhipov , the new repo seems to be private.
