### ISSUE TITLE
Pressing 'Tab` with Autocomplete is not Reliable for fast typing, "pastes" incorrectly.

### ISSUE THREAD

**Issue by joseortiz3** [Microsoft/PTVS#4287]
Very often, when I press 'Tab' (or 'Enter') to accept autocomplete's first suggestion, autocomplete "fills in" incorrectly.

For instance, I'll have some variable or function named `someName`. I will type `s`, and hit tab. Autocomplete will then fill with the entire name, resulting in the typo `ssomeName`.

This often occurs when I am typing very quickly, so it seems to be a race condition of some sort. It is behavior that I have not seen until very recently (within last year), and I have been using PTVS for years.

I am struggling trying to create a reproducible example, but hopefully I or someone else will find one soon.

**Comment by huguesv** [comment]
Thanks for filing this. I've experienced the issue, but haven't been able to get a consistent repro either.

**Comment by joseortiz3** [comment]
It also happens when pressii

**Comment by joseortiz3** [comment]
Whoops, sorry. Didn't mean to press the "close issue" button.

**Comment by zooba** [comment]
I just fixed this with #4390 (because it's been annoying me too, and I stumbled upon the cause but forgot about this bug).
