### ISSUE TITLE
Configuring IronPython

### ISSUE THREAD

**Issue by serverLua** [Microsoft/PTVS#4294]
[Window Title]
devenv.exe

[Main Instruction]
发生意外错误

[Content]
请按 Ctrl+C 复制此对话框的内容并向我们的问题跟踪程序报告此错误。

[^] 隐藏详细信息(D)  [关闭(C)]

[Expanded Information]
```
Build: 15.7.18131.1

System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   在 System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   在 System.IO.Path.GetFullPathInternal(String path)
   在 System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   在 System.IO.Directory.CreateDirectory(String path)
   在 Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.EnsureScriptDirectory(String path)
```

**Comment by huguesv** [comment]
Thanks! I was able to reproduce by using an illegal filename character in a custom environment name, and navigating to the overview page for that environment.

**Comment by huguesv** [comment]
![image](https://user-images.githubusercontent.com/1696845/40857663-a5a70690-6590-11e8-869c-f83fabadbf7e.png)
