### ISSUE TITLE
Deleted variables linger in analysis

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#4299]
Declare `p=1`
Observe `p.` gives completion for `int`.
Delete line with `p=1`
Type `p.`

![image](https://user-images.githubusercontent.com/12820357/40869573-78098cac-65d2-11e8-8403-284cb2d05f00.png)

**Comment by zooba** [comment]
I can't repro this on master.

**Comment by MikhailArkhipov** [comment]
Looks like it went away.
