### ISSUE TITLE
Rename folder/file failed (see #1575)

### ISSUE THREAD

**Issue by mseise123** [Microsoft/PTVS#4329]
#1575  happens again in 15.7.3

**Comment by huguesv** [comment]
@mseise123 I'm not sure how to reproduce this. Can you provide steps?

**Comment by mseise123** [comment]
Exactly as in #1575 - just try to rename a (python) file or folder in the project explorer.  The file on the harddrive is correctly renamed, but (Probably) not in the pyproject file - the name in the explorer view is not renamed. 
The error is (something like) "Member not found" HRESULT:0x80020003, DISP_EMEMBERNOTFOUND"
Adding the renamed file is only possible after reloading the project.

**Comment by mseise123** [comment]
This is fixed in 15.7.4
