### ISSUE TITLE
LastReportedDiagnostics isn't cleared after document is closed and reopened

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#4349]
- Create new module or open an existing one
- Make some good amount of changes in the file to increase the  buffer version
- Make an error that is handled by parser, save & close
- Reopen the file, fix an error or add a new one

**Actual** 
Squiggles don't change 

**Expected**
Squiggles match parsing errors

**Comment by AlexanderSher** [comment]
`OnDocumentChangeProcessingComplete` doesn't call `PublishDiagnostics` if `LastReportedDiagnostics` version is greater than current buffer version:

```cs
foreach (var kv in vc.GetAllParts(doc.DocumentUri)) {
    var part = _projectFiles.GetPart(kv.Key);
    if (!reported.TryGetValue(part, out var lastVersion) || lastVersion.Version < kv.Value.Version) {
        reported[part] = kv.Value;
        PublishDiagnostics(new PublishDiagnosticsEventArgs {
            uri = kv.Key,
            diagnostics = kv.Value.Diagnostics,
            _version = kv.Value.Version
        });
    }
}
```

**Comment by zooba** [comment]
@AlexanderSher I'm pretty sure the fix for this is the same as #4351 - we need to more consistently manage `_openFiles` in `Server`.

**Comment by AlexanderSher** [comment]
Probably. I have the changeset, but I need to test it.

**Comment by zooba** [comment]
Looks like we're also not calling `DidCloseTextDocument` from VS, so that would help :)

**Comment by AlexanderSher** [comment]
Thanks for the hint.
