### ISSUE TITLE
VSC can send `textDocument/didChange` incrementing version by any number.

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#4350]
- Create new module, type some text
- Quickly press `Backspace` twice to erase two symblos, then press `Ctrl+Z` (undo). Both symbols should be restored at once
- Attach debugger to `dotnet` process, put breakpoint at the first line of `Server.DidChangeTextDocument`, add `@params.textDocument.version`  to watch
- Press `Ctrl+Y` (redo), then `Ctrl+Z` (undo), observe that VS Code sends JSON with with version incremented by 2:

```cs
@params.textDocument.version: 22
@params.textDocument.version: 24
@params.textDocument.version: 26
```

Increment can be by any number, depending on the amount of changes VS Code merges together during undo/redo operations. `OpenFile.DidChangeTextDocument` can't handle changes like that and keeps putting incoming changes into `_pendingChanges`.

```
if (fromVersion > docVersion && @params.contentChanges?.Any(c => c.range == null) != true) {
    // Expected from version hasn't been seen yet, and there are no resets in this
    // change, so enqueue it for later.
    _log.TraceMessage($"Deferring changes for {uri} until version {fromVersion} is seen");
    lock (_pendingChanges) {
        _pendingChanges.Add(@params);
    }
    return;
}
```

**Comment by zooba** [comment]
Heh, they're the ones who claimed version numbers would always increase by one...

**Comment by zooba** [comment]
@AlexanderSher Do you know if they're also sending a "previous version" property? Or are they just assuming that messages will never arrive out of order (and silently corrupting the user experience when that does happen...)?

**Comment by AlexanderSher** [comment]
No, but we know the amount of changes, so
```cs
var fromVersion = Math.Max(@params.textDocument.version - changes.Length, 0);
```
is enough to get proper `fromVersion`. But it doesn't fix the issue. After this change, it fails with 
```cs
throw new InvalidOperationException("changes must be in reverse order of start location");
```
```cs
Microsoft.PythonTools.Analysis.DocumentBuffer.Update(Microsoft.PythonTools.Analysis.DocumentChangeSet changes) Line 70
Microsoft.PythonTools.Analysis.ProjectEntry.UpdateDocument(int part, Microsoft.PythonTools.Analysis.DocumentChangeSet changes) Line 429
Microsoft.PythonTools.Analysis.LanguageServer.OpenFile.DidChangeTextDocument(Microsoft.PythonTools.Analysis.LanguageServer.DidChangeTextDocumentParams params, System.Action<Microsoft.PythonTools.Analysis.IDocument> enqueueAction) Line 81
Microsoft.PythonTools.Analysis.LanguageServer.Server.DidChangeTextDocument(Microsoft.PythonTools.Analysis.LanguageServer.DidChangeTextDocumentParams params) Line 227
Microsoft.PythonTools.VsCode.LanguageServer.DidChangeTextDocument(Newtonsoft.Json.Linq.JToken token) Line 196
```

**Comment by zooba** [comment]
That seems odd, unless they're sending a single change and incrementing the version twice... in which case I'd file a bug against VSC.

**Comment by AlexanderSher** [comment]
`DocumentChangeSet` for change from `import s` to `import sys` looks like this:
```
{
    FromVersion: 6,
    ToVersion: 8,
    Changes: [
        {
            InsertedText: "y",
            ReplacedSpan: (1, 9)-(1, 9),
            WholeBuffer: false
        },
        {
            InsertedText: "s",
            ReplacedSpan: (1, 10)-(1, 10),
            WholeBuffer: false
        }
    ]
}
```

Loop fails on the second iteration because `start == 9` and `lastStart == 8`.

**Comment by MikhailArkhipov** [comment]
Yeah, I've seen documents occasionally going out of sync.

**Comment by zooba** [comment]
I don't think we're meant to be generating that change set - it should be being sent through as separate requests if it represents two versions. Multiple changes are allowed for a single update that affects multiple spans (e.g. typing with block selection or global undo).

Do you know what the original message looked like? I don't see where we could be translating it wrong, but maybe there's an edge case I'm not seeing.

**Comment by AlexanderSher** [comment]
It is a correct change set, here is what we get it from VSC's:
```
{
  {
    "textDocument": {
      "uri": "file:///d%3A/Temp/PythonApp1/PythonApp1/PythonApp1.py",
      "version": 8
    },
    "contentChanges": [
      {
        "range": {
          "start": {
            "line": 0,
            "character": 8
          },
          "end": {
            "line": 0,
            "character": 8
          }
        },
        "rangeLength": 0,
        "text": "y"
      },
      {
        "range": {
          "start": {
            "line": 0,
            "character": 9
          },
          "end": {
            "line": 0,
            "character": 9
          }
        },
        "rangeLength": 0,
        "text": "s"
      }
    ]
  }
}
```

**Comment by AlexanderSher** [comment]
As I said in bug description, it merges several changes into one for undo/redo.

**Comment by AlexanderSher** [comment]
> it should be being sent through as separate requests if it represents two versions. 

Maybe they have changed it in protocol version 3.0, but now it is allowed: https://microsoft.github.io/language-server-protocol/specification#textDocument_didChange

```
	/**
	 * The actual content changes. The content changes describe single state changes
	 * to the document. So if there are two content changes c1 and c2 for a document
	 * in state S10 then c1 move the document to S11 and c2 to S12.
	 */
```

This is, however, is different from `TextEdit[]`, where it explicitly specifies that:
```
Text edits ranges must never overlap, that means no part of the original document must be manipulated by more than one edit.
```

**Comment by zooba** [comment]
Okay, so we just have to assume that each message comes in the right order. That should be safe enough now that we've single-threaded the processing loop and made this function non-async.

**Comment by AlexanderSher** [comment]
We don't have to assume it:
- `textDocument.version` gives us `To` version
- `textDocument.version - contentChanges.Length` gives us `From` version

The only thing that is required is that changes inside the message are in the right order, but this is specified in the protocol (at least in its current version).

**Comment by zooba** [comment]
VS can send multiple changes per version. However, it can also send the "from" version, so perhaps we should include that in the message (do we already?) and use it if it's there - otherwise assume only one change per version.

**Comment by AlexanderSher** [comment]
We don't send `textDocument/didChange` from VS directly, we send `FileUpdateRequest` instead.

**Comment by zooba** [comment]
@AlexanderSher Right, but it's translated directly from the `ITextVersion`, which means we can have one version number with multiple changes. And `FileUpdateRequest` is only a thin layer over `textDocument/didChange` while we (slowly) finish migrating VS to use the language server directly.

**Comment by AlexanderSher** [comment]
Ok, I have been able to send two identical arrays of changes, but different version changes.

**Version increased by one:**
- Type two identical letters
- Select first one
- Hit Ctrl+D to select them both
![untitled](https://user-images.githubusercontent.com/8933858/42045318-e2a7f96a-7ac0-11e8-95fd-4ac68b113b4e.png)
- Hit backspace:
```json
[
  {
    "range": {
      "start": { "line": 0, "character": 7 },
      "end": { "line": 0, "character": 8 }
    },
    "rangeLength": 1,
    "text": ""
  },
  {
    "range": {
      "start": { "line": 0, "character": 6 },
      "end": { "line": 0, "character": 7 }
    },
    "rangeLength": 1,
    "text": ""
  }
]
```

**Version increased by 2**
- Quickly type two identical letter
- Hit Ctrl+Z:
```json
[
  {
    "range": {
      "start": { "line": 0, "character": 7 },
      "end": { "line": 0, "character": 8 }
    },
    "rangeLength": 1,
    "text": ""
  },
  {
    "range": {
      "start": { "line": 0, "character": 6 },
      "end": { "line": 0, "character": 7 }
    },
    "rangeLength": 1,
    "text": ""
  }
]
```
