### ISSUE TITLE
Tooltip for `from import` shows wrong module

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#4358]
![image](https://user-images.githubusercontent.com/1693688/41259903-2a4d77d4-6d8a-11e8-886e-09902e0a5f5a.png)

When I hover over `module1` in the `from ... import` statement, it should show me the value of `module1`, but actually shows me the package it belongs to.

If I hover over the module elsewhere in the file, it is correct.

**Comment by MikhailArkhipov** [comment]
We return location of `.` rather than the assigned name.
