### ISSUE TITLE
`from ... import` shows incorrect completions

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#4359]
![image](https://user-images.githubusercontent.com/1693688/41260009-92cd0afe-6d8a-11e8-8e27-ba0a505f7e30.png)

When I do `from .module1 import` I see completions coming from the global `module1` rather than the relative `my_package.module1`.

However, the correct module is imported, and later references get the correct one.

**Comment by MikhailArkhipov** [comment]
Ported to LS
