### ISSUE TITLE
Send to Interactive create a new Interactive session

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4364]
From https://developercommunity.visualstudio.com/content/problem/211707/python-tools-for-visual-studio-send-to-interactive.html

When i try to send code to the interactive window from a Python file (.py) with CTRL+ENTER, it creates a new interactive window unless I keep CTRL+ENTER pressed or spam the key very quickly.
This is very annoying since i'm not able to use the send to interactive like it would be practical, line by line. 

I'm using a virtual env in Anaconda 5.0.0, IPython interactive mode is enabled . When it starts opening new window it does it for every new evaluation.

**Comment by joseortiz3** [comment]
This is still an issue. I recommend reopening it. I am seeing this behavior today. Very, very annoying.
