### ISSUE TITLE
Copy and pasting to python debug interactive when during debugging

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4380]
While debugging I am not able to copy or paste from VS.  Cannot even paste from other programs like notepad to the debug interactive console.  I only use python, so I am not sure if it is specific to python or not.

There is no error message produced,  just canot copy or past to the debug interactive window.

Seem to happen independent of the version of python.  I use Python 2.7 and 3.6  both 32 & 64 bit of each.  Same issue regardless of python version.

Filed at https://developercommunity.visualstudio.com/content/problem/273649/copy-and-pasting-to-python-debug-interactive-when.html

**Comment by joseortiz3** [comment]
I confirm this is a problem with the experimental debugger on my Windows 10 Anaconda 3 computer.

**Comment by nrlcode** [comment]
How can we disable the experimental debugger?

**Comment by AviP1234** [comment]
@huguesv 
Thank you, but I uncheck everything in:
tools/options/python/experimental.
But I still have the same problem.
Do someone have another solution?

**Comment by mdmour** [comment]
disable the experimental debugger by unchecking the options in tools/options/python/experimental did not work for me. Any other suggestions please?

**Comment by huguesv** [comment]
@AviP1234 @mdmour I have verified that Paste works in my Debug REPL when using the legacy debugger / aka not experimental debugger. You may want to try restarting VS after changing the option.

The reason it doesn't work with the new debugger is that we don't have an fallback for when `_activeEvaluator` is `null` at https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/Repl/PythonDebugReplEvaluator.cs#L203 which is the case when using the new debugger.

**Comment by mdmour** [comment]
@AviP1234 
Tools/Options/Python/Debugging
then check "Use legacy debugger"
This worked for me. the tools/options/python/experimental did not help with this issue

**Comment by AviP1234** [comment]
@mdmour 
Thank thank thank you!
you're a lifesaver!

**Comment by joseortiz3** [comment]
Hi guys, despite all the comments here this is still a HUGE issue. Pasting into the new debugger is extremely important for actual python development, and it has been more than six months since this issue was raised.

**Comment by maxmax91** [comment]
Hi. I'm experiencing the same terrible problem. Debugger, like this, it not usable. Switching to legacy debugger solved the problem,  but I lost a lot of time. 
Thanks

**Comment by soumickmj** [comment]
I was using this legacy debugger, and it really resolves the copy paste problem. But recently, it now creates a new problem of its own. The whole visual studio debugging becomes very slow. After executing each line it freezes for a couple of seconds then responds again. During these seconds, visual studio is completely unresponsive, even debug stop button cannot be clicked - totally frozen. Anyone else encountered this problem? Any possible solutions?

**Comment by RaymonGulati1** [comment]
Happy to announce that this issue has been fixed (you can now copy/paste into experimental debugger). It will be released in 16.1.
