### ISSUE TITLE
where to set pydev?

### ISSUE THREAD

**Issue by bitlgy** [Microsoft/PTVS#4398]
when enter debugger mode. occur this hint：
pydev debugger: To debug that process please enable 'Attach to subprocess automatically while debugging?' option in the debugger settings.

so，where is debugger settings? I am using vs2017 community version.

**Comment by huguesv** [comment]
Sorry, some of these pydevd warnings/insructions are not applicable in ptvsd and can be misleading. We'll be suppressing some of these in the future.

Automatically attaching to subprocess is not supported yet. We're tracking this at https://github.com/Microsoft/ptvsd/issues/57

**Comment by bitlgy** [comment]
So, how should I debug my code with vs 2017? Or, how do I switch to single process from multi process?

thanks.

**Comment by huguesv** [comment]
Single process is the best option for now.
