### ISSUE TITLE
LanguageServerTests.CompletionInImport now failling

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4410]
Looking at the results history, this started failing yesterday. It also fails on latest code on my local machine.
![image](https://user-images.githubusercontent.com/1696845/41745215-197550c0-755b-11e8-9d17-479a046f9e88.png)

```
await AssertNoCompletion(s, u, new SourceLocation(1, 25));
```

**Comment by MikhailArkhipov** [comment]
I have the fix

**Comment by huguesv** [comment]
Test passes now
