### ISSUE TITLE
import completions are not filtered for submodules

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4422]
First level is fine:
![image](https://user-images.githubusercontent.com/1696845/41802282-8f561016-7634-11e8-8232-a54d38cf0e17.png)

But not after dot:
![image](https://user-images.githubusercontent.com/1696845/41802295-aa5c9b3c-7634-11e8-9fc6-62fa9cd72ff0.png)

Edit: I checked 15.7 and confirmed it's a regression.

**Comment by zooba** [comment]
This was fixed in #4418 for `from ... import`, so I'll get it for `import ...` as well.
