### ISSUE TITLE
PEP8 Support

### ISSUE THREAD

**Issue by hippieZhou** [Microsoft/PTVS#4426]
I want to know that how can i make it easy in VS2017 to formate my python code by pep8

**Comment by huguesv** [comment]
Sorry for not noticing your question so late.

The functionality currently available is accessed via Edit->Advanced->Format Document and it is configurable in Tools/Options/Text Editor/Python

We have these items that track improvements:
https://github.com/Microsoft/PTVS/issues/4694
https://github.com/Microsoft/PTVS/issues/4698

**Comment by hippieZhou** [comment]
Thanks
