### ISSUE TITLE
Pandas dataframe type not recognized 

### ISSUE THREAD

**Issue by Lyonk71** [Microsoft/PTVS#4428]
The Pandas  dataframe type is not being recognized, which results in code completion and hints to not work  with dataframes. Below is an example:

![image](https://user-images.githubusercontent.com/12675720/41856683-b300dd30-7863-11e8-97f8-9c46d9c02293.png)

Here is an example of the same code working as expected in VS code:

![image](https://user-images.githubusercontent.com/12675720/41856736-d27b717a-7863-11e8-8e73-c99d283ad6ce.png)

I have tried both the intellisense database, as well as the experimental intellisense feature.

Thanks

**Comment by zooba** [comment]
We dup these against issue #3046 to keep track of them.

Our next release will include support for type stubs, so when `pandas` has type stub files available you will be able to use those. (Currently there is not enough information in their source code for us to automatically infer return types, and we have chosen type stubs as the format to manually specify them.)

**Comment by Lyonk71** [comment]
Thanks for reaching out and providing some background. I shared the information with some of my coworkers who do Python development, so now we are looking forward to the next release!
