### ISSUE TITLE
Call Stack should qualify `__init__.py` 

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#443]
When debugging something inside `__init__.py`, function names in Call Stack window look something like `foo in __init__`. Since it's common to have numerous `__init__.py` in a single project, we should qualify which package it belongs to, like we do in Solution Explorer.

**Comment by huguesv** [comment]
Looks like that is done in ptvsd 4.x

![image](https://user-images.githubusercontent.com/1696845/47735917-bfd5d800-dc2a-11e8-8309-d13dd7f74e69.png)
