### ISSUE TITLE
No imports without Python installed

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#4434]
We include default databases with the install for when you don't have Python installed, but we aren't using them.

**Comment by zooba** [comment]
Apparently related, we don't handle the following code well:

```python
import unittest.case
import unittest.loader
import unittest.main
import unittest.result
import unittest.runner
import unittest.suite

BaseTestSuite = unittest.suite.BaseTestSuite
FunctionTestCase = unittest.case.FunctionTestCase
SkipTest = unittest.case.SkipTest
...
```

This creates a multi-valued member `unittest` with each of the imported modules, and does not resolve the children properly.

#4373 suggested rewriting imports, and that will probably work best here. So do `import unittest.case as _module_unittest_case` and then `SkipTest = _module_unittest_case.SkipTest` instead of the multiple attributes.

**Comment by huguesv** [comment]
I've set it to 15.8 because you mentioned yesterday that this is the cause of https://github.com/Microsoft/PTVS/issues/3802
It won't be really common for our users to not have Python, but it may be for VSC.
It does sound potentially risky, and if it is, we can drop from 15.8.
