### ISSUE TITLE
Signatures not merging properly with typeshed

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#4438]
The below signature comes partially from typeshed and partially from our analysis. We should be merging better than this.

![image](https://user-images.githubusercontent.com/1693688/41876120-ae482910-7881-11e8-9cda-8ba4307fb28b.png)

**Comment by zooba** [comment]
This was on Python 3.1, which does not have a `typing` module. That may be related

**Comment by huguesv** [comment]
Same result using Python 3.6
