### ISSUE TITLE
Unable to resolve relative imports in 15.8p2

### ISSUE THREAD

**Issue by rodrickmakore** [microsoft/PTVS#4441]
I am noticing a strange behaviour in PTVS intellisense. It seems Visual studio is unable to resolve dot sourced references. I am running a Flask project. Hovering my mouse over the Flask class name will freeze Visual Studio and becomes permanently unresponsive. 

![image](https://user-images.githubusercontent.com/2578638/41906968-b98eaba0-793f-11e8-9f34-1f044fb3c77f.png)

**Comment by huguesv** [comment]
The freeze on tooltips too large to fit the screen has been fixed by the editor team for Preview 4.
Things have changed quite a bit for imports since Preview 2, and I see different but still incorrect behavior. I'll investigate some more. Thanks!

**Comment by zooba** [comment]
[I just shortened and corrected the title so it's easier for us to track what needs work.]

**Comment by MikhailArkhipov** [comment]
There were several fixes made since. @rodrickmakore - does 15.9 work better for you?

https://github.com/Microsoft/PTVS/pull/4308
https://github.com/Microsoft/PTVS/pull/4496
