### ISSUE TITLE
Strange Test Explorer results when running test project seperatley

### ISSUE THREAD

**Issue by jmarshall9120** [Microsoft/PTVS#4466]
Test Explorer having odd functionality when testing python from a separate project. 

This may be a central bug, or it may be about using PTVS in a manner other than directed. 

I have a custom environment set up that is in a root directory, and a python app project in that same root directory.  When the interpreter is started in that enviroment it automatically adds the root directory to the os.sys.path via a .pth file.  In the root directory I also have a python test project.

I have my unit test set up so it sets the working directory to the "root directory\python app" right before running the test.  Here's the results i'm getting:

![pythontoolstestbug](https://user-images.githubusercontent.com/30184747/42067595-c43213d6-7afb-11e8-9440-2cc29c94fc06.png)

My Machine:
VS: 15.7.4
PTVS: 15.7.18156.1

**Comment by huguesv** [comment]
Thanks for the feedback.

Based on the screenshot, it looks like you have the following issues:
- Test remains in list when it no longer exists
- Test reports no source code

Are any of the test failures expected or do you consider them a PTVS bug?

I created a multi project solution with tests in a separate project, and I thought I might be able to repro the "no source available" but that didn't happen. I'm curious if the problem goes away if you close and reopen the solution?

Accuracy of test discovery (finding all tests and keeping it up to date) has been a constant struggle. It does seem to be better in 15.8. Earlier this week we did discover why we're updating it the tests more often than we should, and that could be the cause of inaccurate test lists.

**Comment by jmarshall9120** [comment]
I have been testing for a while now and have discovered a number of bugs based on this setup.  I'm going to submit several tickets focusing on each bug and close this one down, so I can provide more targeted information per issue.
