### ISSUE TITLE
Intellesense auto complete adds extra character to begining text

### ISSUE THREAD

**Issue by jmarshall9120** [Microsoft/PTVS#4552]
When working in the visual studio code editor using python, when i auto complete a word from intellesense using the tab key, it often leaves the first letter I typed leading the word.  In the case of some code like this:

`myString = "This is a string."`

If I type m afterward, see the intellesense recommendation and hit tab, I get this:

'mmyString'

It always seems to be leaving the first character I type behind regardless of completion.  Please let me know what I can do to provide more info on this.

**Comment by huguesv** [comment]
Thanks! We already have an issue tracking this: https://github.com/Microsoft/PTVS/issues/4436
