### ISSUE TITLE
Intellisense not working when using composed regex in Django url pattern

### ISSUE THREAD

**Issue by JeromeHXP** [Microsoft/PTVS#4557]
To reproduce:
1- Create a new Django web project
2- Update urls.py to something like:
```
...
base = r''

urlpatterns = [
    # Examples:
    url(base + r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
...
```
3- Save, close the solution and reopen
4- IntelliSense is not working any more. 

Same issue arrise if you use something like base.format(). But it does not happen if there is no "name" parameter in the url pattern, i.e.:
`url(base + r'^$', app.views.home)`

**Comment by huguesv** [comment]
This is crashing the analyzer process.

**Comment by zooba** [comment]
@huguesv Do you have a stack trace? This doesn't repro on master for me, and my best guess as to where it came from (`DjangoUrl.cs`) hasn't changed recently.

**Comment by zooba** [comment]
Ignore me - GitHub didn't refresh with yesterday's updates :)
