### ISSUE TITLE
I can't set indent guides in visual studio 2017.how can i fix it?

### ISSUE THREAD

**Issue by MightyWing** [Microsoft/PTVS#4558]
![vside-structurevisualizer](https://user-images.githubusercontent.com/7940696/42743969-54da7632-88fb-11e8-93c8-86b5b81b3a91.png)
I can't see or  set indent guides(Dotted, gray vertical lines) in visual studio 2017 for the python language.how can i fix it?

**Comment by huguesv** [comment]
Unfortunately, we don't have support for structure guide lines yet.

We have an issue for it already, so I'll close this as duplicate.
https://github.com/Microsoft/PTVS/issues/2459
