### ISSUE TITLE
IntelliSense completions don't reliably appear

### ISSUE THREAD

**Issue by qubitron** [Microsoft/PTVS#4560]
When using the PTVS IntelliSense in VS or VS Code (as a Language Server), completions don't reliably appear.

To reproduce, type any variable/symbol, then repeatedly type "." and backspace. Completions sometimes will not appear at all, the severity of the issue seems to vary greatly depending on the code and where IntelliSense is being used.

**Comment by zooba** [comment]
@AlexanderSher This is basically the same as the one you're already looking at for decorators, I believe. (At the very least, assume it is until you can show otherwise :) )

**Comment by AlexanderSher** [comment]
Not sure about that.

@qubitron , can you give a chunk of code to repro the bug?

**Comment by AlexanderSher** [comment]
Looks like it is a race between parser and completions. `ModuleAnalysis.GetMembers` calls `ExpressionEvaluator.Evaluate` before parsing is completed.

**Comment by qubitron** [comment]
This repros for me on any completion, but you can specifically use 
https://github.com/qubitron/intellisense-samples/blob/master/flask_sample.py line 6, remove everything after app and keep pressing "." followed by backspace. This is in VS Code, works for me about 5 times in a row, then fails 2-3 times, then works again.

**Comment by AlexanderSher** [comment]
Do you mean like this?
![image](https://user-images.githubusercontent.com/8933858/42824912-b6fe44d4-8995-11e8-9ca9-50283964fe64.png)

**Comment by qubitron** [comment]
Yep, and same approach works for any completion in that samples repo, at least for me on my windows and mac laptop

**Comment by AlexanderSher** [comment]
Yes, that's a race. It doesn't repro under debugger with this code, but I've found another case.
`VariableDef.Types` is empty when `InterpreterScope.GetMergedVariableTypes` is called.

@zooba , I'm not sure what is a proper fix here. Calling `await AnalysisQueue.WaitForCompleteAsync` at the beginning of `Server.Completion` doesn't guarantee that `VariableDef` won't change.

**Comment by zooba** [comment]
So we _should_ be accessing the old analysis here. When a change is made, the old analysis (chain of scopes) is kept against the current project entry and a new one is cloned, partially cleared, and used for generating the next set of results.

The `ExpressionEvaluator` calls should be using analysis units that are marked `ForEval`, and the scopes they resolve to should be the old scopes and give back results from there. I'm not sure why that wouldn't be happening - I can take a look later on today if you need?

**Comment by AlexanderSher** [comment]
It can be both old and new. I've caught the states inside the `Server.Completion` when `analysis` is equal to `entry?.Analysis` and when it isn't Adding `WaitForCompleteAsync` after `GetParseTree` makes bug harder to reproduce
```cs
            tree = GetParseTree(entry, uri, CancellationToken, out var version) ?? tree;
            await _queue.WaitForCompleteAsync();

            var analysis = entry?.Analysis;
```

But it doesn't fix it completely. We need an awaitable attached to a project entry that would allow us to wait for analysis to complete.

**Comment by AlexanderSher** [comment]
Correct me if I'm wrong, but in case of a dot, partial result means empty set. And previously completed analysis is based on the outdated parse, so completions maybe not partial but irrelevant.

Also, since `Analysis` property is updated before analysis has actually started, we can get incomplete analysis even if it is the old one.

**Comment by AlexanderSher** [comment]
Well, maybe that's not an issue at all? We're showing as many completions as we can at the moment when completions are requested. In this particular case, we haven't found any of them yet.

**Comment by zooba** [comment]
It sounds from Dan's description that we might be racing on the `Analysis` property? Adding/removing dots shouldn't reset everything badly enough.

What if it's triggering _another_ analysis while the previous one is running, and that's forcing it to publish too early?

**Comment by AlexanderSher** [comment]
It isn't a racing only on the `Analysis` property. The main problem is with the `VariableDef.Types` property that is accessed before it is set. If waiting for a full analysis is too much, we can wait for some small amount of time (e.g. 50ms) and only for analysis that is associated with this particular instance of `ModuleAnalysis`.
