### ISSUE TITLE
Tooltip cut off for IronPython overloads

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4584]
Better to be cut off than to hang VS due to not fitting on screen...
![image](https://user-images.githubusercontent.com/1696845/43029070-7e22cffe-8c38-11e8-9f09-6e151b5f7075.png)

**Comment by gramster** [comment]
Hugues, can we close this? It sounds like its a minor annoyance only and not something we need to address?

**Comment by huguesv** [comment]
Given we don't get completions on IronPython anymore, might as well close it.
