### ISSUE TITLE
No completions returned from LS in following code using pandas

### ISSUE THREAD

**Issue by shengyfu** [Microsoft/PTVS#4590]
import pandas as pd
pd_total_file = pd.read_csv('../test.csv')
pd_total_file.

**Comment by zooba** [comment]
See #3046 

This will probably need some type hints to be added for `read_csv`, either as a contribution by us or a third-party.

**Comment by qubitron** [comment]
Would be nice to have a bug that tracks resolution of this specific case, it has come up multiple times #4001, #4428 and was not resolved by #3046
