### ISSUE TITLE
Performance static analysis errors in analysis project

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4593]
Don't know if these need to be arrays for some reason, we can suppress CA1819 on all 3 if that is the case.

```
Python\Product\Analysis\LanguageServer\Settings.cs(29,0): Error CA1819: Microsoft.Performance : Change 'LanguageServerSettings.PythonAnalysisOptions.disabled' to return a collection or make it a method.

Python\Product\Analysis\LanguageServer\Settings.cs(26,0): Error CA1819: Microsoft.Performance : Change 'LanguageServerSettings.PythonAnalysisOptions.errors' to return a collection or make it a method.

Python\Product\Analysis\LanguageServer\Settings.cs(28,0): Error CA1819: Microsoft.Performance : Change 'LanguageServerSettings.PythonAnalysisOptions.information' to return a collection or make it a method.
```

**Comment by AlexanderSher** [comment]
I'd let @MikhailArkhipov take a look at it, but from performance point of view, arrays are better choices because of the way `foreach` loops are compiled for them.

**Comment by zooba** [comment]
These are also meant to serialize directly to/from JSON, so having them as arrays captures this more clearly (i.e. we really don't want them to be some clever list type hiding behind an interface). I'd vote to just suppress the warnings.
