### ISSUE TITLE
Microsoft.PythonTools.Analysis.SingleDict is a mutable struct

### ISSUE THREAD

**Issue by AlexanderSher** [microsoft/PTVS#4596]
It should be either converted into class or made immutable.
Maybe related to the #4560

**Comment by zooba** [comment]
As I recall, this was one of the important ways we used to reduce memory usage. Be careful that changing it does not regress this significantly.

Also, it should never actually be used anywhere except as a field. Perhaps adding an analyzer to check this at compile time would be a better way of ensuring it is used safely without affecting runtime characteristics?
