### ISSUE TITLE
Collections module works in 2.7 but not in 3.6

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/PTVS#4613]
3.6
```python
import collections
collections.deque(). #<- nothing
```

2.7
![image](https://user-images.githubusercontent.com/12820357/43804633-8dea3b62-9a51-11e8-9d19-f79bf5155a27.png)

Might be b/c typeshed `typeshed\stdlib\3\collections\__init__.py` vs `typeshed\stdlib\2\collections.pyi`

**Comment by zooba** [comment]
Looking at what we generated for `_collections`, we probably need to ensure the types are fully defined and not simply referenced. There's already a set of exceptions in `scrape_module.py` for these (where a type is defined in C but lies about its package), so adding the types imported from `collections` in the current generated file should make sure they have full definitions.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/13
