### ISSUE TITLE
Visual studio 2015, 3.6 enviornment cant import openssl

### ISSUE THREAD

**Issue by sb07** [Microsoft/PTVS#4629]
The interpreter works outside visual studio, when i do interactive python inside VS it will import.

I tried repairing and reinstalling, i downgraded python tools that did not solve. VS 2017 not option. Id post some type of log file but i dont know how. I tried clicking the link that says before posting/contributor and it mentions code of conduct, but i didnt see a quick, logging.

I have 2.7 working fine inside VS but the additional 3.6 not working, has worked in past.

Its able to import other libraries, example nltk.

**Comment by zooba** [comment]
You say "VS 2017 not option" - does that mean you're on an older version? Just to set expectations, we usually only fix bugs in the latest release.

If you can post a few screenshots of what you're typing and what you're seeing, that will help us get started.

**Comment by sb07** [comment]
I made a 90 second video: https://github.com/sb07/video-for-zooba/blob/master/outputFile.avi

Yes older version, thought maybe someone knows a quick fix. Id rather pay for 2017 license then get community edition, but i dont generate enough from my work.

**Comment by zooba** [comment]
It looks a bit like the break in the debugger is a false positive, and that you simply ought to continue running past it. Perhaps you have set the flag to always break on ImportError?

**Comment by sb07** [comment]
That was precisely the issue. continuing running runs the script.

Under Tools>>Options>>Python Tools>>Debugging

the last field 'Enable debugging of the standard python library' is by default not checked.

When it is checked this false positive is presented, if you import certain library like requests.

**Comment by huguesv** [comment]
Glad you got it figured out!
