### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by frank-ozgul** [Microsoft/PTVS#4643]
Prior to the 15.8.0 version, my code had no problem with cv2 and numpy imports. I have problem now. The code editor does not recognise these libs. I can get these libraries in the interactive environment though. I have tried to refresh the DB many times, but with no luck. Any suggestions for solving the problem.  I am working on Wİndows 10 environment with Python 3.6.6.

**Comment by zooba** [comment]
Please go to Tools, Options, Python, Experimental and enable "Use new style IntelliSense for environments".

Our old database-based system is deprecated and will be removed completely in the future, so we are not looking to address issues in it. Despite the option remaining under "Experimental", we recommend using the new approach that does not rely on a database.

**Comment by frank-ozgul** [comment]
Thank you for the reply. I had actually tried that prior to uploading my problem here after reading about it in product site.. It had not worked then. However, it works now. probably shutting down my system and booting it up again made it work now.

**Comment by frank-ozgul** [comment]
A second problem: During debugging, the break point is not hit.  It once found the first break point and did not see the rest. But now all fail. I have tried also ticking  the legacy debugging choice  from Python Debugging window but with no success. Any suggestions?

**Comment by huguesv** [comment]
Good to hear you have it working. I'll close this then.

**Comment by Hyperlooper** [comment]
The new system doesn't work. I get no autocomplete suggestions for anything with it.

**Comment by huguesv** [comment]
@Hyperlooper please check https://github.com/microsoft/PTVS/issues/5213 to see if the missing files issue is what you are running into.

If that's not it, please add details on your Python environment and VS version to https://github.com/microsoft/PTVS/issues/5214, as well as a code repro if possible.

thanks
