### ISSUE TITLE
Brace completion cannot be disabled in REPL

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#4655]
When you disable brace completion for Python editors, it still works in the REPL.

(This may need to be passed on to the Roslyn team to fix in the interactive window.)

**Comment by r3m0t** [comment]
If you disable it for all languages, then it is disabled in the repl.

Looks like the option check is done on the text view, and the text view is not given the python content type so doesn't receive its settings? https://github.com/microsoft/PTVS/blob/868592d6e662f7a2eb12d2f49bac4ba67ba279bf/Common/Product/ReplWindow/Repl/ReplWindow.cs#L258-L261

**Comment by r3m0t** [comment]
This can be fixed by ReplWindow.OnCreate:             // we check the user's option in BraceCompletionContextProvider. That way, we don't need to set this
            // again whenever user options change.
            textView.Options.SetOptionValue(DefaultTextViewOptions.BraceCompletionEnabledOptionId, true);


and then checking PythonToolsPackage.LangPrefs.BraceCompletion in the BraceCompletionContextProvider
