### ISSUE TITLE
New style IntelliSense does not work for Python 2.7 environment

### ISSUE THREAD

**Issue by Tim-Sobolev** [Microsoft/PTVS#4664]
Windows 7 x64 SP1, Visual Studio Community 15.8.1, Python 2.7.15, single Python file or file in project

"Use new style IntelliSense for environments" checkbox is on:

- Nothing happens for file when current is Python 2.7 environment.
- File is processed when current is  Python 3.6 environment.

When checkbox is off, IntelliSense starts working properly for Python 2.7 environment.

In Visual Studio Community 15.7.6 new style IntelliSense was working properly.

**Comment by huguesv** [comment]
Thanks for the feedback. This is likely the same as https://github.com/Microsoft/PTVS/issues/4660 where `Microsoft.PythonTools.Analyzer.exe` is crashing during initialization.
