### ISSUE TITLE
Incorrent encoding error meessage

### ISSUE THREAD

**Issue by Leeyxin** [Microsoft/PTVS#4665]
Create a new Python file with Chinese comment in it.

Add: # -*- coding:UTF-8 -*-
And the error message here:

`file has both Unicode marker and PEP-263 file encoding.  You must use "utf-8" as the encoding name when a BOM is present.`

While the file has no BOM at all.
Also the parse seems not work well with "UTF-8" as the encodig name.

**Comment by huguesv** [comment]
Thanks! Same root issue as https://github.com/Microsoft/PTVS/issues/4433
