### ISSUE TITLE
Unable to import numpy and many other libraries in visual studio

### ISSUE THREAD

**Issue by danish199** [microsoft/PTVS#4671]
I an unable to use python library numpy. As i am a beginner, I install python using anaconda and there is numpy package installed in anaconda environment, but when i try to import it in  visual studio it says that there is no such module.
![capture](https://user-images.githubusercontent.com/41705509/44398342-f6bdac80-a55c-11e8-82d8-1f509d8a87b4.PNG)

**Comment by huguesv** [comment]
From the screenshot, it looks like Anaconda 5.1.0 is not the default Python environment, so IntelliSense is probably giving completions for another environment you have installed which doesn't have numpy.

You can either
- Set Anaconda as the active environment for your project
- Change the default environment to be Anaconda (by clicking "Make this the default environment for new projects" hyperlink in the Python Environments window)

For more information on managing environments, please see https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio
