### ISSUE TITLE
LSC: Implement format on type

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/PTVS#4694]
Implementation can be borrowed from 
https://github.com/Microsoft/vscode-python/blob/master/src/client/formatters/lineFormatter.ts

- translate to C#
- change it to use LS tokenizer
- augment with knowledge of the AST where appropriate (such as checking if `=` is inside function arguments)

See also https://github.com/Microsoft/vscode-python/issues/1799

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/python-language-server/issues/5

**Comment by MikhailArkhipov** [comment]
PTVS part is handle Enter and actually invoke formatting

**Comment by huguesv** [comment]
This is implemented by language server client and it almost works - colon and semicolon trigger formatting, but enter doesn't. Filed details in internal bug 998976.

**Comment by huguesv** [comment]
Verified that the VS fix now works correctly.
