### ISSUE TITLE
LSC: Implement document formatting for Black/Pep8/Yapf

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/PTVS#4698]
VS UI part of https://github.com/Microsoft/python-language-server/issues/10
- check which ones are installed, show list in Tools | Options, perhaps implement install on use like VS Code extension does.

**Comment by huguesv** [comment]
Will now be done entirely in VS.

**Comment by huguesv** [comment]
Large portion of this is done and working. I filed smaller issues for the remaining work.
