### ISSUE TITLE
Migrate Doc Page From CodePlex: Pyvot

### ISSUE THREAD

**Issue by crwilcox** [Microsoft/PTVS#47]
Move page from [CodePlex](https://pytools.codeplex.com/wikipage?title=Pyvot) to https://github.com/Microsoft/PTVS/wiki/Pyvot

**Comment by crwilcox** [comment]
Pyvot is not maintained anymore and will not be ported

**Comment by zooba** [comment]
Pyvot should get its docs on RTD, I think they're all ReST...

**Comment by huguesv** [comment]
Yeah, you could point directly to https://pythonhosted.org/Pyvot/tutorial.html from our docs index page.

**Comment by zooba** [comment]
The PyPI page points to them (as I just discovered), but the only thing we could add is that it's basically deprecated. I'm happy to just ignore it.

**Comment by crwilcox** [comment]
I ended up removing this from our index as it is deprecated.  If either of you feels strongly that it be included still, feel free to add a link back to the RTD page.
