### ISSUE TITLE
Adding the word Todo in comments breaks Intellisense

### ISSUE THREAD

**Issue by mzxrules** [Microsoft/PTVS#4704]
Using Visual Studio 15.8.3.

Add the comment `# todo` or `# Todo` on any line of code. Insert a semicolon somewhere illegal, like class MyClass;(object): or so, then delete the semicolon. When the semicolon is deleted, the errors will persist until the todo comment is deleted

Edit: the word Hack is also affected. Possibly related to this?:
 
https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs#L203

**Comment by huguesv** [comment]
Thank you for the report.

I've verified that this has been fixed in master (dev16). PR for the fix was https://github.com/Microsoft/PTVS/pull/4573
