### ISSUE TITLE
sys.exit(0) throws exception in VS 2017 Community with Python 64 bit 3.6

### ISSUE THREAD

**Issue by CodeArc13** [microsoft/PTVS#4713]
I have been looking for a solution to this annoying problem for a day or so now,
the code I am running is a project that I wrote a few months ago and used to work in python on visual studio, which I have since updated and am guessing has changed a lot. I am using VS 2017 Community with Python 64 bit 3.6 all fully updated in the VS installer.

Now for some reason, I get exactly the same error as here https://github.com/Microsoft/PTVS/issues/888
I get the problem this person has with his own code where the option "Break on SystemExit exception with exit code of zero" is cleared and it still breaks with the exception.

I can generate the exception easily with the following code, so I am pretty sure it is nothing to do with my code unless I am missing something new.
```
import sys 
sys.exit(0)
```
My projects code used to work with no arguments but now for some reason needs a 0 or raises a further exception for not allowing a none type.

Thankyou

**Comment by huguesv** [comment]
Thank you, and sorry for the delay confirming both bugs.

The reason they suddenly started to occur is that we made the new debugger the default in 15.8, and these are things we didn't catch yet in the new debugger implementation.

I filed these issues on the ptvsd tracker:
https://github.com/Microsoft/ptvsd/issues/840
https://github.com/Microsoft/ptvsd/issues/841

**Comment by CodeArc13** [comment]
Thank you.  I hope it gets fixed soon, it's so annoying seeing this error everytime I stop running my code.

**Comment by CodeArc13** [comment]
So I just updated to VS 2017 15.8.6 and this bug still isn't fixed :( https://i.imgur.com/ZPaTUJv.png

**Comment by huguesv** [comment]
Sorry, the type error has been fixed. It looks like that might be public too, because the September release is done. If you install ptvsd into your environment. you should be able to see the improvement.
The other bug is VS only, so unfortunately lower priority for them right now.
If the fix require changes in VS, then it won't happen until dev16.

**Comment by CodeArc13** [comment]
ok thankyou!

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/362033/sysexit0-gives-us-an-error-instead-of-exit.html
