### ISSUE TITLE
Failed to launch debug adapter

### ISSUE THREAD

**Issue by weihangChen** [Microsoft/PTVS#4725]
The the issue as described in this [post ](https://github.com/Microsoft/PTVS/issues/4270#issuecomment-392965960) comes back. I was able to do remote debugging using visual studio version 15.7.2 and ptvsd 3.2.1 until I update visual studio to version 15.8, then it stops working with ptvsd 3.2.1 even I checked the option using "legacy python debugger". Then I tried to make ptvsd 4.1.1a9 works with 15.8, but only gets the error "Failed to launch debug adapter"

**Comment by huguesv** [comment]
The only change that would affect the old debugger in 15.8 compared to 15.7 is that we 'reverse' the meaning of the option from "use experimental debugger" to "use legacy debugger". If you've restarted VS after changing the option and double-checked that you have ptvsd 3.2.1 in the dockerfile, than that should work.

If you see an error that points to something wrong in the json, then that is usually a sign of the wrong ptvsd being installed. It's not seeing the protocol that it expects according to the "use legacy debugger" option.

**Comment by weihangChen** [comment]
you are right, I checked the "use lagacy debugger" then 3.2.1 is working again, thanks!
