### ISSUE TITLE
Tests are not removed from test explorer after test is deleted

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#4728]
Create new project
Add 2 test files, one with test_A, other with test_B
Open test explorer
Close and reopen solution
Delete all code from test_B and save
Delete test_B's file

Result: Test explorer is not updated to remove the deleted test. Running it results in test failure (not able to load the test).

**Comment by zhouwangyang** [comment]
If the tests was renamed, the test name in Test Explorer should be renamed, but it was not.

**Comment by huguesv** [comment]
Fixed for 16.3.
