### ISSUE TITLE
New IronPython projects can't detect default Python environment

### ISSUE THREAD

**Issue by najahnasir** [Microsoft/PTVS#4743]
I have Python 2.7 and IronPython 2.7.8 installed on Visual Studio 2013. I have tried making either the default environment but when I create a new IronPython project, it wasn't able to detect the default environment. The new projects were always created with Unknown Python 2.7 being set as its Python environment.

**Comment by najahnasir** [comment]
Does this mean that I have to manually set the environment everytime a new IronPython project is created? I did try making Python 2.7 the default but results are the same (default environment not detected)

**Comment by huguesv** [comment]
Yes, I believe so. The IronPython project templates have an active environment already set, unlike most other templates. That was done to make it more obvious that it won't run with any other env (with the exception of a custom env like you are doing). If you make your custom env the global default for new projects, you can right click and remove the env that is marked as missing when creating a new project, and that will make it use the default.

**Comment by najahnasir** [comment]
I see. Thank you for your help.
