### ISSUE TITLE
Installer does not detect VS2017

### ISSUE THREAD

**Issue by kdschlosser** [Microsoft/PTVS#4744]
msi installer:

    PTVS 202.2.6 VS 202015.msi

from release page
 
> PTVS 2.2.6 requires Visual Studio 2015 Community or higher

It states or higher.. I would hazard a guess this is supposed to work for VS2017

The installer will not allow installation when VS2017 is installed. It states that VS2015 cannot be found

**Comment by huguesv** [comment]
The "or higher" part means Pro and Enterprise, but I agree it's not clear.

If you want to install Python support in VS 2017, please select the Python workload from the VS installer. There's no separate msi to install.

Hope that helps!

**Comment by kdschlosser** [comment]
Yup figured that out. 
When you issue a release it also propagates to the VS 2017 installer?

**Comment by huguesv** [comment]
Correct.
