### ISSUE TITLE
Performance is bad in virtual env page when "Base interpreter" is IronPython or Anaconda

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4781]
To 2.7 64-bit: about 49s 
To 2.7 32-bit: about 39s 
To Anaconda 5.3.0 (3.7, 64-bit): about 30s

**Comment by qubitron** [comment]
Let's remove Anaconda as a base for virtual environment from the list.

**Comment by huguesv** [comment]
@RaymonGulati1 see `AddVirtualEnvironmentView.ResetProjectDependentProperties` and `CondaUtils.IsCondaEnvironment`
