### ISSUE TITLE
Move/rename the corresponding *.pyc file at the same time when moving/renaming the *.py file

### ISSUE THREAD

**Issue by ramiabughazaleh** [Microsoft/PTVS#48]
Thank you for PTVS.

I would like to request that PTVS move/rename the corresponding *.pyc file at the same time when moving/renaming the *.py file.

For example, given the following project structure:
```
package1
    __init__.py
    A.py
package2
    __init__.py
testPackage
    __init__.py
    testA.py
```

testA.py:
```python
import unittest
from package1.A import A

class TestRoutes(unittest.TestCase):

    def testA(self):
        A = A()
        print A.Name

if __name__ == '__main__':
    unittest.main()
```
And then if I move A.py to package2, but don't update the from/import statement, and run the test, I expect the test run to fail with an error like "ImportError: No module named A".

However, it succeeds without error (unexpectedly)!

Even cleaning the solution does not resolve the issue because the *.pyc doesn't get deleted during a clean.

Thank you.

**Comment by zooba** [comment]
Nice, I like it.
