### ISSUE TITLE
Build on VSTS fails with "Cannot write lines to CoreCompilerInputs.cache"

### ISSUE THREAD

**Issue by OsirisTerje** [microsoft/PTVS#4810]
I have a  project with 2 C# projects and one python project.  Building in VS goes fine, but building on VSTS/AzureDevops fails, with the message 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3430,5): Error MSB3491: Could not write lines to file "obj\Release\vmtools.pyproj.CoreCompileInputs.cache". Could not find a part of the path 'D:\A1\_work\243\s\vmtools\obj\Release\vmtools.pyproj.CoreCompileInputs.cache'.

Process 'msbuild.exe' exited with code '1'.`

The solution is set to build in Release/AnyCPU

Looking in the Microsoft.Common.CurrentVersion.targets file, I see this is caused by the _GenerateCompileDependencyCache target:
![image](https://user-images.githubusercontent.com/203432/47388528-b9b79700-d712-11e8-9406-7a96ae4b5820.png)

Is there anything in the project setup that can be changed to make this work?
Since the Python program is not really compiling anything, is there any need for this target at all?
Any other workarounds ?

**Comment by ChrisMenegay** [comment]
I'm having the same issue as Terje.  Hey Terje! did you find a workaround?

**Comment by ChrisMenegay** [comment]
I found a workaround that works for me.  In my pyproj file I added the below which makes sure the obj directory exists.  You could of course create it another way, but I needed to copy those files there anyway.  I was previously doing it on the corecompile:

  <Target Name="BeforeBuild">
    <Copy SourceFiles="@(Compile)" OverwriteReadOnlyFiles="true" DestinationFolder="$(PublishFolder)obj\$(Configuration)" />
    <Copy SourceFiles="@(Content)" OverwriteReadOnlyFiles="true" DestinationFolder="$(PublishFolder)obj\$(Configuration)" />
  </Target>

**Comment by zooba** [comment]
Right. The other thing that could be done is to add this to your project after all other `Import` elements:

```xml
  <Target Name="PrepareForBuild">
    <MakeDir Directories="$(OutDir);$(IntermediateOutputPath);@(CreateDirectory)" ContinueOnError="True"/>
  </Target>
```

But there isn't really a need for that target. I'm not sure why it's being run for you.

**Comment by judej** [comment]
@ChrisMenegay, please reopen if the work around is not satisfactory

**Comment by mamift** [comment]
I just want to mention to those that might come across this; this issue can also be caused when you open VS on a sln file or project folder where the NTFS permissions give your user read permissions, but not write permissions. Adding explicit write permissions fixes it. This can be the case when you're running VS on a [self-hosted build server ](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops) and is controlled by the azagent process.
