### ISSUE TITLE
Activate conda environment on launch, python install, etc

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4820]
Conda environment with python 3.7 and numpy fail to load the dll when running the conda environment's python.exe without first activating the conda environment.

This didn't happen before (with Python 3.6).

We will have to activate conda environment before we launch, and anywhere we run the python interpreter (like install packages, profiling).

**Comment by joseortiz3** [comment]
This error also occurs in Visual Studio Code by the way.

**Comment by huguesv** [comment]
There's a workaround of activating the environment from command prompt and starting VS from that prompt. See https://github.com/Microsoft/PTVS/issues/4874 for details.

**Comment by huguesv** [comment]
Just had a conversation regarding VS Code which is in the process of re-implementing activation.

Since we'll probably want to support pipenv at some point, and that's a problematic scenario (more later), we'll probably want to do the following, which is what VS Code will be doing:

- First time user wants to run code against an environment, we do the activation, print out all environment variables and parse them.
- Start the interpreter exe by specifying the environment variables that were parsed earlier (and merge with any that are set in project settings, etc)

The problem that they discovered with pipenv is that it's only possible to active a pipenv environment by requesting a shell.

Another problem is that activation can be slow, and they do things like linting and formatting in the background, which runs the interpreter exe (so should be activated). That's why the capture of environment once (per VS session) may be the best choice.

**Comment by huguesv** [comment]
Using conda 4.5.12, creating a conda environment will also fail because the base is not activated prior to calling conda create. Activating the base adds directories to PATH.
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2>
Solving environment: ...working... failed
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))
```
