### ISSUE TITLE
ptvsd 2.2.0b1 and ptvs 2.2rc2 not connecting

### ISSUE THREAD

**Issue by kdriedger** [Microsoft/PTVS#484]
Apparently, a regression as I've attached to process using ptvs 2.2rc and ptvsd 2.2.0b1 but after upgrading to ptvs 2.2rc2 I can no longer attach.  Subsequently downgraded to ptvs 2.2rc2.

Any hints on debugging the debugger connection (i.e. ptvsd).  Drop down to pdb (Python Debugger)?  There doesn't appear to be any other process using port 5678 ( `netstat -an ` )

Here's my `pydevd_startup.py`

    import json 
    import sys 

    print "starting... pydevd_startup.py"
 
    if ':' not in config.version_id: 
      # The default server version_id does not contain ':'  
      sys.path.append("lib")  
      import ptvsd  #ptvsd.settrace() equivalent  
      ptvsd.enable_attach(secret = 'joshua')
      print "Hey World, eh"
      print "tcp://joshua@localhost:5678"

      ptvsd.wait_for_attach()

      if ptvsd.is_attached:
          print "Attached debugger, eh"

My startup file: `C:\Program Files\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\gcloud\gcloud.py`

Script arguments:
`preview app run app.yaml --python-startup-script "pydevd_startup.py" --max-module-instances="default:1"`

**Comment by int19h** [comment]
There has been a protocol change between RC and RC2, but we didn't update ptvsd on PyPI. I'll do that shortly. In the meantime, if you use the copy of ptvsd that comes installed with PTVS (it's in "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2" - adjust as needed for your system), it should all work.

**Comment by int19h** [comment]
PyPI now has the up-to-date version. Sorry for the inconvenience!

**Comment by kdriedger** [comment]
Thanks, looking forward to trying it out.   How do you debug the ptvsd?  When I was getting it going on another developer box, the port 5678 was being used and seeing if I had specified the port correctly was difficult.

**Comment by kdriedger** [comment]
Is there a way to detect the old protocol vs. the new protocol and report something on the console?  or is this just a transitional problem and it shouldn't occur again.

**Comment by int19h** [comment]
It has a version check that should give the appropriate message - the problem is that I forgot to update that version when doing the last protocol update :(

**Comment by int19h** [comment]
When it opens the port, it uses standard Python socket functions to do so. So if it can't open, it should cause an exception that'll bubble up all the way to your code.

Note, though, that it uses the flag that lets it take over the port if it has permissions to do so (because we have found out that, if the debuggee process crashes, the port would remain open on Linux, preventing you from reusing it without waiting for several minutes for it to time out). So if you're not seeing an error, it's likely that ptvsd had simply successfully hijacked the port for itself.
