### ISSUE TITLE
How to register external threads?

### ISSUE THREAD

**Issue by SamtFischer001** [Microsoft/PTVS#4857]
The function “ptvsd.debugger.new_external_thread()” no longer exists. Is there another way to register an external thread?

**Comment by huguesv** [comment]
For ptvsd 4.x questions, I'd recommend asking at https://github.com/Microsoft/ptvsd/issues since the ptvsd devs don't hang out here as much anymore. Thanks!

**Comment by SamtFischer001** [comment]
Ok.
