### ISSUE TITLE
Launch with errors - invisible errors after switching from python 3.x to python 2.x

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#486]
PTVS Dev 2015-06-19 VS 2015

Create new console app
Add 2 python environment: 2.7, 3.4
Make 3.4 active
type following code:
```
print "hello"
```
Press F5, you'll be prompted to launch with errors, say no
Make python 2.7 the active environment
You'll see the squiggles go away
Press F5, you'll still be prompted to launch with errors!
Close and reopen file doesn't get rid of it
Close and reopen solution gets rid of it

**Comment by zooba** [comment]
Ah, I'd wondered where that was coming from.

Looks like we have one more warning to clear when we change environment.
