### ISSUE TITLE
Start with/without debugging no longer starts web browser

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4867]
F5 on flask, django or bottle project no longer starts the web browser like it used to.

Probably something that changed on the VS side.

**Comment by RaymonGulati1** [comment]
Unable to reproduce in the latest version of VS and PTVS built from master. Issue may have been caused by VS and updating to latest VS fixes it.

**Comment by RaymonGulati1** [comment]
Problem with the windows registry key. Nothing we can do in PTVS to solve it.
