### ISSUE TITLE
Python background analyzer always at 30% CPU utilization

### ISSUE THREAD

**Issue by maxrossi** [Microsoft/PTVS#4870]
Using custom Python 2.7 environment

**Comment by huguesv** [comment]
Some infinite analysis bugs were fixed for 16.0 Preview 1 (out now) and many more analysis fixes are on the way for 16.0 Preview 2, as we are starting the work to reintegrate the forked python language server back into PTVS.

Unfortunately, without your exact code, it is hard to say whether it is fixed or not.

If you get a chance to try your code in latest VS Code (with JediEnabled=false), or 16.0 Preview 1, and the infinite analysis issue is gone, please let us know.

**Comment by huguesv** [comment]
For 16.0 Preview 4, we've updated the Python language server with a version that has had several bug fixes in them. If you still experience this issue in 16.0, (Preview 4 or later), please open an issue, including details on how to reproduce. Thanks.

**Comment by maxrossi** [comment]
Same problem here still with 16.6.5
