### ISSUE TITLE
debugger with jupyter notebooks loading python scripts

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#4871]
I was debugging an issue within a Python script loaded in a Jupyter Notebook, ipython kernel. I found that vscode was not even able to debug this via attaching to the ptvsd server.

PTVS 2017 was able to attach to the ipython process that loaded this script (even without ptvsd) and I successfully debugged and fixed this script!

This is just a big thank you to the group and not an actual issue :)

But still waiting for these improvements:

https://github.com/Microsoft/PTVS/issues/94
https://github.com/Microsoft/PTVS/issues/774

**Comment by huguesv** [comment]
Thanks! I'll close this as there's no actionable item other than the linked issues which are still open.
