### ISSUE TITLE
Create a Python extension for C#...?

### ISSUE THREAD

**Issue by blueincmultimedia** [microsoft/PTVS#4872]
I see there are lots fo ways to use Python as the base and C++ as the extension but I am wondering: Is it possible to create something similar but using Csharp as the base and Python as the extension?
Here's what I mean: I'm developing an AddIn for ArcGISPro. Previously, in my python addin for ArcGIS 10.6, I use a great method to handle code changes on the fly: I use the regular python addin code (let's call it the 'pythonButtonWrapper') to:

- import a pythonModule.function code that runs when a particular button is clicked;
- 'recompile' that pythonModule code on the fly and;
- handle the button clicks, telling the pythonModule code what button was clicked.

The pythonModule code then takes over execution. It works great. Because I recompile the pythonModule code on the fly, I can code the functionality into the pythonModule code and never have to touch the pythonButtonWrapper. It never changes (unless of course I add new buttons, etc).
ArcGISPro uses Csharp for its addin code and I can generate a 'CsharpButtonWrapper' for it.
My question: how can I preserve the same functionality, calling my PYTHON module code functions from the 'CsharpButtonWrapper' that I get with VS 2017, passing in the button clicks? The last thing I want to do is translate all of the python module's code functionality into C#! Note: I've found lots of online example code that calls python.exe from C# but that's not what I want to do. I need access to the python module functions themselves, likely through a module.dll(?)
Thanks in advance for your helpful response,
Brian
(Thanks @kraigb for pointing me in the right direction :-)

**Comment by blueincmultimedia** [comment]
Thanks for your response. I will look into IronPython further as it seems I have access to it, or at least some form of it. It's a bit difficult as I'm restricted to what I can do on a government server. I've been hunting high and low for a tutorial that would show me how to do what I want but to no avail so far. I'll have to do some baby-step tutorials and work myself up to it, unless of course you could point me to a tutorial on this specific issue?
Thanks again,
Brian
![image](https://user-images.githubusercontent.com/8256033/48911818-b5bd8880-ee28-11e8-998d-42b0c306c7a4.png)

**Comment by int19h** [comment]
This might be a bit dated in places, but it should be possible to get it to work with minor obvious tweaks. I think it covers exactly what you want - how to load a Python module from C#, and use functions and classes in it via `dynamic`. 

https://blogs.msdn.microsoft.com/charlie/2009/10/25/running-ironpython-scripts-from-a-c-4-0-program/

**Comment by blueincmultimedia** [comment]
Brilliant! Thanks so much. 
I've been investigating and I don't think the government install of VS2017 is configured properly. At least I'm on the right track now! Thanks so much,
cheers...B

**Comment by kraigb** [comment]
@blueincmultimedia Glad you found the answers you needed, and Pavel, thanks for helping out!

**Comment by blueincmultimedia** [comment]
I've set up my home development with VS2017 and ArcGIS Pro to have the flexibility outside government confines to work on this project.
IronPython seems to be the way to go and I have the example working perfectly, doing exactly what I originally asked: doing method calls to my python scripts from C#, so thanks again Pavel for your help.

The issue now is that the python code that the button runs imports some specific ArcGIS modules like arcpy, pythonaddins etc that IronPython just does not recognise. I've tried adding them in my C# wrapper to the System searchpaths using:
```
            ScriptEngine pythonEngine = Python.CreateEngine();
            System.Diagnostics.Debug.WriteLine("Search paths:");
            ICollection<string> searchPaths = pythonEngine.GetSearchPaths();
   
            searchPaths.Add("C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3");
            searchPaths.Add("C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib");
            searchPaths.Add("C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages");
            pythonEngine.SetSearchPaths(searchPaths);

            foreach (string path in searchPaths)
            {
                System.Diagnostics.Debug.WriteLine(path);
            }
            System.Diagnostics.Debug.WriteLine("*");

            var ipy = Python.CreateRuntime();
            dynamic test = ipy.UseFile("test.py");  //********** fails on: no module named arcpy
            test.printHello();
```

How do I get IronPython to recognise my python's arcpy module?

Thanks again in advance for your help,
Brian

**Comment by int19h** [comment]
IronPython is Python 2.x, and you're trying to add a Python 3 module, which is probably the issue here. 

In general, I have no idea about ArcGIS, but you might be in the "If your module requires Python 3, or is not compatible with IronPython" category I mentioned earlier - if so you should rather look into Python.NET.

**Comment by denfromufa** [comment]
@blueincmultimedia you may be interested in this blog post about ArcGIS and pythonnet:

https://tereshenkov.wordpress.com/tag/pythonnet/

**Comment by blueincmultimedia** [comment]
> @blueincmultimedia you may be interested in this blog post about ArcGIS and pythonnet:
> 
> https://tereshenkov.wordpress.com/tag/pythonnet/

@denfromufa Thanks for this but it does the exact opposite from what I need, I think: that link is about calling C# from Python but I need to call Python from C#. Thank you anyway; I do appreciate it.

**Comment by blueincmultimedia** [comment]
> IronPython is Python 2.x, and you're trying to add a Python 3 module, which is probably the issue here.
> 
> In general, I have no idea about ArcGIS, but you might be in the "If your module requires Python 3, or is not compatible with IronPython" category I mentioned earlier - if so you should rather look into Python.NET.

@int19h Thanks, I guess I will have to. It's so frustratingly close right now! lol. I feel like if perhaps I could find a way to add the Python env that ArcGIS uses (they bundle their own version with ArcGIS Pro that has arcpy, etc in it) and add that to...IronPython's IRONPYTHONPATH environment variable(?) or something.... I know, grasping at straws now...

**Comment by denfromufa** [comment]
@blueincmultimedia pythonnet works the other way too - you can embed CPython in C# app using pythonnet. The syntax is different from IronPython.

You cannot mix ArcGIS CPython and IronPython unless you setup out-of-process calls. These are 2 totally different Python runtimes.

**Comment by gramster** [comment]
I think you have already moved away from the IronPython approach which is good because supporting it is no longer a priority for us given low usage and the fact that there are alternatives that work with Python 3.

(I am briefly reopening and closing this issue as our data warehouse is still showing this issue as open, and I want to trigger another close event to avoid this showing up in active issue queries).
