### ISSUE TITLE
Need to activate Anaconda 5.3 environment prior to launching interactive ipython console

### ISSUE THREAD

**Issue by MNRK01** [Microsoft/PTVS#4874]
I'm certain that this issue has been reported in various forms, but I can't find it in the form that affects me the most. So, I am creating a new issue for it.
```
OS: Win 10
Visual Studio: 15.9.2 with "R Tools for Visual Studio"
Anaconda: 5.3.0
Python: 3.7.1
```
When I start Visual Studio by clicking the Start Menu icon and attempt to start an interactive ipython console, I get the following error which is due to inability to find the path to some DLL(s):

```
Anaconda 5.3.0 interactive window [PTVS 15.9.18254.1-15.0]
Type $help for a list of commands.
>>> 
Error using selected REPL back-end:
DLL load failed: The specified module could not be found.
Using standard backend instead
>>> 
```

When I start Visual Studio from a cmd.exe prompt as follows:

```
Microsoft Windows [Version 10.0.17134.407]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\MNRK01>c:\PATHTO\Anaconda3\Scripts\activate.bat

(base) C:\Users\MNRK01>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe"

(base) C:\Users\MNRK01>
```

or by using the following batch file:

```
@ECHO OFF

REM add conda PATHs to the system path
PATH=C:\PATHTO\Anaconda3;C:\PATHTO\Anaconda3\Library\mingw-w64\bin;C:\PATHTO\Anaconda3\Library\usr\bin;C:\PATHTO\Anaconda3\Library\bin;C:\PATHTO\Anaconda3\Scripts;C:\PATHTO\Anaconda3\bin;%PATH%

REM then start Visual Studio for the iPython prompt to work correctly
START "" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe"
```

everything works perfectly:

```
Anaconda 5.3.0 interactive window [PTVS 15.9.18254.1-15.0]
Type $help for a list of commands.
>>> 

In [2]: 
```

I'm able to function with the fix above, so I mostly wanted to bring the same issue as others are having to your attention, although in a slightly different form.

Thanks!

**Comment by huguesv** [comment]
Thanks for the info! I've added a link to this in the original issue #4820

I'll close this as duplicate, since we don't need more than one issue for this.
