### ISSUE TITLE
Exact match on shelfset

### ISSUE THREAD

**Issue by SteveScott** [Microsoft/PTVS#4876]
I can only find shelvesets with an exact match of the user or the file name. A partial search should be sufficient to pull up a list of shelvesets or owners to choose from.

**Comment by huguesv** [comment]
Hi Steve, this sounds like an issue/feature request for Team Explorer functionality. This is the tracker for Python extension specific issues. I'd suggest you use the Send Feedback in VS to get this to the right team. Thanks!
