### ISSUE TITLE
Disable auto environment for tasks

### ISSUE THREAD

**Issue by D3f0** [Microsoft/PTVS#4885]
The auto-sourcing/enable of Python environment is a great feature! But I don't know how to disable it for tasks. Pyenv for example automatically activates and runs commands in its virtualenv, so I end up having errors for my pipenv run commands. 
I've made a little GIF with the behavior. Once again, PTVS are my everyday tools both for work and leisure (and teaching).
![vscode activates python sehll](https://user-images.githubusercontent.com/46064/49370728-23f62b00-f706-11e8-901a-e760bf636261.gif)

**Comment by D3f0** [comment]
This is the project tasks.js:
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [{
        "label": "Run IPython Shell",
        "problemMatcher": [],
        "type": "shell",
        "command": "pipenv run ipython",
        "presentation": {
            "echo": true,
            "reveal": "always",
            "focus": true,
            "panel": "shared",
            "showReuseMessage": true,
            "clear": false
        }
    }]
}
```
And this is the output:
```shell
> Executing task: pipenv run ipython <

source /Users/nahuel/.virtualenvs/pysrv-RjlHvHY5/bin/activate
Python 3.6.6 (default, Aug  6 2018, 12:14:58)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: source /Users/nahuel/.virtualenvs/pysrv-RjlHvHY5/bin/activate
  File "<ipython-input-1-944ce73c2717>", line 1
    source /Users/nahuel/.virtualenvs/pysrv-RjlHvHY5/bin/activate
                         ^
SyntaxError: invalid syntax


In [2]:
```

**Comment by huguesv** [comment]
Hi @D3f0 - the VS Code Python extension is not actually PTVS, though they both share a common debugger and soon language server.

Please post at https://github.com/Microsoft/vscode-python/issues and my colleagues will help you out :)

**Comment by D3f0** [comment]
Thank you! I'll open a ticket there
