### ISSUE TITLE
Debugger race condition __len__ override while using pandas

### ISSUE THREAD

**Issue by jmarshall9120** [microsoft/PTVS#4918]
I've been able to constantly produce an error where the debugger is able to call __len__() while setting an attribute reference to an instance of a pandas.DataFrame() and actually detect the attribute as None.

Example:
```
import pandas as pd

class MyClass:
    def __init__(self):
        self._peekBuffer = None
        return

    def __len__(self):
        lineCount = None
        if self._peekBuffer is None:
            self._peekBuffer = nextChunk()
        lineCount = len(self._peekBuffer)

        return lineCount

    def nextChunk(self):
        return pd.DataFrame([], columns=["Col1","Col2","Col3"])

if __name__ == __main__:
    df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["Col1","Col2","Col3"])
    myClass = MyClass()
    myClass._peekBuffer = "Ok"
    print(myClass._peekBuffer)
    myClass._peekBuffer = df
    len(myClass._peekBuffer)
```
Output if run naturally:
```
>>"Ok"
>>3
```
Output if run in debugger:
```
>>"Ok"
>>0
```

What appears to be happening is that when running the line in the debugger:

`myClass._peekBuffer = df`

there is a moment where `myClass._peekBuffer` is `None`.  During that small window, the debugger calls `self.__len()` which loads and an empty df to `myClass._peekBuffer`.  Since it would be weird for the debugger to then throw away my call to set `myClass._peekBuffer` i'm guessing that the `self.__len__()` call is done by some worker thread in the Debugger and the timing is just such that the `self.__len__()` detects the `None` value and then sets the empty DataFrame to my attribute (`myClass._peekBuffer`) overriding my set reference.

**Comment by huguesv** [comment]
Hi @jmarshall9120 is this with ptvsd 4.x?

```
import ptvsd
print(ptvsd.__version__)
```

If not, please uncheck"Enable legacy debugger" option in tools/options/python/debugging and try reproducing it again.

If it still reproduces, please install the latest ptvsd into your python environment (that has precedence over the copy bundled by VS)

If it still reproduces, I can move this over to https://github.com/Microsoft/ptvsd/issues

**Comment by jmarshall9120** [comment]
Hi @huguesv I went ahead and updated to the newest version of ptvsd (pip install ptvsd), the legacy debugger was already turned off.  It has definitely altered the race condition, but it seems like something is still going on.  I'm trying to pin it down now.   Will get back next week with more info.  Thanks for you help thus far.

**Comment by huguesv** [comment]
@jmarshall9120 were you able to get more info?

**Comment by jmarshall9120** [comment]
@huguesv  - yes.   The debugger is defiantly calling the __len__() method of a python object when it comes in frame.  In my build I had my class constructed such that if __len__() was called it would populate the buffer on an IO object with a data-chunk provided it was empty.   As such when, my IO object came in frame of the debugger the debugger was automatically causing it read data into the buffer.  

What I've done is just not use the debugger for testing that particular object and relying solely on improved log output to troubleshoot.

If the design decision to make ptvsd pull on the __len__() method is something you want to mess with (if its even possible)  I can give you more info, but I'm not sure what the solution would be myself.

**Comment by int19h** [comment]
It pretty much has to call it to know if the object is expandable, and display it accordingly.

**Comment by judej** [comment]
Closing old issue, please reopen if more action is required. This is not a high use scenario. thanks
