### ISSUE TITLE
Ruby Tools for Visual Studio

### ISSUE THREAD

**Issue by jonathanpepinmoore** [Microsoft/PTVS#4926]
I was wondering if anyone was wanting Microsoft to bring Ruby to Visual Studio?
I have a good start.

Thanks,

Jonathan

**Comment by huguesv** [comment]
Hi @jdm7dv 

You should post this feature idea at https://developercommunity.visualstudio.com/
Click on Suggest a feature
(this is the replacement for the uservoice site)

You'll get more of a general audience there and be able to see vote counts.

Thanks
