### ISSUE TITLE
How to debug C++ code in a python program using VS2017?

### ISSUE THREAD

**Issue by LaurentBerger** [Microsoft/PTVS#4947]
Hi,

I'm not sure that it is an issue. I posted already [here](https://social.msdn.microsoft.com/Forums/fr-FR/795ba098-2129-4650-9df4-66a3093c8e62/how-to-debug-c-code-in-a-python-program-using-vs2017?forum=vsdebug)

I compiled myself opencv lib for python in release and debug. If I install cv2.cp36-win_amd64.pyd in release I can run and debug my code without problem.

Now I want to debug opencv  C++ code from my python code. I followed this page https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2017.

I install debug configuration for cv2.cp36-win_amd64.pyd and I try to debug this code :

```
import numpy as np 
import cv2 as cv # <-- EXception  is here
img = cv.imread("g:/lib/opencv/samples/data/baboon.jpg")


```
Exception occurs :

Unhandled exception at 0x0000000065CC9E02 (python36_d.dll) in 
python.exe: 0xC0000005: Access violation reading location 
0x0000000000000025. occurred

Stack trace is

     python36_d.dll!PyUnicode_InternInPlace(_object * * p) Line 15272    C
     python36_d.dll!PyUnicode_InternFromString(const char * cp) Line 15307    C
     python36_d.dll!PyImport_Import(_object * module_name) Line 1711    C
     python36_d.dll!PyImport_ImportModule(const char * name) Line 1257    C
     cv2.cp36-win_amd64.pyd!_import_array() Line 1466    C++
    cv2.cp36-win_amd64.pyd!PyInit_cv2() Line 1785    C++
     [External Code]    
     <frozen importlib._bootstrap>!_call_with_frames_removed Line 219    Python
     <frozen importlib._bootstrap_external>!create_module Line 922    Python
     <frozen importlib._bootstrap>!module_from_spec Line 571    Python
     <frozen importlib._bootstrap>!_load_unlocked Line 658    Python
     <frozen importlib._bootstrap>!_find_and_load_unlocked Line 955    Python
     <frozen importlib._bootstrap>!_find_and_load Line 971    Python
     colorRange.py!<module> Line 2    Python

When I run my program  print( sys.version) gives

    3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]

Something weird is in [dll loaded](https://gist.github.com/LaurentBerger/07de1e6016e4e22e53a5b1c518eba0ac) I have got [python36.dll](https://gist.github.com/LaurentBerger/07de1e6016e4e22e53a5b1c518eba0ac#file-gistfile1-txt-L6) and [python36_d.dll](https://gist.github.com/LaurentBerger/07de1e6016e4e22e53a5b1c518eba0ac#file-gistfile1-txt-L224). 

Something in my configuration must be wrong but what ?

I posted here too

My configuration

Microsoft Visual Studio Enterprise 2017
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Visual C++ 2017   00369-90006-86327-AA272
Microsoft Visual C++ 2017

AnalyzePackage   1.0
OpenCL Analyze package

Application Insights Tools for Visual Studio Package   8.14.11009.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Code Builder - API Debugger   4.0.0.1
Enables various API debugging facilities for OpenCL applications. These include (among other features): tracing, dumping buffers & images and visualizing the active OpenCL objects during debug session and afterwards.

CodeBuilderTopMenu   1.0
This package is the top menu item in VS for Code Builder. This is the parent object for all other menu items in other packages.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.9.18254.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Image Watch   1.0

Intel Debugger for Heterogeneous Compute   1.0
Provides debugging capabilities for compute shaders running on the Intel GPU.

Intel® Parallel Studio XE 2018 Update 3 Composer Edition for C++ Windows*   Package ID: w_comp_lib_2018.3.210
Intel® Parallel Studio XE 2018 Update 3 Composer Edition for C++ Windows* Integration for Microsoft* Visual Studio* 2017, Version 18.0.30.15, Copyright © 2002-2018 Intel Corporation. All rights reserved.
* Other names and brands may be claimed as the property of others.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.21001.1 Commit Hash:8dd15923800d931b153ab9e4de74e42a74eba5e6
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

NVIDIA CUDA 9.1 Wizards   9.1
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight Visual Studio Edition   5.5.0.18014
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2018.
•Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
•Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
•Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
•NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
•IronPython and WPFToolkit used under Microsoft Public License (Ms-PL) and are Copyright © Microsoft Corporation
•Portions of RadControls for WPF © 2010-2011 by Telerik Corporation.  All rights reserved.
•zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib)

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

NVIDIA Nsight Visual Studio Edition - CUDA support   5.6.0.0
NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.

OpenCL Debug Engine   1.0
Intel(R) OpenCL Debug Engine

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.9.18254.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.9.18254.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.9.18254.1
Profiling support for Python projects.

Python - VC Project Support   15.8.18116.3
Provides support for launching C++ projects with Python debugging enabled.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61810.11040
Microsoft SQL Server Data Tools

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.28107.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9.28218
Visual C++ for Linux Development

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.77 (d15-9@e3f40b477)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.4.2 (HEAD/8255f42fc)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by huguesv** [comment]
@int19h or @zooba may have suggestions

**Comment by LaurentBerger** [comment]
If I understand well problem I think that I need to compile numpy in debug too. Isn't it?

**Comment by huguesv** [comment]
Yes, please try to compiling all using debug.
