### ISSUE TITLE
"Configure your new project" dialog is still shown after create python project from Existing Python code

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#4953]
VS Version: 28424.114.d16.0stg
Python Tool Version: 16.0.18354.1

Repro step:
1. Copy test folder from python distribution /lib/test, such as C:\Python27\Lib\test
2. Click "File->New->Project->Python->From Existing Python code"
3. Click "Next->Create"
4.Fill the folder or click "…" which containing your Python code
![image](https://user-images.githubusercontent.com/39871640/50536083-acdc7700-0b8b-11e9-9874-d2d7bf9077fd.png)
5.Click next to choose the python interpreter
6.Click "Next->Finish" button

Excepted : " Configure your new project" dialog closes automatically after click finish button
Actual :" Configure your new project" dialog is still shown
![image](https://user-images.githubusercontent.com/39871640/50536464-e0210500-0b8f-11e9-808b-b7cd877a295e.png)

**Comment by huguesv** [comment]
Same root cause as https://github.com/Microsoft/PTVS/issues/4960
