### ISSUE TITLE
Intellisense completely fails when ProjectHome property is non-default

### ISSUE THREAD

**Issue by Artfunkel** [microsoft/PTVS#4956]
In VS 2017, having a `.pyproj` file with the `ProjectHome` property set to anything other than `.` causes Intellisense to die. The suggestions box never appears, no syntax errors are ever identified, and no tests can ever be found.

Manually resetting `ProjectHome` to its default value (and changing all of the paths to your source files) fixes the problem...if you know to do that.

**Comment by Artfunkel** [comment]
No, there are no particular actions needed. It's broken at all times.

I'm on VS 2017 15.9.4 and I can reproduce the issue by downloading [this old revision of my project](https://github.com/Artfunkel/BlenderSourceTools/tree/47a65af72bb987ad9f5941bd6a849648c1f97ba2) and opening the solution.

**Comment by huguesv** [comment]
Thanks for the project sources, that helps a lot.

I was able to repro on 15.9, but not on 16.0 preview 2 internal builds, so I'm hopeful that this has been fixed.
![image](https://user-images.githubusercontent.com/1696845/50868088-c1c2c280-1362-11e9-8fcf-b5bad0fb7993.png)

**Comment by huguesv** [comment]
Will keep it open for now, and test again after the updated language server is integrated.
