### ISSUE TITLE
Startup window popup when creating projects continuously from Cookiecutter

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#4960]
VS Version: 28505.103.d16.0stg
Python Tool Version: 16.0.18354.1
make sure “startup window’  is enabled in options
Repro steps:
1. Click "View->Cookiecutter Explorer"
2. Select a template and then click "Next"
3. Click "Create and Open Folder" button
4. Don't close VS and then select another template 
Click "Next" and "Create and Open Folder"

Expect Result:
It should not show.

Actual Result:
startup window popup
![image](https://user-images.githubusercontent.com/39871640/50750904-2ce89800-1282-11e9-86da-fe258e96b151.png)
	
Note:
startup window does not show when close vs and then create project from cookiecutter.

**Comment by huguesv** [comment]
Internal bug 762352 (covers both the error message and the fact that the start dialog stays up)

This is to be fixed by the VS IDE team.

**Comment by huguesv** [comment]
Fixed upstream.
