### ISSUE TITLE
Update calls to Process.Start

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#4995]
Unless we're launching the interpreter that the user typed in, we should be making sure to use full paths when launching executable.

Example of one that needs to be updated:
https://github.com/Microsoft/PTVS/blob/1d04f01b7b902a9e1051b4080770b4a27e6e97e7/Python/Product/EnvironmentsList/EnvironmentPathsExtension.xaml.cs#L81

We can use `Path.Combine(Environment.SystemDirectory, "explorer.exe")` to specify the full path.

Alternative: `string filepath= "%WINDIR%\\system32\\explorer.exe"; Environment.ExpandEnvironmentVariables(filepath);`

**Comment by RaymonGulati1** [comment]
Internal task: 776703
