### ISSUE TITLE
Generate requirements.txt from IronPython does not work.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5009]
VS Version: 28523.274.d16.0stg
Python Tool Version: 16.0.19011.1
Repro steps:
1. Install IronPython (http://ironpython.net/download/ )
2. Create Python Application project
3. Add existing IronPython environment to python environment node
4. Right-click IronPython environment node and select Generate requirements.txt

Expect result:
requirements.txt can be generated in PE node and the file should include the packages and it's versions, like:
![image](https://user-images.githubusercontent.com/39871640/51668945-50d80780-1ffe-11e9-9dd5-032be3b2d7da.png)
Actual result:
requirements.txt was been generated , but the contents of the file are incorrect
![image](https://user-images.githubusercontent.com/39871640/51669022-84b32d00-1ffe-11e9-9b2f-332958797ce7.png)

**Comment by gramster** [comment]
Closing this issue; we are not investing any more in IronPython support due to low usage and high cost.
