### ISSUE TITLE
wiki entry on Ipython is incomplete

### ISSUE THREAD

**Issue by jmagosta** [Microsoft/PTVS#501]
The section
https://github.com/Microsoft/PTVS/wiki/Using-IPython-with-PTVS
is missing graphics, or is incomplete.   Without being able to follow the steps, its not possible to tell.  

Set ipython in Anaconda installed locally at ~/AppData/local/continuum/Anaconda/Scripts/ipython-script leaves the "interactive window" link in the Python Environments window disabled.

**Comment by crwilcox** [comment]
All of the images are checked in and show as 'x' because for some reason github isn't properly resolving them. It seems to happen with numbers at the end of the path.

I am going to try a few things and see if I can't get these to show up though.
Thanks for pointing this out!

**Comment by crwilcox** [comment]
I just noticed that these seem to work fine in Chrome but on IE they aren't all showing up.

What browser are you viewing our documentation in?

**Comment by crwilcox** [comment]
Also.  Here is a direct link to the image.  This fails (gives a black x) from IE but works with Chrome and Firefox.
https://raw.githubusercontent.com/wiki/microsoft/ptvs/Images/IPython01Step.png

**Comment by crwilcox** [comment]
I have addressed this problem and committed the changes.  Some files ended up in an odd encoding/bit state that made them not display properly in IE.  They work now after reencoding them.
