### ISSUE TITLE
Send to Interactive is Broken in 2019 Preview 2

### ISSUE THREAD

**Issue by joseortiz3** [Microsoft/PTVS#5014]
The update released yesterday includes a broken "Send to Interactive" feature. As a result, "Send to Interactive" doesn't work at all anymore.

![image](https://user-images.githubusercontent.com/18585219/51713065-08b0e900-1fee-11e9-8d41-8956fd48686d.png)

**Comment by RaymonGulati1** [comment]
Thanks for reporting the issue. We're aware of this and recently fixed it. 

It should be updated in P3--hand tight! 

#4954

**Comment by joseortiz3** [comment]
When is Preview 3?

What makes this particularly frustrating is copy and pasting code doesn't exactly replicate the functionality of Send to Interactive. Indentation is not properly handled when pasting into an interactive window. Open a new issue perhaps? This has been a problem for 2+ years.

**Comment by joseortiz3** [comment]
Is it broken in the current VS 2017? I'm scared to update my copy of VS2017 because there's no way to undo the update currently

**Comment by huguesv** [comment]
It should still be working in VS 2017. We haven't updated the Python build in VS 2017 since October. The regression was introduced in changes for VS 2019 Preview 2.
