### ISSUE TITLE
Datetime module

### ISSUE THREAD

**Issue by devparkk** [Microsoft/PTVS#5015]
hey ,, 
i want to say that i'm not able to import datetime  module for python ...whenever i do so it throws an error ...i have uploaded the corresponding program down below ...but the most interesting part ,i am able to do so if  i work on python interactive ...
so plzzz help me out with this...
thanks a lot
adios

[module1.zip](https://github.com/Microsoft/PTVS/files/2795132/module1.zip)

**Comment by RaymonGulati1** [comment]
I created a new python project and executed that code. It seems to run fine. 

I noticed that the zip file only had 1 file--is this issue specific to PTVS? Are you able to run it directly run it directly on python interpreter or another IDE?
