### ISSUE TITLE
Failure creating conda env as administrator due to long paths

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5020]
VS Version: 28526.9.d16.0stg
Python Tool Version: 16.0.19026.2
Repro steps:
1.Create python application
2.Right-click in python environment node and select add environment
3.Select Conda environment tab, select like below:
![image](https://user-images.githubusercontent.com/39871640/51820430-a834eb00-2310-11e9-933f-84f248ad60d8.png)
expect result: create conda virtual environment successfully
actual result: failed to create conda environment, error information:
----- Creating 'env11' -----
Solving environment: ...working... done
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.6.1
Please update conda by running
    $ conda update -n base -c defaults conda
  environment location: C:\Users\vwazho\.conda\envs\env11
  added / updated specs: 
    - pandas
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    pandas-0.24.0              |   py37ha925a31_0         9.6 MB
The following NEW packages will be INSTALLED:
    blas:            1.0-mkl               
    ca-certificates: 2018.12.5-0           
    certifi:         2018.11.29-py37_0     
    icc_rt:          2019.0.0-h0cc432a_1   
    intel-openmp:    2019.1-144            
    mkl:             2019.1-144            
    mkl_fft:         1.0.10-py37h14836fe_0 
    mkl_random:      1.0.2-py37h343c172_0  
    numpy:           1.15.4-py37h19fb1c0_0 
    numpy-base:      1.15.4-py37hc3f5095_0 
    openssl:         1.1.1a-he774522_0     
    pandas:          0.24.0-py37ha925a31_0 
    pip:             18.1-py37_0           
    python:          3.7.2-h8c8aaf0_0      
    python-dateutil: 2.7.5-py37_0          
    pytz:            2018.9-py37_0         
    setuptools:      40.6.3-py37_0         
    six:             1.12.0-py37_0         
    sqlite:          3.26.0-he774522_0     
    vc:              14.1-h0510ff6_4       
    vs2015_runtime:  14.15.26706-h3a45250_0
    wheel:           0.32.3-py37_0         
    wincertstore:    0.2-py37_0            
Downloading and Extracting Packages
pandas-0.24.0        | 9.6 MB    |            |   0% 
pandas-0.24.0        | 9.6 MB    |            |   0% 
pandas-0.24.0        | 9.6 MB    | ###1       |  31% 
pandas-0.24.0        | 9.6 MB    | ######7    |  68% 
pandas-0.24.0        | 9.6 MB    | ########5  |  85% 
pandas-0.24.0        | 9.6 MB    | #########2 |  93% 
FileNotFoundError(2, 'No such file or directory')
----- Failed to create 'env11' -----

note: if create Conda environment with SciPy , it was failed like pandas

**Comment by huguesv** [comment]
I wasn't able to reproduce this.

**Comment by huguesv** [comment]
Let's reopen if that happens again.

**Comment by xiaofeng0123** [comment]
VS Version: 16.0.0 [28727.162.d16.0]
Python Tool Version: 16.0.19074.1
Workload: "Desktop development with C++" and "Python development"
Same error occurs when creating conda env with "pandas",“scipy", "matplotlib","plotly","seaborn","karas","tensorflow","theano","django" and "requests".

**Comment by huguesv** [comment]
Were you running VS as admin?

To get more detailed error, we can run with the verbose option from command line:
```
cd C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64\Scripts

conda create -v -v -v -n myenvname -y pandas matplotlib
```
(repeating -v 3 times gives the most verbose output)

This will print details for the FileNotFound error.

**Comment by zhouwangyang** [comment]
This is the detailed error information:
[condaenv.log](https://github.com/Microsoft/PTVS/files/3020905/condaenv.log)

**Comment by huguesv** [comment]
This is the path causing problem:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64\pkgs\matplotlib-3.0.3-py37hc8f65d3_0\Lib\site-packages\matplotlib\backends\web_backend\jquery-ui-1.12.1\images\ui-icons_cc0000_256x240.png
```
It's 267 characters long, so it's over MAX_PATH.

If the downloaded packages are getting written under VS install folder, it must mean VS is running as admin. When not running as admin, the packages will go under the user folder, which is a shorter path that avoids this issue in most cases.

**Comment by huguesv** [comment]
The change I'm making for the updated miniconda, to force use the pkgs folder under the user's folder, should take care of this.
