### ISSUE TITLE
No typeshed completions is shown

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#5021]
VS Version: 28526.9.d16.0stg
Python Tool Version: 16.0.19026.2
Repro step:
	1. Create a new python application
	2. Input below code:
	Import sys
	e1, e2, e3=sys.exc_info()

Expect Result:
e1 and e2 should have type info, and e1 should be colorized as a class
	
Actual Result:
No type info on e1 and e2, and e1 isn't colorized
![image](https://user-images.githubusercontent.com/39871640/51823521-a5d78e80-231a-11e9-8f8d-411f37a75ae1.png)

**Comment by huguesv** [comment]
Confirmed.

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\Python\Core\Typeshed\Typeshed`

should be

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\Python\Core\Typeshed`

(there's an extra Typeshed folder that shouldn't be there)

**Comment by huguesv** [comment]
We merged the fix for this.
