### ISSUE TITLE
Add existing environment will replace the defalult environment in Python Environment node.

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#5023]
VS Version: 28526.9.d16.0stg
Python Tool Version: 16.0.19026.2
Repro step:
1. Create python application
2. Make sure default environment is Python 3.7(64-bit) in Python Environment node
3. Right-click python environment node and select Add environment
4. Change to Existing environment tab, and select Python 2.7(64-bit) from environment list.
5. Click Add.

Expect result:Python2.7 will be added to python environment node and default environment python3.7 is still there

actual result:Python2.7 was be added and replaced the default environment

**Comment by huguesv** [comment]
This is by design. The default is only visible if the user has not added an environment to the project.
