### ISSUE TITLE
Crazy memory and CPU usage after loading project or starting native debugging

### ISSUE THREAD

**Issue by Artfunkel** [Microsoft/PTVS#503]
Whenever I attach to a process with a Python project present in my solution (whether or not I'm debugging Python), the devenv.exe starts up a multitude of threads which use a significant portion of my CPU and send its memory usage bouncing around between 700MB and 3GB. This behaviour continues until I quit the program and significantly impedes debugging performance. It happens even if the Python project is unloaded.

The threads have stacks like this:

```
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21aa1
clr.dll!LegacyNGenCompile+0x1bf866
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21bea
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21aa1
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21e05
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21cbb
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21d2c
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21b8f
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21bea
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x21ad2
clr.dll+0x2b80
clr.dll+0x9146
clr.dll!DllUnregisterServerInternal+0x11d3
clr.dll+0x2552
clr.dll!DllUnregisterServerInternal+0x3a83
clr.dll!DllUnregisterServerInternal+0x47ac
clr.dll!DllGetActivationFactoryImpl+0x235d
clr.dll!DllUnregisterServerInternal+0x8b52
clr.dll!DllUnregisterServerInternal+0x8bc0
clr.dll!DllUnregisterServerInternal+0x8c8d
clr.dll!DllUnregisterServerInternal+0x8cfb
clr.dll!DllGetActivationFactoryImpl+0x2219
clr.dll!GetMetaDataInternalInterfaceFromPublic+0x1b084
ntdll.dll!RtlInitializeExceptionChain+0x63
ntdll.dll!RtlInitializeExceptionChain+0x36
```

I can't repro this with a new solution, so perhaps it's an issue with the size of my main projects?

To fix the issue I rolled back from RC2 to RC1, but when I did that the issue began to show up as soon as I loaded my solution. I've gone as far back as 2.1 and it's still happening. I've no choice but to uninstall the tools for now.

I have VS 2013 Community and Python 2.7.10 x64.

**Comment by Artfunkel** [comment]
I've been able to reproduce the issue at home. My home system is VS2013 Pro and Python 3.4.3. The project is [this much simpler one](https://github.com/Artfunkel/BlenderSourceTools). I noticed the bug after an extensive session of debugging Blender in pure Python mode.

**Comment by int19h** [comment]
Can you provide a stack trace for those threads when attached to VS in managed or mixed managed/native? Or a crash dump?

**Comment by zooba** [comment]
Managed debugging should be sufficient. Those symbols are not valid (the offsets are much too big), but they're all in clr.dll.

Attaching to VS with a second instance and hitting Break All (and possibly disabling Just My Code) should get an accurate stack trace. Alternatively, you could create a process dump via Task Manager or Process Explorer and upload it somewhere - then we can take a look ourselves. Posting the stack trace should be enough though, especially if it mentions Python anywhere.

**Comment by Artfunkel** [comment]
I've sent you an email, Zooba.

**Comment by int19h** [comment]
Looking at the dump, it seems to be doing code analysis on six threads - I assume that is for your original solution? Does it have six Python projects in it?

Unfortunately, as the dump has no heap info, there's no way to see what objects are consuming all the memory, but it's reasonable to assume that it's related to analysis, as well.

Can you clarify the repro steps for the simpler project? I didn't observe significant memory usage when merely opening it - does it require initiating debugging to repro in that case?

**Comment by Artfunkel** [comment]
No, there's only one Python project in both solutions.

I don't have any steps for the smaller project, and I don't see the problem when merely opening it up either. I just noticed that it was behaving in the same way at the end of a programming session. I did inspect the call stack and the same threads were running though.

My home PC had been running my own build of PTVS but I've since switched to 2.2 RC2. I've not been able to repro the bug but I did just encounter [an analysis crash](https://gist.github.com/Artfunkel/c8f87d4d924d6acfbf6f) which is perhaps related. I can send a dump in if you like.

**Comment by Artfunkel** [comment]
I forgot to mention that the process I'm attaching to in both cases runs an embedded interpreter, and isn't an interpreter itself. At work I've deleted the copy of python27.dll against which the program was linked and allowed it to fall back on the system DLL, which is not the same minor version.

**Comment by huangfeidian** [comment]
Same here, I just begin to learn python with ptvs. After I create one empty python solution with VS, the ptvs prcoss consumes memory and cpu like a monster. I haven't type a single word yet. It's too intimidating to watch this process consuming memory from 150m to 1G with my hands off the keyboard.
<img width="471" alt="pythonbug" src="https://cloud.githubusercontent.com/assets/3107971/11450225/eb3e98b2-95d1-11e5-99bb-47d5ccb5692f.png">

**Comment by zooba** [comment]
That's normal right now - see our [editor docs](https://github.com/Microsoft/PTVS/wiki/Editor-Features#intellisense) for the explanation.
