### ISSUE TITLE
Send to Interactive is not available

### ISSUE THREAD

**Issue by pontnou** [Microsoft/PTVS#5042]
Hello,
After a fresh installation of VS2019 community edition preview, the command “Send to Interactive” is not available. I have tried switching environments, installing new ones, repairing installation, uninstalling and reinstalling, etc. Ctrl + Enter does not work either and the command does not appear in the contextual menu.
With VS2017 community edition, it works right in the same machine, not configuration needed, just Alt + I.
Thanks.
David

![2019-02-03 15_39_58-pythonapplication1 - microsoft visual studio preview](https://user-images.githubusercontent.com/12546552/52178215-c183de80-27cb-11e9-8941-5513924fff63.png)

**Comment by huguesv** [comment]
So sorry about that. It's broken in 16.0 Preview 2. We've fixed it for the upcoming Preview 3.
https://github.com/Microsoft/PTVS/issues/4954

**Comment by pontnou** [comment]
Ok, thanks,
