### ISSUE TITLE
Launch json settings not getting passed through to debugger

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/PTVS#5055]
For example, to enable path mappings, if I want to pass `pathMappings`. It does not goes through.
```js
{
  "type": "python",
  "interpreter": "(default)",
  "interpreterArguments": "",
  "scriptArguments": "--repo microsoft/ptvs",
  "env": {},
  "nativeDebug": false,
  "webBrowserUrl": "",
  "project": "dockerstat.py",
  "name": "dockerstat.py",
  "pathMappings": [
  {
    "localRoot": "C:\\GIT\\pyutils\\",
    "remoteRoot": ".",
  }]
},
```

JSON received in debugger, pathMappings is missing.
```js
{
    "command":"launch",
    "arguments":{
        "noDebug":false,
        "exe":"C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\python.exe",
        "cwd":"C:\\GIT\\pyutils\\",
        "remoteMachine":"",
        "args":"C:\\GIT\\pyutils\\dockerstat.py --repo microsoft/ptvs",
        "options":"WAIT_ON_ABNORMAL_EXIT=True;WAIT_ON_NORMAL_EXIT=True;REDIRECT_OUTPUT=True;SHOW_RETURN_VALUE=True;VERSION=3.7;INTERPRETER_OPTIONS=",
        "env":[...],
    },
    "seq":3,
    "type":"request"
}
```

**Comment by huguesv** [comment]
We'll need to add support on a case-by-case basis. We'll add them to the json schema.

The values need to be retrieved from the setting object that VS has deserialized, and passed on to the LaunchConfiguration object, then onto the debugger.

**Comment by fabioz** [comment]
Note: the closed request on debugpy (https://github.com/microsoft/debugpy/issues/307) is related to supporting `pathMapping` on an `attach` request.

**Comment by mkashif14** [comment]
> Note: the request closed on debugpy ([microsoft/debugpy#307](https://github.com/microsoft/debugpy/issues/307)) is related to supporting `pathMapping` on an `attach` request.

The above issue reported by me is for VS 2019 Community while this issue looks like it's for VS Code. Would it still be counted as the same issue?

**Comment by int19h** [comment]
@mkashif14 This issue is for VS/debugpy integration.

**Comment by int19h** [comment]
Note https://github.com/microsoft/debugpy/issues/307#issuecomment-651231991 wrt path mappings.
