### ISSUE TITLE
Intellisense completion-db never finishes analyzing step

### ISSUE THREAD

**Issue by mkimberling** [Microsoft/PTVS#5097]
Ever since I updated PTVS to the latest version in December 2018, the completion db never finishes for my Python.  It gets stuck on "Analyzing numpy" for my Python 2.7 distro.  Consequently, I don't get any intellisense for my own modules because it never reaches them.

**Comment by huguesv** [comment]
Yeah, that doesn't work anymore. You'll need to disable use of databases. We've removed them completely in dev16.
In dev15, check this option and restart VS:
Tools/Options/Python/Experimental/Enable new style IntelliSense

**Comment by mkimberling** [comment]
Intellisense appears to be working again after I checked that and restarted Visual Studio.  I still see "analyzing numpy" stuck but I'll avert my eyes.  Thanks!
