### ISSUE TITLE
The Japanese labels of Django command are wrong

### ISSUE THREAD

**Issue by saamonumai** [Microsoft/PTVS#5109]
![ws000092](https://user-images.githubusercontent.com/1874934/52938083-17e44600-33a4-11e9-8e9f-b32a5b330fc7.JPG)

When I am going to run django command "manage.py makemigrations" and "manage.py migrate", I use context menu of Visualstudio seems as screenshot.

But, Japanese label of above commands are wrong.

The lavel "Django で移行を実行する"''s mean is "Run migration in Django", but, this label is "manage.py makemigrations"'s label.
I suggest more suitable Japanese  label "マイグレーションファイルを作成する" or "移行ファイルを作成する". 
Also used the word "マイグレーションファイル" in the official documents of Django.

And, the lavel "Django 移行..."''s mean is "Django mingrate", so, above label "Django で移行を実行する"' should be used at this command.

I think these 2 of label are make confuse for users.

**Comment by huguesv** [comment]
Thanks for the feedback. I've passed it on to the localization team.

**Comment by lukaschal** [comment]
VS_PythonTools. On review.

File: localize\ENU\Microsoft.PythonTools.Django.dll
ID: 0; "MigrateLabel"
SRC: Django &Migrate... (Django >= 1.7)
TGT: Django 移行... (Django 1.7 以降)(&M)

File: localize\ENU\Microsoft.PythonTools.Django.dll
ID: 0; "MakeMigrationsLabel"
SRC: Django Ma&ke Migrations (Django >= 1.7)
TGT: Django で移行を実行する (Django 1.7 以降)(&K)

**Comment by lukaschal** [comment]
Fixed.

SRC: Django &Migrate... (Django >= 1.7)
New TGT: Django で移行を実行する... (Django 1.7 以降)(&M)


SRC: Django Ma&ke Migrations (Django >= 1.7)
New TGT: Django で移行ファイルを作成する (Django 1.7 以降)(&K)
