### ISSUE TITLE
incompactable with conda 4.6 

### ISSUE THREAD

**Issue by redreamality** [Microsoft/PTVS#5111]
## environments:
conda 4.6

This throws an exception as follows.
![image](https://user-images.githubusercontent.com/3147776/52994548-ec6c6480-3452-11e9-9c42-fb35ca64e09d.png)

## Probable causation:
conda 4.6 has a different logic of loading `activate SOME_VIRTUAL_ENV`

**Comment by RaymonGulati1** [comment]
Can you give me more information? How do you reproduce this?

**Comment by redreamality** [comment]
--------------------------------------------
visual studio 2017 community edition v15.9.2
PTVS 15.9.18254.1-15.0

	active environment : spacy
	active env location : C:\Users\**\Anaconda3\envs\spacy
	shell level : 2
	user config file : C:\Users\**\.condarc
	populated config files : C:\Users\**\.condarc
	conda version : 4.6.4
	conda-build version : not installed
	python version : 3.6.5.final.0
	base environment : C:\Users\**\Anaconda3  (writable)
	channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
	          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
	          https://repo.anaconda.com/pkgs/main/win-64
	          https://repo.anaconda.com/pkgs/main/noarch
	          https://repo.anaconda.com/pkgs/free/win-64
	          https://repo.anaconda.com/pkgs/free/noarch
	          https://repo.anaconda.com/pkgs/r/win-64
	          https://repo.anaconda.com/pkgs/r/noarch
	          https://repo.anaconda.com/pkgs/msys2/win-64
	          https://repo.anaconda.com/pkgs/msys2/noarch
	package cache : C:\Users\**\Anaconda3\pkgs
	          C:\Users\**\Dropbox\emacs-24.4-bin-i686-pc-mingw32\.conda\pkgs
	          C:\Users\**\AppData\Local\conda\conda\pkgs
	envs directories : C:\Users\**\Anaconda3\envs
	          C:\Users\**\Dropbox\emacs-24.4-bin-i686-pc-mingw32\.conda\envs
	          C:\Users\**\AppData\Local\conda\conda\envs
	platform : win-64
	user-agent : conda/4.6.4 requests/2.21.0 CPython/3.6.5 Windows/10 Windows/10.0.17763
	administrator : True
	netrc file : None
	offline mode : False

I also include the yml file of my environment
[ENV.yml.txt](https://github.com/Microsoft/PTVS/files/2882576/ENV.yml.txt)

-----------------------------------------------------
I found a workaround solving the `BadSourceException` by `conda config --set changeps1 false` following [this](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)

**However there still exists a problem when loading numpy.**

	Traceback (most recent call last):
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
	    from . import multiarray
	ImportError: DLL load failed: 找不到指定的模块。

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\spacy\__init__.py", line 8, in <module>
	    from thinc.neural.util import prefer_gpu, require_gpu
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\thinc\neural\__init__.py", line 1, in <module>
	    from ._classes.model import Model
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\thinc\neural\_classes\model.py", line 2, in <module>
	    from numpy import prod
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\numpy\__init__.py", line 142, in <module>
	    from . import add_newdocs
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
	    from numpy.lib import add_newdoc
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
	    from .type_check import *
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
	    import numpy.core.numeric as _nx
	  File "C:\Users\**\Anaconda3\envs\spacy\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
	    raise ImportError(msg)
	ImportError: 
	Importing the multiarray numpy extension module failed.  Most
	likely you are trying to import a failed build of numpy.
	If you're working with a numpy git repo, try `git clean -xdf` (removes all
	files not under version control).  Otherwise reinstall numpy.

	Original error was: DLL load failed: 找不到指定的模块。

where `找不到指定的模块` means `cannot find the module`.

**Comment by huguesv** [comment]
Thanks for the additional info.

There's a workaround of activating the environment from command prompt and starting VS from that prompt. See #4874 for details.

**Comment by redreamality** [comment]
Thanks very much for the quick response and solution! 
It now works fine.

**Comment by huguesv** [comment]
Great. I'll keep this open for now until I try conda 4.6.
