### ISSUE TITLE
Autocomplete stays open when it is unable to offer valid suggestions

### ISSUE THREAD

**Issue by RaymonGulati1** [Microsoft/PTVS#5118]
Autocomplete stays open, even if it doesn't have valid suggestions
Start typing word such as "war", autocomplete pops up valid suggestions
Type "Q" and the autocomplete dialogue remains open, but cannot offer valid suggestions. 

![image](https://user-images.githubusercontent.com/3315992/53123509-1d5d9f80-350e-11e9-99b4-1bd63a36b3c5.png)

**Comment by huguesv** [comment]
As discussed, it is finding valid suggestions, the list is trimmed down to what the fuzzy matching algorithm determines is relevant.
