### ISSUE TITLE
PythonTools.Analyzer continuously creates IronPython processes

### ISSUE THREAD

**Issue by slozier** [Microsoft/PTVS#5122]
Using VS2019 Preview 3, I have a Python project in my solution with one of it's Python environments being IronPython. Looking at process explorer, the Microsoft.PythonTools.Analyzer.exe process is continuously spinning up ipy.exe instances: `ipy.exe -S -E C:\Users\...some temp folder...\get_search_paths.py`.

**Comment by huguesv** [comment]
The language server in the upcoming preview 4/RC has a number of bug fixes in it (the one in Preview 3 is about 6 months old and pretty much identical to what it was in 15.9).

We'll wait until you can try it out (it should be released very soon). Please let us know if it persists.

@AlexanderSher for awareness

It may be related to https://github.com/Microsoft/python-language-server/issues/663

**Comment by slozier** [comment]
@huguesv Thanks, looks like Preview 4 resolved the issue!
