### ISSUE TITLE
PTVS and Visual Studio code

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#513]
Hi

Are there any plans of integrating PTVS with Visual Studio Code for non-Windows operating systems? 

Thank you

**Comment by int19h** [comment]
It is highly likely that we will bring over at least some parts of PTVS over to VSCode at some point. No promises yet, though, and no specific timeline.

**Comment by sriksrid** [comment]
Thank you, and keep up the excellent work.
