### ISSUE TITLE
debugging python in Visual Studio

### ISSUE THREAD

**Issue by ewhite2142** [microsoft/PTVS#5130]
I'm using Visual Studio 2017 with Python 3.6.

We have functions in several modules. In the main module, we use exec(open('fn.py').read()) to open each of the other functions, and then call the functions from the main module. The problem is, as the functions are opened the way they are, I cannot debug them by stepping though them in Visual Studio the same say if they were in the main module.  I cannot step through or use breakpoints on the opened functions. Is there a way to use exec(open... and use these debugger tools as well?

**Comment by huguesv** [comment]
@karthiknadig or @int19h may know if there's a way

**Comment by int19h** [comment]
You need to make sure that Python (and hence the debugger) is aware of where those functions originate from. Specifically, the filename needs to be reflected in `f.__code__.co_filename`, where `f` is your function.

If you pass the source code directly to `exec()` like this, there's no source information. However, if you first do `compile()`, you'll have a chance to provide the filename there - and then the resulting code object with source information can be passed to  `exec()`.

**Comment by karthiknadig** [comment]
`compile` with filename should work.
```py
import os
obj = compile(open('fn1.py').read(), os.path.abspath('fn1.py'), 'exec')
exec(obj)
```

![image](https://user-images.githubusercontent.com/3840081/53523491-cc135a00-3a91-11e9-8222-b9b75782ab7d.png)

**Comment by ewhite2142** [comment]
Thanks...that works!
