### ISSUE TITLE
Debug debugger does not work with conditions and actions breakpoint

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5135]
VS Version: 28628.205.d16.0stg
Python Tool Version: 16.0.19051.1
Repro step:
1.Create python application
2.Type code in default .py file
```
from math import cos, radians
def make_dot_string(x):
    rad = radians(x)  
    numspaces = int(20 * cos(radians(x)) + 20)  
    st = ' ' * numspaces + 'o' 
    return st
def main():
    for i in range(0, 1800, 12):
        s = make_dot_string(i)
        print(s)
main()
```
3.Intall the latest ptvsd in current python environment
4.Set a conditions breakpoint, hover on red dot and click breakpoint setting
![image](https://user-images.githubusercontent.com/39871640/53625564-6dd7aa00-3c3e-11e9-95ae-d49f9ff6a058.png)
5.Create expressions using Python code like i > 1600 and click "Add condition" to add more expressions
6.Create a message to log to the output window, iptionally continuing execution automatically
![image](https://user-images.githubusercontent.com/39871640/53625598-85af2e00-3c3e-11e9-9468-699e8fdda547.png)
6.F5 to start to debug
Expect result: print successfully in output window
![image](https://user-images.githubusercontent.com/39871640/53626540-f0616900-3c40-11e9-8e63-c0dea7d7377f.png)
Actual result: The output is interrupted in the middle and will not continue  and nothing continue when I I press any key
![image](https://user-images.githubusercontent.com/39871640/53626174-03c00480-3c40-11e9-88a5-cbfc63777b30.png)

**Comment by huguesv** [comment]
I'm unable to reproduce this. Did this happen every time? Can you enable debug adapter host logging, there may be some clues in the log.
https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-in-visual-studio?view=vs-2017#enable-debugger-logging

**Comment by zhouwangyang** [comment]
I've seen this log in output window, no exception, just stuck, unable to continue, I tried in the latest build 28701.213, it worked OK , so I can only guess that it may be the environment at that time

**Comment by huguesv** [comment]
If this happens again, please make sure to enable and provide the debug adapter host log. That's the log that shows the debugger json messages.

**Comment by zhouwangyang** [comment]
This bug reproved  in the version:
![image](https://user-images.githubusercontent.com/39871640/60081457-60ea4380-9764-11e9-9ad8-346afeb67b16.png)

debug adapter host log:
[debug adapter host log.zip](https://github.com/microsoft/PTVS/files/3324234/debug.adapter.host.log.zip)

**Comment by huguesv** [comment]
I was just able to reproduce it in a VM. It took 4-5 attempts.

**Comment by huguesv** [comment]
Filed internal bug 937943

**Comment by huguesv** [comment]
Debugger team fixed this in VS master branch, which at this time means 16.3 Preview 2.
