### ISSUE TITLE
Conda search no longer works on conda 4.6.4

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#5147]
`CondaPackageManager.ExecuteCondaSearch` does a `conda.exe search -p "envpath" --json` and conda reports that `-p` is not a valid option

![image](https://user-images.githubusercontent.com/1696845/53905779-4138df00-3ffe-11e9-8da4-890656e65871.png)

Works fine on 4.5.11 (bundled miniconda).
Have not tested 4.5.12

**Comment by DonJayamanne** [comment]
Fun times with Conda...

**Comment by huguesv** [comment]
Always.

**Comment by huguesv** [comment]
On 4.5.11, passing in the prefix path doesn't appear to affect the results. So we can just remove that parameter.
