### ISSUE TITLE
Add existing folder failed if the existing folder in current project folder

### ISSUE THREAD

**Issue by shimingsg** [microsoft/PTVS#5150]
Repro step:
1. create python application project 
2. in project folder, create folder named ExistingFolder and add some files in it
3. right-click the project and select Add > Existing Folder
4. in pop dialog, select the folder "ExistingFolder", click "Select Folder"
Expected result: "ExistingFolder" is included in the project structure
Actual result: nothing happened

but if the existing folder is not in project folder, works fine

Version: 
![image](https://user-images.githubusercontent.com/20982341/53942139-f5b52c80-40f4-11e9-8912-1f9c454dde07.png)

**Comment by huguesv** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/520975/cannot-add-existing-folder-to-a-python-project.html
