### ISSUE TITLE
Getting nameError while running a simple program in vscode

### ISSUE THREAD

**Issue by vinothbabu** [Microsoft/PTVS#5154]
Python Version => 3.6.7 
VS Code => 1.31.1

`res = input("enter a number")
r = float(res)

print(r)`

I get the below error when i try to run the above code which is perfectly valid. 

> thalaivar@thalaivar:~/workspace/py$ /usr/bin/python3
> Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
> [GCC 8.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> r = float(res)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'res' is not defined
> >>> print(r)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'r' is not defined
> >>>

**Comment by huguesv** [comment]
Issue moved to [Microsoft/vscode-python #4707](https://github.com/Microsoft/vscode-python/issues/4707) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Akgithubpro** [comment]
anyone got the solution
