### ISSUE TITLE
subprocess arguments incorrectly escaped inside the debugger

### ISSUE THREAD

**Issue by Meinersbur** [Microsoft/PTVS#5155]
Consider the following program:
```
import sys
import subprocess

python = sys.executable
subprocess.check_call([python, '-c', 'print("A B")'])
subprocess.check_call([python, '-c', 'print("XY")'])
print("Done")
```

When executed with python from the command line this prints:
```
>python3 module1.py
A B
XY
Done

>python3 --version
Python 3.7.2
```

When executed from inside the Visual Studio 2017 debugger (same python 3.7.2, Python installed product 15.9.18254.1 according to Help -> About...), and Visual Studio 2019 preview, I get:
```
A B
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'XY' is not defined
```

The issue seems that the command line argument is only escaped when there is a space in it, but not deemed necessary with quotes. I checked the subprocess module, it correctly calls CreateProcess with escaped arguments in both cases. That is, the python debugger seems to hook the CreateProcess call, parses the command line, but re-escapes it insufficiently.

**Comment by huguesv** [comment]
Issue moved to [Microsoft/ptvsd #1227](https://github.com/Microsoft/ptvsd/issues/1227) via [**ZenHub**](https://www.zenhub.com/)
