### ISSUE TITLE
Press Enter after ":", the cursor should not be positioned at the beginning of the next line

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#5158]
VS Version: 28711.152.d16.0stg
Python Tool Version: 16.0.19066.1
Repro step:
type code:
def add(a, b):
except result:
![image](https://user-images.githubusercontent.com/39871640/54192263-79568b00-44f2-11e9-9da8-2c7b19bd9ede.png)

actual result:
![image](https://user-images.githubusercontent.com/39871640/54192161-5035fa80-44f2-11e9-9a9d-75a9eb4c4523.png)
![image](https://user-images.githubusercontent.com/39871640/54192281-82dff300-44f2-11e9-88f1-f6a618efdc26.png)

**Comment by huguesv** [comment]
It might be that the smart indent option wasn't set correctly when PTVS was installed. That has happened before. See tools/options/text editor/python/tabs/Indenting and change it to smart if it isn't.

**Comment by zhouwangyang** [comment]
@huguesv thanks, I really need to change to smart from tools/option.../indenting manually, and I verified that smart was set as the default options in the latest build 28712.114 on lab/d16.0stg branch.

**Comment by huguesv** [comment]
Let's reopen if the default is wrong again in the future.
