### ISSUE TITLE
Import warning "File is saved in encoding 'Western European(Windows)'…" appears when import folder under workspace if add .py file with "New File" menu

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5171]
VS Version: 16.0.0 RC.3[28714.193.d16.0]
Python Tool Version: 16.0.19066.1
Repro step:
1. Open a folder as workspace in SE
2. Use "Right-click the folder ->Add->New File" to add a .py file named "module.py"
3. Add a folder named "testfolder" under current workspace
4. Use "New File" menu to add __init__.py file in "testfolder" folder
5. Type code in __init__.py
	def FOLDER1_MSG():
		print("hello world!")
6. Type code in module1.py 
	import testfolder
	testfolder.FOLDER1_MSG()
		
Actual Result:
Import warning "File is saved in encoding 'Western European(Window)' which does not match default UTF-8 encoding" appear after typing code "testfolder.FOLDER1_MSG()"
**Note: The waring will disappear when close and reopen "module.py" file**
![image](https://user-images.githubusercontent.com/41426540/54517969-0dff3400-499e-11e9-947a-4e66f01caf0e.png)

Expect Result:
It should no warning

**Comment by haseebuchiha** [comment]
I have the same issue. Did you find the result good sir??

**Comment by RaymonGulati1** [comment]
@haseebuchiha, the temporary workaround is to close and reopen the file.

**Comment by haseebuchiha** [comment]
I did try that and I failed. Currently there's just this line that's annoying. Otherwise everything is working fine

**Comment by RaymonGulati1** [comment]
@haseebuchiha, can you try to save the file as a UTF-8 encoding?

Steps:
![image](https://user-images.githubusercontent.com/3315992/59138479-331e9580-8942-11e9-9a34-ac797e4fd780.png)

![image](https://user-images.githubusercontent.com/3315992/59138541-8b559780-8942-11e9-93ab-b84ced9eaa3f.png)

![image](https://user-images.githubusercontent.com/3315992/59138676-50a02f00-8943-11e9-8cf0-bbf6c7ddc18e.png)

**Comment by haseebuchiha** [comment]
Oooooooo now that's a solution. Thanks mate

**Comment by judej** [comment]
If the solution does not work, please reopen
