### ISSUE TITLE
Remove VS dependency on ptvsd.debug

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/PTVS#5173]
Launcher script used by VS can use `ptvsd.__main__` instead of `ptvsd.debug` call.
see: https://github.com/Microsoft/vscode-python/blob/master/pythonFiles/ptvsd_launcher.py#L23 for `ptvsd.__main__` usage.

Related: https://github.com/Microsoft/ptvsd/issues/1217

**Comment by RaymonGulati1** [comment]
No longer required because ptvsd_launcher.py is not being used anymore
