### ISSUE TITLE
Set next statement

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#5177]
Update to latest ptvsd and enable the feature.

**Comment by int19h** [comment]
To enable this, `ProvideDebugAdapterAttribute` needs to do the same thing with `SetNextStatement` registry value that `ProvideDebugEngineAttribute` does.

**Comment by huguesv** [comment]
Stable release of ptvsd went out today: https://github.com/Microsoft/ptvsd/releases/tag/v4.2.5

**Comment by karthiknadig** [comment]
There is a issue in the debug adapter host for VS. The adapter host team is looking into it. This is blocked until that issue is resolved.

**Comment by karthiknadig** [comment]
Done. via https://github.com/Microsoft/PTVS/pull/5246
