### ISSUE TITLE
Help people enable localhost in Microsoft Edge

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#518]
When I F5 on a bottle or flask project with IE as the selected browser, it works fine.

But with Project Spartan (hasn't been renamed yet on my win10 build), it says it can't reach the page.

If someone can confirm this working on their machine, that would be great, especially if you are on a newer build.

![spartan](https://cloud.githubusercontent.com/assets/1696845/8418905/de4f2ec0-1e6a-11e5-8ede-71d7e187d85b.png)

**Comment by zooba** [comment]
Still a problem on 10158.

**Comment by zooba** [comment]
That said, I expect it's either an Edge, bottle or WSGIRef problem, rather than a PTVS problem.

**Comment by huguesv** [comment]
http://blogs.msdn.com/b/msgulfcommunity/archive/2015/07/01/how-to-debug-localhost-on-microsoft-edge.aspx

**Comment by zooba** [comment]
http://dev.modern.ie/platform/faq/how-can-i-debug-localhost/ looks like a better link. We probably ought to figure out a good way of exposing this, though it's possible that Edge will gain some sort of functionality in the future (or VS/WinSDK could do it on install?).

**Comment by huguesv** [comment]
Not an issue anymore.
