### ISSUE TITLE
ValueError: "graph_tutorial.wsgi.application" could not be imported

### ISSUE THREAD

**Issue by knguyen1794** [microsoft/PTVS#5184]
I'm trying to deploy an application from my local computer where it's working fine, to Azure.
After hours of fixing and firefighting, I've come to this stage.
Can anyone help me to explain this error from the website when I am trying to access it?

```
Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "D:\Python34\Scripts\wfastcgi.py", line 711, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "D:\Python34\Scripts\wfastcgi.py", line 568, in read_wsgi_handler
    return env, get_wsgi_handler(handler_name)
  File "D:\Python34\Scripts\wfastcgi.py", line 551, in get_wsgi_handler
    raise ValueError('"%s" could not be imported' % handler_name)
ValueError: "graph_tutorial.wsgi.application" could not be imported


StdOut: 

StdErr: 
```

And this is my web.config file

```
<configuration>
  <appSettings>
    <add key="pythonpath" value="%SystemDrive%\home\site\wwwroot" />
    <add key="WSGI_HANDLER" value="graph_tutorial.wsgi.application" />
    <add key="DJANGO_SETTINGS_MODULE" value="graph_tutorial.settings" />
  </appSettings>
  <system.web>
    <compilation debug="true" targetFramework="4.0" />
    <!-- Required for websockets. -->
    <httpRuntime targetFramework="4.5"/>
    <customErrors mode="Off" />
  </system.web>
  <system.webServer>
      <httpErrors errorMode="Detailed"></httpErrors>
      <directoryBrowse enabled="true" />
  </system.webServer>
</configuration>
```

**Comment by huguesv** [comment]
Have you confirmed the existence of this file?
`%SystemDrive%\home\site\wwwroot\graph_tutorial\wsgi.py`

If it's there, it could be that the import finds the module alright but triggers an error in your code during import and it's just not being propagated in the error message. For example, that probably does:
```
from django.core.wsgi import get_wsgi_application
```
Have you checked that django is correctly installed? You're running on python 3.4, which is not supported by the latest version of django.

There were a few customer questions on this topic, there may be some clues in there that could help you.
https://github.com/Microsoft/PTVS/issues/2621
https://github.com/Microsoft/PTVS/issues/3947

The fact that you're running 3.4 points to the very first azure/python/web app support, which was restricted to 2.7 and 3.4.

That was later replaced by https://docs.microsoft.com/en-us/visualstudio/python/managing-python-on-azure-app-service?view=vs-2017 which allows more recent version of Python to be used.

However, as mentioned in the note at the top of that link, that's also been deprecated in favor of App Service on Linux.

If you're getting started, I would advise you investigate using App Service on Linux instead.
