### ISSUE TITLE
No intellisense for ironpython external modules

### ISSUE THREAD

**Issue by ccc159** [Microsoft/PTVS#5205]
**Environment:**
+ Visual Studio Professional 2019 16.0.0
+ Ironpython 2.7.9
+ Windows 10 Pro 1809 64-bit

**Bug:**
No intellisense (autocomplete) for external .dll library or python module

**How to reproduce:**
1. Create a `Ironpython Application` project.
2. In `Solution Explorer -> Search Paths`, add external .dll directory path.
3. Reference .dll using clr
![image](https://user-images.githubusercontent.com/15573101/55462133-60735e00-55f6-11e9-800a-a166fe8b9aa2.png)
4. The code runs with no problem, but there is no intellisense at all. Also `import clr` shows `unresolved import clr`
![image](https://user-images.githubusercontent.com/15573101/55462261-9d3f5500-55f6-11e9-8520-6722b190fbe4.png)

5. In `Solution Explorer -> Search Paths`, add external python module path.
6. The intellisese doesn't show full description of a function as it does in my old setup.
![image](https://user-images.githubusercontent.com/15573101/55462874-0ffd0000-55f8-11e9-892e-0567e4c549ac.png)

FYI, the old setup I was using is:
+ Visual Studio Professional 2015
+ Ironpython 2.7.5
Neither of the above problem appears in that setup.

I really appreciate the effort you've been putting into PTVS. Unfortunately to me I can only use the version from 3-4 years ago. I hope there's a workaround or a fix soon, as intellisense is one of the most important feature for an IDE.

Thanks!

**Comment by huguesv** [comment]
Thanks for the feedback. We have issue #5027 to track this.

**Comment by SamDehghani** [comment]
Any new news on this issue?

**Comment by guerillacodester** [comment]
Any news on this? It is beginning to make be cry :(

**Comment by supachris** [comment]
Is this issue planned to be fixed? It´s very annoying. Thanks.

**Comment by BhuvanKanade** [comment]
Imported .dll module is not showing autocomplete, suggestions and intellisence any update on this ?
