### ISSUE TITLE
Debug button says "Select Startup Item..."

### ISSUE THREAD

**Issue by qubitron** [microsoft/PTVS#5211]
May need to file a bug on workspace team

**Comment by ortollj** [comment]
Now I got the same issue "select a good startup item", after solving **simpy** missing library problem:
https://social.technet.microsoft.com/Forums/en-US/c410e885-9759-409d-b410-af51a51cdb84/errror-on-simpy-import-python-vs2019?forum=visualstudiogeneral

**Comment by huguesv** [comment]
It appears our EditFitler may be causing this. Comment out this line:
```
EditFilter.GetOrCreate(services, vsTextView);
```
and the problem goes away (no button difference when changing focus from solution explorer and document window)
