### ISSUE TITLE
Editor Error Highlighting is flaky

### ISSUE THREAD

**Issue by asantanna-applied** [Microsoft/PTVS#5223]
Quite often, items are underlined as issues in the text editor for Python when in fact there is no problem.  I'm not sure what triggers it but it happens *often*.

The problem can sometimes be fixed by modifying the line or the one before it by adding whitespace to perhaps make the syntax scanner recompute.  What always fixes the problem is to save the file, close the tab and then open it again.

Looks to me like the syntax scanner is not being triggered to recompute in some circumstances when it should.

**Comment by huguesv** [comment]
Thanks @asantanna-applied 

We have a couple of issues on this topic.
https://github.com/Microsoft/PTVS/issues/4962
https://github.com/Microsoft/PTVS/issues/4835

One on colorization of triple quoted strings.
https://github.com/Microsoft/PTVS/issues/4276

It sounds like one or more of these cover what you are describing. If that's not the case, please let us know (please include a screenshot).

**Comment by asantanna-applied** [comment]
Yes, they seem to be the same problem.  Sorry!
