### ISSUE TITLE
Interactive mode hangs: Windows 10, VS 2019, 64 bit

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#5233]
Hi

I have tried two different installations of Python 3 (Aanconda3 2019.03, and a barebones 3.7 with ipython, pandas, matplotlib installed) on Windows 10 (clean install). In both cases, if I set the checkbox "Use IPython interactive mode", the interactive window hangs as soon as I type any command (or even no command, just an enter to increment the counter). Resetting the process outputs three lines:
```
Resetting Python state.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
The interactive Python process has exited.
>> {I press enter}
In [2]: {I press enter}
hangs.
```

I also noticed that the module dropdown (in non IPython mode) shows "__main__", while the IPython mode doesn't show this drop down at all. How should I use the IPython interactive mode with VS 2019?

Thanks.

**Comment by huguesv** [comment]
Thanks for letting us know about this.

It works with Anaconda 2018.12 but now with 2019.03 I see the behavior you described.

**Comment by huguesv** [comment]
The problem appears when using pyzmq==18.0.1 (currently the latest)

You can downgrade that package to 17.1.2 and things appear to work again.

**Comment by sriksrid** [comment]
Thank you. That works great.
