### ISSUE TITLE
pip view in python environment has links to install packages even when pip is not installed

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#525]
PTVS 2.2
uninstall pip
open python environments, pip view
If you search for 'requests' and click on the link to install it, you'll get an error:

```

----- Installing 'requests' -----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pip
----- Failed to install 'requests' -----
```

The first link in the search results is for installing pip, but it doesn't stand out and is easy to miss.

**Comment by zooba** [comment]
We should disallow searching when pip is not installed.

**Comment by zooba** [comment]
Currently we allow searching, the install fails, and then the link to install pip appears. So I'm not massively concerned, but we should still make it much more obvious when you need to install pip.
