### ISSUE TITLE
Unresolved import for dotnet assembly references in Python Project.

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#5255]
Repro step:
1.Create a C#  file named ClassLibrary.cs and typing code:
namespace ClassLibrary1
{
    public class Class1
    {
        public string X
        {
            get { return null; }
        }

        public static void Fob() {
        }
    }
}
2.Compile ClassLibrary.cs as ClassLibrary.dll in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0 
3.Open VS and Create a python application project named PythonApplication1
4.Right-click References and select Add reference...->Assemblies
5.Check the ClassLibrary is selected and then click OK.
![image](https://user-images.githubusercontent.com/39871640/56649524-df206000-66b7-11e9-8f3d-f518374db46c.png)
6.Open PythonApplication1.py and typing code like below:
from ClassLibrary1 import Class1

Except result: we can import ClassLibrary without no warning and errors

Actual result: unresolved import 'ClassLibrary1'
![image](https://user-images.githubusercontent.com/39871640/56649917-97e69f00-66b8-11e9-935f-ffeee0749b5e.png)

Version:
![image](https://user-images.githubusercontent.com/39871640/56649955-ad5bc900-66b8-11e9-8423-e67efb364f02.png)

**Comment by huguesv** [comment]
We don't have completions anymore on .NET types, as in https://github.com/Microsoft/PTVS/issues/5027

**Comment by ccc159** [comment]
> We don't have completions anymore on .NET types, as in #5027

@huguesv Does it mean you no longer support autocomplete on .NET?  Or it is going to be fixed?

**Comment by huguesv** [comment]
@ccc159 we haven't excluded the possibility of fixing it, but the language server team have more common scenarios that have priority right now.
