### ISSUE TITLE
Error using selected REPL back-end

### ISSUE THREAD

**Issue by ecocarlisle** [microsoft/PTVS#5279]
Python 3.7 (64 bit)
When using the Python interactive window in Visual Studio 2019, I always get the following error:

Error using selected REPL back-end:
IPython mode requires IPython 0.11 or later: No module named 'IPython'
Using standard backend instead

**Comment by bschnurr** [comment]
The main docs assume you have minconda install...
[(https://docs.microsoft.com/en-us/visualstudio/python/installing-python-support-in-visual-studio?view=vs-2019)]

If you want to manually install the needed packages for the REPL take a look at the Packages (PyPI) tab in the Python Environments window.
[https://docs.microsoft.com/en-us/visualstudio/python/python-environments-window-tab-reference?view=vs-2019]

Search for the follwing packages:
ipython
ipykernel

and then click "Run command: pip install XXX" for each

Note: there is a bug with latest version of pyzmq (18.0.1) that ipython includes, so you will need to downgrade it by:
1. Enter pyzmq in the search box in Packages(PyPI) tab
2. click the "x" to uninstall it
3. type "pyzmq==17.1.3"
4. Click "Run command: pip install pyzmq==17.1.3

**Comment by judej** [comment]
Please reopen if it the work around doesn't address the issue
