### ISSUE TITLE
Error displays on "Property" page

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5280]
VS Version: 16.1.0 Preview 4.0 [28904.22.d16.1stg]
Python Tool Version: 16.1.19121.1

Repro step:
1. Create a python application
2. Click on the project, click "Property Pages" button on "Properties" panel

Actual Result:
Error displays on "Property" page
![image](https://user-images.githubusercontent.com/41426540/57189801-95503900-6f45-11e9-88e6-624082de1356.png)

Expect Result:
No error display.

**Comment by huguesv** [comment]
I was able to reproduce. I'll file an internal bug.
Error text:
Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.resources" was correctly embedded or linked into assembly "Microsoft.VisualStudio.AppDesigner" at compile time, or that all the satellite assemblies required are loadable and fully signed.

**Comment by huguesv** [comment]
Internal bug 888081

**Comment by huguesv** [comment]
This was fixed yesterday in 16.1 dogfood builds.
