### ISSUE TITLE
Cannot invoke Performance Comparison window

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5328]
VS Version: 16.2.0 Preview 2.0 [28922.351.d16.2stg]
Python Tool Version: 16.1.19129.1

Repro step:
1. Right click on one report to select "Compare Performance Reports..." on "Python Performance Explorer"
2. Select a .vsp file for "Comparison File" in "Select analysis files for comparison" window
3. Click "OK" button

Actual Result:
No response after click "OK" button.

Expect Result:
It should open "Performance Comparison" window and compare performance report

**Comment by huguesv** [comment]
Internal bug 897526

**Comment by huguesv** [comment]
Now fixed in latest VS dogfood build.
