### ISSUE TITLE
Can't set Python breakpoints in mixed-debugging

### ISSUE THREAD

**Issue by tmr232** [Microsoft/PTVS#533]
When I am using mixed-debugging, I can set breakpoints in C code, but not in Python code.

Stepping through Python code words just fine, but whenever I set a breakpoint (even in a file I am currently stepping through) I get an error: `"The breakpoint will not currently by hit. No symbols have been loaded for this document."`

When using pure Python debugging (not mixed), everything works as expected.

I am using:
- Visual Studio Community 2013 
- Python 2.7.10
- PTVS 2.1
- Debugging IDA Pro 6.8 with python.plw compiled with debug symbols. But I assume it will reproduce with other debuggees as well.

**Comment by zooba** [comment]
Are you able to try using our latest releases of PTVS? We've made some significant improvements since 2.1 and it's just as stable (probably better).

**Comment by tmr232** [comment]
I installed the [latest release](https://github.com/Microsoft/PTVS/releases/tag/dev-2015-06-26) and tried again. This time I got this error:

![error](https://cloud.githubusercontent.com/assets/1386239/8472455/334f846a-20aa-11e5-861d-0c292108dada.png)

Again, when connecting with pure Python debugger, everything works fine.

**Comment by int19h** [comment]
Does python.plw link Python statically, by chance?

**Comment by tmr232** [comment]
No. And as I noted before - mixed debugging worked with PTVS2.1, I was only unable to set breakpoints in the Python code.

The error message only appeared when I switched to the latest version.

**Comment by int19h** [comment]
If you were unable to set breakpoints in Python code in 2.1, it is possible that the Python mixed-mode debugger didn't actually get initialized properly there, either, but with less clarity. Can you clarify if you really had mixed-mode going in 2.1 (i.e., say, if you hit a breakpoint in C code, you can see Python frames on the stack, and in the Modules debugger tool window you see .py files)?

Either way, to figure out what's going wrong, I'll need to be able to debug this. Is there a free edition of IDA that could be used for this purpose?
