### ISSUE TITLE
The slow running speed of F5 debugging results in stuck in Native Code Debugging.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5336]
Build of Visual Studio: 16.2.0 Preview 2.0 [28927.9.d16.2stg]
Build of Python Package: 16.2.19142.2

repro step:

1. Create python application project
2. Typing code:
```py
from math import cos, radians
def make_dot_string(x):
	rad = radians(x)      
	numspaces = int(20 * cos(radians(x)) + 20)  
	st = ' ' * numspaces + 'o'         
	return st
def main():
	for i in range(0, 1800, 12):
	    s = make_dot_string(i)
	    print(s)
main()
```

3. Set breakpoint on the line `rad = radians(x)` and `s = make_dot_string(i)`
4. Enable "Native Code Debugging" in project settings / debug page
5. Using F5 to start debugging and debugging between these two breakpoints.

Except result:
The code can be smoothly debugged until it is finished

Actual result:
When I jump to the next breakpoint for execution, the last breakpoint is not finished and the response is slow and takes a few seconds.

**Comment by int19h** [comment]
Could you please clarify what you mean by "the last breakpoint is not finished"?

And also, do you see anything in the Output window when you move from one breakpoint to another, except for the value of `s`?

**Comment by zhouwangyang** [comment]
Pressed F5 to breakpoint1(s = make_dot_string(i)), and then Press F5 again it will jump to breakpoint2(rad = radians(x) ),but It got stuck at the first Breakpoint, I must wait for a few seconds, it can continue to run to bp2, at this time , the output window will also get stuck until the VS can continue executing.

**Comment by zhouwangyang** [comment]
I think it was too slow to switch between the breakpoints during the run, which caused the pause.

**Comment by int19h** [comment]
Ah, so when you press F5 at the first breakpoint, VS doesn't immediately show that it is executing code again?

(it should be possible to tell by the toolbar, depending on whether you see the Run icon or the Pause icon on it)

**Comment by zhouwangyang** [comment]
The pause time at the breakpoint is about five seconds, and the execution button on the toolbar is always running
![image](https://user-images.githubusercontent.com/39871640/58848295-92697500-86b8-11e9-990d-fe8bc930148d.png)

**Comment by huguesv** [comment]
There's a bug that tracks performance improvement at https://github.com/microsoft/PTVS/issues/4929

I'm not seeing this particular slowdown, however. It sounds like it's working as expected, but it's too slow.
