### ISSUE TITLE
Use IPython interactive mode & import files

### ISSUE THREAD

**Issue by oyibor** [microsoft/PTVS#5339]
Use IPython interactive mode & import files
Hello,
is it possible to import Python files and use the interactive window for debugging?
I have two files in the same folder. The first file has a function 'SayHello'. The second file should call that function.
The intellisense recognizes the imported file and debugging is working, too.
Unfortunately the interactive window does not find the file and shows the error 'ModuleNotFoundError'.
How can I reference files and use them in the interactive mode?

![remark 2019-05-28 174850](https://user-images.githubusercontent.com/51128957/58492541-6490a780-8171-11e9-9555-f91509f6a93b.jpg)

**Comment by huguesv** [comment]
Hi @oyibor 

First, close your interactive windows and close/reopen the solution to get into a known clean state.

When you press CTRL+ENTER to send to interactive window, it should create an interactive window that has the project's context (current working folder and search paths). You should see that the label for the window has your project's name.

If it doesn't, you can right click on the project node in solution explorer and select Open Interactive Window.

When creating an interactive window for the project, VS will look at the project's active Python environment and use its IPython setting.

![image](https://user-images.githubusercontent.com/1696845/58494985-2c667600-812b-11e9-8884-fc0fe39256ab.png)

**Comment by oyibor** [comment]
Hi @huguesv, 
thank you very much for your quick response. 
The interactive window works well as you have described it. Amazing!
Have a great day.
