### ISSUE TITLE
Send to interactive VS 2019

### ISSUE THREAD

**Issue by sriksrid** [microsoft/PTVS#5344]
Hi
I notice that send to interactive doesn't seem to work in VS 2019 unless the file is included to the in the solution (and I close and reopen the solution after adding it). This is true even if I create a new file in the project (right click, add new item). 

Is there a way to get send-to-interactive to work, even if the file is not being seen as included in the solution?

Thank you

**Comment by RaymonGulati1** [comment]
Thanks for the reporting the issue. I'm looking into this, but I'm having trouble reproducing the bug. Can you answer a few questions?

What version of VS are you using? 16.0? 16.1? Preview? 
Are you sending to interactive when you are debugging? 
How are you sending it to interactive window? Shortcut (control + enter), drop down menu? 

Can you give me a list on instructions on how to reproduce it?

**Comment by sriksrid** [comment]
Hi

I'm using VS 16.0.1 on Windows 10. I have an interactive console running. I right click on a project in the solution, and add a new item (empty python file). I then type my code in, select some lines, and press Ctrl E+Ctrl E (which is my key binding to Edit.Send Selection To Interactive) and I notice a warning in the status bar (The key combination ... is bound to ... which is not  currently available).

Resetting the interactive window does not seem to help either. 

Please let me know if you need any more information.

Thank you

**Comment by RaymonGulati1** [comment]
I’m still unable to reproduce the issue. Do you mind sending me an email so we can discuss this in greater detail? My email is ragulat@microsoft.com

**Comment by huguesv** [comment]
Since we can't repro it, we'll close. If you can provide further info to help us repro, please reopen. Thanks.
