### ISSUE TITLE
Intellisense for files in different folders

### ISSUE THREAD

**Issue by oyibor** [microsoft/PTVS#5347]
Hello PTVS team,

What is the best way to work with files in different folders?

Here is an example:
I have a project “Project_1” that needs to import a file “util.py” from a different folder.
The project folder is “…\Test\Project_1”
The other file’s folder is “…\Test\utils”

util.py has a function:
`def SayHello(): print('Hello')`

Project_1.py should call the function SayHello() from util.py:
```
# Get file information
import os
import sys
directory_current = os.getcwd()                         # Get current file's path
directory_parent  = os.path.dirname(directory_current)  # Get current file's parent path
# Import custom files from other folder
directory_utils   = directory_parent + '\\utils'
if not directory_utils in sys.path: sys.path.append(directory_utils)
# Import the function
from util import SayHello
# Call the function
SayHello()
```

The advantage of this implementation is that you can easily work with files in different folders. The disadvantage is that you have no intellisense support for the imported file in Visual Studio. If you add the util.py file to the project, a duplicate of the file will be created. You can use intellisense but then you have to synchronize changes being made in the original util.py and the copy.
Is there a way to use files from different folders where you have intellisense support and do not have to work with duplicates of files?

**Comment by huguesv** [comment]
Hi @oyibor 

In solution explorer, you can right click on "Search paths", and add the path to the parent folder. IntelliSense will then know about it, and when you launch the app, VS will adjust `sys.path` so the modules are found at runtime.

**Comment by oyibor** [comment]
Thank you very much, @huguesv.
That is great. The search path even seems to work dynamically. If you change the name of the parent directory, the search path will adjust accordingly.
If I do not have a solution or project but only a single file instead, is there a way that referenced modules are found at runtime, too? Can I set a parent directory as search folder for single files?

**Comment by RaymonGulati1** [comment]
@oyibor, if you only have a single file, then you can add the modules to sys path and they will be discovered at runtime. Same with setting the parent directory for single files. 

As for your first question, VS can also add a file reference in the first project to the 2nd folder/file. If you modify the file in the first project, the changes will be reflected in the 2nd file. You can do this by clicking on Project->Existing item->select file->change "add" to "Add as link". Only do this if you want the 2nd file in the project, else Hugues's option may be better. 

![image](https://user-images.githubusercontent.com/3315992/58831718-275d6700-8602-11e9-84e9-499b518d426d.png)

**Comment by oyibor** [comment]
Hello @RaymonGulati1,
I have found the option to add files as a link in a project, thanks to your remarks and your snapshot. That was very helpful for me, thank you very much.
I am confused about how to add a path to “Search Paths” for single files.
In a project I can add “Search Paths” within the Solution Explorer.
If I have a single module I do not have this option.
I can add a search path via code:
`if not myDirectory in sys.path: sys.path.append(myDirectory)`
This will allow the code to debug or execute but I do not have intellisense available and I cannot use the interactive mode.
Spyder has a combobox where you can set a search path:
![image](https://user-images.githubusercontent.com/51128957/58860088-9fcc3280-86ab-11e9-8c88-3f4e082202cc.png)
I have not been able to find this option in Visual Studio, yet (except for projects).
Could you please explain how to add a path to “Search Paths” for single files/modules?

**Comment by RaymonGulati1** [comment]
There is no way to do this in VS.

**Comment by oyibor** [comment]
That's a pity. Thank you for your help, @RaymonGulati1
