### ISSUE TITLE
Find redundant references and variables

### ISSUE THREAD

**Issue by oyibor** [microsoft/PTVS#5350]
Hello PTVS team,

Does Visual Studio have the ability to find redundant module references or unused variables?
Spyder warns you in such cases:
![image](https://user-images.githubusercontent.com/51128957/58793151-d47db280-85f5-11e9-92f5-ba442a253d80.png)

**Comment by RaymonGulati1** [comment]
@oyibor. You can remove unused imports by right clicking in the file and selecting "Remove imports". 

![image](https://user-images.githubusercontent.com/3315992/58832203-4f999580-8603-11e9-9c50-801cdc3e38b7.png)

There is no way to do this for unused variables.

**Comment by oyibor** [comment]
Thank you very much @RaymonGulati1. 
This works perfect for unused imports, great!
Spyder gives you a notice when you have unused variables inside your code.
![image](https://user-images.githubusercontent.com/51128957/58860936-904de900-86ad-11e9-9651-9394ba7c27cd.png)
Is there a similar option in Visual Studio?

**Comment by RaymonGulati1** [comment]
To the best of my knowledge, no.

**Comment by RaymonGulati1** [comment]
You can find unused variables by running pyLint on the project. 

![image](https://user-images.githubusercontent.com/3315992/58901413-035b5d80-86b6-11e9-9226-560b34e75517.png)

**Comment by oyibor** [comment]
Thank you very much, @RaymonGulati1. 
Works perfect.

**Comment by oyibor** [comment]
Hello @RaymonGulati1,
I have a pyLint specific question.
If you try to catch a generic Exception error pyLint shows 'Catching too general exception Exception' warnings.
![image](https://user-images.githubusercontent.com/51128957/58950522-4ccbab80-878f-11e9-862f-42342f5a930d.png)
Here is an example:
```
try:
    func()
except (ValueError, TypeError) as ex:
    print('ERROR ' + type(ex).__name__ + ': executing' + Source)
except Exception as ex:
    print('unknown ERROR ' + type(ex).__name__ + ': executing' + Source)
```
How can I take care of such a warning?
Can you help me?
