### ISSUE TITLE
LiveShare: Error message popup when client joined live share session

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5352]
VS Version: 16.2.0 Preview 3.0 [29003.219.d16.2stg]
Python Tool Version: 16.2.19142.2

Repro step:
1. Create a python application
2. Start Live Share Session
3. Join live share from client
4. Check client 

Actual Result
Error message popup when client joined live share
![image](https://user-images.githubusercontent.com/41426540/58860787-79c08580-86df-11e9-8767-916a53aeacf9.png)

Expect Result:
No error message popup

Below attachment is ActivityLog.xml:
[ActivityLog.zip](https://github.com/microsoft/PTVS/files/3251116/ActivityLog.zip)

Note:
IntelliSense is not working after this error occurs.

**Comment by MinKPark** [comment]
There is a known issue on Liveshare side and we are following up with LiveShare team.

**Comment by MinKPark** [comment]
The liveshare issue is fixed in preview 2 RC build. please regress and close it as the part of your test pass.
