### ISSUE TITLE
Modify String Pattern for Test Discovery

### ISSUE THREAD

**Issue by Anapo14** [microsoft/PTVS#5358]
@jelizaga3-gatech commented the below [here](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3160):

> By convention, Visual Studio identifies tests as methods whose names start with test.

Is it possible to modify the process that Visual Studio identifies the string pattern to discover tests? I.e. see python doc here: https://docs.python.org/3/library/unittest.html#test-discovery

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
Content: Unit test Python code - Visual Studio
Content Source: docs/python/unit-testing-python-in-visual-studio.md
Product: visual-studio-windows
Technology: vs-python
GitHub Login: @JoshuaPartlow
Microsoft Alias: joshuapa

**Comment by RaymonGulati1** [comment]
@bschnurr will be able to answer this. He's on leave for a couple of weeks, so he won't be able to respond till he gets back.

**Comment by RaymonGulati1** [comment]
This is not possible right now. We are working on pytest support which will have additional features that may support this. 

You can follow the progress in #1847

**Comment by huguesv** [comment]
Related to https://github.com/microsoft/PTVS/issues/5425

**Comment by huguesv** [comment]
this can now be customized in new test adapter, in project settings.
