### ISSUE TITLE
Cannot Fix Crossed Out Python 2.7

### ISSUE THREAD

**Issue by Anapo14** [microsoft/PTVS#5359]
@CBrauer commented the below [here](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3015):

> Python 2.7 is crossed out, but there is no entry in the registry. This case is not covered by this document. How can I fix Visual Studio 2017 to remove the crossed out Python 2.7?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 563f476d-a91b-58c7-9e32-b238756cc97d
> * Version Independent ID: 0a0e9cac-a8dc-47a1-14e1-1dacc3441613
> * Content: [Manage Python environments and interpreters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2019#fix-or-delete-invalid-environments)
> * Content Source: [docs/python/managing-python-environments-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/managing-python-environments-in-visual-studio.md)
> * Product: **visual-studio-windows**
> * Technology: **vs-python**
> * GitHub Login: @kraigb
> * Microsoft Alias: **kraigb**

**Comment by RaymonGulati1** [comment]
You can try a few different things here:
Confirm that you are looking in the correct place for the python registry key
Delete and reinstall python. 
Right click on the python environment and remove it from VS
![image](https://user-images.githubusercontent.com/3315992/59137524-17fd5700-893d-11e9-9d00-3fc8efac7d89.png)
If it's a virtual environment, delete it from the .pyproj. 
![image](https://user-images.githubusercontent.com/3315992/59137481-f3a17a80-893c-11e9-83c6-106f50fe3b1f.png)
