### ISSUE TITLE
No "Python/Native Debugging" entry in C++ project properties

### ISSUE THREAD

**Issue by Anapo14** [microsoft/PTVS#5360]
@skochinsky commented the below [here](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3229):

> Trying to debug Python code in our native app that embeds Python 2.7 (x64). I'm not seeing the "Python/Native Debugging" option in "Debugger to launch" combobox as described on this page. Using VS 2017 (15.9.11). Python support is installed via VS installer.
> I also tried the attach route (choose Native+Python at attach time) but breakpoints in Python code are not being resolved
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 702dd6fa-5ad3-b9c7-04bc-e9431c228623
> * Version Independent ID: 4d8a2c98-429a-b04e-1489-74475df5951a
> * Content: [Mixed-mode debugging for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019#feedback)
> * Content Source: [docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md)
> * Product: **visual-studio-windows**
> * Technology: **vs-python**
> * GitHub Login: @JoshuaPartlow
> * Microsoft Alias: **joshuapa**

**Comment by RaymonGulati1** [comment]
You can enable mixed mode debugging by selecting the "Python native development tools" options in VS installer. This will allow you to select the "Python/Native debugger" from a C++ project. 

![image](https://user-images.githubusercontent.com/3315992/59136994-69581700-893a-11e9-94d7-845d17935ff8.png)
