### ISSUE TITLE
Code coloring in Live Share client does not work.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5375]
Build of Visual Studio: 16.2.0 Preview 4.0 [29013.205.d16.2stg]
Build of Python Package: 16.2.19150.1

repro step:
1.Typing code in Live Share Client 
from xml.etree.cElementTree import ElementTree,ParseError

def parse_xml_from_file(filename):
    try:
        data=ElementTree().parse(filename)

    except ParseError:
        print("Failed to parse file{}".format(filename))

filename=r'C:\Data.xml'
parse_xml_from_file(filename)

Except result in client:
![image](https://user-images.githubusercontent.com/39871640/59495629-47264200-8ec2-11e9-9c70-68cb5d36ee2d.png)

actual result in client:
![image](https://user-images.githubusercontent.com/39871640/59495642-52796d80-8ec2-11e9-872a-39c0798f2bec.png)

**Comment by huguesv** [comment]
This is unfortunately by design.

LiveShare client uses TextMate to colorize based on parser, and is not able to do the 2nd pass colorization that we do for the server, which is based on analysis.

So LiveShare client will not have special colorization for classes, modules, or parameters, etc.
