### ISSUE TITLE
Backport critical fixes to 2.1.1

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#538]
Since we're not supporting PTVS 2.2 on VS 2010 and VS 2012, we should make one more update to 2.1 to backport fixes for critical issues.

This will be a very narrow, focused list, but feel free to suggest major issues and we'll consider them and add them to this list:

* various analysis crashes (backport some changes to Analysis.dll)
* IPython 3.0 support

**Comment by zooba** [comment]
We don't want to backport all changes to Analysis.dll - Python 3.5 support won't be added, for example. But the change to AnalysisDictionary is valuable as it prevents a lot of race-conditions.

**Comment by recife25** [comment]
#538 
I am working on Microsoft Visual Studio Ultimate 2012 ??? does the new python tool set works with such an environment????

**Comment by zooba** [comment]
PTVS 2.2 will not run on VS 2012. PTVS 2.1 will continue to run on VS 2010, 2012 and 2013, and we are planning a minor update to 2.1.1 for those people who can't move to VS 2013 or VS 2015.

**Comment by zooba** [comment]
#548 should be backported
