### ISSUE TITLE
Python background analyser very high CPU and VS 2017 intellisense 

### ISSUE THREAD

**Issue by lefig** [microsoft/PTVS#5383]
With the latest version of VS 2017 and with all updates, PTVS in simple terms is broken.

The background analyser frequently uses high CPU and intellisense is frozen. I have tried all the mentioned fixes such as disabling the experimental features, restarted VS etc.

But I have now given up hope that this will work once again.

**Comment by RaymonGulati1** [comment]
Have you tried VS 2019? It has some improvements you might find useful. 

We're also working on implementing a new language server and client in VS 2019 which should speed things up. You can track the progress on #5210

**Comment by lefig** [comment]
Thank you for coming back to me. Yes, I am tempted to try. I have heard many good things about 2019 and it seems that the Python specific updates are significant.

Much appreciated
