### ISSUE TITLE
The default project name is not correct when creating a python application in a new folder

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5389]
VS Version: 16.2.0 Preview 4.0 [29026.166.d16.2stg]
Python Tool Version: 16.2.19150.1

Repro step:
1. Create two folder named folder1 and folder2
2. Create a python application used the default project name "PythonApplicaiton1" in folder1
3. Create a python application in folder2

Actual Result:
The default project name is "PythonApplication2" in "Configure your new project" dialog when no any applications in folder2
![defaultname](https://user-images.githubusercontent.com/41426540/60256719-a80f3a80-9904-11e9-88b5-ef2b8f765b09.gif)

Expect Result:
The default project name should be "PythonApplication1" in folder2

**Comment by huguesv** [comment]
That appears to be by design. After changing the location, the project name should not reset based on the new location because you may already have edited it prior to changing the location.
