### ISSUE TITLE
Debuggers should not debug visualstudio_py_testlauncher.py

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/PTVS#5406]
Whenever the legacy debugger (run with debugging and then attach TCP) or new debugger (run with debugging or attach TCP) debugs the unit tests, it will also debug visualstudio_py_testlauncher.py. Change it so that this script is not debugged.

**Comment by karthiknadig** [comment]
For this it should just go into do not trace list. You can set this using `setDebuggerProperty`, but the patterns are not additive. This means when you call this API it will apply your filter but will remove the ones it added. 

@int19h we might need to clean that code as well. As you suggested we might want to do glob patterns, and make it additive patterns.

**Comment by karthiknadig** [comment]
Actually, can you try using the `rules` for the attach request. That should address this for the most part. If tracing is absolutely not needed then we could look at an API for this.

**Comment by karthiknadig** [comment]
```js
"rules": [
    {"path": "<extension dir path>/**", "include": false},
]
```
This will allow you to ignore all files in the directory.
