### ISSUE TITLE
Unhandled exception happened in remote debugging with python 2.7 legacy debugger.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5408]
repro step:
1.Create python application and typing code:
```
raw_input('>')
from math import cos, radians
def make_dot_string(x):
	rad = radians(x)                    
	numspaces = int(20 * cos(radians(x)) + 20)   
	st = ' ' * numspaces + 'o'    
	return st
	
def main():
	for i in range(0, 1800, 12):
	    s = make_dot_string(i)
	    print(s)
	
main()
```
2.Set breakpoint in the line "from math ....."
3.Select Python2.7 as your active environment and install package "pip install ptvsd==3.2.1"
4.Make sure "Use legacy debugger" has been checked in tools->options->python->debugging
5.In command prompt(right-click the python environment and select "Open Command Prompt Here…"), execute:
python -m ptvsd -i 127.0.0.1 -p 4022 C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py
6.Launch VS and Debug > Attach to Process, in dialog:
    a.Select connection type with Python remote(ptvsd)
    b. Connection target with 127.0.0.1:4022
In Available processes list, select the appropriate python.exe, click "Attach"
7.Type enter in the console and then press F5

except :
The program should be run over without any errors

actual:
 Unhandled exception in thread started ....
![image](https://user-images.githubusercontent.com/39871640/60790112-49af4b00-a193-11e9-9d60-fe41aceec235.png)

Testing environment:
![image](https://user-images.githubusercontent.com/39871640/60801387-766e5d00-a1a9-11e9-9e76-5fb92cf2edb3.png)

**Comment by huguesv** [comment]
Did this occur every time? Does this seem like a regression?

Were you usually testing by launching via `-m ptvsd` from command prompt, or by adding `enable_attach` / `wait_for_attach` in the script? Maybe the error occurs in one case but not the other?

We are not planning on fixing legacy debugger issues, unless it's something major that regressed. 
Thanks.

**Comment by zhouwangyang** [comment]
This issue did not happen frequently, If several machines have installed the same build to test, this issue will appear in one of them.

**Comment by huguesv** [comment]
Won't fix legacy debugger bugs at this point.
