### ISSUE TITLE
Python file association - VS does not open the file when double click  / Open With from Windows File Explorer

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#5411]
Everytime I double click a python source code which i linked with VS2019, it always start a new instance of VS2019 with blank window whether there is an actived VS2019 instance.

After the instance started, I have to drag the python source file into the instance window to explore and edit everytime, since it's the only and only one procedure to open a .py file in VS2019 without the history file entrance.

This issue has been moved from https://developercommunity.visualstudio.com/content/problem/624756/python-source-code-link-issue-opening-python-sourc.html

**Comment by huguesv** [comment]
I can confirm this behavior. I used Open With -> Microsoft Visual Studio 2019, and it starts VS but doesn't actually open the file.

**Comment by saadjavaid** [comment]
Confirming this behavior - exact same issue

**Comment by luigi-palladino** [comment]
Confirming this behavior - exact same issue.

**Comment by huguesv** [comment]
I've noticed, at least in the LSC branch, that Open With Visual Studio Version Selector works correctly, but Open With Visual Studio 2019 doesn't.

![image](https://user-images.githubusercontent.com/1696845/69361931-587a3400-0c42-11ea-9c27-e863e98cfb10.png)

**Comment by luigi-palladino** [comment]
> 
> 
> I've noticed, at least in the LSC branch, that Open With Visual Studio Version Selector works correctly, but Open With Visual Studio 2019 doesn't.
> 
> ![image](https://user-images.githubusercontent.com/1696845/69361931-587a3400-0c42-11ea-9c27-e863e98cfb10.png)

I confirm this behaviour, it works. Thank you.

**Comment by huguesv** [comment]
2 more data points:
Open with Visual Studio 2017 works fine (on same machine that has VS 2019)
Open with Visual Studio 2019 works fine if you uninstall the Python workload

So something that is part of the workload is breaking it.

**Comment by bschnurr** [comment]
Command line Visual Studio 2019 with Python workload loads fine.

I was able to repro locally by doing Open With experimental hive VS shortcut

**Comment by bschnurr** [comment]
[OpenWith_py_file_VSExperimental.txt](https://github.com/microsoft/PTVS/files/3984983/OpenWith_py_file_VSExperimental.txt)

[commandline_py_file_VsExperimental.txt](https://github.com/microsoft/PTVS/files/3984984/commandline_py_file_VsExperimental.txt)

[OpenWithvsCommandLine.pdf](https://github.com/microsoft/PTVS/files/3984996/OpenWithvsCommandLine.pdf)

**Comment by bschnurr** [comment]
found a similar issue with .js
Related to registry settings.
https://developercommunity.visualstudio.com/content/problem/741536/cant-open-js-file-type-from-explorer-context-menu.html

**Comment by burekas7** [comment]
Confirming this behavior - exact same issue

Is there any solution here?

**Comment by burekas7** [comment]
> I've noticed, at least in the LSC branch, that Open With Visual Studio Version Selector works correctly, but Open With Visual Studio 2019 doesn't.
> 
> ![image](https://user-images.githubusercontent.com/1696845/69361931-587a3400-0c42-11ea-9c27-e863e98cfb10.png)

Actually it works, thanks.
But why does it take VS so long to open and view the file?
