### ISSUE TITLE
Tests are not removed from test explorer after test is renamed.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5427]
repro step:
1.File, New Project, Python, Python Application
2.Add, New Item, Python Unit Test, make sure test1.py was added in python application
3.Open Test explorer,test1 should be found in that
4.Click test1.py and right click to select "Copy"
5.Paste in python application and make sure test1-Copy.py was in python application
6.We will found test1-Copy was found in Test Explorer
7.Right click in test1-Copy and press "F2" to rename, the new test name was test2

Expect:
The test in Test Explorer should be test2 ,and test1-Copy was recovered by test2

Actual:
test1-Copy was still in Test Explorer and test2 was also exist in TE
**and at this time , click "Run All" in TE, An exception occurred in output window and "Run all" does not work:
Not a valid Python module: C:\Users\vwazho\source\repos\PythonApplication1\PythonApplication1\test1 - Copy.py**

![test explorer](https://user-images.githubusercontent.com/39871640/61112047-8fcf1c00-a4bd-11e9-9c77-c687ae842df6.gif)

![image](https://user-images.githubusercontent.com/39871640/61114252-85fbe780-a4c2-11e9-80f0-15cfadb8dc90.png)

**Comment by RaymonGulati1** [comment]
Thank you for the report. 

The testing framework is being reworked which might fix this. If it doesn't, we will revisit the issue. 

You can track the reworking progress at #1847

**Comment by huguesv** [comment]
Thanks. It's broken in a slightly different way in the new test adapter implementation (which is not available yet). I filed a bug for it https://github.com/microsoft/PTVS/issues/5434

**Comment by huguesv** [comment]
This should be fixed now. Note that a file named with a '-' character will not be discovered in test explorer. This matches the behavior of unittest when invoked from command line. Renaming a regular file that has tests detected seems to work as expected.

**Comment by AriNuer** [comment]
After rename test1.py file to test2.py ,test name in Test Explorer was not rename,but apear a new test in Test Explorer named test2.py
![image](https://user-images.githubusercontent.com/42136111/102869148-273beb00-4476-11eb-9874-8e5aac149d15.png)
![image](https://user-images.githubusercontent.com/42136111/102869332-6c601d00-4476-11eb-97cb-02082e9148c5.png)
