### ISSUE TITLE
No test discovery after add existing item from folder.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5428]
repro step:
1.File, New Project, Python, Python Application
2.Add, New Item, Python Unit Test, make sure test1.py was added in python application
3.Right click in python application and select Add ->Existing item..., select test2 in another folder
4.Make sure test2 was added in python application
5.Open TE

Expect:
Test2 should be discovered in TE 
Actual:
Test2 did not be found in TE and Ran "Run all" also could not found test2

******if you open test2 in editor , it could be found in TE.

![test explorer add](https://user-images.githubusercontent.com/39871640/61114666-674a2080-a4c3-11e9-826d-40c37998a571.gif)
![image](https://user-images.githubusercontent.com/39871640/61114676-6dd89800-a4c3-11e9-967c-abe8002467a7.png)

**Comment by RaymonGulati1** [comment]
Thank you for the report.

The testing framework is being reworked which might fix this. If it doesn't, we will revisit the issue.

You can track the reworking progress at #1847

**Comment by huguesv** [comment]
This is now fixed in 16.3
