### ISSUE TITLE
MSVS 2012

### ISSUE THREAD

**Issue by recife25** [Microsoft/PTVS#543]
hi yall
regarding development of Python Tools 2.2 , is it available for Microsoft Visual Studio Ultimate 2012 and Microsoft .Net framework ver 4.5.51641 -- I am happy to read about the new tool, yet I am wondering if I would be able to use it. ???? (~):-}

**Comment by zooba** [comment]
We won't be releasing PTVS 2.2 for VS 2012. It will work with all the free versions of VS 2013 and VS 2015 though, so you can use it with any of those.
