### ISSUE TITLE
Scripts won't run. 

### ISSUE THREAD

**Issue by Zaxamaphone** [microsoft/PTVS#5432]
**Describe the bug**
I just recently installed Visual Studio 2019 Community (2 days prior to this review), and my Python scripts will no longer run within Visual Studio. Everything was working fine just minutes earlier, within the same session.
Attempting to run scripts will cause them to instantly fail and produce the error message shown below. I removed all python features (with the visual studio installer), and then re-installed them. That didn't fix the problem, either. 

This is the output produced by the python.exe window at run time:
```
"Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 90, in <module>
    import ptvsd.debugger as vspd
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 17, in <module>
    from __future__ import with_statement, print_function
ModuleNotFoundError: No module named '__future__'
```
Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415"

After closing the python.exe command window, visual studio shows the following message box.
![image](https://user-images.githubusercontent.com/52887776/61185415-dee09280-a61e-11e9-8e90-2933bce0caee.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.1.6
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
I did not find PTVS on the "Installed products:" list.
Python version: 16.1.19129.1
Debugger Type (if applicable): [New debugger or legacy debugger?] Both debuggers fail.

**Comment by int19h** [comment]
What is your Python version and flavor?

**Comment by RaymonGulati1** [comment]
Is it possible for you to share the scripts with us? You can email it to us at ptvshelp@microsoft.com

**Comment by Zaxamaphone** [comment]
I am using Python version 3.7.4 - 64 bit. I should also tell you that I did
not "install" Python on my system in the traditional sense. I am using an
embeddable version from Python.org.
https://www.python.org/downloads/windows/
"Windows x86-64 embeddable zip file"

I am also going to be completely honest. This is my first time ever using
Python, but everything was working fine just minutes earlier. The script
was running just fine in the ZIP environment, but now it will only run on
the environment that Visual Studio installed.

My goal is to make a little tool that can be stored on a portable flash
drive, but not require installing of any third party resources. This is why
I used the embeddable zip version of python.
I may just uninstall python completely and try ONLY using the zip version
and skip the version that comes with Visual Studio.

If that doesn't work then I will try the opposite, and ONLY use the version
that Visual Studio installs. After all, I am probably over-complicating
things by trying to make a completely portable package for my first time
ever using python. I was hoping the solution to my problem would be a
simple re-install of a file, or something similar.

thanks.

**Comment by int19h** [comment]
I would recommend developing your script using the regular Python install, and then using the embeddable zip specifically for redistribution. While it should be possible to set up debugging with the zip version, even when it works, it won't be a pleasant experience. 

To test it before distributing it, it would be best to run your script outside of VS - i.e. from command line - since that is how your end users will be running it in this configuration, if I understand everything correctly. Do you get a similar issue if you run your script directly? Or does `import __future__` work fine for you there?

**Comment by Zaxamaphone** [comment]
Pavel, thank you for the advice. I can't test the import __future__
functionality right now, but to be honest I don't think this is worth
troubleshooting any further. I think my solution is going to be to use a
virtual environment this time around and ditch the embeddable zip for now.
I'll worry about making everything more portable when the time comes. Heck,
I may not even need to package it in that way, but I assumed doing so would
just make everything easier to manage. I've set up a virtual environment
for a test project and it looks very clean and easy to understand(which is
exactly what I need while trying to learn all of this). I'm simply a novice
tinkering with an environment I don't understand. I'm going to focus on
getting the tool to fully work first within my local environment. Once that
is done I can worry about getting end users set up with Selenium and any
other required packages used within the script.

Thank you for the quick responses, I appreciate your help.
