### ISSUE TITLE
Pytest discovery script should not wait forever

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5440]
If the user's code has an `input()` call at the global scope, or something else similar that blocks, then the discovery phase will wait indefinitely for the python.exe to end.

We should have a timeout after which we kill the process and log an error.

Wait for 60 secs, output using logger that we will wait 60, and then output error when we kill it.

**Comment by bschnurr** [comment]
![image](https://user-images.githubusercontent.com/1946977/62236170-62221800-b383-11e9-81f9-6755a01c3a8e.png)

**Comment by bschnurr** [comment]
to test around this i changed the default timeout to 1 second and added a global sleep

**Comment by bschnurr** [comment]
while True:
    pass

also triggers it
