### ISSUE TITLE
Unable to access System.Drawing

### ISSUE THREAD

**Issue by rkamarowski** [Microsoft/PTVS#545]
I'm using IronPython in VS 2013 Community under Windows 8.1.  In the references I've added System.Drawing. In my code I enter:
from System.  <- and Drawing is not visible.

I've removed and loaded System.Drawing 4.0 and/or 4.5 several times, but I'm never able to access it. Any help would be appreciated.
Bob K.

**Comment by andygraham** [comment]
Have you referenced it n in your Python code?

clr.AddReference('System.Drawing')

It won't show in Intellisense and you can't use it unless you do.

**Comment by rkamarowski** [comment]
That worked!  Thank you.
