### ISSUE TITLE
Error 500.0 on IIS - The FastCGI process exited unexpectedly

### ISSUE THREAD

**Issue by CarloPoletto** [microsoft/PTVS#5450]
Hi all,

I developed a Python application in Django using IIS as a web server. Until a few days ago, I used Python 2.7.15 and everything was ok. This week I decided to upgrade the Python version to 3.7 as next year version 2.7 will be deprecated. The application update went very well but now I can no longer host it with IIS due to the following error: `Error 500.0 - Internal Server Error` `The FastCGI process exited unexpectedly`

This is my initial configuration:

 - Python 3.7.4
 - Django 1.11.17
 - wfastcgi 3.0.0
 - virtualenv 16.6.2

After reading several topics on the subject, I realized that wfastcgi is not compatible with Python 3.7. For this reason I tried to downgrade the application to Python 3.6.8 but nothing has changed. I also read some topics (very old indeed) where it was said that wfastcgi has problems with Python 3.5 and beyond. Although it seemed very strange to me (the [PyPi page](https://pypi.org/project/wfastcgi/3.0.0/) declares a compatibility up to Python 3.6), I tried to use Python 3.4.2 but I realized that it has already been deprecated and therefore I discard it.

This is my web.config configuration:

    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <location overrideMode="Deny">
            <system.webServer>
                <handlers>
                    <add name="Django Handler" 
                         path="*" 
                         verb="*" 
                         modules="FastCgiModule" 
                         scriptProcessor="C:\MyProject\virtualenv\Scripts\python.exe|C:\MyProject\virtualenv\Lib\site-packages\wfastcgi.py" 
                         resourceType="Unspecified" 
                         requireAccess="Script" />
            </handlers>
        </system.webServer>

        <appSettings>
            
            <add key="WSGI_HANDLER" value="django.core.wsgi.get_wsgi_application()" />
            <add key="PYTHONPATH" value="C:\MyProject" />

            
            <add key="DJANGO_SETTINGS_MODULE" value="myproject.settings" />
        </appSettings>
    </location>
</configuration>

**Comment by CarloPoletto** [comment]
After several attempts I tried to install Python 3.6.8 in C:/Python36 (previously it was in C:/Users/MyUser/AppData/Local/Programs/Python/Python36). This seems to have solved the problem.

**Comment by RaymonGulati1** [comment]
Glad you solved it!
