### ISSUE TITLE
Send Feedback creates an empty file when Python package is not loaded

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5452]
We return the file name we're about to create, but probably fail while writing the file leading to an empty file. GetUIThread() probably returns null causing a NRE. We should GetUIThread before creating the file, this way it doesn't get created at all if GetUIThread() returns null because our package is not loaded.

**Comment by nikolami** [comment]
Alternatively (perhaps best for performance) - don't create the file at all. Report Problem will ignore files that don't exist on disk.
