### ISSUE TITLE
Test output shows warnings when there are no tests in a file

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/PTVS#5472]
**Describe the bug**
When there is a python file without any tests, the test output window will print warning messages. 

**Steps to Reproduce**
1. Set project to pytest and add an empty python file
2. Open test output window and it will show warnings

**Expected behavior**
Do not show the warnings

**Additional context and screenshots**
```
Warning message: "[7/23/2019 5:14:53.367 PM Warning] No test is available in c:\users\raymon g\source\repos\pytestinfobars\pytestinfobars\module1.py. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again."
```
[Add any other information such as screenshots, error message, or stack trace]
[FileBug.txt](https://github.com/microsoft/PTVS/files/3424507/FileBug.txt)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: VS 2019
PTVS version: Development

**Comment by huguesv** [comment]
@RaymonGulati1  needs to be retested

**Comment by huguesv** [comment]
We'll reactivate if users send feedback.
