### ISSUE TITLE
Pytest discovery should ignore environment folder

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5488]
I have a virtual environment under my workspace, and I enabled pytest.

I'm getting an error from test discovery (and no test discovered):
```
[7/26/2019 12:55:11.508 PM Error] Not a valid Python module: c:\projects\github\temp\pytest\env\lib\site-packages\setuptools\site-patch.py

```

because it's searching for tests under the virtual environment folder.

We should skip any file that's under the active environment's folder.

**Comment by RaymonGulati1** [comment]
Fixed in https://github.com/microsoft/PTVS/pull/5571
