### ISSUE TITLE
Cannot edit my .pyproj file

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#5498]
**Describe the bug**
I have a multi-language solution with Python and C++ projects.

I right-click to Unload my Python project, and then right-click "Edit ...pyproj". It fails to open.

If I open the file directly via Ctrl+O, I see this error:

```
---------------------------
Microsoft Visual Studio
---------------------------
The document 'C:\Projects\....pyproj' is already open as a project or a solution and cannot be opened in an editor at this time.
---------------------------
OK   
---------------------------
```

I assume something is causing it not to be closed correctly with VS when it is unloaded.

**Configuration information**
VS Version: 16.3 Preview 2.0
PTVS version: 16.3.19183.1
Python version: N/A

**Comment by huguesv** [comment]
Low priority, workaround to edit elsewhere.
