### ISSUE TITLE
Run Python test in Visual Studio Online Hosted Build Controller

### ISSUE THREAD

**Issue by lezi226** [Microsoft/PTVS#55]
[Ported from https://pytools.codeplex.com/discussions/633256 per Zooba]
# 

Hi, is there anyone can tell me how to run python test in Visual Studio Online Hosted Build Controller please? 

 From below link: 
https://www.visualstudio.com/en-us/get-started/build/run-tests-with-builds-vs 

 Looks like I should follow answer in question in this webpage "Can I run tests from a different unit test framework in my builds?" 

 But I can't figure out how yet. 
 Thanks
# 

Sat at 5:53 PM

I made some progress to let the controller try to execute my python project .pyproj. Any solution?

> An exception occurred while invoking executor 'executor://pythontestexecutor/v1': Exception has been thrown by the target of an invocation.
> Value cannot be null.
> Parameter name: sp 
> See http://go.microsoft.com/fwlink/?LinkId=254169
# 

 Zooba

Coordinator

Today at 11:49 AM

(You should move this discussion to our  new page on github to continue it, but I'll respond briefly here.) 

 We make some (rather poor) assumptions in our test framework that we are running as part of Visual Studio. This is fairly important for running Python tests, but it does make it difficult to run tests on separate machines. We are considering removing some of the "intelligence" around test detection and having static lists of tests (auto-updating from VS, hopefully), which may help these scenarios. 

 As mentioned above, please continue this discussion on github.

**Comment by lezi226** [comment]
Hi, Zooba, thanks for replying. Is there any workaround so far?

**Comment by zooba** [comment]
I'm not yet deeply familiar with these tests, but if you can run an arbitrary executable then I'd suggest just running Python directly with your tests.

**Comment by zooba** [comment]
The underlying assumptions about tests only being run from within VS are "fixed", but the recommendation to run tests directly in CI (or using [pytest](https://pytest.org)) still stands.
