### ISSUE TITLE
DependcyProperty problem.

### ISSUE THREAD

**Issue by rkamarowski** [Microsoft/PTVS#551]
Visual Studio Community 2013
IronPython
Windows 8.1

I have a button created using xaml. In python I'm trying to set the background using SetValue.  SetValue requires the DependencyProperty and then the value I want to set. I've been searching the net and trying different values, but I can't find where/how to define the DependencyProptery.

xaml:
  <Style TargetType="Button" x:Key="ToolBarButtonStyleZ">
                <Setter Property="Background" Value="Black"/>
                <Setter Property="Foreground" Value="White"  />
                <Setter Property="HorizontalAlignment" Value="Center"/>
                <Setter Property="Height" Value="35"/>
                <Setter Property="TextBlock.FontSize" Value="20"/>
                <Setter Property="VerticalAlignment" Value="Center"/>
                <Setter Property="Width" Value="200"/>
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="Button">
                            <Border Background="{TemplateBinding Background}">
                                <ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>
                            </Border>
                        </ControlTemplate>
                    </Setter.Value>
                    </Setter>
                    <Style.Triggers>
                    <Trigger Property="IsPressed" Value="True">
                        <Setter Property="Background" Value="Gray" />
                    </Trigger>
                    <Trigger Property="IsMouseOver" Value="True">
                            <Setter Property="Background" Value="Gray"/>
                        </Trigger>
                    </Style.Triggers>
                </Style>

<Button Name="ButtonToolbarSession" 
                Content="Session" 
                Style="{DynamicResource ToolBarButtonStyleZ}"
                Margin="0,24,822,617" Click="ButtonToolbarSession_Click">
        </Button>

------------------------------------------------------------------------
Python:
import wpf
import clr
clr.AddReference('System.Drawing')
clr.AddReference("System.Windows")
clr.AddReference("WindowsBase")
clr.AddReference("PresentationCore")
clr.AddReference("PresentationFramework")
from System.Drawing import Color
from System.Windows import Application, DependencyObject, DependencyProperty, MessageBox, Window

class MyWindow(Window):
    def __init__(self):
        wpf.LoadComponent(self, 'Photography.xaml')
    
    def ButtonToolbarSession_Click(self, sender, e):
       self.Background.SetValue(self.Background, Color.Gray)
      #pass
       
if __name__ == '__main__':
    Application().Run(MyWindow())
-----------------------------------------------------------------------------------

If this is not the correct forum, could someone direct me to one?
Thank you,
Bob K.

**Comment by zooba** [comment]
You could also ask on the [IronPython mailing list](http://ironpython.net/support/), or look for similar examples in the regular WPF documentation.

In this case, I think you want to change `self.Background.SetValue(self.Background, Color.Gray)` to something more like:

```python
self.SetCurrentValue(Control.BackgroundProperty, Color.Gray)
```

The pattern is to specify the target (`self`) first, then the property (`Control.BackgroundProperty`) and then the value (`Color.Gray`). `SetCurrentValue` is typically safer than `SetValue` as it behaves more like the user has specified the value (i.e. doesn't break data binding).

**Comment by rkamarowski** [comment]
Thank you.
