### ISSUE TITLE
Failed to launch debug adapter.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5515]
repro step:
1.Create python application and add python unit test item 
2.Typing code in test1.py
```
import unittest
class Test_test1(unittest.TestCase):
    def test_E(self):
        a=1
        b=2
        self.assertEquals(a,b)
```
3.Set breakpoints in the line a=1
4.In TE, select the test and right-click to select Debug Selected tests

expect result:
breakpoints are hit

actual result:
![image](https://user-images.githubusercontent.com/39871640/62283176-87964b00-b483-11e9-9e57-907d4f8808fe.png)
![image](https://user-images.githubusercontent.com/39871640/62283275-c926f600-b483-11e9-86ce-404326badd0e.png)

**Comment by huguesv** [comment]
Tested that this works in the upcoming test explorer update. Will close this when that's inserted into VS.

**Comment by zhouwangyang** [comment]
This issue happened in 16.3 Preview 2.0
![image](https://user-images.githubusercontent.com/39871640/62781341-586a8400-baea-11e9-8419-d06cef9b854b.png)
video to produce this issue:
![test](https://user-images.githubusercontent.com/39871640/62781207-09245380-baea-11e9-8cb7-598962d0b189.gif)

**Comment by huguesv** [comment]
Okay I figured out how you got into this situation. It's because you are using the new debugger (Use legacy debugger is unchecked) but you have the old ptvsd==3.2.1 in your active environment.

You should uninstall ptvsd from the environment, or install the version that matches your "Use legacy debugger" option. You cannot use the legacy debugger with ptvsd 4.x installed, and you cannot use the new debugger with ptvsd 3.x installed.

Note that the "Use legacy debugger" used to be ignored for "Debug Test". It was always using legacy debugger regardless of the option. Now "Debug Test" launches the debugger that you've selected.

**Comment by zhouwangyang** [comment]
Ok, thanks @huguesv , could I debug this tests if I using the new debugger (Use legacy debugger was unchecked) with  installed the ptvsd 4.x? I debugged failed when I installed ptvsd 4.3.0 and legacy debugger was unchecked.

**Comment by huguesv** [comment]
@zhouwangyang Use legacy debugger unchecked and ptvsd 4.3.0 installed should work. I just tried, and it worked, so we'll need more details on the failure.

**Comment by zhouwangyang** [comment]
"Failed to launch debug adapter..." error dialog sometimes has, sometimes does not have, when does not have the following error:
When I installed the latest ptvsd in the current environment and debug the test, after hitting the breakpoint, press F10 to debug, the following phenomenon will occur,
![debugging](https://user-images.githubusercontent.com/39871640/63081214-aad9f380-bf75-11e9-8c8f-281f4a204cf9.gif)

**Comment by huguesv** [comment]
@zhouwangyang that appears to be this bug: https://github.com/microsoft/ptvsd/issues/1611

**Comment by RaymonGulati1** [comment]
Error occurs only once after VS is installed for the first time and tests are debugged.

**Comment by zhouwangyang** [comment]
When I set test Framework in Test tab and debug in pytest file, it was jump to the follwing page:
![image](https://user-images.githubusercontent.com/39871640/64101186-dcd5bd00-cd9f-11e9-8b2e-1bdea0cacad8.png)
**set pytest**
![image](https://user-images.githubusercontent.com/39871640/64101204-e8c17f00-cd9f-11e9-9409-2d0ca2effc7c.png)

**Comment by RaymonGulati1** [comment]
This bug only occurs on the first time VS is installed and a unit test is debugged. If the test is debugged again, bug will not occur. If a python script is debugged, this bug does not occur and subsequent debugging tests will not cause this bug. Since this happens so rarely, we won't be fixing it.
