### ISSUE TITLE
Python.NET remote ptvsd debugging not responding

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#552]
https://pytools.codeplex.com/workitem/2833

I thought this may have been due to .NET 2.0, but apparently ptvsd does not work with recent pythonnet compiled from master under .NET/CLR 4.0.

**Comment by denfromufa** [comment]
I asked last month and apparently the primary developer of pythonnet is using PyCharm to debug pythonnet:

https://mail.python.org/pipermail/pythondotnet/2015-July/001667.html

It is a pity that PTVS does not provide any reliable option to debug Python code embedded in PythonNET.

**Comment by zooba** [comment]
What does `sys.platform` return for Python.NET? I wonder if it's conflicting with some of the support we have for IronPython (which returns `'cli'`).

(A quick look shows we rely on `sys.platform` rather than `import clr` - the latter would almost certainly be a bad idea here.)

**Comment by denfromufa** [comment]
win32

```
using System;
using Python.Runtime;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (Py.GIL())
            {
                dynamic sys = Py.Import("sys");
                Console.WriteLine(sys.platform);
                Console.ReadLine();

            }
        }
    }
}
```

**Comment by denfromufa** [comment]
@zooba @int19h something different I tried unsuccessfully, but maybe you can help me out. In pythonnet I can import the .NET debugger from System.Diagnostics and see if it is attached, but it looks like this debugger does not "see" the Python debugger that I try to attach from PTVS. So is there any approach like this that could work with Python.NET? In short, since ptvsd does not attach, can I use .NET debugger instead with pythonnet?

**Comment by int19h** [comment]
I very much doubt it, since Python.NET itself isn't managed, it just marshals things back and forth. So if you attach, you'd be debugging managed code that Python.NET calls into, but not Python code...

**Comment by denfromufa** [comment]
@int19h @zooba this is working now, see wiki for usage instructions: 

https://github.com/pythonnet/pythonnet/wiki/Various-debugging-scenarios-of-embedded-CPython
