### ISSUE TITLE
The FastCGI process exited unexpectedly. (IIS + wfastcgi + Django)

### ISSUE THREAD

**Issue by erscl** [microsoft/PTVS#5533]
**Describe the bug**

* Windows10 Version 1809 (Build 17763.615)
* IIS 10.0.17763.1
* Python 3.6.8
* Django 2.0.0
* wfastcgi 3.0.0

The FastCGI process has terminated abnormally.

Event Viewer showed the following EventData.
* Exception code: `0xc0000409`
* Failed module path: `C:\Windows\System32\ucrtbase.dll`
* Failed application path: `C:\inetpub\wwwroot\helloworld\venv\scripts\python.exe`
* Fault offset: `0x00000000006e91e`

Here is my web.config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appSettings>
    <add key="WSGI_HANDLER" value="django.core.wsgi.get_wsgi_application()" />
    <add key="PYTHONPATH" value="C:\inetpub\wwwroot\helloworld" />
    <add key="DJANGO_SETTINGS_MODULE" value="helloworld.settings" />
  </appSettings>
    <system.webServer>
        <handlers>
            <add name="Python FastCGI" path="*" verb="*" modules="FastCgiModule" scriptProcessor="c:\inetpub\wwwroot\helloworld\venv\scripts\python.exe|c:\inetpub\wwwroot\helloworld\venv\lib\site-packages\wfastcgi.py" resourceType="Unspecified" />
        </handlers>
        <tracing>
            <traceFailedRequests>
                <add path="*">
                    <traceAreas>
                        <add provider="ASP" verbosity="Verbose" />
                        <add provider="ISAPI Extension" verbosity="Verbose" />
                        <add provider="WWW Server" areas="Authentication,Security,Filter,StaticFile,CGI,Compression,Cache,RequestNotifications,Module,FastCGI,WebSocket" verbosity="Verbose" />
                    </traceAreas>
                    <failureDefinitions statusCodes="500" />
                </add>
            </traceFailedRequests>
        </tracing>
    </system.webServer>
</configuration>
```

**Comment by huguesv** [comment]
Sorry, but just based on that event viewer info, it is rather impossible to tell what could be wrong.

We're not using wfastcgi anymore, it was built for Azure App Service, but that has all migrated to Linux now. I had never seen a crash in Python like this back when I last used it years ago.

The version of the wfastcgi.py that's in this repo is slightly newer than the one on PyPI, so it may be worth replacing it with that one and see if that helps.
