### ISSUE TITLE
pytest doesn't work for simple workspace

### ISSUE THREAD

**Issue by Anapo14** [microsoft/PTVS#5536]
**Describe the bug**
pytest doesn't work for simple projects, but unittest does. Project structure here:

![image](https://user-images.githubusercontent.com/10341823/62495979-68056800-b78c-11e9-89d7-b1df9998ea0a.png)

**Steps to Reproduce**
1. Create any open folder scenario with both pytest and unittest enabled.
2. try to discover tests using the pytest framework. This doesn't work, but unittest does.

**Expected behavior**
both testing frameworks should work.

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/10341823/62495846-fe855980-b78b-11e9-9396-df1a377d84de.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.3.0 Preview 3.0 (29204.9.master)
PTVS version:
Python version:3.7
Debugger Type (if applicable): 

**Diagnostics file**
[Diagnostic Info 2019-08-05T141725.txt](https://github.com/microsoft/PTVS/files/3469459/Diagnostic.Info.2019-08-05T141725.txt)

**Comment by huguesv** [comment]
VS is caching test list in this folder, which is worth trying to delete: `.vs\PythonApplication2\v16\TestStore`

**Comment by huguesv** [comment]
Related issue https://github.com/microsoft/PTVS/issues/5425

**Comment by bschnurr** [comment]
Added more error checking and warnings around this case.. Please try again on tmr's build. related PR  #5572
