### ISSUE TITLE
Test Adapter tests are randomly failing

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/PTVS#5538]
These 4 tests are related to the new python testing framework and they are randomly passing or failing. They only fail if all 4 python versions of the tests are run together (for example, runUnittest on 27, 35, 36, and 37). The tests are not running in parallel.

[broken unit tests.txt](https://github.com/microsoft/PTVS/files/3469713/broken.unit.tests.txt)

![image](https://user-images.githubusercontent.com/3315992/62501470-ee777500-b79f-11e9-86fc-c47accc04b6f.png)

**Comment by huguesv** [comment]
Related to https://github.com/microsoft/PTVS/issues/4386
