### ISSUE TITLE
Test discovery running too often

### ISSUE THREAD

**Issue by bschnurr** [microsoft/PTVS#5541]
**Describe the bug**
Hitting "run all" always triggers a full test discovery

**Steps to Reproduce**
1. open ptvsd in open folder mode
2. set "src" folder in search path in pythonsettings.json
3. set testframe to pytest in pythonsettings.json

**Expected behavior**
After initial discovery, hitting run shouldn't re-trigger discovery if nothing changed.

**Comment by huguesv** [comment]
It happens when you "run test" on a single test as well.

**Comment by bschnurr** [comment]
Filed and issue with the Test Explorer team. bug 966020

**Comment by bschnurr** [comment]
Note: One way to lessen the effect is to set "testpahts" in pytest.ini to speed up discovery

**Comment by bschnurr** [comment]
Latest Test Explorer changes have fixed this.
