### ISSUE TITLE
Only discovery "*_test.py" and "test_*.py" in Test Explorer for pytest in workspace

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5547]
VS Version: 16.3.0 Preview 3.0 [29206.157.master]
Python Tool Version: 16.3.19214.1

Repro step:
1. Open a folder
2. Add some test python file matching `"*test*.py"`
3. Add test function prefixed with 'test' as function name
4. Set "TestFramework" to "Pytest" in "PythonSettings.json"
5. Check "Test Explorer"

Actual Result:
Only discovery `"*_test.py"` and `"test_*.py"` in Test Explorer for pytest in workspace
![image](https://user-images.githubusercontent.com/41426540/62602685-df6eff00-b926-11e9-97a4-529b90cfbb9d.png)

Expect Result:
It should discovery all tests

Note:
It can discovery all tests in Test Explorer for pytest in project

**Comment by huguesv** [comment]
I think that's by design. See http://doc.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery
