### ISSUE TITLE
VS Code Import Issue

### ISSUE THREAD

**Issue by jimgunn3** [microsoft/PTVS#5560]
I am very pleased with VS Code. Many Thanks.

I am coding PyQt5 GUIs as in the below code. This code works perfectly in Idle, Spyder, Python Interactive, and command line. But it does not work in VS Code. I am using the same Python37 installation in VS Code as other tools. I am doing this work on Win10.

When coded in VS Code, the from PyQt5.QtWidgets import QApplication, QWidget statement has errors indicating that "No-Name-in-Module" for QApplication and QWidget. Yet this code runs as coded in other tools. I can modify the VS Code "from ... import..." statement to below commented statement and VS Code works.

I have carefully inspected paths in Idle, Spyder, etc. and changed paths in VS Code, but with no luck so far.

<# pyqt5_gui.py
import sys
from PyQt5.QtWidgets import QApplication, QWidget
#import PyQt5.QtWidgets as pw 
<# prefixing below QApplication and QWidget with pw. and VS Code Works.>
app = QApplication([])
win0 = QWidget()
win0.setWindowTitle('PyQt5')
win0.show()
sys.exit(app.exec_())>

While this may be a bug and I can find workarounds, guidance to use this very common coding method in VS Code will be greatly appreciated. Thanks you.

**Comment by huguesv** [comment]
Issue moved to [microsoft/vscode-python #6914](https://github.com/microsoft/vscode-python/issues/6914) via [**ZenHub**](https://www.zenhub.com/)
