### ISSUE TITLE
Can't edit Python files in Visual Studio diff window

### ISSUE THREAD

**Issue by slishak** [Microsoft/PTVS#557]
When comparing files in Visual Studio compare/diff (for example, comparing a local version to one checked in to TFS source control), I can't edit the local version of the file. This works fine for other file types. I can also try to use automatic refactoring tools on the local version, but it has no effect after pressing "Apply".

**Comment by eroller** [comment]
Not sure if this is a bug, but I would really like to have this work. It was a huge help for developing C# code in Visual Studio.
