### ISSUE TITLE
Closing brackets forces VS2015 to exit

### ISSUE THREAD

**Issue by kplaxmaster** [Microsoft/PTVS#559]
Repeatable everytime in WIndows 10 (10166), VS2015.  Python code with brackets, when closing a bracket VS2015 will crash.

**Comment by zooba** [comment]
Can you post (as a gist) or email (ptvshelp@microsoft.com) the contents of Tools, Python Tools, Diagnostic Info? This should include details of the crash.

**Comment by kplaxmaster** [comment]
https://gist.github.com/kplaxmaster/78431e94f9353ed63082

**Comment by kplaxmaster** [comment]
Playing with it more, its when I have nested brackets, closing the inner bracket causes a crash 100% of the time.  The outter bracket when closed doesn't cause the issue.

**Comment by zooba** [comment]
Looks like you're using 2.2 RC - can you try with one of our [later releases](https://github.com/Microsoft/PTVS/releases) and see if it repros? We had a bug similar to this that we've fixed since then.

**Comment by DinoV** [comment]
Please re-open this if you're still hitting it with a later release
