### ISSUE TITLE
Test framework info bar should not say it found tests when there are no test files

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5634]
Open a project like this one, with the active environment that has pytest installed.

![image](https://user-images.githubusercontent.com/1696845/63451309-c40cf500-c3f8-11e9-9c1d-377f5bc397d1.png)

You won't see the info bar (correct behavior) if you have app.py open automatically when the project is open, like above.

But if you close all windows, close and reopen the project then open app.py, it will show the info bar (incorrect behavior).

![image](https://user-images.githubusercontent.com/1696845/63451394-f28ad000-c3f8-11e9-9d40-5c6d97063a33.png)

**Comment by RaymonGulati1** [comment]
https://github.com/microsoft/PTVS/pull/5637

Fix #5637
