### ISSUE TITLE
Investigate VS2019 compatibility with Python 3.8

### ISSUE THREAD

**Issue by Anapo14** [microsoft/PTVS#5643]
Go try out Python 3.8 with VS, file new issues: what gets broken, what doesn't, etc.

Results:
https://github.com/microsoft/PTVS/issues/5291
https://github.com/microsoft/PTVS/issues/5682
https://github.com/microsoft/PTVS/issues/5683
https://github.com/microsoft/PTVS/issues/5687

**Comment by huguesv** [comment]
Created epic with all the tasks at https://github.com/microsoft/ptvs/issues/5689

**Comment by alexolog** [comment]
Python 3.9 stable is already out and VS is stuck 2 versions behind.
