### ISSUE TITLE
No output in "Output->Debug" window when doing remote debug on window locally

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5651]
VS Version: 16.3.0 Preview 3.0 [29222.145.master]
Python Tool Version: 16.3.19233.3

Repro step:
1. Create a python application and input below code and set a breakpoint:
```
input('>')
from math import cos, radians
def make_dot_string(x):
	rad = radians(x)                             # cos works with radians
	numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	return st
	
def main():
	for i in range(0, 1800, 12):
	    s = make_dot_string(i)
	    print(s)
	
main()
```
2. Install ptvsd on the environment
3. Right-click the environment and select "Open Command Prompt Here..." 
4. Execute "python -m ptvsd --host [host ip] --port 4022 [.py file]. e.g. <python -m ptvsd --host 127.0.0.1 --port 4022 C:\Users\vxiaofz\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py>
5. On VS and select Debug->Attach to process
6.  Set "Connection type" with "Python remote(ptvsd)" and "Connection target" with "127.0.0.1:4022"
7. In Available processes list, select the appropriate python.exe, click "Attach"
8. Start to debug
9. Check "Output->Debug" window

Actual Result:
No output in "Output->Debug" window when doing remote debug on window locally
![image](https://user-images.githubusercontent.com/41426540/63568551-29ebaf00-c5a8-11e9-9aaf-c0875a56dfec.png)

Attachment is the repro movie:
[debug1.zip](https://github.com/microsoft/PTVS/files/3532903/debug1.zip)

Expect Result:
The content of print statement should output to "Output->Debug" window and Remote window

**Comment by huguesv** [comment]
Same root cause as https://github.com/microsoft/PTVS/issues/5652
