### ISSUE TITLE
IntelliSense for binary modules

### ISSUE THREAD

**Issue by niexuchina** [microsoft/PTVS#5656]
**Description**
Does IntelliSense support binary modules? I import a module which contains a .pyd. But anything in .pyd don't have IntelliSense.

**Tried**
I added possible dependency paths to Search Paths list and global path environment variable. Nothing worked.

**Comment by niexuchina** [comment]
I'm using Python 3.6. Would it be a bug with 3.6?

**Comment by huguesv** [comment]
It's possible. It could also be something in your .pyd that isn't handled.

We're working on integrating the analyzer (aka python language server) used by the VS Code Python extension into VS. Right now we're on an older (and custom) version of that language server (that the team is no longer actively improving).

It could be worth testing with VS Code to see if your .pyd works there. If it does not work in VS Code, you may want to file a bug at https://github.com/microsoft/python-language-server
(make sure you are actually using the microsoft python language server, not jedi, VS Code supports both and may default to one or the other)

If it does work, then the fix will be coming to VS in a future release.

**Comment by niexuchina** [comment]
I tried Visual Studio Code. It works for me.

Thank you!  @huguesv

**Comment by niexuchina** [comment]
@huguesv

Hi. I'm trying Visual Studio Code. I added paths to `python.autoComplete.extraPaths`. Import errors are gone. But members of binaries are still not shown. :(
