### ISSUE TITLE
 [loc][Query][VS_PythonTools] Localizability of 0; "PythonTestFileDetected"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/PTVS#5692]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
A file containing Python tests was detected in the {0} {1}, but the test framework is disabled.

File Name:
localize\ENU\Microsoft.PythonTools.Common.dll

==========================================
Query:

Please, define what will be placeholders replaced by. Same for next strings:
A pytest configuration file was detected in the {0} {1}, but pytest is not enabled. 0; "PyTestInstalledConfigurationFileFound"
A pytest configuration file was detected in the {0} {1}, but pytest is not installed or enabled. 0; "PyTestNotInstalledConfigurationFileFound"
Pytest is enabled in the {0} {1}, but it is not installed in the active environment. 0; "PyTestNotInstalled"

**Comment by RaymonGulati1** [comment]
The "{0}" is replaced by the project or workspace name.
The "{1}" is replaced by either the "workspace" or "project" text, based on which project or workspace name was used. Depending on the language, this text may change. 

The "{0}" is analogous to the name of a person, whereas "{1}" is analogous to the gender of the person. 

Examples (english): 
**If the info bar is shown in a project and the project name is: "HelloWorld"**
"A pytest configuration file was detected in the HelloWorld project, but pytest is not enabled."

**If the info bar is shown in a workspace and the workspace name is: "FOOOOO"**
"A pytest configuration file was detected in the FOOOOO workspace, but pytest is not enabled."

Examples (Chinese):
If the text "project" is translated to "耗" and "workspace" text is translated to "咯".

**If the info bar is shown in a project and the project name is: "姘阿"**
"A pytest configuration file was detected in the 姘阿 耗, but pytest is not enabled."

**If the info bar is shown in a workspace and the workspace name is: "ABC"**
"A pytest configuration file was detected in the ABC 咯, but pytest is not enabled."
