### ISSUE TITLE
[loc][Query][VS_PythonTools] Localizability of 0; "PytestResultsXmlNotFound"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/PTVS#5695]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Results for pytest not found {0}

File Name:
localize\ENU\Microsoft.PythonTools.Common.dll

==========================================
Query:
Please explain what the placeholder will be replaced with. Thanks

**Comment by mark68la** [comment]
https://github.com/microsoft/PTVS/labels/needs%20triage

**Comment by bschnurr** [comment]
The place holder is expected to be a file path to the test results.

**Comment by PDostalek** [comment]
Thanks!
