### ISSUE TITLE
Saving test file doesn't trigger test discovery

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5705]
Add new tests to an existing test file and save the file, discovery is not triggered.

**Steps to Reproduce**
1. New Python application
2. Add New Item, Unit Test
3. Open test explorer
4. Change test framework to unittest or pytest
5. Wait for tests to appear
6. Edit the test file, add a second test method to it, save the file

![image](https://user-images.githubusercontent.com/1696845/64390786-06d6eb80-cffb-11e9-896a-1b39c229b8ce.png)

**Comment by bschnurr** [comment]
updating to latest VS preview 4 release has now fixed this.
![image](https://user-images.githubusercontent.com/1946977/64636748-37ca6e00-d3b7-11e9-96c8-30a85ad2aedd.png)
