### ISSUE TITLE
Cannot discovery large number of tests on python 2.7 envrionment

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5712]
VS Version: 16.4.0 Preview 1.0 [29307.11.master]
Python Tool Version: 16.3.19248.2

Repro step:
1. "New Project->Python->From Existing Python code" to bring up dialog
2. Select a folder such as "C:\Python27\Lib\test" and then click "Next"
3. Select "Python 2.7" as environment and then click "Finish"
4. Open a "test_*.py" file to enable unittest
5. Wait for discovery tests

Actual Result:
Cannot discovery large number of tests on python 2.7 
![image](https://user-images.githubusercontent.com/41426540/64500233-ed7dba00-d2ee-11e9-90d4-dcc89322c4a4.png)

Expect Result:
Discovery tests successfully

**Comment by bschnurr** [comment]
Initial testing points to issues with intellisense, most likely its getting confused due to files inside python 2.7.  

Does this occur on with a another large project?

**Comment by xiaofeng0123** [comment]
It can discover the large number of tests on python 3.7 at this the same project. but cannot discover on python 2.7.

And it can discover tests on another large project

**Comment by bschnurr** [comment]
This seem to be related to the test code assuming that the test folder is not the root.

In other words this is an issue specific to this project.
