### ISSUE TITLE
Interactive window does not stop working when an environment where the interpreter executable is missing

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5719]
**reproduce environment**
![image](https://user-images.githubusercontent.com/39871640/64682857-c96bd580-d4b4-11e9-8b70-71e9b0056ad3.png)

**Steps to Reproduce**
1.Create Python Application project with 3.7 (64-bit )Python Environment
2.Open interactive window and select Environment Python  3.7 (64-bit) 
3.Typing code in interactive window and press enter
2+2
4.You can find the result is 4 in the interactive window
5.Go to the installation directory of python3.7(64 bit) and rename python.exe
6.Typing code again in interactive window and press enter
2+2

**Expected behavior**
The code should not be execute in interactive window.

**Actual behavior**
The code was executed in interactive window

**reproduce video**
[interactive window.zip](https://github.com/microsoft/PTVS/files/3599853/interactive.window.zip)

**Comment by huguesv** [comment]
Once the python executable is loaded in memory and the session is running, then it won't need python.exe anymore, so this is fine. If you click Reset to close the current session and start a new session, then it will need to launch python.exe again, and at that point will give an error.

```
Type $help for a list of commands.
>>> 0
0
>>> 123
123
Resetting Python state.
The interactive Python process has exited.
>>> 0
The interactive window could not be started because the associated Python environment could not be found.

If this version of Python has recently been uninstalled, you can close this window.
Current interactive window is disconnected.
>>> 
```
