### ISSUE TITLE
Change file opening syntax to use with open(filename, mode)

### ISSUE THREAD

**Issue by farziengineer** [microsoft/PTVS#5729]
https://github.com/microsoft/PTVS/blob/4abfdcef36345fa92ea9cfd304bb2cde73782c56/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/win32/Demos/BackupRead_BackupWrite.py#L17-L19

https://github.com/microsoft/PTVS/blob/4abfdcef36345fa92ea9cfd304bb2cde73782c56/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/win32/Demos/BackupRead_BackupWrite.py#L22-L24

https://github.com/microsoft/PTVS/blob/4abfdcef36345fa92ea9cfd304bb2cde73782c56/Python/Product/Miniconda/Miniconda3-x64/Lib/site-packages/win32/Demos/BackupRead_BackupWrite.py#L26-L28

The above code snippets can be leave the file as open if the exception occurs at 
```python
f.write(data)
```
All the 3 snippets can be replaced with
```python
with open(file_name, 'w') as f:
      f.write(data)
```

**Comment by huguesv** [comment]
This is 3rd party code that is bundled with Miniconda that we ourselves bundle unmodified. It's also just code samples, not product code, and does not affect PTVS. If you'd like to see it fixed, I'd suggest reporting or fixing it at the original source, which seems to be https://github.com/mhammond/pywin32, so it gets included in the next release of Miniconda. Thanks.
