### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by nsfnsf** [microsoft/PTVS#5730]
On Execution of import blpapi in VS2019

**Steps to Reproduce**
1. install blpapi into VS2019 using pip
2. type import blpapi
3. switch python debugger to legacy debugger and hit F5

**Expected behavior**
No Errors

**Additional context and screenshots**
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 90, in <module>
    import ptvsd.debugger as vspd
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd\debugger.py", line 43, in <module>
    import datetime
  File "C:\BloombergWindowsSDK\Python\v3.12.2\blpapi\datetime.py", line 8, in <module>
    from . import internals
ImportError: attempted relative import with no known parent package

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415

Configuration information 
VS Version:2019
PTVS version: 4.3.2
Python version:3.7
Debugger Type (if applicable): [New debugger or legacy debugger?] Legacy
[Diagnostic Info 2019-09-15T082251.txt](https://github.com/microsoft/PTVS/files/3613496/Diagnostic.Info.2019-09-15T082251.txt)
[Diagnostic Info 2019-09-15T082251.txt](https://github.com/microsoft/PTVS/files/3613497/Diagnostic.Info.2019-09-15T082251.txt)

**Comment by bschnurr** [comment]
Usually when you try to import something you need to add it's parent folder instead.

try changing your search path from:
C:\BloombergWindowsSDK\Python\v3.12.2\blpapi
to
C:\BloombergWindowsSDK\Python\v3.12.2\

**Comment by nsfnsf** [comment]
Thanks very much for this. Feel a little stupid missing that. This has moved things on although i am getting stuck on the below:

FYI I have downloaded the C++ SDK and added the path for the C++ lib to the environmental variables, and also tried copying the 4 files in the Lib for C++ SDK into the python blpapi directory in the hope that they are then used but to no avail. I also updated Bloomberg on the PC in case that helped fix the problem. I am hoping that there is again something simple that i am missing, if you have any ideas please let me know. Many thanks, Nigel

[Diagnostic Info 2019-09-17T150341.txt](https://github.com/microsoft/PTVS/files/3621721/Diagnostic.Info.2019-09-17T150341.txt)



No module named '_versionhelper'

Could not open the C++ SDK library.

Download and install the latest C++ SDK from:

    http://www.bloomberg.com/professional/api-library

If the C++ SDK is already installed, please ensure that the path to the library
was added to PATH before entering the interpreter.

**Comment by bschnurr** [comment]
Question.. do you need to make actual changes to the SDK, or do you just want to make calls to the blpapi?

Yesterday I was able to get blpapi to install in a conda venv using:
conda install -c conda-forge blpapi

I'll take a look at the log.

**Comment by nsfnsf** [comment]
I am just looking to make calls to the blpapi. I am going to see if i can get this working in VS first but if not will switch to anaconda. 

Thanks for your help!

**Comment by bschnurr** [comment]
So i was able to get a bit further by adding the bin folder to system path.  
C:\\...\blpapi_cpp_3.12.3.1\bin

But then the next message i got was a version mismatch. Note you might have to restart VS
