### ISSUE TITLE
cannot discover the tests immediately after update the configuration in "Test" tab for unittest

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5734]
VS Version: 16.4.0 Preview 2.0 [29316.151.master]
Python version: 16.4.19255.2

Steps to Reproduce
1. Create a python application
2.Add two unittest file such as "test_1.py" "test_2.py" 
3.Set "Test framework" to "unittest"
4. Open "Test Explorer" to make sure the tests are discovered
5. Open "Property->Test", Set "Pattern" to "test_1.py" and then press "Save" button
6. Check "Test Explorer" panel

Expect Result
It should discover the test "test_1.py" immediately after change the configuration for unittest

Actual Result
It cannot discover the tests "test_1.py" immediately after change the configuration for unittest
![image](https://user-images.githubusercontent.com/41426540/65024728-ff530300-d967-11e9-912e-2d85f4f5cca3.png)

**Comment by bschnurr** [comment]
I just tried. Couldn't repro.
 VS Version: 16.4.0 Preview 2.0 [29316.153.master]
Can you try again?

**Comment by xiaofeng0123** [comment]
I tried on 16.4.0 Preview 2.0 [29317.151.master] and always repro. below is my environment, you can repro this issue on my live env if you needed
[Test machine info](https://microsoft.sharepoint.com/teams/CloudPlatformToolsDevOpsCTI/_layouts/OneNote.aspx?id=%2Fteams%2FCloudPlatformToolsDevOpsCTI%2FShared%20Documents%2FTeam%20Notes%2FDevOps%20CTI%20Wuxi&wd=target%2804%20PTVS%2FVS%2FTestResults.one%7C63BE2640-375F-4969-9861-C50F944DE029%2FTest%20Machine%20info%7C2EA9D36B-00A9-455B-BD8A-DF5A977DF565%2F%29
onenote:https://microsoft.sharepoint.com/teams/CloudPlatformToolsDevOpsCTI/Shared%20Documents/Team%20Notes/DevOps%20CTI%20Wuxi/04%20PTVS/VS/TestResults.one#Test%20Machine%20info&section-id={63BE2640-375F-4969-9861-C50F944DE029}&page-id={2EA9D36B-00A9-455B-BD8A-DF5A977DF565}&object-id={6D3B00EE-A535-0A08-3F98-80A81BB080D7}&10)
