### ISSUE TITLE
Dead URL in sample Machine Learning Regression project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#5736]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/733475/dead-url-in-sample-machine-learning-regression-pro.html)._

---
Create new project: set the following filters:

Language=&quot;All languages&quot;,
Platform=&quot;Windows&quot;,
Project type=&quot;Machine Learning&quot;

Three projects will be shown: Classifier, Clustering and Regression.

First two work fine but third one &quot;Regression Project (cookiecutter)&quot; fails due to dead sample data URL (http://mldata.org/repository/data/download/csv/stockvalues/).

**Comment by huguesv** [comment]
Thanks. It looks like that mldata.org site is not coming back. We'll have to change the sample to use different data.

**Comment by stevensrmiller** [comment]
Any relationship to mldata.io?

**Comment by valiko-ua** [comment]
Hi, I am original poster of this issue.
I tried different data from mldata.io and openml.org sites but without success. Seems that structure of that data does not correspond to the one expected by the sample application.
So seems like sample application has to be tuned (in addition to new URL).

**Comment by stevensrmiller** [comment]
> Hi, I am original poster of this issue.
> I tried different data from mldata.io and openml.org sites but without success. Seems that structure of that data does not correspond to the one expected by the sample application.

Thanks for following up. It is maddening that the data itself isn't part of this repository.

**Comment by jabowery** [comment]
I would guess the data is available at [this archive.org link](https://web.archive.org/web/20180322001455/http://mldata.org/repository/data/download/csv/stockvalues/) but when I change the source-embedded URL and run the program I get an error:

```Error tokenizing data. C error: Expected 1 fields in line 6, saw 2```

**Comment by valiko-ua** [comment]
@jabowery Amazing, it works! I downloaded this file, changed URL as the following:

`URL = "file:///c:/Users/UserName/Downloads/stockvalues.csv"`

and got nice plots :) If it's legal to use their data then it can be committed to the repo.

**Comment by huguesv** [comment]
Thanks @jabowery and @valiko-ua !

We've checked the license using the Wayback machine, and it's fine.

I'll update the cookiecutter template and add the file to its repo.

**Comment by huguesv** [comment]
I've updated the template. If you have the cookiecutter template already installed, you should be able to right click on it and select update. Or just delete the local template and clone it again.

**Comment by stevensrmiller** [comment]
Good work, thanks.

**Comment by valiko-ua** [comment]
Right-clicking on installed cookiecutter and selecting "Check for updates" didn't help (it just showed message that check for update completed with green tickmark).
I had to delete it and install again, after that I could see your fixes.
