### ISSUE TITLE
Python Test: Newly added test, if right indented, is not discovered by Test Explorer.

### ISSUE THREAD

**Issue by v-asdhin** [microsoft/PTVS#5740]
**Describe the bug**
Python Test Issue: Newly added test, if right indented, is not discovered by Test Explorer.

**Steps to Reproduce**
1. File -> New -> Project -> Python Application 

2. Right-click project, Add -> New Item -> Python Unit Test 

3. In Project Properties, select Test framework as "unittest" under Test.

4. Add another test such as: 

    class TestMod2(unittest.TestCase): 
        def test_mod_pass(self): 
             self.assertEqual(28 % 5, 3) 

        def test_mod_fail(self): 
            self.assertEqual(37 % 5, 0) 

5. Make sure that the test added in Step #4 is indented to the right.

6. Select Run All from Test Explorer.

**Expected behavior**
The newly added tests under TestMod2 should be discovered by Test Explorer.

**Actual behavior**
The newly added tests under TestMod2 are NOT discovered by Test Explorer. These are discovered only if the is no indentation before the class keyword.

**Additional context and screenshots**
![PythonTest_Screenshot](https://user-images.githubusercontent.com/43151029/65166868-5d2e2c00-d9f6-11e9-9624-4e52941d584c.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [rel.d16.3-29317.77](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3059531)
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.

**Comment by bschnurr** [comment]
Sorry in this case the code inside the "if statement" isn't ran because during discovery this file is actually imported and not ran directly, so "__name__" does not equal "__main__"
