### ISSUE TITLE
Stackless Python

### ISSUE THREAD

**Issue by maxrossi** [microsoft/PTVS#5741]
Stackless Python is supported in mixed-mode debugging?
I have a C++ application that embeds a Stackless Python interpreter using Boost.Python, I tried to use mixed mode debugging, but the breakpoints load but are never hit

**Comment by int19h** [comment]
Mixed-mode only supports CPython. It's relatively tolerant of customization, since it uses native symbols to access internal structures. But it does rely heavily on internal CPython implementation details such as frame objects and the bytecode evaluator.

**Comment by maxrossi** [comment]
OK thank you, so only ptvsd can be used in my case, right?

**Comment by huguesv** [comment]
correct
