### ISSUE TITLE
TestExplorer displays wrong duration with pytest

### ISSUE THREAD

**Issue by coreGreenberet** [microsoft/PTVS#5753]
**Describe the bug**
The duration is displayed wrongly most of the time.
In the screenshot you can see, that all 10 tests of "test_async_device" took 100 min. In reality all were finished in about 10 seconds.

In test_base_connection most of the tests were finished in1-2 seconds (which should be correct). One test displays 69 minutes, but it was finished in ~7 seconds.

In test_devices you can see, that it took 380 minutes to finish all these tests. However this took ~32 seconds.

**Steps to Reproduce**
1. Run pytest tests via "Test Explorer"
2. See result

**Expected behavior**
The duration should display the correct duration of the tests.

**Additional context and screenshots**

![grafik](https://user-images.githubusercontent.com/3853374/65424375-b4276d00-de0b-11e9-9f9a-cbbdef020f2f.png)

![grafik](https://user-images.githubusercontent.com/3853374/65424787-afaf8400-de0c-11e9-9491-db3c60866e7c.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.3.0 Preview 4.0
PTVS version: 16.3.19252.1
Python version: 3.7

**Comment by bschnurr** [comment]
Is this an opensource project?

**Comment by bschnurr** [comment]
can you confirm they times your see in the pytest results xml?

In output window under "Test" the 3rd last line should be something like this"
"generated xml file: C:\ProjectPath\TestResults\junitresults_442b4998-75dc-434f-809f-7da2560f206e.xml "

**Comment by coreGreenberet** [comment]
Yes it's  an open source project https://github.com/coreGreenberet/homematicip-rest-api

It might be a localisation issue.
In the xml all times are under 1 second test_acceleration_sensor has "0.862".
My OS is german so a dot is the separator for 1000 and comma is the decimal point.
862 seconds would be 14 minutes.
