### ISSUE TITLE
IronPython .NET constructors and Intellisense failure

### ISSUE THREAD

**Issue by andygraham** [Microsoft/PTVS#576]
IronPython 2.7.5, PTVS 2.2RC and VS 2013 Desktop

To inherit from a C# class and call a specific base class constructor the IronPython docs say

```
.NET constructors can be overloaded.
 To call a specific base type constructor overload, you need to define a
 __new__  method (not __init__) and call __new__ on the .NET base type.
```

Assuming CSharpTest has multiple constructors and I want to call a specific one this, as recommended, works but gives no Intellisense on c

```
class Child (CSharpTest):
    def __new__(cls):
        instance = CSharpTest.__new__(cls, "one", "two")
        return instance

c = Child()
``` 
  
But if I call the C# constructor directly it also works and I get Intellisense on c.

```
class Child (CSharpTest):
    def __new__(cls):
        instance = CSharpTest("one", "two")
        return instance

c = Child()
``` 
 
It looks like Intellisense can’t track through __new__ to see what the resulting type is. I don't know if this is an IronPython documentation failure (why bother going through  __new__ if calling the constructor directly works) or something that Intellisense doesn't, or can't, do.

Sorry about the formatting  of__ new__ in the last paragraph. It should be double underscore+ "new"+double underscore but I can't see how to override the markdown without putting the text in a code block :(

**Comment by zooba** [comment]
Most likely we don't have any support for calling `__new__` (use a single backtick to quote code inline) on a non-Python class. It's probably just never come up before.

**Comment by zooba** [comment]
Alternatively, we're hitting our default `__new__` handling, which should return an instance of the `cls` parameter, and then we're not handling the managed base class.

**Comment by andygraham** [comment]
It has been pointed out to me that calling the base constructor directly only gives Intellisense on the "c" instance for the original C# class so any further Python defined members of Child are not available in Intellisense. So this is problem has more impact than I originally thought.

**Comment by zooba** [comment]
Yes, but that should match Python's behavior. If you return an object from `__new__` that is not an instance of the class containing `__new__`, then you have created a completely different object.

Your first code snippet is correct and PTVS is incorrectly handling it. You should code correctly for IronPython and don't break your code just for the sake of the editor :)

**Comment by gnychis** [comment]
Thanks for filing this issue, @andygraham!  I've been trying to deal with this, as I have a C# class with a different constructor that I want to call directly.  The only way I can do this is with `__new__`, but as Andy points out, this breaks the Intellisense completely.
