### ISSUE TITLE
Python Projects losing Search Paths on reload

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#5768]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/608925/python-projects-losing-search-paths-on-reload.html)._

---
In a solution with python projects where references have been set, search paths are automatically filled in, but when I repopen the solultion the references are still there but the search paths are missing which causes debugging to break. Removing the project references and re-adding them fixes it temporarily

---
#### Visual Studio Feedback System on 6/16/2019, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/7/2019, 06:33 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .

---
### Original Solutions
(no solutions)

**Comment by bschnurr** [comment]
I was able to repro. looking at this now

**Comment by bschnurr** [comment]
seem to be fixed in the latest for me.
