### ISSUE TITLE
ITestMethodResolver functionality missing 

### ISSUE THREAD

**Issue by bschnurr** [microsoft/PTVS#5776]
Right click in designer to run a single test is currently not implemented.

the default functionality is to run every test is the file.

Look to using QualifiedFunctionNameWalker.cs as an example to convert source, line, to fullyqualifiedname (module + class + funcname), which Test Explorer will use to find the corresponding testcase to pass our test run adapter.

for pytest we will also need to use .pytest_cache nodeids file to match parameter set functions
we can also use partial matching on filename + funcname to save us from trying to find the module name part of the fullyqualifedname.

**Comment by huguesv** [comment]
Run all tests works and other languages do the same, so low priority.
