### ISSUE TITLE
Cannot import modules in immediate window

### ISSUE THREAD

**Issue by jose-alex** [microsoft/PTVS#5799]
In VS 2017 I was able to import python modules using the immediate window. When I try that in 2019 I get the error
SyntaxError('invalid syntax', ('<string>', 1, 6, 'import pandas'))

**Comment by bschnurr** [comment]
I was able to "import pandas" on my local build.  Double check you have the correct Environment set in the Interactive window.

![image](https://user-images.githubusercontent.com/1946977/66331067-93b8e180-e8e6-11e9-8e78-4f09dde9753f.png)

**Comment by huguesv** [comment]
I think @jose-alex is referring to the debugger's immediate window. The difference here is that VS 2017 uses the legacy debugger (ptvsd 3.x) where VS 2019 uses ptvsd 4.x.

An alternative that works is to use the Python Debug Interactive window.

**Comment by jose-alex** [comment]
Like huguesv mentions, I am referring to the immediate window. 
I can import modules in the Python Debug Interactive window, however as I reported in #5800 , one has to be extremely careful not to make any syntax mistakes in that window because any error stops the debugger. This is why I wanted to use the immediate window.

**Comment by judej** [comment]
This scenario is not supported in the immediate window. #5800 is fixed and should be in the next release VS16.5
