### ISSUE TITLE
The first output is incorrect in "Output->Debug" when press F11

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5813]
VS Version: 16.4.0 Preview 2.0 [29410.124.d16.4]
Python Tool Version: 16.4.19275.1

**Steps to Reproduce**
1.Create a python application and type below code:
```
from math import cos, radians
def make_dot_string(x):
	rad = radians(x)                             
	numspaces = int(20 * cos(radians(x)) + 20)   
	st = ' ' * numspaces + 'o'                
	return st
	
def main():
	for i in range(0, 1800, 12):
	    s = make_dot_string(i)
	    print(s)
	
main()
```
2.Set a breakpoint
3.Start debug and press F11

**Expected behavior**
The first output should like below
![image](https://user-images.githubusercontent.com/41426540/66638388-6c944400-ec47-11e9-9a61-d82e2dd557ea.png)

**Actual behavior**
The first output is incorrect
![image](https://user-images.githubusercontent.com/41426540/66638257-2b9c2f80-ec47-11e9-92a6-3ae1bb3dd95c.png)

**Comment by huguesv** [comment]
Looks like the previous message about JustMyCode isn't ending with a new line.

**Comment by huguesv** [comment]
What do you think @karthiknadig ? The message comes from pydevd:
https://github.com/microsoft/ptvsd/blob/a4892f4cd4152b6bcaa600d2a1381e814d725551/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py#L355

**Comment by karthiknadig** [comment]
Yep that is the issue.

**Comment by huguesv** [comment]
Issue moved to [microsoft/ptvsd #1844](https://github.com/microsoft/ptvsd/issues/1844) via [**ZenHub**](https://www.zenhub.com/)
