### ISSUE TITLE
Unable to inspect global/script-wide variables in IronPython, works in Python

### ISSUE THREAD

**Issue by gnychis** [Microsoft/PTVS#583]
PTVS: Dev Build - 2015-07-09
IronPython: 2.7

I have a very simple test application that has a base and child class, where the child inherits the base class:

``` python
import sys

class BaseClass(object):
    def __init__(self):
        self.bValue = 2
    def Ping(self):
        print "Pong"

class Child(BaseClass):
    def Wacky(self):
        print "Wacky"

c = Child()
c.Ping()
```

I've noticed that when using PTVS and standard Python, I am able to debug the instance of the `Child` script-wide variable `c` in the debugger.  However, when using IronPython I am not able to inspect the variable.  

![pythondebugging](https://cloud.githubusercontent.com/assets/1406044/8627831/c177dce8-271b-11e5-9919-beb609c5e22c.PNG)

If I step in to c.Ping(), `self` is visible by the debugger on both ends.

Additionally, if I create a method called `test` and perform the same kind of instructions `d = Child(); d.Ping();` and inspect `d` it is visible in IronPython with PTVS.

![ironpythonfunc](https://cloud.githubusercontent.com/assets/1406044/8627973/da4e307c-271c-11e5-95fc-72ee591c5505.PNG)

**Comment by zooba** [comment]
I think IronPython has some subtleties about the global namespace (or possibly just `globals()`) that we aren't accounting for. @DinoV probably knows better than I do.

**Comment by andygraham** [comment]
This occurs for me with the IronPython (.NET) launcher. Try switching to the Standard Python launcher and it seems to work properly.
