### ISSUE TITLE
LSC: Language server SDK NuGet package

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#5838]
I've created the NuGet.org "PythonTools" organization so we can publish the language server SDK there, and reference it as a NuGet package from PTVS.

I've also reserved the Microsoft.Python.* ids.

We still have to setup the publishing of the package, and the consumption in PTVS.

As a workaround until that is done, I've checked in the SDK dlls in the Python\References\Dev16.0 folder. Note: I think I need that globbing assembly there too, it's a dependency.

.nuspec file for this is athttps://github.com/microsoft/python-language-server/blob/eac8673b90768cadeed0be46ed0d12c00f4162ad/src/LanguageServer/Impl/Python-Language-Server.nuspec

The id in the nuspec will need to be modified to match the id pattern above, ie something like `Microsoft.Python.LanguageServer`, I don't have any strong opinion, but it needs to be within our id reservation.

**Comment by bschnurr** [comment]
Current Analysis id is ```Microsoft-Python-Analysis```

i'll be renaming it to ```Microsoft.Python.Analysis```

**Comment by bschnurr** [comment]
investigating code signing

**Comment by bschnurr** [comment]
turns out we were missing <StrongName>StrongName</StrongName> in our build proj file
