### ISSUE TITLE
Failed to install 'flask' in Python 3.8 conda virtual environement.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5852]
**Test Environment**
![image](https://user-images.githubusercontent.com/39871640/67756336-c765d200-fa74-11e9-8fd3-793481c05b88.png)

**Steps to Reproduce**
1.Create Blank Falsk Web Project in vs
2.Create Conda enviroment following below steps
![image](https://user-images.githubusercontent.com/39871640/67755841-d435f600-fa73-11e9-989a-a3619d057615.png)
3.Right click the conda virtual environment and select Manage Python Packages....
![image](https://user-images.githubusercontent.com/39871640/67756097-59b9a600-fa74-11e9-83c2-0dd54ca60086.png)
4. Input flask to install package
![image](https://user-images.githubusercontent.com/39871640/67756176-79e96500-fa74-11e9-92c9-fb5449186be4.png)

**Expected behavior**
flask can be installed successfully

**Additional context and screenshots**
Failed to install 'flask'

**information in output window**
----- Installing 'flask' -----
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: ...working... failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: ...working... failed
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
  - flask -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0']
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to.  Your current python version
is (python=3.8).  Note that conda will not change your python version to a different minor version
unless you explicitly specify that.
The following specifications were found to be incompatible with each other:
Package wheel conflicts for:
flask -> jinja2[version='>=2.10,>=2.4'] -> setuptools -> wincertstore[version='>=0.2'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip -> wheel
python=3.8 -> pip -> wheel
Package wincertstore conflicts for:
python=3.8 -> pip -> wheel -> setuptools -> wincertstore[version='>=0.2']
flask -> jinja2[version='>=2.10,>=2.4'] -> setuptools -> wincertstore[version='>=0.2']
Package setuptools conflicts for:
python=3.8 -> pip -> wheel -> setuptools
flask -> jinja2[version='>=2.10,>=2.4'] -> setuptools
Package certifi conflicts for:
python=3.8 -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
flask -> jinja2[version='>=2.10,>=2.4'] -> setuptools -> certifi[version='>=2016.09']
Package pip conflicts for:
python=3.8 -> pip
flask -> jinja2[version='>=2.10,>=2.4'] -> setuptools -> wincertstore[version='>=0.2'] -> python[version='>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0,>=3.7,<3.8.0a0'] -> pip
----- Failed to install 'flask' -----

**Comment by bschnurr** [comment]
This appears to be an issue with conda itself not allowing flask to be used with python 3.8.  Not all conda packages with with python 3.8 just yet.  Regular python 3.8 environment dont have this issue.
