### ISSUE TITLE
Remove the python on windows option

### ISSUE THREAD

**Issue by leestott** [microsoft/PTVS#5917]
It is possible to deploy a Python app (e.g. Flask) on Windows using this extension.

This is deprecated (https://docs.microsoft.com/en-us/visualstudio/python/publishing-python-web-applications-to-azure-from-visual-studio?view=vs-2019), leading to an error when trying to run the app.

This leads to confusion with users as they try to deploy a Python app to Widows and see a permissions error on their web site, then they have to google the answer only to find in the docs its deprecated. This was observed at a hackathon this weekend.

Can we remove the option for Windows if they select Python (and maybe add a note in the command palette that windows is deprecated for Python)?

**Comment by qubitron** [comment]
We should signal in the product that this is deprecated, should we recommend users to use VS Code instead for this?

**Comment by huguesv** [comment]
Thanks for the feedback.

We have an existing warning that we put in place a while ago to inform users when the App Service on Windows configuration technique changed:
![image](https://user-images.githubusercontent.com/1696845/69765902-98518780-112a-11ea-9a6c-5c869ac6916d.png)

We should change the contents of that warning:
- Azure App Service on Windows for Python is deprecated
- Azure App Service on Linux for Python is not supported from Visual Studio. We recommend using Visual Studio Code for publishing to it.

I feel we need to continue to let them publish after the warning, and not block it, for users with pre-existing sites, and for users that want to publish to non-Azure locations.

**Comment by leestott** [comment]
@huguesv we should 

We should change the contents of that warning:

Azure App Service on Windows for Python is deprecated
Azure App Service on Linux for Python is not supported from Visual Studio. We recommend using Visual Studio Code for publishing to it.
I agree we need to continue to let them publish after the warning, and not block it, for users with pre-existing sites, and for users that want to publish to non-Azure locations.
