### ISSUE TITLE
Link for PTVS 2.1.1 broken

### ISSUE THREAD

**Issue by puccup** [microsoft/PTVS#5919]
When I click on the PTVS link for Visual Studio 2010 on
 https://github.com/Microsoft/PTVS/releases/v2.1.1
it takes me to
 https://ptvs.blob.core.windows.net/download/PTVS%202.1.1%20VS%202010.msi

which ends up with

This site can’t be reachedptvs.blob.core.windows.net’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by huguesv** [comment]
Thanks for letting us know. I've attached the files to the release.
