### ISSUE TITLE
ipython is very slow and code complete need wait a long time?

### ISSUE THREAD

**Issue by jekoie** [microsoft/PTVS#5924]
I use vs2019,Every time i switch to interactive python and enter some code, it need me waiting a long time.And when i write code in code editor, some time some variable need a long time to show. Pycharm have not those question, but vs2019 had. vs2019 had some good feature, but some feature is very bad.

**Comment by huguesv** [comment]
Thanks for the feedback. We are tracking this issue at https://github.com/microsoft/PTVS/issues/4508
