### ISSUE TITLE
Python code debugging in mixed mode does not work in VS2019 with python 3.6 

### ISSUE THREAD

**Issue by santok1980** [microsoft/PTVS#5927]
We are running python code from managed code (C#) using 3.6 CPython dll (Marshaling). I could see the python debugger attached but still could not set break points. 
Attached simple project which will be helpful to repro the issue.  Select X64 build and change path of python36.dll in CPython.cs file to run the code. Feel free to let me know if you need more details.

 
![PythonMixedModeDebuggingIssue](https://user-images.githubusercontent.com/4975991/70178588-6a6fc400-1691-11ea-9334-4188072f0baf.PNG)

[PythonMixedModeDebugging.zip](https://github.com/microsoft/PTVS/files/3923779/PythonMixedModeDebugging.zip)

**Comment by RaymonGulati1** [comment]
@santok1980, Thank you for the report. 

Can you tell me which VS version you are using? Can you try debugging with Python 3.7 (using the base interpreter, not a virtual environment)

**Comment by santok1980** [comment]
Here are the details 

Microsoft Visual Studio Enterprise 2019
Version 16.4.0

Assuming it works for you, Which versions (VS and Python) are you using where debugging from C# to Python works?

**Comment by judej** [comment]
Not a common scenario. If this needs to be reopened please do.
