### ISSUE TITLE
scikit-learn-based code runs in loop with PTVS in Visual Studio 2013

### ISSUE THREAD

**Issue by baharian** [Microsoft/PTVS#594]
I have a simple Python code (digit recognition exercise from Kaggle), which runs fine if I execute it from the command line (I use Windows 8.1 64-bit with Enthought Canopy 1.4.1). However, the same code behaves extremely strange when executed from within VS2013. It runs until the cross-validation step, and then it starts to loop over the code and rerun everything over and over, sometime spitting out error messages on its way, as shown below: 
![ptvs_error](https://cloud.githubusercontent.com/assets/7094702/8638754/d3de79dc-2892-11e5-801f-f73efada4e15.png)

The code, more details, and my solution is at https://stackoverflow.com/questions/31364379/python-code-runs-in-loop-with-ptvs-in-visual-studio-2013?noredirect=1#comment50709441_31364379

**Comment by int19h** [comment]
Here's the relevant bit:
```
 File "C:\Users\pminaev\AppData\Local\Enthought\Canopy\User\lib\site-packages\s
klearn\externals\joblib\parallel.py", line 595, in __call__
   raise ImportError('[joblib] Attempting to do parallel computing '
ImportError: [joblib] Attempting to do parallel computing without protecting your import on a system that does not support forking. To use parallel-computing in a script, you must protect your main loop using "if __name__ == '__main__'". Please see the joblib documentation on Parallel for more information
```

Also, I'm seeing this repro regardless of whether the script is run from PTVS or directly from command line. 

See the relevant `joblib` doc section that describes what should be done to the code:

https://pythonhosted.org/joblib/parallel.html

Updating the code according to these instructions (i.e. basically wrapping the script in `if __name__ == '__main__':` fixes the issue for me.
