### ISSUE TITLE
Using flake8 and pep8 within Visual Studio 2017 python environment

### ISSUE THREAD

**Issue by Stanislavmaydan** [microsoft/PTVS#5941]
Hello, is there a way to integrate flake8 and pep8 into python environment of Visual Studio 2017? Thanks

**Comment by huguesv** [comment]
Thanks for the feedback.

We don't have anything built-in specifically for these two, but we have a way of extending the Python context menu (right click on a project node in solution explorer) with your own commands.

We've implemented the pylint support using that extensibility. We have documentation for it here: 
https://docs.microsoft.com/en-us/visualstudio/python/defining-custom-python-project-commands

**Comment by Stanislavmaydan** [comment]
Thank you
