### ISSUE TITLE
IronPython unittest debugging

### ISSUE THREAD

**Issue by c200chromebook** [Microsoft/PTVS#595]
All,

I think I'm still having this error: http://pytools.codeplex.com/workitem/2196
RuntimeError: IronPython must be started with -X:Tracing and -X:Frames options to support PTVS remote debugging.

I've added -X:Tracing and -X:Frames to project debug properties and tried with both IronPython and Standard Python Launcher. Is this a known bug?

**Comment by int19h** [comment]
There are two bugs here. The first is that we do not flow through interpreter arguments from project properties to the test adapter (even though we flow most everything else). The second is that we should automatically set -X:Tracing -X:Frames even if it's not specified when we know the tests are running under IronPython.

**Comment by c200chromebook** [comment]
Is there a workaround?

**Comment by int19h** [comment]
I was hoping that I'd have something for you that would require only a modification to a .py file, but unfortunately, that is not the case due to another bug that this unmasks. If you're willing to give building the product a try (it's not actually all that hard - have a look at the wiki page for building, and note that most prereqs are optional), I can give you directions as to the changes that need to be done to fix this.

Unfortunately, at this point, a fix for this issue won't make the bar for 2.2, so a custom build is really the only option here until vNext.

**Comment by c200chromebook** [comment]
A lot of things about IronPython were driving me crazy and I've already
switched to pythonnet. Sorry, I no longer have a dog in this fight. On the
other hand, I got a 24x speedup by switching :-) (at the cost of writing a
~10 line wrapper for .NET dictionaries).

On Mon, Jul 13, 2015 at 1:58 PM, Pavel Minaev <notifications@github.com>
wrote:

> I was hoping that I'd have something for you that would require only a
> modification to a .py file, but unfortunately, that is not the case due to
> another bug that this unmasks. If you're willing to give building the
> product a try (it's not actually all that hard - have a look at the wiki
> page for building, and note that most prereqs are optional), I can give you
> directions as to the changes that need to be done to fix this.
>
> Unfortunately, at this point, a fix for this issue won't make the bar for
> 2.2, so a custom build is really the only option here until vNext.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/PTVS/issues/595#issuecomment-121057527>.
>



-- 
---Mike
--

**Comment by int19h** [comment]
Ah :) if you get a chance to try out mixed-mode debugging with PythonNET, feedback is definitely welcome (just don't forget that you'll need to enable *Native*, Managed and Python in Attach to Process when doing that - don't forget Native, it won't work without it even if you don't actually use it yourself).

**Comment by c200chromebook** [comment]
Will do. Thanks!

On Tue, Jul 14, 2015 at 8:06 PM, Pavel Minaev <notifications@github.com>
wrote:

> Ah :) if you get a chance to try out mixed-mode debugging with PythonNET,
> feedback is definitely welcome (just don't forget that you'll need to
> enable *Native*, Managed and Python in Attach to Process when doing that
> - don't forget Native, it won't work without it even if you don't actually
> use it yourself).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/PTVS/issues/595#issuecomment-121470304>.
>



-- 
---Mike
--

**Comment by denfromufa** [comment]
@c200chromebook can you share minimal example how pythonnet gives you significant speedup? my email is my github handle at gmail dot com. This is great news for pythonnet project and we would like to share this in wiki!
