### ISSUE TITLE
Unable to debug flask and bottle projects with PTVSD 5.*

### ISSUE THREAD

**Issue by RaymonGulati1** [microsoft/PTVS#5954]
There's an issue with bottle and flask web projects. Create new project, install packages as needed and press F5, the browser starts and attempts to load the page but it never ends. By comparison, legacy debugger works fine, also start without debugging is fine.

Related to #5948

**Comment by huguesv** [comment]
I've found a workaround.

Clear the Launch URL text box under project properties debug tab. This will prevent the browser from opening automatically.
Set breakpoint in your route and start debugging.
Manually open browser and navigate to the server URL (which you can see printed in the console)
Request should succeed and breakpoint in the route handler gets hit.

Hypothesis:

It appears to be that the browser is opened too early and the request that is sent to the server may be incomplete/partial and that puts the server in a state that no longer responds to requests (refreshing or sending more requests make no difference).

This used to happen periodically in the past with older versions of ptvsd, more frequently with Edge or Internet Explorer. Maybe those browsers just started faster than Chrome, causing the issue more easily.

Maybe now that we're starting up the adapter python process then starting the app process means that the server is ready to accept requests later than it used to be in the past, causing all browsers to be sending a request too early.

If we switch to watching the output for the URL and invoke the browser only at that time, that should fix the issue. We'll need to decide what to do with regards to the Launch URL in project debug properties though, as that will effectively become deprecated feature.

**Comment by karthiknadig** [comment]
This should be addressed (or at least be better) when you switch to using `output` event to launch the browser rather than pinging the port that we do now.
