### ISSUE TITLE
It displays "..." in Watch/Locals debugger windows with native code debug.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#5963]
## Environment data
Build of Visual Studio: 16.5.0 Preview 2.0 [29709.165.master]
Build of Python Package: 16.5.19345.1

## Expected behavior
This is the correct display.
![image](https://user-images.githubusercontent.com/59192491/72132107-186d3d00-33b9-11ea-94d1-3c09d157b6a9.png)

## Actual behaviour
It displayed Python View and C++ view results after we right click "...".
![image](https://user-images.githubusercontent.com/59192491/72132402-ca0c6e00-33b9-11ea-9660-838f734d160f.png)

## Steps to reproduce:
1. Create new Python Application, add simple Python code
2. Enable "Native Code Debugging" in project settings / debug page
3. Set breakpoint and start debugging
4. In Watch/Locals debugger windows, make sure that you switch Python View and C++ view
5. Check Watch/Locals debugger windows.

**Comment by RaymonGulati1** [comment]
Fixed by debugger team
