### ISSUE TITLE
Information in the output window test panel is displayed twice for each message.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5966]
**Steps to Reproduce**
1.Add unit test in python application project
2.Add some code in this unit test
import unittest
class Test_a_test(unittest.TestCase):
    def test_A(self):
        self.assertEquals(1,1)
if __name__ == '__main__':
    unittest.main()
3.Right click test_A in Test explorer and run this test
4.Open Output window and change to Tests panel

**Expected behavior**
The info of the tests was correctly display once.

**Actual behavior**
Information in the output window test panel is displayed twice for each message.
![image](https://user-images.githubusercontent.com/39871640/72247226-63908580-362f-11ea-8d09-be9a7bad9fd7.png)

**Environment**
![image](https://user-images.githubusercontent.com/39871640/72247269-7e62fa00-362f-11ea-878e-bd0db3821f30.png)

**Comment by huguesv** [comment]
I've reported this to test explorer team when I reproduced it with C# unit tests
https://developercommunity.visualstudio.com/content/problem/880536/test-output-duplicated.html
