### ISSUE TITLE
Extract Method does not appear on the editor context menu

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#597]
(Definitely VS 2015, haven't checked VS 2013 but I doubt it's changed there.)

The Extract Method command is no longer visible on the editor context menu.

It appears under Edit -> Refactor, and the keyboard shortcut still works. Users can use Tools -> Customize to add the item to `Editor Context Menus | Code Window` - "Extract Method" is found under Edit in "Add Command".

**Comment by zooba** [comment]
Moving to 3.0 - this does not meet the bar for 2.2 updates any more.

**Comment by DinoV** [comment]
C# has moved this to Quick Actions
