### ISSUE TITLE
No response when clicking in Watch/Locals debugger windows with native code debug.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#5980]
**Environment data**
Build of Visual Studio: 16.5.0 Preview 3.0 [29715.138.master]
Build of Python Package: 16.5.20009.1

**Steps to Reproduce**
1. Create new Python Application, add simple Python code
2. Enable "Native Code Debugging" in project settings / debug page
3. Set breakpoint and start debugging
4. In Watch/Locals debugger windows, make sure that you switch Python View and C++ view
5. Check Watch/Locals debugger windows.

**Expected behavior**
This is the correct display.
![image](https://user-images.githubusercontent.com/59192491/72502975-97f58300-3875-11ea-9671-ab15b2e26841.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/59192491/72503161-0df9ea00-3876-11ea-969c-7ead909141a0.png)

**Comment by int19h** [comment]
Sounds like #5973?

**Comment by linette-zyy** [comment]
Yes, #5973 can be reproduced. @int19h

**Comment by zhouwangyang** [comment]
#5973 has been closed, is it possible that the build([29715.138](https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=3390006&view=results)) does not contain the modification?

**Comment by huguesv** [comment]
We have not inserted a build that has the fix into VS yet.

**Comment by huguesv** [comment]
I just checked in a local build and it is working properly, so I'll close this. We'll let you know when we have a new build inserted.
