### ISSUE TITLE
print() not working in Debug Console 

### ISSUE THREAD

**Issue by ciararogerson** [microsoft/PTVS#5994]
**Bug**
Using Version 1.37.1 (possibly later versions before 1.41.1), calling print(...) works in the debug console. Since upgrade to 1.41.1, if you call print(...) it does not print in the debug console, only in the terminal window.

**Steps to Reproduce**
1. Run version 1.37.1 in Debug. Call print('hello') => This prints in debug console.
2. Run version 1.41.1 in Debug. Call print('hello') => This does not print in debug console. It only prints in terminal window.

**Expected behavior**
print(...) should print in Debug Console as well as terminal window.

**Comment by huguesv** [comment]
Please see https://github.com/microsoft/ptvsd/issues/2036
