### ISSUE TITLE
 Project dependencies not discoverable (Open Folder extensibility)

### ISSUE THREAD

**Issue by aodl** [microsoft/PTVS#5996]
**How can a project's dependencies (packages) be discovered by third party extensions in Open Folder**
[Open Folder](https://docs.microsoft.com/en-us/visualstudio/extensibility/workspace-indexing?view=vs-2019#types-of-indexed-data) defines an API for registering file dependencies, but this doesn't appear to be utilised by PTVS. 

I'm writing a Visual Studio extension that I would like to work properly in the Open Folder scenario. My extension needs to be able to discover where the dependencies of a project (or startup file) are located. Does PTVS expose a way of discovering this information while the project is loaded in Open Folder (folder view)?

**What have you tried?**
After creating a new Django project and opening it via Open Folder - I've attempted to retrieve`Microsoft.VisualStudio.Workspace.Indexing.FileReferenceInfoType.Dependency` `FileReferenceResult`s from the workspace's `IIndexWorkspaceService`, but there are none. I've also tried the other FileReferenceInfoTypes, but nothing. 

```c#
var projConfigService = await workspace.GetProjectConfigurationServiceAsync();
var currStartupFile = projConfigService.CurrentProject.FilePath;
var indexService = workspace.GetIndexWorkspaceService();
var dependencyResult = await indexService.GetFileReferencesAsync(currStartupFile, referenceTypes: (int)FileReferenceInfoType.Dependency));
// dependencyResult is empty :( 
```

This works for other project systems that are opened via Open Folder, such as [C#, F#, VB](https://github.com/dotnet/project-system). 

The python project definitely has package dependencies, as they are visible via the package manager when switching back to the standard Solution Explorer view.

**Additional context**
One of the primary reasons that [Open Folder](https://docs.microsoft.com/en-us/visualstudio/extensibility/open-folder?view=vs-2019) feature exists is to facilitate extension authors to create rich features for any language, by defining common extension points such as `FileReferenceResult` information. Otherwise an extension author has to consider the special cases of each language and the way that the tooling has been implemented, making it infeasible to ship language agnostic extensions.

I'm hoping there is a way to discover package locations (file paths) that isn't unique to PTVS (and would work just as well for a nodejs project in Open Folder, for example).

**Comment by huguesv** [comment]
Thanks for the feedback.

As you've discovered, PTVS does not implement support for the indexing service.

So unfortunately, you would have to write unique code for PTVS if you want to get at the pip packages for the current Python environment.

**Comment by aodl** [comment]
Okay, thanks @huguesv , are there any plans to provide this support? Does PTVS rely on a language server?

It would be very helpful if you're able to suggest an approach to get at the pip packages from a third party vsix extension. Thanks for your help!

**Comment by huguesv** [comment]
This (indexing) wasn't on our radar until now, and I would say it's unlikely, at least in the short term. Right now we're focused on building a better language server for VS Code (and VS), which we'll integrate into VS.

To get the pip packages from outside PTVS, you'd have to know which Python environment is currently selected (and process when user changes that selection).

If you have python.exe, you can call `python -m pip list` to get the list of packages. You could try getting the selected environment using the standard VS workspace APIs to read the setting from the PythonSettings.json file (and be notified when the value changes) but the value stored there doesn't necessarily make sense for anyone outside PTVS. Sometimes that's an executable path, which is easy enough, but sometimes it's an id created by PTVS, like when it's a global Python install, which requires looking at registry keys to find out the actual location of python.exe.

We have MEF components and interfaces in PTVS for getting selected interperter, etc, but we don't support those for outside use anymore, ie at your own risk, we may break compatibility in any release. And the components/package don't load until one of the Python files in the workspace is opened in the editor. So if you would want to query for info before that happened, you would not get any result.

**Comment by aodl** [comment]
Thanks @huguesv that's really helpful info! This has made me appreciate there really isn't a one size fits all, even in Open Folder. Thanks again.
