### ISSUE TITLE
The left arrow in the server information does not appear correctly in the command window when flaskwebproject is started.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6016]
**Steps to Reproduce**
1.Create FlaskWebProject in VS
2.Create virtual environment like below:
  ![image](https://user-images.githubusercontent.com/39871640/74223067-dce3cc80-4cf0-11ea-9d7b-60e1390ef5ea.png)
3.Make sure virtual environment can be created sucessfully, and then press F5 start debug

**Expected behavior**
The server can be started successfully and Information is displayed correctly

**Actual behavior**
some server information does not display properly in the command window. 
![image](https://user-images.githubusercontent.com/39871640/74223501-ce49e500-4cf1-11ea-847b-45c709d8a8fc.png)
OutPut window:
![image](https://user-images.githubusercontent.com/39871640/74223706-457f7900-4cf2-11ea-9e0b-1972b139c05e.png)

**Testing Environment**
![image](https://user-images.githubusercontent.com/39871640/74223576-fafdfc80-4cf1-11ea-819c-f0070c8f131c.png)

**Comment by huguesv** [comment]
The difference here is the version of flask that is used. This appears when using flask 1.1.1, but not in 0.12.15. They probably changed the type of double-quotes they print out.

**Comment by huguesv** [comment]
This happens when running from command line, without any VS involvement, so I'm closing as external.
