### ISSUE TITLE
PTVS 2.1 Error: Refresh DB (Python 3.4 64-bit)

### ISSUE THREAD

**Issue by samuelyusunwang** [Microsoft/PTVS#602]
Here is the copy of diagnose.
https://gist.github.com/samuelyusunwang/3fddd575463589c1c529

Many errors.
Refresh DB fails on Python 3.4 64-bit;
But succeeds on Python 2.7 64-bit.

**Comment by zooba** [comment]
Sorry for the delayed response. It looks like you're hitting a known issue in PTVS 2.1 that's been fixed in PTVS 2.2 (and will also be fixed in PTVS 2.1.1 for VS 2010 and VS 2012 users, coming in a couple of weeks).
