### ISSUE TITLE
python，如何修改自己需要的版本

### ISSUE THREAD

**Issue by WhiteAzzan** [microsoft/PTVS#6026]
2019版本，安装python包，3版本支持的是3.7。我平时使用以及配置都是3.6。我想是否可以添加一个功能，让用户选择自己需求的版本，或者导入外部环境中的已经安装好的python版本。

**Comment by huguesv** [comment]
Translation:
2019 version, installpython package, version 3 supports 3.7. I usually use and configure is 3.6. I wonder if I can add a feature that lets users choose the version they need, or import the installed python version of the external environment.

Answer:
If you install Python 3.6, using the installer from python.org, then Visual Studio will detect it and make it available for you to select.
Please see the documentation at https://docs.microsoft.com/en-us/visualstudio/python/selecting-a-python-environment-for-a-project?view=vs-2019 for how to do this.

**Comment by WhiteAzzan** [comment]
> Translation:
> 2019 version, installpython package, version 3 supports 3.7. I usually use and configure is 3.6. I wonder if I can add a feature that lets users choose the version they need, or import the installed python version of the external environment.
> Answer:
> If you install Python 3.6, using the installer from python.org, then Visual Studio will detect it and make it available for you to select.
> Please see the documentation at https://docs.microsoft.com/en-us/visualstudio/python/selecting-a-python-environment-for-a-project?view=vs-2019 for how to change the current interpreter for your project.

thank you，i get it。
