### ISSUE TITLE
Microsoft.PythonTools.Analyzer leaks memory

### ISSUE THREAD

**Issue by akochepasov** [microsoft/PTVS#6036]
**Describe the bug**
Microsoft.PythonTools.Analyzer leaks memory during work.

**Steps to Reproduce**
1. Open a project with a few python packages and a few python files, using these packaging
2. Work for a day
3. Look for memory usage

**Expected behavior**
Memory consumption should not crawl up

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/973378/76043182-98bca400-5f0b-11ea-91a2-c11e07018925.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.3.6
PTVS version: 16.3
Python version: Anaconda 2 

**Diagnostics file**
[vs_diag.log](https://github.com/microsoft/PTVS/files/4296108/vs_diag.log)

**Comment by huguesv** [comment]
Thanks for the feedback.

We're currently working on a new Python language server which should have better performance, accuracy and memory usage.

We'll integrate it into VS as part of https://github.com/microsoft/PTVS/issues/5210, so you can follow that issue to be notified when that is done. It's still months away, unfortunately.
