### ISSUE TITLE
Python Analzer in VS2019 hugs up all the CPU and memory.

### ISSUE THREAD

**Issue by rakshithm** [microsoft/PTVS#6037]
**Describe the bug**
Using python projects in VS 2019 has become almost impossible. It spawns way too many python analyzer processes, which consume 100% CPU and crashes eventually as it runs out of memory.
See the attached snapshot of system resources being consumed.

**Steps to Reproduce**
1. Open VS 2019 solution with multiple python projects
2. Edit any python source code file
3. See CPU and memory consumption grow instantaneously 

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/32926340/76055381-915ad080-5fc7-11ea-8b83-f48d9e6e39fe.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: VS Pro 2019 v16.3.6
PTVS version: 16.3.19252.1
Python version: 2.7

**Diagnostics file**
[Diagnostic Info 2020-03-06T163138.txt](https://github.com/microsoft/PTVS/files/4296591/Diagnostic.Info.2020-03-06T163138.txt)

**Comment by huguesv** [comment]
Thanks for the feedback.

We're currently working on a new Python language server which should have better performance, accuracy and memory usage.

We'll integrate it into VS as part of https://github.com/microsoft/PTVS/issues/5210, so you can follow that issue to be notified when that is done. It's still months away, unfortunately.

**Comment by innominate227** [comment]
Is there a way to disable Python Background Analysis until #5210 is ready?

**Comment by linette-zyy** [comment]
PUBLIC community feedback: https://developercommunity.visualstudio.com/content/problem/932644/visual-studio-2019-запускает-множество-процессов.html
