### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by luis9717** [microsoft/PTVS#6038]
I have a problem in Visual Studio when I try to import xmltodict (unresolved import), this happends on Visual Studio but it worked on Visual Studio Code, I assume this is because vs doen't support Python 3.8.

**Comment by Amadeus111** [comment]
I have a similar problem I am using Python 3.6. Importing arcpy works fine until it is called from inside a loop

`import os
import arcpy
from datetime import datetime
import shutil
from arcpy import ProjectRaster_management 

arcpy.env.overwriteOutput = True

rectified_folder = "M:\\minemaps\\rectified"
wrong_prints = "P:\\Test\\minemaps_wrong_prints.shp"
wrong_prints_list = []

wrong_projected_TIFs = "P:\\Test\\wrong_projected_TIFs"
correct_projected_TIFs = "P:\\Test\\correct_projected_TIFs"

with arcpy.da.SearchCursor(wrong_prints, ["MapName"]) as cursor:
    for row in cursor:
        wrong_prints_list.append(row[0] + ".tif")

for wrong_image in wrong_prints_list:
    shutil.copy(os.path.join(rectified_folder, wrong_image[0:2]+000, wrong_image[2:5], 
                             wrong_image), os.path.join(wrong_projected_TIFs, wrong_image)
#gives syntax error here    
arcpy.ProjectRaster_management(os.path.join(wrong_projected_TIFs, wrong_image), 
                                   os.path.join(correct_projected_TIFs, wrong_image),
                                   "NAD_1983_2011_StatePlane_Kentucky_FIPS_1600_Ft_US", 
                                   "", "", "", "", "GCS_WGS_1984")`

**Comment by huguesv** [comment]
Thanks for the feedback.

We're currently working on a new Python language server which should have better performance, accuracy and memory usage.

We'll integrate it into VS as part of https://github.com/microsoft/PTVS/issues/5210, so you can follow that issue to be notified when that is done. It's still months away, unfortunately.
