### ISSUE TITLE
wait_for_attach() hangs

### ISSUE THREAD

**Issue by lefig** [microsoft/PTVS#6040]
Hi,

I have the latest VS 2019 and ptvsd but am unable to debug attach into a python session.

I have enabled logging, firewall settings etc. but at a loss to resolve. The following used to work fine in a previous version:

import ptvsd
ptvsd.enable_attach(address=('localhost', 5678), redirect_output=True)
print(f'Python Tool for Visual Studio Debugger {ptvsd.__version__}')
ptvsd.wait_for_attach()
ptvsd.break_into_debugger()

The VS attach debugger dialogue does not get raised.

Thank you

Fig

**Comment by int19h** [comment]
Looks like it's some issue with the debug adapter not being launched correctly.

**Comment by lefig** [comment]
Thank you for that. Yes, but I managed to make some progress and connect fine using no secret and the default port to connect. Strange 

But at least I connect.

Thanks again
