### ISSUE TITLE
The report folder cannot be expanded on Python Performance Explorer window.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6042]
**Steps to Reproduce**
1. Create python application project and add "Lib\test\pystone.py" and remove the default .py file
2. Analyze > Launch Python Profiling …
3. Checked the option "Open project" and select the current project in drop-down list
4. Click "Start"
5. Wait for the command excuttion done/ close it anytime
6. The .vsp file is generated and opened in VS but not saved
7. Expand report folder.

**Expected behavior**
The folder should be expanded.

**Actual behavior**
The report folder cannot be expanded.
![image](https://user-images.githubusercontent.com/59192491/76603724-739de600-6548-11ea-88fe-c74749f1d789.png)

**VS environment**
![image](https://user-images.githubusercontent.com/59192491/76603810-97f9c280-6548-11ea-8de4-bab3a5d09780.png)

**Comment by huguesv** [comment]
confirmed
works in 16.6.0 Preview 2.0 [29901.30.master]
broken in 16.6.0 Preview 2.0 [29912.179.master]

**Comment by huguesv** [comment]
still broken in 16.6.0 Preview 3.0 [29922.37.master]

**Comment by huguesv** [comment]
Filed internal bug 1091598
