### ISSUE TITLE
No Intelligence in Live Share client.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6044]
**Steps to Reproduce**
1.Open python application project 
2.Connect host and client with Live share
3.Typing code in .py file in client
import decimal
decimal.DT

**Expected behavior**
IntelliSense should work well in client and host.

**VS Environment**
![image](https://user-images.githubusercontent.com/39871640/76752668-26757a80-67bb-11ea-8a27-890532cde8c8.png)

**Comment by zhouwangyang** [comment]
fixed using this build:
Build of Visual Studio: 16.6.0 Preview 3.0 [29923.199.master]
Build of Python Package: 16.5.20042.1

**Comment by huguesv** [comment]
thanks for verifying
