### ISSUE TITLE
Error occured when add python file in open folder.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6046]
**Steps to Reproduce**
1.Open folder in VS
2.Right click in this folder and select "Add New Item"->"Python"->"Empty Module"->Open

**Expected behavior**
python file can be added with no errors

**Additional context and screenshots**
error happened.
![image](https://user-images.githubusercontent.com/39871640/76833846-0a2f1780-6867-11ea-8a70-356eeddd711d.png)

**Environment**
![image](https://user-images.githubusercontent.com/39871640/76834297-de606180-6867-11ea-8399-648cb18489f6.png)

**Comment by huguesv** [comment]
@zhouwangyang it looks like they've fixed it? I could not repro using this build:

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.6.0 Preview 3.0 [29922.37.master]

**Comment by zhouwangyang** [comment]
yes, it was fixed in the lastest build:
Build of Visual Studio: 16.6.0 Preview 3.0 [29922.42.master]
Build of Python Package: 16.5.20042.1

**Comment by huguesv** [comment]
thanks for verifying
