### ISSUE TITLE
Cookiecutter template explorer

### ISSUE THREAD

**Issue by bahlahkay** [microsoft/PTVS#6050]
It would be great to have this functionality "stand-alone" are you aware of how this could be replicated outside of VS Studio?

**Comment by huguesv** [comment]
The code is mostly isolated from the rest of PTVS (except for the build) and the user control is also independent from VS SDK, so it should be feasible.
https://github.com/microsoft/PTVS/tree/master/Python/Product/Cookiecutter

If you try to do this and have specific questions, let me know.

**Comment by bahlahkay** [comment]
Great - thanks for the prompt response.

I will give it a go and come back if I get stuck.
