### ISSUE TITLE
Project -> Add existing folder: incompatible behavior of Search Paths

### ISSUE THREAD

**Issue by joseortiz3** [microsoft/PTVS#6073]
**Describe the bug**
If you "add a folder" to a python project (right click project -> add existing folder), the folder is copied into a new subfolder of the python project (if it isn't already one).

However, Search Paths is updated to reference the original folder path, not the new copied folder in the project directory.

Thus, if you edit anything inside the folder, it edits a file inside the copied folder, but Search Paths is still referencing the original folder. This is unexpected behavior that should be changed.

**Steps to Reproduce**
1. Make python project
2. Add an existing folder to the python project, one that isn't currently inside the python project
3. Edit anything inside the folder via the solution explorer. You made changes to the copied version.
4. Intellisense, python, everything is still referencing the original file.

**Expected behavior**
Search Paths should reference the new copied versions, or the folder in the python project should reference the original folder, not a copied version of it.

Or maybe the current behavior is desirable. I'm not sure. It's just highly unexpected, seemed like a bug at first, took me about 10 minutes to understand this unexpected behavior.

Also Project -> References has a similar unexpected behavior to Search Paths.

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 2019 Preview 16.6.0 Preview 2.1
PTVS version: 16.5.20042.1
Python version: 3.8.2

**Comment by huguesv** [comment]
Prior to adding the existing folder, did you have a "Search Paths" entry to point to the original folder location outside of the project?

I'm not sure how you can get to this result by creating a new project, adding a folder from outside the project, and not ever opening the files from the original location or not having a search path to point to the original location.

**Comment by joseortiz3** [comment]
@huguesv You're right, something was very unusual about my situation, I probably misreported what happened. Let me isolate what happened.

**Comment by joseortiz3** [comment]
@huguesv Oh, whoops, ignore the "Search Paths" and "References" behavior. That was my fault, I forgot I had manually added those.

My situation was
Solution
    Project 1
         Project 1 Subfolder
    Project 2
         Search Paths
              Right Click -> Add Project 1 Subfolder (Forgot I did this months earlier)
         Right Click -> Add existing Project 1 Subfolder (Copies Project 1 subfolder to Project 2)

**Comment by joseortiz3** [comment]
Closed because the behavior I thought I experienced wasn't really what happened
