### ISSUE TITLE
When running some python scripts, it stops running groundlessly

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6074]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/633131/it-stops-running-groundlessly.html)._

---
When im running some python scrypts on visual studio, it may stop groundlessly. 
Possible steps:
Edit a script which has a for clause with input command in it
Run it (shift+alt+f5)
Don't do anything(reset python window or re-open vs) but edit the code
Run again (shift+alt+f5)
!it stops at some point!

---
#### Visual Studio Feedback System on 7/4/2019, 05:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Fiona Niu[MSFT] on 7/4/2019, 05:02 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it
#### Visual Studio Feedback System on 8/8/2019, 09:34 AM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
By design, for shift+alt+f5, every time you run, it will stop the previous session.  If you need to keep the session alive, you can select the code you want to run in the editor and press ctrl+enter to send it to the interactive window.
