### ISSUE TITLE
Name Dog is not define

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/920368/name-dog-is-not-define.html)._

---
class Dog:

# class attributute
    type ="dog"

# instance attribute
    def _init_(self, name,age, breed):
        self.name = name
        self.age = age
        self.breed = breed

# instantiate the Dog class
    Milo = Dog("Milo", 1, "Basset Hound")
    Moli = Dog("Moli", 1, "Labrador")

# access the class attributes
    print("Milo is a {}".format(milo.__class__.type))
    print("Moli is also a {}".format(moli.__class__.type))

# access the instance attributes
    print("{} year old and a {}".format( milo.name, milo.age, milo.breed))
    print("{} year old and a {}".format( moli.name, moli.age, moli.breed))

---
#### Visual Studio Feedback System on 2/18/2020, 07:36 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/27/2020, 09:52 AM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
We're completely replacing our IntelliSense / code analysis engine. We're tracking that work at https://github.com/microsoft/PTVS/issues/5210 

I'll close this as we are not fixing bugs in the current analysis engine at this point. Please follow the issue above to track progress on the new Python language service integration work.
