### ISSUE TITLE
Unable to stop at multi-threading debug points

### ISSUE THREAD

**Issue by lefig** [microsoft/PTVS#6080]
Hello all,

Running VS 2019 16.4.3 and attempting to debug a python threading module.

I view my debug console output to confirm it is running fine.

But I am unable to stop i.e hit a configured break point in the code once the run() method commences.

Possibly related to closed:
microsoft/vscode-python#4263  

Thank you 

Fig

**Comment by int19h** [comment]
If you're starting threads by some means other than the Python standard library and its `threading` module, the debugger is not aware of those threads. You can tell it by doing `import ptvsd; ptvsd.debug_this_thread()` on the thread.

**Comment by lefig** [comment]
No. This was pure python code throughout. 

But we have a fix...

I have upgraded to the most recent VS 2019 and am able to step into the code now.

All is well that ends well.:)

Thank you.
