### ISSUE TITLE
Could not find python when add new item in an open folder.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6083]
I couldn't find any python project templates when I want to add new item in an open folder, 

repro steps:
Open New folder in workspace
Right click in this new folder and select Add->New item

**Expected behavior**
![image](https://user-images.githubusercontent.com/39871640/78790160-b7b5c680-79e0-11ea-8a45-4836748478c1.png)

**Actual result**
![image](https://user-images.githubusercontent.com/39871640/78790287-e2a01a80-79e0-11ea-902b-f86a26ed4f42.png)

**build info**
![image](https://user-images.githubusercontent.com/39871640/78790350-fcd9f880-79e0-11ea-89dc-4832c3e61ba1.png)

**intalled extensions**
![image](https://user-images.githubusercontent.com/39871640/78790518-37439580-79e1-11ea-9170-a6f6625bcdac.png)

**Comment by huguesv** [comment]
Internal bug 1094533

**Comment by huguesv** [comment]
Regression has been fiixed by VS
