### ISSUE TITLE
An error dialog pops up when add new item.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6088]
**Environment data**
![image](https://user-images.githubusercontent.com/59192491/79187306-83ae2b80-7e4e-11ea-919c-29ccd28153ea.png)

**Steps to Reproduce**
1. Create new Python Application
2. Right click in SE, Add new item, Empty Python File

**Expected behavior**
The new item should be added successfully.

**Actural behavior**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/59192491/79187256-62e5d600-7e4e-11ea-93eb-67afbe9cfe26.png)

**Comment by linette-zyy** [comment]
This issue is also reproduced when add new item in folder and other projects.

**Comment by huguesv** [comment]
Internal bug 1104154

It is supposed to be fixed already in a newer 16.7 build.

**Comment by huguesv** [comment]
Now works in build 30015.16
