### ISSUE TITLE
No docs for environment variables field in Debug

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#609]
Need to update the screens at https://github.com/Microsoft/PTVS/wiki/Debugging#debugging-with-a-project and describe the new box (esp. how it relates to global or VS process env vars).

**Comment by FrozenKiwi** [comment]
+1

I tried using the field to modify the PATH env variable, or set some random new one (VS2015, PTVS 2.2.40623.00-14.0) and can't get the field to do anything.  Assumption is that either I'm using it wrong or its intended for another purpose?

**Comment by zooba** [comment]
We've actually had the fix for this sitting in a PR for over a year :( It's updated now: https://github.com/Microsoft/PTVS/wiki/Debugging#command-line-arguments-and-environment-variables

**Comment by zooba** [comment]
@FrozenKiwi If you're sure you are using the field correctly, please file a new issue with as much detail as you can.
