### ISSUE TITLE
Update to latest debugpy (beta 10)

### ISSUE THREAD

**Issue by huguesv** [microsoft/PTVS#6090]
We currently bundled beta 5

**Comment by huguesv** [comment]
UI tests `ExpressionEvaluation` and `SetNextLine` fail on beta 8 and 9 (ok on earlier)

**Comment by int19h** [comment]
Expression evaluation might be broken by https://github.com/microsoft/debugpy/pull/127, but can't think of any obvious reason for the other test.

**Comment by huguesv** [comment]
It's the grouping affecting both tests. I've made changes to the config json to pass in `inline` to disable the grouping.

Filed https://github.com/microsoft/PTVS/issues/6111 to expose grouping options to users.

When https://github.com/microsoft/debugpy/issues/236 is fixed, it should get rid of the top level "Locals" scope in VS and make the tests pass again.
