### ISSUE TITLE
VS is not responding after clicking add new item.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6098]
**Environment data**
![image](https://user-images.githubusercontent.com/59192491/80298477-4be4a380-87bf-11ea-9dd6-3159c780c146.png)

**Steps to Reproduce**
1. Create a project 
2. Select Project > Add New Item

**Expected behavior**
The add new item window should pop up.

**Actural behavior**
VS is not responding.
![image](https://user-images.githubusercontent.com/59192491/80298509-9403c600-87bf-11ea-9d8c-cc9a9e8b8891.png)

**Comment by huguesv** [comment]
Internal bug 1111181

**Comment by huguesv** [comment]
Works now in 16.7.0 Preview 1.0 [30028.18.master]
