### ISSUE TITLE
Python background analyzer (PBA)

### ISSUE THREAD

**Issue by nhanh9d** [microsoft/PTVS#6101]
**Describe your question**
Can you optimize PBA? It took 2/3 of my total 12GB RAM when i was making some django app.

![image](https://user-images.githubusercontent.com/41713343/80898942-ea2eb700-8d33-11ea-8757-a1124544a1fe.png)

**Comment by huguesv** [comment]
Thanks for the feedback.

We are working on a new language server aka analyzer that will provide better performance.  We are tracking its integration into VS at https://github.com/microsoft/PTVS/issues/5210. Thanks!

**Comment by Fozefy** [comment]
Is there any suggested work around for this for the time being?

I have a solution with both python and C#, should I consider splitting my solution for now when only working on C# code?

**Comment by huguesv** [comment]
That's one way to do it. You could check your Python environment for packages that you don't need and uninstall them (or create a virtual env with the minimal packages, if you haven't already done that).  In theory it shouldn't matter as code not referenced should be ignored, but you never know, that might help. Also if you have large dictionaries / lists (as literals) in your code or in your libraries, that might contribute to it.
