### ISSUE TITLE
Python modules not working

### ISSUE THREAD

**Issue by H-waseem** [microsoft/PTVS#6116]
How do i make python modules such as pygame,Beautifulsoup etc work in IDE enviroments like visual studio or pyscripter

I tried to add a path directory and install the modules with pip

when i run a test code of import <module> it doesn't  display any errors in the CMD. I use windows 10 if that matters

**Comment by huguesv** [comment]
I would recommend that have a look at the tutorial we have at https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-00-installation?view=vs-2019

It goes through managing environments and installing packages. It may be that you're not running in the same Python environment while you are in VS as you are from CMD.

If you've installed packages in an environment using pip, there is no need to adjust any path for VS to find it. You just need to have the correct Python environment selected in VS when you start the application.

**Comment by H-waseem** [comment]
Thank you so much!

it works fine now
