### ISSUE TITLE
Properties page can be opened in python application project.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6117]
**Steps to Reproduce**
1.Create python application project.
2.Click property pages in the property window.
![image](https://user-images.githubusercontent.com/39871640/82205007-70541b80-9938-11ea-9533-c8f389a6871d.png)

**Expected behavior**
The page can be opened.

**Actual behavior**
Error happened
![image](https://user-images.githubusercontent.com/39871640/82205047-8235be80-9938-11ea-8051-d7c3285f0d40.png)

if right-click in the py app project to select properties from the list,  nothing happened.

**build info**
![image](https://user-images.githubusercontent.com/39871640/82205276-e9537300-9938-11ea-9133-f31c312301b3.png)

**Comment by huguesv** [comment]
```
---------------------------
Microsoft Visual Studio
---------------------------
Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Designer.resources" was correctly embedded or linked into assembly "Microsoft.VisualStudio.AppDesigner" at compile time, or that all the satellite assemblies required are loadable and fully signed.
---------------------------
OK   
---------------------------
```

**Comment by huguesv** [comment]
Filed internal bug 1126853

**Comment by huguesv** [comment]
Now fixed
