### ISSUE TITLE
Could not create new project with python template.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6126]
When creating project with python template, error happened.
![image](https://user-images.githubusercontent.com/39871640/83106128-86a76780-a0ee-11ea-87b6-b332839df781.png)

**build info**
![image](https://user-images.githubusercontent.com/39871640/83106196-a179dc00-a0ee-11ea-88d7-2f100cfd446f.png)

**Comment by huguesv** [comment]
Filed internal bug 1132519

**Comment by huguesv** [comment]
Fixed in VS
