### ISSUE TITLE
Tests can not be found after close and reopen solution.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6135]
**Steps to Reproduce**
1.Create python application project
2.Add test_1.py and typing code
```
import unittest
class Test_test_1(unittest.TestCase):
    def test_A(self):
        self.fail("Not implemented")
if __name__ == '__main__':
    unittest.main()
```
3.Set Test framework as "unittest" in python project properties page.
4.test_1 can be found in TE, then File->close solution, then File->Open->Project/Solution...

**Expected behavior**
test_1 should can be found in TE

**Actual behavior**
test_1 was not found， 0 tests found in Output Tests window.

**build**
![image](https://user-images.githubusercontent.com/39871640/83847447-d7e2d700-a73e-11ea-80d5-0ac944d40999.png)

**Tests also can not be found when reopen folder in workspace.**

**Comment by huguesv** [comment]
When this happens, the only way I get tests to appear again is to restart VS.

**Comment by zhouwangyang** [comment]
the same issue happened when reopen folder in running tests workspace.

**Comment by zhouwangyang** [comment]
Sometimes, When this happens, I get tests to appear again is to restart VS, the breakpoint could not be hit it tests.

**Comment by bschnurr** [comment]
Seems our ITestDiscoverer ( executor://PythonUnitTestExecutor/v1 ) is not being triggered

[logfile.txt](https://github.com/microsoft/PTVS/files/4815624/logfile.txt)

**Comment by bschnurr** [comment]
internal tracking 1136351

**Comment by huguesv** [comment]
This is now fixed in the latest dogfood build.
