### ISSUE TITLE
VS intellisense not working on Pandas Dataframe

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6141]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1060598/vs-intellisense-not-working-on-pandas-dataframe.html)._

---
[regression]
Hey guys,

I have the following lines and vs intellisense shows no useful intellisense for the last line, just mro or next. Don't why this is happening, do I have to use kite? Any other alternative?

I am considering changing the IDE alotogether. Shame on MS. I have been having similar issues for quite sometime.

import pandas as pd
import numpy as np
import time

start_time = time.time()

Load data
df = pd.read_excel('export.xlsx')
df['DTTM_STAMP_SEC'] = pd.to_datetime(df['DTTM_STAMP_SEC_TEXT'], format='%Y-%m-%d %H:%M:%S')
**df.aggr**

---
#### Visual Studio Feedback System on 6/3/2020, 04:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
Thanks for the feedback.

General improvements to IntelliSense (including specific fixes for pandas) will come with the integration of a new language server. I've tested that with our WIP improvements, the aggregate function appears in the completions for your example.

We are tracking the integration work at https://github.com/microsoft/PTVS/issues/5210

**Comment by nono-london** [comment]
Hi have same issue here. Trying to use pd.read_csv, doesn't preempt the right pandas method.
What is the work around suggested, as it is quite a big issue...
I can't find a way to install kite while problem is occurring, any suggestions for another one?
