### ISSUE TITLE
Javascript completions in <script> section does not work with Django Web Project. 

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6145]
**Steps to Reproduce**
1.In a "Django Web Project", validate html completions in app/about.html:
 2.Javascript completions in a <script> section.
**Sample Code**
```
<script>
var s = 3;
s. 
</script> 
```
**Expected behavior**
Javascript completions should work well.

**Actual behavior**
No any intelliSense of s.

**build**
Python:16.7.20160.3
VS:16.7.0 Pre 3.0 [30209.181.master]

**Comment by huguesv** [comment]
Fixed in VS
