### ISSUE TITLE
Question related to Remote debugging and version of Python

### ISSUE THREAD

**Issue by mkashif14** [microsoft/PTVS#6148]
Do I need to have the same version of Python on my local (Windows 10) machine and on the remote machine(Debian 9.4) for remote debugging through Visual Studio Community 2019? Currently, my local machine has CPython 3.7.5 (64-bit) and the remote machine has CPython 3.5.3 (64-bit) and I'm getting "Failed to launch debug adapter!" error when trying to remotely debug a 'Hello World' sort of Python program. The inner exception is "InvalidOperationException: Path to debug adapter executable not specified." I tried a few things and the next one I would like to try is to have both the OS with the same version of CPython installed. I thought to have a quick check over here before submitting a detailed issue.

**Comment by huguesv** [comment]
Can you try a remote debugging on localhost to see if that works better?

Also, make sure to install the same version of debugpy into the Python environment as the one that is bundled with PTVS (to see the bundled version, run `import debugpy;print(debugpy.__version__)` with F5).

There were further changes to launch/attach in VS 2019 16.6, so if you are on 16.5, it would be worth upgrading.

For example, for me I run this with CTRL+F5 then attach to `tcp://localhost:5678` and it stops at the breakpoint. FYI I am on unreleased build of VS where we bundle 1.0.0b10, yours will likely have an older version bundled.
![image](https://user-images.githubusercontent.com/1696845/84965351-926dc480-b0c3-11ea-9f9c-339527fa041d.png)

**Comment by mkashif14** [comment]
> Can you try a remote debugging on localhost to see if that works better?

I already did and that works. I'm able to attach to process on 'localhost'


>Also, make sure to install the same version of debugpy into the Python environment as the one that is bundled with PTVS

This info is helpful. I figured out how to get the bundled version number. The bundled files reside at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\Python\Core" on my machine. The bundled version for me is 1.0.0b5. The version that gets installed using pip resides at "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\site-packages\". I thought I could just replace the debugpy folders at both the locations with the newer version (1.0.0b11) and would make it work. Thank you for letting me know that's not going to work. Will make sure to use the bundled version going forward.

Anyways, looks like my problem is with the firewall settings. When I do a Telnet on 'localhost' (while my program with debugpy statements is running), I do get the following JSON response 
![image](https://user-images.githubusercontent.com/34096765/85128495-08526700-b24f-11ea-8959-06eac97055d9.png)

But when I telnet to my localhost using it's IP, the connection times out. And the same behavior is seen for the remote server. Even when I try to attach to my local process by giving my local IP, I get the same error as mentioned in the starting of this thread. That makes me believe there's firewall problem.

I'm troubleshooting for that and would update once I have a firm answer.

**Comment by mkashif14** [comment]
I figured out what the problem was. My firewall settings were fine, it's just that the remote machine has two versions of Python and I installed debugpy only for the one I was running my program against. I have filed a separate bug for this issue. Closing this one. Here's the link for the bug - https://github.com/microsoft/debugpy/issues/316

Thanks for all the answers and support!
