### ISSUE TITLE
No coloring of the code after send code to interactive.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6151]
**Steps to Reproduce**
1.Typing code in a python app project.
```
#%% code cell1 
import math 
tan = math.tan
	 
#%% code cell2 
pi = math.pi
	
#%% code cell3
e = math.e
print(pi)
```
2.Press ctrl+enter to execute code from the editor window

**Expected behavior**
Code should be sent with color and executed
![image](https://user-images.githubusercontent.com/39871640/85110428-7c880d00-b245-11ea-9e97-217f0819ac5f.png)

**Actual behavior**
could be sent and executed, but no color
![image](https://user-images.githubusercontent.com/39871640/85111425-e654e680-b246-11ea-90cc-3b15c906985b.png)

**build**
![image](https://user-images.githubusercontent.com/39871640/85111465-f53b9900-b246-11ea-840c-8027929c504f.png)

**Comment by huguesv** [comment]
This was fine in 16.6
![image](https://user-images.githubusercontent.com/1696845/85157869-e6d28a80-b210-11ea-90ed-bb7c4f946327.png)

**Comment by huguesv** [comment]
Also worked in 16.7 Preview 2
![image](https://user-images.githubusercontent.com/1696845/85161850-39ae4100-b215-11ea-9da0-8551b30f8a11.png)

**Comment by huguesv** [comment]
Fixes for this were merged in VS earlier today.
