### ISSUE TITLE
In VS2019, IronPython 2.7.10 is installed inconsistently with half disfunctional 64bit environment, while 32bit is OK.

### ISSUE THREAD

**Issue by Hale812** [microsoft/PTVS#6158]
- The current build of VisualStudio 2019 is not consistent with IronPython distribution, and useless for quick start, and studying IronPython, and following manuals, and textbooks.
- Some advanced installation is required, which is not covered in installation instructions.

### Prerequisites

1. Install Visual Studio 2019 Community Edition "with Python" distribution on Windows x64 system, **clean of any development tools.** I repeat, no other development tools, which would alleviate or worsen the situation. Default config.
2. Install IronPython-2.7.10.msi, default config.

* [Y] Are you running the latest version?
* [Y] Are you reporting to the correct repository?
* [Y] Did you perform a cursory search?

### Description

REPL and basic packages essential for quick start, and studying by the book are not available after installation in 64-bit environment, and no directions are given to advanced installation at the official website and distribution.
32bit environment, on the other hand, works out of the box as in the book:

### Steps to Reproduce
1. Start VS 2019 and create an "IronPython Application" project
2. Add IronPython 2.7 (64 bit) environment (working in x64 OS), make it active and remove 32-bit environment.
3. Go to interactive Python console (Alt+I), and change environment to IronPython (x64)
4. Type "import clr". 
A)    Error appears in the Interactive console:
> >>> import clr
> Error using selected REPL back-end:
> IPython mode requires IPython 0.11 or later: No module named IPython
> Using standard backend instead
> 
5. type "2+2"
The same as above ERROR (A) appears
6.  Go to Python Environments -> Search PyPI and installed packages. Type there IPython.
7. Select Install ipython
B) Another error appears:

> ----- Installing 'ipython==7.15.0' -----
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'main'
> ----- Failed to install 'ipython==7.15.0' -----
> 
> 
8. type  "ipy -V" in the interactive console
C) Adnother Error appears:

> Error using selected REPL back-end:
> IPython mode requires IPython 0.11 or later: No module named IPython
> Using standard backend instead
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> NameError: name 'ipy' is not defined
> 
> 

**Expected behavior:** [What you expected to happen]
REPL and pip should be functional in both 32bit and 64 bit IronPython environments after VS2019 and IronPython installation. 

**Actual behavior:** [What actually happened]
Errors (A) (B), and (C) appear, demonstrating semi-dysfunctional state of IronPython installation in x64 environment.
In addition Developer PowerShell is filled with a red garbage:

> `Import-Module : ファイルまたはアセンブリ 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Microsoft.VisualStudio.DevShe
> ll.dll'、またはその依存関係の 1 つが読み込めませんでした。このアセンブリは現在読み込まれているランタイムより新しいランタイムでビルドされているため、読み込
> むことができません。
> 発生場所 行:1 文字:18
> + & { Import-Module <<<<  $env:VSAPPIDDIR\..\Tools\Microsoft.VisualStudio.DevShell.dll}; Enter-VsDevShell -SkipAutomaticLocation -SetDefaultWindowTitle -In
> stallPath $env:VSAPPIDDIR\..\..\
>     + CategoryInfo          : NotSpecified: (:) [Import-Module]、BadImageFormatException
>     + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand
> 
> 用語 'Enter-VsDevShell' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されている こと
> を確認し、パスが含まれている場合はそのパスが正しいことを確認してから、再試行してください。
> 発生場所 行:1 文字:98
> + & { Import-Module $env:VSAPPIDDIR\..\Tools\Microsoft.VisualStudio.DevShell.dll}; Enter-VsDevShell <<<<  -SkipAutomaticLocation -SetDefaultWindowTitle -In
> stallPath $env:VSAPPIDDIR\..\..\
>     + CategoryInfo          : ObjectNotFound: (Enter-VsDevShell:String) []、CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> `

Despite forced English environment, these strings are in wrong Japanese locale, and originaly non-readable in the console.
Probably, it originates from **unchangeable** Windows7 installation locale, which is Japanese, but should be overiden in VisualStudio.
Approximate translation is as follows:
", Or one of its dependencies could not be loaded. This assembly was built with a newer runtime than the one currently loaded, so can not be used. Occurrence line: 1 character: 18

The word 'Enter-VsDevShell' is not recognized as the name of a cmdlet, function, script file, or operable program. Make sure the name is written correctly, and if the path is included, make sure the path is correct and try again.
  Occurrence line: 1 character: 98

### Versions
ipy -V can not be executed from Interactive console
The version displayed at console initialization: IronPython 2.7 (64-bit) interactive window [PTVS 16.6.20100.1-16.0]
Microsoft Visual Studio Community 2019 Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework Version 4.8.03761

**Comment by huguesv** [comment]
Thank you for the feedback.

It appears that the IPython mode was activated for your IronPython 64-bit environment. It should be off by default, like it probably is for your IronPython 32-bit environment.

This can be changed in the Python Environments tool window by unchecking "IPython interactive mode"
![image](https://user-images.githubusercontent.com/1696845/86292871-61eb5780-bba6-11ea-8b36-30920fdb7c8a.png)

I have tested with the IPython interactive mode off using with IronPython 2.7.10, and both 32-bit and 64-bit worked properly.

Note that the support for IronPython (and for Python 2.7 in general) is likely to be removed in the future (or at a minimum, it will be very low priority for us).

If you're just starting out, I would highly recommend that you look at using Python 3 instead.
