### ISSUE TITLE
Visual Studio runs out of memory

### ISSUE THREAD

**Issue by gavrail** [Microsoft/PTVS#616]
VS 2013
PTVS 2.1

Visual studio runs out of memory after I run the following in the IronPython interactive console:

from System import IO
IO.Path.GetInvalidPathChars()

**Comment by zooba** [comment]
Oh boy, that's pretty bad.

The output string has a `\x1b` character in it, which is used to escape colour sequences, but in this case it's not a valid colour sequence.

Unfortunately, the search index is only advanced when it *is* a valid colour sequence (looks like a closing brace moved lines, probably in a merge :( ), which means we're now sitting in an infinite loop writing text to the REPL window. The only way out is to kill VS.
