### ISSUE TITLE
Can not add new item in open folder.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6160]
**Steps to Reproduce**
1.Open Folder1 in vs
2.Right click in Folder1 and select add new item->python->empty module
3.Click open button

**Expected behavior**
the new empty python module should be added under the folder

**Actual behavior**
The page of add new item always appear and the file does not be added

**build **
![image](https://user-images.githubusercontent.com/39871640/86003316-2f294e00-ba44-11ea-997e-ff63a75c7894.png)

**Comment by huguesv** [comment]
Internal issue 1148147

**Comment by huguesv** [comment]
This is now fixed in latest dogfood build.
