### ISSUE TITLE
Properties on Python project .pyproj

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6166]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1091799/properties-on-python-project-pyproj.html)._

---
I want to utilize pytest according to the following article: https://devblogs.microsoft.com/python/whats-new-for-python-in-visual-studio-16-3-preview-2/
However the properties tab of the respective .pyproj file is empty (see screenshot). Thus I cannot select pytest as a test framework. Do you have a suggestion how to get the properties visible?

---
#### Visual Studio Feedback System on 2020/6/28, 03:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
The project properties can be accessed with CTRL+ENTER when the project node is selected in solution explorer, or via the context menu item:
![image](https://user-images.githubusercontent.com/1696845/86388518-cb707200-bc49-11ea-8fb6-b232e4f2a54f.png)

It will open this window where you can configure Test settings:
![image](https://user-images.githubusercontent.com/1696845/86388564-dc20e800-bc49-11ea-9746-b971b9f2969e.png)


Hope this helps!
