### ISSUE TITLE
The option "Add new line on..."became invalid when the option "Enter commits current completion" is unchecked.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6168]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/86450049-90eefe00-bd4b-11ea-965b-01eeb8dc7286.png)

**Steps to Reproduce**
1. Go to Tools > Options > Text Editor > Python > Advanced tab;
2. Uncheck this option "Enter commits current completion";
3. Also uncheck this option "Add new line on enter at end of fully typed word";
4. Input "import sys"(where sys a fully completed word), and press enter.
![image](https://user-images.githubusercontent.com/59192491/86450752-99940400-bd4c-11ea-960c-f9f20cbf8871.png)

**Expected behavior**
Press enter will close completions popup, and cursor remains where i.

**Actual behavior**
press enter will close completions popup and put cursor on next line
![image](https://user-images.githubusercontent.com/59192491/86450879-c21bfe00-bd4c-11ea-96fa-3a2a54145367.png)

**Comment by huguesv** [comment]
These options will go away when we switch to the VS language client IntelliSense implementation along with Pylance.
