### ISSUE TITLE
Can't get intellisense to work on installed modules

### ISSUE THREAD

**Issue by ghost** [Microsoft/PTVS#617]
Hello,
I am new to Python in Visual Studio and I am trying to write a Flask app in it. The issue is that I can't get intellisense to work properly on a few examples.

When I do the following it doesn't allow intellisense:
from flask.ext.bcrypt import Bcrypt

When I do this though, intellisense works:
from flask_bcrypt import Bcrypt

What is causing this issue?

Thank you for the help.

**Comment by zooba** [comment]
If I recall correctly, `flask.ext` isn't a real package, and so we aren't able to detect it. It only appears at runtime when Flask runs some special code to generate it.

I'm not aware of any generic way to handle dynamic package generation like this (some other styles, such as `-nspkg.pth` files, have reasonable workarounds we can add), so we'll just have to consider adding an explicit hack for Flask.

Until then, you can either use the `flask_bcrypt` import, or you can write something like this to get IntelliSense without causing any runtime effects (our analyser doesn't notice that the `if` block will never run):

```python
from flask.ext.bcrypt import Bcrypt
if False: from flask_bcrypt import Bcrypt
```

**Comment by Cosmo-Kramer** [comment]
@zooba Thanks for the help.

**Comment by zooba** [comment]
See #3046
