### ISSUE TITLE
Live Share Error in client When switching between host and Client.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6172]
**Steps to Reproduce**
1. Start a Live Share session for Python projects.
2. Typing code in host and client.

**Expected behavior**
no error during the process

**Actual behavior**
Error occurred while switching from Host to Client.
If the error dialog box is not handled, the dialog box is repeatedly switched several times, and the dialog box appears repeatedly. The following figure shows the situation of switching three times.
![image](https://user-images.githubusercontent.com/39871640/87925517-f87aac80-cab2-11ea-858f-11a1e69d8e4e.png)

**build**
![image](https://user-images.githubusercontent.com/39871640/87925580-1516e480-cab3-11ea-8ba7-97a29ddba7ae.png)

**Comment by bschnurr** [comment]
So the message boxes are dismissible, but there is a bug here where we should know if there is already a LiveShare Error message still being displayed.

**Comment by bschnurr** [comment]
System.IO.IOException: 'Cannot create a file when that file already exists.
'


` 	
mscorlib.dll!System.IO.__Error.WinIOError(int errorCode, string maybeFullPath) Line 188	C#
mscorlib.dll!System.IO.__Error.WinIOError() Line 127	C#
mscorlib.dll!System.IO.File.InternalMove(string sourceFileName, string destFileName, bool checkHost) Line 1237	C#
Microsoft.VisualStudio.LiveShare.Client.dll!Microsoft.Cascade.Client.FileServiceWorkspace.EnsureFileExistImplAsync.AnonymousMethod__6()	Unknown
Microsoft.VisualStudio.LiveShare.Common.dll!Microsoft.Cascade.Common.IOHelper.PerformIOAsync.AnonymousMethod__0(System.Threading.CancellationToken ct)	Unknown
Microsoft.VisualStudio.LiveShare.Common.dll!Microsoft.Cascade.Common.IOHelper.PerformIOAsync.AnonymousMethod__0(System.Threading.CancellationToken ct)	Unknown
Microsoft.VisualStudio.LiveShare.Common.dll!Microsoft.Cascade.Common.IOHelper.PerformIOAsync<bool>(System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task<bool>> operation, Microsoft.Cascade.Common.IOHelperOptions options, System.Threading.CancellationToken cancellationToken)	Unknown
Microsoft.VisualStudio.LiveShare.Common.dll!Microsoft.Cascade.Common.IOHelper.PerformIOAsync(System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task> operation, Microsoft.Cascade.Common.IOHelperOptions options, System.Threading.CancellationToken cancellationToken)	Unknown
Microsoft.VisualStudio.LiveShare.Common.dll!Microsoft.Cascade.Common.IOHelper.PerformIOAsync(System.Action operation, System.Threading.CancellationToken cancellationToken)	Unknown
Microsoft.VisualStudio.LiveShare.Client.dll!Microsoft.Cascade.Client.FileServiceWorkspace.EnsureFileExistImplAsync(string path, string relPath, Microsoft.Cascade.Client.FileServiceWorkspace.DownloadProgress progress, System.Threading.CancellationToken cancellationToken)	Unknown
[Resuming Async Method]	
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 980	C#
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 928	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask) Line 810	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations() Line 3617	C#
mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree() Line 2363	C#
mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result) Line 490	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result) Line 603	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask) Line 638	C#
[Completed] Microsoft.VisualStudio.LiveShare.Common.dll!Microsoft.Cascade.Common.IOHelper.CopyToAsync(System.IO.Stream source, System.IO.Stream destination, System.IProgress<long> progress, System.Threading.CancellationToken cancellationToken)	Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine) Line 1090	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 980	C#
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 928	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() Line 1070	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0() Line 977	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0() Line 288	C#
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke() Line 1123	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper() Line 681	C#
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 715	C#
mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#
[Async Call Stack]	
[Async] Microsoft.VisualStudio.LiveShare.Client.dll!Microsoft.Cascade.Client.FileServiceWorkspace.EnsureFileExistsAsync(string localPath, System.IProgress<(long totalSize, long downloadedSize)> progress, System.Threading.CancellationToken cancellationToken)	Unknown
[Async] Microsoft.VisualStudio.LiveShare.Core.dll!Microsoft.VisualStudio.Cascade.VsLiveShareUIService.OpenDocumentAsync(string filePath, Microsoft.Cascade.Contracts.WorkspaceFileId fileId, bool isPreview, System.Threading.CancellationToken cancellationToken)	Unknown
[Async] Microsoft.VisualStudio.LiveShare.Coauthoring.dll!Microsoft.VisualStudio.Cascade.Coauthoring.UI.CoauthoringService.JumpToClient.AnonymousMethod__0()	Unknown

`

**Comment by zhouwangyang** [comment]
fixed and verified on 16.8.0 Preview 1.0[30323.130.master]
