### ISSUE TITLE
Failed to add new file and new item in folder.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6175]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/88627448-e87c5180-d0de-11ea-8545-d58e35887e10.png)

**Steps to Reproduce**
1. Open a folder
2. Right click in Solution Explorer, click Add option
3. Observe

**Expected behavior**
Successfully added a new file and new item in the folder.

**Actual behavior **
The option of "New File" and "Add New Item" is disabled.
![image](https://user-images.githubusercontent.com/59192491/88627980-c931f400-d0df-11ea-8a30-ed5f6dae1d1e.png)

**Comment by huguesv** [comment]
Internal issue 1163154
