### ISSUE TITLE
Azure Text to Speech | Error: 401 Something went wrong. Check your subscription key and headers.

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [microsoft/PTVS#6183]
**Getting Error: 401 Something went wrong. Check your subscription key and headers.**

**I have Only tried a plain sample from the official documentation with proper subscription keys and region URL.**
My account is active and everything configured correctly, But I'm not able to reach this service.

Language: **Python**

**Sample Code I Used:**
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/text-to-speech?tabs=dotnet%2Clinux%2Cjre%2Cwindowsinstall&pivots=programming-language-python

**Comment by huguesv** [comment]
Hi @shankarThiyagaraajan, please see the support links at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/support#create-a-github-issue for the appropriate GitHub trackers for issues with Azure Text to Speech.

Thanks!
