### ISSUE TITLE
Improve Lint and intellisense for Python 3.8 new Typing feature

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/PTVS#6190]
I think [Python typing](https://docs.python.org/3/library/typing.html) is very important feature for enterprise project. so I think visual studio need to improve Lint and intellisense for this feature, and bring python to 3.8 for such new feature like [PEP-591](https://www.python.org/dev/peps/pep-0591/) and more ...

I think if Visual Studio Enterprise such invest on python with more power and speed, it can be improve and increase python community on Visual Studio and make it is default and main IDE for python on Windows and Mac

**Comment by soroshsabz** [comment]
link to #5689

**Comment by bschnurr** [comment]
Thank you for the feedback. This is already planned to be addressed. 
see https://github.com/microsoft/PTVS/issues/5210
