### ISSUE TITLE
The intellisense of python project in vsiual studio 2019 is mixed

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6194]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1132654/the-intellisense-of-python-project-in-vsiual-studi.html)._

---
Hi,

the version of Visual Studio: VS2019 Community 16.6.5

Reproduce steps:
1. create a project using python application template
2. define a variable (such as int temp1)
3. then, enter code: print(temp1)
4. when editing "temp1" , the intellisense is mixed.  The intellisense can display the temp1 correctly. You can check the temp2.png. 
 Sometimes, it can't be displayed and we need to find temp1 variable by dragging drop-down list. You can check the temp1.png. 
The situation appears in a project page.

Please help to fix it.

Thanks.

---
#### Feedback Bot on 8/3/2020, 00:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment]
Thanks for the feedback. We'll be replacing the analysis engine that powers IntelliSense completions with an improved and more performant one (Pylance - which is currently available in Preview for Visual Studio Code). We are tracking the integration work at https://github.com/microsoft/PTVS/issues/5210
