### ISSUE TITLE
Feature request: Solution configuration/platform dependent project properties

### ISSUE THREAD

**Issue by mbraakhekke** [microsoft/PTVS#6207]
**Describe the feature you are requesting**
Different properties depending on selected Visual Studio solution configuration and/or platform

**Reasons for requesting this feature**
Some properties entered in the properties form are dependent on platform (x64/x86) or other configurations. Right now I have to change these properties manually if I switch between these. The "Configuration" and "Platform" boxes on the properties are greyed out so I assume that this is currently not supported.

**Describe alternatives you've considered**
None, aside from manually changing the properties.

**Comment by huguesv** [comment]
Thanks for the feedback. We have a (very old) work item at https://github.com/microsoft/PTVS/issues/86 that covers this.

**Comment by mbraakhekke** [comment]
> Thanks for the feedback. We have a (very old) work item at #86 that covers this.

OK thanks any idea when this will be added?
