### ISSUE TITLE
Don't show tooltip for string literals

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#622]
Doesn't help in any way, and is annoying with large doc strings.

**Comment by zooba** [comment]
Or maybe just trim the string aggressively - there's some value in the "str"/"bytes"/"unicode" suffix, but not in the content.

**Comment by jnewman-altair** [comment]
I would argue this is a BUG as it makes editing large doc strings extremely difficult to near impossible.

**Comment by zooba** [comment]
Upgrading to a bug because of the report at https://developercommunity.visualstudio.com/content/problem/109893/python-tooltip-when-hovering-long-string-overlap-m.html
