### ISSUE TITLE
python 3.7.8 debugger half as fast as 3.6.6

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/PTVS#6220]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1150570/python-378-debugger-half-as-fast-as-366.html)._

---
[severity:I'm frustrated, but able to complete my work] [regression] [worked-in:16.4.5]
I ran updated debugger (3.7.8) on my code and find it is 50% slower than 3.6.6 version. Also, now the 3.6.8 debugger is also half as fast as the 3.6.6 version. I have a program that downloads csv files does arithmetic on them and writes them out to new csv files. This data conversion process used to take 59.5 secs on 3.6.6. Now it takes 130.7 secs on 3.7.8, and 124.0 secs on 3.6.8.

I have this code on another machine with 3.7.5 and 3.6.6 and can duplicate this at will. Also I can query the system for more details as you need. It is a few hundred lines of code, but I'm sure some simple subset could reproduce the issue.

3.7.8 is an improvement over 3.7.5 where the same code takes 407.2 secs (I've run it repeatedly today to verify) . I first discovered the issue with 3.7.5 a month ago when I finally updated to it. At the time I simply went back to 3.6.6 due to deadlines.

Now 3.7.8 doubles my run times during testing! And 3.6 (now 3.6.8) is no longer a solution.

I live in the debugger! This has a major impact on my project; please address. 

We really cannot afford to let Python debug coding get another 50% slower! 

There are 4 input files totaling only 4.2 MB. They are the 4 Johns Hopkins University covid-19 data files.

The non-debug times are: 16.7 secs for 3.7.8, 18.1 secs for 3.6.8, 26.8 secs for 3.7.5, 27.9 secs for 3.6.6
The ratios for 3.7.8 are debugger is 7.8 times slower than non-debug, 3.6.8 is 6.85, 3.6.6 is 2.1, 3.7.5 is 15.2 times slower! (glad you fixed that!)

The new debugger is enormously slower; please address that as we use it every working hour of every day.

Toolset now, which has 3.7.8 which is slow: 
VS2019 16.7.1, python 16.7.20181.2

Toolset before, which had 3.6.6 which was **speedy**: 
VS2019 16.4.5, python 16.4.19310.1, conda support 16.4.19310.1, python vc project support 16.1.19129.1

Thank you!

Daniel Johnson
*@yyy

---
#### Feedback Bot on 8/17/2020, 11:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by bschnurr** [comment]
now available in VS 16.3 preview
