### ISSUE TITLE
The "Create and push" button is gery when push code to Github.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6223]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/91131619-89aaf780-e6df-11ea-8223-f623abce9cab.png)

**Steps to Reproduce**
1. Create a Blank Django Web Project
2. Click Add to Source Control 
3. Sign in and input necessary information
4. Check the interface

**Expected behavior**
The "Create and push" can be clicked and push the code to Github successfully.

**Actural behavior**
The "Create and push" button is gery.
![image](https://user-images.githubusercontent.com/59192491/91135629-a98eeb00-e6e0-11ea-88b8-69691106da77.png)

**Comment by huguesv** [comment]
I was able to reproduce this in C# Console App project, so I've submitted this via Send Feedback -> Report a Problem.
https://developercommunity.visualstudio.com/content/problem/1162321/create-a-git-repository-dialog-create-and-push-but.html
