### ISSUE TITLE
search navigation is not supported for this type of debugging visual studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6241]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1160972/search-navigation-is-not-supported-for-this-type-o.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
I'm working on a python project. When I hit a breakpoint and do a search inside the debug window, it shows an error popup "Search not supported for this project"(vscode python debugger).
It does highlight the search string in the locals when it finds a match although since I can't submit the query, I have to browse the tree myself.
I checked out the link below and I don't think i fall within the exclusions of Xamarin, Unity, and SQL
https://devblogs.microsoft.com/visualstudio/enhanced-in-visual-studio-2019-search-for-objects-and-properties-in-the-watch-autos-and-locals-windows/#comment-314895

---
#### Feedback Bot on 8/25/2020, 09:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Yingying Zhang [MSFT] on 8/31/2020, 06:03 PM: 

<p>We need more information to confirm if it is a problem, or it is really not supported. Can you provide screenshots of your code and error interface?</p>

####  on 9/3/2020, 09:35 AM: 

screenshot has been attached. When I type in the search box in debugging mode it highlights what i&#39;m looking for,r but if i press enter the error pops up.

---
### Original Solutions
(no solutions)

**Comment by linette-zyy** [comment]
This function works well in native debug.
![image](https://user-images.githubusercontent.com/59192491/92375967-7151c880-f134-11ea-82d2-5020fdced80f.png)

**Comment by huguesv** [comment]
```
---------------------------
Microsoft Visual Studio
---------------------------
Search navigation is not supported for this type of debugging (VSCode Python Debugger).
---------------------------
OK   
---------------------------
```

**Comment by huguesv** [comment]
Looks like if we add a registry key to ProvideDebugAdapterAttributes.cs, it mostly works:
```
            engineKey.SetValue("SupportsEESearch", 1);
```

**Comment by funmise** [comment]
Hi, I was the one who made the initial post. Has the issue been resolved please ?

**Comment by AdamYoblick** [comment]
I did what Hugues suggested and it seems to be working. I have a PR up now. :)
