### ISSUE TITLE
Intente ejecutar un proyecto Database Fun de un curso de python del MVA y me sale error

### ISSUE THREAD

**Issue by lmobarq** [microsoft/PTVS#6252]
[Window Title]
devenv.exe

[Main Instruction]
Se produjo un error inesperado

[Content]
Pulse Ctrl+C para copiar el contenido de este cuadro de diálogo e informe el error en nuestro detector de problemas.

[V] Mostrar detalles  [Cerrar]

[Expanded Information]
```
Build: 16.3.19252.1

System.InvalidOperationException: No se puede iniciar la operación porque pip no está instalado en el entorno en "E:\INFORMATICA3VIDEOS\05 Developing Websites Using Python and Django\DatabaseFun\DatabaseFun\env\".
   en Microsoft.PythonTools.Interpreter.PipPackageManager.<AbortIfNotReady>d__28.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.PythonTools.Interpreter.PipPackageManager.<InstallAsync>d__40.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.PythonTools.Project.TestFrameworkInfoBar.<InstallPyTestAsync>d__4.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.PythonTools.Project.TestFrameworkInfoBar.<InstallAndEnablePytestActionAsync>d__12.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by bschnurr** [comment]
Thank you for the report.

Pip seems to be missing from your "environment folder"

" No se puede iniciar la operación porque pip no está instalado en el entorno en "E:\INFORMATICA3VIDEOS\05 Developing Websites Using Python and Django\DatabaseFun\DatabaseFun\env\""

I recommend re-creating your "env" folder.

**Comment by lmobarq** [comment]
Thank you for answering but i did what you said and i still can not run the project i show the error message  unsolved import 'django'
![imagen](https://user-images.githubusercontent.com/21117200/94118904-c4ee3280-fe13-11ea-88b3-9b5b933cf7cc.png)

**Comment by bschnurr** [comment]
Do you see a Python Environments window?
https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2019#the-python-environments-window

I'm not sure if you have the Python Tools extension installed.
You should also see django in your Packages Window.
![image](https://user-images.githubusercontent.com/1946977/94166086-c3d2fa80-fe3f-11ea-964c-6ecda0de4d98.png)

**Comment by lmobarq** [comment]
the windows i showed doesn't allowed me to  search django package , when i tried to download PyPi package it appears the following error  , what can i do ? Thank you in advance

![imagen](https://user-images.githubusercontent.com/21117200/94240877-8622b000-fed9-11ea-87eb-396ce7ebb463.png)

**Comment by bschnurr** [comment]
try adding a new environment, the button on the top left.

**Comment by lmobarq** [comment]
It works, thank you very much
