### ISSUE TITLE
How can i run python samples in ptvs ?

### ISSUE THREAD

**Issue by lmobarq** [microsoft/PTVS#6261]
**Describe your question**
[A clear and concise description of your question or what you want help with]

**What have you tried?**
[Have you already searched online? What solutions have you tried?]

**Additional context**
[Add any other information or screenshots that would help us provide you with a better answer]

**Comment by lmobarq** [comment]
I downloaded python tool samples from this link https://github.com/Microsoft/PTVS-Samples and i tried to exetute it and it appears this error message (showed bellow), what  can i do to execute this solution ? 
![imagen](https://user-images.githubusercontent.com/21117200/94331946-5f767f00-ff96-11ea-995c-759d8ca3eeb1.png)

**Comment by huguesv** [comment]
The sources at https://github.com/Microsoft/PTVS-Samples were used to build VS project templates for VS 2015 (as a separate download from VS 2015), and are not meant to be loaded directly as a solution/projects. They need to be built and deployed as VS templates, then processed by the VS New Project wizard to be turned into actual projects.

If you're using VS 2019 (16.7 or earlier), the polls project templates are available in the new project dialog, just search for 'polls' to find them.

Note that we've removed them from 16.8 (currently in preview). Some of the samples are dependent on old deprecated libraries and were not worth the maintenance cost.

**Comment by lmobarq** [comment]
Thank you for the answer
