### ISSUE TITLE
Plots in loop: interactive window

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#628]
Hi

When I run a piece of code in the interactive window, I get all the text first, and the plots all come later. Is there a way to avoid this, and instead get it in the order of execution?

Sample code:
df_Data = pd.DataFrame(index=range(20),columns=["Values",])
for ii in range(10):
    df_Data['Values']=np.random.randn(20,1);
    print("Sample "+str(ii));
    df_Data.plot();

Output:
Sample 1
Sample 2
...
Sample 9
Figure 1
Figure 2
... 
Figure 9

Thank you

**Comment by zooba** [comment]
Sorry for the very late response :(

I think this is a limitation of how IPython works - it will try to combine all plots into a single chart and display it at the end, but `pandas` is requesting separate plots so this doesn't happen.

By adding `matplotlib.pyplot.show()` (or `plt.show()` depending on your imports) after the `df_Data.plot()` call, you can get them to interleave.
