### ISSUE TITLE
An error pops up when created an new project from existing.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6281]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/95730639-1f5f0e00-0cb1-11eb-974b-43ec65576394.png)

**Steps to Reproduce**
1. Launch VS and select File > new > Project
2. In the New Project dialog, select "From Existing Python code" under Python node
3. Point to the generated project , and make sure to select "Customize Project Type: Django Web Project" on the last page
4. Click the "Finish" button

**Expected behavior**
The project is created successfully.

**Actual behavior**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/95730564-00f91280-0cb1-11eb-88d5-b64b7088b8bd.png)

**Log**
[ActivityLog.zip](https://github.com/microsoft/PTVS/files/5364599/ActivityLog.zip)

**Comment by huguesv** [comment]
Filed internal bug 1229481

**Comment by linette-zyy** [comment]
This issue also occurred when create Machine Learning project.
Version 16.9.0 Preview 2.0 [30618.9.main]
![image](https://user-images.githubusercontent.com/59192491/96419069-34461f00-1226-11eb-8c41-1c540648618d.png)

**Comment by huguesv** [comment]
Fix for 1229481 was checked into main branch last night, so next build of 16.9 Preview 2 will have it.

**Comment by zhouwangyang** [comment]
And the item related to this issue have creating classifier project, clustering project, regression project and new project from existing.
