### ISSUE TITLE
Plots to clipboard

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#629]
Hi

Is there an easy way to send plots from the interactive window to the  clipboard? I tried to use the sniping tool (and it works), the plots are small by default (and when I zoom in, the resolution becomes very bad - even if I use figsize in the plot options to control the size). 
Since I am generating multiple graphs in a loop, I'd prefer to use inline plots instead of having one window for each graph.

Thank you

**Comment by zooba** [comment]
You can right-click the plot and select Copy. Unfortunately, that won't improve the resolution. There's a matplotlib option for that (`rcParams['figure.dpi']` perhaps? I forget exactly what it is right now, but I have a feeling it isn't actually the DPI setting you expect).

Also, please make sure you're using PTVS 2.2 final (released today), as we fixed a number of bugs around images in the interactive window in the last few weeks.

**Comment by sriksrid** [comment]
Thank you... The resolution ( rc("savefig",dpi=300) ) with a figsize option while plotting seems to work best.
