### ISSUE TITLE
Could not add Microsoft account when create a git repository.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6296]
**Steps to Reproduce**
1. Create python application in vs
2. Click 'Add to source Control' -> Git ->Account
![image](https://user-images.githubusercontent.com/39871640/96554797-961b8d00-12e9-11eb-8f1f-482adfc96263.png)
![image](https://user-images.githubusercontent.com/39871640/96553718-235de200-12e8-11eb-97e8-45acb400b348.png)
3. Click 'Sign in....', select Microsoft
![image](https://user-images.githubusercontent.com/39871640/96553854-57390780-12e8-11eb-8235-489be7eb225b.png)

**Expected behavior**
no errors after select account 'Microsoft'.

**Actual behavior**
error dialog prompt after select account 'Microsoft'.
![image](https://user-images.githubusercontent.com/39871640/96554100-a41cde00-12e8-11eb-8cd3-15dcdfd1e377.png)

**Comment by huguesv** [comment]
This UI is implemented by VS. I was able to reproduce with C# and Node.js projects as well.
Filed internal bug 1236423

**Comment by huguesv** [comment]
Upstream bug resolved
