### ISSUE TITLE
An error message pops up when attach to progress.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6299]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/97537085-2c8e3380-19f9-11eb-9abd-ee6982f98a30.png)

**Steps to Reproduce**
1. Launch VS and create new python application
2. Add an input('>') at the top of your code
3. Add some more python code after that with breakpoint(s)
4. Start WITHOUT debugging
5. Debug > Attach to Process

**Expected behavior**
The "Attach to Progress" screen pops up without any error.

**Actual behavior**
An error message pops up.
![image](https://user-images.githubusercontent.com/59192491/97537533-e84f6300-19f9-11eb-8b6c-9df464022326.png)

**Log**
[ActivityLog.zip](https://github.com/microsoft/PTVS/files/5456699/ActivityLog.zip)

**Comment by huguesv** [comment]
Thank you. I've filed internal bug 1240218.

**Comment by huguesv** [comment]
Upstream bug has been resolved.
