### ISSUE TITLE
 Where is the extension loading the templates from?

### ISSUE THREAD

**Issue by panicoenlaxbox** [microsoft/PTVS#6300]
Hello,

I have seen that there is an option in VS > Settings for specifying the url feed for loading templates, it's value is https://go.microsoft.com/fwlink/?LinkID=823051 but it returns only a few microsoft github repositories, but the extension shows a lot of templates. Is there any url where I can see all these third-party repositories together?

Thank you so much.

**Comment by huguesv** [comment]
It's doing a GitHub search with the term 'cookiecutter' plus what you've pasted in the search bar.
https://github.com/microsoft/PTVS/blob/master/Python/Product/Cookiecutter/Model/GitHubClient.cs#L50

So with empty search, it is https://api.github.com/search/repositories?q=cookiecutter&sort=stars&order=desc&fork=false

Then the results are filtered to only the repositories with a cookiecutter.json file.

**Comment by panicoenlaxbox** [comment]
Very clear, thanks for the answer
I close the issue!
