### ISSUE TITLE
Breakpoints in third party language files does not persist on closing/reopening solution when solution contains C# .NET Core project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6304]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Breakpoints-in-third-party-language-file/1194243)._

---
[severity:It's more difficult to complete my work]
Breakpoints in non-C#/C++ language files does not persist on closing/reopening solution when solution contains C# .NET Core project
Repro steps:
Create python project
Add a main snippet
Add C# .NET Core Console project to solution
Add a breakpoint in python file
Close solution and reopen solution
Breakpoint will not be present in editor of Python file
Close solution and reopen solution again
Breakpoint is still not present on editor. On Debug->Breakpoints window the breakpoint will be shown as line 1 character 1

---
#### Feedback Bot on 9/23/2020, 02:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Marty Lewis on 9/24/2020, 00:41 AM: 

<p>This impacts more languages than Python. Same repro case failed for me on 16.7 using C# .NET Core and a DBL .NET project.</p>

#### Feedback Bot on 9/28/2020, 03:02 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by linette-zyy** [comment]
Environment
![image](https://user-images.githubusercontent.com/59192491/98923863-29259c80-250f-11eb-9eab-d0eb113808ae.png)

After reopen solution, Breakpoint is still not present on editor, but in Breakpoints window, it also display correctly.
![image](https://user-images.githubusercontent.com/59192491/98923821-19a65380-250f-11eb-9b3b-a6ab9999a4ce.png)

**Comment by bschnurr** [comment]
Reading the comments again, Python isn't the only language this is happening to.

After debugging it appears that VS is sending us the wrong line and character numbers.
see ValidateBreakpointLocation in PythonLanguageInfo.cs
