### ISSUE TITLE
wfastcgi monitors for changes in *.config *.py files in wrong location 

### ISSUE THREAD

**Issue by paweljasinski** [microsoft/PTVS#6306]
I have multiple django applications running under one site.
```xml
           <site name="root" id="2" serverAutoStart="true">
                <application path="/" applicationPool="root_pool">
                    <virtualDirectory path="/" physicalPath="C:\root" />
                    <virtualDirectory path="/app1" physicalPath="c:\app1" />
                    <virtualDirectory path="/app2" physicalPath="c:\app2" />
                    <virtualDirectory path="/app3" physicalPath="c:\app3" />
                </application>
                <bindings>
                    <binding protocol="https" bindingInformation="*:443:www.example.com" sslFlags="0" />
                </bindings>
            </site>
```

when I check the wsgi.log, it says:
```log
2020-11-12 22:33:11.493763: wfastcgi.py 3.0.0 started
2020-11-12 22:33:11.493763: Python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
2020-11-12 22:33:11.493763: wfastcgi.py 3.0.0 initializing
2020-11-12 22:33:12.962561: wfastcgi.py will restart when files in C:\root\ are changed: .*((\.py)|(\.config))$
2020-11-12 22:33:12.962561: wfastcgi.py 3.0.0 initialized
```

Is there any way to tell the configured wfastcgi to use the actual physical path of the app (e.g. c:\app3) ?

For now, as workaround, I modify the wfastcgi.py in virtual environment:
```python
            with handle_response(fcgi_stream, record, output.getvalue, errors.getvalue) as response:
                if not initialized:
                    log('wfastcgi.py %s initializing' % __version__)
                    response.physical_path = "C:\\app3" # not nice but works

                    os.chdir(response.physical_path)
                    sys.path[0] = '.'
```

Would it make sense to add something like WSGI_RESTART_DIR to the settings, so it can be changed without mocking with the source code?

**Comment by huguesv** [comment]
Thanks for the feedback.

We now recommend the [HttpPlatformHandler](https://www.iis.net/downloads/microsoft/httpplatformhandler) for using Python with IIS.

We no longer update or support wfastcgi, so it makes sense to change your local copy for your needs.

**Comment by paweljasinski** [comment]
Thanks for the info.
In case anybody think about using HttpPlatformHandler. It is missing some basic functionality (e.g. [REMOTE_USER header is missing](https://forums.iis.net/t/1230254.aspx?HttpPlatformHandler+and+REMOTE_USER)). In my case, the whole point of the IIS is to use Windows Authentication. I guess I will stay with wfastcgi for now.
