### ISSUE TITLE
Cannot create Machine Learning type project.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6318]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/100327051-b4218f00-3005-11eb-920e-c235a61907d0.png)

**Steps to Reproduce**
1. Launch VS
2. Click “Create a new project" 
3. Choose Classifier Project (cookiecutter) and click Next button
4. Click Create button
5. Observe

**Expected behavior**
The project was created successfully.

**Actual result**
The "Configure your new project" screen does not disappear and the project was not created.
![image](https://user-images.githubusercontent.com/59192491/100327586-71ac8200-3006-11eb-9816-9ba48275bfa6.png)

**Comment by linette-zyy** [comment]
Environment
![image](https://user-images.githubusercontent.com/59192491/100416496-9281df80-30b9-11eb-9686-91d38367014e.png)
This issue also occurred when create "From Existing Python Code" project.
"Configure your new project" dialog is still shown after create python project from Existing Python code
![image](https://user-images.githubusercontent.com/59192491/100416447-77af6b00-30b9-11eb-872c-f93d8a172162.png)

**Comment by zhouwangyang** [comment]
can be reproduced on build 16.9.0 Preview 2.0[30803.129.d16.9]

**Comment by judej** [comment]
Please repro on latest build. It was fixed.
