### ISSUE TITLE
No output in the output window when remote debug.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6321]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/101143460-e2305000-3651-11eb-9347-66a1827b5c10.png)

## Steps to reproduce:
1. Create a Python Application project
2. Type the code as following or the code you are desiring 
```
from math import cos, radians
	
# Create a string with spaces proportional to a cosine of x in degrees
def make_dot_string(x):
    rad = radians(x)                             # cos works with radians
    numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
    st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
    return st

def main():
    for i in range(0, 1800, 12):
        s = make_dot_string(i)
        print(s)

main()

```
3. Manage the environment, pip install ptvsd
4. Right-click the python environment and select "Open Command Prompt Here"
5. Execute:
	a. python -m ptvsd -i [host ip] -p [port] <.py file>
6. Launch VS and Debug > Attach to Process, in dialog:
	a. Select connection type with Python remote(ptvsd)
	b. Connection target with 127.0.0.1:4022
	c. In Available processes list, select the appropriate python.exe, click "Attach"
7. Type enter in the console
	a. Check that it stops at the breakpoint
8. Delete breakpoint to press F5 again, it will execute to the end of code.
9. Check the output window.

**Expected behavior**
The output result is displayed in the output window.

**Actual result **
No output in the output window.
![image](https://user-images.githubusercontent.com/59192491/101145971-6c2de800-3655-11eb-82db-d4f1beae9044.png)

**Comment by bschnurr** [comment]
Can't repo on latest
Version 16.9.0 Preview 3.0 [30811.11.main]
