### ISSUE TITLE
Poor diagnostics for new projects when IronPython is not installed

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#633]
All IronPython project templates preset it as a default Python environment for the project. But when it's not installed, you end up with something that just says "Unknown Python 2.7" under Environments, and when you run it you get an error message about said unknown environment being missing or not installed - there's not a word about IronPython there anywhere past the New Project dialog. This is in contrast with regular templates where you get no weird nodes in Solution Explorer, and guidance on where to download Python from if you try to run it. We should do something like that in this scenario, as well (and probably also for other missing Python versions if someone opens an existing project with an explicit environment reference).

**Comment by zooba** [comment]
:( Again. We have a specific help page for this, but it keeps getting lost in other error handling.
