### ISSUE TITLE
Live Share IntelliSense  does not work on vs16.0.22.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6331]
**Steps to Reproduce**
Type code in live share client.
```
import decimal
decimal.
```

Expect Result:
It should show the code intelliSense

Actual Result:
IntelliSense does not work at all.
![image](https://user-images.githubusercontent.com/39871640/102867529-e0e58c80-4473-11eb-8b6f-5d808be5df79.png)
![image](https://user-images.githubusercontent.com/39871640/102868044-a2040680-4474-11eb-984b-7a9556672e5f.png)

**Comment by bschnurr** [comment]
latest local version now shows intelliSense, but only for host.

![image](https://user-images.githubusercontent.com/1946977/102936327-d370d800-445c-11eb-9a5b-01bc2024eee9.png)
