### ISSUE TITLE
Pytest does not work on Python3.7 with VS 16.4.17

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6332]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/103078298-83d10e80-460c-11eb-9e32-37ff181c467f.png)

**Steps to Reproduce**
1. Create a python application
2. Add python files named test_fixture.py
3. Set test framework as pytest
4. Open any of this files and make sure an Info bar should appear to suggest installing pytest	
5. Click "Install pytest"
6. Make sure pytest is installed successfully with no error
7. Make sure these tests can be found in Test Explorer 
8. Click "Run All"

**Expected behavior**
All the tests can be run successfully.

**Actual result **
All the results are skip.
![image](https://user-images.githubusercontent.com/59192491/103078544-11146300-460d-11eb-9ab2-88333580be6c.png)

This issue is not reproduce on Python 2.7
![image](https://user-images.githubusercontent.com/59192491/103081205-6ef77980-4612-11eb-9aec-efc3fff5d95f.png)

**Sample Code**
test_fixture.py
```
import pytest

@pytest.fixture(params=[0, 1, 3])
def data_set(request):
    return request.param

def test_data(data_set):
    assert data_set != 3
```

**Test output**

```
[12/24/2020 9:28:29.041 AM] ---------- Run started ----------
cd C:\Users\vyizh12\source\repos\PythonApplication7\PythonApplication7\
set PYTHONPATH=C:\Users\vyizh12\source\repos\PythonApplication7\PythonApplication7\
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\testlauncher.py" C:\Users\vyizh12\source\repos\PythonApplication7\PythonApplication7\ pytest "" 0 "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\Packages" "" "" dummyfilename .\test_fixture.py::test_data[0] .\test_fixture.py::test_data[1] .\test_fixture.py::test_data[3] --junitxml=C:\Users\vyizh12\source\repos\PythonApplication7\TestResults\junitresults_6e59f737-9f2c-4418-8d0c-c8ff41793466.xml --rootdir=C:\Users\vyizh12\source\repos\PythonApplication7\PythonApplication7
============================= test session starts =============================
platform win32 -- Python 3.7.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\vyizh12\source\repos\PythonApplication7\PythonApplication7
collected 3 items
test_fixture.py ..F                                                      [100%]
================================== FAILURES ===================================
________________________________ test_data[3] _________________________________
data_set = 3
    def test_data(data_set):
>       assert data_set != 3
E       assert 3 != 3
test_fixture.py:8: AssertionError
- generated xml file: C:\Users\vyizh12\source\repos\PythonApplication7\TestResults\junitresults_6e59f737-9f2c-4418-8d0c-c8ff41793466.xml -
=========================== short test summary info ===========================
FAILED test_fixture.py::test_data[3] - assert 3 != 3
========================= 1 failed, 2 passed in 0.04s =========================
Testcase not found for test result: <testcase classname="test_fixture" name="test_data[0]" time="0.001" />
Testcase not found for test result: <testcase classname="test_fixture" name="test_data[1]" time="0.001" />
Testcase not found for test result: <testcase classname="test_fixture" name="test_data[3]" time="0.001">
  <failure message="assert 3 != 3">data_set = 3

    def test_data(data_set):
&gt;       assert data_set != 3
E       assert 3 != 3

test_fixture.py:8: AssertionError</failure>
</testcase>
[12/24/2020 9:28:30.362 AM] ========== Run finished: 3 tests run (0:00:01.3018527) ==========
```

**Comment by bschnurr** [comment]
does it still happen after you delete your .vs folder?

**Comment by linette-zyy** [comment]
This issue still happen after delete my .vs folder.
If only have test_fixture.py , this issue still fail.
![image](https://user-images.githubusercontent.com/59192491/103113130-5039c700-4694-11eb-8a97-0d76b5c8b93e.png)

**Comment by AdamYoblick** [comment]
I'm also unable to repro this. The only issue I ran into was Visual Studio didn't prompt me to install pytest with an info bar. When I restarted VS, it did.

![image](https://user-images.githubusercontent.com/29436557/103588372-ac7bc280-4eae-11eb-8947-2c07c791e8f7.png)

![image](https://user-images.githubusercontent.com/29436557/103588434-cae1be00-4eae-11eb-9b98-8423f0fb54de.png)

**Comment by bschnurr** [comment]
if you can repor this again let us know.
