### ISSUE TITLE
debugging immediate window display problem

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6342]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/debugging-immediate-window-display-probl/1304274)._

---
problem debugging using python. even if i want to see a simple data frame in the immediate window it prints a lots of extra unncecessary things. makes it annoying while debugging. as you see in the picture. If i create a simple df and type in 'test' and hit enter it prints all these *.

---
#### Feedback Bot on 1/7/2021, 09:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
This will be fixed when https://github.com/microsoft/PTVS/issues/6334 is closed, as variable presentation applies to both the watch window and the immediate window. 😄

**Comment by AdamYoblick** [comment]
Verified that setting variable presentation to `hide` or `group` does indeed fix this in the immediate window:

![image](https://user-images.githubusercontent.com/29436557/104508292-a15f1b80-55ad-11eb-88fd-3046cf604f1a.png)

![image](https://user-images.githubusercontent.com/29436557/104508275-9ad0a400-55ad-11eb-9638-c9fa8b211f42.png)

![image](https://user-images.githubusercontent.com/29436557/104508304-a6bc6600-55ad-11eb-816a-8e4e1eca93dc.png)


This options page is not available in VS yet, but I'm working on getting it in.
