### ISSUE TITLE
Error Message when trying to import matplotlib.py

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6346]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Error-Message-when-trying-to-import-matp/1264879)._

---
<p>In Chapter 15 of the book &quot;Python Crash Course 2nd Edition&quot; written by Eric Matthes. Page 338 offers code on &quot;Plotting Dates&quot;:</p><p>Here is the Code</p><p>import csv</p><p>
from datetime import datetime </p><p>import matplotlib.pyplot as plt </p><p>filename = 'data/sitka_weather_07-2018_simple.csv' </p><p>with open(filename) as f: </p><p>reader = csv.reader(f) </p><p>header_row = next(reader) </p><p>
# Get dates high temperatures from this file. </p><p>dates, highs = [], [] </p><p>for row in reader:
  </p><p>current_date = datetime.strptime(row[2], '%Y-%m-%d')
  </p><p>high = int(row[5])
  </p><p>dates.append(current_date)
  </p><p>highs.append(high)
print(highs) </p><p># Plot the high temperatures </p><p>plt.style.use('seaborn') </p><p>fig, ax = plt.subplots()</p><p>ax.plot(dates, highs, c='red') </p><p># Format plot. </p> <p>ax.set_title(&quot;daily high termperatures, July 2018&quot;, fontsize=24) </p><p>ax.set_xlabel('', fontsize=16) </p><p>fig.autofmt_xdate() </p><p>ax.set_ylabel(&quot;Temperature (F)&quot;, fontsize=16) </p><p>ax.tick_params(axis='both', which='major', labelsize=16) </p><p>plt.show()</p><p></p><p></p><p>Below are the details of the error message</p><p>Traceback (most recent call last):
  File &quot;C:\Users\John\Documents\John's Folder\python_work\My_Notes_and_Workshop\Chapter 16 - Downloading Data\sitka_highs.py&quot;, line 4, in &lt;module&gt;
    import matplotlib.pyplot as plt
  File &quot;C:\Users\John\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\__init__.py&quot;, line 107, in &lt;module&gt;
    from . import cbook, rcsetup
  File &quot;C:\Users\John\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\matplotlib\cbook\__init__.py&quot;, line 28, in &lt;module&gt;
    import numpy as np
  File &quot;C:\Users\John\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\__init__.py&quot;, line 305, in &lt;module&gt;
    _win_os_check()
  File &quot;C:\Users\John\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\numpy\__init__.py&quot;, line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\John\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
[Finished in 0.7s]</p> <p></p>

---
#### Feedback Bot on 11/22/2020, 10:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
An Insider Preview Windows build with the fix is now available. Build 20270 is now in the Dev Channel: https://blogs.windows.com/windows-insider/2020/12/03/announcing-windows-10-insider-preview-build-20270/. If you are affected by this issue and want to test against the fix that will come via Windows Update, you can use this build. This is an insider build with other changes included, of course, so it is not entirely representative of the version that will be serviced, but it can be used to test for specific cases where the bug used to reproduce.

We are still on schedule for servicing Windows build 19041 (the current release version) at the end of January 2021.
