### ISSUE TITLE
Wrong working directory for PyLint and MyPy

### ISSUE THREAD

**Issue by x-santiaga-x** [microsoft/PTVS#6368]
Targets PythonRunPyLintCommand and PythonRunMypyCommand use WorkingDirectory set to $(MSBuildProjectDirectory) that is wrong if ProjectHome property set to something other than '.'.

That results in errors like: 
```
************* Module access.py
access.py(1,0): warning F0001: No module named access.py [F:fatal]
```

Correct value for WorkingDirectory is $(QualifiedProjectHome).

**Comment by AdamYoblick** [comment]
Thank you for the details, I'm able to repro this problem when creating a new python application from existing code, which does set the `ProjectHome` to something other than `.`. 

I will modify the targets file as you suggest and make sure it works 😄

**Comment by AdamYoblick** [comment]
Yep, seems to work for me no matter what `ProjectHome` is set to with your change. I'll get a PR up.
