### ISSUE TITLE
Additional filtering needed for IInteractiveWindowCommands on import...

### ISSUE THREAD

**Issue by KevinH-MS** [Microsoft/PTVS#637]
As of https://github.com/dotnet/roslyn/pull/3982, the "core" commands exported by Microsoft.VisualStudio.InteractiveWindow will be marked with ```[ContentType("code")]```.  Consumers should filter commands on import by checking for a ContentType that matches (or is inherited by) their own content type.  This will prevent conflicts such as the one arising from C# Interactive defining it's own ```#load``` command (conflicted with ```$load```).

**Comment by KevinH-MS** [comment]
Update - with commit 5e9eba1085f7b1b3fc3a969561754e5c156430ef, the "core" commands are marked with ```[ContentType(PredefinedInteractiveCommandsContentTypes.InteractiveCommandContentTypeName)]``` instead.

**Comment by zooba** [comment]
Closed as part of another fix.
