### ISSUE TITLE
how to load jupyter notebook in VS 2019

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6381]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/how-to-load-jupyter-notebook-in-VS-2019/1325352)._

---
[severity:I'm unable to use this version]
How can I load a jupyter notebook into visual studio 2019?

Ambient defined is Conda, with python 3.6.

Tank you

---
#### Feedback Bot on 1/31/2021, 06:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by bschnurr** [comment]
Currently notebook ipynb files are not supported. However there is a guide to export them to .py
https://devblogs.microsoft.com/visualstudio/a-lap-around-python-in-visual-studio-2017/#working-with-jupyter-notebooks
