### ISSUE TITLE
Issue tracker points to Codeplex rather than Github

### ISSUE THREAD

**Issue by timsneath** [Microsoft/PTVS#639]
Hyperlink on "An unexpected error occurred" points to https://pytools.codeplex.com/workitem/list/basic rather than https://github.com/Microsoft/PTVS/issues/new. 

![Uploading error.png…]()

**Comment by zooba** [comment]
Thanks. I've updated the link now - should be coming here.

**Comment by timsneath** [comment]
Good gracious - that was fast :+1:

**Comment by zooba** [comment]
I'm trying to close everything and go home, but someone keeps reporting bugs :)
