### ISSUE TITLE
The VS is crash after clicking the Debug tab.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6404]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/109448818-de11a400-7a81-11eb-9424-e8cc4d32e2c3.png)

**Steps to Reproduce**
1. Create a new project 
2. Click the "Debug" tab

**Expected behavior**
The debug drop-down list is displayed correctly. 

**Actual result**
The VS is crash and restart automacticlly.
![error](https://user-images.githubusercontent.com/59192491/109449586-ce935a80-7a83-11eb-8cc9-3b9e78407abb.gif)

**Error events log**
[Error.zip](https://github.com/microsoft/PTVS/files/6059031/Error.zip)

**Comment by int19h** [comment]
Are there any more specifics wrt repro steps? E.g. having certain Python versions installed, or not installed? I can't repro it so far.

**Comment by linette-zyy** [comment]
@int19h 
Without any other steps to repro, only create a project and click the "Debug" tab.
Here is the Python version I have installed.
![image](https://user-images.githubusercontent.com/59192491/109758010-e4408580-7c25-11eb-8ebd-21489e634412.png)

On today's build, this issue is not repro.
![image](https://user-images.githubusercontent.com/59192491/109758228-371a3d00-7c26-11eb-819d-65578ba6fb9f.png)

**Comment by int19h** [comment]
Since it's the same version of PTVS, but different version of VS, it's almost certainly a VS issue that they have fixed since then. Please re-open if this comes up again.
