### ISSUE TITLE
Autocomplete not working in python file, works in interactive shell

### ISSUE THREAD

**Issue by berkdemir** [microsoft/PTVS#6414]
My question is similar to this one, however, I can't find if there is a solution or if this is a "feature".
https://github.com/microsoft/PTVS/issues/3083

Autocompletes work for objects in interactive shell, but not in python files. Is there a workaround for this? I am using pylance.

Interactive shell:
![image](https://user-images.githubusercontent.com/40423004/109941941-b8380980-7ce4-11eb-8eb8-39ad777eff02.png)
Python file:
![image](https://user-images.githubusercontent.com/40423004/109941963-bf5f1780-7ce4-11eb-97ed-f6b0fd03bd88.png)

**Comment by int19h** [comment]
Are you using Visual Studio Code? Note that this is a repo for Python support in Visual Studio proper, which is a separate product.
