### ISSUE TITLE
python highlight

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6419]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/863743/python高亮.html)._

---
Add a richer highlight (e.g. variables, etc.) to the python

---
#### Feedback Bot on 12/19/2019, 11:12 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### Feedback Bot on 2/5/2020, 02:31 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
