### ISSUE TITLE
'utf-8' codec can't decode byte 0xc4 in position 794: invalid continuation byte

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6420]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/utf-8-codec-cant-decode-byte-0xc4-in-/1338802)._

---
[severity:Other]
Im making a Flask project. Everything was going very well and suddenly when i start the Web server to check my project, it loads my home page but not another html page that it hadnt no issue at all. And im getting this message : "'utf-8' codec can't decode byte 0xc4 in position 794: invalid continuation byte". I did not change anything before the problem appears so i cant get what is going wrong
I saw some reviews in stackoverflow, i closed and start VS again but nothing seems to fix the problem.
I would appreciate the most for any help
Thanks In Advance
[VS screenshot.png] (https://aka.ms/dc/file?name=B64a022115959435a839102b40a336c72637489279585297848_VS_screenshot.png&tid=64a022115959435a839102b40a336c72637489279585297848)

---
#### Feedback Bot on 2/14/2021, 04:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### ΝΙΚΟΛΑΣ ΣΚΟΡΔΕΛΗΣ solved on 2/14/2021, 00:24 PM, 0 votes: 

<p>The problem was that on my html page i had a comment in Greek.  It was  exactly like this:</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, this sounds like it's a problem with Flask.
