### ISSUE TITLE
python项目中无法使用现有的图片等资源文件

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6421]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/827706/python项目中无法使用现有的图片等资源文件.html)._

---
<p><a href="https://developercommunity.visualstudio.com/storage/attachments/105886-%e6%8d%95%e8%8e%b7.png"> Image:105886-捕获.png</a></p><p><a href="https://aka.ms/dc/file?name=B2f2caf1ba6254f148b9a501486022a5e637494365582979486_%e6%8d%95%e8%8e%b72.png&amp;tid=2f2caf1ba6254f148b9a501486022a5e637494365582979486"> Image:file?name=B2f2caf1ba6254f148b9a501486022a5e637494365582979486_捕获2.png&amp;tid=2f2caf1ba6254f148b9a501486022a5e637494365582979486</a></p><p>VS 2019 commuity 版本python工程不能使用图片等文件</p>

---
#### 2914701808 on 11/20/2019, 05:56 AM: 

<p>路径在pycharm中.\\images\\ship.bmp这么写没问题，但在vs2019中就会出问题</p>

#### Feedback Bot on 11/20/2019, 07:41 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### Feedback Bot on 2/5/2020, 02:32 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
