### ISSUE TITLE
Documentation strings for python in VS 2017

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6424]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/705613/documentation-strings-for-pyhton-in-vs-2017.html)._

---
<p>Please, add the functionality of this Visual Studio Code snippet to VS 2017</p><p>https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring</p>

---
#### Feedback Bot on 8/22/2019, 11:48 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it
#### Jane Wu [MSFT] on 8/23/2019, 00:07 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

#### Feedback Bot on 2/5/2020, 02:33 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
