### ISSUE TITLE
Support for publishing Python Apps to Azure Web Apps on Linux

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6425]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/627600/support-for-publishing-python-apps-to-azure-web-ap.html)._

---
<p>Ability to publish Python apps in Visual Studio to Azure Web Apps on Linux</p>

---
#### Jane Wu [MSFT] on 7/1/2019, 04:14 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

#### Reshmi Mangalore [MSFT] on 7/1/2019, 04:55 PM: 

<p>We have determined that your valuable suggestion has a broad community impact and will improve the product experience. We have added the feature to our roadmap and will keep you updated as we make progress. We highly appreciate your contribution in making our product better.</p>

#### Graham Wheeler [MSFT] on 8/21/2019, 01:15 PM: 

<p>We have determined that your valuable suggestion has a broad community impact and will improve the product experience. We have added the feature to our roadmap and will keep you updated as we make progress. We highly appreciate your contribution in making our product better.</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
