### ISSUE TITLE
Define python environment per project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6426]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/619222/define-python-environment-per-project.html)._

---
Our python environment is typically setup via scripts included in our source repository.  This environment is either:

- Completely downloaded as part of the source (i.e. from artifactory, git LFS, perforce, etc.)
- Is a virtual environment based on a minimal python downloaded as part of the source with additional modules installed as part of workspace setup.

However, in order to use this python environment in Visual Studio each user must create their own Python Environment within the GUI and associate it with all python projects that use it.

We would really love a way to define (completely) the python environment for a .pyproj project from within the python project itself (or some included file).  Perhaps this already exists, but I could not find a way to do it.

Ideally, the user flow for this would be:

- Download source tree from source server(s)
- (optional) run setup script to finalize python virtual environment into known location relative to the source download
- Open solution and have all python projects correctly use the downloaded python environment.

If this is possible now, please let me know how!

Thanks

---
#### Steve Dower [MSFT] on 6/24/2019, 11:37 AM: 

<p>It is doable, but it's kind of secret in that the UI doesn't really enable it.</p><p>The syntax in the .pyproj file for virtual environments will work for any environment. See the <a target='_blank' href="https://github.com/microsoft/PTVS/blob/167057bc300eca0c5f86579fc935476bcc333a5c/Python/Tests/TestData/Environments/Unavailable.pyproj#L38-L46" target="_blank">examples in our test suite</a> (note that these are deliberately broken for the tests, but should give you an idea anyway). You can specify any relative or absolute directory in the "Include" attribute, and the rest of the metadata will specify all the other properties.</p><p>If you want to specify this in a separate file (typically .props or .settings, and then &lt;Import Project="..." /&gt;), I believe it will work, but I'm not totally sure whether we consistently used the fully evaluated project. Including it directly in each project should be fine though.</p>

#### Jane Wu [MSFT] on 6/25/2019, 01:31 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

#### Feedback Bot on 2/5/2020, 02:30 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing this functionality at this time.
