### ISSUE TITLE
Python Profiling at line number level

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6427]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/615436/python-profiling-at-line-number-level.html)._

---
<p>Please improve the python performance profiling so that it gives line number break-down, not just function level break-down.</p> <p>Thank you.</p>

---
#### Jane Wu [MSFT] on 6/21/2019, 05:13 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

#### Graham Wheeler [MSFT] on 8/21/2019, 02:20 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
