### ISSUE TITLE
hope for surportting python3 f-string colour.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6429]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/555044/hope-for-surportting-python3-f-string-colour.html)._

---
<p>Same as the title. VS Code first while VS 2019 second as the pictures show.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/71503-tim%e6%88%aa%e5%9b%be20190502221929.jpg"> Image:71503-tim截图20190502221929.jpg</a></p><p><a href="https://aka.ms/dc/image?name=B3fe1d9a1b8db40a18e88dd98de93e8aa637494049523484268_tim%e6%88%aa%e5%9b%be20190502222024.jpg&amp;tid=3fe1d9a1b8db40a18e88dd98de93e8aa637494049523484268"> Image:image?name=B3fe1d9a1b8db40a18e88dd98de93e8aa637494049523484268_tim截图20190502222024.jpg&amp;tid=3fe1d9a1b8db40a18e88dd98de93e8aa637494049523484268</a></p>

---
#### Jane Wu [MSFT] on 5/5/2019, 03:19 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Graham Wheeler [MSFT] on 8/21/2019, 02:23 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing this functionality at this time.
