### ISSUE TITLE
Change Python Tab Indenting to Smart by Default

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6430]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/549728/change-python-tab-indenting-to-smart-by-default.html)._

---
<p>In C#, VB.net, the tab indent default setting is Smart. But in Python, the tab default setting is Block. </p><p>The pointer always goes to the first column when pressing Enter.</p> <p>That makes me always fix indenting myself. A lot of time wasted.</p> <p>I think the tab indenting should be made smart by default. Just like what we did in C# and VB.net.</p> <p></p><p>Actually, in other IDE, (I know only Spyder), the tab indenting is smart, too. So, I think &quot;Smart&quot; should be the default value. </p>

---
#### Eric Zhou on 4/28/2019, 02:07 AM: 

<p>i mean vs2019.</p>

#### Jane Wu [MSFT] on 4/28/2019, 11:30 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Graham Wheeler [MSFT] on 8/21/2019, 02:23 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing this functionality at this time.
