### ISSUE TITLE
rename Python in visual studio and automatic alignment setup

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6431]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/547955/rename-python-in-visual-studio-and-automatic-align.html)._

---
<p>Hi, when we rename a class (or variable/function) in visual studio (VS) for C SHARP, it is pretty easy to rename all by right click to select rename. However, this important function is not existed in VS for Python. Moreover, the VS for Python does not able to automatic alignment setup the codes through comment and uncomment. Would you please kindly consider to add this two functions in VS for Python? Many thanks!</p>

---
#### Jane Wu [MSFT] on 4/26/2019, 00:44 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Graham Wheeler [MSFT] on 8/21/2019, 02:24 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing this functionality at this time.
