### ISSUE TITLE
Stop Python debugger if breakpoint condition failed to execute

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6432]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/533690/stop-python-debugger-if-breakpoint-condition-faile.html)._

---
<p>Currently Python breakpoints that fail to execute (due to incorrect syntax, undefined variables, etc.) cause debugger to print error message to console and continue execution of script. For long scripts it may take long time until developer realizes that something went wrong (console screen is in background by default + there may be too much stdout from script itself which will cause breakpoint error message to be flushed from console screen buffer).</p><p>I suggest to make Python breakpoings to behave the same way as C++ breakpoints in this regard: if C++ breakpoint fails to execute, debugger displays a helpful message box saying &quot;Condition for breakpoint failed to execute... click OK to stop at this breakpoint&quot; and stops at the breakpoint.</p>

---
#### Jane Wu [MSFT] on 4/16/2019, 01:51 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Graham Wheeler [MSFT] on 8/21/2019, 02:24 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
