### ISSUE TITLE
keyboard interrupt for python interpreter

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6434]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/520545/keyboard-interrupt-for-python-interpreter.html)._

---
<p>Most IDEs have a keyboard interrup 'CTRL C' to stop a long running function in the interpreter. VS is the only tool that does not have this. The result is that you have to dump the entire kernel and start over. This makes VS unusable for large REPL projects. </p>

---
#### Jane Wu [MSFT] on 4/9/2019, 02:12 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### William Harding on 4/30/2019, 10:45 AM: 

<p>Man it would be awesome if VS could do this. Then it would clearly be my #1 pick IDE. Currently I'm not using it as I need this feature. Currently using Spyder as it has keyboard interrupt and only using VS for GIT repo management. </p>

#### Feedback Bot on 2/5/2020, 02:30 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

#### pierre.carbonnelle on 5/15/2020, 00:41 AM: 

<p>I've found a nice workaround: instead of ctrl-C, you can pause the debugger by clicking the Pause button in the floating debugger toolbar, just next to the start button !  How didn't I think of it before ??</p>

**Comment by greazer** [comment]
Thanks for the feedback. Looks like you found a good workaround! :)

**Comment by jeanravenclaw** [comment]
The workaround doesn't work for python users. VS Code doesn't have a debugger for python, and therefore I couldn't use the pause button in the floating debugger toolbar.

**Comment by int19h** [comment]
The Python extension for VSCode includes debugging support, and offers the same experience for this particular scenario.
