### ISSUE TITLE
add a code structure view for python, js, etc.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6435]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/516858/add-a-code-structure-view-for-python-js-etc.html)._

---
Code structure(e.g. classes, members, function, methods) can showed in navigation bar, but it'll be more convenient if it could show as a tree view at the left or right of window. if we code c++, solution explorer would show such tree view for each code file. I hope python and js will be supported in the future.
Or like this: https://marketplace.visualstudio.com/items?itemName=oleg-shilo.codemap

---
#### Jane Wu [MSFT] on 4/3/2019, 08:44 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Graham Wheeler [MSFT] on 8/21/2019, 02:19 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

#### Tal Herscovitz [MSFT] on 11/18/2019, 01:06 AM: 

I really want this feature as well. Thanks!

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
