### ISSUE TITLE
Add access to Python documentation from within Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6436]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/515291/add-access-to-python-documentation-from-within-vis.html)._

---
<p>When developing Python code using Visual Studio, I often have to access the standard Python documentation.  I currently have to do this using another application since there is no help menu item within Visual Studio to open this documentation.  It would be great if this material could be opened directly from within Visual Studio.</p>

---
#### Jane Wu [MSFT] on 4/3/2019, 07:03 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Graham Wheeler [MSFT] on 8/21/2019, 02:32 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

#### Brian Gladman on 8/21/2019, 03:31 PM: 

<p>Thank you for giving my suggestion further consideration.</p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
