### ISSUE TITLE
VS 2015 Python interpreter should work fast and a complete offline installer should be there so that no internet connection is required.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6438]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/351110/vs-2015-python-interpreter-should-work-fast-and-a.html)._

---
Migrated from <a href="http://visualstudio.uservoice.com/forums/121579/suggestions/15103701">Visual Studio IDE UserVoice forum</a> <br><br> Python Interpreter seems very slow. It should be faster. 

Again, Visual studio 2015 installation takes a long time than VS 2010.
It also required internet connection while installing  though it is 5.92 GB itself. So, a complete offline installer should be there like VS 2010, VS 2008, VS 2005 etc

---
#### Fredy Canaveral on 2/13/2020, 00:54 PM: 

<p>I think this apps or windows be good for us  </p>

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing VS 2015 functionality.
