### ISSUE TITLE
yapf support

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6439]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/351741/yapf-support.html)._

---
Migrated from <a href="http://visualstudio.uservoice.com/forums/121579/suggestions/35234755">Visual Studio IDE UserVoice forum</a> <br><br> I would like to see Visual Studio support yapf autoformatting the way Visual Studio Code does.

---
#### Fiona Niu[MSFT] on 10/11/2018, 00:25 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about two weeks on our next steps. </p>
#### Graham Wheeler [MSFT] on 8/21/2019, 02:56 PM: 

<p>Your suggestion has been queued up for prioritization.  Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback. However, we have no plans on adding this support at this time.
