### ISSUE TITLE
Python virtual environment in "Open Folder"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6441]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/376409/python-virtual-environment-in-open-folder.html)._

---
<p>Python virtual environment works well with Python project (pyproj) but doesn't work with opening folder via &quot;Open Folder&quot;.</p><p>It could be nice to reuse json file the one VSCode uses (https://code.visualstudio.com/docs/python/environments)</p>

---
#### Fiona Niu[MSFT] on 11/7/2018, 00:48 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>
#### Feedback Bot on 2/5/2020, 02:23 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

**Comment by greazer** [comment]
Thanks for the feedback. We're not able to reproduce the problem you're seeing. Please add steps to reproduce if you can.
