### ISSUE TITLE
Cannot $attach to interactive

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#645]
Hi

I'm not sure if this feature was pulled out of recent versions, but I can no longer attach a debug window to my interactive session. When I type $attach at the interactive prompt, I get the following error message: 

The Python REPL process has exited
Failed to attach: Unable to start program 'd4c066b1-83e2-49b0-a80b-4c9b212afb8b'.

Catastrophic failure

Is this a bug, or is the feature no longer supported?

Thank you.

**Comment by int19h** [comment]
This is definitely a bug, but I can't reproduce it. Can you tell a bit more about the environment - VS version, Python version etc?

**Comment by sriksrid** [comment]
Hi

The version of VS is Community Edition 2013 with Update 4. I'm using Python 2.7.9 (32 bit). The OS is Windows 8 Pro, 64 bit.
I am still able to run the regular debugger (for the project or file) just fine. 

Please let me know what other information you might need to debug this.

Thank you

**Comment by int19h** [comment]
Can you please try to repro this again, and then go to Tools -> Python Tools -> Diagnostic Info, and attach the output there?

**Comment by sriksrid** [comment]
Hi

I have uploaded the diagnostic info here: https://drive.google.com/file/d/0B83Ffz1wmGNjMzZhZXB5QllfbUE/view?usp=sharing

Please let me know if there is anything else you need.

Thank you

**Comment by int19h** [comment]
From the log, there seems to be something weird about your install - it looks like you have bits and pieces of PTVS 2.0 floating around alongside 2.2? Can you take a look at the global list of installed applications in Control Panel, and see if 2.0 is still there somehow? If so, removing it and then reinstalling 2.2 might help.

**Comment by sriksrid** [comment]
Hi
I looked in Control Panel, and found nothing like PTVS 2.0 (Only PTVS 2.2). 

Please let me know if you'd like me to reinstall 2.2 (or if there are any other steps you'd like me to take). I searched in the AppData folder, but found just one PythonTools folder in Local.

Thank you

**Comment by int19h** [comment]
Can you also take a look at `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio`? If you see 2.0 there, remove it and see if that helps any.

**Comment by sriksrid** [comment]
Hi

I saw a 2.1 in there which I deleted and restarted VS (but no 2.0). The problem still persists. Also, I notice that I have Python 2.7.9, but Anaconda updated iPython to 3.2.1 - would this be an issue?

**Comment by zooba** [comment]
Shouldn't be, though $attach-ing to an IPython interactive may not work exactly the way you expect.

When you type $attach, is it the very first thing you type? What if you do an "import sys" or something first?

**Comment by sriksrid** [comment]
Hi

It is the very first thing I type. I occasionally get a slightly different errors, like 
"Invalid pointer" instead of "Catastrophic failure".

Thank you

**Comment by zooba** [comment]
What if you type "import sys" first, and then type "$attach"?

**Comment by sriksrid** [comment]
Hi
I see the same error message. I haven't yet reinstalled PTVS - I just removed the 2.1 directory. Should I try reinstalling PTVS?
Thanks

**Comment by UbermanPrime** [comment]
Hi, I am having a similar issue.  
I am installed Python 3.2 to VS2015, but when i try to fire up the interactive window, I am getting a <disconnected> or "The Python REPL process has exited".  

Were you able to resolve this?

**Comment by willyd** [comment]
Same here on Windows 10 64-bit with VS 2015 Pro Update 2. As a work around on can use:
```
import os
os.getpid()
```
to the the python.exe process id and then attach using Debug > Attach to Process...

**Comment by sriksrid** [comment]
Thanks willyd, your solution works.

I don't remember how the attach to debug worked before, but I now see the result of the commands I type in the debug window being displayed in the interactive window.

**Comment by zooba** [comment]
We have longer-term plans to improve the REPL/debugger relationship, that should eventually replace the need to fix this issue.
