### ISSUE TITLE
PSService Exception when loading pyproj and csproj in same solution.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6450]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PSService-Exception-when-loading-pyproj-/1369607)._

---
[severity:It bothers me. A fix would be nice]
When trying to add a python project to an existing solution on csharp projects the following error occurs:
PSService!9556 HR: E_Exception
Screenshot is it happening in a blank solution created by adding a python application, a csharp console application then trying to reload the python project.

---
#### Feedback Bot on 3/14/2021, 11:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Thanks for the feedback. However, we do not have plans on addressing this issue.
