### ISSUE TITLE
Disable Highlighting of Words Upon Selection

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6453]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Disable-Highlighting-of-Words-Upon-Selec/1359911)._

---
[severity:It's more difficult to complete my work]
Hello, I'm using VS 2019 Community, my environment is Python 3.7, and I'm editing a .sh script in my solution. When my cursor is on a word, all instances of that word are highlighted. It is extremely annoying! How can I disable this highlighting? Note that when I'm editing a .py script in the same solution, words are not automatically highlighted upon selection, thankfully. (I had previously disabled IntelliSense for Python, so maybe that explains the difference in behavior?)

---
#### Feedback Bot on 3/7/2021, 10:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AJVincelli** [comment]
It looks like my Feedback issue was automatically added to this GitHub repository. I'm not sure it belongs in PTVS, considering the behavior is with .sh scripts in my VS solution??

**Comment by AJVincelli** [comment]
Microsoft, please fix this issue! If you need any more info, just let me know.

**Comment by AJVincelli** [comment]
In case this helps illustrate my issue, here's a screenshot of the ridiculous and annoying word highlighting whenever my cursor is on a word in a .sh script within a Python-environment solution:
![HIghlight](https://user-images.githubusercontent.com/46507729/126736332-42d917d9-590b-425b-be12-3941ab93a9da.png)
