### ISSUE TITLE
Debugger is not attached after several hangs in internal python module

### ISSUE THREAD

**Issue by mikolajpiecuch** [microsoft/PTVS#6463]
**Describe the bug**
While I was testing [Issue-6456](https://github.com/microsoft/PTVS/issues/6456) I encountered a problem with debugging but then helped me reinstalling of VS. @int19h asked me to open new issue when problem will be reproduced. One week it was working and now I cannot again debug any python code in VS19. 

I'm using .pyd file created in c++ and trying to test it with pytest. Unfortunately, after some errors in my c++ package (hang processes etc.) I cannot debug python code independently of native code debugging settings. Debugger is not attached after select debug options on test. Looks like VS pass wrong arguments to testlauncher.py - always the same. It is reproducing for all python projects in VS19.

I created new python solution with one file and test. Output from Test's console when I clicked debug on test in Test Explorer:

`C:\Python37\python.exe "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\testlauncher.py" D:\DebuggingTest\DebuggingTest\DebuggingTest\ pytest "" 0 "" "" dummyfilename .\test_example.py::TestExample::test_debugging --junitxml=D:\DebuggingTest\DebuggingTest\TestResults\junitresults_09150ba4-3c0e-4bd1-a198-481922678cd2.xml --rootdir=D:\DebuggingTest\DebuggingTest\DebuggingTest -o junit_logging=all -o junit_family=xunit1`

This `pytest "" 0 "" "" dummyfilename` doesn't change even after enabling/disabling native code debugging.

**Expected behavior**
Debugger is working

**Sample Code**
- python solution created in VS19
- inside one python file: test_example.py
- content of that file:
```
class TestExample():
    def test_debugging(self):
        pass
```

**Configuration information**
VS Version: 16.9.2
PTVS version: 

> Python   16.9.21026.1

> Python - Conda support    16.9.21026.1

> Python - Django support   16.9.21026.1

> Python - IronPython support   16.9.21026.1

> Python` - Profiling support   16.9.21026.1

Python version:
Python 3.7.9

**Comment by mikolajpiecuch** [comment]
I downloaded source code and now I'm trying to debug problem in PTVS. It is difficult because symbols does not load for all project (especially for TestAdapter.Executor where is logic related to running tests). 

I discovered where is problem. 'app' argument, passed to this method in ExecutorService is always null:
`GetDebugSettings(VisualStudioProxy app, IRunContext runContext, PythonProjectSettings projectSettings, out PythonDebugMode debugMode, out string debugSecret, out int debugPort)`

Then in the same method:
```
if (runContext.IsBeingDebugged && app != null) {
    debugMode = projectSettings.EnableNativeCodeDebugging ? PythonDebugMode.PythonAndNative : PythonDebugMode.PythonOnly;
}
```

And I know that 'app' is getting from here but it returns nulll:
`_app = VisualStudioProxy.FromEnvironmentVariable(PythonConstants.PythonToolsProcessIdEnvironmentVariable);`

Do you have any clues how to resolve this problem?

**Comment by mikolajpiecuch** [comment]
Do you have any update on this issue?

**Comment by mikolajpiecuch** [comment]
@int19h could you look and give some tips?

**Comment by int19h** [comment]
My apologies for a very late followup! I can't repro it locally on VS 2019 v16.11 + Python 3.7; if I create a simple project as described, set a breakpoint on `def test_debugging`, and do Debug Test, it gets hit. In case this was an issue with some earlier version of VS and/or PTVS, I would suggest trying the most recent first.

That aside, it looks like the environment variable isn't being inherited by the test runner process for some reason. When you change `SetEnvironmentVariable` to use global or user scope, it's actually persisted when set, so inheritance isn't needed for the other process to see it; but the default is process-scope. It should still be inherited by child processes, though. 

What happens if you try to debug a simple app that just prints out the variable? e.g.:
```py
import os
print(os.environ["_PTVS_PID"])
```

**Comment by mikolajpiecuch** [comment]
Hi, thank you for your answer. I am using the most recent VS. I can check env variable from python side but I checked it while debugging PTVS and it was null. Like I wrote earlier, it happens where projects that are being debugged hang. Only reinstall VS can fix the problem for a while. Is child process always created in the same way? Maybe here is some place to improvement. Could you point me where I should look for process creation? Then I could check env variable in main process and in child process after creation.

**Comment by int19h** [comment]
I've ran into this same fundamental issue while investigating https://github.com/microsoft/PTVS/issues/6796 - that issue has a detailed write-up of the problem, so I'm going to use it to track, and resolve this one as a dupe.
