### ISSUE TITLE
Find in Files looks for files in unrelated and blocked directories

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6464]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Find-in-Files-looks-for-files-in-unrelat/1383440)._

---
Find In Files (Entire Solution) looks somehow at the outside files not mentioned anywhere in the solution. No Misc Files folder in the solution.

In the screenshot, added !test\data\* directory ignore rule (those rules are not documented yet, by the way) doesn't have effect, files in test/data are still included in the search.

---
#### Feedback Bot on 3/28/2021, 11:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Oleg Tkachenko [MSFT] on 3/29/2021, 11:07 PM: 

<p>Thanks for reporting, <a target='_blank' href="https://developercommunity.visualstudio.com/user/087923ab-b170-66c1-9d0d-8d97cbb45a4c/profile">Alex Grigoriev</a>!<br>
Find in Files gets list of files to search in from project system, so it’s very likely PTVS issue unless it also reproduces in C# or C++ projects.<br>
Routing to the Python team.</p>

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/19672699/113183860-5d250400-9209-11eb-85b4-5f01cf514588.png)

**Comment by rchiodo** [comment]
I cannot repro this with a C# project

**Comment by ijoosong** [comment]
I've found that adding * in front of test works, for instance `*test/data*` while not having it there `test/data*` doesn't work.  I'll be closing this.  If you have any other issues, please feel free to let us know!
