### ISSUE TITLE
ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)  : Python Package installation

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6465]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ConnectionResetError10054-An-existing/1386200)._

---
[severity:I'm unable to use this version]
When i try to install packages in python environment in VS2019 i am getting the following error

----- Installing 'matplotlib' -----
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/matplotlib/
ERROR: Could not find a version that satisfies the requirement matplotlib (from versions: none)
ERROR: No matching distribution found for matplotlib
----- Failed to install 'matplotlib' -----

---
#### Feedback Bot on 3/30/2021, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Thanks for the feedback, however, this looks like a problem on the package manager end. Can you install matplotlib with pip? I'm going to close this with the expectation that it has been resolved externally. Please reopen if this is not the case.
