### ISSUE TITLE
 IronPython WPF Application project is missing on build 15.9.35 and 16.4.21.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6466]
**Describe the bug**
installed workload: 
![image](https://user-images.githubusercontent.com/39871640/113404395-abd5c800-93da-11eb-8be7-6617b672b6f5.png)

**repro step:**
Launch VS -> File -> New -> Project -> IronPython WPF Application

Can't find and create WPF application in the following two builds:
16.4.21: [rel.d16.4-31201.114](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D4614448%26view%3Dresults&data=04%7C01%7Cv-wazho%40microsoft.com%7C463dfa3568404ec2651c08d8f5871772%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637529307890976352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vTVmZ6HSCpJwQ2s1FAnySNct9qJYqcpwHo2D2vzysrQ%3D&reserved=0)
15.9.35: [rel.d15.9-28307.1498](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D4615157%26view%3Dresults&data=04%7C01%7Cv-wazho%40microsoft.com%7Cf40d0a23af444d8b278108d8f58728ba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637529308173678155%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UMKrXm7p%2BhE%2BojVx7Ue%2BYcOeq%2Fq6WNa2S5IbQGpQHfM%3D&reserved=0)

**Comment by judej** [comment]
Thanks for the report. Will investigate, but this is lower priority since IronPython is no longer supported

**Comment by zhouwangyang** [comment]
the same issue exits on build **16.9.4 [31202.62.d16.9]**

**Comment by JetteChristensen** [comment]
I experience the same problem too. Got told that ironpython was outphased.  Like to know if this is really true or is it a bug. And when it will be fixed.

**Comment by rchiodo** [comment]
Iron Python is no longer being supported.

**Comment by InquisitorOkabe** [comment]
I support. I can not understand how to put these templates now.

**Comment by Damco92** [comment]
Does someone find any solution to this?

**Comment by ijoosong** [comment]
> Did someone find any solution to this?
Since iron python is no longer supported, going to older versions (V16 and older) will fix it for you but if you want to use newer editions there's no solution to this.  Closing as we can't do anything else on it!
