### ISSUE TITLE
ConfigureCloudService.ps1 pip_downloader.py

### ISSUE THREAD

**Issue by mwonger** [Microsoft/PTVS#647]
Seeing customers receive the following error when the powershell cmdlet ConfigureCloudservice.ps1 is run from the worker role instance - 

" to type "System.Byte". Error: "Input string was not in a correct format."""
At line:1 char:36
+ [System.IO.File]::WriteAllBytes("$(Get-Location)\bin\pip_downloader.py", $req.Co ...
+                                    ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

In ConfigureCloudService.ps1 line 200
           $req = Invoke-WebRequest "https://go.microsoft.com/fwlink/?LinkID=393490" -UseBasicParsing
            [System.IO.File]::WriteAllBytes("$(Get-Location)\bin\pip_downloader.py", $req.Content)
            $pip_downloader = gi "$(Get-Location)\bin\pip_downloader.py" -EA Stop
        }

req.Content is of type string 
https://msdn.microsoft.com/en-us/library/microsoft.powershell.commands.htmlwebresponseobject.content(v=vs.85).aspx

proposal is to call WriteAllText instead of WriteAllBytes instead or convert $req.Content to a byte array?

**Comment by int19h** [comment]
The URL should now serve the file as binary data rather than text, fixing this - can you please try it again to check?

**Comment by mwonger** [comment]
Excellent, thanks for the fast help on this!  It works!  again much appreciated,mike
