### ISSUE TITLE
Failed to executed tests.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6476]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/113811099-29fcea80-979e-11eb-8693-a82eaf7cca51.png)

**Steps to Reproduce**
1. Create a new python project.
2. Right-click project, select Add > New Item …, then select "Python Unit Test" followed by "Add"
3. Set Test framework to "unittest"
4. Click "Run all test".
5. Observe the test results

**Expected behavior**
The test is executed successfully.

**Actual result**
Failed to executed tests. 
![image](https://user-images.githubusercontent.com/59192491/113811374-b4454e80-979e-11eb-9a97-014f1564e085.png)

**Comment by linette-zyy** [comment]
Also failed to debug the test.
![image](https://user-images.githubusercontent.com/59192491/113813870-46e7ec80-97a3-11eb-98d8-e18272ad5970.png)

**Comment by linette-zyy** [comment]
This issue is still reproduced on today's build.
![image](https://user-images.githubusercontent.com/59192491/114820085-0ca8cb80-9df1-11eb-9253-54575ad72b16.png)

**Comment by bschnurr** [comment]
can't repo. closing
Version 17.0.0 Preview 5.0 [31726.67.main]
Version 17.0.0 Preview 5.0 [31726.67.main]
