### ISSUE TITLE
Python 3.9 does not seem run, 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6479]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-39-does-not-seem-run/1390126)._

---
I am trying to run Python 3.9 but does seem to work on visual studio, I change the  to env(Python3.9(64-bit))
and try that , keeping saying  there are errors in file very time I try to start it, proceed with the project, then nother message pop up debuging does not support Python 2.5 or earlier, but I am using Python 3.9, so want is going on here, suggest to to use a virual envirionment  so I did that, does not seem run my proctject.

---
#### Feedback Bot on 4/5/2021, 08:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Sorry for the trouble. Please reactivate this bug with the errors your seeing. We need those to be able to help.
