### ISSUE TITLE
Failed to initialize analyzer

### ISSUE THREAD

**Issue by NUCO-studio** [microsoft/PTVS#6480]
**Describe the bug**
The error message is popped up. (This is once before.)

**Steps to Reproduce**
1. Wake up from sleep mode.
2. Enter PIN and Unlock the PC.
3. Popped up the dialog box.

**Expected behavior**
Nothing happen

**Additional context and screenshots**

<details>
<summary>Error dialog message</summary>

[Window Title]
devenv.exe

[Main Instruction]
予期しないエラーが発生しました

[Content]
Ctrl+C を押してこのダイアログのコンテンツをコピーして、問題の追跡ツールにこのエラーを報告してください。

[^] 詳細の非表示(D)  [閉じる(C)]

[Expanded Information]
```
Build: 16.9.21026.1

System.InvalidOperationException: Failed to initialize analyzer
   場所 Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<InitializeAsync>d__42.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<CreateForProjectAsync>d__33.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Microsoft.PythonTools.Project.PythonProjectNode.<CreateAnalyzerAsync>d__143.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   場所 Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProjectHelper>d__156.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__155.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

</details>

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**

VS Version: 16.9.3
PTVS version: 16.9.21026.1

<details>
<summary>More...</summary>

Microsoft Visual Studio Community 2019
Version 16.9.3
VisualStudio.16.Release/16.9.3+31129.286
Microsoft .NET Framework
Version 4.8.04084

インストールされているバージョン:Community

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.693.2781
詳細については、https://www.asp.net/ をご覧ください

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.693.2781
Azure Functions and Web Jobs Tools

C# ツール   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
IDE で使用する C# コンポーネント。プロジェクトの種類や設定に応じて、異なるバージョンのコンパイラを使用できます。

Common Azure Tools   1.10
Azure Mobile Services および Microsoft Azure Tools で使用する共通サービスを提供します。

Cookiecutter   16.9.21026.1
cookiecutter 形式でテンプレートを検索、インスタンス化、カスタマイズするためのツールを提供します。

Dummy Text Generator   1.2.17
Easily insert dummy text into the editor in Visual Studio. Lorem Ipsum and other vocabularies are supported.

IntelliCode 拡張機能   1.0
IntelliCode Visual Studio 拡張機能の詳細情報

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Visual Studio IDE 内からの Azure DevOps パイプラインの構成を簡略化しています。

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
ターゲット環境で ASP.NET Core アプリケーションを開発、実行、検証します。F5 キーを押してコンテナーで直接アプリケーションをデバッグ実行するか、Ctrl + F5 キーを押してコンテナーをリビルドせずにアプリを編集して更新します。

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Visual Studio での Node.js アプリケーション開発とデバッグのサポートを追加する

NuGet パッケージ マネージャー   5.9.0
Visual Studio 内の NuGet パッケージ マネージャー。NuGet の詳細については、https://docs.nuget.org/ にアクセスしてください

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.21026.1
Python 開発者向けの IntelliSense、プロジェクト、テンプレート、デバッグ、インタラクティブ ウィンドウ、および他のサポートを提供します。

Python - Conda サポート   16.9.21026.1
Python プロジェクトの Conda サポート。

Python - Django サポート   16.9.21026.1
Django Web フレームワークに対してテンプレートと統合を提供します。

Python - IronPython のサポート   16.9.21026.1
IronPython ベースのプロジェクトに対してテンプレートと統合を提供します。

Python - プロファイル サポート   16.9.21026.1
Python プロジェクトのプロファイル サポート。

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic ツール   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
IDE で使用する Visual Basic コンポーネント。プロジェクトの種類や設定に応じて、異なるバージョンのコンパイラを使用できます。

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code デバッグ アダプターのホスト パッケージ   1.0
Visual Studio Code デバッグ アダプターを Visual Studio でホストするための相互運用レイヤー

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio コンテナー ツール拡張機能   1.0
Visual Studio 内のコンテナーを表示、管理、診断します。

</details>

**Comment by greazer** [comment]
We will not be able to fix this problem in 16.x However, Visual Studio v17 should have this resolved.
