### ISSUE TITLE
The associated project "<YourProject>" has changed its configuration. These changes will not be reflected until you reset this interactive window

### ISSUE THREAD

**Issue by oyibor** [microsoft/PTVS#6488]
**Describe the bug**
Hello, since a few weeks I have a problem using the Ipython interactive mode in my Python projects using Visual Studio.
This problem only appears if I have linked a custom file to the active solution.
If I select a piece of code which calls a method or function of the linked file and click „send to interactive“ or „ctrl+enter“ then I get the message "The associated project "prj_test" has changed its configuration. These changes will not be reflected until you reset this interactive window.“
As soon as I continue with other lines of code a new interactive window automatically appears. 

**Steps to Reproduce**
1. create a file named "awesome_linked_file.py" in folder "..\linked_files"
2. the code of "awesome_linked_file.py" is:
def SayHelloLinkedFile():
    print('Hello, I am a linked file')
3. create a Visual Studio Solution "prj_test" with module "prj_test.py"
4. add file "awesome_linked_file.py" as link to the solution
5. the code of "prj_test.py" is:
from awesome_linked_file import SayHelloLinkedFile
SayHelloLinkedFile()

**Expected behavior**
I would expect using the same interactive window executing the code line by line  instead a new interactive window has to be started  as soon as I call a linked file.

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: Microsoft Visual Studio Community 2019 Version 16.9.4
PTVS version: 16.9.21026.1-16.0
Python version: 3.8

**Picture**
![interactive window](https://user-images.githubusercontent.com/51128957/114897874-f2331a00-9e11-11eb-9db2-514c7da2e709.PNG)

**Files**
[prj_test.zip](https://github.com/microsoft/PTVS/files/6319345/prj_test.zip)

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
