### ISSUE TITLE
Debugger does not show proper line of exception

### ISSUE THREAD

**Issue by gnychis** [Microsoft/PTVS#649]
[I watched this video on debugging with PTVS](https://www.youtube.com/watch?v=bO7wpzgy74A&feature=youtu.be&list=PLReL099Y5nRdLgGAdrb_YeTdEnd23s6Ff), which shows perfect functionality of the debugger and its ability to trace the callstack and show an exception on the line it occurs.

However, I am unable to replicate this behavior.  I find that when an Exception is thrown, the debugger stops at the most top-level source file in the method that called it and not at the most nested line of code where it actually occurred.  This makes it very hard (in larger projects) to find the exact line that exception occurred on.  The callstack is also not proper, where I thought I might be able to at least see the true line that the exception occurred on in the callstack.

Here is a video demonstrating the issue.  You'll see that I try to call a non-existant method on an integer, and the debugger shows the exception in the top-level source file (not the most nested line where the Exception actually occurred).  This is both when stepping through (in the first half of the video), and when simply running (second half of the video).

https://youtu.be/hoamS4G05qk

Here is the code used in the video: https://github.com/gnychis/PTVSDebugger

**Comment by int19h** [comment]
I see that you're using IronPython. In project properties, do you have the launcher set to Default or to IronPython (as I recall, if you created a new project, it'll be IronPython)? If the latter, than you're actually running your code under .NET debugger, not the Python debugger, and this will have a lot of quirks, this likely being one of them. You generally want to use the Python debugger for everything, with the only exception being if you need to debug both IronPython and C# code at the same time (stepping through method calls etc), as only the .NET debugger will let you do that.

**Comment by gnychis** [comment]
Hi Pavel,

Thanks for your response!  Ultimately, I will be debugging an IronPython project but I will not need to step through the C# code at the same time.  I only care to step through the Python code.

However, I tried changing "Launch Mode" under my debugger settings to "Standard Python Launcher" but that makes the situation even worse... I don't even see the exception in Visual Studio.  I only see it in a command line.

Worse yet, even I created a project in standard Python and recreate the scenario, I don't even get the exception in Visual Studio.  Video of the scenario:

https://youtu.be/7neteopphFY

I didn't notice any setup/settings that I could be missing in the [PTVS debugging guide](https://github.com/Microsoft/PTVS/wiki/Debugging).

I have tried this on two of my other machines with the most recent PTVS build and all of my machines show the same behavior.  I'm in Visual Studio 2013 CE.

**Comment by andygraham** [comment]
I downloaded your project out of interest as I use IronPython.

 The reason that you don't get the exception with the standard Python launcher seems to be that Menu Debug -> Exceptions -> Python Exceptions -> AttributeError is unchecked. Check UserUnhandled and it breaks with a good stack trace. Like you I don't see a good stack with the .NET Launcher

I'm not sure if there isn't a bug here or if it is by design but it seems that the default for AttributeError is unchecked as pressing the ResetAll button in the Exceptions dialog unchecks AttributeError and a couple of other Python exceptions, like GeneratorExit. It was just bad luck you chose that one for your example

**Comment by gnychis** [comment]
Haha, argh... go figure that by chance, I would choose to generate an exception whose default was user handled.  I now see a better stack trace, too!  Thanks much, Andy.  

@zooba ... is this by design or an issue?  If it's by design, I'll close the issue.  Otherwise I'll leave it open.

**Comment by int19h** [comment]
It's by design. We decided to disable some exceptions that are thrown _really_ often in Python even for common, day-to-day scenarios.

**Comment by zooba** [comment]
More precisely, exceptions that are thrown often as part of a protocol and handled in a way that we can't reliably detect. `StopIteration` is an obvious example, where it isn't easy for us to tell that it's handled by a `for` statement, but there are also a few others like that, including `AttributeError`.
