### ISSUE TITLE
SSDT permissions for R / Python not recognized as valid sql statements

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6491]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SSDT-permissions-for-R--Python-not-reco/1404364)._

---
[severity:I'm unable to use this version]
The data tools return a SQL70596 error (Cannot determine securable object class from permission EXECUTE ANY EXTERNAL SCRIPT.) on the following statement:
_**GRANT EXECUTE ANY EXTERNAL SCRIPT TO <any user or database role>**_

I've seen the same sql error in previois versions of the DACFX Framework / Sqlpackage.exe (fixed in the latest version) in the past too, when deploying to a database where this permission was granted directly from sql server management studio.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
Sorry this isn't actually related to PTVS. We've reassigned it internally to the correct team.
