### ISSUE TITLE
Can't select python project as startup on quick select combobox with solution containing botch VB.Net and Python projects

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6493]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-select-python-project-as-startup-o/1394574)._

---
[severity:It bothers me. A fix would be nice]
Hello,
I have a solution with 4 VB.NET projects (2 WinForm App & 2 DLL Lib) + 1 Python project and I can't set the project as startup project directly on the top toolbar "standard" of VisualStudio. It shows only the 2 WinForm app.
I still can set the project as startup with the solution explorer but it's annoying.

---
#### Feedback Bot on 4/11/2021, 09:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on changing this functionality at this time.
