### ISSUE TITLE
An error message "Your  task failed with the message: Conda environment not detected" pops up when create Conda environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6494]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/115668348-96b8dd00-a379-11eb-8009-b80b1fb8d47c.png)

**Steps to Reproduce**
1. In VS, select File > New > Project,  select the Flask Web Project template.
2. Right click python environment and open “Add Environment…” command
3. Click "Conda environment" tab
4. Add some packages, such as "pyhon=3.7"
5. Click Create button
6. Observes

**Expected behavior**
The environment create successfully and then displayed in the Python Environment list.

**Actual result**
An error message "Your  task failed with the message: Conda environment not detected" pops up.
The output window shows that conda was created successfully, but there is an error message "Conda environment 'env2' was created, but it will not be detected by Visual Studio because it does not contain Python."
![image](https://user-images.githubusercontent.com/59192491/115669667-1abf9480-a37b-11eb-9eac-425e74896611.png)
And the Conda environment will not automatically appear in the Python Environment list 
![image](https://user-images.githubusercontent.com/59192491/115670512-134cbb00-a37c-11eb-9099-531ed19d5031.png)
After manually adding the created Conda environment, it works well.

**Comment by greazer** [comment]
@linette-zyy, This code hasn't changed for a long time. Can you see if this repros on 16.9 and then double check that it's still failing in 16.10. Please reopen if 16.10 continues to fail while 16.9 does not.

**Comment by linette-zyy** [comment]
This issue is reproduced in today’s build.
![image](https://user-images.githubusercontent.com/59192491/117255840-b291a800-ae7c-11eb-8884-94dedc0e8be9.png)

![image](https://user-images.githubusercontent.com/59192491/117255989-cc32ef80-ae7c-11eb-8ef3-7340d2cd0553.png)
