### ISSUE TITLE
Pytools for WSGI & Application Insights Logging

### ISSUE THREAD

**Issue by divyaspec** [Microsoft/PTVS#650]
I am using Python Flask based web services for writing REST API. I am currently having an error when I tried to use Application Insights for my project. Please see below lines of code.
<pre>
from applicationinsights.requests import WSGIApplication
from applicationinsights.logging import enable

app = Flask(__name__)
app.wsgi_app = WGSIApplication('<YOUR INSTRUMENTATION KEY GOES HERE>', app.wsgi_app)
#Set up excepion capture
enable('<YOUR INSTRUMENTATION KEY GOES HERE>')

#log something (this will be sent o the Application Insighs service as a trace)
logging.info('this is message')

#raise an exception (this will be sent to the Application Insighs service as an exception telemetry object)
raise Exception('boom!')
</pre>

**The error I am getting is - name error "WGSIApplication" is not defined.**
Has anyone else had this type of error before, if so how did you resolve this?
Thanks in advance

**Comment by crwilcox** [comment]
You have a typo on the fourth line.
WGSIApplication should be WSGIApplication

Hopefully that fixes your issue.

**Comment by divyaspec** [comment]
The issue is fixed. Apologies for the trouble. Thanks.
