### ISSUE TITLE
Python setuptools cannot find Visual Studio Express 2017

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6502]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-setuptools-cannot-find-Visual-Stu/1411215)._

---
[severity:It's more difficult to complete my work]

Python setuptools find Visual Studio using this command:
> C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere -latest -prerelease -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -products *

It returns nothing although VS Express 2017 is installed.

It's because component ID Microsoft.VisualStudio.Component.VC.Tools.x86.x64 is missing from VS Express 2017
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-express?view=vs-2017

It can be bypassed using vcvarsall.bat, but it's not always easy to use with.

Please add the component ID to VS Express 2017.

---
#### null on 4/29/2021, 10:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Thanks for the feedback. However, at this time we do not have plans on addressing this for VS 2017.
