### ISSUE TITLE
Conda virtual environment can't be detected after creating.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#6508]
**Steps to Reproduce**
1. In VS, select File > New > Project, select the Flask Web Project template.
2. Right click python environment and open “Add Environment…” command
3. Click "Conda environment" tab
4. Add some packages, such as "pyhon=3.7"
5. Click Create button

**Expected behavior**
The environment create successfully and then displayed in the Python Environment list.

**Actual result**
An error message "Your task failed with the message: Conda environment not detected" pops up.
The output window shows that conda was created successfully, but there is an error message "Conda environment 'env2' was created, but it will not be detected by Visual Studio because it does not contain Python."

![image](https://user-images.githubusercontent.com/39871640/118602521-63853480-b7e5-11eb-97d2-b80c79dc0d62.png)

**VS build info**
![image](https://user-images.githubusercontent.com/39871640/118602595-7a2b8b80-b7e5-11eb-9439-2c3e4e5c5082.png)

**Comment by greazer** [comment]
Looks like perhaps you misspelled python in "pyhon=3.7"?
