### ISSUE TITLE
Variables in the Autos window/Locals view are missing  with Legacy debugger.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6509]
**Steps to Reproduce**
1.Create Python Application in VS.
2.Typing code and set a breakpoint on the "for" statement.
![image](https://user-images.githubusercontent.com/82852072/118619874-90424780-b7f7-11eb-9859-be9d6c1346bb.png)
3.Make sure "Use legacy debugger" in tools/options/python/debugging is checked.
4.Press F5 to start debug.

**Expected behavior**
You can inspect in the Variables in the Autos window/Locals view.
![image](https://user-images.githubusercontent.com/82852072/118621070-9edd2e80-b7f8-11eb-8bc8-fe8cd1fcbd09.png)

**Actual behaviour**
![image](https://user-images.githubusercontent.com/82852072/118621653-25920b80-b7f9-11eb-950c-1c90e8605960.png)
After press F10 it still just show "..." and cannot see variables.

**Environment**
![image](https://user-images.githubusercontent.com/82852072/118624404-b7027d00-b7fb-11eb-9a8e-d60ea38463e3.png)

**Comment by greazer** [comment]
We're no longer supporting the legacy debugger. So this no longer needs to be tested. We'll remove the option from Dev17.

**Comment by ttSpace** [comment]
OK, thanks.
