### ISSUE TITLE
.gitignore being generated by adding python support to visual studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6511]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/gitignore-being-generated-by-adding-pyt/1423190)._

---
Adding Python support, possibly via a "R" installation for SQL Express creates .gitignore files in two locations; there are a total of six.gitignores that I did not create. I am using TFS and this system has never used GIT. Those files incorrectly exclude files within existing solutions including required files for the solution. The ignore can be manually overridden. Not that .gitignore is not an allowed attachment for this problem submission so they are included inline.
/pydevd_frame_evaluator.*.so
/pydevd_frame_evaluator.*.pyd
/pydevd_frame_evaluator.pyx

and 
/attach_x86.dylib
/attach_x86_64.dylib
/attach_linux_x86.o
/attach_linux_x86_64.o

---
#### Feedback Bot on 5/13/2021, 07:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ijoosong** [comment]
I haven't been able to repro this.  Going to close it out.
