### ISSUE TITLE
Visual Studio 2019 16.9.4 Tests are not being found in Test Explorer

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2019-1694-Tests-are-not-/1411890)._

---
[severity:I'm unable to use this version]
Getting this issue.. 

_---------- Starting test discovery ----------
Starting unittest discovery for the sentara-edp-ingestion workspace. This can take up to 60 seconds.
cd C:\Users\DGDRAKE\source\repos\sentara-edp-ingestion
set PYTHONPATH=C:\Users\DGDRAKE\source\repos\sentara-edp-ingestion\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\PythonFiles\testing_tools\run_adapter.py discover unittest --output-file C:\Users\DGDRAKE\AppData\Local\Temp\tmp8FAE.tmp -- . test*.py
No test is available in C:\Users\DGDRAKE\source\repos\sentara-...................
========== Test discovery finished: 0 Tests found in 906.5 ms ==========_

I am using a virtual python environment called (env).

If I run a similar command using the virtual environment python..

![Capture.PNG](https://aka.ms/dc/image?name=Be599b698d581445291a48163723e1346637554160062386367_Capture.PNG&tid=e599b698d581445291a48163723e1346637554160062386367)

I get what looks to be correct results in the tmp file.. 

![Capture2.PNG](https://aka.ms/dc/image?name=Bb037e7a7846b482ca7665a73cbe34920637554161248141939_Capture2.PNG&tid=b037e7a7846b482ca7665a73cbe34920637554161248141939)

I can't seem to figure out how to do following

1) Change the python executable being used
2) And make it so that it is following unittest's conventions. It should look for all *_test.py files

Here is my visual studio version

![Capture3.PNG](https://aka.ms/dc/image?name=Bc9992c554d63433995ed5295f0687b5b637554163274694019_Capture3.PNG&tid=c9992c554d63433995ed5295f0687b5b637554163274694019)

Edit: 

Just to add, my project configuration for this is: 

    MSBuild|env|$(MSBuildProjectFullPath)
    unittest
    *_test.py
    .

---
#### Feedback Bot on 5/2/2021, 04:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Are you setting up the test file spec in your project properties like in this image? 
![image](https://user-images.githubusercontent.com/11685408/118895868-d6f97580-b8bb-11eb-9047-4c8e5a43ab6d.png)

We've tried this with *_test.py and it seems to be working correctly.
