### ISSUE TITLE
An error message "Your task failed with the message: Conda environment not detected" pops up when create Conda environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6517]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/119092995-b8bd8200-ba41-11eb-8a38-c8dcfbffb627.png)

**Steps to Reproduce**
1. In VS, select File > New > Project, select the Flask Web Project template.
2. Right click python environment and open “Add Environment…” command
3. Click "Conda environment" tab
4. Add some packages, such as "python=3.7"
![image](https://user-images.githubusercontent.com/59192491/119128551-617ed800-ba68-11eb-857d-9c5b2b1f354a.png)
5. Click Create button
6. Observes

Expected behavior
The environment create successfully and then displayed in the Python Environment list.

Actual result
An error message "Your task failed with the message: Conda environment not detected" pops up.
The output window shows that conda was created successfully, but there is an error message "Conda environment 'env1' was created, but it will not be detected by Visual Studio because it does not contain Python."
![image](https://user-images.githubusercontent.com/59192491/119093204-ff12e100-ba41-11eb-80ee-4b5970be5d3d.png)

**Comment by linette-zyy** [comment]
We can add this Conda environment manually to Enviroment list.

**Comment by rchiodo** [comment]
This sounds like the 'add python' in the dropdown is not working or the python picked is no longer supported by conda.

**Comment by bschnurr** [comment]
@rchiodo didn't we change the task/thread stuff around this?

**Comment by rchiodo** [comment]
That was conda environment detection I believe, but it might be that it's not waiting correctly anymore?

**Comment by bschnurr** [comment]
I was able to repro, investigating still

**Comment by bschnurr** [comment]
seems like a discovery isn't being triggered

**Comment by bschnurr** [comment]
this returns null after we just created the new env, because its list hasn't been updated
```
  // This will return null if the environment that was created does
            // not contain a python interpreter. Common case for this is
            // when the package list the user has entered is empty string.
            var factory = _factoryProvider?.GetInterpreterFactory(expectedId);
```

oh. but right after we couldn't find the new environment the ToolWindow.xaml.cs   calls UpdateEnvironments()
```
private async void Service_InterpretersChanged(object sender, EventArgs e) {

```

so could be a race condition

**Comment by bschnurr** [comment]
oh. i think its this statement is supposed to force discovery when it gets disposed

```
// Force discovery, don't respect the ignore nofitication ref count,
            // which won't go back to 0 if multiple conda environments are being
            // created around the same time. We need the discovery in order to find
            // the new factory.
            using (_factoryProvider?.SuppressDiscoverFactories(forceDiscoveryOnDispose: true)) {
```

**Comment by bschnurr** [comment]
oh man. do we have to use async dispose? https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#using-async-disposable

**Comment by bschnurr** [comment]
@rchiodo I dont really want to replace the 3 implementations of SuppressDiscoverFactories to something async

**Comment by bschnurr** [comment]
i'd rather just remove the newly added DoNotWait() calls

**Comment by linette-zyy** [comment]
This issue still reproduced on 16.11 Preview 3
![image](https://user-images.githubusercontent.com/59192491/125025623-921cde80-e0b5-11eb-8f83-8dbfb7088e7e.png)
![image](https://user-images.githubusercontent.com/59192491/125025710-bed0f600-e0b5-11eb-9b6f-c6bc76a20319.png)

**Comment by rchiodo** [comment]
It looks like the fix is the main branch but hasn't been ported to 16 yet.

**Comment by GregSal** [comment]
As a user experiencing the same issue (see #6596), I would think that a simple solution would be to allow the user to manually trigger a discovery.
