### ISSUE TITLE
Some options like "Update search paths when adding linked files" are missing

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6529]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/119939113-ecf3ee00-bfbf-11eb-858d-6b54c7ef30f5.png)

**Steps to Reproduce**

1. Launch VS and select Tools > Options > Python > General

**Expected behavior**

![image](https://user-images.githubusercontent.com/82852072/119939606-b5397600-bfc0-11eb-9b11-a871776df730.png)

**Actual behavior**

![image](https://user-images.githubusercontent.com/82852072/119939803-f6318a80-bfc0-11eb-836f-def551c405b9.png)

**Comment by rchiodo** [comment]
These options are no longer supported.
