### ISSUE TITLE
Interactive window doesn't like UTF8 BOM

### ISSUE THREAD

**Issue by andygraham** [Microsoft/PTVS#653]
VS2013 Desktop Express, IronPython 2.7.5, PTVS 2.2.30718.00
I may be displaying my ignorance of how to set up Visual Studio but ...

I create a new IronPython project in VS, enter my code in the .py file and it runs fine. This plain vanlila code has no dependencies on search paths etc and should run just fine if I open the file directly and do Menu Debug -> Run in Python Interactive. But it doesn't :( failing with "SyntaxError: unexpected token '\xbb'" on the first line. It seems IronPython projects files are saved as UTF8 with a Byte Order Mark that the interactive window doesn't like.

Have I unwittingly managed to change a default somewhere to cause this?

**Comment by zooba** [comment]
We've heard a few people suffering from Visual Studio automatically adding the BOM without good reason. We ought to trim it off in this case, but we're also looking into how we prevent that happening (or if we even can - it may not be possible to override that).

**Comment by drillep** [comment]
I have a similar problem which can be very problematic.  If I run my app with a syntax error the BOM gets added, I cannot work out how to remove the BOM rendering the project to fail every time even if I remove the offending .py class and start again.

**Comment by zooba** [comment]
This no longer reproduces on VS 2017
