### ISSUE TITLE
Some functions are missing in Dev17.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6530]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/119940185-66d8a700-bfc1-11eb-85b5-2651f0b55f37.png)

**Actual result**
**1. Extract method and remove imports are missing.**
1. Go to to Edit> Refactor
2. Observe
![image](https://user-images.githubusercontent.com/59192491/119954982-25042c80-bfd2-11eb-9625-693e999afae0.png)

**Comment by rchiodo** [comment]
I believe these are no longer supported.

**Comment by rchiodo** [comment]
@judej do you think the changes here need to be documented?

**Comment by ijoosong** [comment]
Looks like some of the docs on this page need to be revisited:
https://docs.microsoft.com/en-us/visualstudio/python/refactoring-python-code?view=vs-2022#extract-method

I'll go ahead and investigate these and close this when the PR is done

**Comment by ijoosong** [comment]
PR in for removing code
