### ISSUE TITLE
Some options are missing in Dev17.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6531]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/119942988-03e90f00-bfc5-11eb-9c1a-47b7c33f3e94.png)

**Actual result**

**1. The language server tab is missing.**
1. Go to Tools/options/python
2. Check the option under Python.
![image](https://user-images.githubusercontent.com/59192491/119942941-f6cc2000-bfc4-11eb-9d1e-3e77c395b0dc.png)

**2. Python entries in the Display items list are missing.**
1. Go to to Tools > Options > Environment > Fonts and colors
2. Check Display items list
![image](https://user-images.githubusercontent.com/59192491/119940411-b6b76e00-bfc1-11eb-8ced-ddb18ac7796f.png)

**3. "Warn when imported module cannot be found" in  tools/options/python/general is missing**
![image](https://user-images.githubusercontent.com/59192491/119955821-03f00b80-bfd3-11eb-9c74-86149ecc8008.png)

**4. Diagnostics tab is missing.**
![image](https://user-images.githubusercontent.com/59192491/119956752-0141e600-bfd4-11eb-98c0-eea6d3203534.png)

**Comment by greazer** [comment]
This is by-design as Pylance does not support these options anymore.
