### ISSUE TITLE
The command of Search Paths/Add Reference don't work

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6533]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/119944380-c9807180-bfc6-11eb-8f7f-35fe9b8015de.png)

**Steps to Reproduce**

1. Module2.py file prepared with below code copied to C:\TestforFolder
   def hello(): print('hello')
2. Right-click Search Paths Node in SE and select Add folder to Search Path
3. Type from Module2 import * to make sure it works

**Expected behavior**

It should work and have any completions on Module2.

**Actual behavior**

It doesn't work, even if display in the earch Paths Node in SE.
![image](https://user-images.githubusercontent.com/82852072/119946505-47457c80-bfc9-11eb-8f8f-e52f54fa31ae.png)

**Additional context and screenshots**
"Add Zip Archive to search path" and "Add PYTHONPATH to search path" don't work either.
![image](https://user-images.githubusercontent.com/82852072/119945969-aa82df00-bfc8-11eb-8734-fa8a53570afe.png)
" Add Reference " cannot get the intellisense of ProjectB.
![image](https://user-images.githubusercontent.com/82852072/119953371-83c8a680-bfd0-11eb-9253-72239d4da569.png)

**Comment by rchiodo** [comment]
This should be fixed with tomorrow's build.
