### ISSUE TITLE
No response after pressing F12 or clicking go to Definition.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6534]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/119946667-75c35780-bfc9-11eb-9acf-2445900d71d5.png)

**Steps to Reproduce**
1. Create a Python Application project
2. Type the code as following or the code you are desiring 
```
	from math import cos, radians
	
	# Create a string with spaces proportional to a cosine of x in degrees
	def make_dot_string(x):
	    rad = radians(x)                             # cos works with radians
	    numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	    st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	    return st
	
	def main():
	    for i in range(0, 1800, 12):
	        s = make_dot_string(i)
	        print(s)
	
	main()
```
3. Move mouse to "make_dot_string" and press F12.

**Actual result**
No response after pressing F12 or clicking go to Definition.
![No response](https://user-images.githubusercontent.com/59192491/119947489-5ed13500-bfca-11eb-8aed-69adbe25bd45.gif)

**Comment by rchiodo** [comment]
It looks to me like pylance isn't up and running yet. You have to wait for some output to appear in the pylance tab.
