### ISSUE TITLE
Rename does not work.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6536]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/119957383-9cd35680-bfd4-11eb-8daf-dce46bba12a5.png)

**Steps to Reproduce**
1. Create a Python Application project
2. Type the code as following or the code you are desiring 
```
	from math import cos, radians
	
	# Create a string with spaces proportional to a cosine of x in degrees
	def make_dot_string(x):
	    rad = radians(x)                             # cos works with radians
	    numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	    st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	    return st
	
	def main():
	    for i in range(0, 1800, 12):
	        s = make_dot_string(i)
	        print(s)
	
	main()
```
3. Move mouse to "make_dot_string" and right click
4. Click rename then input other name and press enter.

**Expected behavior**
The "make_dot_string" is changed.

**Actual result**
Rename does not work.
![Rename](https://user-images.githubusercontent.com/59192491/119958211-677b3880-bfd5-11eb-8c93-d8dace18fdcd.gif)

**Comment by rchiodo** [comment]
This looks to be a bug in the handling of URIs in the VS language server client. See this pr here:
https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/328661

**Comment by rchiodo** [comment]
Should be fixed
