### ISSUE TITLE
Cookiecutter Explorer is missing 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6537]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/119957363-98a73900-bfd4-11eb-905e-31d3d9dfc916.png)

**Steps to Reproduce**

Launch VS, select View > Cookiecutter Explorer
![image](https://user-images.githubusercontent.com/82852072/119957861-0ce1dc80-bfd5-11eb-9467-e61ad8bab5be.png)

**Comment by rchiodo** [comment]
Seems this works when debugging but not during the installation.
