### ISSUE TITLE
No static analysis suggestions in Interactive window.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6538]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/119960743-dfe2f900-bfd7-11eb-8a6f-95f66ccbb568.png)

**Steps to Reproduce**
1. Ensure the completion mode is not "Never evaluate expressions"
2. Ensure the option "Hide static analysis suggestions" is unchecked by default
![image](https://user-images.githubusercontent.com/59192491/119961167-554ec980-bfd8-11eb-88ae-f21b984bc270.png)

**Expected behavior**
Make sure the static analysis suggestions have better information (tooltip and different icons), and there are sometimes more results
![image](https://user-images.githubusercontent.com/59192491/119960966-1ae52c80-bfd8-11eb-8baf-81cf94fbd903.png)

**Actual result**
No static analysis suggestions in Interactive window.
![image](https://user-images.githubusercontent.com/59192491/119961133-4d8f2500-bfd8-11eb-842b-8ab566b8c6bd.png)

**Comment by rchiodo** [comment]
I'm guessing the evaluation options are not passed to pylance (or may not be supported)

**Comment by AdamYoblick** [comment]
If pylance/repl doesn't support this anymore, then the checkboxes should be removed from options, or it needs to be re-added to PTVS

**Comment by ttSpace** [comment]
In today's build ```17.10.0 Preview 2.0 [34617.5.main]```, Python Package ```17.0.24045.1 ```. 
No static analysis suggestions in Interactive window.

<img width="214" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/2984bcb0-1dc9-447d-8a67-dfb269a2afae">

**Comment by judej** [comment]
This is a bug, but given the lack of reports from users, we will not be fixing this.
