### ISSUE TITLE
UnitTest on TargetPlatform x64

### ISSUE THREAD

**Issue by zwing99** [Microsoft/PTVS#654]
Unittest dont show up when the test setting target platform is x64. My solution is a mix of c++ that directly compiles to x64 modules.  Thanks.

**Comment by int19h** [comment]
Do you also have the active Python interpreter for your solution set to a 64-bit Python? (note that if you just did it, you might need to re-open your solution for Test Explorer to notice the change)

**Comment by zooba** [comment]
Actually, this is because our test adapter cannot be loaded in the 64-bit host process. If we sacrifice user-defined environments then we could do it, but really we need to come up with a better way of storing settings (or running unit tests) before this can be enabled.

**Comment by zwing99** [comment]
Sounds like you are aware of the issue. I could pry come up with a sample solution that exhibits the behavior if you need. Currently i am using boost python but i think i could make it work with the raw c-api.

**Comment by zooba** [comment]
Yeah, I investigated it a while back. The simpler repro is to just change the target platform to X64 in the Test menu.

**Comment by zooba** [comment]
And it works (a.k.a. fails :) ) with a pure Python project, because the issue is in part of our C# code.

**Comment by zwing99** [comment]
Is there any progress made for this? I would really like to see all my tests.

**Comment by crwilcox** [comment]
@zwing Thanks for checking in on this. We haven't fixed this yet and to my knowledge no significant progress has been made. It does require a bit of thought on how to address this and is a bit more involved than a 'quick' bug fix.
Thanks!

**Comment by zooba** [comment]
This works in our latest previews, though there is an annoying message reminding you that Python is not .NET language...
