### ISSUE TITLE
"Ctrl + Enter" does not work.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6540]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/119963444-afe92500-bfda-11eb-952a-7249915b97dc.png)

**Steps to Reproduce**
1. Create a new project
2. Input some code
3. Press ctrl+enter to execute code

**Expected behavior**
The code is executed.

**Actual result**
Add a new line after pressing Ctrl + Enter.

**Comment by rchiodo** [comment]
This is expected. CTRL+ENTER is being stolen by another key press.

You can see it here:

![image](https://user-images.githubusercontent.com/19672699/120513924-969cfb80-c381-11eb-80fb-5635e5152a52.png)

If you want to use CTRL+ENTER you have to remap the Edit.LineInsertAbove or use CTRL+E,E
