### ISSUE TITLE
Go To All does not work.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6541]
**Environment*
![image](https://user-images.githubusercontent.com/59192491/119965156-8df0a200-bfdc-11eb-9981-dacb65f664ce.png)

**Steps to Reproduce**
1.Create python application and type code 
```
from math import cos, radians
def make_dot_string(x):
	rad = radians(x)                             # cos works with radians
	numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	return st
def main():
	for i in range(0, 1800, 12):
	    s = make_dot_string(i)
	    print(s)
main()
```
2. Close opened .py file and press ctrl+, ,input "make_dot_string"
3. Choose the file under the list and press enter

**Except result**
The file should be opened.

**Actual result**
No file was opened.

**Comment by rchiodo** [comment]
Not sure how this is handled. Likely something in the language client implementation.

**Comment by rchiodo** [comment]
This looks to be a bug in the handling of URIs in the VS language server client. See this pr here:
https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/328661

**Comment by rchiodo** [comment]
Should be fixed
