### ISSUE TITLE
Debugger behave strange when using @classmethod in a class

### ISSUE THREAD

**Issue by BenjV** [microsoft/PTVS#6542]
**Describe the bug**
When a @classmethod is used and you step through a program with the debugger is activate teh code of that function without being called.

**Steps to Reproduce**
This sample code below demonstrates the problem

**Expected behavior**
If you run it without stepping through it in the debugger the result will be:

> This is a Test
> End of program

If you run it in debugging mode the result will be:

> This is a Test
> End of program
> Test has been done

If you set a break at the first line of the CONF class and step through it with F10 (step over) then the result will be:

> This is a Test
> Test has been done
> Test has been done
> End of program
> Test has been done

If you set a break at the first line of the CONF class and step through it with F11 (step into) then the result will be:

> This is a Test
> Test has been done
> Test has been done
> Test has been done
> Test has been done
> Test has been done
> End of program
> Test has been done

**Sample Code**
```
class CONF:
    test = 'This is a Test'

    @classmethod
    def Read(cls):
        print(cls.test)
        cls.test = 'Test has been done'

CONF.Read()
print('End of program')
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.10.0
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
Python version: 3.8
Debugger Type (if applicable): [New debugger or legacy debugger?]

[Diagnostic Info 2021-05-29T120054.txt](https://github.com/microsoft/PTVS/files/6564434/Diagnostic.Info.2021-05-29T120054.txt)

**Comment by greazer** [comment]
This is by design per the duplicate community bug that we recently closed.

**Comment by BenjV** [comment]
@greazer 

This means @classmethodes cannot be debugged e.g. cannot be used?
Maybe a link to that bug so I can understand it?
