### ISSUE TITLE
No variables in Auto window when debug.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6543]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/120148824-650a2000-c21b-11eb-9007-69974f536303.png)

**Steps to Reproduce**
1. Create a Python Application project
2. Type the code as following or the code you are desiring 
```
from math import cos, radians

# Create a string with spaces proportional to a cosine of x in degrees
def make_dot_string(x):
	  rad = radians(x)                             # cos works with radians
	  numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	  st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	  return st

def main():
	  for i in range(0, 1800, 12):
	      s = make_dot_string(i)
	      print(s)

main()
```
3. Check the code works properly by pressing F5 or select the Debug > Start Debugging
4. Set a breakpoint on the "for" statement 
5. Start the debugger again(F5) and see that running the code hit the breakpoint
	a. You can inspect the call stack and examine variables
	b. Variables that are in-scope appear in the Autos window when they're defined
	c. Locals view show all variables that VS finds in the current scope(including functions), even before they're defined

**Actual result**
No variables in Auto window.
![image](https://user-images.githubusercontent.com/59192491/120149052-bc0ff500-c21b-11eb-9ef6-cb2c49b14d76.png)

**Comment by int19h** [comment]
See https://github.com/microsoft/debugpy/issues/161

**Comment by judej** [comment]
related to https://github.com/microsoft/debugpy/issues/161
