### ISSUE TITLE
IronPython 2.7.11 are not detected and listed in Visual Studio Python Environment

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6548]
**Describe the bug**
![image](https://user-images.githubusercontent.com/82852072/120300579-a58e9a00-c2fe-11eb-8ab9-c210e798ca2e.png)

**Steps to Reproduce**
1. Install IronPython (downloads at http://ironpython.net ) if no IronPython.
2. Create Python Application project.
3. Right-click on Python Environments node in SE and select "View All Python Environments".

**Expected behavior**
The Ironpython distributions installed should displayed in the list.

**Actual behavior**
![image](https://user-images.githubusercontent.com/82852072/120301289-467d5500-c2ff-11eb-98dd-5f2fdb6353c7.png)

**Comment by rchiodo** [comment]
Thanks for the bug. IronPython is no longer supported.

**Comment by sopelt** [comment]
Hi @rchiodo , could you please clarify which support has been dropped/will be dropped? It looks like VS2022 still debugs hosted/embedded IronPython as long as the necessary debug info is still there even though new projects/environments are no longer available.

It also seems like debugging only works for .NET 4.x and not for core/5/6. Do you happen to have any info on why that is?

And as a last request: depending on your answers it might be nice to update https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-in-visual-studio?view=vs-2022 accordingly. Is that content managed by the team itself or should I raise an issue there as well?

**Comment by rchiodo** [comment]
IronPython is no longer officially [supported](https://developercommunity.visualstudio.com/t/will-vs-2022-support-ironpython/1477532). So if it works, it's just by luck. We don't test with it anymore so you'd be on your own if you wanted to use it with VS 2022. I believe VS 2019 was the last version that had support for it.
