### ISSUE TITLE
Enable easier debugging for python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6556]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Enable-easier-debugging-for-python/1429403)._

---
Add debugging rewind feature to python code stepping.  When stepping through code, enable option to step backwards...

---
#### Feedback Bot on 5/24/2021, 02:10 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by rchiodo** [comment]
Thanks for the suggestion.
