### ISSUE TITLE
Visual Studio Developer Command Prompt and Developer PowerShell not working

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6565]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Developer-Command-Prompt-a/1446052)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.10.0]
I recently uninstalled python 3.9.5 from my computer and I had issues with getting a python interpreter to work after trying to install python 3.7.8 through Visual Studio Installer. I then used the repair option in Visual Studio Installer and that got python to work but also made the Developer Command Prompt and Developer PowerShell stop working. I get "The terminal process has exited with exit code -1073741502." The Developer Command Prompt and Developer PowerShell under Tools->Command Line work fine. I am using Windows 10.0.19042.1052. I also tried uninstalling and reinstalling Visual Studio but I get the same problem. I also recently updated Visual Studio.

Also, Firefox and Firefox Developer Edition stopped working. It says "The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem." Microsoft Edge and Chrome work fine.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment]
Thanks for the question, but unfortunately, this is more likely a bug in the Python uninstaller. The easiest solution is to reinstall Python 3.9.5.
