### ISSUE TITLE
"Add PYTHONPATH to Search Path" has no completions.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6568]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/121474069-22ec9580-c9f6-11eb-9fec-da867cce940b.png)

**Steps to Reproduce**

1. module2.py file was prepared with below code.
```
def hello():
    print("hello")
```
2. Add the module2.py path to PYTHONPATH.
3. In the default python file type "import module2" to make sure it works.

**Expected behavior**

It should work and have any completions on module2.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/121475090-9216b980-c9f7-11eb-816f-5acc3bc83315.png)
![image](https://user-images.githubusercontent.com/82852072/121475226-b70b2c80-c9f7-11eb-801c-431a902f07a7.png)

**Comment by rchiodo** [comment]
@ttSpace I believe your usage of PYTHONPATH is incorrect. You should instead have it set like this:

```
PYTHONPATH: "C:\Test"
```

PYTHONPATH is a set of directories, not the files themselves.
