### ISSUE TITLE
The Cookiecutter Explorer module do not detect Python3.9.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6573]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/122326717-49af4c80-cf5f-11eb-98e2-a911b5aec3ff.png)

**Steps to Reproduce**
1.  Launch VS
2. Select View > Cookiecutter Explorer
3. Observe

**Actual result**
The Cookiecutter Explorer module do not detect Python3.9.
![image](https://user-images.githubusercontent.com/59192491/122326685-3d2af400-cf5f-11eb-9e3f-f34cca0617fd.png)

The default installed python is python3.9.
![image](https://user-images.githubusercontent.com/59192491/122326669-369c7c80-cf5f-11eb-8f1d-536ce65f4648.png)

After install Python3.7 manually, the Cookiecutter Explorer works well.

**Comment by rchiodo** [comment]
Thanks. This is a bug in the cookie cutter stuff. It doesn't have code to handle 3.8 or 3.9.
