### ISSUE TITLE
VS is crash when load GitHub repository for a cookiecutter template.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6574]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/122329464-0a372f00-cf64-11eb-91e4-e73e36c30ad1.png)

**Steps to Reproduce**
1. Launch VS
2. Select View > Cookiecutter Explorer
3. In the search box, enter a URL to  
e.g. https://github.com/Microsoft/python-sklearn-classifier-cookiecutter
4. Click next to load.

**Expected behavior**
It should display an error in output window.

**Actual result**
The VS is crash and restart.

**Events log**
[Event Log.zip](https://github.com/microsoft/PTVS/files/6667306/Event.Log.zip)

**Comment by linette-zyy** [comment]
When delete template, the VS is also crash.

**Comment by rchiodo** [comment]
I'm not reproing this. It works for me. 

What error are you expecting?

The error actually looks like PerfWatson is crashing. Ah bug is logged already on core product:
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1341022
