### ISSUE TITLE
VS is crash when delete template.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6575]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/122329464-0a372f00-cf64-11eb-91e4-e73e36c30ad1.png)

**Steps to Reproduce**
1. Launch VS
2. Select View > Cookiecutter Explorer
3. Select a template from the installed section
4. Delete a template
5. Observe

**Expected behavior**
The template is deleted.

**Actual result**
The VS is crash and restart.

**Events log**
[Events log.zip](https://github.com/microsoft/PTVS/files/6667549/Events.log.zip)

**Comment by rchiodo** [comment]
Dupe of #6574. Same error - Perfwatson crash. Assuming the event log has the correct crash in it.
