### ISSUE TITLE
Do not prompt to install the missing module When use IPython interactive mode on python3.9.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6576]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/122714850-95812f00-d29a-11eb-9433-51a254e67bd8.png)

**Steps to Reproduce**
1. Create a python application
2. Open "Python Environments" window->"Overview" page to enable "Use Ipython interactive mode"
4. Open interactive window to type "1"

**Expected behavior**
It should prompt to install "Ipython" and "ipykernel".

**Actual result**
The error message is different from the message on Python 3.7.
![image](https://user-images.githubusercontent.com/59192491/122715384-5d2e2080-d29b-11eb-9073-d40dcf4f6855.png)

**Comment by greazer** [comment]
Thanks. However, this isn't something we need to address. Nothing is blocked there's just more information provided in the actual result vs the expected.
