### ISSUE TITLE
VS is crash

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6577]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/122877722-7e5d4280-d369-11eb-9c7e-5e3bdcda5a88.png)

**Steps to Reproduce**

1. Launch VS
2. Select View > Cookiecutter Explorer
3. In the search box, enter a URL to
   e.g. https://github.com/Microsoft/python-sklearn-classifier-cookiecutter
4. Click next to load.

**Expected behavior**

It should  create successfully.

**Additional context **

VS crashed and restarted. By the way, the VS crash and restart also occurred when deleting the template, which should have been deleted normally.

**Comment by rchiodo** [comment]
This sounds like the same bug as this one:
https://github.com/microsoft/PTVS/issues/6574
