### ISSUE TITLE
VS is crash when load GitHub repository for a cookiecutter template.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6593]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/124425772-9e462a80-dd9b-11eb-9195-dcc8e42a58d2.png)

**Steps to Reproduce**
1. Launch VS
2. Select View > Cookiecutter Explorer
3. In the search box, enter a URL to
4. e.g. https://github.com/Microsoft/python-sklearn-classifier-cookiecutter
5. Click next to load.

**Expected behavior**
It should display an error in output window.

**Additional context and screenshots**
The VS is crash and restart.

**Screenshot**
![VS carsh](https://user-images.githubusercontent.com/59192491/124426405-95a22400-dd9c-11eb-8373-abe163daeeba.gif)

**Comment by linette-zyy** [comment]
https://github.com/microsoft/PTVS/issues/6574

**Comment by linette-zyy** [comment]
This issue is the same as this issue https://github.com/microsoft/PTVS/issues/6574, but I can't reopen, so I submitted a new one.

**Comment by rchiodo** [comment]
The other bug is an issue with perfwatson. It's an external issue.
