### ISSUE TITLE
python collapse/expand not working sometimes

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6598]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python-collapseexpand-not-working-somet/1466081)._

---
Am option a python folder in VS2019, it works.
But after sometime (may be days), the intellisence, expand/collapse etc all stop working.
There should be an option in the tools menu to refresh so we can re-gain all those things instead of closing the project and opening it again.
Thank you

---
#### Feedback Bot on 7/1/2021, 11:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
Do you have any more explicit repro steps? This bug is not reproing locally with both a workspace and a solution.

Do you have a zip of a folder that causes the problem?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen.

**Comment by tojiamathewwork** [comment]
This is still an issue on VS2022 also.
