### ISSUE TITLE
Couldn't get the online figures / graphs in the interactive window

### ISSUE THREAD

**Issue by zcindy9075** [microsoft/PTVS#6600]
I created a virtual environment and installed all the packages for a python application in visual studio 2019. My simulation can run properly in the python interactive window, but no online graphs or figures in the interactive window. Instead, all the data used for the plot are printed out in the interactive window. Therefore, I tried to install a condo environment in order to get my figures and graphs online. Unfortunately, I got an error message: "Conda environment was created, but it will not be detected by Visual Studio because it does not contain Python.". How could I fix my problem to bring my figures and graphs online?

I always tried the example code at https://matplotlib.org/2.0.2/examples/showcase/mandelbrot.html as used in the video https://www.youtube.com/watch?v=rq55s2eTyv4&list=WL&index=26&t=757s, I still couldn't get the figure online in the interactive window.  

After having installed ipython and ipykernel, the figures almost showed up in the interactive window, but it couldn't stay. Finally, I simply got a blank space or a statement "Out [18]: [<matplotlib.lines.Line2D at 0x19349f13f08>]".

**Comment by rchiodo** [comment]
I get the same error. The image will just flash. I believe the interactive mode that IPython is using doesn't work in side of VS. 

This sort of works:

![image](https://user-images.githubusercontent.com/19672699/125372579-4ded4080-e338-11eb-82f6-c4e42bb261c7.png)

But the image disappears after the pause is done. 

You might try playing around with different backends for matplotlib. However I recommend just using VS code's [interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py) instead. It supports all plotting types.
