### ISSUE TITLE
Investigate how to ship an executable for debugpy attach

### ISSUE THREAD

**Issue by rchiodo** [microsoft/PTVS#6606]
Debugpy attach requires launching debugpy using a python interpreter. This works okay if the process being attached is a python interpreter as the same interpreter can be used to start debugpy.

However there are use cases where a user is attaching to a process with python*.dll in it, but there isn't a python interpreter. 

What to do in those use cases?

**Comment by rchiodo** [comment]
One thought: https://www.py2exe.org/

Generate the executable during the PTVS build (so debugpy doesn't have to ship binaries)

**Comment by judej** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PTVS-Pylance-573ddf64cd9225ae72c86a34/issues/microsoft/PTVS/6606?planning-poker) with ZenHub @bschnurr

**Comment by rchiodo** [comment]
@int19h was looking into this in a separate issue. Going to close for now.
