### ISSUE TITLE
VS is no response when open a workspace.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6608]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/125918213-e4b1e688-4333-4f20-bd7e-b07998766ac3.png)

**Steps to Reproduce**
1. Open a folder and add a python file
2. Observers

**Expected behavior**
VS works well.

**Actual result**
VS is no response.

**Events Log**
[Error.zip](https://github.com/microsoft/PTVS/files/6829198/Error.zip)

**Comment by rchiodo** [comment]
Does this repro with other files? This is likely a base editor bug.

**Comment by rchiodo** [comment]
@linette-zyy it looks like VS crashed. Can you set this registry key:

https://docs.microsoft.com/en-US/troubleshoot/windows-server/performance/memory-dump-file-options#registry-values-for-startup-and-recovery

To this value:
CrashDumpEnabled REG_DWORD 0x3 = Small memory dump (64 KB)

And then try again. 

That should save a dmp file at %SYSTEM32%\Memory.dmp.

That dmp file would have the callstack for where the process crashed and we can use that to determine who is actually responsible for the bug.

**Comment by zhouwangyang** [comment]
@rchiodo thanks for your feedback, I set this value as you say, and then reproduce this issue, but no dmp file can be found at %SYSTEM32%\Memory.dmp.
![image](https://user-images.githubusercontent.com/39871640/126114844-9ff7ee4a-0dfc-4030-a69d-6ba1fd90eef6.png)

**Comment by rchiodo** [comment]
Your screenshot shows the DumpFile as ```%SystemRoot%\Memory.dmp```

Does that file exist?

**Comment by zhouwangyang** [comment]
it doesn't exit at that directory.

**Comment by linette-zyy** [comment]
@rchiodo This issue still occurred on today's build.
![image](https://user-images.githubusercontent.com/59192491/126593146-7472eef7-7fc3-4da1-94db-f12f86dcd714.png)
![VS carsh](https://user-images.githubusercontent.com/59192491/126593406-171eea5f-93f6-4c36-beff-f02a1a7f403c.gif)

**Comment by rchiodo** [comment]
That looks different. It's hanging instead of crashing? Does it ever come back?

Does it repro with a non python file?

**Comment by linette-zyy** [comment]
Yes, the VS is no response. In a few minutes, VS will restart and the issue also reproduced.
![image](https://user-images.githubusercontent.com/59192491/126595301-9b8e8002-4d58-4cef-bae7-21e76d2bbdc2.png)
I added some other file, VS is not hang.
![image](https://user-images.githubusercontent.com/59192491/126595365-03a21d55-9b81-48c5-ada1-0f3a423bdda2.png)
After add a python file, VS is hang.

**Comment by rchiodo** [comment]
This should be fixed in the latest build of VS Preview 3. Something like 31529 or later.
