### ISSUE TITLE
Ironpython doesn't work with latest version of VS 2019 (preview 3.0)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Ironpython-doesnt-work-with-latest-vers/1473864)._

---
If you open a project with the python environment set to Ironpython, VS reports an error. You now get unknown interpreter.
**VS 2019 (16.9.3 ) still works.**

---
#### Feedback Bot on 7/13/2021, 10:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
Thanks for the issue. We're about to drop IronPython support (officially in D17) so this is a low priority at the moment. You might have to stick with 16.9 instead.

**Comment by greazer** [comment]
Sorry, but IronPython will no longer be supported in Visual Studio 2022.

**Comment by sanjaynsan** [comment]
i am begginer and this may sound stupid.
which version of iron python supports vs 2019 16.9.3
