### ISSUE TITLE
Error while building the project inside a Docker dev container

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/PTVS#6614]
**Describe your question**
I am trying to build the project inside a Docker container with Ubuntu 20.04, .NET 5.0.300, Mono 6 and nuget CLI installed.

I get the following error when executing this command per the contribution guide `msbuild Python\dirs.proj`:

```
"/workspaces/PTVS/Python/dirs.proj" (default target) (1) ->
(_EnsureDependenciesInstalled target) -> 
  /workspaces/PTVS/Build/Common.Build.settings(98,5): error MSB3073: The command "mono powershell.exe -ExecutionPolicy Bypass -File "/workspaces/PTVS/Build/PreBuild.ps1" -VsTarget 16.0" exited with code 2. [/workspaces/PTVS/Python/dirs.proj]
```

Is there something I could and I am not or is the project not compatible with development under Ubuntu ?

**Comment by rchiodo** [comment]
Sorry but you have to build on windows. Visual Studio only runs on windows. This extension to VS also only runs on windows.
