### ISSUE TITLE
Python selenium scripts not launching in VS 2015 Professional version

### ISSUE THREAD

**Issue by scm1970** [Microsoft/PTVS#662]
Hi,

I migrated to VS 2015 Professional a couple of days ago. I uploaded the latest PTVS extensions.  My Python 3/Selenium tests were imported from VS 2013, where they used to run without any issues.  

There doesn't seem to be any issues or any errors when I look at my scripts via Visual Studio 2015.  VS 2015, Test Explorer/Test Runner discovers all my Python Selenium tests. However, when I launch them through VS 2015, the tests keep running without anything seeming to happen. The FF or Chrome browser never gets launched.  I know the tests are correct as they used to run via VS 2013 and also, even now, if I run them standalone via a Python Shell, they run without any issues.   The debugger doesn't allow me to step through anything. It starts loading up and then exits with the following message: The program '[10428] te.processhost.managed.exe' has exited with code 0 (0x0).

Anyone else having similar issues running their Python Selenium tests via VS 2015 and the associated PTVS extensions?

**Comment by zooba** [comment]
Can you post or link to some example tests? I have no experience running Selenium tests, but it seems likely that a change to our launcher has affected something.

Were you using PTVS 2.2 prereleases on VS 2013? Or did you move directly from PTVS 2.1?

**Comment by scm1970** [comment]
Sure. I'm appending a bare bones script that I just wrote. It runs fine as a standalone script but is not launching through VS 2015 Professional. I did a lot of cleaning up the last few days, and so I'm not sure anymore if I used PTVS 2.1 or the PTVS 2.2 pre-releases with VS 2013.  I can actually re-install VS 2013 alongside VS 2015, but I'm just tied up with a lot of work, and so if you can't see any obvious errors, I can try it next week.  I'm appending a simple piece of code that should launch a firefox browser and go to cnn.com, Thanks again:

===
import unittest, time
from selenium import webdriver



class Test_test1(unittest.TestCase):
    def test_A(self):
        driver = webdriver.Firefox()
        base_url = "http://www.cnn.com"
        driver.get(base_url)
        time.sleep(10)
        driver.quit()
        
if __name__ == '__main__':
    unittest.main()

**Comment by scm1970** [comment]
Sure. I'm appending a bare bones script that I just wrote. It runs fine as a standalone script but is not launching through VS 2015 Professional. I did a lot of cleaning up the last few days, and so I'm not sure anymore if I used PTVS 2.1 or the PTVS 2.2 pre-releases with VS 2013.  I can actually re-install VS 2013 alongside VS 2015, but I'm just tied up with a lot of work, and so if you can't see any obvious errors, I can try it next week.  I'm appending a simple piece of code that should launch a firefox browser and go to cnn.com  (I'm not sure why the Python indentation gets destroyed once I post. It looks ok in the edit form)., Thanks again:
===
import unittest, time
from selenium import webdriver



class Test_test1(unittest.TestCase):
    def test_A(self):
        driver = webdriver.Firefox()
        base_url = "http://www.cnn.com"
        driver.get(base_url)
        time.sleep(10)
        driver.quit()
        
if __name__ == '__main__':
    unittest.main()

**Comment by scm1970** [comment]
Sure. I'm appending a bare bones script that I just wrote. It runs fine as a standalone script but is not launching through VS 2015 Professional. I did a lot of cleaning up the last few days, and so I'm not sure anymore if I used PTVS 2.1 or the PTVS 2.2 pre-releases with VS 2013.  I can actually re-install VS 2013 alongside VS 2015, but I'm just tied up with a lot of work, and so if you can't see any obvious errors, I can try it next week.  I'm appending a simple piece of code that should launch a firefox browser and go to cnn.com  (I'm not sure why the Python indentation gets destroyed once I post. It looks ok in the edit form). Thanks again:

===
import unittest, time
from selenium import webdriver



class Test_test1(unittest.TestCase):
    def test_A(self):
        driver = webdriver.Firefox()
        base_url = "http://www.cnn.com"
        driver.get(base_url)
        time.sleep(10)
        driver.quit()
        
if __name__ == '__main__':
    unittest.main()

**Comment by zooba** [comment]
I edited your comment to format the code - hit Edit yourself to see what I did.

Looking at the code, I can't see anything obvious, but I haven't had a chance to get set up and try running it myself yet.

**Comment by crwilcox** [comment]
I tested this on Windows 10 with Visual Studio 2015 and PTVS 2.2 and Python 3.5 - 32 bit.  I made a virtual env with just pip (7.1.0), setuptools (18.0.1), and selenium (2.47.0)

The test worked for me without issue.  That being said, the first time I was given a security prompt to see if I would open the network for python.  Until I clicked that it didn't start the test.

Is there a chance you didn't notice the prompt?  I nearly did as it popped up on a different monitor.

**Comment by scm1970** [comment]
Thanks. I tried again, but it still didn't work for me. I have Python 3.4.2 64 bit. I'm not sure if that makes a difference. I'll try to do this in the next day or two on a virtual machine with my configuration. If it works, then there's probably some issue with my VS 2015 install process.
