### ISSUE TITLE
An error message pops up when creating a new project "From Existing Python code"

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6621]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/127270738-5e49bc69-d78b-4b3e-b3c0-b33a6088ba0e.png)

**Steps to Reproduce**
1. Launch VS and select File > new > Project.
2. In the New Project dialog, select "From Existing Python code".
3. Click "Create".
4. Observes

**Expected behavior**
Create a project without any error.

**Actual result and screenshots**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/127273085-e03b73e8-5b7a-4456-9d2f-4d23a0eef9e5.png)

**Comment by bschnurr** [comment]
I think there was a previous bug related to this around a year ago. it was platform related last time.

**Comment by rchiodo** [comment]
@linette-zyy I don't get this error myself on the latest bits from main.

Can you run VS with the '/log' command line and paste your activity log here?

More information:
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019

**Comment by rchiodo** [comment]
Oh no it shows up after I close the dialog that we use.

**Comment by rchiodo** [comment]
This might be we need a package update. Might be throwing the wrong exception in our import wizard

```
D:\Source\PTVS\packages\Microsoft.VisualStudio.TemplateWizardInterface.17.0.0-previews-1-31325-097\lib\net472\Microsoft.VisualStudio.TemplateWizardInterface.dll
```
That's the package that has the WizardCancelledException

**Comment by rchiodo** [comment]
Otherwise I don't see how this has changed since D16. It should have had this same problem as all of the code is the same.

**Comment by rchiodo** [comment]
Updating IWizard implementation has no effect on this issue. Logging an internal bug.

**Comment by rchiodo** [comment]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1092785

**Comment by rchiodo** [comment]
Actually this one:
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1364472

**Comment by judej** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PTVS-Pylance-573ddf64cd9225ae72c86a34/issues/microsoft/PTVS/6621?planning-poker) with ZenHub @bschnurr

**Comment by judej** [comment]
Resolved in Preview 4
