### ISSUE TITLE
When debug any test on test explorer in my python solution I get "Path to debug adapter executable not specified."

### ISSUE THREAD

**Issue by greazer** [microsoft/PTVS#6626]
[severity:It’s more difficult to complete my work]

I have WIndows 10, Microsoft visual studio 2019, and 2022 Preview 1. Launching a debug test on test exploer for a python solution it says

Failed to launch debugger adapter. Path to debug adapter executable not specified.

My settings- >

Microsoft Visual Studio Community 2022 Preview

Version 17.0.0 Preview 2.0

VisualStudio.17.Preview/17.0.0-pre.2.0+31512.422

Microsoft .NET Framework

Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   17.0.303.37752

ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.0.303.37752

Azure App Service Tools v3.0.0

C# Tools   4.0.0-2.21362.3+5f7ddf6f02d40036fdbf823cd9910027da277acd

C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10

Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.21175.2

Provides tools for finding, instantiating and customizing templates in cookiecutter format.

NuGet Package Manager   6.0.0

NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0

ProjectServicesPackage Visual Studio Extension Detailed Info

Python - Django support   17.0.21175.2

Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.21175.2

Profiling support for Python projects.

Python with Pylance   17.0.21175.2

Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

TypeScript Tools   17.0.0701.2001

TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-2.21362.3+5f7ddf6f02d40036fdbf823cd9910027da277acd

Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0

Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by greazer** [comment]
Let's try to repro.

**Comment by rchiodo** [comment]
This is working for me in the latest bits (Preview 3)

![image](https://user-images.githubusercontent.com/19672699/127715946-6113c070-52b3-40c7-909e-f55e9a46e4a9.png)
