### ISSUE TITLE
The Signature help appears twice

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6627]
**Describe the bug**
![image](https://user-images.githubusercontent.com/82852072/127445500-ef677402-b498-4079-8b12-da63eeaf47ee.png)

**Steps to Reproduce**

1.  Create empty c++ project named myexttest and add module.cpp

```
#include "Python.h"

static PyObject* AddTwoInteger(PyObject* Self, PyObject* Argvs)
{
	int Argv1(0), Argv2(0);
	if (!PyArg_ParseTuple(Argvs, "ii", &Argv1, &Argv2))
	{
		return 0;
	}

	return PyLong_FromLongLong(Argv1 + Argv2);

	
}

static PyMethodDef ModulesMethods[] =
{
	{ "Add", AddTwoInteger, METH_VARARGS, "Add Two Integers!" },
	{ NULL, NULL, 0, NULL }
};

static struct PyModuleDef ModuleDesc =
{
	PyModuleDef_HEAD_INIT,
	"AddTwoValue_Module",
	"This module is created by C++. And it Add two Integers!",
	-1,
	ModulesMethods
};

PyMODINIT_FUNC PyInit_myexttest(void)
{
	return PyModule_Create(&ModuleDesc);
}
```
2. Create Python Application project, add c++ project cppextcode as reference
3. Add code from  myexttest
  
```
import myexttest
print(myexttest.Add(10, 10))
```

**Expected behavior**

The Signature help of print just appears once. 

**Actual behavior**

By the way, I restart the VS and can repro this.

![image](https://user-images.githubusercontent.com/82852072/127445423-96c0295a-c31d-4f10-a2e0-68e6065a1ff9.png)

**Comment by rchiodo** [comment]
This would likely be in the LanguageServer.Client dll (not in PTVS). It puts up this UI.

**Comment by rchiodo** [comment]
Created a bug on the language server here:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1362812

**Comment by ttSpace** [comment]
@rchiodo This can repro in today's build. You can try to write a few more times **print** to repro this. 

![image](https://user-images.githubusercontent.com/82852072/129671616-1725f9cd-67b9-4fb4-b3b9-319ef45fdacb.png)

![image](https://user-images.githubusercontent.com/82852072/129670991-f66a8ca3-60cc-483c-a941-bb0c37e439d2.png)

**Comment by rchiodo** [comment]
@ttSpace this issue is being tracked here:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1362812

It should be a bug in VS proper as we don't provide the UI for that.

**Comment by matteo-prosperi** [comment]
@ttSpace, I am not able to reproduce this. Could you leave some detailed repro steps on https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1362812 or, even better, take a short screen capture video when you reproduce the issue?
Thanks a lot!
