### ISSUE TITLE
Failed to create "GitHub->cookiecutter-flask/cookiecutter-flask" template in Cookiecutter.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6628]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/127810493-d32f2a4c-dffe-4bee-aec2-6e89f41cff48.png)

**Steps to Reproduce**

1. Launch VS
2. Click "View->Cookiecutter Explorer"
3. Select "GitHub->cookiecutter-flask/cookiecutter-flask" to click "Next"
4. Wait for load successfully and then click "Create and Open Folder"

**Expected behavior**

It should create successfully.

**Additional context and screenshots**

Error occurs when create template.

![image](https://user-images.githubusercontent.com/82852072/127810851-f61ab4b1-699c-4342-83f3-8c2f17b438a1.png)

**Error detail info**
```
----- Creating files using template 'cookiecutter-flask/cookiecutter-flask' -----
DEBUG main.py: context_file is C:\Users\vting\.cookiecutters\cookiecutter-flask\cookiecutter.json
DEBUG generate.py: Context generated is {'cookiecutter': OrderedDict([('full_name', ''), ('email', ''), ('github_username', ''), ('project_name', ''), ('app_name', ''), ('project_short_description', ''), ('use_pipenv', ''), ('python_version', ''), ('node_version', ''), ('use_heroku', '')])}
DEBUG utils.py: Making sure path exists: C:\Users\vting/.cookiecutter_replay/
DEBUG find.py: Searching C:\Users\vting\.cookiecutters\cookiecutter-flask for the project template.
DEBUG find.py: The project template appears to be C:\Users\vting\.cookiecutters\cookiecutter-flask\{{cookiecutter.app_name}}
DEBUG generate.py: Generating project from C:\Users\vting\.cookiecutters\cookiecutter-flask\{{cookiecutter.app_name}}...
DEBUG generate.py: Rendered dir  must exist in output_dir C:\Users\vting\AppData\Local\Temp\85d45923-8a2b-44be-97f7-3883dda14121
Traceback (most recent call last):
  File "c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\cookiecutter\cookiecutter_run.py", line 46, in <module>
    sys.exit(int(main() or 0))
  File "c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\cookiecutter\cookiecutter_run.py", line 37, in main
    cookiecutter(
  File "C:\Users\vting\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\main.py", line 140, in cookiecutter
    return generate_files(
  File "C:\Users\vting\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\generate.py", line 264, in generate_files
    project_dir = render_and_create_dir(
  File "C:\Users\vting\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\generate.py", line 211, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "C:\Users\vting\AppData\Local\Temp\85d45923-8a2b-44be-97f7-3883dda14121" directory already exists
C:\Users\vting\AppData\Local\Microsoft\CookiecutterTools\env\scripts\python.exe returned an exit code of 1.
----- Failed to create files using template 'cookiecutter-flask/cookiecutter-flask' -----

```

**Comment by rchiodo** [comment]
I think this would be a bug in the template code and should probably be logged there?

**Comment by rchiodo** [comment]
Logged a while ago: #6390

**Comment by rchiodo** [comment]
Yeah I get this is I do this more than once. The user has to specify a new directory here before creating:

![image](https://user-images.githubusercontent.com/19672699/127915122-f4525422-90a6-4131-91fc-45c78a6882e6.png)

Or delete the old folder.

**Comment by ttSpace** [comment]
@rchiodo But it was the first time I click "Next" >" Create", it's that suppose to happen?

**Comment by rchiodo** [comment]
Are you sure this directory doesn't exist from a previous test?

**Comment by ttSpace** [comment]
@rchiodo You can see this can repro in today's build. I just launch the VS and do this.

![动画1](https://user-images.githubusercontent.com/82852072/128126537-dcf7cf98-b73f-43a9-81a0-412d5ee5cd70.gif)

**Comment by rchiodo** [comment]
Yes that will happen if the directory already exists on your machine. Did you install on a completely fresh machine?

Before you run anything, verify that the `<user>\source\repos\cookiecutter-flash` directory doesn't exist.

**Comment by ttSpace** [comment]
@rchiodo Yeah, I install on a completely fresh machine and select that template, then click "Next" >" Create" (You  can see that "Installed" section has nothing at first)

**Comment by rchiodo** [comment]
Need to try and repro myself.

**Comment by rchiodo** [comment]
Repos on completely fresh machine. Logged this issue here:
https://github.com/cookiecutter-flask/cookiecutter-flask/issues/1183
