### ISSUE TITLE
Profiler doesn't like UTF8 BOM

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#663]
Example output of what happens when your startup file has a BOM and you start profiling:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio - Profil
ing\2.2\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio - Profil
ing\2.2\vspyprof.py", line 56, in profile
    code = compile(f.read(), file, 'exec')
  File "C:\Projects\Azure\DatasetReader\DatasetReader.py", line 1
    ï»¿import os
            ^
SyntaxError: invalid character in identifier
Press any key to continue . . .
```

**Comment by zooba** [comment]
We should use `tokenize.open` where possible, or the runner helpers from the debugger.

As part of a debugger refactor, we may be able to improve overlap with the profiler.

**Comment by ariccio** [comment]
I hit this too:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio - Profiling\2.2\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio - Profiling\2.2\vspyprof.py", line 56, in profile
    code = compile(f.read(), file, 'exec')
  File "C:\Users\Alexander Riccio\Documents\GitHub\Golf-Analyzer\GolfAnalyzer.py", line 1
    ï»¿'''
      ^
SyntaxError: invalid character in identifier
Press any key to continue . . .
```


*Sidenote*: You're not using a `with open(file, "r") as f:` context manager in `vspyprof.py`?:

```
            f = open(file, "r")
            code = compile(f.read(), file, 'exec')
```

Eh? Is that a ancient-version-of-python-compatibility thing?

**Comment by zooba** [comment]
Yes, we support back to Python 2.5 (which wasn't quite as ancient when that code was first written), and so we can't assume the `with` statement is available.

It should certainly be in a try/finally though...

**Comment by ariccio** [comment]
Wow, I didn't realize that PTVS was that old! ...but [the docs appear to say that the `with` statement is supported in 2.5?](https://docs.python.org/2.6/reference/datamodel.html#context-managers)

Also a side note: How many PTVS users actually use Python *2.5*?

**Comment by zooba** [comment]
It's available, but requires the use of a `__future__` import. Not sure why we don't just use that, but IIRC there was some issue we encountered (it predates me :) ).

I suspect not many use Python 2.5 at this stage, but since we don't have to do much to keep supporting it we just keep it around.

**Comment by ariccio** [comment]
Ahh OK, that makes sense.

I see that the fix is committed. When will it be available as an update?

**Comment by zooba** [comment]
About the same time as VS 2015 Update 1 (though it'll be available for both VS 2013 and VS 2015, and we'll release a dev build and an RC sooner than that).

**Comment by zooba** [comment]
That said, it's a pure-Python change (other than the test), so if you click through to the commit you can copy the contents of the Python files into your installed files and get the fix straight away.
