### ISSUE TITLE
Changing search path from project properties doesn't update solution explorer

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6631]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/127823037-dd1775a1-ded4-4a90-872e-ac0a4b67e6ca.png)

**Steps to Reproduce**

Right click project, properties
In debug tab, set a valid search path, and save.
In solution explorer, the Search Paths node isn't updated
If I clear the "Search Paths" in debug tab, and save, In solution explorer, the Search Paths node isn't updated too, the cleared path is still in SE.

Note: The reverse works fine, if you add a search path through solution explorer it immediately updates in the debug tab.

**Comment by greazer** [comment]
Not a regression from Dev 16, so not going to fix. Thanks for entering it though.
