### ISSUE TITLE
Refactor rename incorrect when the referenced method is defined in another project. 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6638]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/127970584-aebfacea-6601-4cf4-b0d1-c83134bdc0cd.png)

**Steps to Reproduce**

1. Create python application named PythonAppication1
2. Create python application named PythonAppication2
3. Right-click in PythonAppication1 and select Add->reference..., select PythonApplication2 as referenced
4. Typing code in PythonApplication2.py
```
def add(a, b):
    print(a + b)
```
5. Typing code in PythonAppication1.py
```
import PythonApplication2
PythonApplication2.add(1,2)
```
6. Open PythonApplication2.py and select function name add and right-click to select rename...
7. Input a new name **addTest** in rename dialog and press enter

**Expected behavior**

The name add can be renamed as addTest both in PythonApplication2.py and PythonApplication1.py

**Actual behavior**

Nothing has changed.

**Comment by rchiodo** [comment]
Very weird. Only repros with the cross project reference. Otherwise rename works fine.

**Comment by ttSpace** [comment]
In today's build ```17.1.0 Preview 3.0 [32030.14.main]``` , The name of the place where this method is called has not changed.

**Comment by linette-zyy** [comment]
In today's build 17.2.0 Preview 2.0 [32228.339.main].In the same project, rename a method, but the method name of this method in other places where it is called has not changed
![image](https://user-images.githubusercontent.com/59192491/156128800-10945fdf-9788-4c10-b8b9-d7a589e4a63f.png)
![image](https://user-images.githubusercontent.com/59192491/156129065-aca2c7fe-0260-4e50-8828-cc836b7a5031.png)
![image](https://user-images.githubusercontent.com/59192491/156128910-02bc2fec-bd38-4b69-ac8c-cb221925ea37.png)

**Comment by AdamYoblick** [comment]
The original bug is reported for two projects, with one referencing the other. But the latest screenshots show this is broken for two files in the SAME project. We need to investigate and fix both of these cases if they still repro.

**Comment by AdamYoblick** [comment]
@ttSpace Can you please verify if this is still happening on the latest version of Visual Studio? For both single project and multiproject cases. Thank you!

**Comment by ttSpace** [comment]
@AdamYoblick In today's build ```17.6.0 Preview 2.0 [33406.287.main]```, Python Package: ```17.0.23033.1```, In two Projects, Renamed only in PythonApplication2.py. The name of the place where this method is called has not changed. ```foo --> footest```

![image](https://user-images.githubusercontent.com/82852072/217132184-a70ec93e-1817-4f1b-8037-ab1ec7ae3938.png)

This works fine for the two files in the SAME project. ```foo --> footest```

![image](https://user-images.githubusercontent.com/82852072/217130245-341b5c23-3728-457c-a035-95bb8182ba77.png)

**Comment by linette-zyy** [comment]
In today's latest build:**17.7.0 Preview 2.0 [33709.378.main]**,Python package:**17.0.23115.2**
In two Projects, the 'rename' command doesn't have any responce after selecting it
![rename](https://github.com/microsoft/PTVS/assets/59192491/ec008d29-4ee4-4d74-93a7-d3c06fb844e1)

**Comment by StellaHuang95** [comment]
@linette-zyy I was trying to repro this issue, how did you find the other project to add as reference? Mine shows nothing was found.
![image](https://github.com/microsoft/PTVS/assets/100439259/a6647dba-c719-499a-b5e5-f5074ade454a)
