### ISSUE TITLE
Excute File in Python Interactive -- wrong location and always appears

### ISSUE THREAD

**Issue by Andrew-MSFT** [Microsoft/PTVS#664]
1.       P1: Can we move the location below the "core debugging" items group (e.g. give it its own menu group below the “Profiler section” (or just add it to the Profiler section below the Profiler item)
2.       P2: Only have it appear if the Python editor is open.  A lot of developers who may not be Python users will just choose “install everything” so this will reduce visual clutter for them.

**Comment by zooba** [comment]
@Andrew-MSFT For 1, how about immediately above "Other Debug Targets"? I really feel this command needs to stay within IDG_EXECUTION (since it triggers execution).

#2 is easily done.

**Comment by Andrew-MSFT** [comment]
Sure, above "Other Debug Targets" works
