### ISSUE TITLE
Execute project in interactive displays error "The interactive window has not yet started." 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6640]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/127976100-b0bb0fc0-09ae-45aa-a765-ce161dc1a0ab.png)

**Steps to Reproduce**

1. Start VS, ensure there are no interactive windows open. (restart VS as necessary)
2. Create a new project
 ```
print('hello world')
```
3. Debug->Execute Project in Python Interactive

**Actual behavior**

It works, but there is red text (usually a sign of an error) that says "The interactive window has not yet started."

![image](https://user-images.githubusercontent.com/82852072/127976959-ef916a57-fe3c-45ad-89a9-f344180f6713.png)

**Comment by rchiodo** [comment]
Dev 16 (VS 2019) has this same problem. I don't think we're going to fix this.
