### ISSUE TITLE
Send to interactive does nothing if previous send to interactive didn't advance to next line

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6641]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/127980423-9268de55-e121-4dc7-bc80-7a29af22e55c.png)

**Steps to Reproduce**

1. Create new python application
Enter the following code, make sure your editor confirms there are only 2 lines (NO new line chars at the end of line 2)
```
import math 
e = math.e
```
2. Place cursor at beginning of line 1 > CTRL + E, CTRL + E
Result: Line 1 executed, cursor at the beginning of line 2
3. CTRL + E, CTRL + E
Result: Line 2 executed, cursor remains at the beginning of line 2
CTRL + E, CTRL + E (because you want to execute line 2 again)
Result: Nothing happens
Workaround: Move cursor up then down, and then CTRL + E, CTRL + E will work.

![image](https://user-images.githubusercontent.com/82852072/127981350-18c86b62-8cd1-4f6f-894f-9e0179ac0f60.png)

I think this is by design, so that if you just keep hitting CTRL + E, CTRL + E it will eventually stop when you reach the end of the file, instead of keep on executing the last line.

The problem is that there's no visual difference between the 2 states: first time it works, second time it doesn't, despite the location of cursor being the same.

Another workaround is to have a new line at the end of your file, but that won't help when you use code cells, since no amount of new lines at the end will make it advance past the last cell, and you won't be able to re-execute the last cell without moving the cursor first.

![image](https://user-images.githubusercontent.com/82852072/127982592-419e1976-a7d4-4590-aee1-251a1966ac4e.png)

**Comment by rchiodo** [comment]
Thanks for the issue. I don't think we're going to change this.
