### ISSUE TITLE
Python type hint break syntax highlight in Visual Studio 2022

### ISSUE THREAD

**Issue by greazer** [microsoft/PTVS#6653]
From: https://developercommunity.visualstudio.com/t/Python-type-hint-break-syntax-highlight-/1493478

Looks as though we need to update our textmate language grammar. VS Code doesn't repro this and they do the same thing.

**Comment by rchiodo** [comment]
Here's where this code exists:
https://dev.azure.com/devdiv/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor%2FTextMate%2FVSWindows%2FSetup%2FStarterkit%2FExtensions%2Fpython%2Fsyntaxes%2FPython.tmLanguage&_a=contents&version=GBmain

**Comment by int19h** [comment]
And here's the upstream version:
https://github.com/textmate/python.tmbundle/blob/master/Syntaxes/Python.tmLanguage

**Comment by Cozy-69** [comment]
sorry i didn't quite understanding what's going on is there a fix for this issue?

**Comment by rchiodo** [comment]
There is not a fix for the issue yet. We believe the problem lies in the tmlanguage file VS ships for Python.

**Comment by rchiodo** [comment]
This is pending insertion by the editor team of their latest bits.

**Comment by StellaHuang95** [comment]
duplicate of #6782
