### ISSUE TITLE
Squiggles does not go away automatically when installed pytest successfully in Test Explorer.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6657]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/128454595-b2f36f69-0183-4bc6-bdda-527b8cb54371.png)

**Steps to Reproduce**

1. Open a New Folder/ Create a Python Application in VS
2. Add new python item namad test_pt.py
3. Typing code in test_pt.py
```
import pytest
@pytest.fixture(params=[0, 1, 3])
def data_set(request):
    return request.param

def test_data(data_set):
    assert data_set != 3
```
4. Install pytest in current environment

**Expected behavior**

Pytest should be installed successfully and the squiggles in test_pt.py for import pytest should go away automatically.

**Additional context and screenshots**

Successfully installed 'pytest', but the squiggles in test_pt.py did not go away. If I unload and reload the python project  (close the folder and reopen it ), the squiggles will go away. 

![image](https://user-images.githubusercontent.com/82852072/128454960-d2b821bf-820c-40cd-a8c9-843da691d73b.png)

**Comment by linette-zyy** [comment]
This issue also can reproduce on 16.11.
![image](https://user-images.githubusercontent.com/59192491/128493155-16534d97-f111-421e-af3a-308b19de36c9.png)
![image](https://user-images.githubusercontent.com/59192491/128493316-13f92acd-6719-48a9-b8f4-c4a7d3cdb8d6.png)

**Comment by rchiodo** [comment]
Oh this is a known issue with pylance. The file system watchers are not currently turned on because they slow everything down.

**Comment by rchiodo** [comment]
Yeah this issue here:
https://github.com/microsoft/pylance-release/issues/923
