### ISSUE TITLE
Newbie basic question: trouble setting PTVS up properly

### ISSUE THREAD

**Issue by PiNewbie** [Microsoft/PTVS#666]
Hello. First of all I'm sorry if the question shouldn't belong here or it has already been answered, I haven't found another post about this issue yet (and sorry for my bad english). I'm all new here, trying to learn more about Python. Maybe someone had the same problem before and has an idea how I could  manage to solve it.
I have some trouble setting up PTVS in Visual Studio 2013 ultimate.
First of all I installed the recommended 32-bit Python-interpreter (http://go.microsoft.com/fwlink/?LinkID=299430), and after that I added PTVS 2.2.

When starting VS I get an error message saying, that the python tools package did not load correctly and to see the ActivityLog for more details (situated in C:/Users/Username/AppData/Roaming/Microsoft/VisualStudio/12.0/ActivityLog.xml).
(Unfortunately the attached Screenshot is in german).
![errormessagevs](https://cloud.githubusercontent.com/assets/13614454/9027862/abcd8922-3965-11e5-897d-643d400cc15f.PNG)

In the ActivityLog, the following events are highlited.
![errorvs](https://cloud.githubusercontent.com/assets/13614454/9027856/78129136-3965-11e5-8d5c-8a702d174ba3.PNG)

I tried several things, as removing and reinstalling the interpreter and PTVS or repairing VS or installing several VS Updates, but nothing helped.

Has anyone any suggestion how i could solve this issue?
Thank you all in advance and best regards

**Comment by zooba** [comment]
These are fairly tricky to solve, unfortunately.

First, I would make sure you have the latest update for VS 2013 (should be update 5). After installing that, repair PTVS (or uninstall, delete the [install directory](https://github.com/Microsoft/PTVS/wiki/Where-is-PTVS-installed), then reinstall).

If you are still having trouble, we'll need to attach a debugger while loading and see what exceptions are occurring, but let's make sure the install is okay first.

**Comment by PiNewbie** [comment]
Hi Zooba, thanks for your answer.

I already have update 5, and tried repairing and reinstalling PTVS several times.

Sounds quite complicated to find the exception, i think it will be easyer to use another software  to code in python then.
