### ISSUE TITLE
In vs17.0.0 Preview 2.1 python settings, there is a masking problem with the display of Debug/Display Variables

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6667]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/vs1700-Preview-21--python设置中，调试显示变量/1499561)._

---
[regression] [worked-in:17.0.0 Preview 2.1]
! [捕获. PNG](https://aka.ms/dc/image?name=Bf812df3409024bef8f6da03b94075b46637642437864161075_%E6%8D%95%E8%8E%B7.PNG&tid=f812df3409024bef8f6da03b94075b46637642437864161075)

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
![image](https://user-images.githubusercontent.com/19672699/129110326-a0dfc6bd-82eb-4537-8946-b7221eeb681c.png)

**Comment by rchiodo** [comment]
Localization issue. Don't hardcode width of columns.
