### ISSUE TITLE
Django migrations and creating super user causes VS to hang

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6668]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Django-migrations-and-creating-super-use/1493240)._

---
[severity:It's more difficult to complete my work]
In a new Django web project template project, doing a right click on the project > python > Django check (Django >= 1.7) causes VS to get stuck in a not responding state.
The same happens for the options:
Django Make Migrations (Django >= 1.7)
Django Migrate... (Django >= 1.7)
Django Create Superuser (Django >= 1.7)

This is using 64 bit Python 3.9. Using the same project with the same Python install works fine in VS 2019 when using these same features.

---
#### Feedback Bot on 8/3/2021, 01:28 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/3/2021, 06:54 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
Need to investigate the hang

**Comment by rchiodo** [comment]
I'm not reproing this. It works fine. Perhaps this was fixed by the changes to start an environment.

**Comment by rchiodo** [comment]
@linette-zyy can you try? 
- Install VS 2022 with Python 3.9
- Create Django web project
- Click on the project menu like so
![image](https://user-images.githubusercontent.com/19672699/129284396-cebb5960-3820-4ba5-bb94-36f367d91058.png)

Does VS hang?

**Comment by linette-zyy** [comment]
@rchiodo I try on the lasted build.
![image](https://user-images.githubusercontent.com/59192491/129322019-a540f117-222c-43fc-89bf-bd1bdbe452aa.png)
The VS hang on.
![image](https://user-images.githubusercontent.com/59192491/129322168-919d05c3-3166-493a-b8ce-28ca4606d775.png)

Here is the event log.
[Event log.zip](https://github.com/microsoft/PTVS/files/6980711/Event.log.zip)

**Comment by rchiodo** [comment]
Thanks. I retried on a new machine. Finally got the hang.

Here's the callstack of the hang:

 	Microsoft.PythonTools.dll!Microsoft.VisualStudioTools.UIThread.InvokeTaskSync<Microsoft.VisualStudio.InteractiveWindow.ExecutionResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.InteractiveWindow.ExecutionResult>> func, System.Threading.CancellationToken cancellationToken) Line 228	C#
>	Microsoft.PythonTools.dll!Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(Microsoft.VisualStudio.InteractiveWindow.IInteractiveEvaluator evaluator, Microsoft.VisualStudio.Utilities.IContentType contentType, bool alwaysCreate, int id, string title, System.Guid languageServiceGuid, string replId) Line 303	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateTemporary(string replId, string title) Line 223	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreateTemporary(string replId, string title, out bool wasCreated) Line 211	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Project.CustomCommand.RunInRepl(Microsoft.PythonTools.Project.IPythonProject project, Microsoft.PythonTools.Project.CommandStartInfo startInfo) Line 635	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Project.CustomCommand.ExecuteWorker(Microsoft.PythonTools.Project.PythonProjectNode project) Line 466	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Project.CustomCommand.ExecuteAsync(object parameter) Line 271	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Project.PythonProjectNode.ExecuteCustomCommandAsync(Microsoft.PythonTools.Project.CustomCommand command)	C#
 	Microsoft.PythonTools.dll!Microsoft.PythonTools.Project.PythonProjectNode.ExecCommandIndependentOfSelection(System.Guid cmdGroup, uint cmdId, uint cmdExecOpt, System.IntPtr vaIn, System.IntPtr vaOut, Microsoft.VisualStudioTools.Project.CommandOrigin commandOrigin, out bool handled) Line 1418	C#
 	Microsoft.PythonTools.dll!Microsoft.VisualStudioTools.Project.ProjectNode.InternalExecCommand(System.Guid cmdGroup, uint cmdId, uint cmdExecOpt, System.IntPtr vaIn, System.IntPtr vaOut, Microsoft.VisualStudioTools.Project.CommandOrigin commandOrigin) Line 193	C#
 	Microsoft.PythonTools.dll!Microsoft.VisualStudioTools.Project.ProjectNode.Exec(ref System.Guid guidCmdGroup, uint nCmdId, uint nCmdExecOpt, System.IntPtr pvaIn, System.IntPtr pvaOut) Line 531	C#
