### ISSUE TITLE
Exception from HRESULT: 0x80070057 (E_INVALIDARG)

### ISSUE THREAD

**Issue by kjersth** [microsoft/PTVS#6670]
**Describe the bug**
Popup window with "An unexpected error occurred" appears at several occasions. 
Most of the time when trying to open .py-files, but also at launching VS.

Related bug: #6305 

**Steps to Reproduce**
Case 1)
1. Open Visual studio 
2. Try to open a *.py file
3. Popup window with "An unexpected error occurred"
4. The file is opened after closing the dialog.

Case 2) 
1. Open VS
2. Loading project

**Message in the pop up dialog:**
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.11.21196.2

System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.ConfigurationManager.get_ActiveConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<TriggerInfoBarsAsync>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Diagnostics file**
Sent via e-mail

**Comment by greazer** [comment]
@kjersth, we're not able to reproduce this problem. We tried using the repro steps with bug #6305, but still didn't repro. If you can find the steps to make it occur, we'll take another look.

**Comment by calonx** [comment]
Sharing my repros, since they've been 100% for me (out of 3-4 tries).

[Repro 1 steps]

1. Launched new instance VS 2022 with `.sln` specified on cmd line
2. For reference: no documents open; '.sln' has mostly C++ projects with a couple of Python projects; Solution Explorer is visible with a Python project already expanded.
3. Double-click `.py` file in Solution Explorer
4. Observe "unexpected error" dialog

[Repro 2 steps]

1. Continue from Repro 1 (after dismissing error-dialog)
2. Close VS 2022 with `.py` document still open
3. Launch VS 2022 as in Repro 1
4. Observe "unexpected error" dialog immediately with no additional user interaction

> [Window Title]
> devenv.exe
> 
> [Main Instruction]
> An unexpected error occurred
> 
> [Content]
> Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.
> 
> [V] Show details  [Close]
> 
> [Expanded Information]
> ```
> Build: 17.0.21344.1
> 
> System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
>    at EnvDTE.ConfigurationManager.get_ActiveConfiguration()
>    at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
>    at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
>    at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
>    at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PythonTools.Project.PythonProjectNode.<TriggerInfoBarsAsync>d__103.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
> ```
