### ISSUE TITLE
An error pops up when run "Django Check, Django Migrate, Django Create Superuser...".

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6673]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/129514721-1804a4cf-5ea2-412a-a1d3-d994e5fdbf86.png)

**Steps to Reproduce**
1. Create a Django  Web Project
2. In solution explorer, right click on project and
- Python, make migrations >= 1.7
- Python, migrate >= 1.7
- Python, Django Create Superuser >= 1.7		
- Python, collect static files 
- Python, Django check >= 1.7

**Additional context and screenshots**
An error message pops up.
![image](https://user-images.githubusercontent.com/59192491/129515372-1e68d7b4-959f-4f89-b4a1-16e588c2e3db.png)

**Comment by rchiodo** [comment]
This should be fixed when this pr goes through: #6668

**Comment by rchiodo** [comment]
Fixed by https://github.com/microsoft/PTVS/commit/47f84749249bcd9fd7c17b1415252a1f8deb875a
