### ISSUE TITLE
An error pops up when open Property page.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6674]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/129669211-278b984e-c266-4689-bfb6-0288d0ac9ffa.png)

**Steps to Reproduce**
1. Create a new python application
2. Go to open Property page
![image](https://user-images.githubusercontent.com/59192491/129669683-7283ab3c-2b7b-48e5-a124-c40a0dabb3ae.png)

**Actual result**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/129670066-5f25a202-98eb-440d-9f59-d6eb3daef7e5.png)

![image](https://user-images.githubusercontent.com/59192491/129669786-55811182-aabe-454a-a173-0eaf5ffb398a.png)

**Comment by linette-zyy** [comment]
When create a C++ project, the Property page is opened successfully.
![image](https://user-images.githubusercontent.com/59192491/129670834-dc2d92e8-0913-40d7-85cf-d1b9cf197f94.png)

**Comment by rchiodo** [comment]
I can repro. Caused by some update to the shell. Probably need to return a guid from the python project system somewhere.

**Comment by rchiodo** [comment]
This issue is caused by this bug here:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1374647
