### ISSUE TITLE
native debugging pythoncode, when looking for source, the dialog uses the wrong file type, so i can't choose the source file even the file is there

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6678]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/native-debugging-pythoncode-when-lookin/1501095)._

---
! QQ Screenshot20210812105838 .jpg) (https://aka.ms/dc/image?name=B6911a869c6804756acaf2cf4f53a3f3d637643339275577560_QQ%E6%88%AA%E5%9B%BE20210812105838.jpg&tid=6911a869c6804756acaf2cf4f53a3f3d637643339275577560)

---
#### Feedback Bot on 8/12/2021, 02:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
When we produce the call stack, we report filenames for stack frames according to what Python itself reports (`f_code.co_filename`, to be specific). This particular frame corresponds to source code that is not executed from the file directly, but rather loaded into a string and evaluated as such, hence why it has the dummy filename like that.

However, VS itself has the limitation that, when it tries to locate the source code for a frame that you double-click, it expects the filename to match. This is not something that we control, unfortunately.

When we implement https://github.com/microsoft/PTVS/issues/6610, I think it could be used to map such dummy filenames as needed. Until then, there's nothing we can do about it.
