### ISSUE TITLE
The method "Add" is prompted not defined when create a C++ extension for Python.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6679]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/130025250-5c9cc554-4667-49a1-ad77-18e281725c63.png)

**Steps to Reproduce**
1. Create empty c++ project named myexttest and add 3.9 - module.cpp
	a. Go to property page:
	b. Set configuration to All Configurations and Platform to Win32
	c. Set specific properties as described in the following, then select OK
	-   i. General > Target name: leave the default value of $(ProjectName)
	-   ii. General > Target Extension: .pyd
	-   iii. General > Project Defaults > Configuration Type: Dynamic Library (.dll)
	-   iv. C/C++ > General > Additional Include Directories: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_86\include
	-   v. C/C++ > Preprocessor > Preprocessor Definitions: Py_LIMITED_API; to the beginning
	-   vi. C/C++ > Code Generation > Runtime Library: Multi-threaded DLL (/MD)
	-   vii. Linker > General > Additional Library Directories: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_86\libs
	d. Build the c++ project and ensure success both debug and release
	e. Add the method code to C++ project’s module.cpp file
	f. Build the c++ project and ensure success both debug and release
	g. Ensure that superfastcode.pyd is generated
2.  Create Python Application project, add c++ project myexttest as reference
	a. Set active Python Environment with Python 3.9 (32-bit)
	b. Ensure that ..\Debug or ..\Release is added in Search Paths
	c. Add code from myexttest
	d. from myexttest import *
	e. print(Add(1,1))
	f. In project property page, checked "Enable native code debugging" 
	g. Right-click the Python project in SE and select "Set as Startup Project"
3. Ctrl + F5 to run the python project

**Actual result**
The method "Add" with red wavy line and prompt not defined. But  the project can be launched.
![image](https://user-images.githubusercontent.com/59192491/130025446-2aaed00f-5a8f-4b2a-9537-37c48e60bdae.png)
![image](https://user-images.githubusercontent.com/59192491/130025028-91f40a51-a5a6-4599-b1ef-40bba49a82b5.png)

**Pylance Output**
```
Info: Info: Pylance language server 2021.4.1 (pyright 6410a8a2) startingServer root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist

Info: Info: Warning: Info: Info: Info: Info: Info: Info: Setting pythonPath for service "PythonApplication1": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_86\python.exe"No configuration file found.stubPath C:\Users\vyizh12\source\repos\myexttest\PythonApplication1\typings is not a valid directory.Assuming Python version 3.9Assuming Python platform WindowsSearching for source filesFound 1 source fileBackground analysis(1) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\distBackground analysis(1) started
```

**Comment by rchiodo** [comment]
This is by design. Pylance won't know about the C++ references.
