### ISSUE TITLE
Editor status message is incorrect - does not match error list status

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6680]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/130195703-31cf6448-ae2f-4813-bba4-d95b39455b7b.png)

**Steps to Reproduce**
1. Create a python application
2. Type print("hello"
3. Check the prompt info

**Additional context and screenshots**
The prompt info says 1 issue, but there were 2 errors in Error List.
![image](https://user-images.githubusercontent.com/59192491/130195891-0be6025c-439d-40bf-bf45-b2eb10bc3e5b.png)

**Comment by linette-zyy** [comment]
And the warning also does not match.
![image](https://user-images.githubusercontent.com/59192491/130196310-2d644969-f1fc-4fc4-ba2a-157f30d674b3.png)

**Comment by rchiodo** [comment]
This is by design. Reference assembly errors are extra and don't show up in the file. They're related to the project. C#/WPF does this same thing.
