### ISSUE TITLE
Cannot use IPython interactive mode on python3.9

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6682]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/130404698-798e2556-faf7-4f52-a73b-f857799c10a7.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Install "IPython" and "ipykernel" package on Python3.9 environment.
3. Open "Python Environments" window->"Overview" page to enable "Use Ipython interactive mode".
4. Open interactive window to type ```print("hello")```

**Expected behavior**

It should switch to IPython interactive mode.

**Additional context and screenshots**

The interactive window was hung.

![image](https://user-images.githubusercontent.com/82852072/130405283-ed266269-f4da-49cd-b601-6432b6145b2e.png)

After restarting VS, I got this. And I typed  ```print("hello")```, it was still hung.

![image](https://user-images.githubusercontent.com/82852072/130405776-244c7220-2cec-4ca4-a325-1f408e78f9c2.png)

**Comment by ttSpace** [comment]
I can repro in today's build ```17.1.0 Preview 3.0 [32015.214.main]  ```

**Comment by ttSpace** [comment]
In toady's build ```17.1.0 Preview 3.0 [32030.14.main]``` , Python install from Microsoft Store.

**Comment by bschnurr** [comment]
seems to be working now
Version 17.3.0 Preview 3.0 [32607.526.main]
