### ISSUE TITLE
After deleting and re-creating, conda env will not appear in the list.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6683]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/130408446-47eb1835-6bf0-404c-ab12-98747665ef91.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Create a conda environment. (Install Anaconda (downloads at https://www.anaconda.com/download/) if no Anaconda )
3. Close the VS and go to ```C:\ProgramData\Anaconda3\envs```, then delete the env.
4. Launch VS and open the Python Application.
5. Prompt to create and click **Create environment**

![image](https://user-images.githubusercontent.com/82852072/130409597-ab005934-0542-4cc2-9d33-6b117d96d56d.png)

6. The conda env is create successfully. But it doesn’t appear in the list.

![image](https://user-images.githubusercontent.com/82852072/130410133-080cb4bb-0ea8-4404-acb2-3db845b693d8.png)

7. You can add an existing env to show it.

![missing_conda_env](https://user-images.githubusercontent.com/82852072/130411042-76885499-a63c-4471-b47e-1a0f3f3b0855.gif)

**Output info**

```
Info: Info: Pylance language server 2021.4.1 (pyright 6410a8a2) startingServer root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist

Info: Info: Warning: No configuration file found.Setting pythonPath for service "PythonApplication10": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe"Info: Info: Info: stubPath C:\Users\vting\source\repos\PythonApplication10\PythonApplication10\typings is not a valid directory.

Assuming Python version 3.9Assuming Python platform WindowsInfo: Info: Info: 
Searching for source files

Found 1 source fileBackground analysis(1) startedBackground analysis(1) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist



Info: No configuration file found.
Info: Warning: Info: Setting pythonPath for service "PythonApplication10": "C:\ProgramData\Anaconda3\envs\env5\python.exe"Info: stubPath C:\Users\vting\source\repos\PythonApplication10\PythonApplication10\typings is not a valid directory.Assuming Python version 3.9
Assuming Python platform Windows


Info: Searching for source files
Info: Found 1 source file
```

**Comment by rchiodo** [comment]
Might be related to #6686

**Comment by ttSpace** [comment]
I can repro this in today's build ```17.2.0 Preview 1.0 [32110.307.main]```.

**Comment by StellaHuang95** [comment]
Seems related to #6715

**Comment by judej** [comment]
@StellaHuang95 is this a dupe? If so, could you close the newer one?

**Comment by StellaHuang95** [comment]
@judej No the other one is a separate issue.

**Comment by StellaHuang95** [comment]
That should be fixed. See https://github.com/microsoft/PTVS/pull/7603
