### ISSUE TITLE
Failed to Run Tests and Debug Test from Solution Explorer window.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6685]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/130575373-b5e5fc9c-fafa-4e6f-8c61-55aba085eb8f.png)

**Steps to Reproduce**
1. Set breakpoints in the test which you want to debug
2. In SE, right-click to select Debug Selected tests
3. Check that breakpoints are hit
![image](https://user-images.githubusercontent.com/59192491/130576074-10ed2006-214e-48d9-a866-7464f6328c3f.png)

**Actual result**
Failed to Run Tests and Debug Test from Solution Explorer window.
On Test output window， it show No tests found to run.
![image](https://user-images.githubusercontent.com/59192491/130576322-0e52e553-4afc-47cc-9e4e-39f96c3b4677.png)

**Comment by linette-zyy** [comment]
On the latest build
![image](https://user-images.githubusercontent.com/59192491/147813636-d718b3d9-7187-4371-846b-dabf5d5eb37c.png)
This issue also can reproduce.

**Comment by StellaHuang95** [comment]
Can't repro in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 2.0 [32601.540.main]. Please reopen the ticket if the issue persists.
