### ISSUE TITLE
just opening a python file displays build errors that cannot be cleared

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6693]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/just-opening-a-python-file-displays-buil/1512453)._

---
I'm working on data project mix of .py and CSharp.  .py are mostly load/ETL scripts, CSharp for APIs.  I use VSCode for .py editting, Visual Studio 2022 for CSharp.  If I just open the .py file in VS 2022 it displays build errors, but when closing the .py file the build errors never clear.  How do I clear errors from Python language service or tell it I'm not working on that file?  The file was never an "item" in the CSharp solution I have open.  Can I tell Python lang service to disable while I have CSharp solution open?

---
#### Feedback Bot on 8/24/2021, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
We can't seem to repro this problem. Can you include a sample project and a loose py file that repros the problem? Thanks.
