### ISSUE TITLE
Bug editing python code in code editor

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6694]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug-editing-python-code-in-code-editor/1512110)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:Version 17.0.0 Preview 3.1]
If there is a line break on multiple lines using \, the vertical line display will be corrupted.
Also, compared to vs2019, there is no function to set colors such as python functions with the set font and color.

---
#### Feedback Bot on 8/24/2021, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment]
Need to see who is responsible for providing the outline. Does pylance provide the regions for this back to VSLanguageServerClient?

**Comment by StellaHuang95** [comment]
Hi, could you please provide a code snippet or a GIF of the issue you're seeing, that would better help us diagnose the issue😊

In terms of the fonts and colors, you can go to Tools -> Environment -> Fonts and Colors and set it up there. Let us know if you have additional questions. Thanks.

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
