### ISSUE TITLE
Test Explorer do not find pytest files

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6695]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Test-Explorer-do-not-find-pytest-files/1492923)._

---
I create a new Django project. Then I create test files in different folders in the project but not all test_*.py files are found by the test explorer. In some cases they are fond once so I can run the once but then they disappear right before my eyes in the Test Explorer.

---
#### Feedback Bot on 8/2/2021, 06:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi, could you provide a code snippet or a GIF of the issue you're experiencing? :blush:

Additionally, here is a [link](https://devblogs.microsoft.com/python/whats-new-for-python-in-visual-studio-16-3-preview-2/) that might be helpful for enabling and configuring tests in VS. Thanks.

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
