### ISSUE TITLE
After adding the file as a link first, the file will not be added to the project.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6697]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/130910285-661aa8b1-c2f0-4bad-9954-c7fc089a6b2a.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Right click on the project and select Add > Existing Item …
3. In the prompts dialog, select the item you want to add.( **PythonApplication10** )
4. Click the Add drop-down and select "Add As Link".
5. Right click on the project and select Add > Existing Item …
6. Select **PythonApplication10** that you chose before, and select "Add". (You can repeat step 5 and step 6)

**Expected behavior**

After selecting an item "Add As Link" , the item **PythonApplication10** should be "Add" in project.

**Additional context and screenshots**

More than one appeared in SE.( **PythonApplication10** Status is "Add As Link" ) And the file **PythonApplication10** is not in the directory.

![image](https://user-images.githubusercontent.com/82852072/130912085-cc87aba5-f021-430d-8487-85d39d95ef46.png)

![image](https://user-images.githubusercontent.com/82852072/130918452-ac8baa7d-eb5e-4615-a30d-51974a18469f.png)

Restart VS, you can see that there is only one. Then, repeat step 5 and step 6, it can repro this.

![image](https://user-images.githubusercontent.com/82852072/130912617-d1650afd-18f0-48a9-8c37-c62bfb951ae3.png)
![image](https://user-images.githubusercontent.com/82852072/130913268-34b374ec-88e3-4a1f-ae0f-a173df6b8f43.png)

**Output info**
```
Info: Info: Pylance language server 2021.4.1 (pyright 6410a8a2) startingServer root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist

Error: Warning: Info: Info: Info: Info: Error reading settings: TypeError: Cannot read property '0' of nullstubPath typings is not a valid directory.Assuming Python platform WindowsSearching for source filesNo source files found.Background analysis(1) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist





Info: Background analysis(1) started
Info: Info: Warning: Info: Info: Info: Info: Info: Info: No configuration file found.Setting pythonPath for service "PythonApplication12": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe"stubPath C:\Users\vting\source\repos\PythonApplication12\PythonApplication12\typings is not a valid directory.Assuming Python version 3.9Assuming Python platform WindowsSearching for source filesFound 1 source fileBackground analysis(2) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\distBackground analysis(2) started

```

**Comment by ttSpace** [comment]
In today's build ```17.1.0 Preview 3.0 [32029.61.main]```, I can repro this.

**Comment by StellaHuang95** [comment]
@ttSpace Does this still repro? I can't add duplicate projects.
![image](https://user-images.githubusercontent.com/100439259/221019546-56971992-b1c2-4bd9-bb72-c3fc8600c589.png)

**Comment by ttSpace** [comment]
@StellaHuang95 I can repro in today's build ```17.6.0 Preview 2.0 [33423.321.main]```, Python Package: ```17.0.23047.1```. 

![Animation](https://user-images.githubusercontent.com/82852072/221114789-cbadc61a-a8d1-4976-8b35-f98435991599.gif)

**Comment by StellaHuang95** [comment]
This will be fixed once the pr is finished here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/455205
