### ISSUE TITLE
It will have completions even if "Add PYTHONPATH to search path" is not selected.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6698]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/130927989-0102b98b-4b1f-4562-81b5-9a58852ca2c0.png)

**Steps to Reproduce**

1. module2.py file was prepared with below code.
```
def hello(): print('hello')
```
2. Add the module2.py path to PYTHONPATH.

![image](https://user-images.githubusercontent.com/82852072/130929325-e12233fe-bae6-408b-9aa7-c0f339a05042.png)

3. Launch VS and create a Python Application.
4. In the default python file type **import module2**.

**Expected behavior**

It should not have intelliSense of **module2** untill you select "Add PYTHONPATH to Search Path".

![image](https://user-images.githubusercontent.com/82852072/130929644-ea26def4-b2ce-4c81-b2f1-c13139755736.png)

**Additional context and screenshots**

It has completions on **module2**.

![image](https://user-images.githubusercontent.com/82852072/130930680-8c6fcbe2-784c-4ff1-83ad-7b6ab6c25666.png)

![image](https://user-images.githubusercontent.com/82852072/130930486-9d56f0fb-d836-4bbf-bb27-580592ad8d7f.png)

**Output info**
```
Info: Info: Pylance language server 2021.4.1 (pyright 6410a8a2) startingServer root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist

Info: Info: Warning: Info: Info: Info: Info: Info: Info: No configuration file found.Setting pythonPath for service "PythonApplication23": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe"stubPath C:\Users\vting\source\repos\PythonApplication23\PythonApplication23\typings is not a valid directory.Assuming Python version 3.9Assuming Python platform WindowsSearching for source filesFound 1 source fileBackground analysis(1) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\distBackground analysis(1) started

```

**Comment by rchiodo** [comment]
This may be a pylance issue?

**Comment by rchiodo** [comment]
Might be setting this in the workspace config.

**Comment by ttSpace** [comment]
I can repro this in today's build.

![image](https://user-images.githubusercontent.com/82852072/131794642-690c94f8-92d6-417d-9419-cfe74dcb5cef.png)

**Output info**
```
Info: Info: Server root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\distPylance language server 2021.8.3 (pyright fa4194fd) starting

Info: No configuration file found.Info: 
No pyproject.toml file found.
Info: Setting pythonPath for service "PythonApplication9": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe"Warning: 
stubPath C:\Users\vting\source\repos\PythonApplication9\PythonApplication9\typings is not a valid directory.Info: 
Assuming Python version 3.9
Info: Info: Info: Info: Info: Assuming Python platform WindowsSearching for source filesFound 1 source fileBackground analysis(1) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\distBackground analysis(1) started
```

**Comment by AdamYoblick** [comment]
Pylance respects PYTHONPATH and automatically finds modules there. So this is "as designed" since we now use pylance. @judej Should we just get rid of the action "Add PYTHONPATH to Search Path"?

**Comment by int19h** [comment]
Note that not picking up `PYTHONPATH` by default for Intellisense was also very much intentional, hence why the command exists. @zooba might remember why it was done that way.
