### ISSUE TITLE
python enviroment DB refresh fails in  2.2 RC 2013.

### ISSUE THREAD

**Issue by tashia** [Microsoft/PTVS#67]
I am setting Enthought Canopy python enviroment as default. But DB refresh is not able to complete when i am using 2.2 beta. I rolled back to 2.1, it is working. Hope it could get fixed.
Thanks

**Comment by zooba** [comment]
Firstly, could you try with [2.2 RC](https://github.com/Microsoft/PTVS/releases/tag/v2.2-rc), which we released just last week. We fixed some major issues to do with this compared to 2.2 Beta.

If that still has trouble, could you post the contents of Tools, Python Tools, Diagnostic Info from within VS as a gist or email it to ptvshelp@microsoft.com. There are logs in that file that will help us diagnose the problem.
