### ISSUE TITLE
Build Python project always in up-to-date state.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6710]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/132434898-101a0021-2a66-4613-98eb-287f31611b9a.png)

**Steps to Reproduce**
1. Create a new Black Django Web Project 
2. Create a virtual environment for this project
3. In solution explorer, right click on project and click Build.

**Expected behavior**
The Django project build successfully.

**Additional context and screenshots**
In build output window show the project build in up-to-date state, can not finish.
![image](https://user-images.githubusercontent.com/59192491/132435241-22336f5d-2d6c-4a25-b2c1-963911a8b5e5.png)

**Comment by ttSpace** [comment]
Click button **Run All Tests In Views** from Test Explorer, then pop up the build window. And the build window cannot be completed.
Build of Visual Studio: 17.0.0 Preview 5.0 [31726.38.main] 
Build of Python Package: 17.0.21264.5 

![Alwaysbuild](https://user-images.githubusercontent.com/82852072/134860937-92747939-a8e0-4987-84c1-9ef94f3ba60b.gif)

**Comment by bschnurr** [comment]
couldnt' repo with `Version 17.0.0 Preview 5.0 [31726.67.main]

open project mode?

**Comment by bschnurr** [comment]
closing at can't repo
