### ISSUE TITLE
When creating a git repository for the first time, you cannot click the "Create and Push" button.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6714]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/132639690-118fd20b-da73-4b70-a293-2a5d6297391d.png)

**Steps to Reproduce**
1. Create a Python Application.
2. Click the button ```Add to Source Control```.
![image](https://user-images.githubusercontent.com/82852072/132639971-cb42ac5e-3847-408b-b4af-dd24fd385434.png)
3. Sign in your account.

**Expected behavior**

You can click "Create and Push".

**Additional context and screenshots**

When logging in for the first time, this button cannot be clicked. You need to reopen this window to click.

![Screenshot 2021-09-09 151603](https://user-images.githubusercontent.com/82852072/132640836-68292e8c-23b9-4d6c-8763-7e873112a1ca.png)

![image](https://user-images.githubusercontent.com/82852072/132640460-1f2727ca-e6d8-4fed-93a3-25cb49f39a91.png)

**Comment by judej** [comment]
This problem is unrelated to Python. Would you please create an issue from the VS "Send Feedback" option?
https://developercommunity.visualstudio.com/report?space=8&entry=problem

![image](https://user-images.githubusercontent.com/547753/132704085-673ecb1f-ce20-48ec-a96c-44a1b82ab17a.png)

**Comment by ttSpace** [comment]
Create an issue in : https://developercommunity.visualstudio.com/t/when-creating-a-git-repository-for-the-first-time/1527452?from=email
