### ISSUE TITLE
An error message "This project "PythonApplication3" has a reference to a missing Conda environment "env3"" always pops up when restart the VS.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6715]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/132807285-58a5f8f9-8996-4be6-b945-a3571371bbd9.png)

**Steps to Reproduce**
1.  Create a new Python application
2.  Right click Python Environment --> Add Environment to create a Conda environment
3.  Close the VS and restart the VS
4.  Open the project 
5. Observes

**Expected behavior**
The Conda environment list in the Python Environment without any error.

**Actual result**
An error message "This project "PythonApplication3" has a reference to a missing Conda environment "env3"" always pops up
The Conda enviroment does not list in the Python Environment.
![image](https://user-images.githubusercontent.com/59192491/132807926-bf7e3d5b-1ea7-426f-b974-824d85ea35aa.png)

**Comment by AdamYoblick** [comment]
@linette-zyy Does this still repro?

**Comment by linette-zyy** [comment]
@AdamYoblick 
I can repro this in today's latest build:**17.6.0 Preview 1.0 [33402.156.main]**,Python Packages:**17.0.23033.1**
![missingconda](https://user-images.githubusercontent.com/59192491/216503118-f3d697c9-601d-4513-b4ee-81231519b03a.gif)

**Comment by StellaHuang95** [comment]
@linette-zyy Does this still repro? I can't repro it now.

**Comment by AdamYoblick** [comment]
This shouldn’t repro anymore with my async conda env detection fix. Please let me know if it does.
________________________________

**Comment by StellaHuang95** [comment]
Thanks, I am going to close it then. Please reopen if it repros.
