### ISSUE TITLE
Missing package check doesn't understand flask requirements

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6717]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/132808720-07743d24-abdb-47ca-90d2-d296c6112534.png)

**Steps to Reproduce**
1. Create new flask web project
2. Create virtual conda env like below:
![image](https://user-images.githubusercontent.com/59192491/132808850-45ce7703-c4c7-430b-b79d-784ba1bc7fb7.png)
3. Close project
4. Reopen project

**Expected behavior**
Without any error.

**Actual result**
Info bar prompt that there are missing packages. This is not true, the info bar should not appear.
It doesn't work for this flask requirements:
`Flask<1.1`
![image](https://user-images.githubusercontent.com/59192491/132808640-bc6dc51b-bfa1-41c8-b7e1-33b856f0733a.png)

**Comment by StellaHuang95** [comment]
The versions in requirements.txt have been fixed, but this issue could also be caused by #6715 if the conda env is not detected when reopening VS.
