### ISSUE TITLE
Poor Django support in  VS 2022 Enterprise preview

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6730]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Poor-Django-support-in--VS-2022-Enterpri/1528854)._

---
when i create Django project from Visual Studio, i found that the template tags are still version 1.x of Django, so i can't use it to create Django projects.

---
#### Feedback Bot on 9/14/2021, 07:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, could you try upgrading to the latest version of VS and see if that fixes your problem? We currently have django==2.2.28 specified in the requirement.txt when creating a Django project from the Django web project template. Thanks.😊

**Comment by StellaHuang95** [comment]
Going to close this out. Please reopen the ticket if the issue still persists. Thanks😊

**Comment by gabrielking1** [comment]
we have django 4.1 already still stuck at django 2.2.28
