### ISSUE TITLE
"The reference assemblies for .NETFramework,Version=v4.0 were not found" appeared in Python project.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6733]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/134838610-30f6de3f-98c5-4d01-9d7e-f4d430c7c8c5.png)

**Steps to Reproduce**

Create a Python Application project.

**Expected behavior**

It should be created successfully without any errors.

**Additional context and screenshots**

An error appears in the error list.

![image](https://user-images.githubusercontent.com/82852072/134838861-57936b5d-c73a-41e0-994a-d5c256681739.png)

**Comment by bschnurr** [comment]
couldn't repro.
`Version 17.0.0 Preview 5.0 [31726.67.main] `

**Comment by ttSpace** [comment]
@bschnurr hi, I can repro in today's build.

![image](https://user-images.githubusercontent.com/82852072/135375026-b27464d3-f716-4ffd-a034-c21b8bddfb55.png)

**Installation details**

![image](https://user-images.githubusercontent.com/82852072/135374680-65e755b2-2924-43e6-a38e-01afed84020b.png)

**Comment by AdamYoblick** [comment]
Dupe of #6747
