### ISSUE TITLE
openssl.exe has security vulnerability

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6741]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/opensslexe-has-security-vulnerability/1544429)._

---
Our corporate security PC has scanned my PC with the latest version of VC2019 on and reported that C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64\Library\bin\openssl.exe has a security vulnerability. I checked and it is version 1.1.1c. They say it should be upgraded to at lease 1.1.1l. Can you please arrange for this to be upgraded in a release?

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Graham's released statement says we're not fixing old versions of the Python Interpreter, the users need to move up to a more recent version of VS. That being said, the MiniConda component isn't the same as the CPython interpreter, and this is a real security vulnerability, so we might have to fix it. Follow up with Graham for guidance.

**Comment by StellaHuang95** [comment]
Going to close this out as the VS2019 bundled miniconda is labeled as out-of-support so we are not providing full support on security updates.
