### ISSUE TITLE
I can't analyze my code in Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6744]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Не-удается-произвести-анализ-кода-в-Pyth/1546928)._

---
When you select From the Analyze-Execute Code Analysis-In Solution for a Python Program menu, the results are displayed in the window

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, could you provide some more details about the issue you're experiencing? Repro steps or screenshots would really be helpful. Thanks.😊

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks😊
