### ISSUE TITLE
I couldnt import rpa as r into my visual studio community edition program.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6745]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-couldnt-import-rpa-as-r-into-my-visual/1538237)._

---
How to go about it? Already prior install python and javascript installers within the visual studio.

Would like to have TagUI integration into this program. 

Can rpa be used only on python? Or can it be done on javascript as well?

when i write the command : import rpa as r
--> it indicate as unresolved import 'rpa' when i place my cursor onto the 'rpa' variable

---
#### Feedback Bot on 9/24/2021, 00:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
