### ISSUE TITLE
Selection of Python Environment is not persisted in VS 16.11.2

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6746]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Selection-of-Python-Environment-is-not-p/1528933)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.4.2]
Global/default Python environment reverts to Base conda upon every restart of VS. If a different conda environment is made a global default, it is forgotten. If a different Python environment is selected (and saved) in the individual Python project settings they do show up upon restart, but VS still uses the global default, ie, the base conda environment. Moreover, there is a discrepancy -- the settings page shows the desired environment that has been saved, but the project view in Solution Explorer does show the global default, ie the base conda, and this is the one that is used. Even saving the explicit interpreter path in debugging tab of the project is ignored. Selecting a different environment in the project settings _does_ work, however,  if it is done _manually_ --  if it comes from the .pyproj file, it will be ignored. 

Incidentally, the base conda is the only project that is  visible in Windows registry. Otherwise, it is not even on the path -- it is not intended to be used in our projects at all. Also, removing the base conda from the ~/.conda/environments.txt does not change anything. Why isn't VS relying on this file, giving the user some control, rather than scouring the system for every environment imaginable? Is there a way to _hide_ a Python environment from VS? That would be very helpful.

The problem started after upgrading from VS 16.4.2 to the current 16.11.2

---
#### Feedback Bot on 9/14/2021, 07:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen. thanks
