### ISSUE TITLE
The Python version is display wrong when use the latest python to create Conda environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6749]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/136507160-352310db-4e44-4b86-9168-30e69a4e195b.png)

**Steps to Reproduce**
1.  Create a Python project
2.  Right click Python Environments -> Add Environment -> Conda environment
3.  Choose the latest python version to create
![image](https://user-images.githubusercontent.com/59192491/136508142-1e4be4f5-c2d2-420f-8ab9-69b8dfc9b0e1.png)
4. Click Create button
5. Observes

**Expected behavior**
The environment is created successfully and display without aby error.

**Additional context and screenshots**
The Python version is display wrong when use the latest python to create Conda environment.
It displayed Python0.0, it should display Python 3.10
![image](https://user-images.githubusercontent.com/59192491/136509460-f53e2f7f-650b-4040-8b49-01b5256c2277.png)

**Comment by linette-zyy** [comment]
This issue also occurred on Dev16
![image](https://user-images.githubusercontent.com/59192491/136645200-002fa6cc-c74e-4ff5-962d-1a75fcca6111.png)

**Comment by linette-zyy** [comment]
@AdamYoblick 
This issue also can reproduce on the latest build.
![image](https://user-images.githubusercontent.com/59192491/156517063-1b1e175c-d0bb-4fb2-8234-f7f9bc6bcb17.png)
I try to create Conda environment and modify the python version.
Choose Python 3.10 and Python(latest)
![image](https://user-images.githubusercontent.com/59192491/156517204-3f951d2a-5d9c-49a8-b37f-7bbc08336c4c.png)
After create successfully, it still display "python 0.0"
![image](https://user-images.githubusercontent.com/59192491/156517466-ba30147f-ffe4-491c-96d6-494c13bcbfce.png)

**Comment by AdamYoblick** [comment]
> The way it retrieves the version for non-root Conda environments is by printing out `sys.version_info` and then parsing that back on VS side:
> 
> https://github.com/microsoft/PTVS/blob/114a3c8e9503e392385a88f1003d90cbc6ea851e/Python/Product/VSInterpreters/Interpreter/CondaEnvironmentFactoryProvider.cs#L346
> 
> https://github.com/microsoft/PTVS/blob/114a3c8e9503e392385a88f1003d90cbc6ea851e/Python/Product/VSInterpreters/Interpreter/CPythonInterpreterFactoryProvider.cs#L166-L181
> 
> So yes, this error would also break that.
> 
> These types of errors from Conda usually indicate that it has been executed without [activating it properly](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment).
> 
> Now, previously, I have only seen this when importing some module that had a native dependency - so you could still run `python.exe` directly without activation. So the original logic for version detection did work.
> 
> It appears that, with Python 3.10, this is no longer the case, and the zlib dependency is directly from the DLL. So for 3.10+, `python.exe` in non-activated Conda environments is unusable. We'll either need to run the version-retrieval script in an activated environment, or figure out some other way of determining the version.

I looked into this more and I found a way to get the python version from a conda environment without activating it, but it requires a few more steps.

1. Run `conda list -n <env_name>` where `<env_name>` is the name of the environment.

This will output something like this:
```
# packages in environment at C:\Users\advolker\Miniconda3\envs\env:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                he774522_0
ca-certificates           2022.2.1             haa95532_0
certifi                   2020.6.20          pyhd3eb1b0_3
libffi                    3.4.2                h604cdb4_1
openssl                   1.1.1m               h2bbff1b_0
pip                       21.2.4          py310haa95532_0
python                    3.10.0               h96c0403_3
setuptools                58.0.4          py310haa95532_0
sqlite                    3.37.2               h2bbff1b_0
tk                        8.6.11               h2bbff1b_0
tzdata                    2021e                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2             py310haa95532_2
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h8cc25b3_4
```

2. Parse this output, looking for the line that starts with `python`. The python version is on the same line (3.10.0 above).

**Comment by AdamYoblick** [comment]
@bschnurr Graham asked me to send the pylance issue your way, but this PR is broken right now because I pushed up code just to save my work, and it doesn't compile. Once I finish working on my p0 work, I'll get this PR in a healthy state, merge it in, then create separate issues for the debugger and pylance problems with 3.10 in conda and send you the pylance one 😄

**Comment by bschnurr** [comment]
sure thing.

**Comment by bschnurr** [comment]
got a popup when installing conda with python3.10 
![image](https://user-images.githubusercontent.com/1946977/159313123-dad24932-f377-4ed5-bc23-6283acee2689.png)

**Comment by AdamYoblick** [comment]
Yeah this is expected until the linked PR gets merged in. This is because we try to call into python.exe in the conda environment to determine the python version, and this call crashes because of a conda bug with 3.10.
