### ISSUE TITLE
Python automatically associated with the use of tab key to complement when an error occurred

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6751]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python-自动联想之后使用tab键进行补全的时候出现错误/1547679)._

---
[severity:It bothers me. A fix would be nice]
Sometimes automatic complement can not be associated, sometimes automatic association after the use of tab key to complement when there is an error. For more information, see the video
The code is as follows:

```
import datetime
print ('Current year:'str')
```
[2021-10-07-22-06-55.mp4] (https://aka.ms/dc/file?name=Bdefa1f61ed7a41a4995f11515d10d698637692126431676415_2021-10-07-22-06-55.mp4&tid=defa1f61ed7a41a4995f11515d10d698637692126431676415)
Visual studio 2019 version number used: 16.11.4

---
#### Feedback Bot on 10/8/2021, 03:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, could you verify if you are still experiencing the same issue on VS2022? Thanks! 😊

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks😊
