### ISSUE TITLE
Release notes for VS 17.0 GA

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#6753]
This is a super issue to track release notes for outstanding issues in this release. Please add your issue below if you have release notes to add.

- [x] #6713
- [x] #6736

**Comment by AdamYoblick** [comment]
@int19h @bschnurr @judej

**Comment by int19h** [comment]
We're not going to fix https://github.com/microsoft/PTVS/issues/6712 just yet, so it must be documented as missing, along with the workaround of running the project without debugging, and then attaching to it. Something like:

> Python mixed-mode debugging is not available in C/C++ projects. Native processes hosting Python can be debugged using Attach to Process.

The relevant docs are here: https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2019#enable-mixed-mode-debugging-in-a-cc-project

**Comment by AdamYoblick** [comment]
#6713 - This has to do with pylance not being able to see environment package updates. This will be fixed in a future release. Workaround is the close the .sln and re-open it, and pylance will re-evaluate the environment and see the newly added package.
