### ISSUE TITLE
[MSFT Internal] An exception of type AggregateException has been encountered.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6754]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/137438907-94892a2e-28d2-4e31-a987-999282204b05.png)

![image](https://user-images.githubusercontent.com/82852072/137441521-c0645572-7c5f-45b8-be6b-f31886307313.png)

**Steps to Reproduce**

1. Create a Flask Web Project. (For the first time create)
2. Click Create virtual environment.

**Additional context and screenshots**

An error pops up.

![image](https://user-images.githubusercontent.com/82852072/137439284-3f70a4fe-c672-4bc1-ae5c-cb0e909c2b05.png)

![image](https://user-images.githubusercontent.com/82852072/137439075-a20b2a19-8d72-4e24-b364-53efdc3119a2.png)
[ActivityLog.xml.txt](https://github.com/microsoft/PTVS/files/7351233/ActivityLog.xml.txt)

**Comment by judej** [comment]
closing not repro
