### ISSUE TITLE
Cant open files in the search results when using "Find All References"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6756]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-open-files-in-the-search-results-wh/1554697)._

---
[severity:I'm unable to use this version] [regression] [worked-in:2019]
I have a python project and when I use the "Find All References", I see a window with all the references but double clicking an entry doesn't open the file.... yet it shows me the file name, line number and column offset of the reference

---
#### Feedback Bot on 10/15/2021, 03:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/18/2021, 10:34 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by heejaechang** [comment]
I just tried this and I can't repro with the latest VS and pylance.

**Comment by heejaechang** [comment]
by the latest I mean, `VS Version 17.7.0 Preview 3.0` and `Pylance 2023.6.40`

**Comment by heejaechang** [comment]
it is because VS doesn't know how to handle `%3A` in 'file:///c%3A/xxx/PythonApplication2.py' in `Location.uri`

**Comment by olegtk** [comment]
I reactivated original feedback ticket and routed it to the VS Editor, feel free to close this one.
