### ISSUE TITLE
Evaluates all the expressions in interactive windows ignore the Completion Mode setting.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6760]
**Environment**
Build of Visual Studio: 17.1.0 Preview 1.0 [31818.287.main]
Build of Python Package: 17.0.21274.2
OS version: Windows 10 Enterprise 20H2

**Steps to Reproduce**
1.  Go to Tools -> Options ->Python -> Interactive Windows 
2. Set Completion Mode to "never evaluate expressions"
3. Input some code like below
![image](https://user-images.githubusercontent.com/59192491/137853102-7657be93-ad06-4495-9934-86a7d922990a.png)

**Expected behavior**
I typed '.' after x:  Ii should not print the message.

**Actual result**
Whenever which setting I choose, the messages are printed.
![image](https://user-images.githubusercontent.com/59192491/137853535-9de25718-b1d0-42d0-a9c3-56b1de422dcb.png)

**Comment by cwebster-99** [comment]
Thanks for the report. I am closing this in favor of https://github.com/microsoft/PTVS/issues/7979 as this appears to be settings UI related that we should clean up.
