### ISSUE TITLE
Unchecked "Parameter information" still has signature help.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6762]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/137884090-b641e787-99fc-478c-a292-7356263b6277.png)

Python 3.9 install from Microsoft Store
Windows 10 Enterprise, Version 2004

**Steps to Reproduce**

1. Create a Python Application.
2. Type
```
import decimal
decimal.Decimal()
```

**Expected behavior**

Disable signature help.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/137884884-9a8ebaf3-5625-40d6-ba11-f422b9bf0d70.png)

**Comment by ttSpace** [comment]
In today's build```17.1.0 Preview 3.0 [32030.14.main]```, Unchecked "Parameter information" still has signature help.

**Comment by ttSpace** [comment]
In today's build ```17.2.0 Preview 1.0 [32119.255.main]``.
Checked "Parameter information" .
![image](https://user-images.githubusercontent.com/82852072/150299963-2248b7c4-e16f-49d6-94da-099b15766110.png)

Unchecked "Parameter information" . 
![image](https://user-images.githubusercontent.com/82852072/150300446-e15c3e6e-b7dc-4d24-9cd0-c876a400f3a1.png)

**Comment by StellaHuang95** [comment]
@ttSpace Does the bug still repro? Seems like the signature help behaves differently now than what's originally described in the issue. Thanks!

**Comment by ttSpace** [comment]
@StellaHuang95 In today's build ``` 17.5.0 Preview 2.0 [33107.190.main] ```, Python Package: ```17.0.22305.8```, Checked and Unchecked "Parameter information" are the same.

![image](https://user-images.githubusercontent.com/82852072/200491919-cdcde776-93ca-4630-bd85-1d98754d6302.png)

**Comment by cwebster-99** [comment]
Thanks for the report. I am closing this in favor of #7979 as this appears to be settings UI related that we should clean up.
