### ISSUE TITLE
Live Share: Cannot enter the sharing window through the browser, and a warning appears when opened through VS.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6765]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/138224005-caf8770f-3353-4354-af11-e70ff78fff02.png)

Python 3.9 install from Microsoft Store
Windows-10-Enterprise-21H1

**Steps to Reproduce**

1.  Create a Python Application.
2. Click LiveShare and sign in.
3. Visual Studio Live Share Firewall Access, click Ok.
4. You should click allow access.
5. You will come to Visual Studio Live Share page. Click Copy invite link button.
6. Open this link in Explorer, then will be open the shared window , you can give your link to another one , so you can  connected with each other, you can see each other's screens, each other's actions and so on.

**Expected behavior**

Successfully joined Live Share Session.

**Additional context and screenshots**

It was hung.

![image](https://user-images.githubusercontent.com/82852072/138225044-9c473f08-c2b7-43d2-8315-997b77343c2e.png)

BTW, I tried to join using VS and then got this information.(Open VS->File-> Join Live Share Session… )

![image](https://user-images.githubusercontent.com/82852072/138226013-fca790ad-1f34-4a78-acaf-79ced58e5e66.png)

![image](https://user-images.githubusercontent.com/82852072/138227653-21b22ee2-360f-41db-97ac-e3ea15e01ecf.png)

**Comment by ttSpace** [comment]
In today's build, It was hung.

![image](https://user-images.githubusercontent.com/82852072/139629949-e8ec54c0-9685-48c5-a38a-1190c56bf3da.png)

**Comment by bschnurr** [comment]
17.1 seems to work

```
Microsoft Visual Studio Enterprise 2022
Version 17.1.0 [31905.22.main]
VisualStudio.17.Release.Int/17.1.0+31905.22.main
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

ASP.NET and Web Tools 2019   17.1.138.64313
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.1.138.64313
Azure App Service Tools v3.0.0

C# Tools   4.1.0-2.21552.10+7e31604720147bbcd64a0980f4f4bf0979e340fe
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Cookiecutter   17.0.21295.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python - Profiling support   17.0.21295.2
Profiling support for Python projects.

Python with Pylance   17.0.21295.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

TypeScript Tools   17.0.1029.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-2.21552.10+7e31604720147bbcd64a0980f4f4bf0979e340fe
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
```

**Comment by bschnurr** [comment]
17.0 worked for me too. 

do you have any custom liveshare settings?

**Comment by ttSpace** [comment]
@bschnurr hi, I just use the default liveshare settings.

**Comment by ttSpace** [comment]
I can repro in today's build ```17.1.0 Preview 2.0 [31911.256.main]```Completions, signature help, Go to definition does not work in client session.

![image](https://user-images.githubusercontent.com/82852072/141423518-f2ba3d37-0ecc-485f-bc7b-3c8983413c77.png)

**Comment by ttSpace** [comment]
In today's build ```17.1.0 Preview 3.0 [32008.164.main]``` , it cannot join the sharing window through the browser.

![image](https://user-images.githubusercontent.com/82852072/145350560-b49d5fb8-4679-4990-af12-8d0018fa7fd8.png)

**Comment by ttSpace** [comment]
In today's build ```17.1.0 Preview 3.0 [32030.14.main]``` , it cannot join the sharing window through the browser.

![image](https://user-images.githubusercontent.com/82852072/147811697-46536282-54df-4353-9286-7442616d3118.png)

**Comment by StellaHuang95** [comment]
Hi @ttSpace, I can't repro this, could you verify if the issue still exists on the latest build? Trying to clean up some old issues😊Thanks.

**Comment by ttSpace** [comment]
@StellaHuang95 I can't repro in today's build. I can join the session through the browser or the VS.

![image](https://user-images.githubusercontent.com/82852072/172793723-902e25e6-f277-49d1-8044-815a5e3ec186.png)
