### ISSUE TITLE
Using PTVS and Eclipse/PyDev simultaneous

### ISSUE THREAD

**Issue by bckspc** [Microsoft/PTVS#677]
I don't know where else to ask this. Is there a guide or a reference to have a PTVS project working together with PyDev?

I want to use PTVS for development but some developers use Linux+Eclipse/PyDev. I tried to create a VS solution and then create an eclipse project but the VS project stopped working.

Can someone provide a guide on how to do this? Or point me in the right direction?

Sorry if this is the wrong place to post this, but the discussions link on codeplex pointed here.

Thank you all

**Comment by zooba** [comment]
This is probably the best place to ask, but unfortunately the answer is no, there aren't any guides on how to do this.

The most difficult part about this should just be when files are added or removed - you'll have to manually update each project (or the next person who uses it will have to do it). I personally don't think this is such a big deal, as I have to do the same with cross-platform projects that have both a makefile and VS projects (specifically, CPython). Long term we'd love to remove the hardcoded list of files completely, but right now it isn't feasible.

I'm interested in how your VS project stopped working though. That should only happen if PyDev moves all of the Python files into another location. We deliberately avoid doing that to be able to work better with other IDEs, but they may not.

In this case, you may just need to manually modify your .pyproj file to add a `ProjectHome` property. This property is a relative path from the project's directory to the root of the source code (typically these are the same place, so it defaults to empty), and then everything we do will work against that directory (e.g. resolve files, search paths, virtual environments, etc.)
