### ISSUE TITLE
The Python editor always prompts that the specified parameter exceeds the valid range parameter name span

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6770]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python编辑器总是提示指定的参数超出有效范围参数名span/1559865)._

---
[severity:I'm unable to use this version]
I'm learning python, using the VS2019 and PY3.7 environments. Often encounter line breaks in python's text editor (cannot edit the next line), pressing enterer when I need to continue editing the next line of code prompts me to specify parameters that are out of range, parameter names span, such as screenshots, how to resolve?

---
#### Feedback Bot on 10/20/2021, 11:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi, we are sorry for the issue you are experiencing. Could you try upgrading to VS2022 and let us know if the issue still persists?

Alternatively, could you provide us a code snippet or a screenshot of the issue you're seeing? That would really helpful. Thanks.

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
