### ISSUE TITLE
The Python installed from Microsoft Store couldn't view installed packages when first use the environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6774]
**Environment**
Build of Visual Studio: 17.1.0 Preview 2.0 [31904.282.main]
Build of Python Package: 17.0.21295.2
OS version: Windows 11 Enterprise 21H2
Python install from Microsoft Store

**Steps to Reproduce**
1. Create a new python application
2. Expand the one Python Environment in "Python Environments" node
3. Check the package list

**Expected behavior**
All the packages should listed
![image](https://user-images.githubusercontent.com/59192491/140449102-613675c3-7637-4a8c-a643-30aebbdbd535.png)

![image](https://user-images.githubusercontent.com/59192491/140449065-b9258e19-e31a-4a3e-b67d-460678cb2069.png)

**Additional context and screenshots**
The Python installed from Microsoft Store couldn't view installed packages when first use the environment.
![image](https://user-images.githubusercontent.com/59192491/140449184-b0b352b6-9a5a-4a7c-bd86-2cf6494c92d0.png)
![image](https://user-images.githubusercontent.com/59192491/140449228-02ac926d-2d34-4dc7-94ed-28374fe768ad.png)

After I restart the VS, this issue is not reproduce.

**Comment by linette-zyy** [comment]
This issue also can reproduce on today's environment.
![image](https://user-images.githubusercontent.com/59192491/141723441-7b9deba7-3add-4d7d-b329-9fe71304a439.png)
![image](https://user-images.githubusercontent.com/59192491/141723427-f757e6d6-4a98-4a25-b031-abaa1bfaf75c.png)
After restart the VS, we can view installed packages.

**Comment by StellaHuang95** [comment]
I can't repro this. @linette-zyy Could you verify this again on the latest build?

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/172799541-7c47b33f-f8ae-47aa-a545-7402fceef478.png)
@StellaHuang95 In today's build, I can't repro this when install packages(requests) in the 'Packages(PyPI)' search box
![install_from_MS](https://user-images.githubusercontent.com/59192491/172800551-50423c7a-fb6b-4bf1-aedc-91b5f950fabd.gif)
But i can repro this  when install packages(requests) in the command line
![install_from_MS_commandline](https://user-images.githubusercontent.com/59192491/172800960-2f7abdfc-3e89-4544-8e84-202937e16ac1.gif)

**Comment by AdamYoblick** [comment]
Could be a race condition which might make repro'ing tricky.

**Comment by ttSpace** [comment]
In today's build ```17.6.0 Preview 2.0 [33501.332.main]```, Python Package: ```17.0.23055.1```, ```pip install requests``` can be updated but ```pip uninstall requests``` no update. (Python installed from the Microsoft Store)

![image](https://user-images.githubusercontent.com/82852072/222350846-1013047d-3f22-4992-85d7-1a18d34c6348.png)
