### ISSUE TITLE
Mixed-mode debugging doesn't work

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/PTVS#6777]
I believe there's been another regression, identical to https://github.com/Microsoft/PTVS/issues/3611 but for visual studio 16.11.5.

> Create new python application
Project settings/debug/enable native code debugging
Set interpreter to Python 3.6
Write some code and put breakpoints
Start debugging
>
>Result: VS goes to debugging mode and app runs, but doesn't stop at breakpoints. Breakpoint icon says it won't be hit because symbols haven't been loaded.

Not exactly identically because 32 bit version doesn't work either this time.

**Comment by int19h** [comment]
Can you check if debug symbols were loaded for `python*.dll` for the interpreter you're trying to use? Debug -> Windows -> Modules will show this for all the DLLs in the process.

**Comment by tom-huntington** [comment]
```
'python.exe' (Win32): Loaded 'C:\Users\a\source\repos\PythonApplication1\PythonApplication1\env\Scripts\python.exe'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
The thread 0x4924 has exited with code 0 (0x0).
The thread 0x3e20 has exited with code 0 (0x0).
```

No `python*.dll` was loaded. The symbol status for `python.exe` is `Cannot find or open the pdb file`

I'm not sure what's happening because python's successfully calling my dll https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio, but visual studio didn't log that it was loaded.

**Comment by int19h** [comment]
Judging by the path to interpreter, there's a virtual environment involved, so you must be hitting https://github.com/microsoft/PTVS/issues/5623#issuecomment-523390563.

**Comment by tom-huntington** [comment]
Thanks, it works without the virtual environment
