### ISSUE TITLE
When vs2022 edits python formatting Chinese strings are garbled

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6785]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/vs2022-编辑python进行格式化的时候中文字符串会乱码/1577322)._

---
When vs2022 edits python formatting Chinese strings are garbled
I did the path operation when I edited the python code with vs2022 The file name contains Chinese
Then I formatted parts of the python file using CTRL-K, CTRL-D Chinese, and the characters in the python file became garbled

---
#### Feedback Bot on 11/10/2021, 00:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Are you able to provide a repro for this please? Maybe a snippet or a file demonstrating the issue?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by zzzmfps** [comment]
Version: VS 2022 17.1.1
Formatter: All (autopep8, yapf, black)

It works fine only if formatters are not needed at all (statements are already formatted). Otherwise unformatted lines will be garbled.

```
list1 = ['1', '2']  # normal without Chinese characters
list2 = ['一', '二']  # works fine if statement is already formatted

list3 = ['一','二']  # if misses a whitespace, for example
# formatter will garble the statement and even produce a syntax error:
# list3 = ['涓€', '浜?]
```

**Comment by AdamYoblick** [comment]
@StellaHuang95 This might be related to the encoding issue you're working on

**Comment by StellaHuang95** [comment]
Running the formatter from command line seems to work. It might be a problem with how we handle the patch from black.
