### ISSUE TITLE
Autocomplete after open brackets replaces entire line of code

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6786]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Autocomplete-after-open-brackets-replace/1582855)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:Visual Studio 2019 v. 16.11.6]
Visual Studio Community 2022 Current v. 17.0.0 (Windows) in conjunction with the Python extension contains the following bug:
If auto-completion / IntelliSense is used after open brackets, not only the word is completed and inserted, but the entire line of code is deleted and overwritten with the word.

Simple example:
_testword = "This is a test."
print (testw ... #use of IntelliSense leads to ==>
**testword**_

The bug does not occur in Visual Studio Community 2019 (Python) and Visual Studio Code (Python).

---
#### Feedback Bot on 11/15/2021, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
I'm able to repro this in VS2022. The entire line doesn't get replaced, BUT the opening parens does, which is definitely a bug.

**Comment by Stroichik** [comment]
So, after 3 months its still not fixed?

**Comment by AdamYoblick** [comment]
Hi @Stroichik ! Unfortunately, our team has limited capacity at the moment, and we have to prioritize our backlog accordingly. 

We appreciate your patience. We also welcome contributions fyi 😄

**Comment by Stroichik** [comment]
Can't help you on that, since i`m just learning basics. Was very surprised when i found this bug in VS22, so had to switch to other IDE to continue learning Python without accidently erasing whole lines of code. So u dont really want someone like me to accidently commit on release branch :)

**Comment by MartinLith** [comment]
H! Any news on this, it´s quite annoying and it makes you stay away from the intellisense/autocomplete (which it seems not like at all).

**Comment by MartinLith** [comment]
Hi Adam,
thank you for your answer!

No problem! i´m glad to hear that this is next up and i´m looking forward to a solution. 

Martin

**Comment by AdamYoblick** [comment]
I believe this is an LSP client bug in Visual Studio. I've created an internal bug to track this at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528198.

**Comment by AdamYoblick** [comment]
Sorry my last comment wasn't clear. Reproing this bug is blocked by another bug which is preventing variables from showing up in the intellisense completion list. That bug doesn't belong our team, so we're waiting on a fix from the VS team before I can continue with this one. Apologies for the delay.

**Comment by marcinchady** [comment]
I'm on version 17.1.3 and the completion lists populate no problem. The bug is still present, i.e. selecting an item from the list eats the closing bracket and the following operator, if there is one. See the attached video.

https://user-images.githubusercontent.com/51301749/165670452-10bf2208-4834-49ca-b014-29b6c48fc384.mp4

.

**Comment by AdamYoblick** [comment]
Thank you for the information everyone. I've spoken with the Visual Studio team and this is actually happening in some other languages as well, so we believe this is not a PTVS-specific bug. I'm going to create a bug for the VS team to look at. In the meantime, if this happens to anyone else, be sure to create a feedback ticket through VS. Thanks :)

**Comment by SpookyWookyMan** [comment]
Any updates on this? This bug has still not been fixed and while I love Visual Studio, I have no choice but to change to another IDE where the autocomplete feature actually works

**Comment by AdamYoblick** [comment]
Apologies, there was some confusion around where this bug actually is and who owns it. This is my current task and I will get it fixed one way or another 😄

**Comment by AdamYoblick** [comment]
We looked into this further and the bug seems to be in an external team. We've spoken to the team and the bug now has proper ownership. I will stay on top of it to make sure it gets fixed.

**Comment by az5078** [comment]
And..... This is not solved yet......?

**Comment by TheRealQuantam** [comment]
Gotta say given that IME IntelliSense hasn't ever worked right with Python I'm not holding my breath :P

**Comment by JamieSimWin** [comment]
I've been having this issue for a couple of weeks and i have been trying to solve the issue. This is the only information i can find online about this issue.. which still isn't fixed.....

**Comment by AdamYoblick** [comment]
Hi all, this is a Visual Studio fix, not a PTVS one. Their team had some urgent fixes they had to make that had higher priority than this one. They will be working on this for a future release of Visual Studio. I will reply back when it gets fixed 😄

**Comment by DanielLigon** [comment]
Currently having this issue on a fresh install of Visual Studio 2022 in all languages, mostly just tried the C languages. I can't even edit anything without having to retype the entire line of code because everything gets typed over instead of shifted. Any updates when this might be fixed?

**Comment by bluehatgeek** [comment]
The issue is still there. I am currently on a fresh install of VS 2022 and it is still happening.

**Comment by AdamYoblick** [comment]
Hi everyone, I'm trying to reproduce this locally on the latest internal build of visual studio and I can't repro it anymore. It seems the visual studio team has fixed the issue. See below:

![pythonAQutocomplete](https://user-images.githubusercontent.com/29436557/217044017-b45c5964-cf22-491d-932a-a4f05460a03c.gif)

The version of VS I'm on is 17.6 Preview 2. 17.6 will be available to the general public on 5/16.

**Comment by hitarthdoc** [comment]
Checked in Visual Studio Preview 17.5 with ONLY the python development workload and tested it.
Could not repro this issue.

Install Details,
> Microsoft Visual Studio Community 2022 (64-bit) - Preview
> Version 17.5.0 Preview 6.0
> VisualStudio.17.Preview/17.5.0-pre.6.0+33402.96

**Comment by CaligoLab** [comment]
For the record.
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4 (Win)
Python
Autocomplete messes up constantly. Picks up variables from time to time, removes pieces of code around.
Here's a simple example:

https://github.com/microsoft/PTVS/assets/44836679/88bed1c6-7489-49c7-a213-3aa4c25aa113

**Comment by AdamYoblick** [comment]
@CaligoLab Thank you for reporting this. I will try to repro with the latest version of VS again. 👍

**Comment by AdamYoblick** [comment]
@CaligoLab The version you reported this issue in is 17.4.4. I tested previously in 17.6 and couldn't repro this. I just tested again in 17.9 and also couldn't repro it.

Someone else in the comments tested in 17.5 and also couldn't repro.

So I believe this issue is fixed. Can you please try to update your Visual Studio to at least 17.5 or 17.6 and try again?
