### ISSUE TITLE
Refactoring intermittent for Python projects in VS2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6787]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Refactoring-intermittent-for-Python-proj/1582892)._

---
Refactoring command (. Refactor.Rename Ctrl+R+R) in Python project is intermittent, sometimes it works properly and sometimes it invokes and immediately exits by saying that it is not available - without allowing to enter new name for the variable of class. I tried same on VS2019 using same code, there it works properly.

---
#### Feedback Bot on 11/15/2021, 00:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can you please provide a code snippet that fails to refactor for you?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
