### ISSUE TITLE
Python intellisence fails to detect modules within code

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6788]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-intellisence-fails-to-detect-modu/1582945)._

---
[severity:It's more difficult to complete my work]
VS2022: Python intellisence fails to detect modules that are already the part of code, and wrongly hints at the return types.

---
#### Feedback Bot on 11/15/2021, 00:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can you please provide code where this repros? Thanks!

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
