### ISSUE TITLE
Python error is not shown in the right file

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6792]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-error-is-not-shown-in-the-right-f/1573019)._

---
If I have two files, main.py and something.py and there is a error in something.py the cursor jumps to where the function in main.py was called when I start with F5. It should jump to where the actual error is.

---
#### Feedback Bot on 11/7/2021, 05:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
This is as designed because the import is failing due to a parsing error in the imported file.
