### ISSUE TITLE
An error "Frame not in module" pops up when launch template with legacy debug while install VS2019  and VS 2022 at the same time.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6793]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/142374405-db730138-7ffd-4dc6-8fc0-cff5d9fe246e.png)
Prepare environment 
1.	Install VS2019 
     a. Make sure to install Python 3.7.* when installing the Python workload
2.	Install VS2022
     a. Make sure to install Python 3.9.7 when installing the Python workload

**Steps to Reproduce**
1. Open cookiecutter explorer
2. Load the following template: https://github.com/brettcannon/python-azure-web-app-cookiecutter
3. Keep default values and click Create and Open Folder
4. You should see the generated files in Solution Explorer – Folder View
5. Open webapp.py and put a breakpoint on first line in do_GET method
6. Go to Tools -> Options -> Python -> Debugging -> Enable legacy debug
7. Press F5
8.  Observes

**Expected behavior**
After press F5, it should start a console. Open a web browser to http://127.0.0.1:5555, It should hit the breakpoint.

**Additional context and screenshots**
An error message pops up.
![image](https://user-images.githubusercontent.com/59192491/142375385-6bb612ff-19bc-4317-963a-89db463d27ee.png)

**Comment by AdamYoblick** [comment]
@linette-zyy Does this repro when "Use Legacy Debugger" is NOT selected?

**Comment by linette-zyy** [comment]
@AdamYoblick 
When "Use Legacy Debugger" is not selected, this issue is not repro.

**Comment by AdamYoblick** [comment]
This issue is already fixed in the latest debugger (debugpy), we're not going to fix it in the old one.
