### ISSUE TITLE
Live Share: The error "'intelliCodeCppPackage' package did not load correctly" pops up when join live share Session.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6794]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/142374405-db730138-7ffd-4dc6-8fc0-cff5d9fe246e.png)
Prepare environment
Install VS2019
a. Make sure to install Python 3.7.* when installing the Python workload
Install VS2022
a. Make sure to install Python 3.9.7 when installing the Python workload

**Steps to Reproduce**
1. Open VS, no need to load any code/solution beforehand.
2. File-> Join Collaboration Session…
![image](https://user-images.githubusercontent.com/59192491/142394468-bf694b74-2f59-44dc-a1a7-0957e6332558.png)

**Expected behavior**
Join Live Share Session successfully and Intellisense works well.

**Additional context and screenshots**
The error "'intelliCodeCppPackage' package did not load correctly" pops up and Intellisense does not work.
![image](https://user-images.githubusercontent.com/59192491/142394770-46b92507-d179-4ef2-9f34-dfabc615aaa3.png)

**Comment by AdamYoblick** [comment]
Need to repro this but should probably be routed to liveshare team.

**Comment by StellaHuang95** [comment]
@linette-zyy Does this repro? Just trying to clean up some old issues that don't repro anymore. Thanks!

**Comment by linette-zyy** [comment]
@StellaHuang95 
I can't repro this in today's latest build: **17.6.0 Preview 1.0 [33317.342.main]**

**Comment by anzenchitai** [comment]
17.8.5 still having the same problem
