### ISSUE TITLE
Python 3.9 is not in the list of language version.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6802]
**Environment**
Build of Visual Studio: 17.1.0 Preview 2.0 [31929.282.main]
Build of Python Package: 17.0.21308.2
OS version: Win10 Enterprise 20h1

**Steps to Reproduce**
1. In VS, select File > New > Project,  select the Flask Web Project template.
2. Right click python environment and open “Add Environment…” command
3. Pick <Custom> and browse to the environment folder
![image](https://user-images.githubusercontent.com/59192491/144004944-2b09f757-822a-4e7f-98ae-c975a90fbe8d.png)

**Expected behavior**
Browse to a non-virtual env, there will auto-detect but let you customize all parameters. Default is to add it to the registry (make it available globally).

**Additional context and screenshots**
Python 3.9 is not in the list of language version.
![image](https://user-images.githubusercontent.com/59192491/144005029-7334ffa0-d2b9-4012-ac87-93aa8513c254.png)

**Comment by linette-zyy** [comment]
This issue still reproduced on the latest build.
![image](https://user-images.githubusercontent.com/59192491/147808122-981b99be-2156-4609-8cbb-9db3a166c7c2.png)

![image](https://user-images.githubusercontent.com/59192491/147808113-2ff27f30-c3e8-4a99-b4a2-09b3d0045bce.png)

**Comment by StellaHuang95** [comment]
@linette-zyy I can't repro this, can you try it again on the latest version and see if the issue still persists?

**Comment by linette-zyy** [comment]
I verify this issue on the latest build 
![image](https://user-images.githubusercontent.com/59192491/168224852-f56023a8-7d29-4126-8b48-520d09d6bc78.png)
This issue is not reproduce.
![image](https://user-images.githubusercontent.com/59192491/168224772-31f98504-bc4d-43a3-902d-1a221c4ac9fb.png)
