### ISSUE TITLE
pykinect support?

### ISSUE THREAD

**Issue by virgilm** [microsoft/PTVS#6803]
I know this is ancient, but pretty much all links for pykinect are dead (docs/code repo/etc)

Anything listed [here](https://github.com/microsoft/PTVS/wiki/PyKinect) is still available somewhere?

Any pointers would be appreciated.

**Comment by AdamYoblick** [comment]
This is really old (2015!). I believe this was supported in an older branch. Please see PTVS/Python/Product/PyKinect at release/15.9 · microsoft/PTVS (github.com)

**Comment by int19h** [comment]
Yeah, it's been gone for a long time now. We should probably remove it from the wiki tho.
