### ISSUE TITLE
Python file launch in File Explorer does not open Visual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6807]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-file-launch-in-File-Explorer-does/1591129)._

---
This worked in 2019. If you launch a Python file from FileExplorer, Visual Studio launches, but doesn't open the file.

Your screen recorder doesn't work, so I attached a 45 second video.

---
#### Feedback Bot on 11/22/2021, 00:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can repro this in VS2022, without python workflow installed. Need to test with workflow installed.

**Comment by AdamYoblick** [comment]
@bschnurr said he fixed something very similar a while back. Bill can you include details here please?

**Comment by bschnurr** [comment]
Last fix was 16.0 specific. probably needs updating. https://github.com/microsoft/PTVS/pull/5957
