### ISSUE TITLE
Python method outlining breaks if signature is multi-line

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6808]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-method-outlining-breaks-if-signat/1590914)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.11.6]
In Visual Studio 2022 when coding Python I'm unable to collapse a method if the signature spans more than one line.

Correct behavior (VS 2019):
! [image.png] (https://aka.ms/dc/image?name=Bb791d180debf44b2a2ce4ce59f51ea66637729872661814173_20211120-064103-image.png&tid=b791d180debf44b2a2ce4ce59f51ea66637729872661814173)
! [image.png] (https://aka.ms/dc/image?name=Bcec6539a0fc04b8690b181c90380fb35637729872845563118_20211120-064122-image.png&tid=cec6539a0fc04b8690b181c90380fb35637729872845563118)

Incorrect behavior (VS 2022):
! [image.png] (https://aka.ms/dc/image?name=B52c545eed0b84c4bb30dc3c2e13eab52637729873251903956_20211120-064203-image.png&tid=52c545eed0b84c4bb30dc3c2e13eab52637729873251903956)
! [image.png] (https://aka.ms/dc/image?name=B46280067361b4c759c191e5d376467ee637729873420220694_20211120-064220-image.png&tid=46280067361b4c759c191e5d376467ee637729873420220694)

---
#### Feedback Bot on 11/22/2021, 00:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, I could not repro this. Could you verify if you are still experiencing the same issue on the latest VS? Also the images you uploaded before are broken, it would be helpful if you could upload again if the problem persists. Thanks! 😊

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks😊
