### ISSUE TITLE
Profiling is currently not supported for 3.9.7 in build 16.7.23

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6813]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/144560135-bc2162a5-8119-4b26-8709-1b0821429f71.png)

**Steps to Reproduce**

1. Create python application project named PythonApplication2 and typing code in it. ( ```Python 3.9```)
2. Debug->Launch Python Profiling …
3. Checked the option "Open project" and select the current project in drop-down list.
4. Click "Start".

**Expected behavior**

Start without any errors.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/144560446-30c95bd3-5370-4a22-9841-cad2a421ee6d.png)

<details>
<p>

```
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\profiling\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\microsoft\python\profiling\vspyprof.py", line 74, in profile
    raise NotImplementedError("Profiling is currently not supported for " + sys.version)
NotImplementedError: Profiling is currently not supported for 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
```

</p>
</details>

**Comment by int19h** [comment]
VS 16.7 does not fully support Python 3.9.
