### ISSUE TITLE
The output window is not displayed when creating env (Active environment is python2.7)

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6814]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/144562056-db95b8e8-6617-4320-96c5-894b1bd6d8f4.png)

**Steps to Reproduce**

1. Check the option ```Show the output Window when creating virtual environments``` is on. 
( Tools > Options > Python > Show the output Window when creating virtual environments ) 
2. Create a Python Application. ( ```Ensure Active environment is python2.7``` )
3. Create virtual environment

**Expected behavior**

The output window appears when creating virtual environments.

**Additional context and screenshots**

Output windows(closed) doesn't appear.

![image](https://user-images.githubusercontent.com/82852072/144562805-4133386a-7838-4252-94b7-d496986f2ad5.png)

**Comment by AdamYoblick** [comment]
@ttSpace Python 2.7 is not supported anymore. Can you please verify that this happens using Python 3.9 (or whatever 3.* comes with the VS installer)?

**Comment by ttSpace** [comment]
@AdamYoblick It only happens when using ```Python 2.7```.

**Comment by AdamYoblick** [comment]
Ok thanks for the info. I'm going to close this out then since Python 2.7 is out of support.
