### ISSUE TITLE
Failed to launch debug adapter in local attach. (Python 3.9)

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6815]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/144582944-f38e78dc-f14d-4d2f-b04c-564e6aab0562.png)

**Steps to Reproduce**

1. Launch VS and create new python application
2. Add an input('>') or raw_input('>') at the top of your code - depends on version of python
3. Add some more python code after that with breakpoint(s)
4. Start WITHOUT debugging
a. Console will wait for you to input something
5. Debug > Attach to Process, select the appropriate python.exe (easiest if there's only one, you may want to close interactive windows first)
6. Type enter in the console
```
input('>')
from math import cos, radians 
def make_dot_string(x): 
    rad = radians(x) 
    numspaces = int(20 * cos(radians(x)) + 20) 
    st = ' ' * numspaces + 'o' 
    return st 
def main(): 
    for i in range(0, 1800, 12): 
        s=make_dot_string(i) 
        print(s) 
main()
```

**Expected behavior**

Local attach successfully with no errors.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/144583574-16e3f12b-eb3e-415d-945a-1b671a5aec81.png)

![image](https://user-images.githubusercontent.com/82852072/144583822-1f0a8dc4-025c-4841-9ed8-78255885e242.png)

**Comment by int19h** [comment]
VS 16.7 does not fully support Python 3.9.
