### ISSUE TITLE
Failed to hit breakpoint when debug native debug.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6816]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59192491/144583817-92044218-3eed-487b-b11b-8176cdeff292.png)

**Steps to Reproduce**
1. Create new Python Application, add simple Python code
2. Enable "Native Code Debugging" in project settings / debug page
3. Set breakpoint and start debugging

**Expected behavior**
It can hit the breakpoint.

**Additional context and screenshots**
Failed to hit breakpoint.
![breakpoint](https://user-images.githubusercontent.com/59192491/144584395-4dc86e1d-9e08-4920-9dc1-d7029d60d5c4.gif)

**Comment by int19h** [comment]
VS 16.7 does not fully support Python 3.9, as indicated by the banner. Mixed-mode debugging is one of the unsupported features.

**Comment by ttSpace** [comment]
@int19h I can repro in build ```16.9.15``` , is that still an unsupported feature?

**Comment by int19h** [comment]
Yep, this applies to VS 2019 / 16.x in general - we only added proper support for all this stuff in 17.0.
