### ISSUE TITLE
Memory leak in Python background analyzer

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6822]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Memory-leak-in-Python-background-analyze/1602531)._

---
[regression]
Process continuously bleeds memory whilst editing python code - up to 10GB then I did restart VS. Happens right after restart again

---
#### Feedback Bot on 12/3/2021, 11:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, could you verify if you are still experiencing the same issue on the latest version of VS? Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks😊
