### ISSUE TITLE
No Python templates, interpreter, etc. in new Visual Studio 2022 install

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6826]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-Python-templates-interpreter-etc-i/1587770)._

---
[severity:I'm unable to use this version]
I have just installed Visual Studio Community 2022 and selected the Python workload. It cannot make a new Python project. There are no Python templates. There is no Python Interpreter in View | Other windows. There is no Python item in Tools | Options.

In short, I see no evidence Python is installed.

---
#### Feedback Bot on 11/17/2021, 11:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Graham Wheeler [MSFT] on 12/1/2021, 09:49 AM: 

<p>Can you please rerun setup and try to repair your installation? We have not been able to reproduce this problem.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Have you tried repairing your VS install or reinstalling it? I'm not able to repro this myself. Is this still an issue?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with additional information. thanks
