### ISSUE TITLE
PackageId:CPython39.Exe.x64; PackageAction:Install; ReturnCode:1;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6827]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/1604058)._

---
**Describe your issue here**  
  
===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64; PackageAction:Install; ReturnCode:1;

---
#### Feedback Bot on 12/5/2021, 06:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
I checked the logs and the cpython package is failing to install because the machine is win7. Win7 is not officially supported anymore and the installer from python.org probably doesn't work on that OS. This is a no fix for us.
