### ISSUE TITLE
IntelliSense which is modified manually does not work after restart the VS.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6829]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/147221314-c0117398-f2b5-49fe-8ff0-ebefcc1162f9.png)

_**Situation1**_

**Steps to Reproduce**
1. Add folder to search path
	 Module1.py file prepared with below code copied to c:\test folder
```
		def summizing(title: str, mock: bool):
		    pass
		
		def addcross(a: int, b: int):
		    a = a+1
		    b = b+1
		    return a * b
```
2. Right-click Search Paths Node in SE and select Add folder to Search Path
3. The contents are scanned and made available to intelliSense. Type from module1 import * to make sure it works
4. Restart the VS

**Additional context and screenshots**
Search Paths does not work after restart the VS. The "Module1" could not be resolved.
![image](https://user-images.githubusercontent.com/59192491/147221734-6b6d0866-6930-4a6b-aa5b-c75a45a9a616.png)

Even though create a new project, repeat to add the folder to Search Path. IntelliSense does not work.

_**Situation2**_

**Steps to Reproduce**
1. Create a solution with 2 Python application projects: ProjectA, ProjectB
2. Add some python files to each project
![image](https://user-images.githubusercontent.com/59192491/147537058-8ad0cd26-3e6b-47c5-9366-4e186385b54c.png)
3. From ProjectA, right click Add Reference and select ProjectB.
4. Verify that ProjectA search paths was automatically updated with a path to ProjectB
5. Check that in ProjectA you get intellisense against modules in ProjectB

**Additional context and screenshots**
No intellisense in ProjectB.
![image](https://user-images.githubusercontent.com/59192491/147537127-28bbc18f-cc68-4adc-9539-6bbf1e716df8.png)

**Comment by linette-zyy** [comment]
This issue is not reproduced on the latest build
![image](https://user-images.githubusercontent.com/59192491/147807860-902cc0db-cef2-4d17-a280-e6ca47e62b6e.png)
So I closed this issue.

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/151648577-90590767-24a7-4e5d-84a6-a709e873dccc.png)
This issue reproduce on today's build, so I reopen this issue.
Between python applications
![image](https://user-images.githubusercontent.com/59192491/151648561-ade656a8-0c5d-4e25-bdc0-31bfd7617daa.png)
Between Python Application and C++ project
![image](https://user-images.githubusercontent.com/59192491/151648587-6bfcc5f0-75f5-4af5-aed5-ed741a1c6b07.png)

**Comment by AdamYoblick** [comment]
We will try to repro this and take a look.

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/153357793-646600b6-da01-464d-bfdf-dc8798281dba.png)
This issue reproduced on today's build.
![image](https://user-images.githubusercontent.com/59192491/153357739-0d329f0d-ab40-4ac5-97eb-89da1de7d91a.png)

**Comment by linette-zyy** [comment]
I can repro in today's build 17.2.0 Preview 3.0 [32328.412.main].
After start debugging（F5）, the intellisense is missing.
![project_add_reference](https://user-images.githubusercontent.com/59192491/160555344-b5808813-5d34-4870-94c2-9bf0d9c334c4.gif)

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/167084355-23fc9a77-b673-48ad-90bd-329e0d84bbf0.png)This issue reproduced on today's build.
IntelliSense does not work when import folder outside the workspace after restart VS
![image](https://user-images.githubusercontent.com/59192491/167085708-0f359522-357d-4320-9d9e-90093cea47a7.png)
![image](https://user-images.githubusercontent.com/59192491/167085768-8c3f0de3-eb19-42df-a98c-e99fc5838853.png)
![image](https://user-images.githubusercontent.com/59192491/167086010-eddfa599-4c1e-4f02-83bc-8d4555eec78c.png)

**Comment by linette-zyy** [comment]
In today's latest build:**17.6.0 Preview 3.0 [33508.333.main]**, Python package:**17.0.23065.2**
the ProjectB's path in ProjectA's ```Search Paths``` is missing
![rst_VS_reference](https://user-images.githubusercontent.com/59192491/223949001-2ffad292-e7a2-4224-93e3-10a868501fbb.gif)

**Comment by linette-zyy** [comment]
In today's latest build:**17.6.0 Preview 3.0 [33521.512.main]**, Python package:**17.0.23068.1**
No IntelliSense when add folder to Search Path and no IntelliSense when add Zip Archive to Search Path 
![image](https://user-images.githubusercontent.com/59192491/226851141-d6a826c7-fd6f-4ba3-b04b-94babc9f3a6f.png)

**Comment by linette-zyy** [comment]
This issue repro on today's build 
![image](https://github.com/microsoft/PTVS/assets/59192491/d1efb9c3-c3d8-45c1-a489-1f7ec5836106)

**Comment by heejaechang** [comment]
looks like it is a dup of https://github.com/microsoft/PTVS/issues/7828 ? how do you think @AdamYoblick ?

**Comment by heejaechang** [comment]
another potential dup - https://github.com/microsoft/PTVS/issues/6639
