### ISSUE TITLE
Even though the "Ignore system-wide PYTHONPATH variable" option is checked, it will become unchecked after restart the VS.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6831]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/147647723-cff5ef0d-f1cb-4f3c-a3f7-f3bc36ab9e96.png)

**Steps to Reproduce**
1. Create a new Python Application
2. Select the option Tools > Options > Python > General > Ignore system-wide PYTHONPATH variables
![image](https://user-images.githubusercontent.com/59192491/147647828-0a7f8550-3bd7-4bc1-adb8-24abda8a04e5.png)
3. Restart the VS
4. To check the "Ignore system-wide PYTHONPATH variable" option

**Expected behavior**
The option is checked.

**Additional context and screenshots**
The "Ignore system-wide PYTHONPATH variable" option is unchecked
![image](https://user-images.githubusercontent.com/59192491/147648244-9b9d5f84-3566-4e25-bf21-ba8712596fe4.png)

**Comment by AdamYoblick** [comment]
This sounds like a problem saving options to disk. Should be easy to fix.
