### ISSUE TITLE
VS2019 python and AWS problem

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6832]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2019-python-and-AWS-problem/1614618)._

---
I have used the VS python template to create a program.
I havent changed anything in it and it runs ok.
I uploaded the project to AWS using AWS tool kit.
It uploads fine but the link in AWS doesnt work I just get error 403.
Am I missing something somewhere ?

---
#### Feedback Bot on 12/15/2021, 09:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### nigel wright on 12/16/2021, 05:19 AM: 

<p>AWS say their end is working fine as upload has a green no errors status.<br>
They think there is something wrong with the files in Visual Studio.<br>
I tried changing <a target='_blank' href="http://runserver.py">runserver.py</a> to <a target='_blank' href="http://application.py">application.py</a> but that made no difference.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
We need a little more information about this. Are you able to provide a repro? A 403 on files in AWS shouldn't have anything do with Visual Studio.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
