### ISSUE TITLE
UnitTestRootDirectory setting in PythonSettings.json is ignored

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6836]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/UnitTestRootDirectory-setting-in-PythonS/1615926)._

---
1. Clone https://github.com/microsoft/DeepSpeed.git
2. Open it as Local Folder in Visual Studio 2022 with Python workload installed
3. Toggle hidden file display, and open PythonSettings.json from Local settings
4. Use the following settings:
```
{
  "TestFramework": "pytest",
  "UnitTestRootDirectory": "tests\\unit",
  "UnitTestPattern": "test_*.py"
}
```
5. Open Test Explorer and check Output window (show output from: Tests)

**Expected**: pytest command line should restrict looking for tests to tests\unit subfolder
**Actual**: it seems to be using the root folder of the repository ignoring UnitTestRootDirectory setting:

```
python.exe -m pytest --collect-only --cache-clear '--rootdir=C:\Users\USERNAME\Projects\DeepSpeed'
```

---
#### Feedback Bot on 12/16/2021, 07:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
This should work according to https://devblogs.microsoft.com/python/whats-new-for-python-in-visual-studio-16-3-preview-2/. Need to investigate, could be a regression.

**Comment by morten-ofstad** [comment]
For our project, this completely prevents the tests from working because it ends up scanning so many files that it times out before it can find the tests.

**Comment by StellaHuang95** [comment]
Hi, the `UnitTestRootDirectory` only specifies test directory for unittest. You will need to specify a .ini file to config pytest. Please see this [link](https://docs.pytest.org/en/6.2.x/customize.html). 

![folder_view_2](https://user-images.githubusercontent.com/100439259/163026906-8474b683-358c-4d0a-801d-b95cb966104a.png)

Please reopen the ticket if it still does not resolve your issue. Thank you!

**Comment by morten-ofstad** [comment]
This is exactly the issue, if the pytest.ini file is not in the root of the project (in my case a C++ library with bindings for Python and Java that has the tests for each language in separate subdirectories) it takes more than 30 seconds to scan for the Python tests and the Test Explorer always times out. We finally worked around the issue by moving pytest.ini to the root directory of the project, but there should be some way to tell the test discovery process where to find pytest.ini — I thought that was the purpose of the UnitTestRootDirectory setting, but apparently I was wrong.
