### ISSUE TITLE
Please Python encode the file as utf-8 and save it.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6837]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-Python-encode-the-file-as-utf-8-a/1620648)._

---
[severity:It's more difficult to complete my work]
When I run it in Korean, I get the following UTF-8 error. The way to solve this kind of error is to use another program (Notepad, etc.) to change it to UTF-8. To solve this problem, change Python's default storage to UTF-8.

---
#### Feedback Bot on 12/22/2021, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Did you manually enter the text into Visual Studio when getting this error, or did you copy/paste the text from somewhere else? In other words, how did the invalid character get into the editor?

**Comment by ghkimwoo** [comment]
If you do not set anything and start with the default settings.
![image](https://user-images.githubusercontent.com/45334270/149410182-1cefd39a-9467-4aa5-9fae-7795ca2ea4ef.png)
What needs to be fixed for use in Visual Studio.
![image](https://user-images.githubusercontent.com/45334270/149410500-e71318ec-07a2-4f40-8cb1-504b0afb96ac.png)
![image](https://user-images.githubusercontent.com/45334270/149410585-04696c61-7371-46d7-a5b5-5816149e5cef.png)

**Comment by ghkimwoo** [comment]
P.S. The result is the same whether you open it in Notepad or copy and paste it.

**Comment by StellaHuang95** [comment]
This is a dup of #6784 

One workaround is to go to File -> Save As -> Pick "Save with Encoding..." from the Save dropdown menu -> Pick UTF-8.
![image](https://user-images.githubusercontent.com/100439259/165184308-214691a8-d4c7-4e1f-9ef3-ef546b9a62d7.png)
