### ISSUE TITLE
The VS is no response after choose "I will install them myself" when create Blank Django Web Project.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6846]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/148508269-8cd2be84-c59b-4ad4-9ad5-85fee6a376dd.png)

**Steps to Reproduce**
1. In VS, select File > New > Project, search for "Django", and select the Blank Django Web Project template.
2. Enter the Name and location and click OK
![image](https://user-images.githubusercontent.com/59192491/148508367-63c039d2-4420-47df-9d9c-d1097fcd2498.png)
3. After a moment, VS prompts you with a dialog shown below:
![image](https://user-images.githubusercontent.com/59192491/148508443-3f6f1061-7c9e-4422-aeb8-363543e03cc8.png)
4. Select the option "I will install them myself"
5. Observes

**Expected behavior**
The project was created successfully without any error.

**Actual result**
The VS is no response.
![No response](https://user-images.githubusercontent.com/59192491/148509255-f72b4f29-90e3-46ca-b7b7-0347ac6b3937.gif)

**Event log**
[Event log.zip](https://github.com/microsoft/PTVS/files/7827291/Event.log.zip)

**Comment by StellaHuang95** [comment]
Can't repro this. Please reopen it if the issue persists. Thanks.
