### ISSUE TITLE
An error message pops up when unloading the project.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6847]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/148506086-03e59d93-66a9-411c-85a0-eb1c5b540107.png)

**Steps to Reproduce**
1. Create a python application.
2. Select "Property" page, select "Test" to set "Test framework" to "pytest".
3. Unload the python project.

**Expected behavior**

The project unload successfully without any errors.

**Additional context and screenshots**

An error message pops up.

![image](https://user-images.githubusercontent.com/82852072/148510299-12d5a2fa-bbb5-4f94-870d-e6bdf5d6c7c8.png)
[ActivityLog.xml.txt](https://github.com/microsoft/PTVS/files/7827350/ActivityLog.xml.txt)

**Comment by judej** [comment]
This seems like a cache issue. Would you please try clearing the caches? 
You can do that with `dev /setup`  from inside the VS dev command line.

Please let us know if that fixes it for you .

thanks

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen . thanks
