### ISSUE TITLE
An error "Error HRESULT E_FALL has been returned from a call to a COM component" when copy and cut.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6852]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/149721897-54f7b109-707c-4d2a-be94-fcd96e73e733.png)

**Steps to Reproduce**
1. Create a new Python Application
2. Right click PythonApplication14.py
![image](https://user-images.githubusercontent.com/59192491/149724243-3f7c489f-ecef-4dd4-ae14-b7c69fd624f2.png)
3. Choose "Copy" and "Cut" selection

**Expected behavior**
The file can be copy and cut successfully without any error.

**Actual behavior**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/149722796-35cfc810-1dc2-4ac3-a31c-db584ad5d9e7.png)

**Comment by AdamYoblick** [comment]
Need to try to repro this and verify.

**Comment by StellaHuang95** [comment]
I can't repro in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 1.0 [32424.78.main]. Please reopen the issue if it is still a problem. Thank you.
![Animation2 - copy cut2](https://user-images.githubusercontent.com/100439259/165183704-4a1aff57-d796-4ca8-b09f-773e8a7fe654.gif)
