### ISSUE TITLE
Process to generate diagnostics file in bug template is out of date

### ISSUE THREAD

**Issue by debonte** [microsoft/PTVS#6854]
The PTVS new issue "Bug Report" template 

**Steps to Reproduce**
1. https://github.com/microsoft/PTVS/issues/new/choose
2. Click "Get Started" next to "Bug Report"
3. Read the "Diagnostics file" section of the template.
4. Open VS
5. Follow the template instructions to generate a diagnostics file "by going to Tools->Options->Python->Diagnostics"

**Expected behavior**
Diagnostics should either be a subsection under Python or UI within the General section.

**Additional context and screenshots**
Diagnostics isn't found anywhere under the Python options section.

![image](https://user-images.githubusercontent.com/12820898/150028026-36eec320-5002-4341-81bf-d28c181a3956.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 17.1.0 Preview 3.0 [32105.426.main]
PTVS version: 17.0.21344.1

**Comment by AdamYoblick** [comment]
@bschnurr @judej Do you know if this Diagnostics section was meant to be removed from the VS options page? 

- If it was, we should update the instructions in the bug template.
- If it wasn't, we need to figure out where it went 😄

**Comment by StellaHuang95** [comment]
The PythonToolsDiagnostics logs are now saved in the "%TEMP%" folder by default, I will update the template.
