### ISSUE TITLE
Bug template should be more clear about how to find PTVS version

### ISSUE THREAD

**Issue by debonte** [microsoft/PTVS#6855]
**Describe the bug**
The Bug Report issue template says that the PTVS version "Can be found under "Help->About Microsoft Visual Studio->Installed products", but PTVS isn't listed as an installed product in VS.

**Steps to Reproduce**
1. Start VS with Python workload installed.
2. Help->About
3. Look for PTVS in list of installed products, since the template says it wants the "PTVS version".

**Expected behavior**
PTVS is present in installed products list or bug template clarifies which installed product version it actually wants. "Python with Pylance" perhaps?

![image](https://user-images.githubusercontent.com/12820898/150028596-d8244364-421a-4a89-9079-69a8e2d02401.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 17.1.0 Preview 3.0 [32105.426.main]
PTVS version: 17.0.21344.1

**Comment by AdamYoblick** [comment]
Yep, Python with Pylance is the correct product I believe. I'll fix the bug template.
