### ISSUE TITLE
Visual studio 2019 go to definition and Intellisense not working in Python project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6856]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-studio-2019-go-to-definition-and-/1634768)._

---
The description of problem is as title,  thanks for your help.

Closing VS and deleting .vs folder does not help.

---
#### Feedback Bot on 1/11/2022, 10:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can you please provide some sample code or a sample application so we can try to repro this?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
