### ISSUE TITLE
VS python cannot find the python environment after uninstalling/reinstalling VS

### ISSUE THREAD

**Issue by dpugh** [microsoft/PTVS#6873]
**Describe the bug**
I -- with a 17.0 RTM VS (17.0.5) -- managed to trash my Python environment to the point that it thinks it has Python 3.9 installed but can't find it (removing & reinstalling VS does not fix the problem). Nor can I find any instances of 3.9 on my disk (though, if I install the 32 bit versions, I can find those).

I suspect it may have to do with my moving VS from c:\ to d:\ (but moving it back did not help). 

![image](https://user-images.githubusercontent.com/11394666/151672371-25995e4c-1001-4855-9516-4f95a086339d.png)

**Steps to Reproduce** (tentative)
1. Install VS + Python to c:, verify it works and the python environment can be found.
2. Uninstall VS, reinstall to d:, see if the python environment can be found.
3. Uninstall VS, reinstall to c:, see if the python environment can be found.

**Expected behavior**
Uninstalling and reinstalling VS leaves me with a working python environment.

**Additional context and screenshots**

I've attached the VS log file from my machine.

](url
[VSLogs.zip](https://github.com/microsoft/PTVS/files/7964288/VSLogs.zip)
)

**Comment by DietmarSchwertberger** [comment]
I experienced similar and had to remove this one:
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Pytho\PythonCore\3.9\PythonPath`

VS does assume many things around Python and the registry. That's not a good idea and absolutely intransparent:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/7750#issuecomment-1062219276
https://github.com/MicrosoftDocs/visualstudio-docs/issues/7750#issuecomment-1074039286

**Comment by AdamYoblick** [comment]
Going to close this out since it seems to be resolved.
