### ISSUE TITLE
Python target returns Error HRESULT E_FAIL has been returned from a call to a COM component 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6883]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-target-returns-Error-HRESULT-E_FA/1646730)._

---
Starting at Visual studio 2019 version 16.11.8 when building our solutions in command line projects with python target's return the following error:
"Error HRESULT E_FAIL has been returned from a call to a COM component."

Visual Studio 2017 does not report this error on the same solution, so we know this is specific to VS 2019.
The other strange behavior is that opening the solution with the GUI and executing the build on it, no errors are returned.

Restarting VS2019 and the server had no effect.

---
#### Feedback Bot on 1/25/2022, 09:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can you please share some sample code or a repro that causes this error so we can investigate?

**Comment by StellaHuang95** [comment]
Closing old issue. Please reopen this issue with the information requested if this is still a problem. Thanks.
