### ISSUE TITLE
Intellicode deletes everything in line before keyword

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6887]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellicode-deletes-everything-in-line-b/1654997)._

---
[severity:It bothers me. A fix would be nice]
Intellicode deletes everything in line before keyword if i choose keyword through suggestions
for example this code. 

numbers = input("Enter values")
print(numbers)

If i start typing "print(numb" and then use ctrl+space to choose "numbers" my code will start to look like this

numbers = input("Enter values")
numbers

everything before keyword "numbers" will be deleted. I dont understand why. VSCode has no problem like that.

It also bothers me that Suggestions appear not always, and sometimes flash into being for a second and then disappear, until i type some more.

Am i doing something wrong? It really worked quite fine in VSC, its first time i see Intellisense glitch like that.

---
#### Feedback Bot on 2/6/2022, 08:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Stroichik ™ on 2/7/2022, 04:47 PM: 

<p>It is also doesn’t see my variable “list” in this code example</p>
<p><img src="https://aka.ms/dc/image?name=Ba342683982254f168aa787177e565cfd637798779784173620_20220208-034617-image.png&amp;tid=a342683982254f168aa787177e565cfd637798779784173620" alt="image.png"></p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Related to https://github.com/microsoft/PTVS/issues/6885 as well as a few other bugs we have open. Not sure if these are literally duplicates, but they are very similar. The parser doesn't recognize what token to replace and does the wrong thing. Definitely needs investigation and fixing.

**Comment by AdamYoblick** [comment]
Have to follow up with the LSP / VS Editor team about this, I know they have a bug that tracks it.

**Comment by StellaHuang95** [comment]
I've verified that this doesn't repro anymore. Shall we close it? @AdamYoblick 
![intellicode](https://user-images.githubusercontent.com/100439259/221733291-48fc7e5e-3120-4bb7-ac79-6891abc27b90.gif)
