### ISSUE TITLE
An error "cannot import name 'soft_unicode' from 'markupsafe'"pops up when launch Flask project.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6889]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/154637765-11f01202-245c-4454-aa9c-7d35b2302ac7.png)

**Steps to Reproduce**
1. Create a new Flask Web Project
2. And click "Create virtual environment" from the notification message
![image](https://user-images.githubusercontent.com/59192491/154638106-81df34e7-47dc-40c2-951e-a8030103de70.png)
3. When after installing the environment successfully, press F5 to launch the project
4. Observes

**Expected behavior**
The project launched successfully without any error.

**Additional context and screenshots**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/154638471-b22b92e2-ad32-4925-9f41-bd0166854a53.png)

**Output**
```
cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\vyizh12\source\repos\FlaskWebProject5\FlaskWebProject5\env\lib\site-packages\markupsafe\__init__.py)
Stack trace:
 >  File "C:\Users\vyizh12\source\repos\FlaskWebProject5\FlaskWebProject5\FlaskWebProject5\__init__.py", line 5, in <module> (Current frame)
 >    from flask import Flask
 >  File "C:\Users\vyizh12\source\repos\FlaskWebProject5\FlaskWebProject5\runserver.py", line 6, in <module>
 >    from FlaskWebProject5 import app
Loaded 'jinja2.filters'
Loaded 'jinja2.defaults'
Loaded 'jinja2.environment'
Loaded 'jinja2'
Loaded 'flask'
Loaded 'FlaskWebProject5'
Loaded '__main__'
Loaded 'runpy'
The program 'python.exe' has exited with code 0 (0x0).
```

**Comment by stefanweiser** [comment]
I have exactly the same problem with conan, which also uses jinja2! Seems, that there is an error in the official pip mirror.

**Comment by janibonnevier** [comment]
https://github.com/pallets/markupsafe/issues/285

**Comment by janibonnevier** [comment]
https://github.com/pallets/markupsafe/issues/284

**Comment by davidism** [comment]
You are using an unsupported version of Jinja, please update to the latest version. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.
