### ISSUE TITLE
Unable to cast object of type 'Microsoft.VisualStudio.Tools.ClipboardService' to type 'Microsoft.VisualStudioTools.IClipboardService'

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6897]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-cast-object-of-type-Microsoft/1672890)._

---
[severity:I'm unable to use this version]
Running visual studio 2017 and creating python project. In solution explorer trying to copy code file "example.py" ja end into this error. How to fix? Please help.

This will push me out of the visual studio. Really waste of time to keep hitting my head into wall. Perhaps there is better development platforms available.

---
#### Feedback Bot on 2/23/2022, 00:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi, we tested in 2017, 2019, and 2022 versions, but were not able to reproduce it in any of the versions. Could you please try to repair/reinstall 2017, or upgrade to 2019/2022 and see if the problem persists? Thank you.
