### ISSUE TITLE
Visual Studio 2019 fails to set selected python environment

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6898]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2019-fails-to-set-selected/1671016)._

---
[severity:It's more difficult to complete my work]
I am using Visual Studio 2019, version 16.11.10, on my Windows 10 laptop.

VS fails to set any python environment that I select from several existing environments I have. When I do

Steps;-
I start up VS
I see that a python environment named " env_x" is selected and activated.
I change the selected environment  to for example " env_a " and activate that one.
make this the default environment for future project
I do a save all
I exit VS and let it shut down
Then
When I start VS again 
VS starts up but , incorrectly, the previous env_x is activated, not env_a

This happens no matter which other python environment I select. VS always incorrectly starts up with the env_x selected and activated.

I have done the following;-
Up dated VS to version 16.11.10
Executed the " repair " function in the VS installer.

That do not solve the defect

---
#### Feedback Bot on 2/20/2022, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Workaround is to select the appropriate environment, but having to do this every time is annoying. We will try to repro this and get back.

**Comment by StellaHuang95** [comment]
Hi, could you please try upgrading to the latest version of Visual Studio 2022 and let us know if the problem persists? Thank you!

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
