### ISSUE TITLE
Python 3.10 failed to hit breakpoint when attach to a running python.exe.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6899]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/156515306-729f83b3-ed27-4986-b991-8c037b6ca76d.png)
Download Python3.10 from python.org

**Steps to Reproduce**
1. Launch VS and create new python application
2. Add an input('>') at the top of your code
![image](https://user-images.githubusercontent.com/59192491/156515789-52a87cc1-267f-44db-8382-4ac1b6ecccf4.png)
3. Add some more python code after that with breakpoint(s)
4. Start WITHOUT debugging
	a. Console will wait for you to input something
5. Debug > Attach to Process, select the appropriate python.exe 
6. Type enter in the console
7. Check that it stops at the breakpoint

**Expected behavior**
It hit the breakpoint,

**Additional context and screenshots**
Failed to hit breakpoint
![Attach](https://user-images.githubusercontent.com/59192491/156516375-53257858-fcd4-4696-be06-24f8ba3c7653.gif)

Python3.9 can hit the breakpoint.

**Comment by int19h** [comment]
Fixed by https://github.com/microsoft/PTVS/pull/6916
