### ISSUE TITLE
Not possible to import existing Python project  

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [Microsoft/PTVS#69]
After installing Python for visual studio, the option to import existing python projects into Visual Studio is not showing up
![image](https://cloud.githubusercontent.com/assets/5278928/7441725/e20b8ce6-f0c2-11e4-9cd5-f380f7a5ea1a.png)

**Comment by int19h** [comment]
Unfortunately, this Visual Studio dialog is not extensible. The option to create a Python project from existing code is available as a pseudo-project template called "From Existing Python Code" in the New Project dialog. More details are in the [wiki](../wiki/Projects#create-project-from-existing-files).
