### ISSUE TITLE
Live Share: A warning appears when joining a shared window via VS.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6901]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/156712433-331d5d13-3052-4865-83a3-22e6820e94d7.png)

Install Python 3.10 from https://www.python.org/

**Steps to Reproduce**

1. Create a Python Application.
2. Click LiveShare and sign in.
3. Visual Studio Live Share Firewall Access, click Ok.
4. You should click allow access.
5. You will come to Visual Studio Live Share page. Click Copy invite link button.
6. Open VS without preloading any code/solution.
7. File-> Join Live Share Session… 
8. Enter Collaboration Session Invite Link->join.

**Expected behavior**

Joined Live Share session successfully.

**Additional context and screenshots**

The host has ended.

![image](https://user-images.githubusercontent.com/82852072/156714854-ab0a10d5-8174-402f-acdc-1390e6baf716.png)

![join_liveshare](https://user-images.githubusercontent.com/82852072/156714893-07e19407-1ffb-48b1-873e-479f121b3932.gif)

**Comment by ttSpace** [comment]
In today's build ```17.2.0 Preview 3.0 [32309.203.main]```, Python Package: ```17.0.22059.4```, A warning appears to enter the share window **through the browser**, and an extension information is displayed. BTW, Repro this issue by joining a shared window **via VS**.

<img src=https://user-images.githubusercontent.com/82852072/157614051-25802519-392f-49f5-93b8-56443bbd488c.png width=885 height=17>

<img src=https://user-images.githubusercontent.com/82852072/157614656-01c52e57-3f6b-422e-acd6-b4709af515af.png width=696 height=281>

<img src=https://user-images.githubusercontent.com/82852072/157613520-e7b283ed-1a87-48fc-a445-135068836960.png width=885 height=524>

**Comment by linette-zyy** [comment]
This issue also can reproduce on this build.
![image](https://user-images.githubusercontent.com/59192491/158113104-21e3be18-b1d1-4415-9706-bc0d57182734.png)
![image](https://user-images.githubusercontent.com/59192491/158113401-925a7761-a9a9-4b21-b34e-8bf8d4385045.png)
![image](https://user-images.githubusercontent.com/59192491/158113480-f6fa3095-488d-46fd-9ecc-a0ed55485ee8.png)

**Comment by ttSpace** [comment]
I cannot repro this in today's build ```17.6.0 Preview 1.0 [33319.311.main] ```,Python Package: ```17.0.23005.2```.
Successfully joined a Live Share session via VS/Browser.

![image](https://user-images.githubusercontent.com/82852072/213615037-3fcbf958-cc81-4931-ac3b-b389801d43b4.png)
