### ISSUE TITLE
No response when start debug

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6903]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/156960484-d3e22dd5-34b5-4829-89e4-de0538257df9.png)

**Steps to Reproduce**
1.Launch VS and create a python application
2.Add some code
![image](https://user-images.githubusercontent.com/59192491/156961349-4fc22f52-739c-4eda-9526-572f79c24297.png)
3.Set a breakpoint
4.Click Debug -->Start Debugging or press F5

**Expected behavior**
The VS should pop up a console and hit the breakpoint

**Actual behavior**
No response when press F5

**Additional context and screenshots**
![cannot_start_debugging](https://user-images.githubusercontent.com/59192491/156961730-2a54c582-6b72-4aaa-8074-e8d71e6268b8.gif)

**Comment by StellaHuang95** [comment]
I can't repro in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 1.0 [32411.352.main]
![Animation2 - debugger](https://user-images.githubusercontent.com/100439259/163607828-31798f26-3352-46af-80ea-fd43bdb8109d.gif)
