### ISSUE TITLE
Unexpected error pops up when Python remote

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6905]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/156976803-53d1b7f6-5636-4039-b260-6668c293b50c.png)

**Steps to Reproduce**
1.Launch VS and create new python application
2.Right the default environment and install package 'debugpy' 
3.Typing code in python file and set a breakpoint
![image](https://user-images.githubusercontent.com/59192491/156977599-4dbee0a3-8fd9-454e-b02f-7a12801ee7bd.png)
4.Run this with CTRL+F5 then attach to tcp://localhost:5678 and it stops at the breakpoint 

**Expected behavior**
No error pops up and hits the breakpoint

**Actual behavior**
Unexpected error pops up 
![Screenshot 2022-03-07 133647](https://user-images.githubusercontent.com/59192491/156978044-349e684b-9326-46c0-9fe6-58cd9ee507b0.png)
Even though I restarted VS, the squiggly line under debugpy still exists

**Additional context and screenshots**
![python_remote-debugpy](https://user-images.githubusercontent.com/59192491/156978467-de714492-b740-44db-884d-c7ecf598a843.gif)

**Comment by StellaHuang95** [comment]
I can't repro this in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 1.0 [32411.352.main]
![Animation2 - debugger2](https://user-images.githubusercontent.com/100439259/163634624-7504b4bb-4d97-4386-86c5-57c7c4e1428d.gif)
