### ISSUE TITLE
Invalid symbols in Django projects.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6906]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/156981756-913630fd-de6a-42d0-b6a2-930bfa3fec95.png)

**Steps to Reproduce**

1. Create Blank Django Web Project.

**Expected behavior**

There are no invalid symbols.

**Additional context and screenshots**

BTW, I can repro this in **web-based** Projects. (Python Application cannot repro.)

![image](https://user-images.githubusercontent.com/82852072/156982407-e0ce4e30-0edc-4502-a851-76622d0ce699.png)

**Comment by StellaHuang95** [comment]
I can't repro this in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 1.0 [32411.352.main]

![image](https://user-images.githubusercontent.com/100439259/163605070-2f2b6cb0-4e2a-4024-bd3f-dd2daad9ac54.png)
