### ISSUE TITLE
Failed to close VS.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6908]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/157175986-a6434e02-109d-4cdf-9e85-a26fd13dc1e7.png)

**Steps to Reproduce**

1. Create a Python Application project.
2. Close VS.

**Expected behavior**

Closed VS successfully.

**Additional context and screenshots**

Failed to close VS.

![image](https://user-images.githubusercontent.com/82852072/157176876-1122c240-4ac7-4658-ad88-5ae5b2f4c2f5.png)

BTW, When closing the folder, nothing happens.

![image](https://user-images.githubusercontent.com/82852072/157177319-c97a7b43-6804-4f90-a996-865dc8e8e2f7.png)

**Comment by StellaHuang95** [comment]
I can't repro this in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 1.0 [32411.352.main]
