### ISSUE TITLE
Test file discovery for pytest framework is not working

### ISSUE THREAD

**Issue by VeggieMonster** [microsoft/PTVS#6909]
**Describe the bug**
Test file discovery for pytest framework is not working so no tests are showing in the test explorer. 

**Steps to Reproduce**
Do procedure like in the following link decribed.

https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2022#configure-testing-for-python-without-a-project

**Expected behavior**
Test should be displayed in the test explorer.

**Additional context and screenshots**
![shoot1](https://user-images.githubusercontent.com/100716707/157204311-24ead6b4-c7e3-4cf4-a13b-e78845dc4a2e.JPG)

![shoot2](https://user-images.githubusercontent.com/100716707/157204330-a460a818-d048-4aa8-ae67-e34be7a73fad.JPG)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: Microsoft Visual Studio Professional 2022 (64-Bit) Version 17.0.2
PTVS version: 17.0.21293.2
Python version: 3.10.2

**Comment by StellaHuang95** [comment]
Hello @VeggieMonster, have you tried to install/enable pytest package in your active python environment? That might be the cause. Let us know if it does not work. Thanks.
![image](https://user-images.githubusercontent.com/100439259/160459730-39d2cdc6-9aa7-4776-8262-623b24681f41.png)
![image](https://user-images.githubusercontent.com/100439259/160459782-4a2724ed-e6ae-4011-9b51-a79fb3fd2d7e.png)

**Comment by StellaHuang95** [comment]
@VeggieMonster Also, I noticed you were using ProjectSettings.json to configure testing, you'll need to use a PythonSettings.json file.

**Comment by VeggieMonster** [comment]
@StellaHuang95 You are right. I have no PythonSettings.json in my folder structure.
I add this file with only the following content:
  {
      "TestFramework": "pytest"
  }
The rest comes than from pytest.ini

I remember that I have notice that the test framework info was written in file of ProjectSettings.json which was created by Visual Studio and I didn`t realy realized that there is PythonSettings.json neccessary. These two names look so similar.
Thanks for this hint.
