### ISSUE TITLE
IDE crashes when developing python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6911]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE-crashes-when-developing-python/1682988)._

---
[severity:Other] [regression]
When debugging python with python 3.6 or python 3.9 environments the IDE will frequently crash when opening files for write mode, this causes VS to close with no warning.
Subsequently after it restarts it will crash the next time you try to debug the python application.
After a second crash this revers to the point where it crashes on trying to open a file for writing.

---
#### Feedback Bot on 3/3/2022, 06:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report including a code snippet if that is necessary or the steps to reproduce the problem?

thanks
