### ISSUE TITLE
Why Pylance message warning box splashes so often

### ISSUE THREAD

**Issue by VeggieMonster** [microsoft/PTVS#6914]
**Describe your question**
I have different Python projects and using Visual Studio 2022 V 17.1.1.
When I working on those projects there very often comes a warning box with the message of "Pylance language server does not support Python 2.x. Type checking will be performed as in Python 3.x."

This message box also appears sometimes 2-4 simultaneously.

**What have you tried?**
Seraching in your github but doesn`t found any infos how to resolve this.

**Additional context**
![PylanceWarnMessage](https://user-images.githubusercontent.com/100716707/157850805-d12006dd-d9d0-4889-a4f0-ebf055458207.JPG)

[VersionInfos.txt](https://github.com/microsoft/PTVS/files/8231180/VersionInfos.txt)

**Comment by AdamYoblick** [comment]
Python 3.10 support has been added and will be in the next release. This problem will go away once that happens. 😄
