### ISSUE TITLE
Strange error message without detailed infos

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6922]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Strange-error-message-without-detailed-i/1690051)._

---
There is a pop up message that tolds me that I`am using Python 0.0 and when I clicking the link "More info" nothing happens.

---
#### Feedback Bot on 3/11/2022, 01:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
This has to do with PTVS not supporting python > 3.9. It has been fixed and will be in the next release in April.
