### ISSUE TITLE
How can I change the max line lenght of the Python formatting in VS 2022 ?

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6923]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/How-can-I-change-the-max-line-length-of-/1689411)._

---
[severity:It bothers me. A fix would be nice]
! [image.png] (https://aka.ms/dc/image?name=Bacf52d93c8fb493696ea52e344dd5899637825231667428977_20220310-163246-image.png&tid=acf52d93c8fb493696ea52e344dd5899637825231667428977)

Why don't I have the same options as in this example?
https://docs.microsoft.com/fr-fr/visualstudio/python/formatting-python-code?view=vs-2022

---
#### Feedback Bot on 3/10/2022, 06:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Python supports three open source formatters, and each have their own way of supplying configuration options (no longer through the VS IDE). Usually this is done via a config file. 

For example, the default formatter is "black" (https://github.com/psf/black). Instructions on how to change config settings are at https://black.readthedocs.io/en/stable/usage_and_configuration/index.html
