### ISSUE TITLE
can not debug both python and C code

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6924]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/can-not-debug-both-python-and-C-code/1686823)._

---
[severity:It's more difficult to complete my work]
https://github.com/MicrosoftDocs/visualstudio-docs/issues/7750
if I enable native code debugging, only debug C++ code, but cannot step into Python code.
if I disable native code debugging, only step into python code, cannot step into C/C++ code.

---
#### Feedback Bot on 3/8/2022, 06:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
Problems discussed in the issue linked above were satisfactorily resolved, so the only thing remaining is various PTVS bugs around mixed-mode in newer Python versions, which are tracked in separate issues.
