### ISSUE TITLE
Running Pylint does not recognized installed pylint 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6925]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Running-Pylint-does-not-recognized-insta/1684097)._

---
Pylint is installed in the custom python environment
! [image.png] (https://aka.ms/dc/image?name=Bd31daacbe3ac46ea96d442de01ae4027637819995121316000_20220304-150512-image.png&tid=d31daacbe3ac46ea96d442de01ae4027637819995121316000)

Executing Pylint via solution explorer/python/run pylint gives this error message:
! [image.png] (https://aka.ms/dc/image?name=B05da578405d34b3e9049c28d6373c425637819996273662675_20220304-150706-image.png&tid=05da578405d34b3e9049c28d6373c425637819996273662675)

"Run the command without installing the packages" executes pylint though. Selecting the install missing packages option makes no difference, eg pylint is executed but the next time the same error message is displayed.

Here is a link to an old item from VS2017 which asks to create a new report if the issues reappears. 
https://developercommunity2.visualstudio.com/t/Run-PyLint-Does-Not-Recognize-That-Pylin/7246?entry=problem&ref=native&refTime=1646402481267&refUserId=734272ef-3767-60d0-bb9e-1351c55450de

---
#### Feedback Bot on 3/6/2022, 07:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi, I was not able to repro this. I created a custom env with Pylint installed, but was able to execute it. Could you verify if your custom environment is activated? Thanks.

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
