### ISSUE TITLE
Visual studio Community 2022  Project cannot be launched because startup file is not specified

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6927]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-studio-Community-2022--Project-ca/1683278)._

---
[severity:It bothers me. A fix would be nice]
It seems very complicated use visual studio for staring development web project page, even if use  search engine could be found many tutorial but when try with visual studio community could not found project explorer even if check on view menu.
If start with single web project menu by selecting web project new file HTML file  it displayed message “failed to launch project”  (the project can not be launched because startup file is not specified).
Could not understand  whet it refer to startup settings (python???) ever try to set it seems not work.
Have tried on search engine but none works.

```
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <p> hello </p>
</body>
</html>
```

---
#### Feedback Bot on 3/3/2022, 09:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/4/2022, 02:24 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there! We do have the Solution Explorer tool window to create & manage your solutions and projects and to view & interact with your code. It can be found in View -> Solution Explorer. In terms of your other questions, can you please provide sample project/screenshot/gif that shows the problem so we can investigate? Thank you!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
