### ISSUE TITLE
Unable to resolve the sub class in a separate assembly/namespace.  No Intellisense

### ISSUE THREAD

**Issue by brianwvincent** [Microsoft/PTVS#693]
Hello,

So I've been using IronPython for a little while; I'm consistently able to create .NET assemblies, import them into a python script, and execute everything.  BUT, I've NEVER been able to create a .NET assembly that inherits from a class in a separate .NET assembly (both located in the same directory) and use it in a Python project.  It always tells me "Unable to Resolve '<Namespace-here>', Intellisense may be missing for this module."  

I've added the necessary search paths, imported the parent namespace, just about everything I can think of.

What's crazy is that it works in the IronPython Interactive mode!  But the exact same code in the script results in [again] "Unable to Resolve '<Namespace-here>', Intellisense may be missing for this module." 

Can you please help??

**Comment by zooba** [comment]
Can you show a code example of what you've got? Just the Python code will probably be enough (but make sure you include all of it - I'd expect a `clr.AddReference` call or similar, and a reference in your project).

**Comment by brianwvincent** [comment]
Wow, thanks for the fast reply!!

Ok, I've attached 2 screen shots (let me know if you can't see them).  The first [Help1.jpg] shows the C# project/.NET assembly inheriting from another (located in the same directory as itself).  The second [Help2.jpg] shows the Python project and no intellisense.  While working with other assemblies, I haven't yet had to explicitly add a reference to my project, the intellisense on other assemblies have always worked.  As an example, in Help2.jpg, you can see I've instantiated the base class with no problems.

Again, I really appreciate your help!

![help1](https://cloud.githubusercontent.com/assets/6958050/9125164/92250fdc-3c52-11e5-8266-d3ccb31e88de.JPG)

![help2](https://cloud.githubusercontent.com/assets/6958050/9125166/97b9800e-3c52-11e5-9890-ff04c0827181.JPG)

**Comment by zooba** [comment]
So right now PTVS is a bit more strict with its IntelliSense than IronPython is when running. This is something we're looking into improving for the next release, but right now, you'll also need to call `clr.AddReference("BriansDataLogger")` and *maybe* add a direct reference to the DLL under the References node (this may be unnecessary with the search path, or the search path may be automatic - it's been a while since I've worked on this part).

**Comment by brianwvincent** [comment]
Unfortunately, I've tried this as well :( and it still doesn't work.  Here's a screen shot of the everything.


![help3](https://cloud.githubusercontent.com/assets/6958050/9125453/df830f6a-3c55-11e5-92f2-a4bfc7b1724c.JPG)

**Comment by brianwvincent** [comment]
This might help as well...when I "print clr.References" I see this:  (You can see that my DLL is already loaded but the intellisense just isn't picking it up...Intellisense is picking up all the other DLLs though.  That's why I can't help but think it has to do with the inheritance)

![help4](https://cloud.githubusercontent.com/assets/6958050/9143088/f1496c28-3cf8-11e5-8f00-6f712e98303e.JPG)

**Comment by zooba** [comment]
Where does `BaseDataLogger` come from? DataLogging? If it's a separate assembly, maybe PTVS is failing to load it when getting the base class of `BWVDataLogger` and swallowing a .NET/IronPython exception.

Does it work if you add a `clr.AddReference` call for the other DLL?

**Comment by brianwvincent** [comment]
BaseDataLogger lives in the DataLogging assembly.

Unfortunately, it doesn't work if I add "clr.AddReference" to the both DLLs.  Everything [intellisense] works as expected if I execute the same lines in the Interactive window though.

**Comment by brianwvincent** [comment]
Ok, interesting discovery!  Apparently, adding the "clr.AddReference" line to the script (as both you and the documentation suggests) resolves the problem BUT ONLY for PTVS 2.1.  The same code DOES NOT resolve the problem with PTVS 2.2!

**Comment by zooba** [comment]
If this still occurs in the latest release, feel free to provide more information. However, be aware that we are not prioritizing IronPython support very high at the moment as we'd prefer to focus on other features.
