### ISSUE TITLE
PythonLanguageClient handling workspace folders in non-standard way

### ISSUE THREAD

**Issue by debonte** [microsoft/PTVS#6935]
This came up in the LSP Weekly Sync meeting today. [PythonLanguageClient::OnSendToServer](https://github.com/microsoft/PTVS/blob/main/Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs#L483) is modifying the LSP initialize message to claim that workspace folders are supported even though VS does not support them. The recommendation was to instead detect that VS does not support workspace folders (based on capabilities?) and react accordingly on the server side.

There's a 2-3 minute discussion about this starting at 8:45 in the [meeting recording](https://microsofteur-my.sharepoint.com/:v:/g/personal/dirkb_microsoft_com/ES5fsp5-cjNOmM99d1_v4CwBQbVnwdi6MBaUA4SuPN2Zjw).

Afterwards they discuss what [SendDocumentOpensAsync](https://github.com/microsoft/PTVS/blob/main/Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs#L390) is doing (also unexpected), which is likely related.

**Comment by AdamYoblick** [comment]
Pylance has a list of client capabilities, so we should be able to detect if we're running in VS or not and run different logic if needed.

**Comment by StellaHuang95** [comment]
For now, I'll go ahead and close this issue since it doesn't seem to be causing any immediate problems in PTVS. If we receive bug reports related to this issue or if we touch this part of the code in the future, we can certainly consider refactoring it in a more standard way.
