### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\x91'

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6940]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SyntaxError:-Non-UTF-8-code-starting-wit/1690614)._

---
I cannot run some files in a project. When I run the file, it gives me a syntax error to which I cannot solve.

---
#### Feedback Bot on 3/13/2022, 11:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thanks for your report. Could you please give us the version of Visual Studio and detailed repro steps? Thanks.

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
