### ISSUE TITLE
Spaces errantly added to other sections of my code when I paste, breaking functionality

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6941]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Spaces-errantly-added-to-other-sections-/1690765)._

---
[regression] [worked-in:VS 2019 16.11.11]
I am using VS 2022 to work on a python/django web project. When editing an HTML file that is using the Django Template Language I have a line in my code that is as follows: `<a href="{% url "dashboard:dashboard" %}" class="side-nav-link">`

Whenever I paste anything in this document, it adds a space between the " and d in dashboard, resulting in this broken line of code: `<a href="{% url " dashboard:dashboard" %}" class="side-nav-link">`. This causes an exception and is incredibly annoying. 

I can't find what setting is causing this and how to disable it. In my recording, you can see when I pasted a new line onto Line #50, it changed the text on Line #45 as well.

---
#### Feedback Bot on 3/13/2022, 07:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thank you for your report. Unfortunately, we currently do not have special support for Django template editing. Please use single quotes when nesting. Please re-open the ticket if that does not resolve your issue. Thanks.
