### ISSUE TITLE
VS 2022: Formatting Python document (Ctrl+K,D) generates error if it doesn't end with empty line

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6945]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022:-Formatting-Python-document-Ctr/1698248)._

---
Formatting Python document (Ctrl+K,D) generates error if it doesn't end with empty line.

! [image.png] (https://aka.ms/dc/image?name=Ba0e49d874a184466888af64ec8e4deb2637834760114774193_20220321-191331-image.png&tid=a0e49d874a184466888af64ec8e4deb2637834760114774193)

---
#### Feedback Bot on 3/22/2022, 06:26 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
dup of #6752
