### ISSUE TITLE
IntelliSense in Python editor does not see loop variable

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6946]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IntelliSense-in-Python-editor-does-not-s/1697277)._

---
IntelliSense in Python editor does not see loop variable - see screenshot.
I'm using Python 3.11.0a6.

! [image.png] (https://aka.ms/dc/image?name=B6d214b06c2834ab0847256fcac7ea1f1637833848774331191_20220320-175437-image.png&tid=6d214b06c2834ab0847256fcac7ea1f1637833848774331191)

---
#### Feedback Bot on 3/21/2022, 07:17 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Will be fixed in 17.3 Preview 3.
