### ISSUE TITLE
LSP getSemanticToken constantly being requested by client

### ISSUE THREAD

**Issue by bschnurr** [microsoft/PTVS#6947]
**Describe the bug**
see this comment https://github.com/microsoft/PTVS/issues/6859#issuecomment-1083682296

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**
[A clear and concise description of your expectation]

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]

**Sample Code**
```
XXX
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [Can be found under "Help->About Microsoft Visual Studio"]
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products->Python with Pylance"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```

**Comment by randomascii** [comment]
What is the status of this? I've been doing a lot of Python development and I often have a dozen .py files loaded into VS 2022. node.exe constantly rescans all of them and the cumulative CPU load ends up being 100% of a CPU core. That is, https://github.com/microsoft/PTVS/issues/6859 shows that a single Python file can use 20% of a core, so 5+ files can use 100% of a core. This CPU usage goes on indefinitely - infinitely - causing power wastage, battery rundown, fan noise, etc.

I like the syntax checking of Python files, but I'm going to have to turn it off until this is fixed.

**Comment by bschnurr** [comment]
I have a fix on the Pylance side, the VS LSP client team is also going to prevent calling semantic tokens for files not visible.

Unfortunately the update rate of VS is very slow.
