### ISSUE TITLE
Python intellisense replaces another code

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6956]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-intellisense-replaces-another-cod/10004698)._

---
[severity:It's more difficult to complete my work]
In my python code, when I press TAB for accepting the intellisense suggestion it replace more code than needed.

For example:
- When my code is: `print(find_words(` and then I accept `read_matrix` suggetion it replaces the whole line!
- When I type in parenthesis it deletes the second bracket.

And other issues with the intellisense - when I press TAB for accepting suggestion in code snippet (like `for` code snippet), it jumps to next field of the snuppet rather than complete the suggestion.

Can it be like the C# intellisense?

---
#### Feedback Bot on 4/6/2022, 05:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Duplicate #6885
