### ISSUE TITLE
No IntelliSense when import module under the solution.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6958]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/163340254-583a7660-ff4e-491f-8a28-1330b9d405c4.png)

**Steps to Reproduce**
1. Right click in SE, Add new item, Python module, module1.py
2. Enter some code in the new file:
	○ MSG = 'hello'
![image](https://user-images.githubusercontent.com/59192491/163340971-49b0191d-2e93-4583-bcdb-1621a3d74fbb.png)
3. In PythonApplication7.py:
	○ import module1
4. Check for completions:
	○ module1.MSG

**Expected behavior**
Import module1.py should with intelliSense.

**Additional context and screenshots**
No IntelliSense when import module.
![image](https://user-images.githubusercontent.com/59192491/163340710-daea9ddd-a3a4-419f-9cdd-53a2fbf2b571.png)

**Comment by debonte** [comment]
`from` gives the expected completions, but `import` does not.
Pylance issue?

**Comment by ttSpace** [comment]
In today's build, I had to restart VS to get IntelliSense.

![image](https://user-images.githubusercontent.com/82852072/163781714-580f7f29-45a9-4ee3-96a7-3037bb2c1c4d.png)

![image](https://user-images.githubusercontent.com/82852072/163779760-72d0840b-62d5-4350-9e5a-83c2776fedee.png)
