### ISSUE TITLE
Pylance doesn't work for Python 3.10+ in conda environments

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#6963]
Repro steps:

1. Install miniconda
1. Create a Python project
1. Right click Python Environments -> Add Environment -> Conda environment
1. Add the `Python 3.10` package, shown below:

![image](https://user-images.githubusercontent.com/29436557/164116875-ff1de55e-62de-47c1-8c2b-ec9e11e9a8bb.png)

When triggering intellisense, notice that pylance doc strings are not there:

![image](https://user-images.githubusercontent.com/29436557/164116976-adfabbe0-d289-495e-9028-756cdae6454f.png)

When doing the exact same thing with conda, but selecting Python 3.9.7 instead of Python 3.10, it works:

![image](https://user-images.githubusercontent.com/29436557/164117021-99b41942-2fec-4490-b6a0-22f3974feeec.png)

**Comment by bschnurr** [comment]
I believe this is related our our scraper.py failing on python 3.10

**Comment by AdamYoblick** [comment]
Specifically, Conda python 3.10. When I run with 3.10 from python.org, it works just fine.

**Comment by StellaHuang95** [comment]
@AdamYoblick Are you still able to repro this? I created a conda env with python 3.10 but was able to see the doc strings. Just want to check with you first before closing it by mistake.

**Comment by AdamYoblick** [comment]
It's possible that @bschnurr fixed the cause of this bug in pylance. Bill?

**Comment by bschnurr** [comment]
can't repo anymore either.
