### ISSUE TITLE
Live Share: The 'TerminalWindowPackage' package did not load correctly.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6966]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/164394083-0b98c254-96d4-4e5a-ad7c-69a2fb9a32c3.png)

**Steps to Reproduce**
1. Create a Python Application.
2. Open Live Share, make connection between host and client.
3. Click Share Terminal(Read-only)

**Expected behavior**

No warnings and no errors.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/164394644-688d7800-8e09-4b7a-80b9-bcbaffc4a26d.png)

**Comment by StellaHuang95** [comment]
Can't repro in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 1.0 [32411.352.main]
![Animation2 - liveshare](https://user-images.githubusercontent.com/100439259/164537576-02e1a1bf-5fcc-454b-84cb-ee4390a1d0a2.gif)
