### ISSUE TITLE
Project structure is not displayed in SE windows under non-administrators.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6967]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/164394083-0b98c254-96d4-4e5a-ad7c-69a2fb9a32c3.png)

**Steps to Reproduce**
1. Create a Python Application.
**Note: Launch VS under a non-admin user.**

**Expected behavior**

The project structure shows in the SE window.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/164407989-ab8f317b-61e9-480a-965e-c8c6ba4bdefc.png)

**Comment by StellaHuang95** [comment]
Hi @ttSpace, could you be more specific about "Launch VS under a non-admin user" and the repro steps? Are you saying to create a local user account, log into that account, and run VS with that account? Thanks.

**Comment by ttSpace** [comment]
@StellaHuang95 Yes, that is what I mean. Create a local user account, log in to the account, and then use the account to run VS. In today's build ```17.2.0 Preview 2.0 [32228.339.main]```, Python Package```17.0.22047.2``` , it cannot be repro.

![image](https://user-images.githubusercontent.com/82852072/164965716-1b1d9ee0-89fc-4d4c-882c-e38cb7988ea5.png)

**Comment by StellaHuang95** [comment]
@ttSpace Good to know it doesn't repro. Thanks!
