### ISSUE TITLE
Live Share: The 'TerminalWindowPackage' package did not load correctly.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6973]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/165041981-c4f8b75e-dbe1-42ee-892c-f1e4a546f03d.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Open Live Share, make connection between host and client.
3. Click Share Terminal(Read-only)

**Expected behavior**

No warnings and no errors.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/165042445-91f148b2-556b-4f70-ae10-20f6721bc318.png)

![warningbox](https://user-images.githubusercontent.com/82852072/165042264-2f989765-03d6-4166-ae71-a3f2ed8c1844.gif)

**Comment by StellaHuang95** [comment]
dup of #6966 

Still not able to repro this. @AdamYoblick Is there anything else I could do or test before closing this issue? Just want to make sure this doesn't get re-opened the third time. Thanks.
![Animation2 - liveshare v2](https://user-images.githubusercontent.com/100439259/165171858-b69ffead-de66-4a80-998c-fa212cc446c5.gif)

VS Version:
![image](https://user-images.githubusercontent.com/100439259/165172056-c76d6630-da49-4d5f-9ba9-b44cc700d180.png)

**Comment by AdamYoblick** [comment]
The repro looks like there are two windows, one is the live share host and the other is the guest. Did you connect like that?

**Comment by StellaHuang95** [comment]
Just tested with Adam but still couldn't repro. @ttSpace Is there anyone else on the CTI team can repro this on a different machine? If not, could you try repairing your VS installation and let us know if the problem still persists? Thanks!

**Comment by ttSpace** [comment]
In today's build ```17.3.0 Preview 1.0 [32425.303.main] ```, Python Package ```17.0.22114.1 ```, I can repro this. After restarting VS twice, this error is gone.

![image](https://user-images.githubusercontent.com/82852072/165208035-05ab7af8-39f1-48b7-be1e-3eefe7a6e1e4.png)

**Comment by StellaHuang95** [comment]
Sounds good, I will close it since it doesn't repro. Thanks.
