### ISSUE TITLE
Unexpected error in python development: unresolved import '__main__'

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6975]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unexpected-error-in-python-development:-/10012849)._

---
When developing a modular python code (with actual custom modules imported) you can use import \_\_main__ from a module to extract data from main.

The \_\_main__ keyword should not be interpreted by Visual Studio as a module name

That's not what it's actually happening: it's showing a warning in the "Error list" view which says: unresolved import '\_\_main__'

---
#### Feedback Bot on 4/13/2022, 10:57 PM: 

(private comment, text removed)
#### Bill Schnurr [MSFT] on 4/15/2022, 00:03 PM: 

(private comment, text removed)
#### Dario Panico on 4/19/2022, 00:18 AM: 

(private comment, text removed)
#### Bill Schnurr [MSFT] on 4/20/2022, 11:06 AM: 

(private comment, text removed)
#### Dario Panico on 4/21/2022, 00:36 AM: 

(private comment, text removed)
#### Bill Schnurr [MSFT] on 4/21/2022, 02:43 PM: 

(private comment, text removed)
#### Bill Schnurr [MSFT] on 4/21/2022, 03:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dariopnc** [comment]
@dariopnc opened it originally: I'm here for further needs

**Comment by int19h** [comment]
Note that `__main__` is not a keyword - it is, indeed, a module name, it just happens to be the name used by Python itself for the main module when registering it in `sys.modules`. 

Either way, code completion should probably consider it "always present", but resolving members might be trickier. When there's a project, we know the startup file, so we could map it to that.
