### ISSUE TITLE
In VS2022, selecting the "Python Environment" tab kills VS.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6977]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022에서-Python-환경-탭을-선택하면-VS가-강제-종료됩니/10010013)._

Translated to English by Bing:

1. Add Python environment with anaconda command prompt. (conda create --name ...)
2. Install the package with anaconda command prompt. (pip install ...)
3. In Anaconda Navigator, the environment installed with the command prompt appears in the list and works normally.
4. After starting VS2022, if you click the Python Environment tab, an hourglass appears for a while, and then VS is forced to close.
     * For a while, the Python environment added by Anaconda Command Prompt does not appear in the environment list in the Python Environment tab.
5. In order to prevent the Python environment tab from appearing, you need to select the Python environment tab. If you select the Python environment tab, VS2022 is forced to close and you cannot use it.

---
1. 아나콘다 명령 프롬프트로 Python 환경을 추가합니다. (conda create --name ...)
2. 아나콘다 명령 프롬프트로 패키지를 설치합니다. (pip install ...)
3. 아나콘다 네비게이터에서는 명령 프롬프트로 설치한 환경이 목록에 나타나고, 정상 동작됩니다.
4. VS2022 구동 후, Python 환경 탭을 클릭하면 잠시 동안 모래시계가 나타난 후, VS가 강제종료됩니다.
※ 잠시동안의 Python 환경 탭의 환경 목록에는 아나콘다 명령 프롬프트로 추가한 Python 환경이 나타나지 않습니다.

Python 환경 탭이 나타나지 않게 하기 위해서는 Python 환경 탭을 선택해야 하는데,
Python 환경 탭을 선택하면 VS2022가 강제종료 되어서 사용을 할 수 없습니다.

**Comment by AdamYoblick** [comment]
I was able to repro this using the repro steps. The issue is that the user hasn't installed the Python package in the anaconda environment, and our code is trying to get Python Interpreter information from that environment. We assume the python.exe is going to be there, but that's a bad assumption.

Our code needs to not display that environment if there's no python package in the anaconda environment, which is an easy fix.

**Comment by AdamYoblick** [comment]
This has been fixed locally. We no longer display environments that do not have a python package installed. Once you install python into the conda environment, it will show up in the environments list. PR is incoming.

**Comment by sjson** [comment]
Thank you for your effort. Thank you.
수고하셨습니다. 고맙습니다.
