### ISSUE TITLE
Error activating the remote language server, Torch.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6979]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-activating-the-remote-language-ser/10011998)._

---
[severity:It bothers me. A fix would be nice] [regression]
![image.png](https://aka.ms/dc/image?name=B7a724d7c3e65478f9edee86f0cc9eb33637853994348186440_20220412-153034-image.png&tid=7a724d7c3e65478f9edee86f0cc9eb33637853994348186440)

---
#### Feedback Bot on 4/12/2022, 10:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can you please provide repro steps so we can investigate? Thank you!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
