### ISSUE TITLE
why tab character setting is changing automatically?

### ISSUE THREAD

**Issue by noisia04** [Microsoft/PTVS#698]
hello.
i trying to using visual studio 2015 community edition and python 3.4. and, i prefer to use a tab character instead of many spaces. but when i restarting visual studio 2015, tab character setting is changing automatically to "insert spaces". why? and how can i fix this settings permanently?

![1](https://cloud.githubusercontent.com/assets/8155307/9139035/94ed2ea0-3d62-11e5-93c8-47ba967ca76b.png)

**Comment by Gromph** [comment]
I'm running into the same problem. I've tried signing out of visual studio, reinstalling python tools, resetting settings, and I've reproduced on another machine.

**Comment by zooba** [comment]
It's a very good question. I haven't been able to reproduce the issue easily, so I'd guess there's some sort of configuration issue.

@Gromph Are you using English Visual Studio?

**Comment by Gromph** [comment]
Ya I'm using English Windows 10 and Visual Studio

**Comment by clarktx** [comment]
Same problem occurs for me.  'Keep tabs' option is not be retained across a VS restart.  

New install of MVSCom 2015, PT plugin v2.2, Win10 Home Edition.

Clue: I also noticed that if you try to 'export settings', the python language settings are not available under the Text Editors tree branch.

![image](https://cloud.githubusercontent.com/assets/6581411/11454959/c109a1ee-9609-11e5-9522-b18214bd0af2.png)

From diagnostics:
 Microsoft.PythonTools, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.Analysis, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.BuildTasks, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.Debugger, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.Django, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.IronPython, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.IronPython.Interpreter, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.Profiling, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.Uwp, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00
  Microsoft.PythonTools.VSInterpreters, Version=2.0.2.2015, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, FileVersion=2.2.30718.00

**Comment by Gromph** [comment]
Installing Visual Studio 2015 Update 1 and checking on Python Tools (November Update) in the installer fixed this problem for me.

**Comment by clarktx** [comment]
Confirmed fix.  Thanks @Gromph!

**Comment by sergeiv-gridstore** [comment]
have repro with VS2015 update 2; except that spaces revert to tabs.

I don't remember having this prior to Update 2.

**Comment by zooba** [comment]
We believe this is fixed in VS 2017 completely, and won't be trying to update VS 2015 again if there's any more fix required there, so I'm closing this issue now.

**Comment by eugeneko** [comment]
This bug makes me insane. I set this setting five times yesterday's evening and this morning it was reverted again.
One minor thing to mention: I got it with C++ settings.

**Comment by zooba** [comment]
Are you using VS 2017?

C++ defaults to tabs rather than spaces, so if your settings are being reset for some reason then you will see C++ switch back to tabs. If you are using VS 2017, please use the "Report a problem" button in VS and report it that way - we only monitor Python issues here.

**Comment by eugeneko** [comment]
Nope, I'm using VS 15 and the bug appeared after update. I'll update to 2017 later tho.

I know that you support only Python here, just mentioned that it's probably generic Visual Studio issue unrelated to the Python.

**Comment by cephalopodMD** [comment]
This is happening for me in C# on VS 2017 (15.6.2).
