### ISSUE TITLE
Python print are in different colors

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6980]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-print-are-in-different-colors/10012612)._

---
print show up in two different colors at random. It has been like this for a while. I am working on a Django project if that helps.

---
#### Feedback Bot on 4/13/2022, 10:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can you please provide repro steps so we can investigate? Thank you!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
