### ISSUE TITLE
VS 2019 Running any Python Code uses all RAM and does not execute anything.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6981]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2019-Running-any-Python-Code-uses-all/10011942)._

---
[severity:I'm unable to use this version]
A few days ago, I was experimenting with python VS 2019 (32 bit) and asked it to print some very large number (something like 2**140174832054). After running up all my available RAM (10GB), it hung and never completed the operation. I stopped the debugger and tried to print some smaller value, but nothing works anymore. I even tried to print("Hello World"), but that is hanging too. It'll run up to around 5 gb of ram, and then will all of a sudden drop to ~1.5 gb and remains dormant. I've restarted my computer, updated VS, completely uninstalled and reinstalled it, and even updated from Python version ~3.7 (32 bit) to 3.9 (64 bit). I am in school and am no longer able to complete any work.

My computer specs:
Intel i7-8550U
16 gb RAM
512 gb NVME SSD

---
#### Feedback Bot on 4/12/2022, 10:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Hi there! I was not able to repro this in VS2022. VS2022 uses a different debugger than 2019. Can you please try this in VS2022 and let us know if the problem persists? You can also try it in vscode, as it uses the same debugger (debugpy) as VS2022. Thank you!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
