### ISSUE TITLE
JavaScript syntax highlighting is broken when using Django Web Project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6983]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/JavaScript-syntax-highlighting-is-broken/10017608)._

---
[severity:It's more difficult to complete my work]
I have created a new Django web project in VS2019.
Inside the html layout file in the template folder
I have a `<script>` tag and a definition with a variable declaration containing the `{{  }}` or `{ }` character in a string.
When I reload the project, the javascript content color highlighting is broken.
If I remove variables containing the characters `{{ }}` or `{}` Syntax color is displayed.

---
#### Feedback Bot on 4/19/2022, 08:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Hi there! Can you please provide specific repro steps or sample code that shows the problem so we can investigate? Thank you!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
