### ISSUE TITLE
Missing options in editing Fonts and colors

### ISSUE THREAD

**Issue by FrankYou72** [microsoft/PTVS#6985]
I think the software should have, just like VS  2019, options for changing the color  in text editor for differents types of data in general (which could be applied to all suitable languages) or to allow, just like VS 2019, editing the colors for Python files (like classes, operators, variables, built-ins, keywords, modules, etc.)

I think this is useful because it allows the user to customize the work environment the way he feels more confortable with and this is an excellent feature that already existed in previous version (VS 2019).

**Comment by StellaHuang95** [comment]
dup of https://github.com/microsoft/PTVS/issues/7082
