### ISSUE TITLE
Embedded Python 3.10 interpreters not detected by debugger

### ISSUE THREAD

**Issue by Artfunkel** [microsoft/PTVS#6986]
**Describe the bug**
The embedded Python 3.10.2 interpreter within Blender 3.1 is not recognised by PTVS. You can attach to the process, but not debug any Python scripts running within it. Neither Python nor Python+Native debugging work.

_This bug is a duplicate of #6930, which was closed without having been fixed. I am not able to re-open that issue._

**Steps to Reproduce**
1. [Download Blender 3.1](https://download.blender.org/release/Blender3.1/)
2. Start Blender and wait for it to finish loading
3. Try to attach to blender.exe from Visual Studio

**Expected behavior**
Python is displayed in the "Type" column of the Attach to Process window, and Python breakpoints are hit in script files.

This image shows Blender 3.0 (Python 3.9) and Blender 3.1 (Python 3.10) side-by-side. Note how Python is only detected in Blender 3.0.

![image](https://user-images.githubusercontent.com/3618066/163262545-0fe24553-0a61-45e1-ad3c-b5b77e5ae485.png)

**Additional context and screenshots**
Python scripts within earlier versions of Blender can still be debugged. This bug persists even if I delete the python310.dll file that Blender ships with and let it fall back on my system installation.

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: VisualStudio.17.Preview/17.2.0-pre.5.0+32422.2
PTVS version: 17.0.22089.1
Python version: 3.10.2
Debugger Type (if applicable): No idea, can't see anything about this in the settings

**Comment by VascoPi** [comment]
I confirm, the same story with Version 17.3.0 Preview 1.0.

**Comment by DagerD** [comment]
Please add python 3.10 support.

**Comment by bschnurr** [comment]
looks fixed

**Comment by Artfunkel** [comment]
Confirmed fixed, at long last!

**Comment by bnagirniak** [comment]
Confirmed fix with 17.3.0 Preview 2.0

**Comment by DagerD** [comment]
Confirmed. Thank you!
