### ISSUE TITLE
Failed to add environment to list when the environment already added to Global environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6987]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/165719977-c5cd62c1-70dc-44b2-8812-c6cd5b3d1401.png)

**Steps to Reproduce**
1.Launch VS and create a pythonapplication
2.Add an environment that isn’t automatically detected ie is not shown in the list. Pick <Custom> and browse to the environment 
   folder.Browse to a virtual environment, detect all env parameters. 
3.Check 'Make this environment avaiable globally',name the environment 'globalenv07'
4.Click Add button, ensure that the environment 'globalenv07' add successfully.
5.Repeat step2,browse to the same virtual environment
6.Click Add button, ensure that the environment 'env' add successfully

**Expected behavior**
The 'env' should be added in environment node successfully

**Additional context and screenshots**
![existing_env](https://user-images.githubusercontent.com/59192491/165721735-cf95b86f-66ba-4e4d-a0d6-8c6a0bf529ef.gif)

**Comment by AdamYoblick** [comment]
I believe this behavior is "As Designed". You're trying to add an environment that you've already added to the project. The fact that you're adding it through a different codepath is irrelevant. It's the same env, so it doesn't get added twice.

@judej Can you watch the gif above and confirm if my assessment is correct here?
