### ISSUE TITLE
Live Share: The shared window will crash during join in the server.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6992]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/167241955-acd88802-b0b8-4ea5-962e-d15c6cbf8366.png)

**Steps to Reproduce**
1. Create a Python Application.
2. Click LiveShare.
3. Visual Studio Live Share Firewall Access, click Ok.
4. You should click allow access.
5. You will come to Visual Studio Live Share page. Click Copy invite link button.
6. Open this link in Explorer, then will be open the shared window 

**Expected behavior**
The shared window is opened

**Additional context and screenshots**
The shared window will crash 
![liveshare](https://user-images.githubusercontent.com/59192491/167242212-c20d0419-1e12-48d2-999c-299f128c362e.gif)

**Comment by StellaHuang95** [comment]
@linette-zyy I can't repro this, can you test again on the latest VS? Thanks.

**Comment by StellaHuang95** [comment]
Still can't repro in the latest version. Going to close it out.
