### ISSUE TITLE
Intellisense stopped working in ptvs 2.2 RC 2013

### ISSUE THREAD

**Issue by ttustonic** [Microsoft/PTVS#70]
The Intellisense stopped working in VS 2013 with PTVS 2.2 RC installed.
My setup is as follows
1. clean installation of Python 2.7.9 32bit
2. clean installation of GStreamer SDK 32 bit from http://docs.gstreamer.com/display/GstSDK/Installing+on+Windows
3. created virtual env in _C:\Python27\virtual\gst010\_
4. in the virtual lib\site-packages is a .pth file which points to GStreamer SDK site-packages dir:
_F:\gstreamer-sdk\0.10\x86\lib\python2.7\site-packages
F:\gstreamer-sdk\0.10\x86\lib\python2.7\site-packages\gst-0.10
import os; os.environ['Path'] = 'F:\gstreamer-sdk\0.10\x86\bin;F:\gstreamer-sdk\0.10\x86\lib;' + os.getenv('PATH')_
5. After refreshing DB in Visual studio 2012/PTVS 2.1 there are a lots of gst.\* files in .ptvs directory of the virtual env. The same is with Visual Studio 2013/PTVS 2.1, and Intellisense works in both.
6. After removing PTVS 2.1 2013, installing PTVS 2.2 RC, cleaning the .ptvs directory and Refresh DB in Visual Studio, the Intellisense doesn't work. There are no gst\* files in .ptvs directory, although Intellisense in Python Environments shows gst (and others)

![ptvs21](https://cloud.githubusercontent.com/assets/5532089/7443423/2f228026-f149-11e4-80dd-34761b2070b3.jpg)
![ptvs22](https://cloud.githubusercontent.com/assets/5532089/7443422/2f21b89e-f149-11e4-9020-a0777556ac44.jpg)

**Comment by zooba** [comment]
I see multiple "gst010" environments in you list - are you sure you've opened the editor in the right one?

**Comment by ttustonic** [comment]
There's only one "gst010" environment, but there are two Python projects which use them.

**Comment by zooba** [comment]
Ah, another (separate) issue :)

I wonder whether our "improved" path resolution is at fault here. In the `.ptvs` directory there should be a file called `database.path` which will have a list of paths. Can you post the contents of that, or at least confirm whether the gst path is missing?

**Comment by ttustonic** [comment]
database.path has:
*C:\Python27\virtual\gst010\Lib\|stdlib|*
*C:\Python27\virtual\gst010\Lib\site-packages||*

**Comment by zooba** [comment]
So that doesn't include the second path from the .pth file, which probably means it doesn't exist.

We get those paths from `sys.path` within `python.exe`, and IIRC the only validation we do is checking that a directory or file by that name exists. I assume you can import `pygst` and `gst` fine when running Python directly? What shows up in `sys.path` in this case?

**Comment by ttustonic** [comment]
Yes, I can import `pygst` and `gst` and launch a simple Gst player, both in VS Python Interactive and from the virtual environment in the command prompt.
`sys.path` is 
```
>>> sys.path
['', 'F:\\gstreamer-sdk\\0.10\\x86\\lib\\python2.7\\site-packages\\gtk-2.0', 
'F:\\gstreamer-sdk\\0.10\\x86\\lib\\python2.7\\site-packages\\gst-0.10', '.', 
'C:\\Windows\\SYSTEM32\\python27.zip', 'C:\\Python27\\virtual\\gst010\\DLLs', 
'C:\\Python27\\virtual\\gst010\\lib', 'C:\\Python27\\virtual\\gst010\\lib\\plat-win', 
'C:\\Python27\\virtual\\gst010\\lib\\lib-tk', 'C:\\Python27\\virtual\\gst010\\Scripts', 
'C:\\Python27\\Lib', 'C:\\Python27\\DLLs', 'C:\\Python27\\Lib\\lib-tk', 
'C:\\Python27\\virtual\\gst010', 'C:\\Python27\\virtual\\gst010\\lib\\site-packages', 
'F:\\gstreamer-sdk\\0.10\\x86\\lib\\python2.7\\site-packages', 
'C:\\Users\\tom\\AppData\\Roaming\\Python\\Python27\\site-packages', 
'C:\\Python27', 'C:\\Python27\\lib\\site-packages']
```

**Comment by zooba** [comment]
We've already changed to use the actual `sys.path` to determine sources for Intellisense, so this should no longer occur.
