### ISSUE TITLE
VS2022 Closes-Up After a Project is Launched 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7004]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Closes-Up-After-a-Project-is-Laun/10033282)._

---
While my python project runs well under VS2019, VS2022 closes up after the same project is launched. This issue applies to Angular JS projects as well.

Indeed, it ran well until I followed the instructions given by the book, ASP.NET Core 6 and Angular, to install npm and Angular etc.

Please advise how to make it work. Thank you!

\-John

---
#### Feedback Bot on 5/7/2022, 03:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
Can you please provide some sample code or sample project that causes the problem? Thank you!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
