### ISSUE TITLE
"Go to All" doesn't work well

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7005]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/168238485-b7d3a36b-568c-427a-8cc5-728aff382def.png)

**Steps to Reproduce**
1.Launch VS, create one pythonapplication
2.Type some codes  in python file
```
def hello():
    pass
```
3.Edit->Go to->Go To All, type 'hello'

**Expected Behavior**
![image](https://user-images.githubusercontent.com/59192491/168240875-3681f5e0-5077-4762-ac2b-4cafe9fe464b.png)

**Actual Behavior**
![image](https://user-images.githubusercontent.com/59192491/168241676-5be6533d-c827-42cc-933c-d1fe5913a2fe.png)

**Comment by StellaHuang95** [comment]
Can't repro this in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.3.0 Preview 2.0 [32512.517.main]

![image](https://user-images.githubusercontent.com/100439259/168341128-c5b627e2-ab57-472a-bb59-bbad3350b06c.png)
