### ISSUE TITLE
Live Share: The 'TerminalWindowPackage' package did not load correctly. 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7006]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/168545751-76a2295b-b7d8-4846-86f2-b0fb628d995f.png)

**Steps to Reproduce**
1. Create a Python Application.
2. Open Live Share, make connection between host and client.
3. Click Share Terminal(Read-only)

**Expected behavior**
No warnings and no errors.

**Additional context and screenshots**
The 'TerminalWindowPackage' package did not load correctly. 
![image](https://user-images.githubusercontent.com/59192491/168545573-bcdb5884-4fcb-4e46-b925-5e5266c03412.png)

**Comment by StellaHuang95** [comment]
Seems like a similar issue has been filed on AzDO: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1280756. I can't repro this one but I will link to the internal ticket.

**Comment by ttSpace** [comment]
I cannot repro this in today's build ```17.6.0 Preview 1.0 [33319.311.main] ```,Python Package: ```17.0.23005.2```.
After clicking Share Terminal (Read-only), there are no warnings and no errors.

![image](https://user-images.githubusercontent.com/82852072/213618399-72a26687-9f71-45c6-bf03-5540cadc76b1.png)
