### ISSUE TITLE
Project structure is not displayed in SE windows under non-administrators.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7007]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/168978006-7adfb783-fcb3-4fc5-bb87-be1967a97c91.png)

**Steps to Reproduce**

1. Create a Python Application.
**Note: Launch VS under a non-admin user.**
(Create a local user account, log in to the account, and then use the account to run VS.)

**Expected behavior**

The project structure shows in the SE window.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/164407989-ab8f317b-61e9-480a-965e-c8c6ba4bdefc.png)

**Comment by linette-zyy** [comment]
On the latest build 17.6.0 Preview 1.0 [33319.311.main], Python Package: 17.0.23005.2, this issue is not reproduced.
![image](https://user-images.githubusercontent.com/59192491/213638451-79b91ac5-d81d-46d1-9a34-28fb52c67901.png)
