### ISSUE TITLE
Pylense can't import application in VisualStudio

### ISSUE THREAD

**Issue by petrenkonikita112263** [microsoft/PTVS#7018]
## Environment data

-   Language Server version: VS Community 2022 17.2.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda

## Code Snippet

```python
"""
Tests for CPU class
Command line: python -m pytest tests/unit/test_cpu.py
"""
import pytest

from app.models import inventory
```

## Repro Steps

1. XXX

## Expected behavior

No import's errors.

## Actual behavior

reportMissingImports Import "pytest" could not be resolved	
reportMissingImports Import "app.models" could not be resolved

## Logs

```
XXX
```

My PythonSettings in VS:

```
{
  "python.pythonPath": "C:\\Users\\Nikita\\anaconda3\\python.exe",
  "python.autoComplete.extraPaths": [ "C:\\Users\\Nikita\\anaconda3\\pkgs\\python-3.9.12-h6244533_0" ],
  "TestFramework": "Pytest",
  "Interpreter": "Global|ContinuumAnalytics|Anaconda39-64",
  "UnitTestRootDirectory": "tests",
  "UnitTestPattern": "test_*.py"
}
```

**Comment by StellaHuang95** [comment]
Hi @petrenkonikita112263, could you verify if pytest is installed in your environment?

Also, here's a [link](https://devblogs.microsoft.com/python/whats-new-for-python-in-visual-studio-16-3-preview-2/) that might be helpful for the pytest configuration.

**Comment by bschnurr** [comment]
can we see your pylance logs? 
![image](https://user-images.githubusercontent.com/1946977/170559256-2162298f-6ca1-499e-a579-c4bd961eeefa.png)

**Comment by petrenkonikita112263** [comment]
@bschnurr 

![image](https://user-images.githubusercontent.com/56109799/170562039-7a660e77-a313-45ce-8f21-91be87889183.png)

**Comment by petrenkonikita112263** [comment]
It's empty. I re-run the test
![image](https://user-images.githubusercontent.com/56109799/170562403-967780c7-f81a-41f2-a4fb-deca2bafe096.png)

**Comment by petrenkonikita112263** [comment]
```
Info: (12008) Pylance language server 2022.3.3 (pyright dd7420c5) starting
Info: (12008) Server root directory: c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist
Info: (18304) Pylance language server 2022.3.3 (pyright dd7420c5) starting
Info: (18304) Server root directory: c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist
Error: (18304) Error reading settings: TypeError: Cannot read properties of null (reading '0')
Info: (18304) No pyproject.toml file found.
Warning: (18304) stubPath typings is not a valid directory.
Info: (18304) Assuming Python platform Windows
Info: (18304) Searching for source files
Info: (18304) No source files found.
Info: (18304) Background analysis(1) root directory: c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist
Info: (18304) Background analysis(1) started
```

**Comment by petrenkonikita112263** [comment]
@bschnurr 
pythonPath is set in VS to conda.exe, I did step by step from the official website. The env by default is 'base'.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
