### ISSUE TITLE
Python f-strings need syntax highlighting for expressions inside curly braces

### ISSUE THREAD

**Issue by michael-ansolis** [microsoft/PTVS#7024]
**Describe the feature you are requesting**
I would like the code like `string = f'label {value}'` to have "value" highlighted differently than the rest of the string inside the quotes.

**Reasons for requesting this feature**
I'm currently using VS2019 for Python development and syntax highlighting is important to me because it improves readability of my code.

**Describe alternatives you've considered**
I could use other development tools, but I simply don't have access to the latest versions of most of them (company policy).

**Comment by AdamYoblick** [comment]
This works in vscode, even with code completion for the expression within the curly braces, so we need to figure out why the coloring doesn't work in VS at a bare minimum. Completions would be nice to have as well.

**Comment by StellaHuang95** [comment]
This is supported in the latest version of VS2022, please update to the latest version and try again. Thanks!
![image](https://user-images.githubusercontent.com/100439259/235813927-28b6d2b3-327e-48db-95de-f21b143365ec.png)
