### ISSUE TITLE
No intellisense when from 'PYTHONPATH'

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7026]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/172123637-b30fd809-4a81-4414-8cab-4f99b02f83e2.png)

**Steps to Reproduce**
1.Create a module7.py under D:\test_pythonpath
2.Add the module7.py path to PYTHONPATH
![image](https://user-images.githubusercontent.com/59192491/172125741-bde8825e-b73a-4a2d-a80a-24de034badaf.png)
3.Launch VS and create a pythonapplication, make sure "Ignore system-wide PYTHONPATH variables" is unchecked
![image](https://user-images.githubusercontent.com/59192491/172127164-64915c8f-c73e-428b-8534-5fe5f7679dc8.png)
4.Type sample code to get intellisense from 'PYTHONPATH'
```
import module7
```

**Expected behavior**
I can get  intellisense from 'PYTHONPATH'

**Actual behavior**
No intellisense, although i add PYTHONPATH to search path
![image](https://user-images.githubusercontent.com/59192491/172128321-2f45b65e-31c2-48b4-ad7b-f67f92c6012b.png)

![image](https://user-images.githubusercontent.com/59192491/172127372-22b3d6c4-c435-4574-96cf-c632f8549d38.png)

**Comment by StellaHuang95** [comment]
Probably related to #6831.

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/172547424-4d2f89ad-a882-4ee9-806c-095ea81dcde4.png)
In today's build, i can get intellisense from 'PYTHONPATH'. But when i checked the "Ignore system-wide PYTHONPATH variables", i still get the intellisense
![image](https://user-images.githubusercontent.com/59192491/172548582-b9b40c9d-416f-42c4-94c0-2558931ff472.png)

**Comment by linette-zyy** [comment]
@AdamYoblick 
In today's latest build:**17.6.0 Preview 1.0 [33402.156.main]**,Python Package:**17.0.23033.1**
I can get intellisense from 'PYTHONPATH'. But when i checked the "Ignore system-wide PYTHONPATH variables", i still get the intellisense
![testpythonpath](https://user-images.githubusercontent.com/59192491/216511387-f60177f3-8f03-496f-b457-22067f8a62bb.gif)

**Comment by StellaHuang95** [comment]
@AdamYoblick I believe the above behavior is expected, right? The `Ignore system-wide PYTHONPATH variables` only applies when `PYTHONPATH` is not added to Search Paths?

**Comment by AdamYoblick** [comment]
Yeah I think this is expected. Once a path is added to search paths, it doesn't matter how they were added there. In order to make them go away, you'd have to remove them from the search path.

**Comment by StellaHuang95** [comment]
Closing the issue as the behavior is expected.
