### ISSUE TITLE
The result of Test discovery was incorrect.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7027]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/172312142-4a2d07b2-08c4-493f-87c0-f762af9c5afa.png)

**Steps to Reproduce**

1. Create Python application project.
2. Right-click project, select Add > New Item …, then select "Python Unit Test" followed by "Add".
3. Add test_1.py file with code
```
import unittest

class Test_test_1(unittest.TestCase):
    def test_A(self):
        self.fail("Not implemented")

if __name__ == '__main__':
    unittest.main()

```
4. Set Test framework as "unittest" in python project properties page.
5. Open TE with the Test > Windows > Test Explorer menu command

**Expected behavior**

The result of Test discovery was correct.

**Additional context and screenshots**

The result of Test discovery was incorrect.
There is only one test but it shows that two were found.

![image](https://user-images.githubusercontent.com/82852072/172314552-fd558091-b6de-466f-a251-9fe278362862.png)

**Comment by StellaHuang95** [comment]
Can't repro this. I am getting the right number of tests. 
![Animation2 - pytest count](https://user-images.githubusercontent.com/100439259/172439964-6237c37c-87b4-42aa-b419-dfaa50fb43eb.gif)

**Comment by judej** [comment]
Please reopen if you are still seeing the problem.
