### ISSUE TITLE
An error pops up after clicking Fill Comment Paragraph

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7029]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/172331217-ec31832b-5234-47b7-8dad-132f662b4558.png)

**Steps to Reproduce**
1. Type short lines comments like:
![image](https://user-images.githubusercontent.com/59192491/172331374-75bdaca2-4c7f-4c76-b51d-acb901878683.png)
2. Go to Edit > Advanced > Fill Comment Paragraph to reflows and formats comments text

**Expected behavior**
It combined short lines together
![image](https://user-images.githubusercontent.com/59192491/172331692-86627e00-6ad0-41d2-a694-c7390a04a6b2.png)

**Additional context and screenshots**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/172331877-0f5333ae-480a-4d58-99e9-2012cc4d6dca.png)

**Comment by StellaHuang95** [comment]
I can't repro this in the latest build. 
![Animation2 - fill comment para](https://user-images.githubusercontent.com/100439259/172438606-06f10e62-466d-4dab-9b66-5bc3b6632b8a.gif)

**Comment by judej** [comment]
Please reopen if you are able to repro.
