### ISSUE TITLE
Visual Studio Python環境について

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7033]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Python環境について/10061336)._

---
Python環境について
PythonのAnacondaがPython3.9.12にアップグレードしたことに際し、通常の公式pythonを3.9,3.10のみ残して3.8はアンインストールしました。
しかしVisual StudioのPython環境というところにはPython3.8が線で消えていますが表示としては残っています
完全に3.8を表示しない方法はありますか

---
#### Feedback Bot on 6/5/2022, 08:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Translation: 

About the Python environment
When Anaconda of Python upgraded to Python 3.9.12, we uninstalled 3.8 leaving only the usual official python 3.9 and 3.10.
However, in the Python environment of Visual Studio, Python 3.8 is disappeared with a line, but it remains as a display.
Is there a way not to show 3.8 completely

**Comment by StellaHuang95** [comment]
Hi, sorry for the issue you are experiencing, but I was not able to repro what you saw. The environment is shown as "missing" after I manually remove it, and the missing environments can be removed by right click -> remove. Could you provide us a more detailed repro steps or a screenshot/gif of the issue? That would be really helpful. Thanks. 😊

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.
