### ISSUE TITLE
Visual Studio 2022 Python environments

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7035]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Python-environments/10055872)._

---
[severity:It's more difficult to complete my work]
Visual Studio 2022 does not recognize conda environments created in drives other than C:. I have created two conda environments in D: and this tool is forcing me to create any virtual environment in C: and overflooding the C-Drive. Requesting for a fix ASAP

---
#### Feedback Bot on 5/30/2022, 01:10 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi, I was not able to repro this issue. Are you saying that the environments you created in D drive are not showing up in the Add environment -> Existing environment dialog? Could you provide more details or repro steps for us to further investigate? 😊 Thanks.
