### ISSUE TITLE
Visual Studio 2022 freezes during python debugging session

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7036]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-frozeduring-python-de/10059878)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:VS 2019]
This is the second time this has occurred for me. I was in the middle of stepping through some Python code and the entire VS IDE locked up indefinitely.

Unfortunately this is not something I am able to reproduce at will. It happens only occasionally.

---
#### Chris Kline on 6/1/2022, 02:40 PM: 

(private comment, text removed)
#### Feedback Bot on 6/1/2022, 07:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by KorkyPlunger** [comment]
I am the original reporter of the ticket that was moved from Developer Community. 

I eventually narrowed this down to having variables present in either the watch window or pinned data tips. In all cases where this occurred, if I removed the watch window items and datatips, the problem went away.

**Comment by int19h** [comment]
Can you give more information about the variables in question? This likely has to do with the specific variable, or rather its repr() - it would be very helpful if you can narrow it down.

**Comment by KorkyPlunger** [comment]
@int19h I am very sorry to say that I cannot -- I thought I attached screenshots of the issue to the [original DeveloperCommunity ticket](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-frozeduring-python-de/10059878), but I no longer see them there and can no longer remember which variable(s) were problematic. 

I do have an interesting observation, however. At the same time I was having these lockups, I was also experiencing many other issues with the Python integration. For example, no output would appear in my VS debug output window, and it would take 5-10 seconds after starting debugging before execution of the python script would actually begin. 

What was interesting was that if I created a *new* PTVS project, that project's output *would* appear in the output window, and there were no delays in the start of execution.

So, out of curiosity, I re-created my existing python solution and project from scratch in VS 2022, and all my problems went away. No more issues with the debugger hanging, no delays in startup, and output appeared correctly in the debugger output window.

The previous python project was one that I had been upgrading over time as each new version of VS came out, going all the way back to 2013 or so. So I suspect something in the solution or the project file was triggering this issue? I *do* have those two files, so if you are curious to look at their differences, I'm happy to show them to you.

**Comment by int19h** [comment]
It would certainly be interesting to look at the difference in the projects, even if there's no exact repro.

**Comment by KorkyPlunger** [comment]
@int19h 
Sure. Attached are screenshots of the diffs of the .pyproj and .sln files.

![pyproj](https://user-images.githubusercontent.com/4852571/174675074-048335ce-0c13-45b0-ad28-54d1bedde26a.png)

![sln](https://user-images.githubusercontent.com/4852571/174675081-9fa1ec20-01fa-4d77-83f2-62f7cb06aeb7.png)

**Comment by KorkyPlunger** [comment]
Interesting indeed @int19h. I have no idea why the other project was a Django project, perhaps that was set up by accident (I don't even know what Django is).

I did a test today of enabling native code debugging, and it definitely breaks some things. If I turn it on:
* none of my breakpoints are hit
* no output appears in the VS debug output window

If I then turn native code debugging back off, the breakpoints are hit again, and I see the output in the debug window.

So something seems broken with native code debugging. FWIW this is in the latest VS 2022 17.2.4, using python 3.10.5 x64.

**Comment by int19h** [comment]
Native debugger doesn't support Python 3.10 at the moment, so that's not surprising. What I meant is that the difference in behavior between these two projects on the screenshot would stem first and foremost from the difference in debuggers being used. I'm assuming that the project file with it enabled is the older version of the project?

**Comment by KorkyPlunger** [comment]
_I'm assuming that the project file with it enabled is the older version of the project?_

Yes, this is correct.
