### ISSUE TITLE
The result of Test discovery was incorrect.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7043]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/172789728-4ab27026-11fb-493a-9ff6-4f55fe312567.png)

**Steps to Reproduce**

1. Create Python application project.
2. Right-click project, select Add > New Item …, then select "Python Unit Test" followed by "Add".
3. Add test_1.py file with code
```
import unittest

class Test_test_1(unittest.TestCase):
    def test_A(self):
        self.fail("Not implemented")

if __name__ == '__main__':
    unittest.main()

```
4. Set Test framework as "unittest" in python project properties page.
5. Open TE with the Test > Windows > Test Explorer menu command

**Expected behavior**

The result of Test discovery was correct.

**Additional context and screenshots**

The result of Test discovery was incorrect.
There is only one test but it shows that two were found.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/82852072/172789972-8778f8c8-571b-4c3c-850f-50ef7fff1d2d.png)

**Comment by StellaHuang95** [comment]
Might have to do with parallel test discovery that was introduced in preview 2. Filed an internal ticket and can be tracked here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1560000
