### ISSUE TITLE
Go to definition on module not working

### ISSUE THREAD

**Issue by bschnurr** [microsoft/PTVS#7044]
**Describe the bug**
[A clear and concise description of the bug]

**Steps to Reproduce**
1.   Go to definition on 'decimal'
2.  click on any of the results in the search results window
3.

**Expected behavior**
[A clear and concise description of your expectation]

expected to jump to the pyi or py file location

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]
![image](https://user-images.githubusercontent.com/1946977/172962249-fb318ff2-2e57-45d1-8b15-de83bbe9b568.png)

**Sample Code**
```
import decimal 
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [Can be found under "Help->About Microsoft Visual Studio"]
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products->Python with Pylance"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```

**Comment by StellaHuang95** [comment]
Looks like the control-click go to definition is being implemented. https://devdiv.visualstudio.com/DevDiv/_search?text=go%20to%20definition&type=workitem&pageSize=25&filters=Projects%7BDevDiv%7D

**Comment by rchiodo** [comment]
I believe this is a bug in the VSLanguageClient. They're not doing path translation correctly for find all reference results. 

This code here just uses `.localPath` directly:
https://dev.azure.com/devdiv/DevDiv/_git/VSLanguageServerClient?path=/src/product/RemoteLanguage/Impl/Features/FindReference/ReferenceEntryFactory.cs&version=GBdevelop&line=270&lineEnd=270&lineStartColumn=34&lineEndColumn=61&lineStyle=plain&_a=contents

It should be using this instead:
https://dev.azure.com/devdiv/DevDiv/_git/VSLanguageServerClient?path=/src/product/RemoteLanguage/Impl/Utilities.cs&version=GC1c3dbb9a513db2b41ff8f930fd5396ea32176632&line=148&lineEnd=148&lineStartColumn=32&lineEndColumn=44&lineStyle=plain&_a=contents

**Comment by rchiodo** [comment]
Going to transfer this to the VSLanguageClient team.

**Comment by rchiodo** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1859975/
