### ISSUE TITLE
Cannot attach to debug a Python/c++ mixed mode executable in VS 2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7056]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-attach-to-debug-a-Pythonc-mixe/10065427)._

---
[regression] [worked-in:16.11.5]
I have  an application that uses both c++ and python.
In VS 2019, I used to be able to attach to my application using Native + Python in order to view both the c++ and python stack in the same call stack. But in VS2022, when I try to select both Native and Python, I get an error: "Python debugging is not compatible with Native. Would you like to uncheck Native?".  If  choose one or the other, I only see the stack of one or the other. As in I can only see the C/C++ call stack if choose Native, or I only I see  the python stack if I choose Python. I notifed that there's an option now for "Python (native)" and it doesn't seem to do anything.

---
#### Feedback Bot on 6/8/2022, 10:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
Can you clarify what you mean by it not doing anything? It is, indeed, the option that you need to select *instead of* "Python" if you want to use it alongside "Native".

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks😊
