### ISSUE TITLE
not support for python3.8 when Write C++ extensions for Python - Visual Studio (Windows)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7057]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/not-support-for-python38-when-Write-C/10073109)._

---
Documentdetails
⚠ Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.

ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://docs.microsoft.com/nl-nl/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022)
Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md)
Product: visual-studio-windows
Technology: vs-python
GitHub Login: @rjmolyneaux
Microsoft Alias: rmolyneaux
the problem is :
① everything is ok when the conda environment is setup with python=3.9
② The c++ breakpoint is hit , but the python breakpoint is not hit ,when python=3.8
anyone else in the same problem as me?
And how to fix it when python=3.8? (for some reason,I must use python3.8),please.

PS:
I've tried&&checked following many times :
Everything else is the same, just changing the python from 3.9 to 3.8 would cause above problem.

---
#### Feedback Bot on 6/16/2022, 09:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by fenneishi** [comment]
someone know why? thanks

**Comment by int19h** [comment]
We had an issue in mixed-mode debugger on Python 3.8. However, this should be fixed in VS 2022 by now; can you clarify which version of VS you're using?

**Comment by fenneishi** [comment]
> We had an issue in mixed-mode debugger on Python 3.8. However, this should be fixed in VS 2022 by now; can you clarify which version of VS you're using?

Thanks for your response.
I'm using VS2022.
Here are details.

![Snipaste_2022-07-07_14-51-18](https://user-images.githubusercontent.com/33345538/177710978-5cbac9ed-b718-4ebd-bd81-f6f9210b5c88.jpg)

**Comment by int19h** [comment]
Can you try updating VS itself? The most recent stable version of VS 2022 is 17.2. If I remember correctly, 17.0 predates the fix (which was committed in April).
