### ISSUE TITLE
Python debugger does not work when native debugging is enabled

### ISSUE THREAD

**Issue by F-I-D-O** [microsoft/PTVS#7063]
The Python debugger stops at breakpoints normally. But when I enable the native code debugging in the project configuration, those same breakpoints work no longer.

I followed these steps:
1. Install PTVS into Visual studio, including the *Python native development tools* component
2. Install Python 3.10 64-bit including the debugging symbols
3. Create a fresh Python project
4. Add a single line: `print('')`
5. Tested the debugger, break on that single line works
6. Enabled native debugging in the project preferences
7. Run the debugger again
    - Expected behavior: debugger should stop at the breakpoint
    - Real behavior: program finished, breakpoint greyed out with a tooltip: *... no symbols have been loaded*

I checked the Modules tab to see the loaded modules, it appears that the Python pdb files are successfully loaded:
![image](https://user-images.githubusercontent.com/2853732/176491827-2e935fe9-ac15-4b61-bc01-6236f274399c.png)

When I break the process manually, I receive the following call stack:
![image](https://user-images.githubusercontent.com/2853732/176492451-a31e35e2-a1a3-4a7f-baf3-4f019557bed7.png)

To me, it appears that the Python debugger is not running at all. Seems similar to #3611

My configuration (there is no *Diagnostics* in  *Tools->Options->Python* in my Visual Studio):
- VS Version: 17.2.5
- PTVS version: 17.0.22089.1
- Python version: 3.10
- Debugger Type (if applicable): ?

**Comment by int19h** [comment]
Basically, it doesn't support 3.10: #6900

**Comment by F-I-D-O** [comment]
Thank you! With Python 3.9, I can hit Python breakpoint in native code. Now I have another problem though: #7065
