### ISSUE TITLE
How to step into Python stantandard library function?

### ISSUE THREAD

**Issue by F-I-D-O** [microsoft/PTVS#7065]
How can I use PTVS to step from python code to python standard library function? Currently, the debugger just steps over, instead of into.

I tried to add the `PythonDeveloper` key to the registry in order to enable the *Show Native Python Frames* and *Use Python Stepping* options according to #2657, but it has no effect, i.e., the context menu in `Locals` -> `Python` only contains two other options.

**Comment by int19h** [comment]
If I remember correctly, the registry key is only picked up when PTVS is loaded, not live during a debug session - might it be that?

**Comment by int19h** [comment]
My apologies for a belated response - yes, it would only get picked up when VS is restarted. 

If that wasn't the problem, then perhaps you were setting the entries for 32-bit apps? Since VS is now 64-bit I believe the registry paths have changed accordingly.
