### ISSUE TITLE
No response after reopening the Python Environments  window

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7069]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/177124566-f2c50bda-d284-4eab-80aa-3cbdc0bbb411.png)

**Steps to Reproduce**
1.Create a Python Project
2.Select 'View All Python Environments'
![image](https://user-images.githubusercontent.com/59192491/177125169-dd30b49a-ecd4-46d8-ac97-238ebb2e9bcb.png)
3.Check the Python Environments  window is open
4.Close the Python Environments  window and repeat step 2

**Expected behavior**
Python Environments  window open normally

**Actual behavior**
No response when  i did it again

**Additional context and screenshots**
![environment_window](https://user-images.githubusercontent.com/59192491/177126193-ee5e4118-b6af-4f08-b5ed-677588e4d5b9.gif)

**Comment by StellaHuang95** [comment]
@linette-zyy Does this still repro?

**Comment by linette-zyy** [comment]
@StellaHuang95 
In today's latest build, i can not repro this
![image](https://user-images.githubusercontent.com/59192491/221733458-33062378-4f72-4cf5-93bc-a55c4b574309.png)
