### ISSUE TITLE
Can't hit break point in mixed debug mode

### ISSUE THREAD

**Issue by saedrna** [Microsoft/PTVS#707]
Hi,

I have followed the video and tutorial on the mixed debug mode wiki page. Here is my problem.

I'm using ctypes to load a dll with a simple exported function. I can stop in the breakpoints of the cpp file, but the break points in the python file can not be hitted. I have upload some figures of the call stack and the editor as the following.

![image](https://cloud.githubusercontent.com/assets/3850191/9151263/2067a4fc-3e2f-11e5-8d23-86af316144c2.png)

![image](https://cloud.githubusercontent.com/assets/3850191/9151273/641eba3c-3e2f-11e5-8c9c-b295a7da78ce.png)

![image](https://cloud.githubusercontent.com/assets/3850191/9151270/4f6d4eaa-3e2f-11e5-90e6-dfcb10376c7a.png)

Here is my environment

Python 3.4.3 32 bit
VS 2013
windows 8.1 64bit
PTVS 2.2 release 

P.S. I have tried on two different PC and encountered the same problem.

**Comment by int19h** [comment]
If you're seeing python34.dll and _ctypes.pyd in your stacks, then you're not actually debugging Python here, just native code. 

How do you start debugging? Is it Debug -> Start Debugging (F5), or Attach to Process?

**Comment by saedrna** [comment]
I'm debugging using Debug -> Start Debugging.There are two project in my project and the python project is set as startup  project.

![image](https://cloud.githubusercontent.com/assets/3850191/9153404/3c1eb486-3e86-11e5-84a3-d1f33072beba.png)

**Comment by int19h** [comment]
Would it be possible for you to share your project, so that I can look at it and try to repro?

(you can send it to ptvshelp@microsoft.com)

**Comment by saedrna** [comment]
I have sent it to the email.

**Comment by saedrna** [comment]
I think I have figured out the problem. It is maybe because that the program consider as the python.exe as native language rather than python.

![image](https://cloud.githubusercontent.com/assets/3850191/9154043/19111558-3eb1-11e5-9a15-aa4550dd7d08.png)

The gray python (top one) is started using F5 and the black python is started from cmd in the directory and not used for debugging. As you can see that, the gray one is only recognized for native code ("本机" ). But the python start from cmd can be correctly recongnized as both native and python engine.

So how can I solve this? If it's not possible to us F5 for debugging, how can I start debug using the attach to process mode?

**Comment by int19h** [comment]
This isn't an indication of a problem by itself, just a deficiency in our debug engine - it doesn't detect python.exe as running Python if it's already being debugged.

I couldn't repro the issue with your project, so there's something about the environment that must be causing it. Narrowing it down might be tricky, but let's give it a try.

First of all, can you open the Modules tool window (Debug -> Windows -> Modules), and see if Microsoft.PythonTools.Debugger.Helper.x86.dll is present in the list, and has its symbols loaded?

**Comment by saedrna** [comment]
The symbols of the "Microsoft.PythonTools.Debugger.Helper.x86.dll" is loaded as below, but no .py files are loaded
![module_f5](https://cloud.githubusercontent.com/assets/3850191/9187350/0ac4529c-4002-11e5-8b10-b054ad4d9128.jpg)

P.S. I have successfully get the mixed mode debugging running with PTVS 2,1 using the "attatch to process" method. I start a python from cmd and attatch the python.exe. And using PTVS 2.2 I also encountered the problem showed as the picture of this thread
https://github.com/Microsoft/PTVS/issues/533

![python](https://cloud.githubusercontent.com/assets/3850191/9187382/7178c860-4002-11e5-9bda-b11dd59d23ad.jpg)
![stack](https://cloud.githubusercontent.com/assets/3850191/9187388/802ecae4-4002-11e5-8684-8ec343035038.jpg)

**Comment by int19h** [comment]
To clarify: when you say you've encountered the same problem, do you mean that you ran the script from command line, then did Debug -> Attach to Process using PTVS 2.2, and got this error?

![image](https://cloud.githubusercontent.com/assets/1175142/9187493/0c6d8c0c-3f86-11e5-9100-f41ee779f340.png)

**Comment by saedrna** [comment]
Yes, that's it (but in Chinese version)

**Comment by int19h** [comment]
Very interesting. This is a clear failure that should be relatively easy to debug; the only problem is that I cannot reproduce it locally, so I'll need your help. Would you be interested in helping me out? If yes, email pminaev@microsoft.com, and I can explain the specific steps in more detail.

**Comment by saedrna** [comment]
Update: Visual Studio 2015 Community goes well with the integrated python tools

**Comment by dneubelt** [comment]
Hello @int19h ,

I'm on visual studio 2015 community edition and I have the same issue as @saedrna . I can not hit breakpoints in python from within visual studio via running from the python project when the debugger is set to use native debugging.

If I disable native debugging then I can debug python code.

However, if I attach to python then I can hit both native and python code.

I did verify that Microsoft.PythonTools.Debugger.Helper.x86.dll had it symbols loaded.

I've attached diagnostic info for python tools
[Diagnostic Info 2016-12-11T091607.txt](https://github.com/Microsoft/PTVS/files/644626/Diagnostic.Info.2016-12-11T091607.txt)

I'm willing to share my code as it's very small over email, however, I'd suspect its an environment issue and you can't repro.

Any advice?

**Comment by int19h** [comment]
Are you also seeing the same error message box?

**Comment by dneubelt** [comment]
@int19h sorry for the late reply. No I did not get any error box and I attach to the process, however, when I attach everything works great (I can debug both python and native code).

If I run from within the debugger (with enable native debugging checked) I do not have the ability to hit python breakpoints but I can hit native breakpoints.

Here is a look at the callstack of my native debugging

![image](https://cloud.githubusercontent.com/assets/5284502/21322017/233727c2-c5cc-11e6-8fd3-ff0640ff0cb2.png)

**Comment by int19h** [comment]
Interesting. So you do get Python call stack frames with file and line information, variables etc if you launch with mixed mode - it's just Python breakpoints that don't work?

What happens if you try to step out of native back into Python, and then step over some lines of Python code?

**Comment by dneubelt** [comment]
When I try to hit shift-f11 twice (step out) it will then continue execution of the program w/out ever getting into python code.

**Comment by dneubelt** [comment]
Interestingly, when I go into disassembly view from my C++ code and follow to the first return statement it brings me to a cmp statement. Clicking F10 on that cmp statement causes the debugger to stop debugging and the program will continue its execution.

![image](https://cloud.githubusercontent.com/assets/5284502/21357693/02c85118-c68b-11e6-874c-a2c663b6f450.png)

The above is my C++ code and I'll hit F10 to bring me to (assumingly) ctypes code

![image](https://cloud.githubusercontent.com/assets/5284502/21357727/2014af96-c68b-11e6-9a28-9a3aa3af299e.png)

Hitting F10 will then resume my program and debugging will stop.

**Comment by newb78** [comment]
Hi,

I'm currently facing the very same issue and I wanted to know if someone had been able to solve it.

Thanks

**Comment by dneubelt** [comment]
I updated the latest version of visual studio to update 3 and I seem to have resolved it
