### ISSUE TITLE
web project error SyntaxError: invalid syntax The program 'pythonw.exe' has exited with code 1 (0x1).

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7073]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/web-project-error-SyntaxError:-invalid-s/10080723)._

---
![image.png](https://aka.ms/dc/image?name=Bc4d73001050349109ca73d1e280eba8b637917658697676797_20220625-225749-image.png&tid=c4d73001050349109ca73d1e280eba8b637917658697676797)

im new developer in web im trying to use vs2022 as web project builder but when i test sim ple html to run in server it has some error in python i dont know how to fix it.

---
#### Feedback Bot on 6/26/2022, 06:25 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, seems like you're running that HTML as Python and the `<!DOCTYPE html>` is invalid in Python which caused a syntax error. If you are looking to create a Python web application project, you may find this [link](https://docs.microsoft.com/en-us/visualstudio/python/python-web-application-project-templates?view=vs-2022) helpful. Thanks. 😊
