### ISSUE TITLE
Add a python project to solution does not give the environment 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7074]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-a-python-project-to-solution-does-no/10082521)._

---
Hi,

I'm trying to start a new python project and everything works fine using "New project" then select "Python application" and click "ok".

The project solution explorer shows everything, especially the environment settings that have been set up, see here (in german)

![image.png](https://aka.ms/dc/image?name=B18da0eafef164a9a840d1e40c7b85eb0637920147603774738_20220628-140559-image.png&tid=18da0eafef164a9a840d1e40c7b85eb0637920147603774738)

However, if I use an empty solution and try to do the same using "Add project" then select "Python application", the solution is missing the environment setting and I cannot start any python code even if I'm adding environments. But essentially you see in the solution explorer, that there is no environment set, compare it with first picture please:

![image.png](https://aka.ms/dc/image?name=Be529cbe76dbb49c48aeed2b38e1769e2637920150924709777_20220628-141132-image.png&tid=e529cbe76dbb49c48aeed2b38e1769e2637920150924709777)

Why is that different to "New"? What can be done to activte or add this?

Thank you,

Thomas

---
#### Feedback Bot on 6/29/2022, 01:18 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, I was not able to repro this. This is what it looks like when I created an empty solution, and then created a new Python application by right clicking Solution -> Add -> New Project -> Python Applicaton.
![image](https://user-images.githubusercontent.com/100439259/177656397-b701f06c-0a3f-4e40-b444-4d2c36bd830a.png)
Could you follow this [guide](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-projects-solutions?view=vs-2022) and try again on the latest version of VS? Let us know if the issue still persists. Thanks!

**Comment by TomFD** [comment]
Hi, 

you are right. However, the steps to reproduce it are not to create an empty solution and then add a project. I forgot to mention this or more specific, I described it wrong.

I got my empfty "solution" from an empfty github repo, then the solution explorer does not really have a solution but you can add a project. Then adding the python project fails in running it. Adding a blank solution first and then the python app also fails. I would expect that "add a python project" just works like "new" project does.

Here are the steps to reproduce:

(1) On github, create a new empty project
(2) Open VS and use "Clone a repository", paste the new github project link to it, wait until its cloned
(3) Open solution explorer (and see that its empty, even the folder view - which is ok)
(4) Use the visual studio menu -> File -> Add -> New project -> python application
(5) Inspect solution explorere and see, that there is no "solution" file and thus not environment, thus, no possibility to run the python app

Now, how to add the "blank solution" afterwards? Any other way to create access to the environment at this point?

Thomas

**Comment by StellaHuang95** [comment]
Hi @TomFD, I followed your repro steps and I saw the following:
1. Clone an empty github repo.
![image](https://user-images.githubusercontent.com/100439259/177851182-0606d75d-163f-45d2-a59a-cbdc481debc1.png)
2. Right click and open the Folder View
![image](https://user-images.githubusercontent.com/100439259/177851284-c98e5873-784d-4363-b913-01779ed42681.png)
3. File -> Add -> New project -> Python Application
I see Python Environments in the top menu bar, you can also go to View -> Other windows -> Python Environments to open environment window.
![image](https://user-images.githubusercontent.com/100439259/177851442-c4074f48-b9f9-4ede-bc39-f29b08f90887.png)
4. Type something in the .py file and run.
![image](https://user-images.githubusercontent.com/100439259/177851720-ca4faf86-4509-41c7-857a-72a7daf1294e.png)

Could you try again and let me know if that doesn't work? 😊
