### ISSUE TITLE
VS 2022 Pylance crashes all the time

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7076]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-Pylance-crashes-all-the-time/10074867)._

---
[severity:It's more difficult to complete my work] [regression]
This just started happening **today**.

All I have to do is create a new file called 'foo.py`, and then I see this error message:

`Task Failed - Activating language client Pylance: Operation did not complete successfully because the file contains a virus or potentially unwanted software`.  This appears in the Output window under Language Client activation failures.

I can still edit and debug Python code.  However, there is no outlining or completion suggestions, _etc_, so my work is much harder.

I am going back to VS 2019 Professional, even though it does not officially support Python 3.9.

I will also try downgrading VS 2022 and see if the problem goes away.  If it does, then I'll update this issue.

Details on what I have:
```
Microsoft Visual Studio Community 2022
Version 17.2.4
VisualStudio.17.Release/17.2.4+32602.215
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA239
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019   17.2.392.13739
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.392.13739
Azure App Service Tools v3.0.0

C# Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Cookiecutter   17.0.22089.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Markdown Editor v2   2.0.111
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.2.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.22089.1
Profiling support for Python projects.

Python with Pylance   17.0.22089.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
```

---
#### Feedback Bot on 6/19/2022, 08:06 PM: 

(private comment, text removed)
#### Michael Rolle on 6/19/2022, 10:17 PM: 

(private comment, text removed)
#### Bill Schnurr [MSFT] on 6/29/2022, 09:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Going to close this out. Please take a look at the response in the original post and reopen the ticket if the issue still persists, Thanks😊
