### ISSUE TITLE
VS2022 Python Fonts and Colors Customization Regression from VS2019, Defies Microsoft Documentation

### ISSUE THREAD

**Issue by schulmaster** [microsoft/PTVS#7082]
**Describe the bug**
VS2022 Python Fonts and Colors Customization Regression from VS2019, Defies Microsoft Documentation.  No IDE syntax categories at all. Just broad spectrum Interactive colors. 

**Steps to Reproduce**
1.Consult Documentation:
https://docs.microsoft.com/en-us/visualstudio/python/editing-python-code-in-visual-studio?view=vs-2022
2. Read this section:
"To customize the colors, go to Tools > Options > Environment > Fonts and Colors and modify the Python entries in the Display items list:"
3. Observe how VS2022 does not conform to documentation

**Expected behavior**
I would love for Python Syntax highlighting to work like VS2019, and/or to conform to Microsoft's own documentation

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]
I will attach documentation and reality.

![pydoc](https://user-images.githubusercontent.com/43507239/178442668-cd716fe7-f288-4045-bb06-760d76882388.PNG)
![image](https://user-images.githubusercontent.com/43507239/178442844-23247d0c-a3a3-4eb3-b5f2-3bb8466654c1.png)
![image](https://user-images.githubusercontent.com/43507239/178443050-9942d6d8-a9fe-4386-9501-b425414a3117.png)

**Comment by AdamYoblick** [comment]
Pylance is now responsible for determining identifiers, operators, functions, etc. Are there still options in VS to change the colors of these things? If so, we might need to look to see if we are wiring these up correctly when they come back from pylance so VS can change their colors.

**Comment by AdamYoblick** [comment]
(and those docs need to be updated with VS2022 UI)

**Comment by StellaHuang95** [comment]
We didn't provide tmThem file along with TextMate grammar. tmTheme file is used to map the scopes defined in TextMate grammars (e.g. keyword.operator.logical.python) to VS standard color names that are customizable via Tools/Options/Fonts and Colors. 
Unfortunately for the custom colors (e.g. Python Function) to appear there we will need in-proc VS extension to register them.
VS doesn’t support tokenColorCustomizations like VS Code.

**Comment by StellaHuang95** [comment]
The Python display items supported in vs2019 are:

- Python Builtins
- Python Class
- Python Comma
- Python Documentation
- Python Dot
- Python Function
- Python Grouping
- Python Module
- Python Operation
- Python Parameter
- Python Regular Expression

I think we might be able to support some of them, I will look into that.

**Comment by ShiShuyang** [comment]
It has been one and a half year since this issue was raised. I have noticed that many duplicated issues were opened and closed for the same question. This may be a common issue that lots of user desire to solve. And, this function works well in VS 2019 and in VS code. Looking forward to fixing this issue soon! Best wishes!

**Comment by cwebster-99** [comment]
Thanks for raising this issue! PTVS VS 2022 documentation has been updated to exclude these color setting options for now. This should address the documentation mismatch raised in this issue. More investigation is needed to see which code coloring settings can be added to VS 2022.
