### ISSUE TITLE
Can't have Intellisense for Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7088]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-have-Intellisense-for-Python/10093041)._

---
[severity:It bothers me. A fix would be nice]
I can't find intellisense for Python in the settings. 
I've done a repair of vs 2022 but nothing change.
I obviously have the python package.
Link: https://docs.microsoft.com/fr-fr/visualstudio/python/editing-python-code-in-visual-studio?view=vs-2022

Can someone help me please ? 
Thank you in advance !

![Capture d’écran 2022-07-12 153346.png](https://aka.ms/dc/file?name=Bfd4b82acf421431fabe86672a717eace637932297030243161_Capture_d%E2%80%99%C3%A9cran_2022-07-12_153346.png&tid=fd4b82acf421431fabe86672a717eace637932297030243161)
![Capture d’écran 2022-07-12 153410.png](https://aka.ms/dc/image?name=Bf93450d358f94e11a4cc530cb74d8b60637932296776978312_Capture_d%E2%80%99%C3%A9cran_2022-07-12_153410.png&tid=f93450d358f94e11a4cc530cb74d8b60637932296776978312)

---
#### Feedback Bot on 7/12/2022, 05:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
We don't have a configuration page for Intellisense for Python. What behavior are you trying to change in Intellisense?

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
