### ISSUE TITLE
random module in python 2022 can't use random module

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7090]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/random-module-in-python-2022-cant-use-r/10091420)._

---
[severity:I'm unable to use this version]
When using random module in python, I got stuck in an error that says " partially initialized module 'random' has no attribute 'randint' (most likely due to a circular import)"
even when I copy a valid code

---
#### Feedback Bot on 7/10/2022, 10:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Could you please check if you have another module named `random`?

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
