### ISSUE TITLE
An error pops up after clicking "Ignore these local items".

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7094]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/180934702-69f6ae8a-f6d2-44ab-8084-4350ca4d1b44.png)

**Steps to Reproduce**
1. In VS, select File > New > Project, search for "Django", and select the Blank Django Web Project template.
2. Enter the Name and location and check the option "Add to source Control", create the project and wait for project loaded in SE
3. Create the virtual environment with install requirements.txt and exclude it from source control
  a. Go to team explorer click "Changes"
  b. Right-click the virtual environment folder and select "Ignore these local items"
![image](https://user-images.githubusercontent.com/59192491/180935005-e2155989-1e22-4ab5-b47e-95415879ab9c.png)

**Actual result and screenshots**
An error pops up.
![image](https://user-images.githubusercontent.com/59192491/180935146-cfbf415c-cab5-49d6-83d9-30ee481e6945.png)

**Comment by StellaHuang95** [comment]
This is not PTVS bug since it appears in other languages as well. Filed an internal ticket to track this bug. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1582769

**Comment by StellaHuang95** [comment]
Will be fixed once this PR is in. https://devdiv.visualstudio.com/DevDiv/_git/VSTeamExplorer/pullrequest/413871
