### ISSUE TITLE
Can't add Python 2.7 to a fresh VS2022 install

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7098]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-add-Python-27-to-a-fresh-VS2022-i/10098101)._

---
[severity:I'm unable to use this version]
I successfully downloaded VS2022 with Python 3.9 . I have been unable to get VS to add an existing C:\Python27 environment (python 2.7.18). I’ve been struggling to do this for a week and think I read all the relevant docs.\nWhen I select “existing environment” and point the Prefix Path field at C:\Python27 it populates the remaining fields correctly, however, after I click Add no new 2.7 choice is added to Python Environments.

---
#### Feedback Bot on 7/18/2022, 09:11 PM: 

(private comment, text removed)
#### Andrew Marcuvitz on 7/21/2022, 06:17 AM: 

(private comment, text removed)
#### Andrew Marcuvitz on 7/21/2022, 10:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Python 2.7 can be added if the "Make this environment available globally" is unchecked.

**Comment by judej** [comment]
Python 2.7 is no longer maintained [PSF 2.7 support announcement](https://www.python.org/doc/sunset-python-2/.) Pylance which is the language server for Visual Studio no longer supports Python 2.7. [Blog Post on Python 2.7 support](https://devblogs.microsoft.com/python/python-in-visual-studio-code-december-2021-release/#an-update-on-debugging-with-python-2-7)
