### ISSUE TITLE
PTVS Remote debug Modo 801

### ISSUE THREAD

**Issue by Prostrelov** [Microsoft/PTVS#71]
Continuing this thread: https://pytools.codeplex.com/discussions/439880
After establish connection with ptvsd server,  modo stops with Application Error 1000.
System configuration: Win7x64, VS2012, PTVS 2.1, MODO 801.

Faulting application name: modo.exe,  version: 801.0.7.7509, time stamp:  0x547cd8cc
Faulting module name: python27.dll, version: 2.7.3150.1013, time stamp: 0x52836a29
Exception code: 0x40000015
Fault offset: 0x0000000000141b3a
Faulting process id: 0xa54
Faulting application start time: 0x01d08570f02228aa
Faulting application path: C:\Program Files\Luxology\modo\801_SP3\modo.exe
Faulting module path: C:\Program Files\Luxology\modo\801_SP3\extra\python27.dll
Report Id: 40989478-f164-11e4-9c6f-2089844b401a

**Comment by zooba** [comment]
Closing because this is so old it's not clear how to follow up. If someone encounters this again with our latest release, please file a new bug with as many details as you can (i.e. don't rely on the links to the old issue please).
