### ISSUE TITLE
Python editor: Value cannot be null. Parameter name: replaceWith

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7100]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-editor:-Value-cannot-be-null-Par/10100016)._

---
At any time a .py file is saved, debugged etc. the message appears and the file cannot be edited anymore, unless you close and reopen the file.

---
#### Feedback Bot on 7/20/2022, 10:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

Are you using the local file system for save the .py file?

Will need additional environment information to debug.

thanks

**Comment by DanielSeara** [comment]
In my case, I'm using the local file system
