### ISSUE TITLE
Braces highlighting does not work in python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7101]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Braces-highlighting-does-not-work-in-pyt/10100695)._

---
[severity:It's more difficult to complete my work]
When I position the cursor on a brace, the matching left or right brace is not highlighted. I have attached the screenshot.

---
#### Feedback Bot on 7/21/2022, 06:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, if you move the cursor to the right side of the close bracket you're trying to highlight, do you see the highlighting?

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
