### ISSUE TITLE
Python editor: Value cannot be null. Parameter name: replaceWith

### ISSUE THREAD

**Issue by DanielSeara** [microsoft/PTVS#7103]
At any time a .py file is saved, debugged etc. the message appears and the file cannot be edited anymore, unless you close and reopen the file.
In my case, I'm using the local file system
Do NOT mark it as closed since there is no work on it.
_Originally posted by @DanielSeara in https://github.com/microsoft/PTVS/issues/7100#issuecomment-1198276590_

**Comment by heejaechang** [comment]
can you provide step by step repro?

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
