### ISSUE TITLE
IntelliSense and ErrorList Window don't work after new a project

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7110]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/182787322-3f9cd3ff-af17-482f-a14d-0c2237991702.png)

**Steps to Reproduce**
1.Create a project and write 'print xxxx' in default .py file 
2.File -> Project, same steps as step1
3.Check the IntelliSense and ErrorList Window

**Expected behavior**
IntelliSense and ErrorList Window work well

**Actual behavior**
![error list](https://user-images.githubusercontent.com/59192491/182788231-420ab3f6-c77d-416c-aa0b-cd3fe73a8730.gif)

**Comment by StellaHuang95** [comment]
@linette-zyy I can't repro this, could you try one more time? Thanks!

**Comment by linette-zyy** [comment]
![image](https://user-images.githubusercontent.com/59192491/183359361-42de4bf5-29ad-4e48-b2c3-5f04dfdd0093.png)
I can repro this in today's latest build

**Comment by linette-zyy** [comment]
I can also repro this in multiple scenarios , IntelliSense works well, but the error list window still doesn't work.

In VS, File -> New -> Web Project -> Add a python file 
![error list_add_webproject2](https://user-images.githubusercontent.com/59192491/183363113-667b3d45-6f9d-4d60-b4a7-e51bba1248fb.gif)

In VS, File -> Open -> Folder -> one existing folder - > Add a python file
![error list_open_folder](https://user-images.githubusercontent.com/59192491/183363142-e285bcb8-ce19-413a-80e1-e4cdb6425172.gif)







![image](https://user-images.githubusercontent.com/59192491/183366682-d3ca9277-feb6-42fa-a788-97792968808a.png)
![Create C++ extension for Python 3 9](https://user-images.githubusercontent.com/59192491/183363196-b798c6d4-516c-4d07-8c59-7441229d1f34.gif)

****NOTE**: Error list window only gets back to normal after restarting VS**

**Comment by gundermanc** [comment]
Hey @StellaHuang95, FYI I believe I have a fix for this issue: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/422648

**Comment by StellaHuang95** [comment]
@gundermanc Thanks!! I will wait for it to merge in to VS and run the tests😊Thank you so much!

**Comment by StellaHuang95** [comment]
Confirmed fixed in the latest version. 
![image](https://user-images.githubusercontent.com/100439259/191364618-aba5a68f-b665-4eea-a6a8-be5da9549643.png)
