### ISSUE TITLE
Failed to hit the test breakpoint after restarting the VS

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7111]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/183046739-434f2e31-1186-4dd1-a1e4-739f634e1b65.png)

**Steps to Reproduce**
1.Create a project
2.Set the Test framework to 'unittest' and save it
![image](https://user-images.githubusercontent.com/59192491/183047258-b60a74a7-da32-4f29-93f6-19e429b4c938.png)
3.Add a python unit test file  and set a breakpoint
![image](https://user-images.githubusercontent.com/59192491/183048865-b9460774-f340-4721-a2da-24d1aeddbc87.png)
4.Open the TE, make sure test in it 
5.Debug the test
![image](https://user-images.githubusercontent.com/59192491/183049031-1bf53ab6-3510-402a-8d87-ad79a369279b.png)
6.make sure the breakpoint can be hit
7.Restart VS and debug again

**Actual behavior**
The breakpoint can't hit after restarting VS

**Comment by linette-zyy** [comment]
This issue also can reproduce on this environment
![image](https://user-images.githubusercontent.com/59192491/183052739-e2ebe4e7-ebd6-4c6e-8408-6d0ec531217d.png)

**Comment by StellaHuang95** [comment]
dup of #6796. Workaround is to load the project first before opening the Test Explorer.
