### ISSUE TITLE
PLEASE HELP. Non-UTF-8 code starting with '\xff'

### ISSUE THREAD

**Issue by zeqqa** [microsoft/PTVS#7114]
SyntaxError: Non-UTF-8 code starting with '\xff' in file C:\Users\zekio\desktop\python_temelleri\first_app.py on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

I tried a very simple print ("xxxx") code and when I tried to run I got this error, I can't figure it out, can you help me please

**Comment by zeqqa** [comment]
![fdsafasfadsda](https://user-images.githubusercontent.com/109533076/183387229-4808f4ed-0703-44b0-82d3-5e97494159f0.png)
![rqweqwrfas](https://user-images.githubusercontent.com/109533076/183387238-9c0d82d0-eb4e-4ac4-b84d-aabf1a659d9c.png)

**Comment by StellaHuang95** [comment]
Hi, can you try going to File -> Save As -> Pick "Save with Encoding..." from the Save dropdown menu -> Pick UTF-8 and see if that issue still persists?
