### ISSUE TITLE
LiveShare: Intellisense doesn't work.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7123]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/184295347-1e4e66f7-a8f8-46bd-a1cd-be37c76ee0e9.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Open Live Share, make connection between host and client.
3. Type ```import``` in the client.

**Expected behavior**

As you type, your completion list should open and prompt for your input accordingly.

**Additional context and screenshots**

Nothing came up. 

![image](https://user-images.githubusercontent.com/82852072/184295820-eaf4de06-e49e-41c4-b9a1-0b38d23a04f4.png)

**Comment by StellaHuang95** [comment]
@ttSpace I can't repro this, is this still happening in the latest version of VS?

**Comment by ttSpace** [comment]
@StellaHuang95  In today's build ```17.4.0 Preview 3.0 [32906.357.main] ```, Build of Python Package  ```17.0.22242.2 ```, I can repro this.

![image](https://user-images.githubusercontent.com/82852072/188801785-e407eba6-46f9-48ef-b276-6edbb561d70e.png)

**Comment by linette-zyy** [comment]
On today's environment
![image](https://user-images.githubusercontent.com/59192491/192208594-ab1c4790-1242-4d5a-b873-8d69b9f364bb.png)
This issue is not reproduced. Live share works well.
![image](https://user-images.githubusercontent.com/59192491/192208731-76f11e81-d6d8-4240-8002-57f32de8f14e.png)
