### ISSUE TITLE
VScode 2022 extensions trouble

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7127]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VScode-2022-extensions-trouble/10113337)._

---
thank you for supporting and i wish you can reply me by the other mail address which i used the most.
Mail: [Redacted]@[Redacted]

and the problem is, i discover that the extension searching have some issue that i cant find and install the extension which i need to use.

for an example , i cant find the python preview in the VScode but i can find it by online site.
when i click the install button, nothing happens also cant install the extension by downloading the extension.

https://marketplace.visualstudio.com/items?itemName=dongli.python-preview&ssr=false#overview

---
#### Feedback Bot on 8/7/2022, 11:58 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Thanks for the report, however, this is not a Microsoft extension. Please contact the author.
