### ISSUE TITLE
VS2022 Pytest + pytest-xdist unicode params issue

### ISSUE THREAD

**Issue by Full-Hole** [microsoft/PTVS#7130]
**Describe the bug**
Test execution from VS2022 will be skipped if test contains unicode symbols in params like 😎 or Ẅ, with pytest launched with argument -n/--numprocesses (pytest-xdist)

**Steps to Reproduce**
1. Create pytest test with params containing unicode symbols
2. create pytest.ini with [pytest] addopts = -n auto
3. Run test from VS2022

**Expected behavior**
Test group executed successfully

**Additional context and screenshots**
When start test group
![image](https://user-images.githubusercontent.com/76530118/185605544-c2904be7-7996-4bf2-98b9-6aca7459f3ca.png)
When run test separately
![image](https://user-images.githubusercontent.com/76530118/185606217-072c8ee3-f816-4afc-aa73-b8af5554b205.png)
Test without pytesx-xdist
![image](https://user-images.githubusercontent.com/76530118/185606658-d491bf5d-c73d-4503-b976-9d153556ccce.png)
Tests without VS
![image](https://user-images.githubusercontent.com/76530118/185607044-cd76fed2-2514-4948-b00d-f85ef2a171c1.png)

**Sample Code**
```
    @pytest.mark.parametrize('filter', ['Ẅ', 'somedata', '😂'])   
    def test_cant_get_templates(self, filter):
        response = self.some_api_get_with_response_code(filter=filter)
        with assert_all('Asserts test_negative_templates_id'):
            check_equal(ServiceCode.OK, response.code, f'Return Not {ServiceCode.OK} responce code')
            check_equal(CommonConst.EXPECTED_TEMPLATES, response.body,
                        f'Expected template_id: {CommonConst.EXPECTED_TEMPLATES} '
                        f'not in response {response.body}')
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: VisualStudio.17.Release/17.3.0+32804.467
PTVS version: 17.0.22179.3
Python version: 3.10

**Comment by StellaHuang95** [comment]
Hi there, it might have to do with the encoding. Could you try the followings:

Go to File -> Save As -> click the dropdown button next to Save, choose save with encoding -> choose UTF-8 and re-run the tests.

Please re-open the ticket if the issue still persists, thanks!
