### ISSUE TITLE
Breakpoints do not work in Python and C++ code when enabling native code debugging and activating virtual env of Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7139]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Breakpoints-do-not-work-in-Python-and-C/10126314)._

---
[severity:Other]
# Configuration
Here are only two project in solution -- a C++ and another Python

C++ project is initialized as a empty project, but set configuration type : dll
Python project is a initialized as empty project, but enable native code debugging.
Attach to : Python code, Python(native) code

When using global python env, breakpoints in Python do not work, but work in C++.
When using virtual python env, breakpoints in both python and C++ do not work.
When disable native code debugging in python project, breakpoints in Python work, but do not work in C++.

How do I get all the breakpoints working?

# test code
```C++
// in demo.cpp
#include
#include

using namespace std;
namespace py = pybind11;

void hello() {
	cout << "hello world." << endl; // breakpoint here
}

PYBIND11_MODULE(pyd_demo, m) {
	m.def("hello", &hello, py::return_value_policy::reference);
}
```
```python
# in test.py
from pyd_demo import hello

if __name__ == "__main__":
    hello() # breakpoint here
    pass
```

---
#### Feedback Bot on 8/21/2022, 11:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
When Python on Windows is running from a virtual environment, the python.exe that you launch in this manner is actually a stub that locates the *real* python.exe (from the base environment) and spawns it. So, when attaching, you must make sure that you're picking the right python.exe - there should be two.

**Comment by StellaHuang95** [comment]
Going to close this out, please reopen the ticket if the issue persists after trying the steps above. Thanks! 😊
