### ISSUE TITLE
when using pylance code completion, press "enter” will replace the code wrote behind it. 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7147]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/when-using-pylance-code-completion-pres/10126373)._

---
[severity:It bothers me. A fix would be nice]
The action pylance code completion made is just like enabling the INSERT and enter new codes.It will replace the words behind the position you use the code completion.The first screenshot displays that I have selected the option before I press the enter.The second screenshot displays that after I press the enter, the bracket I have wrote before disappeared.
I have no ideas whether it's a bug or just I haven't set current settings of pylance.

---
#### Feedback Bot on 8/21/2022, 07:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, it's a bug we are currently working on. See https://github.com/microsoft/PTVS/issues/6786. Thanks!
