### ISSUE TITLE
Python project Properties menuitem error

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7153]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-project-Properties-menuitem-error/10134340)._

---
How to reproduce the issue:
1. Create a Python command line application
2. Open the Project menu on the menu bar
3. Find the Properties (ALT+F7) menu item
4. Observe the item text: 4294967296 Properties (ALT+F7)
Onserved: incorrect label (see step 4 and screenshot attached: vs_py_bug.png)
Expected: correct label, like  Properties (ALT+F7) or just Properties (ALT+F7), I'm not sure what is the correct label here.

---
#### Feedback Bot on 8/30/2022, 07:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, can you check what's your path/file name length? The correct label is supposed to show project name + Properties. Might have to do with the path/name length exceeding the limits.

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
