### ISSUE TITLE
Please fix a bug! the module 'requests' in Python no works!!!

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7161]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-fix-a-bug-the-module-requests-/10138727)._

---
[severity:It bothers me. A fix would be nice]
The module "requests" in Python-app showns, but no works. If import this module, at startup arises error. Fix this bug please!!! if you no fix this bug I will switch to another platform:(((((

---
#### Feedback Bot on 9/4/2022, 06:42 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, I was not able to repro this. Could you provide detailed repro steps so that we can investigate? Could you also check if requests is installed in your selected python environment? Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
