### ISSUE TITLE
Updating Visual Studio 2019 couldn't download CPython3.exe.x64

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7162]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Updating-Visual-Studio-2019-couldnt-dow/10140366)._

---
[severity:I'm unable to use this version] [regression]
Open Installer
Update 2022 + 2019 Visual Studio 

Error after starting download
only with Visual Studio 2019

---
#### Feedback Bot on 9/6/2022, 05:32 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, looking at your logs, it seems there are still some processes running during the installation. Could you try ending up all VS instances from task manager, cleaning up all processes related to Visual Studio, and rebooting your machine? Please let us know if retrying the installation still does not work. Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
