### ISSUE TITLE
"Ignore these local items" doesn't work when first click

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7165]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/190982030-a5e82a0b-4a8d-43b8-9735-3d2256185758.png)

**Steps to Reproduce**
1.Launch VS, search for "Django", and select the Blank Django Web Project template.
2.Enter the Name and location and check the option "Add to source Control", create the project and wait for project loaded in SE
3.Create the virtual environment with install requirements.txt and exclude it from source control
   a. Go to team explorer click "Changes"
   b. Right-click the virtual environment folder and select "Ignore these local items"

**Actual behavior**
I need click twice "Ignore these local items"
![ignore_env](https://user-images.githubusercontent.com/59192491/190982697-24843ac5-dd6f-41ae-a569-fc344f4569b6.gif)

**Output**
![image](https://user-images.githubusercontent.com/59192491/190983218-6d3cd565-cc6d-43b9-b5fc-5aca655251ac.png)

**Comment by StellaHuang95** [comment]
Hi, could you check if your python path is added to your PATH variable?That might be the reason why Python was not found. Thanks.

**Comment by StellaHuang95** [comment]
Hi, could you check if your python path is added to your PATH variable?That might be the reason why Python was not found. Thanks.

**Comment by linette-zyy** [comment]
I can repro this on today's latest build
![image](https://user-images.githubusercontent.com/59192491/191153389-95e78dc6-8820-4a82-aec0-7351f75e920b.png)

The python is installed from VS as same as yesterday, maybe related this issue:https://github.com/microsoft/PTVS/issues/7050 ?
![image](https://user-images.githubusercontent.com/59192491/191153588-b770cfd2-d51f-4eaf-a64f-af87bb2b01e5.png)
![image](https://user-images.githubusercontent.com/59192491/191153651-0e7541cc-584e-46a6-8c96-e02acead009b.png)

**Comment by linette-zyy** [comment]
I can repro this on today's latest build after adding python path to PATH variable
![image](https://user-images.githubusercontent.com/59192491/191212840-1c0f6509-a3e0-45e8-9292-648867746f0f.png)
![image](https://user-images.githubusercontent.com/59192491/191214212-bf7f62a5-e2ca-45cc-8b4f-96e5b7b35d50.png)

Python is installed from VS
![image](https://user-images.githubusercontent.com/59192491/191214338-416c3c5c-eb50-405d-9f81-1ad58f5957f4.png)
![image](https://user-images.githubusercontent.com/59192491/191214428-46dd6e4b-51ce-4217-8d5f-ec64d413966c.png)

**Comment by linette-zyy** [comment]
On the latest build 17.6.0 Preview 1.0 [33319.311.main], Python Package: 17.0.23005.2, this issue is not reproduced.
