### ISSUE TITLE
Cannot add Python 2.7 environment

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7172]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-add-Python-27-environment/1684079)._

---
When I try to add a Python 2.7 environment with the "Existing environment" options nothin happens when I press Create. The window exits without any error message but there is no new Python 2.7 environment created. I currently have three automatically created environments, Anaconda 2021.11, Plotly (3.9) and the standard Python 3.9

---
#### Feedback Bot on 3/6/2022, 07:19 PM: 

(private comment, text removed)
#### Feedback Bot on 3/10/2022, 08:49 PM: 

(private comment, text removed)
#### Andrew Karpushin on 4/20/2022, 00:51 AM: 

(private comment, text removed)
#### Andrew Marcuvitz on 7/21/2022, 10:40 AM: 

(private comment, text removed)
#### Graham Wheeler [MSFT] on 9/8/2022, 09:35 AM: 

(private comment, text removed)
#### tmathew on 9/19/2022, 08:20 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, starting from the next version, we are going to drop the support for creating custom environments for python versions < 3.7, and only support for the [officially supported versions](https://devguide.python.org/versions/#supported-versions). We recommend using python 3.7+ for better experience. Thank you.😊
