### ISSUE TITLE
The Quick Action icons of 'extract method' and 'remove unused imports' are missing

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7187]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/196359489-db228798-0d8c-4e32-8613-1ca537c67b4e.png)

**Steps to Reproduce**
1.Create a Python Application project
2.Input some code
3.Move the cursor to a one line
4.The Quick Action icon should appear in front of this line.

**Expected behavior**
![chonggou_success](https://user-images.githubusercontent.com/59192491/196362628-167a8c81-40db-4fff-af5b-06edb089551e.gif)

**Actual behavior**
![chonggou_fail](https://user-images.githubusercontent.com/59192491/196363664-bb989d4c-69c3-460b-9c57-e7ca924c99d7.gif)

**Sample Code**
```
import array; import glob; import math
print(math.cos(10))
```

**Comment by StellaHuang95** [comment]
This is not python specific issue. It's being handled here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1643677
