### ISSUE TITLE
Comment hotkey inconsistent between C# and Python contexts

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7195]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Comment-hotkey-inconsistent-between-C-a/10173683)._

---
[severity:It's more difficult to complete my work]
Hello. Running Microsoft Visual Studio Professional 2022.

When developing in C# the block comment toggle ("Edit.ToggleBlockComment") shortcut is "Ctrl+Shift+/"

This does not work in a Python context. How do I get Edit.ToggleBlockComment to work the same way, with the same shortcut in both the C# and Python context?

After spending a month developing in C#, not having the same commenting mechanism in a Python context, in the same software, is detrimental to my muscle-memory efficiency.

Very frustrating default setup that I find far from logical.

Thank you.

---
#### Feedback Bot on 10/16/2022, 07:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, you could use Ctrl+K+C/Ctrl+K+U to comment and uncomment code block for both languages. Thanks!
