### ISSUE TITLE
Add New Item in web template doesn't work.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7204]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/198954094-f1470fb7-bf59-4c51-8815-a4f9f591ea41.png)

**Steps to Reproduce**

1. Create a Blank Django Web Project template. 
2. Right click the project, select Add > New Item

![image](https://user-images.githubusercontent.com/82852072/198955062-d4d9f9cb-c4bb-4128-a181-afdfa27c3398.png)

**Additional context and screenshots**

The "New Item" window did not pop up.

BTW, I can repro it in web-based Projects. (Python Application cannot repro.)

![image](https://user-images.githubusercontent.com/82852072/198980388-7da090de-0073-4cc9-983b-0190e5af8240.png)

**Comment by StellaHuang95** [comment]
@ttSpace does this still repro? I couldn't repro it on the latest version.

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build ```17.6.0 Preview 2.0 [33408.313.main]```, Python Package: ```17.0.23033.1```.

![image](https://user-images.githubusercontent.com/82852072/217733286-8172ef72-af21-4abb-9b3b-537abc59ce48.png)
