### ISSUE TITLE
About the problems in the update process after I added python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7211]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/About-the-problems-in-the-update-process/10181368)._

---
![1666752531594.jpg](https://aka.ms/dc/image?name=B48b01cd5a67541e49de4acda9dd950f0638023493562102092_1666752531594.jpg&tid=48b01cd5a67541e49de4acda9dd950f0638023493562102092)

I waited for a long time and found that it did not move. Then I wanted to close it. Then I pressed Pause and found that it could not be closed

---
#### Feedback Bot on 10/25/2022, 09:32 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
broken image: 
![image](https://user-images.githubusercontent.com/100439259/199552525-49699be2-d951-431a-9cd0-b0c90f620aba.png)
Doesn't seem like a PTVS issue.

**Comment by judej** [comment]
Assigned internal bug to Setup
