### ISSUE TITLE
An error pops up after clicking the icon of 'Property Pages' 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7213]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/200763906-0e8e1e45-6dee-495f-904a-45b209ebcacc.png)

**Steps to Reproduce**
1.Launch VS and create empty c++ project
![image](https://user-images.githubusercontent.com/59192491/200765872-e2493d0e-ebd4-4524-b2de-751f78b952f3.png)

2.Click the icon of 'Property Pages'

**Actual behavior**
An error pops up
![image](https://user-images.githubusercontent.com/59192491/200765702-dacd239e-5c8d-4315-b74a-6dc001c744e6.png)

**Comment by AdamYoblick** [comment]
I sent an e-mail to the VS Extensibility Discussions group, since I'm not sure where to reroute this to. Once we create a bug for the appropriate team, I'll close this out since it's not ours to fix.

**Comment by AdamYoblick** [comment]
This is already tracked at https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1666489. Closing this out.
