### ISSUE TITLE
Fix CodeQL in PTVS and pylance compliance pipelines

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#7217]
Apparently the guardian version of CodeQL isn't compliant. See https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/1761/Static-Analysis for more details.

- [x] Fix in PTVS compliance pipeline
    * https://github.com/microsoft/PTVS/pull/7221
- [x] Fix in pylance compliance pipeline
    * https://github.com/microsoft/pyrx/pull/2963
- [x] Fix in debugpy release? pipeline @int19h 
    * Add TSA upload steps for debugpy?

**Comment by int19h** [comment]
Now also done in debugpy.
