### ISSUE TITLE
Error formatting python documents

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7233]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-formatting-python-documents/10208166)._

---
[severity:It's more difficult to complete my work] [regression]
When working on a python document, I can no longer format the document, either through the keyboard shortcut or the menus.

It comes up with an error dialog saying 'A task was cancelled'.

![image.png](https://aka.ms/dc/image?name=B3df3494f5b194b96b5c74eb21f950757638046206306677832_20221121-094347-image.png&tid=3df3494f5b194b96b5c74eb21f950757638046206306677832)

---
#### Feedback Bot on 11/21/2022, 10:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Image from feedback ticket

![Image](https://user-images.githubusercontent.com/547753/205721300-69486b7b-22ae-45a4-b0f2-026f3b0df921.png)

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
