### ISSUE TITLE
Fold to the definition function name is hidden

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7252]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/折叠到定义函数名被隐藏，求助求助求助求助求助求助求助求助求助求助求助求助求助求助/10194721)._

---
[regression] [worked-in:17.1.7]
17.1.7版本之后：
python代码选择”大纲显示-折叠到定义“操作后函数名被隐藏：
![无标题.png](https://aka.ms/dc/image?name=Bceefd9bf5d2749368d1f15a878441b9f638035827885444515_%E6%97%A0%E6%A0%87%E9%A2%98.png&tid=ceefd9bf5d2749368d1f15a878441b9f638035827885444515)

---
#### Feedback Bot on 11/9/2022, 01:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, this should be fixed in the next version. See https://github.com/microsoft/pylance-release/issues/3580
