### ISSUE TITLE
Issues with some VS functionality after upgrading to Win 11

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7255]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Issues-with-some-VS-functionality-after-/10191019)._

---
At times I will lose functionality after VS 2022 has been open for a little while. I've lost use of search for text in files or I haven't been able to open the GIT side windows. Sometimes I see exceptions in the top bar. This seems to have occurred after upgrading to Win 11.

---
#### Feedback Bot on 11/6/2022, 06:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment]
Thanks for the report. Could you please give us the repro steps and a screen shot or the text of the errors if you can?

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
