### ISSUE TITLE
VS-2019 and VS-2022 splash screens are vulgar (too big)

### ISSUE THREAD

**Issue by flexorx** [microsoft/PTVS#7259]
**Describe the feature you are requesting**

Me and my colleguaes find that the size of the splash screen in VS-2019 and VS-2022 is way too big. Here is 1920x1080 Windows 1.25x scaling instances from 2019 and 2022:

![image](https://user-images.githubusercontent.com/49031207/206268744-190d9cf2-7a4c-45da-857e-15700c513b18.png)

![image](https://user-images.githubusercontent.com/49031207/206268825-4b6a8e8f-ba06-49e2-9fdf-e0af6c9759bf.png)

Compare to 2017:

![image](https://user-images.githubusercontent.com/49031207/206268657-ada04ffa-c849-463a-a4d9-2b3940343726.png)

**Reasons for requesting this feature**

The splash screens take almost entire screen. This looks vulgar.

**Describe alternatives you've considered**

1. Reduce the size of the splash screen to VS-2017 dimentions.
2. Allow to explicitly disable splash screen in VS settings (not `/nosplash`)

**Comment by StellaHuang95** [comment]
Thanks for your feedback, we are PTVS-specific team so this is really beyond what we can do.😊So I would recommend submitting a feedback here: https://learn.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022

Thanks!!
