### ISSUE TITLE
Set Up is near impossible in intel Visual Studio 2022 in Windows 11 for Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7262]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Set-Up-is-near-impossible-in-intel-Visua/10215417)._

---
[severity:It's more difficult to complete my work]
While attempt to use Python is really too difficult to get it to work. Setting the right environment. I notice this: I am in an Intel mainboard. However, in other my AMD mainboard is working fine.

---
#### Feedback Bot on 11/28/2022, 11:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, could you share a little bit more about the issues you're experiencing? What specific issues have you encountered? That will help us further investigate the issues. Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
