### ISSUE TITLE
args in launch.vs.json not passed to Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7269]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/args-in-launchvsjson-not-passed-to-Pyt/10220065)._

---
[regression] [worked-in:17.4.1]
After updating to 17.4.2 the 'args' property specified in the launch.vs.json file are no longer passed to the python program being debugged. The args are passed to C++ programs (type is "default").

launch.vs.json:
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "python",
      "name": "printargs.py",
      "project": "C:\\Project\\printargs.py",
      "projectTarget": "",
      "args": [
        "Hello World!"
      ]
    }
  ]
}

printargs.py:
import sys
print(sys.argv)

output:
['printargs.py']

expected output:
['printargs.py', 'Hello', 'World!']

---
#### Feedback Bot on 12/4/2022, 04:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
launch.vs.json is a C++-specific feature in VS, so far as I know. Did it somehow work for Python projects before?

**Comment by StellaHuang95** [comment]
Looks like it's labeled as enhancement here: https://github.com/microsoft/PTVS/issues/7434
