### ISSUE TITLE
Terminal prompts are disabled when cloning a GitHub repository

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7273]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/208046636-6f125669-f17e-44d9-99c0-ce6dd64217dd.png)

**Steps to Reproduce**

1. Open Cookiecutter Explorer.
2. Load the following template: ``` https://github.com/doesnt/exist ```

**Expected behavior**

You should be prompted to log in with your account.

**Additional context and screenshots**

No prompt window to log in. An error is displayed in the output window.

![image](https://user-images.githubusercontent.com/82852072/208844591-22519506-0502-471e-81f2-1137c84ffc2b.png)

## Logs

<details>

<summary>Output for <code>General</code> in the <code>Output</code> panel 
</summary>

<p>

```
----- Cloning template 'https://github.com/doesnt/exist' -----
Cloning into 'exist'...
warning: could not find UI helper 'GitHub.UI'
fatal: Cannot prompt because terminal prompts have been disabled.
fatal: could not read Username for 'https://github.com': terminal prompts disabled
git.exe returned an exit code of 128.
----- Failed to clone template 'https://github.com/doesnt/exist' -----
```

</p>
</details>

**Comment by StellaHuang95** [comment]
@ttSpace Could be because there's a space at the end of your URL. Could you remove that space and try again to see if that repros?

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build ```17.6.0 Preview 2.0 [33423.321.main]```, Python Package: ```17.0.23047.1```.

![image](https://user-images.githubusercontent.com/82852072/221109669-358b0827-c089-4577-b8f9-debcdedcb4d1.png)
