### ISSUE TITLE
Visual studio 2022 can't install extensions (IronPython or AlterNet Studios)

### ISSUE THREAD

**Issue by Dumb9** [microsoft/PTVS#7275]
I have the updated community version of Visual studio 2022 It is working perfectly.
Except from the extensions. I wanted to make an app using the wpf .net thing on visual studio because its really good for that. And i really wanted to code it in python but then i realized visual studio does not have wpf for python.

So then i tried to download it from other sources. 
First i downloaded it from the official IronPython Github (the most recent version) 
And i did the installer and it looked like it should of worked. Iron python is meant to show up in visual studio when you make a new file but it did not. So then i searched IronPython on my computer and i could run it in the command prompt version but not in visual studio.

Next i tried to download alternet studios using the visual studio extensions installer. Which then took me to the website and after i installed it and i could run it in its own app i checked visual studio and it said it was installed but it would not let me make a python wpf .net file like i was meant to be able too.
It was like i installed the extension but it did not do anything (it said it was enabled)
I looked at loads of youtube videos and searched it up but none of the ideas solved it because they were not the problem.

Thanks for the help.

**Comment by StellaHuang95** [comment]
Hi there, IronPython is no longer supported in Visual Studio 2022, you may have to try with a lower version of VS instead. See https://github.com/microsoft/PTVS/issues/6613
