### ISSUE TITLE
The variable is not visible after the match statement.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7282]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-variable-is-not-visible-after-the-ma/10227078)._

---
On the Python 3.11 64-bit interpreter in Microsoft Visual Studio Enterprise 2019 Version 16.11.21. The variable is not visible after the **match** statement in the development environment. Throws an error in the context "unexpected token 'number'".

---
#### Feedback Bot on 12/11/2022, 06:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi, could you provide a code sample for us to repro the issue? Also could you please try on VS 2022 and see if the issue still persists? Thanks!

**Comment by Sayberix** [comment]
Here is a sample code. Haven't tried the 2022 version. But I'll let you know as soon as I try it.

**Comment by Sayberix** [comment]
Updated to version 2022. There is no such error anymore.
