### ISSUE TITLE
Exception when selecting Python Environments --> pip

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/PTVS#729]
Hello,

I have Visual Studio 2015 RTM running on Windows 10 Enterprise RTM. I do **not** have any version of Python installed. 

I installed the PVTS 2.2 package on VS2015 RTM, opened the `Python Environments` window, created an empty "Environment" and then selected the "pip" option from the drop-down box. I then received the following exception.

![2015-08-11 19_12_35-python tools for visual studio](https://cloud.githubusercontent.com/assets/466713/9214605/3235803e-405d-11e5-9d4a-7fbee9befa8f.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by zooba** [comment]
Strange, I thought we already had this filed, but I can't find it now.

Thanks for the report.

**Comment by zooba** [comment]
Should be fixed now with other changes
