### ISSUE TITLE
Unable to add Platform and Configuration to Python Application project.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7292]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-add-Platform-and-Configuration/10242363)._

---
It would be awesome to have the same configuration capabilities and macro accesses for Python as we have for C++.

---
#### Feedback Bot on 1/3/2023, 00:31 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
Thanks for the feature request, unfortunately, we do not have plans to support platform and configuration metrics in Python Application projects at this time.
