### ISSUE TITLE
Visual studio python debugger error

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7293]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-studio-python-debugger-error/10235325)._

---
[severity:I'm unable to use this version]
I followed the steps to install visual studio, and installed the python package, however, whenever I attempt to run any code whatsoever, an error pops up saying 

"
![image.png](https://aka.ms/dc/image?name=B65a623baad414d41a48a147de009aa2d638071845841692910_20221220-195624-image.png&tid=65a623baad414d41a48a147de009aa2d638071845841692910) 
"

and it gives me the error code "The program 'python.exe' has exited with code 4294967295 (0xffffffff)"

How can I fix this?

---
#### Feedback Bot on 12/20/2022, 06:12 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Screenshot from the feedback ticket:
![image](https://user-images.githubusercontent.com/100439259/210414756-b81419fa-ea90-48fd-9a9c-63a60b1c4f0b.png)

**Comment by StellaHuang95** [comment]
Hi there, are you using Python 3.6 or lower? Could you try with python 3.9? Thanks!

**Comment by judej** [comment]
This works on Python version 3.7 and higher. The older versions of Python are not supported in PTVS.
