### ISSUE TITLE
Win Forms (WPF) For Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7295]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Win-Forms-WPF-For-Python/10182455)._

---
Iron Python included templates for elements like windows forms and WPF in python.

Please create or upgrade the old templates to the new python in windows.

---
#### Feedback Bot on 10/26/2022, 08:27 PM: 

(private comment, text removed)

**Comment by judej** [comment]
IronPython is not supported in the Pylance language server (the language server in PTVS.) The usage is too low.

**Comment by apsis0215** [comment]
@judej  - Is WPF in the CPY3 then?
