### ISSUE TITLE
Python Language Extension to have the same Functionality as C# or C++

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7296]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-Language-Extension-to-have-the-sa/10177066)._

---
I will like Microsoft to extend to the Python language the same functionality that is with the C++ and C# languages on VS IDE.

But before promising me you will come back to me in 7 days.  Do something concrete and just make sure that in the next major release of VS IDE, it will have a fully functional Python language tool (with support for Windows, desktop, Cloud, UWP etc. projects).

If you can do this, then I will believe that in the future, say for the 2024 edition of VS IDE, you will also build in Java, Rust, Kotlin and maybe Scala support.

---
#### Feedback Bot on 10/19/2022, 11:29 PM: 

(private comment, text removed)
#### andrew goh soo meng on 10/20/2022, 06:06 AM: 

(private comment, text removed)
#### andrew goh soo meng on 10/22/2022, 01:40 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Hi there, thank you for your feedback! We do have a roadmap on the way for PTVS, and we have also just opened the discussion session for moving issues to discussion as enhancement requests for comments and upvotes.😊Let us know if you have any specific suggestions. Thanks!
