### ISSUE TITLE
Add Flask Framework for Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7297]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Flask-Framework-for-Python/10152824)._

---
Please add support for Flask web framework.  The VS IDE supports only Django and well some people would prefer Flask.  And if you can, publish a book on web development using Flask.

---
#### Feedback Bot on 9/20/2022, 11:16 PM: 

(private comment, text removed)
#### andrew goh soo meng on 10/22/2022, 06:12 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Response from the original feedback ticket: Thank you Microsoft, but Flask support is found in the VS IDE. You can close this case.
