### ISSUE TITLE
Python return-type in SingleQuotes is not recornized

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7298]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-return-type-in-SingleQuotes-is-no/10119664)._

---
Hi,  
when a python method should return itself, the correct way to define the return type is putting it in single quotes (… -> ‘MyClass’)

```  
class MyClass:

    instance:'MyClass' = None
    @staticmethod
    def getInstance() -> 'MyClass':
        if MyClass.instance==None:
            MyClass.instance = MyClass()
        return MyClass.instance

    def func(self):
        pass
  
```

But when you do so, Visual Studio doesn’t understand the type. So there is no working auto complete.

```  
MyClass.getInstance(). <-- No auto-complete
  
```

Would be nice, to have auto complete and all features, when the returntype is in single quotes, too

Greetings  
Patrick

---
#### Feedback Bot on 8/15/2022, 02:24 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Hi there, is it what you are expecting? 
![forwardtype](https://user-images.githubusercontent.com/100439259/210460863-18bb6f3b-023d-4438-b147-33bf53dad5cb.gif)

**Comment by heejaechang** [comment]
`None` shows error since `instance` can't be assigned with `None`

correct way will be making `instance: Optional['MyClass'] = None`

**Comment by heejaechang** [comment]
also, if you put `from __future__ import annotations` at the top of the file (assuming you are using somewhat latest python version), type annotation evaluation will become lazy, meaning you can put type name as it is rather than putting it as str to make it lazily evaluated.

**Comment by StellaHuang95** [comment]
Please let us know if above doesn't answer your question. Thanks!
