### ISSUE TITLE
Add support for Task Item Priority to LSP Client

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#7300]
One of the diagnostic types that Pylance can return to the LSP Client is a TaskItem. This is done by setting a tag on the diagnostic object which equals TaskItem (-9).

However, both the VS task list options menu (tools -> options -> Environment -> Task List) and the task list window contain a "priority" field which allows you to set the priority of specific task list tokens. The priority header doesn't have a label in the Task List window, but it's here:

![image](https://user-images.githubusercontent.com/29436557/210650717-bc5164af-4eb7-4d44-aa38-71ec9fd754c3.png)

So this task has two parts:

- [x] Modify the Visual Studio LSP Client to support reading priority from task list diagnostics that are returned from the language server.
- [x] Modify pylance to properly return priority when parsing task items from comments

I will meet with the LSP team to get their sign off on my approach before implementing it, and it will take time for those changes to flow into visual studio. The second task can be done immediately (once we decide how priority will be stored), as it just won't do anything without LSP Client support.

**Comment by AdamYoblick** [comment]
The roslyn team has already created a PR to do this work in their language server at https://github.com/dotnet/roslyn/pull/66294. 

VSDiagnostic currently has a DiagnosticRank field, so that's what pylance should set as well. LSP Client needs to be updated to extract this field from task item diagnostics and forward it along.

**Comment by AdamYoblick** [comment]
This will be fixed by https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS-Platform/pullrequest/450871

**Comment by smimon** [comment]
Hi Adam - saw you closed off #7151 and mentioned this. In #7151 several people (including me) were all saying the task list is totally broken for other languages like C#.

Is that getting picked up? Should I raise a new ticket for that, and if so, in what area?

Many thanks

**Comment by AdamYoblick** [comment]
@smimon There were two distinct tasks for python - getting task list working again (since it was completely missing), and getting priority working in the task list pane. The first task was for python only, the second task lights up priority for all teams who have task lists working.

That being said, each language team is responsible for handling task item diagnostics since that's done on the language server side. Visual Studio just makes them visible. I think the only task item token that works for C# is `todo`, but I could be mistaken. The right place to report C# bugs would be https://github.com/dotnet/roslyn :)

**Comment by smimon** [comment]
Thanks for the info @AdamYoblick, I'll create a ticket over there.

**Comment by StellaHuang95** [comment]
@AdamYoblick Can we close this one since the pr is completed?
