### ISSUE TITLE
Why does it always show that the adapter failed to start?

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7318]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Why-does-it-always-show-that-the-adapter/10245372)._

---
[severity:It's more difficult to complete my work]

![0858a1f8b5ddc4c0d77f7f5539ad68d.png](https://aka.ms/dc/image?name=B3288e5ba72e54baebf4cf1b869a383aa638084849063818781_20230105-110827-0858a1f8b5ddc4c0d77f7f5539ad68d.png&tid=3288e5ba72e54baebf4cf1b869a383aa638084849063818781)

---
#### Feedback Bot on 1/4/2023, 10:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, from looking at your logs:
``` 1> ERROR: Debug adapter error output: Fatal Python error: init_stdio_encoding: failed to get the Python codec name of the stdio encoding
 1> ERROR: Debug adapter error output: Python runtime state: core initialized
 1> ERROR: Debug adapter error output: LookupError: unknown encoding: PYTHONIOENCODING=UTF8
 1> ERROR: Debug adapter error output: Current thread 0x000037bc (most recent call first):
 1> ERROR: Debug adapter error output: <no Python frame>
 1> Cancelling outstanding request(s) with ID(s): 1
 1> ERROR: Debug Adapter did not respond to initial requests.
 1> ERROR: Unexpected error
```
seems like an issue with encoding. In debugpy source code both "utf-8" and "utf8" are used to retrieve the codec in different places. So it might be a case-sensitive issue. Could you try changing your encoding to lower case and see it that works? Thanks.

**Comment by StellaHuang95** [comment]
Actually, could you try running `print(codecs.encode("abc", encoding='UTF8'))` and see if that fails?
