### ISSUE TITLE
Python PEP 572 syntax not recognized (walrus operator)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7325]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-PEP-572-syntax-not-recognized-wa/10251680)._

---
[severity:It bothers me. A fix would be nice]
While writing python code, if you use the syntax described in [PEP 572](https://peps.python.org/pep-0572/) in an if statement the line is marked as containing an error and also subsequent lines are marked as well.
I suppose this si coming from the fact that you have a semicolon before the one at end of the condition, and the first on is interpreted as the second one.
Let me show you an example:
![PTVS PEP 572.png](https://aka.ms/dc/image?name=Bbe6296a2f942496c92de25e4b03417f0638091285974209375_PTVS_PEP_572.png&tid=be6296a2f942496c92de25e4b03417f0638091285974209375)
This syntax however is valid and the code runs fine.
The expected behavior would be to not mark that line (and the subsequent ones would follow, I suppose) as containing an error, since the syntax is valid.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, could you try that again in VS2022, we don't support that in VS2019. Let us know if you're still seeing the same error. Thanks!

**Comment by dariopnc** [comment]
Hello this issue seems to not be present in Visual Studio Professional 2022. If VS2019 is unsupported I think you can then close the issue.
