### ISSUE TITLE
One error pops up when copy or cut a file

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7328]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/212612792-a28122a2-114c-4372-a154-3e0387a5f517.png)

**Steps to Reproduce**
1.Launch VS and create a python project
2.Right click on the default file
3.Click 'copy' or 'cut'

**Actual behavior**
One error pops up
![image](https://user-images.githubusercontent.com/59192491/212613481-cce31def-59e1-4a0e-9fc8-cfcae9f96501.png)

**Comment by StellaHuang95** [comment]
close the issue as it doesn't repro in the latest build.
