### ISSUE TITLE
VS 2022 crashes regularly

### ISSUE THREAD

**Issue by akochepasov** [microsoft/PTVS#7329]
**Describe the bug**
VS 2022 crashes regularly, node.exe takes 103MB of private memory bytes and occasionally hogs CPU

**Steps to Reproduce**
1. Open a python project, like a package
2. Work for 1-3 hours 
3. Experience the crash

**Expected behavior**
No crash should happen

**Sample Code**
A python package

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version 17.5.0 Preview 1.0
Python with Pylance 17.0.22297.1
Python version: Anaconda 2022.10 (Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32)
Debugger Type (if applicable): VS debugger

**Diagnostics file**
I have dumped the log regularly because VS crashes regularly. This is the log for the state of 5-10 min before the next crash.
[pylance123.log](https://github.com/microsoft/PTVS/files/10431950/pylance123.log)

**Comment by akochepasov** [comment]
This is what I see in the Output -> General pane
[general.log](https://github.com/microsoft/PTVS/files/10432338/general.log)

**Comment by judej** [comment]
Thanks for the report. This was [fixed ](https://github.com/microsoft/PTVS/pull/7401)in Pylance. This should no longer be repro on the latest VS releases
