### ISSUE TITLE
Project template for creating C extensions

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#735]
Add a new project template that creates the necessary C++ project, with the correct settings for building a C extension to Python 3.5.

This is the next step in our C++ interop support, which started with the introduction of C++ mixed-mode debugging in PTVS 2.1.  Additionally, Python 3.5 (and its extensions) are built with VS 2015, which will be one of the supported VS versions for PTVS 3.0.

Compared to the Win32 Project wizard, it will be a quicker/better experience.  The user won't need to know what type of project, precompiled headers they need to select.  We can also add the correct .h and .lib files, and the output file name.

We should also add a matching Python project to the solution.  A reference to the C++ project will be present, with a entry in search path (that may not be needed?).

We can also generate a correct setup.py that will be used when installing from sources.

We should ensure that any code we generate as part of the template will compile successfully on other operating systems/compilers.

As far as boilerplate code, we probably should be adding some examples of implementing a function/class, and have the matching test code in the Python project.  TBD.

**Comment by zooba** [comment]
Do we need/want to support pre-3.5 versions? I mainly ask because it's so much easier to support 3.5 and later - we can even detect whether symbols have been installed in advance (look for `HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\3.5\InstalledFeatures\@core_pdb`)

**Comment by zooba** [comment]
There's a template published at https://github.com/zooba/PythonExtensionModuleTemplate/releases already (looks like I forgot to push the code into the repo, but there's a release available).

We probably want to use that, and also have a template that adds a unit test project alongside.
