### ISSUE TITLE
Mark VS bundled python version (3.9.13) as out of support

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#7350]
This should be done AFTER 2/2 so it doesn't make it into February patch Tuesday, but gets into March instead.

See https://microsoft.sharepoint.com/teams/python/_layouts/OneNote.aspx?id=%2Fteams%2Fpython%2FDocuments%2FDocuments%2FPython%20Team&wd=target%28Python%20VS%2FDev%20Docs.one%7CD7206CE2-CF40-437B-8CE9-1E55F4BC2F44%2FMark%20older%20Cpython%20as%20Out%20of%20Support%20in%20VS%20Installer%7C7206773E-BA92-4FD6-A01A-80AA38D9B99D%2F%29 for details

The branches that need to be updated are:

- [ ] 17.4 (Stella)
- [ ] 17.2 (Stella)
- [ ] 17.0 (Stella)
- [ ] 16.11 (Adam)
- [x] main (Adam)
    * https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/446558

**Comment by StellaHuang95** [comment]
@AdamYoblick Are we still planning on doing the rest of the branches? If not, I can close it.
