### ISSUE TITLE
Keyboard Shortcuts not Working

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7362]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Keyboard-Shortcuts-not-Working/10259193)._

---
[severity:It's more difficult to complete my work]
When trying to use `Ctrl + ]` to increase indent a line, it does not work (VS 2022 default). Changing the shortcut in the command to something else in preferences also does not work. Decreasing indent does work (`Ctrl + [`) Using Windows 11, Vs 2022, Version 17.4.4 x64.

---
#### Feedback Bot on 1/23/2023, 06:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, if you are looking to increase/decrease line indent, you can try using tab/tab + shift, which will add/remove a tab (or the equivalent spaces) to the selected lines or the current line. Please reopen the issue if that doesn't solve your problem. Thanks!
