### ISSUE TITLE
Dummy issue - testing stale issue bot

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#7369]
The bot should close this issue in 30 days

**Comment by AdamYoblick** [comment]
@StellaHuang95 Looks like the bot worked! :)

Can you please create a work item to get this in place for the pylance and debugpy repos as well? This might be a good way to cut down on stale tickets.

**Comment by StellaHuang95** [comment]
@AdamYoblick Sure I can add the same thing to the other repos!
