### ISSUE TITLE
LiveShare: Intellisense doesn't work. 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7374]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/216537126-d9218c28-81a9-49f7-8e74-69f6e0a40cf6.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Open Live Share, make connection between host and client.
3. Type `import` in the client.

**Expected behavior**
As you type, your completion list should open and prompt for your input accordingly.

**Additional context and screenshots**
Nothing came up.
![image](https://user-images.githubusercontent.com/59192491/216537387-01c8a9c9-3f64-40ab-9281-e82ab5e75cbe.png)

On server, it works well.
![image](https://user-images.githubusercontent.com/59192491/216537914-b814ae3b-1309-4cfe-821f-d4d2e345e6e3.png)

**Comment by StellaHuang95** [comment]
Hi @linette-zyy, looks like this issue was detected in VS2019, could you try on the latest version of VS and see if that repros? Thanks!

**Comment by linette-zyy** [comment]
@StellaHuang95 
In today's latest build:**17.6.0 Preview 2.0 [33407.118.main]**,Python Package:**17.0.23033.1**
I can not repro this
![image](https://user-images.githubusercontent.com/59192491/217416179-d5dd3af8-af55-4a0b-bbaf-444a9a070453.png)
