### ISSUE TITLE
Error displays on "Property" page.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7375]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/216910136-4853312e-b96b-4a29-8e72-5927b3677929.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Click on the project, click "Property Pages" button on "Properties" panel.

**Expected behavior**

No error.

**Additional context and screenshots**

Error displays on "Property" page.

![image](https://user-images.githubusercontent.com/82852072/216910610-b9044291-e91e-406c-9354-4982008aa74c.png)

**Comment by StellaHuang95** [comment]
Hi @ttSpace, I can't repro this, does this still repro in the latest version of VS?

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build ```17.6.0 Preview 2.0 [33407.118.main]```, Python Package: ```17.0.23033.1```.

![image](https://user-images.githubusercontent.com/82852072/217463154-709c6031-cacb-4be9-8a7c-f8306e77207f.png)
