### ISSUE TITLE
Live Share: Error List doesn't display errors or warnings in VS client

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7376]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/216922882-eba7e3ca-25c2-4c7f-afe9-ce86e67caa49.png)

**Steps to Reproduce**
1.Create a Python Application.
2.Open Live Share, make connection between host and client.
3.Write some problematic code in VS clien
4.Check green wave-underline is expected under problematic code
5.Check the errors and warnings should display in the Error List Window

**Expected behavior**
Green wave-underline is under problematic code and the errors and warnings should display in the Error List Window in VS client

**Actual behavior**
![image](https://user-images.githubusercontent.com/59192491/216925595-63175acc-157c-4d96-b6e0-46bca9118e50.png)

**Additional context and screenshots**
The Error List Window works well in VS Host
![image](https://user-images.githubusercontent.com/59192491/216925520-a18482c0-fb6b-423d-b1eb-6c89cbe205c7.png)

**Comment by StellaHuang95** [comment]
This issue is also being tracked here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1743214, so close it as duplicate.
