### ISSUE TITLE
Cannot add existing virtual environment.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7377]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/216924463-42e765a2-9447-4378-87c1-ad6efa1a0c29.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Right click Python Environment -> Add environment -> Existing environment.
3. Select the Environment drop-down, then select Custom.
4. Path to the existing virtual environment.
eg: ```C:\Users\vting\source\repos\PythonApplication1\PythonApplication1\env1```

**Expected behavior**

All parameters should be automatically filled.

**Additional context and screenshots**

Some parameters are not automatically filled.

![image](https://user-images.githubusercontent.com/82852072/216928548-5e4f054e-b3b5-44ed-a34b-9ce16758305d.png)

BTW, it can add the existing python installed from VS.

![image](https://user-images.githubusercontent.com/82852072/216930121-8aa361f2-30ab-4598-b44f-b01842ca89bd.png)

**Comment by StellaHuang95** [comment]
Hi @ttSpace, does this still repro on the latest version? I couldn't repro this one either.

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build ```17.6.0 Preview 2.0 [33407.118.main]```, Python Package: ```17.0.23033.1```.
