### ISSUE TITLE
Conda env is missing after updating python latest version

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7378]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/216937634-3eed8490-4661-456a-94ca-cec853cf37c6.png)

**Steps to Reproduce**
1.Launch VS and create a project
2.Create a conda env
![image](https://user-images.githubusercontent.com/59192491/216937959-e73d8c1b-142c-48e8-94ab-fd3ddd173e96.png)
![image](https://user-images.githubusercontent.com/59192491/216937885-31ae0892-5afa-4b49-af3f-c2e4a5b86fd8.png)
3.Create conda env successfully
4.Upgrade python version 3.7-->3.11

**Actual behavior**
The conda env display missing
![condaenvmissing](https://user-images.githubusercontent.com/59192491/216938498-f83f48fb-f4fd-4361-9a35-c548ccbd7470.gif)

**Comment by StellaHuang95** [comment]
After the fix, the missing label will still show up for a second as it's waiting for re-discovery, then the proper environment will show up.
