### ISSUE TITLE
Adequate file level permissions missing for Python Extension 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7381]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adequate-file-level-permissions-missing-/10259138)._

---
[severity:It bothers me. A fix would be nice]
Problem -1
I created a Python project.
I updated MVS Community to latest Preview 3.0.
I started debugging my Python project on debug mode.
I saw error messages on the console output.
The console output is attached.
The screenshot of the MVS version information is attached.
The screenshot of the file permission related to the permission error message is attached.

Problem - 2
While reviewing the above console log, a log entry related to Python 3.11 Win64 installation logging the win 64 bit environment as Win32 was found.

---
#### Feedback Bot on 1/23/2023, 10:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
We shouldn't be installing .pyc files at all; it's probably a bug in our packaging script for debugpy that doesn't clean up the folder before adding it to installer.

**Comment by int19h** [comment]
I'm really curious as to where those .pyc files come from, because we aren't installing them (at least as of VS 17.5.0 final), and Python itself should not have the permissions to create a `__pycache__` folder in that location. If you delete it, does it reappear?
