### ISSUE TITLE
Live Share: The error is repeated twice in the error list on client.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7385]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/217174717-9e030080-4a8e-4acc-b7bf-6718c8432c14.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Open Live Share, make connection between host and client.
3. Type `import xxx` in the client
4. Check the error list

**Expected behavior**
It should match with the host.

**Additional context and screenshots**
On host 
![image](https://user-images.githubusercontent.com/59192491/217176993-0a6fe975-8791-4d17-9daf-a11bf4ff2644.png)

On client
![image](https://user-images.githubusercontent.com/59192491/217177245-9eb71812-3615-47df-ba73-332dc9cadc9d.png)

**Comment by StellaHuang95** [comment]
This issue is being tracked here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1743214

**Comment by ttSpace** [comment]
I can repro this in today's build.

![image](https://user-images.githubusercontent.com/82852072/230295029-b5f406b4-17f3-4593-b831-03a071a87aa7.png)

**Comment by StellaHuang95** [comment]
Closing as it's not ours to fix. See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1708784
