### ISSUE TITLE
Some Intellisense doesn't work.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7387]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/217471072-3ae59a9c-ffc2-4614-90f0-c3789bf07972.png)

**Steps to Reproduce**

1. Create a Python Application.
2. Type the following:

![image](https://user-images.githubusercontent.com/82852072/217471666-91eae360-38c3-4966-bbbd-42448c2c9df2.png)

![image](https://user-images.githubusercontent.com/82852072/217471902-78e13350-ce02-477e-90e7-7c049b754d69.png)

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/217471785-4cf5da7b-0e0a-4631-a1b0-e285a7c5e4b2.png)

![image](https://user-images.githubusercontent.com/82852072/217472114-54ca6eff-5ea4-426b-9d42-d080434d77aa.png)

**Comment by ttSpace** [comment]
I can repro in today's build ```17.6.0 Preview 2.0 [33421.343.main]```, Python Package ```17.0.23047.1 ``` .

![image](https://user-images.githubusercontent.com/82852072/220533580-9de2c5b0-e34b-4846-b224-b5de8e239d9f.png)

**Comment by StellaHuang95** [comment]
@ttSpace I couldn't repro this, could you verify?

**Comment by ttSpace** [comment]
@StellaHuang95  I can't repro this in today's build ```17.7.0 Preview 1.0 [33605.512.main]```, Python Package ```17.0.23089.2```.
![image](https://user-images.githubusercontent.com/82852072/230296528-d3215a25-9bca-4ee5-9e99-b84c9dbbd7f4.png)
