### ISSUE TITLE
The type information displayed wrong for sys.exc_info with the latest typeshed.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7388]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/217464832-6ff36bd4-def3-4ef0-9835-94d7f08b53c7.png)

**Steps to Reproduce**

1. Ensure the option is unchecked by default
    a. Check there is type information in below example
![image](https://user-images.githubusercontent.com/82852072/217466533-27cb5c51-55b3-40f5-b42b-1c03265a3d0c.png)
![image](https://user-images.githubusercontent.com/82852072/217466848-1d59e5f7-ae37-42cd-8a5f-3e5ddf6fd37f.png)
![image](https://user-images.githubusercontent.com/82852072/217466875-c8185a88-0685-430d-94a5-08adf2150395.png)

2. Custom Typeshed path
    a. git clone https://github.com/python/typeshed, enter the local path on disk where you cloned the repository

![image](https://user-images.githubusercontent.com/82852072/217467097-03b732ce-9257-499e-8dcb-cd9ab2b7b340.png)

    b. open typeshed/stdlib/sys.pyi

<p>

```
		def exc_info() -> Tuple[Optional[Type[BaseException]],
		                        Optional[BaseException],
		                        Optional[TracebackType]]: ...

```

</p>

With this instead:

<p>

```
		def exc_info() -> Tuple[Optional[Type[BaseException]],
		                        Optional[BaseException],
		                        Optional[_version_info]]: ...
```

</p>
3. Close and reopen the project

**Expected behavior**

It should now report e3 as being a version info instance

![image](https://user-images.githubusercontent.com/82852072/217468254-9b6c1e23-c599-4809-8b02-6676cbbe68ee.png)

**Additional context and screenshots**

The type information has not changed with latest typeshed.

![image](https://user-images.githubusercontent.com/82852072/217474202-f01925e1-0fd0-4e1b-9931-46343d3c9821.png)

![image](https://user-images.githubusercontent.com/82852072/217474250-5e4a8c6e-8d88-4560-b826-6a26f5b3a82c.png)

![image](https://user-images.githubusercontent.com/82852072/217474311-059a4a0b-e8cc-472c-a6f1-7cadf1976321.png)

**Comment by StellaHuang95** [comment]
I didn't find
```
def exc_info() -> Tuple[Optional[Type[BaseException]],
                        Optional[BaseException],
                        Optional[TracebackType]]: ...
```
in the file, but I tried the following and the issue doesn't seem to repro:
1. Without typeshed paths info:
![image](https://user-images.githubusercontent.com/100439259/217633348-40269d23-dbf0-47ab-a0f7-0efe456ce9bf.png)
2. Go to typeshed/stdlib/sys.pyi and change `def getallocatedblocks() -> int: ...` to `def getallocatedblocks() -> str: ...`
3. Enter typeshed path:
![image](https://user-images.githubusercontent.com/100439259/217633698-611b805d-fadf-4b46-ad2a-1f16973b18c9.png)
