### ISSUE TITLE
visual studio 2022 disable pydevd warning

### ISSUE THREAD

**Issue by lch32111** [microsoft/PTVS#7389]
**Describe your question**
I'd like to know where I can disable pydevd warning about something slow in visual studio 2022.

**What have you tried?**
I searched and found that you can set some specific flag to disable the warning in visual studio 'code' from [this](https://stackoverflow.com/questions/71695716/pydevd-warnings-in-visual-studio-code-debug-console). But I can't find any information for visual studio.

**Comment by StellaHuang95** [comment]
You could change the environment variable here: Debug -> Properties -> environment variable. See https://learn.microsoft.com/en-us/visualstudio/python/debugging-python-in-visual-studio?view=vs-2022#run-options-search-paths-startup-arguments-and-environment-variables

**Comment by lch32111** [comment]
@StellaHuang95 

Thank you for your quick reply!

In my case, I opened my python visual studio on a folder with right click -> Open With Visual Studio.
I think I can't find the Debug-Properties-Environment tab in my visual studio project.

So I right-clicked my python file on the solution explorer and then clicked the `Add Debug Configuration`.
It generates launch.vs.json file for me that you can add environment variables like visual studio 'code'.

after adding the variable like this, I could disable the warning.
Thanks!

```json
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "python",
      "interpreter": "(default)",
      "interpreterArguments": "",
      "scriptArguments": "",
      "env": { "PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT": "2" },
      "nativeDebug": false,
      "webBrowserUrl": "",
      "project": "experiment.py",
      "projectTarget": "",
      "name": "experiment.py"
    }
  ]
}
```
