### ISSUE TITLE
NullReferenceException in ReverseExpressionParser.GetExpressionRange

### ISSUE THREAD

**Issue by aewhatley** [Microsoft/PTVS#739]
When I hover my cursor over a particular function call, it gives me an error message "An exception has occurred. This may be caused by an extension." The problem is, I have no extensions currently installed, and PTVS in both VS 2013 and 2015 give me this error. Here is the attached screenshot:
![image](https://cloud.githubusercontent.com/assets/11060902/9242956/2479ed98-414f-11e5-9e7f-8a8b861910a5.png)

I get the error message while hovering over the line that reads : "reduceFn = ReduceFn(dbinfo=dbinfo, **dbopts)"

**Comment by aewhatley** [comment]
Here's a screenshot of the log file:

![image](https://cloud.githubusercontent.com/assets/11060902/9243030/861824b0-4150-11e5-8f1e-700b7e88176e.png)

**Comment by zooba** [comment]
Stack trace is:
```
System.NullReferenceException ...
at Microsoft.PythonTools.Intellisense.ReverseExpressionParser.GetExpressionRange(...)
at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.AnalyzeExpression(IServiceProvider, ITextSnapshot, ITrackingSpan, Boolean)
at Microsoft.PythonTools.Intellisense.QuickINfoSource.AugmentQuickInfoSession(IQuickInfoSession, IList`1, ITrackingSpan&)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()
...
```

(Please ignore typos - I copied from the screenshot.)

**Comment by zooba** [comment]
Thanks for the report, I don't think we've seen this one before.

For reports like these, we're fine with the text copy-pasted out of `ActivityLog.xml` (or just paste the entire file into a gist if you like and we'll track down the exception). Screenshots are a bit of a pain in this case :)
