### ISSUE TITLE
Failed to launch debug adapter using Anaconda Environment.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7392]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Failed-to-launch-debug-adapter-using-Ana/10267902)._

---
[severity:It bothers me. A fix would be nice]
Hello, i had a problem when i run code `print('Hello')` in Python using Conda Environment, it shows : 
![image.png](https://aka.ms/dc/image?name=B6a556e5cf64143ecba4809543cbc611d638108926350906085_20230202-065713-image.png&tid=6a556e5cf64143ecba4809543cbc611d638108926350906085)
 and the debug message shows : 
`The program 'python.exe' has exited with code 4294967295 (0xffffffff).`, which it doesn't show the window of my program output

I have Conda Environment named 'radeonzero' using Python 3.6.13 64-bit version, but when I run code in python.exe in my radeonzero Conda Environment, it shows perfectly of my output program 
![image.png](https://aka.ms/dc/image?name=Bd36a85ed07ae4f24a5777b67fb22072f638108929405229201_20230202-070219-image.png&tid=d36a85ed07ae4f24a5777b67fb22072f638108929405229201)

I hope anyone can give a solution on how to fix this..Thanks and stay healthy

---
#### Feedback Bot on 2/1/2023, 07:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment]
We do not support Python 3.6, as it has been out of support upstream since 2022.
