### ISSUE TITLE
No ESLint module was found while trying to lint about.html.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7398]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/218670920-0fe5852f-2a92-4df9-b904-57b1a7914b00.png)

**Steps to Reproduce**

1. Create a Django Web Project.
2. Navigate to app/about.html.
3. In a "Django Web Project", validate html completions in app/about.html.

**Expected behavior**

Html completions appear when typing '<' and contain the standard expected set of html elements valid for that position.

![image](https://user-images.githubusercontent.com/82852072/218672125-c12a02f1-fb05-4f2a-85a0-65287a5adee4.png)

**Additional context and screenshots**

No ESLint module was found while trying to lint about.html and no IntelliSense about html.

![image](https://user-images.githubusercontent.com/82852072/218672343-2e9245de-4960-4ba6-8984-e992a2613918.png)

**Comment by StellaHuang95** [comment]
I can't repro it, can you try again on the latest version? 
![image](https://user-images.githubusercontent.com/100439259/218829683-0850b1ea-9f5e-4353-8fdb-b0510ab3331f.png)

**Comment by ttSpace** [comment]
I can repro in today's build.

![image](https://user-images.githubusercontent.com/82852072/219537238-7947d903-9f12-480d-a4ad-cfe78342b006.png)

**Comment by StellaHuang95** [comment]
Looks like someone has files a similar issue on AzDo: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1735958

**Comment by ttSpace** [comment]
@StellaHuang95 I can't repro it in today's build ```17.7.0 Preview 1.0 [33605.512.main]```, Python Package ```17.0.23089.2```.

![image](https://user-images.githubusercontent.com/82852072/230295713-a18a1f10-7675-47c1-ae73-dee28726ffef.png)
