### ISSUE TITLE
Detect Unicode and save files with proper encoding so users don't lose data

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#74]
The default encoding for .py file sseems to be Western European (Windows). If possible we should detect when users input Unicode chars into a file and automatically save as UTF-8. 
 Otherwise users have to change the encoding themselves manually if they type Unicode into the file or they'll lose data -- saving a file normally results in Unicode chars that can't be represented in the Western European encoding being saved as "??????". 

Before you save: 
![python-encoding-before-save](https://cloud.githubusercontent.com/assets/1693688/7459281/ae057c8e-f24f-11e4-97f3-8b20078b4a56.png)

Click save, then close/reopen the file, and it looks like this: 
![python-encoding-after-save](https://cloud.githubusercontent.com/assets/1693688/7459286/b227a846-f24f-11e4-9d11-ea47674e53e8.png)

In C++ projects, when you save, it doesn't silently lose your data, it warns you: 
![cpp-encoding-save-prompt](https://cloud.githubusercontent.com/assets/1693688/7459291/b5c484f6-f24f-11e4-82ec-4a367b293a6b.png)

As far as I know, all the supported versions of Python will read UTF-8 files with a BOM, but assume 7-bit ASCII otherwise. PEP 0263 (http://www.python.org/dev/peps/pep-0263/) discusses/resolves this.

We should default to UTF-8 for Python 3.x projects:  http://docs.python.org/release/3.0/reference/lexical_analysis.html?highlight=UTF-8#encoding-declarations

(Migrated from https://pytools.codeplex.com/workitem/107)

**Comment by MikhailArkhipov** [comment]
There is no 'default encoding' for plain text files as there is no encoding designator available such as `<meta>` in HTML or `<?xml` PI in XML. So it is up to user to choose UTF-8 with BOM (drawback: some editors don't understand BOM and show weird symbols) or live with this.

VS follows pattern of the file template. If template has BOM, everything auto-magically works.

**Comment by zooba** [comment]
For Python files (which are not plain text) we default to UTF-8 without BOM unless there is a BOM or a [coding comment](https://www.python.org/dev/peps/pep-0263/). We used to default to ASCII because that's what Python 2.x assumes, but since Python 3.x assumes UTF-8 unless there is useful information, we now assume the same.
