### ISSUE TITLE
After changing the settings it didn't work.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7400]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/220552173-6398c3a8-8620-4115-b3fb-dc66ee3c2280.png)

**Scenario 1**

**Steps to Reproduce**

1. Check  "Automatically add brackets for functions" (Tools/Options/Text Editor/Python/Advanced)
2. Add "import os" to python file.
3. Write "os.getc", you'll see autocomplete for os.getcwd, selecting it, ensure:
            a. Auto-complete adds os.getcwd() to the source code.

**Additional context and screenshots**

Only os.getcwd is added to the file.

![image](https://user-images.githubusercontent.com/82852072/220553174-9e2172b0-e059-4cd4-b535-3d53c4f0f0c7.png)

**Scenario 2**

**Steps to Reproduce**

1. Without typeshed paths info:

   ![image](https://user-images.githubusercontent.com/82852072/220555629-8e2c7f88-9405-43bc-b1e7-b89f1e4a328f.png)

3. Custom Typeshed path
       a. git clone https://github.com/python/typeshed, enter the local path on disk where you cloned the repository

![image](https://user-images.githubusercontent.com/82852072/220799719-4eb286a9-0141-4664-bd5d-825251788937.png)

       b. Go to typeshed/stdlib/sys.pyi and change `def getallocatedblocks() -> int: ...` to `def getallocatedblocks() -> str: ...`
 
**Additional context and screenshots**

Nothing has changed.

![image](https://user-images.githubusercontent.com/82852072/220555484-cba89193-cd41-463a-b598-379c6367f5e8.png)

**Comment by StellaHuang95** [comment]
@ttSpace Scenario 1 is by design, I can also repro in vscode so it's not a PTVS issue. For scenario 2, did you add the path to the typeshed path in options?

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build ```17.6.0 Preview 2.0 [33423.321.main]```, Python Package: ```17.0.23047.1```.
After changing the settings, it works.

Scenario 1 : Check "Automatically add brackets for functions" (Tools/Options/Text Editor/Python/Advanced).

![image](https://user-images.githubusercontent.com/82852072/221115267-b781e1a9-da18-4611-9e88-4252e3bb63fe.png)

Scenario 2：Enter typeshed path.

![image](https://user-images.githubusercontent.com/82852072/221115883-02d31874-fe5b-4999-8287-f95cd3c2163b.png)
