### ISSUE TITLE
German umlaute stops unittests from working in Python (VS2022)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7411]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/German-umlaute-stops-unittests-from-work/10283932)._

---
[severity:It's more difficult to complete my work]
The unittests for python in VS 2022 will not be recognized if german "Umlaute" (ä ö ü ß) appears in any comment line.

---
#### Feedback Bot on 2/19/2023, 05:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, you can try the followings:

Go to File -> Save As -> click the dropdown button next to Save, choose save with encoding -> choose UTF-8 and re-run the tests.

 Please re-open the ticket if the issue still persists, thanks!
