### ISSUE TITLE
After changing the settings it didn't work. 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7416]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/221784138-8f10cd2a-9954-4514-aa6a-33145fb5f878.png)

**Scenario 1**

**Steps to Reproduce**

1. Check  "Automatically add brackets for functions" (Tools/Options/Text Editor/Python/Advanced)
2. Add "import os" to python file.
3. Write "os.getc", you'll see autocomplete for os.getcwd, selecting it, ensure:
            a. Auto-complete adds os.getcwd() to the source code.

**Additional context and screenshots**

Only os.getcwd is added to the file.

![image](https://user-images.githubusercontent.com/82852072/220553174-9e2172b0-e059-4cd4-b535-3d53c4f0f0c7.png)

**Scenario 2**

**Steps to Reproduce**

1. Without typeshed paths info:

   ![image](https://user-images.githubusercontent.com/82852072/220555629-8e2c7f88-9405-43bc-b1e7-b89f1e4a328f.png)

3. Custom Typeshed path
       a. git clone https://github.com/python/typeshed, enter the local path on disk where you cloned the repository

![image](https://user-images.githubusercontent.com/82852072/221784993-2df5579a-5aaa-4ac6-a6f3-f0b5dfb648f9.png)

       b. Go to typeshed/stdlib/sys.pyi and change `def getallocatedblocks() -> int: ...` to `def getallocatedblocks() -> str: ...`
 
**Additional context and screenshots**

Nothing has changed.

![image](https://user-images.githubusercontent.com/82852072/220555484-cba89193-cd41-463a-b598-379c6367f5e8.png)

**Comment by bschnurr** [comment]
custom typeshed path appears to be working.

`Version 17.6.0 Preview 3.0 [33505.110.main]`
