### ISSUE TITLE
No intellisense when from 'PYTHONPATH'

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7417]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/221784789-88ba0073-b631-44bd-989a-ac79f3197c10.png)

**Steps to Reproduce**
1.Create a module7.py under D:\testpythonpath
2.Add the module7.py path to PYTHONPATH
![image](https://user-images.githubusercontent.com/59192491/221785651-1b933128-ffb7-4dfd-886c-4a17ba1dc27e.png)
3.Launch VS and create a python project, make sure "Ignore system-wide PYTHONPATH variables" is unchecked
![image](https://user-images.githubusercontent.com/59192491/221786491-67af7934-79de-449d-b657-1cc864b6001d.png)
4.Add PYTHONPATH to search path
![image](https://user-images.githubusercontent.com/59192491/221788130-89e38521-d7c1-4ad9-8ad7-18ed7874ce8e.png)
5.Type sample code to get intellisense from 'PYTHONPATH'

**Expected behavior**
I can get intellisense from 'PYTHONPATH'

**Actual behavior**
I can not get 'module7'
![image](https://user-images.githubusercontent.com/59192491/221788356-f132e439-88be-47c9-b34a-40270828a2a2.png)

**Additional context and screenshots**
![pythonpath](https://user-images.githubusercontent.com/59192491/221788590-60756cad-21ad-4f91-83c6-df7759d4c479.gif)

**Comment by linette-zyy** [comment]
In today's latest build:**17.6.0 Preview 2.0 [33501.332.main]**, Python package:**17.0.23055.1**
```Ignore system-wide PYTHONPATH variables``` is checked by default, and I don't ```Add PYTHONPATH to Search Path```
I can still get the intellisense
![pythonpath20230302](https://user-images.githubusercontent.com/59192491/222386765-cd3f5fcc-19e4-42f0-8c13-1be8d36d585f.gif)

**Comment by judej** [comment]
@linette-zyy, could you remove these tests from the scenarios please

**Comment by linette-zyy** [comment]
@judej, ok, I have removed these tests from the scenarios.
