### ISSUE TITLE
"Attempting to add already-known thread" constantly occurs when debugging multi-threaded python app

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/PTVS#7426]
[severity:I’m unable to use this version]

Occurs randomly while debugging. When it occurs, debugging session is terminated and the task is killed. Seen 50+ times. No known way to get around.

Doesn’t need to be paused to reproduce, however single stepping seems to make the bug much more likely to occur.

Simplest way to reproduce is basic multithreading code such as:

```
def NextTask(...):
        def WorkerThread(pOpen, stdin):
            if stdin is not None:
                stdin = stdin.encode("utf-8")

            (o, e) = pOpen.communicate(stdin)

            if o is not None:
                self.outputstdOut = o.decode("utf-8")
            if e is not None:
                self.outputstdErr = e.decode("utf-8")

            if self.outputLock.locked():  # In case we timed out...
                self.outputLock.release()

        t = Thread(target=WorkerThread, args=(pOpen, stdIn))

        self.bgThread = t

        t.start()```
```
    RunDebuggerToThisLine()
    StartPressingF10()
    NextTask(subprocess.POpen(...),...))
    GoodLuckEverGettingHere()```

Associated work item: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1752703

**Comment by int19h** [comment]
Would it be possible to get a self-contained repro? It's not clear to me what all the `...` are supposed to be in the snippet above.

Also, is this by chance remotely debugging code that is running on Linux or macOS?
