### ISSUE TITLE
Python Search Path not Resolving

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7440]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-Search-Path-not-Resolving/10296028)._

---
[regression]
I have a Python solution and project which references another project relative as "../../Shared" using the Search Path. Before updating to 17.5.1 these imports would resolve... For awhile. Eventually it would stop resolving and I would have to restart Visual Studio. Now with the latest 17.5.1 update, immediately any and all of my imports fail to import, which means I get the green squiggles under imports the value(s) that reference them, and cease to get any Intellisense.

The paths have not changed, and I am able to run the program successfully with no issue. The only problem is with the Intellisense and recognizing the search path(s).

---
#### Feedback Bot on 3/1/2023, 05:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, Thank you for reporting the issue that you encountered. I was not able to repro this, could you please provide us with the specific steps, sample code or screenshots? Did you notice anything unusual output from pylance?

**Comment by iNightfaller** [comment]
> Hi there, Thank you for reporting the issue that you encountered. I was not able to repro this, could you please provide us with the specific steps, sample code or screenshots? Did you notice anything unusual output from pylance?

I'm not too sure if pylance is what I'm looking for in Visual Studio (I'm not using VSCode). 

Unfortunately I'm unable to repro it on my other computer. I am trying a few things on the other computers it's affecting to see if I can find something common with the setups.
