### ISSUE TITLE
Anaconda/Conda environments are broken in VS2022, works in VS2019

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#7444]
From e-mail, repro steps:

1. Install Anaconda
2. Add a new conda environment, set as default for new projects

![image](https://user-images.githubusercontent.com/29436557/223851246-f9668a63-cad8-48d2-af65-bb5a55fb025c.png)

3. Restart VS. Create a new python application.
4. Anaconda environment is not loaded, Python 3.9 is set as default:

![image](https://user-images.githubusercontent.com/29436557/223851485-5ba9e3ef-b871-4da6-bc84-e8fb7ce5fbf5.png)

5. Wait for about 30 seconds, the anaconda environment is loaded as shown below. However, it is not set to default because VS has already set it to Python 3.9:

![image](https://user-images.githubusercontent.com/29436557/223851595-94dce648-48b9-4f59-aa26-497917fb24f9.png)

**Comment by excubo-jg** [comment]
That's a nuisance which I think I began to see regularly since like a month or so. Before that change, the conda envs tended to disappear in VS2022 and one had to re-add them. The inconsistencies between the entries in this drop-down and the envs shown in the solution explorer/python-environments are not as common as before but still there.

**Comment by AdamYoblick** [comment]
Yeah I'm almost positive that it's a race condition. The conda environments are enumerated in another thread because they can take a while to finish and we don't want to freeze the UI. We don't seem to be waiting for this thread to finish which can cause problems like this. So I need to find a good solution.

The easy solution is just to await the async operation that finds the conda envs. But this will stall the project load. If there are lots of conda envs, it might stall by quite a bit.
The better solution is to notify when conda envs are done being detected and refresh the env list and current active environment when it's done. However, this is significantly more work since it would require a good amount of refactoring around project load, etc.

I'm going to look into it 😄

**Comment by AdamYoblick** [comment]
OK I've looked into this a bit more, and it seems like this is two different bugs interacting with each other.

The project system part of PTVS does seems to contain a node for the missing environment. But when the project finishes loading, that node is removed, maybe because the environments are still being enumerated.

![DisappearingEnv](https://user-images.githubusercontent.com/29436557/226482789-89efdf47-70fc-448f-bf07-96b50475c94e.gif)

What should be happening here is the environment node (or the parent one) should be waiting on conda environments to be detected. That part doesn't seem to be working properly, because going to Add Environment -> Existing Environment does show the conda env available to be added. So that's where I'm going to start.
