### ISSUE TITLE
Support for Python Intellisense can't handle "from <module> import *" construct

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7448]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Support-for-Python-Intellisense-cant-ha/10299262)._

---
[severity:It bothers me. A fix would be nice]
In an editor window for a Python file, possible code problems are marked. For example, an undefined symbol has a green squiggle line.
Browsing support for Python can handle 'import' statements and correctly import browsing data for such modules. It appears, though, that the construct:

```
from  import * 
```
Is not properly importing names defined in the module. "from ... import ..." imports names into the current namespace, without the module name prefix. Visual Studio shows such names as undefined. If you explicitly import names from a module, VS shows them as defined. See the attached recording.

---
#### Feedback Bot on 3/5/2023, 10:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, I can only see limited screenshots from the repro steps uploaded. In order to understand your issue better, I have created a simplified version of your code. 😊Based on my understanding, are you indicating that you're only seeing the `func1()` in consume.py has the green squiggles? What does the error say?

```python
# declare.py
def func1():
    print("func1")

def func2():
    print("func2")
```

```python
# consume.py
from declare import *
from declare import func2
func1()
func2()
```
