### ISSUE TITLE
...I can't close it because it is hidden under another element

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7456]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-cant-close-it-because-it-is-hidden/10305568)._

---
[severity:Other]
![image.png](https://aka.ms/dc/image?name=B1345b6ef9ae545c1945f7d37f6dfdb7b638139548326922798_20230309-123508-image.png&tid=1345b6ef9ae545c1945f7d37f6dfdb7b638139548326922798)
I got an error window, but I can't close it because it is hidden under another element. Therefore, I had to crash the Visual Studio 2022.

---
#### Feedback Bot on 3/9/2023, 06:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
![image](https://user-images.githubusercontent.com/100439259/225426606-401d4c61-7082-44b6-8610-6c6dadc0637e.png)

**Comment by StellaHuang95** [comment]
Does this happen to you constantly? Mine has these little triangles that allow me to fold/unfold info.
![image](https://user-images.githubusercontent.com/100439259/225426872-1348adb1-0026-411b-b36b-7b501935451a.png)
