### ISSUE TITLE
Python project build after they are disabled in solution config manager 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/PTVS#7458]
**Describe the bug**
For a large solution (mainly C/C++) distro is created from a batch file by calling: devenv solution_file.sln /Rebuild

Even though Python projects disabled in the solution configuration manager, they attempt to 'build' and fail with many errors (first being 'unable to load python tools'). 

**Expected behavior**
Python project is not included in the build once it is disabled in the solution configuration manager. 

(Feedback from PTVS survey)

**Comment by StellaHuang95** [comment]
We would need more detailed repro steps and a sample code that demonstrates the problem for us to better understand and address this issue. We haven't received similar complaints from other users as of now. So for now, I will mark this issue as closed, and if others encounter a similar problem, we can revisit and gather additional information to investigate further.
