### ISSUE TITLE
PTVS does not notify when library does not exist upon install

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/PTVS#7459]
**Describe the bug**
When installing a library that doesn't exist (type mismatch, wrong information, etc.) PTVS says "Installing" and later shows errors due to the fact that the library is not found. 

**Expected behavior**
Expect to search the library and notify the user if the library is not found. 

(Feedback from PTVS survey)

**Comment by StellaHuang95** [comment]
We do show errors in the latest VS. Needs more info on what the user means. I doubt if there's anything we can do here, we basically just show whatever the pip install command returns.
![image](https://user-images.githubusercontent.com/100439259/227020522-1cafdee9-d4c5-49e1-b42b-b2c68e0e4471.png)
