### ISSUE TITLE
Anaconda displays incorrectly in environment list

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7461]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/226815009-668f7c26-920c-4b18-a623-4b85b1cf0223.png)

**Steps to Reproduce**
1.Install Anaconda (downloads at https://www.anaconda.com/download/) if no Anaconda 
![image](https://user-images.githubusercontent.com/59192491/226815285-914cf230-ff74-4981-900b-51f4e084621a.png)
![image](https://user-images.githubusercontent.com/59192491/226815392-7a4256f8-c439-43c0-85e6-1f0b11cac2ff.png)
![image](https://user-images.githubusercontent.com/59192491/226815422-6c25571b-102b-4061-b544-8dc4c2507b76.png)
![image](https://user-images.githubusercontent.com/59192491/226815481-a66a471f-91df-4ae3-8319-4f9eb25c9d22.png)
2.Create Python Application project 
3.Right-click on Python Environments node in SE and select "View All Python Environments" 
4.Check the environment list

**Expected behavior**
The Anaconda installed from https://www.anaconda.com/download/ should display correctly
![image](https://user-images.githubusercontent.com/59192491/226815916-d2e0b1a4-e621-4ef5-80c0-901e26738b7f.png)

**Actual behavior**
Anaconda displays incorrectly in environment list
![image](https://user-images.githubusercontent.com/59192491/226816285-25718ef4-a49c-4479-bf30-96ca7b806461.png)

**Comment by StellaHuang95** [comment]
I wasn't able to repro this. Could you please try again? If it still repros, I suspect it has to do with what happens in this issue: https://github.com/microsoft/PTVS/issues/7444. Could you wait for a while before checking the environment list as described in step 5 in that issue and see if that works?

**Comment by linette-zyy** [comment]
@StellaHuang95 
In today's latest build:**17.6.0 Preview 3.0 [33522.427.main]**, Python package:**17.0.23068.1**
I can repro this after installing Anaconda in a new VM
![image](https://user-images.githubusercontent.com/59192491/227085070-0bb572a6-f3df-48ec-a88d-294cddfbd581.png)
![image](https://user-images.githubusercontent.com/59192491/227085114-ec51665c-72c9-4a6c-9a42-4f546d0bcb53.png)

**Comment by StellaHuang95** [comment]
@linette-zyy Does the anaconda environment get loaded after waiting for about 1min?

**Comment by linette-zyy** [comment]
@StellaHuang95 
anaconda environment doesn't get loaded , I have waited for more than 1minute

**Comment by StellaHuang95** [comment]
So the default Python interpreter installed with Anaconda that's not associated with any specific environment, is usually installed at `C:\ProgramData\Anaconda3\python.exe`. When you run Python from this location, it uses the libraries and packages installed in the base environment.

The other way is to create an isolated virtual environment that allows you to install packages and dependencies independently of the global Anaconda environment. Those ones are normally located at `C:\Users\xxx\Anaconda3\envs\my-env\python.exe`.

The `python 3.1` in your screenshot is the base environment installed with Anaconda so it's showing up correctly, so I don't think it's a bug.

**Comment by yalov** [comment]
> The python 3.1 in your screenshot is the base environment installed with Anaconda

are you talking about some kind of internal "base" environment for anaconda, and not the system "base" python?

I have miniconda and VS2022, and the only python environment detected by VS2022 is showed as Python 3.1, while I have 3.11.5 as base Python version from miniconda installment

VS2022:
![](https://i.imgur.com/mHKohm7.png)

cmd.exe
```
C:\Users\user>activate base
(base) C:\Users\user>where python
C:\Users\user\miniconda3\python.exe
(base) C:\Users\user>python -V
Python 3.11.5 
```
