### ISSUE TITLE
Rename with ctrl-r ctrl-r doesn't work correctly UI is not working.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7465]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Rename-with-ctrl-r-ctrl-r-doesnt-work-c/10308486)._

---
Typing ctlr-r ctrl-r to do a rename, in a python file.
Expect: the rename dialog UI thingy pops up and allows me to type the new name
Actual: sometimes it comes up and works correctly, and sometimes it appears briefly and then disappears.  And after the disappearance subsequence attempts to use ctrl-r ctrl-r make a beep and say it is not available now.  However right click rename does work correctly - it is only the keyboard shortcut that is unreliable.

---
#### Feedback Bot on 3/13/2023, 06:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mcginnie** [comment]
This problem persists
