### ISSUE TITLE
VS unable to pass "find symbol" for external Python files

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7468]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-unable-to-pass-find-symbol-for-exte/10312922)._

---
[severity:It's more difficult to complete my work]
It appears that "Find symbol" (F12) operation for Python files receives the external Python parser results which are returned in some MinGW or Cygwin format as:
>/c:/program files/microsoft visual studio/2022/preview/common7/ide/extensions/microsoft/python/core/pylance/dist/typeshed-fallback/stdlib/tempfile.pyi(399):def mkdtemp(suffix: str | None = ..., prefix: str | None = ..., dir: StrPath | None = ...) -> str: ...  # type: ignore[misc]
>/c:/program files/microsoft visual studio/2022/preview/common7/ide/extensions/microsoft/python/core/pylance/dist/typeshed-fallback/stdlib/tempfile.pyi(401):def mkdtemp(suffix: bytes | None = ..., prefix: bytes | None = ..., dir: BytesPath | None = ...) -> bytes: ...
>/c:/Python310/Lib/tempfile.py(340):def mkdtemp(suffix=None, prefix=None, dir=None):

Note that the paths use right slashes and are prefixed with one extra slash. Since that extra slash makes it an invalid Win32 path, VS cannot go to the symbol definition, because it doesn't recognize the path.

![image.png](https://aka.ms/dc/image?name=B73170861b414455a823af13919d851ec638145937882077386_20230316-130307-image.png&tid=73170861b414455a823af13919d851ec638145937882077386)

---
#### Feedback Bot on 3/16/2023, 08:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
screenshot from the original ticket: 
![image](https://user-images.githubusercontent.com/100439259/227038601-c7580830-3ecb-45e8-ae44-6ae366533b14.png)

**Comment by StellaHuang95** [comment]
Hi there, could you clarify which exact command you invoked first? Shortcut can vary, and I don't think F12 is the default for Find Symbol. Shift+Alt+F12 is the default for Quick Find Symbol, but the UI it displays is very different from what's on the screenshot. Thanks!
