### ISSUE TITLE
Using Python: Multiline comments

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7483]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Using-Python:-Multiline-comments/10319718)._

---
[regression] [worked-in:Version before ]
Python: Multiline comments ( ’’’ Text ’’’ """ Text """ ) are mixed up with strings after last update. Best Regards.

---
#### Feedback Bot on 3/23/2023, 06:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Can you show me which version of VS are you seeing the colorization is different for multiline comments and strings?
