### ISSUE TITLE
Excessive memory usage in Environments View

### ISSUE THREAD

**Issue by int19h** [microsoft/PTVS#7485]
MemWatson reports Mgd_PythonTools_Microsoft.PythonTools.EnvironmentsList!Microsoft.PythonTools.EnvironmentsList.PipPackageView as the culprit. The problem is that the database of available packages on PyPI is loaded entirely into memory, and furthermore this happens separately for each environment, so as users switch between environments those in-memory databases end up consuming hundreds of megabytes of RAM.

**Comment by int19h** [comment]
From discussions:

> The low-hanging fruit here is making sure that the installable packages list gets cleared as users switch between envs; there's really no reason to keep the list of installable packages in memory for each environment that user has inspected, even once they moved away from it. This should be fairly straightforward, and it would keep the total live count of PipPackageView at the same level, preventing the tool pane from ballooning beyond ~350 Mb (but, of course, this will still get worse as PyPI package count grows). I'm working on this fix; I suggest that we ship that by itself first and see how it affects the numbers out in the wild. 

> Then we can optimize the code to cut down on amount of memory used even without persistent duplicates - this should help with GC. E.g. a bunch of temporary arrays get created to return results from async calls; we can use async enumerables now. But I'm not convinced that this is a long-term solution. Given the sheer amount of data here, I think we need to seriously consider moving to SQLite to cache local package data and then query that from the UI as needed, instead of having the entire view model in memory. This would solve the problem long-term regardless of how large PyPI gets. 

This issue is tracking the first part.

**Comment by int19h** [comment]
Original issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460022

**Comment by bschnurr** [comment]
When changing between environments we weren't always clearing the list of available pip packages in the previous view.

Ideally, we wouldn't load the entire list and create views for them.. but for now just removing the excess memory do to holding on to multiple lists.
