### ISSUE TITLE
[MSFT Internal] An exception of type  MissingMethodException  has been encountered. This may be caused by an extension. 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7486]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/228766407-183c3146-1631-4e48-92cd-3dc574fb73e3.png)

**Steps to Reproduce**
1.Create a Flask Web Project
2.Click create virtual environment

**Actual behavior**
![image](https://user-images.githubusercontent.com/59192491/228766811-777308e5-2d25-4d02-90d3-2790e5bef8c9.png)
![image](https://user-images.githubusercontent.com/59192491/228767204-79d4dd38-2284-420e-95bf-49a132a0506c.png)
[open_log_file.zip](https://github.com/microsoft/PTVS/files/11109157/open_log_file.zip)

**Comment by StellaHuang95** [comment]
This is not a python specific issue, it seems to happen with other languages as well. Were you noticing any features not working?

**Comment by linette-zyy** [comment]
Features is not affected currently
In today's latest build:17.6.0 Preview 3.0 [33530.532.main], Python Package: 17.0.23087.1
I can't repro this
