### ISSUE TITLE
Test Explorer doesn't find tests, it need restart VS

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7487]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/228778620-3a18da41-fec2-4a51-a9a4-1e3f71b72473.png)

**Steps to Reproduce**
1.Launch VS and create a python project
2.Set Test framework to 'unittest'
![image](https://user-images.githubusercontent.com/59192491/228779328-986fd9bd-6946-479e-9a51-245eb45f39f5.png)
3.Add a unittest file
'''
import unittest

class Test_test_1(unittest.TestCase):
    def test_A(self):
        self.fail("Not implemented")

if __name__ == '__main__':
    unittest.main()

'''
4.Open Test Explorer

**Expected behavior**
TE works well

**Actual behavior**
Test Explorer doesn't find tests, when I restart VS, it works well
![image](https://user-images.githubusercontent.com/59192491/228780184-c5bff2bf-76c2-4fcc-a18c-ed607693a19e.png)

**Comment by StellaHuang95** [comment]
I wasn't able to repro this. Could you verify? Did you save the test file before opening the test explorer?
![image](https://user-images.githubusercontent.com/100439259/228921676-5b16ed07-d2ba-40cb-8fc5-78e4d964ab57.png)

**Comment by linette-zyy** [comment]
@StellaHuang95 
In today's latest build:**17.6.0 Preview 3.0 [33530.532.main]**, Python Package: **17.0.23087.1**
I can repro this only when I first do these steps, and I restart VS ,it works well

**Comment by StellaHuang95** [comment]
@linette-zyy Thanks, could you verify if it still repros?

**Comment by linette-zyy** [comment]
@StellaHuang95 
In today's latest build:**17.7.0 Preview 1.0 [33624.386.main]**, Python Package:**17.0.23104.3**
I can repro this when I first launch VS and do this steps, after restarting VS, it works well

**Comment by StellaHuang95** [comment]
I am still not able to repro it, I am on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.7.0 Preview 3.0 [33807.613.main]

**Comment by StellaHuang95** [comment]
@linette-zyy Can you verify if it still repros?

**Comment by linette-zyy** [comment]
I can't repro this issue on today's latest build
![image](https://github.com/microsoft/PTVS/assets/59192491/a1be1070-2ced-4d3c-9b80-502938779e77)
