### ISSUE TITLE
Improve debugger performance by rewriting parts in native code

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#749]
Using Python callbacks for debug events (`sys.settrace`) is incredibly slow due to the overhead of calling and evaluating several lines of Python code for every line executed by the main interpreter loop. Switching to an implementation that has pure native code on the hottest path (i.e. per-line callbacks, determining breakpoints that are hit, no stepping in progress) can give anywhere from 2x to 15x improvement in performance, depending on the code.

Because such an implementation would rely on CPython extensibility API and ABI, it would necessarily be specific to CPython. So this must be optional, with a pure Python fallback for use with PyPy, IronPython, Jython etc.

**Comment by zooba** [comment]
I'd like to see this as just part of a revamped `ptvsd`, such that `pip install --no-use-wheel ptvsd` will be able to compile for the target Python. We *might* be able to get away with doing all builds using VS 2015, but that adds a level of complexity we can avoid fairly easily.

**Comment by int19h** [comment]
It's an interesting problem. On one hand, yes, I do want this to be all buildable with `setup.py` in the normal fashion, and thus becoming a proper part of the package. On the other hand, if we actually need to build it separately for all supported Python versions, the local layout will be a bit of a mess (though I suppose we could just reuse wheels), and we'll also need to load the appropriate version depending on interpreter version for all start and attach scenarios.

Also, the mixed-mode debugger helper native module, which basically does the same thing (and which it _might_ be possible to unify with), is already version-agnostic, using the same basic approach as the attach helper. This means that it also contains most of the supporting code that's needed to do basic stuff like tracing/breakpoints (like, say, string comparison) that we could reuse here.

**Comment by zooba** [comment]
I'm not really a fan of what the attacher does - it's far higher maintenance than it ought to be. But we also don't necessarily need to ship 18 different .pyds - we can limit this to 2.7, 3.4 and 3.5 by default and say "if you pip install ptvsd and compile it then you'll get the speedup too". Then we can add an extra search path to find our PTVS version after any potentially installed versions.

**Comment by int19h** [comment]
One other thought: we would still want ptvsd to be "buildable" (as a pure source package) and installable on implementations where the .pyd won't work because they're not CPython-compatible. Is it possible to make setup.py build work that way? i.e. ignore it and proceed with install if it can't build it?

**Comment by zooba** [comment]
Yeah, though I don't know how off the top of my head. markupsafe does this.

**Comment by denfromufa** [comment]
@zooba @int19h why don't you re-write in 'native cython' like pydevd did?

https://pypi.python.org/pypi/pydevd

**Comment by zooba** [comment]
That's certainly something we'll consider. Of course, we need to redirect the engineering resources to actually do the refactoring necessary to make this possible at all, and right now we're fully booked.

**Comment by zooba** [comment]
From #2328:
* add a public API to register the current thread with the debugger (for cases where we miss doing our own settrace)
 * perhaps use the JIT API to automatically register threads we haven't seen before?

**Comment by mmusket** [comment]
Is there something similar to c# Debugger.break() in PTVS. 
I found this thread after researching why tensorflow takes a century to load when not using the interactive window, and it is in fact the debugger. Ctrl+f5 runs the script super fast. 

If I can attach the debugger after TF loads it would solve my problem since I can skip the slow bits and start debugging more focused parts of the code, and I am sure this would help the other users with the same problem.

**Comment by denfromufa** [comment]
@mmusket I'm using `sys.gettrace()` for this:

https://github.com/Microsoft/PTVS/issues/1347

**Comment by mmusket** [comment]
A little bit of a hack, but worth a go. Thanks

**Comment by denfromufa** [comment]
The debuggers in general are a hack anyway :)

**Comment by denfromufa** [comment]
just tried cythonizing ptvsd and it looks feasible, but i don't know how to resolve this error:

https://groups.google.com/forum/m/#!topic/cython-users/DSmOcM3B2jA

**Comment by denfromufa** [comment]
ok, ptvsd is now compiled with cython and enable_attach works as is. For compilation I had to make few changes in the source code. I can submit a patch if you are interested. It is all here:

https://www.dropbox.com/s/77yc2e4bornorb4/ptvsd_.zip?dl=0

**Comment by int19h** [comment]
Interesting. How much speedup did you get out of it on your projects?

**Comment by denfromufa** [comment]
The speed-up is really only about 15%, but I did not apply any Cython static annotations to ptvsd yet. Anything further is well beyond my skills. If you can think of easy static annotations that I can add inside enable_attach, that would be great!

**Comment by zooba** [comment]
`ptsvd.debugger.trace_func` would be the place to look at. I think `event` can be annotated with `str`, and maybe the dict dispatch could become a series of comparisons. The more of this call tree that can become `cpdef` functions rather than `def`, the more speed improvement we should see.

**Comment by zooba** [comment]
(Also, in case you aren't working from master, we recently restructured the package quite heavily. So if you're using any released build, files will be in different places with different names.)

**Comment by denfromufa** [comment]
Ok, I see significant changes to ptvsd. I'll try your suggestions, but profiling data would be helpful.

@scoder gave this link for re-writing the tracing function in Cython:

https://docs.python.org/3/c-api/init.html#profiling-and-tracing

**Comment by int19h** [comment]
The problem is that there's considerable conflation of various concepts in debugger.py code - there's messaging/networking code intermixed with tracing, stack walking, expression evaluation, frame and value inspection etc, in a manner that makes it hard to decouple. Of all these, only tracing is perf-critical enough to make the effort of avoiding pure Python worthwhile.

I'm working on refactoring this stuff out into more manageable components; once tracing is out, it could be reimplemented in Cython, or better yet, pure native code (this would allow some more flexibility with respect to data structures used for e.g. fast breakpoint lookups), with the pure Python implementation used as a fallback for IronPython, Jython, PyPy etc.

Unfortunately, tracing is also the hardest part to untangle from the rest, so it might take a while.

**Comment by huguesv** [comment]
https://github.com/Microsoft/ptvsd is based on pydevd and we get some nice performance boost with it
