### ISSUE TITLE
'Code snippets' display nothing

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7490]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/229033160-06963362-16da-43b2-aafe-3e3558a10353.png)

**Steps to Reproduce**
1.Create a python project
2.Edit > IntelliSense > Surround With or Insert Snippet
3.Using command Surround With or Insert Snippet

**Expected behavior**
It should show "Python", then I can select a snippet 

**Actual behavior**
'Code snippets' display nothing
![image](https://user-images.githubusercontent.com/59192491/229034875-30bd063f-efcd-4fdd-9f03-106ae23c5c86.png)
![image](https://user-images.githubusercontent.com/59192491/229034911-288b6e7d-c646-4625-aeb5-9d84f9c9a476.png)

**Comment by StellaHuang95** [comment]
Seems like an editor issue, see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1782465
