### ISSUE TITLE
Missing package check doesn't understand flask requirements

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7493]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/230288614-c571e32e-c98d-46b9-9db7-a58778c7e6b4.png)

**Steps to Reproduce**
1.Create new Flask web project
2.Create virtual conda env like below:
![image](https://user-images.githubusercontent.com/59192491/230289081-024beabc-dfc0-45fe-8a1b-90c23e16e7ec.png)
3.Unload Project
4.Reload Project

**Expected behavior**
Without any warning

**Actual behavior**
![image](https://user-images.githubusercontent.com/59192491/230290920-50207aff-6503-4050-91ae-2291e37cb7f4.png)
Info bar prompt that there are missing packages. This is not true, the info bar should not appear.
It doesn't work for this flask requirements:
```
Flask>=2.2.3
```
![reloadproject](https://user-images.githubusercontent.com/59192491/230291674-03abdd4d-d715-4ae2-a1e9-3fabcbd0b5a1.gif)

**Comment by StellaHuang95** [comment]
There were some security vulnerabilities found in the lower versions of Flask so we had to bump it up to the latest version. Conda and pip have different release schedules, and in this case, seems like the latest version of Flask is available in pip before it is available in Conda. We don't want to ship a version that has vulnerabilities, so the workaround here is to either wait until conda releases this version, or manually change the version in requirement.txt to dismiss the warning.
