### ISSUE TITLE
Code not working - no matter how i change the code it does not display the code 24/08/2023 as 24 Aug 2023

### ISSUE THREAD

**Issue by Venetia143** [microsoft/PTVS#7494]
#import datetime

#store the value in a variable called currentDate
currentDate = datetime.date.today()
#print (currentDate)
#print (currentDate.year)
#print (currentDate.month)

#print(currentDate.strftime(%d %b, %Y)
#print(currentDate.strftime(%d %b, %y)

#("Please attend our event %A, %B %d in the year %Y"))

userInput = input('Please enter your birthday ')
birthday = datetime.datetime.strptime(userInput, '%m/%d/%Y')
print(birthday)

**Comment by StellaHuang95** [comment]
Hi @Venetia143, thanks for reporting this. Could you provide more detailed repro steps so that we can investigate it? What do you mean by "it doesn't display the code"? Thanks.

**Comment by gramster** [comment]
This seems like a Python issue, not something to do with Visual Studio. That said, you did try the correct approach, which would be:



```
print(currentDate.strftime("%d %b %Y"))
```

So the question is, what do you see when you use that approach? If you are not getting the right format, there may be something wrong with the locale you are using.
