### ISSUE TITLE
Failed to drop down the list on the .vsp file.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7495]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/231366117-7c2f674d-4548-496a-be60-cc344cf42f17.png)

**Steps to Reproduce**
1. Create python application project and add "Lib\test\pystone.py" and remove the default .py file
2. Debug> Launch Python Profiling …
3. Checked the option "Open project" and select the current project in drop-down list
4. Click "Start"
5. Wait for the command excuttion done/ close it anytime
6. The .vsp file is generated and opened in VS but not saved
7. Do some check with view types:
	a. Summary
	b. Call tree
	c. Function details
        d. Etc...

**Expected behavior**
The View Type list can be toggled.

**Actual result**
Failed to drop down the list on the .vsp file.
![launch_profiling](https://user-images.githubusercontent.com/59192491/231367599-fc4c70ef-aad1-4931-8391-45661ba9730d.gif)

**Comment by StellaHuang95** [comment]
@linette-zyy I can't repro this one, could you verify if you're still able to repro it?

**Comment by linette-zyy** [comment]
@StellaHuang95 
I can't repro this in today latest build
![image](https://user-images.githubusercontent.com/59192491/233942477-bfd77cb9-2462-4085-b705-a75ead6aa60c.png)
