### ISSUE TITLE
Tokens not working in Python files

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7498]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Tokens-not-working-in-Python-files/10324825)._

---
Tokens are not working in Python files. Neither custom or default tokens work. To reproduce:
- Create or open any Python file
- add the line "# TODO token test"
- open Task List and this will not show.
- do the same with a cpp file and add the line "//TODO token test"
- Note the TODO will show in the Task List for the cpp file but not for the py file, even in the same project.

---
#### Feedback Bot on 3/28/2023, 06:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, we have checked in the fix recently, see https://github.com/microsoft/PTVS/issues/7151. Could you update to the latest VS version and try again? Please reopen the issue if it persists. Thanks.
