### ISSUE TITLE
Refactor ptvsd

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#750]
The Python portion of the debugger code is rather messy and hard to maintain. Furthermore, while start with debugging, local attach, and remote attach all share the majority of the code, there are very significant differences in the initial path that loads and initializes debugger modules, and this reflects in an inconsistent API for the users. For example, when using remote attach with `ptvsd`, it's possible to use helper functions such as `is_attach` and `break_into_debugger`, but they're not readily available for local (indeed, the entire `ptvsd` package is not user-accessible, even though all the code behind it is loaded). 

It's time for a big cleanup to tackle all these things. The end result should:
1. Have ptvsd as the end-all be-all package encapsulating all Python code in the debugger. 
2. Make it visible to the users in all debugging scenarios, with the same API and semantics in all cases.
3. Have clean, well-organized, easy to maintain code.
4. Use a text-based protocol (JSON?) for ease of debugging and diagnostics.
5. Use a single transport for all scenarios that works everywhere and can easily traverse firewalls and proxies (e.g. websockets).
6. Try to maintain forwards- and backwards-compatibility to a reasonable degree (e.g. just because a new version of ptvsd adds a new command, should not prevent an old version of VS from attaching to it).

This also ties into #749, as a significant refactoring of the debugger is necessary in any case for that to happen.

**Comment by huguesv** [comment]
Done as part of ptvsd 4.x
