### ISSUE TITLE
IPython Interactive not working when using virtual environment.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7500]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IPython-Interactive-not-working-when-usi/10327763)._

---
[severity:I'm unable to use this version]
Try simple example from tutorial, Interactive window doesn't have out [] event for simple commands.
Please see screenshot. I use just virtual environment.

---
#### Feedback Bot on 3/30/2023, 07:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Screenshot of the original ticket: 
![image](https://user-images.githubusercontent.com/100439259/231897504-36dc7eaa-023f-4099-9750-bc7a9687f5fe.png)

**Comment by StellaHuang95** [comment]
This is a duplicate of https://github.com/microsoft/PTVS/issues/7219
