### ISSUE TITLE
Python UTF-8 does not come out UTF-16? It was strange from startup, but it was fixed and an error occurs with (utf-8) with the Japanese character code.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-UTF-8-does-not-come-out-UTF-16-I/10331377)._

---
![2023-04-05.png](https://aka.ms/dc/image?name=B1f8093d422e843a3bcb0236c563b434e638162699510856604_2023-04-05.png&tid=1f8093d422e843a3bcb0236c563b434e638162699510856604)
Garbled in the run below. Is it a mistake between UTF-8 and UTF-16?

---
#### Feedback Bot on 4/5/2023, 08:29 PM: 

(private comment, text removed)
#### Unknown on 4/7/2023, 00:39 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
![image](https://user-images.githubusercontent.com/100439259/233218337-277f136b-4e63-472c-8f32-12ea4375d4c0.png)

**Comment by StellaHuang95** [comment]
Hi there, thanks for reporting this. It seems that the character you used has a byte representation that is not valid in the encoding that Python is trying to use to read your file. Could you go to File -> Save As -> click the dropdown button next to Save, choose save with encoding -> choose UTF-8 and re-run the script? Please re-open the ticket with a copy of your script if the issue still persists, thanks!
