### ISSUE TITLE
Fail to manage pip packages for a virtual environment.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7519]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/232993551-70bbe4f6-a15c-46f4-b670-455493d3e6c2.png)

Python install from Microsoft Store.

**Steps to Reproduce**
1. Create a Python Application.
2. Create a virtual environment.
3. Update ```pip```.

![image](https://user-images.githubusercontent.com/82852072/233002410-860ec27e-f118-4d3a-950a-1c9be829d6fa.png)

**Expected behavior**

Successfully updated ```pip```.

**Additional context and screenshots**

Updating pip for the first time, the output shows ```successfully installed 'pip'```, but the package windows is not updated.
Update pip for the second time and report an error.

![image](https://user-images.githubusercontent.com/82852072/233004245-98b416fa-e2a2-479a-9434-72cc04d7dbe8.png)

BTW, After updating ```pip```, SE windows can't see the package.

![image](https://user-images.githubusercontent.com/82852072/233004905-da523f15-7ce1-4cb7-af49-1f1345e6315a.png)

**Output**
<details>
<p>

```
Virtual environment is being created at 'C:\Users\vting\source\repos\PythonApplication11\PythonApplication11\env'
Virtual environment was successfully created at 'C:\Users\vting\source\repos\PythonApplication11\PythonApplication11\env'
AssignProcessToJobObject: (87) The parameter is incorrect.


----- Installing 'pip' -----
Collecting pip==23.1
  Using cached pip-23.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.1
----- Successfully installed 'pip' -----

----- Installing 'pip' -----
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
----- Failed to install 'pip' -----
```

</p>
</details>

**Comment by StellaHuang95** [comment]
This is a duplicate issue of https://github.com/microsoft/PTVS/issues/7518, they both have to do with Python downloaded from Microsoft Store and installing packages using the `--user` option.
