### ISSUE TITLE
Class Designer availability for other languages like python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7543]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Class-Designer-availability-for-other-la/1660913)._

---
I would love to see the class designer and all it´s diagram tools ported to other languages like python. 
It doesnt need to have the same functionality, the tool can at least be used for some documentation and modeling of the arkitekture.

---
#### Feedback Bot on 2/11/2022, 00:06 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
Unfortunately, it is not in our plans to add support for this request.
