### ISSUE TITLE
Python editor text-color in VS2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7544]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-editor-text-color-in-VS2022/1669871)._

---
The font color options of Python language in vs2022 are not as rich as those in vs2019. The color of Python text is currently in a very difficult state to read.

---
#### Feedback Bot on 2/21/2022, 00:54 AM: 

(private comment, text removed)
#### ce shen on 3/29/2022, 11:12 AM: 

(private comment, text removed)
#### Cameron James Walker on 3/7/2023, 06:08 PM: 

(private comment, text removed)
#### PerseusW on 3/13/2023, 02:50 AM: 

(private comment, text removed)
#### Robert Randolph on 3/22/2023, 11:19 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
Additional  information:

"I have the same problem. I didn’t see this post when searching the forums. Perhaps you can upvote that thread to help make this issue more visible. https://learn.microsoft.com/en-us/answers/questions/1191966/i-can-t-change-the-text-editor-colors-for-python "

**Comment by cwebster-99** [comment]
Related https://github.com/microsoft/PTVS/issues/7082
