### ISSUE TITLE
Missing Intellisense / auto-completion 

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/PTVS#755]
# Problem

I'm using Python Tools for Visual Studio 2.2 in Visual Studio 2015 RTM on Windows 10 Enterprise RTM. I'm using the `boto3` Python library for Amazon Web Services (AWS). I am noticing that I am sometimes not getting Intellisense for the "client" object I have created.

![image](https://cloud.githubusercontent.com/assets/466713/9267341/999b8ad0-420a-11e5-9400-a7f522ba6dba.png)

Here is the code I'm using to reproduce the problem. At the end, I use `{CTRL} + {SPACE}` to invoke Intellisense, and nothing appears, similar to the screenshot above.

``` python
### Import the necessary modules for this script
import boto3,json

### Set up a session to Amazon Web Services (AWS)
awskeyid = 'AWSACCESSKEYID'
awskey = 'AWSSECRETACCESSKEY'
region = 'us-west-2'
awssession = boto3.session.Session(aws_access_key_id = awskeyid, aws_secret_access_key = awskey, region_name = region)

### List the available "resources" (higher-level abstractions) in Amazon Web Services (AWS)
resourcelist = awssession.get_available_resources()
print(json.dumps(resourcelist))

### List the cloud service "clients" (raw APIs) available on Amazon Web Services (AWS)
servicelist = awssession.get_available_services()
print(','.join(servicelist))

### Create an AWS S3 Bucket
s3client = awssession.client('s3')
s3client.create_bucket(Bucket = 'boto3testing')
s3client.<TAB>
```
# Expected Result

PVTS should be providing Intellisense for this S3 "client" object.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by muratmozdemir** [comment]
I am having a similar problem, but when mine does load, it looks like this:

![image](https://cloud.githubusercontent.com/assets/3821628/9745501/3f8eca1c-5640-11e5-9f2b-acc54761537d.png)

**Comment by zooba** [comment]
See #3046
