### ISSUE TITLE
Need support for Python as an Azure IoT Edge module

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7550]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Need-support-for-Python-as-an-Azure-IoT-/10034002)._

---
Looks like only C# and C++ are supported as Azure IoT Edge module development.
Python needs to be added for IoT Edge module development and debug support

---
#### Feedback Bot on 5/8/2022, 09:41 PM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
Azure IoT Edge tool offerings are in maintenance mode and do not seem to be adding support for Python. Please see  https://github.com/microsoft/vs-azure-iot-edge-docs/issues/42
