### ISSUE TITLE
Add space after the comment.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7551]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-space-after-the-comment/10041312)._

---
I very much doubt that I am the first person to say this. If you could add a space after the comment character in whatever the language is ('//' in C#, '#' in Python), it would make the comments much more readable. Currently I'm having to add the space manually which is quite annoying. Thank you very much in advance :)

---
#### Feedback Bot on 5/16/2022, 02:06 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
This has been fixed in https://github.com/microsoft/PTVS/pull/7533.

**Comment by LozmindaSnr** [comment]
Still unfixed 17.10 June 2024. Just wondering how long the dev cycle is ?

**Comment by shaltai** [comment]
That's weird rly :-C
