### ISSUE TITLE
Option to auto-activate python virtual environment in Visual Studio terminal.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7553]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Option-to-auto-activate-python-virtual-e/10069336)._

---
We need a way to make the Visual Studio's Developer PowerShell auto-activate the virtual environment, as is possible in PyCharm or in VS-Code. 

Right now, one has to explicitly run the command `.\env\Scripts\activate` in the Terminal to activate the Virtual Environment.

---
#### Feedback Bot on 6/14/2022, 09:38 PM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
Hi there! Thank you for suggesting such a feature for PTVS - we appreciate you taking the time to provide recommendations to improve PTVS. Given our current limited resources, it's unlikely we will be able to fix this issue in the near future, so we're closing it to focus on higher priority issues. However, if this is a critical issue for you, let us know, and we can reevaluate. Thanks!
