### ISSUE TITLE
structure guidelines python not showing in VS 2019

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7555]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/structure-guidelines-python-not-showing-/10084405)._

---
I am using VS 2019 community edition.
I know it was reported as "structure guidelines python not showing" for VS 2017. However, I think that structure guidelines for python editor would be perfect since python structured by indentation. Therefore, please reconsider to add this feature for python.

---
#### Feedback Bot on 6/30/2022, 01:37 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
This is supported in the most recent version of Visual Studio, VS 2022.
