### ISSUE TITLE
When you open vs, create a new file, and switch the python environment, two warning windows pop up for each python file you open

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7559]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/当打开vs、创建新文件、切换python环境时，每打开一个python文件就弹出/1591515)._

---
! [temp.png] (https://aka.ms/dc/image?name=B0e65d84bb7ae401c9749cdd0c48281b4637731569520155904_temp.png&tid=0e65d84bb7ae401c9749cdd0c48281b4637731569520155904)

---
#### Feedback Bot on 11/22/2021, 01:34 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
Pylance does not support Python 2. Please update your Python version in order to get Pylance support.
