### ISSUE TITLE
Please add Function of Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7560]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-add-Function-of-Python/1544673)._

---
I want you to add the function of formatting code (automatic correction such as indent position error) to Python of Visual Studio 2019 Community Edition.

---
#### Feedback Bot on 10/5/2021, 08:34 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
We are no longer adding features to VS 2019. We recommend using Black formatter. You can do so with Ctrl+K, Ctrl+D (Format Document) in VS 2022 which is wired up to use Black and automatically install it if needed.
