### ISSUE TITLE
Feature Request:  Add python 3.12 and up to Visual Studio Preview 2022 ...

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7565]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Request:--Add-python-312-and-up/10290957)._

---
Feature Request:  Add python 3.12 and up to Visual Studio Preview 2022 ...

![pyththon_Visual-studio.png](https://aka.ms/dc/image?name=B9f7bf9021fbc42df9a1da1d0b350cefa638128361933262849_pyththon_Visual-studio.png&tid=9f7bf9021fbc42df9a1da1d0b350cefa638128361933262849)

i know 3.12 is still beta, but will be stable soon.. also add python templates to start a new project, or learn Python ....

---
#### Feedback Bot on 2/27/2023, 00:36 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment]
https://peps.python.org/pep-0693/

**Comment by cwebster-99** [comment]
Thanks for filing this feature request, we appreciate hearing from users on how PTVS can be improved! We have a number of issues in our repo that are tracking similar work related to Python 3.12 support. I am closing this issue as a duplicate in favor of those referenced above.

**Comment by paul-michalik** [comment]
In the meantime, is it possible to disable the warning box somehow?

**Comment by mcDandy** [comment]
Still an issue more than a year later on 17.10.3. I thought it requires python 3.13 which is not even out yet untill finding this.

**Comment by SoumyadipYT-OSS** [comment]
Is there any other way (without cookiecutter), to detect python interpreter automatically for Visual Studio Community 2022 with python 3.12.4

**Comment by weav74** [comment]
Even if its not planned to support 3,12 can we please disable the warning we have to dismiss every time we open up Visual Studio 2022?    I've accepted that VS2022 doesn't support it , it would just be good not to have dismiss it every time
