### ISSUE TITLE
We didn't find any interpreters

### ISSUE THREAD

**Issue by Pearl-CSI** [Microsoft/PTVS#757]
I am VERY new to this technology, and doing an Intro to Python course with Microsoft .... I followed their download instructions for "Visual Studio Express 2013",  "Python Tools" and "Python 3.4 Interpreter"

I created a new project, and let it default to the "hello world" print statement .... but when I try to run it, I get an error that says "We didn't find any interpreters"

When I open the extra window in Visual Studio, and look at Environments, I see "Python 3.4"

I have absolutely no idea what I'm missing, or where I've gone wrong.   Any assistance would be greatly appreciated.

**Comment by zooba** [comment]
Did you create an IronPython project? We have a bug right now where we don't display a more helpful message when you don't have 

Have a look at our docs on [Project Environments](https://github.com/Microsoft/PTVS/wiki/Python-Environments#project-environments) - if you don't see Python 3.4 listed in your project then you may need to make a change there.

**Comment by Pearl-CSI** [comment]
OMG .... that's it !!!     Thank you SO much !!!
