### ISSUE TITLE
LiveShare: Intellisense doesn't work in client.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7574]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/236392557-ae6f0389-f1cb-4849-92c8-c8bdb2769525.png)

**Steps to Reproduce**
1.Create a Python Application.
2.Open Live Share, make connection between host and client.
3.Type ```import``` in the client.

**Expected behavior**
As you type, your completion list should open and prompt for your input accordingly.

**Actual behavior**
Nothing came up.

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/59192491/236393196-4c3962de-20dd-430b-a019-e2c200da4a71.png)

On server, it works well.
![image](https://user-images.githubusercontent.com/59192491/236393312-8ae4a2ed-ed9c-4fff-82c2-192cb15032f7.png)

**Comment by StellaHuang95** [comment]
There's an internal ticket tracking it, see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1798878. Closing it as it's not ours to fix.
