### ISSUE TITLE
Git failed with a fatal error.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7578]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/237050693-c77505b1-fc73-46b0-baac-9e53f68cf974.png)

**Steps to Reproduce**

1. Create a Blank Django Web Project.
2. Click the button ```Add to Source Control```.
![image](https://user-images.githubusercontent.com/82852072/132639971-cb42ac5e-3847-408b-b4af-dd24fd385434.png)
3. Sign in your account and click "Create and Push".
4. Check the **output** from **Source Control - Git**.

**Expected behavior**

Commit without errors.

![image](https://user-images.githubusercontent.com/82852072/237054153-2721869c-5e56-4035-af4c-d146ee7eea58.png)

**Additional context and screenshots**

The output says "Git failed with a fatal error".

![image](https://user-images.githubusercontent.com/82852072/237056681-7c309d3b-9e44-487e-9cd4-bf1edfddd576.png)

## Logs

<details>

<summary>Output for <code>Source Control - Git</code> in the <code>Output</code> panel 
</summary>

<p>

```
A new Git repository has been created for you in C:\Users\vting\source\repos\DjangoWebProject5. Open the Git Repository window to view its contents.
Opening repositories:
C:\Users\vting\source\repos\DjangoWebProject5
Opening repositories:
C:\Users\vting\source\repos\DjangoWebProject5
Commit e9b0d0cf created locally in repository C:\Users\vting\source\repos\DjangoWebProject5
Opening repositories:
C:\Users\vting\source\repos\DjangoWebProject5
Opening repositories:
C:\Users\vting\source\repos\DjangoWebProject5
Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/ttSpace/DjangoWebProject5.git/': error setting certificate verify locations:  CAfile: c:/program files/microsoft visual studio/2022/preview/common7/ide/commonextensions/microsoft/teamfoundation/team explorer/Git/mingw64/ssl/certs/ca-bundle.crt CApath: none
```

</p>

**Comment by StellaHuang95** [comment]
Looks like there's an internal ticket tracking the same issue. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1815532. Going to close this one as it's waiting for upstream to fix.
