### ISSUE TITLE
Intellisense and Code Collapse Blocks stop working

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7585]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-and-Code-Collapse-Blocks-st/10347132)._

---
Python file 2000+ lines. I can open the file just fine, but as soon as I start editing, the group indicators next to the line numbers disappear, I mean the items that allow you to collapse sections of code. Intellisense and code-complete also stops working.

---
#### Feedback Bot on 4/24/2023, 08:04 PM: 

(private comment, text removed)
#### Sam Hammond on 5/4/2023, 07:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Can you share the code sample or screenshots so that we can further investigate? Thanks.
