### ISSUE TITLE
Latest VS2022: 'Help’ > ‘Send Feedback’ > ‘My Feedback’ menu is not working

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7587]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Latest-VS2022:-Help’--‘Send-Feedback’-/10350659)._

---
[severity:It bothers me. A fix would be nice]
I have the latest VS2022 (17.5.4) and recently the ‘Help’ > ‘Send Feedback’ > ‘My Feedback’ menu has stopped working! I click on it, just like before, but there is absolutely no reaction - neither “Report a problem” nor “Suggest a feature” do anything. Same if invoked via the shortcut through the small icon in the upper right-hand corner. I had Python Tools installed before but I had recently uninstalled them (I only use C# and C++). I believe the problem started somewhere around that time. I know this issue was reported previously (https://developercommunity.visualstudio.com/t/Send-Feedback-button-does-not-work-in-VS/1452077) and was marked as "fixed", with the fix being available since 2021, but it is obviously still very much there. I'm reporting this problem from within a clean VS2022 installation that I setup in a VM, just to report this problem.

---
#### Feedback Bot on 4/27/2023, 07:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Transferred to DevDiv\Technical Insights\Customer Feedback Services
