### ISSUE TITLE
Visual Studio Config and Use

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Config-and-Use/10352838)._

---
[severity:It's more difficult to complete my work]
I struggle with VS.  I use it for Power BI models and am daunted by the amount of configuration and operation that is required.  In short, wouldn't Visual Studio be best used for coding (.Net, Python, etc.) and have tabular models be attached to SSMS?  That would allow for a much simpler interface, no?
Thanks!
Peter Alexander

---
#### Feedback Bot on 5/3/2023, 11:03 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Not sure why it got transferred to us, transferred to VSCore.
