### ISSUE TITLE
Visual Studio is very hard to use for Python development

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7594]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-is-very-hard-to-use-for-Py/10355423)._

---
[severity:It's more difficult to complete my work]
Latest Visual Studio 17.5.5 is very hard to use for Python development, with multiple issues that get in the way and force one to use 3rd-party tools instead of relying on IntelliSense and continuously trigger merge conflicts because of poor comment continuation practices.

I had very bad experience submitting issues for VS/Python and will not create separate issue because I have a feeling that all of them will be considered as Not A Bug and closed, as happens with most VS issues nowadays. Nevertheless, here are the biggest ones, in case if somebody fishes out even one thing to fix from these. Or not.

1. Whenever a Delete or Backspace key is pressed anywhere in Python code, a pop-up with useless suggestions comes up, full of things like `and`, `assert`, etc. The only way out is Esc, which needs to be done every time a line is deleted or similar action is taken. Sometimes, when typing/deleting, a quick Enter inserts one of those nonsensical "suggestions" into the code and more needs to be deleted.

2. When typing a comment and Enter is pressed when there's text following the caret position, the next line is automatically commented, but these lines are inserted using CRLF, creating a mess when various IDEs that find this mix and convert it implicitly to LF or CRLF, so the entire file is changed, creating numerous merge conflicts.

Here's an example. Select LF as the line ending in the bottom right corner in the editor and place the caret as shown below and press Enter.
```python
    #    v-- place typing caret here, press Enter
    # ABC <-- may be a space without this comment - same behavior
    #
```
Observe how line endings in the bottom right corner are changed to MIXED. If there is no text following the caret, it ignores multiple levels of indentation and jumps to the first position, so in a class with methods, a ton of indentation needs to be introduced.

3. IntelliSense struggles in complex projects that may have some types unknown. Doesn't matter which packages, but it always happens for things like PyMongo, BoTo, jsonpath-ng, etc. When the folder with Python source is opened, IntelliSense reports parsing some source files, then lights up with errors that are caused by "Unknown" types. After about 30 minutes or more - I don't have the exact timing, most of the red squiggles disappear and it no longer reports any issues, so the only way to find type errors is to run `mypy` from command line, which is needless to say is counterproductive.

4. Sometimes when a conditional breakpoints is set with values the debugger cannot resolve the conditional expression, a modal pop-up is presented with details, but then if the breakpoint is being continuously hit, this modal pop-up keeps being presented and it's impossible to stop debugging or even exit Visual Studio and it has to be killed via Task Manager. 

More issues like these are happening. You are practically driving people away from using Visual Studio. Some people I work with already switched to PyCharm and VS Code. I do mixed C++, TypeScript and Python development and have to use Visual Studio, but you are not making it easy to do so.

---
#### Feedback Bot on 5/4/2023, 07:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by cwebster-99** [comment]
Thanks for your feedback and bug reports. I have created 4 separate issues to track each point of feedback. Our team will investigate these and follow up on the corresponding issues. I will close this issue in favor of the tracking issues
