### ISSUE TITLE
Highlight references when cursor is on an identifier

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#76]
This is a feature C# has in 2010 - if your cursor is on a local or other variable the other usages of it will be highlighted.

(Migrated from https://pytools.codeplex.com/workitem/129)

**Comment by ITSecMedia** [comment]
Yes please, it would help a lot!

http://blogs.msdn.com/b/vcblog/archive/2011/08/24/10200097.aspx   (Reference Highlighting)

http://docs.wholetomato.com/default.asp?W186  (Highlight References to Symbol Under Cursor)

**Comment by 2Dews** [comment]
The Highlight All Occurrences extension used to supply the highlighting for both c# and python. Now that the highlighting is built in for c# and the extension does not support VS 2015 I am missing this feature in Python. Would love to see this built in.

**Comment by smwikipedia** [comment]
@2Dews hi, the "highlight all occurrences" extension claims to support VS 2015 now. Check here: https://visualstudiogallery.msdn.microsoft.com/2a3c622e-f99b-4da1-b430-e1bf37fe93e7

**Comment by huguesv** [comment]
Also reported on developer community at https://developercommunity.visualstudio.com/content/problem/255977/python-点相同变量不提示高亮.html
