### ISSUE TITLE
Issue with Python Experience

### ISSUE THREAD

**Issue by azariah15yocoder** [microsoft/PTVS#7617]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.11.21196.2

System.NotSupportedException: version 2884 is no longer in memory
   at Microsoft.PythonTools.Intellisense.LocationTracker.GetLineLocations(Int32 version)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceLocation loc, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceSpan span, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.TaskProviderItem.CreateSquiggleSpan(SimpleTagger`1 tagger)
   at Microsoft.PythonTools.Intellisense.TaskProvider.<RefreshAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.TaskProvider.Refresh()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by AdamYoblick** [comment]
@azariah15yocoder Thank you for reporting this. Just to confirm, this is in VS 2019 correct?

Are you able to provide any sample code that causes this issue? I need to try and repro it, but anything you have would help. Thank you :)

**Comment by azariah15yocoder** [comment]
Yes, this was in VS 2019. The thing about this particular issue is that it only happens when I'm actively writing Python code.

Here is the code that I was working on when this happened:

`import os
import time

def cls():
    if os.name == "nt":
        os.system("cls")
    else:
        os.system("clear")

def convert_to_binary(number): # work on this more later
    rem_stack = []
    rem = 0
    binary_string = ""
    while number > 0:
        rem = number % 2
        rem_stack.append(rem)
        number = number // 2
    if len(rem_stack) < 8:
        counter = 0
        position = -1
        new_stack = []
        while len(new_stack) != len(rem_stack):
            counter = counter + 1
            position = position + 1
            new_stack.append(rem_stack[position])
            if counter == 8:
                new_stack.append(" ")
                counter = 0
        if counter < 8:
            while True:
                counter = counter + 1
                new_stack.append("0")
                if counter == 8: break
        rem_stack = new_stack
    while len(rem_stack) != 0:
        binary_string = binary_string + str(rem_stack.pop())
    if len(binary_string) < 8:
        while True:
            binary_string = "0" + binary_string
            if len(binary_string) == 8: break
    return binary_string

def find_subnet(ip, mask):
    for i in range(len(ip)):
        number = int(ip[i])
        convert_to_binary(number)

cls()

while True:
    ip_address = input("Enter IP address here: ")
    if len(ip_address) < 1: 
        print("Have a nice day!")
        time.sleep(5)
    address_mask = input("Enter IP address mask here:")
    if len(address_mask) < 1: address_mask = "255.255.0.0"
    try:
        ip_address = ip_address.split(".")
        address_mask = address_mask.split(".")
        print(find_subnet(ip_address, address_mask))
    except:
        print("Hmm. It looks as if you made a mistake while writing the IP addresses. Please try again.")
        time.sleep(5)
ip_address = input("Enter IP address here: ")`

The main thing that occurs before the popup occurs is that the VS starts to slow down. This is something that happens with any of the programs that I'm writing in any language. After that, there are alerts that appear on my screen (usually one or two) that are mentioning one of these Python bugs. That usually occurs when I am actively writing Python code, though.

Thank you for helping out with fixing this issue. Let me know if you need any more information.

**Comment by AdamYoblick** [comment]
> The main thing that occurs before the popup occurs is that the VS starts to slow down. This is something that happens with any of the programs that I'm writing in any language. After that, there are alerts that appear on my screen (usually one or two) that are mentioning one of these Python bugs. That usually occurs when I am actively writing Python code, though.

Thank you for the information. Are you saying that this particular issue happens when working in any language, or it only happens when working in Python?

**Comment by azariah15yocoder** [comment]
I want to say that it only happens when working with Python.

**Comment by AdamYoblick** [comment]
> I want to say that it only happens when working with Python.

Ok thank you. Have you tried VS2022 to see if the issue persists? Many things have changed between these versions, and many bugs were fixed in 2022 that were not necessarily fixed in 2019.

**Comment by azariah15yocoder** [comment]
I have not tried it yet. I'll be happy to check to see if the issue continues there. Thank you so much for the input!

**Comment by AdamYoblick** [comment]
Please give VS2022 a shot and respond back on this issue if it repros again and we can look into it.

**Comment by azariah15yocoder** [comment]
Turns out, VS2022 was the fix to the issue. Thank you so much!
