### ISSUE TITLE
An unexpected error occured when first creating the conda env.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7618]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/6041971e-d624-497c-afa1-4a3f320c4a04)

**Steps to Reproduce**
1. Create a Python Application.
2. Create a conda environment. (Install Anaconda (downloads at https://www.anaconda.com/download/) if no Anaconda )

**Expected behavior**

The conda environment was created successfully and no error was reported.

**Additional context and screenshots**

An unexpected error occured. (Note: Only repro when first created.)

![image](https://github.com/microsoft/PTVS/assets/82852072/179f0f02-4581-4fd0-a894-26bc1b086489)

**Comment by StellaHuang95** [comment]
I wasn't able to repro it, and we haven't touched this code path recently, need to investigate to see what's going on here.

**Comment by StellaHuang95** [comment]
@ttSpace Does this still repro for you? I still wasn't able to repro it.

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build.

![image](https://github.com/microsoft/PTVS/assets/82852072/093c251e-c95a-4d13-84ac-93d8c38ee28a)
