### ISSUE TITLE
insert space before comment

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/PTVS#7624]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/insert-space-before-comment/10340193)._

---
When you use the toggle comment hot-key-combination there should be an option to also insert a space between the comment operator and the commented line. It should also remove the space if there is a space inserted between the comment operator and the comment when you toggle off the comment.

The reason I wish it was like this is because Python Black inserts spaces and it is a minor annoyance to manually remove them when I toggle off comments.

It works like this in VSCode and I think it should be that way here to.

---
#### Feedback Bot on 4/19/2023, 01:14 AM: 

(private comment, text removed)

**Comment by LozmindaSnr** [comment]
I'm just wondering because on  Visual Studio 2022 17.10, this is still an issue, so that's 1 year, how long is that dev cycle ?
