### ISSUE TITLE
Python code analysis checks too many files

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/PTVS#7630]
Local changes like adding a new line or altering "if i > 0:" to "if i < 0:" in a file should not cause a cascading reevaluation of several files in a project. It takes up to 10 seconds of checking other files to verify that adding a new line did not break the code. The time needed seems dependent on the imports - edits in some files are checked immediately, edits in others not.

![image](https://github.com/microsoft/PTVS/assets/52322342/942c8dc2-b0b3-4094-b641-4766c7858c7e)

**Comment by StellaHuang95** [comment]
@excubo-jg Could you set your Log Level to `Trace` and share the pylance logs?

**Comment by excubo-jg** [comment]
Both logs are written after setting the log level to triage. Once the initial analysis has run its course a blank line (hitting return) is added in step.py. I have put a note in the logs when this happens. The logs then show the activity until the system settles down again.

Initially behavior is that step.py is checked (not sure why constants.py is accessed). After working with VS for a couple of minutes it gets a bit anxious and starts checking other files which causes noticeable delay. The second log is captured after that change has happened.

[inital.txt](https://github.com/microsoft/PTVS/files/11642149/inital.txt)
[broken.txt](https://github.com/microsoft/PTVS/files/11642148/broken.txt)

**Comment by StellaHuang95** [comment]
@excubo-jg Thanks! If you set your `Diagnostic mode` to `Open files` only, do you still observe the same behavior? If the problem persists, to help us narrow down the problem, it would be helpful if you could provide us with a code sample that we can use to reproduce the issue.

Also, based on the logs, it appears that the issue might be related to Pylance rather than PTVS. Are you also encountering the same behavior in Visual Studio Code (VSCode) when Pylance is set as your Python language server? Thanks!

**Comment by excubo-jg** [comment]
My `Diagnostic mode` had been set to `Open files only`.

I have attached another log file which covers the time beginning with opening the project. The last change I did was adding an empty line to check if the delays were reproducible and I then stopped the logging.
[full_log.txt](https://github.com/microsoft/PTVS/files/11669469/full_log.txt)

I am not using VSC with this project so I cannot comment.

**Comment by StellaHuang95** [comment]
Looks like pylance is taking a long time to analyze the play_turn.py file. Not sure why. If you could share that code or provide a file that repros the problem, that would make it possible for us to possibly figure out what is taking so long.

**Comment by StellaHuang95** [comment]
Thanks, without the code sample, I'll do my best to understand the issue you're facing. If I understand correctly, you're saying with the diagnostic mode set to `Open files only`, modifications made to an open file are causing Pylance to analyze and check other closed files as well. Is that correct?

**Comment by excubo-jg** [comment]
Apologies, no, this is not what I was pointing at. [ I just tested it and with `open files only`, the diagnostics is only done on open files. With the setting workspace, also closed files are checked. ] What I am observing is that adding a new line in a file causes checks to be done on several other files. You can see in the log files I provided earlier, that numerous files are accessed although there is no reason to do so. And, if these checks take several seconds to run the user experience deteriorates.

To provide you with a code sample, I just downloaded this repo `https://github.com/Extrality/AirfRANS` and installed it locally. With the diagnostic mode set to `workspace`, inserting a blank line in metrics.py in line 11 causes several files to be checked and these warning messages:
Info: (11244) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1686161700673 at c:\Users\Admin\Documents\Visual Studio 2022\Projects\AirfRANS-main\metrics.py (2542ms)
Info: (11244) [BG(1)] Long operation: checking: c:\Users\Admin\Documents\Visual Studio 2022\Projects\AirfRANS-main\main.py (2011ms)

I hope this clarifies things

**Comment by StellaHuang95** [comment]
Thanks, if you set diagnosticMode to "workspace" and modify one file, pylance will reanalyze the modified file and any files that depend on it, especially if it's a source file that many other files depend upon, then all dependent files require reanalysis.  If you encounter any further issues related to the language server, I would recommend creating a ticket at the Pylance repository (https://github.com/microsoft/pylance-release). The Pylance repository is dedicated to addressing issues specific to the Pylance language server.
