### ISSUE TITLE
Unexpected frame displays after closing search box

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7632]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/4a632cf5-289d-47d6-9ef5-c19b108ed553)

**Steps to Reproduce**
1.Create a python project
2.Menu to navigate to, that Edit > Go To > Go To All 
3.Close the search box

**Actual behavior**
The frame still exists
![image](https://github.com/microsoft/PTVS/assets/59192491/003115c3-882e-4a64-882f-e37369d10706)

![go_to_all_frame](https://github.com/microsoft/PTVS/assets/59192491/58021f62-a079-4f08-8ef3-e7bd44812aa5)

**Comment by debonte** [comment]
@linette-zyy, we believe this is either a VS bug or a WPF bug. Can you close this and open an issue in AzDO instead?

**Comment by linette-zyy** [comment]
I create a new bug at here:https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1834497
so close this issue
