### ISSUE TITLE
Cannot add new item to an open folder.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7633]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/b3156bce-f775-456b-8e32-d88803042181)

**Steps to Reproduce**
1.Open a folder.
2.Right click the folder and select Add New Item... -> python -> empty module
3.Click open button.

**Expected behavior**
File added successfully.

**Actual behavior**
The file is shown, but not successfully added. 
![add_item](https://github.com/microsoft/PTVS/assets/59192491/efa2fed3-2967-43c7-a7b9-388f48bf2c36)

**Comment by StellaHuang95** [comment]
@linette-zyy This doesn't repro for me on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.7.0 Preview 3.0 [33813.580.main], could you check again? Thanks.

**Comment by linette-zyy** [comment]
I can not repro this on today's latest build
![image](https://github.com/microsoft/PTVS/assets/59192491/6da929db-aabf-4ea6-a561-ba8c1e4182e5)
