### ISSUE TITLE
Django IntelliSense in html files doesn't work well. 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7634]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/cd8336b2-c92d-444b-a5d5-9630550e8e72)

**Steps to Reproduce**

1. Create a Django Web Project.
2. Navigate to app/about.html.
3. In a "Django Web Project", validate html completions in app/about.html.

**Expected behavior**

Html completions appear when typing '<' and contain the standard expected set of html elements valid for that position.

![image](https://user-images.githubusercontent.com/82852072/218672125-c12a02f1-fb05-4f2a-85a0-65287a5adee4.png)

**Additional context and screenshots**

When "<" is input, "<<" is displayed.

![image](https://github.com/microsoft/PTVS/assets/82852072/a1c24036-8a7e-4989-9141-cf0e6f2206bd)

**Comment by StellaHuang95** [comment]
@ttSpace This doesn't repro for me on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.7.0 Preview 3.0 [33813.580.main], could you check again? Thanks.

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build ```17.7.0 Preview 3.0 [33814.347.main]```,  Python Package: ```17.0.23150.1```.

![image](https://github.com/microsoft/PTVS/assets/82852072/4401f03e-94f0-4473-bee1-5eb42f1a074b)
