### ISSUE TITLE
The Python static type checker thinks `inspect.currentframe()` returns None

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7635]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-Python-static-type-checker-thinks-i/10387728)._

---
[severity:It's more difficult to complete my work]
After turning on "Basic" mode for type checking (Tools > Options> Python > Analysis), enter this code in:
```
frame = inspect.currentframe().f_back
filename = frame.f_code.co_filename
lineno = frame.f_lineno
```
it incorrectly gives an error that all three properties are trying to access a member from `None`.

---
#### Feedback Bot on 6/8/2023, 05:43 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. Can you please provide a minimal, self-contained code sample that exhibits your problem? The code sample you've provided above is incomplete and references symbols (like `inspect`) that are not defined.

**Comment by gramster** [comment]
We get the type from typeshed, specifically here:

https://github.com/python/typeshed/blob/c38fc45d9c9340eb11e6dd279f460f8a1b3d5d7b/stdlib/inspect.pyi#L553

where you can see the return type is a union type `FrameType|None`. If you know for certain that the type won't be none, you can cast it with `typing.cast`.

**Comment by Captain-Quack** [comment]
Oh, I didn't know about that function, thanks.
