### ISSUE TITLE
BUG: string split with space, python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7636]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/BUG:-string-split-with-space-python/10388379)._

---
Splitting string with split(" ") or split(' ') appends extra element """ to the return list. The element passes if "\"" != elm:. Before splitting, checking the space in last, the string and then removing solves.

---
#### Feedback Bot on 6/11/2023, 06:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. This sounds like a python issue to me, could you provide a code sample with repro steps so that we can further investigate? Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
