### ISSUE TITLE
Auto indentation in python files broken after VS update

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7649]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Auto-indentation-in-python-files-broken-/10392045)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.7.0 Preview 2]
Two new issues (regressions) with auto-indentation while editing Python files:

1. Upon entering a new line, indentation characters (tabs or spaces) are inserted immediately to the expected indent. Previously the indentation characters were only inserted upon typing the new line contents.
2. Upon entering a new line from end of a comment line, the caret stays on the first character position. Previously, the caret would be positioned at an auto-indent position.

---
#### Feedback Bot on 6/15/2023, 00:52 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
This is due to a change made in the pylance language server that implements `formatOnType` setting. The setting currently supports auto-indent, which seems to take precedence of VS's auto indent feature.  We could consider adding a setting on PTVS side to give users the option to turn it off.

**Comment by StellaHuang95** [comment]
The first issue is by design, and the second issue is tracked in the pylance repo.
