### ISSUE TITLE
[CPUWatson] Python: FileWatcher component trying to continually communicate with a JsonRpc component that has been torn down underneath it (0.3% of high-CPU sessions, 90 MB/s at worst)

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/PTVS#7651]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1824482.

**Comment by StellaHuang95** [comment]
Might be related to https://github.com/microsoft/PTVS/pull/6938 and https://github.com/microsoft/PTVS/issues/6904

**Comment by bschnurr** [comment]
I think PR should fix this. https://github.com/microsoft/PTVS/pull/7662
