### ISSUE TITLE
Code color  changes to white when debugging

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7659]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/31a3ec24-d475-4ed3-8455-b037bb97cc2a)

**Steps to Reproduce**
1.Launch VS and create a python project
2.Type sample code and set a breakpoint
3.Start Debugging and Stop Debugging
4.Check the line where is set breakpoint

**Expected behavior**
Code's color is normal

**Actual behavior**
Code's color is changed to white, after I delete breakpoint, I can't see the code because of the background is white 
![code_change_color](https://github.com/microsoft/PTVS/assets/59192491/230aa092-8c51-4e8f-9691-b15ccffb3711)

**Sample Code**
```
from math import cos, radians 

 

# Create a string with spaces proportional to a cosine of x in degrees 

def make_dot_string(x): 

    rad = radians(x)                             # cos works with radians 

    numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces 

    st = ' ' * numspaces + 'o'                   # place 'o' after the spaces 

    return st 

 

def main(): 

    for i in range(0, 1800, 12): 

        s = make_dot_string(i) 

        print(s) 

 

main() 
```

**Comment by StellaHuang95** [comment]
Looks like it's not python specific issue, see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1841400. I will keep track of it.

**Comment by StellaHuang95** [comment]
Looks like there's a fix for it from the upstream already. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1841132. Should be fixed in the next version.
