### ISSUE TITLE
An error pops up when create a project

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7660]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/2def5761-2d21-4e0f-be55-037e4aa0e150)

**Steps to Reproduce**
1.Launch VS and create a python project

**Expected behavior**
No error pops up

**Actual behavior**
An error pops up and IntelliSense & error list don't work
![image](https://github.com/microsoft/PTVS/assets/59192491/a332f8bc-0f92-4457-9970-2a2220153b0b)
![IntelliSense_fail](https://github.com/microsoft/PTVS/assets/59192491/bb482b24-bed6-4d4e-a9ec-795f4b79b80c)
![image](https://github.com/microsoft/PTVS/assets/59192491/9affee9d-f63b-4173-b518-d2daad922da6)

**Comment by StellaHuang95** [comment]
Could you follow [this instruction](https://github.com/microsoft/PTVS/wiki/Build-and-Debug-Instructions-for-PTVS#:~:text=and%20try%20again.-,Install%20nodejs/npm,-from%20https%3A//nodejs) to install nodejs and try again?

**Comment by linette-zyy** [comment]
I can still repro this in today's latest build, though I have installed nodejs from https://nodejs.org/en/download/
![image](https://github.com/microsoft/PTVS/assets/59192491/9938e8d7-c163-451e-8d99-182cb3e2406c)

**Comment by StellaHuang95** [comment]
Can you open your command prompt, type the `node --version` command and see if it outputs anything?

**Comment by linette-zyy** [comment]
![image](https://github.com/microsoft/PTVS/assets/59192491/17072d11-58ff-461a-b6f5-86d86a0bcaf0)

**Comment by StellaHuang95** [comment]
You shouldn't have to install node to run pylance in VS unless you're building PTVS. VS comes with node. Could you check if there's node.exe in your VS folder? Mine locates at `C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\NodeJs`. If you find it, could you try adding it to the PATH environment variable and see if the issue persists?

**Comment by linette-zyy** [comment]
I find it and add it to the PATH environment variable , I can still repro this 
![image](https://github.com/microsoft/PTVS/assets/59192491/246e7284-61df-46e8-8e28-24880545ca52)
![nodejs_is_not_found](https://github.com/microsoft/PTVS/assets/59192491/41eef4c2-2e1d-45ef-97b8-9533b607d5d4)

**Comment by StellaHuang95** [comment]
Does it only repro on one machine? How were you able to run other tests for PTVS?

**Comment by linette-zyy** [comment]
@StellaHuang95 
This issue repro on all machines. The issue affected pylance-related tests and other tests we can run.

**Comment by StellaHuang95** [comment]
I will submit the fix to both VS main and 17.7 release branch, will have to go through the QB approval process for it to get into preview 4.

**Comment by StellaHuang95** [comment]
The PR has been merged into VS main, should be fixed in the next int preview version. Could you verify? Thanks! @linette-zyy

**Comment by AdamYoblick** [comment]
Link to the VS PR please?
________________________________

**Comment by StellaHuang95** [comment]
PR to VS main: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/482974
PR to rel/d17.7: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/482957

**Comment by linette-zyy** [comment]
![image](https://github.com/microsoft/PTVS/assets/59192491/747d92e2-da0e-425a-a15d-8376bcb6b8d2)
I can't repro this in PR to VS main

![image](https://github.com/microsoft/PTVS/assets/59192491/dfa6b5f9-e928-46de-942b-65b19c4b2a42)
I can't repro this in PR to rel/d17.7
