### ISSUE TITLE
Running .Py file from visual studio 2022 without changing "set as startup file" every time

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7663]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Running-Py-file-from-visual-studio-2022/10398700)._

---
![image.png](https://aka.ms/dc/image?name=B7033cacfdfc84f95bd5300a182042f0a638230895250158339_20230623-092839-image.png&tid=7033cacfdfc84f95bd5300a182042f0a638230895250158339)

I have 3 .Py files in my project.I need to run whatever i need. Now i am facing challenge is every time i need to opt the  .py file as "Set as startup file" before running.I would like to know how to avoid this selection option before running.Let me know if you need any info. below mentioned screenshot for same.

---
#### Feedback Bot on 6/24/2023, 06:32 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. There are alternative ways to run a specific Python file in Visual Studio without setting it as the startup file. One of the options would be opening the file in the Python editor window, right-click within the editor and select "Start with/without Debugging" to run the file. Please reopen the ticket and let us know if that doesn't answer your question. Thanks!
