### ISSUE TITLE
VS 2019 fails to use the previously selected environment in existing projects

### ISSUE THREAD

**Issue by agribot2** [microsoft/PTVS#7667]
This defect is similar to " Use last used environment when opening an existing solution in Visual Studio 2019 #6343 "
which was unresolved, but this defect now has additional problems

I am using visual studio 2019 community and using python. I have several existing solutions and several different existing environments. The VS error is ;- When I open an existing solution VS fails to use the specific environment that was previous assigned and activated in that solution... VS incorrectly always uses one other environment. This error happens no matter how often I set the correct environment with "use this environment for the default for new projects", and regardless if I replace the wrong environment with the specific existing environment required by the project. VS 2019 is at version 16.11.27 .

In order to assign and activate an required existing environment , users have to go through the steps needed to assign an environment to a project and activate the environment  ... every time VS 2019 is started and an existing solution is re-opened. 

This defect is similar to " Use last used environment when opening an existing solution in Visual Studio 2019 #6343 "
which was unresolved, but this one has additional problems;-  Note that setting the global default environment does not work ( with existing solutions )

How to reproduce this defect;-
open and existing solution / project. VS incorrectly always activates one specific incorrect existing environment
  
Efforts to resolve the VS 2019 error;-

1)I re-opened VS with an existing solution and changed the environment that is used and activated by that existing solution / project and saved all, closed the solution and closed VS 2019 - but the error still re-occurs when I relaunch VS and the solution.

2) I set the "use this environment for the default for new projects" to the correct existing environment required by the project, and also included that correct environment in the project, and activated it, I removed the incorrect environment from the solution, then saved all, closed the solution then closed VS - but the error still reoccurs.

Expected behaviour;-
The previously selected and activated environment that was previous activated in the project should be selected and activated automatically when VS 2019 and that existing solution and project are re-start again. 

Versioning information
I am using visual studio 2019 community at version 16.11.27.
I am using several existing environments that use several versions of python 3.

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. Could you give VS2022 a try and see if your issue persists? We have resolved lots of old bugs in the latest release, and it is possible that the problem you encountered in VS2019 may have already been addressed in VS2022. Thank you!

**Comment by agribot2** [comment]
Additional information;-  The desired environment, which VS should use on startup is a customer environment type. The one that VS incorrectly activates is a custom type.

**Comment by agribot2** [comment]
typing correction;-
Additional information;- The desired environment, which VS should use on startup is a conda type (not "customer" , as typed above )   environment type. The one that VS incorrectly activates is a custom type.

Please tell me where the VS 2019 setting that tell VS which virtual environment to use on start up is stored ?
which file ?

**Comment by StellaHuang95** [comment]
Hi there, the issue you're described has been fixed recently. See https://github.com/microsoft/PTVS/pull/7489

Could you try it on the latest VS version and reopen the issue if the problem still persists? Thanks!
