### ISSUE TITLE
Python code compiled and run successfully in Android's Pydroid 3 IDE can't compile in Visual Studio python environment

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7669]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-code-compiled-and-run-successfull/10405319)._

---
I have a piece of code (shown below) that can compile/run in Andriod phone's Pydriod 3 IDE, but can't compile in Visual Studio python environment. Don't know why, I think I pip install all the necessary python modules. Anyone has idea?

#####################################################################################
#                                                                                   #
#                PLOT A LIVE GRAPH IN A PYQT WINDOW                                 #
#                EXAMPLE 2                                                          #
#               ------------------------------------                                #
# This code is inspired on:                                                         #
# https://learn.sparkfun.com/tutorials/graph-sensor-data-with-python-and-matplotlib/speeding-up-the-plot-animation  #
#                                                                                   #
#####################################################################################

from __future__ import annotations
from typing import *
import sys
import os
from matplotlib.backends.qt_compat import QtCore, QtWidgets
# from PyQt5 import QtWidgets, QtCore
from matplotlib.backends.backend_qt5agg import FigureCanvas
# from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib as mpl
import matplotlib.figure as mpl_fig
import matplotlib.animation as anim
import numpy as np

class ApplicationWindow(QtWidgets.QMainWindow):
    '''
    The PyQt5 main window.

    '''
    def __init__(self):
        super().__init__()
        # 1. Window settings
        self.setGeometry(300, 300, 800, 400)
        self.setWindowTitle("Matplotlib live plot in PyQt - example 2")
        self.frm = QtWidgets.QFrame(self)
        self.frm.setStyleSheet("QWidget { background-color: #eeeeec; }")
        self.lyt = QtWidgets.QVBoxLayout()
        self.frm.setLayout(self.lyt)
        self.setCentralWidget(self.frm)

        # 2. Place the matplotlib figure
        self.myFig = MyFigureCanvas(x_len=200, y_range=[0, 100], interval=20)
        self.lyt.addWidget(self.myFig)

        # 3. Show
        self.show()
        return

class MyFigureCanvas(FigureCanvas, anim.FuncAnimation):
    '''
    This is the FigureCanvas in which the live plot is drawn.

    '''
    def __init__(self, x_len:int, y_range:List, interval:int) -> None:
        '''
        :param x_len:       The nr of data points shown in one plot.
        :param y_range:     Range on y-axis.
        :param interval:    Get a new datapoint every .. milliseconds.

        '''
        FigureCanvas.__init__(self, mpl_fig.Figure())
        # Range settings
        self._x_len_ = x_len
        self._y_range_ = y_range

        # Store two lists _x_ and _y_
        x = list(range(0, x_len))
        y = [0] * x_len

        # Store a figure and ax
        self._ax_  = self.figure.subplots()
        self._ax_.set_ylim(ymin=self._y_range_[0], ymax=self._y_range_[1])
        self._line_, = self._ax_.plot(x, y)

        # Call superclass constructors
        anim.FuncAnimation.__init__(self, self.figure, self._update_canvas_, fargs=(y,), interval=interval, blit=True)
        return

    def _update_canvas_(self, i, y) -> None:
        '''
        This function gets called regularly by the timer.

        '''
        y.append(round(get_next_datapoint(), 2))     # Add new datapoint
        y = y[-self._x_len_:]                        # Truncate list _y_
        self._line_.set_ydata(y)
        return self._line_,

# Data source
# ------------
n = np.linspace(0, 499, 500)
d = 50 + 25 * (np.sin(n / 8.3)) + 10 * (np.sin(n / 7.5)) - 5 * (np.sin(n / 1.5))
i = 0
def get_next_datapoint():
    global i
    i += 1
    if i > 499:
        i = 0
    return d[i]

if __name__ == "__main__":
    qapp = QtWidgets.QApplication(sys.argv)
    app = ApplicationWindow()
    qapp.exec_()

---
#### Kan Chu on 7/1/2023, 03:41 AM: 

(private comment, text removed)
#### Feedback Bot on 7/2/2023, 06:49 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. Can you share the error messages or traceback information displayed when attempting to compile the code in Visual Studio?

**Comment by cameronchu1** [comment]
Hi,
The error message is listed bleow:

____________________________________________________________________________________________________________
Traceback (most recent call last):
  File "C:\Users\a5130433\Visual Studio 2022\Projects\strat_backtest\qt5_mat2.py", line 102, in <module>
    app = ApplicationWindow()
  File "C:\Users\a5130433\Visual Studio 2022\Projects\strat_backtest\qt5_mat2.py", line 41, in __init__
    self.myFig = MyFigureCanvas(x_len=200, y_range=[0, 100], interval=20)
  File "C:\Users\a5130433\Visual Studio 2022\Projects\strat_backtest\qt5_mat2.py", line 60, in __init__
    FigureCanvas.__init__(self, mpl_fig.Figure())
  File "C:\Users\a5130433\AppData\Roaming\Python\Python39\site-packages\matplotlib\backends\backend_qt.py", line 205, in __init__
    super().__init__(figure=figure)
  File "C:\Users\a5130433\AppData\Roaming\Python\Python39\site-packages\matplotlib\backend_bases.py", line 1695, in __init__
    super().__init__()  # Typically the GUI widget init (if any).
TypeError: __init__() missing 2 required positional arguments: 'fig' and 'func'
Exception ignored in: <function Animation.__del__ at 0x0000024CC91D2DC0>
Traceback (most recent call last):
  File "C:\Users\a5130433\AppData\Roaming\Python\Python39\site-packages\matplotlib\animation.py", line 883, in __del__
RuntimeError: wrapped C/C++ object of type MyFigureCanvas has been deleted
Press any key to continue . . .

**Comment by StellaHuang95** [comment]
From reading your error messages, seems like the issue lies within your code and involves the use of the `matlibplot` library, which falls outside the scope of PTVS. I found a similar issue in matplotlib repo (https://github.com/matplotlib/matplotlib/issues/25856r) that might be helpful to you. I recommend opening a ticket there to seek further assistance. Thank you!
