### ISSUE TITLE
Python - Add a shortcut way to run the current file in debug mode from within a Python project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7673]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python---Add-a-shortcut-way-to-run-the-c/10399261)._

---
Currently, in order to debug a single file in a Python project, you must right click on the file and then click "Start with debugging". Aswell as this there should be a way of setting the run configuration to this as well as having a shortcut key.

It is useful to new up a quick file to test something in some cases and it is lightly frustrating to have to right click on a file and select that specific option each time.

---
#### Feedback Bot on 6/25/2023, 02:21 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. Currently, we only support debugging startup file with a single click. To config this, you can right-click on the file tab of the file you want to debug and select "Set as Startup File" from the context menu. This will designate the current file as the entry point for debugging. 

We understand that it would be more convenient to have an option to set the run configuration and a shortcut key to initiate debugging directly. We appreciate your feedback and will consider this suggestion to improve the debugging experience. Thanks!
