### ISSUE TITLE
Node.js not found after upgrade to Version 17.7.0 Preview 3.0

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/PTVS#7677]
1. Open any solution
2.
![image](https://github.com/microsoft/PTVS/assets/52322342/05a6f4d2-1a62-4e1f-bd14-cfcd97b80b42)

**Expected behavior**
Pylance working

![image](https://github.com/microsoft/PTVS/assets/52322342/917cc154-c54c-46ad-8d03-384b12ea29ad)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. This is a known issue and the workaround is documented here: https://developercommunity.visualstudio.com/t/Pylance-language-server-isnt-starting-i/10411774

It will be fixed in 17.7 preview 4. Thanks!
