### ISSUE TITLE
Keras support for Python language & Multilanguage & Multiplatform Development

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7683]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Keras-support-for-Python-language--Mult/10406920)._

---
[severity:Other]
I am uncertain as to whether Microsoft should have added in support for the Keras library - for Python Neural Networks and Deep Learning.  It seems Scikit-learn is sufficient for Machine Learning according to Microsoft.

Secondly, I would like Microsoft to create compilers, debuggers and software development tools for all the open source extension projects that are in the VS Marketplace - such as D language, Ada language, and follow jGrasp's example, by adding in coverage for the Kotlin and Ruby programming languages.

Third, I would reiterate, that developers using the Microsoft VS stack - JS, TS, VB, C, C++, C#, F#, Python should be equipped for web, desktop and cloud environment development.

Thanks for taking note.

---
#### Sean Hicks on 7/4/2023, 00:57 AM: 

(private comment, text removed)
#### Tracy Wang [MSFT] on 7/4/2023, 01:52 AM: 

(private comment, text removed)
#### Feedback Bot on 7/4/2023, 03:11 AM: 

(private comment, text removed)
#### andrew goh soo meng on 7/4/2023, 07:14 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Thank you for sharing your suggestions! Your suggestions seem to cover enhancing machine learning support, expanding development tools for different programming languages, and ensuring comprehensive support for web, desktop, and cloud-based development within the Microsoft VS stack, which might fall outside the scope of the PTVS repo.

To better address your requests, could you provide more specific details about the features you would like to see in Python tools for Visual Studio? It will enable us to assess the feasibility and consider your requirements more effectively. Thanks!

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
