### ISSUE TITLE
The Quick Action icon for "Extract Method" is missing.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7685]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/a5bac369-e595-4c64-a152-785618e3ffe8)

**Steps to Reproduce**
1. Create a Python Application.
2. Select the lines of code.
```
x = 1
y = 2
```
3. Move the cursor in front of the code.

**Expected behavior**

The quick action icon should appear before the code.

![image](https://github.com/microsoft/PTVS/assets/82852072/670b9785-09d9-4d3b-9df1-8b7394d3dd54)

**Additional context and screenshots**

The quick action icon for "Extract Method" is not displayed.

![image](https://github.com/microsoft/PTVS/assets/82852072/25c5ff79-5d66-4296-8a10-f093a8365fd9)

**Comment by StellaHuang95** [comment]
Might have to do with the commit that added the extra 'kind' checking for code actions: https://github.com/microsoft/pyrx/commit/b31c1f4a6982246aaa0ea7799999ecc87cd1d5c0

**Comment by StellaHuang95** [comment]
Closing as it doesn't repro anymore on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.8.0 Preview 2.0 [34002.499.main]
