### ISSUE TITLE
"import xxxxx" without any warnings in the error list.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7687]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/744f1c75-c648-4ab4-a3a9-7b1ed617e128)

**Steps to Reproduce**

1. Create a Python Application.
2. type ```import xxxxx```.

**Expected behavior**

Displays a green squiggly line under xxxxx and a warning in the error list.

![image](https://github.com/microsoft/PTVS/assets/82852072/67609084-d9af-48bc-98d1-bd3b392708b7)

**Additional context and screenshots**

No green squiggly lines and warnings.

![image](https://github.com/microsoft/PTVS/assets/82852072/cbdb5338-597d-45a3-8649-ebd829f0231e)

**Comment by StellaHuang95** [comment]
Closing as it doesn't repro anymore on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.8.0 Preview 2.0 [34002.499.main]
