### ISSUE TITLE
The Combo box and the Python Environment list is not update when change the default environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7692]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/c17cf0c4-6a6e-49b0-8a4d-dbcdda1388e1)

**Steps to Reproduce**
1.Install Anaconda (downloads at https://www.anaconda.com/download/) if no Anaconda
2.Create a Python Application project
3.Right-click on Python Environments node in SE and select "View All Python Environments"
4.The python distributions installed should all displayed in the list
![image](https://github.com/microsoft/PTVS/assets/59192491/d1465579-15f2-452f-ab82-382756f40d94)
5.Select 'Python 3.1(64-bit)'
6.Overview -> 'Make this the default environment for new projects'

**Expected behavior**
The Combo box and the Python Environment list should all change to 'Python 3.1(64-bit)'

**Actual behavior**
The Python Environment list doesn't change to 'Python 3.1(64-bit)'

**Additional context and screenshots**
![make_default_env](https://github.com/microsoft/PTVS/assets/59192491/fe6c2b96-3589-4682-b52f-bc167beb5e9e)

**Comment by StellaHuang95** [comment]
This is by design. Note that this option sets the default environment for NEW projects, if you save the options and create a new python project, it will use the default environment.
