### ISSUE TITLE
Go To All can't find the method where is defined in another project

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7696]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/b99a95c5-f0cf-4b91-883e-8199c4660230)

**Steps to Reproduce**
1.Create a solution with 2 Python application projects: ProjectC, ProjectD
2.Type same codes in both python files
```
def hello():
    pass
```
3.Menu to navigate to, that Edit > Go To > Go To All 

**Expected behavior**
![image](https://github.com/microsoft/PTVS/assets/59192491/b53da663-f4a4-4fcf-87c7-46a4f05e97b8)

**Actual behavior**
![image](https://github.com/microsoft/PTVS/assets/59192491/e915fc76-4e8e-43e0-a5d5-92c281c3791e)

**Additional context and screenshots**
**NOTE:** Only when I restart VS， it matches normally
![gotoall_another_project](https://github.com/microsoft/PTVS/assets/59192491/aaf950c0-beea-4edb-b8cb-0d20d9dd2826)

**Comment by judej** [comment]
Thank you for the report! Given our current limited resources, and given that it works on restart, it's unlikely we will be able to fix this issue in the near future. We're closing it so we can focus on higher priority issues. However, if this is a critical issue for you let us know and we can reevaluate. Thanks!
