### ISSUE TITLE
Edit and Continue

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#77]
Allow code to be modified while broken in the debugger, then continue executing the modified code using the same state.

(Migrated from https://pytools.codeplex.com/workitem/212)

**Comment by Kielland** [comment]
This would be great!

**Comment by UniBreakfast** [comment]
Can't wait to use it...

**Comment by wonkoRT** [comment]
Jep, ENC would be awesome

**Comment by Leeyaa** [comment]
hi zooba, this question was raised 2 years ago  ,i wonder if the ENC available now?

**Comment by zooba** [comment]
I don't think anyone has looked into this recently, as we think it'll take changes in CPython itself in order to be useful (currently we could do it, but only for functions not currently on the stack, which means you'd have to return and re-call the one you just edited).

@karthiknadig and @int19h are probably thinking hardest about it right now.

**Comment by Leeyaa** [comment]
> I don't think anyone has looked into this recently, as we think it'll take changes in CPython itself in order to be useful (currently we could do it, but only for functions not currently on the stack, which means you'd have to return and re-call the one you just edited).
> 
> @karthiknadig and @int19h are probably thinking hardest about it right now.

thanks a lot. looking forward to this cool function.

**Comment by eduardovra** [comment]
This feature would be game changing.

**Comment by steinemann** [comment]
Would absolutely love this

**Comment by thecyman** [comment]
Please add this. This would put Visual Studio way above other Python options, in my view, for Python development. Even if I needed to re-enter the function, that would be pretty useful. (So long as this is well-documented.) Consider it for large projects or Django. You could make some edits on the fly and retest.
That said, yes, with .NET C# you can really "code as you debug" which is more powerful and may need CPython changes. Total game changer.

Today however, running VS2019, if I edit a line of Python code while debugging, the debugger just ignores the change and the debugger still highlights the line (even if I change the code on that line or inserted a totally new line of code). So the "bug" of unmatched code is already there. Perhaps a well-documented refreshing when off the stack could be considered a partial fix.

There is a research paper on adding "Edit and Continue" to CPython with 300 lines of code I found here: https://www.hpi.uni-potsdam.de/hirschfeld/publications/media/HenningStanglNiephausKruckHirschfeld_2019_HotCodePatchingInCPythonSupportingEditAndContinueDebuggingInCPythonWithLessThan300LinesOfCode_AcmDL.pdf
"Hot Code Patching in CPython" by Johannes Henning et al.
