### ISSUE TITLE
Python code not working on mac 

### ISSUE THREAD

**Issue by AryanAT13** [microsoft/PTVS#7700]
I am trying to run a hello world code in python but when i do so it runs successfully but no output, but when a run the same python file in terminal it works, i m using a macbook.
<img width="1440" alt="Screenshot 2023-08-18 at 12 04 51 AM" src="https://github.com/microsoft/PTVS/assets/124758101/ced776fa-bb4d-4653-96e1-13c383d76a86">
<img width="1440" alt="Screenshot 2023-08-18 at 12 06 33 AM" src="https://github.com/microsoft/PTVS/assets/124758101/1ee0f4e5-a4ae-44c5-bab6-aabafce5b790">
<img width="1440" alt="Screenshot 2023-08-18 at 12 06 58 AM" src="https://github.com/microsoft/PTVS/assets/124758101/863615a2-ba73-476a-a03d-21744798a36c">

**Comment by StellaHuang95** [comment]
It seems like you're working with VSCode, which is slightly beyond the focus of our repository that primarily deals with Python tools for Visual Studio. Would you mind creating a ticket on the https://github.com/microsoft/vscode-python repository and share the repro steps? Thank you!
