### ISSUE TITLE
Writing comments in python functions mess up indentation

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7703]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Writing-comments-in-python-functions-mes/10441048)._

---
[regression]
If I write python code and insert a comment in the middle of a function VS2022 things the function ended.
To replicate the error write a comment in a function and hit enter then the indentations for the next line will be wrong.
```
def fun():
    a = 0
    # comment
b=0
```
If I hit enter after I written the comment the it thinks the function is over. This is annoying.

---
#### Feedback Bot on 8/15/2023, 06:39 PM: 

(private comment, text removed)
#### Владислав Милоста on 8/17/2023, 01:04 PM: 

(private comment, text removed)
#### Martin Persson on 8/22/2023, 03:35 AM: 

(private comment, text removed)
#### Владислав Милоста on 8/22/2023, 09:23 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
New issue created here in pylance: https://github.com/microsoft/pylance-release/issues/4763

**Comment by StellaHuang95** [comment]
Hi there, the issue you reported has already been addressed in Pylance. Once the latest stable version of Pylance is integrated into PTVS, you can expect the same resolution for this issue in the next PTVS release.
