### ISSUE TITLE
Deubugger: Strings with multiline separator throwing source code highlighting and break-points off

### ISSUE THREAD

**Issue by vramakanth** [Microsoft/PTVS#771]
When debugging code with multiline string separator '\', I find that the debugger is unable to resolve the correct line number of the code. When I am setting breakpoints, I need to set offset them, depending on the number of '\' separators I have used in the code .

I think the code below explains it a lot better than I can. 

Thanks,
Vikram

``` python
"""
Visual Studio 2010 with PTVS 2.1, Windows 7 64 bit, Iron Python 2.7, Issue occurs when using the 'Standard Python Launcher' and the 'Iron Python (.NET) launcher' 
"""
def get_list():
                        # the multiline string seperator '\' below throws line detection off. Depending on how many such seperators the code has, the line number detection for source code below them gets thrown off.
    l = ['for\
          he',       
         'is a jolly good fellow']

    return l


if __name__ == "__main__":  # you need to place the break point here for the debugger to break at the next line, at print get_list
    print get_list()        # if you place a breakpoint here, print get_list() would have already been executed and you will see the output in the terminal; and the code will be breaking at next line
    print 'done.'           # if you place the breakpoint here, this script will never break (the standard python launcher prompts before the console is terminated, the iron python launcher terminates automatically)
```

**Comment by zooba** [comment]
This is probably because Python is concatenating the line at the trailing backslash and *then* calculating line numbers, whereas VS does not do this. We'll probably need to add our own line mapping somehow.

**Comment by DinoV** [comment]
This is actually a bug in IronPython...  The parser isn't properly tracking the new line locations here.

**Comment by DinoV** [comment]
Pull request submitted to IronPython: https://github.com/IronLanguages/main/pull/1285
