### ISSUE TITLE
reportMissingModuleSource	error "Import ... could not be resolved from Source"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7710]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/reportMissingModuleSource	error-Import-/10447137)._

---
I was using Visual Studio Code fine without any problems, but for academic purposes, I needed to pivot to Visual Studio 2022. When I installed it, if I run the developer Powershell or the Developer Command Prompt, I'm able to run my Python codes just as in VS Code. Even in the integrated Developer Powershell, I have no problems. But, in the Visual Studio Interface, IntelliSense is detecting that I don't have some modules, that I have installed on VS Code. I tried to find this similar problem online and it says it may be related to choosing a different Python interpreter, but I only have one available, and as I tried to confirm it, I thinks is exactly the same as the one in VS Code. I'm also not able to run my code via the play button on the startup Item in the VS 2022 interface.

Any idea how to fix this issue? Thanks in advance!

---
#### Feedback Bot on 8/22/2023, 07:31 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
