### ISSUE TITLE
Incorrect behavior with "Format Document"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7722]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-behavior-with-Format-Document/10461563)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.7.3]
This problem happened when I am using the lasted VS (17.7.3).
After i finish my code, I want vs to format my code, so I pressed "Ctrl+K; Ctrl+D" and then errors occurred.
Here are my original code:
```
fp = 0
def show(frame):
    global fp
    if not fp:
        cv2.imshow("frame", cv2.resize(frame, None, fx=ZOOM, fy=ZOOM))
        cv2.waitKey(WAITKEY)
    fp += 1
    fp %= 10
    if cnt / isz and not fp:
        print("\r%6.2f%%  used:%8.2fs  last:%8.2fs error:%3d"%(round(cnt / isz * 100, 2),round(time.time() - ts, 2),round((time.time() - ts) / (cnt / isz) - (time.time() - ts), 2),err,),end="")
    return
```
and after VS formatting:

```
fp = 0

def show(frame):
    global fp
    if not fp:
        cv2.imshow("frame", cv2.resize(frame, None, fx=ZOOM, fy=ZOOM))
        cv2.waitKey(WAITKEY)
    fp += 1
    fp %= 10
    if cnt / isz and not fp:
        print(
            "\r%6.2f%%  used:%8.2fs  last:%8.2fs error:="
            % (
                round(cnt / isz * 100, 2),
                round(time.time() - ts, 2),
                round((time.time() - ts) / (cnt / isz) - (time.time() - ts), 2),
                err,
            ),
            end="",
        )")
    return
```
It can be seem that: string `error:%3d` wrongly become `error:=`, and redundant `")` are added.

---
#### Feedback Bot on 9/10/2023, 10:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
This also repros with 
```python
print("%3d"
      )
```

**Comment by StellaHuang95** [comment]
https://github.com/microsoft/PTVS/blob/b8d44384a70487468c060b424757022887162505/Python/Product/PythonTools/PythonTools/Editor/Formatting/DiffMatchPatch.cs#L2254
