### ISSUE TITLE
Property name is not allowed by the schema.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7729]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/2a61cbbb-a9eb-43b0-953c-318cc1c7e26c)

**Steps to Reproduce**

1. Open folder in SE. 
2. Add new python file in SE named WholsRunningMe.py.
3. Select an python environment from the python toolbar to open PythonSettings.json and you can check “Show All Files” on the toolbar to reveal local settings. 

**Expected behavior**

No warning.

**Additional context and screenshots**

Many warnings are displayed in the error list.

![image](https://github.com/microsoft/PTVS/assets/82852072/b3a5a86c-e997-4d60-8c62-5e491781ecab)

**Comment by StellaHuang95** [comment]
![image](https://github.com/microsoft/PTVS/assets/100439259/ebb1dc75-6a9e-4ed2-bf3f-96dc3f6610e5)
It doesn't repro with no schema picked.
