### ISSUE TITLE
Rename with ctrl-r ctrl-r doesn't work correctly

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7730]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/2cd71cac-4187-4574-8851-7e43181d3ac7)

**Steps to Reproduce**
1.Create a python project
2.Create a method in default python file
3.Type ctlr-r ctrl-r to do a rename

**Expected behavior**
The rename dialog UI thingy pops up and allows me to type the new name

**Actual behavior**
Sometimes it comes up and works correctly, and sometimes it appears briefly and then disappears.However right click rename does work correctly - it is only the keyboard shortcut that is unreliable.
![ctrl+r_rename](https://github.com/microsoft/PTVS/assets/59192491/ff49eb45-66c8-4f6a-93e4-caab3bb69fe9)

**Comment by judej** [comment]
@linette-zyy, could not repro this with preview or 17.7.4. Tried with ctrl-r ctrl-r and f2. 

Could you please try and repro on another machine perhaps?

**Comment by judej** [comment]
tried on Version 17.9.0 Preview 1.0 [34208.28.main]
