### ISSUE TITLE
Updated to full version, can no longer read .cs files

### ISSUE THREAD

**Issue by jared-streich** [microsoft/PTVS#7734]
**Describe the bug**
[A clear and concise description of the bug]

**Steps to Reproduce**
1. Get trial version of Visual Studio 2022 Pro
2. Company purchases full version of Visual Studio Pro
3. Reopen Visual Studio 2022 Pro after installing and updating to full version

**Expected behavior**
I expected to use the product as normal. Now all my .csproj have (incompatible) next to them. I click on them and underneath they say "The application is not installed."

VS Version: 17.7.5

**Comment by StellaHuang95** [comment]
Can you go the your Visual Studio installer and share which workloads have you installed in that version?

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
