### ISSUE TITLE
VS crash when editing

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/PTVS#7736]
Editing or copying code or using ctrl-x crashes VS which gets stuck displaying a message box "copy - Formatting selection". This happens when not waiting until the status message "x files to analyze" disappears and "Python analysis done" shows.

![image](https://github.com/microsoft/PTVS/assets/52322342/d0668251-5e4f-4b73-95fa-8e2c81001acb)

**Comment by excubo-jg** [comment]
In some instances the message is: "Please wait for an editor command to finish"

**Comment by StellaHuang95** [comment]
Hi there, thanks for bringing this issue to our attention. The problem you've encountered is related to the upstream, and it falls outside of this repository to address. There are multiple similar issues that are currently being monitored and investigated by the editor team internally.

- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1859908
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1554292

To help resolving this problem, would it be possible for you to provide us with more information? I will make sure it reaches the appropriate team for further analysis and action. 

Could you provide detailed repro steps about your issue using https://www.screentogif.com/?

Would you also please provide dump file when the issue recurs again with below method?

1. Follow your steps to get VS to hang
2. Launch task manager
3. Click on “More Details” if you haven’t already done that, Switch to the Details tab
4. Right click on devenv.exe and select “Create Dump File”
5. Compress and attach the dump file to this developer community entry so we can investigate.

Thanks

**Comment by excubo-jg** [comment]
To repro I open a file, put the cursor someplace in the code and do ctrl-x and then ctrl-v. After the first or second sequence VS hangs. Is a video really necessary?

The compressed file size is 316MB and I can only upload 25MB here. Please provide another way to get the file to you

**Comment by StellaHuang95** [comment]
Could you try this? https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

**Comment by excubo-jg** [comment]
I have issued a report with a reference to this issue.

As my Microsoft accounts are thoroughly messed up, more often than not I do not get any updates from the dev community pages and if things really go awry I cannot log in over there or cannot see my reports when logged in... May I ask that you cross-post additional requests here if you not see a reaction from me on the other site?

**Comment by olegtk** [comment]
@excubo-jg, thank you for reporting this issue. please check if you have this checkbox checked and if so, uncheck it. It got checked inadvertently in 17.8 previews.

<img width="548" alt="image" src="https://github.com/microsoft/PTVS/assets/27849/9b899cd3-7ab2-4b15-95b0-6d534bddf2f2">

**Comment by excubo-jg** [comment]
Many thanks for your swift reply. Unchecking solves the issue.
