### ISSUE TITLE
Hello, I am logged into the GitHub application to complete my week 3 assignment and I cannot see the start button to debug the input.  

### ISSUE THREAD

**Issue by Sgirl64** [microsoft/PTVS#7737]
**Describe your question**
[A clear and concise description of your question or what you want help with]

**What have you tried?**
[Have you already searched online? What solutions have you tried?]

**Additional context**
[Add any other information or screenshots that would help us provide you with a better answer]

**Comment by StellaHuang95** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue.

If this continues to be a problem, would you please reopen the issue and add repro steps and code samples for us to further investigate?
