### ISSUE TITLE
Numpy array content not displayed fully in preview version

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/PTVS#7739]
In the recent preview versions the displays of numpy arrays has been changed so that it is impossible to see the content of longer arrays as they get cut-off:
![image](https://github.com/microsoft/PTVS/assets/52322342/f3d86729-ef72-4c03-b274-ccaac93a5892)

In the regular version (screenshot from Version 17.7.5), the content of the same variable can be accessed by scrolling vertically.
![image](https://github.com/microsoft/PTVS/assets/52322342/401f49b7-a3ea-4d7c-89e5-737ef7802df4)

Removing the functionality to display longer arrays is ill-conceived. Please add back.

**Comment by StellaHuang95** [comment]
It's a bug in debugpy, see https://github.com/microsoft/debugpy/issues/1408. Going to close this one and please track the issue there. Thanks!
