### ISSUE TITLE
Add monthly pipeline schedule to coincide with pylance releases

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/PTVS#7748]
Modify the PTVS yaml to perform a scheduled run every month, sometime after the pylance stable release, so it gets bundled up properly and in a timely manner.

- [ ] update pipeline
- [ ] update docs
- [ ] hotfixs

**Comment by StellaHuang95** [comment]
Maybe consider keeping the same schedule, but adding logics to check if msft_consumption has a newer version of pylance available.

**Comment by AdamYoblick** [comment]
I've modified the pylance release yaml to include a step to launch the ptvs azdo pipeline after the release occurs. See https://github.com/microsoft/pyrx/pull/4339
