### ISSUE TITLE
Execute Project In Python Interactive Django doesn't work

### ISSUE THREAD

**Issue by cmedcoff** [Microsoft/PTVS#775]
All I see in the interactive window is:

```
"Running C:\Users\cmedcoff\Documents\Visual Studio 2013\Projects\DjangoWebProject3\DjangoWebProject3\manage.py

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:....
```

Its like its not passing runserver.

 Below is the "Diagnostic Info" dump (abbrevisated - too large for allowed submit here)

```
Projects: 
    Project: DjangoWebProject3\DjangoWebProject3.pyproj
        Kind: Python
        InterpreterId: b908c31f-3231-4be5-ac0f-cdd9cea4a9c8
        InterpreterVersion: 3.4
        StartupFile: C:\Users\myname\Documents\Visual Studio 2013\Projects\DjangoWebProject3\DjangoWebProject3\manage.py
        WorkingDirectory: .
        PublishUrl: <undefined>
        SearchPath: 
        CommandLineArguments: <undefined>
        InterpreterPath: <undefined>
        PythonDebugWebServerCommandType: script
        PythonDebugWebServerCommandArguments: runserver --noreload --settings DjangoWebProject3.settings %SERVER_PORT% 
        PythonRunWebServerCommandType: script
        PythonRunWebServerCommandArguments: runserver --settings DjangoWebProject3.settings %SERVER_PORT% 
        PythonWsgiHandler: django.core.wsgi.get_wsgi_application()

        Interpreter: env (Python 64-bit 3.4)
            Id: b908c31f-3231-4be5-ac0f-cdd9cea4a9c8
            Version: 3.4

    Project: <MiscFiles>
        Kind: {66A2671D-8FB5-11D2-AA7E-00C04F688DDE}

Environments: 
    Microsoft.PythonTools.Project.LoadedProjectInterpreterFactoryProvider
        Id: b908c31f-3231-4be5-ac0f-cdd9cea4a9c8
        Factory: env (Python 64-bit 3.4)
        Version: 3.4
        Arch: Amd64
        Prefix Path: C:\Users\myname\Documents\Visual Studio 2013\Projects\DjangoWebProject3\DjangoWebProject3\env\
        Path: C:\Users\myname\Documents\Visual Studio 2013\Projects\DjangoWebProject3\DjangoWebProject3\env\Scripts\python.exe
        Windows Path: C:\Users\myname\Documents\Visual Studio 2013\Projects\DjangoWebProject3\DjangoWebProject3\env\Scripts\pythonw.exe
        Lib Path: C:\Users\myname\Documents\Visual Studio 2013\Projects\DjangoWebProject3\DjangoWebProject3\env\Lib
        Path Env: PYTHONPATH

    Microsoft.PythonTools.Interpreter.ConfigurablePythonInterpreterFactoryProvider
    Microsoft.PythonTools.Interpreter.CPythonInterpreterFactoryProvider
        Id: 9a7a9026-48c1-4688-9d5d-e5699d47d074
        Factory: Python 64-bit 3.4
        Version: 3.4
        Arch: Amd64
        Prefix Path: C:\Python34
        Path: C:\Python34\python.exe
        Windows Path: C:\Python34\pythonw.exe
        Lib Path: C:\Python34\lib
        Path Env: PYTHONPATH

    Microsoft.IronPythonTools.Interpreter.IronPythonInterpreterFactoryProvider
Launchers:
    Launcher: Microsoft.PythonTools.Project.DefaultLauncherProvider
        Launches and debugs Python programs. This is the default.
        Standard Python launcher

    Launcher: Microsoft.PythonTools.Project.Web.PythonWebLauncherProvider
        Launches web sites using the Python debugger. This enables launching and starting a web browser automatically, using the commands specified in the project file.
        Web launcher

    Launcher: Microsoft.IronPythonTools.Debugger.IronPythonLauncherProvider
        Launches IronPython scripts using the .NET debugger.  This enables debugging both IronPython code as well as other .NET code such as C# or VB.NET.
        IronPython (.NET) launcher

    Launcher: Microsoft.PythonTools.Django.Debugger.DjangoLauncherProvider
        Launches Django web sites using the Python debugger. This enables launching and starting a web browser automatically. It launches using manage.py and passes the runserver flag as well as additional options to configure the port and other settings.
        Django launcher

Logged events/stats:
Installed Interpreters: 1
Configured Interpreters: 0
Debug Launches: 0
Normal Launches: 1

Installed Packages:
Name,Version,InterpreterName,InterpreterVersion,InterpreterArchitecture,Installer,Elevated,InstallResult
  Successful Installations
    django,1.8.4,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0
    pip,7.1.0,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0
    setuptools,18.0.1,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0
    wheel,0.24.0,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0
    pip,7.1.0,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0
    setuptools,18.0.1,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0
    wheel,0.24.0,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0
    django,1.8.4,DerivedInterpreterFactory,3.4,Amd64,Existing,False,0

  Failed Installations


System events:
```

**Comment by zooba** [comment]
(I wrapped some of your text in triple backticks to make it more readable. You can also post long logs on gist.github.com and link to them.)

This is currently "by design", but I'm not entirely clear what behavior you'd like or why you'd like it. If you launch normally then you can use the Debug Interactive window at a breakpoint, but running a web server in a regular interactive doesn't seem to make much sense.

Can you describe what you're trying to achieve? We may have another way to do the same thing.

**Comment by cmedcoff** [comment]
Thank you.  Perhaps I don't understand the intent of the command. I had the expectation that rather than launching/running python/django on a separate console window, it would do so in a combination of the output and interactive window.  Perhaps that is what happens when just performing a normal "F5" type of debug.  The console window output is confusing compared to ASP.NET web app development.

**Comment by zooba** [comment]
Yes, compared to ASP.NET it is strange. Unfortunately, compared to Python development outside of VS it is entirely normal, so it isn't easy for us to match either of them without potentially confusing people.

I suspect you'd really like the Debug Interactive window, which you can find under the Debug, Other Windows menu. We should copy all output from the console into this window, and if you hit a breakpoint then you can interact directly with the code - think of it as a combined Output and Immediate window, but much more powerful.

[This video](https://www.youtube.com/watch?v=y1Qq7BrV6Cc) (about 6 minutes) is about cross-platform debugging, but it also demonstrates the Debug Interactive window.

**Comment by cmedcoff** [comment]
OK, I can accept the 'extra window' since that's how the django test server works without visual studio and yes it seems that the Debug Interactive window does what I expected.  I would like to understand what the purpose of "Execute Project In Python Interactive" is and why it isn't suitable for a django/web app.  I will say that I'm very happy to find rich support for Python in the IDE where I spend most of my time.

**Comment by zooba** [comment]
That execute command is more directed at single-run processing scripts. For example, you may be parsing a text file and doing something with the results. Running it in the interactive window is like running each command by hand, except far more convenient, and you have all the variables (parsed log lines) stick around after it's finished. It's like running `python.exe -i <script>`, but within VS we expose it as a separate command.

A web server basically loops until it's terminated, and there's no reason to interact with it directly (both accessing the web content and debugging are considered "indirect" here), so it doesn't make much sense to run it in an interactive window. It's output should be going into the Output window, as for C# applications, but because people also expect to see the console window we display that too.

**Comment by cmedcoff** [comment]
Thanks.
