### ISSUE TITLE
[error report] issue with installing jinja package

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7751]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/error-report-issue-with-installing-jin/10503166)._

---

I am currently experiencing an issue while trying to install the Jinja package in my Python project. Upon running the command 'pip install jinja', I encountered the following error:

"python setup.py egg_info did not run successfully.
exit code: 1

[7 lines of output]
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "C:\Users\M-ELITE TECHNOLOGIES\AppData\Local\Temp\pip-install-ux3z7p9x\jinja_32c2093bad3b4f92bca742bc2491d17c\setup.py", line 28   
    except DistutilsError, e:
           ^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details."

This error seems to originate from a subprocess, and it appears to be a problem with the package metadata generation. I have already tried updating pip and setuptools, clearing the pip cache, checking my internet connection, and temporarily disabling my antivirus, but the issue persists.

I would greatly appreciate any guidance or support from the developer community on how to resolve this issue and successfully install the Jinja package for my project.

- Operating System: [windows 10 pro]
- Python Version: [ Python 3.12(64-bit)]
- Pip Version: [Pip 23.3.1]

Any help or insights would be highly appreciated. Thank you for your time and assistance.

Best Regards,
[Elisee Biyong]

---
#### Nicole Hu [MSFT] on 10/30/2023, 10:40 PM: 

(private comment, text removed)
#### Feedback Bot on 10/30/2023, 11:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thank you for the issue. It appears that the error message you're encountering is related to the Jinja package's setup script, not with PTVS. To clarify, the package you are trying to install is typically named `Jinja2` not `Jinja`. To resolve this issue, please try running this command `pip install Jinja2` and check if it resolves your installation problem. If the issue persists and you suspect it's related to PTVS, please feel free to reopen the issue with more details. We'll be happy to assist you further. Thank you.
