### ISSUE TITLE
About the default closing of the turtle graphics window

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7755]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/About-the-default-closing-of-the-turtle-/10512842)._

---
when the turtle program is done,the turtle graphics windows is default closed,i can't keep it on my screen.
I consulted ERNIE Bot. She tried the operation and help, and was unable to find the option of "Close the window after completing the program", so I came to you to respond to the question

---
#### Feedback Bot on 11/12/2023, 09:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, if you're running your code that closes the turtle window immediately after execution, you can add the `turtle.done()` function at the end of your code. This function keeps the window open until the user closes it manually.

Please reopen the issue if you have any PTVS specific questions. Thanks!
