### ISSUE TITLE
The option of 'Code Snippets Manager' is missing

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7757]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/2eea4081-9228-4c26-854c-8b75bbb9b2f8)

**Steps to Reproduce**
1.Create a python project
2.Tools > Code Snippets Manager

**Expected behavior**
![image](https://github.com/microsoft/PTVS/assets/59192491/6f993047-3865-420c-8084-b68f9aa7c026)

**Actual behavior**
![image](https://github.com/microsoft/PTVS/assets/59192491/77dfd5bf-221f-4835-ac4e-257c04835bee)

**Comment by StellaHuang95** [comment]
The code snippets manager is not specific to PTVS, it's outside the scope of this repo, it also repros for all other languages. I haven't found an internal associated work item yet, but for now just label it as waiting for upstream since there's nothing we can do there.
