### ISSUE TITLE
Type Hints via stub files doesn't change after deleting .pyi file

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7758]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/751f11e8-6db3-4f12-9f81-58e8b049e595)

**Steps to Reproduce**
1.Create a Python Application project
2.Add a module file named employee.py and enter below code:
```
def is_valid_employee(name, id): 

       return False
 ```
3.In default .py file which has no type:
```
from employee import *
is_valid_employee()
```
![image](https://github.com/microsoft/PTVS/assets/59192491/6dc5cd2b-fb70-4fbf-aa71-5dad05d0f921)

4.Add a stub file named employee.pyi and enter below code:
```def is_valid_employee(name:str, id: int) -> bool: pass ```
5.In default .py file, tooltip that shows VS proposes the types found in the .pyi
![image](https://github.com/microsoft/PTVS/assets/59192491/f7c305bd-4e20-4358-bd87-80f0f174f3c6)
6.Delete employee.pyi
7.Check type Hints whether change to 'Any'

**Expected behavior**
![stub_files_correct](https://github.com/microsoft/PTVS/assets/59192491/5b4e2c17-00ea-4514-aed7-9f78b39f89ca)

**Actual behavior**
![stub_files_incorrect](https://github.com/microsoft/PTVS/assets/59192491/256329e6-f3b9-4ccb-b4b6-dee339b85e61)

**Additional context and screenshots**
**Out from Pylance:**
```
Info: (9120) Pylance language server 2023.11.10 (pyright 088ebaa5) starting
Info: (9120) Server root directory: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Microsoft\Python\Core\pylance\dist
Info: (9120) Starting service instance "PythonApplication18"
Info: Un-registering request handler for ce1ac14c-b4d8-451a-8149-838de3401d61 failed.
Info: (9120) Setting pythonPath for service "PythonApplication18": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe"
Info: (9120) Assuming Python version 3.9
Info: (9120) Found 1 source file
Info: (9120) Found 2 source files
Info: (9120) Found 3 source files
```

**Comment by StellaHuang95** [comment]
This is a little bit tricky, it seems to be fixed in pylance 10.50 or above, but 11.10 was rolled back to 10.40, so 11.10 is actually version 10.40. See changelogs here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md

Since pylance team has changed their release cadence to once a month, most likely the fix will be in at the end of this month after they release the next pylance stable version.
