### ISSUE TITLE
Problems with VS 2013, PTVS 2.2 and Anaconda

### ISSUE THREAD

**Issue by tkpmep** [Microsoft/PTVS#776]
I am having trouble using PTVS 2.2  with Anaconda and would greatly appreciate some help. I installed Anaconda 3-2.2.0 64 bit and then installed VS 2013 Express and PTVS 2.2. I created an  enviroment named Anaconda in VS 2013 with the following settings:
Path: C:\Anaconda3\python.exe
Windows Path: C:\Anaconda3\pythonw.exe
Library Path: C:\Anaconda3\Lib
Architecture: x64
Language Version: 3.4

After loading a simple Python Script (not a VS project, just a .py file) I now see the following:
I have two interactive Python windows: Python Debug Interactve and Aanaconda Interactive
On the Debug menu, Start Debugging and Start Without Debugging are both grayed out. The only option I have to exectue a file seems to be "Execute the File in Python Interactive" 
If I click on Project> Start with Debugging or Project> Start without Debugging , I get an error message: Unspecificed Error (Exception from HRESULT: 0x800004005 (E_FAIL).
If I click on Debug > Execute file in Python Interactive, it runs in the Anaconda Interactive window
I can set breakpoints (using F9) but the program will not stop at them.
There's a green triangle on the toolbar with a dropdown that allows one to Attach to other processes, but nothing to execute, single step through code etc.

I'm lost, and havn't been able to Google my way to a solution, so I'd greatly appreciate any thoughts on what the cause of my problem is.

Thanks in advance

Thomas Philips

**Comment by zooba** [comment]
This may be a bug that we found after releasing PTVS 2.2.

This will sound strange, but try opening Solution Explorer (you don't need to have anything in it, you just need to bring up the window), and then start running the file again.

**Comment by tkpmep** [comment]
Wow! that's a dark secret! i tried it and sure enough, if I click on Project> Start with Debugging, it will start the program and stop at breakpoints. The execution, however, takes place not in an iteractive window, but in a Dos box, but once a breakpoint is reached, I don't seem to be able to do anything from the Anaconda Interactive prompt i.e. print variables etc. . I then clicked Debug > Execute File in Python Interactive and I get an Anaconda Interactive Window as well as a Python Debug Interactive Window, bu no locals or watch windows, and i could not examine variables in the Python Debug Interactive window. is there something else I need to do in order to be able to interactively debug my code? I'd like to print variables, play around with etc.  etc. standard debugging stuff.

**Comment by zooba** [comment]
Execute in Python Interactive shouldn't work like that... very strange.

I'm not sure what you've got in your script, but maybe you just want to use the regular Interactive Window for that environment? You can select text in the editor, right-click and use "Send to interactive" to run it into the interactive window, and then continue working with the results. (This is exactly how "Execute in Python Interactive" is *supposed* to work...)

We're looking into making the whole debugging from the interactive experience considerably better for our next release, but right now the best we can do is to enable attaching through Interactive Options, type `$attach` in the interactive window, and then enter whatever code you want to debug.
