### ISSUE TITLE
"CTRL-C" to quit does not work for Python BottleWebProject.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#7762]
**vs environment**
![image](https://github.com/microsoft/PTVS/assets/39871640/ee77cfde-adec-4939-b089-29a2f13a92aa)
**python version**
download python 3.9.13 from Microsoft store.
**Steps to Reproduce**
1. Create BottleWebProject in vs.
2. Create virtual environment for the project.
3. Start and run the project.
4. Hit "Ctrl-C" to quit the terminal.

**Expected behavior**
server should be quit after press "Ctrl-C" to quit the terminal.

**Actual behavior**
"CTRL-C" to quit does not work after press ctrl-c. 

**Additional context and screenshots**
![image](https://github.com/microsoft/PTVS/assets/39871640/bd59cac5-aa45-44ca-84d7-3fbf92644529)

**Comment by StellaHuang95** [comment]
Can't repro this either, can you share a gif of what's going on on your side?

**Comment by StellaHuang95** [comment]
The debug mode may interfere with the default Ctrl+C behavior. Debug mode often enables features like code reloading, which can complicate the shutdown process. Try running the server without debug mode to see if the issue persists.

**Comment by StellaHuang95** [comment]
Closing this issue as it appears to be beyond the scope of PTVS to address.
