### ISSUE TITLE
Python Profiling does not work.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#7764]
![image](https://github.com/microsoft/PTVS/assets/39871640/b90b4511-879c-4245-b33a-0e71065f532f)

.vsp file is empty after launch python profiling......

**Steps to Reproduce**
1. create python project.
2. write code in .py file
3. debug->launch python profiling...... 

**Expected behavior**
The .vsp file is generated and opened in VS but not saved.

**Actual behavior**
The .vsp file is generated and opened in VS **but is empty**.
![image](https://github.com/microsoft/PTVS/assets/39871640/3fd7dc34-7cb1-4b82-b40e-f4fcf9aaa440)

**Comment by linette-zyy** [comment]
This issue is reproduced on today's build
![image](https://github.com/microsoft/PTVS/assets/59192491/804b549e-8243-487c-953c-fcf0e5978916)
![image](https://github.com/microsoft/PTVS/assets/59192491/b878d162-8d53-4eb6-afa9-8aa831399c60)

**Comment by StellaHuang95** [comment]
Can't repro this one. What's the python version you use? Were you able to run any python code?

**Comment by zhouwangyang** [comment]
> Can't repro this one. What's the python version you use? Were you able to run any python code?

I discovered this problem by using Python 3.9.13 that comes with installing VS. The entered python code can be run successfully. The .vsp file can be generated but nothing can be displayed in vs.

but today, this issue can't repro on the latest build on main branch (17.9.0 Preview 2.0 [34329.215.main]). install python 3.9.13 from Microsoft store.

**Comment by StellaHuang95** [comment]
Can you try again with the VS bundled python and latest VS see if it repros?
