### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by kapsalyamova** [microsoft/PTVS#7765]
**Describe the bug**
When I use Microsoft visual studio and run the following command from VS: 
import pandas as pd
I get the following error:
ModuleNotFoundError: No module named 'pandas'

What can be done? I am using Python 3.9 and Visual studio 2022 version. In general, I have an impression that VS is not connected to Python, though I installed Python package to VS? Thanks.

Best regads,
Zhanna
```

**Comment by cwebster-99** [comment]
Hi @kapsalyamova, it seems you might have not installed pandas in your selected Python environment. Try checking out [our tutorial](https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2022) and see if your issue will resolve after following these steps to install the pandas module. 

If you have installed the pandas module, make sure that the environment that you installed pandas in is activated. 

Please reopen the issue, if you are still having trouble!
