### ISSUE TITLE
Some of the file extensions paths registered by VS have errors

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7766]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Some-of-the-file-extensions-paths-regist/10516439)._

---
\[severity:It’s more difficult to complete my work\]  
Such as `.pyproj`, loacted in `HKEY_CLASSES_ROOT\VisualStudio.Launcher.pyproj.2c6bdd5d\DefaultIcon`,should be registered to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\PythonProject.ico`, but has been registered to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Extensions\Microsoft\Python\Core\PythonProject.ico`.

Such as `.py`, loacted in `HKEY_CLASSES_ROOT\VisualStudio.py.2c6bdd5d\DefaultIcon`,should be registered to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\PythonFile.ico`, but has been registered to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Extensions\Microsoft\Python\Core\PythonFile.ico`.

Such as `.vsglog`, loacted in `HKEY_CLASSES_ROOT\VsGraphics.vsglog.2c6bdd5d\DefaultIcon`,should be registered to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Graphics\Debugger\VsGraphicsDebuggerPkg.dll`, but has been registered to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\VsGraphics\VsGraphicsDebuggerPkg.dll`.

Such as `.jsproj`, loacted in `HKEY_CLASSES_ROOT\VisualStudio.jsproj.2c6bdd5d\DefaultIcon`, I do not know where it should be registered to, but the origin path is not existed `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\WebClient\Project System\Microsoft.VisualStudio.JavaScript.Project.dll`.

All those faults will result in being unable to open the specific file or being unable load the file icon. Those might be written by VSInstaller.

---
#### Feedback Bot on 11/15/2023, 06:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
This isn't a PTVS issue, I've directed this to the proper upstream team.
