### ISSUE TITLE
application won't download

### ISSUE THREAD

**Issue by wenicawoods** [microsoft/PTVS#7772]
**Describe your question*
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 17.0.23189.3

System.ObjectDisposedException: Cannot access a disposed object.
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```
**What have you tried?**
[Have you already searched online? What solutions have you tried?]

**Additional context**
[Add any other information or screenshots that would help us provide you with a better answer]

**Comment by StellaHuang95** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. Could you provide more detailed repro steps and sample code if possible so that we can further look at the issue? Thanks!

**Comment by wenicawoods** [comment]
When I try logging in to GitHub it says “ system failure, proxy firewall failure “. Then I have to try it multiple times to login until it works. Once I’m login it will not clone or upload the document code to the system. That message that I sent you pops up. Once I start coding and try to run the document it only runs the code that I recently wrote and not the full script. Sent from my iPhoneOn Dec 4, 2023, at 2:03 PM, Stella ***@***.***> wrote:﻿
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. Could you provide more detailed repro steps and sample code if possible so that we can further look at the issue? Thanks!

**Comment by wenicawoods** [comment]
Hey it happens every time I load the application Sent from my iPhoneOn Dec 12, 2023, at 6:59 PM, Stella ***@***.***> wrote:﻿
Thanks, I will try to repro this. Do you have any conda environment installed and activated for the project you're trying to upload? Does it issue occur consistently, meaning every time you perform a certain action, or is it more sporadic, happening randomly or under specific conditions?

**Comment by StellaHuang95** [comment]
I am still not able to repro the issue with the info you provided. Is your source code available in a public repository? Or could you provide it to us? Can you also provide your activated environment?
