### ISSUE TITLE
Adding Python FastAPI support into new-project modules

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7799]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adding-Python-FastAPI-support-into-new-p/10516349)._

---
FastAPI is a modern, fast, and efficient web framework for building APIs with Python. It provides excellent support for OpenAPI. Now Visual Studio has supported Flask and Django and I think it necessary to add FastAPI support.

Compared to Flask and Django, FastAPI offers several advantages. It is designed to be easy to use, efficient, and flexible, with a focus on building APIs. FastAPI leverages modern Python features such as type hints and async/await syntax, allowing for faster development and better code quality.

FastAPI's popularity has been increasing rapidly due to its performance and developer-friendly features. It offers automatic validation and serialization of request and response data, built-in support for asynchronous operations, and automatic generation of interactive API documentation.

Adding FastAPI support to Visual Studio would provide developers with more options for building high-performance APIs. It would enable them to take advantage of FastAPI's features and benefits, enhancing their productivity and the overall development experience.

I suggest considering the addition of FastAPI support to Visual Studio to cater to the growing demand for this powerful web framework.

---
#### Feedback Bot on 11/15/2023, 11:59 PM: 

(private comment, text removed)

**Comment by bschnurr** [comment]
What kind of support are you suggesting?

Are you working with the FastApi cookie cutter template?
