### ISSUE TITLE
Support up-to-date Python versions and environment management by adding Conda support or Virtualenv/Pipenv/PDM support

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7800]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Support-up-to-date-Python-versions-and-e/10516378)._

---
In Visual Studio Installer, only VERY old version of Python is provided. Python has updated to 3.12 but the provided version is 3.9, which cannot support many new features and is not quite secure if not updated regularly.

Moreover, as Python projects may need different packages and environments, but currnetly Visual Studio doesn't support environment management well. I strongly recommend that adding Conda support into Visual Studio as it is the best tool to manage python environments, especially for Data Science and Scientific Calculation, with many tools including Cudatoolkit, cudnn, and great support for Torch and TensorFlow, which are widely used tools in Machine learning and AI. Moreover, it can manage Python versions easily, by simply inputing `conda create -n $ENV_NAME python=$VERSION` an environment is easily created and versions of python is easily managed.

However, as Conda is designed for data science, it might not be the best tool in other fields, so please, in addition, support all still officially supported Python versions including 3.8, 3.9, 3.10, 3.11, 3.12 in Visual Studio Installer, and provide support for VIrtualenv/Pipenv or the venv coming with Python, to manage environments. Moreover, as many projects use `pyproject.toml`, perhaps supporting PDM is a better, as PDM itself can manage virtual environments. Using a virtual environment can use the needed python version without any conflicts.

Thus I recommend adding environment management support for Python, especially Conda for Python in Data Scienvce field, and provide more python versions and use a proper environment management tool to manage the needed version in a project, no matter a program written in Python or a installable PYPI package/module, which is just greatly supported by PDM.

---
#### Feedback Bot on 11/15/2023, 11:59 PM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Hello, thank you for your feedback. Supporting Python 3.12 is currently being tracked through various work items, such as this one: https://github.com/microsoft/PTVS/issues/7786. Please refer to these work items for the latest updates on Python support. Regarding conda, PTVS already has some support. You can find more information at [this link](https://learn.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2022#conda-environments). If you have any additional suggestions, feel free to let us know. Thanks!
