### ISSUE TITLE
Failed to install Github.Copilot components.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7808]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/90d42b9d-60e3-45fa-acac-d75d783965cf)

**Steps to Reproduce**
 Select these options to install.
![image](https://github.com/microsoft/PTVS/assets/59192491/a0e95727-4418-4439-b164-9d7c37464571)

**Expected behavior**
Install successfully without any error. 

**Additional context and screenshots**
![image](https://github.com/microsoft/PTVS/assets/59192491/720320db-185c-4375-8934-05b2d7dc14fc)

![image](https://github.com/microsoft/PTVS/assets/59192491/79f2c7af-e2a8-4a56-add6-c27ac01f2e11)

**Logs**
[dd_setup_20240119052931_errors.zip](https://github.com/microsoft/PTVS/files/13984717/dd_setup_20240119052931_errors.zip)

**Comment by StellaHuang95** [comment]
This is an upstream issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1942701
