### ISSUE TITLE
Problems regarding COMSPEC and cmd.exe for Python (Extension)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7814]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problems-regarding-COMSPEC-and-cmdexe/10544806)._

---
[severity:I'm unable to use this version]
Hi, Visual Studio will not allow me to use . net to build websites without changing the edit variable for comspec with cmd.exe. The problem is when I try to set it in the edit variable section comspec isn't even a option what should I do?
![image.png](https://aka.ms/dc/image?name=B6e547f6e0da54c82a83171dbbccb68c7638386340443845806_20231219-195404-image.png&tid=6e547f6e0da54c82a83171dbbccb68c7638386340443845806)
![image.png](https://aka.ms/dc/image?name=Bd9a9778850684e23bf58ec00322ad4d3638386341053919879_20231219-195505-image.png&tid=d9a9778850684e23bf58ec00322ad4d3638386341053919879)
![image.png](https://aka.ms/dc/image?name=B2cda217aa8da43aaa4e42ec9f15c2789638386341498185031_20231219-195549-image.png&tid=2cda217aa8da43aaa4e42ec9f15c2789638386341498185031)
nowhere to be found. What do I do?
![image.png](https://aka.ms/dc/image?name=B960259cc804347b7b1e9f3c71664a872638386343736174348_20231219-195930-image.png&tid=960259cc804347b7b1e9f3c71664a872638386343736174348)
This is the Error message I keep getting when I open visual studio.

Thank you for your help.

---
#### Tracy Wang [MSFT] on 12/19/2023, 06:33 PM: 

(private comment, text removed)
#### Frank Martin on 12/20/2023, 06:55 AM: 

(private comment, text removed)
#### Feedback Bot on 12/20/2023, 06:21 PM: 

(private comment, text removed)
#### Feedback Bot on 1/29/2024, 06:05 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for reporting the issue. Were you using Visual Studio or VSCode? The last screenshot seems like a VSCode one? Thanks.
