### ISSUE TITLE
MicroBuild Template for 1ES Template migration

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/PTVS#7815]
We’re a non-microbuild pipeline, so we need to move to the 1ES pipeline template. See Adam's email for details.

Our pipeline yaml is at [https://github.com/microsoft/PTVS/blob/main/azure-pipelines.yml](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FPTVS%2Fblob%2Fmain%2Fazure-pipelines.yml&data=05%7C02%7Cstellahuang%40microsoft.com%7Cdedec2dff6e5420b6d3308dc22ba4d1f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638423431038490308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wafpG1TRUon3n%2Fv%2FoV%2B9RqypiI%2B1p2ZWBYZnougA6pQ%3D&reserved=0)

**Comment by StellaHuang95** [comment]
Do you know if we need to create agent image and agent pool ourselves? @AdamYoblick 

[This doc](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/onboardingesteams/create-agent-pool) says "If you are a product team, there is a chance that your Spoke ES team already manages infrastructure for you."

**Comment by AdamYoblick** [comment]
Almost positive we do not need to manage any pools. Just use the pool we already use I think.

**Comment by StellaHuang95** [comment]
@AdamYoblick I did, but then the build failed because the node version in the image doesn't meet the version requirement. See [the build failure](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9023601&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca&t=b700cb98-6adf-5a7d-1ac8-1351904e01bc).

**Comment by StellaHuang95** [comment]
Update: The Microbuild team is working on updating the VSEngSS-MicroBuild2022-1ES pool to user a newer version of node. The image has been created but they are still working on pushing it to production.

**Comment by StellaHuang95** [comment]
Validate a pipeline after migration: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/migration/validate-migration
