### ISSUE TITLE
error installing vs community and python developmen and i get this error

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7816]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/error-installing-vs-community-and-python/1649118)._

---

Package 'Microsoft.VisualStudio.Log.Resources,version=16.0.28315.86,language=ru-RU' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualStudio.Log.Resources;PackageAction=Install;ReturnCode=0x80096004
    Details
        SHA256 verification for 'payload.vsix' failed. Expected hash: A0B57E65A229F48A2551BD85C12D30578609A9E18194AB100CDB6E5B299BD33F, Actual hash: A39E3C67378357C8C020FC1234ED59EFA0552C36F7F26C9FBD598D47124D977E
    Impacted workloads
        Python development (Microsoft.VisualStudio.Workload.Python,version=16.0.28621.142)
        Visual Studio core editor (Microsoft.VisualStudio.Workload.CoreEditor,version=16.0.28315.86)
    Impacted components
        Connectivity and publishing tools (Microsoft.VisualStudio.Component.Common.Azure.Tools,version=16.0.28315.86)
        JavaScript and TypeScript language support (Microsoft.VisualStudio.Component.JavaScript.TypeScript,version=16.0.28625.61)
        Python language support (Microsoft.Component.PythonTools,version=16.0.28625.61)
        Python miniconda (Microsoft.Component.PythonTools.Miniconda,version=16.0.28625.61,chip=x64)
        Python web support (Microsoft.Component.PythonTools.Web,version=16.0.28517.75)
        Visual Studio core editor (Microsoft.VisualStudio.Component.CoreEditor,version=16.0.28315.86)

---
#### Feedback Bot on 1/28/2022, 00:34 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. We would need more detailed logs to see what's really going on. Can you please try it again and collect more logs by running http://aka.ms/vscollect.exe and uploading %temp%\vslogs.zip. Thank you!😊

**Comment by StellaHuang95** [comment]
If the issue still persists, please reopen with the information requested. Thanks.
