### ISSUE TITLE
I don't see line numbers in my code! )

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7821]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-dont-see-line-numbers-in-my-code-/10576482)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:vs code 2019]
In this IDE, it is possible to configure it so that the line numbers are normally visible, so that next to them, on the left, it is possible to set debug points ?? )

---
#### Feedback Bot on 2/1/2024, 05:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, you can turn on the line numbers by going to Tools -> Options -> Text Editor -> All Languages -> General -> Line Numbers. Please re-open the issue if it doesn't solve your problem. Thanks!
