### ISSUE TITLE
"import xxxxx" without any warnings in the error list. 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7827]
**Describe the bug**

<img width="378" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/6174a7db-50f0-4ef5-a16f-ec033a0fa6e5">

**Steps to Reproduce**

1. Create a Python Application.
2. type ```import xxxxx```.

**Expected behavior**

Displays a green squiggly line under xxxxx and a warning in the error list.

![image](https://github.com/microsoft/PTVS/assets/82852072/67609084-d9af-48bc-98d1-bd3b392708b7)

**Additional context and screenshots**

No green squiggly lines and warnings.

<img width="431" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/0ec59192-2966-4db5-9743-b6a50760c160">

## Logs

<details>

<summary>Output for <code>Pylance</code> in the <code>Output</code> panel 
</summary>

<p>

```
Info: (9784) Pylance language server 2024.2.2 (pyright version 1.1.348, commit cfb1de0c) starting
Info: (9784) Server root directory: file:///c%3A/program%20files/microsoft%20visual%20studio/2022/preview/common7/ide/extensions/microsoft/python/core/pylance/dist
Info: (9784) Starting service instance "PythonApplication3"
Info: Un-registering request handler for 02b1ea61-5009-494e-a1c9-ead895eabc4e failed.
Info: (9784) Found 1 source file
Info: (9784) Background analysis(1) root directory: file:///c%3A/program%20files/microsoft%20visual%20studio/2022/preview/common7/ide/extensions/microsoft/python/core/pylance/dist
Info: (9784) Background analysis(1) started
Info: (9784) Indexer background runner(2) root directory: file:///c%3A/program%20files/microsoft%20visual%20studio/2022/preview/common7/ide/extensions/microsoft/python/core/pylance/dist (index)
Info: (9784) Indexing(2) started
Info: (9784) scanned(2) 14 files over 1 exec env
Info: (9784) indexed(2) 5 files over 1 exec env
Info: (9784) Indexing finished(2).

```

</p>
</details>

**Comment by StellaHuang95** [comment]
#7827 , #7830 , #7831 , #7832 repro with pylance version >= 2023.12.103, which indicates the bugs might be caused by one of the pyrx commits from 1/4/2024 - 1/10/2024.

**Comment by StellaHuang95** [comment]
The commit that caused all these regressions has been narrowed down to https://github.com/microsoft/pyrx/commit/bad397c6c7a04e40ec917e3da412cd7b04e74f2d
