### ISSUE TITLE
Intellisense working on all assemblies but one!

### ISSUE THREAD

**Issue by andygraham** [Microsoft/PTVS#783]
VS desktop Express 2013, IronPython 2.7.5, PTVS 2.2

I have several assemblies referenced in my IronPython project. One local assembly in this project, IronPy.dll, which is on the search path '.', the others are from the GAC.

![085248](https://cloud.githubusercontent.com/assets/3984778/9435442/d316f5b4-4a3f-11e5-93b9-02b9c55c5dde.png)

Intellisense works on all except Microsoft.VisualBasic.Interaction. The project does run properly and I can see no difference between the treatment of this dll and the others.

![085200](https://cloud.githubusercontent.com/assets/3984778/9435452/eff88e5e-4a3f-11e5-9235-7fe11231fc9b.png)

I have tried changing the clr reference to clr.AddReference('Microsoft.VisualBasic.Interaction') which doesn't work and causes a run time error.

**Comment by andygraham** [comment]
Probably only to be expected but the latest build "PTVS Dev 2015-08-21 VS 2013.msi" also exhibits this problem.

**Comment by zooba** [comment]
I was kind of hoping it would fix it, as we've added a fix for a few IronPython issues.

I suspect there's something special about the VB assembly here. Currently working through a critical fix we need, but then I'll take a look.

**Comment by zooba** [comment]
It looks like the problem is that `Interaction` is a class and not a namespace. The following is probably what you'll want:

```python
import Microsoft.VisualBasic
InputBox = Microsoft.VisualBasic.Interaction.InputBox

# alternatively
from Microsoft.VisualBasic import Interaction
...
value = Interaction.InputBox(...)
```

**Comment by andygraham** [comment]
Aha! I didn't notice that, thanks for pointing it out. As I have only ever used that aAssembly in C#  because it has the useful when debugging InputBox I've never really looked at it closely and wrongly assumed Interaction was a namespace.
