### ISSUE TITLE
The type information displayed wrong for sys.exc_info with the latest typeshed. 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7832]
**Environment**

<img width="381" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/256f4e50-72f2-4958-bb24-49a9a30a600d">

**Steps to Reproduce** 

1. Ensure the option is unchecked by default 
-  Check there is type information in below example

 ![image](https://user-images.githubusercontent.com/59192491/224633668-46593e56-c326-45e6-85f6-2d81c69100de.png)

2. Custom Typeshed path 
-  git clone https://github.com/python/typeshed, enter the local path on disk where you cloned the repository 

![image](https://user-images.githubusercontent.com/82852072/220799719-4eb286a9-0141-4664-bd5d-825251788937.png)

-  Add `from typing import Optional, Tuple, Type` to ```__init__.pyi ```
-  open ```typeshed/stdlib/sys/__init__.pyi```

 ```
 def exc_info() -> OptExcInfo: ...
```
 
 **With this instead:**

 ```
 def exc_info() -> Tuple[Optional[Type[BaseException]],
 		        Optional[BaseException],
 		        Optional[_version_info]]: …
```

 **Expected behavior** 

It should now report e3 as being a version info instance

![image](https://user-images.githubusercontent.com/59192491/224634990-06456097-190c-4426-8223-017f884b5fff.png)
 
**Actual behavior** 

The type information has not changed with latest typeshed.

<img width="168" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/575eaf3c-b3ab-42ef-8dbd-8d823f2fdcf2">

**Comment by StellaHuang95** [comment]
#7827 , #7830 , #7831 , #7832 repro with pylance version >= 2023.12.103, which indicates the bugs might be caused by one of the pyrx commits from 1/4/2024 - 1/10/2024.

**Comment by StellaHuang95** [comment]
The commit that caused all these regressions has been narrowed down to https://github.com/microsoft/pyrx/commit/bad397c6c7a04e40ec917e3da412cd7b04e74f2d
