### ISSUE TITLE
Exception thrown in blank bottle web project.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7833]
**Describe the bug**

<img width="329" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/44c1984a-1b00-400f-975f-424f9c3c6d32">

**Steps to Reproduce**

1. Create a Blank Bottle Web Project.
2. Create virtual environment( Make sure Bottle was successfully installed ).
3. Start Debugging

**Expected behavior**

No error.

**Additional context and screenshots**

Throw an exception.

<img width="336" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/6ee6126d-e379-4b30-9054-cd55c476ab39">

**Comment by StellaHuang95** [comment]
This problem isn't specific to PTVS alone, as I've been able to replicate it in multiple editors. It could possibly be an issue within the bottle framework itself. I wouldn't be too concerned about it as it doesn't seem to impact debugging, and no users have raised complaints about it. I'll go ahead and mark it as closed unless we hear from a user.
