### ISSUE TITLE
Enable pulling pre-release pylance into PTVS builds

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/PTVS#7835]
**Goal:**
Create vsix that uses the latest prerelease Pylance bits for CTI's non-sign off testing.

**Implementation:**
Set up some configurable build options that can pull pylance from the internal feed instead of the stable one, create and upload vsix as a build artifact and CTI should be able to test that way. 

** Progress **

Bundling into VS
- [x] Create a VS bootstrapper with our payload injected (see commented step in PTVS pipeline)
- [x] Publish the bootstrapper as a build artifact
- [x] Make sure CTI can consume the bootstrapper 

The bootstrapper work is complete with https://github.com/microsoft/PTVS/pull/7867.
It can be found in the pipeline artifact called "bootstrapper".

Getting pre-release pylance
- [x] Add the prerelease flag to PreBuild.ps1. This is ONLY used for tagging the build. The version is still used to download pylance.
- [x] Tag the build with "Pylance-Stable" for non-prerelease builds only
- [x] Change release pipeline trigger, add "Pylance-Stable" tag filter
- [x] Change pylance release.yml to launch PTVS pipeline on ALL releases, pass in pre-release flag when appropriate

**Comment by StellaHuang95** [comment]
**Suggestion from Erik:**

"Regarding publishing Pylance prerelease builds to npm, I think you said that Adam had suggested having two separate feeds (stable and prerelease). But I think we can achieve the same thing with tags. If you look at the raw feed json (see links below), you can see a list of dist-tags at the top which point to the latest version that was published with each tag.
 
The DevDiv feed has "latest" (which I believe is the latest version published with no tag, aka stable), "pre", and "dev" (which seems to be old/dead), whereas the msft_consumption feed just has "latest" because we've never published prerelease builds there.
 
I think if we started publishing prerelease builds using the "pre" tag, PTVS could update its logic to pull either "latest" or latest "pre" and accomplish the same thing with less work. At least it would be less work on Pylance's side.

DevDiv: [devdiv.pkgs.visualstudio.com/_packaging/Pylance/npm/registry/@pylance/pylance](https://devdiv.pkgs.visualstudio.com/_packaging/Pylance/npm/registry/@pylance/pylance)
msft_consumption: [pkgs.dev.azure.com/azure-public/vside/_packaging/msft_consumption/npm/registry/@pylance/pylance](https://pkgs.dev.azure.com/azure-public/vside/_packaging/msft_consumption/npm/registry/@pylance/pylance)"

**Comment by AdamYoblick** [comment]
That would definitely be less work for everyone. Because then I'm just changing the version string being pulled, which is what we already do when overriding to an older version when specified.

**Comment by StellaHuang95** [comment]
We will now start publishing and tagging prerelease pylance to the feed. See https://github.com/microsoft/pyrx/pull/4735

**Comment by AdamYoblick** [comment]
Instructions on how to pull consume PTVS with pre-release pylance are at https://microsoft.sharepoint.com/teams/python/_layouts/15/Doc.aspx?sourcedoc={30d33826-9f98-4d3e-890e-b7d198bbbcbe}&action=edit&wd=target%28Python%20VS%2FDev%20Docs.one%7Cd7206ce2-cf40-437b-8ce9-1e55f4bc2f44%2FTest%20PTVS%20builds%7C8042c592-5c24-49e8-a6db-06a82acf33b8%2F%29&wdorigin=NavigationUrl
