### ISSUE TITLE
Interactive Window not working

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7839]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Interactive-Window-not-working/10587115)._

---
[severity:It's more difficult to complete my work]
Using a python environment on a newly install Visual Studio 2022 community edition. I am unable to run any statements inside of my Interactive Window. If I use the commands such as $help then it generates the output but something as simple as print(4), leaves me with a spinning wheel. 

---
#### Feedback Bot on 2/18/2024, 05:30 PM: 

(private comment, text removed)
#### Chris Fitch on 2/20/2024, 07:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thanks for your report. This is a dupe of https://github.com/microsoft/PTVS/issues/7219 and https://github.com/microsoft/PTVS/issues/7118. Please track these 2 issues for progress. Thank you!

**Comment by DukeBot18** [comment]
I am still waiting on a solution for this. I just continue to get a loading spinner when attempting any commands in the window

**Comment by bobjs1** [comment]
I just installed today and am also having the identical issue
