### ISSUE TITLE
String layout issues in code

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7840]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/String-layout-issues-in-code/10599495)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:vs code 2019]
In VS code 2019, if I needed to make lines of my code more compact, I just pressed "Alt + Z" and the lines of my code became more compact! or I could select this command in the "View" tab and the same thing happened! In Visual Studio 2022 Preview, I unfortunately did not find this feature!! )

---
#### Feedback Bot on 2/26/2024, 00:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for your issue. Did you customize keyboard shortcuts in Visual Studio through the Options dialog? What is your `alt+z` mapped to? It's not the default shortcuts in VS. See https://learn.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2019. Thanks.

**Comment by Worker14** [comment]
я установил тогда русскоязычную версию vs code 2019 и ещё дополнительно сниппет родной от майкрософта , переводчик , и в этом переводчике выбрал и установил русскоязычный пакет , так как даже в русскоязычной версии vs code 2019 кое-что было на английском ( я предпочитаю разговаривать , в основном на русском языке ) , и насколько я помню - и до установки переводчика , и после сочетание клавиш "alt + z" было настроено по-умолчанию , и прекрасно работало , я сам его специально не устанавливал , и не настраивал . )

**Comment by Worker14** [comment]
сама функция сочетания клавиш "alt + z" в vs code 2019 , заключается в том чтобы длинные строчки кода , которые при обычных настройках выходят из видимой зоны программиста , размещать более компактно , в видимой зоне на мониторе ! )

**Comment by StellaHuang95** [comment]
Are you talking about the zoom in/out feature? Can you try the following keyboard shortcuts:

Zoom In: Ctrl + + (Press and hold the Ctrl key, then press the plus key)
Zoom Out: Ctrl + - (Press and hold the Ctrl key, then press the minus key)
