### ISSUE TITLE
Please update python 3.9 to python 3.10 or 3.11 in visual studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7841]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-update-python-39-to-python-310-/10585941)._

---
Python 3.9 is out of date and it is still being used in visual studio 2022. I think it should be updated since it is now unsupported.

---
#### Feedback Bot on 2/18/2024, 05:04 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
This issue is closed as a duplicate. Please use the linked issue (https://github.com/microsoft/PTVS/issues/7769) for all updates.
