### ISSUE TITLE
Added wrong python reference in project setup and now get error

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7846]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Added-wrong-python-reference-in-project-/10601702)._

---
New -> VisualGDB project -> ESP32/ESP8266 IDF/ADF Project Wizard ->
             Project Type :: CMake
             Toolchain     :: Toolchain: Esp32 in C:\SysGCC\esp32
                                    Device : ESP32C6

Get Failed to initialize virtual Python environment

The problem after adding first project as described above but added required reference to python (was not previously setup) and I pointed it to the wrong location (one I had previously setup in "C:\msys32\mingw32\bin\python.exe"

This caused the following log to be printed:

Run "C:\msys32\mingw32\bin\python.exe C:\SysGCC\esp32\esp-idf/v5.1\tools\idf_tools.py install-python-env" in directory "" on local computer
--------------------------
  File "C:\SysGCC\esp32\esp-idf/v5.1\tools\idf_tools.py", line 458
    info(f'Downloading {url}')
                            ^
SyntaxError: invalid syntax
--------------------------
Command exited with code 1

I can not figure out how to undo the error.

---
#### Rex Brown on 2/26/2024, 02:17 PM: 

(private comment, text removed)
#### Rex Brown on 2/26/2024, 02:22 PM: 

(private comment, text removed)
#### Feedback Bot on 2/26/2024, 08:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by RexLBrownSr** [comment]
I found an option in VisualStudio that allows modifying the path and this is no longer an issue:
Debug -> options -> VisualGDB/General/Tools:Python directory

**Comment by StellaHuang95** [comment]
Glad to hear that!
