### ISSUE TITLE
Fail to run test in Pytest.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7853]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/217d37dd-8191-49d3-8386-a34240ae1511)

Python from VS

**Steps to Reproduce**

1. Create Python Application Project.
2. Add test_1.py file with code
```
def test_passing():
    assert 42 == 42
def test_failure():
    assert 42 == -13
```
3. Set Test framework as "pytest" in python project properties page.
4. Open TE with the Test > Windows > Test Explorer menu command
5. Run Tests.

**Expected behavior**

Tests can be run successfully. 

**Additional context and screenshots**

The test was skipped.

![image](https://github.com/microsoft/PTVS/assets/82852072/04689d21-4dde-4df0-92dd-5a64301b83d3)

## Logs

<details>

<summary>Output for <code>General</code> in the <code>Output</code> panel 
</summary>

<p>

```
========== Starting test run ==========
cd C:\Users\vting\source\repos\PythonApplication6\PythonApplication6\
set PYTHONPATH=C:\Users\vting\source\repos\PythonApplication6\PythonApplication6\
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe" "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\testlauncher.py" C:\Users\vting\source\repos\PythonApplication6\PythonApplication6\ pytest "" 0 "" "" dummyfilename .\test_1.py::test_failure .\test_1.py::test_passing --junitxml=C:\Users\vting\source\repos\PythonApplication6\TestResults\junitresults_9bc9d3ef-2301-4c1f-a1be-cb0ecd8ad0f4.xml --rootdir=C:\Users\vting\source\repos\PythonApplication6\PythonApplication6 -o junit_logging=all -o junit_family=xunit1
Traceback (most recent call last):
  File "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\testlauncher.py", line 189, in <module>
    main()
  File "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\testlauncher.py", line 30, in main
    run(testRunner, coverage_file, test_file, args)
  File "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\testlauncher.py", line 119, in run
    patch_translate_non_printable()
  File "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PREVIEW\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\testlauncher.py", line 136, in patch_translate_non_printable
    translate_non_printable =  getattr(_pytest.compat, "_translate_non_printable")
AttributeError: module '_pytest.compat' has no attribute '_translate_non_printable'
Results for pytest not found C:\Users\vting\source\repos\PythonApplication6\TestResults\junitresults_9bc9d3ef-2301-4c1f-a1be-cb0ecd8ad0f4.xml
========== Test run finished: 2 Tests (0 Passed, 0 Failed, 2 Skipped) run in 272 ms ==========

```
</p>

**Comment by StellaHuang95** [comment]
If you enter `pytest==8.0.2` and run the `pip install`, the error should be gone. It's an issue within that pytest version. ![image](https://github.com/microsoft/PTVS/assets/100439259/2be89567-de95-47e3-b64d-d52817ec0629)

**Comment by The-Compiler** [comment]
As clearly shown in the screenshotted stacktrace, this is an issue with PTVS accessing pytest private API which has moved. It should not do that at all ideally, but if it does, it's not pytest's fault if things break - that's why it's private API in the first place.
