### ISSUE TITLE
No response after clicking "Add to Source Control" button.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7862]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/66081416-146e-4f81-95b2-eccd5cb52b1d)

**Steps to Reproduce**
1. Go to File -> Add to Source Control
![image](https://github.com/microsoft/PTVS/assets/59192491/9d291c94-f647-45a8-9a16-1d226cb639bd)

Or on the screen of the lower right corner, click Add to Source Control -> Git
![image](https://github.com/microsoft/PTVS/assets/59192491/8a78e0e3-a2ba-45f2-a63b-9c85129e50c0)

**Additional context and screenshots**
No response after clicking "Add to Source Control" button and an error message display on the Output window
`Could not load file or assembly 'Octokit, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0be8860aee462442' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by StellaHuang95** [comment]
This is an upstream issue, it's tracked here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2010084
