### ISSUE TITLE
The "Add to source control" button is missing.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7871]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/f9f428d6-3903-4d96-bb84-7f9ea68758a2)

**Steps to Reproduce**

1. Launch VS.
2. The "Add to Source Control" button is in the lower right corner.

![image](https://user-images.githubusercontent.com/82852072/132639971-cb42ac5e-3847-408b-b4af-dd24fd385434.png)

**Additional context and screenshots**

The "Add to source control" button is missing.

![image](https://github.com/microsoft/PTVS/assets/82852072/8af10c09-6485-47c2-b7e4-aea8281e05ab)

**Comment by StellaHuang95** [comment]
It's an upstream issue, which is tracked here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2033057
