### ISSUE TITLE
An error pops up when reopen Properties file.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7874]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/211d6ff0-a6e0-4bc3-b21f-2a30c9950843)

**Steps to Reproduce**
1.Open a PythonApplication project.
2.Open properties and save it
![image](https://github.com/microsoft/PTVS/assets/59192491/ddb94089-6850-4ce9-9fda-cdb685c4d47f)
3.Close the VS and reopen the VS

**Expected behavior**
The properties page displayed successfully without any error.

**Additional context and screenshots**
An error pops up.
![image](https://github.com/microsoft/PTVS/assets/59192491/8b7684a1-a412-44b4-a99f-69f6d810b0b0)

**Comment by StellaHuang95** [comment]
Seems like a bug in Solution Experience, reported the bug here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1575652
