### ISSUE TITLE
The Quick Action icon for 'remove unused imports' only appear if the code is selected.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7877]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/c3fbce15-5a80-49c1-8981-5b3655d2711f)

**Steps to Reproduce**
1. Create a Python Application project
2. Input some code
```
import array; import glob; import math
print(math.cos(10))
```
3. Move the cursor to a one line
4. The Quick Action icon should appear in front of this line.

**Expected behavior**

![image](https://github.com/microsoft/PTVS/assets/82852072/71d9027b-b76a-4c7e-a620-c0c6bb5cf51e)

**Additional context and screenshots**

![image](https://github.com/microsoft/PTVS/assets/82852072/b20df0af-bb92-4987-ae19-d4acfec867aa)

You must select this line of code for it to appear.

![remove](https://github.com/microsoft/PTVS/assets/82852072/aa43a9c9-9345-4a6c-96c2-3b28237c5a93)

**Comment by linette-zyy** [comment]
In today's build
![image](https://github.com/microsoft/PTVS/assets/59192491/770059a3-fb11-44f6-89b7-964b10c15097)
The Quick Action icon for 'Extract method' only appear if the code is selected
![image](https://github.com/microsoft/PTVS/assets/59192491/57a95f77-0916-4c42-809b-0b7f96218c70)

**Comment by StellaHuang95** [comment]
I can't repro this first one regarding `remove unused imports`. As long as the cursor is on the same line it just shows up for me. For the `extract method` one, it's expected to have certain range selected to trigger the code action.

I am on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.11.0 Preview 2.0 [34914.235.main]. Can you verify? @ttSpace

**Comment by ttSpace** [comment]
@StellaHuang95 In today's build, I can repro it.

![image](https://github.com/microsoft/PTVS/assets/82852072/de439915-3aed-401c-b2b2-b61c6576a3ce)

The Quick Action icon for ```remove unused imports``` only appear if the code is selected.

![image](https://github.com/microsoft/PTVS/assets/82852072/0158dc37-e2e3-4903-8329-02bc5a582b93)

For the```Extract method``` one, Only appear if the code is selected. But when I tested another code, the icon did not appear when selecting a single line or more than a single line.

![image](https://github.com/microsoft/PTVS/assets/82852072/dd84455e-5de0-4d71-85c1-c345907446d8)

![ExtraMethod](https://github.com/microsoft/PTVS/assets/82852072/6527d385-1752-44a4-8722-c80b8c561e7d)

**Sample Code**

<details>
<p>

```
from math import cos, radians
	
# Create a string with spaces proportional to a cosine of x in degrees
def make_dot_string(x):
	rad = radians(x)                             # cos works with radians
	numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	return st
	
def main():
	for i in range(0, 1800, 12):
		s = make_dot_string(i)
		print(s)
	
main()
```
</p>

**Comment by StellaHuang95** [comment]
can't repro anymore


![Image](https://github.com/user-attachments/assets/cff9a6d5-95e2-4dc5-8ddc-49f9bfb74438)
