### ISSUE TITLE
Django on visual studio 2022 community

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7878]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Django-on-visual-studio-2022-community/10640819)._

---
When I created a Djongo webproject using visual studio community 2022 and able to run perfectly on my pc. However when i transfer this package to another pc. It is not able to run and realize the files in the Env folder are gone. Try to reinstall using the requirement.txt but often get an error "no pip installed". Could someone tell me is this normal whenever we transfer the package to anohter pc you will have to delete off the Env folder and recreate the Environment again with all the package reinstallation. Is this how the visual studio IDE work. Thanks.

---
#### Alison Jin [MSFT] on 4/18/2024, 01:50 AM: 

(private comment, text removed)
#### CL Yeoh on 4/18/2024, 01:58 AM: 

(private comment, text removed)
#### Feedback Bot on 4/18/2024, 06:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by gramster** [comment]
User solved the issue themselves:

"I just manage to find out all these have to do with a file call pyvenv.cfg in the env folder. When you transfer the whole package to another computer you will have to update the home:python path for that computer in this pyvenv.cfg file manually in order for the package to work. "
