### ISSUE TITLE
Enable inlay hints in Visual Studio

### ISSUE THREAD

**Issue by MariaSolOs** [microsoft/PTVS#7888]
**Describe the feature you are requesting**
Visual Studio now has support for inlay hints via LSP, so given that the Python serves has support for these, it would be nice to enable them in Visual Studio.

**Reasons for requesting this feature**
It would better align with the language service experience in other editors (e.g. VS Code).

**Additional context**
TypeScript is now using LSP for their inlay hints in Visual Studio, and Razor is also using them to provide C# inlay hints in script blocks: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#inlay-hints-for-c-code-in-razor-files

**Comment by StellaHuang95** [comment]
@MariaSolOs Thanks for reaching out. Are we only looking to display the inlay hints, or are you anticipating a behavior that's more consistent with VS Code, where users can double-click the inlay hints in the editor to insert into their code?

**Comment by MariaSolOs** [comment]
> @MariaSolOs Thanks for reaching out. Are we only looking to display the inlay hints, or are you anticipating a behavior that's more consistent with VS Code, where users can double-click the inlay hints in the editor to insert into their code? What do other languages in VS currently support?

The plan is to support the same level of interactivity that VS Code has (AFAIK that’s part of the editor roadmap).
