### ISSUE TITLE
Problem creates "Search Path" inside Python Project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7896]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Problem-creates-Search-Path-inside-Pyt/10646427)._

---
[severity:It bothers me. A fix would be nice]
![image.png](https://aka.ms/dc/image?name=B1fe1c97fd14642ceba32bddcf8a66027638495830990213158_20240424-221818-image.png&tid=1fe1c97fd14642ceba32bddcf8a66027638495830990213158)

Look at scr.shot.
Path creates as relative from ProjDir. 
\\.virtualenvs is %userprofile%\\.virtualenvs
ProjDir is %userprofile%\source\repos\MyProj

1. i create shortcut (on Desktop) to MyProj
2. i create symlink (on Desktop) to MyProj

If i open MyProj folder with shortcut - "Search path" work (if relative path looks like on scr.shot).
If i open MyProj folder with symlink - "Search path" not work (if relative path looks like on scr.shot).

Why it happen?
Because:
- shortcut is %userprofile%\source\repos\MyProj
- symlink is %userprofile%\Desktop\MyProj

I think create "Search path" as relative is not good idea.

PS
Interesting.
How VS create relative "Search path" if \\.virtualenvs place on another disk? ;)

---
#### Feedback Bot on 4/24/2024, 07:18 PM: 

(private comment, text removed)
#### Feedback Bot on 4/24/2024, 07:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thanks for reporting the issue. The screenshot attached is corrupted, could you please share it again?

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
