### ISSUE TITLE
Launch Python Profiling,the VSP file always shows loading

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7905]
Environment
![image](https://github.com/microsoft/PTVS/assets/59192491/8ad8b985-2027-421b-86d2-37654aaf38b4)

**Steps to Reproduce**
1.Create python application project and add "Lib\test\pythoninfo.py" and set as Startup File
2.Debug> Launch Python Profiling
3.Press any key to continue

**Expected behavior**
The VSP file displays content normally.

**Additional context and screenshots**
The VSP file always shows loading.
![image](https://github.com/microsoft/PTVS/assets/59192491/b0fc4d94-5575-43ca-a381-53da249bb9ab)

**Comment by StellaHuang95** [comment]
@AdamYoblick Is this deprecated already?

**Comment by AdamYoblick** [comment]
> @AdamYoblick Is this deprecated already?

Technically no, vsp should still be supported. Let me reach out to the VS team.

**Comment by AdamYoblick** [comment]
@linette-zyy What version of python did you have installed for this?

**Comment by AdamYoblick** [comment]
@linette-zyy Also can you please provide the pythoninfo.py file you mentioned so we can use it to troubleshoot?

**Comment by linette-zyy** [comment]
@AdamYoblick Python install from workload, the version in Python3.9
The pythoninfo.py file  is contained in the annex.
[file.zip](https://github.com/microsoft/PTVS/files/15398462/file.zip)

**Comment by StellaHuang95** [comment]
I can repro this one. The .vsp file is created but just the UI just hangs on `Preparing data. xxx`.

**Comment by AdamYoblick** [comment]
Patrick Nelson would be the one from the VS team that can help troubleshoot this. But he just went on PTO :)

**Comment by StellaHuang95** [comment]
I can't repro this anymore in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.12.0 Preview 1.0 [35114.17.main]
