### ISSUE TITLE
Without Javascript completions in a <script> section.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7908]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/9a88436d-8c4b-431c-bc8b-0f42f6528ed0)
 We used the pre-release pylance to test.

**Steps to Reproduce**
1. In a "Django Web Project", validate html completions in app/about.html:
2. Javascript completions in a <script> section.
Example define a int variable myvariable:
![image](https://github.com/microsoft/PTVS/assets/59192491/e253473c-1622-4105-ae72-19cc7799a23c)

**Expected behavior**
Javascript completions in a <script> section.

**Actual result**
Without Javascript completions in a <script> section.
![image](https://github.com/microsoft/PTVS/assets/59192491/ebad0282-93ab-4a4d-8995-cf9c0be0f701)

**Comment by StellaHuang95** [comment]
Does repro for me in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview
Version 17.11.0 Preview 2.0 [34914.235.main]. Can you verify?

**Comment by ttSpace** [comment]
@StellaHuang95 I cannot repro in today's build.

![image](https://github.com/microsoft/PTVS/assets/82852072/665a03c4-a140-48be-80a3-a70c4326e48c)

![image](https://github.com/microsoft/PTVS/assets/82852072/eaa729f4-8400-4aae-90b1-56e2aeeeada5)
