### ISSUE TITLE
Inconvenient Behavior with Enter Key in Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7911]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Inconvenient-Behavior-with-Enter-Key-in-/10657473)._

---
[severity:It bothers me. A fix would be nice]
When using the `Enter` key in Python editor, there is inconvenient behavior that differs from C# editor. In Python, pressing Enter adds spaces on a new line, whereas in C#, this does not occur. This creates inconvenience and complicates code editing. I constantly have to manually remove these spaces.

**Steps to Reproduce the Issue:**

- Open a Python editor.
- Write code that starts not from the beginning of the line but after a few spaces.
- Press the Enter key.
- Notice that extra spaces are added on a new line after pressing Enter (they are visible when selecting the entire code).

**Watch the attached video for a visual demonstration:**
- download [Video.wmv.zip](https://aka.ms/dc/file?name=Bc9e17ff9f6b34c1d99a2892fc70100ca638511319801308359_Video.wmv.zip&tid=c9e17ff9f6b34c1d99a2892fc70100ca638511319801308359)
- or view on [Youtube](https://youtu.be/Jxduf3-Jyz8)

**Expected Behavior:**
Pressing Enter should not automatically add spaces on a new line, as observed in the Python editor. The behavior should match that of the C# editor.

**Explanation of the Issue:**
The problem leads to the following undesirable consequences:

1. Pressing the backspace key adds spaces to the end of the previous line, which can distort the intended formatting of the code.
2. The constant appearance and disappearance of spaces create more differences in code versions (Git), leading to frequent code merges and conflicts.
3. This behavior complicates code editing and readability, making it harder for developers to maintain and collaborate on projects effectively.

---
#### Feedback Bot on 5/12/2024, 07:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for your issue. In Python, indentation is used to define the structure of code blocks, such as loops, conditional statements, and function definitions. Incorrect indentation can lead to syntax errors or alter the logic of your code.

In C#, indentation is not required for the compiler to understand the structure of your code, as it uses curly braces `{}` to define code blocks.

But that said, you can still disable smart indentation by going to Options -> Text Editor -> Python -> Tabs and turn off the indenting there.
