### ISSUE TITLE
Every time the code in the python environment is entered, an error will be reported when the output Chinese is output

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7914]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Every-time-the-code-in-the-python-enviro/10661418)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.9]
说是要加个前缀声明，但每次这样过于麻烦，而且没有效果，希望把python环境下的文件编码默认是utf-8的模式，降低新手使用vs的操作难度
SyntaxError: Non-UTF-8 code starting with '\xc4' in file D:\代码_project\PythonApplication1\PythonApplication1.py on line 4, but no encoding declared;

---
#### Feedback Bot on 5/19/2024, 08:12 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. To save in UTF-8, you can navigate to File -> Save As -> click the dropdown button next to Save, choose save with encoding -> choose UTF-8 and re-run the script? Please re-open the ticket if that doesn't answer your question, thanks!
