### ISSUE TITLE
VSStudio Community 2022 version 17.10.0 not backward compatible with NVIDIA CUDA 11.8

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7915]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VSStudio-Community-2022-version-17100-/10664619)._

---
[regression] [worked-in:17.7.5]
I've been trying at great length to build https://github.com/NVIDIA/VideoProcessingFramework with Python 3.10 and CUDA 11.8 after having upgraded to VSS 17.10.0, but nvcc will not work with this version.

---
#### Feedback Bot on 5/22/2024, 10:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Is this the same issue you're encountering? https://developercommunity.visualstudio.com/t/VS-2022-1710-C-build-tools-144019/10668943. Please see [response](https://developercommunity.visualstudio.com/t/VS-2022-1710-C-build-tools-144019/10668943#T-N10669571) from the team. If it's not the same issue, we will need more detailed repro steps and sample code to repro your issue.
