### ISSUE TITLE
[LiveShare] It shows empty windows after right click and choose "Go to definition" on customized module.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7925]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/dc27ba11-d678-46a8-b283-bdfb8a97cf55)

**Steps to Reproduce**
1. Create a new Python application
2. Open Live Share, make connection between host and client.
3. Input some codes
![image](https://github.com/microsoft/PTVS/assets/59192491/f08457e6-bb44-4c35-a10e-23e505d55470)
4. Hovering the mouse to "make_dot_string" and right click, then choose go to definition
![image](https://github.com/microsoft/PTVS/assets/59192491/6cc785a3-7ec9-4f07-bea5-a75745529e73)
5. Observes
	
**Expected behavior**
It opened a new window and show the definition

**Additional context and screenshots**
It shows empty windows.
![image](https://github.com/microsoft/PTVS/assets/59192491/688d520b-283d-4388-954d-dbdb1f7361ad)

And this issue always occurred on the first connected. Reconnected is not repro.

**Comment by StellaHuang95** [comment]
I couldn't repro on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.11.0 Preview 3.0 [35010.243.main]. This is when you go to File -> Start Live Share Session and do go to def on the function?

**Comment by StellaHuang95** [comment]
@linette-zyy does it still repro?

**Comment by linette-zyy** [comment]
@StellaHuang95 
I found this issue is not repro on this environment.
![image](https://github.com/microsoft/PTVS/assets/59192491/754bae6d-300a-4566-ab2c-f425a41e9c52)
