### ISSUE TITLE
When importing, IntelliSense doesn't seem to cover some of the Standard Library modules

### ISSUE THREAD

**Issue by miguelmartins1987** [Microsoft/PTVS#793]
When creating a new Python console application and typing "import" (no quotes), followed by a space, several modules are shown as possibilities to import, as expected. However, some of the Standard Library modules appear to not be listed, such as "argparse", "mutex" and "os".

The "Refresh DB" button under the Python Environments window does not seem to affect this issue.

![screenshot_1](https://cloud.githubusercontent.com/assets/232489/9504307/d098027e-4c33-11e5-899a-d89243b8b979.png)

**Comment by zooba** [comment]
It seems you have a corrupt completion DB, or perhaps Python install (you shouldn't have zero modules in the standard library).

Can you go to Tools, Python Tools, Diagnostic Info and copy the output into a [gist](https://gist.github.com)? We may be able to spot what's not working from that.

**Comment by miguelmartins1987** [comment]
Here. Hopefully it should help: https://gist.github.com/miguelmartins1987/cb4054882f4cfd4e6951

**Comment by zooba** [comment]
Unfortunately, it was refreshing when you took that log and so there's no helpful info in it.

The file at `'C:\Users\Miguel Martins\AppData\Local\Python Tools\CompletionDB\14.0\2af0f10d-7135-4994-9156-5d01c9c11b7e\2.7\AnalysisLog.txt` will be most interesting - everything else that I can see in the log looks file.

**Comment by miguelmartins1987** [comment]
Looks like it works all of a sudden... Was this perhaps just a matter of letting the completion DB fully refresh?

Here's the AnalysisLog.txt for completion sake, though I suppose this is a non-issue at this point: https://gist.github.com/miguelmartins1987/4e275c5afe240afbe38d

**Comment by zooba** [comment]
Guess it was. If it doesn't complete then we don't have full information to display - the modules you see by default are a very minimal subset that covers CPython 2.x, CPython 3.x and IronPython, and isn't especially useful for coding.

We have some ideas in the works to improve this, but ultimately it's just a matter of having to wait for it to finish and dealing with limited information until then.
