### ISSUE TITLE
Unable to select any environment in the toolbar combo box.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7932]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/e11267ba-a58a-4f3e-b75d-0c3a3ffb4bb8)

**Steps to Reproduce**

1. Open a folder.
2. Add a python file.
3. Select any environment in the toolbar combo box.

**Expected behavior**

The environment was switched successfully.

**Additional context and screenshots**

Cannot select any environment in toolbar combo box and no other environments are shown.

![image](https://github.com/microsoft/PTVS/assets/82852072/62bf5653-7053-4ccc-bc40-594f46bfabec)

![image](https://github.com/microsoft/PTVS/assets/82852072/1eb15938-865f-4cc9-903c-5456610c6a24)

**Comment by StellaHuang95** [comment]
After discussing with the team, we've decided that issues identified by CTI on older branches, where [changes](https://github.com/microsoft/PTVS/issues/7921) were made to the Python version, will be closed if they do not reproduce in the latest version of PTVS, unless they are security or critical issues.
