### ISSUE TITLE
Unable to display the Property page.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7933]
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/56417bf4-9f72-4853-87ea-73963d1c477f)

**Steps to Reproduce**

1. Create a Python Application project
2. Open properties.

**Expected behavior**

The properties page was displayed successfully.

![image](https://github.com/microsoft/PTVS/assets/82852072/84d1368f-1a4a-47a0-ba65-33fa4799e765)

**Additional context and screenshots**

Unable to display the property page. 

![image](https://github.com/microsoft/PTVS/assets/82852072/88604de7-a436-4ff6-a7e0-b0bca0e4326a)

**Comment by StellaHuang95** [comment]
After discussing with the team, we've decided that issues identified by CTI on older branches, where [changes](https://github.com/microsoft/PTVS/issues/7921) were made to the Python version, will be closed if they do not reproduce in the latest version of PTVS, unless they are security or critical issues.
