### ISSUE TITLE
IntelliSense does not work when type @.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7934]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/b61d77d5-2cd0-449b-8b14-95118d00fe05)

**Steps to Reproduce**
1.Enter the code as shown in the image

**Expected behavior**
![image](https://github.com/microsoft/PTVS/assets/59192491/0d49de59-c597-411a-8790-6371bbd74beb)

**Additional context and screenshots**
IntelliSense does not work when type @.
![image](https://github.com/microsoft/PTVS/assets/59192491/384ced30-42fc-4063-bf1d-cddad51467a9)

**Comment by StellaHuang95** [comment]
After discussing with the team, we've decided that issues identified by CTI on older branches, where [changes](https://github.com/microsoft/PTVS/issues/7921) were made to the Python version, will be closed if they do not reproduce in the latest version of PTVS, unless they are security or critical issues.
