### ISSUE TITLE
Conda environment is not detected after restart the VS.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7935]
**Describe the bug**
![image](https://github.com/microsoft/PTVS/assets/59192491/5bfa55af-6d96-45ca-b3a8-9b602f4b6bd1)

**Steps to Reproduce**
1. Create a new Python application
2. Right click Python Environment --> Add Environment to create a Conda environment
3. Close the VS and restart the VS
4. Open the project
5. Observes

**Expected behavior**
The Conda environment list in the Python Environment without any error.

**Additional context and screenshots**
The Conda environment is not detected and an error message "This project "PythonApplication" has a reference to a missing Conda environment "env"" pops up.
![image](https://github.com/microsoft/PTVS/assets/59192491/2420fab4-e4de-43e6-805a-ed71a50ed0f8)

**Comment by StellaHuang95** [comment]
After discussing with the team, we've decided that issues identified by CTI on older branches, where https://github.com/microsoft/PTVS/issues/7921 were made to the Python version, will be closed if they do not reproduce in the latest version of PTVS, unless they are security or critical issues.
