### ISSUE TITLE
Please, help me. My Cookiecutter Classifier template is not installing (MS Visual Studio 2022)

### ISSUE THREAD

**Issue by valtrojo** [microsoft/PTVS#7938]
**I go through with creating the solution, and it installs up until it says**
> Name || Create To || Options
> Add to solution || Cancel

It does everything, and then drops a few errors in.

I have tried everything I see. I re-installed Visual Studio _completely_, I re-installed the latest Python interpreter. I use anaconda and download every package (sci-kit learn, matplotlib, numpy and pandas), I make an anaconda environment, I deleted and re-installed the "data-science with python" extension in Visual Studio and I added `C:\Users\LENOVO\anaconda3\Scripts` to path. 

I just don't know what to do anymore, I've been putting this off because I'm kind of a beginner, yet every solution I've seen, I've followed through with, yet it still does not work.

![Microsoft Visual Studio 01_07_2024 23_35_57](https://github.com/microsoft/PTVS/assets/168493228/f0171856-da76-4b2d-b088-201806a42955)
**Additional context**
I use Windows 11.
I have Anaconda Navigator.

**Comment by StellaHuang95** [comment]
Are you following this doc to create your python project? https://learn.microsoft.com/en-us/visualstudio/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter?view=vs-2022. Which python version are you using?
