### ISSUE TITLE
It shows empty window after clicking "Open details" on the .vsp file.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7939]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/fa27749b-abba-4799-9ef8-4753bb41b76e)

**Steps to Reproduce**
1. Create python application project and add "Lib\test\pythoninfo.py" and remove the default .py file
2. Debug> Launch Python Profiling …
3. Checked the option "Open project" and select the current project in drop-down list
4. Click "Start"
5. Wait for the command execution done/ close it anytime
6. The .vsp file is generated and opened in VS but not saved
7. Click "Open details"
![image](https://github.com/microsoft/PTVS/assets/59192491/1ce69c24-546b-4bad-a8ab-ec62b1abc8e7)

**Expected behavior**
An windows opened without any error.

**Additional context and screenshots**
It shows empty window.
![image](https://github.com/microsoft/PTVS/assets/59192491/af9c8ae1-aa84-4f13-8964-0c5e9f851c9e)

**Comment by StellaHuang95** [comment]
I can't repro this in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.12.0 Preview 1.0 [35114.17.main]. Does it still repro for you? @linette-zyy If so, can you share your source code?

**Comment by linette-zyy** [comment]
[pythoninfo.zip](https://github.com/user-attachments/files/16278268/pythoninfo.zip)
I used this code.
Today, on this  environment
![image](https://github.com/user-attachments/assets/d9c532e9-2315-4cfa-b0e4-d3c736be1a99)
 I found this issue can repro on the first time. after restart VS, it is not repro.
