### ISSUE TITLE
Open interactive window，loading all the time after entering enter in the Anaconda environment.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7940]
Environment
![image](https://github.com/microsoft/PTVS/assets/59192491/037e9397-1d8c-4f38-80c8-ee4e9d999ab2)

**Steps to Reproduce**
1.Install Anaconda (downloads from https://www.anaconda.com/download/)
2.Create Python Application project and view all Python Environments
3.Choose Anaconda environment and Open interactive window
4.Entering enter or typing some code to play 

**Expected behavior**
Loads and displays content normally

**Additional context and screenshots**
Loading all the time after entering enter
![11](https://github.com/microsoft/PTVS/assets/59192491/63502f58-e930-4565-ae74-29800a0504b4)

**Comment by StellaHuang95** [comment]
I can't repro this in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.12.0 Preview 1.0 [35114.17.main]. Does it still repro for you? @linette-zyy
