### ISSUE TITLE
Lack of option to run currently opened script.

### ISSUE THREAD

**Issue by paulschmeida** [Microsoft/PTVS#795]
If I have a project with a bunch of separate scripts I want to be able to run the script I'm currently working on without having to go to solution explorer and marking that file as a startup script. I should be able to simply click one button to execute current script in a interactive window.

**Comment by denfromufa** [comment]
right-click on the script and choose "Start with/without Debugging"

**Comment by sanshinron** [comment]
Unfortunately this will open a popup window. I want to be able to run the script inside the docked interactive python window. What if I want to look at the output of a script and change something in the code? With popup window I can't do that. I also have to manually close those popup windows. I know it's related to the general behaviour of VS, but maybe the PTVS developers could circumvent this problem? Other IDEs like PyCharm output scripts to the docked windows and I don't have to juggle between windows or even take my hands of the keyboard.

**Comment by denfromufa** [comment]
There is send to interactive REPL option, also debug interactive REPL can be attached, finally VS does have an output and error windows while debugging. What else?

**Comment by alexranaldi** [comment]
Is there a hot-key to run the current script, or to send the current script to interactive REPL?  I would like to run the currently opened script without having to find it in the Solution Explorer, right click, etc.

**Comment by zooba** [comment]
You can right-click anywhere in the editor and you'll see the same "Start with[out] debugging" menu items. There is also Shift+Alt+F5 (IIRC - look in the Debug menu) for "Execute file in Python Interactive", and you can select all (Ctrl+A) and send selection to interactive (Ctrl+E, E) if you're in a project and want to run a file other than the startup file.

That's all that is currently available. We are planning some changes to make things smoother for people who work in scripts/REPL as opposed to projects - our current design assumed everyone was using projects.

**Comment by alexranaldi** [comment]
I'm finding the Control +E,E sequence to be a bit lengthy - I'm used to a single keystroke to do that (MATLAB).  I'm happy to hear some changes are planned and perhaps a shorter key sequence could be considered as well. Thanks!

**Comment by int19h** [comment]
Note that you can rebind the keystroke in Tools -> Options -> Environment -> Keyboard. The command name is `Python.SendSelectionToInteractive`. The default shortcut is what it is mainly because when we pick them, we have to be careful to not steal something that's already being used in VS, and VS has so many commands that it's getting difficult. But if you don't care about all that other stuff, but use this command a lot, you might as well rebind it to something really short.

**Comment by zooba** [comment]
Ctrl+Enter is available in VS 2017 as an alias for Ctrl+E,Ctrl+E.
