### ISSUE TITLE
Better syntax highlightin colours for Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7951]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Better-syntax-highlightin-colours-for-Vi/10694313)._

---
There should be a way to add better visual studio syntax customizations. In PyCharm, for example, there is just a area when you can select colors for variables, functions, etc. Also, the custom colors doesn't support hex format, which makes it very difficult to copy my colours across from vs code

---
#### Feedback Bot on 7/2/2024, 00:00 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment]
Thank you for bringing up this issue. This request is similar to the one raised in https://github.com/microsoft/PTVS/issues/7082. Please review the response from our team regarding the plan for addressing it.
