### ISSUE TITLE
Install of 17.10.4 cannot install CPython39.exe.x64

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7953]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Install-of-17104-cannot-install-CPytho/10699526)._

---
I tried to install the 17.10.4 update for all supported versions (MSVS 2022, MSVS 2019, MSVS 2017). I get a dialog "Sorry, something went wrong". The message is "Couldn't install CPython39.Exe.x64)". I checked that the folder 
C:\ProgramData\Microsoft\VisualStudio\Packages\CPython39.Exe.x64,version=3.9.13.1,chip=x64 exists and the file timestamps are for today (when I attempted the update).

The install log has
Package 'CPython39.Exe.x64,version=3.9.13.1,chip=x64' failed to install.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=CPython39.Exe.x64;PackageAction=Install;ReturnCode=1603
    Details
        Command executed: "C:\ProgramData\Microsoft\VisualStudio\Packages\CPython39.Exe.x64,version=3.9.13.1,chip=x64\python-3.9.13-amd64.exe" /quiet /log "C:\Users\deber\AppData\Local\Temp\dd_setup_20240709141843_332_CPython39.Exe.x64.log" InstallAllUsers=1 CompileAll=1 Include_symbols=1 TargetDir="C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64"
        Return code: 1603
        Return code details: Fatal error during installation.
    Log
        C:\Users\deber\AppData\Local\Temp\dd_setup_20240709141843_332_CPython39.Exe.x64.log
    Impacted workloads
        Python development (Microsoft.VisualStudio.Workload.Python,version=17.10.34803.213)
    Impacted components
        Python 3 64-bit (3.9.13) (out of support) (Component.CPython39.x64,version=3.9.13.1)

---
#### Feedback Bot on 7/9/2024, 06:36 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thanks for bringing up the issue. Are you saying you were not able to install python from VS installer? Could you try downloading the Python runtime directly from https://python.org/ and install it manually.

If that doesn't solve your issue, we could use more detailed logs to see what's really going on. Can you please collect more logs by running http://aka.ms/vscollect.exe and uploading %temp%\vslogs.zip if the issue persists? Thank you!
