### ISSUE TITLE
No change with the type information when change the sys.exc_info with the latest typeshed.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7955]
**Environment**
![image](https://github.com/user-attachments/assets/2f1c1cb6-ebf2-4c6e-b046-0e07fea13246)

**Steps to Reproduce**
1. Ensure the option is unchecked by default
-     Check there is type information in below example
![image](https://github.com/user-attachments/assets/1979eb2f-7a35-44d0-af49-5d5f8e811b96)
2. Custom Typeshed path
-   git clone https://github.com/python/typeshed, enter the local path on disk where you cloned the repository
![image](https://github.com/user-attachments/assets/180edeab-663c-4110-ad58-3a2cbca9fbc7)
- open` typeshed/stdlib/sys/__init__.pyi`, add from typing import Optional, Tuple, Type to `typeshed/stdlib/sys/__init__.pyi`
- open `typeshed/stdlib/sys/__init__.pyi,` change
With this instead:
```
def exc_info() -> Tuple[Optional[Type[BaseException]],
		        Optional[BaseException],
		        Optional[_version_info]]: …
```
**Expected behavior**
It should now report e3 as being a version info instance
![image](https://github.com/user-attachments/assets/b8014626-3521-498f-a9f5-49c9f5c94a84)

**Actual behavior**
The type information has not changed with latest typeshed.
![image](https://github.com/user-attachments/assets/eca01954-0ed2-47ac-bae7-55ca717619fe)

**Comment by StellaHuang95** [comment]
We don't listen to file change events on files outside the workspace so that's expected. Note that if you change the typeshed file first and then add the path to `typeshed paths`, you will see the type changes.
