### ISSUE TITLE
use of macro in pyproj Interpreter Include does not appear to work

### ISSUE THREAD

**Issue by schleprock** [microsoft/PTVS#7962]
it appears that macros can be used in pyproj files but i'm not able to use a macro when defining the path to a python install. basically i want to do this:

...
\<ItemGroup>
    \<Interpreter Include= "$(PYTHON_3_9_PYBIND_1_13_BASEDIR)">
...

where the macro PYTHON_3_9_PYBIND_1_13_BASEDIR contains the path to a python installation. when VS 2022 starts up, the python project shows this environment as either invalid or simply doesn't have that path on the drop down in Python Environments.

so, does pyproj support the use of a macro(s) in the Interpreter Include?

**Comment by StellaHuang95** [comment]
Unfortunately, this is not supported. Please see https://github.com/microsoft/PTVS/issues/7292
