### ISSUE TITLE
TODOs not displaying for Python in Task List

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7963]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/TODOs-not-displaying-for-Python-in-Task-/10710932)._

---
[severity:It bothers me. A fix would be nice]
Using Microsoft Visual Studio version 17.11.0 Preview 5:
TODOs and the other tokens aren't displayed in the task list for Python.
`# TODO: fix animation` should work, from what I've read, but it does not. Nor do other variants:
`#TODO: fix animation`, `#TODO fix animation`, `# TODO fix animation`, etc.
I could not find similar reports, and am not entirely sure if this is a bug or a feature request.
Thanks for reading and being!

---
#### Feedback Bot on 7/28/2024, 07:13 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Hi there, I was using Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.11.0 Preview 6.0 and was not able to repro any of the above cases. Could you try updating your VS version and see if it still repros?
![image](https://github.com/user-attachments/assets/8b2719fd-2804-4a41-9b0b-b32097b4b659)

**Comment by blaynemm** [comment]
Apologies on the delay, as I hadn't received a notification. I've updated to 17.11.0 Preview 6, but to no avail. I see you're using VS Enterprise though. I am on Visual Studio Community. I'm not sure if I was on the right feedback page anymore!

**Comment by StellaHuang95** [comment]
From PTVS perspective, we don't differentiate between the Community and Enterprise versions of Visual Studio. Could you provide detailed repro steps about your issue using https://www.screentogif.com/? I'd like to see how your task list items are being created.

**Comment by blaynemm** [comment]
![Untitled](https://github.com/user-attachments/assets/d55c1d02-b754-4f34-b303-c0685489fc44)
Apologies if there's anything more you need (or something I'm missing entirely). I'm not sure what else needs to be done to get task list items working.

**Comment by StellaHuang95** [comment]
I'm still unable to reproduce the issue in the Community version of Visual Studio. To determine if this is related to PTVS, could you try creating a simple project in another language, such as a C# console app? Add the same task items and see if the issue occurs there as well.

**Comment by AdamYoblick** [comment]
I also tested this and I couldn't repro on the latest Public Preview of VS.

**Comment by blaynemm** [comment]
Works on everything (that I've tested thus far) except anything Python! That's on Preview 7 now
