### ISSUE TITLE
python function:print report an error

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7965]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python-function:print-report-an-error/10707101)._

---
[severity:It bothers me. A fix would be nice]
print(positionStr, end='') It can't work.........................................................................

---
#### Feedback Bot on 7/21/2024, 06:57 PM: 

(private comment, text removed)
#### Graham Wheeler [MSFT] on 7/31/2024, 09:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thanks for reporting the issue. Could you provide the code sample that repros the issue you see? Also, can you share the diagnostics in the `ErrorList`?
