### ISSUE TITLE
pip install requests this command is not working some warning msg is showing , but python is already installed

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7967]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/pip-install-requests-this-command-is-not/10711167)._

---
i want to test some API in python , So when i try to install the Packages "requests" by using pip install requets its showing some warning msg  like the screensshot that i provided . Not able to install the packages that i need 

---
#### Feedback Bot on 7/28/2024, 07:24 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Thanks for reporting the issue. Could you share the screenshot and repro steps again? I don't see it being attached to the bug report. Thanks.

**Comment by StellaHuang95** [comment]
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊
