### ISSUE TITLE
Interactive window hangs in Visual Studio Professional 2022 (64-bit) with Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7968]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Interactive-window-hangs-in-Visual-Studi/10711227)._

---
[severity:It's more difficult to complete my work]
I have reported this problem on StackOverflow without success.

I have tried this on both the Microsoft Visual Studio Professional 2022 (64-bit) - Current and 2022 (64-bit) - Preview Version 17.11.0 Preview 5.0.

I am following the Python in Visual Studio tutorial [https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl?view=vs-2022]

I have installed the ipython and ipykernel packages

When I open the Interactive window and enter $help it returns the keyboard shortcuts and REPL commands – OK.

However, when I enter an instruction like 2+2 – it hangs.

This is similar to the 2 year old Stackoverflow question "IPython İnteractive Window in Visual Studio" which I have also tried to use without success.

The problem appears a well-known one, see also [https://trycatchdebug.net/news/1346983/python-visual-studio-hangs] Unfortunately their suggestions do not solve my problem.

What am I doing wrong?

---
#### Feedback Bot on 7/29/2024, 10:23 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Going to move this issue under https://github.com/microsoft/PTVS/issues/7868
