### ISSUE TITLE
syntax highlighting - comments

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#797]
in this snippet below xvalues is grey (argument) instead of green (comment):

```
def interpolate_1d(xvalues, yvalues, method='linear', limit=None,
                   fill_value=None, bounds_error=False, order=None, **kwargs):
    """
    Logic for the 1-d interpolation.  The result should be 1-d, inputs
    xvalues and yvalues will each be 1-d arrays of the same length.

    Bounds_error is currently hardcoded to False since non-scipy ones don't
    take it as an argumnet.
    """
    # Treat the original, non-scipy methods first.

    invalid = isnull(yvalues)
    valid = ~invalid

    valid_y = yvalues[valid]
    valid_x = xvalues[valid]
    #new_x = xvalues[invalid]
```

**Comment by denfromufa** [comment]
I think the source of the problem is this window when I try to refactor:

"Waiting for analysis to complete..."

This is analysis on full pandas project.

**Comment by zooba** [comment]
Yeah, we do two pass colourisation and the second pass needs analysis to complete. We should be able to mask out certain tokens sooner than that.

**Comment by denfromufa** [comment]
I don't know if this is a separate issue, but modifying the source code of pandas, triggered PTVS analysis for long duration of time during which refactoring was very limited, at least on new changes.
I had to use PyCharm to get responsive refactoring.
The analysis engine seems to get choked on large projects and maybe even get into some infinite loops.
Try yourself editing pandas from VS 2015, PTVS 2.2 with github and git plugins enabled.

**Comment by zooba** [comment]
Yeah, that's known. When we run analysis in the background it has to use different settings or things blow way out of proportion like this - we don't yet have the degradation mechanisms tuned well (i.e. they don't degrade quality fast enough for huge/complex projects like pandas).

**Comment by denfromufa** [comment]
Perhaps Resharper for Python on top of PTVS is going to be very useful feature :) 
debugging experience from PTVS and refactoring from PyCharm + Cython syntax support.

**Comment by michaelosthege** [comment]
This might be related to an issue I observe with my current project: Syntax highlighting is very slow.
When I open my solution in the morning, I need to switch tabs before classes, arguments and modules get colored.
Also when I insert code, it sometimes breaks the highlighting and whole sections start to have the wrong color.
I had the feeling that it's worse in those files that import a cython module, but I am not entirely certain about that.

**Comment by zooba** [comment]
@michaelosthege That sounds like a separate problem - please file a new bug for it if you're currently using Visual Studio 2017 Update 15.4 Preview 2. If you are on an earlier version, we have probably already fixed the issue that requires you to switch tabs.

**Comment by huguesv** [comment]
We'll need to look at the performance of editing pandas with the new no completion database analysis. I don't think we need to keep this bug open for that though. If anyone tests and finds there are still performance issues with our new analysis, then feel free to file a new bug.
