### ISSUE TITLE
VS will crash and restart when load Cookie template. 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7970]
**Environment**
![image](https://github.com/user-attachments/assets/34761633-eb08-4cf6-bd29-b5911464547c)
Python install from Microsoft store

**Steps to Reproduce**
1.Launch VS
2.Click "View->Cookiecutter Explorer"
3.Load Cookie template under Github or Recommended

**Expected behavior**
It should load successfully.

**Additional context and screenshots**
VS will restart when load Cookie template.
![16](https://github.com/user-attachments/assets/64c6edbb-8f4d-47d2-8b81-4a1211b7f898)

[Events log.zip](https://github.com/user-attachments/files/16491278/Events.log.zip)

**Comment by StellaHuang95** [comment]
Doesn't repro for me on Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.12.0 Preview 2.0 [35211.24.main]. Going to close this for now.
