### ISSUE TITLE
Make it easy to install numpy and tkinter in cpython

### ISSUE THREAD

**Issue by scottz1** [Microsoft/PTVS#798]
I would like to work with the cpython 3.5 beta and be active in bug testing, but I find it extremely difficult to install tkinter, MatPlotLib, and numpy into cpython 3.5. I understand there are several c language dependencies, and I'm willing to build those, but I wasn't able to find any project files, build scripts, or makefiles, so it's impossible for me to use anything but IronPython or Anacanda in PTVS for my analytic projects that require tkinter and numpy.
Request: please make it easy to install numpy, matplotlib, and tkinter in cpython 3.5 with PTVS.
Thanks Microsoft PTVS for already creating an outstanding tool with PTVS 2.2!

**Comment by denfromufa** [comment]
you can get python 3.5 numpy binaries (even linked with MKL) here, compiled 4 days ago:

http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

regarding building numpy looks like people successfully did this:

http://mail.scipy.org/pipermail/numpy-discussion/2015-June/073038.html

I would recommend waiting 2-3 months before going to Python 3.5 on Windows (10?).

tkinter is something i would not even try.

**Comment by scottz1** [comment]
Yes, Win10. I'd like to install 3.5 to help the community find and fix bugs before it's released.
Tkinter is working fine for me. It's not as good as wpf or winforms, but it's ok. What free alternatives are there for python 3?
I neglected to mention matplotlib in my original post. It's an important part of my work. I'm very grateful that such a powerful charting and analysis tool exists for python. Less powerful packages costs thousands of $'s for .net.

**Comment by zooba** [comment]
Yes, this is something we're always looking to improve, though it has to be a separate (i.e. community/distribution/etc.) solution from PTVS. We don't need to track it on here so I'll close this issue.

Thanks for the vote of support and other kind words.

**Comment by zooba** [comment]
(Oh, and now is the best time to try [Python 3.5 rc2](https://www.python.org/downloads/release/python-350rc2/) on Windows 10 as there is still time for them to fix issues. Also, tkinter is part of a normal Python install unless you deselected it, so there's nothing to add there, but you could look at PyQt/PySide as an alternative.)

**Comment by scottz1** [comment]
Any tips on how to install a wheel for Numpy in PTVS? I downloaded numpy wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/  into c:\temp.
Then run this command in the cpython 3.5 directory:
> pip install --no-index --find-links=c:\temp\numpy-1.9.3+mkl-cp35-none-win32.zip numpy
It gets an error running python setup.py egg_info (no such file)

**Comment by zooba** [comment]
The command you need is just `pip install c:\temp\numpy-1.9.3+mkl-cp35-none.win32.zip` (did your browser rename it from `.whl` to `.zip`?)

In Visual Studio on the pip tab (see [these docs](https://github.com/Microsoft/PTVS/wiki/Python-Environments#global-environments)) you can also enter the path to the file and click the `"pip install ..." from PyPI` option - it won't need to download anything if you give it the file.

**Comment by scottz1** [comment]
Thanks zooba. I tried that command in pip tab in ptvs and got same error (below) as from the command line. The browser didn't rename on download; the file is a .zip at ~gohlke. And it's not a .whl inside the zip.

Any advice?

Processing c:\temp\numpy-1.9.3+mkl-cp35-none-win32.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
Command "python setup.py egg_info" failed with error code 1 in C:\Users\scott\AppData\Local\Temp\pip-2lbscroc-build
      File "<string>", line 18, in <module>
      File "C:\Users\scott\AppData\Local\Programs\Python\Python35-32\lib\tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\scott\\AppData\\Local\\Temp\\pip-2lbscroc-build\\setup.py'

**Comment by zooba** [comment]
I'd try renaming it to `.whl`. His page lists it as a wheel, and I guess pip thinks it's actually a source package because of the extension. (Source packages need a `setup.py`, while wheels don't.)

**Comment by Dual2Core** [comment]
@zooba worked for me, +1
