### ISSUE TITLE
Please allow Python scripts calling C# methods be references Visual Studio can see

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7998]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-allow-Python-scripts-calling-C-m/10711495)._

---
We use Pythonnet in our Python scripts to interface with our C# code. When code changes within our C# codebase, we sometimes forget to make the changes in our Python code resulting in errors usually resulting in method name mismatch, parameters being swapped around, or object types being broken. Since Visual Studio recently added Python support, I was wondering if we can directly interface with our Python code and see if our method names/parameters are correct and maybe Visual Studio can even mark it with a red line indicating that the script might not work.

---
#### Feedback Bot on 7/29/2024, 00:31 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by StellaHuang95** [comment]
Thanks for reaching out. As of now, VS provides Python support through PTVS, but it doesn't support directly validate Python code against C# code yet. This could be a potential future enhancement if we hear more user requests. We currently don't have any plans in the near term to support it yet. Thanks again for the issue.
