### ISSUE TITLE
PTVS installs to global packages instead of virtualenv

### ISSUE THREAD

**Issue by kimlindberg** [Microsoft/PTVS#8]
I've tried all approaches I can think of - creating a new virtualenv from with in PTVS, using an existing virtualenn, recreated projects etc. No matter how I try the virtualenv seems to be ignored. Visual studio is showing my virtualenv by name active and all, but is actually listing global packages. And installing packages through PTVS also installs to global packages instead of the virtualenv. 

Attaching screenshot to clarify.

I'm using Visual Studio 2013 community edition. PVTS 2.1 (also tried 2.2 beta). Python 2.7.9. 

![screen shot 2015-04-08 at 10 17 00](https://cloud.githubusercontent.com/assets/1436153/7041358/01075c08-ddd9-11e4-8676-e08ae21a0b2c.png)

**Comment by zooba** [comment]
I suspect your virtual environment has enabled global site-packages somehow, and pip is using that to install to the base environment. We really aren't doing anything here other than calling out to pip, so you should be getting identical results from the command line (`pip list` and `pip install`, where `pip` is in `env\Scripts\pip.exe`).

There may also be something misconfigured in your project (.pyproj) file. Could you post that in a gist or email to ptvshelp@microsoft.com so we can take a look?

**Comment by kimlindberg** [comment]
Sorry, I gave this up some days later and went back to my old non-VS environment since being able to work with virtualenvs properly was too important at the time. 

But what I can add to this is that it was not identical to running pip list and install from command line. Not with that particular virtualenv set. It was more like running from command without a virtualenv set.

But since I probably won't be working with this in the nearest future and add details for you I guess you can go ahead and close the issue if you cannot reproduce it.
