### ISSUE TITLE
support discovery of nose and py.test test cases

### ISSUE THREAD

**Issue by zooba** [microsoft/PTVS#80]
Currently we only detect unittest based testcases, we could support nose and py.test as well.

(Migrated from https://pytools.codeplex.com/workitem/1800)

**Comment by ipyguy** [comment]
+1;  Pressing CTRL+F9 and being able to multi-select my 'nose' tests is about the only thing I'm missing from Eclipse/PyDev now.  Although I've learned to write sequencer nose.run() scripts, it was a nice feature for just selecting a couple of tests.  If this ever gets implemented, it would be nice to configure what exactly nose considers a test, through the VS IDE/PTVS.

**Comment by cwhelms** [comment]
I agree with ipyguy. Being able to use nose would be nice (we use the logging to junit format, which we currently configure as part of the cmd line arguments of the current test running in Eclipse/PyDev.

**Comment by zooba** [comment]
Agreed, though logging to junit format wouldn't be a benefit within VS because we don't understand it. 

To do this properly we'd need our own logger that can send known-format results (e.g. XML or JSON) as tests are executing (that is, we can't just read a log file at the end). That's where most of the effort has to go here - we don't even do that properly for `unittest` yet :(
