### ISSUE TITLE
Flask web role-Cloud service deployment not working though deployment shows successful on visual studio

### ISSUE THREAD

**Issue by divyaspec** [Microsoft/PTVS#800]
Hi,
I have a flask web application converted to a cloud service project with a flask web role using visual studio 2013. All I did is build the template that was installed with the project and published using built in visual studio publish method. I entered my credentials and chose the storage account, enabled the remote debugging diagnostics & then deployed the cloud service application separately. The application ran successfully on local emulator and I pinged the rest api hello world. However, from the azure portal link, when I clicked the link I got 500 server error. This is the third time I tried even creating a new virtual machine with windows server 2012 settings built in visual studio, every time I keep getting the same error. This is an issue and I really want someone to have a look at python PTVS 2.2 tools if there are issue in deploying a flask application. I hope to hear from someone soon. Please see the screenshots from the debugging tools.
![deploymenteventlog](https://cloud.githubusercontent.com/assets/7250796/9568156/acf173ec-4f39-11e5-80ee-41f36b3ddbd6.jpg)

![deploymenterror](https://cloud.githubusercontent.com/assets/7250796/9568304/90f64c40-4f3d-11e5-9646-730076f9179a.jpg)

Thank you for your time in advance.

**Comment by zooba** [comment]
There isn't "an" issue in deployment, but there are a lot of ways it can go wrong. See our [Cloud Service](https://github.com/Microsoft/PTVS/wiki/Cloud-Project) docs for some troubleshooting steps (near the end).

If you're still having trouble after that, could you post your `.pyproj` file (just the project - don't need everything else initially), either to a [gist](https://gist.github.com) or privately to ptvshelp@microsoft.com?

**Comment by divyaspec** [comment]
Thank you for your reply. I have went through the documentation. I used the PTVS 2.2 version tools on visual studio and published the web role project from the template offered by the visual studio. I didn't include any code or edited any lines. I followed the tutorial to publish the app. Would you know of any known issues or deployment errors for flask web app.

**Comment by zooba** [comment]
Can you post the logs from the remote machine?
