### ISSUE TITLE
Missing Output window when running python prg

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#8004]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-Output-window-when-running-pytho/10749523)._

---
[severity:I'm unable to use this version]
After having installed Python 3.12.6 and MS Visual studio I can run my program, no errors, but I cannot see the proper output (window).
I just use "print" to show if program works.

---
#### Feedback Bot on 9/20/2024, 09:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by gschmidt176** [comment]
Hi,
after I have removed the last line of code, it works!
I was testing the strange example, written in a booklet, it seems there is something wrong.
I didn't understand the code, therefore I was trying this example.
You may close this ticket. 
Thanks for your patience!
