### ISSUE TITLE
django debug remote

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/PTVS#801]
Hi

Is there a way to start the debugging of a web (django) project, while allowing remote access to the site? When I'm running the project without debugging, I could go to the command line and type: python manage.py runserver 0.0.0.0:80 (without going through PTVS). However, if I want to use the PTVS debugger, is there a way to do this (so that I can debug while someone remotely accesses the site)?

Thank you

**Comment by zooba** [comment]
If you open Project Properties and go to the Debug tab, there are some options there you can use. Specifying the host name as "0.0.0.0" should do what you want (though I don't recall right now whether we supported that one for Django or just the other web projects).

**Comment by sriksrid** [comment]
Hi

I couldn't find the host name field in the debug options - trying to force the options (either by modifying arguments for the server command, setting a SERVER_HOST='0.0.0.0') doesn't seem to work.
The port number field, on the other hand, works as expected.

Is there some other way of setting the host to 0.0.0.0? 

Thank you.
