### ISSUE TITLE
Runtime Parse Error When Using Semantic Kernel In Python Project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#8022]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Runtime-Parse-Error-When-Using-Semantic-/10761523)._

---
[severity:I'm unable to use this version]
I am trying to use Semantic Kernel in a Visual Studio 2022 Python project but I get the following runtime exception:
(7, [('expected', 'letter or digit', None)]) at the line import semantic_kernel.

Steps to reproduce the error:
1. Create new Python Project
2. Add 'import semantic_kernel'
3. Run the application

Application stops with the exception:
(7, [('expected', 'letter or digit', None)])

I am using Python verion 3.9 (64-bit) and semantic-kernel (0.9.6b1)

Further details in Output:
Stack trace:
 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 259, in _G_many_2 (Current frame)
 >    _G_apply_1, lastError = self._apply(self.rule_letterOrDigit, "letterOrDigit", [])
 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 262, in rule_name
 >    _G_many_3, lastError = self.many(_G_many_2)
 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 604, in _G_lookahead_2
 >    _G_apply_1, lastError = self._apply(self.rule_name, "name", [])
 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 608, in rule_rule
 >    _G_lookahead_3, lastError = self.lookahead(_G_lookahead_2)
 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 641, in _G_many_1
 >    _G_apply_1, lastError = self._apply(self.rule_rule, "rule", [])
 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 644, in rule_grammar
 >    _G_many_2, lastError = self.many(_G_many_1)
 >  File "C:\VSProjects\PythonApplication2\PythonApplication2\PythonApplication2.py", line 1, in <module>
 >    import semantic_kernel
 >pymeta.runtime.ParseError: (7, [('expected', 'letter or digit', None)])

---
#### Feedback Bot on 10/8/2024, 10:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by StellaHuang95** [comment]
Thanks for reaching out. Is your code in a public repo or could you provide code samples that help us repro this issue? Thanks!

**Comment by GDT48** [comment]
Please refer to:
[https://github.com/GDT48/PythonApplication2](url)

**Comment by StellaHuang95** [comment]
Thanks! I don’t see your environment included in the repo, and I wasn’t able to repro the issue. Based on the error message, it seems like a compatibility issue with the `semantic-kernel` package’s dependency on `pymeta`. Could you try updating or reinstalling both `semantic-kernel` and `pymeta`? You might also want to run the script outside of Visual Studio to check if it’s specific to the IDE

**Comment by GDT48** [comment]
I have updated and tidied the project, creating an environment.
The environment has 'semantic-kernel==0.9.6b1'.
However if I run with **from semantic-kernel import KernelI** get error - invalid syntax, because of the hyphan.
If I edit to to **from semantic_kernel import Kernel** I get the exception - (7, [('expected', 'letter or digit', None)])

Note the inconsistency between semantic-kernel (with a hyphan) and semantic_kernel (with an underscore).

I am able to create a Python project with semantic_kernel in VS Code without issue.

**Comment by 784651** [comment]
I had the exact same issue, and I solved it. Posting so if others run into this they can also resolve.

Fix:
**Delete Workspace Settings**
.vscode/*

**Delete Python Extension Cache**
%APPDATA%\Code\User\workspaceStorage (I think this was the issue, but no way to validate/verify)
%APPDATA%\Code\User\globalStorage\ms-python.python

**Delete Virtual Environment Metadata**
.venv/*

After deleting all of this, I reran my pip installs and things worked out... This issue drove me crazy. 

For me, the issue just randomly started happening when I was trying to run some tests.

**Comment by MahrRah** [comment]
I ran into the same issue and realized I had the `User Uncaught exception` option selected under `Breakpoints`. Once I unchecked it, I was able to debug as expected. 

<img width="665" height="126" alt="Image" src="https://github.com/user-attachments/assets/5a659a91-73eb-425d-b3fb-431fc4f4c92e" />

**Comment by nm-free** [comment]
I'm encountering an exception when attempting to debug a Python project in Visual Studio 2022. The project uses Python 3.13 and the semantic-kernel library, version 1.36.2. The exception occurs immediately upon starting the debug session.


(7, [('expected', 'letter or digit', None)])

스택 추적:

 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 259, in _G_many_2 (Current frame)

 >    return self.builder.pred(expr)

 >                                ^^

 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 262, in rule_name

 >    def eatWhitespace(self):

 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 604, in _G_lookahead_2

 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 608, in rule_rule

 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 641, in _G_many_1

 >  File "C:\pymeta_generated_code\pymeta_grammar__Grammar.py", line 644, in rule_grammar

 >  File "C:\ai-python\kernel\semantic_kernel_service.py", line 6, in <module>

 >    from semantic_kernel.connectors.ai.chat_completion_client_base import ChatCompletionClientBase

 >  File "C:\ai-python\kernel\__init__.py", line 1, in <module>

 >    from .semantic_kernel_service import SemanticKernelService

 >  File "C:\ai-python\ai\ai_service.py", line 12, in <module>

 >    from kernel import SemanticKernelService

 >  File "C:\ai-python\ai\__init__.py", line 1, in <module>

 >    from .ai_service import AIService

 >  File "C:\ai-python\ai_api.py", line 24, in <module>

 >    from ai import AIService

 >  File "C:\ai-python\app.py", line 7, in <module>

 >    from ai_api import ai_api_bp, init_services, initialize_encryption

**Comment by dtklein7** [comment]
I saw the same error, did exactly what [784651](https://github.com/784651) said they did. This step, which is the last one I did, resolved it for me:

> **Delete Python Extension Cache**
> %APPDATA%\Code\User\workspaceStorage (I think this was the issue, but no way to validate/verify)
> %APPDATA%\Code\User\globalStorage\ms-python.python

Note that this did seem to mess vscode for a while, I believe I restarted it twice before it figured itself back out.
