### ISSUE TITLE
There was no line numbering in Python projects

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#8023]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/There-was-no-line-numbering-in-Python-pr/10756855)._

---
There was no line numbering in Python projects 
[2024-10-01_21-38-11.png](https://aka.ms/dc/file?name=Ba1d46aef3f214af696e6900adbe1d070638633974571621969_2024-10-01_21-38-11.png&tid=a1d46aef3f214af696e6900adbe1d070638633974571621969)
![Image](https://github.com/user-attachments/assets/4816692a-f190-4779-9d15-62f7b903fdc3)

Even after rolling back to the previous version, the line numbering did not return 
What is going on?

---
#### Feedback Bot on 10/4/2024, 04:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by debonte** [comment]
You can enable line numbers by going to Tools > Options > Text Editor > Python > General and checking the "Line numbers" checkbox. My guess is that it's not checked. Can you take a look?
![Image](https://github.com/user-attachments/assets/9ce95091-0b10-4ec1-b707-8c625bb45dce)

**Comment by debonte** [comment]
@StellaHuang95, did the default value for the "Line numbers" setting change recently? I'm guessing not, since I checked both VS 2019 and VS 2022 on my machine and found that there were no line numbers. I guess I've just never noticed. Maybe they should be enabled by default? I think they are on by default in C#.

**Comment by StellaHuang95** [comment]
@debonte Yeah that makes sense, I can change the default to `true`.
