### ISSUE TITLE
PTVS forces intellisense results when no results are found.

### ISSUE THREAD

**Issue by ssarangi** [Microsoft/PTVS#803]
While typing class names or function names the intellisense for PTVS will force the name it finds in intellisense. This becomes a bit of a pain to delete the result and retype the name I want and then press Esc to force it not to show up. 

Steps to reproduce:
1) Create a blank python file
2) type: 
```
if __name__ == "__main__":
    main
```

As "main" on line 2 is being typed, intellisense shows up ImportWarning & RemoteWarning and then if I press ( or Enter it replaces it with ImportWarning. 
IMHO, the feature should be to stop with intellisense at this point and not force it.

**Comment by zooba** [comment]
Strange, we're not supposed to show intellisense at that point at all (exactly because of this scenario). We'll take a look.

Can you tell us the exact versions of VS and PTVS you are using?

**Comment by ssarangi** [comment]
Visual Studio Professional 2013
PTVS version: 2.2

Thanks for looking into this.

**Comment by zooba** [comment]
I can't reproduce this on an equivalent setup.

There is a separate extension (made by someone else) to add this feature to Python IntelliSense. Do you maybe have that one installed?
