### ISSUE TITLE
Debugging a Django project doesn't trigger breakpoints

### ISSUE THREAD

**Issue by manabreak** [Microsoft/PTVS#804]
I have a Django project that uses Django REST Framework. None of the views trigger a breakpoint when debugging. Am I missing something here?

All I've done is I set the breakpoints and chose "Start with debugging", but all the requests are handled without breakpoints triggering.

**Comment by zooba** [comment]
There may be something special about the REST framework. I haven't looked into it yet.

Do you know if it uses subprocess or multiprocessing to handle requests? If so, that will prevent debugging, but there may be an option to disable it while testing. We have feature #125 that will eventually be able to handle this, but right now it's not supported.

**Comment by zooba** [comment]
A second thought that occurs - have you set breakpoints in Python code or in Django template files? (Does the REST framework even use template files?)

**Comment by manabreak** [comment]
@zooba Thanks for your replies. Neither of those were the case; I browsed through similar issues and the solution was to add `--noreload` to the arguments of the debug server.
