### ISSUE TITLE
Girhub error

### ISSUE THREAD

**Issue by johnsojo03** [microsoft/PTVS#8047]
**Describe your question**
[A clear and concise description of your question or what you want help with]

**What have you tried?**I have an error
[Have you already searched online? What solutions have you tried?]

**Additional context**
[Add any other information or screenshots that would help us provide you with a better answer]

**Comment by StellaHuang95** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue.

If this continues to be a problem, would you please reopen the issue and add repro steps with sample code? Thanks.
