### ISSUE TITLE
PEP-3107 issue.

### ISSUE THREAD

**Issue by FrankStain** [Microsoft/PTVS#805]
Seems [PEP-3107](https://www.python.org/dev/peps/pep-3107/) currently not supported by PTVS.
Is it possible to support? It rly usefull.

Currently i use PTVS 2.2 on MSVS-2013.

**Comment by zooba** [comment]
It should be supported. What is not working for you?

**Comment by FrankStain** [comment]
@zooba In next code annotations will not be shown for me.
```python
def foo( x : int, y : int ) :
	# Tooltip here shows <unknown type> for both `x` and `y`
```
Or for next example too.
```python
class Foo( object ) :
	def __init__( self ) :
		self.x	= 10
		self.y	= 2
		
def bar( f : Foo ) :
	# IntellISense doesn't shows `f` members here.
	# Type of `f` also shown as <unknown type>.
```

As i can know, this is expected behaviour of function annotations.

**Comment by zooba** [comment]
This is actually PEP 484, and is new for Python 3.5 (see #82). Previously, they were not meant to be interpreted specially unless you wrote your own code for it.

We're looking at supporting PEP 484 sometime soon, so I'll close this issue.
