### ISSUE TITLE
Combo box only displays one environment at a time.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#8072]
**Describe the bug**

![Image](https://github.com/user-attachments/assets/27bb0a41-4368-4cb9-bd29-f4a876576425)

**Steps to Reproduce**

1. Create a Python Application.
2. Create a few virtual environments.

**Expected behavior**

The combo box should display all environments.

![Image](https://github.com/user-attachments/assets/06da7df3-a874-47c3-aad0-5773159c9791)

**Additional context and screenshots**

Only one environment is shown in the combo box at a time, and you need to scroll to see the rest.

![Image](https://github.com/user-attachments/assets/883c0470-5ed3-426a-8f96-c6ef76344bcf)

**Comment by ttSpace** [comment]
I can repro in today's build ``` 17.13.0 Preview 2.0 [35605.110.d17.13]```, Python Package: ```17.0.24323.2```.

![Image](https://github.com/user-attachments/assets/4609ed32-feee-4222-bca2-272deabfcf40)

**Comment by StellaHuang95** [comment]
This is a VS upstream change not a PTVS change, this affects all components in the UI such as https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2301388
