### ISSUE TITLE
The native debug progress exited unexpectedly when debug after hit breakpoint.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#8077]
**Environment**
![Image](https://github.com/user-attachments/assets/3ddfed0b-647c-4d49-9b3e-7f4acb16732e)

**Steps to Reproduce**
1. Create new Python Application, add simple Python code
2. Enable "Native Code Debugging" in project settings / debug page
3. Set breakpoint and start debugging
4. When hit the breakpoint then hit "F10"

**Expected behavior**
It should jump next line.

**Actual result**
The native debug progress exited.

When hit the breakpoint then hit "F11"， an error pops up.
![Image](https://github.com/user-attachments/assets/4c24ba13-cabc-40f8-97c3-e7e198d9bc50)

**Comment by rchiodo** [comment]
@linette-zyy what version of Python are you using? 3.9/3.10? 

3.8 and 3.7 are no longer supported if you're using them.

**Comment by linette-zyy** [comment]
@rchiodo I used the Python3.9 installed from workload

**Comment by rchiodo** [comment]
Okay thanks, that should work then. I'll investigate.

**Comment by rchiodo** [comment]
The latest submission should fix this. At least I can no longer reproduce the problem with the latest bits. Once this PR goes through, the next build on main will have the fix:
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/595760
