### ISSUE TITLE
$(ProjectDir) doesn't appear to work in python project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#8083]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ProjectDir-doesnt-appear-to-work-in-/10791218)._

---
[severity:Other]
I'm trying to create a project and solution around existing python code not created in Visual Studio (using 2022).  The code relies extensively on environment variables.  

To facilitate debugging, I'm able to set the variables in the project's properties under the debug tab manually.  Additionally, $(SolutionDir) appears to resolve as expected.  However, $(ProjectDir) does not.  It seems to return nothing.

---
#### Feedback Bot on 11/15/2024, 00:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by StellaHuang95** [comment]
Unfortunately, macros are currently not fully supported. Please see https://github.com/microsoft/PTVS/issues/7292
