### ISSUE TITLE
Feature Request: Power BI Python API/integration? 

### ISSUE THREAD

**Issue by datnamer** [Microsoft/PTVS#809]
Hi PTVS, thanks for the great open source work!

I would love to have the ability to programmatically create/deploy/integrate with Power BI (and Excel) products from python.

**Comment by zooba** [comment]
So would we :)

It looks like Power BI has a [REST API](https://powerbi.microsoft.com/developers) that we could plug into, and the only hard part is doing [authentication](https://msdn.microsoft.com/en-us/library/dn877545.aspx) (which I thought we had a library for - maybe @huguesv knows where it is?).

**Comment by huguesv** [comment]
We have a library Azure Active Directory Authentication (ADAL), but it's not publicly available yet.  When it is, it will be here: https://pypi.python.org/pypi/adal/
@RandalliLama is now working on this.

It should be possible to follow the "client app" scenario described here:
https://msdn.microsoft.com/en-us/library/dn877545.aspx

With a simple HTTP POST similar to the one described here instead of using ADAL:
http://azure-sdk-for-python.readthedocs.org/en/latest/resourcemanagementauthentication.html

If you try it out and need more help, let us know.

**Comment by franmer** [comment]
So do i!!

Actually the potential of PowerBI comes from being accesible from 3rd party web apps. Python is massively spreading for DataScientist and really encouraging to have an integration soon!! This would be spectacular.

**Comment by aggFTW** [comment]
Hi, is there any progress on this Python PowerBI REST client?
We're a team inside Microsoft (Azure) that would be interested in working on this :)

**Comment by zooba** [comment]
@aggFTW You should get in touch with our internal alias then, so we can get the right people chatting in person :)

**Comment by raeisi** [comment]
Is there any progress on this?

I also need Power BI to send a request to a server and get the data in the date-time range provided in i.e. XML query

**Comment by zooba** [comment]
You're probably best to follow up at the [Power BI forums](https://ideas.powerbi.com/forums/265200-power-bi?query=python), where there are some similar requests already.

The kind of support you're asking for is independent from Visual Studio, so it won't be added to PTVS, but should be available as either a simple REST API or a Python library from the Power BI project.

**Comment by JuaSmithy** [comment]
Hi, is there any progress on this Python PowerBI REST client?

**Comment by raeisi** [comment]
Have a look at this and see if this satisfies your requirements. https://msdn.microsoft.com/en-us/library/dn877544.aspx

**Comment by zooba** [comment]
And to add to that post, everything about authentication using .NET should work just as well with the equivalent Python library `adal` - https://github.com/AzureAD/azure-activedirectory-library-for-python
