### ISSUE TITLE
Visual Studio Python Debugger hangs on subprocess.check_output

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#8099]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Python-Debugger-hangs-on-s/10797971)._

---
[severity:It's more difficult to complete my work]
Consider the following code:

```
import subprocess
output = subprocess.check_output(["cmd.exe", "/c", "date", "/t"])
print(output.decode())
```

When running it normally, it works as expected. However, when using the Visual Studio debugger, it hangs indefinitely when hitting the subprocess.check_output line.

---
#### David Airapetyan on 11/22/2024, 05:58 PM: 

<p>Update - this might be a non-issue, this was happening on a fork of Python 3.12. When I tried this with vanilla Python 3.10, the problem no longer reproduced.</p>

#### Feedback Bot on 11/24/2024, 06:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by judej** [comment]
Thanks for the update. Closing.
