### ISSUE TITLE
Referencing several Python extension Modules (*.pyd) does not work

### ISSUE THREAD

**Issue by kgrigo** [Microsoft/PTVS#810]
We have a python Project and using PTVS 2.2 in Visual Studio Pro 2013 (Update 2).

While trying to add several references, Intellisence is working only for one. It seems after adding a new reference the *.idb files in AppData\Local\Python Tools\ReferencesDB\12.0 from the existing ones will be deleted.

I checkt the PTVS sources and found a bug in PythonTypeDataBase.cs -> FindDbFile. I could fix it by moving the part with check for correct file last modified date after the check for the correct module Name (see resulting code in ScreenShot). I tested it with a new build and it works fine in our Environment.

Did you already heared about this bug? Is there a possibility to get it fixed in your next released Version?

Best regards
Karo

![changedcode](https://cloud.githubusercontent.com/assets/14127246/9685800/caf5dd16-5320-11e5-9882-bdcc4be8fb42.PNG)

**Comment by zooba** [comment]
Nope, haven't heard about it. Good catch!

Can you send us a pull request with your change?

**Comment by zooba** [comment]
(Oh, and looks like some indentation got moved around in your fix lines 317-18. We'll probably ask you to fix that in a PR, so maybe get it first :) )
