### ISSUE TITLE
Space formatting options with duplicate names

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#811]
Insert space within empty square brackets appears twice:

![square-brackets1](https://cloud.githubusercontent.com/assets/1696845/9691043/d39e3e9e-52f4-11e5-897f-e834845e0615.png)

![square-brackets2](https://cloud.githubusercontent.com/assets/1696845/9691045/d66eeb96-52f4-11e5-8dcd-7582eaee9e8e.png)

**Comment by crwilcox** [comment]
in CodeFormattingOptions.cs we have two options flagged with this.  It seems the second one should probably not be using the phrase 'empty' as it is for non empty lists and spacing around the '[' and ']'

```csharp
[CodeFormattingExample("[ ]", "[]")]
[CodeFormattingCategory(CodeFormattingCategory.Spacing)]
[CodeFormattingDescription("SpacesWithinEmptyListExpressionShort", "SpacesWithinEmptyListExpressionLong")]
[CodeFormattingDefaultValue(false)]
public bool? SpacesWithinEmptyListExpression { get; set; }

[CodeFormattingExample("[ a, b ]", "[a, b]")]
[CodeFormattingCategory(CodeFormattingCategory.Spacing)]
[CodeFormattingDescription("SpacesWithinEmptyListExpressionShort", "SpacesWithinEmptyListExpressionLong")]
[CodeFormattingDefaultValue(false)]
public bool? SpacesWithinListExpression { get; set; }
```
