### ISSUE TITLE
Unexpected error pops up in the console when remote debugging.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#8110]
**Environment**
![Image](https://github.com/user-attachments/assets/07e59e55-65bf-4a4c-8469-0345ad27a454)

**Steps to Reproduce**
1.Launch VS and create new python application.
2.Download debugpy package.
3.Typing code in python file.

    import debugpy
    print(debugpy.__version__)
    debugpy.listen(("localhost", 5678))
    debugpy.wait_for_client()
    print('hello')
4.Run this with CTRL+F5

**Expected behavior**
The console has no errors.

**Actual result**
Unexpected error pops up in the console when run this with CTRL+F5.
![Image](https://github.com/user-attachments/assets/18627d7e-6870-4caf-96f5-6a961afe2fa3)

**Comment by StellaHuang95** [comment]
@linette-zyy does this still repro? I can't seem to repro it.

**Comment by linette-zyy** [comment]
I verify this issue on the latest build 
![Image](https://github.com/user-attachments/assets/c18db713-a7d4-427a-9d0f-f83a4c4d7510)
And found this issue is not repro.
![Image](https://github.com/user-attachments/assets/9fc0ac03-9ce7-49c3-986b-d12bdd396042)
