### ISSUE TITLE
 IntelliSense only available until VisualStudio restart

### ISSUE THREAD

**Issue by causa-prima** [Microsoft/PTVS#812]
Using Visual Studio Express 2013 with PVTS - IronPython v2.2 I have a simple testproject structured as follows:

```
testproject
|
|-subpackage
|  |
|  |- __init__.py
|  |- subpackagetest.py
|
|- __init__.py
|- test.py
```

Both `__init__.py` files are empty. `test.py` contains

```
from testproject.subpackage.subpackagetest import Subpackagetestclass

class Projectclass(object):
    pass
```

and `subpackagetest.py` contains

```
from testproject.test import Projectclass

class Subpackagetestclass(object):
    pass
```

When hovering over any of the imported classes or packages Visual Studio only shows `<unknown type>`.

The project file is alongside the package. When I create new files and classes, IntelliSense is (not always?) available until I restart VisualStudio.

**Comment by andygraham** [comment]
Have you added your testproject folder to 'Search Paths' in your IronPython project?

**Comment by causa-prima** [comment]
Yes, the folder containing my *.py-files is in "Search Paths".

**Comment by zooba** [comment]
You actually need to add the directory *above* `testproject` as a search path if you want to write `import testproject`. Python will only resolve modules inside a search path, not the search path itself.

**Comment by causa-prima** [comment]
Then why does it (sometimes?) work until I restart Visual Studio?

**Comment by causa-prima** [comment]
I just had to revert the changes I did to apply your solution for some company-internal reason, and IntelliSense still works. The core folder is not even in the search path and I just restarted Visual Studio - still works. I have no idea what's going on, but as long as it works it's fine with me.
