### ISSUE TITLE
NLTK is not working in PTVS 2.2

### ISSUE THREAD

**Issue by HK-Zhang** [Microsoft/PTVS#813]
When I try to import libraries like NLTK in the python application and run python code, it says "un(shallow)copyable object of type <type 'Element'>". How do we resolve it? Thanks.

**Comment by int19h** [comment]
It's an exception in the standard library (the `copy` module) that is handled, but in such a way that PTVS cannot properly detect that it's handled, so it reports it. You can just tell it to continue running, and it'll work from there; or you can disable that exception altogether in Debug -> Exceptions. 

We should probably add it to the standard list of exceptions and disable it by default until we find some way to properly detect it, or to work around it.

Here's the original bug: http://pytools.codeplex.com/workitem/2077

**Comment by HK-Zhang** [comment]
Thanks for your suggestion. It works.
