### ISSUE TITLE
Registering extension in Visual Studio 2013 can not proceed

### ISSUE THREAD

**Issue by wupeng78** [Microsoft/PTVS#814]
I have test Python tool 2.1 and 2.2, when it comes to "Registering extension in Visual Studio 2013", it cannot proceed. I have installed the IDE. Hope you solve the problem.

**Comment by zooba** [comment]
You may have a corrupted VS install (note that registering may take a few minutes, especially on a slow or busy machine).

If it's failing, then run a repair of your VS install and try again. If it's just taking a long time, open Task Manager and see if `devenv.exe` is running. If it is, then it's still busy and you should keep waiting. If not, we'll need to do some more debugging.

**Comment by palapiessa** [comment]
I had same issue and noticed that VS devenv must be running in order registration to complete.

**Comment by zooba** [comment]
Correct, devenv needs to finish running as part of VS install.

Since we didn't hear anything back from the OP, I'll close this to keep things tidy around here.
