### ISSUE TITLE
Make project file more suitable for version control

### ISSUE THREAD

**Issue by assafmendelson** [Microsoft/PTVS#818]
Today the project file for python projects has on file which handles both private and public elements. 
This means that when we commit it to version control (which we need in order for others to work with the project) we keep getting conflicts on elements such as command line arguments.
in contrast C++ project files are divided into two: A "public" one which contains the list of files, definitions, link options etc. and a "private" one which contains elements relevant to the user alone. We then commit the "public" one to the version control and add the "private" one to the ignore list.
Specifically the startup project and command line arguments should be part of the "private" project.

**Comment by int19h** [comment]
Is it the same as #661, or did you have other things in mind that are not listed in that issue?

**Comment by zooba** [comment]
This looks like a dup to me.
