### ISSUE TITLE
Allow separate paths for runtime and editor

### ISSUE THREAD

**Issue by assafmendelson** [Microsoft/PTVS#819]
Because of issues of using a 3rd party package which we need to save in the source control, we have the package in a specific location relative to our python package. To import it we need to change the path to include the relevant position. This makes ptvs confused (as the path is changed as part of the python script itself before the import).
While it is possible to change the path in the project configuration, I prefer not to do so as that would not represent actual run environment (i.e. I might have import problems which would only occur on runtime). It would be nice to be able to configure the path for viewing only (e.g. auto completion etc.) while leaving it the same as runtime environment for running (debugging)

**Comment by zooba** [comment]
If you add a search path, it will be stored as relative to your code and only resolved fully when you run. Does this help?

Perhaps you could show what your code layout looks like to help me get a better idea of what you need to achieve?
