### ISSUE TITLE
Problem when running tests from Test Explorer

### ISSUE THREAD

**Issue by grbd** [Microsoft/PTVS#821]
For info I'm running VS2015 Full

Lets say I create a very simple test

```
import unittest

class Test_test1(unittest.TestCase):
    def test_A(self):
        self.fail("Not implemented")

if __name__ == '__main__':
    unittest.main()
```

If I try to run this via the Test Explorer window, it seems to get stuck on running the first test.
In that it never exits with ether success or failure (I have to manually Cancel it)

If I click the Green Start Button under visual studio to run it as a normal bit of code
then there's no problem

```
F
======================================================================
FAIL: test_A (__main__.Test_test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\SourceControl\GitRepos\GBD.Build.BlackJack\blackjack\test\cmake\storage\test1.py", line 5, in test_A
    self.fail("Not implemented")
AssertionError: Not implemented

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (failures=1)
```

**Comment by zooba** [comment]
Are you on Windows 7? If so, you're probably hitting #668

**Comment by grbd** [comment]
I do have windows 7 and I did notice that one

It might be related, but for me its only when running the tests from within the test explorer window that there's a problem (test never ends).
If I run the test via usual debugging of the script, it seems to work fine and the immediate out window shows the expected output and everything looks okay

```
..
----------------------------------------------------------------------
Ran 2 tests in 12.045s

OK
```

so testing does work, just not in the test explorer window

**Comment by grbd** [comment]
for info I tried to run this from the cmd line and it seems to work fine
this suggests a problem in the gui handling code for test explorer somewhere

```
D:\SourceControl\GitRepos\GBD.Build.BlackJack\blackjack\test\cmake\storage>C:\Python34\python.exe "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Visual Studio\2.2\visualstudio_py_testlauncher.py" -m test1 -t Test_test1.test_A
```


```
======================================================================
FAIL: test_A (test1.Test_test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\SourceControl\GitRepos\GBD.Build.BlackJack\blackjack\test\cmake\storage\test1.py", line 5, in test_A
    self.fail("Not implemented")
AssertionError: Not implemented

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)

```

**Comment by zooba** [comment]
Yep, that's the same issue.
