### ISSUE TITLE
jupyter kernel - connecting from csharp

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/PTVS#822]
Hi PTVS team,

since you connect jupyter kernel in PTVS, so I thought maybe you can point out what is the problem with ICSHARP. I recall that PTVS had similar connection problems once ipython project got updated from version 2 to 3. Can you please have a look?

https://github.com/zabirauf/icsharp/issues/5

**Comment by denfromufa** [comment]
@zooba @int19h we got ICSHARP (c# kernel) working for jupyter 4.0, is it possible to use VS intellisence in C# within ipython REPL if the kernel is switched from python to c#?

**Comment by int19h** [comment]
The current REPL is hardwired for Python editing, and won't switch language according to what the backend actually uses.

Note that C# guys are working on [their own REPL](https://github.com/dotnet/roslyn/issues/4110) (using the same core implementation as PTVS in VS 2015 - it's now part of VS platform, to be reusable by any language that needs one). Connecting to Jupyter sounds more like a feature for their implementation to support, though if they do it, it would probably be based on the work that we do for ours for 3.0.

**Comment by zooba** [comment]
We can't actually connect to a Jupyter kernel yet, though it's pretty high on my wishlist for 3.0. Once we have that, it should be relatively easy to port between languages.

**Comment by denfromufa** [comment]
how are you going to support R without this multi-language REPL? :) does NTVS use different REPL mechanism (no ipython)?

**Comment by int19h** [comment]
R support is a separate thing (RTVS) that's going to have its own REPL, same as C# etc. We're not focusing on Jupyter integration there for the first release, though it's probably going to happen at some later point.

NTVS REPL is its own thing and has no IPython integration.

**Comment by zooba** [comment]
Actually, the current REPL doesn't use IPython either :)

We mostly just hook stdin and stdout and redirect those. If you look at [visualstudio_ipython_repl.py](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/visualstudio_ipython_repl.py) you'll see we're hijacking messages that would have been rendered by the console renderer, rather than using the protocol directly.

**Comment by denfromufa** [comment]
this has been fixed
