### ISSUE TITLE
IPython: No module named 'ipykernel'

### ISSUE THREAD

**Issue by petgit** [Microsoft/PTVS#825]
I want use Ipython in VS2013 (see  https://github.com/Microsoft/PTVS/wiki/Using-IPython-with-PTVS)

It works in the python console: https://github.com/Microsoft/PTVS/wiki/Using-IPython-with-PTVS#1-first-lets-make-sure-ipythonmatplotlib-have-been-installed-on-your-system--work-properly

Then I set Interactive Mode to IPython:
https://github.com/Microsoft/PTVS/wiki/Using-IPython-with-PTVS#3-switch-back-to-overview-click-configure-interactive-options-and-set-interactive-mode-to-ipython

But in the interactive Window in VS2013 I get the error:

Error using selected REPL back-end:
No module named 'ipykernel'
Using standard backend instead

I tried Python 2.7 x86, 3.4 x86 & x64 : All the same error.

**Comment by zooba** [comment]
What version of IPython do you have installed? It's possible they've made more breaking changes.

It should work fine if you install version 3.x or earlier. That's the latest version we were able to test with before we released.

**Comment by petgit** [comment]
Actual IPython Version is 4.0. 
With "pip install -I ipython==3.2.1" it works with this steps:

Version 3.2.1 or 3.0  result in error with path , 
see http://stackoverflow.com/questions/32252122/installing-ipython-importerror-cannot-import-name-path 
After use path.py=7.7.1 the next error is: IPython.kernel.zmq requires pyzmq >= 13
with "pip install pyzmq" it works nows.

Thanks.

**Comment by zooba** [comment]
I'll keep this open as we ought to add support for IPython 4.0 before our next update is released.

**Comment by denfromufa** [comment]
ipython 4.0 works for me

**Comment by zooba** [comment]
Maybe @petgit can confirm whether IPython 4.0 was fully installed or not? Things are a little bit confusing with the Jupyter/IPython split, and I believe `ipykernel` is a separate project now too, so it may just have been an install issue.

**Comment by petgit** [comment]
IPython I installed normal with pip, so I got the latest 4.0. 
It worked outside of VS2013: c:\Python34\Scripts>ipython
So I installed nothing extra, also not ipykernel.
Now I execute "pip install ipykernel":
....
Successfully installed ipykernel-4.0.3 jupyter-client-4.0.0 jupyter-core-4.0.4 pyzmq-14.7.0

That was the problem. Now it works also in VS2013.
