### ISSUE TITLE
Import opencv in PTVS

### ISSUE THREAD

**Issue by Tegdam** [Microsoft/PTVS#828]
Hello everyone,

I have successfully installed PTVS using python 2.7, and I was able to install opencv 2.4.11 in python. However when I do "import cv2" in PTVS it does not recognize cv2. Therefore, I was wondering how I could import and use opencv in PTVS. Opencv is installed in visual studio c/c++ as well.

Thanks for your efforts !!!!

**Comment by zooba** [comment]
After installing, there is a refresh step that needs to be completed. Have a look at [the docs](https://github.com/Microsoft/PTVS/wiki/Editor-Features#intellisense) and see whether it is finished (or maybe hasn't been started automatically).
