### ISSUE TITLE
PTVS 2.2 VS 2013 setup failed.

### ISSUE THREAD

**Issue by trozean** [Microsoft/PTVS#843]
I have installed Visual Studio 2013 Update 5, and now i am trying to install PTVS 2.2 VS 2013 but it's showing "your version of Visual Studio 2013 is not supported please install the latest update from http://www.visualstudio.com/.". Please help, i am a new user.

**Comment by andygraham** [comment]
Which version of Visual Studio 2013 are you using? I guess it might be Express for Windows. You need a full version of VS 2013 or Community, Desktop Express or Web Express to use PTVS. See the "Installation Instructions" in the wiki here

https://github.com/Microsoft/PTVS/wiki

**Comment by trozean** [comment]
yea mistakenly i have had download VS for windows, i should download for desktop. Thank you for suggestion. That was my mistake not any error.
