### ISSUE TITLE
How to add python 3.4 to Python Environments in VS15? 

### ISSUE THREAD

**Issue by heathyates** [Microsoft/PTVS#856]
Please see the screen shot below. Where can I obtain Python 64-bit 3.4 for my Python Environments? It seems VS2015 only installed Python 2.7. 

![pythonrepl](https://cloud.githubusercontent.com/assets/1896424/10203619/c33baab8-677c-11e5-821a-da6471c60d64.JPG)

I checked the PTVS documentation and issues created in the past. As far as I know, it has not been discussed how to add 3.4 to the environment. If possible, can someone please lend a quick hand. I know I am making this harder than it is. Thanks.

**Comment by zooba** [comment]
Check out our [installation instructions](https://github.com/Microsoft/PTVS/wiki/PTVS-Installation).

In short, VS doesn't install any versions of Python, so you'll have to find and install them yourself. There are instructions and links on the above page.

**Comment by heathyates** [comment]
@zooba Thanks for your quick reply. I have already checked this out.  Do you meant the interpreters part of that documentation? See below: 

![image](https://cloud.githubusercontent.com/assets/1896424/10203784/b43fcbe2-677d-11e5-8f43-de6db57732ff.png)
