### ISSUE TITLE
(i)python interactive lacks completion... and magic commands

### ISSUE THREAD

**Issue by sylvain-bougnoux** [Microsoft/PTVS#858]
In standard ipython (and python as well) I can type the beginning of a command and then the up-key. All the previous commands starting with these characters will loop. I found it particularly useful.
However PTVS does not have this feature, 
I am wondering what kind of ipython/interpreter is integrated, is it a subset of it, the regular one, or some commands are caught-up by the VS interpreter (as ENTER before the last character).

Same idea: %rep ... is a non sense within PTVS, !ls does not work... 
Before investigating you'd better clarify what is the subset of %magic commands that do not work?

Thanks

**Comment by zooba** [comment]
The history search feature is available, but it's bound to different keys by default. If you open Tools/Customize/Keyboard and look for "Search History" then you'll find the commands and either see what keys will trigger it (Alt+Left, Alt+Right IIRC) or change them to whatever you like.

For magic commands, we pass those through to the IPython kernel that is running on your machine. This means that many of them will work, but as you point out not all of them are relevant.

Bang commands such as `!ls` are actually sent to the shell (`cmd.exe` on Windows), so you can only use commands that work in a regular command prompt. `!dir` should work fine. (Alternatively, I believe there's a `%ls` magic that works correctly cross-platform, even on systems that don't have an `ls` command.)

**Comment by sylvain-bougnoux** [comment]
Thanks but it is "SearchHistory" no space. Now it works.

Just a question, what are the options "Arrow Keys use smart history" we have in "Options/Python Tools/Debug Interactive Window" and in "Interactive Windows".

Just another small issue on history. From an empty prompt when pressing up, it goes to the previous command, but when pressing down just after it does not go back to the empty prompt.

Thanks.

**Comment by zooba** [comment]
The smart history option, when enabled, lets you use normal Up/Down keys to navigate history when you're at the end of an entry. If you disable that option, you have to use Ctrl+Up/Ctrl+Down to navigate history and regular Up/Down navigate the current item.

I think that history issue will be resolved in VS Update 1.
