### ISSUE TITLE
Changing environment from 2.7 to 3.5 doesn't work without closing and re-opening solution

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#867]
- Create a project
- Set environment to a 2.7 environment
- Add a new environment, choose 3.5
  *\* In Solution Explorer, under Python Environments it now shows that the project is set to 3.5, and right clicking the Project and choosing Properties confirms this.
- Intellisense is not updated accordingly and still claims that 3.5 specific functionality is a syntax error, and running the program still uses the 2.7 environment.

**Comment by zooba** [comment]
Should be fixed
