### ISSUE TITLE
Show completion list after a character is typed

### ISSUE THREAD

**Issue by TimeArrow001** [Microsoft/PTVS#869]
Thanks for adding the code collapse feature I advocated for in the latest major version. It;s really an extremely helpful feature.

Can we also have an intellisense feature similar to C#, i.e., "Show completion list after a character is typed"?

This can be really a productivity enhancing, which also avoids "undefined variable" error due to typos.

We had an old plugin (Python Intellisense Enhancer) exactly for this purposes which cease to support VS2015 unfortunately.
https://visualstudiogallery.msdn.microsoft.com/644b4359-5eeb-4ba5-9374-78a8507761f0

And almost all other IDEs support this feature OR variable definition check.

Thanks.

**Comment by TimeArrow001** [comment]
![ptvs](https://cloud.githubusercontent.com/assets/14990108/10299840/d0dac866-6bb4-11e5-9f06-80029b89c89b.PNG)

**Comment by zooba** [comment]
It's here (and should be on by default):
![image](https://cloud.githubusercontent.com/assets/1693688/10300020/35a71ccc-6ba6-11e5-807e-d352b8020822.png)

We don't display it automatically in a few places, since it's often more annoying than useful. Notably, you don't get it at the start of a line, since we found that it makes the editor basically unusable (though at some point we may make it pop up but not automatically select items, similar to when typing the first item in lists).

If you've been trying just typing single letters on a blank line, try writing `x = <single letter>`.

**Comment by TimeArrow001** [comment]
Thanks for the quick response.

Indeed, I've been trying to let the completion to pop out on the left hand side of assignment with no success. 

thisVariableNameIsVeryLong = []
thisVariableNameIsVeryLong.append('NoCompletion')

I would suggest that, if the cursor is at the start of line, this completion of identifier gets triggered after a long sequence (say 5) of characters have been keyed in, rather than gets completely disabled.  This way, the editor won't display a lot of random information when we try to define new variables, but is also able to 'intelligently' help us find old variables. A filtered list triggered after 5 characters usually tends to be very short and accurate, and editor performance won't suffer that much.

Or, it would be really nice to have automatic detection feature for unused variable or undefined variable, just like what Spyder IDE does.

**Comment by zooba** [comment]
We're certainly keen to support the last part - we already have all the information in our code analysis about whether you're defining a new variable or using an existing one, we just haven't had time to expose it through the editor (it's actually harder than I make it sound...).

The likely behavior we'll go with at the start of the line will be the same as when you start typing `[x` - the "first" element in a list could be a comprehension expression, so we don't force-commit the suggestion, but you can use Enter or Tab (or the mouse) to select it.
