### ISSUE TITLE
Support encoding in scripts

### ISSUE THREAD

**Issue by Zygonie** [Microsoft/PTVS#878]
Related to the #875 issue, PTVS does not like encoding in Python source code.
Specifying the encoding with `# -*- coding: utf-8 -*-` prevents scipt debuging from stopping at a breakpoint and also prevents file from opening without specifying to open with the `Python Editor with Encoding` (right click on the py file)

**Comment by zooba** [comment]
I can't reproduce this issue - we should properly support coding comments (and certainly handle utf-8 and utf-8-sig correctly).

What is the actual encoding of the file? Is it UTF-8 without a BOM?

**Comment by Zygonie** [comment]
Hmmm very strange. After the fix from my side (removing encoding header and special characters), I tried to restore the failing code version but I did not experienced the issue firstly observed....
Sorry for that, I'll give more details if I have the issue again, because the strange fact is that is was on two different machines the same issue.

**Comment by zooba** [comment]
Depending on what encoding Visual Studio thinks your doc has when you open it, you may get different encodings of the same characters. I'd guess you're probably adding the characters back outside of VS (in which case it's up to whatever editor you're using), but that may be the cause.

Python in general does not work if the encoding does not match the coding comment, and while VS takes the comment into account when opening files, not every other editor will.
