### ISSUE TITLE
Support code cells

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#88]
One thing to keep in mind is that Spyder or MATLAB go one step further: for interactive scripting, you break your script into sections using special comment markup (#%% in Spyder or %% in MATLAB). Then no matter where in the code section the cursor position is, the whole section can be executed with a keyboard shortcut. This has several advantages: it is very fast as there is no need to select a region of code. Also selecting exactly the same region of code repeatedly can be distracting and very boring. In addition, when you select a region of code you could accidentally press a "wrong" key and lose the code! Then you will have to press Undo, etc etc. 

 So I guess a more complete proposal would be to adopt or including a similar feature to Spyder's "Code Cells" (the #%% comment markup) in addition to the "Execute cell" and "Execute and advance to the next cell" command and the respective short-cuts. 

https://pythonhosted.org/spyder/editor.html

We can go beyond REPL support here and also support some visuals for these cells (e.g. adorn them with a border, maybe add some other visual effects to emphasize the boundaries). 

(Migrated from https://pytools.codeplex.com/workitem/3018 and http://pytools.codeplex.com/discussions/581641#post1398987)

**Comment by nidleo** [comment]
I very much agree. Running code cells is crucial for on-the-fly development of anything beyond one liner toy code. 
It enables editing a complex piece of functionality, possibly depending on the outputs of previous "Code Cells", and re-running it as you go with a single key shortcut. I just cannot be as productive without it.

**Comment by chanansh** [comment]
agreed

**Comment by bordingj** [comment]
This feature would make me switch from Spyder to PTVS

**Comment by zooba** [comment]
I might take you up on that :)

![image](https://cloud.githubusercontent.com/assets/1693688/16633885/2071a9f0-4380-11e6-9f43-8a546ea5987e.png)

**Comment by bordingj** [comment]
Awesome! When will this be released ?

**Comment by zooba** [comment]
We'll put out a dev build tomorrow that has the change, but it won't be properly released until Visual Studio "15" (name still TBD). (Currently we're only planning to release for the next version of VS, but the dev build should work fine with VS 2015.)

**Comment by denfromufa** [comment]
@zooba ipython notebook can export .py files with cell metadata in comments starting # In[XX]:. any chance this could be supported in addition to #%%?

**Comment by zooba** [comment]
@denfromufa Yep, that's easy. We just have a regex for checking the line contents, so that can be extended.
