### ISSUE TITLE
Auto-indent not working in interactive window + extra new lines

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#880]
PTVS 2.2.1 (2.2.31007.01)
VS 2015 Update 1 RC 24606.01
Define the bar function in interactive window.  Compared to PTVS 2.2.0, you will be forced to tab after hitting enter.  Also, extra new lines appear every time you hit enter.

```
>>> def bar():
... 
...     print('bar')
... 
... 
>>> def baz():
... 
... print('baz')
... 
... 
  File "<stdin>", line 3
    print('baz')
        ^
IndentationError: expected an indented block
>>> 
```

**Comment by zooba** [comment]
This should be fixed by #883
