### ISSUE TITLE
Break points bring up a "This application is in break mode" and doesn't break in source

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#882]
PTVS 2.2.1 (2.2.31007.01)
VS 2015 Update 1 RC 24606.01

Python 3.5 64-bit virtual env
Bottle project
Put breakpoint in routes.py about() method
F5 with Microsoft Edge browser selected
Browse to about page
You'll see this:

![breakmode](https://cloud.githubusercontent.com/assets/1696845/10380954/0ea33d0e-6dcc-11e5-927d-15d8388ca31e.png)

Debug interactive works, but call stack doesn't appear (see pic).

**Comment by huguesv** [comment]
It's a VM with defaults for everything in VS, except for auto-indent set to None for Python.

**Comment by huguesv** [comment]
Bug went away in VS 24613.01 & PTVS 2.2.31014.03

**Comment by qiansen1386** [comment]
Could anyone remove the stupid "Break mode" page??
