### ISSUE TITLE
VS2015 cannot run IoT Core Python background task.

### ISSUE THREAD

**Issue by NNM11** [Microsoft/PTVS#887]
Create a PTVS - IoT Core Background App with simple code: print('hello world')
1. Set the remote device IP address for the IoT Core MBM (build 10531).
   The VS2015 Enterprise reported "The debugger cannot continue running the process.  Unable to start debugging?
2. Project report "unknown Python 3.5", 

Load the Blinky-Headless python sample, got the same error.  
VS2015 run fine for C#, Node.js, C++ projects.
![2015-10-12](https://cloud.githubusercontent.com/assets/12702095/10441277/f92266d4-70fb-11e5-9c89-39d40d538c9c.png)

**Comment by zooba** [comment]
Ping @alanch-ms - have you seen this issue?

**Comment by alanch-ms** [comment]
@NNM11 - By any chance, did you install the "Python UWP SDK (pyuwpsdk.vsix)"?  If not, you can install it from <https://github.com/ms-iot/python/releases>.  See the "Set up your PC" section on <http://ms-iot.github.io/content/en-US/win10/samples/PythonBlinky.htm> for details.

**Comment by NNM11** [comment]
I installed the pyuwpsdk.svix file through double-click and Open with...  It appears the installation was not succeeded.  It was quite and the document did not say what extension was installed.
I have to open a "VS2015 cmd prompt" in Admin mode and type the command "SVIXXInstaller pyuwpsdk.svix" installed it.  - This should be added to the instruction as a back up.

Once this installed, I was able to create IoT Core Background project.  However, there is a new problem with installing "pip" for the "Python 3.5 UWP" environment.  The error VS2015 reported error when I select "download and install pip package manager" .  Without pip installer, the UWP python projects can not import existing libraries to reuse.

![image](https://cloud.githubusercontent.com/assets/12702095/10552647/180a2594-740a-11e5-9b01-845f210bd34a.png)


----- Installing pip -----
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudioTools.Project.ProcessOutput..ctor(Process process, Redirector redirector)
----- Failed to install pip -----

**Comment by zooba** [comment]
This is something that we still haven't fully resolved yet. I don't recall what the recommended procedure for adding external packages into an IoT project is, but it's likely to require some manual effort right now.

After creating the project, are you able to build and run?

**Comment by NNM11** [comment]
I could create a BackgroundApp project to do simple print("hello world") stuff to run.   
The debugging (step over) is very slow though.

Please post procedure for manual import python packages if you have one.  But getting the PIP to function likes the npm for node.js is an ideal thing.

**Comment by alanch-ms** [comment]
>The debugging (step over) is very slow though.
This is a known issue.  I just checked in the fix for that yesterday.   As a workaround, you can hide your 'auto' and 'watch' window by default, the debugger will be more responsive.  The 'local' window is okay though.
