### ISSUE TITLE
Sys.Exit not working

### ISSUE THREAD

**Issue by AwesomoBeard** [Microsoft/PTVS#888]
Hi
Using Visual Studio 2015, with Python 2.7.

 if event.type == QUIT:
                pygame.quit()
                sys.exit()

On the sys.exit() line, I get the message "SystemExit was unhandled by user code"
I don't get this message if I use IDLE.
Is there a different way I should use to exit for VS2015?
Thanks

**Comment by zooba** [comment]
There's an option (under Tools, Options, Python Tools, Debugging if I recall correctly) called "Break on SystemExit exception with exit code of zero". If you unselect this, `sys.exit()` should no longer break. It should be unselected by default.

There is also [exception settings](https://github.com/Microsoft/PTVS/wiki/Debugging#exceptions) where you can customize whether we break on that exception or not. This is a heavier hammer, as it affects *all* places where your code may abort, but that may be desirable in some cases (and it's extremely useful for other exceptions).

**Comment by AwesomoBeard** [comment]
Hi
That box was already unselected for me. I ticked it and cleared it again, just in case, but it made no difference. I get the same error for when the box is ticked, and when its not ticked.

**Comment by zooba** [comment]
Hmm... seems we now have `None` being passed as `ex_value` here. It's a fairly simple fix to one of our files that you can do yourself, but I don't think I can get it into our next update (which is coming up very  soon).

The fix is in `visualstudio_py_debugger.py` which you'll find in our [install directory](https://github.com/Microsoft/PTVS/wiki/Where-is-PTVS-installed). Search for `SystemExit` and you'll find the code below:

```python
            if issubclass(ex_type, SystemExit):
                if not BREAK_ON_SYSTEMEXIT_ZERO:
                    if ((isinstance(ex_value, int) and not ex_value) or 
                        (isinstance(ex_value, SystemExit) and not ex_value.code)):
                        break_type = BREAK_TYPE_NONE
```

Change it to:

```python
            if issubclass(ex_type, SystemExit):
                if not BREAK_ON_SYSTEMEXIT_ZERO:
                    if (ex_value is None or
                        (isinstance(ex_value, int) and not ex_value) or 
                        (isinstance(ex_value, SystemExit) and not ex_value.code)):
                        break_type = BREAK_TYPE_NONE
```

And you're set! There are a couple of other places we need to update as well, but this is the one that is causing your issue.

**Comment by AwesomoBeard** [comment]
Em, this caused me a bit of a problem. 
My computer now blue screens when I exit Python programs. 
Code below, I'm using Windows 8.1 and Visual Studio 2015 Enterprise 2015.


        if break_type:
            if issubclass(ex_type, SystemExit):
                if not BREAK_ON_SYSTEMEXIT_ZERO:
                    if (ex_value is None or
                        (isinstance(ex_value, int) and not ex_value) or 
                        (isinstance(ex_value, SystemExit) and not ex_value.code)):
                        break_type = BREAK_TYPE_NONE

        return break_type

**Comment by AwesomoBeard** [comment]
Actually, ignore the above, seems to be working fine now that I rebooted. Possibly just a coincidence.
