### ISSUE TITLE
IDE (debug/view/edit) function if code loads via import hook (not on filesystem) ?

### ISSUE THREAD

**Issue by technomagos** [Microsoft/PTVS#892]
Hi

First, well done for a great tool  - keep it up!

Qeustion: Could PTVS work (or be made to work easily?) in a scenario where the python importer is hooked (as per PEP 302: https://www.python.org/dev/peps/pep-0302/) . So that certain set of modules actually loaded and evaluated on the fly, and do not exist on the file system. E.g. loading could be via a remote connection or e.g. extracting from a zip file, on demand.  How in that case, would one view (possibly edit inplace, no files) and debug scripts (local or remote) in such a scenario? 

If this is not possible now, could you suggest how it could be made possible and how much effort that could be? Perhaps if PTVS interfaces directly to the running (hooked) python importer to get to the blocks of code, it the work for case where modules are on file system or hook-loaded.

Thank you

**Comment by zooba** [comment]
Yes, it's possible. Visual Studio supports downloadable sources, and we'd need to add new messages to the debugger to be able to respond with a copy of the source (from `inspect` probably) if VS can't find it.

I would like to be able to do this, and there's a chance we'll be able to make it happen for our next big release (when we'll likely heavily revamp the debugger), so I'll add it to the milestone.

**Comment by huguesv** [comment]
ptvsd 4.x has the ability to send code back to the ide.
