### ISSUE TITLE
Web role failure when loading existing cloud service solution

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#896]
Create new Azure cloud service project
Select a flask web role
Save & close solution
Reopen solution
Notice the warning sign on Roles node in solution explorer
Attempting to publish gives a "Sequence contains no element" error

In the screenshot below, I had published immediately after creating the solution.  I then closed and reopened, and tried to publish.

I tried using C# Azure Cloud service project with MVC ASP.NET web role, closing and reopening, but it didn't repro there.

![roles](https://cloud.githubusercontent.com/assets/1696845/10501078/ae1bf540-7292-11e5-8b23-20e3ed112b7b.png)

**Comment by huguesv** [comment]
Can't repro after restarting VS.  It might be that publishing is one of the required repro steps.  I'll try that again.

**Comment by zooba** [comment]
There's a serious amount of moodiness involved with cloud service projects, unfortunately... this is probably just that. Reopening the solution and/or VS normally resolves it - I think there are some race conditions in initialization.

**Comment by huguesv** [comment]
Yeah, it repro'd if I do a publish, but I don't think it's worth investigating, as this is unlikely to be in our code.

**Comment by zooba** [comment]
Reproing with a debugger attached to see what exceptions are being swallowed is probably a good idea though. Hopefully AT is installed on my test machine by now, so I can do that.

**Comment by zooba** [comment]
I can't seem to reproduce this. Hopefully for 3.0 this issue will be redundant anyway, as I really want to revamp deployment as part of cloud service (probably based on how [VSO does it](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/AzureCloudPowerShellDeployment/Publish-AzureCloudDeployment.ps1) or maybe in an azure-based Python library).

**Comment by VolodymyrGladchenko** [comment]
After installing Azure App Service Tools v 2.9.6 have the similar issue:

Notice the warning sign on Roles node in solution explorer
Attempting to publish gives a "Sequence contains no element" error.

Pleas, describe what data do you need to proceed with that bug ? Otherwise I would try to use older release without that bug ...
