### ISSUE TITLE
PTVS installs properly in a hive, but cannot create Python project

### ISSUE THREAD

**Issue by dpacbach** [Microsoft/PTVS#904]
Hi there,

I have successfully downloaded the PTVS 2.1 source code and built the solution in Visual Studio 2013.  I generated a key, put it in the assembly files, then produced a vsix package.  Then I successfully installed it into a hive named testenv.  When I open VS in that hive I can see the Python Tools menu and everything seems to work well (repl, debugging, etc.).  When I go to the Extensions window I can see PTVS listed there as an installed extension.

However, I have a problem that it will not allow me to create a Python project.  When I go to the New Project window and select "Python" I see the "Get Python Tools for Visual Studio" in the center window, then when I type in a name and click OK it creates a new project, but it's a C# project!  Why can't I create a new python project?  Do to the nature of my project I cannot install PTVS into the default VS instance, it has to remain in a hive.

Thank you
David

**Comment by zooba** [comment]
So the "Get Python Tools for Visual Studio" template is part of the main VS install, so if you can't modify the global install it will just have to remain there (our MSI is responsible for removing it). It is supposed to open a web page with a download link, and has to work without PTVS being installed so we went with C#. (For VS 2015 we replaced it with a new built-in system that is much better.)

There should be actual projects listed below that, and if not, then your templates are not registered correctly. This was fairly common for non-default hives with VS 2013. You may also need to run `devenv.exe /setup /rootSuffix testenv` (or possibly swap the argument order... the argument parsing code is very naïve).

You are also likely to have to adjust the templates in source code, as (IIRC - 2.1 was a while ago for me) they expect to find MSBuild targets files in a shared directory. Again, our MSI would normally place these correctly, but you'll have to make changes to your projects to find them elsewhere (which will also make your projects incompatible with other PCs running our official release - just a heads-up).

One of our aims for PTVS 3.0 is to reenable per-user installs (which inherently enables non-default hives), but PTVS 2.0 through 2.2 are generally not compatible. I suspect your current issue is entirely to do with template registration, but you will encounter more issues as you progress.

**Comment by dpacbach** [comment]
Hi zooba,

Thanks for the quick response.  I did some googling and it appears that to fix template registration it looks like I'll have to modify the registry?

https://msdn.microsoft.com/en-us/library/bb165750.aspx

Or do I have to modify any files in the solution?  I saw some files in the PythonTools project that appear relevant, such as:

PythonTools/Templates/Files/EmptyPyFile/empty.vstemplate
PythonTools/Templates/Projects/FromExistingCode/FromExistingCode.vstemplate

However I didn't see anything in these files that looked like it could be changed (public key?)... am I missing something?  How does one register templates?  My users will be running an installation script written by me, so I can easily add additional steps to it if necessary.  Thank you

David

**Comment by zooba** [comment]
You shouldn't need to modify the registry - the `devenv /setup` command I gave you above will do that - but it's possible that it doesn't work correctly with a non-standard hive. Generally only the default and experimental hives are well tested.

It's possible that the vsixmanifest needs to be updated if you intend to run out of that directory structure - normally we install to the global directories and so it doesn't matter, but if it doesn't specify the right directories here then the templates may not be found.

**Comment by dpacbach** [comment]
Hi zooba,

I did some searching and, sadly, it looks like one needs to run devenv /setup as administrator for it to work?  Indeed when I run it either in my testenv hive or in the Exp hive I get a permission error either way (Access Denied).  I'm trying to set this up for my team but the entire process must be done without admin rights... would really be nice to get it working somehow!

Actually -- is it possible just to pre-generate an empty python project file and then open it in the testenv hive even if the corresponding template is not registered?  If so then this would be doable as I could add into the end-user instructions that if they want to create a python project they simply have to clone an existing one (better than nothing).

By the way I also looked into the vsixmanifest files output by the build but I didn't see anything in there that looked like it could be modified (though I'm not familiar with the contents of these things).

Thanks again,
David

**Comment by dpacbach** [comment]
Update: looks like I can indeed import an existing python project file into the solution in the hive, and so far it appears to work.  So I can use this as a workaround if there is no other way.

**Comment by zooba** [comment]
Yeah, opening a project is probably fine. Strange that templates aren't working.

IIRC, in 2.1 we had an extra pkgdef file in PythonTools called `VsTemplate<something...>.pkgdef` that was meant to help debugging. It may be that you need to include that file (and maybe update it somehow? I forget what the contents looks like) to run from a custom hive. Shouldn't have to do anything except be in the install folder.
