### ISSUE TITLE
have multiple start params

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#906]
I'm constantly going back and forth in a project and adding different command-line arguments depending on what script I want to run.  I save all my command line arguments within a text file because ptvs only supports one set of command line arguments passed to a python script, and only one can be designated as the startup script.  Is there a way to run any script I want and store it's command line arguments separately from others?

**Comment by crwilcox** [comment]
Currently there is no way in PTVS to do this. A project is meant to be runnable and the place where you enter args is meant for debugging the project. There are some ways I can think to accomplish what you want though.

1) Create a separate project file for each script you want to run.  This would allow you to change the startup project and then run the corresponding script.  This might be a bit ridiculous.
2) Create a script that can run any of your scripts and have that be what you point to with VS.

There are likely a few other workarounds, but I would just do 2.  That would give you a single file that is run and it could just run whichever one you need at the time and just comment out the others. There are fancier ways but this is the most simple way I can think to stop you from just using a text file.

RunScript.py (set this as the startup file)
```
# AScriptToRun.main("arg1", "arg2")
# AnotherScript.main()
TheOneRunningNow.main()
```

**Comment by sma202** [comment]
How can I have Vs point to the script if I go with #2?

**Comment by zooba** [comment]
Dup of #659, but feel free to keep discussing workarounds for now.
