### ISSUE TITLE
search paths broken in - Dev Build - 2015-08-21

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#907]
After installing the "Dev Build - 2015-08-21" build, my projects can't find modules I have added to the reference "the search paths".  I've tried removing, reinstall visual studio and still having the same issues. Interestingly, type "import mymodule" in the python interactive window  works and intellisense seems to work too.  When I debug or run, it says "importerror: no module name mymodule"

**Comment by sma202** [comment]
Also, vs 2013 with my old version of python tools works fine 2.2.2

**Comment by zooba** [comment]
Search paths have been completely rewritten for VS 2017, so I assume this issue no longer applies.
