### ISSUE TITLE
PTVS causes the VS to crash while loading Django Project

### ISSUE THREAD

**Issue by uadnan** [Microsoft/PTVS#908]
Every time I tries to load Django project, VS runs for few seconds with loaded project and high CPU usage. After that Windows Crash Reporting service came into action and VS closed unexpectedly.

Activity Log and diagnostics info is here: https://gist.github.com/uadnan/f6ec02eebf10d4ea5950

**Comment by zooba** [comment]
It looks like some of the assembly paths are not correct, which normally indicates that VS needs repairing (or that you're developing PTVS itself).

If VS crashed, then there should be extra information under Tools, Python Tools, Diagnostic Info. Could you create a [gist](https://gist.github.com) and copy that output into there? It's generally too long to put on an issue directly.

**Comment by uadnan** [comment]
I've creates gits with Diagnostics Info & Activity Log here https://gist.github.com/uadnan/f6ec02eebf10d4ea5950

**Comment by zooba** [comment]
So it looks like VS is corrupted, judging by the inability to find the `VsInteractiveWindow` DLL, but that shouldn't be causing your crash.

Are you able to open any interactive windows? I suspect those errors may have been temporary and we have something else going on.

**Comment by uadnan** [comment]
No interactive windows is opened. A snap of VS few minutes before crash is attached. Many times I submitted crash report to VS but that seems like caused by PTVS because everything else is fine & only this specific python project crashes.

I previously also got same issue but removing few one of models.py fixes the issue I can guess there is something wrong while handling circular imports during static code analysis done for intellisense. 

Might that helps to resolve this issue

![screenshot](https://cloud.githubusercontent.com/assets/8841282/10953166/6d55f556-8368-11e5-89cf-a1269c8521cc.png)

**Comment by zooba** [comment]
The crash reports should have appeared in the log you sent earlier, but since they didn't, can you look under Event Viewer and the Application log? You should see errors marked ".NET Runtime" and "Application Error" each time you had a crash. The details of these will help us diagnose what's going on.
