### ISSUE TITLE
Some MSBuild targets use wrong working directory

### ISSUE THREAD

**Issue by chausner** [Microsoft/PTVS#909]
My Django solution uses the following directory structure:

solution
solution\solution.pyproj
solution\solution.sln
solution\project
solution\project\manage.py
solution\project\project
solution\project\project\settings.py

To be able to run and debug the server I set in the project settings "Startup file" to "project\manage.py" and "Working Directory" to "project". Everything works fine except that the first time I press Ctrl+F5 to run the server, the build fails. If I press a second time Ctrl+F5 the server starts up correctly. After I make any changes to the files I again have to attempt to build two times until it succeeds.

I found out that the reason for the build failure is that PTVS runs "C:\Program Files (x86)\Python27\python.exe" -c "import project.settings as settings; print(settings.STATIC_URL)" in the background but from the wrong working directory. It should run from solution\project according to my "Working Directory" setting like the other Django commands do, but it runs from the solution root and consequently can't find the settings module.

In Microsoft.PythonTools.Django.targets I changed all WorkingDirectory="$(QualifiedProjectHome)" to WorkingDirectory="$(WorkingDirectory)" like in all the other commands in the file and it fixed my problem.

**Comment by zooba** [comment]
Don't suppose you'd like to create a PR and send us your fix? :)

**Comment by chausner** [comment]
Thanks zooba, consider it done.
