### ISSUE TITLE
Publish VS 2013, wfastcgi-enable setting

### ISSUE THREAD

**Issue by leonbrave** [Microsoft/PTVS#919]
Hi there Steve.

I'm a very enthusiast user with Flask/python, i made a project on Visual Studio 2013 with bootstrap templates and jade code. Now i'm trying to publish the project in a "Local" way before port to the main server (next step).

On this moment and after read a lot of documentation i pretty sure i'm very confused  with the steps for complete my objective.

what already done:

-Install the IIS features (all of them) in Windows 7
-Install wfastcgi with pip (the msi too... )

===================================================
The publish Web Configuration

method: Web Deploy
Server: localhost
sitename: C:\inetpub\wwwroot

validate connection --> "OK"

===================================================

When i press "Publish" Button all the files are copied to the wwwroot (i think that's the normal process), but an error displayed:

Details on VS13:

Auto ConnectionString Transformed web.config into obj\Release\CSAutoParameterize\transformed\web.config.
Copying all files to temporary location below for package/publish:
obj\Release\Package\PackageTmp.
Updating file (C:\inetpub\wwwroot\env\pyvenv.cfg).
Updating file (C:\inetpub\wwwroot\Myproject\views.py).
Updating file (C:\inetpub\wwwroot\web.config).
Updating file (C:\inetpub\wwwroot\web.debug.config).
Adding ACL's for path (C:\inetpub\wwwroot)
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(4274,5): Error : Web deployment task failed. (A value for the 'setAclUser' setting must be specified when the 'setAcl' provider is used with a physical path.)
Publish failed to deploy.

==============================================================================

another thing: the wfastcgi-enable, this file (and the disable and main file . exes) are into this folder 

"C:\Users\username\Documents\Visual Studio 2013\Projects\Myproject\Myproject\env\Scripts"

if i executed with "run as admin" the cmd consoles shows up and bring a "ensure your user has sufficient privileges and try again"

i need some advices with this problems, i'm trying to read and search solutions, but maybe i need to do additional steps.

I will be grateful for any help you can provide

pd: on IIS management>FASTCGI is added the wfastcgi.py

**Comment by leonbrave** [comment]
Update, now the Publish process don't display any errors...

but "localhost" doesn't display the app...

i add *.py on fastcgi config, there's something  i'm not doing on runserver.py, maybe???

thanks in advance

**Comment by zooba** [comment]
Can you post the `web.config` file from `C:\inetpub\wwwroot\web.config`? It's possible that we aren't configuring it correctly for a local deployment and you'll need to update some paths manually.

**Comment by leonbrave** [comment]
Hi, glad you ask

the web.config of the root folder, how to look like?
 here i post the different web.config

...
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
</configuration>
...


here is the code of the C:\inetpub\wwwroot\My_app\ web.config

...

<?xml version="1.0"?>

<configuration>
  <system.diagnostics>
    <trace>
      <listeners>
        <add type="Microsoft.WindowsAzure.Diagnostics.DiagnosticMonitorTraceListener, Microsoft.WindowsAzure.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" name="AzureDiagnostics">
          <filter type="" />
        </add>
      </listeners>
    </trace>
  </system.diagnostics>
  <appSettings>
    <add key="WSGI_ALT_VIRTUALENV_HANDLER" value="runserver.wsgi_app" />
    <add key="WSGI_ALT_VIRTUALENV_ACTIVATE_THIS" value="D:\home\site\wwwroot\env\Scripts\python.exe" />
    <add key="WSGI_HANDLER" value="ptvs_virtualenv_proxy.get_venv_handler()" />
    <add key="PYTHONPATH" value="D:\home\site\wwwroot" />
  </appSettings>
  <system.web>
    <compilation debug="true" targetFramework="4.0" />
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <handlers>
      <add name="Python FastCGI" path="handler.fcgi" verb="*" modules="FastCgiModule" scriptProcessor="D:\Python34\python.exe|D:\Python34\Scripts\wfastcgi.py" resourceType="Unspecified" requireAccess="Script" />
    </handlers>
    <rewrite>
      <rules>
        <rule name="Static Files" stopProcessing="true">
          <conditions>
            <add input="true" pattern="false" />
          </conditions>
        </rule>
        <rule name="Configure Python" stopProcessing="true">
          <match url="(.*)" ignoreCase="false" />
          <conditions>
          </conditions>
          <action type="Rewrite" url="handler.fcgi/{R:1}" appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
...

and there's another web.config from the VS2013 project folder

**Comment by leonbrave** [comment]
Hi, glad you ask

the web.config of the root folder, how to look like?
here i post the different web.config

here is the code of the C:\inetpub\wwwroot\My_app\ web.config
```xml

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
</configuration>

```
and there's another web.config from the VS2013 project folder
```xml

<?xml version="1.0"?>
<!-- Generated web.config for Microsoft Azure. Remove this comment to prevent
     modifications being overwritten when publishing the project.
-->
<configuration>
  <system.diagnostics>
    <trace>
      <listeners>
        <add type="Microsoft.WindowsAzure.Diagnostics.DiagnosticMonitorTraceListener, Microsoft.WindowsAzure.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" name="AzureDiagnostics">
          <filter type="" />
        </add>
      </listeners>
    </trace>
  </system.diagnostics>
  <appSettings>
    <add key="WSGI_ALT_VIRTUALENV_HANDLER" value="runserver.wsgi_app" />
    <add key="WSGI_ALT_VIRTUALENV_ACTIVATE_THIS" value="D:\home\site\wwwroot\env\Scripts\python.exe" />
    <add key="WSGI_HANDLER" value="ptvs_virtualenv_proxy.get_venv_handler()" />
    <add key="PYTHONPATH" value="D:\home\site\wwwroot" />
  </appSettings>
  <system.web>
    <compilation debug="true" targetFramework="4.0" />
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <handlers>
      <add name="Python FastCGI" path="handler.fcgi" verb="*" modules="FastCgiModule" scriptProcessor="D:\Python34\python.exe|D:\Python34\Scripts\wfastcgi.py" resourceType="Unspecified" requireAccess="Script" />
    </handlers>
    <rewrite>
      <rules>
        <rule name="Static Files" stopProcessing="true">
          <conditions>
            <add input="true" pattern="false" />
          </conditions>
        </rule>
        <rule name="Configure Python" stopProcessing="true">
          <match url="(.*)" ignoreCase="false" />
          <conditions>
          </conditions>
          <action type="Rewrite" url="handler.fcgi/{R:1}" appendQueryString="true" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>

```

**Comment by zooba** [comment]
So I'm guessing these paths are incorrect:

```xml
    <add key="WSGI_ALT_VIRTUALENV_ACTIVATE_THIS" value="D:\home\site\wwwroot\env\Scripts\python.exe" />
    <add key="PYTHONPATH" value="D:\home\site\wwwroot" />
      <add name="Python FastCGI" path="handler.fcgi" verb="*" modules="FastCgiModule" scriptProcessor="D:\Python34\python.exe|D:\Python34\Scripts\wfastcgi.py" resourceType="Unspecified" requireAccess="Script" />
```

You can override them by manually editing your project file and adding the following section:

```xml
<PropertyGroup>
    <DeployedPythonInterpreterPath>C:\Python34\python.exe</DeployedPythonInterpreterPath>
    <DeployedWFastCgiPath>C:\Python34\Lib\site-packages\wfastcgi.py</DeployedWFastCgiPath>
    <DeployedSiteRoot>C:\inetpub\wwwroot</DeployedSiteRoot>
</PropertyGroup>
```

(I just guessed what your actual paths might be - you may need to change them.)

Note that this will probably break deploying to Azure, so you'll have to remove the properties to do that. (Or maybe changing the first line to `<PropertyGroup Condition="$(Configuration) == 'Debug'">` will be enough - we haven't tested this.)

**Comment by leonbrave** [comment]
ok, i will edit this, i think the settings are ok, i'm starting with a very simple example app, if works i will apply to my main project.


thanks for the help!
