### ISSUE TITLE
Unit test debugging - Error occurred connecting to debuggee

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#921]
I still get this error periodically, and I don't think we have an open bug for it anymore.

Last seen on PTVS 2.2.31016.00, VS 14.0.24620.00 Update 1 RC.

When you do a Debug Test, you sometime get this in the output window.

```
------ Run test started ------
Error occurred connecting to debuggee.
========== Run test finished: 1 run (0:00:14.7584065) ==========
```

**Comment by papadi** [comment]
I get this all the time... :(

**Comment by weitzhandler** [comment]
Hi,

I'm still facing this issue.
I'm unable to debug TS tests. As soon as I try to debug a test I get the aforementioned error.
