### ISSUE TITLE
Setting a breakpoint on a "declarative" line should move the breakpoint forward

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#925]
Consider this code:

    def foo():
        global bar
        print(bar)

If you set a breakpoint on the `global bar` line, PTVS will happily do this for you.  Everything looks fine, until you run the code, and the breakpoint never gets hit.  Obviously this is because there is no code associated with the line `global bar`, it just affects name lookup.  PTVS should detect this and when you try to set the breakpoint via F9, it should push the breakpoint forward to the print statement.

**Comment by zooba** [comment]
#207 is basically the same issue. We'd really need to determine and somehow build in the rules of which part of a statement is executable to do this at design time, but once we start running and get into the actual function it should be easier.
