### ISSUE TITLE
Debugging code that uses libmproxy prevents the library from working correctly.

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#93]
libmproxy is a mitm proxy server packaged as a python library.  Using Python 2.7.9 and the RC of Python Tools 2.2, when I create a simple relay server that does nothing, only passes every request through, when attached via PythonTools the library hangs indefinitely when waiting for requests to come through.

Other curious behavior is that it takes an EXTREMELY long time (over a minute sometimes in my testing) just to import the libmproxy module.  It is very likely this is related to the other behavior, if there is code inside of libmproxy that depends on things happening within a certain time period, and the debugger is causing those assumptions to be false, then the library could be in an inconsistent state as a result.  To reproduce the long import problem, simply "pip install mitmproxy" on a fresh 2.7.9 Python installation, add one line of code:

```
from libmproxy import proxy
```

F5 with a breakpoint on that line, and then step over.  It will take a very long time.  The same statement run outside of a debugger is almost instantaneous.

To reproduce the inconsistent state problem, the following repro should do it:

```
from libmproxy import controller, proxy
from libmproxy.proxy.server import ProxyServer

class Handler(controller.Master):
    def __init__(self, host):
        controller.Master.__init__(self, host)

    def run(self):
        try:
            return controller.Master.run(self)
       except KeyboardInterrupt:
            self.shutdown()

    def handle_request(self, flow):
        flow.reply()

    def handle_response(self, flow):
            flow.reply()   # Put a breakpoint here

config = proxy.ProxyConfig(port=options.opts.port)
host = ProxyServer(config)
m = Handler(host)
m.run()
```

The breakpoint will never get hit.

**Comment by zjturner** [comment]
Also worth mentioning, the problem happens on both attach as well and Run under debugger.  So you can start without debugging, visit websites successfully while pointed at the proxy server (easiest way to test this is just change your phone's wi-fi to point its HTTP proxy to <hostname>:8080) and everything works fine.  As soon as you attach debugger it stops working.

**Comment by zjturner** [comment]
The slow import, and perhaps the underlying probelm that's causing all of these issues, is netlib.socks.  Instead of importing libmproxy, you can reproduce the slow import (which may or may not be what's also causing the library to not work correctly) with just

    from netlib import socks

This looks like a native module so unfortunately I can't step in further to diagnose.

**Comment by zooba** [comment]
The slow import doesn't occur any more, and the callback issue was probably because we were being prevented from hooking a thread (that library seems to be based on Tornado, which would explain that). I'm sure there's a more specific issue for the threading limitation, so I'll close this.
