### ISSUE TITLE
python profiling error

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#935]
When I launch Python Profiling on my solution, use the default "Open Project" rather than standalone scripts, then I get an error "Object reference not set to an instance of an object".  My script is already set to run as the startup script with all the command line arguments setup, it runs in debug mode.

If I manually select "Standalone Script" in the Python Profiling, then choose my script and add the command line arguments, then it works.

Please help.

**Comment by zooba** [comment]
Hi. I've been trying to reproduce this today and am not having any luck.

Could you give it a try with [PTVS 2.2.1 RC](https://github.com/Microsoft/PTVS/releases/tag/v2.2.1-rc) to see if it's been fixed already, or maybe share your project in case there's something in that?

**Comment by sma202** [comment]
The problem happens if the python module set as startup is in a sub folder relative to the project.  So if I have my module in myproject\com\util\test.py, then you get this error.  If it is located in myproject, then it works.

**Comment by zooba** [comment]
I can't reproduce this with our latest release, so guessing we fixed it at some point (I certainly made changes around here).
