### ISSUE TITLE
Store debug settings in the .pyproj.user file

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#936]
Closely related to #263 and #905 , for the purposes of relocating projects the debugger command line settings should be stored in the `.pyproj.user` file.  This is so that, for example, if you have the `.pyproj` checked into a repo you don't end up with git showing you have unstaged changes in the `.pyproj` file simply because you wanted to debug a script with a different set of command line arguments.  As far as I can tell, almost everything on the `General` and `Debug` pages should go into the user file.   (Maybe not the `Windows Application` checkbox, but I'm not sure exactly what that does)

**Comment by zooba** [comment]
Dup of #661.
