### ISSUE TITLE
Debug without project doesn't work

### ISSUE THREAD

**Issue by Marimout** [Microsoft/PTVS#940]
When I try to launch debug from a single file (without project), it doesn't work. I got the following exception:
"Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))"

However, if I include the same file in a project, it works correctly.

**Comment by zooba** [comment]
I believe this is already fixed (in [2.2.1 RC](https://github.com/Microsoft/PTVS/releases/tag/v2.2.1-rc) - released yesterday).

If opening the Solution Explorer window fixes it (you don't have to do anything except open the window through the View menu or by expanding it), then this has been fixed.

**Comment by Marimout** [comment]
Indeed, if the Solution Explorer window is opened, the error won't occur. Thanks for your answer.
