### ISSUE TITLE
Cannot import tkinter (Python 3.5)?

### ISSUE THREAD

**Issue by Catch21** [Microsoft/PTVS#941]
I'm new to Python (Visual Studio Tools for Python too though not for VS more generally (I'm using VS Community Version 14.0.23107.0 D14REL), and just starting a tkinter tutorial, so this issue is easily reproducible:

#from Tkinter import *
'''if you are working under Python 3, comment the previous line and comment out the following line'''
from tkinter import *
root = Tk()
w = Label(root, text="Hello Tkinter!")
w.pack()
root.mainloop()

If the environment is Python 2.7 (64 bit) (note the comment so I'm using Tkinter for 2.7) it works fine. But fails in Python 3.5 (64 bit) when I'm using tkinter line (correct usage) with following error messages:

Message: SyntaxError was unhandled by user code
Message: invalid syntax (tkinter.py, line 4)

Possibly related to vcruntime140.dll- see http://stackoverflow.com/questions/31952889/python-3-5-0b3-3-5-0rc1-how-to-make-tkinter-idle-and-turtle-work-on-windows (I tried the suggestion- move vcruntime140.dll- but no joy).

Related Qs:
1) Is it safe to use 3.5 (64 bit) (yet)? Or wait (but I don't want to learn 2.7)?
2) Any ideas on fix(es) (time line) and from whom (MS, Python)?

Really any help/pointers on this issue to someone new to PTVS (it's neat, I really like it) and Python? 

Thanks.

**Comment by zooba** [comment]
While Chris looks into the issue, I'll get the related questions:

1. It's safe to start testing products with 3.5 and for personal use, though I'd hold out for 3.5.1 before running any production code against it. Doesn't sound like you're in this category though, so it's fine to use. Python 3.4 is also perfectly good - there's no reason to use Python 2.7 (and it's easy enough to learn the differences later if you end up needing it).

2. Updates to Python come from www.python.org, and I'd expect 3.5.1 should be later this year. But I'm fairly sure Chris is going to give you a solution that doesn't require a fix to Python itself.

**Comment by crwilcox** [comment]
@Catch21, The issue here is that you are naming your file `tkinter.py`. Name your file (nearly) anything else and this will work. For instance `tktutorial.py`

Due to the way python imports modules you are attempting to reference yourself, not Tk, and it is failing. For a fun experiment, you can try changing the file name to `Tkinter.py` (uppercase T) and it will fail on 2.7 now.

Good timing by the way. This has been a topic of an active thread on Python-List as well as a lunch topic. ;)

**Comment by Catch21** [comment]
@crwilcox, thanks for reply. File name is actually hello.py, My (basic at present) understanding is that tkinter (that's imported with "from tkinter import *") is a (the?) GUI library that comes bundled with Python (Tkinter in 2.7, tkinter in 3.5). 

To duplicate what I mean save the code above as hello.py, then run using Tkinter from within PTVS using a Python 2.7 environment. It works. Switch to run using tkinter from within PTVS using a Python 3.5 environment and it doesn't. 

But if I run outside of PTVS using 3.5 (in IDLE say) it does works. Which would indicate there's nothing wrong with tkinter itself, rather something in PTVS's processing to run using a 3.5 environment.

Or to make it simpler, forget 2.7. Using 3.5 and tkinter, just run program (as hello.py say) both from within PTVS with a 3.5 environment and outside (I used IDLE and 3.5) and you'll see it runs outside PTVS but not when run from within it (I'm using 64 bit versions of 3.5).

**Comment by zooba** [comment]
The error message says you've got a file called `tkinter.py` that has an error in it. Find that file and rename it (it's probably in the same directory as `hello.py`) - it is interfering with your sample because it has the same name as the standard library module you are trying to import.

**Comment by Catch21** [comment]
@zooba, thanks for replies, and link to latest VS2015 build. 

There's no tkinter.py conflict but this did get me thinking of names. It turns out the project/solution within PTVS is called tkinter and this seems to be causing the conflict. If I set up a new project with a different name, and move hello.py to it, it runs fine.

Seemed logical (to me?) to name the project/solution with this name as its only purpose was to get familiar with using tkinter to build a basic GUI.

Thanks for all your help- appreciated.

**Comment by Catch21** [comment]
@zooba , @crwilcox - looking further at what's in the directory you're dead right. Not only is the project named tkinter, but there is indeed a tkinter.py in there named similarly. Mea culpa, of course there's going to be a conflict if your trying to import tkinter.py and you've a file called that in the directory you're calling it from- it'll never bother looking in the Python directory. I'm used to calling files with different extensions. Apologies for wasting your time and thanks again.

**Comment by xtaraim** [comment]
go lib\tkinter\_init_.py
remove unwanted 't'
from line no. 3372

**Comment by jae1324** [comment]
try to set anaconda module as a default module
![capture](https://user-images.githubusercontent.com/39914071/40922897-5fe75ca2-684e-11e8-97be-a3ce3212b6d9.PNG)
