### ISSUE TITLE
Loading Blinky for Python

### ISSUE THREAD

**Issue by pcopa** [Microsoft/PTVS#942]
I'm trying to install and run the Python Blinky Sample on VS2015.
After loading the solution file, I'm getting "error : Object reference not set to an instance of an object". 
And when trying to open the properties on the solution tab, I'm getting a slew of "An error occurred while loading the rule set file 'C:\Prog......" messages.
![ptvs-1](https://cloud.githubusercontent.com/assets/15312957/10860260/5e3fad12-7f3c-11e5-8b2c-1e2323a131cd.jpg)
Reinstalling VS2015 did not help

BTW Blinky for C# works fine.

**Comment by zooba** [comment]
Ping @alanch-ms. Seen this before?

**Comment by pcopa** [comment]
The same thing happens when starting a new Python BackgroundApplication.
![ptvs-2a](https://cloud.githubusercontent.com/assets/15312957/10860986/65709ed2-7f48-11e5-92ab-315f85c0a566.jpg)
![ptvs-2b](https://cloud.githubusercontent.com/assets/15312957/10860992/90d5ce6c-7f48-11e5-9d82-bc1d3d1dc223.jpg)

**Comment by alanch-ms** [comment]
Unfortunately, I haven't seen it before.  From the error message, it seem to related to static analysis instead of python.  Can you verify if the file, "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\Rule Sets\AllRules.ruleset" exists?  If it doesn't exist, I'm afraid your VS installation might be corrupted.

Also, please ensure that you have installed python, PTVS, and Python UWP SDK.  

•Install Python for Windows (3.*) from http://www.python.org/downloads
•Download and install PTVS (Python Tools for Visual Studio) VS 2015 latest release from here - https://github.com/microsoft/ptvs/releases
•Download and install the latest Python UWP SDK (pyuwpsdk.vsix) release from here - https://github.com/ms-iot/python/releases

**Comment by pcopa** [comment]
Thanks Alanchch-ms, the "C:\Program Files (x86)\Microsoft Visual Studio 14.0\..." directory was missing, so I decided to uninstall VS2015. This took me a long time because KB282970 crashed every time I tried to uninstall. I found some references to VS2013 so I uninstalled that too and then I could uninstall VS2015. 
After reinstalling VS2015 and all the programs you mentioned, I tried starting the BackgroundApplication (IoT) template and this came up.
![ptvs-3a](https://cloud.githubusercontent.com/assets/15312957/10871062/5e9d3cce-80aa-11e5-9ed4-70e589d42958.jpg)

My environment: Quad core Intel I7 with 16G ram.  My C: drive is a SSD 250G running windows. All my programs, including VS2015 and others, are installed on a normal drive D:.  

The program(s) mentioned in the error are indeed not on the C: drive but are on the D: drive. Could this be a clue?

**Comment by alanch-ms** [comment]
The BackgroundApplication4.pyproj mentioned in the error messages uses the following lines to import the "Microsoft.PythonTools.Uwp.targets" file.  

  <PtvsTargetsFile Condition="'$(PtvsTargetsFile)' == '' or !Exists('$(PtvsTargetsFile)')">$(MSBuildProgramFiles32)\Microsoft Visual Studio $(VisualStudioVersion)\Common7\IDE\Extensions\Microsoft Corporation\Python Tools for Visual Studio - UWP\$(PtvsVersion)\Microsoft.PythonTools.Uwp.targets</PtvsTargetsFile>

  <Import Project="$(PtvsTargetsFile)" />

It seems that the msbuild property $(MSBuildProgramFiles32) is pointing to "C:\program files(x86)".  Is "C:" or "D:" your system drive?  Did you manually change the install location of VS2015 to "d:"?  If so, this might be a bug in the python project template.  It shouldn't assume that VS is always installed in default location on the system drive.

As a workaround, you can modify line 55 of your d:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplatesCache\Python\Windows IoT Core\BackgroundService.zip\PythonBackgroundService.pyproj.  Replace the $(MSBuildProgramFiles32) with "D:\Program Files (x86)".   And make the same modification for line 6 of d:\program files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft Corporation\Python Tools for Visual Studio - UWP\2.2\Microsoft.PythonTools.Uwp.targets.

Restart VS and try to create python again.

Unfortunately, all the IoT samples online (ie. blinkyheadless, blinkyserver etc) are created based on the same template.  So you will need to make the same modifications before loading them in VS.

**Comment by pcopa** [comment]
C: is my system drive only running Windows 10. All other programs, that give me an option, I manually change from C: to D:. So VS2015 and Python 3.5 are installed on D:. All my personal files start out on C:\Users\Sxxx\AppData.......
Will try the change later, wordpad is not working for this.

**Comment by zooba** [comment]
It looks like assuming `$(MSBuildProgramFiles32)\Microsoft Visual Studio $(VisualStudioVersion)` is the installation path is incorrect. We should probably move the UWP targets into the shared MSBuild folder along with the other Python targets.

It may also be that Team Tools has the same bug. @pcopa - can you check whether `Team Tools\Static Analysis Tools\Rule Sets\AllRules.ruleset` exists under wherever you chose to install VS 2015?

**Comment by pcopa** [comment]
Yes found it at  "D:\Program Files (x86)\Microsoft Visual Studio 14.0\Team
Tools\Static Analysis Tools\Rule Sets"

**Comment by pcopa** [comment]
1) @alanch-ms  I was able to make the change to PythonBackgroundService.pyproj and Microsoft.PythonTools.Uwp.targets with notepad and am happy to say I can now create a new Python IoT project without any errors. Thanks

2) Loading the "PythonBlinkyHeadless.sln" in samples now reports "The project requires user input"
![ptvs-4](https://cloud.githubusercontent.com/assets/15312957/10890980/62b82930-8169-11e5-87d4-42f3375e22c1.jpg)

**Comment by zooba** [comment]
Typically reloading the project in this situation will display a more specific error message, either in a dialog box or the  Output window.

**Comment by alanch-ms** [comment]
I guess you missed the last part of my last message. :)
>Unfortunately, all the IoT samples online (ie. blinkyheadless, blinkyserver etc) are created based on the same template. So you will need to make the same modifications before loading them in VS. 

In this case, you need to modify the 4th line from the bottom.  Replace the $(MSBuildProgramFiles32) with "D:\Program Files (x86)".

**Comment by pcopa** [comment]
I did, but that was it.
If I continue with "Attach" and enter the remote and background info, I get:
![ptvs-4a](https://cloud.githubusercontent.com/assets/15312957/10891648/216356a4-816d-11e5-8fc3-116ebb0b2153.jpg)


And then entering attach again I get this:

![ptvs-4b](https://cloud.githubusercontent.com/assets/15312957/10891657/2c0abfca-816d-11e5-92f3-03d23f28c772.jpg)

**Comment by pcopa** [comment]
@alanch-ms Sorry, I missed your las message. I will make the changes first.

**Comment by pcopa** [comment]
@alanch-ms  OK much better now.  It ran once where I could click "Attach" and it loaded something, but then a second time the debugger won't start anymore and I get this when rebuilding: 
![ptvs-4c](https://cloud.githubusercontent.com/assets/15312957/10893453/d236de02-8176-11e5-91cb-7caecdadf0b6.jpg)
Is there another place to make the change for the UWP?

**Comment by pcopa** [comment]
I've given up on running the programs on the D: drive.   Everything is now re-installed with defaults on the C: drive and after a few hiccups, the programs are running as described.
Thanks for the help.

**Comment by zooba** [comment]
I'll reopen the issue, because we obviously have some issues here that need fixing. We shouldn't be forcing people to install in a particular location.
