### ISSUE TITLE
All environments disappeared, cannot add any

### ISSUE THREAD

**Issue by catusf** [Microsoft/PTVS#944]
Today when I triedto add a custom environment, VS crashed. When I restart VS, all environments disappeared, VS can no longer detect or add any environments.

How do I add an environment now?

My setup
- VS: 2015 Professional
- PTVS: 2.2 comes default with VS
- Python: Anaconda3-2.3.0-Windows-x86_64

**Comment by catusf** [comment]
The screenshot is as below.
![capture](https://cloud.githubusercontent.com/assets/2290127/10877995/89ed1006-817d-11e5-8431-4c97f34ebcaf.PNG)

**Comment by zooba** [comment]
That's a strange crash, but it looks like some files have become corrupted.

Under Programs and Features you should be able to see Python Tools for Visual Studio (even though it was installed with VS). If you run the Repair operation through that there's a good chance it will come back.

**Comment by catusf** [comment]
I did it, but issues remain. Even uninstall/reinstall Visual Studio does not help.

**Comment by zooba** [comment]
Can you open Tools, Python Tools, Diagnostic Info and post the contents as a [gist](https://gist.github.com) or to ptvshelp@microsoft.com?

**Comment by catusf** [comment]
@zooba Sure. Here you are https://gist.github.com/catusf/d88eed0dd7e5df51f236

**Comment by zooba** [comment]
Looks like that crash you mentioned managed to save some invalid data into the registry. Every time we reload it, it breaks again and so we fail to load the bits we need to manage custom environments.

You'll need to open Registry Editor and find `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\PythonTools\Interpreters`. Beneath this key you should find the info you added last time. You can either delete it and restart VS, or find the invalid path and correct it.

I'll look into making this more robust for our next update so it can't happen accidentally.

**Comment by catusf** [comment]
I deleted the key, and it works like a charm. Thanks so much.
