### ISSUE TITLE
Intellisense is broken in the presence of relative imports

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#949]
If you type this:

`from . import foo`

PTVS doesn't seem to understand this syntax.  After you write the `.` (note the space) you get an intellisense popup suggesting module names, so as you continue typing `import` it selects `importlib` and you end up with 

`from . importlib foo`

The modules that its suggesting in this intellisense popup are not located in the specified directory either it just seems to be all the modules in the search paths.  So I think PTVS simply has no concept of relative imports.

If you actually go and type out a valid relative import, it _is_ able to resolve it.  So something like

`from ..foo import bar`

if it is a valid module, you will have working intellisense on bar and no squigglies.  The problem seems to be isolated only to the case of typing the import statement.

**Comment by zooba** [comment]
The tricky thing here is that `from . module import ...` is totally valid, so we really need to interleave the `import` keyword here. (Turns out that `import` is not a usable module name, which is handy.)

**Comment by zjturner** [comment]
Ugh, I looked at the grammar of the import statement, you're right.

Yea in that case I guess you'd want to interleave the `import` keyword, but only if a space precedes  (because you can't write `from .import foo`, it has to be `from . import foo`)

But really just having some level of relative import support would be nice, even if there are some edge cases.  For example, if I type `from .` it would be nice if the IntelliSense popup was filtered to only those modules that are in `.`, and if I typed `from ..` it would dynamically update the list to only those modules that are visible in `..`, etc.

Of course, proper handling of the `import` keyword would make it even better.

**Comment by zjturner** [comment]
Has this bug been fixed?

**Comment by zooba** [comment]
You're right, it hasn't. We were a bit hasty closing this one and misread it (we did a really quick run over _all_ our old issues today to try and clean up a bit).

We get completions for members of relative imports, but once imported we lose any idea of what they are. We also don't properly handle the `. import` or `.<module>` cases.

**Comment by Jman420** [comment]
Any chance of an update on this issue?  This causes huge slow-downs for me during development time, needing to open modules I've referenced through relative imports in a text editor and make sure I am calling correct methods, attributes, etc.

**Comment by diryboy** [comment]
I got a lot of squiggles when I open [this file](https://github.com/fastai/fastai/blob/master/fastai/learner.py#L1-L14) from fastai folder in VS15 using Open Folder, is here the correct place to +1?

![image](https://user-images.githubusercontent.com/159110/40717018-7d10f028-643d-11e8-9422-7cf148d70267.png)
