### ISSUE TITLE
StopIteration is handled by the debugger when native code debugging is enabled

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#952]
If you do something like

``` python
for (a, b, c) in os.walk(foo):
    pass
```

And you have native code debugging enabled, the debugger will break due to a `StopIteration` exception being thrown.  Strangely, if native debugging is not enabled, the debugger will ignore this.

I'm not sure how it even propagates up outside of the call to `os.walk` anyway, but either way, something seems wrong here.

**Comment by zjturner** [comment]
Maybe this isn't specific to native debugging being enabled.  I just now got it on this line:

```python
        dont_do_dsym_test = dont_do_dsym_test or any(platform in target_platform for platform in ["linux", "freebsd", "windows"])
```

when native debugging was not enabled.

**Comment by int19h** [comment]
I believe we have breaking on `StopIteration` disabled by default in Debug -> Exceptions for this exact reason (it just occurs too much for perfectly valid reasons). Can you check to see if that is enabled, and that doing "Reset" on your exception settings disables it?

Note that for pure Python debugger, there is a distinction between handled and unhandled, but it should really be unchecked for both. For mixed-mode debugger, all exceptions are considered handled by default, because support for distinguishing them hasn't been implemented yet.

`StopIteration` should normally propagate out of `os.walk`, that part is correct - that's how the `for` loop knows that it's done.

**Comment by zjturner** [comment]
Here's an example of it happening with `GeneratorExit`.

![untitled](https://github-cloud.s3.amazonaws.com/assets%2F11823433%2F10956962%2Fddf27aae-8314-11e5-9abc-2459be36f4f1.png)

Even if it does propagate out of the `os.walk`, it shouldn't ever result in a debugger break because it's handled by the loop.  I'm not sure about the case I've attached here, I assume `GeneratorExit` is handled by `any()` so maybe it's a similar cause?

All the checkboxes in the `Exceptions` window are unchecked, btw.

**Comment by int19h** [comment]
The determination whether something is handled or unhandled is a heuristic at best - Python doesn't have the notion of first and second pass for exception handling, so the best we can do is look at the code on the call stack, parse it, and try to figure out if it will actually handle things. That said, we should be able to do it for straightforward use of `for`, it just isn't done yet (which is, again, why the exception is disabled by default).

This window in VS 2015 is misleading - it only shows you one checkbox that corresponds to "break if thrown". Every exception actually has two flags: one determining whether debugger should break every time it is thrown (regardless of whether it's handled or not), and another determining whether it should break when it's unhandled.

I'm not actually sure if there's an easy way to change the latter setting for exceptions in advance in VS 2015 - the old modal dialog in previous releases has both checkboxes side by side, but now there's only one, and I can't find any UI to show both. However, if you look at the pop-up notification for the exception, it will have that checkbox for that particular exception type ("Break when that exception type is user-unhandled"). The default for this exception type should really be to have that unchecked, but on your screenshot it is checked.

**Comment by zooba** [comment]
I believe you can add an extra column to the new exceptions window to allow changing that option. But it is only available if you have Just my Code enabled.

**Comment by zjturner** [comment]
Ahh, you can also right click the entry and there's a context-menu check item "Continue when Unhandled in User Code".  Which is confusing, because the on state of that checkbox is the opposite of the on-state in the popup window, but either way they're now both checked (on the context menu, not the dialog).
