### ISSUE TITLE
History search in REPL does not work

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#958]
Pressing Ctrl+Alt+Up/Down should search the REPL history to find entries with matching prefixes. However, this currently does not work - nothing changes about the current input.

This appears to repro with C# Interactive, so it may be their issues.

**Comment by shaggygi** [comment]
These combination keys make the orientation of my monitor change when using C# Interactive.  Anyone else seeing this using VS 2015 Update 1?

**Comment by zooba** [comment]
@shaggygi I'd guess that's an interaction between a global shortcut from your display driver and the VS shortcut. You probably just need to change one of them (VS's can be changed through Tools, Options, Keyboard, search for "search" and find the interactive ones).

**Comment by zooba** [comment]
Can't repro this outside of an RDP session, which seems to swallow the default keyboard shortcut.

**Comment by shaggygi** [comment]
You are correct, it was global shortcut from graphics.  Just disabled and feature now works in REPL.  Thanks!
