### ISSUE TITLE
Django shell REPL input 2 characters for every character typed

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#962]
2.2.31104.01
VS 2015 Update 1

- Create new Django project.
- On project node, right-click and Open Django Shell.
- Type 'import', you'll see 'iimmppoorrtt'

Note: arrow keys and backspace do not repeat.

This makes the Django shell is unusable.

**Comment by zooba** [comment]
We're throwing an exception when accessing `_bufferParser` in `IntellisenseController.cs` and it is null. In this case, we should just not trigger auto-listing.
