### ISSUE TITLE
Open command prompt here confused about selection?

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#967]
I have multiple environments setup in my project, but only the first one is installed.
When I select Command Prompt here on the one that's installed, it complains about one that isn't installed.

![command-prompt-env-not-found](https://cloud.githubusercontent.com/assets/1696845/10984285/318e51b6-83cd-11e5-9ee1-b3e5030dc2ab.png)

Interesting, I closed and reloaded the solution, and one of the Unknown Python 3.4 is bolded.  So it was picking up the one that is active instead of the one that's selected.  I couldn't tell before because the bolding is so unreliable...

**Comment by zooba** [comment]
`PythonProjectNode.cs` around line 1156 gets the current environment path to add to the PATH variable of the console window. We shouldn't be doing this in any case really, as the following line will get the "same" path from the correct environment.
