### ISSUE TITLE
Stepping doesn't work inside modules located via `sys.path`

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#975]
_Edit: I'm using VS 2015_

1) Create a Python 3.5 Debug interpreter and set your project to use it.  (I don't think debug interpreter is required for this repro, that's just how I'm set up)

2) Create a folder layout that looks like the following:

```
pytest
|__ pytest.py
|__ foo
    |__ bar.py
```

3) Now write the following code in these files:

``` python
# pytest.py
import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'foo'))

import bar
pass
```

``` python
# bar.py
import os
import sys
import functools
import importlib

print("This is a test")
pass
```

Set a breakpoint on the `import os` statement from `bar.py`.  Run `pytest.py` under the debugger so that the breakpoint gets hit.  Now press F10 or click the Step Over button on the toolbar.

The entire contents of the file are stepped over, and the instruction pointer moves directly to `pytest.py:6`, the `pass` statement.  The code is definitely executed, because you can see the `This is a test` printed to the screen.  Stepping just seems to be messed up for some reason.

**Comment by zooba** [comment]
Presumably we're detecting this file as being part of the standard library, so enabling the debugging option to allow stepping in the stdlib should allow you to work around this.

I thought we had fixed the issue where breakpoints and stepping didn't agree on this, as you shouldn't even be hitting the breakpoint there if we think it's stdlib. Are you using the latest dev build?

**Comment by zjturner** [comment]
Definitely using the latest dev build.  I turned on the option to enable debugging of the standard library.  I confirmed that this did in fact allow me to debug the standard library, but did **not** allow me to debug this file.  So maybe something else is going on.

**Comment by zjturner** [comment]
Ahh wait, you updated the dev build again 2 days ago.  So I'm not using the latest.  I will try again.

**Comment by zjturner** [comment]
Still doesn't work with the newest dev build.  Once I'm stopped at the breakpoint in `bar`, I can put other breakpoints in `bar` and they all work just fine.  It's just step that doesn't work.

**Comment by zjturner** [comment]
This also appears to work with Python 2.7, just not with 3.5

**Comment by zooba** [comment]
I think we have a category of bugs that summarise as "debugging doesn't work well within `import` statements", probably because of the way we filter the Python callstack when importlib is on there.

**Comment by zooba** [comment]
We have some longer term debugger improvements on the way that should handle this. No reason to keep this particular bug around.
