### ISSUE TITLE
Replace in Files not remembering skipped entries.

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/PTVS#98]
Pretty sure I've seen this work in VS, so assuming there's a plug-in part to this which might not be working.  I'm doing a 'Replace in Files' command in my Python folder.  

I've found something which I don't want to change, so I'm hitting 'Find Next', but after I Replace the next result, it jumps back to this result that I've already looked at and asks if I want to replace it again...

If I hit 'Skip File' instead, it behaves in the same manner.  I want it to continue going through to the other results, before it comes back to this one, which is the usual behavior.

**Comment by zooba** [comment]
Are you sure you've seen this work in VS? That functionality is completely file-type agnostic, and so we shouldn't be interacting with it at all.

Which version of VS are you using?

**Comment by hawkerm** [comment]
I'm using VS2013, wonder if it was 2015 that I remember.  Will have to try it out and if anything file a bug with VS ;).
