### ISSUE TITLE
Starting a new Python background solution

### ISSUE THREAD

**Issue by pcopa** [Microsoft/PTVS#982]
First of all, the "Blinky" sample is running fine and I can make changes.

Now I want to recreate this sample starting with a new project. Till now I only have 2 lines and i'm stuck.

print  ("/// Test 1 ///")
import _wingpio as gpio

After hitting F5, I get this:

====
The program '[4032] backgroundTaskHost.exe' has exited with code 0 (0x0).
/// Test 1 ///
Traceback (most recent call last):
  File "visualstudio_py_remote_launcher.py", line 119, in <module>
    run_as
  File "visualstudio_py_remote_launcher.py", line 58, in debug_remote
    vspd.exec_file(file, globals_obj)
  File "C:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\ptest1VS.Debug_ARM.Schelto\visualstudio_py_util.py", line 111, in exec_file
    exec_code(code, file, global_variables)
  File "C:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\ptest1VS.Debug_ARM.Schelto\visualstudio_py_util.py", line 87, in exec_code
    exec(code_obj, global_variables)
  File "StartupTask.py", line 2, in <module>
    import _wingpio as gpio
ImportError: No module named '_wingpio'
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\ptest1VS.Debug_ARM.Schelto\ptvsd\visualstudio_py_debugger.py", line 2197, in _excepthook
    do_wait()
  File "C:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\ptest1VS.Debug_ARM.Schelto\ptvsd\visualstudio_py_debugger.py", line 2324, in do_wait
    msvcrt.getch()
AttributeError: module 'msvcrt' has no attribute 'getch'

Original exception was:
Traceback (most recent call last):
  File "visualstudio_py_remote_launcher.py", line 119, in <module>
    run_as
  File "visualstudio_py_remote_launcher.py", line 58, in debug_remote
    vspd.exec_file(file, globals_obj)
  File "C:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\ptest1VS.Debug_ARM.Schelto\visualstudio_py_util.py", line 111, in exec_file
    exec_code(code, file, global_variables)
  File "C:\Users\DefaultAccount\AppData\Local\DevelopmentFiles\ptest1VS.Debug_ARM.Schelto\visualstudio_py_util.py", line 87, in exec_code
    exec(code_obj, global_variables)
  File "StartupTask.py", line 2, in <module>
    import _wingpio as gpio
ImportError: No module named '_wingpio'
The program '[4032] python @ tcp://pisvd:5678/?sd=C%3a%5cUsers%5cSchelto%5cDesktop%5cptest1%5cptest1&td=C%3a%5cUsers%5cDefaultAccount%5cAppData%5cLocal%5cDevelopmentFiles%5cptest1VS.Debug_ARM.Schelto&host=uwp' has exited with code -1 (0xffffffff).
=======

(Sorry for the formatting above, I can't fix it)

The screen says: 
ImportError was unhandled by user code
Message: No module named '_wingpio'

After the build was done and comparing the two solutions, I found differences in directory structures and missing files.  Copying the windevises directory and licence.txt file into the solution did not help.

The root cause seems to be File "visualstudio_py_remote_launcher.py". I cant find it and no useful info on Google.

What should I try next?

**Comment by alanch-ms** [comment]
pcopa,

The error, <File "StartupTask.py", line 2, in import _wingpio as gpio ImportError: No module named '_wingpio'>, means that python cannot find the _wingpio module.  The _wingpio module needs to be downloaded to the device (ie, raspberry Pi) along with the python interpreter/libraries during deployment.  

To do that, you need to 
1) copy the files under windevices to your blinky project (which you have done already)
2) and add a reference to the _wingpio to your *.pyproj.  You can do that by comparing the your *.pyproj and the PythonBlinkyHeadless.pyproj.  You should find an item group that looks like the following.  Just copy the whole block to your project.

```xml
<ItemGroup>
    <Reference Include="windevices\ARM\_wingpio_d.pyd" Condition=" [...snip for brevity ...]>">
      <Name>_wingpio_d.pyd</Name>
      <PythonExtension>windevices\ARM\_wingpio_d.pyd</PythonExtension>
    </Reference>
    [ ... snip... other references for other architectures ...]
</ItemGroup>
```

Hope this helps!

**Comment by pcopa** [comment]
@alanch-ms  Thanks Alan, that explains a lot. I would have never figured that out myself. Blinky is blinking again.

There are still 2 errors popping up during debug and the output window also disappears, but pops back up at the end and shows no errors. But that's another story!

I'm a computer HW eng and completely new to Python. 
When in VS I've noticed that i could not edit the .pyproj file. Only if it's broken, edit is available on tight click. 
To look what's going on, I used file-explorer and notepad to edit and some edits got corrupted after starting sln again. 
Is there a better editor? I'm always weary of special formatting characters.

**Comment by alanch-ms** [comment]
> Is there a better editor?

There is a way to modify the project file (.pyproj) in Visual studio.  You will need to unload the project first  `right click on the project in the solution explorer -> unload project`.  After the project has been unloaded, `right click on the project -> edit *.pyproj` .  The xml content of the project file should opened in VS.  After you have made your modifications, you can reload the project by `right click on the project -> Reload Project`

**Comment by pcopa** [comment]
@alanch-ms  Thanks Alan, that works fine.  
Moving on to trying the spi interface, I replaced the windevices directory with the pywindevices directory and changed/added the references in the .pyproj file.  But I could not get the spi pins to budge. Not with pin addressing and not with GPIO addressing.  
So I re-addressed the spi pins to unused GPIO pins and now everting is working.

Do the spi pins need to be enabled in raspberry pi2?
Is there a description of the supported commands in pywindevices?  Im looking for something like "GPIO.setmode(GPIO.BCM)"
