### ISSUE TITLE
multiprocessing debugging

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#983]
I'm using the multiprocessing module.  Is there any to debug multiple processes, if I do "attach to process", it doesn't link to any code.  Stopping at a breakpoint doesn't show multiple processes in the "processes" window but I can two instances of python.exe in taskmgr.

If I attach to that 2nd process ctrl-alt-p, it doesn't link back to the code.

**Comment by zwn** [comment]
Is this a duplicate of #125?
