### ISSUE TITLE
Missing hover-over variable information while debugging multi-threaded applications 

### ISSUE THREAD

**Issue by slishak** [Microsoft/PTVS#989]
When I hit a breakpoint in one thread, I can inspect variables by hovering over them, but if I change the thread (e.g. back to the main thread) I don't get anything when hovering over variables. The locals window does display variables from that thread, so it's not like the information is inaccessible.

The following code reproduces the issue. Place a breakpoint on the print statement, and then change back to the main thread.

``` python
import threading

def f():
    a = 'test'
    print(a)

t = threading.Thread(target=f)
t.start()
t.join()
```

PTVS 2.2 on VS2015, Python 2.7.10

**Comment by zooba** [comment]
That's expected behaviour, as the variable `a` has not been defined in the main thread. If you also call `a()` before `t.join()` then you'll hit the breakpoint twice (once in each thread) and `a` will be defined in both.

**Comment by slishak** [comment]
Sorry, I could have been clearer with this. I meant that variables that _are_ defined in the main thread don't give any information when hovering over (such as `t` and `threading`, not `a` which is obviously only visible in the scope of `f`)

**Comment by zooba** [comment]
It looks like the `Thread.join` call prevents us from being able to evaluate variables on that thread. I changed it to `while True: pass` and it works fine.

We get the list of variables in the Locals window from a different source that apparently still works here, so maybe we just need to fall back on that when the thread is otherwise locked.

**Comment by zooba** [comment]
Oh, we also need to display the error in the datatip. Currently we're just swallowing it and not displaying it anywhere...
