### ISSUE TITLE
Unit Tests named 'runTest' aren't detected by Test Explorer.

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/PTVS#99]
[According to the documentation:](https://docs.python.org/2/library/unittest.html)

> The simplest TestCase subclass will simply override the runTest() method in order to perform specific testing code:

Tests can basically be named **test*** as convention for the runner OR they can override the **runTest** method as mentioned in that fourth line of section 25.3.4.

I can run my test cases successfully in my script through unittest.main() if I call the method **runTest** or **test_whatever** on my TestCase.  But, PTVS only picks up the *test_whatever* in my Test Explorer.

It should pick up the **runTest** method as well and give it the name of its class as the test case name.

Thanks!

**Comment by hawkerm** [comment]
Haven't gotten to the Pull Request part of learning GitHub yet, but looks like in PTVS/Python/Product/TestAdapter/TestAnalyzer.cs, the last function (line 160) should have the search for 'runTest':

```C#
        private static IEnumerable<KeyValuePair<string, IAnalysisSet>> GetTestCaseMembers(
            IPythonProjectEntry entry,
            AnalysisValue classValue
        ) {
            return classValue.GetAllMembers(entry.Analysis.InterpreterContext)
                .Where(v => v.Key.StartsWith("test") || v.Key == "runTest")
                .Where(v => v.Value.Any(m => m.MemberType == PythonMemberType.Function || m.MemberType == PythonMemberType.Method));
        }
```

Surprised I found this since test was such a generic search term...

**Comment by crwilcox** [comment]
Hey Hawkerm.

You are correct.  The current implementation will only discover methods that match test*.  The docs do seem to indicate though that runTest should also be treated as valid.

I made the change you listed here and added it to our test cases.

I will create a pull request and you can sign off on it.  If you would rather submit a pull request that is fine too.  I wrote some quick instructions below.  

Forking/Pulling:
1) Fork: https://github.com/Microsoft/PTVS/issues/99#fork-destination-box
This will get you a clone of our repo that you have rights to push to.
2) Make the changes in the source.  Add unit tests and run appropriate tests. In this case the TestDiscoverTests.cs file.
4) Commit and Push to your fork like you would any project you have on GitHub
5) Go to https://github.com/Microsoft/PTVS/pulls and create a pull request.

**Comment by crwilcox** [comment]
https://github.com/Microsoft/PTVS/pull/101
