### ISSUE TITLE
PTVS Doesnt Detect VS 2013 Express Update 5

### ISSUE THREAD

**Issue by idx10** [Microsoft/PTVS#990]
Hello i have Visual Studio 2013 update 5
i tried installing PTSV  but it give me error message that i need to update my visual studio
- Tested using PTVS v2.2 & PTVS latest version (4/11/2015)

**Comment by zooba** [comment]
Are you using VS Express for _Windows_? That version is not supported - you'll need Express for Web or Express for Desktop. (It's very quick to install more versions of Express once you have the first.)

**Comment by idx10** [comment]
Yeah i guess im using the Windows version
What is the difference between that and Desktop or Web Versions (Sorry im new to programming )

**Comment by zooba** [comment]
They come with different feature sets. Express for Windows is targeted towards Windows Store apps, which don't support Python so there's no value in having Python support there. Express for Web is for web sites and services, and Express for Desktop is meant for Win32-based apps.

You can also get Visual Studio Community Edition for free, which supports all of these (including Python) as well as letting you install other extensions.

**Comment by idx10** [comment]
I was just checking, and if i can get VS for Desktop by updating the one i already have it would be nice (its too much download) and i'll consider having VS 2015 community aswell later
Thanks Alot for Help zooba :)

**Comment by zooba** [comment]
The download should be much smaller because you've already got the core part. VS is designed to share most of the common parts.
