### ISSUE TITLE
MySQL is not recognized/Apache Cordova and Django

### ISSUE THREAD

**Issue by aewhatley** [Microsoft/PTVS#992]
If MySQL is already installed on your computer before creating a Apache Cordova or Django app, then running the program will apparently cause the interpreter to return "MySQL' is not recognized as an internal or external command". I have run into this problem while using VS 2015, as have other users on StackOverflow: http://stackoverflow.com/questions/32715093/mysql-is-not-recognized-as-an-internal-or-external-command-cordova-in-vs2015

This problem can be solved by putting quotation marks around the name of the SQL system variable in path, but I think that this still be resolved by VS itself.

**Comment by int19h** [comment]
Apache Cordova and PTVS are two completely different project systems, and there's nothing in PTVS that specifically uses or otherwise references MySQL. Can you describe the PTVS-related scenario in more detail?

**Comment by aewhatley** [comment]
Here are some screenshots from another SO user with the same problem: http://stackoverflow.com/questions/32615139/apache-cordova-mysql-is-not-reconized-as-an-internal-or-external-command

Hopefully this helps....

**Comment by int19h** [comment]
This still shows a Cordova project. Cordova and PTVS are not related in any way.

**Comment by int19h** [comment]
If you really want to file a bug against Cordova VS support specifically, I can help you locate the right place to do so. But you mentioned PTVS specifically, so I'm curious what's the angle there.
