### ISSUE TITLE
Can't auto complete methods of value of dict or child class of dict which init by __init__

### ISSUE THREAD

**Issue by fan-wenjie** [Microsoft/PTVS#995]
if input the code in editor
a=[1,2,3]
b=dict(c=a)
b["c"].

a=[1,2,3]
b=dict({'c':a})
b["c"].

class map(dict):
...
a=[1,2,3]
b=map({"c":a})
b["c"].

It show  "No completions"
But if input it in python interactive or 
a=[1,2,3]
b={'c':a}
b["c"].
it can auto complete methods of a

**Comment by zooba** [comment]
I think we're missing handling for the dict constructor. Using `b = {c: a}` should work fine (though this is an area that is _really_ hard to get 100% correct... there are so many dicts that we can very quickly run out of memory if we try to be too thorough).
