### ISSUE TITLE
"Keep tabs" setting reverts to "Insert spaces"

### ISSUE THREAD

**Issue by CBRS** [Microsoft/PTVS#999]
On two separate PCs I've encountered an issue where the Text Editor -> Python -> Tabs settings revert to their defaults upon exiting and restarting Visual Studio (reproduced in VS 2015 Community on Windows 10, and VS 2015 Professional on Windows 7).

Specifically, the "Keep tabs" option is set back to "Insert spaces".

Apologies if this is a known issue - the only similar bug I can find is #43.

**Comment by zooba** [comment]
I think #698 is the same issue. We still haven't been able to reproduce it...
